### ISSUE TITLE
Import über Zwischenablage in CE Aufzählung

### ISSUE THREAD

**Issue by Babelfisch** [contao/core#1369]
Im Inhaltselement Aufzählung kann man ja Listen auch in verschiedenen Formaten als Datei importieren. In vielen Fällen wäre es deutlich schneller, wenn man stattdessen ein Textfeld hätte, in dem man den Text im gewählten Format nur reinkopiert und dann daraus die Listeneinträge erstellt werden. Also zusätzlich zum Icon „CSV-Datei Importieren“ noch ein Icon „Text Importieren“, bei dem eine Textbox mit einem Auswahlfeld für das Format aufgeht. Gerade Listeneinträge habe ich oft einfach als reinen Text mit Zeilenumbruch und da lohnt es nicht für ein paar Einträge jedes mal eine Datei zu speichern und zu importieren. Ein Import über ein Textfeld würde die Arbeit in vielen Fällen erleichtern.

--- _Originally created on January 7th, 2010, at 10:58am (ID 1369)_

**Comment by leofeyer** [comment]
Ich schließe das Ticket aufgrund mangelnden Interesses.
