### ISSUE TITLE
Captcha only once

### ISSUE THREAD

**Issue by tsarma** [contao/core#1485]
Hi TL Team,
I would like to make a feature request about Captcha. It would be really nice if captcha question is asked only one time. Say e.g. I filled a form with wrong e-mail, at preasent I have to correct the e-mail and do Captcha one more time. This is not much a users oriented, If someone filled the captcha right once, then it should not be ask again when correcting other fields, as we know by then its a human.
Thanks TT

--- _Originally created on February 1st, 2010, at 10:15am (ID 1485)_

**Comment by leofeyer** [comment]
@ausi has enhanced the captcha in Contao 4.4 so the security question is only visible if a bot fills in certain invisible fields (honeypot).
