### ISSUE TITLE
Stylesheet-Generator: font-style: normal fehlt

### ISSUE THREAD

**Issue by NinaG** [contao/core#1550]
Wenn man im Stylesheet-Generator bei "Schriftstil" den Haken bei **normal** setzt, wirkt sich das als **font-weight: normal** aus;

Es fehlt aber eine Angabe für **font-style: normal** (mit dem man z. B. ein font-style: italic überschreibt).

--- _Originally created on February 11th, 2010, at 08:32pm (ID 1550)_

**Comment by leofeyer** [comment]
8 Jahre später schließe ich das Ticket mangels Relevanz.
