### ISSUE TITLE
Einfache JavaScript-Einbindung in Formulare

### ISSUE THREAD

**Issue by jantheofel** [contao/core#1724]
Prinzipiell ist es möglich "unobtrusive" JavaScript-Funktionen im Nachhinein in fertige Formulare einzubauen. Für kleinere Scripte ist das aber oft relativ aufwendig. Daher würde ich vorschlagen, dass man JavaScript-Funktionen direkt über die Formularfunktion im TYPOlight Core einbinden kann. Dazu würde ich folgende Anpassungen vorschlagen:

Im Formular:
1. Auswahl einer JavaScript-Datei. Diese würde auf Seiten, die dieses Formular umfassen, automatisch in den Seitenkopf integriert.
2. Angabe einer onload-Funktion. Diese würde im Seitenkopf als onload-Anweisung in den body-Tag zusätzlich zu bestehenden Angaben mit aufgenommen.
3. Angabe einer Submit-Funktion. Diese würde als onsubmit-Anweisung in das Formular integriert.
(Zusatz: Die Punkte 1 und 2 könnte man natürlich auch über ein eigenes Seitenlayout definieren. Aber ich halte es für nicht sinnvoll, prinzipiell für jedes Formular ein neues Seitenlayout zu erstellen, und diese sich nur durch die einzubindenden JavaScript-Funktionen unterscheiden.)

Im Formularfeld:
1. Angabe einer onchange-Funktion. Diese würde als onchange-Anweisung direkt in die Ausgabe des Formularfelds integriert.

Insgesamt werden also "nur" vier Felder benötigt, die bei der Frontendausgabe an entsprechenden Stellen mit zu berücksichtigen sind. Prinzipiell könnten diese Anpassungen auch über ein Modul gelöst werden. Da aber beispielsweise sehr grundlegende Funktionen wie "generateWithError" betroffen sind, würde ich eine Implementoerung im TYPOlight Core vorziehen.

--- _Originally created on March 16th, 2010, at 05:39pm (ID 1724)_

**Comment by leofeyer** [comment]
Ich schließe das Ticket aufgrund mangelnden Interesses.
