### ISSUE TITLE
Funktion "Speichern und neu" nach Anlegen einer Kopie

### ISSUE THREAD

**Issue by jantheofel** [contao/core#1725]
Im Backend steht die Funktion "Speichern und neu" beim Anlegen von Datensätzen zur Verfügung. Nutzt man diese nachdem man eine Kopie von einem Datensatz angelegt und mit diesem Button gespeichert hat, erscheint ein neuer, leerer Datensatz. Ich fände es wünschenswert, dass es parallel eine Funktion "Speichern und neue Kopie" gibt. Dabei sollte dann für den nächsten neuen Datensatz zuerst wieder eine Kopie angelegt und diese dann editiert werden können. Dadurch wäre die Anlage größerer Menge sehr ähnlicher Daten noch effizienter möglich.

Related issues: #907

--- _Originally created on March 16th, 2010, at 05:48pm (ID 1725)_

**Comment by leofeyer** [comment]
Das Feature wurde mittlerweile implementiert (siehe https://docs.contao.org/manual/de/administrationsbereich/datensaetze-bearbeiten/).
