### ISSUE TITLE
Manual sorting in dca list view (mode 1 and 2)

### ISSUE THREAD

**Issue by importer** [contao/core#1760]
I'm often asked to make entries manually sortable in backend, so users can move items positions. 

That's no problem when I can use a parent table, I use the parent/child view (mode 4), but it's not always possible to fake the data structure into that.

May it be possible to have mode 1 and 2 handling custom sorting as mode 4, 5 and 6?

--- _Originally created by kik on March 24th, 2010, at 02:18pm (ID 1760)_

**Comment by xApep** [comment]
Hi. Is there any solution for manual sorting in 3.5.X in mode 1?

thanks.

**Comment by Toflar** [comment]
No, there's none. Use the tree view.
