### ISSUE TITLE
Template für pagination items (wie nav_default.tpl) einführen?

### ISSUE THREAD

**Issue by markusmilkereit** [contao/core#1930]
Ich vermisse die Möglichkeit auf die normalen pagination-items Einfluss nehmen zu können, ideal wäre ein eigenes Template wie nav_default.tpl, also zum Beispiel pager_item.tpl). Aktuell muss ich dafür die Pagination.php überschreiben und nach Updates immer wieder anpassen - manche Projekte benötigen einfach Anpassungen bei den Pagination-Ausgaben. Inhalt könnte sowas sein:

```
<li>
<?php if(isCurrent): ?>
<span class="current"><?php echo $this->pagenumber ?></span>
<?php else: ?>
<a href="<?php echo $this->link ?>" class="link" title="<?php echo $this->title?>"><?php echo $this->pagenumber ?></a>
<?php endif; ?>
</li>
```

--- _Originally created on May 6th, 2010, at 12:06am (ID 1930)_

**Comment by leofeyer** [comment]
Mittlerweile implementiert (Contao 3.5 glaube ich).
