### ISSUE TITLE
reset filter button

### ISSUE THREAD

**Issue by Toflar** [contao/core#1979]
Hi Leo

People start complaining about having the majority of all tickets in German on the tracker, so I'll go on in English here from now on :-)

I was just checking out the new filter and sorting options in Contao and I think it would be a great feature if we had a kind of a "reset filter" button in the panelLayout.

I guess a simple icon next to the yellow refresh icon would do the job! :-)

--- _Originally created on May 17th, 2010, at 11:19pm (ID 1979)_

**Comment by leofeyer** [comment]
Closed in favor of #6239.
