### ISSUE TITLE
Einstellungsmöglichkeit: Theme löschen

### ISSUE THREAD

**Issue by NinaG** [contao/core#2162]
Ich möchte eine Benutzergruppe anlegen, die auf die Module zugreifen darf, aber sonst am Theme/Layout nichts drehen soll. Also setze ich den Haken beim Abschnitt "Backend-Module" für "Themes" und beim Abschnitt "Theme-Module" für "Module".

Wenn dieser Nutzer sich nun einloggt und auf "Themes" klickt, würde ich erwarten, dass er neben dem Theme-Namen nur das Icon für die Module sieht. Tatsächlich ist aber z. B. auch das Löschen-Icon da (und ließe sich benutzen), genauso wie das Exportieren-Icon. Letzteres geht ja noch, aber die Lösch-Funktion sollte bei der Einstellung imho unbedingt deaktiviert sein.

Es ist ja durchaus nachvollziehbar, dass eine Nutzergruppe mit den Modulen hantieren darf (um z. B. in der FAQ-Ansicht einen neuen FAQ-Abschnitt freizuschalten), aber sie sollte doch nicht in der Lage sein dann auch gleich das gesamte Theme zu löschen!

Deshalb fände ich es sehr wichtig, dass man bei den Benutzergruppen einstellen kann, ob ein Nutzer berechtigt ist ein Theme zu löschen oder nicht (ähnlich wie bei den Archiven).

--- _Originally created on June 20th, 2010, at 12:52pm (ID 2162)_

**Comment by leofeyer** [comment]
Ich schließe das Ticket aufgrund mangelnden Interesses.
