### ISSUE TITLE
Add button "Save and Upload"

### ISSUE THREAD

**Issue by DyaGa** [contao/core#2168]
To my mind, it will be good to add button **"Save and upload"** (after **"Save and close"**) to form when creating a _new folder_ in **Filemanager**...

--- _Originally created on June 21st, 2010, at 01:47pm (ID 2168)_

**Comment by leofeyer** [comment]
With the new drag and drop upload feature in Contao 4.6 (see https://github.com/contao/core-bundle/pull/1386) such a button is no longer necessary.
