### ISSUE TITLE
Im Inhaltselement Hyperlink auch interne Downloads aufrufbar machen

### ISSUE THREAD

**Issue by NinaG** [contao/core#2237]
Mit dem Inhaltselement Hyperlink kann man mit Hilfe des lightbox-Eingabefeldes auch z. B. MP3-Audiodateien aufrufen.

Beispiel: _rel="lightbox[audio 50% 20]_

Es wäre deshalb schön, wenn das "Seitenwähler"-Symbol rechts neben der Link-Adresse nicht nur das Dropdown für interne Seiten anzeigt, sondern auch für interne Dateien. Dann könnte man dort eben z. B. eine MP3-Datei aus der Dateiverwaltung auswählen und mit Hilfe der oben genannten Lightbox-Angabe schön abspielen lassen.

Es funktioniert natürlich schon jetzt, aber dann muss man den genauen Link zur MP3 in der Dateiverwaltung auswendig kennen und manuell eintragen.

--- _Originally created on July 3rd, 2010, at 01:02pm (ID 2237)_

**Comment by leofeyer** [comment]
Wurde mittlerweile implementiert.
