### ISSUE TITLE
BBCode <quote> mit <blockquote> statt <div class="quote"> ersetzen

### ISSUE THREAD

**Issue by NinaG** [contao/core#2244]
Es wäre schön, wenn der BBCode `<quote>` nicht mehr mit `<div class="quote">` ersetzt wird, sondern mit dem entsprechenden HTML-Element `<blockquote>`.

--- _Originally created on July 4th, 2010, at 04:37pm (ID 2244)_

**Comment by leofeyer** [comment]
Changed in contao/comments-bundle@cbd709d3887377f0cfa1e923b1ad30ddf2a1798c.
