### ISSUE TITLE
Ergänzende Info im Log

### ISSUE THREAD

**Issue by NinaG** [contao/core#2447]
Im Log von Contao gibt es manchmal Fehlermeldungen, die schwer korrigierbar sind, da die Information fehlt, auf welcher Seite der Fehler aufgetreten ist. Gerade bei sehr großen Webseiten steht man dann vor einer fast unlösbaren Aufgabe bzw. müsste sich durch ein paar hundert Seiten klicken und die Fehlerquelle suchen.

Falls es möglich ist, würde ich deshalb darum bitten, dass das Logfile bei solchen Fehlermeldungen ergänzt wird, damit man sieht auf welcher Seite der Fehler aufgetreten ist.

BEISPIELE:

Wenn z. B. im Logfile steht, dass die Datei http://www.domain.tld/system/html/DRA-e5f8c34d.jpg nicht vorhanden ist, weiß ich nicht, auf welcher URL dieses nicht vorhandene Bild eingebunden ist.

Oder wenn ein Insert-Tag nicht umgesetzt wird, sehe ich als Fehlermeldung nur _No active page for page ID "{?{link_url::12}}", host_... und weiß somit nicht, wo der fehlerhafte Insert-Tag eingefügt wurde.

Genauso wenn ein Modul gelöscht wurde, aber in den Artikeln teilweise noch eingebunden ist. _Content element class "" (content element "mp3_player") does not exist_. Gute Meldung, aber wo ist das Element von den Redakteuren eingebunden worden?

Es würde den Nutzen der Logfiles wirklich massiv aufwerten, wenn die Seite mit ausgegeben würde, von der das Problem ausgeht :)

Related issues: #2164

--- _Originally created on August 18th, 2010, at 10:53am (ID 2447)_

**Comment by leofeyer** [comment]
Ich schließe das Ticket aufgrund mangelnden Interesses.
