### ISSUE TITLE
Add tree-level to checkboxWizard

### ISSUE THREAD

**Issue by ghost** [contao/core#2565]
I noticed that in Isotope they have a tree-checkboxwizard, which allows them to specify items in a collapsable checkboxWizard tree, e.g. basically a checkbox tree style (for alexf) combined with the orderable view of a checkbox wizard. Isotope calls this control AttributeWizard, but they have some code specific to isotope, but we can rather make it operate like alexf's tree view.

I also like the fact that its possible to show items that are disabled from selection, but still moveable, e.g. internal fields or stuff like that.

Here is an example of what I mean:

![attributewizard](https://user-images.githubusercontent.com/1192057/37648753-1dae7e24-2c30-11e8-85da-64c6c6c41dd9.jpg)

[Download the attachments](http://www.contao.org/tl_files/tickets/2565.zip)

--- _Originally created by thyon on September 23rd, 2010, at 03:16pm (ID 2565)_

**Comment by leofeyer** [comment]
This has been implemented meanwhile.
