### ISSUE TITLE
Felder zum Newsletterabonnieren immer anzeigen

### ISSUE THREAD

**Issue by ghost** [contao/core#2605]
Das Standardmenütemplate ist so ausgelegt, dass die aktuelle Seite nicht angeklickt werden kann. Das führt jedoch zu einem kleineren Problem beim Abonnieren eines Newsletter. Wenn der Benutzer z.B. ein ungültiges Token hat ("Der Aktivierungslink ist ungültig oder veraltet."), wird das Template "mod_newsletter" statt "nl_default" verwendet. In dem werden die Felder zum abonnieren nicht mitgerendert - und man kann das Template dahingehend auch nicht modifzieren, da das Modul das nicht mehr berechnet. Wenn der Benutzer also ein falsches Token hat, kann er nicht sofort noch einmal seine Mail-Adresse eingeben um sich ein neues Token schicken zu lassen, noch kann er im Menü nochmals auf Newsletter klicken und dann die Daten erneut eintragen. Somit muss man im Fehlerfalle momentan irgendeine andere Seite aufrufen, dann wieder die Newsletter Seite und dann nochmal abonnieren.

Da bereits einige Nachrichten direkt über den Feldern eingeblendet werden, wäre es konsequent, wenn auch die Fehlermeldungen darüber erscheinen, also dass das Template mod_newsletter.tpl wegfällt und nl_default dafür alles übernimmt (und das Modul natürlich alles zusammen berechnet). Damit müsste der Benutzer nur noch die Daten nocheinmal eingeben um ein gültiges Token zu bekommen, anstatt erst 2x im Menü rumzuklicken.

--- _Originally created by SunBlack on October 9th, 2010, at 11:58am (ID 2605)_

**Comment by leofeyer** [comment]
Wie lässt sich das in der Onlinedemo reproduzieren?

**Comment by ausi** [comment]
Wenn man <https://demo.contao.org/en/newsletter.html?token=invalidtoken> aufruft, sind unter der Überschrift „Subscribe to our newsletter“ keine Felder zum abbonieren mehr sichtbar.

Das Problem mit der Navigation lässt sich jedoch nicht mehr nachstellen.

**Comment by leofeyer** [comment]
@ausi Sollen wir das dann wie oben beschrieben anpassen?

**Comment by ausi** [comment]
Ja, ich denke das ist sinnvoll. Die Fehlermeldung sollte direkt über dem subscribe Formular angezeigt werden.

**Comment by leofeyer** [comment]
This has been fixed meanwhile.
