### ISSUE TITLE
mandatory Sternchen als Sprachvariable

### ISSUE THREAD

**Issue by Aybee** [contao/core#2624]
Hallo Leo,

der eine möchte kein Sternchen, der andere noch div. Klammern drum herum, der nächste direkt einen kurzen Text. Könnte man das Sternchen nicht als Sprachvariable anbieten?

Gruß Andreas

--- _Originally created on October 20th, 2010, at 06:18pm (ID 2624)_

**Comment by leofeyer** [comment]
Ich schließe das Ticket aufgrund mangelnden Interesses.
