### ISSUE TITLE
Preview mit User-Switch auch für nicht-Admins

### ISSUE THREAD

**Issue by markusmilkereit** [contao/core#2677]
Ich schlage vor die Option des Member-Wechsels davon abhängig zu machen ob der angemeldete User Zugriff auf das Modul "Mitglieder" hat, oder alternativ noch genauer auf ein einzelnes Feld, zum Beispiel "login". Es ist ansonsten für normale Redakteure recht schwer zugriffsgeschützte Bereiche vernünftig zu testen, obwohl sie mit den obigen Berechtigungen vollen Zugriff auf die Frontend-User haben.

--- _Originally created on November 16th, 2010, at 10:28pm (ID 2677)_

**Comment by leofeyer** [comment]
@contao/developers /cc

**Comment by aschempp** [comment]
Haben wir das nicht auch bereits für Backend-Benutzer über entsprechende Gruppenberechtigungen gelöst? Könnte man für FE doch genauso tun?

**Comment by leofeyer** [comment]
Hab gerade festgestellt, dass wir das schon implementiert haben. 😄

<img width="416" alt="" src="https://user-images.githubusercontent.com/1192057/38600886-0b13ccaa-3d66-11e8-9643-41b84e7d7be1.png">
