### ISSUE TITLE
Template und Absender bei Newslettern

### ISSUE THREAD

**Issue by importer** [contao/core#2896]
Hallo Leo,

ich hab hier noch eine Anregung für das Newsletter-Modul. 
Beim Aufbei eines kleinen einfachen Newsletters für meine Internetseite (deshalb möchte ich keine große Newsletter-Extension reinladen) ist mir eine störende Sache aufgefallen. Jedesmal wenn ich einen neuen Newsletter erstellen will, darf ich nicht vergegssen das richtige Mail-Template auszuwählen und muss jedesmal den Absendername und die Absendermail eintragen, da ja sonst die Mail-Adresse aus den Grundeinstellungen genommen wird.

Wäre es hier nicht sinnvoller die Absenderangaben auf der Channel-Seite einzurichten (da ich ja eigentlich nicht ständig mit nem anderen Absender versenden will) und auch das Template auf der Channel-Seite zudefinieren?? Man könnte ja beim einzelnen Newsletter die Angaben lassen und eine Überschreibung der Channel-Angaben möglich machen!?

Schöne Grüße aus Stuttgart,
Arne

PS: Ich habe es jetzt leider nicht so einfach geschafft einen Beispiel-Code zu erstellen, da ich mich dann sehr in dein Newsletter-Modul reindenken müsste. Vielleicht kann ich dir was von der Arbeit abnehmen.

--- _Originally created by renderart on February 28th, 2011, at 12:38pm (ID 2896)_

**Comment by Anke** [comment]
+1
Template und Absender auf Channel-Ebene ist auf jeden Fall kundenfreundlicher. Die E-Mail des SYSTEMadmins - im Newsletter eher unerwünscht.

**Comment by leofeyer** [comment]
Ich bin auch dafür, allerdings ist das nicht rückwärtskompatibel. Können wir so eine Änderung in einer Minor-Version bringen? Oder lieber erst in Contao 4?

**Comment by may17** [comment]
Dafür aber ich denke, dass wäre eher etwas für ein Major Release (Contao 4).

**Comment by leofeyer** [comment]
Implementiert in contao/newsletter-bundle@1cdc6119e821ccdad44c6ee9e4ea2857f4795cc4.
