### ISSUE TITLE
Add ability to create folder hierarchy fast

### ISSUE THREAD

**Issue by Serhii-DV** [contao/core#2907]
It will be nice if FileManager could create multilevel folders.

For example, now if I want to create folders with hierarchy like that:

```
folder
   subfolder
      sub-subfolder
```

I have to do this procedure three times.

It will be fast, if we could just enter 

```
folder/subfolder/sub-subfolder
```

in folder `Name` value when creating folder and FileManager creates this folder hierarchy for us

--- _Originally created on March 4th, 2011, at 12:57pm (ID 2907)_

**Comment by leofeyer** [comment]
See contao/contao#3793. Thanks to Symfony, this could be implemented very easily now.
