### ISSUE TITLE
Nur 1 Fehlermeldung gemeinsam für Passwort/Bestätigungsfelder

### ISSUE THREAD

**Issue by NinaG** [contao/core#2933]
In Contao gibt es die Felder "Passwort" und "Bestätigung", die in der Kombi auftreten (z. B. im Registrierungsmodul). Im Gegensatz zu allen anderen Feldern die in Contao in Formularen vorkommen, geben diese Felder nur **gemeinsam eine Fehlermeldung** aus, die dadurch im Code auch eine andere Code-Konstellation hervorruft als das normalerweise der Fall ist (Normal: 1 Label, 1 Fehlermeldung, 1 normales Feld). Das bringt einerseits gestalterische Formatierungsprobleme mit sich, andererseits ist das auch wegen Barrierefreiheit problematisch weil eine klare Zuordnung kaum möglich ist.

**Erhoffte Änderung:**
Bitte ändere das so ab, dass Contao auch hier der Norm folgt und jedem normalen Feld seine eigene Fehlermeldung ausgibt.

--- _Originally created on March 16th, 2011, at 05:31pm (ID 2933)_

**Comment by leofeyer** [comment]
Ich schließe das Ticket aufgrund mangelnden Interesses.
