### ISSUE TITLE
Add option "Show all news link" to newslist module

### ISSUE THREAD

**Issue by DyaGa** [contao/core#3109]
When using `newslist` module on `Homepage` for showing last 3 news items there are often needed link `All news`. So, why not generate this link with `newslist` module.

I see it as module option `Show all news link` which is similar to `Jump to page`.

--- _Originally created on May 30th, 2011, at 12:45pm (ID 3109)_

**Comment by leofeyer** [comment]
I'm closing the ticket due to lack of interest.
