### ISSUE TITLE
Übergabe von Variablen während der Registrierung

### ISSUE THREAD

**Issue by Aybee** [contao/core#3119]
Für das Double-Opt-In Verfahren bei der Registrierung kann man mit ##username## usw. die Feldwerte bereits in die Bestätigungs-Mail übergeben. Das ist seht schön.

Ich würde mir wünschen, dass man diese Werte auch zur Weiterleitungsseite weiterreichen könnte. Damit könnte ich den sich Registrierenden bereits auf der Website persönlich ansprechen. 'Hallo ##username## Sie erhalten eine E-Mail...'

Und auf der Weiterleitungs welche durch den E-Mail-Link aufgerufen wird dann ebenfalls. 'Hallo ##username##, Sie können sich nun einloggen...'

--- _Originally created on May 31st, 2011, at 03:45pm (ID 3119)_

**Comment by leofeyer** [comment]
Ich schließe das Ticket aufgrund mangelnden Interesses.

**Comment by Aybee** [comment]
Mmh, seltsam, dass keiner Interesse bekundet hat. Ich sehe dies im Forum ansonsten immer wieder, dass alle die Formulardaten weiterreichen möchten.
