### ISSUE TITLE
Form generator: add "Don't send via email" setting for form widgets

### ISSUE THREAD

**Issue by DyaGa** [contao/core#3170]
When form option `Send form data via e-mail` is checked, the retrieving from user form data can be sending via email. Also, this submit data can be store in database. For doing this, some field in Form have to be `hidden`, for example: `pid`, `tstamp`, `published` or `status`, etc.
For now, when user submits a form data the module stores it in database and then sends all values via email.
To my mind there is no need to send `pid`, `tstamp`, `published` or `status` field via email. 

So, I think it would be good to add checkbox option `Don't send via email` for form widget. And if it checked then field value will not be sending via email.

--- _Originally created on June 16th, 2011, at 11:13am (ID 3170)_

**Comment by leofeyer** [comment]
I'm closing the ticket due to lack of interest.
