### ISSUE TITLE
Datum simulieren in Frontend-Vorschau

### ISSUE THREAD

**Issue by ghost** [contao/core#3183]
Die Funktion ist vielleicht nicht zwingend erforderlich, wäre aber in meinen Augen ein nice-to-have:

Analog zu der Möglichkeit, versteckte Inhalte anzuzeigen oder zu verbergen; oder FE-User zu simulieren, würde ich mir ein Datumsfeld wünschen, mit dem ich in der Frontend-Vorschau bestimmte Zeitpunkte simulieren kann, um die Anzeige datumsgesteuerter Veröffentlichungen zu kontrollieren.

--- _Originally created by mv_alex on June 21st, 2011, at 12:02pm (ID 3183)_

**Comment by leofeyer** [comment]
See https://github.com/contao/contao/issues/4561
