### ISSUE TITLE
Berechnung von Globalen Variablen

### ISSUE THREAD

**Issue by psren** [contao/core#3193]
In Contao 2.10 werden ja die 'Globalen Variablen' eingeführt.
Praktisch fände ich wenn man die Globalen Variablen auch zur Berechnung nutzen könnte.

$boxwidth = 300
$boxheight = $boxwidth / 3

so könnte man einfach Verhältnisse ausrechnen was auch z.B. für Schriftgrößen etc praktisch wäre.

Viele Grüße
psren

Related issues: #3216

--- _Originally created on June 24th, 2011, at 11:09am (ID 3193)_

**Comment by leofeyer** [comment]
Contao unterstützt mittlerweile auch SCSS- und LESS-Dateien, in denen solche Berechnungen durchgeführt werden können.
