### ISSUE TITLE
Bewertungen im ER-Client

### ISSUE THREAD

**Issue by psren** [contao/core#3251]
Ich finde es Schade, dass Erweiterungen mit mehreren tausend Downloads bei den Bewertungen um die 20 oder so haben (catalog).
Die Vermutung liegt nahe, dass das daran liegt, dass man nicht direkt im Backend im ER-Client bewerten kann und die meisten ihre Erweiterung eben über diesen Beziehen.

Also wäre es schön die Möglichkeit zu haben die Bewertung direkt im ER-Client abzugeben. Ebenso sollte man die Möglichkeit haben Rezensionen auch direkt übers Backend zu lesen.

Letzteres ist bis jetzt quasi garnicht möglich (siehe Screenshot win7/chrome12)

[Download the attachments](http://www.contao.org/tl_files/tickets/3251.zip "Download the attachments of this ticket")
Related issues: #2487

--- _Originally created on July 9th, 2011, at 11:27am (ID 3251)_

**Comment by leofeyer** [comment]
Das das ER2 zeitnah durch die Composer-Paketverwaltung abgelöst werden soll, implementieren wir keine neuen Features mehr.
