### ISSUE TITLE
Eigene Erweiterungen mit auflisten

### ISSUE THREAD

**Issue by importer** [contao/core#3294]
Hallo,

beim entwickeln meiner ersten Erweiterung ist mir aufgefallen, dass die eigene Erweiterung nicht in der Erweiterungsverwaltung aufgelistet wird, wenn sie nicht über die Repository installiert wurde.

Meiner Meinung nach macht es jedoch Sinn, dass selbst entwickelte Erweiterungen, die aus verschiedensten Gründen nicht über die Repository zur Verfügung gestellt werden (z.B. sehr spezifische Erweiterung im Kundenauftrag), mit in der Liste der aktiven Erweiterungen aufgenommen werden. Eine einfache Auflistung ohne Verlinkungen zur Repository und ohne Bearbeiten-Icons. Da ja nicht alle Ordner in system/moduls in der Erweiterungsverwaltung auftauchen sollen, würde es sich anbieten, dieses Verhalten per config.php steuern zu können (z.B. per Hook?).

Welchen Vorteil würde die Auflistung der manuell installierten Erweiterungen bringen:
- einen Überblick über (alle) installierte Erweiterungen für den Nutzer (z.B. der Admin des Kundens, in dessen Auftrag die Erweiterung entwickelt wurde, die Erweiterung jedoch nicht in der Repository veröffentlich wird/werden soll)
- "normale" Erweiterungen, die eigentlich in der Repository veröffentlicht sind, jedoch manuell installiert wurden, werden so auch in der Liste aufgeführt.

Viele Grüße
µaTh

--- _Originally created by maTh on July 23rd, 2011, at 09:08pm (ID 3294)_

**Comment by discordier** [comment]
Can be closed IMO as we are using composer now and therefore this is most likely obsolete?

**Comment by BugBuster1701** [comment]
:+1:

**Comment by aschempp** [comment]
:+1: for closing this
