### ISSUE TITLE
Kommentare im Multidomain Betreib mit verscheidenen Backend usern

### ISSUE THREAD

**Issue by importer** [contao/core#3302]
Hallo,

vorweg contao ist ziemlich gut und ich nutze und empfehle es sehr gerne.
Aber mir sind 2-3 Dinge aufgefallen die anders sein könnten. Ich habe dafür keine Lösungen, sonder erkläre nur das Problem.

Kommentare werden in Contao leider im Backend nicht so sauber getrennt. Es ist so das ich verschiedene Seiten in einer Installation habe mit verschiedenen Admins für die jeweiligen Seiten.

Problem Jeder Backenuser sieht alle Kommentare und kann Sie ändern, löschen und Publizieren.
Es wäre toll wenn jeder nur Kommentare sieht die auf den Seiten veröffentlicht sind auf denen er zugriff hat (z.B für einen Startpunkt einer Seite). Genau so wie bei Artikeln, ein User kann ja auch da nur Artikel verlinkten die er auch so sehen würde.

Diese Funktion würde mir und sicher einigen anderen Admin das leben leichter machen.

--- _Originally created by CThor on July 25th, 2011, at 08:48pm (ID 3302)_

**Comment by leofeyer** [comment]
Leider bleibt es dabei, dass eine solche Prüfung in der Listenansicht nicht möglich ist.

Zwar ist es korrekt, dass eine Zugriffsprüfung erfolgt, allerdings gilt das nur für das Bearbeiten **eines** Datensatzes und nicht für das Anzeigen **aller** Datensätze. Der Grund ist, dass die Prüfung sehr aufwändig ist:

https://github.com/contao/core/blob/master/system/modules/comments/dca/tl_comments.php#L328-L420

Diese Methode müsste in der Listenansicht auf **jeden einzelnen** Datensatz angewendet werden, um herauszufinden, welche der Benutzer sehen darf und welche nicht. Das würde bei 10.000 Kommentaren also 10.000 zusätzliche Datenbank-Abfragen bedeuten, nur um die Liste auszugeben.

**Comment by madmaharaja** [comment]
Schade, aber vielen Dank fürs nochmal Reinschauen!

Und ich hätte gedacht, dass folgender Code fast die Lösung sein könnte:
```
<?php
if($Kommentarbearbeitungsicon == "system/themes/default/images/edit_.gif")
{
  return "nixShowComment";
}
?>
```

**Comment by leofeyer** [comment]
Das kannst Du schon so machen, aber es sollen ja im Idealfall immer 30 Kommentare pro Seite angezeigt werden. Wenn Du die Kommentar einfach ausblendest, hast Du im Zweifel eine leere Liste, wenn der Redakteur keinen der 30 bearbeiten darf.

**Comment by madmaharaja** [comment]
Für mich wäre der Idealfall eher, wenn der Redakteur "nur" die handvoll Kommentare sieht, die er auch tatsächlich bearbeiten darf, als immer eine volle Liste mit 30 Einträgen, von denen er aber viele/keine bearbeiten kann. Gucken kann er ja im Frontend, das Backend ist doch eher zum "Anpacken" da. Und, wenn's nichts zu bearbeiten gibt, braucht er ja auch nichts sehen ...
