### ISSUE TITLE
Disable edit button if no fields are enabled

### ISSUE THREAD

**Issue by aschempp** [contao/core#3546]
I think it would be useful to disable (or hide) the edit button in a DCA, if no fields for that table are enabled.

I know that this could be tricky because we don't want to register a button_callback on EVERY edit button, but either the DataContainer should take care of it or we should at least provide a function available to register as the button_callback.

--- _Originally created on October 14th, 2011, at 08:44am (ID 3546)_

**Comment by leofeyer** [comment]
Meanwhile implemented.
