### ISSUE TITLE
Make page type icons configurable somehow

### ISSUE THREAD

**Issue by Toflar** [contao/core#3554]
Hi Leo

What do you think about making the page type icons configurable somehow?
The problem actually resides in here: http://dev.contao.org/projects/typolight/repository/entry/trunk/system/modules/backend/dca/tl_page.php#L1216

You add the icon to the row using the label_callback which cannot be defined twice. So I can override the core callback and implement my version by copying the core routine and adding my icons for my custom page type but if I install another extension that does exactly the same, it overrides my callback again and I do not get my icon displayed :(

First, I was thinking about just adding the icon to the TL_PTY array but then I realized that they are always dependent on different states of the page (hidden, protected etc.) so I think it's best to implement a pagetype_icon_callback or something like that?

And it would be very cool to respect this callback also in the pageTree widget because that's where we currently have no possibility of adding an icon at all and so implementing this feature would also increase consistency =)

Related issues: #3559

--- _Originally created on October 17th, 2011, at 08:18pm (ID 3554)_

**Comment by garyee** [comment]
+1 (oder gibts schon eine Lösung dafür ?)

**Comment by aschempp** [comment]
@garyee hängt davon ab. Meinst du für eigene Themes oder für eigene Page Types? Es gibt einen Hook…

**Comment by Toflar** [comment]
Implemented via my PR: https://github.com/contao/core/pull/7556
