### ISSUE TITLE
"Speichern und Bearbeiten" auch bei existierenden (kopierten) Einträgen

### ISSUE THREAD

**Issue by tristanlins** [contao/core#3567]
Beispiel Artikel

Wenn man in den Artikeleinstellungen eines vorhandenen Artikels ist, ist der Button "Speichern und Bearbeiten" nicht mehr da. D.h. wenn man nicht zufällig vorher auf dem Artikel selbst war (z.B. wenn man den Artikel kopiert), dann landet man i.d.R. wieder in der Artikelübersicht (Baum). Hier wäre der Button "Speichern und Bearbeiten" auch nützlich, um direkt auf den Inhalt zu springen, statt zur vorherigen Ansicht.
Vor allem beim Kopieren von Artikeln spart man sich dadurch 1~2 Klicks, weil man in der Regel nach dem Kopieren den Inhalt bearbeiten will.

Gleiches gilt natürlich auch für andere Elemente mit Kinddatensätzen (z.B. Nachrichtenarchive).

--- _Originally created on October 21st, 2011, at 11:10am (ID 3567)_

**Comment by leofeyer** [comment]
Implementiert in contao/core-bundle@cea3a2f0cd99f33f11f367c6539138e39ab0d872.
