### ISSUE TITLE
Adaptive Images

### ISSUE THREAD

**Issue by importer** [contao/core#3589]
Hello,

I would like to propose [Adaptive Images](http://adaptive-images.com.)

I think that is an excellent solution to manage automatically the display of images on smartphones and tablet computers with Contao.

--- _Originally created by lionel on October 30th, 2011, at 05:59pm (ID 3589)_

**Comment by dmolineus** [comment]
Stumpled upon it. Guess it can be closed as responsive images are supported now.

**Comment by leofeyer** [comment]
Thanks @dmolineus.
