### ISSUE TITLE
rel=lightbox für Link-Insert-Tags

### ISSUE THREAD

**Issue by NinaG** [contao/core#3651]
Es wäre sehr hilfreich, wenn man nicht nur Bild-Insert-Tags mit dem Lightbox-Aufruf versehen kann, sondern auch Link-Insert-Tags.

Die Umsetzung wäre also:
{{link::40?rel=lightbox}}
{{link::40?rel=lightbox[680 500]}}

--- _Originally created on November 24th, 2011, at 04:22pm (ID 3651)_

**Comment by leofeyer** [comment]
Ich schließe das Ticket aufgrund mangelnden Interesses.
