### ISSUE TITLE
Mitglied hat Benutzername vergessen

### ISSUE THREAD

**Issue by ghost** [contao/core#3663]
Die Funktion Passwort vergessen ist bereits da, aber was ist wenn jemand seinen Benutzernamen (Mitglieder) im Frontend vergessen hat?

**Comment by leofeyer** [comment]
Mir ist gerade aufgefallen, dass das schon längst möglich ist. Man muss dazu in der Modulkonfiguration die Option "Benutzernamen nicht abfragen" auswählen und im Text der Bestätigungsmail das Simple-Token `##username##` verwenden.

<img width="492" alt="" src="https://user-images.githubusercontent.com/1192057/48784420-f612ee80-ece2-11e8-91fc-097a85474691.png">

<img width="653" alt="" src="https://user-images.githubusercontent.com/1192057/48784540-2d819b00-ece3-11e8-9be8-c89b7da03d41.png">

Somit schließe ich dieses Ticket.
