### ISSUE TITLE
RSS Reader - Einträge pro Feed

### ISSUE THREAD

**Issue by ways2web** [contao/core#3680]
Es ist ja möglich im RSS-Reader mehr als einen Feed einzutragen. 
Aber man hat nur die Möglichkeit eine max. Anzahl von Einträge aller Feeds einzutstellen.

Problematik 1: 
ich hab 3 Feeds, möchte von jedem nur die ersten 5 Einträge ausgeben. Das geht nicht.

Problematik 2:
gebe ich eine maximale Anzahl von Beiträgen ein, z.B. 20, und der erste Feed von den drei Feeds gibt schon allein 20 Einträge aus, ist von den beiden anderen Feeds nichts mehr sichtbar.

Daher wäre die Option "Einträge pro Feed" wünschenswert.

**Comment by leofeyer** [comment]
Ich schließe das Ticket aufgrund mangelnden Interesses.
