### ISSUE TITLE
Multi domain cross linking error

### ISSUE THREAD

**Issue by Ruudt** [contao/core#3765]
When I have a multi domain setup I want to include a (sub-)menu of domain2 into an article on domain1. This is possible because I created a navigation module with the reference page somewhere within domain2. However, the links that the menu creates are relative to the base page. This means that the links go to the wrong spot (domain1.com/page.html), where it should obviously be domain2.com/page.html. All of the information would be known to Contao, so I wonder why it should not detect the correct domain and prefix the url whenever needed.

Same thing goes for links inserted into text. For example: {{link_url::20}}. This will generate an url because the page is know, but the base page is left out even though it is on another domain.

For the user the domain is external. But it is 1 Contao setup that manages both domain names, so I'd say it should detect when the domains want to interact with eachother...

**Comment by fritzmg** [comment]
This is still not fixed for news and possibly search, forms and events as well, as adressler mentioned. If the link target of a news entry points to a page that is in a different domain, the generated link will simply not be correct.

**Comment by fritzmg** [comment]
The problem is still present in Contao 3.5.0.
