### ISSUE TITLE
Select or enter stylesheet categories

### ISSUE THREAD

**Issue by Anke** [contao/core#3770]
Bei Bearbeiten eines Stylesheet-Datensatzes wäre es sehr praktisch, wenn das Feld "Kategorie" sowohl per Dropdownliste die bereits vorhandenen Kategorien zur Auswahl als auch die Eingabe einer neuen Kategorie anbieten würde. 

Ich weiß nicht, ob das v.a. unter dem Aspekt der Barrierefreiheit machbar ist, aber es wäre hilfreich beim Vermeiden doppelter Kategorieeinträge, wenn jemand die bisher verwendete Schreibweise nicht im Kopf hat.

**Comment by leofeyer** [comment]
Ich schließe das Ticket aufgrund mangelnden Interesses.
