### ISSUE TITLE
partielles leeres des Seitencaches

### ISSUE THREAD

**Issue by leo-unglaub** [contao/core#3829]
Hallo !
Wie jeder weiß bin ich ein riesen Fan von Caching/Optimierungen, ... . Daher cache ich bei all meinen Seiten immer alles so lange wie möglich. (aktuell 30 Tage) Nun ist es aber etwas nervig, auch nach kleinen Änderungen immer den ganzen Cache löschen zu müssen. Daher wäre es praktisch, wenn man den Cache partiell löschen könnte. (oder das auch gleich automatisch beim Speichern von Content Elementen macht).

Da der aktuelle Cache noch nicht sehr genau ist, wäre es doch eine idee vor den Hash-Namen des Cache files die Seiten-ID zu generieren. Dann könnte man einfach wenn man die Seite 12 editiert hat her gehen und im save_callback alle files löschen, die mit 12-.... anfangen. Fertig.

Es wäre cool, wenn das noch in die 2.11 rein kommen würde.
Danke und viele Grüße

**Comment by leofeyer** [comment]
Siehe https://github.com/contao/manager-bundle/issues/46 .
