### ISSUE TITLE
optimize tables daily by cron

### ISSUE THREAD

**Issue by DVeris** [contao/core#3866]
optimize tables daily by cron (config - week,daily, etc)
and maybe and repair?

like this
http://www.contao.org/en/extension-list/view/mysql_tools.10000009.en.html

but built-in
and cronjob

---
sorry for my english

**Comment by leofeyer** [comment]
It is not the responsibility of a CMS to optimize tables. These kind of maintenance should be carried out by the server admin, possibly automated via cron.
