### ISSUE TITLE
Installtool um .htaccess Funktion erweitern

### ISSUE THREAD

**Issue by AgentCT** [contao/core#3892]
Um den Schutz für das Backend zu erhöhen wäre es mit Sicherheit nicht schlecht im Installtool am Ende eine zusätzliche Auswahl einzubauen, mit der man das contao-Verzeichnis mit einem .htacess Verzeichnis schützen kann.
Dies könnte man mit zwei zusätzlichen Feldern (Usernamen und Passwort) realisieren.

Dann hätten auch User die noch Anfänger sind von Beginn an automatisch einen besseren Schutz.

**Comment by leofeyer** [comment]
Da Contao 4 nicht mehr auf `.htaccess`-Dateien setzt, schließe ich dieses Ticket.
