### ISSUE TITLE
Spitze Klammer in Formularen

### ISSUE THREAD

**Issue by no-one** [contao/core#3998]
Enthält ein Input-Feld bei einem Formular eines der verbotenen Zeichen <code>=<>&/()#</code> erscheint normalerweise eine Fehlermeldung. Schreibt der Nutzer aber ein <code><</code> und darauf folgt kein Leerzeichen, werden alle folgenden Zeichen abgeschnitten.

Beispiel für Nutzereingabe in Textarea (mit Eingabeprüfung "Erweiterte alphanumerische Zeichen") in einem Kontaktformular:
<code>foo &lt;hier steht viel Text</code>

Ergebnis in der E-Mail des Empfängers:
<code>foo</code>

Das könnte problematisch sein, wenn der Nutzer versehentlich ein <code><</code> tippt und dadurch viele Informationen nicht übermittelt werden. Ist dieses Verhalten gewünscht?

**Comment by leofeyer** [comment]
Implementiert wir besprochen in d0c29fc909bd97da10a8879e3129952ffd7ebda0. Hier sind mein Tests dazu:

```php
$_POST['foo'] = '<strong>bar</strong> ist <5 und < 10 und << 20.';
dump($_POST['foo'], Input::postHtml('foo', true));

$_POST['foo1'] = '<p>hier test <5</p>';
dump($_POST['foo1'], Input::postHtml('foo1', true));

$_POST['foo2'] = '<br /> <br> <br/> <br/ >';
dump($_POST['foo2'], Input::postHtml('foo2', true));

$_POST['foo3'] = '<p title="test> 5"> <p title="test > 5"> <p title="test <p> 5">';
dump($_POST['foo3'], Input::postHtml('foo3', true));

$_POST['foo4'] = 'Arthur Friend <a.friend@email.com> Arthur Friend <a friend@email.com>';
dump($_POST['foo4'], Input::postHtml('foo4', true));

$_POST['foo5'] = 'bla << bla <<5';
dump($_POST['foo5'], Input::postHtml('foo5', true));

$_POST['foo6'] = '<!-- comment --> <![CDATA ]>';
dump($_POST['foo6'], Input::postHtml('foo6', true));
```

@all Bitte prüfen und entsprechend nachvollziehen.

@ausi Könnten durch die neue Routine irgendwelche Sicherheitslücken entstehen?

**Comment by ausi** [comment]
Ich hab mir die Routine angesehen und hab keine Sicherheitsprobleme feststellen können. Es sollte also nicht unsicherer geworden sein. Angaben natürlich ohne Gewähr ;)

Unabhängig davon bin ich derselben Meinung wie @Toflar in [seinem Kommentar](https://github.com/contao/core/issues/3998#issuecomment-49547679). Die Herangehensweise die Daten in der Input-Klasse zu filtern ist nicht richtig. Input sollte im Rohformat vorliegen und bei der Ausgabe escaped werden.

**Comment by leofeyer** [comment]
> Die Herangehensweise die Daten in der Input-Klasse zu filtern ist nicht richtig. Input sollte im Rohformat vorliegen und bei der Ausgabe escaped werden.

Da sind wir uns alle einig :)
