### ISSUE TITLE
Zugriffsrechte für Inhaltselemente

### ISSUE THREAD

**Issue by NinaG** [contao/core#4053]
Es wäre sehr hilfreich, wenn man auch für Inhaltselemente Zugriffsrechte einstellen könnte.

Anwendungsbeispiel:
Manchmal muss ich wichtige Module direkt als Inhaltselement einbinden. Es würde keinen Sinn machen, das über ein eigenes Seitenlayout zu lösen, da das Modul z. B. zwischen anderen Elementen auftauchen soll bzw. weil man sonst xx Seitenlayouts machen müsste (die sich nur in diesem einen Modul unterscheiden). 

Ich hätte nun gerne die Einstellmöglichkeit, dass dieses Modul z. B. ausschließlich von einer bestimmten Benutzergruppe bearbeitet/gelöscht werden darf. Alle anderen Redakteure die Zugriff auf die Seite/den Artikel haben, können es zwar sehen, aber nichts daran rumbasteln oder es gar löschen.

**Comment by leofeyer** [comment]
Das ist mittlerweile implementiert (Contao 3.5 glaube ich).

**Comment by aschempp** [comment]
öhm, nein?

**Comment by fenepedia** [comment]
Ich denke auch nicht.

Was hier gemeint ist, dass pro Inhaltselement individuelle Rechte für den Backend-User vergeben werden können sollen.

Im Moment kann man Zugriffsrechte vergeben, das betrifft das FrontEnd.

**Comment by leofeyer** [comment]
Mein Fehler.

**Comment by leofeyer** [comment]
Wurde mittlerweile implementiert.

**Comment by aschempp** [comment]
> Wurde mittlerweile implementiert.

Eh… nein? :D

**Comment by leofeyer** [comment]
Hm, und täglich grüßt das Murmeltier 😄

**Comment by discordier** [comment]
:smiley_cat:

**Comment by Luminanz** [comment]
Wird dieses Thema noch aktiv verfolgt?
Könnte man es nicht so lösen, wie es diese Erweiterung bei den Artikel macht:
https://contao.org/en/extension-list/fileview/lock_articles.10.en.html
![artikel sperren](https://user-images.githubusercontent.com/1551887/29117282-ee1da9a0-7cfd-11e7-9284-4aba54123d69.png)

**Comment by leofeyer** [comment]
In Contao 4.9 ist das Feature jetzt aber definitiv implementiert worden. 😄
