### ISSUE TITLE
Links to named anchors in the Custom Navigation module

### ISSUE THREAD

**Issue by septentrio** [contao/core#4080]
Hello,
It would be a nice feature in the custom navigation module to have the possibility to link to anchors nested in articles.
What do you think about it ?

**Comment by pswerbung** [comment]
Yes, this is sometimes needed, i.e. for One-Page-Sites. At the moment I'm asking myself a similar Anchor-Problem: How to add anchors to the links Contao generates in an array like <?php echo $this->pagination; ?>?

**Comment by leofeyer** [comment]
I'm closing this ticket due to lack of interest.
