### ISSUE TITLE
Palettes as array instead of string

### ISSUE THREAD

**Issue by christian-kolb** [contao/core#4127]
When you want to add fields to a dca of another module you have to change the string with str_replace or something like this. If you want to move the fields into the middle of the palette you have to rely on fields already existing.
This can cause to problems if two or more extensions extend the same module.

Wouldn't it be possible to change the palettes string to an array in Contao 3? For backwards compatibility you could check whether it's a string or an array and render it accordingly.

**Comment by leofeyer** [comment]
@aschempp is currently working on a palette manipulator: contao/core-bundle#474

**Comment by leofeyer** [comment]
I think we can close this ticket now that we have the palette manipulator, can't we?

**Comment by aschempp** [comment]
Fine with me
