### ISSUE TITLE
"chosen" im Filter

### ISSUE THREAD

**Issue by thescrat** [contao/core#4132]
Wäre es möglich die Suche in Selects, die mit 'chosen'=>true erzeugt werden, auch im allgemeinen Filter zu übernehmen. 
Entweder als eigene Eigenschaft speziell für den Filter, nach 'filter' => true oder einfach wenn das Feld im eval eh diesen Schlüssel besitzt (was eher Sinn macht)

Btw: Auf der Contao Referenz Webseite der Schlüssel "chosen" unter Evaluation nicht aufgeführt.

Danke

**Comment by leofeyer** [comment]
See contao/contao#3660
