### ISSUE TITLE
Backend-Formulare erweiterbar machen

### ISSUE THREAD

**Issue by AgentCT** [contao/core#4136]
Ich würde es schön finden, wenn man im Backend als Admin endlich die Möglichkeit hätte einfach die Formular um neue Felder ergänzen zu können.

Ich finde dabei den Ansatz bei Dolphin (http://www.boonex.com/demo) sehr gut gelungen, dort man ganz leicht neue Felder (über den Fields builder ) anlegen und somit Formulare problemlos erweitern. Meinem Wissen nach wird dabei Ajax verwendet.

Dadurch könnten sich die Administratoren auch problemloser die Strukturen von Formularen anpassen, die nicht über den Formulargenerator verwaltet werden können.

Ich hoffe das dieser interessante Ansatz in die Version 3 einfließen kann.

**Comment by leofeyer** [comment]
Ich sehe das so wie @psi-4ward.
