### ISSUE TITLE
Invalid request token - Extra page type

### ISSUE THREAD

**Issue by christian-kolb** [contao/core#4142]
Hello, I have read the discussion in the issue #3214. There was the proposal to add a new page type for the request token error.
Even though the request token is a security feature and not a usability feature, it has a tremendous negative usability effect when a user get the yellow error page. It would be great if we could get a extra page type which would be shown (as long as one is defined). If there's no defined the yellow box should still apear. Similar to the "Page not found" error message when there is no "Page not found" page defined.

**Comment by leofeyer** [comment]
The request token check will generate a customizable pretty error screen in Contao 4.
