### ISSUE TITLE
[Contao 3] Centralize new caching routine

### ISSUE THREAD

**Issue by Toflar** [contao/core#4164]
Hi Leo

I saw that you're caching dca, language and sql files in system/cache but you do this manually for every use case.
Let's take the sql for example:

		// Create the file
		$objFile = new \File('system/cache/sql/' . $this->strTable . '.php');
		$objFile->write("<?php\n\n");

		// Meta
		$objFile->append("\$this->arrMeta = array\n(");
		$objFile->append("\t'engine' => '{$sql['engine']}',");
		$objFile->append("\t'charset' => '{$sql['charset']}',");
		$objFile->append(');', "\n\n");

		// Fields
		$objFile->append("\$this->arrFields = array\n(");

		foreach ($fields as $field=>$config)

And so on and so forth.
Building the **content** of the file there is correct but directly writing it would be better if it was in a separate component.

Is there a chance that you centralize this in a certain class? :)
Something like

    $objCache = new SystemCache('sql');
    $objCache->appendTo('tl_article', $strContent);
    $objCache->replace('tl_article', $strContent);

This would allow us to cache other things in the Contao manner very easily and also make maintenance easier. I found that there's no option in the back end to kill the cache and this would be very easy with something like

    $objCache = new SystemCache('sql');
    $objCache->delete('tl_article');

    // or
    SystemCache::clearAll();

In fact this should also be done in Backend::handleRunonce() because usually after the installation of a third party module you'll have new things to be added to the cached files ;-)

Get back at me anytime if you need some further info :-)

Thanks a bunch!

**Comment by leofeyer** [comment]
Now that we have Contao 4 with Symfony, the ticket is redundant.
