### ISSUE TITLE
Dateien bei Download-Inhaltselemente beschränken mit 'extensions'=>$GLOBALS['TL_CONFIG']['allowedDownload']

### ISSUE THREAD

**Issue by danielritter** [contao/core#4271]
Wie es der Titel schon sagt, fände ich es sinnvoll, wenn man die Download-Inhaltselemente mit 'extensions'=>$GLOBALS['TL_CONFIG']['allowedDownload'] beschränkt. So kann man wirklich nur die Dateien auswählen, die auch erlaubt sind zum Downloaden.

**Comment by leofeyer** [comment]
Ist mittlerweile implementiert.
