### ISSUE TITLE
[Contao 3] use association tables

### ISSUE THREAD

**Issue by Toflar** [contao/core#4272]
Hey Leo

This is something I'd like to discuss with you and the developers (everyone who reads this basically :-)).
As we now have models and we can do cool things like this to get all the groups a member belongs to

    $objMemberGroupCollection = MemberModel::findById(12)->getRelated('groups');

it feels like there's very little needed to extend it to finally use association tables (I said "it feels like" - I don't know, that's why I want to discuss it :-)).

I can't get all the members that belong to member group id 3.

    $objMemberCollection = MemberGroupModel->findById(3)->getRelated('???'); // the closest would be the "id" field but in fact the ID can be used for other association tables too...

This would be a massive step forward but I'm struggling with the implementation.

Also we would need the DC_Table to use the ```save()``` method on the model instead of writing into the database directly so associations are kept up-to-date. But this would be cool anyway.

Tell me what you think :-)

**Comment by Toflar** [comment]
For Contao 3 and 4 there's "haste" that supports many-to-many relations for the convenience of the developers. I have been using it in almost all of my projects and it's working very well. It even supports things like `'filter' => true` in the DCA or restoring relations when undoing a delete action.

For the future I think we should rather discuss on how we can dynamically generate doctrine models based on our DCA's which should be something we should discuss on a developer meeting (for the concept) and then implement for a future version of Contao.

**Comment by bytehead** [comment]
@Toflar lets talk about this at the SymfonyCon. I've discussed a lot with @sheeep about doctrine and dca :)
