### ISSUE TITLE
Include-Inhaltselement Script

### ISSUE THREAD

**Issue by danielritter** [contao/core#4274]
Situation:
Ich habe häufig Projekte, bei denen ich nur ein Script für eine einzelne Seite brauche.

Problem:
Bis jetzt muss für jedes Script, welches nur für eine Seite gedacht ist, ein neues Layout erstellt, dort ausgewählt und einer Seite zugewiesen werden. 

Wunsch:
Ich wünsche mir ein neues Include-Inhaltselement und zwar eines, welches ganz einfach Scripte (vorallem MooTools-Scripte) von "Templates" einfügt. Kann von mir aus auch vor dem schliessenden Body-Tag eingefügt werden. Muss nicht in #container selbst sein.

Vorteile:
- Weniger Layouts (Reduzierung des Datenbalasts)
- Es verkürzt die Arbeitszeit
- Man ist flexibler

**Comment by leofeyer** [comment]
Ich schließe das Ticket aufgrund mangelnden Interesses.
