### ISSUE TITLE
Weitere Artikelteaser ober-/unterhalb anzeigen

### ISSUE THREAD

**Issue by dhe** [contao/core#4406]
Ich fände es toll, wenn man die Möglichkeit hätte, auf der Detailansicht eines Artikels die Teaser der anderen Artikel anzeigen zu lassen, um nicht immer über den Zurück Link auf die Übersicht springen zu müssen.

**Comment by leofeyer** [comment]
Ich schließe das Ticket aufgrund mangelnden Interesses.
