### ISSUE TITLE
Optimize backend theme images and increase the loading speed time

### ISSUE THREAD

**Issue by DyaGa** [contao/core#4407]
How this can be done.

1. We can convert all `gif` and `jpg` images to `png` and optimize it.

As example. Image `collapse.gif (1101 bytes)` could be converted and optimized to `collapse.png (488 bytes)`.

2. Increase the loading speed (two solutions):

2.1. Make a sprite with all this images. So browser will load a one file insead of multiple.

2.2. Move all images to css or html as data-uri.

example:

```css
.icon {   background: url(data:image/gif;base64,R0lG...); }
```

or

```html
<img width="16" height="16" alt="icon" src="data:image/gif;base64,R0lG...">
```

**Comment by leofeyer** [comment]
I'm closing this in favor of #4608 (development of a new icon set).
