### ISSUE TITLE
Optimierung der Seitenicons

### ISSUE THREAD

**Issue by andreasisaak** [contao/core#4501]
Wenn ich eine externe oder interne Weiterleitung im Menü verstecke, dann ist es nicht über das Icon gekennzeichnet. Bei einer regulären Website schon. Das ist etwas mühselig, besonders wenn man 20 Seiten durchklicken muss.

Man müsste den Pfeil ja nur in der Sättigung reduzieren.

**Comment by leofeyer** [comment]
Dieses Ticket sollte sich mit dem neuen Backend-Theme erledigt haben.
