### ISSUE TITLE
3.x: Don't support old browsers in backend

### ISSUE THREAD

**Issue by DyaGa** [contao/core#4544]
What does I mean:

1. Use only `png` icons, not `gif` (see #4407)
2. Make bg image as `png`, not `jpg`. JPG for gradient looks ugly. Or, even use CSS3 for this.
3. Remove `ie6`, `ie7` support from `css`
4. Remove of using `hoverRow` javascript function for hovering table rows. Do it with `css`.
5. ...

**Comment by leofeyer** [comment]
I'm closing this ticket in favor of #4608 (new back end icon set).
