### ISSUE TITLE
Inhaltselement Download Bild hinzufügen

### ISSUE THREAD

**Issue by dhe** [contao/core#4583]
Das Inhaltselement Download sollte die Möglichkeit erhalten, dem Download optional noch ein Bild hinzuzufügen, um z.B. ein Vorschaubild für PDFs auszugeben. Analog zu der Erweiterung downloadarchive. Möchte aber nicht für jeden DL ein Archiv erstellen.

**Comment by leofeyer** [comment]
Ich schließe das Ticket aufgrund mangelnden Interesses.

**Comment by akroii** [comment]
Mittlerweile gibt es einige Ergebnisse bei Google die ebenfalls danach suchten. 
Wäre es nicht doch irgendwie möglich, zumindest für 4.x? 😉

**Comment by fritzmg** [comment]
Wenn dann sollte das imho in der Dateiverwaltung gemacht werden, nicht direkt im Download Inhaltselement, damit man auch im Download**s** Inhaltselement die Möglichkeit hat Vorschaubilder anzeigen zu lassen.

**Comment by Aybee** [comment]
@akroii Du kannst ein Feld zum Dateimanager hinzufügen, mit welchem du dann ein Vorschaubild auswählst, welches du dann über dein Template ausgeben kannst.
