### ISSUE TITLE
Redirect to a Specific Archive in the Backend

### ISSUE THREAD

**Issue by beaniemonk** [contao/core#4603]
It's a little thing, but I was just thinking this would be nice...

For news, events, FAQs, newsletters, etc. in the back-end, if only one archive has been created, and a (non-admin) user/group does not have permission to create any new archives, clicking those modules would take them directly into the existing archive.

For example, we have many sites that use the news feature but only need a single news archive -- for example an archive named "Blog".

If I give a user access to the "Blog" news archive, but set permissions so they can't create any other news archives, clicking the "News" module in the back-end navigation would dive them directly into the listing of "Blog" articles.

In such a case, the listing of news archives doesn't serve much of a purpose for them (they can still edit the "Blog" archive via the header). This would save them an extra click, and possibly avoid some confusion over what that intermediate step is for.

I use the custombemodules extension to do this now, and it does the trick for the most part. The only problem is that when logged in as an admin, you see both sets of links, which can clutter the interface after a while.

Thanks!

**Comment by rocchidavide** [comment]
+1

**Comment by leofeyer** [comment]
See contao/contao#3794
