### ISSUE TITLE
Contao Backend images retina ready

### ISSUE THREAD

**Issue by christian-kolb** [contao/core#4608]
The Contao backend is already retina ready as the most of the layout consists of css (shadows). The only missing part would be icons with a double size.
To make it easy to use for third party developers, it would be great to have a icon generation function which chooses the icon depending on the display.

**Comment by leofeyer** [comment]
@frontendschlampe We should engage your friend to create the new icon set now, shouldn't we? @aschempp /cc

**Comment by aschempp** [comment]
If you are referring to the Contao Association, the budget for 2015 has already been planned and sent to the association members. But we could certainly add that for next year or maybe cover from an existing budget (like core support). That obviously depends on the amount…

**Comment by frontendschlampe** [comment]
I will talk to my colleague to create an example icon. Should we talk about it before to think about the direction we want to go with the icons in future? Maybe we can meet us in short mumble call!? Because of budget of the Contao Association we have to discuss! ;-)

**Comment by leofeyer** [comment]
Today at 4pm?

**Comment by frontendschlampe** [comment]
Yes, no problem! :-)

**Comment by aschempp** [comment]
Want me to join?

**Comment by leofeyer** [comment]
Of course. I want everyone involved to join :)

**Comment by jenda77** [comment]
👍

**Comment by leofeyer** [comment]
This one has eventually been resolved with the new back end theme in Contao 4.2.
