### ISSUE TITLE
Add a feature just to crop image without resizing

### ISSUE THREAD

**Issue by DyaGa** [contao/core#4650]
Now, when setting up a crop mode, for example `Left top`, image is resized and then crop. But in some cases we need a feature just to crop an image without resizing.

![](http://gyazo.com/97b2e72a03318573ac88acd5c3a904ae.png?1345034013)

_UPDATE:_ in this case [imagecopyresized](http://www.php.net/manual/en/function.imagecopyresized.php) function should be used

**Comment by leofeyer** [comment]
See #3719.
