### ISSUE TITLE
Contao 3 methods: Controller::getPageStatusIcon()

### ISSUE THREAD

**Issue by aschempp** [contao/core#4695]
@contao/developers 

I'm not totally sure, but I think this should be `Backend::getPageStatusIcon()`.

While looking at it, we would all wish there was a hook in this method, because new page types can currently not register their images.

Just before the return statement:
```
if (isset($GLOBALS['TL_HOOKS']['getPageStatusIcon']) && is_array($GLOBALS['TL_HOOKS']['getPageStatusIcon']))
{
	foreach ($GLOBALS['TL_HOOKS']['getPageStatusIcon'] as $callback)
	{
		$this->import($callback[0]);
		$image = $this->$callback[0]->$callback[1]($objPage, $sub, $image);
	}
}
```

**Comment by leofeyer** [comment]
We have added the hook long time ago, so the only open issue is moving the code to the `Backend` class. Do we still want this?

**Comment by Toflar** [comment]
Long time ago? I added a PR for 3.5 in January this year, that's not really long time ago... :-)

**Comment by leofeyer** [comment]
Ok, I'll correct myself: we have added the hook meanwhile, do we still need to move the method?

**Comment by Toflar** [comment]
Sorry, forgot to answer that: I don't think it makes sense in 3.5.
