### ISSUE TITLE
Support for "download" attribute

### ISSUE THREAD

**Issue by aschempp** [contao/core#4704]
http://davidwalsh.name/download-attribute

It would be cool to support the "download" attribute in Contao 3.1. This can be applied in the ContentDownload element, so a user can specify a custom download file name.

**Comment by leofeyer** [comment]
Does this actually work for you? It only works for direct links (files that would otherwise be shown in a new browser window) in my test environment and not for the download links of the download elements.

**Comment by leofeyer** [comment]
We have recently discussed the download attribute in https://github.com/contao/core-bundle/pull/1336 and voted against adding it to fix a Safari bug. Do we want to keep this ticket open anyway?
