### ISSUE TITLE
tinymce.css 

### ISSUE THREAD

**Issue by pmmueller** [contao/core#4743]
Contao 3 has a really neat new file and folder structure. Everything seems to have found a neat place to live, apart from the tinymce.css, which still sits in /files, sticking out like a sore thumb.  

It has been promoted as part of the css framework, and it still sits in /files, which has been labelled the "upload"-folder. 

1. Quickfix 
I would suggest to at least move it to /tiny_templates, even if it is not literally a template. I'm sure tinymce.css would feel more at home in that folder as part of the "tiny templates"-family than it does all alone in /files. 

2. Idea for a clean solution  
Ideally it would be stored in /assets/contao/css with the rest of the CSS-framework and have some kind of updating mechanism, like templates do. The original file would stay in the original folder and a copy gets edited. 

That way we would also get rid of the problem that the contao check marks an edited tinymce.css as "damaged" and the live update would no longer try to "repair" it kaput.

**Comment by leofeyer** [comment]
Both the `tinymce.css` file and the `tiny_templates` folder have been removed in Contao 4. It is now much easier to overwrite the TinyMCE configuration file in an update-safe manner, therefore you can set up your own preferred solution in the configuration template.
