### ISSUE TITLE
Dateinamen statt IDs beim Versionsvergleich

### ISSUE THREAD

**Issue by rumpelsepp** [contao/core#4828]
Das neue Contao 3 Dashboard mit der Diff Ansicht ist genial. Leider hat es zwei Schönheitsfehler.

1) Beim Klick auf den "Unterschiede anzeigen" Button sollte standardmäßig der Vergleich zwischen den letzten beiden Versionen angezeigt werden. Momentaner Standard ist die erste und letzte Version.

Wenn zwischen Version 1 und 35 verglichen wird, ist es logisch, dass sich viel geändert hat. Für den Redakteur sind aber in der Regel immer die neusten Änderungen interessant, die ein anderer Redakteuer gemacht hat (hier im Beispiel wären es Version 34 und 35). 

2) Bei vielen Sachen werden nur die IDs angezeigt. Zum Beispiel CSS File 1,3 und 5 hinzugefügt. Hier sollten die Dateinamen, oder zumindest Feldbezeichnungen geladen werden.

**Comment by leofeyer** [comment]
Ich schließe dieses Ticket zu Gunsten von contao/core-bundle#1548.
