### ISSUE TITLE
Seitenlayout + Seitenlayout für Unterseiten

### ISSUE THREAD

**Issue by pressi** [contao/core#4868]
Hallo.

Ich hatte schon öfters das Problem das ich einer Seite ein Seitenlayout zugewiesen habe, das Layout gilt ja dann auch für die Unterseiten.
Aber bei den Unterseiten brauche ich ein anderes Layout.

Bsp.:
-Seite 1 > Layout 1
--Unterseite 1 > Layout 1 (automatisch)
--Unterseite 2 > Layout 1 (automatisch)
...

Ich bräuchte es oft so:
-Seite 1 > Layout 1   => (hier sage ich Unterseitenlayout: Layout 2)
--Unterseite 1 > Layout 2
--Unterseite 2 > Layout 2

Ich hätte denn Vorschlag das man das Layout für Unterseiten schon in der Übergeordneten Seite definieren kann. Bei 10 Unterseiten ist es dann umständlich wenn sich das Layout ändert das dann bei allen Unterseiten umzustellen (auch mit der mehrere bearbeiten funktion).

Haben so ein Problem mehrere? Was meint Ihr zu diesem Feature?

**Comment by ausi** [comment]
This has been implemented in Contao 4.13. See https://github.com/contao/contao/pull/3419
