### ISSUE TITLE
Feature: Newsletter Blacklist

### ISSUE THREAD

**Issue by ofriedrich** [contao/core#4999]
Löscht ein Benutzer sein Newsletter-Abonnoment, wird der Eintrag in der Datenbank gelöscht.

Das Newslettermodul bietet die Möglichkeit, Adressen im Backend manuell oder per Import einzufügen.  Bei einer solchen Eingabe wird eine E-Mail-Adresse, die ein Benutzer zuvor gelöscht hat, stets neu eingefügt.

Anstatt die Adresse zu löschen wäre es besser, ein Flag "blacklist" zu setzen und beim Versand entsprechend zu filtern, so dass ein erneuter Import der Adresse verhindert wird.

**Comment by ofriedrich** [comment]
@leofeyer Wie sieht es mit diesem Ticket aus? Wird hieran noch gearbeitet?

**Comment by fiedsch** [comment]
Bin erst heute über das Ticket gestolpert und werfe als evtl. interessante Referenz 

https://www.rtr.at/de/tk/TKKS_ECGListe_20150702160916

in den Raum. Das wäre genau der von @tristanlins angesprochenen Hash-Ansatz.

**Comment by leofeyer** [comment]
Wie wäre denn hier das korrekte Vorgehen? Wenn ein Benutzer einen Channel abbestellt, wird seine E-Mail-Adresse dann für alle Channels blockiert oder nur für den, den er abbestellt hat? Was ist, wenn ein Benutzer 2 Channels abonniert hat und nur einen davon abbestellt?

@contao/developers /cc

**Comment by aschempp** [comment]
An der Abmeldung ändert sich doch nichts? Wenn bisher eine Abmeldung nur aus einem Channel gelöscht wurde, dann sollte das so bleiben. Statt löschen sollten wir aber einen "abgemeldet"-Status einführen (eine Checkbox auf dem Empfänger).

**Comment by aschempp** [comment]
Bzw. vielleicht die Bestätigt-Status in eine Radio-Option ändern

**Comment by leofeyer** [comment]
Hinzugefügt in contao/newsletter-bundle@def58209c5717a1ba405a6ea79c9e8ff57d36053.

**Comment by aschempp** [comment]
Great addition! Any way better implemented than I would have thought about :+1:
