### ISSUE TITLE
Automatically add sitemap XML to robots.txt

### ISSUE THREAD

**Issue by NinaG** [contao/core#5014]
I am not sure if this is possible but:

When someone activates the option for a sitemap XML in the starting point of a website, Contao should add this information automatically to robots.txt so that robots will find this sitemap XML easily (since it is not in the root anymore).

Sitemap: http://www.domain.tld/share/sitemap.xml

I suppose this will also work if you manager several websites with individual sitemaps

Sitemap: http://www.domain.tld/share/sitemap_page1.xml
Sitemap: http://www.domain.tld/share/sitemap_page2.xml
etc

**Comment by frontendschlampe** [comment]
try hofff/contao-robots-txt-editor :-)

**Comment by leofeyer** [comment]
We have discussed this many times and the rule is "never manipulate user generated files". It is ok to create a `robots.txt` file if there is none yet, but we must never mess with an existing and potentially customized file!
