### ISSUE TITLE
Alle Metainformationen zu einem Bild (oder anderen Dateien) zentral in der Dateiverwaltung eingeben

### ISSUE THREAD

**Issue by dackelchen** [contao/core#5050]
Moin, im Augenblick ist es so, dass man in Contao 3 in der Dateiverwaltung die Informationen für die Bilder eingibt, und zwar Titel, Link und Bildunterschrift. Den alternativen Text dagegen gibt man im Inhaltselement selbst an. Das bedeutet für die Mehrfachverwendung eines Bildes, dass diese Beschreibung jedes Mal neu eingegeben werden muss, obwohl sie sich ja eigentlich nie ändert.

Besteht da nicht die Möglichkeit, dass die Bildbeschreibung als weiteres Feld in der Dateiverwaltung eingegeben werden kann.

(Darüber hinaus könnte man für Redakteure die Newseingabe weiter vereinfachen, wenn es bei der Eingabe des Teaseers einen Haken gäbe, der die Funktion haben müsste, dass Teasertext und Teaserbild als Inhaltselement auch im Nachrichtenleser stehen . Zurzeit muss man das ja doppelt anlegen.)

**Comment by pswerbung** [comment]
@V15 : ja die Feldzuordnung ist nicht logisch.

-> In der 3.5x Version werden nachträgliche Beschriftungen von Bildern (Title in der Dateiverwaltung) nicht publiziert/übernommen im Frontend. Auch wenn man das Bild selbst öffnet und das CE nochmals speichert wird der Title/ALT nicht nachgeladen … erst wenn das Bild NEU ausgewählt wird, erscheint der Titel NACH dem Speichern. Tönt nach BUG für mich, nicht?

**Comment by zonky2** [comment]
für mich auch - das Verhalten ist für den Aufbau eine mehrsprachigen Seite "tödlich" - https://github.com/contao/core/issues/7774#issuecomment-284686567

**Comment by leofeyer** [comment]
Das wurde inzwischen in Contao 4 entsprechend implementiert.
