### ISSUE TITLE
C3: Ensure all Icons in the system is replaceable by DCA or CONFIG items

### ISSUE THREAD

**Issue by brandbrilliance** [contao/core#5080]
A lot of icons are  hardcoded in files and other extension code. There isn't a unified place in the DCA where we can replace icons overall. 

Having developed a BE Theme (ztheme_favorite), it was extremely difficult to do this to create larger icons for display. This applied to many icons that are simply hardcoded into templates and also into code. This is most likely as there isn't a convenient place where all icon types can be stored. Some are also rendered as CSS backgrounds so simply replacing an icon wouldn't be enough, as the CSS code to render the padding would also be needing to change.

Just a complete overhaul of the icon system will make is very friendly to quick theme replacement as well.

I started using a $GLOBALS['BE_ICONS'] in my theme, but I'm not sure if that is the correct way.

**Comment by leofeyer** [comment]
Since icon fonts are not accessible and we are now using SVG icons in the new back end theme, can this ticket be closed?
