### ISSUE TITLE
Add some SQL helper methods

### ISSUE THREAD

**Issue by DyaGa** [contao/core#5121]
In issue #4255 I propose to add `array_to_list` helper function. But, for now in Contao 3 we have a `QueryBuilder` class. So, I think this helper function should be here.

What methods I propose to add.

1 `sqlIN` and `sqlNotIN` (or another name) for producing SQL code like `id IN (1, 4, 19)` or `id NOT IN (1, 3, 5)`. Example of function:

``` php
/**
 * Return SQL IN statement
 */
public static function sqlIN($strField, array $arrValues, $blnNot = false)
{
    return sprintf('%s %sIN (%s)',
                $strField,
                $blnNot ? 'NOT ' : '',
                implode(',', array_map('intval', $arrValues))
            );
}

/**
 * Returns SQL NOT IN statement
 */
public static function sqlNotIN($strField, array $arrValues)
{
    return static::sqlIN($strField, $arrValues, true);
}
```

This methods are just an examples and have a limitation, `$arrValues` should be only as array of integers.

2 `sqlLIKE` - for generating SQL code like `id LIKE '%value%'`
3 ...and other used SQL constructions in Contao

**Comment by leofeyer** [comment]
I'm closing this ticket due to lack of interest.
