### ISSUE TITLE
[Contao 3] Include mysql triggers in the dca

### ISSUE THREAD

**Issue by SyZn** [contao/core#5141]
Hi Leo,

Thanks for all your great work! Contao rocks! I would suggest a new feature for future contao versions: It would be great if one could define SQL triggers in the DCA, just like the `sql` entry that has been moved there. I think of something like:

``` php
'sqlTriggers' => array
(
    'myFirstTrigger' => 'CALL avisota_recipient_list(NEW.id, NEW.lists);'
)
```

I would put it in the `config` section, like the `sql` array below that is already there:

``` php
'sql' => array
(
    'keys' => array
    (
        'id' => 'primary'
    )
)
```

There is a [beta-Extension](https://contao.org/de/extension-list/fileview/MySQLMultiTriggerFramework.10000003.de.html) from Tristan Lins avaliable for it already, but it would be great in the core, I think.

**Comment by leofeyer** [comment]
Since there will be no more feature releases for Contao 3, I'm closing this ticket.
