### ISSUE TITLE
FR: Headlines for module CE's

### ISSUE THREAD

**Issue by Anke** [contao/core#5230]
I often find it a bit inconvenient adding and maintaining module headlines of those modules I want to integrate in articles while on the other hand I can define headlines in form-CE's. 

So I wonder if there might be a way to add a headline field to module content elements? (One that might or might not overwrite the headline defined in the module itself that is to be used with th apage layout?)

**Comment by leofeyer** [comment]
I'm closing this ticket due to lack of interest.
