### ISSUE TITLE
C3: Inhaltselemente zwischen verschiedenen 

### ISSUE THREAD

**Issue by dmolineus** [contao/core#5234]
Möchte man Inhaltselemente beispielsweise von einem Artikel nach Events verschieben, so bekommen Redakteure eine Fehlermeldung. Im Log steht dann, dass der Nutzer keine Rechte zum Zugriff hatte, obwohl normale Bearbeitungsfunktionen funktionieren.

In der Demo reproduzierbar. Beispielsweise mit h.lewis Inhaltselemente aus Events in einen Artikel verschieben

**Comment by leofeyer** [comment]
This is now a [known limitation](https://github.com/contao/core/blob/master/system/docs/LIMITATIONS.md#moving-content-elements-as-non-admin-user).
