### ISSUE TITLE
Javascript code editor in Themes

### ISSUE THREAD

**Issue by ghost** [contao/core#5335]
It's possible to edit a JS file in the folder / tl_files / via the "Files Explorer".

What would be interesting is to move (or duplicate?) the possibility to integrate directly into the module Themes. 

As for the CSS module (also present in the module Themes). Codes JS, CSS, ... would thus be present in a single location : logical and much easier to manage in the long term, indeed JS codes are codes like CSS... almost inevitable today for a theme / frontend website quality.

Of course, as for the CSS module, it's possible to activate or not a JS script for a specific page Page layout (checkboxes, such as Mootools or Jquery templates Page layout). All optimized (minified, concatenated, ...)

This module would be an improvement in the "Custom JavaScript Code" in this Page layout. This section could possibly stay.

Please find attached document.

![js in themes](https://f.cloud.github.com/assets/3490680/131122/fbc78a28-7049-11e2-9d0b-f2dc4f1208b8.jpg)

This idea came to me because I noticed that it's impossible (or very difficult ?) to add custom JS script directly in Page layout (in the same way that the scripts j_accordion, j_colorbox, j_mediaelement,. ...) !

I hope this idea will be incorporated into future versions of Contao!

Thanks Contao, I like it !

**Comment by leofeyer** [comment]
This has been implemented in Contao 4.5.
