### ISSUE TITLE
Upload fields produce garbage files when the form is invalid in some other field

### ISSUE THREAD

**Issue by deerwood** [contao/core#5486]
If an upload widget in a form is set to store the uploaded file in "tl_files/WHATEVER" the file is moved over to the destination in the widgets method FormFileUpload.validate(), if the upload widget itself validates. That happens before the form at a whole is checked.

But when the form does not validate for any other reason (e.g. some mandatory field/widget not filled in) that move/store isn't undone. The uploaded file is still there:
1. without "doNotOverwrite" it has overwritten the original file, which can't be undone and falsifies the original
2. with "doNotOverwrite" checked, second/third etc. "file__2/3.xxx" files exist, many of them being garbage

Deleting the unwanted files after the fact / validating the whole form might work in case 2. But for case 1. the only good solution I can come up is to introduce a new widget method, say commit(), in at least upload fields, called from class Form only when all is OK. The upload field would NOT move the file in validate(), but only in commit().

Even that might fail in case of multiple upload fields in a form ... but would be better than the current state. [EDIT] Stupid me, naturally commit() would not move anything / cleaning up itself in case of error and return that to the Form class, so that Form doesn't call any other upload commit() methods.[/EDIT]

This is a bug in 2.11 (LTS) and still present in 3.0.x and should be fixed in both.

Thanks, best regards, Georg

Please see also #3007

**Comment by leofeyer** [comment]
Finally fixed in contao/contao#3734.
