### ISSUE TITLE
Angleichung des Formular-Renderings

### ISSUE THREAD

**Issue by webdecker** [contao/core#5510]
Hallo,

Feature-Wunsch: 

Ich würde es begrüßen, wenn sämtliche Formulare des Cores (Login, Registrierung, Persönliche Daten, Newsletter-Abo, Passwort vergessen, Kommentar, Formular-Generator) auf die gleiche Art gerendert würden, mämlich via form- und den widget-Templates.
Bisher führen z.B. login, comment und nl_default noch ein Eigenleben.

Hintergrund: Wenn ich die widget-Templates anpasse und style, möchte ich gerne, dass das auch auf die genannten Formulare wirkt und ich nicht jedes gesondert behandeln muss.
Bspw. hat login gar keine divs um die Felder, form_widget auch nicht, mod_comment_form hat div.widget drum herum.

Da der HTML-Code der Widgets recht spärlich ist, baue ich für das benötigte Styling eigentlich in jedem Projekt an diesen Templates herum.

Wenn ich dann ein paar weniger anfassen müsste, wäre das super!

**Comment by leofeyer** [comment]
Mittlerweile in Contao 3.5 geändert.
