### ISSUE TITLE
Provide a page list when editing an image's link

### ISSUE THREAD

**Issue by injeek** [contao/core#5544]
Hi, I like the new version's feture that you can add a link when editing an image in file manager. However, it would be better if there is a dropdown list that shows all the pages and you can choose from it, and a page Insert Tag automatically filled in the link text box. That means when I move the CMS to another domain or directory, I don't need to change the link again. That would be nice.

**Comment by mecintosch** [comment]
Ein Feature das ich des öftern vermisse. 
Somit könnte man sich das manuelle setzen der Insert Tags sparen.

**Comment by fritzmg** [comment]
The new DCA picker could be used there.

**Comment by leofeyer** [comment]
This has been implemented meanwhile.
