### ISSUE TITLE
Remove the meta keywords tag

### ISSUE THREAD

**Issue by DyaGa** [contao/core#5611]
In `fe_page.html5` instead of:

```html
<meta name="keywords" content="<?php echo $this->keywords; ?>">
```

use this:
```php
<?php if ($this->keywords): ?><meta name="keywords" content="<?php echo $this->keywords; ?>"><?php endif; ?>
```

**Comment by leofeyer** [comment]
Changed in d3f4616c909045e0b184b09cd9449d26768feafc.

**Comment by xchs** [comment]
The changes have been committed to the `core-bundle` repository: see https://github.com/contao/core-bundle/commit/d3f4616c909045e0b184b09cd9449d26768feafc

**Comment by leofeyer** [comment]
@xchs Thanks for the heads-up :)
