### ISSUE TITLE
Neues Inhaltselement "Richt Text Table"

### ISSUE THREAD

**Issue by psi-4ward** [contao/core#5634]
Neues Inhaltselement mit dem man die Tabellen-Zellen über den TinyMCE mit formatiertem Text befüllen kann.

Siehe: https://contao.org/de/extension-list/view/table4ward.de.html

![Screenshot](https://contao.org/files/repository/table4ward/10000039/picture.jpg)

**Comment by leofeyer** [comment]
Ich schließe das Ticket aufgrund mangelnden Interesses. Vermutlich benutzen die Leute eure Extension. 😄
