### ISSUE TITLE
mod_login/mod_registration - DIVs um Label und Input

### ISSUE THREAD

**Issue by phreak** [contao/core#5677]
Das Login und Registrierungsmodul in Contao wäre deutlich einfacher zu stylen und zu designen, wären nummerierte CSS-Klassen in DIVs rund um Label und Input gelegt.

Der Code des mod_login sieht jetzt so aus (stripped zwecks Übersichtlichkeit):

```html
<div class="formbody">
...
<label for="username">E-Mail</label>
<input type="text" name="username" id="username" class="text" maxlength="64" value="">
<br>
<label for="password">Passwort</label>
<input type="password" name="password" id="password" class="text password" maxlength="64" value="">
...
</div>
``` 

Deutlich mehr Möglichkeiten und weniger gefrickel gäbe es wenn DIVs rund um die einzelnen zusammengehörigen LABELS und INPUTs gelegt werden könnten. Ich hab gerade nicht die genaue und übliche Contao Syntax der Formulare im Kopf, aber ihr wisst was ich meine denke ich.

```html
<div class="formbody">
...
<div class="row1">
<label for="username">E-Mail</label>
<input type="text" name="username" id="username" class="text" maxlength="64" value="">
</div>
<div class="row2">
<label for="password">Passwort</label>
<input type="password" name="password" id="password" class="text password" maxlength="64" value="">
</div>
...
</div>
```

Ua. wäre das Nebeneinanderstellen von den beiden Formularinhalten wäre damit viel einfacher, background-CSS könnten damit vergeben werden, individuelle Abstände box-shadows für wichtige Felder, etc. Gestaltung und Design könnte viel weiter gehen.

Warum das Ticket, dies Dinge kosten mich beim CSS oft viel Zeit und unbefriedigende Ergebnisse, vielleicht geht das anderen auch so.

**Comment by leofeyer** [comment]
Die Formular-Templates wurden in Contao 3.5 komplett überarbeitet.
