### ISSUE TITLE
Use mBox MooTools plugin for Modals and Tooltips (maybe Notices) in Contao Backend

### ISSUE THREAD

**Issue by DyaGa** [contao/core#5740]
mBox with demos can be found here: http://htmltweaks.com/mBox

To my mind using of mBox have next advantages:

1) Default mBox modal window theme is very similar to Contao default backend theme:

![687474703a2f2f6779617a6f2e636f6d2f63313861643130343663353061336531396562383439646336323235313234642e706e67](https://f.cloud.github.com/assets/1192057/999750/a6789682-0a38-11e3-8ffa-b604793ea2f3.png)

2) mBox tooltips is very similar to Contao and has a lot of options:

![687474703a2f2f6779617a6f2e636f6d2f37366233623234333034623832336263643437303238623930353666323239612e706e67](https://f.cloud.github.com/assets/1192057/999752/ab61d87a-0a38-11e3-89fe-a7bef244e453.png)

or even better:

![687474703a2f2f6779617a6f2e636f6d2f66373332303766366132383935353137313338636362613966656435373735352e706e67](https://f.cloud.github.com/assets/1192057/999758/b25df712-0a38-11e3-9f38-863854b212e7.png)

3) Contao ajax data loading message can be replaced with mBox core (current Contao overlay has some css bugs):

![687474703a2f2f6779617a6f2e636f6d2f65613962333566323463393430636635353738623433316535343666303338322e706e67](https://f.cloud.github.com/assets/1192057/999759/b570182c-0a38-11e3-8b03-1faeb55724dc.png)

**Comment by leofeyer** [comment]
Since the mBox project has been abandoned (see https://github.com/StephanWagner/mBox/), I guess we can close the ticket.
