### ISSUE TITLE
Anzeige der autoload.php im Autoload-Creator

### ISSUE THREAD

**Issue by zonky2** [contao/core#5744]
Hi,

wäre es möglich im Autoload-Creator bei den Checkbox-Einträgen hinter dem Modulnamen anzuzeigen, ob eine autoload.php vorhanden ist bzw. fehlt.

Sofern die generierten autoload.php-Dateien unterscheidbar von "moduleigenen autoload.php-Dateien" wäre ein Hinweis ggf. auch schön.

**Comment by leofeyer** [comment]
Da es für Contao 3 keine neuen Features mehr gibt und in Contao 4 keinen Autoload-Creator mehr, hat sich dieses Ticket wohl erledigt.
