### ISSUE TITLE
Show more information in title of `Show differences` modal window

### ISSUE THREAD

**Issue by DyaGa** [contao/core#5800]
If you will open current `Show differences` window, you will see something like this:

![687474703a2f2f6779617a6f2e636f6d2f32643565323632323034343939623166646339653439616338613136653136652e706e67](https://f.cloud.github.com/assets/1192057/1200260/fc2f8690-2521-11e3-9a3d-e51be81c2ff9.png)

As you can see, there is no any information about differences of what record are showing.

Just for now I propose to show information in title like this: 
`Show differences: tl_news (ID: 1)`

**Comment by leofeyer** [comment]
Implemented in ae1da00c4d77b14b9472e7c3d44ac0a1985f2bf0.
