### ISSUE TITLE
Link meta information present in the file manager with alt and title attributes TinyMCE

### ISSUE THREAD

**Issue by ghost** [contao/core#5819]
In Contao 3.1, it's possible to select a file in the file manager directly from the TinyMCE editor.

If a file that has the specified meta information (Title, Link, Caption) is selected this information will not end up in the TinyMCE editor. The idea would be to link this information. And so, the information would be:
- Title (in file manager) = title attribute
- Caption (in file manager) = alt attribute

An update of information in the file explorer, would automatically update the title and alt attributes.

What do you think?

**Comment by leofeyer** [comment]
I'm closing this ticket due to lack of interest.
