### ISSUE TITLE
Add filters to the File manager module

### ISSUE THREAD

**Issue by fixounet** [contao/core#5876]
In many modules Contao (in BE), there are filters that can quickly find what you are looking for.

Except File manager module. This is quite annoying when you have hundreds of files and / or folders. It quickly loses his head!

The idea is to be able to filter by file type, filing date or by name (all files that begin the name "home", for example).

What do you think?

A +

**Comment by leofeyer** [comment]
Meanwhile implemented in Contao 4.1.
