### ISSUE TITLE
Create new Insert tags for File manager

### ISSUE THREAD

**Issue by ghost** [contao/core#5879]
`{{explorer_name::*}}`
Will be replaced by the current file name. **Ex : "name of my file"**

`{{explorer_title::*}}`
Will be replaced by the current title of the file is present in the "meta information". Ability to pass arguments to select the language. The argument "joker" will automatically select the language according to the language of the visitor. **Ex : "title of my file"**

`{{explorer_link::*}}`
Will be replaced by the current file link present in the "meta information". Ability to pass arguments to select the language. The argument "joker" will automatically select the language according to the language of the visitor. **Ex : "http://www.google.fr"**

`{{explorer_caption::*}}`
Will be replaced by the current description of the file is present in the "meta information". Ability to pass arguments to select the language. The argument "joker" will automatically select the language according to the language of the visitor. **Ex : "This is a description of my file that can be used as content for alt attribute"**

`{{explorer_url::*}}`
Will be replaced by the current URL of the file. **Ex : "./files/folder/file.jpg"**

`{{explorer_format::*}}`
Will be replaced by the format type of the current file. **Ex : ".jpg"**

`{{explorer_mime::*}}`
Will be replaced by the MIME type of the current file. **Ex : "image/jpeg"**

`{{explorer_list::*}}`
Show all files (links or previews) located in the specific folder. 

**Replace "*" with the ID file / folder**

These Insert tags may be used in any piece of content, but also and especially for the "alt" and "title" attribut.

What do you think?

**Comment by leofeyer** [comment]
I'm closing this ticket due to lack of interest.
