### ISSUE TITLE
Links in TinyMCE zu Nachrichten, Artikeln und Veranstaltungen

### ISSUE THREAD

**Issue by jankout** [contao/core#5920]
Lieber Leo,

ich würde toll finden, wenn man im TinyMCE-Editor auch einen Link zu einer Nachricht, einem Artikel oder einer Veranstaltung einfügen könnte. Habt ihr es vor? Früher gab es da eine Erweiterung dafür (https://contao.org/de/extension-list/view/morelinks.html). Ich würde aber toll finden, das direkt im Core zu haben. 

Ich danke dir schon jetzt für deine Mühe und Antwort. Mach es gut.

Jan

**Comment by jenda77** [comment]
Ich möchte nur fragen, ob ihr es demnächst umsetzen möchtet? :-)

**Comment by leofeyer** [comment]
Ist in Contao 4.4 implementiert.
