### ISSUE TITLE
schema.org Angaben für Events in Template integrieren

### ISSUE THREAD

**Issue by NinaG** [contao/core#5968]
Ich fände es sehr vorteilhaft, wenn Contao endlich schema.org Angaben in Event-Templates integriert. Ich mache das seit ner Weile manuell bei relevanten Event-Kalendern und kann jedes Mal wieder die Vorteile in den Suchmaschinen sehen.

Da die Suchmaschine durch diese Angaben versteht, dass es sich um ein Event handelt und welche Angaben was sind, tauchen diese Event-Seiten dann sogar besonders gestyled (direkt tabellarisch angezeigt nach Datum, Titel, etc.) und hervorragend lesbar direkt in den Suchmaschinen-Ergebnissen auf.

Microformats wären sicher auch eine Möglichkeit, aber schema.org ist "internationaler".

http://schema.org/Event

**Comment by ideefixx** [comment]
Der Kalender sollte ggf. auch um Felder erweitert werden. Somit wäre es später auch möglich zu prüfen ob alle relevanten Daten ausgefüllt wurden und entsprechend der Angaben könnte das Markup dann als json eingefügt werden. Sollten die relevanten Daten nicht im Mindestumfang vorhanden sein, so kann dies einfach umgangen werden um weiterhin einwandfreien Code auszuliefern.

**Comment by leofeyer** [comment]
Implementiert durch #7780.
