### ISSUE TITLE
Display category in the styles view

### ISSUE THREAD

**Issue by qzminski** [contao/core#5975]
I think it would be nice to display the style category in the list view.

![2013-07-15 at 09 58](https://f.cloud.github.com/assets/1192057/800003/65e2b5e6-ed80-11e2-9990-52e3741d7add.png)

**Comment by leofeyer** [comment]
Since the internal CSS editor has been deprecated in Contao 4 and will be removed in Contao 5, I guess we can close this issue now. 🙈
