### ISSUE TITLE
(Einfache) Verlinkung zu den Nachrichten und Events im TinyMCE-Editor

### ISSUE THREAD

**Issue by jenda77** [contao/core#5991]
Hallo Leo,

ich würde toll finden, wenn Contao in seiner Grundinstallation im TinyMCE-Editor eine Liste mit den veröffentlichten Nachrichten und Events haben könnte, um diese leichter zu verlinken. 

Es gab früher eine Erweiterung moreLinks. Aber diese wird nicht mehr entwickelt. Und das mit einem InsertTag zu lösen, ist für die Redaktore eine Zumutung. 

Liebe Grüße,

Jan

**Comment by leofeyer** [comment]
Siehe #5920.

**Comment by jenda77** [comment]
Hallo Leo, heißt das jetzt, dass es bald erscheint? Darüber würde ich mich sehr freuen. Liebe Grüße, Jan
