### ISSUE TITLE
CSS ID/Klassen werden beim INCLUDE nicht mit übergeben

### ISSUE THREAD

**Issue by Mike008** [contao/core#6011]
Sobald ich mit insert_article einen Artikel includiere wird die IDS respektive ID nicht mitübergeben. Es wäre gut das wenn dies möglich wäre, denn wenn man mehrere Artikel includiert, die beispielsweise alle ein und dieselbe Klasse haben sollen, ist man derzeit gezwungen, um jeden insert_article ein DIV zumachen oder die CSS ID/Klasse woanders mitgeben. Das ist sehr zwitaufwändig und unpraktisch.

**Comment by leofeyer** [comment]
Es gibt jetzt einen PR dazu: https://github.com/contao/core-bundle/pull/250

Der PR implementiert das Zusammenführen der CSS-Klassen, wie wir es auch schon mal besprochen aber wegen fehlender Rückwärtskompatibilität wieder verworfen hatten. Da der PR aber für Contao 4 ist, können wir die Lösung trotzdem verwenden.

Bitte testen und ggf. kommentieren.

**Comment by leofeyer** [comment]
Übernommen in contao/core-bundle@d2b1fa8663099c0060678c53d6ae8718175a566d.
