### ISSUE TITLE
Classnames on radio and checkbox span

### ISSUE THREAD

**Issue by Ruudt** [contao/core#6077]
The radio- and checkbox fields are individually enclosed within a span element, generated by the class (and cannot be templated). It would be helpful to add classes to the spans for item_first/item_last, item_0 .. item_n and item_even/item_odd. All of this can be done with CSS, but not all browsers support this. AFAIK only IE7 and IE8 don't support these selectors, and IE8 is still used a lot.

The use for this in the core is not as large as it is in (custom) extensions that generate widgets. ATM I need to select the first and last radio items, and color the odd items.

**Comment by leofeyer** [comment]
Since we have dropped support for IE 8 a while ago, I'm closing the ticket.
