### ISSUE TITLE
Zeitpunkt des Wöchentlichen Cron selbst bestimmen

### ISSUE THREAD

**Issue by MacKP** [contao/core#6089]
Ich finde das wäre ein nettes feature, wenn man in der localconfig oder in den Einstellungen angeben kann, an welchem Tag denn der wöchentliche Cron ausgeführt wird (Select von Wochentagen o.ä.).
Dadurch kann man sich wichtige Seiten auf verschiedene Tage legen um das besser unter Kontrolle zu haben.

Wäre aber zugegeben eher low priority ;-)

Viele Grüße

**Comment by leofeyer** [comment]
The cron service in Contao 4 allows for this (see contao/contao#1098), therefore I am closing this issue.
