### ISSUE TITLE
Use callbacks for hooks

### ISSUE THREAD

**Issue by aschempp** [contao/core#6092]
It would be very helpful to allow PHP callback for hooks and DCA callbacks.

http://php.net/manual/en/language.types.callable.php

The only thing I could not (yet) figure out is how this will work with singletons.

@Toflar @lindesbs @psi-4ward @TristanLins @discordier

**Comment by leofeyer** [comment]
I'm closing this ticket in favor of https://github.com/contao/core-bundle/pull/204.
