### ISSUE TITLE
Accept certain tags in figcaption tag.

### ISSUE THREAD

**Issue by lionel-m** [contao/core#6108]
For example : `<em> - <strong> - <sup> - <sub>`

For the field `Image caption` in the content element "Image" and "Text".

**Comment by leofeyer** [comment]
Contao 4 allows to define custom sanitizer rules now, therefore I am closing the ticket.

<img width="755" alt="" src="https://user-images.githubusercontent.com/1192057/145438197-043cfb3a-7904-4dba-926f-b149ae1c3378.png">
