### ISSUE TITLE
Error when toggling visibility

### ISSUE THREAD

**Issue by aschempp** [contao/core#6157]
I got this error message in my XHR results on Contao 3.1:

> Recoverable error: Argument 1 passed to tl_content::showJsLibraryHint() must be an instance of Contao\DataContainer, instance of tl_content given, called in system/modules/core/dca/tl_content.php on line 1624

The `tl_content::toggleVisibility` method triggers the onload_callbacks and passes `$this` as the first parameter. However, the `showJsLibraryHint` expects an instance of `DataContainer`.

If you remove the type forcing, the error should be gone.

**Comment by aschempp** [comment]
This problem re-appeard/still exists in Contao 4 (see https://github.com/contao/core-bundle/blob/b2a111165f347abcc35045b92f4d6e3a9398ed3d/src/Resources/contao/dca/tl_content.php#L1030)

**Comment by leofeyer** [comment]
Fixed in 694f18c915a68f6421f05883710ffd1f386c03ac.
