### ISSUE TITLE
Meta Informationen - Eingabemasken automatisch auf Basis der definierten Sprachen

### ISSUE THREAD

**Issue by saress** [contao/core#6254]
Es wäre sehr praktisch, wenn bei den Meta-Informationen eines Files (in der Dateiverwaltung) bereits die Sprachen standardmäßig aktiviert wären, die auch in den jeweiligen Seitenbäumen definiert sind.

Aktuell ist es so, dass man bei jedem File die zusätzlichen Sprachen erst immer wieder mühsam hinzufügen muss. Hier würde ein Automatismus sehr viel Zeit sparen. Alternativ könnte man sich auch überlegen vergleichbar mit den Fallback-Sprachen einfach eine komma-separierte Liste anzugeben, die die Eingabefelder dann quasi steuert/erzeugt.

**Comment by leofeyer** [comment]
Implementiert in contao/contao@5402a0c384d30b44069bbf083d6505d7da0f7f1c.
