### ISSUE TITLE
odd / even CSS Klasse bei Elementen in tabellenlosen Formular

### ISSUE THREAD

**Issue by neckarpixel** [contao/core#6259]
Es wäre super, wenn Formularelemente, die in einem tabellenlosen Formular existieren analog zur Tabellenvariante auch eine odd / even Abstufung erhalten würden.

Und was noch besser wäre, wenn innerhalb einer <fieldset> Gruppe die odd / even Zählung neu beginnen würde.

**Comment by leofeyer** [comment]
Wofür brauchst Du das in Zeiten von [:nth-child](https://css-tricks.com/useful-nth-child-recipies/)?

**Comment by leofeyer** [comment]
The automatic classes `first`, `last`, `even` and `odd` will be dropped in Contao 5 in favor of the corresponding CSS selectors, therefore I am closing this ticket.
