### ISSUE TITLE
Consistent icons

### ISSUE THREAD

**Issue by Ruudt** [contao/core#6266]
Similar actions should have consistent icons and descriptions.

Using the yellow pencil at this moment:
- for pages edits page properties (act=edit),
- for articles edits content elements list (table=...),
- for content elements edits properties of content element (act=edit),

Using the wrench/screwdriver at this moment:
- for articles edits article properties (act=edit)

As you can see this is not consistent. Even worse; when I want to edit an article from the content list (table=tl_content) the icon to edit the article (act=edit) suddenly IS the yellow pencil. So I can reach the same page using two different icons.

I think UI consistency is very important. Using two icons that represent the exact same thing can be confusing. If my description is not clear enough I can provide some screenshots.

**Comment by leofeyer** [comment]
Changed in 52e65e983ae52bf40e114d6f0e7472b1200cab43.
