### ISSUE TITLE
3.2 RC 1: Metadaten der Bilder per Ajax nachladen

### ISSUE THREAD

**Issue by schmanat** [contao/core#6403]
Wenn in einem CE ein Bild hinzugefügt wird (egal ob vom Typ Text, Bild, Galerie) werden die Metadaten welche in der Dateiverwaltung bereits eingetragen wurden nicht direkt übernommen.

Als Beispiel:
Ich lade ein Gruppenfoto in der Dateiverwaltung hoch, dieses versehe ich mit einem Titel sowie mit Bildunterschrift.
Wenn ich nun im Artikel ein Text (ce_text) erstelle, ein Bild hinzufüge und dieses auswähle bleibt der Titel sowie Bildunterschrift leer, wenn ich nun den Artikel speichere werden die Felder (Titel, Bildunterschrift) übernommen.

Es wäre ein nettes Usability Feature wenn diese Felder ebenfalls direkt nach der Auswahl des Bildes befüllt werden würden.

PS: Ich konnte das leider in der online Demo nicht testen, da es nicht erlaubt ist Meta Informationen Bilder hinzuzufügen.

**Comment by leofeyer** [comment]
Ist mittlerweile implementiert.

**Comment by Total-Reality** [comment]
@leofeyer Was genau wurde denn implementiert? Die Bildunterschrift wird bei mir in Contao 3.5.24 leider nicht ausgegeben, obwohl diese in der Dateiverwaltung definiert wurde. Es funktioniert nach wie vor irgendwie nur, dass die Bildunterschrift bei Galerien angezeigt wird, aber nicht bei Text mit Bild.

**Comment by fritzmg** [comment]
Das liegt daran, dass die Galerie die Daten direkt aus dem DBAFS bezieht, wären das Inhaltselement "Text" die Daten nur einmalig beim speichern aus dem DBAFS lädt und direkt im Element speichert.

Es gibt hier mittlerweile ein neueres Ticket, wo für Contao 4 eine andere Variante diskutiert wird: #7774
