### ISSUE TITLE
Viewport IE 11 -> Modern UI

### ISSUE THREAD

**Issue by Zeromax** [contao/core#6413]
There is a feature/bug in IE11 (10?) wich is realy stupid. It scales the page if you are resizing the Modern UI Browser. Maybe same problem for Windows Phone as well. While rotating the device.

>By default, Internet Explorer automatically scales content when the window is narrower than 1024px. This primarily includes the snapped state and portrait mode. If the @-ms-viewport rule is specified, it overrides default scaling.

>In cases where scaling is not needed or desired, the device-width keyword can be used. This keyword signifies that the page is optimized to work well regardless of the dimensions of the window. 

>When using this keyword, make sure that the page continues to work well in a variety of window sizes, including the narrow snapped state and portrait modes. 

http://bit.ly/19RdO5n

This small line is fixing this.
```css
@-ms-viewport { width: device-width; }
```

We need this in the Backend and Frontend Framework. Please put this in 3.2.

**Comment by aschempp** [comment]
I can't see a reason why not to add it. It would probably also affect any Windows tablet. Here's the MSDN information: https://msdn.microsoft.com/en-us/library/ie/hh869615(v=vs.85).aspx

**Comment by leofeyer** [comment]
Without testing how this affects things I'd prefer not to add it. Especially not in the front end, where the incompatibility risk is much higher than in the back end.

**Comment by Zeromax** [comment]
@leofeyer I am totally fine to add this only to the back end. This snippet has only effect to the "App/Modern UI/Metro" Internet Explorer since Windows 8.

**Comment by leofeyer** [comment]
Is this still relevant in Windows 10?

**Comment by Zeromax** [comment]
Nope. Only for windows 8 and Metro IE
