### ISSUE TITLE
Set protocol relative (let the browser decide)

### ISSUE THREAD

**Issue by rightvision** [contao/core#6511]
In PageRegular.php the protocol for jquery, mootools and google fonts should be
$protocol = '//';
instead of
$protocol = \Environment::get('ssl') ? 'https://' : 'http://';
This will allow Proxy-System with SSL (eg STUNNEL) to run the pages without any error, as with STUNNEL the protocol at the server is still http.

**Comment by leofeyer** [comment]
Meanwhile implemented.
