### ISSUE TITLE
pagePicker / filePicker > ersetzen mit globalen Picker

### ISSUE THREAD

**Issue by pressi** [contao/core#6538]
Hallo!

Ich würde vorschlagen einen globalen Link Picker.
In der Lightbox kann mann dann oben per Tab wechseln: Seitenstruktur, Dateiverwaltung oder externer Link.

So kann sich der Redakteur entscheiden was er verlinken will, jetzt bestand immer nur die Möglichkeit eine Datei oder eine Seite per Picker zu verlinken.
Wenn er etwas anderes wollte musste er den Link kopieren und einfügen.
Nicht jeder Redakteur kennt die Insert Tags und kann damit umgehen.

lg

**Comment by leofeyer** [comment]
Das Feature haben wir in Contao 4.4 implementiert.
