### ISSUE TITLE
Artikelverwaltung SEO Description statt Keywords

### ISSUE THREAD

**Issue by ghost** [contao/core#6582]
Man hat das Problem, so sehe ich das, dass beim Anlegen eines Artikels nur die Schlüsselwörter statt Seitenbeschreibung hinterlegen kann. 

Artikel mit Teaser leiten dann auf den Artikel weiter, aber die Seitenbeschreibung wird aus der Seitenstruktur geholt, was zu doppelter Seitenbeschreibung führt, obwohl es ja eigentlich eine eigene Seite ist.

**Comment by leofeyer** [comment]
See https://github.com/contao/contao/pull/161
