### ISSUE TITLE
ID / Klasse eigener Layoutbereiche selber vergeben

### ISSUE THREAD

**Issue by dhe** [contao/core#6630]
FR: Ich fände es gut, wenn man im Zuge von #6294 die Möglichkeit hätte, die ID und Klasse des eigenen Layoutbereichs individuell anzupassen.
Desweiteren könnte man das `<div class="custom">` entfernen oder? 
Ich persönlich habe noch keinen Nutzen darin gesehen.

**Comment by basistom** [comment]
+1

**Comment by dmolineus** [comment]
Wer das ganze jetzt schon nutzen möchte, ich hab das ganze in einer Erweiterung umgesetzt: https://github.com/netzmacht/contao-flexible-sections

Eine Anpassung des Frontend-Templates ist jedoch erforderlich. Dafür wird das `fe_flexible_sections` Template mitgeliefert in den jeweiligen Versionen für Contao 3.2, 3.3 und 3.4.

![unbenannt](https://cloud.githubusercontent.com/assets/1186266/5940055/7d044486-a708-11e4-9b8c-955d0c7e51e7.png)

**Comment by Samuelll** [comment]
+1

**Comment by frontendschlampe** [comment]
sehr fein @dmolineus ... und das jetzt als Core-Feature! :-)

**Comment by ausi** [comment]
+1
Zusätzlich zur ID sollte man auch einen Klassennamen für den Bereich festlegen können

**Comment by timgatzky** [comment]
Mhh... der Ansatz ist gut. Aber das widget ist für Verschachtelungen z.B. ein neuer Bereich im #main zu ungenau, oder man müsste in dem Select auch die bereits angelegten Layoutbereiche anbieten.
Ein baumartiger Aufbau wäre seitens der Usability ala Seitenstruktur oder Taxonomy besser.
Gerendert wird alles im #wrapper. Standardmäßig sind die alten Bekannten Bereiche aus dem fe_page.

**Comment by jenda77** [comment]
+1

**Comment by christianromeni** [comment]
Warum wird das denn immer weiter verschoben? Das is doch nen Hammer Feature....

**Comment by aschempp** [comment]
Es scheint bisher hatte niemand Lust seine Freizeit dafür zu opfern ;-)

**Comment by zonky2** [comment]
+1

**Comment by JLNNN** [comment]
+1

**Comment by leofeyer** [comment]
Implementiert in contao/core-bundle@aa91f2ba70e8ccca44cf49c7623cfecfd6d7881d.

**Comment by Xendiadyon** [comment]
Das Problem: Es ist nicht kompatibel mit bereits implementierten Layout-Bereichen. Die werden jetzt alle gelöscht und man muss sie noch einmal festlegen. Das macht Updaten zu einem ziemlichen Gefummel. Gerade bei einem Projekt festgestellt...

**Comment by aschempp** [comment]
Das wäre natürlich äusserst unschön!

 1. hast du ein bestehendes Contao 4 aktualisiert? Ab welcher Version?
 2. Du hattest eigene Layoutbereiche angelegt?
 3. Die normalen Module haben aber soweit funktioniert, oder gingen alle Module im Layout verloren?

**Comment by Xendiadyon** [comment]
Ich habe Contao 4.2.3 auf Contao 4.3 aktualisiert. Im Layout waren eigene Layoutbereiche angelegt und sichtbar/zugewiesen. Nachdem ich das Layout das nächste Mal bearbeitet hatte, sind auf einmal alle (vor dem Update) selbstdefinierten Layoutbereiche verschwunden und lassen sich auch nicht durch Wiederherstellung älterer Versionen wieder herholen.
Die im Layout eingebundenen Module sind alle in die Kopfzeile gewandert, das Layout demnach zerschossen.

Bekommen wir da irgendwie eine Update-Kompatibiliät hin?

**Comment by ausi** [comment]
Das sollte eigentlich über das Update-Skript [Version430Update.php:41-61](https://github.com/contao/installation-bundle/blob/4c594f2be8d3a2dab515a063357d310c8cb9f452/src/Database/Version430Update.php#L41-L61) im Install-Tool behandelt werden. Hast du das Install-Tool (/contao/install) nach dem Update fehlerfrei ausführen können?

**Comment by fritzmg** [comment]
Ich dachte diese Dinge passieren auch, oder nur mehr, über die Post Update Commands mit Composer? War da nicht mal die Rede davon?

**Comment by Xendiadyon** [comment]
ja, das Install-Tool hat problemlos funktioniert.

Eine weitere Anmerkung:
die IDs der Layoutbereiche wird immer klein geschrieben. CamelCase oder so funktioniert nicht.
![layoutbereiche](https://cloud.githubusercontent.com/assets/2657385/20702650/f73cd29c-b618-11e6-8597-27b40271c07e.PNG)

und in den Artikelcontainern wählt man die ID des Layoutbereiches aus und nicht den Namen:
![anzeigenin](https://cloud.githubusercontent.com/assets/2657385/20702661/0ea0b6d8-b619-11e6-973b-5aec188b3bb4.PNG)

Geht schon, aber vielleicht etwas unschön und auch ein Problem beim Update, insbesondere wenn man vorher die Layoutbereiche händisch mit CamelCase eingefügt hat.

**Comment by fritzmg** [comment]
Ich denke für beide Probleme sollten eher zwei separate Tickets angelegt werden.

**Comment by fritzmg** [comment]
Also Problem Nummer 1 kann ich nicht nachvollziehen. Nach einem Update auf Contao 4.3 (von Contao 4.2.5) wurden die Sections korrekt auf das neue Format übertragen.

Das Problem Nummer 2 habe ich hier festgehalten: https://github.com/contao/core-bundle/issues/639

**Comment by fritzmg** [comment]
> und in den Artikelcontainern wählt man die ID des Layoutbereiches aus und nicht den Namen:

Ticket dafür: https://github.com/contao/core-bundle/issues/640

**Comment by ausi** [comment]
> Also Problem Nummer 1 kann ich nicht nachvollziehen. Nach einem Update auf Contao 4.3 (von Contao 4.2.5) wurden die Sections korrekt auf das neue Format übertragen.

Ich konnte das Problem auch nicht reproduzieren, ein Update von 4.2 auf 4.3 hat die Layoutbereiche korrekt übernommen.
