### ISSUE TITLE
Easy way to remove images from gallery

### ISSUE THREAD

**Issue by alarstyle** [contao/core#6684]
What about little cross in the corner of images to remove it. So you don't need to search an image in the file tree to uncheck it.
![image](https://f.cloud.github.com/assets/1730120/2000161/8d625832-8552-11e3-9708-cc4711c2d5c8.png)

**Comment by jenda77** [comment]
+1

**Comment by leofeyer** [comment]
Implemented in contao/core-bundle@2db79c087457e469baad284bebe39d6e5f8503b9 and contao-components/contao@29162ab0acec9344abf87f5004859baa8ed6e5b5.

There is a little problem though: We can only remove images which have been added as single images. If the user selects a whole folder, it is impossible to remove a single image. The widget therefore looks like this:

<img width="706" alt="bildschirmfoto 2015-10-08 um 11 13 33" src="https://cloud.githubusercontent.com/assets/1192057/10362235/a3d43dac-6dad-11e5-81c8-d7e8bcdbdf16.png">

Can we live with this limitation? @contao/developers /cc

**Comment by Toflar** [comment]
I can :-) I would add a folder and a regular image icon to indicate the source though. This makes it very easy to explain to the users:

> For each image you can see whether you selected this specific image (image icon) or if it's loaded from a folder you selected (folder icon). Because you cannot remove one image only from a selected folder, the delete icon is only available for specificly chosen images (image icon).

**Comment by leofeyer** [comment]
Nope, because then you cannot sort the images from the folder anymore.

**Comment by leofeyer** [comment]
Ok, got it. GitHub collapsed the quote at the end of your comment, therefore I did not read it at first. I agree with you now :)

**Comment by asaage** [comment]
my personal opinion:
I can hardly see an improvement of usability if we can only remove images which have been added as single images... even with folder-indicating icons.

**Comment by jenda77** [comment]
In my eyes it should also work in every case.

**Comment by leofeyer** [comment]
It is impossible. It would either remove *all* images of the folder or the selection would have to be converted to a single image selection, which does not allow to add more images by just uploading them.

**Comment by leofeyer** [comment]
Now it looks like this:

<img width="662" alt="bildschirmfoto 2015-10-08 um 12 57 31" src="https://cloud.githubusercontent.com/assets/1192057/10364497/2ab7b89a-6dbc-11e5-8c01-abf63f6c8389.png">

**Comment by leofeyer** [comment]
It is more consistent this way than with the folder icon.

**Comment by asaage** [comment]
:ok:
