### ISSUE TITLE
No alias generation on exotic languages

### ISSUE THREAD

**Issue by andreasisaak** [contao/core#6689]
I discovered that the alias in Chinese cannot be created, the field remains empty. The generation of an alias works for Japanese pages every now and then.

Is it possible to extend the translation tables (as they already present for Russian) with the missing characters? Otherwise the Chinese customers has to generate each alias manually, which is a very time consuming tasks, trying to translate over 200 pages.

By the way, this problem can be reproduced in the online demo. Just use the following names as the page title:

会社 -> Company -> Japanese
公司 -> Company -> Chinese

**Comment by aschempp** [comment]
We should take a look at the Transliterator for this purpose (also see Security mailing list).
