### ISSUE TITLE
Extend element filter in articles' CE listing

### ISSUE THREAD

**Issue by Anke** [contao/core#6702]
I'd like to have a checkbox element filter in the CE-listing of an article to be able to combine filter options, e.g. to show all 'headline AND text elements'. This would be of great comfort in articles consisting of numerous different types of elements.

If there isn't enough room for checkboxes, maybe a multiple select dropdown would do as well, or the filter section could be set on some expandable panel ...?

What do you say?

**Comment by leofeyer** [comment]
I'm closing this ticket due to lack of interest.
