### ISSUE TITLE
Hinzufügen der Option "Responsive deaktivieren" in den Layouteinstellungen

### ISSUE THREAD

**Issue by gerritlo** [contao/core#6720]
Es wäre vorteilhaft, wenn in den Layouteinstellungen das responsive Verhalten des Layoutbuilders bzw. des Grids deaktiviert werden könnten, da dieses nicht immer gewüscht ist.

**Comment by leofeyer** [comment]
Inzwischen ist das responsive Verhalten in einem separaten Stylesheet gekapselt.
