### ISSUE TITLE
Browser.Features.Touch on Chrome always TRUE

### ISSUE THREAD

**Issue by psi-4ward** [contao/core#6741]
Hi there,

it seems that Mootools `Browser.Features.Touch` is alwys `true` on latest Chrome versions. (https://github.com/cpojer/mootools-mobile/issues/15)

It makes some click-actions in listing unusable cause the second click leads to the edit-mask. I could patch it with 
```javascript
// touch fix
if(!(('ontouchstart' in window) || window.DocumentTouch && document instanceof DocumentTouch)) {
  Browser.Features.Touch = false;
}
window.addEvent('domready',function(){
  if(!Browser.Features.Touch) $(document.body).removeClass('touch');
});
```

in my extension, we sould put this in the core.

**Comment by aschempp** [comment]
Due to no feedback on my last question within a year, we can probably close this.
