### ISSUE TITLE
Empty permissions are not inherited in page

### ISSUE THREAD

**Issue by aschempp** [contao/core#6782]
I have discovered a permission issue. Steps to reproduce in demo:

1. Go to page tree
2. Edit page courses
3. Remove all checkboxes for the backend user permissions (basically, none of the selected users should be able to change anything)
4. Login as limited user
5. You will see that permissions are correct on the "Courses" page, but not inherited to the child pages

I wanted to remove access to a specific part of the page for all regular users (because there are only news modules)...

**Comment by leofeyer** [comment]
As discussed on Mumble on May 21st, this needs to be fixed; in version 3.5 and 3.2 (transition phase).

**Comment by leofeyer** [comment]
Fixed in cd37b1be82204e08497dd7a1d8127c1623f78c4d.
