### ISSUE TITLE
Speicherung als timestamp, bei Verwendung eigener Formulare, z.B. auf die DB-Tabelle tl_calender_events oder andere

### ISSUE THREAD

**Issue by ThomasPichlo** [contao/core#6827]
Es wäre vom Vorteil, wenn die Core-Funktionen so angepasst werden, dass generell Datum und Uhrzeit-Angaben als timestamp in der DB gespeichert werden.

Ich finde es sehr unglücklich, dass hier unterschiedliche Herangehensweisen bestehen.

**Comment by leofeyer** [comment]
Geändert in e5d6d93a7c17ada4eceed994d95d131237542256.

**Comment by Gr3yh0und** [comment]
@leofeyer :+1: 
Können wir das wie ursprünglich mal getaggt (3.4.0) auch für 3.5.X kriegen?

**Comment by leofeyer** [comment]
Nein, da die Änderung nicht rückwärtskompatibel ist.

**Comment by iosis101** [comment]
Das gleiche Problem besteht wieder bei Contao 4.

**Comment by xchs** [comment]
@iosis101 Welche Contao-Version genau? Unter Contao 4.4.18 kann ich es jedenfalls nicht reproduzieren. Das Datum wird korrekt als Timestamp in der entsprechenden Tabellenspalte gespeichert.

**Comment by Aybee** [comment]
@xchs Ja, kann ich auch bestätigen.

**Comment by iosis101** [comment]
4.4.18 Ich brauche um ein Event über Frontend zu speichern das Startdatum sowie die Start -und Endzeit. Das Datum ist kein Problem. Es wird per Datumsfeld auch als timestamp in der DB gespeichert. 1A. Die Zeit Das Problem liegt bei der Uhrzeit. Sie lässt sich nicht als timestamp speichern. Zumindest wüsste ich nicht wie.


UPDATE: danke closed.

**Comment by fritzmg** [comment]
> 4.4.18 Ich brauche um ein Event über Frontend zu speichern das Startdatum sowie die Start -und Endzeit. Das Datum ist kein Problem. Es wird per Datumsfeld auch als timestamp in der DB gespeichert. 1A. Die Zeit Das Problem liegt bei der Uhrzeit. Sie lässt sich nicht als timestamp speichern. Zumindest wüsste ich nicht wie.

Zeit = Datum + Zeit.
