### ISSUE TITLE
saving in edit all of tl_page is very slow

### ISSUE THREAD

**Issue by backbone87** [contao/core#6830]
ursache:
https://github.com/contao/core/blob/3.5/system/modules/core/dca/tl_page.php#L34
das rekursive generieren der sitemap wird für jede bearbeitete seite im edit all durchgeführt, dadurch wird das speichern extrem langsam, wenn man 100+ seiten bearbeitet.

**Comment by leofeyer** [comment]
Fixed in contao/contao@156f6287f8b90cc2c53066e2d721de4699ee226f.
