### ISSUE TITLE
authenticate in BackendUser nutzbar machen

### ISSUE THREAD

**Issue by Babelfisch** [contao/core#6850]
Wäre es möglich, die `authenticate`-Methode in `BackendUser` für Erweiterungen nutzbar zu machen? Momentan ist es ja leider nicht möglich den Status eines BE-Nutzers mit der Methode abzufragen, da im Erfolgsfall gar nichts zurückgegeben wird (`return;`) oder im Fehlerfall eine Weiterleitung auf die Anmeldeseite erfolgt.

Notwendig ist dies bspw. in Hooks wie `outputBackendTemplate`, die auch aufgerufen werden, wenn der Nutzer abgemeldet ist und es für eine Erweiterung damit nicht möglich ist, festzustellen, ob der Zugriff von einem angemeldeten Nutzer kam.

Schön wäre es, wenn man bspw. mit `authenticate(false)` die Weiterleitung deaktivieren und `true` oder `false` zurückbekommen könnte.

**Comment by leofeyer** [comment]
@contao/developers What do you think about this?

**Comment by aschempp** [comment]
Halte ich für unnötig/falsch, weil das ganze ja durch Symfony Security ersetzt werden soll…

**Comment by Babelfisch** [comment]
Kann man mit Symfony Security dann im FE auch schon angemeldete BE-Nutzer authentifizieren?

**Comment by aschempp** [comment]
> Kann man mit Symfony Security dann im FE auch schon angemeldete BE-Nutzer authentifizieren?

Theoretisch… Symfony benutzt sogenannte "Firewalls" für verschiedene Bereiche, die voneinander unabhängig sind. Da die entsprechenden Informationen aber in der Session stehen, sollte das schon gehen. Bin mir nur noch nicht sicher wie genau am besten ist. Und die Contao 4.0 ist da noch nicht soweit… (siehe https://github.com/contao/core-bundle/issues/122)

**Comment by ausi** [comment]
Im Frontend zu überprüfen ob ein User im Backend eingeloggt ist wäre aus meiner Sicht ein wichtiges Feature. Ich habe die Problematik in einer Erweiterung mit einer Ableitung von `BackendUser` gelöst: [madeyourday/contao-rocksolid-frontend-helper/…/FrontendHelperUser.php](https://github.com/madeyourday/contao-rocksolid-frontend-helper/blob/b221e10857ffb98e698db578e0226e6dd8e4f9f7/src/MadeYourDay/Contao/FrontendHelperUser.php).

**Comment by Babelfisch** [comment]
Klingt dann aber nicht wirklich nach einem sauberen Weg, wenn man die Daten direkt aus der Session nimmt.

Nur noch mal zum Hintergrund: Das Problem ist bei meinem Frontend Editor aufgefallen. Frontend Editing ist ja (unabhängig von meiner Erweiterung) ein durchaus interessantes Thema und dort ist es nun mal unabdinglich, dass alle Daten über den angemeldeten BE-Nutzer zur Verfügung stehen.

**Comment by aschempp** [comment]
Das ist mir schon klar. 

> Klingt dann aber nicht wirklich nach einem sauberen Weg, wenn man die Daten direkt aus der Session nimmt.

Das habe ich mich auch schon gefragt, ist aber bei Symfony normal so. Und die werden sich schon was überlegt haben… ich muss da aber auf jeden Fall noch etwas nachforschen.

**Comment by leofeyer** [comment]
Und ganz generell halte ich es auch für falsch, die `authenticate()`-Methode umzubiegen, weil es sich eben nicht um eine `isAuthenticated()`-Methode handelt. Sofern wir hier also tätig werden, würde ich eine neue Methode bevorzugen.

**Comment by Babelfisch** [comment]
Da habe ich kein Problem damit. Mir geht es nur um eine saubere Möglichkeit, ohne mich am System vorbei mogeln zu müssen.

**Comment by leofeyer** [comment]
@Babelfisch Hat sich dieses Ticket mit Symfony Security (Contao 4.5) erledigt?

**Comment by Babelfisch** [comment]
Kann ich leider nicht sagen, da ich noch bei der 3.5.x hänge.

**Comment by aschempp** [comment]
Ich denke das hat sich mit Contao 4.5/Sf Security erledigt.

**Comment by timgatzky** [comment]
Nimm doch einfach die tl_session Tabelle und prüfe diese auf tstamp, sessionID und name=BE_USER_AUTH. 
tstamp aktualisiert sich je Reload im Backend. tstamp + Systemeinstellung für die Session-Lease muss kleiner dem aktuellen unix timestamp sein.  Damit du ggf. nicht dich selbst identifizierst, muss die sessionID != deiner aktuellen php session_id sein.
Die pids sind dann die ids der angemeldeten BE-Users.

**Comment by bytehead** [comment]
`tl_session` gibts in Contao 4.5 nicht mehr.

**Comment by timgatzky** [comment]
Babelfish ist in 3.5. In 4.5 kann laut Andreas Symphony selbst genutzt werden.

**Comment by Babelfisch** [comment]
Ich nutze ja mittlerweile auch tl_session. Mir ging es hier aber ursprünglich um eine von Contao bereitgestellte Möglichkeit, um ebene bei genau solchen Änderungen wie von 3.x auf 4.x nicht die komplette Authentifizierung umstellen zu müssen. Da es aber für die 3.x nun ehe keine Änderung mehr gibt und es bei der 4.5 ja (vermutlich) eine Möglichkeit gibt, brauchen wir das nicht weiter vertiefen. Trotzdem danke für alle Tipps!
