### ISSUE TITLE
Filepicker in den Stylesheets speichert noch Pfade ab

### ISSUE THREAD

**Issue by andreasisaak** [contao/core#6853]
Das Filepicker Wizard (https://github.com/contao/core/blob/master/system/modules/core/dca/tl_style.php#L384) in den Stylesheets speichert noch Pfade ab. Wir haben den Fehler grade bemerkt als wir diesen Bug (https://github.com/menatwork/MultiColumnWizard/issues/140) im MCW fixen wollten.

Kann man das Verhalten ändern? Diesen speziellen Filepicker ganz aus dem Core entfernen würde ich nicht, da er schon extrem praktisch ist. Grade bei Wizards wie dem MCW.

Man könnte z.B. in Contao 3.3 eine Routine mitliefern die die bisherigen Inhalte konvertiert und dann weiterhin UUID's abspeichern, im Textfeld aber das ganze wieder leserlich umwandeln. Funktioniert ja bei den normalen Filepickern auch recht gut.

**Comment by leofeyer** [comment]
Da der interne CSS-Editor in Contao 4 als veraltet markiert wurde und in Contao 5 entfernt wird, schließe ich dieses Ticket.
