### ISSUE TITLE
Stylesheet Ausgabe anpassbar machen

### ISSUE THREAD

**Issue by saress** [contao/core#6898]
Es wäre super, wenn es eine Möglichkeit geben würde, die Ausgabe der zusammengefassten und komprimierten Stylesheets im Frontend zu beeinflussen.

Aktuell wird das ja im Front durch:

```
<?php echo $this->stylesheets; ?>
```

gelöst und in /system/modules/core/pages/PageRegular.php zusammengesetzt.
Bei der Ausgabe ergibt das dann z.B. folgendes:

```
<link rel="stylesheet" href="assets/css/957f79ebab16.css">
```

Es wäre aber interessant, wenn man hier noch weitere Daten ergänzen könnte. Zum Beispiel eine id oder sonstiges. Warum? Als aktuelles interessantes Beispiel habe ich z.B. folgendes gefunden:

http://www.holisticon.de/2014/02/perfect-google-pagespeed-insights-score-der-mobilen-website-von-elitepartner-beine-machen/

Hier ist der Abschnitt "CSS asynchron laden" ziemlich interessant. Das gleiche Konzept könnte man dann eventuell auch auf andere derzeit nicht beeinflussbare Ausgabeparameter anwenden, wie z.B. die Ausgabe $this->mooScripts; oder $this->framework;

Beste Grüße und vielen Dank
Sares

**Comment by leofeyer** [comment]
Ich schließe das Ticket aufgrund mangelnden Interesses.
