### ISSUE TITLE
Contributing Guidelines

### ISSUE THREAD

**Issue by xchs** [contao/core#6904]
We might consider adding a `CONTRIBUTING.md` file in the root of the repository, so we can explain thoroughly about how to submit e.g. new issues, pull requests etc.

Thus, we could teach a contributor for instance to
* search first the issue tracker before filing a new ticket
* clearly describe the issue including all the steps how to reproduce the bug in the Contao online demo
*  …

Look at some [example](https://github.com/TryGhost/Ghost/blob/master/CONTRIBUTING.md) `CONTRIBUTING` [files](https://github.com/puppetlabs/puppet/blob/master/CONTRIBUTING.md) to get a better idea of the usage and of how this could be written in detail.

Furthermore, this will automatically add a hint with a link to the `CONTRIBUTING` file when a contributor creates a new issue or opens a pull request:

![contributing](https://cloud.githubusercontent.com/assets/1218766/2742615/e1e20e0c-c706-11e3-9da5-41ce02b6fabd.jpg)

See the GitHub [Contributing Guidelines](https://github.com/blog/1184-contributing-guidelines) for further information.

**Comment by leofeyer** [comment]
Finally added in 9594dd8e11c6a71806335bdca7ffbb15619d014a.
