### ISSUE TITLE
Additional Style Sheets

### ISSUE THREAD

**Issue by rburch** [contao/core#6911]
In Additional Style Sheets section it may be helpful to add an option for external style sheets. I use Font Awsomes's Bookstrap stylesheet that they serve (`<link href="//netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css" rel="stylesheet">`) and other's once and awhile as well. I normally just add them in the Additional `<head>` section, but when doing that it loads them after pulling in Contao's javascript file so that the external style sheets load out of order after the javascript. Google Page Speed recommends all style sheets loading one after the other and then the Javascript loading after that. I could edit the fe_page template, but I try to avoid that when I can.

**Comment by leofeyer** [comment]
This has been implemented meanwhile.
