### ISSUE TITLE
CodeMirror for TinyMCE 4

### ISSUE THREAD

**Issue by xchs** [contao/core#6936]
To facilitate editing (HTML) source code and to beautify the code presentation it would be nice to have a syntax highlighting within TinyMCE's code editor.

There is a TinyMCE plugin based on the CodeMirror code editor which provides such a functionality: http://www.avoid.org/codemirror-for-tinymce4/

I've done a short test on the latest develop branch and it appears to be working correctly so far:

![tinymce_codemirror](https://cloud.githubusercontent.com/assets/1218766/2858216/21968a9c-d183-11e3-9f9e-bfaa12ecffeb.png)

However, it would be even better if we could also use the ACE source code editor instead of CodeMirror since we are already using this plugin.

**Comment by xchs** [comment]
FYI: The [CodeMirror plugin](https://github.com/cliffparnitzky/TinyMceCodeMirror) can be loaded via the [TinyMcePluginLoader](https://github.com/cliffparnitzky/TinyMcePluginLoader) as well. Thanks to @cliffparnitzky!

**Comment by leofeyer** [comment]
@cliffparnitzky Look great!

**Comment by cliffparnitzky** [comment]
@leofeyer thx
