### ISSUE TITLE
Contao 3.2.x - CE-Download / News Attachments - Meta-Information from the Filemanager

### ISSUE THREAD

**Issue by blackbee** [contao/core#6966]
Hi guys,

I have a question about the Meta-Information by the Filemanager in combination with Attachments in News-/Events or as an CE-Download (Single).

Why does the Meta-Information provided in the Filemanager for a File is not shown in the Frontend? Is it a bug or a feature?

Here a short List of the tests I made:

News -> Settings of the News -> One or more files added as attachment:
the Meta Information (Filemanager) are ignored

News -> News Content -> Use the Single Download Item and added not extra Meta-Information:
the Meta-Information (Filemanager) are ignored

News -> News Content -> Use the Downloads-Element:
the Meta-Information (Filemanager) are working

The same behavior is also when using the CE-Download / CE-Download in a regular article.

I know that I can set an Meta-Information for a single CE-Download manually. But what is about the Attachment-Function in News?

Should the behavior with Meta-Informations not the same like dealing with an Image?

Cheers

**Comment by DVeris** [comment]
+1
meta for enclosure in news - very necessary

**Comment by leofeyer** [comment]
> Why does the Meta-Information provided in the Filemanager for a File is not shown in the Frontend?

This has been changed meanwhile.
