### ISSUE TITLE
Option for showing news-image in Newsreader

### ISSUE THREAD

**Issue by rustykowski** [contao/core#6985]
In Contao 2.x konnte das Nachrichtenbild auch automatisch im Nachrichtenleser angezeigt werden. In 3.x hat sich die Logik aufgrund der Inhaltselemente im Nachrichtenleser geändert.
Dennoch enthält die Modulkonfiguration für den Nachrichtenleser immer noch Felder für Bildgröße und Beschneidung, die in der Regel jedoch nicht wirksam werden, weil das Standardtemplate news_full kein Nachrichtenbild enthält.
Gut wäre ein zusätzliches Standardtemplate mit Ausgabe des Nachrichtenbildes, oder besser noch eine Checkbox wie für die Metafelder Datum, Autor, Kommentare.

**Comment by leofeyer** [comment]
Ich schließe das Ticket aufgrund mangelnden Interesses.
