### ISSUE TITLE
Separate Email address settings for Form sender, Administrator and Errors receivers. 

### ISSUE THREAD

**Issue by tsarma** [contao/core#7024]
At the moment "E-mail address of the system administrator" is used for many purposes like form senders email, or Account lock email receiver or 3rd party module may use this too.

It would be nice to set emails for all these individually. For example a from should have a new input field where once can specify senders email with a fall back to administrator's email.

**Comment by leofeyer** [comment]
@aschempp Is this something that the notification center can do?

**Comment by aschempp** [comment]
Definitely for the form, yes.
