### ISSUE TITLE
disableAlias does not work with useAutoItem

### ISSUE THREAD

**Issue by aschempp** [contao/core#7026]
https://github.com/contao/core/blob/master/system/modules/core/library/Contao/Controller.php#L2183

If aliases are disabled in the frontend, the auto_item parameter will not work. I think it should generate an URL like `index.php?id=5&auto_item=alias`.

Very low priority for me, maybe we should think about dropping `disableAlias`?

**Comment by leofeyer** [comment]
The flag has been dropped meanwhile, therefore I'm closing the ticket.
