### ISSUE TITLE
Synchronisation timeout

### ISSUE THREAD

**Issue by iCodr8** [contao/core#7035]
I am using Contao 3.2.9 and have many many files in my filesystem. If I want to start a sync, than I am getting a timeout after 30 seconds.
If I am setting ```ini_set('max_execution_time', 0);``` in my localconfig.php (only for test) than it takes a long time, but it works.

Is it possible to set this by default on sync?

**Comment by leofeyer** [comment]
Fixed in ad5fe5480caf484540d6286b72102e8b362cf344 then.
