### ISSUE TITLE
Image sizes are not passed to callbacks

### ISSUE THREAD

**Issue by volkerrichert** [contao/core#7066]
Hi Contao Team!

at https://github.com/contao/core/blob/master/system/modules/news/modules/ModuleNews.php#L202

you push the "plain" article array into the news callbacks but in 170ff you add some information about the image of the news to a copy of that array.

Maybe it's better to call

```
$this->$callback[0]->$callback[1]($objTemplate, $arrArticle, $this);
```

even if the row may be changed by a callback...

**Comment by leofeyer** [comment]
@ausi What's your opinion?

**Comment by ausi** [comment]
I don’t see the need for this, `$arrArticle` is only used for `addImageToTemplate()`, even the template object itself gets the unmodified data in [ModuleNews.php:85](https://github.com/contao/core/blob/8f678aaf08102432f943241a90d13c1c308741bd/system/modules/news/modules/ModuleNews.php#L85). What is the use case for this change?
