### ISSUE TITLE
Filter funktionieren im Treeview (mode 5/6) nicht.

### ISSUE THREAD

**Issue by Sehiro** [contao/core#7074]
Einerseits wird ein aktivierter Filter der im DCA konfiguriert wird nicht mit den möglichen Werten befüllt und andererseits wird ein gewählter Filter nicht berücksichtigt.

Basis Version 3.3.2

Ich kann leider keine gefixte Version anhängen (nur Bilder sind erlaubt). Hab jetzt schon screenshots versucht...

Die Datei schick ich gern per mail. 

Mit dem fix funktioniert dann z.B auch ein Filter für Artikel. 

```php
$GLOBALS['TL_DCA']['tl_article']['fields']['author']['filter'] = true;
$GLOBALS['TL_DCA']['tl_article']['fields']['protected']['filter'] = true;
$GLOBALS['TL_DCA']['tl_article']['fields']['inColumn']['filter'] = true;
$GLOBALS['TL_DCA']['tl_article']['list']['sorting']['panelLayout'] .= ';filter';
```

Offen für Feedback.

Viele Grüße

Stefan

![](https://cloud.githubusercontent.com/assets/7794408/3174396/688e0474-ebf1-11e3-989a-b76baae89225.jpg)

![](https://cloud.githubusercontent.com/assets/7794408/3174409/9e7a02ea-ebf1-11e3-87d2-56258aa0c50f.jpg)

![](https://cloud.githubusercontent.com/assets/7794408/3174411/9e7deff4-ebf1-11e3-9bf5-b039160a0f9b.jpg)

![](https://cloud.githubusercontent.com/assets/7794408/3174410/9e7ab41a-ebf1-11e3-96d8-e8abea95429d.jpg)

**Comment by leofeyer** [comment]
Implementiert in contao/core-bundle@0f66cd425c31835191fae92287bc95e56b35fd3c.
