### ISSUE TITLE
Key Value whitelist für http POST analog zu "requestTokenWhitelist"

### ISSUE THREAD

**Issue by Sehiro** [contao/core#7082]
Es wäre prima, wenn ich den php session check beim http POST optional umgehen könnte. Ich habe auch schon "requestTokenWhitelist" gefunden. Allerdings ist dazu ein reverse dns lookup nötig und der Server von dem mein Contao gerufen wird ist in der cloud, also nicht fix.

Da der Call per HTTPS kommt, sind die Post Parameter ja verschlüsselt, deswegen wäre es Klasse, wenn ich einen magic Parameter übergeben könnte, mit dessen Hilfe ich meinen Request identifizieren könnte.

Ich würde mir folgendes im RequestToken.php in der Funktion validate nach dem requestTokenWhitelist check wünschen:

    if (\Config::get('requestTokenKeyValueWhitelist'))
    {
    	foreach (\Config::get('requestTokenKeyValueWhitelist') as $key=>$value)
    	{
    		$postValue = Input::post($key);
    		if (!empty($postValue))
    		{	
    			if ($postValue == $value)
    			{
    				return true;
    			}
    			else
    			{
    				break;
    			}
    		}
    	}
    }

Im localconfig.php hätte ich dann sowas wie:

    $GLOBALS['TL_CONFIG']['requestTokenKeyValueWhitelist'] = array( "magicPostParameter" => "verySecretValue");

stehen.

Danke, Grüße

Stefan

PS: Bin ich mit solchen Requests hier überhaupt richtig?

**Comment by leofeyer** [comment]
Entweder Du deaktivierst den Request-Token-Check komplett oder Du legst Dir einen separaten Entry-Point an, bei dem der Token-Check umgangen wird.
