### ISSUE TITLE
jQuery laden: Quelle (Feature Request)

### ISSUE THREAD

**Issue by Babelfisch** [contao/core#7091]
Ich fände es praktisch, wenn man nach dem Anwählen von `jQuery laden` in der Dropdown-List `jQuery Quelle` als vierte Option noch `nicht automatisch laden` oder etwas in der Art hätte. In diesem Fall würde man jQuery selbst irgendwo im Layout laden, könnte aber trotzdem bequem über Contao `j_` jQuery-Templates dazu laden. Außerdem könnten so Extensions `$objPage->hasJQuery` nutzen.

Sinnvoll ist dies bspw. bei Frameworks wie Bootstrap oder Foundation, die im Allgemeinen gleich eine passende und getestete jQuery-Version mitbringen und die Reihenfolge beim Laden der einzelnen Komponenten vorgeben. Das lässt sich am einfachsten direkt im Template machen, jedoch kann man dann Contao nicht mitteilen, dass jQuery genutzt wird.

**Comment by leofeyer** [comment]
Ich schließe das Ticket aufgrund mangelnden Interesses.
