### ISSUE TITLE
Beim Aufruf des Contao Ordners den User prüfen

### ISSUE THREAD

**Issue by andreasisaak** [contao/core#7100]
Ausgangsbasis ist eine nicht vorhandene Prüfung des derzeit eingeloggten Backend-Users. Ich habe z.B. öfter den Fall das ich mit einem Tab im Backend eingeloggt bin und im 2ten Tab das Frontend besuche. Wenn ich dann unvorsichtigerweise /contao anstelle von /contao/main.php dranhänge, werde ich ausgeloggt. Im ersten und im zweiten Tab.

Könnte man in der index.php eine Prüfung hinterlegen und dann einfach auf /contao/main.php mit eingeloggtem User weiterleiten? Es ist schon ziemlich nervig einfach ausgeloggt zu werden :(

Testen kann man das in der Demo so:

1. Im Backend einloggen
2. Frontend im neuen Tab öffnen
3. Im Frontend-Tab /contao an die Url hängen (man bekommt dann den Login zu sehen)
4. Im ersten Tab ist man nun auch ausgeloggt

**Comment by leofeyer** [comment]
In Contao 4 wird es dieses Problem nicht mehr geben, da `/contao` die Haupt-Backend-Route ist und `/contao/login` die Anmelde-Route.
