### ISSUE TITLE
Adding a plugable auth system

### ISSUE THREAD

**Issue by leo-unglaub** [contao/core#7113]
Hey,
i think its time that we add a pluggable authentication system to Contao 4. The main goal of this would be to remove the coupeling between the user model and the tl_member table.

This would allow single sign ons, open id auth, ldap, ... authentications.
Greetings
Leo

**Comment by garyee** [comment]
While doing some searching for this subject I came across [this extension](https://mp-itconsulting.com/single-sign-onoff.html). The author did respond to my e-mail that he is planning to put it in the ER when it is finished (even with some more possibility's of authentication and other stuff)
I do not know if it will be compatible to Contao 4.x ... 
Anyways I am all for the decoupling, to facilitate future development.

**Comment by leofeyer** [comment]
I guess this ticket can be closed now that we are using Symfony security.
