### ISSUE TITLE
Always show save buttons on screen

### ISSUE THREAD

**Issue by Ruudt** [contao/core#7149]
Displaying a submit container at the bottom of the viewport in the BE will increase ease of use. Hiding the submit container when the regular one is visible. Analog to Magento, TYPO3 and many others.

Since a submit container has more space there may be room for a "Go Back" button on it as well.

**Comment by leofeyer** [comment]
In Contao 4, you will be able to compose your own Contao edition. You can then make the sticky footer extension part of your distribution.
