### ISSUE TITLE
pagepicker in meta-informations of files

### ISSUE THREAD

**Issue by frontendschlampe** [contao/core#7169]
Actually I have to insert a string (URL or insert tag) but it will be much more comfortably for internal Contao-pages if it would be possible to integrate the same functionality of page-picker like in ce_image (and other elements) with the pickpage-icon.

**Comment by frontendschlampe** [comment]
it will also be very useful, if I can choose, if the link should open in new window (`target="_blank"`)

@leofeyer could you move the ticket to contao/core-bundle?

**Comment by frontendschlampe** [comment]
... and maybe implement it in one of the next versions. ;-)

**Comment by leofeyer** [comment]
Don't need to move it. It is open and tagged as feature.

**Comment by ausi** [comment]
I created a pull request for this feature: contao/core-bundle#1568

@frontendschlampe what do you mean regarding `target="_blank"`?
