### ISSUE TITLE
Überscheiben und Löschen von Metadaten bei Bildern

### ISSUE THREAD

**Issue by dackelchen** [contao/core#7177]
Im Normalfall setzt man die Bildunterschrift direkt in der Dateiverwaltunbg ein.

Ein Redakteur kann diese später direkt im Inhaltselement Bild überschreiben.

Wenn er dann die neue Bildunterschrift direkt am Bild wieder rausnimmt, wird nicht die ursprüngliche Angabe aus der Dateiverwaltung übernommen, sondern es erscheint gar keine Bildunterschrift.

Ein Blick an die entsprechende Stelle der Datenbank zeigt::

Wenn direkt beim Inhaltselement ein eingegebener Text (bildunterschrift)gelöscht wird stht in der DB dann der Wert NUKK, nehme ich den in der DB raus, werden die Metadaten wieder übernommen

Ich habe dazu auch ergänzend einen Thread im Forum gemacht: https://community.contao.org/de/showthread.php?51534-Problem-Bidunbterschrift

**Comment by leofeyer** [comment]
Wir wollen das zukünftig anders handhaben: #7774.
