### ISSUE TITLE
OAuth-Unterstützung

### ISSUE THREAD

**Issue by leofeyer** [contao/core#7179]
Ich fände es wichtig, wenn Contao endlich mal eine OAuth-Unterstützung erhielte. Dabei stelle ich mir zum einen folgendes vor:
- Anmeldung mit Twitter
- Anmeldung mit Facebook
- Anmeldung mit Google+

Aber ich möchte darüber hinaus noch ein anderes Szenario abbilden:
- Eine zentrale Contao-Installation verwaltet Mitglieder
- Eine andere Contao-Installation soll gegen diese zentrale Installation Mitglieder mittels OAuth authentifizieren können
- Wurde ein Mitglied authentifiziert, soll ein Abgleich der Daten aus `tl_member` erfolgen, beispielsweise über einen JSON-Datensatz

Das Problem daran ist, dass ich noch nie mit OAuth gearbeitet habe. Hat jemand von euch schon Erfahrung damit und kann uns mit seinem Fachwissen unterstützen? Sind die beschriebenen Szenarien realistisch?

**Comment by ADoebeling** [comment]
Ein großes +1 hierfür von meiner Seite :)

Ergänzen möchte ich:
* Login via GitHub (BE)

**Comment by fritzmg** [comment]
In Contao 4 ist das mit der Symfony Firewall wohl nun leichter zu implementieren (ohne es an ein Mitglied zu binden), nehme ich an.

**Comment by iCodr8** [comment]
Wir (@craffft) haben eine OAuth2 Authentifizierung basierend auf dem Symfony [FOSOAuthServerBundle](https://github.com/FriendsOfSymfony/FOSOAuthServerBundle) für Contao 4 umgesetzt. Dabei wird momentan die tl_member Tabelle verwendet. Könnt ihr euch ja mal anschauen. Habe gerade gestern die Version 1.0.0 deployed.

https://github.com/Craffft/contao-oauth2-bundle

**Comment by aschempp** [comment]
Very nice!

> Please update your database with the following command, because the contao install tool will not generate the symfony relevant tables.

Kleiner Hinweis, in Contao 4.3 ist das geändert, sodass sowohl das Install-Tool auch ORM-Tabellen kennt, also auch `doctrine:schema:update` die Änderungen aus Contao. Das könnte bei dir zu Problemen führen weil du die Definition sowohl im DCA als auch im Entity hast.
