### ISSUE TITLE
Send the 404 page in (news) reader modules

### ISSUE THREAD

**Issue by tristanlins** [contao/core#7238]
@frontendschlampe and me find out, that the news reader send it's own 404 page content.
We agree that this behavior is wrong, the reader should use the 404 error page.

It should be easy to fix, replace [these 3 lines](https://github.com/contao/core/blob/master/system/modules/news/modules/ModuleNewsReader.php#L108-L110) with [this one](https://github.com/contao/core/blob/master/index.php#L97-L98).

Calendar module: [ModuleEventReader.php#L108-L110](https://github.com/contao/core/blob/master/system/modules/calendar/modules/ModuleEventReader.php#L108-L110)

FAQ module: [ModuleFaqReader.php#L105-L107](https://github.com/contao/core/blob/master/system/modules/faq/modules/ModuleFaqReader.php#L105-L107)

Newsletter module: [ModuleNewsletterReader.php#L107-L109](https://github.com/contao/core/blob/master/system/modules/newsletter/modules/ModuleNewsletterReader.php#L107-L109)

**Comment by leofeyer** [comment]
Changed in f4fa803d6a597fef77c3516eeefb31b6b31326f0. It now also renders the 404 page if a given page number is invalid.

**Comment by frontendschlampe** [comment]
I like :-)

**Comment by leofeyer** [comment]
Me too :)
