### ISSUE TITLE
Abweichender Form-Aufbau bei Newsletter-Subscription/Unsubscription

### ISSUE THREAD

**Issue by NinaG** [contao/core#7273]
In den normalen Formularen wird nach der Kombi Label + Eingabe-/Auswahlelement immer entweder:
- danach ein BR
- rundherum ein SPAN oder 
- rundherum ein DIV.widget
gesetzt.

Bei den Modulen Newsletter-Anmeldung und -Abmeldung ist das aber nicht der Fall. Das fällt meist nicht auf, da die Labels hier standardmäßig ausgeblendet werden. Wenn man sie aber einblendet (Usability / Barrierefreiheit), stolpert man über das fehlende Element. Es wäre eigentlich egal, welches der obigen Elemente eingefügt wird. Hauptsache eines davon, so dass man zu der nachfolgenden Formularkombi (wenn die Verteilerauswahl aktiv ist) irgendein Trennelement hat (z.B. um floatende Labels zu clearen o.ä.).

Es wäre schön, wenn Contao an der Stelle konsequent bleibt und auch hier das Formular so aufbaut, wie man es von den anderen Modulen gewohnt ist.

**Comment by leofeyer** [comment]
Ich schließe das Ticket zugunsten von #7292.
