### ISSUE TITLE
Mehrere Logins pro Seite und unterschiedliche Weiterleitungsziele

### ISSUE THREAD

**Issue by mwitzmann** [contao/core#7286]
Guten Tag,

wenn man mehrere Logins mit unterschiedlichen Weiterleitungszielen in eine Seite integriert, dann verwendet Contao immer die Weiterleitungsseite des ersten Login-Formulars, welches es auf der Seite findet.
Sollte es hier nicht prüfen, von welchem Login-Formular eine Anfrage gestellt wurde und dementsprechend die dazugehörige Weiterleitungsseite selektieren?

Reproduzierbar in der aktuellen Contao-Demo.

**Comment by leofeyer** [comment]
Geändert in contao/core-bundle@76e82f4ab4fd0746ba989aea48b8b60652ee2b96.
