### ISSUE TITLE
Inkonsistente Templates für Formulare (Change Request)

### ISSUE THREAD

**Issue by cepharum** [contao/core#7292]
In Contao 3.3.5 fallen mir recht unterschiedliche Formulare auf, die es teilweise erforderlich machen, beim Anwenden eines möglichst einheitlichen Designs mehrere CSS-Selektoren zu nutzen, damit alle Formulare homogen erscheinen. In #6238 wurde eine Revision der Formulare erwähnt, die aber noch nachbesserungswürdig zu sein scheint.

Ich bin mir natürlich dessen bewusst, dass sich für eine Upgrade-Fähigkeit die Formulargestaltung nicht ständig ändern sollte. Daher wäre das IMHO eine Möglichkeit für den nächsten Major-Step (4.0).

### Formulargenerator

Wenn ich im Formulargenerator ein Formular erzeuge, dann sieht das im HTML so aus:

```
<div class="formbody">
 <div class="mandatory">
  <label for="ctrl_1" class="mandatory">label</label>
  <input name="a" id="ctrl_1" class="text mandatory" value="" required="" type="text">
 </div>
 <div class="explanation">
  <p>Text</p>
 </div>
 <div>
  <label for="ctrl_2">label</label>
  <input name="b" id="ctrl_2" class="text" value="" type="text">
 </div>
 <div>
  <label for="ctrl_3">label</label>
  <input name="c" id="ctrl_3" class="text" value="" type="text">
 </div>
 <div class="mandatory">
  <label for="ctrl_4" class="mandatory">label</label>
  <textarea name="d" id="ctrl_4" class="textarea mandatory" rows="10" cols="40" required=""></textarea>
 </div>
 <div class="error">
  <p class="error">Bitte beantworten Sie die Sicherheitsfrage!</p>
  <input name="c20988cf39afe379abd5beda3d0c951d5" id="ctrl_5" class="captcha mandatory error" value="" maxlength="2" required="" type="text">
  <span class="captcha_text error">Bitte rechnen Sie 5 plus 2.</span>
 </div>
 <div class="submit_container">
  <input id="ctrl_6" class="submit submit_container" value="Senden" type="submit">
 </div>
</div>
```

Der Selektor für das Label eines Felds wäre hier exemplarisch  `.formbody > div > label`. 

Dass die Submit-Schaltfläche selbst noch einmal als "submit_**container**" ausgezeichnet wurde, ist vermutlich ein Versehen.

### Mitglieder-Login

Demgegenüber wird das Formular für den Mitglieder-Login noch nach einem älteren Stand gerendert:

```
<div class="formbody">
 <input name="FORM_SUBMIT" value="tl_login" type="hidden">
 <input name="REQUEST_TOKEN" value="token" type="hidden">
 <label for="username">Benutzername</label>
 <input name="username" id="username" class="text" value="" type="text"><br>
 <label for="password">Passwort</label>
 <input name="password" id="password" class="text password" value="" type="password">
 <div class="checkbox_container">
 <input name="autologin" id="autologin" value="1" class="checkbox" type="checkbox"> <label for="autologin">Angemeldet bleiben</label>
 </div>
 <div class="submit_container">
  <input class="submit" value="Anmelden" type="submit">
 </div>
</div>
```

Die Nutzung von `<br>` erscheint mir generell fragwürdig, da es Aufgaben zur visuellen Gestaltung von Nicht-Fließtext-Inhalt wahrnimmt und darum unnötig im CSS entfernt werden muss, wenn man es nicht wünscht, mal davon abgesehen, dass es bspw. zwischen den ersten beiden Feldern erscheint, vor dem Checkbox hingegen nicht, weil dieses in einem `<div/>` liegt. Sich hier auf visuelle Eigenschaften im Browser zu verlassen erscheint mir unvorteilhaft, doch vermutlich wurden darum andere Fälle bereits korrigiert.

### Passwort vergessen / Mitglieder-Registrierung

Beim Passwort-Vergessen-Formular und beim Mitglied-Registrieren-Formular hingegen findet sich eine leicht anders geartete Revision der Templates:

```
<div class="formbody">
 <input name="FORM_SUBMIT" value="tl_lost_password" type="hidden">
 <input name="REQUEST_TOKEN" value="token" type="hidden">
 <div class="fields">
  <div class="mandatory">
   <label for="ctrl_email" class="mandatory">
    <span class="invisible">Pflichtfeld</span> E-Mail-Adresse<span class="mandatory">*</span>
   </label>
   <input name="email" id="ctrl_email" class="text mandatory" value="" required="" maxlength="255" type="email">
  </div>
  <div>
   <label for="ctrl_lost_password">Sicherheitsfrage</label>
   <input name="secret" id="ctrl_lost_password" class="captcha mandatory" value="" maxlength="2" required="" type="text">
   <span class="captcha_text">Bitte rechnen Sie 6 plus 4.</span>
  </div>
 </div>
 <div class="submit_container">
  <input class="submit" value="Neues Passwort anfordern" type="submit">
 </div>
</div>
```

Zum einen existiert hier ein zusätzlicher Container .fields um alle Elemente, abgesehen vom Submit. Auch ist die Gestaltung des Captcha im CSS schwerer zu fixieren, weil man bspw. für ein 2-spaltiges Layout das label floaten lassen muss, das input und span aber zusammen um das label floaten müssten, damit sie sauber in der rechten Spalte bleiben.

## Lösungsvorschlag

Man könnte alle Formulare nach einem einheitlichen HTML-System erzeugen lassen, 
* das nicht nur abwärtskompatibel ist, sondern 
* mit nur wenigen CSS-Regeln jeweils 
  * entweder ein 2-spaltiges Layout per float oder aber 
  * als Tabelle mit flexibler Breite  oder 
  * eine komplett alternative Anordnungen (1-zeilig statt 2-zeilig) auf einem Smartphone odgl. erlabt:

```
<div class="formbody">
  <div class="field field-type-bspw-email">
    <label>text<span class="mandatory">*</span></label>
    <div>
      <input> oder <textarea> oder <select> ...
    </div>
  </div>
  <div class="field password error">
    <label>text</label>
    <div>
      <span class="error">Das Passwort ist falsch!</span>
      <input type="password" ...>
    </div>
  </div>
  <div class="field captcha">
    <label></label>
    <div>
      <input type="answer">
      <span>the calculation</span>
    </div>
  </div>
  <div class="field submit">
    <label></label>
    <div>
      <input type="submit">
    </div>
  </div>
</div>
```

* Die Markierung, welche Art von Element in der Zeile vorliegt, könnte auf dem Zeilen-Container als Klasse ausreichend sein und so alle Optionen für das Styling offenhalten, bspw. um zwischen einem `.captcha` und einem `.submit` einen anderen Abstand einzubauen als zwischen einem `.select` und einem `.submit`.

### Design für 2-spaltige Darstellung per float (linke Spalte mit fester Breite)

```
.formbody > .field, 
.formbody > .field > * { 
  position: relative; 
  overflow: hidden; 
}
.formbody > .field > * { 
  float: left; 
}
.formbody > .field > label {
  width: 10em;
}
```

* Da alle Elemente der rechten Spalte in einem eigenen Container sind, kann man diesen unabhängig per `position:relative;overflow:hidden;` _einsperren_, damit sie definitiv nicht unter das Label nach links rutschen können, wenn die rechte Spalte weit und oft genug umbricht. In den jetzt vorliegenden Formularen wäre eine solche Stabilisierung komplexer Inhalte neben dem Label nicht wirklich realisierbar.
* Der `*` im Selektor ist zugegeben nicht optimal, doch durch das `>` ja durchaus stark eingeschränkt, so dass die Performance eher kaum leiden dürfte.

### Design für 2-spaltige Darstellung (linke Spalte mit variabler Breite)

```
.formbody {
  display: table;
}
.formbody > .field {
  display: table-row;
}
.formbody > .field > * {
  display: table-cell;
}
```

* Elemente über die volle Breite wären hierbei nur bedingt realisierbar, doch bliebe dann noch der vorherige Ansatz mit float als Alternative. Ich persönlich finde es übersichtlicher, wenn Erklärungen in einem Formular ebenfalls auf die rechte Spalte begrenzt sind, doch das ist natürlich sehr subjektiv.

### 1-spaltig

```
.formbody > .field > label,
.formbody > .captcha > span {
  display: block;
}
```

Ich hatte unter 2.x mal eine Extension entwickelt, die entsprechend die Standardtemplates des Formulargenerators überlud, doch auch dieser Ansatz würde jetzt nicht optimal greifen, solange im Core verschiedene Quellen zum Generieren von Formularen genutzt werden und jeweils gesondert angepasst werden müssten.

**Comment by leofeyer** [comment]
Also, der aktuelle Aufbau im Formulargenerator ist dieser:

```html
<div class="widget widget-text mandatory">
  <label for="ctrl_3" class="mandatory">Your e-mail</label>
  <input type="email" name="email" id="ctrl_3" class="text mandatory" value="@" required>
</div>
 <div class="widget widget-textarea">
  <label for="ctrl_4">Message</label>
  <textarea name="message" id="ctrl_4" class="textarea" rows="6" cols="40"></textarea>
</div>
<div class="submit_container">
  <button type="submit" id="ctrl_6" class="submit">Submit form</button>
</div>
```

Diesen Aufbau könnten wir auch für die anderen Formulare übernehmen. Allerdings gibt es ja noch die Option "Tabellenlayout", bei der der Aufbau ein anderer ist:

```html
<tr>
  <td><label for="ctrl_3" class="mandatory">Your email</label></td>
  <td><input type="email" name="email" id="ctrl_3" class="text mandatory" value="@" required></td>
</tr>
<tr>
  <td><label for="ctrl_4">Message</label></td>
  <td><textarea name="message" id="ctrl_4" class="textarea" rows="6" cols="40"></textarea></td>
</tr>
<tr>
  <td>&nbsp;</td>
  <td>
    <div class="submit_container">
      <button type="submit" id="ctrl_6" class="submit">Submit form</button>
    </div>
  </td>
</tr>
```

@contao/developers @frontendschlampe @MacKP Hier frage ich mich, ob wir das Tabellenlayout überhaupt noch brauchen?

**Comment by xantippe** [comment]
für mich kann Tabelle raus - eine "doppelspaltige" Tabelle (also zwei Eingabefelder+Label nebeneinander) responsive zu machen, ist eher "schwierig"...

Wer das trotzdem benötigt, könnte auf ein eigenes Template zurück greifen.

**Comment by frontendschlampe** [comment]
Also ich sehe keinen Bedarf mehr für Tabellenlayouts. Gerade in Zeiten von responsive Design kann man diese sowieso nicht mehr gebrauchen, deshalb würde ich Sie entfernen.

Als zweites ist mir noch aufgefallen, dass das ```<div class="submit_container">``` um die Konsistenz zu wahren, eigentlich ```<div class="widget widget-submit">```heißen sollte.

Des weiteren wäre ich dafür, dass wir bei den einzelnen Formularelementen die Option "Absende-Schaltfläche hinzufügen" entfernen sollten. Das verwirrt in meinen Augen nur.

**Comment by xantippe** [comment]
```Des weiteren wäre ich dafür, dass wir bei den einzelnen Formularelementen die Option "Absende-Schaltfläche hinzufügen" entfernen sollten. Das verwirrt in meinen Augen nur.```

JA, JA, JA!!

**Comment by Toflar** [comment]
Und hätten wir eine generelle Form-Klasse die sowohl die Formulare des Formular-Generators als auch alle anderen auf Basis von Widgets rendern würde, hätten wir die Inkonsistenz nie gehabt.

**Comment by xantippe** [comment]
so isses - wie meine Oma immer sagt!

**Comment by MacKP** [comment]
Tabelle kann von mir aus auch raus an der Stelle. :)

**Comment by cepharum** [comment]
@leofeyer Um nochmal auf meinen obigen Lösungsvorschlag zurückzukommen und mit deinem Vorschlag zu vergleichen: dein Vorschlag bildet noch keine möglichen Fehlermeldungen oder dergleichen ab. Sofern diese auch weiterhin geplant sind, würde ich sehr die Grundstruktur

```html
<div>
  <label/>
  <div>
    <input/>
    <span/>
  </div>
</div>
```

pro Formularzeile vorschlagen. Dies erlaubt durch Floating oder auch durch Anwendung von `display:table-cell` auf das `<label/>` und dessen nebenrangiges `<div/>` ein Nebeneinanderlegen dieser beiden und das gesicherte Limitieren einer Fehlermeldung auf die "rechte Spalte". Ich hatte das oben in meinem Lösungsvorschlag so exemplarisch abgebildet. Einzeilige Labels und mehrzeilige Felder (Captcha mit Fehler bspw.) rechts daneben würden so sich prima floaten oder eben per CSS zu zweispaltigen Tabellen stylen lassen.

**Comment by frontendschlampe** [comment]
> Dann kannst Du aber keine einzeiligen Formulare mehr machen, oder?

Doch, natürlich: ```.widget { float: left; }``` oder ```.widget { display: inline-block; }``` und in Bootstrap würden die beiden ```.widget``` eine col-Klasse bekommen.

**Comment by frontendschlampe** [comment]
@cepharum Das kannst du aber auch erreichen, wenn label, input und error in der selben Ebene liegen - ich bin mir nicht sicher, ob ein weiterer verschachtelter div sinnvoll ist.

**Comment by xantippe** [comment]
ich denke auch, dass label, input und (error)-span auf einer Ebene liegen sollten - so ist es warscheinlich einfacher, die Reihenfolge zu ändern z.B. um den Error-span vor/über das Label zu setzen oder bei rtl alle umzudrehen

**Comment by cepharum** [comment]
@frontendschlampe Mal ein Konstrukt wie dieses annehmend:

```html
<div class="widget widget-text mandatory error">
  <label for="ctrl_1" class="mandatory error">
    <span class="invisible">Pflichtfeld</span> E-Mail-Adresse<span class="mandatory">*</span>
  </label>
  <p class="error">Bitte füllen Sie das Feld "E-Mail-Adresse" aus!</p>
  <input type="email" name="email" id="ctrl_1" class="text mandatory error" value="" required>
</div>
```

Kann ich natürlich auch durch einen margin nach links auf dem `<p>` und dem `<input/>` erreichen, dass diese erscheinen als wären sie in einer rechten Spalte. Aber:

- Das Design der Tabelle müsste stets auch an den darin enthaltenen Elementen wiederholt werden (Redundanz).
- Inhaltsabhängige Spaltenbreiten wären so nicht möglich: wenn ich bspw. erreichen möchte, dass alle Formularzeilen wie eine Tabelle erscheinen, bei der die linke Spalte abhängig von der Länge aller Labels automatisch gesetzt wird.
- Selbst fixe Breiten für die Labels in relativen Maßen werden schwierig, wenn in den Elementen rechts dann nicht einheitliche Basisgrößen für relativ bemaßte Margins vorliegen. Bspw. durch eine kleinere Schrift beim `<p/>` mit dem Fehler würde ein `margin-left: 10em` eine andere Weite bewirken als beim `<input/>` danach.

All diese Probleme wären mit einem zusätzlichen Container sofort aus der Welt. Einziger Nachteil: etwas mehr HTML-Code. Doch fällt das IMHO kaum ins Gewicht, erst recht so lange manche Markierungen wie `mandatory` (siehe Beispiel von Leo Feyer oben) in mehreren Instanzen wiederholt werden, obwohl durch Kaskadierung eine Markierung am Container genügen würde, ohne dank der restlichen Klassen in den Elementen einer CSS-Performance-Optimierung im Wege zu stehen ...

```CSS
.mandatory > label {
}

.mandatory > .text {
}
```

**Comment by cepharum** [comment]
@xantippe Eine Änderung der Reihenfolge ist IMHO mit der zusätzlichen Verschachtelung nicht unterbunden. Im Gegenteil: label und Extra-div kann man für rtl immernoch tauschen.  Auch ohne Styling bliebe die Folge im HTML label, span, input. Das div lässt sich bei semantischer Betrachtung ausblenden.

Durch den Extra-div kann ich dann so immernoch ein neues Referenzkoordinatensystem eröffnen und relativ dazu den Fehler nach oben und unten schieben, was ohnehin per Kapselung nur jenes Extra-div betreffen könnte, ohne Auswirkungen auf das label davor zu haben. Somit kann ich tauschen und doch regeln, dass bspw. auch in einem RTL-System nicht margins gedreht werden müssen, weil table-cells definiert sind, die der Browser stets richtig ausrichtet.

```CSS
div.row { position: relative; overflow: hidden; padding-top: 1em; }
div.row > label { float: right; width: 10em; }
div.row > div.field { position: relative; overflow: hidden; }
div.row > div.field > span.error { position: absolute; top: -1em; left: 0; right: 0; }
```

Mal ungetestet skizziert ...

**Comment by xantippe** [comment]
o.k. ....

**Comment by leofeyer** [comment]
Es gibt jetzt einen PR  für die Änderungen: https://github.com/contao/core-bundle/pull/249

**Comment by leofeyer** [comment]
Bitte die Änderungen in contao/core-bundle#249 testen und ggf. kommentieren, damit der PR zeitnah übernommen werden kann.

**Comment by Aybee** [comment]
Gibt es irgendwo ne Demo von Contao 4 zu sehen mit den ganzen Formularen und allen Feldern drin?

Sind alle sonstigen Formulare berücksichtigt worden?

- Quicknavigation
- Quicklink
- Login-Formular
- Persönliche Daten
- Registrierung
- Passwort vergessen
- Konto schließen
- Abonnieren
- Kündigen
- Suchmaschine
- Kommentare
- Auflistung

Bin mir nicht sicher, ob das alle sind.

**Comment by leofeyer** [comment]
Der PR wurde in contao/core-bundle@d10c826ae5dd7a4ec984dbe65325cd28ef50abc4 übernommen.
