### ISSUE TITLE
Keine Weiterleitung bei leerem Passwort beim Ändern.

### ISSUE THREAD

**Issue by cepharum** [contao/core#7303]
Ich habe in Contao 3.3.5 ein Formular eingerichtet, dass nur die Möglichkeit bietet, dass Mitglieder-Passwort zu ändern. Dazu nutze ich ein "Persönliche Daten"-Modul und habe dort eine Weiterleitungsseite definiert, welche nach dem Speichern der Persönlichen Daten angezeigt werden soll.

Wenn ich nun die Seite aufrufe und die Angaben zum Passwort leer lasse, aber auf die Schaltfläche "Daten speichern" klicke, wechselt Contao zur Weiterleitungsseite, welche unabhängig von der Angabe eines neuen Passworts angibt, man hätte erfolgreich sein Passwort geändert.

Die Intelligenz im Modul, nicht zur Weiterleitung zu wechseln, wenn nur die Eigenschaft "Passwort" aktiviert ist aber keine Angabe im Formular erfolgte, wäre "nice to have" ... stattdessen wäre eine Fehlermeldung, dass man ein Passwort angeben muss, oder einfach das Neuladen der aktuellen Ansicht (so als wäre keine Weiterleitungsseite gesetzt) sinnvoller.

**Comment by leofeyer** [comment]
Das entsprechende Modul wurde in Contao 3.5 hinzugefügt.
