### ISSUE TITLE
SMIME/PGP - Support für SwiftMailer

### ISSUE THREAD

**Issue by katgirl** [contao/core#7310]
Da SwiftMailer SMIME/PGP Unterstützung bietet, wäre es schön, wenn man diese auch für Formulare nutzen könnte.

**Comment by squareZ** [comment]
Gibt es hierzu Neuigkeiten? Würde gerne ausgehende Nachrichten (Registrierung, Passwort vergessen etc.) per S/MIME unterschreiben lassen.

**Comment by discordier** [comment]
@leofeyer @katgirl Please review and test PR #7616.

**Comment by leofeyer** [comment]
See #7616.
