### ISSUE TITLE
FR (-Frage) URL-Seitenpicker mit Option für Artikel

### ISSUE THREAD

**Issue by zonky2** [contao/core#7312]
Hallo,

wäre es möglich den Seitenpicker optional (Checkbox o.ä.) um die Anzeige von Artikeln zu erweitern?

Wenn ich einen bestimmten Artikel "picken" will, geht das nicht und ich muss mir den Insert-Tag selbst zusammenbauen `{{article::*}}`

Im Forum habe ich keine "Workarounds" o.ä. gefunden - daher hier mein Posting.

**Comment by leofeyer** [comment]
Das Feature wurde in Contao 4.4 implementiert.
