### ISSUE TITLE
Rewriting problem with getUnusedGet

### ISSUE THREAD

**Issue by LupusVII** [contao/core#7317]
Hi.

First, I am sorry if the subject was already opened (in german) but I don't find it with english translations of german.

I work on Contao 3.3.4
The problem is that I wanted to make specific URLs for the forum I have made. But the system find an error on the :
```php
catch (UnusedArgumentsException $e) at index.php - l.262
```
I have this rule on my htaccess : 
```htaccess
RewriteRule forum/([A-Za-z0-9-]+)/([A-Za-z0-9-]+).html$ sujet/$2.html?theme=$1 [QSA,L]
```  
This work perfectly on a htaccess tester. But not on Contao, who give me in $objPage->alias (in index.php) the string "forum".

After, I decided to show the $_SERVER array, and I found that Environnement::request() get the variable 
static::get('requestUri'). So, the Environnement class don't find redirect urls and send wrong pages to the browser.

I change this (Environnement Class : line 424) :
```php 
$strRequest = preg_replace('/^' . preg_quote(TL_PATH, '/') . '\/?/', '', static::get('requestUri'));
```
To : 
```php
if(static::get('redirectUrl') != static::get('requestUri')) {
	$strRequest = preg_replace('/^' . preg_quote(TL_PATH, '/') . '\/?/', '', static::get('redirectUrl'));
} else {
	$strRequest = preg_replace('/^' . preg_quote(TL_PATH, '/') . '\/?/', '', static::get('requestUri'));
}
```

It works now but I don't know if this is the right way to do it. Maybe you have a good reason to send requestUri instead of redirectUrl.

Thanks for your answer and excuse my english :)

**Comment by leofeyer** [comment]
You can adjust the `$_SERVER` array in your `initconfig.php` file.
