### ISSUE TITLE
Add image resize modes that add instead of crop

### ISSUE THREAD

**Issue by Ruudt** [contao/core#7319]
When re-sizing images for a gallery (or several image elements next to one another) I need to **cut** parts of **images** that are in various aspect ratios to get matching dimensions to fit a list. A new option that fits the image to the dimensions and then fills the background with top left, bottom right, transparent or fixed color could solve this.

This is related to #3719 and #4650; just another addition. Perhaps to support all these the entire re-sizing function could be replaced with a tool like Aviary (preferably better if available) as an extra option or complete replacement. Such a tool would probably not be an option for multiple images.

**Comment by leofeyer** [comment]
The script is not open source.
