### ISSUE TITLE
Internet Explorer (up to Version 9) only supports up to 4095 CSS Selectors per File

### ISSUE THREAD

**Issue by fatcrobat** [contao/core#7320]
Internet Explorer until Version 9 supports only a maximum of 4095 CSS Selectors. If files in TL_CSS or TL_USER_CSS has the static flag, the Combiner will aggregate CSS into one file, without taking max CSS-Selector count into consideration.

[MSDN Blog Post] (http://blogs.msdn.com/b/ieinternals/archive/2011/05/14/internet-explorer-stylesheet-rule-selector-import-sheet-limit-maximum.aspx)

I know Internet Explorer 9 is bit outdated, but still supported by Microsoft until [2017] (http://www.zdnet.com/microsoft-to-drop-support-for-older-versions-of-internet-explorer-7000032437/).

Maybe you could use the following Plugin: https://github.com/dlundgren/php-css-splitter and split the aggregated Files, if beyond 4095, into parts.

**Comment by leofeyer** [comment]
I'm against implementing this. IE9 is outdated and CSS file aggregation is deprecated in favor of HTTP/2. 

@contao/developers What do you think?

**Comment by aschempp** [comment]
Should be fixed if we add the option **not** to combine CSS in the page layouts.

**Comment by Toflar** [comment]
I second @leofeyer as well as @aschempp. Can be closed imho.

**Comment by ausi** [comment]
> I second @leofeyer as well as @aschempp.

Me too
