### ISSUE TITLE
Accessible HTML5-video player

### ISSUE THREAD

**Issue by NinaG** [contao/core#7322]
Paypal hat einen barrierefreien HTML5-Player mit guter Fallback-Lösung unter einer guten Lizenz veröffentlicht:
https://github.com/paypal/accessible-html5-video-player

Er ist JS-Framework unabhängig, unterstützt Untertitel und ist sehr gut barrierefrei umgesetzt.

Vielleicht eine gute Alternative zum aktuellen Player im Core?

**Comment by xchs** [comment]
https://contao.org/en/extension-list/view/accessible-html5-video-player.en.html
