### ISSUE TITLE
Manuelle Sortierung / Cut-Button funktioniert nicht überall (paste_button_callback)

### ISSUE THREAD

**Issue by Total-Reality** [contao/core#7354]
Hallo,

Ich habe wie im tl_article festgelegt, dass die Elemente "ausgeschnitten" werden können, um ihre Sortierung ändern zu können.

Es funktioniert allerdings nur im Mode 5. Ich verwende allerdings den Mode 2 wie die Mitgliederlisten z.B.

Dort habe ich in der DCA testweise ein neues Feld "sorting" und den cut-Button hinzugefügt

PHP-Code:
      'cut' => array 
      ( 
        'label'               => &$GLOBALS['TL_LANG']['tl_member']['cut'], 
        'href'                => 'act=paste&amp;mode=cut', 
        'icon'                => 'cut.gif', 
        'attributes'          => 'onclick="Backend.getScrollOffset()"' 
      ),  

Außerdem kommt der paste_button_callback zum Einsatz.

PHP-Code:
'paste_button_callback'   => array('tl_member_ext', 'pasteMember')  
In der Funktion steht zum Test ein echo 'test'; das mir in Contao nach dem Kopieren oder Einfügen eines Elementes aber fälschlicherweise nicht angezeigt wird (mode 2). In mode 5 wird es allerdings angezeigt.
Das lässt mich zu dem Schluss kommen, dass im mode 5 scheinbar der paste_button_callback ignoriert wird?!

Kann man das irgendwie umgehen oder so erweitern, dass es funktioniert?

**Comment by leofeyer** [comment]
Wie genau lässt sich das reproduzieren?

**Comment by Total-Reality** [comment]
Hallo Leo,

1. Z.B. die Datei system\modules\core\dca\tl_member.php auf mode 5 statt mode 2 umstellen.
2. Anschließend bei fields natürlich noch eine pid hinzufügen.
3. Bei operations noch den cut Button einsetzen. Bspw.

      'cut' => array
      (
        'label'               => &$GLOBALS['TL_LANG']['tl_member']['cut'],
        'href'                => 'act=paste&amp;mode=cut',
        'icon'                => 'cut.gif',
        'attributes'          => 'onclick="Backend.getScrollOffset()"'
      ),

Ich hoffe du kannst das jetzt nachstellen oder brauchst du beispielhaft eine Datei?

**Comment by aschempp** [comment]
Der Mode 2 unterstützt keine Sortierung/Verschiebe-Funktionen. Das geht nur in Mode 4, 5 und 6.

**Comment by Total-Reality** [comment]
Ja weiß ich doch, ich möchte aber, dass es sortierbar gemacht wird. Warum geht das nicht?

**Comment by Toflar** [comment]
Weil es nicht gebaut wurde? :D Contao unterstützt es nicht. Wenn du's brauchst, musst du's selber irgendwie bauen.

**Comment by aschempp** [comment]
Und am besten dann einen Pull-Request stellen damit alle davon profitieren können :-)

**Comment by Total-Reality** [comment]
Ähm wie soll ich ein Pull-Request stellen, wenn ich nicht weiß man das in den Core einbauen soll? 
Ich kann also keinen PR stellen, weil ich keinen geänderten Code habe... und ein Issue kann ich auch nicht stellen, weil das hier abgeschmettert wurde...
Hää? :D Soll hier noch einer durchblicken?

**Comment by aschempp** [comment]
Vielleicht war meine Aussage mit dem Pull-Request etwas unklar. Ich versuche mal meine Ansicht zu formulieren:

Wir drei Core-Entwickler geben der Funktion keine hohe Priorität, weil die Funktion über einen anderen Weg (Mode 5) bereits machbar ist. Falls du das also trotzdem haben möchtest, solltest du dich mit dem Code von Contao beschäftigen, die Funktion einzubauen und danach einen Vorschlag (Pull-Request) für die Umsetzung liefern. Selbstverständlich kannst du auch jemand Drittes finden oder beauftragen der das für dich übernimmt.

**Comment by Total-Reality** [comment]
Okay, das ist dann schon verständlicher ;)
Also ich brauche das ständig und sehe es als wichtig an, weil du nur in mode 2 (1 und 0 wahrscheinlich auch) eine ordentliche tabellarische Übersicht. Bei mode 5 kann ich ja keine Spalten darstellen und außerdem darf ich keine pid haben...

Ich bin fast fertig mit der Umsetzung. Die Änderungen halten sich in Grenzen.
Es betrifft /core/classes/DataContainer.php
Sowie /core/drivers/DC_Table.php
