### ISSUE TITLE
Inhaltselement Tabelle - CSS Klasse beim Speichern gelöscht

### ISSUE THREAD

**Issue by emkayy** [contao/core#7358]
Nach dem Import einer längeren CSV-Datei in das Inhaltselement Tabelle wurde die die CSS Klasse des Inhalt-Elements gelöscht. Auch nach erneutem Eintragen und Abspeichern kann sie nicht wieder eingetragen werden.
Nur mit Hilfe von "Mehrere bearbeiten" in der Listenansicht kann die Klasse wieder gespeichert werden. Beim erneuten Speichern im CE wird diese aber sofort wieder gelöscht.

Contao 3.2.12

**Comment by leofeyer** [comment]
Tritt dieses Problem in Contao 3.5 bzw. 4.4 noch auf?

**Comment by Aybee** [comment]
In ner 3.5.34 tritt dies noch auf. Dies liegt an max_input_vars, welches default auf 1000 steht. D.h. bei ca 5 Spalten und 200 Zeilen müsste dies auftreten.

**Comment by ausi** [comment]
Duplicate of #5954

See also: #7749, #7938, contao/docs#390
