### ISSUE TITLE
Use `<mark>` element in search results

### ISSUE THREAD

**Issue by aschempp** [contao/core#7370]
There's a new HTML5 element to mark highlighted text. https://developer.mozilla.org/en-US/docs/Web/HTML/Element/mark

We could use that in our search results module.

**Comment by leofeyer** [comment]
The tag has been changed to `<strong>` in Contao 4. Is this sufficient or do we need `<mark>`?

**Comment by lionel-m** [comment]
Please use `<mark>` instead of `<strong>`

> The HTML Mark Element (`<mark>`) represents highlighted text, i.e., a run of text marked for reference purpose, due to its relevance in a particular context. For example it can be used in a page showing search results to highlight every instance of the searched-for word.


> Do not confuse the `<mark>` element with the `<strong>` element. The `<strong>` element is used to denote spans of text of importance in context of the text, when the `<mark>` element is used to denote spans of text of relevance to a different context.

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/mark

**Comment by leofeyer** [comment]
Changed in dea1e8d844de52929573facdcb4a5ea3236444cf. Just noticed that Chrome applies a nice default formatting to the `<mark>` element :)

**Comment by Aybee** [comment]
Same for FF 37 :grinning: 
```css
mark {
  background: none repeat scroll 0 0 yellow;
  color: black;
}
```
