### ISSUE TITLE
New forms only check the first user group for access rights

### ISSUE THREAD

**Issue by blackbee** [contao/core#7371]
Hi,

perhaps I found a logical bug in Contao 3.2.x and other Versions, which has to do with Formulars in Contao.

Scenario:
- regular User (not Administrator)
- User has the group rights to create / delete Formulars with the Formulargenerator 
- User creates a new Formular and can edit the new formular in the backend (new Fields, etc)
- User wants to insert the new Formular as an Content-Element somewhere on the Page
  Problem:
  He cannot select the previous created formular (by him or other regular user) in the Article, cause the the formular is not shown in the Inlcude-List of Formulars.

This is caused, because the Formular has to been selected in the Group-Rights for allowed formulars. Otherwhise a regular user cannot select it.

But, why is there a setting for creating / deleting in the rights-management in the backend, where a user can create new formulars on one hand, when he cannot insert them as an Content-Element on the other hand?
So the regular user must ask everytime an Administrator, that he change the group right settings, that the new formular can be accessed in the article contect.

I think this makes not sense and produces unnecessary work.

The code, which cause this problem is here:

`/system/modules/core/dca/tl_content.php`

in function getForms:

`if ($this->User->isAdmin || $this->User->hasAccess($objForms->id, 'forms'))`

Does it make sense to change the If-Clause to something like this?

`if ($this->User->isAdmin || $this->User->hasAccess($objForms->id, 'forms') || USER-HAS-RIGHT-TO-CREATE-FORMULARS)`

At the moment I have to edit the DCA / overwrite the Function by 2 customers, so that regular User can create and insert Formulars without an administrator who edit the group rights everytime.

Cheers Ben

**Comment by leofeyer** [comment]
Es ist richtig, dass nur die Hauptgruppe (nämlich die erste) in diesem Fall herangezogen wird.

Warum das so ist, weiß ich nicht aus dem Stegreif; eventuell gibt es dazu Tickets? Es muss wegen mir auch nicht unbedingt so bleiben.

@contao/developers /cc

**Comment by aschempp** [comment]
Die Gruppe mit den bestehenden Formular-Rechten erweitern erscheint mir auch eher schlüssig… wie ist es denn bei News und Events?

**Comment by blackbee** [comment]
Ich habe gerade mal nachgeschaut, wie es bei den anderen Modulen ist:

**Events (= Calendar),**
dort ist in Version 3.5.9 im DCA tl_calendar.php Zeile 318 ff. der gleiche Code wie bei den Formularen verbaut.

**News,**
dort ist in Version 3.5.9 im DCA tl_news_Archive Zeile 321 ff. der gleiche Code wie bei den Formularen verbaut.

Ich habe mir immer Abhilfe geschaffen bei Formularen, dass ich Kunden Formulare auf "Vorrat" angelegt habe, oder aber bei den Gruppen immer die Gruppe die die Rechte zum Anlegen von Formularen hat, ganz oben steht. Allerdings muss man daran denken.

Bei den News und Kalender Modulen macht es natürlich wie beim Newsletter etwas weniger Sinn oder ist es komplizierter, weil es dort ja die Auflistung- und Reader-Module gibt, die beim Anlegen von Archiven etc. sich nicht automatisch mit verändern.

**Zurück zu den Formularen:**
Im DCA tl_form.php in Version 3.5.9 wird in Zeile 346 ja abgefragt, ob bei dem Benutzer Custom Rechte vergeben sind. Erst wenn das fehl schlägt, dann werden die Gruppen-Rechte abgefragt und ergänzt.

Vielleicht würde es Sinn machen, die "elseif" Bedingung in Zeile 365 raus zu nehmen und die Select-Abfrage in Zeile 367 und die Update-Abfrage in Zeile 378 so zu verändern, dass diese nur die Gruppen aktualisieren, welche das Recht zum Formular Anlegen/Löschen hat.

**Comment by mankra** [comment]
Gibt es hierzu eine Lösung? Wir nutzen momentan Contao 3.4.5 und haben dasselbe Problem: Der Mitarbeiter kann (und soll) Formulare anlegen, hat jedoch keine Adminrechte. Er ist stattdessen in einer Benutzergruppe, die für die Formulare zuständig ist. Legt er ein Formular an, kann er es nicht sehen, bis ein Admin die Rechte entsprechend gesetzt hat. Das nervt.

Wenn das Problem in einer neueren Version behoben ist oder wird, ziehen wir ein Contao-Update in Betracht.

**Comment by leofeyer** [comment]
Geändert in 439c08d08abd51c21631328a67f564599fc54831.

**Comment by aschempp** [comment]
Are you intentionally adding it to all groups now? Because I can't see a break in the while loop when successfully added…

**Comment by leofeyer** [comment]
I am adding it to all groups which grant the "create new …" right. If a group grants the right to create a new calendar, I assume that it also wants the calendar to be accessible.

**Comment by aschempp** [comment]
If that's intended, fine for me. It's just a behaviour change, but it makes sense to me.
