### ISSUE TITLE
Contao 3.2.14 / Platzierung von Login-Modul verursacht permanenten 303 Redirect

### ISSUE THREAD

**Issue by webathlet** [contao/core#7376]
Bei Platzierung eines Login-Modules, erfolgt nach Anmeldung ein permanenter Redirect auf die angegebene letzte Weiterleitungsseite bzw. gleiche Seite. Getestet auch bei abgesichertem Modus unter Contao 3.2.14.

In ModuleLogin.php wird trotz bestehender Anmeldung immer wieder if (\Input::post('FORM_SUBMIT') == 'tl_login') getriggert. Notlösung ist, nur für Gäste sichtbar schalten und eigenen Logout-Button einsetzen mit Weiterleitung auf spezielle Logout-Seite mit verwendetem Modul "Automatischer Logout".

**Comment by leofeyer** [comment]
Wie am 29. Januar auf Mumble besprochen würden beide Lösungsansätze nicht funktionieren. Ich werde mir nochmal genau ansehen, wo das Problem entsteht.

**Comment by aschempp** [comment]
@wola warum baust du denn mit dem Formulargenerator ein Login-Formular, wenn das Login-Formular selber schon auf der Seite ist?

**Comment by wola** [comment]
Es wurde ein einfacher Login benötigt, der nur eine Kennung benötigte und keinen Benutzernamen. Diesen hatte ich dann vorbelegt.

**Comment by wola** [comment]
Nur als weiteren Erfahrungswert dazu. Ähnliche seltsame Effekte mit der Post[FORM_SUBMIT] und SESSION[FORM_DATA] gab es bei Erweiterung oder eben dem Überspielen von hauseigenen Funktionen wie der tl_registration. Meist ergab sich dann mit einem folgenden Hook, dass man nicht korrekt auf die Daten zugreifen konnte bzw. aus unerklärlichen Gründen der Request-Token weg war. Ich kann mich noch erinnern, dass hier auch ein Submit auf die gleiche Seite nicht möglich war und der Submit auf eine Folgeseite mit wiederum gesetztem Registrierungsmodul abgearbeitet werden musste. Behalte ich im Auge und gebe es weiter, wenn das dann auch reproduzierbar und kein Sonderfall ist. Da in diesem Fall "damals" keine Stable-Module (extended_registration etc.) benutzt und manuell auf die 3er-Version angepasst wurde, hielt ich einen Alarm für verfrüht und unnötig.
