### ISSUE TITLE
FR: Variable for calendars

### ISSUE THREAD

**Issue by Anke** [contao/core#7388]
It would be nice to have a variable <code>$this->calendar</code> in order to easily get a calendar's title (equivalent to <code>$this->archive</code> for news archives).

**Comment by leofeyer** [comment]
Implemented in 9ba927233bd3ee7a88f115719a4a67c82df6dd4b.

@Anke @bezin Please check if this works for you.

@bezin I assume you were using `CalendarModel::findByPk($event['parent'])` in your solution?
