### ISSUE TITLE
Sitemaps mit hreflang

### ISSUE THREAD

**Issue by ways2web** [contao/core#7395]
Hi Cimmunity,

ist es möglich das Sitemap -Konzept von Contao ein wenig zu pimpen?
Bei großen multi-language sites ist es mühsam die ganze urls manuell zu pflegen.
Als alternative kann man laut google zb die sitemaps verwenden.

Wenn man mit mehreren Seitenbäumen und fallback-Seite arbeitet, sollten die Daten ja irgendwo abrufbar sein um eine sitemap zu generieren oder? Und x-default könnte ja in den Seitenbäumen gesetzt werden

https://support.google.com/webmasters/answer/2620865?hl=de

**Comment by leofeyer** [comment]
Siehe dazu auch #7699.
