### ISSUE TITLE
FR: Debug Bar actions in plain javascript instead of mootools

### ISSUE THREAD

**Issue by tim-bec** [contao/core#7400]
If you use jquery in your project and activate the debug mode, mootools is loaded to open / hide the debug bar. 
This behaviour took me some time, while i tried to debug my project javascript (jquery). So it would be great to use plain javascript instead of mootools to prevent side effects.

https://github.com/contao/core/blob/master/system/modules/core/library/Contao/Template.php#L343

**Comment by leofeyer** [comment]
Since we are using the Symfony web profiler as of Contao 4, I guess we can close this ticket.
