### ISSUE TITLE
Mitglied Versionen bei Änderung im Frontend mit Modul Persönliche Daten

### ISSUE THREAD

**Issue by Mynyx** [contao/core#7415]
Wenn ein Mitglied, das noch nicht im Backend bearbeitet wurde, das erste Mal im Frontend mit dem Modul Persönliche Daten Änderungen vornimmt, dann steht die ursprüngliche Version vor den Änderungen nicht zur Verfügung, obwohl ein entsprechender Hinweis im Systemlog zu finden ist ("A new version of record "tl_member.id=x" has been created").
Ursache scheint zu sein, dass mit dem Speichern erstmals überhaupt eine Version angelegt wird, während dies im Backend bereits beim Aufruf des Formulars automatisch geschieht.

**Comment by Mynyx** [comment]
> Außerdem legt das Modul Persönliche Daten beim Speichern immer eine neue Version an, auch wenn gar keine Änderungen vorgenommen wurden, während die im Backend nur geschieht, wenn tatsächlich Daten verändert wurden.

Dies ist in der 3.4.2 immernoch der Fall.

**Comment by leofeyer** [comment]
Wie lässt sich das in der Onlinedemo reproduzieren?

**Comment by Mynyx** [comment]
1. http://demo.contao.org/en/login.html einloggen als j.smith
2. http://demo.contao.org/en/my-account.html aufrufen und ohne Änderungen absenden
3. http://demo.contao.org/en/my-account.html nochmals aufrufen und erneut ohne Änderungen absenden
4. http://demo.contao.org/contao/ einloggen als k.jones siehe "Latest changes"

**Comment by leofeyer** [comment]
Behoben in 69c3b25991b7cc30472ab912eda4a80f2e82d8e6.
