### ISSUE TITLE
[3.3.6] Mandatory Passwort-Feld im Frontend ohne required-Attribut

### ISSUE THREAD

**Issue by Mynyx** [contao/core#7418]
Bei einem mandatory Passwort-Feld fehlt im Frontend das required-Attribut z. B. im Registrierungsformular.

**Comment by leofeyer** [comment]
Wie am 26. Februar auf Mumble besprochen, sollte das `required`-Attribut im Registrierungsformular gesetzt sein, da das Passwort hier auf jeden Fall eingegeben werden muss. Im Modul "Persönliche Daten" ist die Eingabe jedoch nicht required, weil da ja schon ein Passwort gesetzt ist.

Wir wollen aber ein neues Modul zur Passwort-Änderung hinzufügen, in dem als zusätzliche Sicherheitsmaßnahme noch das alte Passwort abgefragt wird, bevor ein neues gesetzt werden kann.

**Comment by leofeyer** [comment]
Implementiert in c3b2de619ee3bd774841f7bc59395420434b3073.
