### ISSUE TITLE
[3.3.6] tl_member Beschriftung Spalten lastLogin und currentLogin

### ISSUE THREAD

**Issue by Mynyx** [contao/core#7426]
Die Spalten lastLogin und currentLogin werden im Backend beide mit "Last login"/"Letzte Anmeldung" beschriftet.

Zutreffender wäre "Vorletzte Anmeldung" und "Letzte Anmeldung"?

**Comment by leofeyer** [comment]
Behoben in 813799e548fb0c284ee13d6465dc8a79c679e89d.
