### ISSUE TITLE
Clicking on diff for an deleted object leads to an error

### ISSUE THREAD

**Issue by amenk** [contao/core#7429]
Steps to reproduce (in the backend)

1. Create object (for example news entry)
2. Delete the object
3. There appears an entry on the main page
4. Click the diff icon
5. An error is shown

**Comment by amenk** [comment]
I still can reproduce it but with slightly different steps:

Steps to reproduce (in the backend)

1. Create object (for example news entry)
2. Click to times on the Publish-Eye-Icon
3. Delete the object
4. There are two entries on the main page
5. Click the diff icon
6. An error is shown

Isn't it another bug that the news entry does not show before publishing/un-publishing it?

**Comment by amenk** [comment]
Contao tries to read the news entry which is non-existent anymore, see `system/modules/news/dca/tl_news.php:535` One options would be to just hide the diff button for deleted objects.

**Comment by leofeyer** [comment]
Fixed in 3ccaddfbf4482faa305fdb50b2bb73d65ebfd05f.
