### ISSUE TITLE
Teilweise signifikante Verbesserung der SQL-Leistung durch kleine Code-Anpassung in Models und DCA

### ISSUE THREAD

**Issue by KaiserCh** [contao/core#7450]
Im gesamten Core-Code und quasi jeder Erweiterung wird auf ein einheitliches Schema hinsichtlich der DB-Abfragen zurückgegriffen. Felder wie "published" oder "start/stop" werden bei quasi jeder Anfrage, egal ob an Seiten, Artikel, Content Elements, News,... mit gefiltert. Dazu kommen bei News & Events noch die Sortierung nach der Zeit und Filterung nach Highlight-Events/News.
Keines dieser Felder hat aber einen SQL Index.

Bei Seiten mit relativ wenig Durchsatz und einer überschaubaren Inhaltsfülle macht sich das noch nicht negativ bemerkbar. Ich habe die letzten Monate an einer Seite gearbeitet, die pro Monat einige hundert News veröffentlicht und wirklich einiges an Requests abhalten muss.

Was mir bei der Untersuchung gewisser Performance-Probleme aufgefallen ist:
1.) keine Indizes auf Spalten, nach denen immer sortiert und gefiltert wird. 
2.) Start/Stop haben eine zu hohe Präzision in den Abfragen. Obwohl nur minutengenau im Backend gewählt werden kann, wird im Query sekundengenau gesucht. Das verhindert den sinnvollen Einsatz des Query Caches. Statt der aktuellen Lösung "start < $time", wobei $time = time() wäre es sinnvoller, $time vorher per Modulo auf volle Minuten zu runden. Somit hat man dieselbe Präzision wie im Backend angegeben, dafür aber zumindest für eine Minute den Query Cache der DB zur Verfügung. Bei hohem Traffic eine kräftige Erleichterung.
3.) Selbst wenn Indizes gesetzt werden, wird nur bei den Integer-Spalten wie "time" (News & Events) korrekt gefiltert. Alle anderen Spalten, wie published sind vom Typ Char(1). Die in PHP zusammen gebauten Queries lauten z.B. WHERE published = 1. Korrekt wäre aber: WHERE published = '1'. MySQL macht hier einen großen Unterschied.  =1 wäre eine Integer-Prüfung, der Index liegt aber auf einer Char-Spalte. Kein Index möglich. = '1' hingegen ist kompatibel mit dem Index. 

Die Änderungen an den Queries lassen sich leicht mit ein paar EXPLAIN SELECT überprüfen. 

Nachdem ich tl_news und ein selbst geschriebenes News Model mit obigen Korrekturen versehen habe, sanken die Seitenladezeiten spürbar. Die reine Query-Laufzeit hat sich in etwa halbiert.

Betroffen sind vornehmlich Models (findBy - Funktionen) und der DCA, aber auch manche Module (z.B. die News Liste) verwenden die für den Index falsche Typisierung.

**Comment by KaiserCh** [comment]
Ich möchte noch ein paar Code-Schnipsel nachliefern, die sich in den letzten Wochen so ergeben haben und die mit wenig Aufwand teilweise echt interessante Wirkung zeigen:

Quasi überall wird tl_content eingebunden, bei großen Seiten eine gewaltige Tabelle. Folgender mehrspaltiger Index erhöht bei großen Seiten die Effizienz der Standard-Queries (\ContentModel::findPublishedByPidAndTable(...)):
`$GLOBALS['TL_DCA']['tl_content']['config']['sql']['keys']['pid,ptable,invisible,sorting'] = 'index'; `
Dieser Key kann theoretisch sogar den regulären Key auf "pid" ablösen, da Mehrfach-Keys so oder so von links nach rechts erfüllt werden.

Zur bereits angesprochenen Start/Stop-Problematik kann man die Start/Stop-Felder auf int(10) NULL ändern, wobei NULL der nicht gesetzte Zeitpunkt ist (analog zu "" jetzt). Dazu braucht es im DCA noch einen Hook für Load & Save, um kompatibel zum aktuellen Datums-Wizard zu bleiben.
```
public function saveStartStop($varValue, \DataContainer $dc) {
        if($varValue == "") {
            $varValue = NULL;
        }
        return $varValue;
    }

public function loadStartStop($varValue, \DataContainer $dc) {
        if($varValue == NULL) {
            $varValue = "";
        }
        return $varValue;
} 
```

In Models (und Modulen), bei denen dann Elemente in Abhängigkeit von Start/Stop geladen werden, muss die passende Zeile etwas geändert werden.
Beim \NewsModel::findPublishedByPids() würde das dann in etwa so aussehen.
```
if (!BE_USER_LOGGED_IN || TL_MODE == 'BE') {
            $time = time();
            $arrColumns[] = "($t.start IS NULL OR $t.start<=".($time-$time%60).") AND ($t.stop IS NULL OR $t.stop>".($time-$time%60+60).") AND $t.published='1'";
} 
```
Hier ist die früher angesprochene 60-Sekunden-Rundung für besseres Query Caching bereits mit drin. Die Vergleiche gegen Integer und NULL sind schneller als gegen die bestehenden Varchars und ein potentiell im Einsatz befindlicher Index wäre deutlich kleiner.

**Comment by leofeyer** [comment]
@KaiserCh Die Änderung des Feld-Typs wäre jedoch ein BC-Break und daher erst in Contao 4 möglich. Würde die 60-Sekunden-Rundung nicht auch ohne die Typ-Änderung greifen?

**Comment by KaiserCh** [comment]
Ja, natürlich. Die Rundung bringt immer etwas für den Query Cache. Es wäre dann nur eben zusätzlich sinnvoll, den Datentyp (varchar()) korrekt im Query zu beachten. Aktuell wird im Query ja auf $t.start=$time geprüft, wobei MySQL jetzt start als Integer behandelt, obwohls eine Varchar-Spalte ist. Es müsste im Query also $t.start='$time' heißen.
Das würde den optionalen Einsatz von Indizes auf Start/Stop ermöglichen, z.B. in Form eines mehrspaltigen Index.
Bei tl_news wäre das, wenn ich mich nicht irre, ein mehrspaltiger Index über (id, pid, alias, start, stop, published) sinnvoll. Evtl. wären hier auch mehrere mehrspaltige Indizes möglich, z.B. ein weiterer über (pid, date, start, stop, published, featured). Der dürfte NewsModel::findPublishedByPids() beschleunigen. Da "featured" nicht zwingend im Frontend-Query vor kommt (während start/stop/published nur in der Admin-Vorschau ignoriert wird), sollte die Spalte ans Ende des Multi-Index.

Eine Sache ist mir kürzlich noch aufgefallen im News-System, genauer gesagt in der Parser-Funktion parseArticle(): Wenn man eine News-Liste darstellt, wird trotzdem für jeden Eintrag direkt der jeweilige Content in $objTemplate->text  geladen. Da die meisten News-Listen den Content nicht benötigen, sondern eher einen Teaser (oder nur den Titel) anzeigen, wird hier auch Leistung verbraten. Auf der Startseite von contao.org sind das z.B. im Fuß 2x5 überflüssige Queries für das Sammeln der CTE.
Besser wäre an der Stelle, im NewsList-Modul eine Checkbox einzubauen, durch die der Administrator dieses Nachladen abschalten kann. Hier kann entweder ein Checkbox-Feld mit Default auf "1" genutzt werden, durch das in parseArticle() im Falle von !="" erst die Content Elements geladen werden, oder eine Checkbox mit Default "" wird dazu benutzt, dass im Parser bei ="1" die Content Elements nicht geladen werden. 

Ich vermute, ich werde noch viele Sachen am News-System finden. Ich bin wahrscheinlich der erste Bekloppte, der Contao mit weit über 100 teils sehr umfangreichen News pro Monat füttern lässt...

**Comment by fritzmg** [comment]
Checkbox für's Artikel laden klingt gut :+1: 

Und ich glaube du bist nicht der erste bekloppte :D (oder zumindest nicht der einzige). Ich hab mir das News System auch schon mal durchgesehen und ein wenig analysiert, was passiert, wenn man 10000e News Einträge hat und der Speicher am Server deswegen ausgeht. Siehe https://community.contao.org/de/showthread.php?52268-Newsarchiv-mit-%FCber-10-000-Eintr%E4gen-sprengt-Speicher

**Comment by leofeyer** [comment]
> Aktuell wird im Query ja auf $t.start=$time geprüft, wobei MySQL jetzt start als Integer behandelt, obwohls eine Varchar-Spalte ist. Es müsste im Query also $t.start='$time' heißen.

Genau genommen prüfen wir auf `$t.start>$time` und bei größer gleich wäre es nicht korrekt `$time` in Anführungszeichen zu setzen, oder? Sollten wir hier stattdessen einen Int-Cast einbauen?

**Comment by aschempp** [comment]
Wirklich korrekt wäre eigentlich eine INT-Spalte mit Standard `NULL`?

**Comment by leofeyer** [comment]
Siehe dazu https://github.com/contao/core/issues/7450#issuecomment-83537208.

**Comment by leofeyer** [comment]
Ich habe angefangen die Vorschläge in #7710 umzusetzen.

@KaiserCh Bitte schau mal, ob das alles so stimmt.

@all Ich habe diverse `FIXME`-Tags an Stellen eingefügt, wo ein kombinierter Index Sinn machen würde, ich es aber nicht geschafft habe, einen zu definieren, den MySQL auch anschließend verwendet hat.

**Comment by Samson1964** [comment]
> Ich vermute, ich werde noch viele Sachen am News-System finden. 
> Ich bin wahrscheinlich der erste Bekloppte, der Contao mit weit über 100 teils sehr 
> umfangreichen News pro Monat füttern lässt...
Nein, bist Du sicher nicht. Ich schaffe zwar keine 100 News im Monat, aber auf insgesamt knapp 10.500 Datensätze in tl_news komme ich trotzdem im Laufe der Jahre. Die Geschwindigkeit ist soweit okay, allerdings darf ich dann keine Performancefresser wie die Fremderweiterung tags installieren. Die ist für soviel Datensätze nicht ausgelegt.

**Comment by KaiserCh** [comment]
@leofeyer 
Der Teil mit den Rundungen passt nicht ganz. Es wäre besser, bei stop noch 60 Sekunden aufzuschlagen wie in meinem obigen Code. Ansonsten kriegt man n heftigen Rundungsfehler und die Stop-Zeit geht ne ganze Minute falsch.
Was den Int-Cast angeht: Da kannst du, so wie ich das sehe, nichts casten. Die Spalten sind ja aktuell Varchars, also muss hier eben auch ein Char-Vergleich ran. Tatsächlich funktioniert $t.start > 'tstamp als String' wunderbar, man kann MySQL sogar dazu überreden, es als Index zu akzeptieren. Meist gewinnt aber die höhere Kardinalität von Spalten wie pid, published,...

Schade, dass man Toggle-Spalten wie Published nicht ohne extremen Stress auf was passenderes als Varchar ändern kann. Tinyint(4) wäre cool (mangels Boolean in MySQL), spart viel Platz, gerade bei Indizes. Aber das ballert das halbe Backend-JavaScript auseinander.

Was die FIXMEs für die kombinierten Indizes angeht: Manchmal müssen hier Queries auch noch etwas in ihrer Reihenfolge angepasst werden. Ich bin mir nicht vollkommen sicher, dass der MySQL Query Optimizer auch wirklich alles automatisch umsortiert, bis es auf einen Multi-Index passt. 
Wenn MySQL Indizes manchmal partout nicht nutzen will, kann das auch einfach daran liegen, dass zu wenig Inhalt vorhanden ist. Bei ner Tabelle mit nur nem Dutzend Einträge oder so entscheidet MySQL gern mal, dass ein Table Scan immer noch performanter ist, als sich erst durch die Indizes zu wühlen. Im Zweifel kann man zu Testzwecken auch immer noch ein USE INDEX oder gar FORCE INDEX in den Query bauen. 
In allen Tabellen, die jetzt einen Multi-Index mit "pid" als erstes Element erhalten, sollte der reine Index auf pid übrigens weg. Der Multi-Index übernimmt die Aufgabe komplett.

Für die fehlenden Indizes: Spalten wie ID oder Alias sollten immer als einzelne Indizes existieren und nicht in die Mehrspaltigen rein. Hier ist die Kardinalität maximal, besser wirds nicht. Bei Alias müsste man vor allem mal prüfen, ob ein Unique-Index möglich ist. Wird wahrscheinlich Probleme beim Anlegen von Objekten verursachen, da ist der Alias kurz leer. Würde etwas Platz sparen und schneller sein.

- für tl_faq würde ich aus der Kalten "pid, published, sorting" vorschlagen. 
- für tl_article: "pid, start, stop, published, sorting", wobei man sich über start/stop jetzt noch streiten könnte. 

Queries im Vorschaumodus, für die Start/Stop/Published nicht genutzt werden und die Indizes dann nicht perfekt greifen, kann man hinsichtlich der Performance getrost ignorieren.

**Comment by leofeyer** [comment]
@KaiserCh Ich habe alles entsprechend angepasst (siehe #7710). Bitte schau mal hier:

https://github.com/contao/core/blob/feature/db-optimization/system/modules/core/dca/tl_page.php#L47

Kann der Index über die Spalte `type` weg?

**Comment by leofeyer** [comment]
Implementiert in 573b4b67a4d2c3a8f3fd28ace1a34392c1675ae6.
