### ISSUE TITLE
Form module : Copy of email + newsletter subscription

### ISSUE THREAD

**Issue by fixounet** [contao/core#7454]
Add two features:

- A visitor complete a form, when sending, add a parameter allowing the visitor to receive a copy of the email and / or an email (not just a notification on the web page !) indicating that the success email has been sent. Make this customizable option in the BE.

- Submit the form (eg : contact form) a checkbox allowing the visitor to subscribe to the newsletter. Added information directly in the newsletter module. Make this customizable option in the BE.

Thanks !

**Comment by leofeyer** [comment]
?
