### ISSUE TITLE
Seitencache ignoriert Cache-Einstellung

### ISSUE THREAD

**Issue by dmolineus** [contao/core#7455]
Man kann ja unter Systemeinstellungen die Die Anweisung setzen, dass nur der Servercache verwendet werden soll. Leider ignoriert Contao diese Einstellung, wenn eine Seite aus dem Cache kommt. Dort wird das "no-store must-revalidate" Flag nicht gesetzt.

[Ausgabe einer ungecachten Seite](https://github.com/contao/core/blob/16d1d433c7f12410727b8f976ea4fd587e37b783/system/modules/core/classes/FrontendTemplate.php#L252) vs. [Ausgabe gecachte Seite](https://github.com/contao/core/blob/aa700cc155574813f57f312dce34a6ef9134b0c3/index.php#L418).

HTTP Response Header gecachte Seite:
```
HTTP/1.1 200 OK
Date: Wed, 19 Nov 2014 10:54:45 GMT
Server: Apache/2.2.22
X-Powered-By: PHP/5.4.16
Vary: User-Agent,Accept-Encoding
Cache-Control: no-cache, pre-check=0, post-check=0
Expires: Fri, 06 Jun 1975 15:10:00 GMT
Pragma: no-cache
Set-Cookie: ****
Last-Modified: Wed, 19 Nov 2014 10:54:45 GMT
Connection: close
Content-Type: text/html; charset=utf-8
```
HTTP Response Header ungecachte Seite:
```
HTTP/1.1 200 OK
Date: Wed, 19 Nov 2014 10:54:59 GMT
Server: Apache/2.2.22
X-Powered-By: PHP/5.4.16
Cache-Control: no-store, no-cache, must-revalidate, post-check=0, pre-check=0
Pragma: no-cache
Expires: Fri, 06 Jun 1975 15:10:00 GMT
Vary: User-Agent,Accept-Encoding
Set-Cookie: ****
Set-Cookie: ****
Set-Cookie: ****
Last-Modified: Wed, 19 Nov 2014 10:54:59 GMT
Connection: close
Content-Type: text/html; charset=utf-8
```

**Comment by leofeyer** [comment]
Fixed in a83ff5bef48c15f9852d4ddfc89976781e78eb64.
