### ISSUE TITLE
Hook modifyFrontendPage und gecachte Seiten

### ISSUE THREAD

**Issue by dmolineus** [contao/core#7457]
Der modifyFrontendPage Hook wird momentan nach dem Cachen einer Seite ausgeführt. Dies führt dazu, dass er nur auf ungecachte Seiten angewandt. Die Ausgabe einer gecachten Seite kann man leider nicht damit beeinflussen.

Es wäre wünschenswert, dass der Hook entweder vor dem Cachen angewandt wird. Alternativ wäre es wünschenswert, dass er innherlab `Controller::outputFromCache` vor der Ausgabe getriggert wird.

Der outputFrontendTemplate Hook ist mir noch zu früh, da ich den Output-Buffer inklusive gesetzten JS/CSS Dateien benötige.

**Comment by leofeyer** [comment]
?

**Comment by dmolineus** [comment]
Ich benötige einen Hook um an den HTML-Output einer Seite zu kommen, wenn die Platzhalter für JS/CSS bereits ersetzt sind. Wird die Seite nicht gecacht, so bietet mir der `modifyFrontendPage` die Möglichkeit dafür.

Da dieser jedoch erst ausgeführt wird, nachdem die Seite in den Seitencache geschrieben wird und bei gecachten Seiten nicht getriggert wird, greift dieser Hook bei gecachten Seiten nicht. 

Zwei mögliche Lösungen:
 - Den Hook **vor** dem Cachen des Seiteninhalts aufrufen
 - Den Hook auch triggern, wenn die Seite aus dem Cache kommt

**Comment by leofeyer** [comment]
Geändert in 3f17549e7df43f4cad4920c62d168ceebb73b113. Bitte schau, ob das so für Dich funktioniert, und gib uns dann ein kurzes Feedback.

**Comment by dmolineus** [comment]
Works fine.

**Comment by leofeyer** [comment]
:+1:

**Comment by kartoffelheinz** [comment]
It would be super nice to have this also fixed in the 3.2 branch. We rely on a modifyFrontendPage hook to provide retina image functionality there. Works just fine with caching disabled, but that makes for slower page loads.

**Comment by Zeromax** [comment]
@kartoffelheinz https://contao.org/de/release-plan.html

**Comment by kartoffelheinz** [comment]
Well, there are certainly a lot of installation which cannot that easily be upgraded (or not in short time) and will need the whole transition phase. For me, in-transition also does _not_ mean that there will be no bugfixes. There might be a misunderstanding on my side here though.

So, while 3.2 is still in transition, I would really appreciate backport for this bugfix.

**Comment by BugBuster1701** [comment]
Das es die FrontendIndex.php in der 3.2 nicht gibt, versuche mal das:
nehme diese Zeilen: https://github.com/contao/core/blob/develop/system/modules/core/controllers/FrontendIndex.php#L456-L464
und baue die hier ein in die index.php https://github.com/contao/core/blob/3.2.21/index.php#L393

**Comment by Zeromax** [comment]
> Transition: Transition time between two LTS versions. Only security-relevant updates are provided.

Is this a security critical issue?
