### ISSUE TITLE
FR: LTS Version as only demo

### ISSUE THREAD

**Issue by tim-bec** [contao/core#7468]
During the "github basic" session on the camp, we run into the problem that the online demo is just available in the current version, but many people use the LTS Version. So "how can we reproduce in the online demo" wouldn't fit to all tickets. Would be great to get a online demo for LTS to.

**Comment by may17** [comment]
It looks like this ticket could be closed. The COD for Contao 3.2. is released since february :)

**Comment by leofeyer** [comment]
@may17 That's not what @tim-bec means. He wants to have demo32.contao.org :)
