### ISSUE TITLE
Kommentar E-Mail intelligenter gestallten -> Status 'Moderiert' überprüfen

### ISSUE THREAD

**Issue by MacKP** [contao/core#7478]
Wenn man eine E-Mail bekommt bei einem neuen Kommentar steht aktuell unten drunter:

'Wenn Sie Kommentare moderieren, müssen Sie sich im Backend anmelden und den Kommentar veröffentlichen.'

Es wäre schön, wenn man den Status abfragt und dann explizit hinschreiben würde das die Kommentare moderiert sind und man den freischalten muss. Im Falle von nicht moderiert brauch dieser Satz gar nicht angezeigt werden (nur ein Link zum Bearbeiten).

Viele Grüße

**Comment by leofeyer** [comment]
Implementiert in contao/comments-bundle@eeca3d59c7aba86eeb633e4c393c541fe578da50.
