### ISSUE TITLE
Also export/import table tl_files in theme export/import

### ISSUE THREAD

**Issue by leofeyer** [contao/core#7480]
See #7465.

**Comment by leofeyer** [comment]
@ausi I have added some comments to your initial PR (see #7465).

**Comment by leofeyer** [comment]
As discussed on Mumble on April 21st, we want to revert the changes to @ausi's original logic.

**Comment by leofeyer** [comment]
@ausi Please review https://github.com/contao/core/compare/develop...feature/export-file-paths

**Comment by ausi** [comment]
@leofeyer LGTM

**Comment by leofeyer** [comment]
Merged in c03b588dcee6ce23f7effa0ff5a5f77863b34a30 then.
