### ISSUE TITLE
CSS Export remove remark sign by mistake

### ISSUE THREAD

**Issue by magicsepp** [contao/core#7482]
Hallo Leo,
enthält ein Css Eintrag ein Kommentar mit ```/* Kommentar */``` in Contao 3.4.0
wird im Export File das /* und */ durch die Funktion compileDefinition im StyleSheetes.php heraus replaced.
Ursache ist $blnWriteToFile in Zeile 1399 wird als false von exportStyleSheet() gesetzt. (Ursache)
Beim Export sollte der Kommentar als solches erhalten bleiben.

**Comment by leofeyer** [comment]
Behoben in 5790f36728904038c21f3a7d67c4047a0b6fbd25.
