### ISSUE TITLE
replaceDynamicScriptTags Hook und Server Cache Contao 3.4

### ISSUE THREAD

**Issue by bruc13** [contao/core#7487]
Hi,
Ich wollte die kombinierte JS-Datei ins Body versetzen. Dafür diesen Hook genommen, klappt auch alles gut, wenn ich Cache ausschalte. Ich habe einfach den aus der Controller.php genommen und wollte dann das $GLOBALS['TL_JAVASCRIPT']; leeren, damit der Dazugehörige Teil nicht in Controller .php noch mal ausgeführt wird (nach dem Hook). Leider bekommt man dann beim 1 Aufruf der Seiten keien JS Datei, nur beim 2 Aufruf. Wenn ich die $GLOBALS['TL_JAVASCRIPT'] nicht leere, dann geht es auch beim 1 Aufruf. 
Code:

``` php
public function MoveToBody($strBuffer)
    {


    $arrReplace = array();
    $strScripts = '';
        // Add the internal scripts
        if (!empty($GLOBALS['TL_JAVASCRIPT']) && is_array($GLOBALS['TL_JAVASCRIPT']))
        {
            $objCombiner = new \Combiner();
            $objCombinerAsync = new \Combiner();

            foreach (array_unique($GLOBALS['TL_JAVASCRIPT']) as $javascript)
            {
                $options = \String::resolveFlaggedUrl($javascript);

                if ($options->static)
                {
                    if ($options->async)
                    {
                        $objCombinerAsync->add($javascript, filemtime(TL_ROOT . '/' . $javascript));
                    }
                    else
                    {
                        $objCombiner->add($javascript, filemtime(TL_ROOT . '/' . $javascript));
                    }
                }
                else
                {
                    $strScripts .= \Template::generateScriptTag(static::addStaticUrlTo($javascript), $blnXhtml, $options->async) . "\n";
                }
            }

            // Create the aggregated script and add it before the non-static scripts (see #4890)
            if ($objCombiner->hasEntries())
            {
                $strScripts = \Template::generateScriptTag($objCombiner->getCombinedFile(), $blnXhtml) . $strScripts;
            }

            if ($objCombinerAsync->hasEntries())
            {
                $strScripts = \Template::generateScriptTag($objCombinerAsync->getCombinedFile(), $blnXhtml, true) . "\n" . $strScripts;
            }
        }
    $arrReplace['[[TL_BODY_JS]]'] = $strScripts;
    // Add the internal <head> tags
    $strScripts = '';
        if (!empty($GLOBALS['TL_HEAD']) && is_array($GLOBALS['TL_HEAD']))
        {
            foreach (array_unique($GLOBALS['TL_HEAD']) as $head)
            {
                $strScripts .= trim($head) . "\n";
            }
        }
        $arrReplace['[[TL_HEAD]]'] = $strScripts;
        //$GLOBALS['TL_HEAD'] = array();
        //$GLOBALS['TL_JAVASCRIPT'] = array();
        return str_replace(array_keys($arrReplace), array_values($arrReplace), $strBuffer);
    }


    public function hookParseTemplate(Template $template)
    {
        if ($template instanceof FrontendTemplate) {
            if (substr($template->getName(), 0, 3) == 'fe_') {

                $template->mootools = '[[TL_BODY_JS]]' . $template->mootools;
            }
        }

```

Wollte dann diesen Hook nutzen (für str_replace), scheint aber das es beim Cache auch nicht geht.
https://github.com/contao/core/issues/7457

**Comment by leofeyer** [comment]
Kann das irgendjemand reproduzieren?

**Comment by markusmilkereit** [comment]
Ich hab auch ein entsprechendes Modul im Einsatz, das die kombinierten CSS und Javascript-Dateien über den Hook replaceDynamicScriptTags an anderer Stelle in der Seite einbauen will - sobald der Cache aktiv ist klappt das nicht mehr - die kombinierten Dateien werden nicht eingebunden. Aktuell läuft die Seite nur mit Cache = 0 Sekunden fehlerfrei. 

Aktueller Stand von meinem Entwicklungs-Contao ist 3.5.3 - ich mach gerade mal ein Update auf die aktuellste Version und geh dem Problem dann auf den Grund.

**Comment by fritzmg** [comment]
The double replacement of the script tags also causes this problem in netzmacht/contao-theme-plus#83

**Comment by bytehead** [comment]
Hätte hier sonst noch eine Extension, die genau das macht: https://github.com/1up-lab/contao-j2b :)

**Comment by davidmaack** [comment]
Yes, theme-plus has the same problem. I´m wondering why it is neccessary to trigger this hook twice? This might result in different outputs for the current and the cached version of a page. For example if an inserttag is counting something or resetting Session-Data (I´know strange setting but cant think of an better example right now ;))

**Comment by leofeyer** [comment]
Die Lösung wäre vermutlich, die Platzhalter nicht zu ersetzen, wenn die Cache-Datei geschrieben wird. Stattdessen müssten wir `replaceDynamicScriptTags()` aufrufen, wenn wir eine Cache-Datei laden.

@contao/developers /cc

**Comment by Toflar** [comment]
> Die Lösung wäre vermutlich, die Platzhalter nicht zu ersetzen, wenn die Cache-Datei geschrieben wird. Stattdessen müssten wir replaceDynamicScriptTags() aufrufen, wenn wir eine Cache-Datei laden

Ich hab das Problem noch nicht wirklich verstanden, aber das was du machen möchtest, halte ich für falsch. Die Tags werden beim regulären Output ersetzt und somit auch der Hook ausgeführt. Das ist das HTML was dann in den Seitencache von Contao geht (oder gehen sollte). Warum muss der Hook überhaupt ausgeführt werden, wenn das gecachte HTML ausgeliefert wird?

**Comment by Toflar** [comment]
Ach so, jetzt seh ich das Problem. Meiner Meinung nach müsste  `replaceDynamicScriptTags()` nur 1x ausgeführt werden und zwar bevor `addToCache()` ausgeführt wird.

**Comment by leofeyer** [comment]
Das könnte auch gehen :)

**Comment by markusmilkereit** [comment]
Wenn der Hook direkt vor `addToCache()` ausgeführt wird könnte er auch gespart werden, weil genau da sitzt der Hook `outputFrontendTemplate` - die beiden Hooks haben vermutlich unterschiedliche Ideen und Einsatzszenarien dahinter gehabt. Wahrscheinlich müsste `replaceDynamicScriptTags()` sogar später kommen und aus der Funktion  `addToCache()` raus und in die Funktion 'outputFromCache()' rein. Dann wird die Logik immer direkt vor der Ausgabe des HTML verwendet, egal ob es aus dem Cache kommt oder nicht (anders als outputFrontendTemplate - dessen Ergebnis gecacht wird).

**Comment by Toflar** [comment]
Mit vielen Hooks kann erreicht werden, was mit anderen auch irgendwie ginge. Das ist nicht wirklich ein Argument. :) Das was du willst (immer ausgeführt werden) macht der `modifyFrontendPage` Hook. Der `replaceDynamicScriptTags` muss **vor** dem Cachen ausgeführt werden, dann ist alles so wie's sein sollte. :)

**Comment by davidmaack** [comment]
@markusmilkereit  `replaceDynamicScriptTags` ist ja mehr als nur ein Hook :)

Ich sehn das wie Toflar, die Funktion gehört VOR dem Aufruf von `addToCache` aufgerufen - der Aufruf innerhlab von `addToCache` kann damit entfallen.

Im Prinzip müsste also nur der Block https://github.com/contao/core/blob/master/system/modules/core/classes/FrontendTemplate.php#L100 VOR den Aufruf von `addToCache` geschoben werden, der Block bei https://github.com/contao/core/blob/master/system/modules/core/classes/FrontendTemplate.php#L246 kann dann entfallen.

Oder übersehen wir hier irgendwelche Seiteneffekte?

**Comment by leofeyer** [comment]
> Oder übersehen wir hier irgendwelche Seiteneffekte?

Ja, zum Beispiel diesen hier: https://github.com/contao/core/issues/4203#issuecomment-5297906

> Ich habe z. B. in einem Artikel ein Modul zur Darstellung eines Sliders. Dort läuft der Slider sauber. Wenn ich nun hergehe und in einem anderen Artikel (auf einer anderen Seite) diese Slider-Instanz via Insert-Tag aufrufe, läuft der Slider dort nicht, da das zugehörige JavaScript im Header auf dieser anderen Seite nicht automatisch eingebunden wird.

Die Skript-Tags dürfen daher erst *nach* den Inserttags ersetzt werden.

**Comment by leofeyer** [comment]
Was spricht dagegen, die Skript-Tags im der Cache-Datei nicht zu ersetzen und dafür in der `outputFromCache()` nochmal `replaceDynamicScriptTags()` aufzurufen?

**Comment by Toflar** [comment]
Naja, je mehr wir nachträglich auf dem gecachten HTML rumwerkeln bevor es ausgeliefert wird, umso mehr stellt sich die Frage, wie sinnvoll dieser Cache überhaupt ist. Das er in der Form schlecht ist, wissen wir, aber ich meine die aktuelle Implementierung jetzt.

Was ist damit?

```diff
diff --git a/system/modules/core/classes/FrontendTemplate.php b/system/modules/core/classes/FrontendTemplate.php
index ecaef99..8b2164b 100644
--- a/system/modules/core/classes/FrontendTemplate.php
+++ b/system/modules/core/classes/FrontendTemplate.php
@@ -90,16 +90,18 @@ class FrontendTemplate extends \Template
 			}
 		}
 
+		// Replace insert tags and dynamic tags
+		$this->strBuffer = $this->replaceInsertTags($this->strBuffer);
+		$this->strBuffer = $this->replaceDynamicScriptTags($this->strBuffer); // see #4203
+
 		// Add the output to the cache
 		$this->addToCache();
 
 		// Unset only after the output has been cached (see #7824)
 		unset($_SESSION['LOGIN_ERROR']);
 
-		// Replace insert tags and then re-replace the request_token tag in case a form element has been loaded via insert tag
-		$this->strBuffer = $this->replaceInsertTags($this->strBuffer, false);
+		/// Re-replace the request_token tag in case a form element has been loaded via insert tag
 		$this->strBuffer = str_replace(array('{{request_token}}', '[{]', '[}]'), array(REQUEST_TOKEN, '{{', '}}'), $this->strBuffer);
-		$this->strBuffer = $this->replaceDynamicScriptTags($this->strBuffer); // see #4203
 
 		// HOOK: allow to modify the compiled markup (see #4291)
 		if (isset($GLOBALS['TL_HOOKS']['modifyFrontendPage']) && is_array($GLOBALS['TL_HOOKS']['modifyFrontendPage']))

```

**Comment by davidmaack** [comment]
> Oder übersehen wir hier irgendwelche Seiteneffekte?
Ja, zum Beispiel diesen hier: #4203 (comment)

Das Ticket hatte ich schon gesehen, daher der Vorschlag den kompletten Codeblock (Zeile 100-102) zu verschieben. Damit würde `replaceDynamicScriptTags` immer noch **nach** `replaceInsertTags` aufgerufen.

> Was spricht dagegen, die Skript-Tags im der Cache-Datei nicht zu ersetzen und dafür in der outputFromCache() nochmal replaceDynamicScriptTags() aufzurufen?
Ja, es gibt bei dem `outpuFromCache()` kein Page-Objekt und damit kein outputformat...

**Comment by leofeyer** [comment]
@davidmaack Wohin soll der Block verschoben werden?

**Comment by davidmaack** [comment]
Naja direkt vor  `addToCache()`, also eigentlich ziemlich genau dass, was Toflar in seinem Diff gemacht hat. Das ersetzen des Request-Tokens darf natürlich nicht verschoben werden, da hat Toflar etwas besser aufgepasst als ich ;)

**Comment by leofeyer** [comment]
Das würde aber alle Inserttags bereits vor dem Cache ersetzen, auch die "cachbaren". Der Aufruf in der `addToCache()` lässt ja Tags wie `{{date::Y}}` oder `{{irgendwas|uncached}}` bestehen, damit diese erst beim Laden aus dem Cache ersetzt werden.

**Comment by Toflar** [comment]
Deswegen enthält mein Code-Vorschlag den zweiten Parameter `false` bei `replaceInsertTags()` nicht.

**Comment by leofeyer** [comment]
Ja, aber Dein Code enthält auch keinen Aufruf mehr, der die cachbaren Inserttags vor der Ausgabe der Seite ersetzt. :)

**Comment by Toflar** [comment]
Stimmt, hab nur den cache-Fall berücksichtigt. Der müsste dann noch mit einem `false` aufgerufen werden. Ausserdem ist auch das  `str_replace()` für den Request Token überflüssig. Macht doch InsertTags eh automatisch.

**Comment by leofeyer** [comment]
Darauf würde ich mich jetzt nicht unbedingt verlassen. Der Code ist ja aus irgendeinem Grund da :)

**Comment by leofeyer** [comment]
Aber ja, eigentlich schon.

**Comment by Toflar** [comment]
> Der Code ist ja aus irgendeinem Grund da :)

Ich hab ihn nie verstanden und bei keinem eigenen Entry Point jemals benutzt :)

**Comment by Toflar** [comment]
Ach so. Doch, das ist weil InsertTags in Contao 3.5 nicht rekursiv sind, sondern nur 1 Level-Nesting unterstützen.

**Comment by leofeyer** [comment]
Das kann gut sein.

**Comment by Toflar** [comment]
Updated:

```diff
diff --git a/system/modules/core/classes/FrontendTemplate.php b/system/modules/core/classes/FrontendTemplate.php
index ecaef99..b380477 100644
--- a/system/modules/core/classes/FrontendTemplate.php
+++ b/system/modules/core/classes/FrontendTemplate.php
@@ -90,16 +90,21 @@ class FrontendTemplate extends \Template
 			}
 		}
 
+		// Replace cacheable insert tags and dynamic tags
+		$this->strBuffer = $this->replaceInsertTags($this->strBuffer);
+		$this->strBuffer = $this->replaceDynamicScriptTags($this->strBuffer); // see #4203
+
 		// Add the output to the cache
 		$this->addToCache();
 
 		// Unset only after the output has been cached (see #7824)
 		unset($_SESSION['LOGIN_ERROR']);
 
-		// Replace insert tags and then re-replace the request_token tag in case a form element has been loaded via insert tag
+		// Replace non-cacheable insert tags
 		$this->strBuffer = $this->replaceInsertTags($this->strBuffer, false);
+
+		/// Re-replace the request_token tag because replaceInsertTags() only supports 1 nesting level (e.g. a form element has been loaded via insert tag)
 		$this->strBuffer = str_replace(array('{{request_token}}', '[{]', '[}]'), array(REQUEST_TOKEN, '{{', '}}'), $this->strBuffer);
-		$this->strBuffer = $this->replaceDynamicScriptTags($this->strBuffer); // see #4203
 
 		// HOOK: allow to modify the compiled markup (see #4291)
 		if (isset($GLOBALS['TL_HOOKS']['modifyFrontendPage']) && is_array($GLOBALS['TL_HOOKS']['modifyFrontendPage']))
```

**Comment by leofeyer** [comment]
Und natürlich müssen in der `addToCache()` Zeile 247 und Zeile 248 weg, richtig?

**Comment by Toflar** [comment]
Ach so, ja klar. Das dachte ich wäre offensichtlich. Aber indeed, komplette Änderungen wären so:

```diff
diff --git a/system/modules/core/classes/FrontendTemplate.php b/system/modules/core/classes/FrontendTemplate.php
index ecaef99..43e193c 100644
--- a/system/modules/core/classes/FrontendTemplate.php
+++ b/system/modules/core/classes/FrontendTemplate.php
@@ -90,16 +90,21 @@ class FrontendTemplate extends \Template
 			}
 		}
 
+		// Replace cacheable insert tags and dynamic tags
+		$this->strBuffer = $this->replaceInsertTags($this->strBuffer);
+		$this->strBuffer = $this->replaceDynamicScriptTags($this->strBuffer); // see #4203
+
 		// Add the output to the cache
 		$this->addToCache();
 
 		// Unset only after the output has been cached (see #7824)
 		unset($_SESSION['LOGIN_ERROR']);
 
-		// Replace insert tags and then re-replace the request_token tag in case a form element has been loaded via insert tag
+		// Replace non-cacheable insert tags
 		$this->strBuffer = $this->replaceInsertTags($this->strBuffer, false);
+
+		/// Re-replace the request_token tag because replaceInsertTags() only supports 1 nesting level (e.g. a form element has been loaded via insert tag)
 		$this->strBuffer = str_replace(array('{{request_token}}', '[{]', '[}]'), array(REQUEST_TOKEN, '{{', '}}'), $this->strBuffer);
-		$this->strBuffer = $this->replaceDynamicScriptTags($this->strBuffer); // see #4203
 
 		// HOOK: allow to modify the compiled markup (see #4291)
 		if (isset($GLOBALS['TL_HOOKS']['modifyFrontendPage']) && is_array($GLOBALS['TL_HOOKS']['modifyFrontendPage']))
@@ -243,10 +248,6 @@ class FrontendTemplate extends \Template
 				}
 			}
 
-			// Replace insert tags for caching
-			$strBuffer = $this->replaceInsertTags($this->strBuffer);
-			$strBuffer = $this->replaceDynamicScriptTags($strBuffer); // see #4203
-
 			// Add the cache file header
 			$strHeader = sprintf
 			(
```

**Comment by leofeyer** [comment]
Ok. Und soll ich das jetzt echt in einen Maintenance-Release einbauen? 😄

**Comment by Toflar** [comment]
Es ist ein Bug, wir werden müssen. Aber sicher nicht in die 3.5.13. Die Leute sollen die Änderungen testen. Kannst ja den 3.5.14 Branch bereits anfangen, damit man ihn nur ziehen muss.

**Comment by leofeyer** [comment]
Und wer genau testet einen 3.5.14-Branch, wenn die offizielle Version die 3.5.13 ist? Richtig, niemand. 😄 

Wie wäre es, wenn ich die Änderungen stattdessen erstmal in der 4.2.0 vornehme und wir sie dann zurück portieren, wenn es keine Probleme gibt?

**Comment by leofeyer** [comment]
Und ein echter "Bug" ist es auch nicht. Man kann einfach den oben beschriebenen Anwendungsfall mit dem Hook nicht umsetzen; es gibt aber ja eine Alternative.

Von daher wäre ich fast sogar der Meinung, dass wir das erst in Contao 5 ändern sollten.

**Comment by davidmaack** [comment]
Naja da es schon einmal funktioniert hat und mit dem aktuellen Verhalten die Daten im Cache durchaus andere sein können als beim direkten Rendern der Seite ist das schon irgendwie falsch....

**Comment by discordier** [comment]
IMHO this is irrelevant for Contao 4.3 when ESI PR https://github.com/contao/core-bundle/pull/551 is merged.
For Contao 3.5 I am undecided if the suggested change by @Toflar above will work out correctly or what will break (IMO any change in the caching in Contao will cause a big pile of problems).
Therefore I tend to call the overall issue a known limitation in Contao 3.5 that will solve itself in Contao 4.3+ and close it.

**Comment by leofeyer** [comment]
@Toflar Ist dieses Ticket noch relevant, jetzt da wir den HTML-Cache in Contao 4.3 entfernt haben?

**Comment by Toflar** [comment]
Ich glaube es müsste sich jetzt erledigt haben. Unser HTML-Cache ist komplett weg und wir haben jetzt echten Reverse-Proxy Support 🎉 . Insofern ist es jetzt eine Sache der korrekten Response-Header. Ich würde das erst mal schliessen und ein neues Ticket eröffnen lassen, wenn etwas in Contao 4.3 immer noch nicht funktioniert. Schliesslich sind die ganzen in diesem Ticket erwähnten Stellen im Code nicht mehr aktuell.
