### ISSUE TITLE
C 3.4.0: Inserttag {{article_teaser}} löst {{file}} nicht auf

### ISSUE THREAD

**Issue by mpunkt** [contao/core#7488]
Ein Artikelteaser enthält ein Bild dessen src-Attribut das {{file}} -Tag enthält (wenn man den Teaser mit dem TinyMCE bearbeitet ist das ja Standard). Bindet man diesen Teaser in einem anderen Element per Inserttag {{article_teaser}} ein, so wird das Bild nicht angezeigt. Im src-Attribut wird das {{file}} -Tag nicht zum Dateipfad aufgelöst.

**Comment by leofeyer** [comment]
Dein Fix ist korrekt. Und wenn wir ihn einbauen, sollten wir dasselbe auch gleich für die `news_teaser` und `event_teaser` Inserttags einbauen.

**Comment by leofeyer** [comment]
Behoben in 892708fb01aca9df8afce509974899247b081119.
