### ISSUE TITLE
Contao 3.4.0: backend login not possible under certain PHP versions

### ISSUE THREAD

**Issue by fritzmg** [contao/core#7489]
In Contao 3.4.0, (backend) login always fails with message

> Login failed (note that usernames and passwords are case-sensitive)!

when using PHP version 5.3.1 (not supported anyway), 5.3.3 or 5.3.5 for instance (probably more versions from PHP 5.3 affected), even though the username and password are definitely correct. PHP version 5.3.28 seems to work.

I tested this with XAMPP 1.7.2 (PHP 5.3.1) and XAMPP 1.7.3 (PHP 5.3.5) under Windows 7, by doing a regular, fresh Contao 3.4.0 installation and no upgrade. It also seems to happen when updating from Contao 3.3.7 to 3.4.0 for isntance. More user reports can be found [here](https://community.contao.org/de/showthread.php?54248-Nach-Update-auf-3-4-ist-Passwort-Installpasswort-nach-Speichern-immer-falsch).

**Comment by Toflar** [comment]
> I guess so too, but @Toflar is the expert on the topic…

I did 2 pull requests. One was #5853 which replaced the whole password hashing and verifying routine using the new password hashing api (or if not available uses the BC layer by Anthony Ferrara). Because such a major change should only be executed on a major version (v4) I did #7115 which only adds timing-attack prevention to the current 3.x-branch if `hash_equals` exists - nothing else. 
Neither of the two pull requests made it into the core. The current implementation in 3.4 is something Leo developed himself so I'm not an expert on this piece of code at all.

**Comment by leofeyer** [comment]
> It works in PHP 5.3.8.
>
> I just noticed, that Contao's [README](https://github.com/contao/core/blob/master/README.md) specifies the minimum PHP version as PHP 5.3.7 anyway (may be the login works in PHP 5.3.7 too). However, the [Contao Check](https://github.com/contao/check/blob/fa53efdb66805f7c584156b37eef1774c9aabc62/check/controller/index.php#L58) still only lists PHP 5.3.2 as the minimum requirement and the [documentation on the website](https://contao.org/en/manual/3.4/installation.html#contao-system-requirements) also only lists PHP 5.3.2 as the minimum requirement.

This is only a documentation problem. Contao 3.4 does require at least PHP 5.3.7 as mentioned in the README file. We simply forgot to update the `composer.json` file and the Contao check.

> The tl_user table get under the password field an other value, it always change for example from the original value: (01) `b13c70f88b869a89a691a78d2abae0255c90ec09` 
>To (02) a strange value (always begins with $-sign): `$6$d9ca0cf1756d77c2$fZ.yNxcGSxg/ZvARZci3z3eaXpxDtsutils8w6I8nJoTsg7DJ2wgCMs7T4UHlYuk9Wwv.bm7QWj5XQ0PEBWN4`. Hope that there is soon a bugfix for this.

The original value is a SHA-1 hash, which is weak and no longer secure. The "strange" value is a SHA-512 hash and therefore correct.

**Comment by aschempp** [comment]
I have updated the system requirements in the documentation (see https://github.com/contao/docs/commit/d57639301a1ab1cccbb124f6f83a39f31097e19a)

**Comment by leofeyer** [comment]
I have fixed the `composer.json` in fbc0d0b6231cbb6d311249ff59d5ecd8651a89ed.
