### ISSUE TITLE
Expecting Model for every Table

### ISSUE THREAD

**Issue by christianromeni** [contao/core#7490]
It should be optional to have a Model for Tables.
The Core is expecting it: https://github.com/contao/core/commit/694097190d44819e4dc5f5f77393fc2f6b134978

See: https://community.contao.org/de/showthread.php?54223-Class-ProjekteModel-not-found-in-BackendFile-php

**Comment by christianromeni** [comment]
Gibt es hierzu ein Update?
Ich weiß, war Weihnachten/Neujahr... Aber eventuell wurde ja doch etwas weiter entwickelt?

**Comment by leofeyer** [comment]
Behoben in 903fc0db1cffe808f4fd41c1acf5bc1001718307. Bitte kurz bestätigen, dass der Patch das Problem löst.

**Comment by nelhop** [comment]
Ja, funktioniert bei mir.

**Comment by BugBuster1701** [comment]
Funktioniert bei mir.
