### ISSUE TITLE
patched mediabox.js inconsistent regarding contextmenu

### ISSUE THREAD

**Issue by fritzmg** [contao/core#7501]
Contao's version of the mediabox.js adds the following patch, to enable the contextmenu on image links by default:
```JavaScript
// PATCH: enable the contextmenu
//links.addEvent('contextmenu', function(e){
//	if (this.toString().match(/\.gif|\.jpg|\.jpeg|\.png/i)) e.stop();
//});
// PATCH EOF
```
However, the contextmenu on the actual image is still disabled. In order to enable it, the following line (#900) needs to be disabled:
```JavaScript
preload.addEvent('mousedown', function(e){ e.stop(); }).addEvent('contextmenu', function(e){ e.stop(); });
```

But may be it would be better to upgrade the mediabox to its newest version. mediabox 1.5.x introduces this option:
```JavaScript
clickBlock: true, // Adds an event on right-click to block saving of images from the context menu in most browsers (this can't prevent other ways of downloading, but works as a casual deterent).
```
When `clickBlock` is false, both the already patched part and the part I mentioned will be disabled.

**Comment by leofeyer** [comment]
Too bad the maintainer did not tag their releases, otherwise we would have known that there is a version 1.5 :(

**Comment by leofeyer** [comment]
I have updated the [Contao mediabox component](https://github.com/contao-components/mediabox) accordingly, however, it requires to adjust the `moo_mediabox` template and can therefore only be included in Contao 4.

So for Contao 3, I have just commented out line 900 in 46e670f5891baa30ed6753757313f9ba039adc81 to fix the issue.

**Comment by fritzmg** [comment]
Sounds good :)
