### ISSUE TITLE
v3.3+ double headline at using ce_table.xhtml template

### ISSUE THREAD

**Issue by 463** [contao/core#7502]
By changing the standard templates to inheritance types the result of using the table content element with the ce_table.xhtml template is a double headline in the front-end. 
It was forgotten to delete the headline section in the modified template (lines 5 to 7). The headline is already typed in the extended block_searchable template. 
In ce_table.html5 the lines are deleted correctly.
An short evaluation shows that no other content element seems to be affected.

**Comment by leofeyer** [comment]
Fixed in 78c7aea43a3005a00982acf3199d95e3362f4989.
