### ISSUE TITLE
Setzen von Ankern wieder in tinyMCE übernehmen

### ISSUE THREAD

**Issue by NinaG** [contao/core#7518]
Im alten tinyMCE konnten Redakteure einfach mit dem Ankersymbol irgendwo in den Text ein Ankerziel #anchor-name setzen. Mit {{env::request}}#anchor-name konnten sie dann einen Link von einer anderen Stelle darauf setzen.

Im neuen tinyMCE gibt es kein entsprechendes Symbol oder Funktion mehr.

**Comment by may17** [comment]
@leofeyer Ich mache mir mal Gedanken dazu und erstelle dann einen pull request.

**Comment by Toflar** [comment]
Würde ich auch begrüssen, bin gespannt @may17 :)

**Comment by cliffparnitzky** [comment]
Das [Anker Plugin](https://github.com/cliffparnitzky/TinyMceAnchor) kann auch mit dem [TinyMcePluginLoader](https://github.com/cliffparnitzky/TinyMcePluginLoader) nachträglich eingebunden werden.

**Comment by leofeyer** [comment]
Ich schließe das Ticket zugunsten von @cliffparnitzky's [TinyMcePluginLoader](https://github.com/cliffparnitzky/TinyMcePluginLoader).

**Comment by cliffparnitzky** [comment]
:+1:
