### ISSUE TITLE
Some php files do not set http-header to UTF-8 charset

### ISSUE THREAD

**Issue by 463** [contao/core#7519]
Some backend-outputs e.g. for the maintenance mode with 'be_unavailable.html5' and also the contao-check do not set the http-header to UTF-8 so that browsers show iso-8859-1 charset with wrong letters for additional characters above ASCII127 e. g. German mutated vowel / umlauts. The UTF-8 meta-tag in the templates are not sufficient.

The line
```
header('Content-type: text/html; charset=utf-8');
```
shall be part of any php-view-file before first output (some files have it apparently) or 
```
<?php
header("Content-Type: text/html; charset=utf-8");
?>
```
must be added in the affected templates.

See https://community.contao.org/de/showthread.php?54400-Einige-zentrale-Backendtemplates-werden-mit-Windows-1252-Zeichensatz-angezeigt

**Comment by leofeyer** [comment]
Fixed in 26d59dba55249eda0c6fea7536ae306436208a8c.
