### ISSUE TITLE
Create Image Size alias

### ISSUE THREAD

**Issue by christianromeni** [contao/core#7520]
You can set the mode in Image::get to any defined: crop, left_top, center_center and so on.
But when it comes to image sizes, you have to use the ID of the image size.

    <?php $src = Image::get($project['cover']['singleSRC'], 350, 350, '1'); ?>

It would be very helpfull that Image Sizes could have an alias (generated from the Image Size Name), wich can be used in the mode:

![image](https://cloud.githubusercontent.com/assets/1358040/5424591/d783465e-82f6-11e4-89ed-2f9d54fbb5dc.png)

    <?php $src = Image::get($project['cover']['singleSRC'], 350, 350, 'projekte-cover'); ?>

**Comment by leofeyer** [comment]
We have discussed this at the developer's meeting in July 2016 and we think that your code is wrong. You should not hardcode the width, height and image size ID parameters and provide select menus in the back end form instead. The code would then look like this:

```php
<?php $src = Image::get($project['cover']['singleSRC'], $project['cover']['width'], $project['cover']['height'], $project['cover']['imageSize']); ?>
```

**Comment by christianromeni** [comment]
Ok, but sometimes its not possible to define that in the backend..
I just think it could be helpful to have not only the ID but also the alias as option to set the imageSize manually..

**Comment by fritzmg** [comment]
Also the alias could be used as the CSS class to help solve this problem #8202 (among other things).

**Comment by aschempp** [comment]
Can you give an example of when it would not be possible to have such a configuration option?

**Comment by christianromeni** [comment]
Nope.. I dont have a usecase for that in mind right now...
Its just convenience.. But using the alias as additional css class could really be an idea...

**Comment by aschempp** [comment]
A CSS class per image size setting is another feature we also discussed and will likely be implemented.

**Comment by ausi** [comment]
> A CSS class per image size setting is another feature we also discussed and will likely be implemented.

See contao/core-bundle#555
