### ISSUE TITLE
Manche Felder der DNS-Einstellungen für tl_page in Benutzergruppen nicht vorhanden

### ISSUE THREAD

**Issue by michelbalzer** [contao/core#7522]
In den Benutzergruppen-Einstellungen gib es keine Möglichkeit, die Felder _Datei-URL_, _Assets-URL_ und _Sprache_ der DNS-Einstellungen für einen Startpunkt an- oder abzuhaken. (tl_page staticFiles, staticPlugins, language).

Habe ich in der 3.3.7 (Screenshot) sowie der 3.4.0 der Online-Demo.

![bildschirmfoto 2014-12-16 um 13 20 16](https://cloud.githubusercontent.com/assets/1337412/5453331/7d895396-8526-11e4-8665-c699481536a3.png)

**Comment by leofeyer** [comment]
Behoben in 1abe37b671f80749709b641880925955baf069a4 (die Checkbox für *Sprache* war bereits da – 5. Zeile von oben).
