### ISSUE TITLE
HTML code "textfield"

### ISSUE THREAD

**Issue by EDsolution** [contao/core#7525]
Hi,
the height of HTML code textfield is always to small. For example I have two lines of code but visiable is only one, the "auto resize" doesn't work.

**Comment by EDsolution** [comment]
You can create new Custom HTML and past this code (firefox).

<div class="social">
                <a class="fb" target="_blank" href="">Facebook</a>
                <a class="ld" target="_blank" href="">Linkdin</a>
            </div>

It will only show 3 rows insted of 4.

**Comment by leofeyer** [comment]
Nope, it worked like a charm in my test:

![](https://cloud.githubusercontent.com/assets/1192057/6482991/4f9071da-c26c-11e4-8a6e-5c73ace8bf50.png)

Which browser and OS are you on?

**Comment by EDsolution** [comment]
Meybe this is only on Windows. I have Win 8, latest FireFox

**Comment by leofeyer** [comment]
Can anyone else reproduce this?

**Comment by aschempp** [comment]
I have seen that a lot of times, but I remember we fixed a bug related to fonts. @EDsolution what version of Contao do you use?

**Comment by EDsolution** [comment]
3.4.4

**Comment by xchs** [comment]
It works on my system (W7, FF, Chrome), actually.

**Comment by EDsolution** [comment]
Try W8. I don't know...but I have 3 different computer with W8 and FF and on all I've notice this bug (randomly - didn't figure out if number of lines of code are the issue or smth. else.)

**Comment by EDsolution** [comment]
Argh...ok...try this code:
```html
Phone: + xxxxxxxxxx  <span class="delimiter">|</span>  <span class="mail">Email: <a href="mailto:info@xxxxxxxxxxxx.com">info@xxxxxxxxxxxx.com</a></span>
                    <div class="copyright">©2015 xxxxxxxxxxxx. All rights reserved!</div>

I get only 1 row

**Comment by leofeyer** [comment]
Works like a charm on my system:

![bildschirmfoto 2015-04-04 um 20 05 09](https://cloud.githubusercontent.com/assets/1192057/6993926/f6e5bcb8-db05-11e4-81b0-69175a0a2851.png)

**Comment by DyaGa** [comment]
I think, here is it. I clicked inside and outside "html code" area.

![](http://i.gyazo.com/3110962d27283f68ddcc3dc7c22d05d1.gif)
http://gyazo.com/3110962d27283f68ddcc3dc7c22d05d1

Contao 3.4.4. W8.1, Chrome 42.

And in Firefox 37.

![](http://i.gyazo.com/3466e13ac84e61084c427bcd0a6bb0d5.gif)
http://gyazo.com/3466e13ac84e61084c427bcd0a6bb0d5

**Comment by Aybee** [comment]
Maybe it's an ACE bug as Contaos setupTextareaResizing is not working on this textarea because it has the CSS class "noresize".

**Comment by EDsolution** [comment]
Strange on my FireFox when clicked inside it doesn't extend and also in Chrome I have 2 lines :)

**Comment by DyaGa** [comment]
This bug also happend when editing content:

![](http://i.gyazo.com/8206edcf64b710377ec77d0c50c857e4.gif)

**Comment by DyaGa** [comment]
and next code looks ok

![](http://i.gyazo.com/45e66d0fc9783a4c8849baa7a3b38464.png)

**Comment by leofeyer** [comment]
There has been a later ticket regarding the same issue: #8328 

Can you please check if it fixes your issue as well?
