### ISSUE TITLE
CSS Name mit Umlaut wird als Datei nicht gefunden

### ISSUE THREAD

**Issue by BugBuster1701** [contao/core#7526]
Im Backend eine CSS anlegen (Themes » Stylesheets) mit dem Namen "Überschriften" und im Layout einbinden. Wenn der Combiner nun versucht diese zu lesen gibt es eine Fehlermeldung:
```
Fatal error: Uncaught exception Exception with message File assets/css/Überschriften.css does not exist thrown in system/modules/core/library/Contao/Combiner.php on line 138

#0 system/modules/core/library/Contao/Controller.php(1939): Contao\Combiner->add('assets/css/\xC3\x9Cbe...', '1418810707', 'all')
#1 system/modules/core/classes/FrontendTemplate.php(99): Contao\Controller::replaceDynamicScriptTags('...')
#2 system/modules/core/pages/PageRegular.php(195): Contao\FrontendTemplate->output(true)
#3 system/modules/core/controllers/FrontendIndex.php(253): Contao\PageRegular->generate(Object(Contao\PageModel), true)
#4 index.php(22): Contao\FrontendIndex->run()
#5 {main}
```
aufgefallen in Contao 3.4.

**Comment by leofeyer** [comment]
Ich kann es nicht reproduzieren. Welches Betriebssystem und welches Dateisystem läuft auf Deinem Server?

**Comment by BugBuster1701** [comment]
LinuxMint 17 (Ubuntu 14.04.1 LTS), ext4

**Comment by leofeyer** [comment]
Hast Du vielleicht die UTF-8-Lokale nicht installiert? Schau mal bitte ob und wie die Datei in `assets/css/` angelegt wird.

**Comment by BugBuster1701** [comment]
Es wird eine Datei namens: ```berschriften.css``` angelegt.
locale gibt aus:
```
LANG=de_DE.UTF-8
LANGUAGE=
LC_CTYPE="de_DE.UTF-8"
LC_NUMERIC="de_DE.UTF-8"
LC_TIME="de_DE.UTF-8"
LC_COLLATE="de_DE.UTF-8"
LC_MONETARY="de_DE.UTF-8"
LC_MESSAGES="de_DE.UTF-8"
LC_PAPER="de_DE.UTF-8"
LC_NAME="de_DE.UTF-8"
LC_ADDRESS="de_DE.UTF-8"
LC_TELEPHONE="de_DE.UTF-8"
LC_MEASUREMENT="de_DE.UTF-8"
LC_IDENTIFICATION="de_DE.UTF-8"
LC_ALL=
```

**Comment by xchs** [comment]
@leofeyer Hast Du nach Einbindung des Stylesheets im Layout die Frontend-Ansicht aktualisiert?

**Comment by leofeyer** [comment]
Ja, habe ich. Und ich habe mir die Datei angesehen, die in `assets/css/` angelegt wurde. Bei mir ist es `Überschriften.css` mit  dem Ü.

**Comment by leofeyer** [comment]
Es scheint wohl eher so zu sein, dass **mein** OS das Problem umgeht. Auf der Kommandozeile sehe ich nämlich auch die falsche Kodierung.

**Comment by leofeyer** [comment]
Behoben in d5fa56e2a9be20e8758a40821c1907cc015ee797.
