### ISSUE TITLE
[3.2.16] Backend-Vorschau findet benutzerdefinierte Templates in Unterverzeichnissen nicht

### ISSUE THREAD

**Issue by Samson1964** [contao/core#7531]
Ich habe eine Erweiterung erstellt, die ein Inhaltselement enthält, wo man sich via Funktion getTemplateGroup ein Template auswählen kann. Das funktioniert wunderbar, auch mit Templates die in einem Themeverzeichnis gespeichert sind. Sobald man aber in die Backendansicht der Inhaltselemente zurückkommt und hatte zuvor ein benutzerdefiniertes Template in einem Themeverzeichnis ausgewählt, verabschiedet sich Contao mit einem "Could not find template in TemplateLoader Zeile 127". Im Frontend funktioniert die Anzeige des Templates einwandfrei.

Umgehen kann man das erstmal wohl nur, indem man die Backendvorschau selbst generiert, wie das beim Inhaltselement Modul passiert. Da hat man ja dann sowas zu stehen wie:

    ### NACHRICHTENLISTE ###
    Portal - Topnachricht 2 (ID: 228) 

Allerdings stecke ich noch nicht so tief in der Materie drin, ob das überhaupt geht. Aber das Inhaltselement Modul hat ja auch seine eigene Ausgabe.

Wahrscheinlich ist der Fehler mit der Backendvorschau in Contao bisher nicht aufgefallen, weil noch niemand versucht hat, ein Inhaltselement mit einem benutzerdefinierten Theme-Template zu parsen. Läuft ja in der Regel alles über Module.

**Comment by leofeyer** [comment]
Wie genau lässt sich das Problem reproduzieren?

**Comment by discordier** [comment]
@leofeyer kann man nicht reproduzieren oder beheben, da kein objPage im BE vorhanden und daher auch kein theme und somit auch nicht via theme geladen werden kann.
Ich mach in MetaModels auch eine Wildcard bei den Content Elementen, da man eben im BE nicht an custom templates ran kommt (ohne einen eigenen template loader zu schreiben).
