### ISSUE TITLE
[3.2.16] Platzhalter vom Inhaltselement Hyperlink erzeugt ein Leerzeichen

### ISSUE THREAD

**Issue by Samson1964** [contao/core#7532]
Beim Elementtyp Hyperlink wird vor und nach dem Platzhalter %s ein überflüssiges Leerzeichen angelegt, welches zum Link gehört.
Ebenso ist der Hilfetext unter dem Eingabefeld wenig erleuchtend, Zitat: "Für mehr Informationen besuchen Sie %s".

**Comment by leofeyer** [comment]
Diese Ausgabe ist dem Template geschuldet. In diesem Fall ist es einfach nicht möglich, nur einen Teil eines Wortes zu verlinken. Stattdessen kann jedoch der TinyMCE verwendet werden.

**Comment by Samson1964** [comment]
Okay, sehe ich auch gerade nach dem Blick in ce_hyperlink.html5. Damit das Core-Inhaltselement wie gewünscht die vorgesehene Ausgabe erledigt, muß ich also das Core-Template überschreiben.

**Comment by aschempp** [comment]
Die Lösung wäre doch ganz einfach? Im Template das `embed_pre` und `embed_post` nicht auf einer neuen Zeile machen?
