### ISSUE TITLE
Wrong LESS import path

### ISSUE THREAD

**Issue by psi-4ward** [contao/core#7533]
See the path-resolve logic in https://github.com/oyejorge/less.php/blob/master/lib/Less/Tree/Import.php#L227

so we need the absolute path as array-key and the relative as value in https://github.com/contao/core/blob/master/system/modules/core/library/Contao/Combiner.php#L356

```php
			$filePath = dirname($arrFile['name']);
			$arrOptions = array
			(
				'compress' => !\Config::get('debugMode'),
				'import_dirs' => array(TL_ROOT . '/' . $filePath => $filePath)
			);
			$objParser = new \Less_Parser($arrOptions);
			$objParser->parse($content);
```

Solves: `Fatal error: Uncaught exception Less_Exception_Parser with message File bootstrap/less/bootstrap.less not found. in anonymous-file-0.less thrown in vendor/oyejorge/less.php/lib/Less/Parser.php on line 2579`

**Comment by leofeyer** [comment]
Fixed in 449607753f585ae80b43b318e4f9b29c47a8013e.
