### ISSUE TITLE
[bis Contao 4] htaccess im Dateibaum ausblenden

### ISSUE THREAD

**Issue by xantippe** [contao/core#7536]
Es wäre schön, wenn die htaccess im Dateibaum analog den .svn und .DS_Store ausgeblendet wird.

Die "Gefahr", dass die "Schutz-Datei" versehentlich oder aus Unwissenheit gelöscht wird ist recht groß.

Das wäre also im DC_Folder.php

```
        // Scan directory and sort the result
        else
        {
            foreach (scan($path) as $v)
            {
                if ($v == '.svn' || $v == '.DS_Store' || '.htaccess')
                {
                    continue;
                }  
```
schöner wäre m.E. eine Prüfung regen ein Array, welches per DCA-Config angepasst werden kann - etwa

```
        // Scan directory and sort the result
        else
        {
            foreach (scan($path) as $v)
            {
                if (in_array($v, $DCA_ARRAY))
                {
                    continue;
                } 
```

siehe u.a. https://community.contao.org/de/showthread.php?37430-htaccess-in-Dateiverwaltung-ausblenden&p=352835&viewfull=1#post352835

... auch wenn in Contao 4 nicht mehr notwendig, hilft es so manchem Admin davor einen Herzkasper zu bekommen ;-)

**Comment by xantippe** [comment]
nun als "echte" Erweiterung - siehe http://www.e-spin.de/hide-files.html

Als Fazit bleibt für mich der Wunsch nach einem Hook oder Konfigurationsmöglichkeit der Dateien - aktuell muss ich die Funktion in DC_Folder "beobachten" und ggf. die Erweiterung updaten...

**Comment by leofeyer** [comment]
@contao/developers Was denkt ihr?

**Comment by aschempp** [comment]
Ich finde die Idee auch gut. Vielleicht auch nur für Admins anzeigen. Jedenfalls sollte sie ausgeblendet werden wenn man keine Berechtigung hat den Verzeichnisschutz einzustellen.

**Comment by Toflar** [comment]
Ich finde auch, dass man sie ausblenden kann. Mir fällt kein Anwendungsfall ein, wo die `.htaccess` in `files` zusätzliche Direktiven enthalten sollte. Wenn sowas gefordert ist, dann hat es zu 99% nichts mit Contao zu tun und sollte deshalb auch besser ausserhalb von `files` passieren.

**Comment by xantippe** [comment]
Hallo,

paranoid ist aufgefallen, dass die ".htaccess" trotz der Erweiterung über den "FileTree" angezeigt wird z.B. beim CE Downloads in der Lightbox... darauf hin habe ich /core mal nach ".DS_Store" untersucht und bin etwas "irritiert"...

Ich bin davon ausgegangen, dass mit Einführung des DBFS es eine Stelle gibt, die die physischen Dateien (aus /files) in die DB schreibt und alle anderen Funktionen sich auf das DBFS beziehen - mit der obigen Suche sind mir einige Aufrufe der Helper-Funktion "scan" in die Hände gefallen. z.B. gibt es in /core/wigdets/FileSelector.php 
```
if (!is_dir($path.'/'.$v) && $v != '.DS_Store')
```
[ohne die Filterung nach .svn - Bug oder Feature?]

die über die "physikalischen Dateien" suchen - warum?

Mir scheint, die Änderung bzw. der Änderungswunsch reißt größere Baustellen auf. In /Dbafs/Filter.php gibt es die "Ignored files" z.B. auch nur als fest verdrahtetes Array...

**Comment by leofeyer** [comment]
Implementiert und vereinheitlicht in be420c0440f3f753fdba0efbe413df3a1ec721af.

**Comment by xantippe** [comment]
schade, dass es für die Auflistung keinen "zentralen Service" gibt - dann wäre die Implementierung eines Filter-Hooks relativ einfach zu machen - z.B. kommt 1und1 auf die glorreiche Idee in alle (wirklich alle) Ornder einen symb. Link zu einer php.ini zu setzen, um bestimmte Werte zu verändern. Mit dem Hook könnte man auch die ini-Dateien ausblenden...

**Comment by leofeyer** [comment]
Einen solchen Service gibt es absichtlich nicht, da die Liste der ignorierten Dateien maßgeblich für das Datenbank-gestützte Dateisystem ist. Die Hashes der Ordner werden beispielsweise anhand der enthaltenen Dateien berechnet und eine Installation, die `php.ini`-Dateien ignoriert, wäre dann nicht mehr kompatibel zu einer, die das nicht tut.

**Comment by xantippe** [comment]
o.k. - verstehe... wo wäre der Ansatzpunkt, um bestimmte Dateien oder Dateitypen in den Auswahl-Ansichten zu unterdrücken? in den meisten Fällen dürfte das eher "kosmetischer" als "sicherheitsrelevanter" Natur sein - aber dennoch stolpern einige "Redakteure" über solche Anzeigen...

**Comment by leofeyer** [comment]
Im konkreten Fall von 1und1 wäre ein ordentlicher Hoster angezeigt ;)
