### ISSUE TITLE
Insert Tag wird nicht ersetzt bei aktiviertem Seitencache

### ISSUE THREAD

**Issue by saress** [contao/core#7537]
Wir haben bei einem Projekt ein Frontend Modul angelegt (Modultyp Eigener HTML Code, ID20) und darin via {{file::xy/mod_share.html5}} die Social Media Icons integriert. Dieses Modul haben wir dann in ein weiteres Frontend Modul (ebenfalls vom Typ Eigener HTML Code) via {{insert_module::20}} integriert.

Aktiviert man daraufhin in der Seitenstruktur den Cache (Cachezeit festlegen, z.B. 24 Stunden), so wird im Frontend der Insert Tag nicht ersetzt und im Sourcecode steht dann {{file::xy/mod_share.html5}}.
Deaktiviert an den Cache wieder, funktioniert alles wie erwartet.

Getestet mit Contao 3.4. In der Demo lässt sich das mangels Zugriff auf die Templates nicht testen. 

Beste Grüße
Saress

**Comment by leofeyer** [comment]
Tritt das Problem in Contao 3.5.5 noch auf?

**Comment by asaage** [comment]
Ich denke da hat sich generell nichts dran geändert.
https://community.contao.org/de/showthread.php?50288-Probleme-mit-inserttag-file-und-Seitencache

**Comment by leofeyer** [comment]
Wie genau kann ich das Problem reproduzieren?

**Comment by asaage** [comment]
Eigentlich so wie @saress es beschrieben hat.
file-insert auf einer gecachten Seite platzieren, servercache leeren und dann in einem anderen Browser (oder incognito) diese Seite aufrufen.

**Comment by leofeyer** [comment]
Mir ist es gerade nicht gelungen, das Problem zu reproduzieren.

**Comment by asaage** [comment]
Ich hab einen anderen Weg gewählt und eine Erweiterung für einen mini-anwendungsfall geschrieben.
Es kam - soweit ich mich erinnere darauf an, was man in dem includierten file verwenden möchte.
ein ``` echo  replaceInsertTags('{{page::id}}'); ``` z.B. ging nicht - und hat dann {{file::myfile}} im FE ausgegeben.
