### ISSUE TITLE
Improvement: Better BE-UID referring Module-/CE-Type-Selects

### ISSUE THREAD

**Issue by Hendriks** [contao/core#7538]
Hi there!

In editing view of modules, content elements, etc. it would be much more consistent and provide better user experience (orientation, etc.) if the type selector would outstand / be visually separated from the body of settings, e.g. like so:

![bildschirmfoto 2014-12-25 um 01 06 41](https://cloud.githubusercontent.com/assets/1499091/5554654/9ad79a94-8c69-11e4-8415-ceaf55171c5b.png)

Don't you think!?

This would also save us one valuable row in the generic upper part of the layout...

The first legend should then be called something like "Title and headline", of course... Or —to gain even more vertical space— why not remove the first legend completely; because it's also very basic information, that should(!) even be "forced" to be visible all the time!?

Even the generic back button would be better of separated from the rest by moving it also one row up into the light grey box, next to the type select, on the very left; in nice button style.... and, counterpart, place an aditional generic back button in the footer, moving the bunch of save buttons to the right; where —from a usability point of view, _imho_— rather they belong... :-)

**Comment by leofeyer** [comment]
I don't agree at all!
