### ISSUE TITLE
Contao und CloudFlare Flexible SSL

### ISSUE THREAD

**Issue by squidi** [contao/core#7542]
Bezugnehmend auf:

https://community.contao.org/de/showthread.php?54749-Contao-und-CloudFlare-Flexible-SSL&p=353150&viewfull=1#post353150

könnte dies eine Lösungsansatz sein.

Contao erkennt über den CloudFlare Reverse-Proxy die Variable $_SERVER['HTTPS'] nicht, mit der in der Environment.php für die <base> https oder http generiert.

CloudFlare gibt dort aber $_SERVER['HTTP_X_FORWARDED_PROTO']

Setzt man nun in Zeile 317

return ($_SERVER['SSL_SESSION_ID'] || $_SERVER['HTTP_X_FORWARDED_PROTO'] == 'https' || $_SERVER['HTTPS'] == 'on' || $_SERVER['HTTPS'] == 1);

funktioniert es auch über CloudFlare Flexible SSL

**Comment by leofeyer** [comment]
Ich würde es vorziehen, das nicht zu implementieren. Es handelt sich bei CloudFlare nicht um eine echte Ende-zu-Ende-Verschlüsselung, da nur der Traffic zwischen Client und CloudFlare verschlüsselt ist, die eigentliche Verbindung zum Server aber wieder über HTTP erfolgt. Insofern ist die Erkennung der `Environment`-Klasse korrekt.

Wer CloudFlare nutzt, kann das ganz einfach in der `initconfig.php` umbiegen:

```php
if (isset($_SERVER['HTTP_X_FORWARDED_PROTO']) && 'https' === $_SERVER['HTTP_X_FORWARDED_PROTO']) {
    $_SERVER['HTTPS'] = 1;
}
```

Ich sage bewusst "umbiegen", weil hier eine technische Voraussetzung vorgegaukelt wird, die in Wahrheit nicht besteht. Es handelt sich nämlich wie gesagt in keiner Weise um eine sichere Verbindung.

**Comment by squidi** [comment]
Leo, da gebe ich Dir heute völlig Recht, soweit es sich um Flexible SSL handelt, allerdings verstehe ich das in den anderen Varianten Full SSL und Strict SSL anders.

https://support.cloudflare.com/hc/en-us/articles/200170416-What-do-the-SSL-options-Off-Flexible-SSL-Full-SSL-Full-SSL-Strict-mean

Aber der Eintrag in der initconfig.php sollte es auch tun, wurde auch schon im Forum angedacht.

**Comment by leofeyer** [comment]
Bei Full SSL und Strict SSL besteht das Problem nicht, weil hier eine echte SSL-Verbindung am Server ankommt :)

**Comment by squidi** [comment]
Hast Du das getestet ? Ich meine dort kommt auch $_SERVER['HTTP_X_FORWARDED_PROTO'] ,bin mir aber nicht 100% sicher, ob dort dann nicht Pro und höher verwendet werden muss.

**Comment by leofeyer** [comment]
Nein, ich habe keinen Pro-Account bei CloudFlare. Aber wenn deren Server eine HTTPS-Verbindung aufbaut ist das für den Zielserver ja eine ganz normale HTTPS-Verbindung.

**Comment by dive13** [comment]
Woran kann das liegen, dass nicht einmal der oben erwähnte Eintrag in der initconfig.php hilft? Bekomme nach wie vor kein https in die base URL. Contao 3.5.27 auf uberspace + Cloudflare Flexible SSL.

**Comment by Fruchuxs** [comment]
Die Prüfung auf "On" (upper-case o) scheint zu fehlen, zumindest war das ein Problem bei einer von mir betrauten Contao-Installation.
