### ISSUE TITLE
Feature: Kommentar in komprimierten CSS- und JS-Dateien um Dateinamen erweitern

### ISSUE THREAD

**Issue by Aybee** [contao/core#7543]
Momentan steht dieser Kommentar in allen komprimierten Dateien
```
/* Contao Open Source CMS, (c) 2005-2014 Leo Feyer, LGPL license */
```
Bei der Auslieferung durch den Combiner kann man leider nicht auf die Quelle schließen. Ich würde mir wünschen, dass der Dateiname mit in dem Kommentar enthalten wäre. Z.B.
```
/* responsive.css, Contao Open Source CMS, (c) 2005-2014 Leo Feyer, LGPL license */
```

**Comment by leofeyer** [comment]
Dafür gibt es doch den Debug-Mode?

**Comment by Aybee** [comment]
Ich persönlich benutze diesen Debugmodus nicht, der stört mich irgendwie. Wäre doch nicht so aufwendig, eben den Dateinamen oben in den Kommentar zu schreiben, oder?

**Comment by leofeyer** [comment]
Nicht aufwändig aber eben unnötig. Und da wir penibel darauf achten, die Assets so gut es geht zu komprimieren, bin ich dagegen. Vor allem ist "der Debugmodus stört mich irgendwie" kein Argument ;)

**Comment by Tastaturberuf** [comment]
:-1: 

Sehe ich genau wie Leo, der Debug-Mode tut genau das.

**Comment by Zeromax** [comment]
What about `sourcemap`?
https://developer.chrome.com/devtools/docs/css-preprocessors

**Comment by Aybee** [comment]
Sourcemap? Habe den Artikel überflogen, aber mir erschließt sich der Sinn nicht, sorry.

Mir ging es hauptsächlich darum, dass, wenn man vom Kunden oder aus dem Forum um Hilfe gebeten wird, man mal eben im FE sehen kann, welche CSS-Dateien eingebunden sind. Ansonsten müsste ich nach einem BE-Zugang fragen, das Layout der Seite ausfindig machen und mir die eingebundenen Dateien ansehen.

**Comment by Zeromax** [comment]
Ziemlich simple ;)
In der Kombinierten CSS Datei gibt es einen Kommentar am Ende: `/*# sourceMappingURL=style.css.map */`

in der Datei `style.css.map` stehen die Quellen:
```json
{
"version": 3,
"mappings": "...",
"sources": ["_reset.scss","_grid.scss"],
"names": [],
"file": "style.css"
}
```

So sieht man es im Chrome z.B. direkt welche Datei verwendet wird...
