### ISSUE TITLE
$ der Variablen für css gradient wird nicht ersetzt ( 3.2.16 )

### ISSUE THREAD

**Issue by WolleBugreport** [contao/core#7544]
Definiert man im CSS eine globale Variable 'var' und setzt im style für gradient die variable wird zwar 'var' ersetzt, jedoch nicht das $.
Beispiel im CSS:
background:-moz-linear-gradient(225deg,#fff 0%,#$f4b93b 80%);

**Comment by leofeyer** [comment]
Hast Du die globale Variable nur `var` genannt oder `$var`?

**Comment by WolleBugreport** [comment]
Nur var.

Das zu ersetzen Element mit $, ohne wird nicht ersetzt.

**Comment by aschempp** [comment]
Die Variable muss auch mit $ benannt sein.

**Comment by WolleBugreport** [comment]
Danke für die schnelle Antwort. Anregung wäre hier einen check auf das $ Zeichen einzubauen und diese Falscheingabe zu verhindern :-)
