### ISSUE TITLE
Rename admin folder?

### ISSUE THREAD

**Issue by dsuckau** [contao/core#7547]
Hey,

is it safe to just rename the `mysite/contao/` admin subfolder to anything else? Or are files of it referenced anywhere else in the application? I don't want to get visitors to the admin login form.

Greets

**Comment by aschempp** [comment]
No that is not possible. You should use a htaccess protection or similar to prevent visitors from accessing it.=

**Comment by leofeyer** [comment]
Please refer to the forums with this kind of questions.
