### ISSUE TITLE
HTTPS access of Extension Repository and PHP 5.6

### ISSUE THREAD

**Issue by taca** [contao/core#7548]
I've just read https://contao.org/de/news/probleme-mit-dem-repository-beheben.html via Google Translation.  I cannot access Extension Repository with Contao 3.4.0 on PHP 5.6.4.

> SOAP-ERROR: Parsing WSDL: Couldn't load from 'https://contao.org/services/repository.wsdl' : failed to load external entity "https://contao.org/services/repository.wsdl"

I guess that it is the same problem as described in http://stackoverflow.com/questions/25142227/unable-to-connect-to-wsdl.  And I partly succeeded by adding 'stream-context' SSL options.

* I succeeded to list extension repository.
* I did not succeed to update an extension.

Something should be change to solve this problem...

**Comment by leofeyer** [comment]
It works like a charm on my system without adding an SSL context to the stream. Did you make sure that the repository URL is correct and that the WSDL cache has been purged?

**Comment by taca** [comment]
Yes, sure.  In `system/config/localconfig.php` contains:
```php
$GLOBALS['TL_CONFIG']['repository_wsdl'] = 'https://contao.org/services/repository.wsdl';
```
And similar systems running on PHP 5.5.x are just fine.

**Comment by taca** [comment]
Oh, I find out what was wrong!

My server's openssl library dose not have proper root certificates and now I solved the problem.

Please close this Issue.

**Comment by leofeyer** [comment]
Ah, good to know that this can be an issue. Thanks for debugging.

**Comment by taca** [comment]
From another point of view, accessing to `contao.org` is encrypted but the target domain is not verified on prior to PHP 5.6 environment.
It had better that Contao's code explicitly set SSL parameter of "verify_peer" and "verify_peer_name".

**Comment by TB1234** [comment]
I have also a problem with the Repo and PHP 5.6(.4).

Warning: SoapClient::__doRequest(): SSL operation failed with code 1. OpenSSL Error messages: error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed in system/modules/repository/classes/RepositoryBackendModule.php on line 222

I can switch down to an older version of PHP an with 5.5 it works without problems. So I don't think it's a problem with my openssl. The configuration of the two PHP installations are also the same.

I have got the same problem with the Live Update. (posted here: https://community.contao.org/de/showthread.php?54200-LU-funktioniert-nicht-mehr-mit-PHP-5-6)

**Comment by leofeyer** [comment]
@TB1234 It **is** a problem with your OpenSSL library, as @taca wrote above:

> the target domain is not verified on prior to PHP 5.6 environment

This also explains why it does work with PHP 5.5.

**Comment by taca** [comment]
On Linux, root certificats are provided by a package whose name is like "rootcerts".
On PHP 5.5 and prior environment, SSL connection would not verify server certificates of the connecting server, so no problem had happened.  But PHP 5.6 and later this verification is enabled default.

One of the important function of SSL, protecting from spoofing, Contao should be enable "verify_peer" and "verify_peer_name" explicitly on PHP 5.5 and prior environment.

**Comment by TB1234** [comment]
Yes, I know. That's the reason why I thought that's all perfect. But you are right it is not. I added the StartSSL Root Cert and it works now. So it seems, in Scientific Linus 6 (what I use), the StartSSL root is not included and you will get this problem.

I am not sure, if everybode change many root certs on a webserver. If you add a root cert you have also to remove it by yourself it if is revoked. If you use the maintained packages this should be done by the maintainer. That's one of the reasons why I am using this...

**Comment by leofeyer** [comment]
@taca @TB1234 Maybe we should use a certificate from another issuer, who's root certificates are available on all Linux distributions as well as Windows and Mac?

**Comment by taca** [comment]
I do not think change the certificate of `contao.org`.
In my case, platform is NetBSD.  NetBSD and other BSD systems dose not install root certificates default as plain OpenSSL.  It is popular on NetBSD using "security/mozilla-rootcerts" package from pkgsrc.

**Comment by monojp** [comment]
Hello,
on our servers this is **NOT a problem with the certificate chain**. contao.org uses SSL with **Server Name Indication** (SNI) [1] which is NOT supported by older openssl versions as they are present in e.g. Centos5 [2].
Downgrading PHP and therefore disabling the peer verification works because there seems to be another cert installed which will be used e.g. for insecure cURL transfers because

```sh
curl -v -k -I https://contao.org/services/repository.wsdl
```

on systems with no SNI support **uses a cert with "*.w1.vhost.io" as common name** in contrast to

```sh
curl -v -I https://contao.org/services/repository.wsdl
```

on systems with SNI support that **uses the correct cert with "www.contao.org" as common name.**

The best fix to be compatible with older clients would be not using SNI at all, altough if there are no other SSL hosts on the server simply changing the default cert would also fix the problem, right? It seems the domain vhost.io belongs to the Contao team anyway.

[1] https://www.ssllabs.com/ssltest/analyze.html?d=contao.org
[2] http://en.wikipedia.org/wiki/Server_Name_Indication#Libraries
