### ISSUE TITLE
C 3.4.0: Mehrere Fehler in  system/modules/core/library/Contao/Controller.php

### ISSUE THREAD

**Issue by mpunkt** [contao/core#7550]
1. Zeile 1268 und 1272: Eine falsche Klammerung im Aufruf $this->replaceInsertTags verhindert die Übergabe das Parameters $blnCache an replaceInsertTags.
2. Zeile 1285, 1289, 1302 und 1306: Hier fehlt der rekursive Aufruf von $this->replaceInsertTags ganz. Dadurch werden ggf. weitere Inserttags im Teaser überhaupt nicht mehr erkannt.

Richtig wäre jeweils: ...($this->replaceInsertTags($objTeaser->teaser, $blnCache));

Siehe auch #7488.

**Comment by leofeyer** [comment]
Behoben in 892708fb01aca9df8afce509974899247b081119.
