### ISSUE TITLE
[3.2.16] Pb in calendar/event : External URL field disappears when not logged in as administrator

### ISSUE THREAD

**Issue by JLBA** [contao/core#7552]
Hi,

I have a calendar - mycalendar - and I want some user to access nothing else in BE but this calendar. 
So I created a user group - mycalendargroup- to which I granted these authorizations : 
- Calendar permissions : mycalendar
- Allowed fields : Title and some other fields, Redirect target, Redirect page, Article, Link target.

When I edit an event logged in as an administrator, I see :  Redirect target > Redirect target : Use default, Page, Article, External link. When I'm logged in with mycalendargroup permissions I only see : Use default, Page, Article. No more External link. Do I miss something (another checkbox not checked) ?

For info, there could be a little error in the french translation in user group permissions > tl_calendar_events : 
- redirect target -> Page de redirection (instead ofCible de redirection).
- redirect page-> Page de redirection

But I don't think this is the problem as I get the problem with english and german BE too. 
I've tested with clean 3.2.16 and 3.4 installs, I still have the problem.

Thanks for your help.

**Comment by leofeyer** [comment]
How do I reproduce this in the online demo?

**Comment by JLBA** [comment]
Hi,

Create a new calendar/event archive.

Create new usergroup with only these parameters checked : 
• Backend modules : Events
• Calendar permissions: the new calendar
• Allowed fields / tl_calendar_events : redirect target, redirect page, article, link target

Create a new user with new usergroup permissions.

Connect with this user. Go to the calendar, add an event. You’ll see Redirect target with use defaut, page and article. No external link option.

Thanks

JLuc
jltest@free.fr

**Comment by JLBA** [comment]
Hi again,
Thanks to the french forum, I've found the problem. "Link target" and "Open in new window" must be checked together.

So I asked myself there isn't a double problem with labels : 
- there are reversed : "Open in new window" should "Link target"
- and "External URL" should be a better translation than "link target".

There should be another problem with the obligation to check both option for it work. So we can't let user add an external link without activation "Open in new window option".

Read you.

**Comment by JLBA** [comment]
Sorry, I didn't notice I accidentally closed the issue.

**Comment by leofeyer** [comment]
We should remove the `$this->User->hasAccess('tl_calendar_events::target', 'alexf')` condition in the `tl_calendar_events.php` file.

**Comment by leofeyer** [comment]
Fixed in c8f315645892a04df74ae0e2d9e2fa86bab0e5b5.
