### ISSUE TITLE
New Items do not appear in latest changes

### ISSUE THREAD

**Issue by amenk** [contao/core#7558]
1. Create new item (for example news entry)
2. Item does not appear on the backend home page "Latest changes" section

(see also comment in #7429)

**Comment by leofeyer** [comment]
Why should a newly created item appear in the "latest changes" section? There is only one version yet.

**Comment by amenk** [comment]
From a user point of view this seems logical. At least in one possible interpretation of the latest changes list.

I think you implemented it as "what objects got changed". I was thinking of it as a changelog "what was changed on the page". And when I add a new item this is still a change to the general page and it is nice to see what was added. The undo action of a new item would be to delete it.

**Comment by leofeyer** [comment]
This issue has been fixed meanwhile.

**Comment by amenk** [comment]
Cool. Thanks
