### ISSUE TITLE
[3.4.0] CSS Export, missing mediaQuery value

### ISSUE THREAD

**Issue by BugBuster1701** [contao/core#7560]
Exportiert man  z.B. aus der COD die responsive400, diese hat die Definition ```(max-width:400px)```, kommt diese Angabe nicht in der exportierten Datei an.
Offensichtlich beachtet die Methode ```compileDefinition``` diesen Wert gar nicht.

**Comment by leofeyer** [comment]
?

**Comment by BugBuster1701** [comment]
Vielleicht verstehe ich das ja auch falsch, aber der Export ist:
```
/* responsive400.css */

#jump-to-nav {
    padding-right:0;
}

/*----- slider ------- */
    
    .slidebox1 h1 {
    font-size:2em;
    line-height:1em;
}
```
Sollte der nicht so sein?
```
/* responsive400.css */

@media (max-width:400px){
#jump-to-nav {
    padding-right:0;
}

/*----- slider ------- */
    
.slidebox1 h1 {
    font-size:2em;
    line-height:1em;
}
}
```
Sonst  müsste man ja beim Import die mediaQuery Angabe per Hand einbauen, sofern man überhaupt noch weiß, wie die war.

**Comment by leofeyer** [comment]
Da hast Du Recht.

**Comment by leofeyer** [comment]
Behoben in a5427f7709826d93b5ad7dcc741ebfdfa8016104.
