### ISSUE TITLE
[3.x.x] getPageIdFromUrl funktioniert nicht ohne domainlose Roots

### ISSUE THREAD

**Issue by verstaerker** [contao/core#7563]
Line 184 in Frontend.php (3.4.0) setz voraus, dass eine universale Domain '*' gesetzt ist. In einem Fall, wo für alle Root-Seiten ein Domainname definiert ist, schlägt dies aber fehl. (In meinem Fall wurde wurde wegen einer URL Manipulation nur eine Seite aus einer Fremddomain gefunden, deren Eintrag somit auf Linie 178 ebenfalls nicht vorhanden war.)

Wird diese Zuweisung aber durch eine Condition abgefangen, wird die Methode auf Zeile 201 per return false; beendet und der getPageIdFromUrl-Hook nie aufgerufen wird.

**Comment by leofeyer** [comment]
Ist das dasselbe wie https://github.com/contao/core/issues/6739#issuecomment-69019441?

**Comment by verstaerker** [comment]
Ja, dürfte das gleiche Problem sein.

**Comment by leofeyer** [comment]
Behoben in 670822ce82a72a8d654e37106ec0e0b5f7d68e48.
