### ISSUE TITLE
Pfadanzeige im Backend bei Inhaltselementen falsch

### ISSUE THREAD

**Issue by Samson1964** [contao/core#7566]
Den nachfolgenden Fehler konnte ich in meinem 3.2.16 als auch in der Onlinedemo 3.4.0 nachstellen.

1.) Ein Inhaltselement in einem Artikel erstellen oder bearbeiten. Z.B. in der Seite "Home". Sobald Version 2 davon angelegt ist, erscheint die Version im Log auf der BE-Startseite.
2.) Jetzt im Log auf der BE-Startseite das Inhaltselement eines anderen Artikels zum Bearbeiten wählen.

Im Pfad wird "Artikel -> Home -> ..." angezeigt, obwohl gar kein Inhaltselement aus dem Artikel "Home" bearbeitet wird. Contao verwendet offensichtlich den aus der letzten regulären Bearbeitung gespeicherten(?) Pfad und zeigt diesen an.

**Comment by leofeyer** [comment]
Kann ich nicht reproduzieren. Ich habe es mit einem Artikel aus "Home" sowie aus "The academy" versucht und jedes Mal war der Pfad korrekt.

**Comment by bennie99** [comment]
Genau wie oben beschrieben ist das zu reproduzieren, auch in der Online-Demo.

**Comment by xchs** [comment]
Ich kann das ebenfalls unter Contao 3.4.2 reproduzieren.

**Comment by Samson1964** [comment]
Nochmal im Detail:
1.) Einloggen in der Demo
2.) Auf BE-Startseite ein Element tl_content bearbeiten
3.) Im Pfad steht z.B. "Articles » Edit content element ID 173"
4.) Jetzt in den Artikeln, z.B. den Artikel "Content elements" auswählen
5.) Ein neues Element anlegen und speichern
6.) Evtl. noch ein zweites Mal das Element bearbeiten und speichern.
7.) Auf BE-Startseite das in Pkt. 2 noch einmal zum Bearbeiten auswählen.
8.) Im Pfad steht jetzt im Unterschied zu Pkt. 3: "Articles » Content Elements » Edit content element ID 173", also ein falscher Pfad

**Comment by leofeyer** [comment]
Könnte das ein Fehler in der Onlinedemo sein? Denn ich kann es hier lokal definitiv nicht reproduzieren.

**Comment by xchs** [comment]
Ich beschreibe nochmals kurz, wie ich das gegenständliche Problem reproduziert habe:
* Contao 3.4.4 & COD
* _"Systemwartung"_ > _"Versionen löschen"_ > _"Daten bereinigen"_ 
* _"Inhalte"_ > _"Artikel"_ > Artikel **"Home"** (Artikel-ID: 1) bearbeiten
* Inhaltselement ID 1 bearbeiten, den Text beliebig modifizieren und die Änderung speichern
* _"Inhalte"_ > _"Artikel"_ > Artikel **"Content Elements"** (Artikel-ID: 63) bearbeiten
* Inhaltselement ID 163 bearbeiten, den Text beliebig modifizieren und die Änderung speichern
* Auf der Backend-Startseite werden nun unter _"Zuletzt bearbeitet"_ zwei Einträge betreffend die zuvor gemachten Änderungen angezeigt
* Auf der Backend-Startseite unter _"Zuletzt bearbeitet"_ das **Element mit der ID 1** (!) bearbeiten:
![versions](https://cloud.githubusercontent.com/assets/1218766/6721908/cbb2038e-cdd2-11e4-80ea-e5735cdd329d.png)
* Die Headline zeigt nun im Pfad anstelle "Artikel » **Home** » Inhaltselement ID 1 bearbeiten" fälschlicherweise "Artikel » **Content Elements** » Inhaltselement ID 1 bearbeiten" an:
![path](https://cloud.githubusercontent.com/assets/1218766/6721976/9190b230-cdd3-11e4-9637-7df6bfd38191.png)

**Comment by leofeyer** [comment]
Danke @xchs, jetzt konnte ich es auch reproduzieren.

Das Problem entsteht durch die Konstante `CURRENT_ID`, die nach einem bestimmten System gesetzt wird, um verschiedene Probleme zu lösen. Normalerweise muss man ja erstmal einen Artikel aufrufen, um ein Inhaltselement zu bearbeiten, und dabei merkt sich Contao in der Session, welchen Wert `CURRENT_ID` hat. Beim Aufruf über die Versionsliste auf der Startseite fehlt der Weg über das Artikelmodul, daher hat `CURRENT_ID` einfach den Wert des Artikels, der zuletzt (ohne direkten Zugriff) aufgerufen wurde.

@contao/developers Eine Idee, wie man das beheben könnte?

Aus meiner Sicht ist das Problem viel zu unwichtig, als dass wir da Energie investieren sollten. Gerade die Konstante `CURRENT_ID` ist in ihrer Verwendung relativ komplex, so dass hier Fehlerpotential besteht.

**Comment by Toflar** [comment]
Dito.

**Comment by xchs** [comment]
Stimme ich ebenfalls zu.

**Comment by aschempp** [comment]
> Aus meiner Sicht ist das Problem viel zu unwichtig, als dass wir da Energie investieren sollten.

:+1:

**Comment by Samson1964** [comment]
Okay, muß ich halt mit leben. So oft benutze ich das an der Stelle nicht.
