### ISSUE TITLE
Feature: CEs als Teaser deklarieren

### ISSUE THREAD

**Issue by mpunkt** [contao/core#7569]
Ich habe eben die Migration einer Joomla!1.5-Seite (>2500 Artikel) nach Contao 3.4 erfolgreich zu Ende gebracht. Auf der Seite war fast jeder Beitrag mit einem Teaser (oft mit Bild) versehen, wobei der Teaser immer auch Bestandteil der Vollansicht war.

Ich hätte gerne alle Beiträge in Nachrichtenarchive gepackt und per Nachrichtenarchiv-Modul und Nachrichtenleser in die Seite eingefügt (das schien mir die eleganteste Methode zu sein). Leider klappte das nicht, da die Beiträge eine vom Nachrichtendatum unabhängige feste Reihenfolge haben sollten, man in Contao mit Nachrichtenarchiven aber an eine Datumssortierung gebunden ist.
So blieb nur die Artikel-Lösung.

Warum unterscheidet sich die Teaserbehandlung in der Artikelvariante von der in News und Events? Beispiel: Der Titel eines Artikels wird nur in der Teaseransicht als Überschrift verwendet, bei News und Events ist das anders. Im Artikelteaser kann man, im Gegensatz zu News und Events, keine Bilder hinzufügen (die Lösung per TinyMCE 4 ist zwar möglich, aber eigentlich nicht brauchbar, da es keine Vorschaubilder mehr gibt und die Variante mit {{image:*}} zu unkomfortabel ist).
Ist das wirklich so gewollt?
Warum bildet man den Teaser eigentlich nicht auch in Inhaltselementen ab?

Es könnte so aussehen: Der Teaser wird aus (beliebig vielen) Contentelementen gebildet. Die CEs, die den Teaser bilden sollen, erhalten ein entsprechendes Optionsmerkmal. Ganz flexibel wird es, wenn dieses Optionsmerkmal die Zustände "normal (nicht Teaser)", "auch als Teaser" und "exklusiv als Teaser" kennt.

Ein Fehler ist das natürlich nicht, ich hoffe aber trotzdem, dass sich da etwas machen lässt, denn Contao ist derzeit mein Favorit.

Günter.

**Comment by xantippe** [comment]
der Text hätte sicher gut ins Contao-Forum gepasst...

**Comment by mpunkt** [comment]
Ja das ist richtig, aber es gibt hier einige Artikel, die als Feature gelabelt wurden. Und das mit der unterschiedlichen Teaserbehandlung (Artikel - News) bzw. die Teaserfunktionalität in CEs abzubilden möchte ich schon als Feature verstanden wissen.

**Comment by xantippe** [comment]
... ich muss zugeben, dass ich auch nach dem 3.mal durchlesen nicht verstanden habe, was der Kern des Pudels ist...

**Comment by xantippe** [comment]
vielleicht geht das in die Richtung?
https://github.com/contao/core/issues/7357

**Comment by mpunkt** [comment]
Eigentlich nicht.
Ich werbe ja dafür, dass der Teaser (egal ob im Artikel, News, Event) als Contentelement (eines oder mehrere) abgebildet wird und somit aus den Artikel-, News- oder Eventeinstellungen ganz verschwindet.

Damit könnte man auch klar festlegen was als Überschrift des Artikels, sowohl in der Teaser als auch Vollansicht, verwendet werden soll. Die Überschrift wäre also vom Artikeltitel entkoppelt. Insofern besteht durchaus eine Verbindung zu #7357.

**Comment by xantippe** [comment]
Vestehe ich Dich richtig, Du möchtest ein FE-Modul "Teaser" bzw. ein CE_Teaser haben, in dem
1.) der Teasertyp ausgewält werden kann (News, Events, Artikel...)
2.) von welchen Elementen was angezeigt wird - Auswahl des/der News, Events, Artikel
3.) Ausgabeparameter wie Sortierung o.ä.

?

**Comment by mpunkt** [comment]
Nein, kein FE-Modul und auch kein CE_Teaser. Für den Teaser möchte ich ganz normale CEs verwenden. Die CEs müssten lediglich mit einem zusätzlichen Optionsfeld (Spaltenname in tl_content  z.B. useASTeaser) versehen werden, in dem ich bestimmen kann, ob das jeweilige Element im Teaser verwendet werden soll oder nicht.

Zum Rendern eines Teasers wähle ich dann die CEs mit "SELECT * FROM `tl_content` WHERE `pid` = <ArtikelID> AND `ptable` = 'tl_article' AND `useAsTeaser` ORDER BY `sorting`".

Zum Rendern des ganzen Artikels "SELECT * FROM `tl_content` WHERE `pid` = <ArtikelID> AND `ptable` = 'tl_article' AND NOT `useAsTeaser` ORDER BY `sorting`"

Wenn useAsTeaser nicht Boolean sondern vom Typ Char wäre, könnte man auch noch festlegen, ob ein CE sowohl im Teaser als auch im Artikel verwendet wird.
useAsTeaser = 0: Das CE wird nur im Artikel verwendet.
useAsTeaser = 1: Das CE wird nur im Teaser verwendet.
useAsTeaser = 2: Das CE wird im Artikel un im Teaser verwendet.

**Comment by xantippe** [comment]
Bei einem Artikel soll das dann i.E. so aussehen
* Artikel 1
** CE 1
** CE 2 [useAsTeaser]
** CE 3

Fragen: 
* was ist wenn mehrere CEs als Teaser markiert sien?
* was ist mit CEs, die per Inserttag oder CE_Inhaltselement in einem anderen Artikel landen?

... hast Du mal getestet, ob man einen CE per Inserttag in den Teaser des Artikels "werfen" kann?

**Comment by mpunkt** [comment]
Ja genau so sollte es aussehen. Den Teaser hole ich mir bereits per {{insert_content}}.

Aber du hast recht: Wenn CEs per Inserttag in anderen Artikeln landen gibt es Probleme :(

So reduziert sich meine Wunschliste auf einen Punkt:
Der Teaser in den Artikeleinstellungen sollte um "Ein Bild hinzufügen" erweitert werden.

**Comment by xantippe** [comment]
für das Bild gibt es eine Erweiterung...

**Comment by Aybee** [comment]
> Aber du hast recht: Wenn CEs per Inserttag in anderen Artikeln landen gibt es Probleme :(

Wieso sollte das Probleme geben? Mit insert_content sage ich ja explizit dass ich dieses CE includen möchte, da wäre der Status also egal, und mit insert_article kann ja beim Includen der Status berücksichtigt werden, also nur CEs ohne den Status "teaser only" ausgeben.

Ich arbeite zwar selten mit Teasern und Artikeln (meist nur mit News und Events), finde das Konzept aber durchaus Wert überdacht zu werden. Besonders gefällt mir, dass man in der CE-Auflistung direkt die Teaserinhalte sehen würde, man direkt einen Teil der CEs als Teaser deklarieren kann und z.B. auch ein Video u.a. in den Teaser stellen kann. Rein visuell müsste der Teaserstatus bereits in der Auflistung der CEs ersichtlich sein, nicht erst, wenn ich ein CE öffne.

Ich hatte dein Anliegen übrigens anhand des ersten Posts verstanden, würde aber den Titel des Threads ändern in "Feature: CEs als Teaser deklarieren" o.ä..

**Comment by mpunkt** [comment]
xantippe: Ich bin nicht so ein Freund davon, für Dinge, die eigentlich in den Core gehören, eine Erweiterung zu installieren. Übergangsweise mag das eine Lösung sein, auf Dauer aber eindeutig nicht. Die Sonderbehandlung von Artikelteasern im Vergleich zu News kann ich eigentlich verstehen.

Aybee: Danke dass Du Gefallen an meinem Vorschlag findest. Ich habe den Titel geändert. Wie ich in meinem ersten Post andeutete, hätte ich auch viel lieber mit Nachrichten gearbeitet. Leider kann ich das aus den genannten Gründen nicht machen.

**Comment by xantippe** [comment]
wären den mehrer CEs als Teaser-Kennzeichnung erlaubt? - Wenn nicht, müsste man bei den CEs immer auf unique zu pid und ausAsTeaser prüfen 
oder
man macht die Auswahl in die Artikeleigenschften und bestimmt an der Stelle das "Teaser-CE"

**Comment by mpunkt** [comment]
Es sollten ganz klar mehrere erlaubt sein. Ich möchte den Teaser ja so flexibel wie möglich gestalten können.

**Comment by mpunkt** [comment]
Bei einer Realisierung in Contao x.x.x wäre natürlich ein etwas größeres Datenbankupdate fällig. Aber auch das stelle ich mir nicht allzu kompliziert vor: In Schritt 1 würde ich aus allen tl_article.teaser != NULL Text-Contentelemente machen. In Schritt 2 käme dann ein ALTER TABLE um die überflüssigen Spalten in tl_article zu löschen. Gleiches mache ich mit tl_news und tl_calendar_events.
