### ISSUE TITLE
Newsletter Funktion "mehrere bearbeiten" wirft "Es ist ein Fehler aufgetretten"

### ISSUE THREAD

**Issue by garyee** [contao/core#7570]
Contao Version: 3.4.0

Steps to reproduce:

1. zwei Newsletter-Verteiler anlegen
2. Einen Abonenten in Newsletter-VerteilerA anlegen
3. Einen Benutzer anlegen
4. Dem Benutzer alle Rechte geben
5. Als Benutzer einloggen und in dem Newsletter-Verteiler A auf "mehrere bearbeiten" klicken.
6. Den Abonenten markieren und auf verschieben drücken
7. In Newsletter-Verteiler B gehen und auf das einfügen icon klicken.
... "Es ist ein Fehler aufgetretten"

**Comment by Samson1964** [comment]
An solche Fehler habe ich mich inzwischen gewöhnt. Teilt man einem Benutzer neue Rechte zu und testet diese gleich aus, kommt z.B. beim Erstzugriff auf die Dateiverwaltung auch "Es ist ein Fehler aufgetreten". Wenn man das zweite Mal klickt, ist alles in Ordnung. Aber unerfahrene Benutzer klicken  nie ein zweites Mal, sondern melden sich bei mir, es geht nicht.

Letztens hatte ich diese Meldung auch bei der Modul-Entwicklung. Da lag es daran, daß ich in der config.php die Datenbanktabelle nicht eingetragen hatte, auf die ich gerade zugreifen wollte.

**Comment by garyee** [comment]
Das ist ja gut das man sich an Fehler gewöhnen kann, könnte ich vielleicht auch bei Fehlern die man durch ein zweites Mal klicken lösen kann. Nur das dies nicht einer dieser Fehler ist :(
Und es ist auch kein Bug der durch eine eigene Erweiterung kommt, alles nur Contao-Bordmittel.

**Comment by aschempp** [comment]
Habe das eben in der Demo probiert. Habe den Testbenutzer zum Admin gemacht, und keine Probleme. Oder was meinst du mit "Alle Rechte geben"? Hast du eine Benutzergruppe angelegt?

**Comment by garyee** [comment]
"Alle Rechte geben" heißt bei den Berechtigungen des Benutzers einfach alles anhaken.
(die erforderlichen Newsletter Berechtigungen reichen eigentlich, aber zu sagen "Alles" ist einfacher und schließt aus das man vergisst den entscheiden Haken zu setzten)

Ja beim Admin gehts, aber das ist leider nur eine temporäre Lösung bei einem produktiven Einsatz.

**Comment by aschempp** [comment]
Ok, so kann ich es reproduzieren. Das liegt daran, dass verschieben von Empfängern eigentlich nicht vorgesehen ist. Deshalb gibt es in der Empfängerliste auch keinen blauen Verschieben-Button.

Zwei Möglichkeiten (@leofeyer):
 - Wir bauen die Verschieben-Funktion ein, könnte man imho auch im hotfix. Die Copy-Funktion sollte dann auch zum Clipboard werden.
 - Wir deaktivieren die Verschieben-Funktion im Edit-All Mode. Dann sollte man aber eigentlich auch das Kopieren deaktivieren, denn das macht ja noch weniger Sinn.

Ich wäre für Option 1. Kann für beides gerne einen PR stellen :-)

**Comment by leofeyer** [comment]
Die Verschieben-Funktionalität ist nicht aus technischen sondern aus rechtlichen Gründen bei den Newsletter-Empfängern nicht verfügbar. Beim Double-Opt-In-Verfahren bestätigt ein Abonnement das Abonnement eines bestimmten Channels. Ein Verschieben in einen anderen Channel müsste also wieder seitens des Abonnenten per Double-Opt-In bestätigt werden.

Daher kommt nur Option 2 in Frage.

**Comment by aschempp** [comment]
Ok, dann müsste aber auch der Copy-Button entfernt werden oder?

**Comment by leofeyer** [comment]
Ich weiß es nicht. Es gibt ja auch die Möglichkeit, Empfänger manuell anzulegen. Wir müssten hier mal klären, wie die aktuelle Rechtslage wirklich ist.

**Comment by aschempp** [comment]
Die weltweite Rechtslage? ;-)

**Comment by leofeyer** [comment]
Die deutsche sollte reichen. Zumindest wird ja immer gesagt, dass große Unternehmen wie Google Ihre Datenschutz-Bestimmungen in Deutschland prüfen lassen und wenn sie dort bestehen, reichen sie für den Rest der Welt auch ;)

**Comment by aschempp** [comment]
Naja, aber dafür kann ein Amerikaner nicht mehr kopieren obwohl es dort erlaubt ist… ich weis nicht ob die Einschränkung auf ein bestimmtes Land sinnvoll ist.

**Comment by christianromeni** [comment]
Entschuldigung.. Aber die Rechtslage sollte doch eigentlich Wurst sein....
Sonst müsste auch bei jeder Contao Seite ein Impressum mit erstellt werden.

Ich würde sagen, das wenn ein Benutzer sein Contao nicht so verwendet wie es die Rechtliche Situation erlaubt, ist das Sein Problem, und nicht das von Contao..

Gleiches gilt übrigens auch für die Vorname/Nachname Felder beim Newsletter.... Ob die nun verwendet werden oder nicht, kann Contao egal sein, das ist lediglich Benutzer-Entscheidung.

**Comment by Samson1964** [comment]
Da stimme ich Christian zu. 
Das Newsletter-Modul ist zuallererst reine Technik, die zu allem Möglichem verwendet werden kann. Das muß nicht ein Newsletter sein, wozu ich ein Newsletter-Modul gebrauche. Erst wenn der Benutzer eine bestimmte Anwendung damit umsetzt und diese öffentlich macht, muß er sich an Regeln halten. Falls es überhaupt welche gibt. Wenn ich bei der Newsletter-Anmeldunge dem Besucher mitteile, daß seine Daten so und so verwendet werden, muß ich als Benutzer auch die Möglichkeit haben dies zu tun.

Deshalb: Das Kopieren/Verschieben von Datensätzen gehört einfach zur Grundfunktionalität.

**Comment by garyee** [comment]
Ich schließe mich dem an, würde aber auch ohne die Funktionen überleben.
Am 21.01.2015 16:46 schrieb "Frank Hoppe" <notifications@github.com>:

**Comment by fritzmg** [comment]
Ich finde auch, dass sich technische Funktionalitäten in Contao sich nicht auf die rechtliche Situation in Deutschland festfahren sollten. In so fern wäre es auch begrüßenswert, wenn das Newsletter Modul eigentlich nur die _option_ für Double Opt-In hat und nicht zwingend vorgibt.

**Comment by leofeyer** [comment]
Wie am 29. Januar auf Mumble besprochen werden wir die bestehende Beschränkung im nächsten Feature-Release aufheben und kopierte oder verschobene Empfänger als "manuell angelegt" markieren.

**Comment by christianromeni** [comment]
Gilt das dann auch für Vorname/Nachname Felder in der Newsletter Anmeldung?

**Comment by frontendschlampe** [comment]
Es gilt für den Eintrag in der Empfängerliste eines Newsletters. Die Empfängerliste enthält **NUR** die E-Mail-Adresse und eine Checkbox für aktiviert/deaktiviert. Vorname und Nachname sind nicht enthalten und können somit auch nicht dupliziert werden.

**Comment by christianromeni** [comment]
Jo... Meine Hoffnung war, dass diese Felder hinzugefügt werden können... Denn der Umweg über die Mitglieder ist naja.... Und auch wenn E-Mail Adresse das einzige ist was man Pflichtfeld machen darf.. Spricht doch nichts dagegen das man andere Informationen auch abfragt.

**Comment by frontendschlampe** [comment]
Das ist leider erstmal nicht vorgesehen.

**Comment by leofeyer** [comment]
Geändert in 33bf503bd61358f7968b6bb07b74ada2bf313046.
