### ISSUE TITLE
[3.2.16] install tool crashes after database scheme update / deleted localconfig.php / missing class Database\

### ISSUE THREAD

**Issue by bezin** [contao/core#7571]
Hei there, 

I have a problem with a contao installation (3.2.16), which was already running for two years without any problems. I updated the database schema for a custom model and run the install tool. After that, I'll be promted with a white screen, finding the following error in the log file: 

```
[15-Jan-2015 11:55:49 GMT] PHP Fatal error:  Class 'Database\' not found in ...\system\modules\core\library\Contao\Database.php on line 160
```

Contao Check says, everythings fine. I deactivated all custom modules. 

I don't know, why the install tool crashes, but I found out that #7412 is the same issue and the following suggestion of @leofeyer solves my problem: https://github.com/contao/core/issues/7412#issuecomment-63320741

Did somebody else already experience this issue in 3.2.16?

**Comment by bezin** [comment]
I tracked the issue down to system/config/initconfig.php. I used the bottom snippet from http://www.contao.glen-langer.de/Anzeige_nur_Admins.html to hide system messages from everybody but admins:

[code]
// initconfig.php
if (!\BackendUser::getInstance()->isAdmin)
{
    foreach ((array) $GLOBALS['TL_HOOKS']['getSystemMessages'] as $k => $arrHook)
    {
        if ($arrHook[1] == 'versionCheck')
        {
            unset($GLOBALS['TL_HOOKS']['getSystemMessages'][$k]);
        }
    }
}
[/code]

The first line of code causes the (wrong) "Database\" class to be loaded, when the install.php includes initconfig.php

**Comment by bezin** [comment]
For documentary purposes: Since that problem occurs, if no database driver has been set, simply use the following snippet instead: 

´´´php
if (!empty($GLOBALS['TL_CONFIG']['dbDriver']) && !\BackendUser::getInstance()->isAdmin)
{
    foreach ((array)$GLOBALS['TL_HOOKS']['getSystemMessages'] as $k => $arrHook)
    {
        if ($arrHook[1] == 'versionCheck')
        {
            unset($GLOBALS['TL_HOOKS']['getSystemMessages'][$k]);
        }
    }
}
´´´

Successfully tested with Contao 3.2.16

**Comment by BugBuster1701** [comment]
Thanks, I've updated my snippet.

**Comment by bezin** [comment]
You are welcome, thanks for taking care :)
