### ISSUE TITLE
[3.3.x] Cursor Pointer im Uploadfeld deklarieren

### ISSUE THREAD

**Issue by akroii** [contao/core#7573]
Nur ein kleines Problem, stiftet aber trotzdem etwas Verwirrung beim Kunden. Wenn man in der Dateiverwaltung im Uploader eine Datei hochladen will muss man das über die Textfläche "Hier klicken oder Dateien ablegen" erledigen. Wenn man mit der Maus drüberfährt sollte statt dem Mausicon `cursor:text;` ein `cursor:pointer;` kommen. 
Das ist logischer.

Kann man die Klickfläche noch grün hinterlegen? So das der Nutzer instinktiv weiß das hier eine Aktion gefordert ist?

Es handelt sich bei dem Problem um den "DropZone" Uploader

**Comment by leofeyer** [comment]
Was genau meinst Du? `cursor:pointer` ist bereits gesetzt:

https://github.com/contao/core/blob/master/system/themes/flexible/src/main.css#L1548

**Comment by akroii** [comment]
Seltsam, die Auszeichnung ist an sich richtig gesetzt - wird aber nicht aufgerufen.
Getestet in Firefox 35.0,Chrome 39.0,Opera 26.0 bei Contao 3.3.7

Wäre es nicht sinnvoller den `cursor:pointer` bei `dz-message span` zusetzen?

**Comment by leofeyer** [comment]
Warum sollte das sinnvoller sein? Der gesamte Bereich lässt sich ja anklicken und nicht nur der Text.

**Comment by akroii** [comment]
Ist der Bug nur bei mir? Dort wo jetzt steht "Hier klicken oder Dateien ablegen" wird bei mir kein Cursor:Pointer dargestellt, sondern ein Cursor:text. 
Ich hab es jetzt nocheinmal auf dem Mac im Safari 8.0.2 getestet. Das gleiche Problem.

**Comment by leofeyer** [comment]
Wie lässt sich das in der Onlinedemo reproduzieren?

**Comment by akroii** [comment]
Fehlalarm, mein Problem liegt in der Erweiterung smart_backend_theme. Dort ist die Darstellung nicht korrekt. In den Systeminternen Backend-Themes von Contao (default & flexible) ist alles in Ordnung.
