### ISSUE TITLE
testability broken

### ISSUE THREAD

**Issue by dtomasi** [contao/core#7578]
If I test my Contao-Console application against the core by running the `system/initialize.php` it will break my tests since release 3.3.*. In my case the core lays in the `vendor` directory where `TL_ROOT . '/vendor/autoload.php'` does not exist. I think the `system/initialize.php` should have the ability to be called from everywhere.

https://github.com/contao/core/blob/master/system/initialize.php#L110

Please check first if `TL_ROOT . '/vendor/autoload.php'` exists.

**Comment by aschempp** [comment]
You can symlink the root vendor folder into contao/core to fix this.

**Comment by dtomasi** [comment]
This does not the trick. My Application do a Build and following Test against the packagist package of `contao/core`. So the build-server loads the core via `composer install --prefer-dist --no-interaction` into `vendor`. Then I run `vendor/bin/phpunit tests/*`. Of course, there is a chance to create the symlink between these 2 steps. 

Is `vendor/autoload.php` a required dependency of contao?  If not, I think contao should have the ability to run the `system/initialize.php` also without.

here is my `composer.json`.
```
{
    "name": "dtomasi/contao-console",
    "description": "Console Application for Contao CMS",
    "type": "library",
    "authors": [
        {
            "name": "Dominik Tomasi",
            "email": "dominik.tomasi@gmail.com"
        }
    ],
    "require": {
        "symfony/console": "2.5.*"
    },
    "require-dev": {
        "contao/core": "3.2.*",
        "phpunit/phpunit": "3.7.*"
    },
    "bin": [
        "bin/cc"
    ],
    "autoload": {
        "psr-4": {
            "ContaoConsole\\": "src/",
            "ContaoConsole\\Tests\\": "tests/"
        }
    }
}
```

**Comment by dtomasi** [comment]
Ok, I tested to create a symlink in my build-script between building and testing. This works for me: `ln -s -r vendor/autoload.php vendor/contao/core/vendor/autoload.php`

**Comment by aschempp** [comment]
Contao 3.3+ does use Composer for dependencies, so the whole vendor folder should be available. Not saying they're necessary for your tests though…

Here's what I built this week to get Contao running on Travis CI: https://github.com/isotope/core/blob/hotfix/2.2.1/.travis.yml

**Comment by leofeyer** [comment]
Can I close this ticket?

**Comment by dtomasi** [comment]
Yes, I found a working solution with a little help form @aschempp. Thanks

**Comment by discordier** [comment]
Follow up link to the now broken link by @aschempp: https://github.com/isotope/core/blob/master/.travis.yml
