### ISSUE TITLE
Looks like the RSS-Reader Module (tested 3.2/3.4) makes trouble.

### ISSUE THREAD

**Issue by ciaobello** [contao/core#7579]
I tried to create a rss feed and integrated it on the page over the module as it is made on the online Demo. Unfortunately it not displays anything.
On the demo the RSS Feed button displays a empty page too.

I tryed to change the path > http://contao.org/share/news-en.xml >https:// 
no changes.

**Comment by leofeyer** [comment]
How do I reproduce this in the online demo?

**Comment by ciaobello** [comment]
click on rrs feed in the header (Icon top right). This should be a module who displays  http://contao.org/share/news-en.xml.

**Comment by ciaobello** [comment]
I checked the server error log, gives following message if i access my page with the rss-reader module included:

[Tue Jan 20 19:49:48 2015] [error] [client 80.74.145.10] mod_security: Access denied with code 406. Pattern match "(WBSearchBot|SimplePie|AcoonBot|Sogou|PycURL|SearchmetricsBot|Fever|jjBot)" at HEADER("USER-AGENT") [severity "EMERGENCY"] [hostname "example.com"] [uri "/share/contao_lts.xml"] 

Contao 3.2.16
You get the same error on demo.contao.org?

**Comment by leofeyer** [comment]
No, I don't. We are not using mod_security on demo.contao.org. Our RSS feed reader is in fact SimplePie, which matches the pattern defined in the rule.

```
(WBSearchBot|SimplePie|AcoonBot|Sogou|PycURL|SearchmetricsBot|Fever|jjBot)
```

Therefore access is denied by mod_security, which is not a Contao bug. Your server administrator should be able to help you.

**Comment by ciaobello** [comment]
COD displays just a blank screen too on the RSS feed.
Should i open a issue for the Online Demo?

**Comment by leofeyer** [comment]
What exactly did you do in the online demo?

**Comment by ciaobello** [comment]
As it not worked on my Website i made tests there too. It Contao appears the same error as i got in my Contao > Error importing RSS feed "http://contao.org/share/news-en.xml"
I just tried to change http: to https: with no changes for the result. For me it looks like that on demo.contao.org also a security rule or similar is active.

On my page it works now. The provider gave me a hint to solve, with deactivate the mod_security. I made a entry in the German forum to solve: 
rss reader (simplepie) | weisse Seite | Serverlog Error 406 > Workaround

**Comment by bastlwastl** [comment]
Ich habe das gleiche Problem und dieses ist auch auf der Demoseite nachzustellen.
Wenn man ein RSS-Reader Modul anlegt und die Feed-Url der Contao Seite eingibt (https://contao.org/share/news-de.xml), dann wird der Feed im Frontend ausgegeben.
Wenn ich aber unseren Feed, der auch über eine Contao Installation generiert wurde, eingebe wird weder der Feed noch die Überschrift des RSS-Reader Moduls ausgegeben.

Unser Server Administrator sagt, dass es keine Serverseitige Sperre gibt und das Problem bei der Contao-Installation zu suchen ist.

**Comment by leofeyer** [comment]
What are the exact steps to reproduce this in the online demo?

**Comment by bastlwastl** [comment]
Ich hoffe es ist in Ordnung wenn ich die einzelnen Schritte in deutsch schreibe.

Ich war gerade dabei die einzelnen Schritte zu dokumentieren und warum auch immer... jetzt mit den gleichen Schritten funktioniert die Ausgabe des Feeds auf der Demo-Seite sowie auf unserer Seite.

Ich werde die Sache mal beobachten und melde mich sobald das Problem wieder auftreten sollte.
