### ISSUE TITLE
Blockstruktur für searchable ungünstig

### ISSUE THREAD

**Issue by markknochen1** [contao/core#7580]
Meines Erachtens ist die Blockstruktur in der jetzigen Form ungünstiger, als es im alten Contao der Fall war. Zumindestens die Überschrift h1 sollte wieder zurück in die eigentlichen Templates wandern. Ich habe immer wieder den Fall, dass ich eigene Ausgabetemplates bauen muss, auch u.U. für die Templates ce_image usw. Wenn die Überschrift der Module aber übergeordnet ist, baue ich mir im Template block_searchable einen Wolf mit mehreren Abfragen nach bestimmten CSS Klassen, um dort zu ermitteln, zu welchem CE der Block nun gerade gehört.

Auch das verschieben der Überschrift geht nun nicht mehr so einfach, weil die Überschrift im eigentlich Template ja nun gar nicht mehr vorhanden ist.

Oder denke ich da zu verquer? Das jetzige Verhalten erinnert mich ungut an Typo3 wo das ähnlich und noch viel ausgeprägter so gemacht wird.

**Comment by aschempp** [comment]
> Oder denke ich da zu verquer?

Ja tust du. Du kannst die Block-Vererbung einfach entfernen und alles ins selbe Template schreiben ;-)

**Comment by Gruenfisch** [comment]
Hallo Andreas

Gibt es für deinen Ansatz irgendwo ein Beispiel?

Danke und lieben Gruß, Oliver
