### ISSUE TITLE
[C 3.4.0] TinyMCE 4 Link einfügen: Dateiwähler speichert Pfad

### ISSUE THREAD

**Issue by mpunkt** [contao/core#7581]

**Comment by leofeyer** [comment]
?

**Comment by mpunkt** [comment]
Ich dachte der Titel sei eindeutig. Ich Gegensatz zum Bild einfügen wird beim Link einfügen der Pfad eingesetzt. Mir würde es gefallen wenn man den in {{file::}} übersetzen könnte.

**Comment by leofeyer** [comment]
Geändert in dab077955ab87d009793cd36350a7a20a2549932.
