### ISSUE TITLE
DCA files check the permissions in the wrong way.

### ISSUE THREAD

**Issue by discordier** [contao/core#7585]
All the HOOKs for dca files assume they are within the only DC that is being loaded via page impression.
When dc-general is in use, we load all the data containers referenced and instantiate the DCs as needed for inter DC communication.

All the HOOKs must check if the module (`\Input::get('do')` and `\Input::get('table')`) are intended for the check permission HOOK or not and accordingly exit when they are not meant.

The problem is for example in https://github.com/contao/core/blob/0b3636ef2430e6ad3510dca8bdf839e962395161/system/modules/core/dca/tl_page.php#L663 where the only check is for admin.
Assuming an URL like `contao/main.php?do=page&table=mm_references&act=edit&id=mm_references::5` when dc-general is loading the parent table DC for detecting it's environment, the check runs up to https://github.com/contao/core/blob/0b3636ef2430e6ad3510dca8bdf839e962395161/system/modules/core/dca/tl_page.php#L801 where the id `mm_references::5` of course is unknown to the tl_page (it originates from `mm_references` anyway).

IMO this is a bug and therefore has to be fixed in the LTS.
I am willing to provide a PR to LTS within the next days.

Ref: MetaModels/core#708

**Comment by leofeyer** [comment]
> I am willing to provide a PR to LTS within the next days.

Yes, please. Should we discuss the approach beforehand so you don't do unnecessary work?

**Comment by discordier** [comment]
I am free to do so, but IMO it will be enough to check the above mentioned query parameters for the correct module and table name. If either mismatches, exit the check.

Do you want to mumble?

**Comment by discordier** [comment]
IMO we should an check for all core tables in the same manner as in https://github.com/contao/core/blob/5d878de67eb218d5eb7ba967dbc669859b8489ec/system/modules/core/dca/tl_content.php#L829.

In contrast to adding it as inline check in the dca file I'd rather push it to the top of the checkPermission() method. i.e. for `tl_page::checkPermission()`:
OLD:
```php
if ($this->User->isAdmin)
{
	return;
}
```
NEW:
```php
if ($this->User->isAdmin || (\Input::get('do') !== 'page'))
{
	return;
}
```

What do you think about this @leofeyer.

**Comment by discordier** [comment]
As discussed on mumble this will be added to 3.5 and implemented as mentioned above for all check permission hooks in all core DCA files.

**Comment by leofeyer** [comment]
@discordier What is the status of this PR? I know that we have discussed it another time after the Mumble call but I don't remember.
