### ISSUE TITLE
Contao 3.4.1 archive corrupt?

### ISSUE THREAD

**Issue by ben-eSM** [contao/core#7588]
A clean installation of 3.4.1 isn't possible. Installer throws quite a few PHP Notices like ``Undefined index: SSL_SESSION_ID``. Even when ignoring them and installing, Contao seems to be corrupt. Trying to create a directory ends in a fatal error.

The Contao 3.4.0 archive however works well. So must be something messed up in the 3.4.1 package.

**Comment by leofeyer** [comment]
Please run the Contao check.

**Comment by ben-eSM** [comment]
Contao check runs well. No issues found and it even validates the installation.

But the mentioned problems remain. Seems to be something wrong with the archive.

**Comment by leofeyer** [comment]
Try commenting line 97 in `system/initialize.php`:

```php
// Before
set_error_handler('__error', Config::get('errorReporting'));

// After
//set_error_handler('__error', Config::get('errorReporting'));
```

**Comment by ben-eSM** [comment]
Doesn't solve the problem. Sure, the notices aren't displayed. But there should be none anyway, as 3.4.0 shows also none on my server.

After installing, I get the mentioned fatal error again, when trying to create a directory.

```
PHP Fatal error:  Maximum function nesting level of '100' reached, aborting! in /var/www/vhosts/s390501649.online.de/httpdocs/testground/buerk.esales-media.de/contao-3.4.1/system/modules/core/library/Contao/Validator.php on line 297
```

**Comment by leofeyer** [comment]
Do you have any third-party extension installed?

**Comment by ben-eSM** [comment]
I have no extensions installed. It's a clean fresh vanilla installation I want to set up.
And 3.4.0 and some 3.2.x installations work fine on the server.

**Comment by Toflar** [comment]
@leofeyer Regarding the notices: https://github.com/contao/core/blob/master/contao/install.php#L19-L20

**Comment by leofeyer** [comment]
Please try to replace line 66 in `system/modules/core/models/FilesModel.php`:

```php
// Old
return static::findOneBy('id', $intId, $arrOptions);

// New
return static::findBy('id', $intId, $arrOptions);
```

**Comment by leofeyer** [comment]
The error message points to an xdebug issue:

http://stackoverflow.com/questions/8656089/solution-for-fatal-error-maximum-function-nesting-level-of-100-reached-abor

Please try disabling xdebug or increase the nesting level: `xdebug.max_nesting_level=500`

**Comment by discordier** [comment]
It indeed is xdebug, but I wonder why we reach a recursion level of 100?
What is going on in the file system there?

**Comment by leofeyer** [comment]
No idea. Maybe we'll get another error message once xdebug has been disabled?

**Comment by ben-eSM** [comment]
Xdebug was already disabled i thought, yet I have commented out the xdebug extension completely. Didn't solve the issue. The fatal error changed to an allowed memory size exhausted one. But I think 128MB should be sufficient to create a directory. :)

However, if I make your proposed changes in `system/modules/core/models/FilesModel.php` it works.

**Comment by leofeyer** [comment]
> However, if I make your proposed changes in `system/modules/core/models/FilesModel.php` it works.

I figured. The change probably leads to an infinite loop somewhere :(

**Comment by discordier** [comment]
Doubt it.
@ben-eSM could you please put the following in `system/modules/core/library/Contao/Validator.php` just before line 297 so that the method should read:
```php
public static function isBinaryUuid($varValue)
{
	$e = new \Exception(); echo '<pre>' . $e->getTraceAsString() . '</pre>';
	if (strlen($varValue) == 16)
	{
		return ($varValue & pack('H*', '000000000000F000C000000000000000')) === pack('H*', '00000000000010008000000000000000');
	}

	return false;
}
```
Be warned, this will dump a whole lot of trace blocks.
We need the block just before the fatal error.

**Comment by ben-eSM** [comment]
I'll try to get you the block. The Output is so long that it crashes Chrome. Maybe Firefox can handle the amount.

But from the little I can tell before it crashed, there's a lot of `FilesModel` recursion going on.

**Comment by leofeyer** [comment]
I guess `findOneBy('id')` somehow recursively triggers `findById()` or vice versa, which is why xdebug throws the maximum nesting error.=

**Comment by ben-eSM** [comment]
Can't get the stack trace.

But yes, it seems like Leo said. findOneBy('id') seems to trigger findById().

**Comment by LeoUnglaub** [comment]
If your browser crashes, maybe you could `curl` it and pipe the output into a plain text file.

**Comment by discordier** [comment]
Ok, I guess I found it.
1. Start at: 
https://github.com/contao/core/blob/5d878de67eb218d5eb7ba967dbc669859b8489ec/system/modules/core/classes/Versions.php#L75-75
The pid is not an uuid here.
2. As the pk is 'id', we hop to: https://github.com/contao/core/blob/47b4fca94e394e6847f702c588b4ab5b65a1f08a/system/modules/core/models/FilesModel.php#L44-44
3. As the id is still no uuid, we now hop to: 
https://github.com/contao/core/blob/47b4fca94e394e6847f702c588b4ab5b65a1f08a/system/modules/core/models/FilesModel.php#L66-66
4. Now we are Model.php where we have no options at all and therefore try to load at https://github.com/contao/core/blob/5d878de67eb218d5eb7ba967dbc669859b8489ec/system/modules/core/library/Contao/Model.php#L799-799
5. This redirects back to: https://github.com/contao/core/blob/47b4fca94e394e6847f702c588b4ab5b65a1f08a/system/modules/core/models/FilesModel.php#L44-44
6. Continue with 3.

**Comment by leofeyer** [comment]
Exactly. The question is now how to fix it.

Option 1: Force the return value to be a model even though we are calling `findBy`:

```php
// FilesModel::findById()
if (\Validator::isUuid($intId))
{
	return static::findByUuid($intId, $arrOptions);
}

if (!isset($arrOptions['return']))
{
	$arrOptions['return'] = 'Model';
}

return static::findOneBy('id', $intId, $arrOptions);
```

Option 2: Remove the `return static::findByPk($intId, $arrOptions);` from `Model::findOneBy()` and use `find` instead:

```php
// Try to load from the registry
if (empty($arrOptions))
{
	if (is_array($strColumn))
	{
		if (count($strColumn) == 1 && $strColumn[0] == static::$strPk)
		{
			// Use find here
			//return static::findByPk($intId, $arrOptions);
		}
	}
	else
	{
		if ($strColumn == static::$strPk)
		{
			// Use find here
			//return static::findByPk($intId, $arrOptions);
		}
	}
}
```

**Comment by leofeyer** [comment]
Theoretical option 3: Apply `->current()` to the return value if it is not `null`:

```php
// FilesModel::findById()
if (\Validator::isUuid($intId))
{
    return static::findByUuid($intId, $arrOptions);
}

$objCollection = static::findBy('id', $intId, $arrOptions);

if ($objCollection !== null)
{
    $objCollection = $objCollection->current();
}

return $objCollection;
```

**Comment by Kahmoon** [comment]
Mit den Änderungen an der Datei Model.php geht bei mir die Dateiverwaltung wieder.
Ich kann Ordner erstellen und Dateien bearbeiten UND ich sehe bei Bildern die Bild-/Billdschwerpunktsansicht. Das war davor nicht der Fall.

VG und Danke!

**Comment by leofeyer** [comment]
Fixed in 455cd9d382f5f9aae0f7c5e3a8882c9033b2eef5.

**Comment by psren** [comment]
In der 3.2.17 ist das noch nicht gefixt, oder doch?

**Comment by fritzmg** [comment]
@psren : denke nicht, issue wurde zum 3.2.18 milestone hinzugefügt.
