### ISSUE TITLE
id in aliases

### ISSUE THREAD

**Issue by DVeris** [contao/core#7589]
<a target="_blank" href="http://fastpic.ru"><img src="http://i59.fastpic.ru/big/2015/0122/f4/a2e3f3d3f60b8c5af46fcdc667255ff4.jpg" border="0"></a>

i think it is a bug

**Comment by Toflar** [comment]
No it's not, an alias cannot start with a number.

**Comment by DVeris** [comment]
hm, why? :)
delete "id-" and save, and will be site.com/article/3-cars.html


id-3 it is not an id for this news
logicaly will be

id107-3-cars

107 it is a news id

**Comment by DVeris** [comment]
but i think must be "3-cars"
site.com/article/3-cars.html

**Comment by BugBuster1701** [comment]
see (german) https://github.com/contao/core/issues/82

**Comment by DVeris** [comment]
BugBuster1701, sorry, difficult to read on german

for example in joomla:
url
```
http://www.joomla.org/announcements/general-news/5580-joomla-offers-free-hosted-website-solution-on-joomla-com-in-partnership-with-siteground.html
```

**Comment by BugBuster1701** [comment]
which contao version do you use?

**Comment by DVeris** [comment]
3.2

**Comment by BugBuster1701** [comment]
The alias can be manually set to "3-cars" that works.
For historical reasons, it will still generate the "id-" Alias.
There were a logic problem with MySQL in older Contao versions.

*A pure number as an alias should be avoided, for example. With this number, there could be both. A page with the ID as an alias with this ID, but represent different pages.*

Perhaps it is possible to adjust the automatic generation of the alias.
(is_numeric: "id-...", else ....)

**Comment by Zeromax** [comment]
see #7236
