### ISSUE TITLE
`FrontendCron` controller: fatal error at the first run

### ISSUE THREAD

**Issue by xchs** [contao/core#7595]
The Contao 3.4.2 install tool throws an exception when running the first time:
```
PHP Fatal error: Uncaught exception 'Exception' with message 'Query error: Table 'contao_master.tl_cron' doesn't exist (SELECT * FROM tl_cron WHERE name='lastrun' LIMIT 0,1)' thrown in /system/modules/core/library/Contao/Database/Statement.php on line 293
#0 /system/modules/core/library/Contao/Database/Statement.php(262): Contao\Database\Statement->query()
#1 /system/modules/core/controllers/FrontendCron.php(129): Contao\Database\Statement->execute()
#2 /system/modules/core/controllers/FrontendCron.php(41): Contao\FrontendCron->hasToWait()
#3 /system/cron/cron.php(20): Contao\FrontendCron->run()
#4 {main}
```
Additionally, some other notices are shown on top of the page:
```
Notice: Undefined index: HTTP_X_FORWARDED_HOST in /system/modules/core/library/Contao/Environment.php on line 302

Notice: Undefined index: SSL_SESSION_ID in /system/modules/core/library/Contao/Environment.php on line 313

Notice: Undefined index: HTTPS in /system/modules/core/library/Contao/Environment.php on line 313

Notice: Undefined index: HTTPS in /system/modules/core/library/Contao/Environment.php on line 313
```

**Comment by leofeyer** [comment]
Table `contao_master.tl_cron` doesn't exist. Did you create all tables in the install tool?

**Comment by xchs** [comment]
It was the first run, so yes, no database tables at this point:

![install_tool_notices](https://cloud.githubusercontent.com/assets/1218766/5874422/85914d70-a301-11e4-8e6d-93f27ad68550.png)

But now I figured out that the exception only occurs if the back end login mask is (intentionally) opened before running the install tool.

To reproduce:

* Set up a new fresh installation
* Open the back end login mask `example.com/contao`
* Run the Contao install tool
* Check the Contao error log `system/logs/error.log`

I therefore assume that the error is expected when the back end login page is loaded before the installation process is completed.
