### ISSUE TITLE
Selectbox zum Umschalten von Subpaletten mit verschieden sprachigen Optionen

### ISSUE THREAD

**Issue by garyee** [contao/core#7597]
Ein Feature Request der an https://github.com/contao/core/issues/1156 anknüpft.

Es wäre sehr praktisch, wenn man die Selectboxen mit denen man subpaletten umschaltet, so gestalten könnte das man sie aus einem $GLOBALS['TL_LANG'] array "befüllen" kann.

Bsp:
Im Backend, es soll zwischen verschiedenen "Link-Typen" umgeschaltet werden können. Die Umschaltung eröffnet wieder jeweils andere Optionen. Es gibt z.B. external,internal(PagePicker) und file(fileTree). Nun wäre es ja gut wenn man das auch auf Deutsch haben könnte.

**Comment by discordier** [comment]
Aeh? Meinst du das hier?
```php
$GLOBALS['TL_DCA']['tl_foo']['fields']['bar'] = array
(
  'label'     => &$GLOBALS['TL_LANG']['tl_foo']['bar'],
  'exclude'   => true,
  'inputType' => 'select',
  'options'   => array_keys($GLOBALS['TL_LANG']['tl_foo']['bar_types']),
  'reference' => &$GLOBALS['TL_LANG']['tl_foo']['bar_types'],
  'eval'      => array
  (
    'includeBlankOption' => true,
    'submitOnChange'     => true,
  )
);
```

**Comment by garyee** [comment]
Ich weiß nicht ob ich das richtg sehe, aber entweder hat man dann 0,1,2,3,... zur Auswahl, oder die arrayKeys die dann aber pro Sprache nicht unterschiedlich sein werden. Und selbst wenn man die nur die jeweiligen Values nimmt, ist dann die Frage ob die "Verbindung" zu den jeweiligen Subpaletten noch geht.

**Comment by do-while** [comment]
warum guckst Du nicht in den Core, wie der das macht?
Beispiel aus tl_content.php

		'listtype' => array
		(
			'label'                   => &$GLOBALS['TL_LANG']['tl_content']['listtype'],
			'exclude'                 => true,
			'inputType'               => 'select',
			'options'                 => array('ordered', 'unordered'),
			'reference'               => &$GLOBALS['TL_LANG']['tl_content'],
			'sql'                     => "varchar(32) NOT NULL default ''"
		),

Übersetzungen für alle Sprachen stehen in den Texten, 'reference' weiß auch wo.

**Comment by discordier** [comment]
Wieso sollten die array keys pro Sprache unterschiedlich sein? Das macht doch keinen Sinn.
Allgemein magst du dir evtl. die Erweiterung meta-palettes ansehen. Die hat viel komplexeres Paletten handling.

**Comment by garyee** [comment]
Die Selectbox aus der tl_content.php schaltet leider keine Subpaletten um, weswegen es nicht relevant ist.

Habe aber jetzt den Fehler gefunden... der Schlüssel zum Erfolg ist das [__reference__](https://contao.org/de/manual/3.0/data-container-arrays.html#felder) keyword in der dca der Select-Box. (Und eine gute Benennung der felder bei komplizierteren Vorhaben)
Am besten zu sehen [hier](https://github.com/contao/core/blob/960155bf2c6225cdf2f3d2f21fb9ae9492f86a11/system/modules/news/dca/tl_news.php#L353)
