### ISSUE TITLE
loadDataContainer hook not executed when local cache is created

### ISSUE THREAD

**Issue by alarstyle** [contao/core#7600]
On frontend, when local cache is on and created, `loadDataContainer ` hook is not executed. But it works when there is no local cache.
I think, it must work same way in both situations.

**Comment by aschempp** [comment]
You must be wrong on that. If you check the code (https://github.com/contao/core/blob/master/system/modules/core/library/Contao/DcaLoader.php#L74-L99), the hook is always executed for both cases with or without cache.

**Comment by alarstyle** [comment]
But on frontend if cache is created dca files are not loaded, sql files are loaded instead.
You can see it in DcaExtractor.php _construct method.

**Comment by aschempp** [comment]
`DcaExtractor` is not loading a data container, it's loading model relation information. 
Maybe you can explain what you're trying to do?

**Comment by alarstyle** [comment]
`DcaExtractor` in `_construct` method has this code:
```
$this->strTable = $strTable;
$this->strFile = 'system/cache/sql/' . $strTable . '.php';

// Try to load from cache
if (!\Config::get('bypassCache') && file_exists(TL_ROOT . '/' . $this->strFile))
{
	include TL_ROOT . '/' . $this->strFile;
}
else
{
	$this->createExtract();
}
```

So `$this->createExtract();` will not be executed if there is local cache.

When I change the code to:
```
$this->strTable = $strTable;
$this->strFile = 'system/cache/sql/' . $strTable . '.php';

$this->createExtract();
```
`loadDataContainer` hook starts working.

**Comment by aschempp** [comment]
I'm aware of that because `createExtract` does call `\Container::loadDataContainer`, which in turn calls the hook. Maybe you actually need a `createExtract` hook, but then again read #5753.

PS: you still have not explained what you're trying to do.

**Comment by alarstyle** [comment]
I can explain what I'm doing, but it really doesn't meter for this issue I submitted :)
I'm checking dca for special value in fields array and if value exists I store field and table names in my array to use it later.

The thing is that `loadDataContainer` hook is not working. Please don't look at the code. Just test it on your local machine. :)

**Comment by aschempp** [comment]
Ok well, the hook is working perfectly fine, it's just not executed in this case because it's not supposed to be. Executing it would render the cache useless. 

I guess you should find another way to do what you want to do (e.g. call `\Controller::loadDataContainer` yourself), because the hook wont be called if noone calls `\Controller::loadDataContainer`

**Comment by alarstyle** [comment]
I don't agree.
For example I'm creating extension that do something important for frontend on `loadDataContainer`. And it works perfectly. But then I create local cache and it stops working.

So I think this hook must work when cache is created or must not work even when there is no cache. 
I'm talking about frontend only here.

**Comment by aschempp** [comment]
You're misunderstanding. 
`\DcaExtractor::__construct` !== "loadDataContainer", `\Controller::loadDataContainer` is the method you mean. 
The DcaExtractor is simply not calling *loadDataContainer* because it does not need to. If **you** need to load the datacontainer, you must call it yourself in your extension.

**Comment by alarstyle** [comment]
I understand what you are saying. 
But I was talking not about methods, but about logic of this hook execution.
Anyway if you don't think that this is a bug or a useful feature, you can close the issue.
