### ISSUE TITLE
/assets/js/html send 403

### ISSUE THREAD

**Issue by garyee** [contao/core#7601]
Hi,

wäre es nicht besser [hier] (https://github.com/contao/core/blob/master/assets/js/index.html) eine 403 zu senden?

**Comment by discordier** [comment]
noe, da diese html das directory listing deaktivieren soll und nicht den Zugriff auf den Inhalt des Verzeichnisses verbieten.
Sonst kommt ja keiner mehr an die js files ran. :)

**Comment by garyee** [comment]
naja das das könnte man doch auch über eine htaccess regeln oder ?

**Comment by discordier** [comment]
Klar, sowas koennte man durch ein `Options -Indexes` ggf. deaktivieren. Jedoch NUR DANN, wenn der Server Admin in seinen `AllowOverrides` selbiges auch erlaubt.
Eine .htaccess zu bauen die alle moeglichen Spezialfaelle abdeckt steht in keinem Verhaeltnis zu einer leeren index.html.

Hinzu kommt noch, dass mit Contao 4 und nginx die .htaccess Dateien alle entfallen werden. Es spricht also nichts dafyr nun eine einzubauen die wir hinterher wieder ausbauen und durch die selbe index.html ersetzen werden die wir aktuell schon haben und tadellos funktioniert.

Was genau stoert dich denn so arg daran dass es eine leere html ist?

**Comment by garyee** [comment]
Ah das mit dem rausfallen wusste ich nicht. So arg stört mich das jetzt nicht und wenn die eh alle wegfallen. :)

**Comment by xchs** [comment]
Dient u. a dazu, dass im Git Repository die Verzeichnisse auch tatsächlich angelegt werden (siehe die Diskussion in #7576)
