### ISSUE TITLE
DNS settings misses 'System URL' field

### ISSUE THREAD

**Issue by Sanderadio** [contao/core#7602]
Suppose you have site www.example.com and home.example.com that both use the same Contao installation. For the 'home'-site you need to set 'Domain name' under DNS Settings of the website root to 'home.example.com', Files URL and Assets URL to 'www.example.com'. But some files or assets are found under 'system/modules' (if you use extensions). Shouldn't there be also a 'System URL' field under DNS Settings to accommodate this? 

E.g.: I use the i18nl10n extension to change language, but the country flags etc. are not found for the 'home.example.com'-site. Also system/cron/cron.txt is not found.

Thanks, Sanderadio

**Comment by fritzmg** [comment]
I read your thread on the english community forum. I think the real question is: why are your assets not accessible via home.example.com ?

**Comment by Sanderadio** [comment]
@fritzmg Good question! I used DNS forwarding with CNAME to redirect traffic from home.example.com to www.example.com. Sites runs perfectly now, except for the images from third party extensions in the systems/modules folder.

**Comment by fritzmg** [comment]
This must be some sort of server misconfiguration. If you have a CNAME entry for your subdomain, plus an alias entry for that domain in your Virtual Host configuration for this webspace of your Apache, everything should work fine.

**Comment by Sanderadio** [comment]
I tried to set that in my .htaccess (since I don't have access to my Apache setting with my hosting provider). I tried

`<VirtualHost *>
  ServerName home.example.com
  Redirect 301 / http://www.example.com/
</VirtualHost>`

but that gives a 500 Internal Server Error.

**Comment by fritzmg** [comment]
No no, that's not what you should do. You need to find out how you can add the subdomain as a second domain for the same document root. What's your hosting provider?

**Comment by Sanderadio** [comment]
I am with one.com

**Comment by fritzmg** [comment]
Hm, I can't find any information how you would properly do it on one.com.

**Comment by Sanderadio** [comment]
And the problem can't be solved with a rewrite rule in `.htaccess`?

**Comment by fritzmg** [comment]
Maybe with something like this:
```
RewriteCond %{HTTP_HOST} ^example\.com$ [NC]
RewriteCond %{THE_REQUEST} ^[A-Z]+\ /+home/ [NC]
RewriteRule ^home/(.*)$ http://home.example.com/$1 [R=301,L]
```

**Comment by Sanderadio** [comment]
No, I still get the error that `/system/cron/cron.txt` and `/system/modules/i18nl10n/assets/img/flag_icons/en.png` can't be found.

**Comment by Aybee** [comment]
Is it possible to fake a host in the browsers address bar? I don't think so. So as soon as you see home.example.com in the address bar (that's what you want) it gets redirected to www.example.com. So how shoold this work?

**Comment by Sanderadio** [comment]
@Aybee Are you asking me or fritzmg?

**Comment by Aybee** [comment]
@Sanderadio and @all

**Comment by Sanderadio** [comment]
I don't know exactly what you mean by 'fake a host in the address bar'. That's why I use CNAME. Traffic will be redirected to `www.example.com` while the GET command still says `home.example.com`. So Contao knows the user would like to see the home-site instead of the www-site. Under Site Structure I therefore have set 'Domain name' of the website root to `home.example.com`.

**Comment by discordier** [comment]
You are mixing two things up here.

1. DNS and aliasing of hostnames on name server level.
2. HTTP and Name based vhosts on apache level.

DNS is ONLY responsible for translating a human friendly name (www.example.com and home.example.com) to IP adresses.
A CNAME simply tells: "Hey, the host named home.example.com has the same IP as www.example.com."

So now your browser knows: "When I want to talk to home.example.com, I have to check the DNS which IP has www.example.com and connect to there."
There your browser marches off and attempts to connect to the IP.
On that IP, apache is listening for requests but unfortunately it only knows about www.example.com (as configured in the apache config as <vhost> entry) and therefore responds with whatever the provider has configured as default page when accessing the root of the domain.
As your browser in this case wants to retrieve assets from system/modules which are, almost for sure, not available at the apache's default site, it will respond with 404.

**Comment by Sanderadio** [comment]
@discordier So basically you're saying you cannot use home.example.com with Contao?

**Comment by fritzmg** [comment]
You can, but you need to configure your webspace accordingly. It doesn't seem to be possible on one.com

**Comment by Sanderadio** [comment]
Too bad. But my site is working quite well now (at one.com) although the web browser gives the error:
`Failed to load resource: the server responded with a status of 404 (Not Found) http://home.example.com/system/cron/cron.txt`. 
If I leave out the Files URL and Assets URL (www.example.com) my site won't load its css and images. So back to my original question: shouldn't there be a 'System URL' field as well to load these specific assets (like cron)? 

And maybe it would be a good idea to write about this issue in the manual, so users know that they need a specific hosting proving with access to (and knowledge of!) vhosts.

**Comment by discordier** [comment]
There is no need for a system URL as the assets are added either via the assets URL or via the "home" url in code.

Your problem simply seems to be an incorrect configuration. Is everything working when you leave out all the URLs?

IMO there is no need to write this in the documentation as users in need of a hosting provider where they want to use vhosts most likely already know that the hosting provider has to support them.
It's like we would write that you need a hosting provider that provides hosting to host your website.

The approach you want to configure here is simply called name based vhosts, it is the configuration of routing multiple (sub-)domains into the same web root but appearantly your provider does not support to configure this. Therefore you will end up using the same domain for all content (assets & websites).
