### ISSUE TITLE
Out of memory

### ISSUE THREAD

**Issue by psren** [contao/core#7605]
Contao 3.2.17 (mit 3.2.16 geht das noch)

Ich habe 2Gb memory_limit, das sollte eigentlich reichen.
Ich vermute das hängt irgendwie mit #7588 zusammen.

```
Fatal error: Out of memory (allocated 490733568) (tried to allocate 65484 bytes) in system/modules/core/models/FilesModel.php on line 44
```

**Comment by leofeyer** [comment]
Siehe #7605.

**Comment by leofeyer** [comment]
Ich lasse das Ticket hier mal als Erinnerung zum Backport offen.

**Comment by leofeyer** [comment]
Behoben in 6e6f957c296ef262a2bdf050f604ec6efc82526a.
