### ISSUE TITLE
Inserttag um MetaTitle der aktuellen Rootseite zu bekommen

### ISSUE THREAD

**Issue by psren** [contao/core#7606]
Momentan gibt es folgende Inserttags

<table>
<tr><th>{{page::mainTitle}}</th><td>Dieses Tag wird mit dem Namen der übergeordneten Hauptseite ersetzt.</td></tr>
<tr><th>{{page::mainPageTitle}}</th><td>Dieses Tag wird mit dem Titel der übergeordneten Hauptseite ersetzt.</td></tr>
<tr><th>{{page::rootTitle}}</th><td>Dieses Tag wird mit dem Titel der Webseite ersetzt.</td></tr>
</table>

Dem Startpunkt vergebe ich meist einen Namen der für den Backendbenutzer/Kunden leicht zu verstehen ist.
z.B. **AcmeCompany [de]** für die Deutsch Sprachvariante
Beim Meta-Title trage ich dann ein was für den Frontendbenutzer erscheinen soll.

Das Logo baue ich als eigenes HTML ein.

```
<figure class="logo">
	<a class="logo__link" href="{{env::path}}">
		<img class="logo__image" src="/files/reich/logo.png" alt="{{page::rootTitle}}" />
	</a>
</figure>
```

Jetzt gibt ```{{page::rootTitle}}``` leider meinen nicht sehr Suchmaschinenfreundlichen Titel der Rootseite aus.
An den Meta-Title scheine ich nicht hinzukommen.
Für normale Seiten ist das ohne Probleme möglich.

**Comment by Aybee** [comment]
Das ist falsch. 
{{page::rootTitle}} = Name
{{page::rootPageTitle}} = Titel
@aschempp Andreas kannst du das bitte in der Doku ergänzen und korrigieren? https://contao.org/de/manual/3.4/managing-content.html#seiteneigenschaften

ps Du solltest besser ein CE oder einen Artikel includen z.B. {{insert_article::logo}}, denn Contao kann solche Bausteine ja bilden. Dann profitierst du automatisch von den neuesten Technologien, Barrierearmut, DB-Verwaltung des Bildes usw.,  es können sich auch keine Fehler im HTML einschleichen und das Element wird auch für den Kunden verwaltbar.

**Comment by aschempp** [comment]
@Aybee ist eingefügt

**Comment by Aybee** [comment]
Ah, haste mal bei der Feuerwehr gearbeitet? ;) Danke.

**Comment by psren** [comment]
:+1: 

Danke.
(Das mit dem Modul war nur ein Beispiel :-) und in dem Fall ist es meine eigene Seite, da muss es nicht für den Kunden pflegbar sein)
