### ISSUE TITLE
Fatal error while adding Website root page

### ISSUE THREAD

**Issue by Sanderadio** [contao/core#7607]
Hi,

I use Contao 3.4.2 and I just tried under 'Site Structure' to add a third website root to my installation but I got this fatal error:

`[29-Jan-2015 12:49:33 America/Chicago] PHP Fatal error: Uncaught exception 'Exception' with message 'Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ')' at line 1 (UPDATE tl_page SET language = 'en' WHERE id IN())' thrown in /path/to/system/modules/core/library/Contao/Database/Statement.php on line 293

#0 /path/to/system/modules/core/library/Contao/Database/Statement.php(262): Contao\Database\Statement->query()
#1 /path/to/system/cache/dca/tl_page.php(2079): Contao\Database\Statement->execute('en')
#2 /path/to/system/modules/core/drivers/DC_Table.php(1986): tl_page_l10n->updateDefaultLanguage(Object(Contao\DC_Table))
#3 /path/to/system/modules/core/classes/Backend.php(622): Contao\DC_Table->edit()
#4 /path/to/system/modules/core/controllers/BackendMain.php(126): Contao\Backend->getBackendModule('page')
#5 /path/to/contao/main.php(20): Contao\BackendMain->run()
#6 {main}`

What could be wrong? Thanks.

**Comment by aschempp** [comment]
Looks like a bug in the `i18nl10n` extension and certainly not the Contao core.

**Comment by Sanderadio** [comment]
Thanks. I disabled the extension and adding a new website root works fine.
