### ISSUE TITLE
Warnings from install-tool

### ISSUE THREAD

**Issue by ofriedrich** [contao/core#7608]
If you start the install tool with version 3.4.2 there is a huge number of warnings. For example in file

system/modules/core/library/Contao/Database/Installer.php
line 450 ff

You should not read values, that are not set. You don't have $field['length'] and $field['precision'] in many field definitions. And there are many other warnings.

As a result the redirect after clicking on the database-update-button does not work any more.

Please fix it!

**Comment by xchs** [comment]
See #7593
