### ISSUE TITLE
Cursorproblem bei zwei oder mehr TinyMCE in Formularen

### ISSUE THREAD

**Issue by Samson1964** [contao/core#7609]
Der nachfolgende Fehler war mir vor Monaten bei einer eigenen Modulentwicklung aufgefallen. Nun bemerkte ich, daß der Fehler zum Core gehört (Subpalettenproblem) oder ein TinyMCE-Problem ist.

Zum Nachstellen des Fehlers in der Onlinedemo 3.4.2 als auch in 3.2.17:

1) Neuen Kommentar in FE erstellen
2) Im BE eine Antwort zu diesem Kommentar hinzufügen "Add a reply"
3) Die Subpalette mit dem zweiten/weiteren TinMCE öffnet sich, aber man bekommt den Cursor nicht in die TinyMCE-Textarea.

Getestet mit FF 35.0.1 als auch schon mit früheren FF-Versionen.

Erst nach dem Speichern des Formulars (und der Fehlermeldung "bitte ausfüllen") ist die Textarea aktiv.

**Comment by leofeyer** [comment]
Siehe #4399 und #7348.
