### ISSUE TITLE
CE - Media erkennt `.ogg` als Audio

### ISSUE THREAD

**Issue by katgirl** [contao/core#7610]
Leider wird bei der Angabe webm und ogg die Ausgabe als Audio und nicht als Video erkannt. Sobald ein mp4 dazu kommt passt es, jedoch nicht bei nur den beiden erstgenannten Formaten.

**Comment by BugBuster1701** [comment]
Das hatten wir schon mal, zumindest für "ogg".
"ogg" ist nur ein Containerformat. "ogg" wurde Anfangs vornehmlich für Audio genutzt, Video war weniger verbreitet.  Daher hat sich später für Video die Endung "ogv" etabliert.
(Das Contao auch so definiert)
https://github.com/contao/core/blob/master/system/config/mimetypes.php#L135

**Comment by BugBuster1701** [comment]
Nachtrag: Wobei ich grad nicht getestet habe, ob CE Media das auch so sieht.

**Comment by katgirl** [comment]
Aber ich habe ja webm und ogg drin in dem Mediaelment und dann sollte nach meinem Verständnis Video gewählt werden. 

Die Liste der Quellen scheint alphabetisch abgearbeitet zu werden und der erste bestimmt den Typ.

Habe das gerade mal mit OGG, OGV und Webm probiert, es wird weiterhin als Audio ausgegeben. Habe eh ein angepasstes Template so das ich Audio erstmal dort löschen konnte.

**Comment by leofeyer** [comment]
Die Methode `FilesModel::findMultipleByUuidsAndExtensions()` sucht alle passenden Dateien und die Klasse `ContentMedia` bestimmt anhand des letzten Eintrages, ob es sich um ein Video handelt oder nicht. In Deinem Fall ist dies die `.ogg`-Datei und somit geht Contao nicht von einem Video aus.

Der eigentliche Fehler ist aber, dass Du die Dateitypen gemischt hast (Audio und Video). Hierbei ist `.ogg` ein Sonderfall, wie @BugBuster1701 schon geschrieben hat, weil es sowohl Audio als auch Video enthalten kann.

@contao/developers Wie sollen wir `.ogg`-Dateien zukünftig handhaben?

**Comment by Toflar** [comment]
Deswegen ist es immer falsch, auf Dateiendungen zu prüfen.
Die Mime-Types `audio/ogg` und `video/ogg` sprechen nämlich für sich :)

**Comment by ausi** [comment]
Lt. [Wikipedia](http://de.wikipedia.org/wiki/Ogg):

> Im September 2008 wurde RFC 3534 durch RFC 5334 ersetzt. Dabei wurden der Internet Media Type application/ogg neu definiert und die Internet Media Types audio/ogg für Audiodaten und video/ogg für Videodaten ergänzt. Als Dateinamenserweiterungen wurden .ogx für application/ogg, .ogv für video/ogg und .oga, .ogg und .spx für audio/ogg festgelegt.

`.ogg` sollte also für audio und `.ogv` für video stehen, wenn ich das richtig verstehe.

**Comment by ausi** [comment]
> Deswegen ist es immer falsch, auf Dateiendungen zu prüfen.

Auf die Mime-Types zu prüfen finde ich auch besser. PHP kann doch sogar nativ den Mime-Type von Dateien auslesen, oder? Dann sollte man das recht einfach umbauen können...

**Comment by Toflar** [comment]
Je nach Config ja. Siehe auch den `MimeTypeGuesser` von SF2.

**Comment by aschempp** [comment]
Einfach die Datei von `.ogg` auf `.ogv` umbenennen dürfte das Problem ja bereits lösen?

**Comment by leofeyer** [comment]
> Einfach die Datei von `.ogg` auf `.ogv` umbenennen dürfte das Problem ja bereits lösen?

Ja sicher. Die Frage war ja nur, wie wir das generell mit `.ogg`-Dateien handhaben.

>> Im September 2008 wurde RFC 3534 durch RFC 5334 ersetzt. Dabei wurden der Internet Media Type application/ogg neu definiert und die Internet Media Types audio/ogg für Audiodaten und video/ogg für Videodaten ergänzt. Als Dateinamenserweiterungen wurden .ogx für application/ogg, .ogv für video/ogg und .oga, .ogg und .spx für audio/ogg festgelegt.
>
> `.ogg` sollte also für audio und `.ogv` für video stehen, wenn ich das richtig verstehe.

Ja. Somit macht Contao schon alles richtig :)

> Auf die Mime-Types zu prüfen finde ich auch besser.

Ich auch. Pull-Request anyone? :)

**Comment by Toflar** [comment]
> Ich auch. Pull-Request anyone? :)

Ist mit SF2 Komponenten viel einfacher, kann man in der 4.x ändern :)
