### ISSUE TITLE
TinyMCE and Ace prefs overwritten at update

### ISSUE THREAD

**Issue by justschim** [contao/core#7611]
Hi,
the tinyMCE and Ace prefs in system/config are overwritten and back to default every time a Contao update is performed. That's not what should happen, isn't it.

Just

**Comment by xchs** [comment]
See https://contao.org/en/manual/customizing-contao.html#customizing-tinymce

**Comment by Aybee** [comment]
If you don't know the fields you have, e.g. you have some extensions, you can use this to replace all tinyMCE with tinyCustom. Use this in your system/config/dcaconfig.php
```php
// use tinyCustom for all textareas that use tinyMCE
array_walk_recursive($GLOBALS['TL_DCA'], function(&$v, $k){
  if($k === 'rte' && $v === 'tinyMCE')
  {
    $v = 'tinyCustom';
  }
});
```

**Comment by xchs** [comment]
Cool :+1:
