### ISSUE TITLE
Suche - "oee" wird zu "o" normalisiert

### ISSUE THREAD

**Issue by Domi1244** [contao/core#7613]
Ins Formular habe ich "oee" eingegeben. Ergebnisse hierfür bekam ich weit über 100. Kaum eine der Seiten beinhaltete allerdings das Wort.
Ich habe ein wenig nachgeforscht und herausgefunden, dass die Zeile 
```php
$strKeywords = mb_eregi_replace('[^[:alnum:] \*\+\'"\.:,_-]|\. |\.$|: |:$|, |,$', ' ', $strKeywords);
```
in der Search.php mir aus "oee" "o " macht, wodurch die vielen Treffer natürlich Sinn ergeben.

Wenn ich die Funktion und die if außenrum entferne und somit die Fallback funktion "preg_replace" greift, habe ich nur noch 4 Ergebnisse, die auch alle zutreffen, allerdings habe ich dann Probleme mit echten Umlauten. Kann man da etwas machen?

**Comment by leofeyer** [comment]
Lässt sich das Problem in der Onlinedemo reproduzieren?

**Comment by xchs** [comment]
Ich kann das (in meiner Demo) nicht reproduzieren (getestet mit "OEE GmbH" und "moeechte").

**Comment by Domi1244** [comment]
Ich bin mir inzwischen selbst nichtmehr sicher, ob das nicht evtl. ein Fehler vom Server war. Lokal funktioniert das ganze nämlich scheinbar.

**Comment by leofeyer** [comment]
Eventuell ein DB-Collation-Problem?
