### ISSUE TITLE
Synchronisieren der Dateiverwaltung führt bei Sonderzeichen zu Fehler

### ISSUE THREAD

**Issue by TempleClause** [contao/core#7615]
Wenn man Synchronisieren der Dateiverwaltung anklickt und deutsche Umlaute in den Ordnernamen hat, führt es zu Fehlern. (ä ö ü)

**Comment by Toflar** [comment]
Die da wären??

**Comment by TempleClause** [comment]
? Was meinst du?

**Comment by Toflar** [comment]
Du schreibst "führt es zu Fehlern". Wo bitte sollen wir denn mit der Suche beginnen, wenn wir noch nicht mal eine Fehlermeldung haben? :)

**Comment by TempleClause** [comment]
oh Entschuldigung! 

Fatal error: Uncaught exception Exception with message No parent entry for files/Bilder/2_Produkte/3_Lastentr�ger thrown in ****\system\modules\core\library\Contao\Dbafs.php on line 538
#0 ****\system\modules\core\drivers\DC_Folder.php(2004): Contao\Dbafs::syncFiles()
#1 ****\system\modules\core\classes\Backend.php(425): Contao\DC_Folder->sync()
#2 ****\contao\main.php(137): Contao\Backend->getBackendModule('files')
#3 ****\contao\main.php(288): Main->run()
#4 {main}

**Comment by xchs** [comment]
> gibts ne Möglichkeit code schöner dar zu stellen?

Siehe https://guides.github.com/features/mastering-markdown/

**Comment by frontendschlampe** [comment]
> EDIT: sorry bin neu hier, gibts ne Möglichkeit code schöner dar zu stellen?

ja ... schau mal hier: https://guides.github.com/features/mastering-markdown/ ... ;-)

Ansonsten zu Deinem Problem: also auf Dateiebene solltest du es auf jeden Fall vermeiden, Umlaute zu verwenden!

**Comment by Toflar** [comment]
Contao kommt aber auch problemlos mit Umlauten klar. Allerdings dein Dateisystem bzw. deine Datenbank womöglich nicht. Auf jeden Fall hab ich soeben eine Datei auf meinem Localhost `släider.png` benannt und ich kann problemlos synchronisieren.

**Comment by xchs** [comment]
Ich habe es jetzt mit Deinem Ordnernamen probiert (Contao 3.4.2):

![folder](https://cloud.githubusercontent.com/assets/1218766/6032850/808302a4-ac0e-11e4-92ca-a32c00937bfd.png)

Wurde (bei mir) problemlos vom DBAFS indiziert.

**Comment by TempleClause** [comment]
Okay Danke für die Hilfe, hab noch kur ein bisschen rumprobiert, konnte es aber nicht fixen. 
Kann aber gut damit leben keine Umlaute zu brauchen.

**Comment by leofeyer** [comment]
Was hast Du denn für einen Zeichensatz bzw. Collation in MySQL eingestellt?

**Comment by TempleClause** [comment]
utf_general_ci

**Comment by kikmedia** [comment]
Hmmm - same here, Contao 3.5.0 under the following preconditions:
* Strato PowerWeb
* see check at http://relaunch.sozialoekonomie-online.de/check/
* collation utf8-general-ci

My customer just uploaded a bunch of very old PDF documents into directories like "Archiv ZFSö-182-183", seeing exactly the same exceptions like @TempleClause 

After all, Contao isn't able to get the directory path, showing an image only for the file folder without any  further informations.

After checking the directory name in backend via editing function, I see something like "Archiv ZfS�-182-183" (and couldn't figure out what's behind the '�' ...), seeing also a lot of file names beeing cutted off after the ninth character.

If you need any more informations please drop me a line.

**Comment by discordier** [comment]
Some questions to get a grasp of this:
- What is the php.ini default charset?
- What are the php.ini settings for:
  - php.input_encoding
  - php.internal_encoding
  - php.output_encoding
  - iconv.input_encoding
  - iconv.internal_encoding
  - iconv.output_encoding
  - mbstring.http_input
  - mbstring.internal_encoding
  - mbstring.http_output
- Was the file uploaded with an FTP client in ASCII mode or using UTF-8 in the control channel?

**Comment by kikmedia** [comment]
Well it's obvious that the charset is iso-8859-1 on Strato servers. All the other values are not set by default. 

Setting all of them to utf-8 doesn't change anything. Creating directories containing Umlauts via FTP leave the file manager unable to render the directory names and prevents the directory contents from beeing displayed at all.

As far as I can see, files were transmitted in binary mode.

**Comment by discordier** [comment]
That is why I was referring to the Control channel of the FTP, not the data channel (where there is a difference like ASCII and binary).
But as you already stated, the Problem is the ISO charset used by the file system, I am unsure of what we can do here aside from adding a separate setting and converting the file names by hand everywhere we need them.
