### ISSUE TITLE
Missing urldecode when setting URL request params

### ISSUE THREAD

**Issue by backbone87** [contao/core#7619]
https://github.com/contao/core/blob/master/system/modules/core/classes/Frontend.php#L268

Aktuell (nicht so gut):
`\Input::setGet($arrFragments[$i], (string) $arrFragments[$i+1], true);`

```
/my-request-with-param/land/Vereinigtes+K%C3%B6nigreich
\Input::get('land') == 'Vereinigtes+K%C3%B6nigreich'
```

(oder `\Input::get('land') == 'Vereinigtes+Königreich'` je nachdem ob UTF-8 URLs verwendet werden oder nicht)

Besser:
`\Input::setGet($arrFragments[$i], urldecode((string) $arrFragments[$i+1]), true);`

```
/my-request-with-param/land/Vereinigtes+K%C3%B6nigreich
\Input::get('land') == 'Vereinigtes Königreich'
```

**Comment by backbone87** [comment]
Evtl. auch:
`\Input::setGet(urldecode($arrFragments[$i]), urldecode((string) $arrFragments[$i+1]), true);`

**Comment by Toflar** [comment]
I don't think the latter is correct. When I call an example code using `http://localhost/test.php?Vereinigtes+K%C3%B6nigreich=Vereinigtes+K%C3%B6nigreich` containing a simple `print_r($_GET);` I get this:
```
Array ( [Vereinigtes_Königreich] => Vereinigtes Königreich )
```

So while `urldecode` on the __value__ is perfectly fine (according to my results and the manual), php does something I could not find any documentation about (yet) with the __key__. Any idea? /cc @contao/developers

**Comment by backbone87** [comment]
Benutze mal bitte var_dump statt print_r

**Comment by Toflar** [comment]
Bau dir doch den Mini-Testcase selber schnell? :-D
```
array (size=1)
  'Vereinigtes_Königreich' => string 'Vereinigtes Königreich' (length=23)
```

**Comment by backbone87** [comment]
http://stackoverflow.com/questions/283751/php-replaces-spaces-with-underlines

**Comment by leofeyer** [comment]
Die URL wird bereits in Zeile 80 dekodiert:

https://github.com/contao/core/blob/master/system/modules/core/classes/Frontend.php#L80

**Comment by leofeyer** [comment]
This has been implemented meanwhile (see https://github.com/contao/core/blob/master/system/modules/core/classes/Frontend.php#L271).
