### ISSUE TITLE
aria-expanded in accordion

### ISSUE THREAD

**Issue by Skipman** [contao/core#7620]
Please include the attribute aria-expanded into the accordion as discussed in #7574. This will improve accessibility as shown in http://www.w3.org/TR/wai-aria/states_and_properties#aria-expanded

**Comment by leofeyer** [comment]
I just checked and noticed that we are already using the attribute :)

https://github.com/contao/core/blob/master/system/modules/core/templates/mootools/moo_accordion.html5#L12
