### ISSUE TITLE
Ide_compat.php bei verschachtelten Namespaces

### ISSUE THREAD

**Issue by amenk** [contao/core#7621]
Ich habe ein Modul mit 

    namespace Foo\Bar;
    class Baz { ... };

Nun macht Contao daraus ja via class_alias ein \Baz
Wenn ich die `ide_compat.php` generiere, so ergibt das allerdings

    namespace Bar {
	class Baz extends \Foo\Bar\Bar {}
    }

Der umgebende Namespace Bar müsste doch weg oder welchen Hintergrund hat das?

**Comment by leofeyer** [comment]
> Nun macht Contao daraus ja via class_alias ein \Baz

Nein, Contao macht daraus ein `Bar\Baz`.

**Comment by amenk** [comment]
Bist du sicher? Ich kann die entsprechenden Klassen via \Baz ansprechen. In der load Methode sieht es auch so aus als ob alle Namespace-Ebenen entfernt werden:

![screenshot_selection_024](https://cloud.githubusercontent.com/assets/1087128/6124076/6002829c-b10a-11e4-8206-14f880a9ce07.png)

Übersehe ich da was? Contao Version ist 3.3.2

**Comment by aschempp** [comment]
Es wird immer nur der erste Teil des Namespaces entfernt, bzw. was du registriert hast. Bestes Beispiel, die Klasse `Contao\Model\Registry` wird zu `Model\Registry`.

**Comment by aschempp** [comment]
Wie sieht denn deine Autoload-Datei aus?

**Comment by amenk** [comment]
<?php
    
    /**
     * Register the namespaces
     */
    ClassLoader::addNamespaces(array
    (
        'iMi\PropertiesIS24',
    ));
    
    /**
     * Register the classes
     */
    ClassLoader::addClasses(array
    (
        'iMi\PropertiesIS24\ImiPropertiesIS24Api' => 'system/modules/imi_properties_is24/classes/ImiPropertiesIS24Api.php',
        'iMi\PropertiesIS24\ImiPropertiesIS24Upload' => 'system/modules/imi_properties_is24/classes/ImiPropertiesIS24Upload.php',
        'iMi\PropertiesIS24\ImiPropertiesIS24' => 'system/modules/imi_properties_is24/classes/ImiPropertiesIS24.php',
    ));

**Comment by aschempp** [comment]
ja wenn du den Namespace so registrierst, dann wird wohl auch der ganze Teil abgeschnitten. Könnte sein dass der ide_compat Generator das nicht korrekt erkennt.

**Comment by leofeyer** [comment]
Besteht das Problem noch oder kann das Ticket geschlossen werden?

**Comment by amenk** [comment]
Habe es nicht mehr weiter getestet ... sollte es denn gefixt worden sein?

**Comment by aschempp** [comment]
Dürfte sich mit Contao 4 sowieso erledigt haben.

**Comment by leofeyer** [comment]
> sollte es denn gefixt worden sein?

Ich denke nicht. Aber da es sich mit Contao 4 sowieso erledigt hat (wir benutzen dort den Composer-Autoloader), ist die Frage, ob wir es noch fixen müssen.

**Comment by amenk** [comment]
Besser die Energie in Contao 4 stecken ... das war ja eh recht kosmetisch-
