### ISSUE TITLE
tl_page DCA calls Backend::addPagesBreadcrumb() onload in edit mode, causing issues with filePicker

### ISSUE THREAD

**Issue by blairwinans** [contao/core#7623]
We have a custom image/singleSrc DCA field that we are assigning at the page level to tl_page DCA, and the fact that `Backend::addPagesBreadcrumb()` gets called onload means that it hijacks the `$_GET['node']` value before it can be handled by `Backend::addFilesBreadcrumb()` when trying to filter a node in the filePicker.

This leaves someone unable to filter to a specific node, as well as unable to back out of it when trying to select a file.

Since the page breadcrumb is not even shown in edit mode, I would suggest wrapping the call to `Backend::addPagesBreadcrumb()` in a check that `\Input::get('act') != 'edit'` [here](https://github.com/contao/core/blob/master/system/modules/core/dca/tl_page.php#L878).

Steps to reproduce:

1. Add a fileTree field to the tl_page DCA and regular page palette.
2. Edit the page and launch the file picker
3. Try to filter to a specific file node. It will not work.

**Comment by blairwinans** [comment]
Scratch that recommendation as a solution, because the node link uses `act=show`, which it also used by the pagePicker, so that will not work. Not sure how to handle that at the moment, actually.

**Comment by blairwinans** [comment]
Further info: adding more to the issue is the fact that when you are editing a page (or anywhere in Site Structure using `do=page`, such as an Internal redirect), the `PageSelector` widget will not call `\Backend::addPagesBreadcrumb('tl_page_picker')` [here](https://github.com/contao/core/blob/master/system/modules/core/widgets/PageSelector.php#L146).

It seems like the onload callback for the breadcrumb on tl_page was acting more as a stopgap solution for this, so it seems like we are missing a piece of logic that can tell either the `PageSelector` class or the `FileSelector` class to call the correct method in `Backend`.

**Comment by leofeyer** [comment]
See #8302.
