### ISSUE TITLE
Feature: navigation modules - respect language on multi language trees

### ISSUE THREAD

**Issue by Aybee** [contao/core#7624]
Ausgangssituation:
Zweiter Seitenbaum für andere Sprache. Changelanguage installiert, weil man mit dieser Erweiterung die Verbindung von Seiten in verschiedenen Sprachen herstellt. 

Binde ich ein "Navigation menu" ein, dann werden im FE automatisch die Links des Baumes der Sprache in welcher ich mich gerade im FE befinde ausgegeben. Wahrscheinlich, weil hier einfach nur nach den Ebenen geschaut wird (vorhandenes core feature).

Sobald ich aber eine Referenzseite angebe, wird die Sprache nicht mehr berücksichtigt, was ich auch grundsätzlich erstmal richtig finde (obwohl ich die Unhabhängigkeit von der Sprache hier noch nie benötigt habe).

Hier wünschte ich mir dann aber eine Checkbox "**Respect FE-Language**". D.h. wenn ich als Referenzseite z.B. eine Seite "Service-Menü" (welche als Unterseiten die Seiten für das Servicemenü enthält) auswähle und diese Seite ist (durch changelanguage) mit der Seite "Service menu" verknüpft (Fallbackseiten per changelanguage). Dann sollte im FE bei diesem Menü als Referenzseite die mit changelanguage verknüpfte Seite genommen werden.

Gleiche Checkbox sollte für alle Navigationen mit einstellbarer Referenzseite existieren. Auch die anderen Navigationen bei denen es Sinn macht (Individuelle, Book, Quick...) könnten so eine Checkbox gebrauchen um auf die zugewiesenen Seiten (changelanguage) der anderen Sprachen zu switschen.

**Comment by frontendschlampe** [comment]
Wie in meinem Kommentar auf https://github.com/terminal42/contao-changelanguage/issues/19#issuecomment-73459055 bereits erwähnt, ist es schwierig diese Funktion in den Core zu übernehmen, da sie auf die Funktionalität einer Erweiterung aufbaut. Ohne changelanguage kann Contao keine Verbindung zwischen Seiten, Modulen oder sonstigen Inhalten verschiedener Sprachen herstellen. Für die "Standardnavigation" nimmt Contao einfach die Root-Seite als Referenz und diese ist dann natürlich für jede Sprache einmal vorhanden, aber für die individuelle Navigation mit einer Referenzseite müsste Contao erstmal wissen, welche denn die passende Referenzseite in einer anderen Sprache ist.

**Comment by Aybee** [comment]
So 'ne Checkbox fände ich auf jeden Fall sehr praktisch. Ich hätte auch eher gedacht, dass es zu changelanguage gehört weil es die sprachliche Seitenverbindung herstellt.

**Comment by frontendschlampe** [comment]
Naja, ich hatte mich gestern dazu mit @Toflar unterhalten und es ist nicht die Aufgabe von changelanguage, denn changelanguage stellt "nur" ein Frontendmodul für das Umschalten von Seiten in verschiedenen Sprachen zur Verfügung. Die gewünschte Funktionalität ist auch schwierig für die Core-Navigationsmodule nachzurüsten. Wenn changelanguage 3 dann soweit ist, werden wir dieses Feature in unser Navigationsmodul mit aufnehmen.

**Comment by Aybee** [comment]
Ah gut, also tut sich da was in Zukunft. Bis dahin kann man sich ja weiter behelfen. Danke.

**Comment by leofeyer** [comment]
Das Problem wurde zwischenzeitlich behoben (ich weiß nicht genau in welcher Version, sicher aber in Contao 3.5.5).
