### ISSUE TITLE
SOAP Error bei Aufruf des Erweiterungskatalogs mit php 5.6

### ISSUE THREAD

**Issue by voglohnee** [contao/core#7625]
Ich bekomme beim Aufruf des Erweiterungskatalogs bzw. der Erweiterungsverwaltung folgende Fehlerhinweis: SOAP-ERROR: Parsing WSDL: Couldn't load from 'http://contao.org/services/repository.wsdl' : failed to load external entity "http://contao.org/services/repository.wsdl"

Ich habe dieses Problem bei meinem Hoster urgiert und da wurde mir folgendes mitgeteilt:
"Das Verbindungsproblem kommt daher das php 5.6 bei https-verbindungen das Zertifikat und die Verschlüsselung bereits bei Verbindung peinlich genau prüft und bei Unregelmäßigkeiten die Verbindung verweigert. Da contao offenbar ein Zertifikat für contao.org auf anderen Servern verwendet kommt es hier zu Verbindungsproblemen. Einzige Möglichkeit ist hier auf einen ältere PHP Version zu wechseln, oder das Problem mit dem contao support abzuklären."

Ist da was dran an dieser Aussage? Oder was soll ich am besten machen?

**Comment by Toflar** [comment]
https://contao.org/de/news/probleme-mit-dem-repository-beheben.html

**Comment by leofeyer** [comment]
@voglohnee Hast Du in den Backend-Einstellungen `https://` für die Repository-URL eingegeben?

**Comment by voglohnee** [comment]
Hatte ich nicht. Habe es aber schon ausgebessert, nur hat sich am Status nichts geändert. Ich habe mal dem Hoster den Link oben von Toflar gemailt. Mal sehen was die zurückmelden.

**Comment by voglohnee** [comment]
Ich habe von meinem Hoster folgende Antwort erhalten:
"Das Problem liegt wie gesagt am verwendeten Zertifikat von contao. Wir können da nichts machen, Sie können höchstens auf PHP 5.5 umsteigen da dann die Sicherheitsrichtlinien nicht so streng sind."

Der Umstieg auf php 5.5 kann aber, wenn überhaupt, nur eine kurzfristige Lösung sein finde ich. Das Ticket vom Taca https://github.com/contao/core/issues/7548 wurde ja wieder geöffnet. 
Da schreibt er: "From another point of view, accessing to contao.org is encrypted but the target domain is not verified on prior to PHP 5.6 environment.
It had better that Contao's code explicitly set SSL parameter of "verify_peer" and "verify_peer_name"."
Gibt es da irgendwelche Neuigkeiten?

Das mit der tmp WSDL Datei, weiß ich leider auch nicht wo ich diese finden soll. Mein Hoster schreibt es gibt keine außerhalb meines root-Verzeichnis, aber im Rootverzeichnis finde ich auch keine. Wo sollte die sein? 

Gibt es da bezüglich contao Zertifikat und php 5.6 irgendwelche geplanten Aktivitäten eurerseits?

**Comment by leofeyer** [comment]
In #7548 geht es darum, die strikte Zertifikatsprüfung auch in PHP 5.5. und 5.4 zu aktivieren, so dass sie in allen PHP-Versionen gleich ausgeführt wird.

> Da contao offenbar ein Zertifikat für contao.org auf anderen Servern verwendet

Hat der Support nur das geäußert, was Du oben gepostet hast? Oder hat er auch erklärt, warum genau das SSL-Zertifikat von Contao das Problem sein soll? Das Zertifikat ist schließlich gültig und von einer offiziellen Stelle signiert.

@contao/developers @taca

**Comment by aschempp** [comment]
Es scheint als wird StartSSL nicht von allen Distributionen standardmässig akzeptiert?

**Comment by voglohnee** [comment]
Ich habe vorher nur die oben stehende Info erhalten, jetzt nochmal nachgefragt bez. Leo's Input hinsichtlich Details und hier ist die neue Antwort vom Support:

Eine curl abfrage direkt am Webserver liefert folgendes:
curl -l https://contao.org/services/repository.wsdl
curl: (51) SSL: certificate subject name 'w1.vhost.io' does not match target host name 'contao.org'

Hilft euch diese Auskunft?

**Comment by leofeyer** [comment]
Ja, und zwar insoweit als dass Dein Client offenbar kein SNI unterstützt (Server Name Indication). Welches Betriebsystem und welche Version von cURL bzw. wget ist installiert?

**Comment by leofeyer** [comment]
Also laut Google unterstützt wget vor Version 1.14 und cURL vor Version 7.18.1 kein SNI.

**Comment by voglohnee** [comment]
Also diese Abfrage am Webserver habe nicht ich vorgenommen, sondern der Hoster auf dessen Webserver. Ich habe keine Ahnung mit welchem Client der da abgefragt hat. Oder meinst du meinen Client mit dem ich das Contao Backend aufrufe? Sorry falls ich da gerade auf der Seife stehe. 
Bei mir am Client habe ich Mac OS 10.10 (Yosemite) und da ist cUrl in einer Version  7.37 dabei.

**Comment by leofeyer** [comment]
Nein, ich meinen schon den Server. Offenbar läuft da ein älteres OS wie z.B. Debian 6 oder Ubuntu 12.04, das die beiden Pakete noch nicht in der mindestens benötigten Version hat. Frag doch mal beim Support nach, ob die beiden Pakete aktualisiert werden können?

**Comment by leofeyer** [comment]
Wobei wir auch noch etliche Server mit Ubuntu 12.04 haben und da gibt es keine solchen Probleme.

**Comment by discordier** [comment]
The support is present since Ubuntu 8.10 (libcurl 7.18.2-1ubuntu4) which is EOL 30.04.2010.

**Comment by voglohnee** [comment]
Mein Hoster hat mir heute mitgeteilt, dass auf dem Server wo die Seite läuft nur die curl Version 7.15 installiert ist. Das wird wohl der Grund gewesen sein. Er hebt die Version in Kürze. 
Danke für Eure Unterstützung. Ich schließe die Sache mal.

**Comment by pcr-coding** [comment]
Ich fürchte ich habe das selbe Problem leider ist der Hoster nicht bereit curl upzudaten :( Gibt es eine Möglichkeit das Problem zu umschiffen oder ist ein Update die einzige Möglichkeit?

**Comment by discordier** [comment]
Evtl. kann man es hacken indem man die SoapClient klasse extended und diese neue Klasse im ER verwendet. Hierbei muss man dann die `__doRequest()` Methode yberschreiben, dass sie den curl request intern selbst handhabt und die Host verification komplett deaktiviert.

```php
<?php

class HackedSoapClient extends SoapClient
{
    public function __doRequest($request, $location, $action, $version)
    {
        $headers = array(
            'Method: POST',
            'Connection: Keep-Alive',
            'User-Agent: PHP-SOAP-CURL',
            'Content-Type: text/xml; charset=utf-8',
            'SOAPAction: "'.$action.'"',
        );

        $ch = curl_init($location);
        curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
        curl_setopt($ch, CURLOPT_HTTP_VERSION, CURL_HTTP_VERSION_1_1);
        curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, false);
        curl_setopt($ch, CURLOPT_SSLVERSION, 3);

        if ($headers) {
            curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);
        }
        if ($request) {
            curl_setopt($ch, CURLOPT_POST, true );
            curl_setopt($ch, CURLOPT_POSTFIELDS, $request);
        }

        $response = curl_exec($ch);

        if (!$response) {
            throw new \RuntimeException(curl_error($ch));
        }

        return $response;
    }
}
```
Diese Klasse irgendwo registrieren, z.B. in einem zzz_custom module.
Anschliessend noch die Klasse aendern in [RepositoryBackendModule.php](https://github.com/contao/core/blob/5d878de67eb218d5eb7ba967dbc669859b8489ec/system/modules/repository/classes/RepositoryBackendModule.php#L117)
```diff
-						$this->client = new SoapClient($wsdl, array(
+						$this->client = new HackedSoapClient($wsdl, array(
```

Ungetestet und ohne Gewaehr, aber koennte klappen.
