### ISSUE TITLE
Form CSS ids sowie Element CSS ids nicht eindeutig, wenn das Form mehrfach verwendet wird

### ISSUE THREAD

**Issue by amenk** [contao/core#7626]
Reproduzierbar wie folgt:
* Form erstellen
* Mehrmals in die Seite einfügen

Nun hat das Form immer die gleiche CSS id, die Elemente ebenfalls. Das kommt z.B. recht häufig bei Responsive Webdesign vor, wenn z.B. Formulare an zwei verschiedenen Stellen eingebunden und dann dynamisch ein/ausgeblendet werden.

Ich habe mir den Code angeschaut und auf Anhieb keine einfache Lösung gefunden. Ansatz wäre die Modul/Artikel Hierachie in der ID abzubilden und z.B. die einzelnen IDs aneinander zu hängen.

Oder gibt es einen anderen Ansatz hierzu?

**Comment by leofeyer** [comment]
@contao/developers

**Comment by Toflar** [comment]
Das ist ein generelles Problem mit den automatisch vergebenen ID's. Contao macht standardmässig automatisch `id="f<formular-id>"` ausser du gibst bei `CSS ID / Klasse` händisch eine eigene ID ein. Du kannst dein Problem also durch manuelle Vergabe von ID's lösen.

**Comment by leofeyer** [comment]
Kann er nicht, denn wie soll er denn demselben Formular zwei verschiedene CSS-IDs zuweisen? :)

**Comment by Toflar** [comment]
Ah, ja...Depp. Naja, das können wir nur beheben indem wir irgendwie über die Globals hochzählen, aber

a) ist das unschön.
b) ändert das alle bestehenden ID's und wäre somit auch ein BC break.

**Comment by amenk** [comment]
Über Globals hochzählen geht auch nicht so einfach: Wenn ich ein weiteres Form in die Seite einfüge, ändert sich die ID.

**Comment by Toflar** [comment]
Ja ich meinte natürlich eine Kombi. Also bei Formular ID 50 sowas: `50_1`, `50_2` etc.

**Comment by amenk** [comment]
Okay die Idee ist eigentlich gar nicht so schlecht. Wenn man so zählt: `50`, `50_2`, `50_3`, ... ist es kaum noch BC-breaking. Denn wenn man das Formular schon doppelt hat, funktionieren die CSS Selektoren usw. eh bisher meist nicht korrekt. Wenn man das Formular nur einmal verwendet, ändert sich die ID nicht.

**Comment by amenk** [comment]
Und Achtung: Bei den Feld-IDs gibt es das gleiche Problem. Kann aber analog gelöst werden.

**Comment by Toflar** [comment]
> Und Achtung: Bei den Feld-IDs gibt es das gleiche Problem. Kann aber analog gelöst werden.

Ja klar :)

Ja, aber ich mag die Globals nicht :-D Static in der Form Klasse?

**Comment by do-while** [comment]
Man könnte vielleicht über einen neuen InsertTag die Content-Element-ID in die Klasse einbauen. Dann ist es updatekompatibel und die wenigen Problemfälle könnten so manuell zu eindeutigen IDs erweitert werden.

**Comment by amenk** [comment]
Frage mich ob so ein Insert Tag implementierbar ist? `\Contao\Controller::replaceInsertTags` hat ja erstmal keine Kenntnis über den Contents in dem es aufgerufen wird, oder?

Static in der Form Klasse klingt eigentlich gut finde ich.

**Comment by do-while** [comment]
Das stimmt natürlich, replaceInsertTags bekommt da keine Info mit.
Ein Token, z.B. ##CID## für Content-Id ist auch nicht so schön, sowas merkt sich keiner.
Die Idee mit dem hochzählen verstehe ich aber auch noch nicht, wer zählt? und wenn ich darüber ein Formular einfüge, verändern sich die IDs der nachfolgenden Formulare. Die Content-ID wäre da eindeutiger.

**Comment by amenk** [comment]
Gute Frage. evtl. im compile/generate? Wir haben das Formular übrigens als Frontend Module eingebaut. Da wird compile/generate nur einmal aufgerufen :-(

**Comment by Toflar** [comment]
Bittesehr: https://github.com/contao/core/pull/7643

**Comment by amenk** [comment]
Joah - nur leider geht es nicht im Zusammenhang mit Insert Tags wie z.B. `{{insert_form::123}}`, da diese gecacht werden :-(

**Comment by Toflar** [comment]
Nutz halt `{{insert_form::123|refresh}}`.

**Comment by leofeyer** [comment]
Ich schließe das Ticket zugunsten #7643 (@Toflar's Pull-Request). Allerdings habe ich diesen dem nächsten Feature-Release zugewiesen, weil ich nicht sicher bin, ob die Änderung nicht unerwünschte Nebenwirkungen hat (siehe Kommentare).
