### ISSUE TITLE
Update Error: Fatal error: Uncaught exception Exception with message Query error: Duplicate entry

### ISSUE THREAD

**Issue by white91wolf** [contao/core#7627]
Ich habe soeben versucht ein Update von 3.3.x auf die aktuelle Version zu machen. Nun bekomme ich bei der Aktualisierung der Datenbank folgenden Fehler:

````
Fatal error: Uncaught exception Exception with message Query error: Duplicate entry 'n\x85\xE6)\xAF?\x11\xE4\x93\x9Dn\xD4\xD9\xC5P>-Pepsi.jpg' for key 'pid_name' (ALTER TABLE `tl_files` CHANGE `name` `name` varchar(255) NOT NULL default '';) thrown in system/modules/core/library/Contao/Database/Statement.php on line 293

#0 system/modules/core/library/Contao/Database.php(199): Contao\Database\Statement-query('ALTER TABLE `tl...')
#1 system/modules/core/controllers/BackendInstall.php(602): Contao\Database->query('ALTER TABLE `tl...')
#2 system/modules/core/controllers/BackendInstall.php(169): Contao\BackendInstall-adjustDatabaseTables()
#3 contao/install.php(24): Contao\BackendInstall->run()
#4 {main}
````

habe gelesen, dass es früher zu solchen Fehlern gekommen ist, wenn der Dateiname zu lang oder Sonderzeichen hatte - das sollte aber glaube ich auch schon behoben sein.

**Comment by Fruchuxs** [comment]
Problem gefunden: Contao scheint bei tl_files.name nicht mehr zwischen Groß- und Kleinschreibung zu unterschieden (gab Pepsi.jpg und pepsi.jpg). Nachdem zweiteres händisch in der DB umbenannt worden ist, war das Update kein Problem mehr.

**Comment by leofeyer** [comment]
@contao/developers Ist das richtig? Oder sollten wir zwischen Groß- und Kleinschreibung unterscheiden?

**Comment by Toflar** [comment]
+1 für case-sensitive.

**Comment by Zeromax** [comment]
siehe auch #7641

**Comment by leofeyer** [comment]
Wie am 26. Februar auf Mumble besprochen wollen wir Case-Sensitivity nicht explizit unterstützen, da unter Umständen etliche andere Probleme (z.B. bei standardisierten URLs) nach sich zieht, die dann auch wieder gefixt werden müssten.
