### ISSUE TITLE
Bug: Modul Nachrichtenarchiv-Menü produziert leere HTML-Seite 

### ISSUE THREAD

**Issue by dibole** [contao/core#7630]
Seit dem letzten CONTAO-Update 3.2.18 funktioniert das Modulelement Nachrichtenarchiv-Menü nicht mehr. Wenn dieses Modul irgendwo in eine Seite eingebunden ist, führt das dazu, dass eine komplett leere Seite angezeigt wird (auch kein anderer Quellcode mehr)!

**Comment by Toflar** [comment]
Fehlermeldungen anzeigen einschalten und Fehlermeldung posten, bitte :)

**Comment by dibole** [comment]
Fatal error: Cannot redeclare class NewsCategories\NewsModel in /var/www/vhosts/dibomedia_c3/html/system/modules/news_categories/models/NewsModel.php on line 22

**Comment by Toflar** [comment]
Na bitte, der Fehler kommt aus dem Modul "news_categories" und hat nichts mit dem Core zu tun.

**Comment by qzminski** [comment]
This bug should be fixed in news_categories 2.2.2.
