### ISSUE TITLE
DropZone.php calculates max file size in MiB wrong

### ISSUE THREAD

**Issue by fritzmg** [contao/core#7633]
Minor issue in [DropZone.php #29](https://github.com/contao/core/blob/960155bf2c6225cdf2f3d2f21fb9ae9492f86a11/system/modules/core/classes/DropZone.php#L29): `$intMaxSize`, which is supposed to represent the maximum upload size in MiB, is calculated wrong. Instead of dividing the value returned by `$this->getMaximumUploadSize()` (the maximum upload size in bytes) by 1048576, it is divided by 1024000.

[FileUpload.php::getMaximumUploadSize()](https://github.com/contao/core/blob/960155bf2c6225cdf2f3d2f21fb9ae9492f86a11/system/modules/core/classes/FileUpload.php#L242) calculates the maximum upload size in bytes in the correct way.

**Comment by leofeyer** [comment]
Fixed in a6a7d56bc38f1cb747df7710497ead6232e87d64.
