### ISSUE TITLE
Responsive Images als InsertTag

### ISSUE THREAD

**Issue by dmolineus** [contao/core#7635]
Aktuell lädt der Inserttag für Bilder nicht die Responsive Images. 

Es wäre klasse, wenn sobald die Bildgröße über `{{image::12?mode=2}}` übergeben wird das entsprechende Bild-Element auch als Picture-Element erstellt wird.

**Comment by leofeyer** [comment]
Habe ich gerade in Contao 3.4 getestet und hat bereits funktioniert. Klappt es in der Onlinedemo nicht?

**Comment by dmolineus** [comment]
Nein, funktioniert nicht. Sonst würde es ja nicht das Ticket geben?!
Es wird lediglich das Image-Tag erzeugt.

1. Bildgröße mit unterschiedlichen Bildgrößen anlegen
2. Insert-Tag einbinden
3. Resultat ist lediglich ein einfaches `img` Tag, nicht das `picture` Element.

```html
<img src="assets/images/8/DSC_5276-747c7f08.jpg" width="300" height="200" alt="">
```

**Comment by ausi** [comment]
Kann ich bestätigen, weder `srcset` noch `<picture>` werden von `{{image::}}` generiert.
[system/modules/core/library/Contao/Controller.php:1619-1646](https://github.com/contao/core/blob/1f7448f356cbef9299d7285b2b3068723e620eb1/system/modules/core/library/Contao/Controller.php#L1619-L1646)

**Comment by dmolineus** [comment]
Would you reopen the ticket please or should I create a new one for this feature?

**Comment by leofeyer** [comment]
@ausi Du hast nicht zufällig Zeit und Lust, Dir das anzuschauen? ;)

**Comment by ausi** [comment]
@leofeyer Ja, kann ich machen. Soll ich den `{{image::}}` anpassen oder machen wir einen neuen `{{picture::}}`?

**Comment by leofeyer** [comment]
Gute Frage. Ich weiß es nicht. @contao/developers Was denkt ihr?

**Comment by ausi** [comment]
Eigentlich wäre es ein BC break wenn wir die Ausgabe von `{{image::}}` jetzt ändern, andererseits könnte man es als Bug sehen und die Ausgabe würde sich ja nur für Image-Sizes mit Media-Queries ändern. Ich denke ich bin für `{{image::}}` anpassen.

**Comment by aschempp** [comment]
Gibt es den `mode=2` Parameter bereits? Dann wäre es wohl ein Bug. Ansonsten gefällt mir `{{picture}}` besser, weil offensichtlich was generiert werden soll.

**Comment by ausi** [comment]
Ja, `mode=2` funktioniert bereits, erzeugt aber nur die Fallbackgröße der angegebenen Bildgröße, nicht das komplette Picture-Element. `{{picture::}}` könnte verwirrend sein, da es für Bildgrößen ohne Media-Queries kein `<picture>` sondern nur ein `<img>` ausgibt.

**Comment by Toflar** [comment]
```{{responsive_image::}}```? Ist zwar lang aber dafür weiss man auch was es tut?

**Comment by aschempp** [comment]
neee, warum heisst der HTML-Tag dann nicht `<responsive_img>`? :-P

**Comment by ausi** [comment]
Gibt es einen Anwendungsfall wo man bei `{{image::12?mode=2}}` nicht will dass das Bild wie in der Bildgröße eingestellt erzeugt wird?

**Comment by aschempp** [comment]
Das kann ich mir ehrlich gesagt gut vorstellen. Beispielsweise wenn du das Bild in ein PDF generieren willst.

+1 für `{{picture}}`. Selbst @dmolineus hat von *diesem Feature*  geschrieben ;-)

**Comment by Toflar** [comment]
Ich find `{{picture}}` auch gut, lässt auch Raum für weitere, responsive-bezogene Parameter offen. Wenn wir alles in den `{{image}}` packen, wird der irgendwann zu komplex.

**Comment by ausi** [comment]
OK, dann mach ich `{{picture}}`. Welche Parameter wollen wir haben?

* `size` ID der Bildgröße
* `alt` Attribut für `<img>`
* `class` CSS-Klasse für `<img>`
* `rel` bei `{{image::}}` erzeugt das automatisch einen Link um das Bild herum
* `template` Wenn man ein anderes Template als `picture_default` verwenden möchte

**Comment by Toflar** [comment]
Sieht gut aus :+1:

**Comment by ausi** [comment]
Bitte #7718 testen.

**Comment by ausi** [comment]
@leofeyer I think we should change the milestone for this issue to 3.5.0

**Comment by leofeyer** [comment]
Der PR wurde in 68e80040b5ff697749e35ee1ecd9d7156475f7c9 übernommen.
