### ISSUE TITLE
[Feature] Use button Element instead of input[type="submit"]

### ISSUE THREAD

**Issue by ben-eSM** [contao/core#7637]
The Contao form builder outputs submit buttons as `<input type="submit"...`. Since this kind of buttons can't handle CSS Pseude elements like `:after` and `:before`, the form builder should instead use the `<button type="submit"...>` element. Although the submit button could be changed by altering the template, it's not working for the form's addSubmit option where the button is placed alongside any other widget.

**Comment by ben-eSM** [comment]
Just saw that it's possible to change the addSubmit in the form templates in Contao 3.4 also.
Yet I see no reason for sticking to the ´input´ type of button.

**Comment by leofeyer** [comment]
Except for backwards compatibility.

@contao/developers What do you think?

**Comment by Toflar** [comment]
Well, it's a fact that elements that cannot contain child elements don't support `:before` or `:after`. I have never had the need to use any pseudo element on an `<input>` but on the other side I can't see any disadvantage of using `<button>` instead. I'm fine with a BC break in Contao 4 here because it's one that provides us with more flexibility. But certainly not in 3.5.

**Comment by aschempp** [comment]
I agree with @Toflar, changing this in 3.5 would break a lot if CSS

**Comment by ben-eSM** [comment]
If you wanna use neat css3 styling for buttons, it comes in handy when you can use pseudo elements. As @Toflar said, it provides a lot more flexibility.

**Comment by ausi** [comment]
+1 for Contao 4. I'm using the `<button>` element all the time...

**Comment by christianromeni** [comment]
+1

**Comment by leofeyer** [comment]
Changed in cca616d1d1037b0da62ea3c8f49389ca3a9d5fcb.

**Comment by aschempp** [comment]
This won't work. The button "name" is only submitted if it has a value, and we do need the name for "saveNclose" etc.

**Comment by leofeyer** [comment]
It does work on my local environment. Did you try it?

**Comment by ausi** [comment]
`<button>`s with a name attribute but without a value attribute should be sent as an empty string. I tested it in Firefox and it worked as expected.

**Comment by aschempp** [comment]
I haven't tested it, but I know the problem from Isotope.

It would work in https://github.com/contao/core-bundle/blob/develop/src/Resources/contao/drivers/DC_Table.php#L2053 but not in https://github.com/contao/core-bundle/blob/develop/src/Resources/contao/drivers/DC_Table.php#L2453

**Comment by leofeyer** [comment]
Fixed in c58725cfa5fb49f8125b3f9407ea486b54e0583d.
