### ISSUE TITLE
Page cache does not work

### ISSUE THREAD

**Issue by aloesche** [contao/core#7638]
Hi, I tried to enable the page cache on a single page (and on on root page to inherit) with v3.2.19 related to the below settings:
1) Settings > bypass internal cache = no
2) Settings > cache type = server cache only (tried server and browser cache too with same result)
3) Page > root page or any other page > caching time = 7days
4) Cleared cache, rebuild internal cache
5) Called page

Result:
1) Page in the frontend is rendered in the same time area (ms) no performance improvement
2) Changes to a content (text element) are available promt
3) Maintenance > Site cache = 0 entries (/system/cache/html/ empty)

I am quite new to Contao but I reproduced this on a vanilla version of Contao without any extensions to ensure.

**Comment by bytehead** [comment]
Try it in a private tab. AFAIK it does not apply, if you're logged in to the backend at the same time.

**Comment by aloesche** [comment]
Damn! :) You are right! Now at least the page appears in /system/cache/html/ Will check further. Thank you!

**Comment by bytehead** [comment]
No worries! Could you please close the issue then?

**Comment by aloesche** [comment]
sure. thx

**Comment by bytehead** [comment]
By the way: there is a [forum](https://community.contao.org/en/) where you get help as well :)

**Comment by aloesche** [comment]
Believe me or not but I reviewed the forum (and Google of course) regarding this but could not find this "hint" ... :)
