### ISSUE TITLE
Contao 3.4.4, gzdecode gibt es erst ab PHP 5.4

### ISSUE THREAD

**Issue by BugBuster1701** [contao/core#7639]
Laut Readme soll Contao 3.4 ja mit PHP 5.3+ laufen.
Gerade sehe ich in der core/classes/Versions.php die Funktion gzdecode:
```
if ($objFile->extension == 'svgz')
{
	$objRecord->content = gzdecode($objFile->getContent());
}
```
Laut Handbuch gibt es die erst ab PHP 5.4

Ich hoffe mal, dass kaum noch jemand PHP 5.3 einsetzt, daher würde ein Hinweis vielleicht in der LIMITATIONS.md oder in der README.md reichen meiner Meinung nach.
Contao 3.5 auf PHP 5.4+ in den Anforderungen hochzusetzen wäre sicherlich nicht verkehrt.

**Comment by leofeyer** [comment]
Wir könnten auch eine Fallback-Funktion einbauen: http://php.net/gzdecode#115403

Oder wir lassen die Kompatibilität auf PHP 5.3+ uns sagen in der `LIMITATIONS.md` das `.svg`-Dateien nicht mit PHP 5.3 genutzt werden können.

@contao/developers Was meint ihr?

**Comment by aschempp** [comment]
+1 für LIMITATIONS.md

**Comment by Toflar** [comment]
Die Fallbackfunktion die du genannt hast, geht wohl zu wenig weit. Ich würde eher auf die von http://include-once.org/p/upgradephp/ setzen. Nun ja, wer 5.3 einsetzt ist eh selber schuld, aber ich finde es nicht richtig, die minimalen Anforderungen auf 5.3 zu setzen und fehlende Funktionen in der LIMITATIONS.md zu dokumentieren. Entweder kann es das oder es kann's nicht und entsprechend sind die Systemanforderungen. -1 für LIMITATIONS.md bzw. +1 für Fallback.

**Comment by leofeyer** [comment]
UpgradePHP ist cool, bedeutet aber auch viel Overhead. Würde sich meiner Ansicht nach nur lohnen, wenn wir damit auch weitere PHP 5.3-Probleme beheben können.

**Comment by Toflar** [comment]
Ja, ich würd nur gerade die entsprechende Methode kopieren bzw. noch prüfen, auf welche anderen Funktionen die intern zurückgreift und ob da evtl. noch eine weitere kopiert werden muss. Ich würd sie zudem auch nicht in die functions.php packen sondern ein `contao/php-53-compat` repo bauen und das per Composer require reinziehen, dann ist es nämlich auch automatisch in Contao 4 nicht drin :)

**Comment by Tastaturberuf** [comment]
Da 5.3 sein End of Life erreicht hat, würde ich ich Requirements auf 5.4 legen. Dann kann ich endlich auch die Short Array Syntax und Short-Open-Tag nutzen (grade in Templates übersichtlicher).

**Comment by leofeyer** [comment]
Hab einen Absatz in die `LIMITATIONS.md` aufgenommen (siehe 46ccce32929180883d16aa7529d14780ea0ee9c6).

**Comment by discordier** [comment]
Theorethisch koennte man aber 3.5 auf php 5.4 dep legen, oder?

**Comment by leofeyer** [comment]
Naja, ist schon auch eine Art von BC-Break, oder?

**Comment by discordier** [comment]
Mhh... dann haetten wir von 3.3 auf 3.4 aber auch nicht die PHP Anforderung hochziehen dyrfen... oder? Oder ist es bei "nur patchlevel ohne neue features" akzeptabel, php mit BC und NICHT EOL vorauszusetzen hingegen nicht? :)

IMO sollten wir den toten Gaul PHP 5.4 nicht endlos reiten, zumal meines Wissens nach alle grossen Mainstream hoster inzwischen mind. bei 5.4 angekommen sind, wenn nicht gleich noch aktueller.

Wer dennoch PHP 5.3 braucht, der kann weiterhin auf die LTS setzen, denn dafyr ist sie da. Damit sie lange betrieben werden kann und damit man mit den neuen Minors auch voran schreiten kann.

Ich muss da @Tastaturberuf schon recht geben, wir werden dadurch dann bis Juni 2017 PHP 5.3 supporten myssen.
Das waere dann bis Juni gerechnet (da PHP 5.3 sein EOL am 18.08.2014 hatte) immerhin die beachtliche Anzahl von 1.018 Tagen (2,79 JAHRE) nachdem der Gaul vom Besitzer erschossen worden ist. Wenn der da mal nicht schon vollkommen vergammelt ist.

Wenn du wirklich an PHP 5.3.7 festhalten willst, dann wird auf kurz oder lang der Core das Einzige sein was PHP 5.3 supported. Alle (groesseren) Erweiterungen werden in ihrer composer.json langsam sagen dass sie 5.4 wollen (zumindest im Laufe der LTS Phase).

**Comment by MacKP** [comment]
Grundlage:
Soweit ich weiß, wird von so ziemlich allen größeren Hostern PHP in höheren Versionen angeboten (ich setzte selber in der Regel 5.6 ein...).

Ich muss sagen, das selbst wenn es ein BC Brake ist. Dann sollte man den doch in Contao 3.5 machen. Wenn nicht zu dem Zeitpunkt, wann dann? Ich kann Xtra da nur in seiner Meinung unterstützen.

**Comment by Toflar** [comment]
5.4 für die 3.5 kann ich auch unterstützen. Alleine die Tatsache dass 5.3 EOL ist sollte Grund genug sein :)

**Comment by leofeyer** [comment]
> Mhh... dann haetten wir von 3.3 auf 3.4 aber auch nicht die PHP Anforderung hochziehen dyrfen... oder? Oder ist es bei "nur patchlevel ohne neue features" akzeptabel, php mit BC und NICHT EOL vorauszusetzen hingegen nicht? :)

Von 3.3 auf 3.4 haben wir lediglich die PHP-Version von 5.3.2 auf 5.3.7 angehoben. Das ist nochmal etwas anderes als von 5.3 auf 5.4.

> Wer dennoch PHP 5.3 braucht, der kann weiterhin auf die LTS setzen, denn dafyr ist sie da. Damit sie lange betrieben werden kann und damit man mit den neuen Minors auch voran schreiten kann.

@discordier Eben nicht, denn Contao 3.5 wird die neue LTS-Version :)

**Comment by discordier** [comment]
Ich meinte ja die "bisherige LTS". :)

Aber evtl. sollten wir mal eine Umfrage machen wer wirklich noch php53 verwendet. All zu viele koennen das nicht sein.

**Comment by aschempp** [comment]
Ich kenn da leider Hosting-Anbieter… Mir wäre 5.3 für die LTS lieber, auch wenn ich euren Argumenten absolut Recht geben muss…

**Comment by discordier** [comment]
Welche sind dies?
Sind die wirklich relevant oder nur ein "Nieschenhoster von nebenan" der sich keinen Admin leisten will?
@aschempp Ich weiss nicht wie es bei Euch aussieht, aber ich werde 5.3 in meinen Extensions mittelfristig nicht mehr supporten. Das meinte ich oben mit dass nur noch der Core 5.3 supporten wird.
Wenn man dann auf der Werbetafel schreibt "Contao braucht nur 5.3" aber alle Extensions schon 5.4 sind, dann sorgt das doch eher fyr mehr Frust als wenn alle sagen 5.4 ist schon so alt, da kann man das voraus setzen.

**Comment by aschempp** [comment]
Natürlich sind es "Nieschenhoster von nebenan", aber meine Kunden nutzen die nunmal. Die brauchen auch Safe-Mode-Hack und bei denen funktioniert teilweise das Live-Update nicht weil PHAR deaktiviert und so sch***. 

Wir wissen dass Contao 4 die Anforderungen erhöht und das ist gut so. Deshalb würde ich die 3.5 LTS noch kompatibel halten. Mit der `LIMITATIONS` kann ich perfekt leben, dann kann ich bei den Kunden halt keine SVG nutzen. Das ist völlig irrelevant für deren Systeme.

**Comment by leofeyer** [comment]
Vor allem ist das Anheben der Minimum-PHP-Version ganz und gar nicht notwendig. SVGZ ist momentan das einzige Problem und dazu gäbe es auch andere Lösungen.

**Comment by Toflar** [comment]
Das grosse Problem was ich immer wieder sehe mit diesen Mindestanforderungen ist einfach, dass dann niemand die Serverkonfiguration ändert. Solange wir 5.3 als Mindestanforderung definieren, wird es auch Unmengen an Leuten geben, die 5.3 für Contao einsetzen. Wir alle wissen, dass 5.3 bereits Sicherheitslücken enthält, die nicht mehr geschlossen werden. 5.3 ist EOL! Es ist absolut unverantwortlich 5.3 immer noch einzusetzen und da sich unsere Anwender dessen nicht bewusst sind, können wir sie mit dem Anheben der Mindestanforderungen vielleicht vor bösen Überraschungen schützen.

**Comment by leofeyer** [comment]
Sehe ich nicht so. Wir sind nicht dafür verantwortlich, welche PHP-Versionen die Leute einsetzen.

Ich habe mir gerade mal die Vendor-Skripte angesehen und die meisten davon supporten auch noch PHP 5.3. Überlegt mal, wie lange PHP 5.2 noch weit verbreitet war, obwohl sie ihr EOL schon erreicht hatte.

**Comment by aschempp** [comment]
Selbst Symfony 2.7 unterstütz noch PHP 5.3…
https://github.com/symfony/symfony/issues/12401#issuecomment-61532219

**Comment by Toflar** [comment]
> Sehe ich nicht so. Wir sind nicht dafür verantwortlich, welche PHP-Versionen die Leute einsetzen.

Ich habe auch nicht gesagt, dass wir das sind. Ich habe gesagt wir könnten die Leute so evtl. vor bösen Überraschungen schützen.

> Selbst Symfony 2.7 unterstütz noch PHP 5.3…

Natürlich unterstützen die Libraries alle noch 5.3 und natürlich können wir das auch machen. Das steht ja nicht zur Diskussion. Ich will ja nicht plötzlich einfach PHP 5.4-Features in die 3.5 einbauen. Was ich sagen will, ist dass es in dieser Diskussion eine Konstante gibt und die heisst **PHP 5.3 ist EOL und enthält Sicherheitslücken**. Der Einsatz von 5.3 ist **unverantwortlich**. An dieser Tatsache ändert sich nichts.

Und ich bin der Meinung, dass wir Unverantwortlichkeit nicht unterstützen sollten. Jeder der 5.3 einsetzt ist selber schuld, um solche Leute wollen wir uns nicht kümmern müssen. Es ist mir ziemlich egal wie lange 5.2 noch verbreitet war und wie viele Libraries noch 5.3 unterstützen. Darum geht es nicht.

Meine Aussage ist einzig und allein: Ein Anheben auf 5.4 ist absolut kein Problem, weil jeder der einen anständigen Hosting-Anbieter hat bereits (mindestens) bei der Version sein **muss**.

**Comment by discordier** [comment]
@Toflar /signed.

**Comment by leofeyer** [comment]
> Meine Aussage ist einzig und allein: Ein Anheben auf 5.4 ist absolut kein Problem, weil jeder der einen anständigen Hosting-Anbieter hat bereits (mindestens) bei der Version sein **muss**.

Jaja, soweit die Theorie. Die Praxis sieht leider anders aus. Ich habe selbst noch Kunden, die PHP 5.2 einsetzen müssen, weil Sie vor Jahren Software gekauft haben, die mit dem alten Zend Encoder verschlüsselt ist. Und solche Fälle gibt es haufenweise in der Praxis.

**Comment by discordier** [comment]
@leofeyer einen vendor lock in fyhrst du doch nun bitte nicht ernsthaft ins Feld um zu vertreten dass eine 100% open source Software nicht den Support von veralteteter Technologie dropped?

**Comment by leofeyer** [comment]
Wir sollten das nochmal besprechen. Wenn wir jedoch auf PHP 5.4 gehen, dann entferne ich auch die bisherigen PHP 5.3-Workarounds und passe die Templates an (`<?php echo` -> `<?=`). Sonst lohnt sich das Anheben der Mindestversion wirklich nicht.

**Comment by discordier** [comment]
Koennte man machen, aber ich sehe es nun nicht als zwingend an, dass von Beginn an alle Templates umgestellt sind.
Das kann auch mit Patch levels kommen, aber nur dann, wenn man bei Release >=5.4 ist.
Es voraus zu setzen heisst ja nicht, dass man gleich alles davon verwenden muss sondern kann die Einfyhrung schleichend machen. Ansonsten solltest du gleich alle Arrays auch auf short notation umbauen usw.

**Comment by leofeyer** [comment]
Mit dem Unterschied, dass die Templates in Contao 4 bereits alle umgebaut sind und ich die nur kopieren müsste.

**Comment by fenepedia** [comment]
Ich bin ja kein Entwickler, aber ich möchte mal die Erfahrung bei meinen Kunden wiedergeben.

Viele Kunden wollen nicht mal Geld für die Wartung von Contao bezahlen. D.h. ich werde nie alle Kunden auf 3.5 bringen. Und wenn einer noch ein Hosting mit altem PHP hat und doch mal auf Contao 3.5 gehen will, dann muss er halt bei ner älteren Contao Version bleiben oder es gibt endlich einen Grund das Hosting zu wechseln ;-) 

Ich fände es besser wenn man weniger Zeit in Workarounds steckt und dafür sich um andere Dinge kümmert.

**Comment by leofeyer** [comment]
Umstellung auf PHP 5.4 in e8503b3ee4ee2458eecb831070f9e5616301bd01. Die Ergebnisse der [Abstimmung](http://twtsurvey.com/15a3hsa6xmeuebn) waren mit 29 dafür und 4 dagegen eindeutig.

**Comment by Tastaturberuf** [comment]
:+1: Short-Array ich komme :)
