### ISSUE TITLE
Login-Modul leitet in Firefox nicht auf "zuletzt besuchte Seite", sondern auf cron.php

### ISSUE THREAD

**Issue by Defcon0** [contao/core#7640]
Hallo,

es gibt scheinbar einen Bug in Bezug auf die Funktion "Zur zuletzt besuchten Seite" im Login-Modul. Wenn ich dieses anhake und bei Weiterleitungsseite nichts auswähle, gelange ich in Firefox manchmal nicht zur zuletzt besuchten Seite (welche natürlich eine geschützte ist), sondern zu /system/cron/cron.php. Ich habe mir Testausgaben in ModuleLogin ausgeben lassen. getReferer() liefert diese URI zurück und in der $_SERVER-Variable steht:

```
["FE_DATA"]=>
  array(2) {
    ["referer"]=>
    array(2) {
      ["last"]=>
      string(21) "system/cron/cron.php"
      ["current"]=>
      string(10) "system/cron/cron.php"
// ...
```

Ist das ein Bug? Contao-Version ist 3.3.5.

Ciao Defcon0

**Comment by Toflar** [comment]
Also see https://github.com/contao/core/pull/7568
