### ISSUE TITLE
Problem in Dateiverwaltung mit Groß- und Kleinschreibung

### ISSUE THREAD

**Issue by Samson1964** [contao/core#7641]
Contao 3.2.19
Habe gerade ein Szenario erlebt, was nicht so oft vorkommt.

1.) Datei p1040893.jpg hochgeladen
2.) Eine andere Redakteurin lädt unabhängig von mir eine Datei P1040893.JPG in dasselbe Verzeichnis hoch. Einziger Unterschied dieser Dateien: ich habe mein Bild vor dem Upload um 90 Grad gedreht, damit es nicht auf der Seite liegt. Dadurch sind die Dateigrößen natürlich auch unterschiedlich.
3.) Ich setze eine Bildunterschrift. Bei welchem der beiden Bilder weiß ich aber nicht mehr. Ich denke mal bei meiner Version, weil mir das andere Bild zu dem Zeitpunkt noch nicht aufgefallen war.
4.) Mein Artikel geht online. Seltsamerweise liegt mein Bild auf der Seite. Ich schaue in die Dateiverwaltung und sehe beide Bilder P1040893.JPG (ungedreht) und p1040893.jpg (gedreht).
5.) Ein Klick auf Bearbeiten zeigt mir bei beiden(!) Bildern die Bildunterschrift, die ich nur einmal gesetzt habe. Im FE wird die Bildunterschrift aber nie angezeigt, egal welches Bild ich eingebunden habe.
6) Ich lösche die von der Redakteurin hochgeladene Datei, worauf auch bei meinem Bild die Bildunterschrift verschwindet.

Vor der Löschung hatte ich mir tl_files in der Datenbank angeschaut. Dort hatte jedes hochgeladene Bild seine eigene ID bekommen. In der Spalte "name" stand jeweils derselbe Dateiname in Kleinschreibung ohne Pfad. Aber das ist wohl normal.

Kann das Verhalten jemand nachstellen? Ich versuche es auch nochmal.

**Comment by thomaspahl** [comment]
Das ist leider sehr leicht zu reproduzieren, auch auf anderen Wegen (in 3.2.19):
Um die beteiligten Funktionen minimal zu halten, habe ich zunächst die files außerhalb Contao erstellt:
1. files/test/image.jpg außerhalb Contao erstellt
2. Dateiverwaltung, zeigt image.jpg an, dort Bildunterschrift eingefügt. Jetzt in der Datenbank.
3. files/test/IMAGE.JPG erstellt (in Linux bzw. case-erhaltendem NAS), physisch gibt es jetzt 2 files.
4. Dateiverwaltung aufgerufen, dort gibt es jetzt beide files, klein und groß, und bei beiden(!) wird die Bildunterschrift des ersten Bildes angezeigt. In der Datenbank steht bisher aber nur das erste Bild.
5. Ändere ich jetzt nur an IMAGE.JPG die Beschriftung, wird diese Änderung danach bei beiden angezeigt. In der Datenbank steht aber immer noch nur das erste Bild (image.jpg).
6. Synchronisiere ich die Dateiverwaltung, steht immer noch nur image.jpg drin.
7. Lade ich IMAGE.JPG hoch, wird der Eintrag von image.jpg auf IMAGE.JPG geändert (im `path` steht der richtige Name, in `name` steht weiterhin die lower-case Version). Es gibt aber immer noch nur 1 Eintrag.
8. Lade ich dann auch image.jpg hoch, springt der Pfad im vorhandenen Eintrag wieder auf lower-case.
9. Nach Löschen des Eintrags in der DB und neu Synchronisieren gibt es immer noch nur einen Eintrag (path=.../image.jpg). In der Dateiverwaltung werden beide Bilder angezeigt, aber beide mit dem Thumbnail von IMAGE.JPG.
10. Die Bilder beide in die Datenbank zu bekommen ist mir nicht gelungen.

**Comment by Samson1964** [comment]
Der einzige Unterschied ist dann wohl: Wir haben die Dateien über die Dateiverwaltung hochgeladen und es existierten richtigerweise zwei Datensätze. Im BE/FE wird aber offensichtlich nur auf einen Datensatz zurückgegriffen und der andere ignoriert.

**Comment by leofeyer** [comment]
Siehe #7627.
