### ISSUE TITLE
Model "Archive Menu News" ignoriert

### ISSUE THREAD

**Issue by luger95** [contao/core#7642]
Hallo,

Erstelle ich einen "News-Archiv Menü" Modul, ich habe mehrere Archivtypen ausgewählt, ich sagte: "Jahr" in "Archivformat" in der benutzerdefinierten Vorlage "mod_newsmenu_year_select" Modul, das ist eine Kopie der "mod_newsmenu_year" aber was auch immer das Inhaltsmodell, wodurch die Stirn nicht ändert.

Ich glaube, dass das Modul nicht mein eigenes Template enthalten.

Danke.

**Comment by ChrisEbert** [comment]
Kann ich bestätigen, hab das selbe Problem. Der Modultyp "Nachrichtenarchiv-Menü" lässt kein individuelles Template zu. Das individuelle Template wird zwar gespeichert, im Frontend wird es aber nicht geladen.

**Comment by luger95** [comment]
This problem is very annoying.

**Comment by vmulot** [comment]
Same problem here with the mod_newsmenu_year template, can"t use another one than the default one.

**Comment by BugBuster1701** [comment]
What is your Contao version?

**Comment by luger95** [comment]
3.4.5

**Comment by leofeyer** [comment]
Das Problem sollte in Contao 3.5 behoben sein.
