### ISSUE TITLE
Issues with replacing insert tags in the backend

### ISSUE THREAD

**Issue by dmolineus** [contao/core#7647]
Since Contao 3.4 insert tags for RTE fields are replaced in the backend (see #7428).

This raises some issues:
 - Users don't see where an insert tag is used in the content element preview anymore.
 - Some inserttags creates wrapping html code which breaks backend view now.

**Comment by aschempp** [comment]
I guess we should only replace {{file}}-Inserttags…

**Comment by Aybee** [comment]
A hint that the content gets rendered by an InsertTag could also be helpful.

What if we strip all inline-style? I think this is the only one that can cause a break of the backend view. Am I wrong?

![article-home-contao-344](https://cloud.githubusercontent.com/assets/1143013/6268696/1c2622bc-b84f-11e4-955e-c75709f3b4a9.png)

**Comment by leofeyer** [comment]
Fixed in 0bb7a11b07d9c4bd537bd5490b000c1e03e81859.
