### ISSUE TITLE
PageCache der Root-Seite funktioniert nicht bei Sprach-Fallback

### ISSUE THREAD

**Issue by amenk** [contao/core#7650]
Szenario:

* Browser sendet Http Accept Language en-US,en,de
* Seitensprache ist de + Fallback (nur ein Seitenbaum)

In addToCache wird jetzt die Sprache der Seite verwendet (in meinem Fall z.B. de)
In outputFromCache wird die Http Accept Language verwendet
Das führt zu einem Cache Tag empty.en-US welches nicht existiert. Folglich kommt ein Cache-Miss zustande.

**Comment by BugBuster1701** [comment]
Hat Ähnlichkeit mit https://github.com/contao/core/issues/7618
Wie hier zu lesen "Eine Datenbank-Abfrage kommt jedoch beim Laden aus dem Cache keinesfalls in Frage."
Also wird das wohl nicht so einfach lösbar sein.

**Comment by amenk** [comment]
Duplicate von #7618 - sorry
