### ISSUE TITLE
Sass @mixin und @extend

### ISSUE THREAD

**Issue by adihimself** [contao/core#7651]
Hi,

ich habe meine scss Datei direkt in Contao inkludiert und seitdem funktionieren meine mixins und extends nicht mehr.
Gibt es eine Möglichkeit die Funktionen zu nutzen?

Contao Vers. 3.4.0

LG

**Comment by grusch-it** [comment]
Kann ich nicht nachvollziehen - hier klappen mixins mit 3.4.4 ohne Probleme.

Eine etwas detaillierte Fehlerbeschreibung sowie Auszüge aus den SASS-Dateien wären sicherlich hilfreich!

**Comment by adihimself** [comment]
Mittlerweile funktioniert bei mir auch alles. Keine Ahnung wieso es nicht lief. closed
