### ISSUE TITLE
Form captcha inside events not working

### ISSUE THREAD

**Issue by tsarma** [contao/core#7653]
When content element of type from is placed inside events, form captcha is on working. Hence we can not submit the form.

Goto online demo website:
1. Login backend
2. goto: http://demo.contao.org/contao/main.php?do=calendar&table=tl_content&id=6
3. Add a second content element of type form. (Contact (ID: 5))
4. goto: http://demo.contao.org/en/event-detail/contao-north-day.html

The form will not work.

**Comment by leofeyer** [comment]
Why did you close the ticket?

**Comment by tsarma** [comment]
Opps, I thought it is of not much interest. And I do not want open tickets lying around.

**Comment by leofeyer** [comment]
Just be patient. We have a lot of work and a lot of open tickets :)

**Comment by leofeyer** [comment]
I cannot reproduce this issue. The form was submitted without a problem when I tried it.
