### ISSUE TITLE
Problem nach Umstellung auf Apache 2.4

### ISSUE THREAD

**Issue by Samson1964** [contao/core#7654]
Domainfactory hat bei allen Kunden am 18. Februar 2015 den Apache auf die Version 2.4 aktualisiert. Daraus ergeben sich einige grundlegende Änderungen in der .htaccess

[Mitteilung Domainfactory](https://www.df.eu/forum/threads/75708-Aktualisierung-des-Apache-Webservers-am-18-02-2015?highlight=apache)

Ich war deswegen in Kontakt mit dem Support und postete die nicht mehr funktionierenden .htaccess aus /system und beispielhaft aus /system/modules/news/assets (jeweils Contao 3.2.19):

Hier der Inhalt von /system/.htaccess:
```
<IfModule !mod_authz_core.c>
   Order deny,allow
   Deny from all
</IfModule>
<IfModule mod_authz_core.c>
   Require all denied
</IfModule>
```
Und hier von /system/modules/news/assets/.htaccess
```
<IfModule !mod_authz_core.c>
   Order allow,deny
   Allow from all
</IfModule>
<IfModule mod_authz_core.c>
   Require all granted
</IfModule>
```
Folgende Antwort kam vom Support:
Bei mod_auth-Statements gab es auch eine Änderung. "Deny from all" bdeutet nun auch tatsächlich, dass niemand mehr zugreifen darf. "Allow from all" selbst gibt es nach der neuen Syntax nicht mehr. Wenn nichts hinterlegt ist bedeutet dass das alle zugreifen dürfen, wenn "Require ip (...)" oder "Require host (...)" eingetragen ist wird der Zugriff auf Einzelne eingeschränkt. 

Damit ist Contao wohl nicht mehr Apache-2.4-kompatibel.

**Comment by BugBuster1701** [comment]
Da ist doch extra eine Weiche drin? Allow from all wird doch nur verwendet wenn das Modul mod_authz_core.c **nicht** geladen ist. Was bei Apache 2.2 der Fall sein sollte.
Bei Apache 2.4 gilt nur der untere Abschnitt. Sollte also alles laufen.
Macht DF da was anders?

**Comment by BugBuster1701** [comment]
Wurde in Contao 3.1 so geändert. Hast du vielleicht ne ältere dort zu laufen?

**Comment by Samson1964** [comment]
Ich habe nochmal eine Nacht drübergeschlafen. Nach dem Studium der bisherigen Beiträge zu Apache 2.4 und Contao, dem Nachdenken darüber was passiert ist - (nur!) Firefox fand einige CSS-Dateien und Icons nicht mehr - bin ich zu folgendem Schluß gekommen: Alles in Ordnung!

Der Domainfactory-Supporter hat mich auf die falsche Fährte gelockt. tatsächlich sind die htaccess-Dateien kompatibel mit Apache 2.4 - auch bei Domainfactory. Allerdings gibt es bei einigen Fremderweiterungen noch veraltete htaccess. Und die wurden jetzt mit der Softwareumstellung auf den neuen Apache mit einem Schlag ungültig.
