### ISSUE TITLE
Validierung für Datum- und Zeitformat (Einstellungen)

### ISSUE THREAD

**Issue by Dancger** [contao/core#7655]
Nicht nummerische Datums- und Zeitformate bringen Contao zum Absturz:
Fatal error: Uncaught exception Exception with message Invalid date format "d.M.Y"....

Bitte um eine Validierung im Backend oder einen entsprechenden Hinweis (z.B. Achtung: Nur nummerische Werte verwenden!) unter den entsprechenden Feldern (Datumsformat, Zeitformat, Datum- und Zeitformat).

Thread: https://community.contao.org/de/showthread.php?22961-Fehler-Invalid-Date-Format-bei-Nachrichten&p=360227&viewfull=1#post360227

**Comment by leofeyer** [comment]
Siehe #7433, #5212, #1628 oder #765.
