### ISSUE TITLE
Verlinkung zu News und Events (Entwurf)

### ISSUE THREAD

**Issue by jankout** [contao/core#7656]
Liebes Entwicklungsteam,

ich habe einen Entwurf für die Verlinkung zu News und Events erstellt (siehe Anhang). Ich und meine Kunden würden uns sehr freuen, wenn es in der Grundinstallation inbegriffen wäre. Wenn man schon diese Module für News und Events damit liefert, wäre es auch gut, dass man auch die interne Verlinkung anbietet, wie es bei Dateien und Seiten der Fall ist. 

Bei weiteren Fragen stehe ich euch gerne zur Verfügung. 

Liebe Grüße,

Jan
![verlinkung-fur-alle-internen-sachen-contao_jan-kout](https://cloud.githubusercontent.com/assets/3715050/6387804/738bd578-bd91-11e4-9eb7-90802bad4605.png)

**Comment by Samson1964** [comment]
+1

**Comment by akroii** [comment]
+1

**Comment by christianromeni** [comment]
+1

Das ganze sollte dann erweiterbar sein, um eigene Module hinzufügen zu können.

**Comment by Toflar** [comment]
> Das ganze sollte dann erweiterbar sein, um eigene Module hinzufügen zu können.

Was sinnvoll wäre, aber bereits aufzeigt, dass der Vorschlag impraktikabel ist. Die Liste würde möglicherweise viel zu lang :)

**Comment by jenda77** [comment]
@leofeyer Was hältst Du davon? Ich denke, dass eine große Verbesserung der Benutzerfreundlichkeit wäre, wenn man Events, News, FAQ komfortabel über TinyMCE über eine Benutzeroberfläche statt über Iserttags verlinken könnte. Die jetzige Lösung finde ich stiefmütterlich, weil man eigene Module, die toll sind, vernachlässigt und nicht für andere Module so komfortabel erreichbar macht. Ich wäre sicherlich nicht der Einzige, der sich darüber sehr freuen würde - abgesehen von vielen Kunden, die mit Contao arbeiten.

**Comment by jenda77** [comment]
@leofeyer @Toflar Ich wollte fragen, ob ihr längerfristig diese, meiner Meinung nach, grundlegende Funktion einbauen möchtet (Verlinkung zu News, Events, FAQs im TinyMCE-Editor)? Momentan finde ich und auch viele Kunden recht benutzerunfreundlich die Links zu News, Events, FAQs zu setzen. Das bedarf mehrere Schritte, um die richtige ID herauszufinden, statt konform in dem vorhandenen Editor die Event-News- oder FAQ-Liste abzurufen und den gewünschten Beitrag auszuwählen, ohne sich im Becken von der Stelle "bewegen" zu müssen. Wie ich schon oft schrieb, wäre das eine große Verbesserung der Benutzerfreundlichkeit und damit würde man diese eigenen (!) Module im TinyMCE-Editor nicht mehr stiefmütterlich behandeln wie bis jetzt. 

Ich fände das wirklich richtig toll und gebe hier keine Ruhe, solange ich kein gutes Argument bekomme, warum das nicht wichtig ist. :-)

**Comment by Toflar** [comment]
> Ich fände das wirklich richtig toll und gebe hier keine Ruhe, solange ich kein gutes Argument bekomme, warum das nicht wichtig ist. :-)
> 
Niemand hat je das Gegenteil behauptet.

**Comment by jenda77** [comment]
Leider habe ich diesen Eindruck nach ein paar Jahren bekommen. Im Forum und hier wurde mehrmals über die Jahre das Bedürfnis geäußert. 

Und ich bin davon überzeugt, dass man damit vielen Nutzern/Kunden eine große Freude machen würde. 

Ich wünsche mir hier eine sachliche Diskussion, wie man das eingehen kann. Das kann uns weiterbringen. 

Zugleich sehe ich als eine Chance,  das Contao noch mehr konkurrenzfähiger zu machen. Und das fände ich auch großartig und nachhaltig, weil ich Contao mag und gerne benutze. :-)

**Comment by jenda77** [comment]
Und gerne kann ich mich noch damit befassen, wie man das lösen kann. :-)

**Comment by christianromeni** [comment]
Steht das eigentlich noch irgend wann auf dem Plan? Ich bekomme ständig die Frage von unseren Kunden wie es Möglich ist direkt auf eine News zu verlinken. Das ist echt bitter Nötig.

**Comment by jenda77** [comment]
Darüber würde ich mich und meine Kunden sich auch sehr freuen. Damit würde Contao ein Stück benutzerfreundlicher. ;-)

**Comment by akroii** [comment]
Same here.

**Comment by jenda77** [comment]
@leofeyer @aschempp I would like to ask you again whether you could implement it. It would be a big improvement of the user experience and make Contao really accessible and user friendly across the whole application.

**Comment by fritzmg** [comment]
Yes, I do support the idea of course, many of our customers often link to news entries, but currently they can only do that by copying the absolute link (from a news list for example), which is cumbersome and not ideal should the domain change.

**Comment by pandroid** [comment]
Same here. 
+1

**Comment by michelbalzer** [comment]
+1

**Comment by fenepedia** [comment]
+1

**Comment by jscholtysik** [comment]
+1

**Comment by ADoebeling** [comment]
+1

**Comment by Aybee** [comment]
:+1:

**Comment by fritzmg** [comment]
Btw. this should be implemented as a general picker (e.g. for the `tl_content.url`, `tl_content.imgUrl`, `tl_news.source` and `tl_calendar_events.source` field), not just for the link functionality in TinyMCE.

**Comment by freiwild** [comment]
+1 Great Idea. Auch meine Kunden möchten oft von News auf Events oder umgekehrt verlinken. Umsetzung evtl. als Inhaltselement.

**Comment by mauricemoss** [comment]
Was macht ihr hier eigentlich?!! Ich beschäftige mich grad zum ersten Mal (auf Kundenwunsch) intensiver mit Contao und bekomm den Mund vor lauter Staunen nicht mehr zu.... Ich bin mir nicht mal sicher, ob der Kunde weiß, dass sowas geht; was umso trauriger wäre, weil es eine Selbstverständlichkeit sein sollte. Ich werd versuchen ihn noch von einem Relaunch zu überzeugen.
Abschließend und der Konstruktivität wegen: +1 für die Verlinkungen!

**Comment by jankout** [comment]
@mauricemoss Dazu kann ich Ihnen nur sagen, dass wir diese, meiner Meinung nach, grundlegende Funktion seit Jahren erwarten, verlangen. Ich weiß es selber nicht mehr, wie ich das Entwicklungsteam dazu motivieren kann, das wirklich bald umzusetzen. Für mich gehört es auch zu einer der Grundfunktionen. 

Ich verstehe, dass Contao ein Open-Source-Projekt ist, aber wenn ich mir die anderen anschaue (Drupal, Typo3), werden wichtige Funktionen, die von den Kunden vorgeschlagen wurden/werden, schon schneller implementiert. Vielleicht muss man bei Contao das Entwicklungsteam auch vergrößern und überlegen, ob man da noch eine andere Geldquelle findet, um die Contao-Entwicklung zu finanzieren und somit voranzubringen? 

FontAwesome hat es neulich gezeigt, wie das gehen kann, wenn viele Nutzer tolle neue Funktionen haben und genießen wollen. Jetzt wissen die FontAwesome-Entwickler, dass sie einen Fulltimejob haben. 

Ich bitte hier noch einmal ausdrücklich, Contao an den Core-Stellen noch mehr benutzerfreundlicher zu machen. Davon hängt die Zukunft von Contao ab. Danke.

**Comment by zonky2** [comment]
@mauricemoss ich bin bei MetaModels recht aktiv dabei und erlaube mir mit dem Hintergrund ein paar Worte...

Wenn Du das _unbedingt haben willst_, und Du nicht in der Lage bist, das selbst zu programmieren, suche Dir jemanden, der das macht, bezahle ihn und gebe das Ergebnis zur freien Verfügung der Contao-Community!

> Vielleicht muss man bei Contao das Entwicklungsteam auch vergrößern

Ich möchte deine - im meinen Augen naive - Ansicht dämpfen. Es ist leider nicht so, dass man mal eine kurze Rundmail schreibt und plötzlich 10 neue Core-Programmierer zur Stelle stehen. Eine Beauftragung gegen Geld steht hier auch außer Frage.

>und überlegen, ob man da noch eine andere Geldquelle findet

Wie wäre es, dass "man" gegen "ich" auszutauschen?!? Dir wird sicher keiner Steine in den Weg legen, wenn Du für die Entwicklung von Contao Sponsoren auftreibst. Von MetaModels und anderen "4free-Projekten" kenne ich das "Geschäft" und dessen Relation von Aufwand zu Spende... Aber vielleicht bist Du ja der "Weiße Ritter" für Contao...

**Comment by mauricemoss** [comment]
In der Zwischenzeit empfehle ich euch (wie auch meinem Kunden) einen Blick auf ProcessWire CMS.
Und mal eine ernstgemeinte Frage an die "Disliker". Wie soll ich denn bitte ohne rot zu werden einem Kunden erklären, dass er um einen Link auf einen Beitrag INNERHALB des System zu setzen, vorher die ID des Beitrags finden und sie sich merken muss, um diese dann dort wo er den Link erstellen möchte wieder händisch einzufügen. Baut mal eine Liste mit 3, 4 Links zu Beiträgen ohne Stift und Papier zu Hilfe zu nehmen.

**Comment by frontendschlampe** [comment]
@mauricemoss Man kann auch einfach die URL aus dem Frontend kopieren und im Link einfügen. Dann muss man sich keine ID's merken.

Aber trotz alledem: Heute ist offizieller Contao Mumble Call und das Thema hat ein "Up for Discussion"-Label, was bedeutet, dass es in einem Mumble-Call besprochen wird.

**Comment by asaage** [comment]
> Baut mal eine Liste mit 3, 4 Links zu Beiträgen ohne Stift und Papier
In dem Fall würde ich einfach das "featured" Feature der Beiträge verwenden.

**Comment by jankout** [comment]
@zonky2 Während hier über grundlegende Funktionen gestritten wird, freuen sich woanders über so einen Vorschlag. Diese Einstellung muss sich bei Contao ändern. Heutzutage lebt Sotwareentwicklung vom Nutzerfeedback mehr denn je und viele Firmen schätzen das sehr, weil das ihre Produkte konkurrenzfähiger macht. Und Contao bekommt immer mehr Konkurrenz. 

Und ich würde auch gerne etwas bezahlen - ich verstehe nicht, warum zonky2 mir etwas anderes unterstellt. Investieren gerne, aber nur unter einer Bedingung: wenn ich weiß, was genau für mein Geld umgesetzt wird und ob es wirklich eine deutliche Verbesserung der Handhabung für meine Kunden wird. Daher habe ich mit einer großen Freunde FontAwesome unterstützt, weil es von Anfang an klar war, was das Entwicklungsteam vorhat. Daraus wurde noch mehr, weil sie viele schon mit den ersten Vorschlägen begeistert haben.

Bitte lassen wir uns von anderen inspirieren und die Konkurrenz ernst nehmen, sonst bleibt Contao weiterhin "nur" interessant überwiegend im deutschsprachigen Raum. Und das ist, glaube und hoffe ich, nicht der Sinn der Sache, oder?

**Comment by zonky2** [comment]
> Und ich würde auch gerne etwas bezahlen

mit "Konjunktiv" und "man" habe ich bisher noch nie erlebt, dass was passiert ist... Vorschläge sind gut und wichtig - mache ich auch

Die o.g. Sichtweise, wie bestimmte Sachen umgesetzt werden können, halte ich für "weltfremd" bei einem OpenSource-Projekt.

**Comment by kikmedia** [comment]
> Bitte lassen wir uns von anderen inspirieren und die Konkurrenz ernst nehmen, sonst bleibt Contao weiterhin "nur" interessant überwiegend im deutschsprachigen Raum. 

Irgendwie klingt das als würdest Du das gesamte Contao-Team für mindestens leicht bescheuert halten. Sorry, kein Verständnis dafür.

**Comment by jankout** [comment]
@kikmedia das ist nur deine Interpretation. Mein Satz ist ermutigen gemeint.

**Comment by jankout** [comment]
Der hier erwähnte Vorschlag habe ich aus verschiedenen Forenbeiträgen aufgegriffen, was viele seit Jahren verlangen. Viele Kunden haben damit wirklich Probleme. Ich bitte nur darum, das ernst zu nehmen. Danke und noch einen schönen Tag.

**Comment by NinaG** [comment]
Ich denke, es wird ernst genommen. Es ist aber oft eine Frage der Priorisierung. Hoffentlich können wir gemeinsam dafür sorgen, z.B. durch die Besprechung im Mumble Call,dass dieser Wunsch höher priorisiert wird :)

Grundsätzlich kann ich den Wunsch, nach einer für Redakteure leichten Verlinkung zu News/Events auf jeden Fall nur dringend unterstützen, wie ich bereits zu diversen Gelegenheiten gesagt habe.

**Comment by jankout** [comment]
Hallo, wie sieht es aus. Wurde das als eine der demnächst wichtigsten Funktionen übernommen? Wie mehrmals geschrieben, viele würden sich darüber sehr freuen. Und zwar über Jahre hinweg.

**Comment by leofeyer** [comment]
Siehe https://github.com/contao/core-bundle/pull/755.

**Comment by jankout** [comment]
Vielen lieben Dank an alle Entwickler. Eine tolle Arbeit. Das ist noch eine weitere Motivation, zu 4.4 zu wechseln.
