### ISSUE TITLE
Administratorlogin nach Installation nicht möglich

### ISSUE THREAD

**Issue by AMAF** [contao/core#7657]
Hallo, ich habe hier gerade ein sehr seltsames Problem mit einer Contao 3.4.4 Installation.
Ich habe die Installation per wget direkt vom Webserver aus geladen, entpackt und eingespielt. Danach habe ich über die ../contao/install.php die absolute Grundeinrichtung vorgenommen. Soweit alles ok, unter anderem habe ich natürlich einen administrativen Grundaccount angelegt. Soweit ok.

Ich habe dann versucht mich mit dem gerade angelegten Account anzumelden - Login fehlerhaft Meldung ("Anmeldung fehlgeschlagen (Benutzernamen und Passwörter unterscheiden zwischen Groß- und Kleinschreibung)!"). Natürlich habe ich es nochmal probiert (in der Annahme ich habe mich vertippt), mit dem selben Ergebnis. Anschließend habe ich, in der Annahme ich habe Unfug beim Anlegen eingegeben, alle Tabellen im MySQL per PhpMyAdmin gelöscht. Anschließend über das Install-Tool wieder angelegt, Administrator angelegt: Immer noch selbes Problem.

Im folgenden habe ich dann per PhpMyAdmin in der tl_user Tabelle für das Passwortfeld hart mit SHA1 als Funktion in das Feld mein Wunschpasswort eingetragen. Eingeloggt in Contao, alles wunderbar, geht, ich bin im Backend. Also zum testen ob das nur das Installscript betrifft schnell einen weiteren Nutzer mit administrativen Rechten aus dem Backend heraus angelegt, gespeichert, ausgeloggt. Damit einloggen wollen, wieder die "Benutzername-Passwort-Falsch" Meldung. Wieder mit dem ursprünglich aus dem Installtool angelegten Administrator einloggen: Geht auch nicht mehr. Wieder in die tl_user geschaut: Contao hat die Passwörter für beide nun existierenden Nutzer umgeschrieben (sahen danach wieder aus wie vom Installtool angelegt, das SHA1 sieht deutlich anders aus).

Ich hoffe ich melde jetzt keinen schon bekannten Bug, aber das ist absolut reproduzierbar gerade (natürlich nur bei mir, das offizielle Demosystem kann ich schlecht neu installieren).

Contaoversion ist die 3.4.4 als tar.gz, auf der Zielmaschine (da ahne ich böses) läuft aus Gründen ein PHP 5.3.3-7 mit Suhosin-Patch.

**Comment by AMAF** [comment]
Hinweis: Ich habe gerade an selbe Stelle eine 3.2.19 LTS installiert, da ist das Problem nicht vorhanden.

**Comment by aschempp** [comment]
Possibly related to https://github.com/contao/core/issues/7489

**Comment by leofeyer** [comment]
Tritt das Problem in Contao 3.5 noch auf?

**Comment by leofeyer** [comment]
Hatte das Passwort zufällig Sonderzeichen? Ich meine mich zu erinnern, dass wir in Contao 3.5 etwas umgestellt haben, um alle Sonderzeichen in Passwörtern zu unterstützen.
