### ISSUE TITLE
Argument 1 passed to Contao\Model\Registry::register() must be an instance of Model

### ISSUE THREAD

**Issue by garyee** [contao/core#7658]
Hallo,

hab einen kleinen Bug gefunden.
Für ein Projekt habe ich meine eigenen Models geschrieben.
Jetzt kommt da ein Fehler wenn ich MeinModel::findbyPK("id");
machen will:
Das Problem ist in der [Zeile](https://github.com/contao/core/blob/master/system/modules/core/library/Contao/Model/Registry.php#L109):

```php
public function register(\Model $objModel)
```
es kommt der Fehler:

```php
Recoverable error: Argument 1 passed to Contao\Model\Registry::register() must be an instance of Model, instance of Hot\SeasonModel given, called in /www/htdocs/w01172b0/test2.postyou.de/system/modules/core/library/Contao/Model.php on line 164 and defined in system/modules/core/library/Contao/Model/Registry.php on line 109

// etc.
``` 
wenn die Zeile in 
```php
public function register(\Contao\Model $objModel)
```
geändert wird, gehts wieder.

Ist so ein Namespace ding glaub ich. Meine eigenen Models haben auch ihren eigenen Namespace, falls das eine Rolle spielt.

**Comment by Toflar** [comment]
Nein, dein Model muss einfach das von Contao extenden und zwar das vom globalen Namespace, nicht das von Contao, dann funktioniert das schon.

**Comment by garyee** [comment]
Ha mm gut
