### ISSUE TITLE
Duplicate content with page ID

### ISSUE THREAD

**Issue by aschempp** [contao/core#7661]
The following two URLs get the same page:

http://demo.contao.org/en/modules.html
http://demo.contao.org/en/49.html

**Comment by Tastaturberuf** [comment]
Ja, aber in der Sitemap landet nur eines. Die Diskussion dazu finde ich ich nicht mehr (des geht dort generell um den Umstand vom Model ```::getIdOrAlias```. Suchmaschinen würden die ID-Variante nie von alleine finden, der duplicate Content ist also relativ.

**Comment by aschempp** [comment]
Das ist mit dem `/index.php` in der URL aber dasselbe…

**Comment by leofeyer** [comment]
You are right, but I have no idea of how to solve this.

**Comment by aschempp** [comment]
Can't we simply disallow to a page with ID if the alias is not empty? Similar to what we do with the `index.php` fragment?

**Comment by leofeyer** [comment]
I like the idea. We should definitely try it.

**Comment by leofeyer** [comment]
Fixed in 4ef3fe03a1f2c74b512df427c6b19b9858e43f39.

**Comment by Tastaturberuf** [comment]
Hab grade überlegt ob es nicht sinnvoller ist dann einen Canonical zu setzen, so hätte man ein Feature für Kurze URLs und duplicate Content gibt es dadurch auch nicht mehr.

**Comment by backbone87** [comment]
Dies ist ein BC-Break, vorhandene Erweiterungen (z.B. meine backboneit_trueurl) die den getPageIdFromUrl-Hook benutzen und dabei im $arrFragments[0] eine Seiten-ID zurückgeben (weil der Hook schon die Seitenauflösung durchgeführt hat) resultieren dann in 404-Seiten..

**Comment by backbone87** [comment]
AFAIK ist es kein Duplicate Content, wenn der gleiche Inhalt unter verschiedenen Pfaden der gleichen Domain zu erreichen ist. Duplicate Content soll nur sicherstellen das "deine" Seite keinen "interessanten" Inhalt anderer Seiten nimmt, sondern sollte selbst Inhalte kreieren.

**Comment by Tastaturberuf** [comment]
>Hab grade überlegt ob es nicht sinnvoller ist dann einen Canonical zu setzen, so hätte man ein Feature für Kurze URLs und duplicate Content gibt es dadurch auch nicht mehr.

**Comment by aschempp** [comment]
> Dies ist ein BC-Break, vorhandene Erweiterungen (z.B. meine backboneit_trueurl) die den getPageIdFromUrl-Hook benutzen und dabei im $arrFragments[0] eine Seiten-ID zurückgeben (weil der Hook schon die Seitenauflösung durchgeführt hat) resultieren dann in 404-Seiten.

Das Problem hatte ich in Isotope auch. Man muss im Hook halt das Alias zurückgeben…

**Comment by BugBuster1701** [comment]
Bin ich auch schon drüber gestolpert, denn selbst getPageIdFromUrl() gibt den Alias zurück, die nicht ID wie der Name vermuten lässt.
Daher sollte man das im Hook auch so tun.

**Comment by leofeyer** [comment]
Behoben in e11027c5cce1f7b6431fbfa0f76193526d7ba79d.

**Comment by fritzmg** [comment]
I am not sure what the status on this is now - are pages supposed to be accessible via their ID in Contao `>=3.5.3` now or not? Currently it _is_ possible to access a page via its ID instead of its alias. For example: http://demo.contao.org/en/48.html (vs. http://demo.contao.org/en/content-elements.html)

**Comment by Webstylerin** [comment]
Whats the current status of this issue? Should it be possible to access the page via ID or not? I have a 3.5.15 site where it is possible to open the page via alias and via ID but fritzmg said some month ago it was fixed.
