### ISSUE TITLE
Requests are handled slowly

### ISSUE THREAD

**Issue by amenk** [contao/core#7662]
Page views take around one second to respond. Before the update to 3.4 it was around 0.3secs

Can this be fixed?

**Comment by BugBuster1701** [comment]
With or without cache? I have no performance problems with Contao 3.4.
(Internal cache is built and page cache is enabled.)

**Comment by amenk** [comment]
pagecache disabled, other caches enabled.

**Comment by Zeromax** [comment]
any thirdparty module enabled?

**Comment by amenk** [comment]
I use the alpha theme and it's modules.
