### ISSUE TITLE
Formularfeld bearbeiten keine Checkbox für Sichtbarkeit

### ISSUE THREAD

**Issue by Mynyx** [contao/core#7663]
Bei der Ansicht zum Bearbeiten eines Formularfeldes fehlt die Checkbox für die Sichtbarkeit, wie sie z. B. bei Inhaltselementen vorhanden ist.

**Comment by Mynyx** [comment]
Fehlen hierzu noch Infos?

**Comment by leofeyer** [comment]
Das stimmt, aber braucht man die unbedingt? Reicht das Auge-Icon nicht? @contao/developers

**Comment by Toflar** [comment]
Das ist mir noch gar nie aufgefallen. Aber aus Gründen der Konsistenz würde ich das eigentlich hinzufügen, ja.

**Comment by aschempp** [comment]
Ja, wir haben das vor einiger Zeit auch bei Inhaltselementen deshalb eingeführt.

**Comment by leofeyer** [comment]
Nein, das stimmt so nicht. Wir haben das bei Inhaltselementen eingefügt, weil wir das zeitgesteuerte Veröffentlichen hinzugefügt haben. Aber bei Formularfeldern oder auch bei Formatdefinitionen (Stylesheets) gab es noch nie eine Checkbox dafür.

**Comment by leofeyer** [comment]
Wurde inzwischen implementiert.
