### ISSUE TITLE
Auswahlfelder im unteren Bereich nicht klickbar

### ISSUE THREAD

**Issue by xchs** [contao/core#7668]
In aktuellen Firefox- bzw. Chrome-Versionen sind – jedenfalls unter Windows – einige Auswahlfelder (z. B. Backend-Login, Installtool, Contao Check usw.) am unteren Randbereich nicht klickbar, da das eigentliche Select-Element mit dem gestylten Auswahlfeld nicht (mehr) vollständig übereinstimmt:

![select](https://cloud.githubusercontent.com/assets/1218766/6471110/b0e81958-c1e8-11e4-8355-01b2838f5830.png)

Ich bin mir nicht ganz sicher, aber die folgenden Styles aus der `stylect.css` braucht es neuerdings (?) offenbar auch nicht mehr:
```{.css}
.firefox .styled_select {
	line-height:21px;
}

.win.firefox .styled_select {
	line-height:22px;
}
```
Keine Ahnung, wie die ganze Sache unter OS X aussieht.

**Comment by leofeyer** [comment]
Das Problem ist, dass das Select-Feld nicht so hoch ist wie das Stylect-Menü:

![](https://cloud.githubusercontent.com/assets/1192057/7931414/d9378668-0910-11e5-8754-1f6748b465a4.png)

Das rot hinterlegte ist das originale Select-Feld. Wir können diesem aber auch nicht einfach `height: 22px` zuweisen, weil das die Abstände der anderen Elemente beeinflusst.

Im Rahmen des nächsten Feature-Releases könnte ich mir das anschauen.

**Comment by aschempp** [comment]
Dann sollten wir generell das Stylect überarbeiten, da es damit öfters auch mal floating-Probleme gibt.

**Comment by leofeyer** [comment]
Eventuell geht es mit `margin-bottom: 1px` und `height: 22px` (im Firefox `height: 23px`). Hab es bisher aber nur auf Mac getestet.

**Comment by Aybee** [comment]
Ich habe gerade festgestellt, dass das Problem nur in der Online-Demo auftritt. In einer normalen Installation werden alle Sprachen angeboten, in der Demo nur Englisch. In einer normalen Installation "drücken" Chinesisch und Japanisch die OPTIONS auf eine Höhe von 17px, die anderen haben 15px.

Mit diesem CSS müsste es eigentlich zu beheben sein:
```css
option {
  height: 17px;
  line-height: 17px;
}
```
Windows 10, FF 42

**Comment by leofeyer** [comment]
Ich habe ein paar Tests gemacht:

![](https://cloud.githubusercontent.com/assets/1192057/11213693/a04e7dd2-8d3d-11e5-9f10-f265d714e32a.png)

![](https://cloud.githubusercontent.com/assets/1192057/11213694/a04e8570-8d3d-11e5-8c6d-35c41058b073.png)

![](https://cloud.githubusercontent.com/assets/1192057/11213695/a04f0950-8d3d-11e5-9ca3-6e90f0e99261.png)

![](https://cloud.githubusercontent.com/assets/1192057/11213698/a053f69a-8d3d-11e5-932a-085bd55d3ff4.png)

![](https://cloud.githubusercontent.com/assets/1192057/11213696/a04fa19e-8d3d-11e5-8e6d-1d18c29f47d5.png)

![](https://cloud.githubusercontent.com/assets/1192057/11213697/a04fe1d6-8d3d-11e5-9b84-45f84c6f74aa.png)

Mit `margin-bottom: 1px` und `height: 22px` funktioniert es in allen getesteten Browsern. Firefox benötigt jedoch `23px` Höhe unter Mac und `24px` unter Windows – früher schrieben wir Extra-Code für den IE, heute ist es Firefox :(

**Comment by leofeyer** [comment]
Behoben in 9a672db487d8c5d930575aa67604957092f4c614.

**Comment by Aybee** [comment]
Hattest du meine Lösung auch mal ausprobiert, damit hätten alle Options die gleiche Höhe.

**Comment by leofeyer** [comment]
IMHO ist es nicht möglich, die Höhe des `<option>`-Tags in Webkit per CSS zu ändern.

**Comment by Aybee** [comment]
Ups, sorry, das hätte ich jetzt überhaupt nicht erwartet. Danke für die Info.
