### ISSUE TITLE
BE filter Select-Feld mit optgroups

### ISSUE THREAD

**Issue by garyee** [contao/core#7672]
Hallo,

ich habe eine eigene Tabelle/view mit einem Feld (Inputtyp select) das ich gerne Filtern würde und, ich bräuchte aber auch Optgroupse.
Wenn ich die Funktion im Option_callback so gestalte das sie mir ein einfaches (key=>value) Array zurück gibt, also ohne Optgroups dann kann ich filtern (bzw. stehen die Filtermöglichkeiten oben in der Filterselectbox) und wenn ich auf "Optgroup-Array" (group=>(key=>value)) umstelle wird nur der Feldname und "---" in der Filterbox angezeigt.
```php
'season'	=> array
		(
			'label'	=> &$GLOBALS['TL_LANG']['tl_competitions']['season'],
			'inputType'	=> 'select',
			'filter'	=> true,
			'eval'	=> array
			(
				'chosen'	=> true,
				'mandatoty'	=> true,
				'submitOnChange'=>true,
				'tl_class'	=> 'w50',
			),
			'sql'	=> "int(10) unsigned NOT NULL default '0'",
			'options_callback'	=> array("SeasonModel","getAllForSelectBox")
		),
```
Die Callback funktion gibt eigentlich schon alles an Informationen zurück die ich brauch...
Aber es klappt (einzelview mit optgruppen & filter) erst wenn ich:
```php
            'foreignKey'	=>	"tl_seasons.name",
            'reference'  => &$GLOBALS['TL_LANG']['CTE'],
```
einfüge.
Wobei der foreignKey logisch ist, aber die Referenz kann irgendwas sein.

**Comment by leofeyer** [comment]
Am besten stellst Du diese Frage im [Forum](https://community.contao.org/de/).
