### ISSUE TITLE
<fieldset> and <legend> instead of <label> in Template nl_default

### ISSUE THREAD

**Issue by Skipman** [contao/core#7673]
If you have more than 1 Newsletter Channel, youre able to give the choise in users hands. That`s fine! But to meet [WCAG v2 Rules 1.3.1/3.3.2] (http://www.w3.org/TR/WCAG20-TECHS/H71.html) (Level A)  it is nessesary to put (more than one) checkbox or radio-button fields into a fieldset.

Therefore please use:
`<?php if ($this->showChannels): ?>` 
`<div id="ctrl_channels_<?php echo $this->id; ?>" class="checkbox_container">`
`<fieldset>`
`<legend><?php echo $this->id; ?>" class="invisible"><?php echo $this->channelsLabel; ?></legend>`
.... some code
`</fieldset>`
instead of the actual solution.
Thank You!

**Comment by leofeyer** [comment]
Siehe #6876.
