### ISSUE TITLE
Inserttag for files (by uuid)

### ISSUE THREAD

**Issue by christianromeni** [contao/core#7674]
I have been looking for a way to hardcode a file into a template by using its uuid.
I would like to use an inserttag for that, since there is nothing else possible there.
Is there a way to create something like

{{pathFile::44ae856c-b927-11e4-968e-sf40f2ecab1f}}

**Comment by Toflar** [comment]
Questions should be asked in the community forum. We track issues here :)
Use `{{file::44ae856c-b927-11e4-968e-sf40f2ecab1f}}`.

**Comment by christianromeni** [comment]
Oops... can be closed.. Sorry
