### ISSUE TITLE
{{insert_module::ID}} is not rendered correctly in newsletter

### ISSUE THREAD

**Issue by seaneble** [contao/core#7676]
Using the inserttag insert_module to include a news list module within a newsletter leads to unexpected results:

    ### NACHRICHTENLISTE ### 
    Newsletter :: Beitrag 1 (ID: 13)

It seems as though the newsletter module assumes a backend context and renders the placeholder text instead of the module. In my eyes, this is not correct and should be fixed (v.3.3.4).

**Comment by seaneble** [comment]
I started to look at the source code and discovered that every module is responsible for this switching between different outputs itself. Rather than to change each module, it might be required to simulate the context for the frontend while rendering the newsletter. But I don't have a quick pull request, as intended.

**Comment by fritzmg** [comment]
Ticket already exists: #7587

**Comment by seaneble** [comment]
Sorry, I did not find this via the search. Thanks for pointing it out.
