### ISSUE TITLE
[3.4.4] Layout webfonts input field: pipe is coverted to %7C in source

### ISSUE THREAD

**Issue by Tastaturberuf** [contao/core#7677]
In backend: ```Open+Sans|Open+Sans+Condensed```
In source: ```Open+Sans%7COpen+Sans+Condensed```

The request drop ```Error (400): Missing font family```

**Comment by BugBuster1701** [comment]
Das muss was anderes sein, bei mir steht im Quelltext: ```family=Ubuntu%7CLobster```
und es werden beide Fonts geladen. (Firefox)
Welcher Browser bei dir?

**Comment by Tastaturberuf** [comment]
Tritt jetzt nicht mehr auf.
