### ISSUE TITLE
filepicker links not synchronized with DBAFS

### ISSUE THREAD

**Issue by Aybee** [contao/core#7678]
In einer Demo (nicht auf demo.contao.org) so nachzustellen.

- CE Typ Text anlegen. 
- Ein Wort im RTE verlinken.
- Als Linkziel mit dem Filepicker (Dateiwähler) ein Bild auswählen. foo.jpg
- In der Dateiverwaltung das Bild umbenennen. files/foo.jpg => files/bar.jpg
- Im Frontend zeigt der Link jetzt noch auf das Bild vor der Umbenennen. <a href="files/foo.jpg...

**Comment by fritzmg** [comment]
Das ist normal (in egal welcher Contao Version) und passiert auch so in der Online Demo.

**Comment by Aybee** [comment]
Da Contao dieses DBAFS hat und ich deshalb davon ausgehen darf, dass mit Contao gesetzte Links auf Dateien ihr Ziel behalten, sehe ich es als Bug oder zumindestens als missing Feature.

**Comment by Toflar** [comment]
Irgendwo gibt's schon ein Ticket dazu, aber ich kann's nicht finden...

**Comment by fritzmg** [comment]
Hier gibt es zB eins: #7581
