### ISSUE TITLE
Proxy Unterstützung für Automator checkForUpdates() 

### ISSUE THREAD

**Issue by BugBuster1701** [contao/core#7681]
Ebenso wie die Repository Klassen wäre es wünschenswert wenn auch bei Automator checkForUpdates() der Hook genutzt werden würde.
Ich habe lange gesucht warum bei mir nie ein Update Hinweis kam. (Firmen Zwangsproxy)
Die Zeile 41 https://github.com/contao/core/blob/master/system/modules/core/library/Contao/Automator.php#L41
```
		    $objRequest = new \Request();
```
ersetzen durch
```
		// HOOK: proxy module
		if (Config::get('useProxy')) {
		    $objRequest = new \ProxyRequest();
		} else {
		    $objRequest = new \Request();
		}
```
(entnommen aus der RepositoryManager Klasse)

**Comment by ciaobello** [comment]
+1

**Comment by leofeyer** [comment]
Geändert in 94dd80fbc57f6c307e159ea17492ff594cebb11e.

**Comment by Toflar** [comment]
Can somebody explain me where the class `ProxyRequest` comes from? I've never heard from it and I can't find the class at all?!?!

**Comment by leofeyer** [comment]
https://contao.org/de/extension-list/fileview/proxy.de.html

**Comment by Toflar** [comment]
kk

**Comment by aschempp** [comment]
Should we add a `in_array('proxy', \ModuleLoader::getActiveModules())` too?

**Comment by leofeyer** [comment]
Yes, maybe. I have also thought about adding the class to the core. Maybe @BugBuster1701 can prepare a pull request?
