### ISSUE TITLE
[3.2.16] generate a dynamic link with recursive insert tags on frontpage not working

### ISSUE THREAD

**Issue by bezin** [contao/core#7682]
Hei there, 

I found unexpected behaviour while using the following recursive insert tag {{link_url::{{page::id}}}} and would like to discuss it. I expect it to return the url of the current page, so that I can use it within an anchor element href attribute. It works like a charme on every subpage in my local installation, but not on the frontpage (alias=index). 

[In cause you are wondering why I need a link to the current page: I have a page where I use the History-API to browse within a div, that slides in from aside. I need the url of the actual page the user is on, to trigger closing the div again, when the user uses the back and forward buttons of the browser.] 

You can't really reproduce the issue on the demo page, because it adds the language to the url and that behaviour can't be turned off. But do the following:

1. Create a custom html element on any article on the demo frontpage
2. Insert {{link_url::{{page::id}}}}
3. Go to frontend: you'll see the output 'en/'

This is fine so far. But if you have a mono-lingual page like I have in my local installation, this insert tag returns ''. Shouldn't it return '/' instead? The way it is it can't be used for its intended purpose.

Looking forward to your opinions. 

Cheers

**Comment by bezin** [comment]
Maybe a more generalized statement:
When I use {{link_url::2}} to generate a link to my index page (id 2, alias 'index'), it returns no href. 
It looks like it is no issue with the recursive insert tags, but a bug with the link_url insert tag in general.

**Comment by Aybee** [comment]
> Shouldn't it return '/' instead?

No, as there is the BASE tag `<base href="http://demo.contao.org/">` which already has a trailing slash.

I think you have to do it manualy in your templates or with JS.

**Comment by bezin** [comment]
Well, yes, you are right, that is the explanation for that behaviour. But I am wondering, if this is the desired behaviour, since it means, you can't generate a link to the frontpage with this insert tag. 

I solved my specific issues javascript-wise.

**Comment by Aybee** [comment]
> ...you can't generate a link to the frontpage with this insert tag. 

I think this is not right. You can create URLs to the actual page with
`{{env::request}}` or
`{{link_url::{{page::id}}}}` (should be the same)
and to the homepage with
`{{env::url}}`
on multilingual and monolingual pages.
