### ISSUE TITLE
Eigener Layoutbereich "start" entfernt andere Layoutbereiche

### ISSUE THREAD

**Issue by poldixd** [contao/core#7683]
Hallo,

ich habe ein Layoutbereich "start" angelegt und diesem Layoutbereich unter Frontend-Module Artikel zugewiesen.

Wenn ich jetzt das Layout einer Seite zuweise, kann ich keine Artikel mehr in den Layoutbereich packen, da unter "Artikel bearbeiten > Layoutbereich und Suchbegriffe > Anzeigen in"  nur noch _Hauptspalte_ und _Anzeigen ab_ steht:

![contao](https://cloud.githubusercontent.com/assets/695449/6617159/10891564-c8b6-11e4-80cc-efd234b1e767.jpg)

Verwendet man einen anderen Namen, dann geht es. 

Der Bug ist auch reproduzierbar in der Contao Demo (CMS 3.4.4)!

viele Grüße

**Comment by leofeyer** [comment]
Ich würde das mal als "known limitation" bezeichnen. Wenn Du Deinen eigenen Layoutbereich so nennst wie ein vorhandenes Tabellenfeld, übersetzt Contao das in bester Absicht für Dich. Die Lösung hast Du ja selbst schon genannt: einfach einen anderen Namen wählen.

**Comment by fritzmg** [comment]
Naja, man könnte es ja trotzdem beheben, indem man die Übersetzungen einfach in ein eigenes Array verpackt, statt direkt in `tl_article`. Also sodass im DCA dann 
```php
'inColumn' => array
(
	...
	'reference'               => &$GLOBALS['TL_LANG']['tl_article']['inColumn'],
	...
)
```
oder ähnliches steht.

**Comment by leofeyer** [comment]
Geändert in 2c0aad18053ec33e25fcdc2cc1dd31dfc65ed6e2.

**Comment by aschempp** [comment]
Damit gehen halt auch alle vorhandenen Übersetzungen verloren, und alle welche die bisher benutzt haben gehen auch nicht mehr. Wäre es nicht einfacher die bekannten Übersetzungen explizit zuzuweisen?

```php
'reference' => array(
    'header' => &$GLOBALS['TL_LANG']['tl_article']['header'],
    'left' => &$GLOBALS['TL_LANG']['tl_article']['left'],
    'right' => &$GLOBALS['TL_LANG']['tl_article']['right'],
    'main' => &$GLOBALS['TL_LANG']['tl_article']['main'],
    'footer' => &$GLOBALS['TL_LANG']['tl_article']['footer'],
);
```

**Comment by leofeyer** [comment]
Könnte man, aber ich habe bei der Gelegenheit auch gleich die Redundanz entfernt; die Spaltennamen waren sowohl in `tl_article` als auch in `tl_module` hinterlegt.
