### ISSUE TITLE
The ce_hyperlink_image model is not taken into account when renamed

### ISSUE THREAD

**Issue by luger95** [contao/core#7685]
Hello,

I have to note that the model surchargant "ce_hyperlink_image" and renaming it to "ce_hyperlink_image_produit" it is no longer used by contao in front.

Contao v 3.4.4

THX

**Comment by fritzmg** [comment]
Hm, can you be more specific? If you create your own ce_hyperlink_image_template, you need to select that in your content element under _Template settings_.

**Comment by luger95** [comment]
Yes I selected my template, but it does not override the default

**Comment by Aybee** [comment]
Das liegt evtl. an dieser Zeile
https://github.com/contao/core/blob/master/system/modules/core/elements/ContentHyperlink.php#L66
Sobald du im Element Hyperlink einen Bildlink erstellst wird das Template ce_hyperlink_image genommen.

**Comment by qzminski** [comment]
I have the same issue. The problem lies in this line:

https://github.com/contao/core/blob/master/system/modules/core/elements/ContentHyperlink.php#L68

**Comment by leofeyer** [comment]
There is no backwards compatible way to solve this problem in Contao 3, therefore it has been solved in Contao 4.
