### ISSUE TITLE
Possible bug in Automator

### ISSUE THREAD

**Issue by aschempp** [contao/core#7687]
While working on Contao 4 I stumbled upon the following:

https://github.com/contao/core/blob/master/system/modules/core/library/Contao/Automator.php#L652

The last if-condition checks if the same file has been included before and then skips it. However, 3 lines later the files array is filled without the file extension. So as far as I can see, the check never succeeds?

**Comment by discordier** [comment]
You are right on this one.
It doesn't check correctly which results in writing the same file twice.

**Comment by leofeyer** [comment]
Fixed in 086118f8a8d2c51fe6f43450e7e99d91de7cce77.

**Comment by aschempp** [comment]
There seems to be exactly the same bug when building the DCA cache?
https://github.com/contao/core/blob/master/system/modules/core/library/Contao/Automator.php#L573

**Comment by leofeyer** [comment]
Fixed in 19b1ed08352af1048c7605fba44b2498dd7820e0.
