### ISSUE TITLE
Contao/PageModel für fe_page

### ISSUE THREAD

**Issue by katgirl** [contao/core#7689]
Aktuell steht das Contao/LayoutModel in der fe_page zur Verfügung, jedoch nicht das Contao/PageModel. Es gibt Teile des PageModels, welche übergeben werden, jedoch lässt sich aktuell nur über Inserttags an die ID und dann selbsthinzugefügte Felder in der tl_page kommen. Schöner wäre man hätte gleich die ID oder den Alias um die SeitenInformationen sich in Template zu holen.

**Comment by aschempp** [comment]
$GLOBAL['objPage'] ist immer das PageModel

**Comment by discordier** [comment]
@aschempp es ist ein Hybrid. Es kommen noch Layout Infos dazu. Aber allgemein hast du recht, es ist da. :)

**Comment by katgirl** [comment]
Ja, klar aber über $this läst es sich nicht ansprechen direkt. Jedoch der Pagetitle von Page oder die Description.

**Comment by discordier** [comment]
Aber du kannst doch statt `$this` einfach `$GLOBALS['objPage']` nehmen?

**Comment by BugBuster1701** [comment]
Ab wann gibt es dieses $GLOBALS['objPage']?
