### ISSUE TITLE
TinyMCE 4.1.9 released

### ISSUE THREAD

**Issue by fritzmg** [contao/core#7690]
TinyMCE 4.1.9 was released a few days ago. It fixes a bug where `&nbsp;` are always inserted before or after a link (depending on the browser), when using the "Insert link" function.

See also:
http://www.tinymce.com/develop/bugtracker_view.php?id=7429
http://www.tinymce.com/develop/changelog/index.php?ctrl=version&act=view&pr_id=1&vr_id=879
https://community.contao.org/de/showthread.php?56025-TinyMCE-amp-nbsp-nach-vor-link

**Comment by leofeyer** [comment]
Updated in 8f5c9bd05e0d89ff640b7c37cd66624612f664ed.
