### ISSUE TITLE
Feature: fields - inputType: number

### ISSUE THREAD

**Issue by Aybee** [contao/core#7691]
Wenn ich im DCA ein Feld vom Typ **...['inputType'] = 'text'** deklariere und rgxp auf digit setze, dann habe ich im FE automatisch ein Feld type="number" anstatt "text". Müsste man das Feld im DCA nicht besser als "number" deklarieren. Oder eine Möglichkeit haben über ['eval']['type']='text' die Ausgabe als type="text" zu forcieren?

Ich bin gerade dabei ein Feld Type = text mit rgxp = digit als Type = text auszugeben, was mir so erstmal nicht so einfach gelingt.

**Comment by fiedsch** [comment]
Wenn Du mit rgxp = digit nur Ziffern erlaubst, wieso willst Du dann ein input type="text"? number passt doch genau zu digit.

**Comment by Aybee** [comment]
Mir ging es da erstmal um das optische Erscheinungsbild des Feldes im FF. Das sieht nicht schön aus und die Pfeile sind so klein.

**Comment by aschempp** [comment]
Das Styling des Feldes kannst du mit CSS beliebig anpassen und die Buttons auch entfernen, Google ist dein Freund ;-)
