### ISSUE TITLE
Fatal error: Allowed memory size of 262144 bytes

### ISSUE THREAD

**Issue by DVeris** [contao/core#7696]
Fatal error: Allowed memory size of 262144 bytes exhausted (tried to allocate 3072 bytes)

when synchronizing files (when follow the link "Synchronize" in File Manager)

memory_limit 512M

**Comment by aschempp** [comment]
What are you expecting us to do about that with such little information?

**Comment by DVeris** [comment]
maybe optimize "Synchronize" function?

when over 1000 pictures

**Comment by Toflar** [comment]
262144 bytes are about 0.25 megabytes...

**Comment by DVeris** [comment]
Yes, I know, but
I don't know what it is

**Comment by Toflar** [comment]
Well, you only have 0.25 megabytes of RAM available. That's what the error message says. Obviously that's way too little for Contao to run properly.

**Comment by DVeris** [comment]
memory_limit 512M
!!!

phpinfo shows it

**Comment by aschempp** [comment]
@DVeris according to the message your memory limit is 256KB and not 512M…

**Comment by DVeris** [comment]
https://github.com/contao/core/issues/7035

my hosting says
after commenting in /system/modules/core/library/Contao/Dbafs.php
lines 454-459 

```
		// Consider the suhosin.memory_limit (see #7035)
		if (extension_loaded('suhosin'))
		{
			if (($limit = ini_get('suhosin.memory_limit')) !== '0')
			{
				@ini_set('memory_limit', $limit);
			}
		}
		else
		{
			@ini_set('memory_limit', -1);
		}
```

**Comment by DVeris** [comment]
all works fine

**Comment by DVeris** [comment]
if (extension_loaded('suhosin')) - makes a bug

**Comment by DVeris** [comment]
litespeed server

**Comment by leofeyer** [comment]
What kind of bug?

**Comment by BugBuster1701** [comment]
what is the output of this:
<?php
echo ini_get('memory_limit') . "<br>";
echo ini_get('suhosin.memory_limit') . "<br>";
?>

**Comment by DVeris** [comment]
Leo,
Fatal error: Allowed memory size of 262144 bytes exhausted (tried to allocate 49152 bytes) in
```
		// Consider the suhosin.memory_limit (see #7035)
//		if (extension_loaded('suhosin'))
//		{
//			if (($limit = ini_get('suhosin.memory_limit')) !== '0')
//			{
//				@ini_set('memory_limit', $limit);
//			}
//		}
//		else
//		{
			@ini_set('memory_limit', -1);
//		}
```

BugBuster1701,
only one line:
1024M

**Comment by DVeris** [comment]
var_dump(ini_get('suhosin.memory_limit'));
display
bool(false)

**Comment by DVeris** [comment]
and after this:

```
		if (extension_loaded('suhosin'))
		{
		//	if (($limit = ini_get('suhosin.memory_limit')) !== '0')
		//	{
		//		@ini_set('memory_limit', $limit);
		//	}
		}
		else
		{
			@ini_set('memory_limit', -1);
		}
```

Synchronisation works fine

**Comment by DVeris** [comment]
var_dump(extension_loaded('suhosin'));
display
bool(true)

**Comment by DVeris** [comment]
$limit = false ??
@ini_set('memory_limit', false);

**Comment by leofeyer** [comment]
It seems that the `suhosin.memory_limit` setting is misconfigured on your server. According to the docs, the value should be an integer:

http://suhosin.org/stories/configuration.html#suhosin-memory-limit

**Comment by DVeris** [comment]
hosting says
we don't have this option (suhosin.memory_limit)
and they dont have value (false)

**Comment by DVeris** [comment]
hosting says
we don't have this option (suhosin.memory_limit)
and this dont have value

**Comment by leofeyer** [comment]
You wrote the following above:

```php
        if (extension_loaded('suhosin'))
        {
        //  if (($limit = ini_get('suhosin.memory_limit')) !== '0')
        //  {
        //      @ini_set('memory_limit', $limit);
        //  }
        }
        else
        {
            @ini_set('memory_limit', -1);
        }
```

Why do you think did it help to comment out these lines if the suhosin extension is not installed on your server? You should never get there without it.

**Comment by DVeris** [comment]
extension_loaded('suhosin') display true
suhosin extension is installed

but server dont have suhosin.memory_limit 

only this option

**Comment by leofeyer** [comment]
Can you please post a screenshot of your `phpinfo()` (everything related to Suhosin)?

**Comment by DVeris** [comment]
http://mycontao.ru/i.php

before add in your hosts
91.218.228.197 mycontao.ru

**Comment by BugBuster1701** [comment]
hmm no "suhosin.memory_limit". :-1: 
ini_get results "false", false !== 0, and memory_limit is set with "false", that's wrong.

**Comment by leofeyer** [comment]
I am well aware of what is wrong. I just wonder why Suhosin is installed and the option is missing.

**Comment by DVeris** [comment]
![image](https://cloud.githubusercontent.com/assets/1255917/6891733/5197a020-d6c6-11e4-8255-05fc5901e53c.png)

**Comment by no-one** [comment]
Maybe you should try the latest (stable) version? 0.9.37.1

**Comment by leofeyer** [comment]
Fixed in 799c6eab4d843c3e741d4ce92d8fa558b9d6dcc3.

**Comment by DVeris** [comment]
the problem remained

**Comment by DVeris** [comment]
if ($limit = false)
@ini_set('memory_limit', false);

**Comment by DVeris** [comment]
maybe?
```
$limit = ini_get('suhosin.memory_limit')
if ($limit)
{
@ini_set('memory_limit', $limit);
}
```

**Comment by DVeris** [comment]
WOW
WHY 3.5 ???
3.2

**Comment by DVeris** [comment]
Leo, please, do it for version 3.2

**Comment by leofeyer** [comment]
@DVeris You should make yourself familiar with our [release plan](https://contao.org/en/release-plan.html). Contao 3.2 has entered its transition phase, in which only security related issues will still be fixed.
