### ISSUE TITLE
mod_article.html5 won´t override default

### ISSUE THREAD

**Issue by memikeandi** [contao/core#7697]
When I create a new template for mod_article.html5 and change the code it won´t override the default template. I haven´t changed the name and it is in the correct theme-folder, I have also cleared the cache but nothing happens. 
Contao 3.4.4

**Comment by xchs** [comment]
I cannot reproduce this on my installation. Could you elaborate on that, please?

**Comment by do-while** [comment]
Do you use HTML5 or XHTML template in your page layout?
It must correspond to the extension of the template file.

**Comment by memikeandi** [comment]
@xchs Wierd :/ Well, I create a new mod_article.html5 and put it in the theme-folder, keep the name (off cause), change the code but nothing happens, contao still uses the default template. If I choose the template manually it works thought.
@do-while Yes, i use HTML in page layout and .html5 on my templates. I´m well aware of that :)

**Comment by memikeandi** [comment]
OMG, I´m so stupid I wanna bang my head against the wall right now... I´m using the tags_news extension but that also requiers the tags extension so the mod_article.html5 will be override by the mod_article_tags.html5. 

Thanks for your help and sorry I wasted your time!
