### ISSUE TITLE
sitemap um lastmod erweitern (feature)

### ISSUE THREAD

**Issue by fenepedia** [contao/core#7699]
Bei der Generierung der Sitemap soll das Attribut lastmod mit erzeugt werden.
Lt. Google werden damit neue Seiten schneller in den Index aufgenommen.

**Comment by xchs** [comment]
> Lt. Google werden damit neue Seiten schneller in den Index aufgenommen.

Könntest Du die Quelle bitte noch verlinken?

**Comment by fenepedia** [comment]
Leider schwierig..  Sitze gerade auf der SMX in München und das war ein Tipp von John Mueller (Google Switzerland) http://smxmuenchen.de/muenchen2015/programm-details/#p1503

**Comment by aschempp** [comment]
Solche Funktionen hat die Erweiterung googlesitemap (https://contao.org/de/extension-list/view/googlesitemap.10020039.en.html) mal geboten. Vielleicht gibt es einen Nachfolger davon oder jemand der die übernehmen würde.

**Comment by leofeyer** [comment]
Das Feature ist leider nicht rückwärtskompatibel, da die Methode `getSearchablePages()` aktuell nur eine URL und keinen Zeitstempel zurück liefert. Das müsste man erstmal so umbauen, dass ein Array beidem zurück kommt und dann wäre es ein BC-Break.

**Comment by fenepedia** [comment]
Danke für die Mühe. So wie ich das heute einschätze bringt das vmtl. nur was bei größeren Seiten einen Vorteil. Für kleine Seiten wird das wohl wenig bringen, da ist der Googlebot ja gleich fertig.
