### ISSUE TITLE
Fehlende Überprüfung im Login-Modul

### ISSUE THREAD

**Issue by Defcon0** [contao/core#7701]
Hallo,

in einer Kundendatenbank kommt der Fall vor, dass es mehrere Accounts des gleichen Benutzernamens gab (zustande gekommen durch die Erweiterung mailusername). Das login-Flag war jedoch nur bei einem Member gesetzt. Leider kam das Login-Modul trotzdem durcheinander, weil es nur auf username checkt und gar nicht prüft, ob login gesetzt ist. Die Zeile

$objMember = \MemberModel::findByUsername(\Input::post('username'));

müsste IMO also korrekt lauten

$objMember = \MemberModel::findBy(array('username', 'login'), array(\Input::post('username'), '1'));

Oder liege ich falsch?

Ciao Defcon0

**Comment by aschempp** [comment]
Grundsätzlich :+1: 
Vielleicht sollte der Username auch einen Unique-Index bekommen? Dann könnte das nicht mehr passieren.

**Comment by Tastaturberuf** [comment]
Der Username sollte im jedem Fall unique sein. Das Problem ist aber im Moment das Contao schon einen leeren Datensatz bei der Erstellung erzeugt und die Datenbank dann meckert.

**Comment by leofeyer** [comment]
Im Backend hatten wir eh schon einen Unique-Index, im Frontend wurde der wohl vergessen. Hab ich jetzt in 4e647267d32e6f3ae8e7d2019e559c956933d744 nachgerüstet.

**Comment by aschempp** [comment]
Bei einem Update könnte der Index aber nicht hinzugefügt werden, weil alle leeren Spalten noch nicht NULL sind oder?

**Comment by leofeyer** [comment]
Korrekt. Ich habe hierzu noch ein `FIXME` im Installtool.

**Comment by aschempp** [comment]
:+1:
