### ISSUE TITLE
[feature] BE_USER_LOGGED_IN on frontend (FE)

### ISSUE THREAD

**Issue by DVeris** [contao/core#7703]
i think it would be great

for example (news_full)

```
<?php if (BE_USER_LOGGED_IN): ?>
<a href="contao/main.php?do=news&amp;table=tl_content&amp;id=<?php echo $this->id; ?>&amp;rt={{request_token}}" title="Edit" class="editheader" target="_blank"><img src="system/themes/default/images/edit.gif" alt="" height="16" width="12" /></a>
<?php endif; ?>
```

**Comment by Toflar** [comment]
You can do that already?

**Comment by Zeromax** [comment]
I think the check should be explicit: `if (true === BE_USER_LOGGED_IN)`

**Comment by DVeris** [comment]
now it works when
Front end preview -> Unpublished elements: show

**Comment by DVeris** [comment]
why closed?

**Comment by leofeyer** [comment]
Because you wrote *now it works*?

**Comment by DVeris** [comment]
but only when
Front end preview -> Unpublished elements: show

without Front end preview -> Unpublished elements: show = not works

**Comment by DVeris** [comment]
for example
when Front end preview -> Unpublished elements: **hide**  - not works

when without Front end preview function - not works

**Comment by aschempp** [comment]
Its supposed to be like that!

**Comment by Zeromax** [comment]
@aschempp it does not.
read the code ;) https://github.com/contao/core/blob/5d878de67eb218d5eb7ba967dbc669859b8489ec/system/modules/core/classes/Frontend.php#L503
it Returns false.

I tracked it down with xDebug to be sure.
But I remember somer other discussions about that... I think this was in the community forum

**Comment by Zeromax** [comment]
@DVeris you can use this snippet: ` sha1(session_id() . (!Config::get('disableIpCheck') ? Environment::get('ip') : '') . 'BE_USER_AUTH') != Input::cookie('BE_USER_AUTH')`
It is from the analytics template. This works.

see as reference: https://github.com/contao/core/blob/master/system/modules/core/templates/analytics/analytics_piwik.html5#L13

**Comment by Aybee** [comment]
I also often wished their is a constant that works like DVeris supposed BE_USER_LOGGED_IN will work. As it is a bit unlogical, that BE_USER_LOGGED_IN is false even if a BE user is logged in. Maybe BE_USER_LOGGED_IN_STRICT opr something.

**Comment by DVeris** [comment]
https://community.contao.org/en/showthread.php?19154-BE_USER_LOGGED_IN-where-can-i-get-this-true

**Comment by marebe1602** [comment]
+1 for Aybee
it's really unlogical. For compatibility reasons, the suggested BE_USER_LOGGED_IN_STRICT would be a good compromise

**Comment by leofeyer** [comment]
In Contao 4 you can do `$this->hasAuthenticatedBackendUser()` in your templates (see https://github.com/contao/core-bundle/blob/develop/src/Resources/contao/templates/analytics/analytics_piwik.html5#L13).

**Comment by Aybee** [comment]
But LTS 3.5 runs till June 2017

**Comment by leofeyer** [comment]
Just use the code we are currently using in Contao 3:

https://github.com/contao/core/blob/develop/system/modules/core/templates/analytics/analytics_piwik.html5#L13
