### ISSUE TITLE
The polyfill an unused unit

### ISSUE THREAD

**Issue by luger95** [contao/core#7704]
Hello,

When I create an event with an image, without defining configuration polyfill and I create an event list module and I define a polyfill, it is not taken into account by the front display.

Thank you.

**Comment by leofeyer** [comment]
?

**Comment by luger95** [comment]
After several test, I feel that the images, caching, events are not generated.

**Comment by xchs** [comment]
> without defining configuration polyfill

What do you mean by "polyfill"? In web development, a polyfill is something that implements technology that a developer expects the browser to provide natively.

Are you talking about the image settings?

**Comment by xchs** [comment]
Okay, I guess I got it.

@luger95 most likely refers to the "Event list" front end module and the image settings not being considered by the partial template.

Probably a duplicate of #4918.

**Comment by luger95** [comment]
Yes that's right

**Comment by leofeyer** [comment]
Does this issue still occur in Contao 3.5.5?

**Comment by xchs** [comment]
Yes. However, I suppose it is related to #4918 which is actually tagged as feature request.

**Comment by leofeyer** [comment]
See #4918 then.
