### ISSUE TITLE
Modul Auflistung Ergebnismeldung

### ISSUE THREAD

**Issue by peter67** [contao/core#7705]
Wenn bei der Abfrage einer Tabellenspalte mit dem Modul Auflistung kein entsprechender Eintrag gefunden wird, wird leider keine Ergebnismeldung ausgegeben. Es werden lediglich die definierten Spaltenüberschriften der Ergebnistabelle angezeigt.
Mein Vorschlag: Darstellung einer Meldung wie im Suchmodul. Beispiel: "Keine Ergebnisse für xyz (0.0327 Sekunden)".

**Comment by rike01** [comment]
Gibt es zu diesem Thema schon eine Lösung? Ich bräuchte dringend die Ausgabe einer Meldung, insofern bei dem Modul Auflistung kein Ergebnis gefunden wird..

**Comment by Aybee** [comment]
Die Variable `$this->total` ist bereits vorhanden. Es müssen noch Sprachvariablen angeleget werden und das Template leicht angepasst werden. Wenn man die Sprachvariable nicht direkt im Template wünscht, muss die Variable `$this->message` noch ins Template gebracht werden.
https://github.com/contao/core/blob/master/system/modules/listing/modules/ModuleListing.php#L333

**Comment by leofeyer** [comment]
Implementiert in 21cd488672be13f4184435824fc6cb3ef9db178a.
