### ISSUE TITLE
Email - Bild aus erster Mail rutscht unerwartet in zweite Mail

### ISSUE THREAD

**Issue by Aybee** [contao/core#7706]
Ich weiß nicht genau, ob das ein Contao-Bug ist.
https://github.com/felixpfeiffer/contao-simple-event-registration/issues/11#issuecomment-85035922
Ich bin davon ausgegangen, dass wenn man `$objEmail->html` verändert  nachdem man die Mail mit sendTo() verschickt hat und dann mit `$objEmail->sendTo()` das Mail-Objekt noch einmal versendet, dass dann nichts von dem vorherigen  `$objEmail->html` mit übernommen wird.

**Comment by fritzmg** [comment]
Ist imho kein Bug, da du ja kein neues `Email` Objekt erzeugst und nur die Variable `html` neu setzt. Bei `sendTo()` werden ja Bilder automatisch eingebettet, so fern `$blnEmbedImages` auf `true` steht (was es by default ja ist). Diese Daten werden im `Email` Objekt innerhalb des `$objMessage` Objektes gespeichert. Und dieses Objekt wird wiederum nur dann neu erzeugt, wenn du auch ein neues `Email` Objekt erzeugst.
