### ISSUE TITLE
[bug] rss feeds 3

### ISSUE THREAD

**Issue by DVeris** [contao/core#7707]
https://github.com/contao/core/issues/7679

another problem:

i have two rss

rss1:

car (selected)
food (selected)
house (selected)

rss2:

car (selected)
food (!!!not selected!!!)
house (selected)

when add news in news archive "food" - RSS FEED ISN'T UPDATED (rss1)

**Comment by leofeyer** [comment]
See #7679.

**Comment by DVeris** [comment]
Leo!!!!
it is 3rd problem

please carefully read

**Comment by leofeyer** [comment]
I have read it carefully and it is exactly the same comment as you wrote here: https://github.com/contao/core/issues/7679#issuecomment-84927401

**Comment by DVeris** [comment]
you fixed only
### Fixed
+Update news and calendar feeds from the content view (see #7679).

and all

**Comment by leofeyer** [comment]
Yes, of course, you have only added your comment **after** I had fixed the first issue.

**Comment by DVeris** [comment]
2 rss
one news archive "Food"

in rss1 Food selected
in rss2 Food not selected

when add news in news archive "Food" - xml file rss1 not updated

**Comment by DVeris** [comment]
it is not duplicate
it is 3rd problem with rss

**Comment by DVeris** [comment]
my fault wrote in fixed issue
created another issue for another problem
