### ISSUE TITLE
Alias "index" is not being redirected to the root page if called directly

### ISSUE THREAD

**Issue by Toflar** [contao/core#7711]
Open http://demo.contao.org/en/index.html, the page will be shown instead of redirecting to http://demo.contao.org/en/.

**Comment by leofeyer** [comment]
If you had a real `index.html` file, the server would behave exactly the same. Google knows this :)

**Comment by Toflar** [comment]
Yeah, I don't care about Google actually but my customer that can access the same site with the same URL. I guess it should still not work :) I'm pretty sure if I removed the `.html` extension in the settings and called  `http://demo.contao.org/en/index` it would work as well? Would Google know that? :)

**Comment by leofeyer** [comment]
But we cannot generally redirect. If there e.g. is a news archive, the URL would be `index/james-wilson.html`. We could only redirect `index.html`.

**Comment by Toflar** [comment]
Shouldn't the correct redirect then be `/james-wilson.html`? :)

**Comment by aschempp** [comment]
> Shouldn't the correct redirect then be /james-wilson.html? :)

No, that would be a page alias.

**Comment by Toflar** [comment]
I see.

**Comment by leofeyer** [comment]
We still could redirect `index.html` to the empty domain?

**Comment by Toflar** [comment]
I don't mind, either way is fine for me :) I did not think about the regular `index.html` directory index so I can easily explain it to my customer :)
