### ISSUE TITLE
[3.4.4] Backend-Benutzer kann über Versionswiederherstellung Rechte zurückerlangen

### ISSUE THREAD

**Issue by Mynyx** [contao/core#7713]
Ein Backend-Benutzer kann unter /contao/main.php?do=login frühere Versionen seines Benutzers wiederherstellen.
Hierdurch ist es möglich entzogene Rechte wie z. B. den Administratur-Status zurückzuerlangen, indem der Benutzer eine frühere Version, in der dieses Recht bestand, wiederherstellt.

**Comment by leofeyer** [comment]
Behoben in 83843f0ecb50c6d3b668859107b3416ed19dd0af.
