### ISSUE TITLE
Upload singleSRC -> uuid

### ISSUE THREAD

**Issue by markknochen1** [contao/core#7716]
Ich frage das mal hier, weil ich an der Stelle wirkich ein Verständnis-Problem habe.
Mit einem Formular lade ich ein Bild hoch (Formular per efg in eine Tabelle gespeichert), welches von Contao verarbeitet wird und daraufhin auch in der tl_files landet.

per Hook prepareFormData komme ich auch an die uuid ... als String .. und könnte diese dann auch per String::uuidToBin binär erhalten.

Aber wie kann ich diesen Hook verwenden, um z.B. anhand der uuid auch in ContentElementen das Feld singleSRC mit diesem File zu verbinden?

Danke schonmal 

mark

**Comment by leofeyer** [comment]
Auf GitHub kannst Du Fehler melden. Fragen dieser Art sind im [Forum](https://community.contao.org/de/) besser aufgehoben.
