### ISSUE TITLE
(also href) Automatically convert file paths in TinyMCE into insert tags from #5965

### ISSUE THREAD

**Issue by joeherold** [contao/core#7717]
Ist derzeit nur auf das src Attribut beschränkt.
Könnte man das auch auf das href Attribut erweitern, falls ein link zb. zu einem PDF im TinyMCE erstellt wird? Leider machen das viele Kunden nach wie vor nicht mit dem Download-Element sondern schnöde im TinyMCE und verschieben nachher lustig die Ordner.

**Comment by leofeyer** [comment]
Siehe #7581.

**Comment by joeherold** [comment]
nice, danke
