### ISSUE TITLE
Modul Registrierung Meldung bei bereits vergebenem Benutzernamen/E-Mail-Adresse missverständlich

### ISSUE THREAD

**Issue by Mynyx** [contao/core#7719]
Wenn im Modul Registrierung im Frontend ein bereits vergebener Benutzername/E-Mail-Adresse eingegeben wird, erscheint folgender Fehlermeldung:
> Doppelter Eintrag im Feld "Benutzername"!

Dies ist insbesondere für unerfahrene Benutzer nicht verständlich, viele geben an diesem Punkt sogar auf. Die Meldung bezieht sich offenbar auch die entsprechende Datenbanktabelle, der Benutzer hat aber nur sein Formular vor Augen, wo er nichts doppelt eingegeben hat...
Eine Meldung wie z. B. Benutzername bereits vergeben / E-Mail-Adresse wird bereits verwendet wäre erheblich versändlicher und würde die Benutzerfreundlichkeit stark verbessern.

**Comment by Aybee** [comment]
:+1:

**Comment by greq7** [comment]
:+1:

**Comment by leofeyer** [comment]
Es handelt sich hierbei um die generische Fehlermeldung `ERR.unique`. Wir können also höchsten diese Meldung anpassen, so dass sie nach wie vor allgemein verwendet werden kann. Ideen?

**Comment by aschempp** [comment]
Ich fände es auch super wenn wir die Meldung verbessern können. ggf. müssten wir die User-Tabelle halt selber prüfen?

**Comment by leofeyer** [comment]
Wie am 16. Juli auf Mumble besprochen, sollte es möglich sein, für jedes Feld und jede Prüfung eine eigene Fehlermeldung zu hinterlegen. Die Umsetzung ist jedoch noch fraglich.

**Comment by leofeyer** [comment]
@Mynyx Würde eine Änderung der Formulierung vielleicht schon helfen?

> Dieser Eintrag im Feld "Benutzername" ist bereits vorhanden!

**Comment by Aybee** [comment]
:+1: für andere Formulierung

Besser fände ich noch **vergeben** anstatt **vorhanden**.
> Dieser Eintrag im Feld "Benutzername" ist bereits vergeben!

**Comment by aschempp** [comment]
Tja, und hier zeigt sich die Unmöglichkeit des Vorhabens. Ein Benutzername ist **vergeben**, aber eine Email eben **vorhanden**.

**Comment by Aybee** [comment]
> Dieser Eintrag im Feld "E-Mail-Adresse" ist bereits vergeben!
Dieser Eintrag im Feld "Benutzername" ist bereits vergeben!

Ok, sieht wirklich nicht so gut aus wie bei Benutzername. Dann wäre **vorhanden** wohl das, was auf alle Felder erstmal besser passt.

**Comment by discordier** [comment]
... bereits registriert?

**Comment by leofeyer** [comment]
Ich habe die Fehlermeldung in 70fc4634bfa1a09dd617f599f24f440de0edae52 angepasst.

> Wie am 16. Juli auf Mumble besprochen, sollte es möglich sein, für jedes Feld und jede Prüfung eine eigene Fehlermeldung zu hinterlegen. Die Umsetzung ist jedoch noch fraglich.

Sollen wir diesbezüglich ein separates Ticket aufmachen und noch versuchen, eine Lösung zu finden?

**Comment by aschempp** [comment]
+1 für ein Ticket, ich versteh aber nicht was noch zu klären ist ;-)

**Comment by leofeyer** [comment]
> Wie am 16. Juli auf Mumble besprochen, sollte es möglich sein, für jedes Feld und jede Prüfung eine eigene Fehlermeldung zu hinterlegen. **Die Umsetzung ist jedoch noch fraglich.**
