### ISSUE TITLE
Aditional Language Changer for BE User

### ISSUE THREAD

**Issue by ciaobello** [contao/core#7720]
Proposal:
User k.jones | Türkçe > Turkish

Making it possible to change the BE users language settings beside the user name in the BE (top right, beside front-end preview) with a language hint in English.

Background:
A question came up in the Forum and i did send the Person to [Github] (https://github.com/contao/official-demo/issues/54#issuecomment-85998307) to ask by the contao_official_demo

A other argument would be for the internationalization of contao. When i do have clients where i send to the demo.contao.org to see the the marvelous CMS Contao, they might get a wrong idea of the Product when there is just English as Backed Language. People with open mind and eyes will see the possibility of changing the language without to know that this change can be just made in the User Profile.

**Comment by Aybee** [comment]
:-1: 
This only would make sense in the demo if at all.

**Comment by aschempp** [comment]
> People with open mind and eyes will see the possibility of changing the language without to know that this change can be just made in the User Profile.

They should also see the language options when they log in? And the dropdown should already be assigned to their browser language?

**Comment by Samuelll** [comment]
:-1: 
Macht nur auf der Demoseite (demo.contao.org) selbst Sinn.
In Contao generell hat diese Funktion aber nichts zu suchen, da man die Sprache für Gewöhnlich einmal ändert und der Button damit viel zu prominent wäre!

**Comment by Sascha07** [comment]
Denke auch es macht nur auf demo.contao.org selbt Sinn (da aber ruhig prominenter platziert). Wäre sicher hilfreich für Einige die Contao zum ersten Mal austesten wollen, aber dem Englischen nicht so mächtig sind.

**Comment by ciaobello** [comment]
@aschemp, yes this would already a help. I just find because of confusion with foreign languages to switch off the languages in the demo is not a solution. The demo should be also international. If I already invest time to translate Contao to a foreign language, i would expect to be able to present new clients the Demo in their language.

**Comment by ciaobello** [comment]
[My opinion in the German forum, as an international user of Contao] (https://community.contao.org/de/showthread.php?56348-Contao-Demo-auf-Deutsch&p=364014&viewfull=1#post364014)
