### ISSUE TITLE
tiny_templates - Berücksichtigung von Templates in Unterverzeichnissen

### ISSUE THREAD

**Issue by greq7** [contao/core#7722]
Hallo zusammen, 

aktuell wird das Verzeichnis "files/tiny_templates" nach Dateien bzw. Templates durchsucht und
anschließend im TinyMCE-Editor unter dem Punkt "Einfügen=>Vorlage einfügen" zur Auswahl 
angezeigt.
Unterverzeichnisse wie bspw.: 
"files/tiny_templates/thema_a" 
oder 
"files/tiny_templates/thema_b" 
werden nicht berücksichtigt, da sie sich eine Hierarchiestufe unter dem "tiny_templates"-Verzeichnis befinden. 

In Contao 3.4.4 betreffende Datei: /contao-3.4.4/system/modules/core/classes/Backend.php (Zeile 195)
=> function getTinyTemplates() 

Ggf. könnte man Unterverzeichnisse in den nächsten Releases von Contao berücksichtigen.

Gruß,
Gregor

**Comment by leofeyer** [comment]
Since the support for `files/tiny_templates` has been dropped meanwhile, I am closing this issue.
