### ISSUE TITLE
content element downloads unresponsive when there are consecutive spaces in filename

### ISSUE THREAD

**Issue by ivl1705** [contao/core#7723]
if the filename contains consecutive spaces, and the file is selected in a download element, you'll receive a spinning wheel.

if you look into your serverlogs, you'll find a line like this:

    PHP Fatal error: Uncaught exception 'InvalidArgumentException' with message 'Invalid resource $filename_with_multiple_spaces' thrown in /$path_to_contao/system/modules/core/library/Contao/Dbafs.php

liennumber depends on your version of contao.

obvious reason: in the backend template filenames will be trimmed from multiple spaces. The resulting 'false' filename will cause the error.

remedy: check for multiple spaces in file upload

**Comment by leofeyer** [comment]
How do I reproduce this?

**Comment by ivl1705** [comment]
the behaviour can be limited to pdf-files. 
image files (tested with *.png) seem to work properly.

**Comment by leofeyer** [comment]
How do I reproduce this?
