### ISSUE TITLE
Maxlength wird nicht serverseitig validiert

### ISSUE THREAD

**Issue by Defcon0** [contao/core#7726]
Sollte das nicht der Fall sein?

**Comment by aschempp** [comment]
Das müsste auf denen Fall so sein. Hast du das mal in der Demo versucht? Frontend oder Backend?

**Comment by Defcon0** [comment]
Ich nutze die Widget-Klassen (also z.B. FormText) im Frontend (erzeugt durch eine unserer Erweiterungen mit dem Namen contao-formhybrid). In diesem Modul wird u.a. auch die validate-Methode jedes gerenderten Widgets aufgerufen. Und dort scheint keine Validierung dieser eval-Eigenschaft stattzufinden.

**Comment by leofeyer** [comment]
Die Validierung erfolgt auf jeden Fall serverseitig: https://github.com/contao/core/blob/master/system/modules/core/library/Contao/Widget.php#L897-L900
