### ISSUE TITLE
[3.3ff] FE-Modul Eventliste: CSS-Klasse odd/even fehlt bei 2. Item, wenn Datum gleich

### ISSUE THREAD

**Issue by xantippe** [contao/core#7727]
Beim Modul Eventliste wird die CSS-Klasse odd bzw. even dem Item nicht mitgegeben, wenn vorher ein Item mit gleichem Datum ausgegeben wird. Die Checkbox "mehrere tage zusammenfassen" hat keinen Einfluß

Workaround: "Zebra" per CSS-Pseudoattribute machen

Screenshot mit Contao 3.4.5
![zwischenablage02](https://cloud.githubusercontent.com/assets/1045318/6870054/c17fd7a6-d499-11e4-82e2-4ba22de134c5.jpg)

**Comment by leofeyer** [comment]
Wie muss ich die Events anlegen, um das zu reproduzieren?

**Comment by xantippe** [comment]
jeweils 
```
Startdatum*
29.03.2015
```
siehe Screenshot
![zwischenablage11](https://cloud.githubusercontent.com/assets/1045318/7958736/64952774-09f2-11e5-9900-2d5e2e29bfbe.jpg)

**Comment by xantippe** [comment]
sorry, ich war, wie ich gesehen habe, nicht ganz korrekt... es gibt einen Hook 
```
$GLOBALS['TL_HOOKS']['getAllEvents'][] = array('filterEvents', 'filterTopEvents');
```
der alle Events, die nicht den Fag "Top-Event" haben raus

```
...
			foreach ($arrEvents as $event=>$value){

				$key = $event;

				foreach ($value as $k=>$v){

					if(!$v[0]['swTopEvent']){
						unset($arrEvents[$key][$k]);
					}
				}
			}
			
			return $arrEvents;
...
```
aber auch nach dem Hook, sollte odd/even korrekt bzw. vollständig ausgeliefert werden...

**Comment by leofeyer** [comment]
Wenn es ohne den Hook klappt und mit dem Hook nicht, liegt der Fehler nicht im Contao-Core. Am besten wendest Du Dich an den Extension-Programmierer.
