### ISSUE TITLE
Deaktivierung Mitteilung über Kontosperrung

### ISSUE THREAD

**Issue by Mynyx** [contao/core#7728]
Bei einer Installation mit vielen "Mitgliedern" erhält man mehrmals täglich Mitteilungen per E-Mail, dass ein Contao-Konto aus Sicherheitsgründen gesperrt wurde.

Es wäre schön, wenn es eine Option zur Deaktivierung dieser Mitteilung geben würde.

**Comment by leofeyer** [comment]
Eventuell lässt sich das im [notification center](https://github.com/terminal42/contao-notification_center) konfigurieren?

**Comment by aschempp** [comment]
Lässt es sich nicht. Mit dem Notification Center lassen sich E-Mail Texte eingeben, nicht E-Mail Versand steuern. Ich könnte mir vorstellen dass wir dafür eine Bundle-Konfiguration einführen, das liesse sich im entsprechenden Security Listener leicht prüfen.

**Comment by leofeyer** [comment]
Über den Sinn der Mail lässt sich eh streiten. Vielleicht bräuchte man sie auch gar nicht?

**Comment by leofeyer** [comment]
Entfernt in contao/core-bundle@8e5e16687212a22a9bd32aaed8d99b87722f1793.
