### ISSUE TITLE
Pflichtfelder im Backend mit HTML5 required-Attribut auszeichnen

### ISSUE THREAD

**Issue by Mynyx** [contao/core#7729]
Im Backend sind Pflichtfelder noch nicht mit dem HTML5 required-Attribut ausgezeichnet

**Comment by leofeyer** [comment]
Was genau meinst Du?

**Comment by Mynyx** [comment]
Pflichtfelder wie beispielweise unter https://www.knowware.de/contao/main.php?do=login die Felder Name, E-Mail-Adresse, Passwort und Bestätigung analog zum Frontend mit dem required-Attribut zu kennzeichnen.

**Comment by Aybee** [comment]
Z.B. hier das Feld firstname http://demo.contao.org/contao/main.php?do=member&act=edit&id=1&rt=f31164a8fca4b4f7b55a9fb028ec72c3&ref=2579065b
```html
<input
  type="text"
  onfocus="Backend.getScrollOffset()"
  maxlength="255"
  value="John"
  class="tl_text"
  id="ctrl_firstname"
  name="firstname"
  required
>
```
Das **required** fehlt.

**Comment by leofeyer** [comment]
Das haben wir in Contao 4 bereits korrigiert.
