### ISSUE TITLE
Versionierung Anzeigen von Informationen über erste Version

### ISSUE THREAD

**Issue by Mynyx** [contao/core#7730]
Bei versionierbaren Elementen werden Informationen über die Versionen nur angezeigt, wenn mindestens zwei Versionen vorhanden sind, also eine Wiederherstellung möglich ist.

Es wäre nützlich, wenn auch in dem Fall, das nur eine Version vorhanden ist, die gleichen Informationen über diese an selbiger Stelle einfach als Text angezeigt werden würden, also Erstellungszeitpunkt und Autor.

**Comment by leofeyer** [comment]
Geändert in fe8fc9bdc26d2987c667573ba7a043abb56af1a4.

**Comment by Mynyx** [comment]
Es werden nun - unter der Überschrift "Zuletzt bearbeitet" - sämtliche initiale Versionen angezeigt, also auch Versionen die lediglich beim Aufruf von Elementen erstellt wurden, die bisher keine Version hatten.
Könnten diese Versionen bei der Erstellung nicht z. B. markiert werden, sodass hier dann nur Versionen angezeigt werden, die beim Neuanlegen eines Elementes erstellt wurden?

**Comment by leofeyer** [comment]
Was genau meinst Du?

**Comment by Mynyx** [comment]
Initiale Versionen können entstehen bei
a) Neuanlage eines Elementes, oder
b) Aufruf eines Elementes, zu dem noch keine initiale Version vorhanden ist.

Es werden nun auch initiale Versionen, die durch b) entstanden sind, angezeigt - die also gar nicht vom Benutzer bearbeitet wurden.
Mein Vorschlag wäre daher bei b) die Versionen zu kennzeichnen, sodass diese gefiltert werden können, oder nicht bereits beim Aufruf sondern erst bei Änderungen vor dem Speichern diese anzulegen.

**Comment by leofeyer** [comment]
Die einzige Änderung, die technisch machbar ist, wäre dass wir den Zeitstempel der Version nicht auf `time()` setzen sondern auf die Zeit, zu der ein Element erstellt wurde `->tstamp`. Auf diese Weise würden zwar weiterhin Einträge für neue Versionen angelegt, diese würden aber in der Versionsübersicht weiter unten angezeigt werden.

**Comment by leofeyer** [comment]
Geändert in d1f54561e2b781da93356be50ff63524c555a6a9.

**Comment by Mynyx** [comment]
Weiterhin wird nun unzutreffend der Name des Benutzers angezeigt, der das Element aufgerufen hat. Wäre es nicht möglich, bei Anlegen einer initialen Version durch Aufruf eines Elementes, zu dem noch keine initiale Version vorhanden ist, das Benutzerfeld frei zu lassen?
