### ISSUE TITLE
[3.4.5] Backend mandatory-Sternchen fehlt bei Checkbox

### ISSUE THREAD

**Issue by Mynyx** [contao/core#7731]
Im Backend wird bei Checkboxen kein mandatory-Sternchen angezeigt.

Beispiel Mitglieder -> Login erlauben, wenn 
> $GLOBALS['TL_DCA']['tl_member']['fields']['login']['eval']['mandatory'] = true;

**Comment by fiedsch** [comment]
Was soll denn mandatory bei einer Checkbox (ja/nein Frage) sein, wenn es nur "gecheckt" == ja gibt?

**Comment by Mynyx** [comment]
Die Funktionalität ist nunmal so möglich und wird auch Contao entsprechend geprüft, es fehlt nur das Sternchen.

**Comment by Aybee** [comment]
> Was soll denn mandatory bei einer Checkbox (ja/nein Frage) sein, wenn es nur "gecheckt" == ja gibt?

z.b. bei einem Feld "AGB gelesen". Wenn es mandatory ist, muss es angehakt werden, ist by default aber nicht angehakt.

Bei einer Checkbox "ich möchte  den Newsletter" wäre es z.B. nicht mandatory.

**Comment by leofeyer** [comment]
> Im Backend wird bei Checkboxen kein mandatory-Sternchen angezeigt.

Bei einer einzelnen Option ist das korrekt, weil immer nur ein komplettes Feld mandatory sein kann und nicht einzelne Optionen daraus.

```
<fieldset>
  <legend>Mandatory*</legend>
  <input type="checkbox" value="foo"> <label>Foo</label>
  <input type="checkbox" value="bar"> <label>Bar</label>
</fieldset>
```

Bei einer einzelnen Option entfällt jedoch das umschließende Fieldset:

```
<div>
  <input type="checkbox" value="foo"> <label>Foo</label>
</div>
```

**Comment by Aybee** [comment]
Ich weiß nicht, ob wir bei den Core-Feldern irgendwo eine mandatory checkbox mit nur einer Option haben, aber wenn man z.B. ein Feld für die Member hinzufügt. "AGB gelesen" welches man auf mandatory setzt, dann sollte eigentlich auch ein Sternchen dort sein.

```html
<div class="mandatory">
  <input type="checkbox" value="agb" required> <label>AGB</label>
</div>
```

**Comment by leofeyer** [comment]
Behoben in f181cdab2e15440e7b27956fd5ef7de28cea0a25.
