### ISSUE TITLE
ce_hyperlink and insert tags

### ISSUE THREAD

**Issue by Anke** [contao/core#7732]
I have a 3.4.4 installation trying to use ce_hyperlink for a back link. 

The description under the link field says you can enter insert tags, using {{link::back}} however end up like this in the FE:
~~~html
<div class="ce_hyperlink last block">  
    <a href="<a href="javascript:history.go(-1)" title="Go back">Go back</a>" class="hyperlink_txt" title="zurück" rel="">zurück</a>
</div>
~~~
If it's just the back-link-insert-tag that cannot be used here, wouldn't it be nice to have a back-link-CE?

**Comment by fritzmg** [comment]
There are a lot of insert tags that cannot be used there, i.e. any insert tag that produces HTML. Use {{env::referer}} instead for example.

**Comment by leofeyer** [comment]
Why don't you use `{{link_url::back}}`?

**Comment by Anke** [comment]
Thank you! Sorry ...

**Comment by Aybee** [comment]
> Why don't you use {{link_url::back}}?

Maybe as it's not mentioned in the manual https://contao.org/en/manual/3.4/managing-content.html#link-elements.
