### ISSUE TITLE
[3.4.5]  Hilfe bei CSS-Framework nicht aktuell

### ISSUE THREAD

**Issue by Mynyx** [contao/core#7733]
Themes -> Seitenlayout -> Bearbeiten -> CSS-Framerwork -> Hilfe-Assistent
>Layout-Builder 	Erstellt ein <b>responsives</b> CSS-Layout auf Basis der Seitenlayout-Einstellungen. Diese Komponente muss aktiv sein, damit der Seitengenerator korrekt arbeitet!

>Responsives Layout 	Fügt der Kopfzeile ein Viewport-Tag hinzu und skaliert das CSS-Layout basierend auf der Breite des Endgerätes.

Die Komponente "Layout-Builder" ist entgegen der Erklärung seitdem es die separate Komponente "Responsives Layout" gibt nicht mehr responsive.

**Comment by leofeyer** [comment]
Geändert in ac5f279f77b8edf8584725e3e416dbc80bca82d8. Muss aber noch zurück portiert werden.

**Comment by leofeyer** [comment]
Ist mittlerweile zurück portiert worden.
