### ISSUE TITLE
Inserttag für Theme-Ordner

### ISSUE THREAD

**Issue by denniserdmann** [contao/core#7735]
Moin!

ich vermisse aktuell einen Inserttag, um den Pfad bis in den Theme-Ordner erstellen zu lassen. 

Das wäre vor allen Dingen dann praktisch, wenn sich der Name des Theme-Ordners ändert. Für viele Kundenprojekte setze ich ein selbsterstelltes Basis-Theme auf, dessen Ordnername ich dann umbenenne. Dann muss ich allerdings durch mein Theme durchgucken und den Pfad von Hand anpassen. Ein entsprechender Inserttag wäre hier praktisch.

Grüße,
Dennis

**Comment by psren** [comment]
:+1: den hatte ich mir auch schon gewünscht.

**Comment by leofeyer** [comment]
Ich gehe davon aus, dass Du das Frontend-Theme und darin das Feld "Folders" meinst, oder? Dort kann ich jedoch mehrere Ordner auswählen.

**Comment by denniserdmann** [comment]
Stimmt. Du hast recht, das habe ich übersehen und eine praktikable Lösung fällt mir so spontan auch nicht ein.

**Comment by leofeyer** [comment]
Sollen wir das Ticket dann erstmal schließen?
