### ISSUE TITLE
Nach Login Weiterleitung zur vorletzten/letzten Seite

### ISSUE THREAD

**Issue by matthiasneid** [contao/core#7736]
Der Fix https://github.com/contao/core/pull/7568 sorgt bei Seiten, bei denen das Loginmodul direkt in eine normale Seite eingebaut ist für Probleme, da nach dem Login nicht zur letzten sondern sozusagen zur vorletzten Seite weitergeleitet wird, bedingt durch `if (!$_POST && $this->redirectBack)`, was bei eigenständigen Loginseiten durchaus Sinn macht.

Am besten wäre es also, um alle Einsatzmöglichkeiten abzudecken, eine Auswahl treffen zu können, ob ein Loginmodul zur letzten oder zur vorletzten Seite weiterleiten soll, bzw. ob es sich um eine eigenständige Loginseite handelt oder nicht.

**Comment by leofeyer** [comment]
@Toflar /cc

**Comment by Toflar** [comment]
Ich verstehe das Problem nicht.

**Comment by fritzmg** [comment]
@matthiasneid in solchen Fällen, wo du das Login Modul im Page Layout eingebunden hast, musst du einfach die Optionen _Weiterleitungsseite_ und _Zur zuletzt besuchten Seite_ deaktivieren. Du willst ja auf der selben Seite bleiben nach dem Login, deiner Beschreibung nach zumindest, daher darfst du eben weder eine Weiterleitungsseite einstellen, noch die Option _Zur zuletzt besuchten Seite_ aktivieren.

**Comment by matthiasneid** [comment]
Danke @fritzmg das funktioniert auch bei mir.
