### ISSUE TITLE
Standardlayout pro Theme

### ISSUE THREAD

**Issue by frontendschlampe** [contao/core#7740]
In Verbindung mit https://github.com/contao/core/issues/7739 könnte man dann auch nochmal darüber nachdenken, die Funktionalität des Standardlayouts wieder einzuführen, welches pro Theme und somit pro Seitenbaum festgelegt werden kann. Damit braucht man im Startpunkt einer Website nur noch das Standardtheme wählen, was automatisch ein Standardlayout setzt (eine Layoutauswahl wäre für den Seitentyp Startpunkt nicht mehr nötig). Die Layoutauswahl für alle anderen Seitentypen bleibt davon unberührt.

**Comment by Aybee** [comment]
:+1: für Standardlayout, das vermisse ich, seit es entfernt wurde.

**Comment by leofeyer** [comment]
Ich schließe dieses Ticket zugunsten von #7739.
