### ISSUE TITLE
[3.4.5] Searchindex does not regonize SSL for news and faq

### ISSUE THREAD

**Issue by GodMod** [contao/core#7741]
When rebuilding the search index from backend, Contao lists all pages.
The protocol for normal articles is correct, but for dynamic things like news or FAQs, the protocol is still http. This leads to an security error in Browser, because he blocks access to http from a https site.

Screenshot from the page list:

![2015-04-02_0917](https://cloud.githubusercontent.com/assets/1192057/7931461/37996fe6-0911-11e5-9e6a-a17726f222b7.png)

**Comment by GodMod** [comment]
Also ich hab mal etwas nachgeforscht, woher dieser Fehler kommt.
Er betrifft alles, was durch den Hook "getSearchablePages" reinkommt. Z.B. im ModuleFAQ.php, Methode "getSearchablePages()" wird mittels `$objParent->rootUseSSL` geprüft, ob die Parent Seite das SSL Flag hat. Haben aber alle meinen Seiten nicht, ich wüsste auch nicht, wo ich das einstellen sollte, ich habe meine komplette Seite mittels einer .htaccess auf SSL umgeleitet und greife auch nur über https darauf zu. Da aber eben das Flag nicht gesetzt ist, werden die URLs nur mit http gebildet. Auch wenn ich es in der .htaccess erlauben würde, http zu nutzen, würde der Browser hier immer noch Probleme machen und den Ajax-Request blocken.

**Comment by leofeyer** [comment]
Das entsprechende Feld ist hier:

![](https://cloud.githubusercontent.com/assets/1192057/7931512/7e2fa63c-0911-11e5-9344-8f1755238773.png)
