### ISSUE TITLE
Error after bad search with page picker

### ISSUE THREAD

**Issue by Aybee** [contao/core#7743]
Contao 3.4.4 in der Online-Demo
Inhaltselement Hyperlink erstellen.
Page picker öffnen.
`[` in das Suchfeld eingeben.

Es erscheint der Fehler
```
Fatal error: Uncaught exception Exception with message Query error: 
Got error 'brackets ([ ]) not balanced' from regexp (SELECT id FROM tl_page 
WHERE CAST(title AS CHAR) REGEXP '[') 
thrown in system/modules/core/library/Contao/Database/Statement.php on line 293
```
Dieser Fehler erscheint jetzt immer wenn man den Seitenwähler anklickt. Für den Seitenwähler im RTE gilt dasselbe. Er verschwindet erst wieder, wenn man in den Benutzereigenschaften die Session-Daten bereinigt.

**Comment by leofeyer** [comment]
Behoben in 70dd1ba1f224b8909345af63902049b208b04a93. Muss aber noch zurück portiert werden.

**Comment by leofeyer** [comment]
Wurde inzwischen zurück portiert.
