### ISSUE TITLE
[3.4.5] Wrong description of default value for Title-Tag field in layout

### ISSUE THREAD

**Issue by schubidos** [contao/core#7744]
Title-Tag in page layout has description:
"Here you can overwrite the title tag (defaults to &lt;em&gt;{{page::pageTitle}} - {{page::**rootTitle**}}&lt;/em&gt;)."

Should be:
"Here you can overwrite the title tag (defaults to &lt;em&gt;{{page::pageTitle}} - {{page::**rootPageTitle**}}&lt;/em&gt;)."

**Comment by leofeyer** [comment]
Fixed in eccf521922141ad908c1d08eb310809ccbc8920b. Should be back ported though.

**Comment by leofeyer** [comment]
It seems this has been fixed in Contao 3.5 already.
