### ISSUE TITLE
[3.4.5] Backend-Startseite "Zuletzt bearbeitet" fehlerhafte Links bei vorheriger Änderung über "Mehrere bearbeiten"

### ISSUE THREAD

**Issue by Mynyx** [contao/core#7745]
Wenn Änderungen über "Mehrere bearbeiten" -> "Überschreiben" oder "Bearbeiten" oder "Aliase generieren" vorgenommen werden, wird auf der Backend-Startseite unter "Zuletzt bearbeitet" bei den Links am Zeilenende zum Bearbeiten/Vergleichen auf die Mehrere-Überschreiben/-Bearbeiten/Aliase generieren-Funktion verlinkt, statt auf die einzelne Bearbeiten-Funktion des jeweiligen Elementes.

**Comment by leofeyer** [comment]
Behoben in 7b63281158db456a3a799d4a46202f93709f0298.
