### ISSUE TITLE
[3.4.5] Template bearbeiten: keine Nennung des Templates in Überschrift

### ISSUE THREAD

**Issue by Mynyx** [contao/core#7746]
Beim Bearbeiten eines Templates wird dieses nicht in der Überschrift genannt, anders als z. B. beim Bearbeiten in der Dateiverwaltung wo der Pfad angezeigt wird ("Dateiverwaltung » files/tinymce.css").

**Comment by leofeyer** [comment]
Fixed in 3b5b87c8ab893f996ac2cea5308a66877e554ddd.

**Comment by aschempp** [comment]
Again something that can't be used by extension developers :-(

**Comment by leofeyer** [comment]
This is a bugfix, because Contao 3.5 is RC already. Feel free to create a PR for the general interface, which however would be a feature.
