### ISSUE TITLE
[3.4.5] Artikel Inhaltselement Typ "Download" Beschreibung bei Dateiauswahl

### ISSUE THREAD

**Issue by Mynyx** [contao/core#7747]
Bei einem Inhaltselement des Typs "Download" in einem Artikel ist bei der Dateiauswahl folgende Beschreibung:
>Bitte wählen Sie eine Datei oder einen Ordner aus der Dateiübersicht.

Auswählbar sind ist aber nur eine Datei und keine Ordner.

**Comment by leofeyer** [comment]
Das ist korrekt, da pro Feld nur eine Beschreibung hinterlegt werden kann. Und je nach Inhaltselement lassen sich eben entweder Dateien oder Ordner auswählen.

**Comment by Mynyx** [comment]
https://github.com/contao/core/blob/master/system/modules/core/dca/tl_content.php#L210-L225

Entsprechend `'filesOnly'=>true` können grundsätzlich keine Ordner ausgewählt werden?

**Comment by BugBuster1701** [comment]
korrekt, dafür gäbe es dann Downloads, mit dem Feld multiSRC

**Comment by Mynyx** [comment]
Ist das Problem immer noch unklar?
