### ISSUE TITLE
[3.4.5] utf8_romanize(): Erhebliche Geschwindigkeitsverbesserung durch Prüfung des Parameters auf ASCII

### ISSUE THREAD

**Issue by Mynyx** [contao/core#7748]
Die Funktion ``utf8_romanize()`` ist sehr langsam und erhöht bei Aufruf eines System-Log mit ca. 100.000 Einträgen so erhebliche die Ladezeit (durch die Funktionsaufrufe bei der Generierung der Filter).

Wenn der übergebene Parameter zunächst darauf geprüft wird, ob eine Umwandlung notwendig ist, tritt eine signifikante Geschwindigkeitsverbesserung ein. (Bei ca. 11.500 Aufrufen mit ASCII-Parameter beträgt diese ungefähr 1.500 ms (sic!)).

https://github.com/contao/core/blob/master/system/helper/mbstring.php#L238
```
	if (utf8_detect_encoding($str) == 'ASCII')
		return $str;
```

**Comment by Toflar** [comment]
Ich habe bei meinen blackfire.io-Tests auch gesehen, dass diese Funktion einer der grössten Bottlenecks ist, die Contao noch hat. Ich denke also es wäre sehr sinnvoll, hier ein bisschen Research reinzustecken. Insbesondere, weil wir uns für die 3.5 für PHP 5.4 entschieden haben und nun den Transliterator nutzen könnten: http://php.net/manual/en/class.transliterator.php

Ausserdem hab ich noch ein Package mit 3.5 Millionen Downloads gefunden, welches versucht, die ganzen `iconv`, `Intl` und `mbstring` Sachen zu abstrahieren und je nach System das schnellste zu wählen: https://github.com/tchwork/utf8
Ein `return \Patchwork\Utf8::toAscii($str);` dürfte womöglich das gleiche Resultat wie bei uns bieten und einiges schneller sein. Die prüft übrigens auch darauf ob überhaupt UTF-8-Ranges betroffen sind (https://github.com/tchwork/utf8/blob/master/class/Patchwork/Utf8.php#L42).

**Comment by leofeyer** [comment]
> Ich denke also es wäre sehr sinnvoll, hier ein bisschen Research reinzustecken. 

+1

**Comment by leofeyer** [comment]
Hinzugefügt in 4060cd95e506b6527bba807394bb5db1418a90c0.

**Comment by Toflar** [comment]
Also kein Research? :)

**Comment by leofeyer** [comment]
Doch, sicher. Das Researching ist doch nicht mit dieser speziellen Optimierung verknüpft, oder?

**Comment by Toflar** [comment]
Nene, nur weil das Ticket zu ist :)

**Comment by leofeyer** [comment]
Könntest Du Deinen Kommentar in ein neues Ticket kopieren?

**Comment by Toflar** [comment]
Hab's direkt zum core-bundle gepflanzt. Würde ich nicht riskieren in der 3er-Version :)
