### ISSUE TITLE
Benutzergruppen Rechte: Anzahl aktiver Checkboxen ist begrenzt.

### ISSUE THREAD

**Issue by Ainschy** [contao/core#7749]
In den Benutzergruppen Einstellungen lasse sich nicht mehr als 955 Checkbox gleichzeitig aktivieren.

Die große Anzahl kommt zu Stand, als ich diverse Module u.a. isotope installierte und versuchte die Benutzerrechte für News anzupassen. Das BLOG Feld 'alexf' liegt bei 35,8 KiB.

Festgestellt in Contao Version 3.4.5 darunter noch nicht geprüft.

Das 'Deaktivieren' der Benutzergruppe wird nicht angenommen.

**Comment by discordier** [comment]
Noch ein Grund dass wir diese endlich normalisieren sollten. Aber das wird erst was in einer der naechsten minors.

**Comment by Ainschy** [comment]
Kannst du mir den Umstand näher erklären?

**Comment by leofeyer** [comment]
> lassen sich nicht mehr als 955 Checkbox gleichzeitig aktivieren

Was genau bedeutet das? Ist der POST-Request zu groß oder das DB-Feld zu klein? Wie äußert sich der Fehler? Gibt es eine Fehlermeldung?

**Comment by Ainschy** [comment]
Es lässt sich nur eine begrenze Anzahl an Checkbox gleichzeitig aktivieren.

Nachstellbar ist dieses der Einfachheit halber mit der Isotope Demo, da hier genügend Checkbox vorhanden sind. [https://isotopeecommerce.org/en/demo.html]

Versuche bitte bei der Benutzergruppe: Editors alle Checkbox zu aktivieren und anschließend zu speichern. Sobald eine gewisse Anzahl (ich habe 955 gezählt) überschritten wird, werden alle darauf folgenden ignoriert. Ob das jetzt an dem POST Request liegt oder ein DB-Feld zu klein ist kann ich nicht sagen. Da die Anzahl der aktiven Checkboxen auch verteilt sein kann. In der tl_user_group ist das Feld 'alexf' 31.3 KiB groß.

![benutzergruppen gruppe id 3 bearbeiten - contao open source cms 3_4](https://cloud.githubusercontent.com/assets/1788135/7023930/7d30910a-dd39-11e4-8df1-5c80d0fe8b5b.png)

**Comment by fritzmg** [comment]
Mach mal folgendes:

* gehe im FireFox in das Backend und editiere die Benutzergruppen rechte
* bevor du auf _Speichern_ klickst, drücke F12 und öffne den _Network/Netzwerk_ Tab
* klicke auf Speichern und danach im Netzwerk Tab auf den POST Request.
* Sieh mal nach, was bei _Content-Length_ (ganz unten)  unter _Headers_ steht

**Comment by leofeyer** [comment]
@aschempp will sich hierzu nochmal melden :)

**Comment by leofeyer** [comment]
Kommentar von @ausi: [max_input_vars](http://php.net/manual/de/info.configuration.php#ini.max-input-vars)

**Comment by BugBuster1701** [comment]
bei "Suhosin with Hardened PHP" gibt es noch:
```
suhosin.post.max_vars
suhosin.request.max_vars
```

**Comment by Total-Reality** [comment]
Also hat im Endeffekt nichts mit Contao zu tun, und nur durch Änderung der php.ini zu realisieren?
Hab mal dort mal max_input_vars = 1500 reingeschrieben und funktioniert.

Wie wärs mit einem Hinweis in den Benutzergruppen, dass die Anzahl der Felder der Einstellung in der php.ini übersteigt und man erst speichern sollte, wenn man den Wert erhöht hat.
Oder kann man die Wert aus der php.ini nicht auslesen?

**Comment by fritzmg** [comment]
Siehe das über dir verlinkte Issue ;).

**Comment by asaage** [comment]
offtopic:
@Ainschy : mich würde mal interessieren, wie du diesen Screenshot erstellt hast.

**Comment by fritzmg** [comment]
Im FireFox geht das zB mit [FireShot](https://addons.mozilla.org/en-us/firefox/addon/fireshot/)

**Comment by Ainschy** [comment]
Erfassen Webseite Screenshot - FireShot FireFox / Chrome Erweiterung

**Comment by asaage** [comment]
danke-danke sowas hätte ich schon öfter mal gebrauchen können.

**Comment by baumannsven** [comment]
@leofeyer wenn man mit js denn submit abgreift und ab einer gewissen Größe unterteilt. wäre doch eine Idee. was meinst du dazu?

**Comment by baumannsven** [comment]
@leofeyer meiner Meinung wäre dies dann auch kein bc Break oder ähnliches

**Comment by Ainschy** [comment]
@baumannsven Nein, geht leider nicht. Wer viel zu konfigurieren hat, wie in meinem Fall. Kann eine zweite Benutzergruppe anlegen und diese dann zuweisen.

**Comment by baumannsven** [comment]
@Ainschy wenn die Übertragung von dem Formular splittest dann geht. hatte selbst schon den Fall.

**Comment by Ainschy** [comment]
Das geht dann nur über ein geteiltes Formular.

**Comment by baumannsven** [comment]
Nein zerlegt Submission mit js

**Comment by Aybee** [comment]
*offtopic:*
> @asaage mich würde mal interessieren, wie du diesen Screenshot erstellt hast.

Ich nutze schon seit Jahren Screengrab https://addons.mozilla.org/de/firefox/addon/screengrab-fix-version/ . Sehr gut.

**Comment by Total-Reality** [comment]
Nochmal die Frage: Warum kann man in Contao nicht einfach ne Fehlermeldung auswerfen, wenn die php.ini Einstellung max_input_vars niedriger ist als die Anzahl der theoretisch speicherbaren Checkboxes etc. der aktuellen Seite?
Dann wüsste der Admin gleich, dass er vorher etwas an der php.ini ändern muss.

Kann ja nicht sein, dass man jemanden mühselig tausende Felder anklicken lässt und am Ende ist bloß die Hälfte davon ausgewählt

**Comment by asaage** [comment]
Die Anzahl der Checkboxen hängt davon ab, welche/wieviele Erweiterungen installiert sind.
Vielleicht auch noch davon, welche legenden aufgeklappt sind.
Es wird wohl schwer Möglich sein, den Wert zu ermitteln, um ihn mit max_input_vars zu vergleichen.

**Comment by fritzmg** [comment]
Wieviele input fields vorhanden sind, sollte eigentlich nicht schwer zu ermitteln sein, egal welche Erweiterungen installiert sind. Und wenn es, warum auch immer, doch nicht so leicht ermittelbar ist, dann kann zumindest ein JavaScript erzeugt werden, dass diesen Vergleich macht.

**Comment by Total-Reality** [comment]
Du musst doch bloß von allen Datenbank-Tabellen alle Felder zählen... das ist ne Abfrage, die in 0.03 Sekunden oder so erledigt ist...

**Comment by asaage** [comment]
Stimmt, ein clientseitiger Check mit js on-submit wäre wirklich nicht so schwer, der Wert für max_input_vars müßte aber mit ini_get verfügbar gemacht werden. Als hidden-field im Formular oder als cookie..

**Comment by fritzmg** [comment]
> Du musst doch bloß von allen Datenbank-Tabellen alle Felder zählen... das ist ne Abfrage, die in 0.03 Sekunden oder so erledigt ist...

Naja, so einfach ist es nicht. Im DC_Table müssen einfach alle input und select Felder gezählt werden, die für einen View erzeugt werden.

> Stimmt, ein clientseitiger Check mit js on-submit wäre wirklich nicht so schwer, der Wert für max_input_vars müßte aber mit ini_get verfügbar gemacht werden. Als hidden-field im Formular oder als cookie..

Ich würde den Wert von `max_input_var` direkt als JavaScript Variable injecten und dann bei document-ready überprüfen, ob irgendein Formular mehr inputs/selects hat, als dieser Wert - wenn ja, dann eine Warning in den DOM geben.

**Comment by asaage** [comment]
Dein Einsatz in allen Ehren aber ehrlichgesagt find ich's fraglich, ob's den Aufwand wert ist.
Vielleicht sollte man eher mal darüber nachdenken, diese spezielle Einstellungsseite zu splitten und anders zu organisieren - ich könnte mir vorstellen das würde die Bedienbarkeit wirklich vebessern wenn man z.B. die Feld-berechtigungen (sowie die Archiv-, Kategorie-, Kalender-, Pagemounts-, Filemounts-Auswahl) bei den entsprechenden Modulen zu stehen hätte und dann so einen Art Child-View für jedes Backend-Modul hätte.
Oder halt wenigstens das Formular splitten, dass man pro Abschnitt einen Speichern-button hat.
Beides müßte die max_input_vars Problematik doch eigentlich auch mehr oder weniger beheben.
