### ISSUE TITLE
File Upload -> uuid wird nicht in Zieltabelle gespeichert

### ISSUE THREAD

**Issue by markknochen1** [contao/core#7751]
Ich beziehe mich hier nochmal auf die Issues 

https://github.com/contao/core/issues/6986
https://github.com/contao/core/issues/6849

Ich benutze ein Contao 3.4.4 - und habe per Formulareditor ein Formular mit File-Upload -> benannt singleSRC
Das Formular soll per "Formulardaten speichern" in eine Tabelle gespeichert werden ... in dem Fall tl_calendar_events

Hochgeladen wird das File, in der Session ist die UUID auch vorhanden .... aber in die Zieltabelle wird nicht diese uuid geschrieben ....

Mark

**Comment by leofeyer** [comment]
Was steht denn nach dem Upload in `tl_calendar_events.singleSRC`?

**Comment by markknochen1** [comment]
Auch ein Wert, der wie eine uuid aussieht - aber was anderes ist ...

**Comment by leofeyer** [comment]
Geht es etwas konkreter?

**Comment by fritzmg** [comment]
@markknochen1 Wenn du per Form Generator die Daten in eine Tabelle speichern lässt, speichert Contao dort nur den Pfad zur Datei, nicht die UUID. Siehe [Form.php#L444](https://github.com/contao/core/blob/master/system/modules/core/forms/Form.php#L444).

Du musst hier zusätzlich noch einen eigenen `storeFormData` Hook schreiben, wo du an der entsprechenden Stelle in `$arrSet` statt dem Pfad die UUID hineinschreibst. Am einfachsten geht das mit
```php
$objFile = \Dbafs::addResource( $arrSet['filefield'] );
$arrSet['filefield'] = $objFile->uuid;
```
(ungetestet)

Hinweis: die Datei ist zu diesem Zeitpunkt schon im DBAFS vorhanden - aber so stellt man sicher, dass das tatsächlich der Fall ist und man bekommt gleich das File Object zurück.

**Comment by markknochen1** [comment]
Danke ... das funktionert 

@leofeyer im $arrSet['singleSRC'] steht noch der Pfad + Dateiname und das wird vermutlich dann in das binäre Feld 'singleSRC' geschrieben ... hier sollte doch dann eher der Core die Funktion mitbringen, dass die uuid da rein kommt.

btw: den Hook storeFormData hatte ich nicht gefunden ... sollte man mal hier mit listen:

https://contao.org/de/manual/3.0/customizing-contao.html

Danke

Mark

**Comment by fritzmg** [comment]
> @leofeyer im $arrSet['singleSRC'] steht noch der Pfad + Dateiname und das wird vermutlich dann in das binäre Feld 'singleSRC' geschrieben ... hier sollte doch dann eher der Core die Funktion mitbringen, dass die uuid da rein kommt.

Naja, normalerweise ist der Form Generator dafür ja nicht unbedingt vorgesehen. Du kannst die Dateiinformationen ja in eine beliebige Tabelle speichern willst - in welcher Form die Daten gespeichert werden sollen (also als UUID oder einfach nur als Pfad) weiß das Formular ja nicht.

Eine Checkbox für das entsprechende File Form Field wäre natürlich praktisch. Ich könnte mir auch vorstellen, dass beim speichern der Informationen in die Tabelle automatisch das DCA überprüft wird, ob die Zieltabelle darin vorkommt und wenn ja, ob das entsprechende field ein file field ist wo die binäre UUID gebraucht wird.

Letzteres könnte man auch in einer allgemeinen, simplen Extension machen.


Bzgl. Dokumentation: stimmt - das sollte man mal nachziehen.

**Comment by aschempp** [comment]
> Bzgl. Dokumentation: stimmt - das sollte man mal nachziehen.

Im experimentellen Teil der Doku (https://github.com/contao/docs/blob/3.4/api/hooks/storeFormData.md) ist der Hook schon vorhanden. Vermutlich werden wir das für die neue docs.contao.org übernehmen (bzw. mit der bestehenden Doku zusammenführen).

**Comment by fritzmg** [comment]
@aschempp ah ok :)

Ich habe hier mal eine kleine Erweiterung gebastelt, mit der das Konvertieren zu einer UUID nun automatisch passiert, wenn das Ziel-Feld im DCA als single fileTree input definiert ist.

* ER2: [[store_uuid](https://contao.org/de/extension-list/view/store_uuid.10009.de.html)]
* GitHub: [fritzmg/contao-store-uuid](https://github.com/fritzmg/contao-store-uuid)
* Packagist: [fritzmg/contao-store-uuid](https://packagist.org/packages/fritzmg/contao-store-uuid)
