### ISSUE TITLE
[3.5] Add attributes template var to picture_default template again.

### ISSUE THREAD

**Issue by dmolineus** [contao/core#7752]
As part of the pull request #7718 the `attributes` template var was `added` to the picture_default template (5ffb76721c86e31bd8229d6d5bdb811820c12a57). When switching to the short tags it was accidently removed again [picture_default.html5](https://github.com/contao/core/blob/1a784d5105fa115a42005e10032c78af964828bc/system/modules/core/templates/picture/picture_default.html5).

Please readd the attributes parameter again.

**Comment by ausi** [comment]
The `class` attribute added in 83e85c7ff83188e992482096f2b5291c996f7c86 was also removed accidentally in 1a784d5105fa115a42005e10032c78af964828bc.

**Comment by leofeyer** [comment]
Fixed in ca96e4c17752c0a60e4f06449c2de2944a27795b.
