### ISSUE TITLE
[3.2.16] Such Index bei großen Seiten lässt Einträge aus

### ISSUE THREAD

**Issue by zirkai** [contao/core#7753]
Hallo zusammen, habe im Changelog zur 3.5 beta1 gelesen, dass Datenbank zugriffe massiv beschleunigt wurden. Das begrüsse ich sehr.
Habe eine Newsportal mit 22,890 tl_news-Einträge und inzwischen 28,542 tl_content-Einträge in der Datenbank. Das führt dazu, dass der Suchindex Newsbeiträge nicht erfasst oder übergeht. Die tl_search hat gerade mal 20,673 Einträge. Einige News-Beiträge fehlen im Suchergebnis. Da ich Webdesigner und kein Programmierer bin, fehlt mir das Knowhow die Hintergründe zu erfassen und den Fehler genauer zu beschreiben. 
Falls ein Testsystem gesucht wird oder jemand Ideen zur Optimierung der bestehenden Indexierung hat, gerne melden. Ein Update der DEV-Version auf 3.5 sollte kein Problem sein, falls das hilft.
Das Contao ist auf einem Managed Server, die Ressourcen sollten ausreichen.
Frohes Schaffen und Gruß, Kai

**Comment by Toflar** [comment]
Hast du denn auch den Suchindex aufgebaut? Der Newsbeitrag wird erst indexiert, wenn er zum ersten mal im Frontend aufgerufen wurde bzw. der Suchindex manuell neu aufgebaut wird.

**Comment by holist** [comment]
Hi,
auch alte News aus 2009, die mehrfach manuell angeschuckt wurden, werden nicht erfasst. Es muss noch an etwas anderem liegen.
Beispiel Suchbegriff „Greeen“:
https://www.inka-magazin.de/suchergebnis/alle.html?keywords=greeen <https://www.inka-magazin.de/suchergebnis/alle.html?keywords=greeen>
Es werden 3 Events angezeigt. 

Der eigentlich gesucht Artikel https://www.inka-magazin.de/popkultur/greeen.html <https://www.inka-magazin.de/popkultur/greeen.html> erscheint nicht.

Vielleicht hilft das für das Verständnis.
Gehe auch davon aus, dass Events vor den News indexiert werden?
Danke vorab für eure Hilfe.
Frohes Schaffen und Gruß, Kai

**Comment by holist** [comment]
Hab den Index gelöscht und neu aufbauen lassen. Mal sehen wie es dann morgen aussieht, wenn er durch ist.
Schönen Abend und Gruß

**Comment by Toflar** [comment]
Also ich glaube zwar nicht, dass es an Contao liegt, aber wenn ich vollen Zugriff (Admin, (S)FTP) auf ein Testsystem erhalte, würd ich mir das bei Gelegenheit mal ansehen. Zugangsdaten dann per E-Mail an mich :)

**Comment by Toflar** [comment]
So. Analyse:

* Indexiert werden die Suchergebnisse nicht, weil die Reader-Seite der News auf "Nicht durchsuchen" gestellt ist. Anwenderfehler.
* Der Suchindex ist mit 3 Millionen Einträgen natürlich jetzt schon gross. Trotzdem braucht das Such-Query nicht mehr weder 900ms. Bei der Menge und der Tatsache, dass es auch noch nach Relevanz sortiert und die Seiten-ID's prüft, durchaus vertretbar. Die DB-Indexe sind korrekt gesetzt und greifen auch. Dein DB-Server braucht einfach manchmal bis zu 4.5 Sekunden zusätzliche Antwortzeit. Lokal wirst du das nicht nachstellen können. Vielleicht mal beim Server-Admin nachfragen...

Also alles nicht Probleme, die Contao lösen kann.

Das einzige was @leofeyer bzw. wir optimieren könnten wäre die Models per Option nicht in die Registry aufzunehmen. Bei deiner riesigen Anzahl News, braucht das Generieren der Sitemap extrem viel RAM obwohl die Zwischenspeicherung in der Registry in diesem Fall nichts bringt, weil die gleiche News nie zwei Mal kommen wird. Aber das hat nichts mit Geschwindigkeit und nichts mit dem von dir beschriebenen Problemen zu tun.

**Comment by zirkai** [comment]
Immer diese Flüchtigkeitsfehler *tss ts ts
Vielen Dank Toflar für deine Hilfe, manchmal sieht man den Wald vor lauter Bäumen nicht.
Habe alles durchgetestet. Läuft jetzt alles wie es soll. Solide wie gewohnt von Contao. Bin gespannt was performancemäßig noch passiert. DB-Zugriffe habe ich weitergeleitet zur Prüfung.
Frohes Schaffen und Gruß, Kai
