### ISSUE TITLE
Inconsistency with index page when not using URL rewriting 

### ISSUE THREAD

**Issue by fritzmg** [contao/core#7757]
Applies to any Contao version I think.

### Problem description

* Create a site structure with the first page having the alias "index", as usual
* Create a navigation module and include it in the page layout
* Do not activate URL rewriting in the settings
* Now open the frontend with http://www.domain.com/

Naturally, this will display the start page. However:

1. in the navigation menu, the link to the start page is not empty, but contains `index.php/`.
2. in the navigation menu, the link to the start page does not have the `active` class, but instead has the `trail` class, as if the current page was a subpage of the start page.

### Cause

[1.] seems to be a known limitation when not using URL rewriting, since [Contao\Controller::generateFrontendUrl](https://github.com/contao/core/blob/master/system/modules/core/library/Contao/Controller.php#L2226) has the following lines of code:
```php
// Correctly handle the "index" alias (see #3961)
if ($arrRow['alias'] == 'index' && $strParams == '')
{
	$strUrl = (\Config::get('rewriteURL') ? '' : 'index.php/') . $strLanguage;
}
else
{
	$strUrl = (\Config::get('rewriteURL') ? '' : 'index.php/') . $strLanguage . ($arrRow['alias'] ?: $arrRow['id']) . $strParams . \Config::get('urlSuffix');
}
```
So even if you are on the index page, you will always have `index.php/` in the url when not using URL rewriting. May be this could be changed, so that if `$strLanguage` is empty, `index.php/` is always omitted.

[2.] is a problem within [Contao\Module::renderNavigation](https://github.com/contao/core/blob/master/system/modules/core/modules/Module.php#L317), specifically this condition:
```php
// Active page
if (($objPage->id == $objSubpages->id || $objSubpages->type == 'forward' && $objPage->id == $objSubpages->jumpTo) && !$this instanceof \ModuleSitemap && $href == \Environment::get('request'))
{
	// Mark active forward pages (see #4822)
	$strClass = (($objSubpages->type == 'forward' && $objPage->id == $objSubpages->jumpTo) ? 'forward' . ($trail ? ' trail' : '') : 'active') . (($subitems != '') ? ' submenu' : '') . ($objSubpages->protected ? ' protected' : '') . (($objSubpages->cssClass != '') ? ' ' . $objSubpages->cssClass : '');

	$row['isActive'] = true;
	$row['isTrail'] = false;
}
```
Or more specifically, the last part of the condition:
```php
$href == \Environment::get('request')
```
(introduced due to #7189) It assumes, that if the href equals the request, then ist must be the active page. However, this will not be true for the start page href (without using URL rewriting), if you request the page with http://www.domain.com/, since the computed href of the startpage will actually be http://www.domain.com/index.php/ . Though this problem would not occur anymore if [1.] is changed.

### References

[2 Seiten: Eine MIT Deppenlink, eine OHNE -- wieso?!](https://community.contao.org/de/showthread.php?56534-2-Seiten-Eine-MIT-Deppenlink-eine-OHNE-wieso-!)

**Comment by leofeyer** [comment]
Fixed in 548ea9b41accc658aed658b9723c1523a4ec4090.
