### ISSUE TITLE
[3.4.5] Sitemap enthält Seiten mit Robots-Tag noindex

### ISSUE THREAD

**Issue by Mynyx** [contao/core#7758]
In der von Contao generierten Sitemap sind auch Seiten enthalten, die mit dem Robots-Tag noindex gekennzeichnet sind.

**Comment by leofeyer** [comment]
Das ist korrekt. Das Robots-Tag hat nichts mit der Sitemap zu tun. Dafür gibt es die Einstellung "In der Sitemap anzeigen".
