### ISSUE TITLE
[3.4.5] Mitgliederregistrierung: E-Mail-Versand

### ISSUE THREAD

**Issue by minstyle** [contao/core#7759]
Bei der Registrierung eines neuen Mitglieds erhält der Admin automatisch eine neue E-Mail.

Aktiviere ich im Backend im Modul "Registrierung" die Checkbox "Aktivierungsmail verschicken", dann wird bei einer Neuregisitrierung eines Mitglieds keine E-Mail an den Administrator verschickt. Nur die Bestätigungs-E-Mail an den Nutzer wird versendet.

Schön wäre es, wenn hier beide jeweils eine E-Mail erhalten. Also der Admin wie auch der neue Nutzer.

**Comment by Aybee** [comment]
:+1: Wenn "Aktivierungsmail verschicken" angehakt ist müsste die Mail an den Admin wahrscheinlich erst nach der Bestätigung erfolgen.

**Comment by aschempp** [comment]
FYI: mit dem [Notification Center](https://contao.org/de/extension-list/view/notification_center.10020029.en.html) kannst du das frei konfigurieren.

**Comment by minstyle** [comment]
@Aybee 
Nein, leider nicht.

@aschempp
Leider finde ich hierzu keine Tutorials im Netz. Ich verstehe diese Erweiterung nicht wirklich.

Handelt es sich denn jetzt hier um einen Contao-Bug oder ist das so normal?

**Comment by aschempp** [comment]
> Handelt es sich denn jetzt hier um einen Contao-Bug oder ist das so normal?

Das ist das normale verhalten. Der Admin bekommt eine Email um das Konto freizuschalten. Bei Benachrichtigung ist das nicht nötig, weil der Benutzer ja selber freischalten kann.

**Comment by minstyle** [comment]
Hierbei handelt es sich um ein Mitglied, nicht um einen Benutzer. Das Mitglied hat nur Zugriff auf versteckte Seiten.

Ich brauche unbedingt eine Benachrichtigung für den Admin, um das Mitglied freischalten zu können.

**Comment by Aybee** [comment]
> Ich brauche unbedingt eine Benachrichtigung für den Admin, um das Mitglied freischalten zu können.

Wenn das so funktioniert wie es soll und wie @aschempp es auch nochmal gesagt hat macht das ja keinen Sinn, denn über die Bestätigungsmail aktiviert sich das Mitglied ja selber.

- Wenn angehakt bekommt der Admin keine Mail. Mitglied muss sich selber aktivieren.
- Wenn nicht angehakt bekommt der Admin eine Mail um das Mitglied zu aktivieren.

Ich dachte die Mail würde zur Info benötigt, also auch dann, wenn der Kunde sich selber aktiviert, dafür war mein :+1:

**Comment by minstyle** [comment]
Das Mitglied soll sich registrieren können ohne Möglichkeit sich selbst aktivieren zu können.

Der Admin erhält daraufhin eine Info via E-Mail und kann das Mitglied aktivieren oder ablehnen.

Bei Aktivierung soll das Mitglied eine Bestätigungs-E-Mail erhalten.

Schade das es hier keine Möglichkeit gibt. Anscheinend nur mit Erweiterungen, die aber mit der aktuellen Contao-Version derzeit alle nicht kompatibel sind.

**Comment by Aybee** [comment]
> Bei Aktivierung soll das Mitglied eine Bestätigungs-E-Mail erhalten.

Ok, das ist aber jetzt was anderes als das was du im ersten Post geschrieben hast.
