### ISSUE TITLE
[3.4.5] Multiselect wird ohne Wert nicht gespeichert

### ISSUE THREAD

**Issue by valentin-** [contao/core#7760]
Wenn ein select ('multiple' => true) ohne Wert gespeichert wird, wird das Feld nicht gespeichert. 
Lässt sich in der aktuellen Demo reproduzieren.

```
Config:

$GLOBALS['TL_DCA']['tl_member']['fields']['test'] = array
(
	'label'	            => &$GLOBALS['TL_LANG']['tl_member']['test'],
	'inputType'	        => 'select',
	'options' => array(1,2,3),
	'eval'		        => array
	(
		'includeBlankOption' => true,
		'feEditable'    => true,
		'multiple'		=> true,
		'feGroup'       => 'personal'

	),
	'sql'                     => "blob NULL"
);
```

1) Wert 1, 2 ist ausgewählt (und gespeichert)

![bildschirmfoto 2015-04-14 um 13 12 18](https://cloud.githubusercontent.com/assets/90033/7135527/e4857370-e2a7-11e4-8277-f7bfbbea680a.png)

2) Selektion wird aufgehoben

![bildschirmfoto 2015-04-14 um 13 12 30](https://cloud.githubusercontent.com/assets/90033/7135533/f49dfc8c-e2a7-11e4-86a0-f3be927d98b2.png)

3) Nach Speichern + Reload sollte keine Auswahl vorhanden sein

![bildschirmfoto 2015-04-14 um 13 13 48](https://cloud.githubusercontent.com/assets/90033/7135541/19b8c498-e2a8-11e4-8de4-733a461e93a9.png)

Ergänzung:

Das Feld kann im Backend bearbeitet werden. Sobald jedoch im Frontend das Feld gespeichert wurde und das Feld ohne Wert gespeichert werden soll, ist es auch im Backend nicht mehr möglich das Feld ohne Wert zu speichern.

![bildschirmfoto 2015-04-14 um 13 22 40](https://cloud.githubusercontent.com/assets/90033/7135661/58c2ca20-e2a9-11e4-97ea-7c8d018abf4e.png)

**Comment by leofeyer** [comment]
Konnte ich im aktuellen `release/3.5.0`-Zweig nicht reproduzieren. Das Feld ließ sich sowohl im BE als auch im FE ohne Probleme leer speichern.

**Comment by rittler** [comment]
Der Fehler lässt sich mit der aktuellsten Version 3.5 noch immer reproduzieren.

1. Login im Backend und das Feld bearbeiten 
2. Login im Frontend und das Feld bearbeiten
3. Zurück in das Backend wechseln und versuchen, das Feld ohne Werte zu speichern --> nicht möglich

Mit einer frischen Session (Logout + Login im Backend) kann das Feld wieder gespeichert werden.

**Comment by leofeyer** [comment]
Behoben in 13616dc2f839492ff8630685c0b765c1fea3964f.
