### ISSUE TITLE
Template für Formular / $this->getForm mit Template-Parameter

### ISSUE THREAD

**Issue by Fuzzyma** [contao/core#7761]
Man kann nur für Formularfelder ein Template angeben, nicht aber für das Formular an sich.
Kann man das noch hinzufügen? 
Zusätzlich könnte ich mir auch noch einen zusätzlichen Paremeter für die `getForm`-Funktion vorstellen, wo man das Template auch angeben könnte.

**Comment by leofeyer** [comment]
Inzwischen gibt es ein `form_wrapper.html5`-Template.
