### ISSUE TITLE
Formular Klassen nicht dem wrapper-div hinzugefügt

### ISSUE THREAD

**Issue by Fuzzyma** [contao/core#7762]
Alle Klassen, die man beim erstellen eines Formulares angibt landen letztendlich im form-tag statt im div, der das Formular umgibt. So ist es nicht möglich, den div für ein spezifisches Formular zu ändern.
Gannz zu schweigen von der verwirrung, die das verursacht, wenn `$this->class` im template auf einmal leer ist und in `this->attributes` auf einmal die Klassen auftauchen.

**Comment by Aybee** [comment]
Das Formular hat ja eigentlich keinen DIV als Wrapper. Der DIV wird erst erzeugt, wenn man das Formular ins FE bringst, entweder als CE Typ Formular, CE Typ Modul oder wenn man es als Modul ins Layout bringt. Du kannst die Klasse für das Formular-DIV also im CE oder im Modul setzen.

**Comment by Fuzzyma** [comment]
Das ist zwar richtig, aber da man ja davon ausgehen kann, das Formulare dafür da sind um angezeigt zu erden und das form-template jenen div enthält (also auch in jedem Fall so ausgegeben wird), sollte der div die Klassen bekommen.
Es ist auf in jeden Fall komplett sinnfrei, wenn in `this->class` einfach nichts mehr drinne steht (wozu dann überhaupt ausgeben) und das in `this->attributes` die Klassen auf einmal auftauchen.
Dann lieber doch `this->class` im Formulartag ausgeben um wenigstens das übersichtlicher zu halten

**Comment by Aybee** [comment]
Ah, ok, der DIV ist also doch in dem Template drin. Ja, da gebe ich dir recht, das wäre einfacher. Allerdings, wenn die Anpassung zu aufwändig wird, würde ich auf die Möglichkeit zurückgreifen die Klassen im CE|Modul einzutragen.

`$this->class` ist übrigens nicht leer.

Du möchtest also, dass die Klasse des Formulars, welche durch `$this->attributes` als ` class="myformclass"` ausgegeben wird, mit in `$this->class` übernommen wird, welches momentan die Klassen des CEs|Moduls|u.a. enthält.
Beispiel:
vorher
`$this->class == "ce_form form-search"`
nachher
`$this->class == "ce_form form-search myformclass"`
`$this->attributes` kann so bleiben, Template muss auch nicht angepasst werden.
https://github.com/contao/core/blob/master/system/modules/core/templates/forms/form.html5#L3
attributes in Zeile 9.
