### ISSUE TITLE
Textanker bzw. Springen zu Fehlermeldungen im Formular

### ISSUE THREAD

**Issue by madmaharaja** [contao/core#7765]
Wenn Formulare weiter unten auf Seiten eingebunden werden, sodass man zum Formular scrollen muss, kann es passieren, dass die Fehlermeldung bei einem fehlerhaft oder unzureichend ausgefülltem Formular außerhalb des Blickfelds des Users liegt und somit nicht realisiert wird, dass das Formular noch gar nicht versendet wurde. Dieses Usability-Problem lässt sich z.B. folgendermaßen im Contao-Demo reproduzieren:
1. Man bindet im Artikel "Text Elements" zuunterst das Formular "Contact" ein.
2. Man ruft die Frontendseite http://demo.contao.org/en/text-elements.html auf, füllt das Formular vollständig aus, gibt aber eine *falsche Antwort* bei der Sicherheitsfrage ein (Feld nicht leer lassen).
3. Wenn man das Formular nun abzusenden versucht, lädt der Browser kurz und springt dann zum Anfang der Seite. Das Formular samt Fehlermeldung liegt nun außerhalb des Blickfelds. Wenn man nicht stutzig wird, weil man keine Bestätigungsseite angezeigt bekommen, könnte man als User nun leicht meinen, das Formular sei abgesendet worden.
Mein Vorschlag/Featurewunsch wäre, dass in solchen Fällen, die Seite automatisch zu der entsprechenden Stelle mit der Fehlermeldung springt.

**Comment by may17** [comment]
Das Problem hat man auch bei den Paginationen. Wenn man z.b. auf eine Seitenzahl in einer Navigation klickt, und diese in der Mitte der Seite ist, dann muss man erst wieder an die Position scrollen. Ich habe daher für die Contaodemo ein kleines jQuery script gebaut welches dieses Problem löst. Das Script für mootools oder frameworkless zu bauen wäre kein Problem.

Man sieht das problem ganz gut in der Listing Funktion http://demo.contao.org/en/applications.html da das boomerang script fehlt (404 fehler).

**Comment by leofeyer** [comment]
Das kannst Du per JavaScript lösen, beispielsweise so:

```js
// Form field focus
window.addEvent('load', function() {
        var el = $$('p.confirm');
        if (el[0]) {
                if (el[0].getPosition().y > window.getSize().y) {
                        window.scrollTo(0, el[0].getPosition().y - 120);
                }
        }
});
```

Das obige Beispiel bezieht sich auf Bestätigungsmeldungen; Fehlermeldungen wären dann `p.error`.

**Comment by madmaharaja** [comment]
Danke für den Hinweis! Würde nicht eine Implementierung dessen im Core Sinn Sinn machen?

**Comment by seaneble** [comment]
Wenn das mal noch jemand mit jQuery statt mit Mootools machen möchte:

```js
// Form field focus
$(document).ready(function() {
        var el = $('p.error');
        if (el[0]) {
                if (el.offset().top > $(window).height()) {
                        $('html, body').animate({
                                scrollTop: el.offset().top - 120
                        },'slow');
                }
        }
});
```
