### ISSUE TITLE
Werte von Readonly Feldern werden nicht gespeichert.

### ISSUE THREAD

**Issue by garyee** [contao/core#7766]
Hallo,

ich baue gerade an einem Modul welches ein  Datenbankfeld hat, dessen Wert sich aus verschiedenen anderen Werten errechnet.
Jetzt hab ich das Feld in der DCA auf readonly gesetzt, ein loadcallback reingetan und dachte das geht..
Der Wert des Text-Inputs steht auch in dem $_Post Array drinn, wird aber von Contao nicht übernommen. (Widget class Zeile 290 ?)
Außerdem wäre ein "richtiges" (ausgrauen und nicht mehr ausklappen) readonly für Selectboxen gut.
Ich nehme jetzt an dass das eine mit dem anderen zusammenhängt (Pseudo Readonly für Selectboxen durch nicht übernahme der Werte).
Es ist aber irgendwie etwas missverständlich, finde ich, wenn ich nicht möchte das die Werte des Inputs übernommen werden, dann setzte ich das Feld disabled und wenn ich möchte das der Nutzer die Werte nicht verändern kann sie aber trozdem aber mit aber übernommen werden, dann nehm ich readonly.

**Comment by bytehead** [comment]
`readonly`-Felder werden meines Wissens ignoriert, auch wenn du den Wert änderst. Du hättest die Möglichkeit allenfalls per Hooks (z.B. [prepareFormData](https://contao.org/de/manual/3.4/customizing-contao.html#prepareformdata) oder [processFormData](https://contao.org/de/manual/3.4/customizing-contao.html#processformdata)) noch in das Verhalten einzugreifen und evt. das `readonly`-Flag vor dem Speichern noch zu entfernen.

**Comment by leofeyer** [comment]
Das ist korrekt, `readonly`-Felder speichern niemals einen Wert.

**Comment by garyee** [comment]
Aber da ist das dann ja das selbe wie disabled

[w3c Recommendation](http://www.w3.org/TR/html4/interact/forms.html#h-17.12)

> In contexts where user input is either undesirable or irrelevant, it is important to be able to disable a control or render it read-only. For example, one may want to disable a form's submit button until the user has entered some required data. Similarly, an author may want to include a piece of read-only text **that must be submitted as a value along with the form**. The following sections describe disabled and read-only controls.

Oder hier noch ein [guter Artikel](https://kreotekdev.wordpress.com/2007/11/08/disabled-vs-readonly-form-fields/):

> The Disabled attribute
> Values for disabled form elements are not passed to the processor method. The W3C calls this a successful element.(This works similar to form check boxes that are not checked.)
> 
> The Read Only Attribute
> Form elements with the readonly attribute set will get passed to the form processor.

Der Grund warum es "disabled" und "readonly" gibt liegt doch darin das der Wert des Inputs einmal mit "verschickt" wird und bei den anderen nicht. In dem Sinne müsste Contao doch eigentlich auch die Werte von Inputfeldern übernehmen die auf readonly gesetzt sind. Sonst kann man die Readonly-Eigenschaft ganz raus nehmen und hat halt nur disabled.

**Comment by aschempp** [comment]
Diese Diskussion hatten wir schon. Readonly-Felder können vom Benutzer manipuliert werden, deshalb kann es nie eine gute Idee sein diese zu verarbeiten.

**Comment by garyee** [comment]
Ah okay das wusste ich nicht, gibt es irgendwie ein issue, oder was wo man sich die Diskussion mal durchlesen kann?

**Comment by aschempp** [comment]
Irgendwo hier im Issue-Tracker, müsstest du mal suchen (auf deutsch und englisch probieren).

**Comment by garyee** [comment]
Okay Problem erfasst. Aber wäre es da nicht besser read-only gleich aus der DCA Definition rauszunehmen? Weil im Endeffekt macht das dann ja genau dasselbe wie disabled.

**Comment by leofeyer** [comment]
Nein, denn das eine setzt das `readonly`-Attribut und das andere das `disabled`-Attribut.

**Comment by garyee** [comment]
Wobei bei Contao beides aufs selbe rauskommt von der Verarbeitung der Daten her, aber egal.
Es muss nur damit gerechnet werden das ich nicht der letzte bin der auf die Idee kommt das readonly nicht das selbe Ergebniss liefert wie readonly das eigentlich tut... 

zwei kurze Ideen:
- das so in die Doku schreiben (Handbuch) um solchen Fragen wie meiner vorzubeugen
- Man könnte doch den Wert der rausgeschrieben wird, persistieren um dann den Input zu ignorieren und dann den Wert für das Feld einfach wieder (aus der Session) zu nehmen.

**Comment by garyee** [comment]
Okay das mit dem persitieren ist nicht sinnvoll ich weiß. Aber es wäre irgendwie gut wenn wenigstens der Save_Callback des Feldes gerufen werden könnte, weil eigentlich ja ein Wert gespeichert werden sollte, da könnte an der Stelle einfach der aus der Datenbank reingschoben werden.

**Comment by Toflar** [comment]
:-1: Das wäre ein unsinniger BC Break. So wie's ist passt's. Alternative Verhaltensweisen kann man sich mit einem eigenen Widget dazuprogrammieren.

**Comment by garyee** [comment]
okay.
