### ISSUE TITLE
Formular-Generator, Feldtyp „Überschrift“: Bezeichnung irreführend

### ISSUE THREAD

**Issue by michelbalzer** [contao/core#7767]
Ein „Fehler“ der mir seit der 2.11 oder auch schon 2.10 entgegen läuft:

Die Bezeichnung des Feldtyps „Überschrift“ im Formulargenerator ist irreführend, da ich hier einen WYSIWIG-Editor aufrufe und nicht nur ein einzelndes Überschriften-Feld wie es in Artikeln der Fall ist.  Besser wäre wohl „Freitext“ oder sowas in der Art, um nicht in Konkurrenz zum Textfeld zu treten.

Davon ab ist das Feld doppelt gemoppelt mit dem Erklärungsfeld, nur die Ausgabe im Frontend unterscheidet sich durch eine CSS-Klasse. Aber aus Abwärtskompatibilitätsgrunden wird es wohl dabei bleiben müssen.

**Comment by leofeyer** [comment]
Ja, das würde ich auch gerne mal konsolidieren. Geht vielleicht sogar ohne BC-Break.

**Comment by aschempp** [comment]
Wenn wir dem Erklärungs-Feld ein Property für die CSS-Klasse geben, könnte man das sehr einfach auflösen.

**Comment by leofeyer** [comment]
Ich habe das Feld "Überschrift" in contao/core-bundle@7028dbf1d479b69e0240fb5e92ed435cd69241b5 entfernt.

**Comment by aschempp** [comment]
Bitte dann das Feld CSS-Klasse für das Textfeld ermöglichen…

**Comment by leofeyer** [comment]
Wozu?

**Comment by aschempp** [comment]
Um die Erklärung verschieden zu stylen?

**Comment by leofeyer** [comment]
Du kannst doch im TinyMCE eine CSS-Klasse vergeben, oder?

**Comment by frontendschlampe** [comment]
Über den Tiny könnte man das schon machen, aber das ist eher *bähhh - außerdem beschneidest du den Tiny immer weiter in seinen Funktionen und jetzt sollen wir doch wieder CSS-Klassen darüber vergeben - das ist nicht so ganz konsistent! ;-)

**Comment by leofeyer** [comment]
Ich hab das Feld für die CSS-Klasse hinzugefügt, aber ich bin mir nicht sicher, ob die CSS-Klasse **anstatt** der CSS-Klasse `explanation` oder **zusätzlich** dazu eingefügt werden soll?

**Comment by aschempp** [comment]
Eher **anstatt**, weil damit liesse sich sehr einfach auch die bisherige headline wieder herstellen.

**Comment by frontendschlampe** [comment]
zusätzlich - wird ja bisher alles zusätzlich dazu gemacht, also warum sollte es hier auf einmal anstatt sein?

**Comment by frontendschlampe** [comment]
des weiteren bleibt es ja eine ```explanation``` - die aber etwas anders formatiert sein könnte ...

**Comment by leofeyer** [comment]
Hinzugefügt in 3c8239b3b4c75ed893a4990a50d57ddfa116d3eb.
