### ISSUE TITLE
"Easy Company" template compatible with Contao 3.4.4?

### ISSUE THREAD

**Issue by fbuchinger** [contao/core#7768]
Hi,

I wanted to install the "Easy Company" template in Contao 3.4.4, but install.php gives me the error " error - the structure of the database and the template file are not compatible with the contao version". Is this template really incompatible with Contao 3.4.4 or do I have to tweak some settings?

**Comment by leofeyer** [comment]
This is the Contao core issue tracker. You can contact the theme designer here:

https://themes.contao.org/de/support.html?t=easy-company-v-ii
