### ISSUE TITLE
Nachrichtenarchiv-Bearbeitungslink (Stift-Icon) obwohl keine Rechte 

### ISSUE THREAD

**Issue by Hendriks** [contao/core#7770]
Kleiner Schönheitsfehler:

Wenn ein Benutzer keinerlei Rechte zur Bearbeitung eines Nachrichtenarchivs hat, so erscheint in der BE-Nachrichtenübersicht oben im Archiv-Header trotzdem der "Stift"; und führt dann etwas unschön zu einer leeren Bearbeitungsmaske... In der Archivübersicht zu Anfang ist das entspr. Bearbeitungssymbol hingegen ordnungsgemäß inaktiv.

Auch der "Mehrere bearbeiten"-Link sollte überall ggf. besser deaktiviert / ausgeblendet werden, insofern es keine Einträge gibt oder der User keinerlei Rechte zur Bearbeitung hat.

![bildschirmfoto 2015-04-20 um 09 16 25](https://cloud.githubusercontent.com/assets/1499091/7225443/deaf2874-e73e-11e4-98d5-acba95117dc0.png)
![bildschirmfoto 2015-04-20 um 09 16 53](https://cloud.githubusercontent.com/assets/1499091/7225444/dec061ca-e73e-11e4-94e9-72730874af48.png)
![bildschirmfoto 2015-04-20 um 09 17 34](https://cloud.githubusercontent.com/assets/1499091/7225446/df7da460-e73e-11e4-9b91-a2e8e90fcf49.png)
![bildschirmfoto 2015-04-20 um 09 18 15](https://cloud.githubusercontent.com/assets/1499091/7225448/dfedbcbe-e73e-11e4-8c2d-ad9b025e599e.png)

**Comment by aschempp** [comment]
Welche Contao-Version verwendest du? Lässt sich das in der Demo reproduzieren?

**Comment by Hendriks** [comment]
Hi! Ich verwende die aktuelle 3.4.5. Sollte eigentlich einfach zu reproduzieren sein..

**Comment by Toflar** [comment]
Das wäre dann deine Aufgabe :)

**Comment by Hendriks** [comment]
Juhuuu, ne Aufgabe! ;-) ...und ja, ist in der Demo genauso!

**Comment by leofeyer** [comment]
Ich könnte schwören, dass wir das Problem schon mal behoben haben. Aber offenbar nicht :)

**Comment by Hendriks** [comment]
Ja ja... Redundanz hat kurze Beine, ist wie Unkraut und kommt immer wieder... ;-)

**Comment by leofeyer** [comment]
Behoben in 3967ecd688f47e7fb0e9fe9da2273c2ebc1c14b7.
