### ISSUE TITLE
Data attribute values can not be assigned to Widgets

### ISSUE THREAD

**Issue by fatcrobat** [contao/core#7772]
https://github.com/contao/core/blob/master/system/modules/core/library/Contao/Widget.php#L334-337

Is there any reason for this behavior? In my case i want to add data-toggle="tooltip" to an widget, but the result is data-toggle="data-toggle".

Thanks

**Comment by aschempp** [comment]
Looks like a bug to me (introduced in #7095)

**Comment by leofeyer** [comment]
Line 336 should be `$this->arrAttributes[$strKey] = $varValue;`.

**Comment by leofeyer** [comment]
Fixed in 8a2544339f6e195541c2047bae87e8e9c1fc1c0b.
