### ISSUE TITLE
Small typo

### ISSUE THREAD

**Issue by lionel-m** [contao/core#7773]
be found in **in** the

> ... The script execution stopped, because something does not work properly. The actual error message is hidden by this notice for security reasons and can be found in in the <code>app/logs/error.log</code> file (see above). ...

v4_0-core-exception

**Comment by bytehead** [comment]
The C4 (core-bundle) issue tracker is here: https://github.com/contao/core-bundle/issues

**Comment by lionel-m** [comment]
Thanks for the info

**Comment by leofeyer** [comment]
In this case, the error was already in version 3 :)

Fixed in 3b35b917706fe6f3047c5b9ef7f9ef18c9b242d4.
