### ISSUE TITLE
Decrease the input fields to add images

### ISSUE THREAD

**Issue by leofeyer** [contao/core#7774]
As discussed on Mumble on April 21st, we want to remove unnecessary input fields when adding images. Candidates are "Image margin" and "title". Instead, we want to add a field "use meta information", which makes the element use the meta title as `alt` attribute and the meta caption as image caption.

**Comment by MacKP** [comment]
Maybe Important -> https://github.com/contao/core/issues/3494

**Comment by Ruudt** [comment]
You could reverse that logic and keep all meta fields as subpalette of checkbox "override meta information"? Both clean and flexible.

**Comment by leofeyer** [comment]
No, we cannot. We have discussed this idea but it is not possible to have sub-palettes in a sub-palette and "add an image" is a sub-palette already.

**Comment by leofeyer** [comment]
Now that Contao 4.3 supports nested sub-palettes, we could go for something like this:

<img width="894" alt="" src="https://cloud.githubusercontent.com/assets/1192057/22152548/c27e90d4-df23-11e6-8b91-62fe06e9b93e.png">

This will use the image meta data from the file manager for title, alternate text, link and caption and only if you enable "overwrite meta data", the other input fields will show up:

<img width="895" alt="" src="https://cloud.githubusercontent.com/assets/1192057/22152555/c7aa69de-df23-11e6-84c4-692281eddef2.png">

However, the "full-size view/new window" option might be needed independently from the "overwrite meta data" option and so might the "image margin" option (which should be dropped entirely IMO).

**Comment by leofeyer** [comment]
@contao/developers /cc

**Comment by aschempp** [comment]
How would you migrate existing data?

**Comment by asaage** [comment]
From my experience a link to *Edit meta data* would be very useful too.
currently you can *change selection* then switch from *file-picker* to *file-manager* and then find the file again and then *edit* which is rather cumbersome.

**Comment by leofeyer** [comment]
> How would you migrate existing data?

If any of the fields has a value, check the "overwrite meta data" option during the database update.

**Comment by aschempp** [comment]
One of the problems I see is it does no longer suggest the user to enter anything, even though the file metadata is empty in most of the cases (at least for my clients).

**Comment by leofeyer** [comment]
As discussed in Mumble on January 26th, we want to implement this as shown above; although the "Full size" and "Image margin" fields are not supposed to be in the sub-sub-palette.

**Comment by zonky2** [comment]
It´s very strange! and in my mind a bug...

I have the meta attributes at any different languages and if I save e.g. the CE Picture with backand language german, I have the german words as default... 

The template shows only the CE input, but not the file database as fallback - if I delete the default text strings, I see at frontend nothing :-(

How can I build a multi language site!?!

**Comment by asaage** [comment]
@zonky2 did you probably overrwrite metadata with blank values?

multi language could realy be an issue with this suggestion thats why i again would recommend a direct link to edit single-file metadata of the chosen file.

**Comment by zonky2** [comment]
> @zonky2 did you probably overrwrite metadata with blank values?

yes, I tested this... with blank values, we havn´t a fallback with the database data :-(

**Comment by fritzmg** [comment]
> multi language could realy be an issue with this suggestion

This suggestion would fix that, would it not? If you want the meta data from the database (in its correct langaguage), you simply do not enable __Overwrite meta data__.

**Comment by fritzmg** [comment]
> yes, I tested this... with blank values, we havn´t a fallback with the database data :-(

At present, there is none.

**Comment by Aybee** [comment]
> @asaage ...thats why i again would recommend a direct link to edit single-file metadata of the chosen file.

IMHO that's a different approach. These are all tl_content fields and are intended as override for the tl_files data. Tl_content fields never were language specific till now. Saving data do this tl_content data set should not touch the data in tl_files.

But a pop up to directly edit the tl_files data IMHO also would be nice:

**Comment by asaage** [comment]
a pop up / lightbox whatever you would like to call it is exactly what i mean.

![image](https://cloud.githubusercontent.com/assets/4138336/23705211/1768a51c-0409-11e7-8cf9-16d29d76bfd7.png)


![image](https://cloud.githubusercontent.com/assets/4138336/23705252/424f0b68-0409-11e7-9904-7b44e201f561.png)

**Comment by Aybee** [comment]
Yes, but this wouldn't be an override but a shortcut to tl_files.

**Comment by asaage** [comment]
shortcut to tl_files -> that's true.

override could still be implemented in the subpalette if needed like @leofeyer suggested https://github.com/contao/core/issues/7774#issuecomment-274083065

and if over write is checked but title/caption/alt is left blank there is also no need for a fallback mechanism IMHO

**Comment by Aybee** [comment]
> and if over write is checked but title/caption/alt is left blank there is also no need for a fallback mechanism 

I agree. But a fallback, or call it switch, should be done in templates "if override than tl_content fields else tl_files meta". So you can "disable" an output at all while leaving the tl_content fields empty.

**Comment by leofeyer** [comment]
See contao/core-bundle#807.
