### ISSUE TITLE
[3.5.0b1] Mehrere bearbeiten und Kopieren von CSS-Formatdefinitionen funktioniert nicht

### ISSUE THREAD

**Issue by Samson1964** [contao/core#7776]
Nach der Auswahl mehrerer Formatdefinitionen im CSS-Modul und dem Klick auf "Kopieren" erscheinen keine Einfügelinks.

![zwischenablage01](https://cloud.githubusercontent.com/assets/4542730/7290851/48e490b4-e986-11e4-80a8-3fd81df1dc82.jpg)

**Comment by Samson1964** [comment]
Ist mir gerade aufgefallen: Das Kopieren funktioniert an sich. Allerdings wird SOFORT und ohne Rückfrage kopiert und in der aktuellen Ansicht eingefügt.

**Comment by leofeyer** [comment]
Was genau ist das Problem?

**Comment by Samson1964** [comment]
Themes -> Stylesheets -> CSS auswählen.
In der Formateübersicht auf "Mehrere bearbeiten" klicken und mehrere Formate auswählen. Danach auf "Kopieren" klicken. Im Gegensatz zu früher und zum allgemein üblichen Verhalten, erfolgt keine Abfrage, wohin die markierten Formate kopiert werden sollen. Die markierten Formate werden sofort in die aktuelle Ansicht kopiert!

**Comment by leofeyer** [comment]
Behoben in 64647bbce51269925090f854e60a1997cc2d13fe.
