### ISSUE TITLE
Plötzliches Logout Safari & Firefox (manchmal)

### ISSUE THREAD

**Issue by jenda77** [contao/core#7777]
Hallo Leo, 

dieses Problem habe ich ständig mit den letzten Versionen von Safari (OS X Yosemite). Ich denke, dass Contao etwas verlangt, was von Safari verweigert wird? Leider beeinträchtigt das die Arbeit sehr. Könntet ihr euch das bitte noch einmal anschauen, woran das liegen kann? 

Dieses Problem wurde schon einmal hier diskutiert. Anscheinend gibt es aber immer noch keine Lösung - Wechsel zu einem anderen Browser ist sicherlich eine der Lösungen. Aber für mich gewährleistet es nicht, dass Contao tadellos in Safari benutzt werden kann. 

Siehe https://github.com/contao/core/issues/3263

**Comment by frontendschlampe** [comment]
Bei mir tritt es sporadisch im Safari auf. Eine Seite die gestern noch problemlos ging, funktioniert heute nicht mehr. Irgendwann später aber geht's dann wieder. Ich konnte leider den Fehler noch nicht finden. Manchmal hilft es, die Cookies und Cache vom Browser zu löschen, manchmal nicht. Das BE in einem anderen Browser geöffnet, funzt ohne Probleme. Irgendwie strange ...

**Comment by leofeyer** [comment]
Ich kann das hier nicht reproduzieren. Was genau macht ihr, wenn der Fehler auftritt? Und welche Contao-Version und welche Extensions habt ihr installiert?

**Comment by jenda77** [comment]
Das tritt bei mir sehr oft auf - vor allem, wenn ich die Templates bearbeite. Ich habe alles von Rocksolid installiert. Contao 3.4.5 und dessen Installation liegt in einem Unterordner, um an der Neuentwicklung separat von der Hauptdomain zu arbeiten.

**Comment by bytehead** [comment]
Ich habe gerade auch so ein komisches Verhalten. Logge mich ein, werde aber umgehend wieder ausgeloggt. Falls ich mal drin bin, muss ich mich nach dem nächsten Klick erneut einloggen. Im Anhang noch ein Screenshot der `tl_log`-Tabelle. Interessant ist da die 10er-IP vom internen Netz des Hosters. Ich frage mich, ob da irgendwie noch ein Cache-Proxy dazwischenfunkt und so die Session immer wieder verloren geht. Kann das sein?

Browser: Chrome 42.0.2311.90
Contao: 3.2.20

![bildschirmfoto 2015-04-30 um 16 25 18](https://cloud.githubusercontent.com/assets/754921/7414979/5915b064-ef56-11e4-929c-640fdaba534a.png)

**Comment by leofeyer** [comment]
Sieht tatsächlich danach aus. Aktivier mal die Einstellung "Disable IP check" und versuch es damit nochmal.

**Comment by bytehead** [comment]
Scheint ein möglicher Weg zu sein. Auch wenn ich ungern solche Prüfungen abschalte.
Der verwendete Hoster ist eh nicht so das Gelbe vom Ei, für temporär kann so wenigstens bis zum Umzug gearbeitet werden. Danke für den Tipp!

**Comment by jenda77** [comment]
Ich würde auch sagen, dass es auch mit dem WLAN-Router zusammenhängen könnte (gleiches Verhalten bei O2 und Kabeldeutschland). Allerdings wäre es schön, wenn man da eine Standardlösung hätte. 


Jan

30. 4. 2015 v 17:11, David Greminger <notifications@github.com>:

Scheint ein möglicher Weg zu sein. Auch wenn ich ungern solche Prüfungen abschalte.
Der verwendete Hoster ist eh nicht so das Gelbe vom Ei, für temporär kann so wenigstens bis zum Umzug gearbeitet werden. Danke für den Tipp!

**Comment by leofeyer** [comment]
Contao hat dafür bereits eine Standardlösung, nämlich die Einstellung "Disable IP check", die genau für diese Fälle hinzugefügt wurde.
