### ISSUE TITLE
[3.5.0b1] Bildgröße in Text- und Bildelementen läßt sich bei Voreinstellung nicht anpassen

### ISSUE THREAD

**Issue by Samson1964** [contao/core#7778]
Standardmäßig läßt sich bei Bild- und Textelementen keine Bildgröße einstellen. Nachdem ich erst dachte, das hätte mit den neuen Bildgrößen-Varianten des Themes zu tun, fiel mir auf, daß das Feld wo sonst standardmäßig "Proportional" steht, keine Auswahl enthält. Siehe Bildschirmfoto:

![zwischenablage01](https://cloud.githubusercontent.com/assets/4542730/7332222/b1ec6d56-eb35-11e4-9f48-e00d4c807ae2.jpg)

Erst nach erfolgter Auswahl läßt sich eine Bildgröße einstellen. Wegen der Benutzerfreundlichkeit sollte es doch bitte bei dieser Vorauswahl von "Proportional" bleiben. Da stolpern Profis drüber, die bisher was anderes gewohnt waren und für Anfänger scheinen Bildgrößeneinstellungen grundsätzlich nicht möglich zu sein.

**Comment by xchs** [comment]
Duplikat von #7565
