### ISSUE TITLE
Not loading country version for tinyMCE4 languages

### ISSUE THREAD

**Issue by aschempp** [contao/core#7779]
https://github.com/contao/core/blob/master/system/modules/core/classes/Backend.php#L94

The `$lang` in this case would be written `de-DE` due to our `tl_page.language` format and should be converted to find the file.

**Comment by aschempp** [comment]
Same problem in https://github.com/contao/core/blob/master/system/modules/core/library/Contao/Controller.php#L548

**Comment by leofeyer** [comment]
Fixed in 3939790614470d3223bfba4dc5a0ab9d12c026b7.
