### ISSUE TITLE
Contao dies when trying to cache a file with shorttags

### ISSUE THREAD

**Issue by Paratron** [contao/core#7782]
Hey,
I just had a very weird error in contao that made it render only blank pages in the BE when turning the system cache on.

It turns out all the trouble (no errors, nothing) happend just because ONE file of a module used a PHP short open tag (<? instead of <?php).

The caching ignored the file because [this method](https://github.com/contao/core/blob/master/system/modules/core/library/Contao/System.php#L637) just looks for long open tags. Thanks to @netzmacht for the find.

**Comment by leofeyer** [comment]
Contao does not support short open tags (except for the built in `<?=` tag).

**Comment by Paratron** [comment]
Meiner Meinung nach ein wenig nach dem "Probleme die ich ignoriere, existieren nicht"-Prinzip, aber gut. Ich würde kein Produkt entwickeln wollen, dass ohne einen Mucks und Fehler einfach den Geist aufgibt, wenn Code von Dritten - von dem das Produkt lebt - ein Problem verursacht. Aber dies ist ja nicht mein Projekt.

**Comment by aschempp** [comment]
https://nealpoole.com/blog/2010/07/php-security-tip-beware-the-opening-tags/

> PHP can be configured to accept or ignore these tags using the short_open_tag directive in php.ini. As a result, they’re considered non-portable; if you’re writing code that’s intended to be used by others or that may be used in environments where you can’t control PHP settings, you’re encouraged to forgo short tags in favor of standard tags.

http://www.hacksparrow.com/why-not-to-use-php-short-opening-tags.html

> > Should you use PHP short opening tags?

> The short answer is "NO, you should not".

http://www.askapache.com/php/shorthand-short_open_tag.html

> **Important** Never use shorthand PHP tags.

https://perishablepress.com/php-short-open-tag/

> Using short open tags when they are disabled produces no error or warning message of any kind. It simply fails, outputting your code directly and silently.

Das Problem liegt an der Extension, nicht an Contao.

**Comment by Paratron** [comment]
Mmn liegt das Problem sehr wohl bei Contao, denn Contao werkelt am PHP Code herum. Warum auch immer. Die reine Tatsache, dass PHP selbst die short open tags unterstützt macht eigentlich jede Diskussion darüber, ob Contao diese Erfassen können sollte überflüssig. Immerhin will der Cache Mechanismus mit PHP arbeiten.

Mir ist bewusst, dass Short Open Tags nicht verwendet werden sollten. Aber - wieder meiner Meinung nach - sollte aufgrund der fehlerhaften Verwendung eines solchen Tags nicht das ganze Produkt einfach sang und klanglos den Geist aufgeben. Wäre mir als Entwickler von Contao ein wenig peinlich.

Dann reibe ich dem User beim Aufbau des Cache lieber ne Warnung unter die Nase das eine PHP Datei, welche mit einem Short-Open-Tag begonnen hat ignoriert wurde und es deshalb vermutlich zu Problemen kommen kann. Oder baue etwas ein, das die Ausgabe einer weißen Seite bei aktiven Cache verhindert - oder einfach IRGENDWAS. Einfach zu sagen: interessiert nicht, ist irgendwie schwach.
