### ISSUE TITLE
Validator::isEmail()

### ISSUE THREAD

**Issue by Mynyx** [contao/core#7783]
Die Funktion Validator::isEmail erkennt E-Mail-Adressen, die zwischen einer "Subdomain" und der Domain die Zeichenfolgen ``.-`` oder ``..`` enthalten nicht als ungültig (beispielsweise test@sub.-example.com und test@sub..example.com).

Weiterhin werden E-Mail-Adressen, die mit ``-`` beginnen fälschlich als ungültig erkannt (beispielsweise -test@example.com).

**Comment by Mynyx** [comment]
Sind hierzu noch weitere Beispiele notwendig?

**Comment by discordier** [comment]
`sub.-example.com` ist eigentlich laut [rfc2181](https://tools.ietf.org/html/rfc2181), [rfc822 6.1](https://tools.ietf.org/html/rfc822#section-6.1) ein legaler host name.
Dass jedoch NICs einen underscore/hyphen nicht als erstes Zeichen erlauben geht meiner Meinung nach yber die Definition einer "validen" Adresse hinaus. Ansonsten myssten wir ja beim check einen test "RCPT TO"-Anruf an den zustaendigen Mailserver machen, welcher dann sagt ob er die Adresse kennt oder nicht.

Mit deinem zweiten Beispiel, direkt aufeinander folgende Punkte, hast du hingegen recht, das ist falsch und muss somit als ungyltig erkannt werden.
Dein drittes Beispiel ist ebenfalls eine Fehlerkennung, ein hypen als Mailbox ist vollkommen legal  (siehe hierzu ebenfalls wieder [rfc822 6.1](https://tools.ietf.org/html/rfc822#section-6.1).

**Comment by leofeyer** [comment]
Machst Du einen PR mit den notwendigen Änderungen?

**Comment by discordier** [comment]
After further reading, I came to the conclusion that it definately is not worth the hassle to implement own checks which will validate against:
- http://tools.ietf.org/html/rfc5321
- http://tools.ietf.org/html/rfc5322
- http://tools.ietf.org/html/rfc4291
- http://tools.ietf.org/html/rfc1123#section-2.1
- http://tools.ietf.org/html/rfc2821
- http://tools.ietf.org/html/rfc2822
- http://tools.ietf.org/html/rfc3696

Therefore I suggest we will use the php embedded method `filter_var` which should be just "good enough.

If we do not want to, there is https://code.google.com/p/isemail/ which tries to cover almost any valid address.

**Comment by leofeyer** [comment]
I'm closing this ticket in favor of https://github.com/contao/core-bundle/pull/313 then.
