### ISSUE TITLE
[Warnung] "the specified value 't' is not a valid email address." von mootools

### ISSUE THREAD

**Issue by Matze202** [contao/core#7784]
Hiho @all,

mein Google-Chrome Version 42.0.2311.90 m (64-bit) spuckte mit Version 3.4.5 von Contao folgende Warnung aus:
"the specified value 't' is not a valid email address."

Dies bezieht sich auf das assets/mootools, wie ich mit Google folgendes gefunden habe:
http://stackoverflow.com/questions/29074591/core-1-5-1-throws-warning-on-ie-input-type-email-check-after-updating-to-latest

Dies habe ich bei mir geändert und die Warnung ist weg. (Fürs Backend muss das in einer 2. Datei geändert werden.)

Nun die Frage:
Kann diese Änderung andere Probleme im Contao mit sich bringen, welche mir nicht sofort aufgefallen sind und ändert ihr das mit einem der nächsten Updates oder müsst ihr auf die offiziellen Updates von mootools warten?

Gruß Matze202.

**Comment by dmitrisgit** [comment]
Hey guys,
The warning generated by the latest MooTools lib is still there:
The specified value 't' is not a valid email address.

You can see it on http://matter.vc/ in console

**Comment by leofeyer** [comment]
Fixed in a3954976c4ed09889b196aa6fc304cb969b6f395.
