### ISSUE TITLE
E-Mail-Betreff vom selbstgeneriertem Formular auch generieren

### ISSUE THREAD

**Issue by Matze202** [contao/core#7786]
Hiho @all,

ich habe in meiner Recherche lieder immer nur gefunden, dass es nicht möglich sei, den Inhalt vom selbst erzeugten Betreff-Feld, als Insert-Tag im Betreff-Feld der E-Mail einzutragen und somit zu generieren.

Ich nutze die Version 3.4.5 von Contao und habe schon einiges ausprobiert, aber leider nicht zum laufen bekommen.

Ich hoffe, dass dies von euch irgendwann in nächster Zeit mit eingeführt werden könnte (falls es nicht schon eingeführt ist), damit man auch am Betreff erkennen kann, worum es in der E-Mail geht und somit eventuell über ein Select-Menü noch Themenbereiche mit administrieren kann, um dass man bei hohem E-Mail aufkommen, auch diese eingehenden E-Mails schon leichter filtern kann.

Dies ist mir wichtig für einen Bekannten, der selbst nicht viel im Backend unterwegs sein wird, sondern alles per E-Mail erledigen möchte.

MfG. Matze202.

**Comment by aschempp** [comment]
https://github.com/terminal42/contao-notification_center

**Comment by Matze202** [comment]
Danke für den Link, aber eigentlich habe ich mir auch Informationen über die Zukunft des Insert-Tag im Bezug auf das Betreff-Feld beim E-Mail versenden erhofft.
Ich habe das mir aber dennoch angeschaut, installiert und bereits etwas ausgetestet, aber leider funktioniert es bei mir noch nicht, denn ich weiß nicht, wo das unter "Sending a notification" geändert werden soll.

Ich kann leider kaum Englisch, daher kann ich schlecht auf englisch suchen. Die Translater-Tools verwende ich zwar schon sehr häufig, aber die helfen leider oft auch nicht weiter.

Im Systemlog habe ich folgendes gefunden:
ID:	52
Datum:	2015-04-29 11:38
Ursprung:	Frontend
Kategorie:	ERROR
Benutzer:	
Details:	Could not find any messages for notification ID 2
Funktion:	NotificationCenter\Model\Notification::send
IP-Adresse:	XXX.XXX.XXX.XXX
Browser:	Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2311.90 Safari/537.36

Was mir aber leider auch fast nichts sagt, außer das es mit der Erweiterung zu tun hat, weshalb ich es ohne Erweiterungen versuchen wollte.

**Comment by aschempp** [comment]
Dazu solltest du dich ans Community Forum wenden (https://community.contao.org)

**Comment by Matze202** [comment]
Danke für die Info, da roll ich das dort nochmal auf.

Eigentlich habe ich mich in einer ähnlichen Angelegenheit von https://community.contao.org/ hier her schicken lassen, weil ich hier die Fragen beantwortet bekommen sollte.

Sonst wäre ich nie auf die Idee gekommen, hier rein zu posten, weil ich bei github.com noch nie durchgesehen habe und mich auch jetzt noch schwer tue.

Für welche Angelegenheiten seit ihr nun hier Zuständig und für was sind die von https://community.contao.org/ zuständig?

**Comment by aschempp** [comment]
Forum = Fragen
GitHub = Bugs und Features für Contao Core

**Comment by Matze202** [comment]
Features bezieht sich das nur auf Erweiterungen oder auch auf das eigentliche Contao?

**Comment by Zeromax** [comment]
Nur auf Contao und die core Erweiterungen. Bei der jeweiligen Erweiterung musst du den Entwickler oder hier auf Github das Repo suchen

**Comment by Matze202** [comment]
bevor ich mich hier im github weiter rum quäle, werde ich alles im Contao-Forum fragen, bevor ich mich hier wieder rein verirre (sorry, aber das hin und her finde ich bissel umständlich für Neulinge)

Ich hoffe, dass mein folgender Post hier wenigstens richtig ist:
https://github.com/contao/core/issues/7784

**Comment by Zeromax** [comment]
@Matte202 keiner will dich verwirren ;). Aber du hast recht, die ganzen verschiedenen Kanäle und dann die Frage: Wo darf ich Probleme berichten ist nicht immer leicht zu durchschauen.

Viel erfolg noch ;).
