### ISSUE TITLE
URL-Prüfung bei externen Weiterleitungen 

### ISSUE THREAD

**Issue by bekanntmacher** [contao/core#7790]
Beim Seitentyp externe Weiterleitung ist das erlaubte Zeichenspektrum zu eng gefasst. URL's wie folgende sind leider nicht möglich:
```
https://www.google.ch/maps/place/Wirtschaftsschule+KV+Chur/@46.849412,9.530387,17z/data=!3m1!4b1!4m2!3m1!1s0x4784c770fceba123:0x56d2793eb66259ad?hl=de
```

**Comment by aschempp** [comment]
Die Zeichen müssen encodiert werden, dann funktioniert die URL.

**Comment by fritzmg** [comment]
URL encoding sollte eigentlich nicht notwendig sein. Darüberhinaus lässt sich die von @bekanntmacher gepostete URL in der Contao Demo problemlos bei anderen URL Feldern eintragen, im Link target field einer External redirect page jedoch nicht.

**Comment by Samson1964** [comment]
Das kenne ich auch irgendwie von anderen Feldern, wo partout keine solche URL einzutragen war. Ich wurde damals auch auf die eigene Encodierung verwiesen. Sowas muß man dann mal normalsterblichen Benutzern erklären...

**Comment by bekanntmacher** [comment]
Was spricht dagegen, die URL cotaoseitig nicht zu prüfen?

**Comment by fritzmg** [comment]
Entweder sollte die URL überall oder nirgends geprüft werden. Derzeit ist das nicht der Fall. Außerdem müssen, im Fall der externen Weiterleitung zB, die Zeichen nicht URL encodet sein, oder?

**Comment by leofeyer** [comment]
Das eigentliche Problem ist, dass der reguläre Ausdruck in `Validator::isValidUrl()` nicht ganz mit dem RFC 3986 übereingestimmt hat. Es fehlten die Zeichen `!`, `$` und `*`.

Behoben in contao/core-bundle@5a22440d9c2acd659f1a53ec282b4f099025b1cc, ich lasse das Ticket aber noch offen, damit wir daran denken, den Fix in die 3.5 zu portieren.

**Comment by leofeyer** [comment]
Portiert in 4e263eaf4257ed0f8f998b5ab162c501e53d8cbd.
