### ISSUE TITLE
File picker : button "Apply" doesn't work

### ISSUE THREAD

**Issue by lionel-m** [contao/core#7792]
For example the content element image: "Source files" -> "Change selection" -> "Apply".
Click on the button has no effect.

Contao 3.5 RC1

**Comment by leofeyer** [comment]
I have noticed this as well today and I have already fixed it in 718910d82c98663e51d1b92c94fbe48c6522ecd1.

**Comment by marebe1602** [comment]
aha, dann liegt's also nicht an mir :)

**Comment by BugBuster1701** [comment]
Im Branch release/3.5.0 ist es behoben, funktioniert bei mir.
