### ISSUE TITLE
Module change password - translation

### ISSUE THREAD

**Issue by lionel-m** [contao/core#7793]
The sentence "[The old password is not correct](https://github.com/contao/core/blob/develop/system/modules/core/modules/ModuleChangePassword.php#L154)" is not translatable.

Contao 3.5 RC1

**Comment by leofeyer** [comment]
Good find. I forgot to change it.

**Comment by leofeyer** [comment]
Fixed in 3267b8d39ef1a4d6ab1bb0147afdef27ec019ab7.
