### ISSUE TITLE
Add new calendar events template "event_teaser_image"

### ISSUE THREAD

**Issue by marebe1602** [contao/core#7806]
Community discussion:
https://community.contao.org/de/showthread.php?35327-Eventteaser-mit-Bild-ausgeben

in contrast to the news templates, there is no event template, displaying the singleSRC image of the event. The admin has to insert the image code manually.
To avoid conflicts on update of existing installations, a new template should be created, which looks the same as event_teaser, but has the image code, too.

**Comment by leofeyer** [comment]
See #4918 and #5146.
