### ISSUE TITLE
[3.5.0 RC1] - Es ist nicht möglich Bilder in Galerien- oder Text-Elemente einzubauen

### ISSUE THREAD

**Issue by tglassner** [contao/core#7807]
Firebug meldet folgenden Fehler:
"Uncaught TypeError: Cannot read property 'getElementsByTagName' of null"
Siehe auch beigefügte Screenshots.

Gerade auch noch einmal mit Version 3.4.5 gegen getestet. Dort funktioniert es einwandfrei.

![bildschirmfoto 2015-05-05 um 20 50 38](https://cloud.githubusercontent.com/assets/6862902/7480821/a109dfa8-f36b-11e4-912d-6ffd5702bd00.png)
![bildschirmfoto 2015-05-05 um 20 50 57](https://cloud.githubusercontent.com/assets/6862902/7480826/a918bd7c-f36b-11e4-9c6f-c6cc5b63e3b6.png)
![bildschirmfoto 2015-05-05 um 20 51 18](https://cloud.githubusercontent.com/assets/6862902/7480829/ad8c8a8c-f36b-11e4-849a-ca58e56b0e37.png)

**Comment by leofeyer** [comment]
Siehe #7792 und #7801.
