### ISSUE TITLE
[3.5.0-RC1] Templates Vergleichen Bezeichnungen vertauscht

### ISSUE THREAD

**Issue by Mynyx** [contao/core#7808]
Bei der Funktion Templates Vergleichen wird links vom Pfeil der Name des ausgewählten Templates (als Text) und rechts vom Pfeil der Name des Vergleichstemplates (als Auswahlmenü) angezeigt.
Diese Darstellung ist verkehrt, da das Vergleichtstemplate als Vergleichsgrundlage genutzt wird, es müsste also links vom Pfeil stehen.

**Comment by leofeyer** [comment]
Alternativ könnte man auch einfach den Pfeil umdrehen :)

**Comment by Mynyx** [comment]
Für die arabische Sprachversion wäre das vielleicht eine Lösung ;-)

**Comment by leofeyer** [comment]
Behoben in dca782c41c1615550477c57d7067807ba84e186b.
