### ISSUE TITLE
[3.5.0-RC1] Dateien auswählen

### ISSUE THREAD

**Issue by Wusch** [contao/core#7809]
Bei dem Modultyp Zufallsbild z.B. erhalte ich nach dem Auswählen eines Bildes und dem Klick auf Anwenden den folgenden Fehler (core.js:497):
```javascript
TypeError: null is not an object (evaluating 'a.document.getElementById("tl_listing").getElementsByTagName')
```

**Comment by leofeyer** [comment]
Siehe Siehe #7792, #7801 und #7807.
