### ISSUE TITLE
Update the assets (bugfix releases only)

### ISSUE THREAD

**Issue by Aybee** [contao/core#7811]
http://www.tinymce.com/download/download.php

**Comment by leofeyer** [comment]
The following assets are outdated and should be updated:

* https://highlightjs.org/
* https://jquery.com/download/
* http://mediaelementjs.com/
* https://github.com/aFarkas/respimage
* http://www.tinymce.com/download/download.php

**Comment by leofeyer** [comment]
All plugins have been updated.
