### ISSUE TITLE
ModulePersonalData ignores DCA encrypt

### ISSUE THREAD

**Issue by fjacobi** [contao/core#7815]
Source: https://community.contao.org/de/showthread.php?57012-Pers%F6nliche-Daten-Felder-verschl%FCsseln-nicht-im-Frontend

The personal data module uses DCA to render the form - currently it correctly decrypts the values, but it doesn't encrypt them during saving the personal data.

**Comment by leofeyer** [comment]
Fixed in 88660e3fb1f996cfba21efcf9aa8abc2eb2384c0.

**Comment by t-me** [comment]
Hello LeoFeyer,
I'm running Version 3.5.4 and on registration the DCA is not encrypting.

It is only on front end registration not on back-end.
On updating the profile (front-end) it is working fine only on registration it is not working.
