### ISSUE TITLE
[3.5.0-RC1] Backend CSS .tl_show td

### ISSUE THREAD

**Issue by Mynyx** [contao/core#7817]
Durch hinzufügen von ``vertical-align:top;`` und ``width:50%`` zu ``.tl_show td`` der Backend-CSS wird die Details-Ansicht einheitlich dargestellt.
Denn insbesondere wenn man mehrere Elemente zum manuellen Vergleich nebeneinander öffnet ist es irritierend, wenn die Spaltenbreiten stets variieren.

**Comment by leofeyer** [comment]
Der Vorteil von Tabellen ist doch gerade, dass die Breite variabel ist. Die linke Spalte braucht selten mehr als 20% der Breite, die rechte dafür je nach Tabelle sehr viel (z.B. `tl_undo`). Wozu sollten wir das künstlich einschränken?
