### ISSUE TITLE
[3.5.0-RC1] Mehrere bearbeiten > kopieren > keine Positionsmöglichkeit

### ISSUE THREAD

**Issue by swiss-netwalk** [contao/core#7821]
Wenn man z.b. in der Seitenstruktur oder bei den Artikeln "Mehrere bearbeiten" anklickt und dann verschiedene Artikel auswählt und "Kopieren" drückt, werden diese direkt kopiert und platziert und man hat keine Möglichkeit diese an einen gewünschten Platz zu kopieren. Man muss dann die kopierten Artikel an den jeweiligen Platz verschieben was kein grosser aber meiner Meinung nach, ein unnötiger Aufwand bedeutet.
PHP  5.4.38
MySQL-Version 	5.5.42-cll
Linux-System

Getestet auf verschiedenen Browsern FF, Chrome, IE 11

**Comment by leofeyer** [comment]
Siehe #7776.
