### ISSUE TITLE
[3.5.RC1] Weiterleitungsseiten nicht auswählbar

### ISSUE THREAD

**Issue by eS-IT** [contao/core#7822]
In einer neuen 3.5.RC1-Installation habe ich versucht eine Weiterleitungsseiten auswählen. Das Modal-Window öffnet sich, man kann eine Seite auswählen, aber beim Klick auf Speichern passiert nichts. In der Browserkonsole wird folgender Fehler angezeigt:
`TypeError: a.document.getElementById(...) is null   core.js:2:13928`

Contao: 3.5.RC1
Browser: Firefox 37.0.2 (33.0+build2-0ubuntu0.14.10.1)
Betriebssystem: Ubuntu 14.10

Vorgehen:
* Contao installieren
* Zwei Seiten anlegen
* Ein Template anlegen
* Ein Theme anlegen
* Ein Modul vom Typ Suchmaschiene anlgen
* In dem Modul versuchen eine Weiterleitungsseite zu wählen

**Comment by BugBuster1701** [comment]
Auch wenn man ein Image Element im Artikel anlegen will, das Bild im Modal Windows auswählt und auf Anwenden drückt, passiert nichts. Selbe Meldung in der Browserkonsole.
```
TypeError: a.document.getElementById(...) is null core.js:2:13928
...rn void alert(Contao.lang.picker);for(e=a.document.getElementById("tl_listing")....
-------------------------------------------^
```

**Comment by ciaobello** [comment]
Beim Zusätzlichen externen auswählen eines CSS (Dateien auswählen) passiert nichts. Kriege auch nur folgende Meldung in der Konsole.
TypeError: a.document.getElementById(...) is null 7bdd2d75b23e.js:23:13928

**Comment by BugBuster1701** [comment]
Das wird wohl der Filepicker generell sein der da spinnt.

**Comment by leofeyer** [comment]
Hast Du Contao über die `app_dev.php` aufgerufen?

**Comment by leofeyer** [comment]
Ach so, Contao 3.5 :D

**Comment by eS-IT** [comment]
Ich habe es noch einmal mit Chromium probiert. Das funktioniert auch nicht, ist also wohl keine Sache des Browsers. Chromium Version 41.0.2272.76 Ubuntu 14.10 (64-bit).

**Comment by ciaobello** [comment]
Nein scheint ein .js Problem zu sein ... Aufruf von Mootools .. Chromium zeigte mir "cann not call method" an.

**Comment by eS-IT** [comment]
Ich habe mal etwas weiter nach geforscht. Es wird mit `a.document.getElementById("tl_listing").getElementsByTagName("input")` auf ein Element mit der ID `tl_listing` zugegriffen. So ein Element gibt es aber nicht, das Element hat in meinem Fall die ID `jumpTo`. Wenn ich diese manuell in `tl_listing` ändere funktioniert es!

**Comment by leofeyer** [comment]
This has been fixed in 718910d82c98663e51d1b92c94fbe48c6522ecd1 already.
