### ISSUE TITLE
Fehler bei der Synchronisation in der Dateiverwaltung

### ISSUE THREAD

**Issue by syntaxys** [contao/core#7823]
Nach der Synchronisation werden Dateien als gelöscht erkannt, die noch unverändert im Dateisystem vorhanden und in Benutzung sind. Dementsprechend zerbrechen die Referenzen in den Artikeln und wenn man kein aktuelles Backup der DB zur Verfügung hat, steht eine Menge Arbeit an.

Status Quo bzgl. des Projekts:
* Upgrade von 2.11.12 auf 3.2.20 per LiveUpdate und kleineren manuellen Anpassungen, wie in den HowTo's beschrieben.
* Den Ordner *tl_files* hatte ich zuerst belassen, nach dem Fehler dann aber mit dem Update-Script die DB auf *files* geändert. Auch dann entsteht der Fehler.
* In der Theme-Konfiguration habe ich auch sämtlich zum Projekt gehörenden Ordner mit aufgenommen, das bringt jedoch keine Abhilfe.
* Die Synchronisation hatte seltsamerweise zuerst gut funktioniert, ich hatte sie mehrfach angewendet, nach dem ich den Datenbestand per *ftp* geändert hatte.

Gibt es die Möglichkeit eines *dry run*?

**Comment by leofeyer** [comment]
Am besten fragst Du diesbezüglich im [Forum](https://community.contao.org/de/) nach.
