### ISSUE TITLE
Login page with error message is cached in server cache

### ISSUE THREAD

**Issue by nkirstein** [contao/core#7824]
Tested in Contao 3.2.9, 3.4.4 (official demo) and 3.4.5

Contao will cache login pages with error messages if 
* the server cache is activated in the frontend configuration AND 
* a cache timeout of >0 is set in the page tree.

This can be reproduced in the Official Contao Demo as follows:
* In the backend, activate the server cache in the front end configuration settings
* Set a cache timeout of (e.g.) 60 minutes for the root page
* Log out of the backend and go to http://demo.contao.org/en/login.html
* Click on "login" without entering anything in the form. The page will reload with an error message displayed above the form.
* Now browse around in the Contao Demo, clear your browser cache if you like, and go back to the login page. The error message is still there. It even shows up if you open the page in another browser. So it's definitely in the server cache.

I don't know why this happens but it doesn't seem to be the intended behaviour as there is a line in `classes/FrontendTemplate.php` which looks like it's supposed to prevent this from happening:

```php
// Decide whether the page shall be cached
if (!isset($_GET['file']) && !isset($_GET['token']) && empty($_POST) && !BE_USER_LOGGED_IN && !FE_USER_LOGGED_IN && !$_SESSION['DISABLE_CACHE'] && !isset($_SESSION['LOGIN_ERROR']) && intval($objPage->cache) > 0 && !$objPage->protected)
{
	$intCache = time() + intval($objPage->cache);
}
```

**Comment by leofeyer** [comment]
Fixed in 36e957c92c42108108732abdbf0503b9dd1a83c5.
