### ISSUE TITLE
Events / Calendar: Access to position and total number in list

### ISSUE THREAD

**Issue by mimamuxx** [contao/core#7825]
Hello,

the calendar functionality seems to be a bit neglected in contrast to the news module.
In the news templates we have access to to position and total number of articles in the current list. Unfortunately, there’s not the same for events.

In the forum there are several request to get a total count and an current position in an event list:
https://community.contao.org/de/showthread.php?56864-EVENTS-Ausgabe-der-Position-in-der-Gesamt-Liste
https://community.contao.org/de/showthread.php?48993-Fortlaufende-Nummer-pro-Nachrichtenbeitrag
https://community.contao.org/de/showthread.php?16381-Nummerierung-in-der-Newslist-umkehren 

The solutions are messy, not exactly an not update compatible.

So I ask you to extend the events list model that we can use this->count and this->total in the event templates.

Thanks!
Mimamuxx

**Comment by jenda77** [comment]
Would it be possible to integrate it into 3.5.x too, please? I would like to use something similar like $this->count in news. That would be great. Thank you.

**Comment by mimamuxx** [comment]
In fact, that would be great!

**Comment by jankout** [comment]
@leofeyer when do you want to implement it? I think it would be very useful feature.

**Comment by leofeyer** [comment]
Does contao/calendar-bundle#32 solve your issue?

**Comment by jankout** [comment]
Thank you. I hope so. At the moment I cannot try it - I don't know how to do it. ;-) In general it would be great to have the similar logic and argument/command like we have it in the news module.

**Comment by leofeyer** [comment]
See contao/calendar-bundle#32.

**Comment by jankout** [comment]
Thank you very much.
