### ISSUE TITLE
Double-opt-in confirmation link needs anchor

### ISSUE THREAD

**Issue by Anke** [contao/core#7827]
I just left a comment at the bottom of a long page. Uisng the confirmation link in the received email took me to the top of the commented page, so that I had to scroll a long way down to find the confirmation notice. Normal visitors might easily miss the small notice "Ihr Abonnement wurde aktiviert".

Possible solution: provide an id for the ce_comments div and add the anchor #[id] to the token link.

**Comment by leofeyer** [comment]
I'm closing this ticket due to lack of interest.
