### ISSUE TITLE
metaDescripton für Nachrichtenbeiträge

### ISSUE THREAD

**Issue by Kreativsoehne** [contao/core#7830]
Uns ist aufgefallen das man den Nachrichtenbeiträgen keine eigene metaDescription hinzufügen kann.
Unser Vorschlag ist hier ein optionales Feld für diese. (Wenn nicht ausgefüllt gekürzten Teaser verwenden - wenn explizit eine metaDescription eingegeben wird, diese benutzen).
Dies wäre eine sinnvolle Erweiterung der Standard-Funktionalität.
Wir freuen uns über Feedback.

**Comment by Kreativsoehne** [comment]
In der Zwischenzeit haben wir dafür ein kleines Modul geschrieben https://github.com/Kreativsoehne/Contao_NewsMetaDescription.
Freuen uns über Feedback :)

**Comment by jenda77** [comment]
Ich würde es auch toll finden, um die SEO für News zu verbessern bzw. diese mehr beeinflussen zu können.

**Comment by leofeyer** [comment]
Das wurde inzwischen implementiert.
