### ISSUE TITLE
Feature Request: News and Events categories

### ISSUE THREAD

**Issue by jenda77** [contao/core#7832]
It would be great when the core news could give the possibility to add a category to an event or a news. I think it should be a core feature because it is very important when you want to filter the news/events. 

Best wishes, Jan

**Comment by qzminski** [comment]
There is already an extension for news that provides such features.

https://github.com/codefog/contao-news_categories

**Comment by jenda77** [comment]
I know the extension but I think this feature should be a core feature. What do you think?

**Comment by qzminski** [comment]
No, I don't think so. There is no reason to integrate it in the core module - the extension is compatible with all new Contao versions and is easy to install. Besides, this feature is not something that you need for every website and thus it must not become an integral part of core.

**Comment by jenda77** [comment]
Ok, what's a pity. 

How does it look with the feature for linking of events and news per TinyMCE? I guess it's more important then the first suggestion.

**Comment by qzminski** [comment]
I think you can use some insert tags for that - https://docs.contao.org/books/manual/3.5/en/04-managing-content/insert-tags.html

**Comment by jenda77** [comment]
Yes, I know that but for the not-technic users it's not comfortable enough. Already there is the possibility for another intern files and sites. And it's very comfortable. For the editors is not easy to understand why it's not so easy to set a link to news or event how they can do it for files, sites. That could increase the user friendliness of Contao very well. I think Contao should focus on the user experience very strong at this point.

**Comment by qzminski** [comment]
You have my sword.
