### ISSUE TITLE
[3.5.0-RC1] Frontend-Module, Individuelle Navigation, Seitenauswahl wird nicht gespeichert

### ISSUE THREAD

**Issue by eweitzel** [contao/core#7833]
Beschreibung: Das Module "Individuelle Navigation" speichert die ausgewählten Seiten nicht

Arbeitsschritte: 
1. in der Admin-Console -> Themes -> FE-Module -> Neues Modul 
2. Titel ausfüllen
3. Modultyp "Individuelle Navigaton" selektieren
4. Seiten - Auswahl ändern
5. Seiten auswählen (Häckchen setzen)
6. Klick auf Anwenden

Erwartetes Verhalten: Auswahl wird gespreichert und Fenster wird geschlossen.
Aktuelles Verhalten: Beim Klick auf anwenden passiert nichts. Auswahl wird nicht gespeicher. Fenster wird nicht geschlossen.

Weitere Infos:
OS: OSX 10.9.5
Browser: FF 38.0.1
CMS: Contao Open Source CMS 3.5.0-RC1
Environment: MAMP Version 3.2.1

**Comment by leofeyer** [comment]
Siehe #7822.
