### ISSUE TITLE
Modul als Inhaltselement (CSS ID & Klasse verschwunden)

### ISSUE THREAD

**Issue by Nico0o** [contao/core#7835]
Hallo,
wenn ich ein Modul erstelle und eine CSS ID & Klasse zuweise und dieses Modul anschließend über das Inhaltselement "Modul" in einen Artikel einbinden möchte, wird die ID & Klasse nicht mit ausgegeben.
Ich muss jedes mal die Klasse oder ID im Inhaltselement setzen um mein Modul über CSS/JS anzusprechen. Ist das so gewollt, oder ist dies ein Fehler?

MfG Nico

**Comment by fritzmg** [comment]
Das ist gewollt. Das Verhalten wird erst in Contao 4 geändert: https://github.com/contao/core-bundle/pull/250

**Comment by fritzmg** [comment]
Mit folgender Extension kannst du das Verhalten ändern:

* ER2: [mergecssclasses](https://contao.org/de/extension-list/view/mergecssclasses.10000009.de.html)
* Packagist: [fritzmg/contao-mergecssclasses](https://packagist.org/packages/fritzmg/contao-mergecssclasses)
