### ISSUE TITLE
FileTree mit eigenem path und Dbafs-Exception

### ISSUE THREAD

**Issue by Tastaturberuf** [contao/core#7836]
Contao 3.5.0-RC1

Ich habe in einem Modul im DCA einen FileTree mit 
```'path' => 'system/modules/myModule/assets/images'``` 
konfiguriert. 

Das Auswahlmenü funktioniert noch.
Beim Anwenden wird dann folgende Exception geworfen: https://github.com/contao/core/blob/master/system/modules/core/library/Contao/Dbafs.php#L56
Ist ja auch logisch, liegt ja nicht im ```files```-Ordner.

Die Dateien sollen **nicht** im ```files```-Ordner liegen. Aus welchem Grund darf die Datei nicht außerhalb des Ordners liegen?

Hat jemand nen Lösungsvorschlag?

**Comment by fjacobi** [comment]
Was ist genau das Ziel?
Eine Datei im Frontend zur Verfügung stellen, die per Extension mit ausgeliefert wird?

Spontan würde ich das per Select Menu mit einem Options Callback machen.

Das Dateisystem von Contao ist nur für den files Ordner gedacht.

**Comment by Tastaturberuf** [comment]
Im Frontend und im Backend. Eine Vorschau bei der Auswahl ist wichtig, mir würde allerdings reichen, wie in Contao 2, das nur der Pfad gespeichert wird.

**Comment by nafetagrats** [comment]
Der Fehler tritt auch unter Contao 3.4.5 auf. 

Wenn man in seinem Modul Dateien außerhalb des Verzeichnis /files verfügbar machen möchte, so schlägt die Überprüfung in https://github.com/contao/core/blob/master/system/modules/core/library/Contao/Dbafs.php#L56
 fehl.

' ' ' 
// The resource does not exist or lies outside the upload directory
		if ($strResource == '' || strncmp($strResource,  $strUploadPath, strlen($strUploadPath)) !== 0 || !file_exists(TL_ROOT . '/' . $strResource))
		{
			throw new \InvalidArgumentException("Invalid resource $strResource");
		}
' ' ' 

Sofern der FileSelector die Möglichkeit der Angabe eines individuellen Pfades ermöglicht, sollte dies auch von Dbafs::addResource() ermöglicht werden.

Hilfreich z.B. für die Einbindung von externen Javascript aus dem /vendor Verzeichnis heraus.

**Comment by leofeyer** [comment]
Das Problem sollte in Contao 3.5.5 behoben sein.

**Comment by Tastaturberuf** [comment]
:+1: Vielen Dank.
