### ISSUE TITLE
$this->action undefined in form view

### ISSUE THREAD

**Issue by luger95** [contao/core#7842]
I just find that my contao 3.4.5, the method attribute of a custom form was not defined in the html. So I check the configuration of my form. I had indeed POST method and a landing page set.

So I look in the file: system\modules\core\forms\form.php line 250 (if ($this->method == 'GET' && $this->jumpTo && ($objTarget = $this->objModel->getRelated('jumpTo')) !== null)).
I deleted: "$this->method == 'GET' && " I am my method that appears.

**Comment by leofeyer** [comment]
How do I reproduce this in the online demo?

**Comment by leofeyer** [comment]
That's actually correct. If the method is not GET, the form will always be submitted to the current site and the visitor will be redirected **after** the form has been submitted successfully.
