### ISSUE TITLE
block_section does not contain <div class="inside">

### ISSUE THREAD

**Issue by aschempp** [contao/core#7843]
When using `$this->sections()` in a `fe_page` template, each section has a `<div class="inside">` (see https://github.com/contao/core/blob/master/system/modules/core/templates/block/block_sections.html5#L6).

However, when using `$this->section('mysection')`, the `<div class="inside">` is missing (see https://github.com/contao/core/blob/master/system/modules/core/templates/block/block_section.html5).

**Comment by leofeyer** [comment]
Not sure if we should change this in Contao 3.5?

**Comment by aschempp** [comment]
I don’t know either, I only need it in Contao 4 ;-)

**Comment by leofeyer** [comment]
Fixed in f94e3e7f549b412362bd798d8af0b8ccc40c6e39.

**Comment by aschempp** [comment]
While we're at it, we might also use the block template for the regular sections in `fe_page`?

**Comment by aschempp** [comment]
Oh, and we could also use short array syntax. Want a PR?

**Comment by leofeyer** [comment]
No short array syntax in the legacy code :)
