### ISSUE TITLE
[3.5.0-RC1] File-/Page-Picker: Click inside table row to select entry not working anymore

### ISSUE THREAD

**Issue by ben-eSM** [contao/core#7844]
In former Contao versions it was possible to click almost anywhere inside the table row to select a file/page in the File-/Page-Picker. This feature is broken in the current 3.5.0 RC. At the moment, the checkbox/radio has to be clicked to select the entry.

**Comment by xchs** [comment]
Does the issue affect both checkboxes and radio buttons or only the latter? See 0784b96e5b189d5d5856b76e311742236438e566.

**Comment by ben-eSM** [comment]
When I first noticed, it was affecting checkboxes and radio fields. However, it seems to only affect the radio fields now. At least I can only reproduce it with radios. The checkbox issue could have been related to something else. Maybe the cached/combined versions of the JS where corrupted. After cleaning up every cache such, it occurs on the radios only.

**Comment by leofeyer** [comment]
See #7822, #7792 or #7785.
