### ISSUE TITLE
contao.org SSL/TLS certificate is only securely accessible via SNI

### ISSUE THREAD

**Issue by monojp** [contao/core#7845]
Hi, I already made a comment at https://github.com/contao/core/issues/7548#issuecomment-104612294 but because the issue is already closed I thought it would be best to open a new one. Please correct me if I'm or my tests are wrong! c/p:

on our servers this is also not working and is **NOT a problem with the certificate chain**. contao.org uses SSL with **Server Name Indication** (SNI) [1] which is NOT supported by older openssl versions as they are present in e.g. Centos5 [2].
Downgrading PHP and therefore disabling the peer verification works because there seems to be another cert installed which will be used e.g. for insecure cURL transfers because

```ssh
$ openssl version
OpenSSL 0.9.8e-fips-rhel5 01 Jul 2008

$ md5sum /etc/pki/tls/certs/ca-bundle.crt
3fca775db8bf2d756662f3ecf4790427  /etc/pki/tls/certs/ca-bundle.crt

$ curl -v -k -I https://contao.org/services/repository.wsdl
* About to connect() to contao.org port 443
*   Trying 134.119.21.26... connected
* Connected to contao.org (134.119.21.26) port 443
* successfully set certificate verify locations:
*   CAfile: /etc/pki/tls/certs/ca-bundle.crt
  CApath: none
* SSLv2, Client hello (1):
SSLv3, TLS handshake, Server hello (2):
SSLv3, TLS handshake, CERT (11):
SSLv3, TLS handshake, Server key exchange (12):
SSLv3, TLS handshake, Server finished (14):
SSLv3, TLS handshake, Client key exchange (16):
SSLv3, TLS change cipher, Client hello (1):
SSLv3, TLS handshake, Finished (20):
SSLv3, TLS change cipher, Client hello (1):
SSLv3, TLS handshake, Finished (20):
SSL connection using DHE-RSA-AES256-SHA
* Server certificate:
* 	 subject: /C=DE/ST=Nordrhein-Westfalen/L=Wuppertal/O=Leonhard Feyer/CN=*.w1.vhost.io/emailAddress=webmaster@vhost.io
* 	 start date: 2015-05-19 05:16:03 GMT
* 	 expire date: 2017-05-19 15:57:31 GMT
* 	 common name: *.w1.vhost.io (does not match 'contao.org')
* 	 issuer: /C=IL/O=StartCom Ltd./OU=Secure Digital Certificate Signing/CN=StartCom Class 2 Primary Intermediate Server CA
* SSL certificate verify ok.
```

on systems with no SNI support **uses a cert with "*.w1.vhost.io" as common name** in contrast to

```sh
$ openssl version
OpenSSL 1.0.1e-fips 11 Feb 2013

$ md5sum /etc/pki/tls/certs/ca-bundle.crt
3fca775db8bf2d756662f3ecf4790427  /etc/pki/tls/certs/ca-bundle.crt

$ curl -v -I https://contao.org/services/repository.wsdl
* About to connect() to contao.org port 443 (#0)
*   Trying 134.119.21.26... connected
* Connected to contao.org (134.119.21.26) port 443 (#0)
* Initializing NSS with certpath: sql:/etc/pki/nssdb
*   CAfile: /etc/pki/tls/certs/ca-bundle.crt
  CApath: none
* SSL connection using TLS_DHE_RSA_WITH_AES_256_CBC_SHA
* Server certificate:
* 	subject: E=hostmaster@inetrobots.com,CN=www.contao.org,O=Leonhard Feyer,L=Wuppertal,ST=Nordrhein-Westfalen,C=DE
* 	start date: May 19 23:12:07 2015 GMT
* 	expire date: May 19 12:19:14 2017 GMT
* 	common name: www.contao.org
* 	issuer: CN=StartCom Class 2 Primary Intermediate Server CA,OU=Secure Digital Certificate Signing,O=StartCom Ltd.,C=IL
```

on systems with SNI support that **uses the correct cert with "www.contao.org" as common name.**

The best fix to be compatible with older clients would be not using SNI at all, altough if there are no other SSL hosts on the server simply changing the default cert would also fix the problem, right? It seems the domain vhost.io belongs to the Contao team anyway and may be not properly configured.

[1] https://www.ssllabs.com/ssltest/analyze.html?d=contao.org
[2] http://en.wikipedia.org/wiki/Server_Name_Indication#Libraries

**Comment by monojp** [comment]
Sorry if I'm being rude, but does somebody from the Contao team (e.g. @leofeyer) have any opinions on this? It seems that with the current SNI fallback certificate it is not safely possible to use Contao on servers with older openssl but newer PHP versions (e.g. CentOS 5).

**Comment by leofeyer** [comment]
We can neither disable SNI nor change the default certificate. You have to update you OpenSSL version I'm afraid.

**Comment by monojp** [comment]
I see. Our problem is that on CentOS 5 a simple OpenSSL update is not really possible because of other packages depending on OpenSSL and therefore forced recompilation of half of the system which of course also interfers with stability. The support effort spent fixing these problems is not insignificant. As we are in charge of 150k webhosts and providing a one-click-install-solution for Contao we would like to avoid solutions like disabling Contao or certificate peer verification via PHP.
I think that also many other hosters and users may be affected by this problem.
Is there no other solution on the server side? Does the updater really need SNI and / or SSL/TLS?

**Comment by leofeyer** [comment]
It is 2015 and SNI is widely supported. You might know that IPv4 addresses have become rare and that IPv6 is still not commonly used, so SNI has become a requirement. I'm not familiar with CentOS, but it seems that there is a [work-around to get SNI working on CentOS 5.6](https://blog.dembowski.net/2011/sni-on-centos-5-6-mod_gnutls/).

**Comment by monojp** [comment]
It's not about hosting with SNI, I'm talking about the client access to the contao.org server and of course IPv4 shortage is a huge issue, but shouldn't you try to be as compatible as possible when providing an infrastructure for a well known repo/cms?
To sum it up: RHEL5/CentOS5 based and other old but still maintained enterprise grade hosting systems won't be able to connect to your SNI based repo URL.
So we'd like to find a solution which does not include re-installing 1k server systems only due to the fact that Contao admins moved the repo to an SNI based host. Of course these re-installs will and do happen, but we'd like to have a solution for all of our Contao users wanting to use YOUR repo now.

**Comment by leofeyer** [comment]
If you really cannot update OpenSSL, the only solution seems to be instructing your customers to stick with PHP 5.5 until the re-installs, I'm afraid.
