### ISSUE TITLE
Template insertion $this->insert() does not work

### ISSUE THREAD

**Issue by Aybee** [contao/core#7848]
*Contao 3.4.5*
EN - Manual
https://github.com/contao/docs/blob/3.4/manual/en/04-managing-content/templates.md#template-insertion
DE - Handbuch
https://github.com/contao/docs/blob/3.4/manual/de/04-inhalte-verwalten/templates.md#templates-mischen

Das "Mischen" von Templates, wie im Handbuch beschrieben funktioniert nicht.

Ist so nachzuvollziehen:
- Template anlegen **fe_custom**
- das Template dem Layout zuweisen
- folgenden Code ins Template **fe_custom** schreiben
```php
<?php $this->insert('fe_page'); ?>
```
Das Frontend gibt lediglich folgendes aus (weiße Seite):
```html
<!DOCTYPE html>
<html lang="">
  <head>
    <meta charset="">
    <title></title>
    <base href="">
    <meta name="robots" content="">
    <meta name="description" content="">
    <meta name="keywords" content="">
    <meta name="generator" content="Contao Open Source CMS">
    <!--[if lt IE 9]><script src="assets/html5shiv/3.7.0/html5shiv-printshiv.js"></script><![endif]-->
  </head>
  <body id="top" class="win firefox gecko fx38">
    <div id="wrapper">
      <div id="container">
        <div id="main">
          <div class="inside">
          </div>
        </div>
      </div>
    </div>
  </body>
</html>
```

**Comment by bezin** [comment]
I can confirm that. Doesn't work for me either.

**Comment by dmolineus** [comment]
You habe to pass all attributes sich you want to use.

```php

<?php $this->insert('fe_page', $this->getData()); ?>

```

**Comment by aschempp** [comment]
It works perfectly fine, but you didn't pass any parameters. You probably should use the `extend()` in this case.

**Comment by Aybee** [comment]
Yes, I used `$this->extend('fe_page')` already, just wanted to point out that the manual is not clear in that particular point. Maybe we should slightly redact it.

The hint by @dmolineus with `$this->getData()` as parameter to fetch all parent variables will be fine.

**Comment by aschempp** [comment]
@Aybee I guess you're right, feel free to contribute an improvement to [contao/docs](https://github.com/contao/docs/) :-)

**Comment by Aybee** [comment]
Ok, ich habe da jetzt online einen Vorschlag gemacht, muss ich da jetzt noch auf **Create pull request** clicken?

**Comment by aschempp** [comment]
ich denke ja, ich hab zumindest noch nichts bekommen. Hier gibt’s eine kleine Anleitung von GitHub: https://help.github.com/articles/using-pull-requests/
