### ISSUE TITLE
3.5.0 RC1 Fehler in der Dateiverwaltung und im Installtool

### ISSUE THREAD

**Issue by do-while** [contao/core#7849]
bei Installation in Contao2Go (alle vorherigen Versionen haben kein Problem) tritt im installierten Contao ein Fehler auf. Die Synchronisation der Dateiverwaltung wirft eine Fehlermeldung, wenn in /files eine noch unbekannte Datei entdeckt wird.

So läßt sich das Problem nachstellen:
1) Download contao-3.5.0-RC1.zip von Contao.org
2) Verzeichnis in Contao2Go erstellt
3) ZIP ausgepackt
4) neue Datenbank angelegt
5) Install aufgerufen, Datenbankzugang eingetragen, alles fertig gemacht (kein Composer!)
6) Backend einloggen, Erweiterungsverwaltung aufrufen
7) Erweiterung installieren: "official_demo" 3.4.2
8) Installtool: Template importieren:
	D:\Contao2GoV2\htdocs\vhosts\contao-3.5.RC1/templates/contao_v34_official-demo.sql
	bei alten Versionen stand die SQL ohne Pfad !!
9) Import schlägt fehl: Meldung "Bitte wählen Sie eine Template-Datei!"

Dann ohne Import weiter im Backend
10) Datei Problem.txt als Datei in /files hineinkopiert
11) In der Dateiverwaltung Synchronierung aufrufen

FEHLERMELDUNG:

```
Fatal error: Uncaught exception Exception with message No parent entry for D:\Contao2GoV2\htdocs\vhosts\contao-3.5.RC1/files thrown in system\modules\core\library\Contao\Dbafs.php on line 541

#0 system\modules\core\drivers\DC_Folder.php(2107): Contao\Dbafs::syncFiles()
#1 system\modules\core\classes\Backend.php(639): Contao\DC_Folder->sync()
#2 system\modules\core\controllers\BackendMain.php(131): Contao\Backend->getBackendModule('files')
#3 contao\main.php(20): Contao\BackendMain->run()
#4 {main}
```

Contao2Go meldet dann auch Fehler:

```
Warning: filesize(): stat failed for D:\Contao2GoV2\htdocs\vhosts\contao-3.5.RC1/D:\Contao2GoV2\htdocs\vhosts\contao-3.5.RC1/files/Problem.txt in system\modules\core\library\Contao\File.php on line 184

#0 [internal function]: __error(2, 'filesize(): sta...', 'D:\Contao2GoV2\...', 184, Array)
#1 system\modules\core\library\Contao\File.php(184): filesize('D:\Contao2GoV2\...')
#2 system\modules\core\drivers\DC_Folder.php(2406): Contao\File->__get('filesize')
#3 system\modules\core\drivers\DC_Folder.php(308): Contao\DC_Folder->generateTree('D:\Contao2GoV2\...', 0, false, false, false)
#4 system\modules\core\classes\Backend.php(639): Contao\DC_Folder->showAll()
#5 system\modules\core\controllers\BackendMain.php(131): Contao\Backend->getBackendModule('files')
#6 contao\main.php(20): Contao\BackendMain->run()
#7 {main}
```

Der selbe Vorgang in in den älteren Contao-Versionen kein Problem!
@leofeyer  Wir können gern hier in Lüneburg noch mal auf meinen PC gucken, wenn's hilft

**Comment by Zeromax** [comment]
Related #7847
