### ISSUE TITLE
Dateiwähler liefert keine InsertTags

### ISSUE THREAD

**Issue by Defcon0** [contao/core#7850]
Hallo,

seit einer der letzten Contaoversionen können ja wieder Bilder im Dateiwähler (bspw. in den Links) gesucht werden. An sich wunderbar :-) Nur eine Kleinigkeit stört etwas: Es sollten keine relativen Pfade aus einem Auswählen einer Datei resultieren, sondern, wie auch bei Seiten, ein InsertTag, also bspw. {{file::<uid>}}. So gehen immer die Links kaputt, wenn ich eine Datei verschiebe.

Oder geht das bereits irgendwie?

Ciao Defcon0

**Comment by Aybee** [comment]
related #7581

**Comment by Defcon0** [comment]
Ah, ok. Aber hier betrifft es das Link-Tool im tinyMCE.

**Comment by pswerbung** [comment]
Ja es sollten in jedem Fall InsertTags verwendet werden, z.B.:
- bei Text/Bild: Bildlink einfügen (Datei oder Seite)
- bei Hyperlinks mit Ziel auf Datei oder Seite

Gerade wenn der Kunde sich eine Dokumentablage «baut» und auch mal Dateien umorganisiert oder umbenennt müssen die Links setzen, die er schon selber auswählt.

Danke wenn man dies fixen kann – geht das innerhalb der 3.5-Schiene?

**Comment by leofeyer** [comment]
Was genau ist das Problem?

**Comment by pswerbung** [comment]
Wenn man z.B. einen Bildlink hinzufügt und mit dem Dateiwähler auf eine Datei zeigt, dann wird der relative Pfad hineinkopiert und kein {{file::ID}}, was eigentlich viel sicherer/praktischer wäre. Könnte dies in Contao nicht implementiert werden?

**Comment by Aybee** [comment]
related #7678 dort oben findet sich auch nochmal eine Erklärung des Problems.

**Comment by leofeyer** [comment]
Der relative Pfad wird bereits im Hintergrund in ein `{{file::}}`-Tag umgewandelt und beim Aufruf von TinyMCE wieder in einen relativen Pfad zurück.

**Comment by pswerbung** [comment]
@leofeyer Die Frage bezog sich nicht alleine auf TinyMCE, sondern auf die «normale» Inhaltselemente Text (mit Bild) oder z.B. auch Hyperlinks. Dort werden Links auf Dateien nicht mit der {{file::ID}} umgewandelt, wie ich das sehe …

**Comment by Aybee** [comment]
Ja, habe es gerade auch nochmal gestestet.

CE-Download - OK
CE-Text Text im RTE auf Datei verlinken - OK
CE-Hyperlink - **nicht** OK

Ich habe den Test nur durch Verschieben der Datei im Dateimanager durchgeführt und dann im FE geguckt, ob sich der Link dementsprechend angepasst. hat.

**Comment by pswerbung** [comment]
… und zwischendurch benötigen wir auch den CE-Text Bildlink als Link z.B. auf ein PDF. Dort sollte dann der Dateiwähler auch erscheinen, das wäre der Vollständigkeit her auch sinnvoll, wenn es dort {{file::ID}} Links generiert.

**Comment by leofeyer** [comment]
> CE-Hyperlink - **nicht** OK

Das ist klar, es handelt sich hierbei ja um einen Picker, mit dem man _entweder_ Seiten _oder_ Dateien auswählen kann.

> CE-Text Bildlink als Link z.B. auf ein PDF. Dort sollte dann der Dateiwähler auch erscheinen

Das ist bei mir bereits der Fall.

**Comment by Aybee** [comment]
> Das ist klar, es handelt sich hierbei ja um einen Picker, mit dem man entweder Seiten oder Dateien auswählen kann.

Aber beim "Picker" öffnet sich doch der Dateiwähler. Siehe auch Threadtitel "Dateiwähler liefert keine InsertTags". Seit dem DBAFS gehen die Redakteure ja davon aus, dass wenn sie über die BE-Optionen per Auswahl eine Datei als Ziel wählen, dass sie diese Datei dann in der Dateiverwaltung umbenennen, bzw. verschieben können. Sie sehen halt nicht den teschnichen Hintergrund, dass das gerade jetzt an dieser Stelle mal nicht funktioniert.

Wenn das Ticket jetzt als "kein Bug" eingestuft wird, dann sollte es meiner Meinung nach als Feature-Request eingestellt werden.

**Comment by Defcon0** [comment]
Irgendwie verstehe ich nicht, wo hier überhaupt der Konflikt liegt. Wenn ein Dateiwähler aufgeht, sollte er auch Inserttags liefern. Alles andere ist für Redakteure absolut intransparent und führt absehbar zu toten Links.

Warum muss über solche Dinge immer so lange diskutiert werden :-(? Nicht böse gemeint, aber ich verstehe es einfach nicht.

**Comment by fritzmg** [comment]
This was closed and later on tagged as a feature. Shouldn't it be reopened again?

**Comment by fritzmg** [comment]
Why was this removed from Contao `4.2.0`? What are the reasons for not implementing this? It has been requested multiple times, but never was it explained, why it will not be implemented. Is there a specific reason for not doing it this way?

**Comment by leofeyer** [comment]
> Why was this removed from Contao 4.2.0? 

As you have explained yourself, the issue has mistakenly been assigned to a milestone, even though it was long closed. Now the milestone has been removed again.

**Comment by fritzmg** [comment]
Yes, but as asked by others in other issues and myself in other issues: why are these requests closed without comment? What is the reason for the picker not providing a `{{file::…}}` insert tag? Is there an issue that we are missing by providing file references as a `{{file::…}}` insert tag?

**Comment by Aybee** [comment]
:+1: zu
> @Defcon0 - Alles andere ist für Redakteure absolut intransparent und führt absehbar zu toten Links.

Ich weiß nicht, wie es anderen ergeht, aber mir persönlich ist jetzt total unklar, ob das implementiert wird oder nicht. Meiner Meinung nach wäre es auch immer noch ein Bug und kein Feature-Request.

**Comment by Defcon0** [comment]
Da schließe ich mich natürlich gern noch mal mit an. Das ist aus meiner Sicht ein Bug. :+1:

**Comment by leofeyer** [comment]
> why are these requests closed without comment?

Because we are discussing the exact same thing in #8213 and we do not need two open tickets for the same issue, do we?

**Comment by fritzmg** [comment]
> Because we are discussing the exact same thing in #8213 and we do not need two open tickets for the same issue, do we?

Issue #8213 is about links to files/folders having spaces in them and you were talking about solving that issue by encoding the spaces with a save callback. From the comments there I am not sure now if the file picker returning `{{file::…}}` insert tags is now up for discussion or not.

The only ticket that is _specifically_ talking about the file picker (`contao/file.php`) for `tl_content.url`, `tl_content.imageUrl`, etc. not returning `{{file::…}}` inser tags is #8035, but it was closed in favor of #7850, which was already closed by then.
