### ISSUE TITLE
[3.5.0-RC1] New abstract methods of DataContainer

### ISSUE THREAD

**Issue by ausi** [contao/core#7851]
The `DataContainer` got two new abstract methods `getPalette()` and `save()` in e674beac7645b367dacf63e4336abe783b7aab1c. This is a BC break for people who did extend the class. Should we document this change in [UPGRADE.md](https://github.com/contao/core/blob/2b6bb1bb73000d4fe3a670f16ec17888483ed971/system/docs/UPGRADE.md#datacontainer)?

**Comment by leofeyer** [comment]
Since you could not implement your own `DC_*` class without the two methods, I doubt that this will be a problem for anyone. Or are you just suggesting to document the change?

**Comment by ausi** [comment]
> Since you could not implement your own `DC_*` class without the two methods

Well, I did :) That’s how I recognized this change, but my use case is very special and I think documenting this change should be sufficient.

**Comment by Toflar** [comment]
+1 for the UPGRADE.md

**Comment by leofeyer** [comment]
I have just realized that there is no `UPGRADE.md` file in Contao 3.5. Most likely because there are no backwards incompatible changes :)

Do we really need to create the file with just one entry?

**Comment by ausi** [comment]
I think the UPGRADE.md is for all Contao 3 versions: https://github.com/contao/core/blob/cd37b1be82204e08497dd7a1d8127c1623f78c4d/system/docs/UPGRADE.md#version-34-to-35

**Comment by leofeyer** [comment]
Sorry, my bad. I did not check the `system/docs` folder. :facepalm:

**Comment by aschempp** [comment]
Maybe we just add the abstract methods in Contao 4? It does not really matter…

**Comment by leofeyer** [comment]
Added in 86f943029558853180db53c28b65e042b102420b.
