### ISSUE TITLE
Invalid 302 redirect for requests in page-directory

### ISSUE THREAD

**Issue by andypillip** [contao/core#7853]
The online demo is redirecting pages like http://demo.contao.org/en/sitemap/a.html or http://demo.contao.org/en/sitemap/b.html to /en with a 302.

The correct status code would be either a 404 – or a 302 to /en/sitemap.html.

I found this issue because our installation magically is not rewriting those invalid URLs at all.

**Comment by aschempp** [comment]
That's a matter of configuration.

**Comment by andypillip** [comment]
Can you please be more specific?

I don't think configuration is possible to produce the correct behaviour.

**Comment by aschempp** [comment]
The 404 page type is set to forward to the homepage, thats why you get the current result.

**Comment by andypillip** [comment]
Ok thanks, sorry for the troubles.

I didn't expect an option like that.
