### ISSUE TITLE
Widget::getPost() minor issue

### ISSUE THREAD

**Issue by qzminski** [contao/core#7855]
This statement in ```Widget::getPost()``` is always true and will be always executed:

https://github.com/contao/core/blob/master/system/modules/core/library/Contao/Widget.php#L828

Thus the last line of the method will never be executed:

https://github.com/contao/core/blob/master/system/modules/core/library/Contao/Widget.php#L845

**Comment by aschempp** [comment]
According to the `explode()` manual, the method will return `false` if the passed-in string is empty.

**Comment by aschempp** [comment]
Ah I was wrong, it would only return `false` if the given `delimiter` is empty.

**Comment by leofeyer** [comment]
What if `$strKey` is empty?

**Comment by qzminski** [comment]
Is it even possible? I am not sure but if there is no name given then you cannot identify the widget to validate it either. The ```$strKey``` identifies the field name and it must not be empty or otherwise something is wrong with your form.

**Comment by qzminski** [comment]
According to me the check ```strpos($strKey, ']')```should be performed first, before exploding the key and parsing the array.

**Comment by leofeyer** [comment]
So what are you suggesting?

**Comment by qzminski** [comment]
See my previous comment. I suggest to have a ```strpos``` check. It should be backwards compatible.

**Comment by leofeyer** [comment]
Why?

**Comment by qzminski** [comment]
To check if we should treat the field as an array or not.
```field[foobar]``` -> yes
```field``` -> no

**Comment by leofeyer** [comment]
It does not matter, because `explode()` will also do the array conversion for us. We'd have to cast otherwise, which means an additional if-else condition, which would increases the cyclomatic complexity. Therefore the current code is fine.

**Comment by aschempp** [comment]
But Kamil is correct that the current code has stuff that is never executed. A unit test would show that, but I guess that’s difficult to add (even just for Contao 4) ?

**Comment by leofeyer** [comment]
I don't see how adding a `strpos()` check would solve this?

**Comment by aschempp** [comment]
it wouldn't, but the `if (!empty($arrParts))` is unnecessary (if Kamil is right).

**Comment by leofeyer** [comment]
Unless `$strKey` can be empty, which we cannot deny for sure, can we?

**Comment by aschempp** [comment]
No. If `$strKey` is empty, the result will be an array containing an empty string. The result would only be `false` if the *delimiter* would be empty, but that's never the case (the *delimiter* is always `[`).

**Comment by leofeyer** [comment]
Ok, so what do you want me to change now?

**Comment by aschempp** [comment]
I have created a unit test for Contao 4 to test this method (see https://github.com/contao/core-bundle/pull/291). The code coverage safely tells us that we can remove line 828 and 845 as mentioned by @qzminski

**Comment by leofeyer** [comment]
@aschempp Is this correctly assigned to version 3.5.6?

**Comment by aschempp** [comment]
I would suggest to remove it in 4.1 and run the unit test. The coverage should already tell you that case does never happen.

**Comment by leofeyer** [comment]
There is another problem: the method passes empty keys to the `Input` class, which should not be the case. AFAIK, `$_POST['']` can never occur, can it?

**Comment by aschempp** [comment]
No idea what would happen, but you could add this check to the unit tests? ;)

**Comment by leofeyer** [comment]
> http://www.w3.org/TR/html401/interact/forms.html#successful-controls
>
> A successful control is "valid" for submission. Every successful control has its control name paired with its current value as part of the submitted form data set. A successful control must be defined within a FORM element and ​*must have a control name.

Therefore, [these lines](https://github.com/contao/core-bundle/blob/master/tests/Contao/WidgetTest.php#L83-L85) of the unit test are wrong. L83 and L84 should expect `null`; not sure about L85 though.

@contao/developers /cc

**Comment by aschempp** [comment]
As far as I know, the unit tests are currently passing. That means we're currently returning what you think is wrong. Also see https://github.com/contao/core-bundle/pull/291#issuecomment-109928602

**Comment by leofeyer** [comment]
Changed in 4f8d235d5e68018283dc68f8ef7030df842a404d.
