### ISSUE TITLE
FR: automatischer Seitenalias: HTML-Tags entfernen

### ISSUE THREAD

**Issue by xantippe** [contao/core#7857]
Hin und wieder kommt es vor, dass ich bei Seitentitel einen HTML-Tag einbauen muss, um die Anzeige z.B. in der Navigation anzupassen (Beispiel: Firmenname in bestimmter Schreibweise)

Die automatische Generierung des Seiten-Alias entfernt zwar die Sonderzeichen wie < > = " aber nicht den kompletten Tag - somit kommen dann Wörter wie span, class, usw. in den Alias.

Ein Alias sollte aber aussehen, wie im Screenshot:

![zwischenablage10](https://cloud.githubusercontent.com/assets/1045318/7954679/0ada96f8-09d2-11e5-9561-fcaee491db4e.jpg)

**Comment by Ainschy** [comment]
Ich sehe das so:

Wenn du dich entscheidest HTML-Tags im Seitenname zu verwenden, dann kannst du auch den Alias händisch eintragen.

**Comment by discordier** [comment]
Da muss ich @Ainschy beipflichten. Das was du da machst ist schlechter Stil und definitiv nicht wuenschenswert.

**Comment by Toflar** [comment]
Ein `strip_tags` wäre aber auch kein Problem ;)

**Comment by discordier** [comment]
@Toflar Du meinst beim `generateAlias()` nicht nur standardize sondern auch noch `strip_tags` aufrufen?
Ich weiss nicht, das wird langsam overkill... dann kann man auch gleich yberall HTML erlauben.

**Comment by Toflar** [comment]
Ich find das jetzt überhaupt nicht problematisch^^

**Comment by leofeyer** [comment]
Behoben in ad03d80f1710412410723d3182798aae76183bca.

**Comment by xantippe** [comment]
Dank!
