### ISSUE TITLE
[Contao 3.4.4] Leerers Feld bei Gruppenrechten

### ISSUE THREAD

**Issue by akroii** [contao/core#7858]
Ich bekomme ein leeres Feld bei den Gruppenrechten innerhalb "Erlaubte Felder".
Screen-Shot:
![err](https://cloud.githubusercontent.com/assets/8830861/7956748/8d695c20-09e2-11e5-9dfd-0d9ac535b84f.jpg)

**Comment by fritzmg** [comment]
Das ist das label für das field `customLanguageText` aus der Erweiterung (terminal42/contao-changelanguage)[https://github.com/terminal42/contao-changelanguage]. Das Label ist leer, weil keine Übersetzung für das field label angegeben wurde, aus welchem Grund auch immer: (terminal42/contao-changelanguage/languages/de/tl_module.php#L38)[https://github.com/terminal42/contao-changelanguage/blob/master/languages/de/tl_module.php#L38]
```php
$GLOBALS['TL_LANG']['tl_module']['customLanguageText']	= array(' ', 'Bitte geben Sie einen Ersatz für jede Sprache ein.');
```
Solche Fehler findet man bei Contao Extensions leider recht häufig.

**Comment by leofeyer** [comment]
Ist kein Fehler im Core, daher bitte beim Entwickler der Extension melden.
