### ISSUE TITLE
Creating new layout - hex2bin

### ISSUE THREAD

**Issue by dennispost** [contao/core#7861]
Clean install. Create new layout. No changes, just click save:

Fatal error: Call to undefined function Contao\hex2bin() in /var/www/vhosts/myurl/myurl/system/modules/core/library/Contao/String.php on line 544

**Comment by BugBuster1701** [comment]
You need PHP >= 5.4.0

**Comment by BugBuster1701** [comment]
Fixed in Contao 3.3.0: https://github.com/contao/core/issues/7010

**Comment by BugBuster1701** [comment]
Which Contao version do you use?

**Comment by cebe** [comment]
had the same issue, this is most likely because you have a PHP version < 5.4, hex2bin() is only available since 5.4 which is the minimum requirement since contao 3.5.0 https://github.com/contao/core/tree/3.5.0#system-requirements
