### ISSUE TITLE
Gallery - strange behavior with different image types in one folder

### ISSUE THREAD

**Issue by Aybee** [contao/core#7862]
*[Contao 3.4.4]* *(Online demo)*

Go to the demos gallery http://demo.contao.org/contao/main.php?do=article&table=tl_content&act=edit&id=290

In source files select the folder contaodemo/media/slider/

It throws this errors

```
Warning: filesize() [function.filesize]: stat failed for /home/www/demo/files/contaodemo/media/slider/contao_extensions.png in system/modules/core/library/Contao/File.php on line 181
#0 [internal function]: __error(2, 'filesize() [__get('size')
#3 system/modules/core/classes/Ajax.php(325): Contao\FileTree->generate()
#4 system/modules/core/classes/Backend.php(399): Contao\Ajax->executePostActions(Object(Contao\DC_Table))
#5 system/modules/core/controllers/BackendMain.php(126): Contao\Backend->getBackendModule('article')
#6 contao/main.php(20): Contao\BackendMain->run()
#7 {main}

Fatal error: Uncaught exception Exception with message Directory "system/themes/default/images/" is not a file thrown in system/modules/core/library/Contao/File.php on line 94
#0 system/modules/core/library/Contao/Image.php(823): Contao\File->__construct('system/themes/d...', true)
#1 system/modules/core/widgets/FileTree.php(210): Contao\Image::getHtml(NULL, '', 'class="gimage" ...')
#2 system/modules/core/classes/Ajax.php(325): Contao\FileTree->generate()
#3 system/modules/core/classes/Backend.php(399): Contao\Ajax->executePostActions(Object(Contao\DC_Table))
#4 system/modules/core/controllers/BackendMain.php(126): Contao\Backend->getBackendModule('article')
#5 contao/main.php(20): Contao\BackendMain->run()
#6 {main}
```

I discovered this while I was checking the select folder option of a gallery because I have problems with folders that contain different image types. But this does not throw above errors in my installation [3.4.5] so I don't know if both thing maybe are related.

Selecting a folder with only JPGs seems to be ok.

Following images (3 diff. types, 2 with same name)
- icon-en.gif
- icon-de.gif
- logo.gif
- logo.jpg
- another.png

results in only showing one image above the **Change selection** button. It is the **logo.gif** file.

Following images (3 diff. types, 3 with same name)
- img_1.jpg
- img_2.jpg
- img_3.jpg
- img_3.gif
- img_3.png

results in only showing the JPGs

After some clicking around - selecting single images instead of a folder, doing a sync in the file manager - somewhere along the way all images in gallery are fine.

Seems that there something is not programmed correctly.

**Comment by leofeyer** [comment]
The error message seems correct to me, since the file does not exist:

http://demo.contao.org/files/contaodemo/media/slider/contao_extensions.png

**Comment by Aybee** [comment]
Stimmt, bleibt die Frage, warum Contao versucht dieses Bild einzufügen, es wird in dem Ordner ja auch nicht angezeigt. Nach einem Sync in der Dateiverwaltung kommt der Fehler übrigens nicht mehr. Hat das evtl. etwas mit der besonderen Konfiguration der Demo zu tun was wir dann vernachlässigen könnten?

Bleibt der Rest des Tickets. Soll ich dafür mal ein paar Bilder vorbereiten mit welchen das dann nachgestellt werden kann?

**Comment by Loilo** [comment]
Ich habe hier einen ähnlichen Fehler, könnte zusammenhängen. Ich kann keine JPGs im fileTree auswählen und bekomme auch das Thumbnail angezeigt, PNGs werfen allerdings eine Exception.
'Directory "system/themes/default/images/" is not a file'
...obwohl ich in dem Ordner gar nichts ausgewählt habe. Könnte das zusammenhängen?

**Comment by leofeyer** [comment]
Lässt sich das Problem in der Onlinedemo mit jetzt Contao 3.5 noch reproduzieren?

**Comment by Aybee** [comment]
Ich mach's mal auf Deutsch, weil da ein paar sehr seltsame Sachen sind.

In der **Online-Demo** kann ich den Fehler jetzt nicht mehr provozieren. Scheint also **OK**.

Dann habe ich einen Test mit 3 Bilder für eine Galerie gemacht. Ordner und Dateiaktionen per FTP, keine BE-Dateiverwaltung.
```
files/test/red.gif
files/test/red.jpg
files/test/red.png
```
Galerie erstellt, Ordner test ausgewählt - alles OK.

Um sicher zu gehen, wollte ich es noch ohne Debug-Modus und ohne internen Cache versuchen.

Das Ergebnis war, dass ich in der Galerie jetzt den Ordner test zwar anhaken konnte, aber **keine Bilder in der Vorschau** angezeigt wurden.

Auch das einschalten des Debug-Modus und mit oder ohne internen Cache brachte jetzt keinen Erfolg mehr.

Als ich dann nochmal ganz von vorne anfing - neues CE Galerie, Ordner mit Testdateien auswählen - habe ich die Vorschaubilder auf einmal wieder gesehen.

**Fazit**: Das Problem mit unterschiedlichen Dateitypen und gleichem Namensteil schein nicht mehr vorhanden zu sein. Es gibt aber **Situationen**, wo bei der Auswahl eines Ordners **keine Vorschaubilder** angezeigt werden. Die Umstände konnte ich nicht herausfinden.

Hier die 3 Bilder zum Testen, sie hießen ursprünglich alle "red.xxx":
![red](https://cloud.githubusercontent.com/assets/1143013/8778137/4eb55eae-2efc-11e5-8980-ff693eeb304b.gif)
![red](https://cloud.githubusercontent.com/assets/1143013/8778138/4ebaff58-2efc-11e5-86e8-7f870d7ef9cb.jpg)
![red](https://cloud.githubusercontent.com/assets/1143013/8778139/4ebcc0f4-2efc-11e5-869b-d42c27c37c1b.png)

**Comment by leofeyer** [comment]
> In der Online-Demo kann ich den Fehler jetzt nicht mehr provozieren. Scheint also OK.

> Es gibt aber Situationen, wo bei der Auswahl eines Ordners keine Vorschaubilder angezeigt werden. Die Umstände konnte ich nicht herausfinden.

Dann schließe ich das Ticket erstmal, bis wieder so eine Situation auftritt.

**Comment by Aybee** [comment]
Ja, einverstanden. Ich kenne die internen Abläufe, auch die mit dem Cache und dem DBAFS, nicht wirklich gut, sodass ich das debuggen könnte. Wenn überhaupt, müsste vielleicht ein Entwickler, der wirklich im Core "sitzt" sich den Code ansehen und mal überlegen, in welchen Situationen und warum das auftreten könnte.
