### ISSUE TITLE
Individuelles Templates - umbenennen wird nicht übernommen

### ISSUE THREAD

**Issue by saress** [contao/core#7863]
Erstellt man ein beliebiges Template z.b. ce_text_custom, ordnet es bei einem Artikel dem Inhaltselement als "Individuelles Template" zu und benennt das Template dann unter "Layout -> Templates" um, dann erhält man im Frontend einen Fehler, da die Änderung beim Inhaltselement nicht übernommen wurde und man das namentlich geänderte Template im Artikel (bzw. in allen Artikeln) neu zuordnen muss.

Fatal error: Uncaught exception Exception with message Could not find template "ce_text_custom" thrown in system/modules/core/library/Contao/TemplateLoader.php on line 123

Getestet mit Contao 3.5 RC1.

**Comment by aschempp** [comment]
Das ist „by design“ und ein Konfigurationsfehler, ich glaube nicht dass wir das ändern können…

**Comment by leofeyer** [comment]
Das glaube ich auch nicht. Sonst müssten wir eine Usage-Tabelle pflegen.

**Comment by saress** [comment]
Ok, das ist natürlich nicht gut, denn wenn man an verschiedenen Stellen individuelle Templates einsetzt, dann kann man alle möglichen Artikel durchsuchen und hoffen, dass man nicht irgendwo etwas übersieht.

Ich hab leider keine Ahnung wie das intern funktioniert, aber wäre es vielleicht eine Möglichkeit einfach nach der Änderung des Template-Namens in der tl_content die Spalten customTpl bzw. ggfs. galleryTpl upzudaten?

**Comment by aschempp** [comment]
Das System weis nicht welches Template wo zugewiesen wird. Aber vielleicht könnte man die Fehlermeldung verbessern?

**Comment by saress** [comment]
Wenn ich mir die Datenbank so anschaue, dann steht da in der tl_content in der Spalte customTpl der Filename des Templates drin und in der galleryTpl der Filename des customized Gallery-Templates. Wenn man also den Filenamen unter Layout->Templates  ändert, was spricht dagegen einfach alle File-Referenzen auf den neuen Dateinamen mit einer SQL-Abfrage zu ändern? 

Gleiches würde übrigens auch beim Löschen des Templates Sinn machen, denn da tritt der Fehler logischerweise auch auf.

**Comment by Aybee** [comment]
:+1: für eine Lösung.

Ist mir auch schon des öfteren passiert, dass ich da ne Fehlermeldung auf ein nicht mehr existierendes Template bekam und auf die Suche gehen musste.

**Comment by aschempp** [comment]
> Wenn ich mir die Datenbank so anschaue, dann steht da in der tl_content in der Spalte customTpl der Filename des Templates drin und in der galleryTpl der Filename des customized Gallery-Templates.

Das sind bei weitem nicht alle Vorkommnisse. In beinahe jedem Frontend-Modul kannst du ein Template wählen. Im Navigationsmodul noch eins. Im Seitenlayout die MooTools + jQuery + Javascript + Analytics-Templates. Und jeder Entwickler kann seine eigenen Felder für diesen Fall hinzufügen…
