### ISSUE TITLE
Sortierung Newsletter in Modul Persönliche Daten  im Frontend und Backend

### ISSUE THREAD

**Issue by Acta2000** [contao/core#7864]
Getestet in der aktuellen Contao Demo: 

Sachverhalt: 
Legt man im Contao Newsletter Modul verschiedene Newsletter an, so erfolgt die Sortierung im Backend unter dem Menüpunkt Newsletter und in den Modul-Einstellungen des Moduls "Persönliche Daten" in Alphabetischer Reihenfolge. 

Problem: 
Bindet man das Modul Persönliche Daten im Frontend ein, und erlaubt das Abonnieren der Newsletter wird dort eine völlig andere, nicht logische Reihenfolge verwendet. Die Reihenfolge wird entsprechend Hinweis vom "the_scrat" im Cotao Forum (https://community.contao.org/de/showthread.php?57453-Reihenfolge-Newsletter-im-Modul-Pers%F6nliche-Daten&p=372052#post372052) über die Datenbank Tabelle "tl_newsletter_channel" gesteuert. Die Sortierung erfolgt im Frontend weder Alphabetisch (was wünschenswert wäre) noch nach der ID des Newsletters. 

Es ist aktuell nicht möglich, den Nutzern eine Sinnvolle Sortierung der vorhanden Newsletter zur Verfügung zu stellen.

**Comment by leofeyer** [comment]
Behoben in 616195217655a92de53931613eb04622b6739d68.

**Comment by Acta2000** [comment]
Thank You!
