### ISSUE TITLE
[3.4.5] Deleting website root leaves orphaned pages, articles and content elements

### ISSUE THREAD

**Issue by Aybee** [contao/core#7866]
In a multilingual page I deleted a website root of a language I don't need anymore. Therefore I clicked on "delete page". By accident I found out that none of it's subpages (incl. articles and CEs) were deleted. None of the orphaned pages are visible in BE as the root (pid) did not exist anymore.

Not tested yet: Does this only happen with website roots or other pages with subpages too?

Das wäre mir garnicht aufgefallen, wenn ich nicht in einem CE einen Artikel hätte includen müssen und mich wunderte, warum da so viele Artikel angeboten wurden, was die Auswahl irgendwie unmöglich machte.

Quick fix if this happened to you:
1. Find out the ID of deleted website root by looking for pid in DB->tl_page of orphaned records.
2. Create a record by copying a root page (phpmyadmin). 
3. Set the ID of this new record to the ID of the deleted root. 
4. go to BE - now you will see all pages again.
5. Open this root as breadcrumb
6. toggle all open
7. use "edit multiple" to delete all pages

**Comment by leofeyer** [comment]
@contao/developers How do we solve this?

**Comment by aschempp** [comment]
This should be cleaned up by `revieseTable`?

**Comment by leofeyer** [comment]
Are you sure?

**Comment by aschempp** [comment]
Pretty sure, but I don't know when it will happen. I remember I noticed this a very long time ago, but I couldn't find a ticket. Still worth investigating, but `reviseTable` might be a starting point :-)

**Comment by discordier** [comment]
Erm... I hope not. reviseTable is intended for removing "stale" (unsaved and children of non existing parents ) items.
To widen this scope now over the whole parent table hierarchy will be pretty slow and almost unmanagable. We will then have to load all data containers and examine the complete hierarchy.

Articles and CE will already be properly pruned, the question is, why when deleting a page the children of said one are not deleted.

For this, refer to [this line](https://github.com/contao/core/blob/6f0fdc3d951fcc03b97ea34ea19c510dbc160724/system/modules/core/drivers/DC_Table.php#L1425-1425):
```php
if ($this->Database->fieldExists('pid', $this->strTable) && !strlen($this->ptable))
```
This is correct, we are fetching all children from tl_page here BUT:
```php
// Delete all child records if there is a child table
if (!empty($this->ctable))
{
	foreach ($delete[$this->strTable] as $id)
	{
		$this->deleteChilds($this->strTable, $id, $delete);
	}
}
```
This will now only delete children from `tl_article` and `tl_content`. IMO the bug should be fixed by defining `tl_page`also as ctable of itself in the dca.

**Comment by aschempp** [comment]
> reviseTable is intended for removing "stale" (unsaved and children of non existing parents ) items.

Isn't that exactly the case here?

**Comment by discordier** [comment]
Nope, as you would have to potentially scrape every table and retrieve all datasets but in the other direction as from `delete()`.

**Comment by aschempp** [comment]
Well `reviseTable` is executed on the current table you're viewing, so that should clean up `tl_page` and not "every table".

**Comment by discordier** [comment]
Yeah, but `tl_page` is a child of itself, `tl_article` is a child as well, `tl_content` is a child of that one, `tl_something` might be parent of `tl_page` or any other table etc.
When using `reviseTable` you would have to examine the whole tree of table dependencies to really get rid of all dangling items (as they might not yet be dangling but only when another entry has been pruned of which the grand-grand-parent is dangling).
By only visiting the current page the initial issue will not be solved, it can ONLY be solved (performantly) by deleting all references "downstream" upon delete of an item and NOT by deleting via checking if the parent is still existent when examining a table.

**Comment by aschempp** [comment]
I don't get your point. `reviseTable` is supposed to clean up, whatever that means…?

**Comment by leofeyer** [comment]
We have discussed this on Mumble on August 13th and none of use managed to reproduce the issue. We have even tried the online demo. How do we reproduce the issue?

**Comment by Aybee** [comment]
Now I also can not reproduce it anymore.

Das ist ja verrückt, der Root war definitiv verschwunden ohne den Rest auch zu löschen. Ich habe versucht es zu rekonstruieren, dazu musste ich erst nochmal rausfinden, in welchem Projekt das war. Ich hoffe ich habe das richtige gefunden. 
> Contao 3.4.5
Erweiterungen:
BackendThemeExtended 1.0.6 14, Version 1.0.6, Build 15 verfügbar
changelanguage 2.2.8 6, Version 2.2.8, Build 8 verfügbar
rocksolid-frontend-helper 1.1.1 6 Version 1.2.2, Build 4 verfügbar

Dann kann das Ticket wohl als "invalid" ausgezeichnet werden. Hoffen wir mal, dass es nur eine zufällige Aneinanderreihung von diversen Umständen war.
