### ISSUE TITLE
Add the module name to tl_user_group::getExcludedFields()

### ISSUE THREAD

**Issue by daniel-nemeth** [contao/core#7868]
Hi community!

I'm often using a lot of extensions for my Contao website. When creating a user group, I sometimes have the problem, for example in tl_content, that the label of two different extensions has the same value (e.g. Title).

I know, the intention of every extension developer should be using self-explaining field labels, but thats not the standard.

My question to the community: Would it be a good idea to add the module name after the field label (e.g. Title [core] or Website title [x-seo]) in the system/modules/core/dca/tl_user_group.php file?

Thanks,
Daniel

**Comment by Toflar** [comment]
Imho best would be to show the table and field name. So something like that:

* Title (tl_page.title)
* Website title (tl_page.x-seo_title)
* etc.

I'm +1 on that feature. Should be fairly easy to implement but it's for Contao 4.1 so we actually need to move that issue. How shall we proceed with issues that actually belong to contao-core but have been created here @contao/developers?

**Comment by daniel-nemeth** [comment]
With the code from Contao 3.5, the DCA tablename is provided within the loop. So this was a nice idea Toflar.

Thx.

**Comment by daniel-nemeth** [comment]
The same feature would be nice for the Edit multiple mode in tl_content. Should I open a seperate ticket?

**Comment by aschempp** [comment]
So the real difference whould be to add the database field name to the permissions and edit-multiple, right?

**Comment by daniel-nemeth** [comment]
Yes.

**Comment by leofeyer** [comment]
Implemented for user groups and the "edit multiple" mode in contao/core-bundle@d1d2d4e32cc1ea8d90d4a4ea325ab08451bf912e.
