### ISSUE TITLE
One step action

### ISSUE THREAD

**Issue by EDsolution** [contao/core#7870]
Hi.
This is more feature than bug.
I really miss in contao one step action. Explanation what I have in mind.
Let say you have English version of site and you want to have DE also. So you duplicate whole EN root. When you do this the DE root pages are unpublished. If you want to publish it you must do this individual for every page or via multiple edit. But in both cases you must select Publish for every page manualy. 

What if you would have option to apply 1 option for every selected page. 
For example:
You would select Edit multiple, select pages you want and than you should have new button Edit All.
When you select this everything should be the same, you select the fields which you want to edit.
But when you select field and click Continue you should have only 1 option for every selected page, not 1 option per selected page. 

This would be much easier to edit big page with a lot of site structure also if this would be part of all Edit, than it would be usefull everywhere in Contao (modules, news, etc.).

**Comment by Aybee** [comment]
This is already built in. Edit multiple - select all - override.
Or put this into your dcaconfig.php
```php
// Pages are instantly published
$GLOBALS['TL_DCA']['tl_page']['fields']['published']['default'] = true;
```

**Comment by EDsolution** [comment]
Hehe...blush :)

TNX!
