### ISSUE TITLE
Search via module ID

### ISSUE THREAD

**Issue by EDsolution** [contao/core#7871]
Hi.
It would be very nice if you could seach via module ID in backend. So for example if you set search field to ID and you enter 2 it should show you module with ID 2. Simple and very effective.

When you do translations and you copy all EN modules and you must than insert module for DE and you have in fe_template 
if (lang....'en') 
{{insert_module::2}}
if (lang....'de') 
{{insert_module::XX}}

it's very frustrating now how to find english module, easiest way now is to search via phpmyadmin.
But if you could than search in BE you would just type module ID, you will get the name of Module and than you can easly find BE module for DE. (the same name as EN): for example module name:
EN - Search box (id 2)
DE - Search box (id X).

**Comment by leofeyer** [comment]
> easiest way now is to search via phpmyadmin

The easiest way right now is to open any content element and to simply adjust the URL. But you can easily add `'search' => true` in the DCA to enable searching by ID if you prefer to detour :)
