### ISSUE TITLE
New article button without access rights

### ISSUE THREAD

**Issue by aschempp** [contao/core#7873]
I have added a user to my system that is not allowed to edit any article hierarchy. There is still a button to add a new article, but all the paste buttons are disabled. It would make sense to hide the button in this case.

**Comment by leofeyer** [comment]
Can you please post a screenshot?

**Comment by aschempp** [comment]
Fairly easy to reproduce in the demo:
 - Make sure no page has access right assigned
 - Add access rights to the root page and remove rights to change article structure (but allow to edit)
 - Make sure the Editors group can see the page tree
 - Login as j.wilson, you will see this:


![bildschirmfoto 2015-11-26 um 09 52 29](https://cloud.githubusercontent.com/assets/1073273/11418790/720cdc10-9423-11e5-90ce-834f25ae8c54.png)
![bildschirmfoto 2015-11-26 um 09 52 34](https://cloud.githubusercontent.com/assets/1073273/11418791/7276a6cc-9423-11e5-85b7-276a574953d6.png)

**Comment by leofeyer** [comment]
Fixing this is not trivial, because we would have to check *every* page to make sure that no one grants permission to create new articles.
