### ISSUE TITLE
Links on contao.org

### ISSUE THREAD

**Issue by syncgw** [contao/core#7874]
Pls update "Nützliche Links" on https://contao.org/de/download.html. They all point to nowhere...

**Comment by fritzmg** [comment]
Also in the changelogs (e.g. https://contao.org/en/changelog/versions/4.0.html) there is always a paragraph at the bottom that says

> A detailed roadmap and an overview of already completed milestones is available at the [development page](http://dev.contao.org/).

However, that "development page" (http://dev.contao.org/) does not exist anymore.

**Comment by leofeyer** [comment]
This issue does not belong here (and will be resolved as soon as we have relaunched the website).
