### ISSUE TITLE
Vorschaubilder bei Inhaltselementen "Bild" im Backend mit responsive Images in Originalgröße

### ISSUE THREAD

**Issue by Kahmoon** [contao/core#7875]
Servus beisammen,

mir ist in 3.4.x schon aufgefallen das Vorschaubilder im Backend (Inhaltslement) nicht mehr klein skaliert werden, sondern in voller Größe angezeigt werden, sobald man eine Vorlage der responsive Images verwendet. Leider wurde das mit 3.5 nicht geändert... 

Nutzt man keine Vorlage dann haben die Vorschaubilder eine max-width die nicht überschritten wird. Das wird aber ignoriert sobald man eine Vorlage verwendet.

Siehe Anhang (Das Bild ist im Original 1100px breit)

**Mit Bildvorgabe - Contao zeigt das Bild in Originalgröße:**

![](https://cloud.githubusercontent.com/assets/1192057/8772038/9c3298b0-2ec8-11e5-954d-52a9510c00b8.jpg)

**Ohne Bildvorgabe -> Contao verwendet maximale Breite:**

![](https://cloud.githubusercontent.com/assets/1192057/8772043/a34359a0-2ec8-11e5-8ebb-ed1ade32df96.jpg)

Dieses Verhalten ist in der Demo reproduzierbar.

Forumbeitrag: http://bit.ly/1MDSMsD

VG
Frank

**Comment by Kahmoon** [comment]
Nachtrag:
Auch Galerien sind davon betroffen. Hab mein Ticket oben mit einem Bild editiert

**Comment by Kahmoon** [comment]
Kleiner Nachtrag:

Im Backend-Source finde ich folgendes:

<script>window.respimage&&window.respimage({elements: [document.images[document.images.length - 1]]});</script>

[HTML]
<figure class="image_container protected">
<picture>
<source srcset="assets/images/6/2015-05-09_M%C3%A4delsabend_8991_web-4c995df6.jpg 1x, assets/images/1/2015-05-09_M%C3%A4delsabend_8991_web-e73c6391.jpg 2x" media="(max-width: 360px)">
<source srcset="assets/images/5/2015-05-09_M%C3%A4delsabend_8991_web-e84aaeb5.jpg 1x, assets/images/4/2015-05-09_M%C3%A4delsabend_8991_web-95f0eba4.jpg 2x" media="(max-width: 480px)">
<source srcset="assets/images/a/2015-05-09_M%C3%A4delsabend_8991_web-e612e9da.jpg" media="(max-width: 767px)">
<source srcset="assets/images/9/2015-05-09_M%C3%A4delsabend_8991_web-be8109e9.jpg" media="(min-width: 980px) AND (max-width: 1140px)">
<img src="assets/images/b/2015-05-09_M%C3%A4delsabend_8991_web-ff601d6b.jpg" sizes="100vw" alt="2015-05-09_Mädelsabend_8991_web.jpg"></picture>
<script>window.respimage&&window.respimage({elements: [document.images[document.images.length - 1]]});</script></figure>
[/HTML]


Wenn ich mein Backend per strg + M skaliere und die Seite neu lade, nimmt er tatsächlich eine der reponsive Größen. Eigentlich sollte sowas ja nicht im Backend sein oder?

**Comment by bekanntmacher** [comment]
Danke für die Nachricht,
wir sind ab dem 10. August gerne wieder für Sie da!

E-Mails werden nicht weitergeleitet. Unsere Geschäftsnummer 071 222 90 10 bleibt aber während dieser Zeit bedient. 

Sommergrüsse vom Team bekanntmacher
...
bekanntmacher, Schokoladenweg 10, 9011 St. Gallen 
T 071 222 90 10, http://www.bekanntmacher.ch

**Comment by fritzmg** [comment]
> Eigentlich sollte sowas ja nicht im Backend sein oder?

Wie schon im Thread erwähnt spielt das keine Rolle. Der ausgegebene HTML Code ist der Gleiche.

**Comment by leofeyer** [comment]
Wie genau lässt sich das in der Onlinedemo reproduzieren?

**Comment by Kahmoon** [comment]
In dem man bei Bildgröße eine Einstellung aus den responsive Images nimmt.

**Comment by leofeyer** [comment]
Bitte nicht so genau, sonst verstehen wir es und können das Problem am Ende wirklich reproduzieren und beheben.

**Comment by Kahmoon** [comment]
....

Ich habs doch oben schon genau beschrieben? Mit Bildern! :-]

Ich lege in der Demo einen Eintrag für responsive Images an. Dann gehe ich in irgendein Inhaltselemnt "Bild". Verwende ich dort die normalen Breite/Höhe Einstellungen ist in der Vorschau des Inhaltselement die Grafik verkleinert (Darstellung OK). Verwende ich in diesem Element aber die Einstellung aus den responive Images ist das Bild in der Vorschau des Inhaltselement riesig.

Siehe Bilder

**Comment by fritzmg** [comment]
Wie schon im Thread erwähnt konnte ich das Problem nicht reproduzieren mit den Einstellungen die du dort gepostet hast.

Poste auch hier nochmal die **exakten** Einstellungen (vollständig, nicht so wie im Thread, wo du Teile davon weggelassen hast), die du jeweils verwendest für so ein Bild Inhaltselement.

**Comment by Kahmoon** [comment]
Ich habe gerade zum Test einfach nur eine neue Imagesize 800x600 ohne irgendeine andere Einstellung gemacht. Noch 38 Min in der Demo verfügbar :dancer: 

http://demo.contao.org/contao/main.php?do=article&table=tl_content&id=1&rt=f335d349b57656f39e864791989a40f0&ref=ac608901

Ohne Einstellung Responsive Image
![](http://mmtz.de/media/img/20-07-2015-NON-RSPI.jpg)

Mit Einstellung für Responsive Image
![](http://mmtz.de/media/img/20-07-2015-RSPI.jpg)

**Comment by fritzmg** [comment]
Naja, das entspricht aber immer noch nicht dem, was du ursprünglich hier gepostet hast. Das Bild wird nicht in **Originalgröße** im Backend ausgegeben, sondern in der angegebenen Größe der Responsive Image Einstellung, also 800x600.

Das Problem, dass du eigentlich hier meinst ist, dass die in der Funktion `addImageToTemplate` hardgecodete Maximalgröße von 320px für das Backend ( https://github.com/contao/core/blob/3.5.0/system/modules/core/library/Contao/Controller.php#L1436 ) bei Bildinhaltselementen nicht greift, wenn eine Responsive Image Einstellung ausgewählt wurde.

**Comment by leofeyer** [comment]
Behoben in a95af91c2f6963f665cc65f25eddeba58c9c0049.

**Comment by Kahmoon** [comment]
Ja, genau von dieser Funktion "addImageToTemplate" mit 320px wusste ich nichts. Aber genau darum geht es.

Wennd as Bild größer ist als diese 800x600 wurde es auch breiter angezeigt bzw. hat sich drunter reingeschoben. Aber ist ja jetzt behoben. Danke.
