### ISSUE TITLE
At save Layout or Theme: PHP Fatal error:  Call to undefined function Contao\hex2bin()

### ISSUE THREAD

**Issue by mrezler** [contao/core#7876]
Result is a white page and this error in the error log:

[09-Jun-2015 07:28:49 UTC] PHP Fatal error:  Call to undefined function Contao\hex2bin() in /var/www/system/modules/core/library/Contao/String.php on line 544

contao 3.5

**Comment by Toflar** [comment]
What PHP-Version do you have?

**Comment by leofeyer** [comment]
Contao 3.5 requires at least PHP 5.4.

**Comment by danielhoover** [comment]
Leo - this is wrong or at least not clearly written within the documentation of Contao 3.5:

https://docs.contao.org/books/manual/3.5/de/01-installation/den-live-server-konfigurieren.html#contao-systemvoraussetzungen

Quote: "Contao benötigt einen Webserver wie Apache oder IIS mit PHP- und MySQL-Support. PHP muss mindestens in der Version 5.3.7 vorliegen und MySQL in der Version 5.0.3."

Also wrong within the english Version: https://docs.contao.org/books/manual/3.5/en/01-installation/configuring-the-live-server.html#contao-system-requirements

**Comment by aschempp** [comment]
The documentation is not up to date.

**Comment by leofeyer** [comment]
@danielhoover You could help us out and fix this by creating a pull request here: https://github.com/contao/docs

**Comment by aschempp** [comment]
There’s one in progress but not moving forward: https://github.com/contao/docs/pull/321/files
