### ISSUE TITLE
Problem with Model Registry fetching models of extended classes

### ISSUE THREAD

**Issue by DyaGa** [contao/core#7877]
For example.

I have a module `z_app` with table `tl_table` and model `AppTableModel`.
Also. I have another module `z_app_ext` which adds some new fields to `tl_table` and I use a model `AppExtTableModel` in this module which extends `AppTableModel` class.

The problem here:

```php
$TableObj = AppTableModel::findByPk(95);
$ExtTableObj = AppExtTableModel::findByPk(95);
```

Expected to get object of class `AppExtTableModel` in var `$ExtTableObj` but got `AppTableModel` class object.

This is in Contao 3.4, but, as I see 3.5 has the same problem.

**Comment by Toflar** [comment]
That should not be the case as we use late static binding. Can you post your code?

**Comment by Toflar** [comment]
Ah I see your point. That's never going to work. We could change this https://github.com/contao/core/blob/master/system/modules/core/library/Contao/Model.php#L1248-L1251 into

```php
protected static function createModelFromDbResult(\Database\Result $objResult)
{
    $strClass = \Model::getClassFromTable(static::getTable());
    return new $strClass($objResult);
}
```

which would allow you to define that `AppExtTableModel` is responsible for `tl_table` but that would also cause `AppTableModel::findByPk(95);` to return an instance of `AppExtTableModel`. That's something we cannot solve.

**Comment by DyaGa** [comment]
Method `\Model::getClassFromTable(static::getTable())` will return model class name from `$GLOBALS['TL_MODELS']` array (if it is defined). But in my case, class `AppTableModel` is only defined in `z_app` module. Because, I have another module `z_app_ext2` which also adds some fields to `tl_table` and has `AppExt2TableModel`.

I mean, the problem is a little bit wider (to my mind):

```php
$TableObj = AppTableModel::findByPk(95);
// expected - object class AppTableModel
// return - AppTableModel

$ExtTableObj = AppExtTableModel::findByPk(95);
// expected - AppExtTableModel
// return - AppTableModel

$Ext2TableObj = AppExt2TableModel::findByPk(95);
// expected - AppExt2TableModel
// return - AppTableModel
```

I think the code, should be something like this:

```php
protected static function createModelFromDbResult(\Database\Result $objResult)
{
    $strClass = get_called_class();
    return new $strClass($objResult);
}
```

**Comment by Toflar** [comment]
The thing is, it will not work. The model that is registered to the registry can only be an instance of one class. Basically, you cannot have multiple classes responsible for the same model.

**Comment by DyaGa** [comment]
In other words, you mean one table - one model?

**Comment by Toflar** [comment]
Yes. The registry keeps the very same object (`spl_object_hash()`) in the memory. As soon as you change instances it will be a different object and actually render the whole registry more or less useless.

**Comment by DyaGa** [comment]
But, is it right? For example, `tl_module` table. Custom modules can add additional fields. and every module works with custom fields. Yes, for this reason we could output data with `ModuleModule` classes but it is Module and it's main goal to output Module data. But what class should we use to manipulate data. I mean, should we register models. I think we should register `Database\Result` objects, not Models.

**Comment by Toflar** [comment]
> But, is it right?

No it's not but I guess it cannot be changed. It's just the way it is :) If you want to have more sophisticated ORM features then you should probably checkout Contao 4 and use any third party PHP library such as Doctrine ORM or Laravel's Eloquent to work with models.
There's nothing else I can add to this discussion right now.

**Comment by aschempp** [comment]
You should be aware that models in Contao are only data containers. They are not supposed to contain functionality, so there shouldnt be a reason for you to add methods. 

Yes, Isotope does this wrong ;-)

**Comment by DyaGa** [comment]
But, where should we collect such data manipulation methods then? To my mind, model is an easy way to do this.

**Comment by Toflar** [comment]
@DyaGa You are right. It's perfectly fine to have fat models. That's actually a recommended approach. However, it doesn't work for Contao as you can see.

**Comment by DyaGa** [comment]
Yes, I see.. Untill Model Registry it works fine for me. And now, I have some problems with it. Ok. I'll try to find a solution. Thanks.

**Comment by Toflar** [comment]
We also can't just convert the instance of `AppTableModel` into `AppExtTableModel` when retrieving from the registry as that would result in a different object instance. So I'd recommend you don't extend the model but add your modifying methods to a service like that:

```php
class TableModelHelperService
{
    public function __construct(\TableModel $model);
    public function doThat();
    public function getThis();
}
```

**Comment by DyaGa** [comment]
Thank you. I thought about such service class also.

Another solution to my mind can be:

```php
$TableObj = AppTableModel::findByPk(95);
$ExtTableObj = new AppExtTableModel;
$ExtTableObj->setRow($TableObj->row());
```

But I don't like it.. Will try service class.

**Comment by aschempp** [comment]
We should improve the `createModelFromDbResult` method as @Toflar explained, then model classes can be overwritten locally.

**Comment by leofeyer** [comment]
Will you be creating a pull request?

**Comment by Toflar** [comment]
I have already added the code that needs to be changed in https://github.com/contao/core/issues/7877#issuecomment-110362941

**Comment by leofeyer** [comment]
You also wrote:

> but that would also cause `AppTableModel::findByPk(95);` to return an instance of `AppExtTableModel`.

**Comment by Toflar** [comment]
Yes, obviously that would be the case. So either `get_called_class()` or just ignore the issue as it's not gonna work anyway.

**Comment by leofeyer** [comment]
As discussed on Mumble, there is no real solution to this problem, as `get_called_class()` does not solve the registry problem. The next best solution is what you have proposed yourself:

```php
$TableObj = AppTableModel::findByPk(95);
$ExtTableObj = new AppExtTableModel();
$ExtTableObj->setRow($TableObj->row());
```

It might not be nice, but the only possibility to "extend" a model (which is not really supported in Contao).
