### ISSUE TITLE
3.4.5 Controller::sendFileToBrowser seems to prevent session from saving data

### ISSUE THREAD

**Issue by bcat-eu** [contao/core#7879]
This does not work (no session data saved):

    $this->Session->set('testKey', 'testValue');    
    \Controller::sendFileToBrowser($objFile->path);

This does work (explicit call to destructor to make session save data)

    $this->Session->set('testKey', 'testValue'); 
    $this->Session->__destruct();
    \Controller::sendFileToBrowser($objFile->path);

Can have something to do with this line: https://github.com/contao/core/blob/master/system/modules/core/library/Contao/File.php#L711 Might make sense to destruct session object in this method.

**Comment by leofeyer** [comment]
`File::sendFileToBrowser()` explicitly closes the session to prevent session locking during the download.

**Comment by bcat-eu** [comment]
then all set() calls that were made before are lost cause (as far as I understand) session destructor shoots blanks trying to save session data 
https://github.com/contao/core/blob/master/system/modules/core/library/Contao/Session.php#L69-L85

if you destruct the session before calling `session_write_close();` the data would be saved first

**Comment by leofeyer** [comment]
Fixed in daf42101ea7cbe8e65a2190ca3630ab02d36a43b.

**Comment by leofeyer** [comment]
I have reverted the changes, because on the one hand, we don't know if the change has any side-effects and on the other hand, the problem does no longer occur in Contao 4 anyway.
