### ISSUE TITLE
3.5.0 Error in the class "DropZone.php" for the FileUpload.

### ISSUE THREAD

**Issue by bennie99** [contao/core#7880]
Error in the class "DropZone.php" for the FileUpload.
If the value for "$ this-> getMaximumUploadSize ()" is not evenly divisable by 1024 a javascript error is reportetd.
Proposal for correction:
line 30 in /system/modules/core/classes/DropZone.php

change

		$intMaxSize = ($this->getMaximumUploadSize() / 1024 / 1024);

to

		$intMaxSize = (int)($this->getMaximumUploadSize() / 1024 / 1024);

**Comment by leofeyer** [comment]
Fixed in 73841ddef28cf82de17c450f10478b2209a17426.
