### ISSUE TITLE
[4.0.0] Templatenamen

### ISSUE THREAD

**Issue by xantippe** [contao/core#7881]
https://contao.org/de/news/contao_4-0-RC1.html

sollten dann nicht alle mit Binnenmajuskel geschireben werden? also

* ce_accordion -> ce_accordionSingle
* ce_accordion_start -> ce_accordionStart
* ce_accordion_stop -> ce_accordionStop
* ce_slider_start -> ce_sliderStart
* ce_slider_stop -> ce_sliderStop
* mod_article_list -> mod_articleList (!)
* mod_article_nav -> mod_articleNav (!)
* mod_random_image -> mod_randomImage
* mod_event -> mod_eventReader (!)
* mod_newsletter_list -> mod_newsletterList
* mod_newsletter_reader -> mod_newsletterReader

**Comment by leofeyer** [comment]
Für diesen Einwand ist es nun leider zu spät. Die nächste Möglichkeit, die Template-Namen zu ändern, wäre Contao 5. Außerdem war die Mehrheit der Templates, die auf "list" oder "reader" enden, ohne Camel-Case benannt, so dass die Anpassung der Templates hier zumindest für eine Vereinheitlichung gesorgt hat.
