### ISSUE TITLE
[3.5.] Frontendmodule Template; Escape Inserttag Syntax

### ISSUE THREAD

**Issue by Fruchuxs** [contao/core#7883]
Hallo,

besteht die Möglichkeit, Contao dazu zu überreden, `{{}}` nicht zu interpretieren bzw. nicht durch "nichts" zu ersetzen? Versuche zZ ein Contao Frontendmodul zu entwickeln, welches [vue.js](http://vuejs.org/) verwendet (geht um das dynamische Abrufen und Darstellen von JSON Daten eines Webservices).

Allerdings ersetzt Contao mir {{<bez>}} immer durch einen leeren String und somit ist es unmöglich vue.js zu verwenden. Typisches Escaping wie `\{{` oder `\{\{` haben leider zu keinen Resultaten geführt.

Beispiel:
```php
<?php $this->extend('block_unsearchable'); ?>
<?php $this->block('content'); ?>

<ul id="list">
    <li v-repeat="i : list">
        {{i}}
    </li>
</ul>

<?php $this->endblock(); ?>

```

P.S.: Ich kämpfe mich schon seit einigen Tagen durch die "Extension Erstellung für Contao", gibt es zu diesem Thema aktuelle Dokumentationen die ich übersehen habe? 

Grüße,
Fruchuxs

**Comment by BugBuster1701** [comment]
Hast du noch weitere externe Erweiterungen installiert? Das sieht so typisch danach aus, dass eine Erweiterung die u.a. Insert Tags ersetzt, die nicht mit false beantwortet, wenn diese nicht zuständig ist.

**Comment by Fruchuxs** [comment]
Nein. Nur contao-community-alliance/composer-client

**Comment by aschempp** [comment]
Inserttags werden durch leer ersetzt, wenn unbekannt…

**Comment by fiedsch** [comment]
Vielleicht könntest Du `Vue.config.delimiters = ['open tag', 'close tag'];` mit anderen Delimitern/Tags verwenden

**Comment by Toflar** [comment]
Escapen kannst du `[{]` und `[}]`.

**Comment by Fruchuxs** [comment]
@fiedsch Generell ja. Wenn ich dann allerdings andere Vue Components verwende, wird es dann ggf. Probleme geben (allerdings noch nicht getestet).

@Toflar Das funktioniert. `[{]var[}]` ersetzt Contao durch `{{var}}`. Falls nicht schon vorhanden, kann man das ja ggf. in der Dokumentation unter "Inserttags" ergänzen.

Danke an alle.
