### ISSUE TITLE
featurerequest: prefill forms through url

### ISSUE THREAD

**Issue by klml** [contao/core#7885]
I would like it to have a out of the box function to prefill my contao forms through url.

for example http://demo.contao.org/en/applications.html#salutation=mr&email=jon@example.com&name=Jon should give me a prefilled form with "Salutation": "Ms", "Name": "Jon", etc

I think this can be done clientside, non-JS-user still can fill in the whole form.

This would allow admins to send out customized links and to unburden users from filling in all the form. (eg newsletter, request for products, feedback for customer support etc)

This feature was discusses on [stackoverflow](http://stackoverflow.com/questions/14070105/pre-fill-form-field-via-url-in-html) and a working (but serverside) [example](http://tumblr.followd.co.nz/login.php?email=masterofcoins)

**Comment by Toflar** [comment]
You can develop this on your own with JS? Why should that be a CMS functionality?

**Comment by klml** [comment]
> Why should that be a CMS functionality?

Imho it is a often needed feature for forms in general.

**Comment by Toflar** [comment]
I don’t think so. I’m -1 on this.

**Comment by discordier** [comment]
-1 from me also.
