### ISSUE TITLE
Der Punkt "Systemwartung" im BE verschwindet

### ISSUE THREAD

**Issue by KlausGrenoble** [contao/core#7886]
Der Punkt "maintenance" (Systemwartung) verschwindet, wenn man die installierte Erweiterung "maintenance" deaktiviert. @tab meint, es wäre möglicherweise wegen der Namensgleichheit im core.
@tab:"Ich kann jedenfalls gut damit leben". Ist auch meine Meinung.
https://community.contao.org/de/showthread.php?57612-3-2-21-Punkt-quot-Systemwartung-quot-fehlt-im-BE&p=373332&viewfull=1#post373332

**Comment by leofeyer** [comment]
> möglicherweise wegen der Namensgleichheit im core

Ja, so ist es. Die Erweiterung muss einen anderen Key registrieren.
