### ISSUE TITLE
newsletter ModuleSubscribe sets up wrong error variable when no channels are selected

### ISSUE THREAD

**Issue by cdxOo** [contao/core#7887]
How to reproduce: create a page that contains  mod_subscribe and mod_unsubscribe -> submit subscribe form w/o selecting any channels -> error message appears on unsubscribe form instead of subscribe form

how to fix: substitute "UNSUBSCRIBE_ERROR" to "SUBSCRIBE_ERROR" in ModuleSubscribe.php line 207 (as of commit 4779b0c20e81ff4150d9cd48a95661f12e9b0480) 
see: https://github.com/contao/core/blob/4779b0c20e81ff4150d9cd48a95661f12e9b0480/system/modules/newsletter/modules/ModuleSubscribe.php

might also appear in older version (3.4.5 is where i found it)

**Comment by leofeyer** [comment]
Does this issue still occur in version 3.5.0?

**Comment by ibksoft** [comment]
The bug still exists in 3.5.9. 

In ModuleSubscribe.php, line 204: change UNSUBSCRIBE_ERROR to SUBSRIBE_ERROR to fix it.

**Comment by leofeyer** [comment]
Fixed in b902775afab575de76a9311da1b4bdf46b4865eb.
