### ISSUE TITLE
Usage of empty() with function return values in PHP < 5.5

### ISSUE THREAD

**Issue by gartram** [contao/core#7888]
PHP Version 5.4.25
Contao Version 4.0.0
File: `vendor/contao/core-bundle/src/Resources/contao/classes/FrontendTemplate.php`
Line: 188

**Error:**

```
php.CRITICAL: Fatal Compile Error: Can't use function return value in write context {"type":64,"file":"[...]/vendor/contao/core-bundle/src/Resources/contao/classes/FrontendTemplate.php","line":188,"level":7159,"stack":[]} []
```

**Reproduction:**

Create an empty Contao 4.0.0 site (in my case: layout without header and footer and without Layout Builder etc.), root page, start page and no custom sections.

**Offending line:**
```php
if (empty(array_filter($this->sections)))
```
  

**Problem:**

In PHP versions prior to 5.5, empty can't be used with function return values:

```
Note:
Prior to PHP 5.5, empty() only supports variables; anything else will result in a parse error. In other words, the following will not work: empty(trim($name)). Instead, use trim($name) == false.
```

**Solution:**

Change offending line to:

```php
if (count(array_filter($this->sections)) == 0)
```

That solves the problem for me (site is displayed without error), but I don't know which other parts of the system are affected by the usage of `empty()`.

**Comment by fritzmg** [comment]
`empty` should only be used if it is unknown whether a variable has been set or not (which in this case is not applicable anyway). iirc, you don't even have to use `count`, an empty array cast to boolean should return false anyway.

**Comment by leofeyer** [comment]
See https://github.com/contao/core-bundle/pull/310.
