### ISSUE TITLE
3.5.0 news/NewsModel > parseArticle: Bildgröße wid nicht übernommen

### ISSUE THREAD

**Issue by mhger** [contao/core#7890]
Durch eine falsche Variablenverwendung werden in der NewsList Ansicht alle Bilder auf einen Standardwert von 150x150 Pixel skaliert und die Einstellung aus dem Backend greifen nicht.

Es wird fälschlicher Weise auf **$this->imageSize** statt **$this->size** zugegriffen.

Korrigierte Fassung, Zeilen 178-186
```
				if ($this->size != '')
				{
					$size = deserialize($this->size);

					if ($size[0] > 0 || $size[1] > 0 || is_numeric($size[2]))
					{
						$arrArticle['size'] = $this->size;
					}
				}
```

**Comment by fritzmg** [comment]
Es ist `$this->imgSize` nicht `$this->imageSize` und `$this->imgSize` stimmt schon, denn `$this` ist in diesem Fall das NewsList Modul und der Parameter in `tl_module` heißt eben `imgSize`: https://github.com/contao/core/blob/master/system/modules/core/dca/tl_module.php#L537
