### ISSUE TITLE
normalize.css integrieren?

### ISSUE THREAD

**Issue by dazzle89** [contao/core#7891]
Hallo,

ich weiß nicht ob darüber schon mal diskutiert wurde, aber ich persönlich würde es sinnvoll finden, wenn normalize.css im Core eingebunden wird. Also eine neue Checkbox im Seitenlayout, sodass man dort je nach Geschmack entweder die normalize oder den Reset auswählen kann.

**Comment by Aybee** [comment]
:+1:

**Comment by leofeyer** [comment]
Du kannst beliebige CSS-Dateien unter "externe Stylesheets" einbinden. Wähle einfach das Reset-Stylesheet des Contao-Frameworks ab und lade das Deiner Wahl.

**Comment by a-v-l** [comment]
👍 
Normalize.css ist mittlerweile zur Standard-Lösung geworden. Ich plädiere dafür den CSS-Reset durch Normalize.css zu ersetzen. Mit Leos Argument könnte man auch den CSS-Reset oder das 12-Spalten Grid aus dem core entfernen.

**Comment by Aybee** [comment]
> @a-v-l  Ich plädiere dafür den CSS-Reset durch Normalize.css zu ersetzen.

Das wäre wohl ein BC break.
