### ISSUE TITLE
Composer needs to much memory (1und1)

### ISSUE THREAD

**Issue by jenda77** [contao/core#7894]
I have tried to use the composer client. Unfortunately, I cannot use because it needs to much memory that I don´t get from my hosting service. It would be great to reduce the usage of the memory of composer. I am using Contao 3.5

``` Fatal error: Out of memory (allocated 74711040) (tried to allocate 16999335 bytes) in phar://....Composer/Util/RemoteFilesystem.php on line 247 ```

**Comment by leofeyer** [comment]
The Composer client repo is here: https://github.com/contao-community-alliance/composer-client/issues
