### ISSUE TITLE
BE: Paste top and pagination

### ISSUE THREAD

**Issue by dmolineus** [contao/core#7895]
When being on the second the content element view and want to paste an element on top (No matter if moving, copying or create new) it is always moved to the top of the first page.

Steps to reproduce:
 - Have a multi page content element view
 - Go to 2nd page
 - Cut an element and paste to top

**Comment by leofeyer** [comment]
?

**Comment by aschempp** [comment]
I do understand the problem. If you have a mode 4 view and paginate the results, the header paste button does not paste before the first element you see, but at the top of all results.

**Comment by leofeyer** [comment]
That seems correct to me.

**Comment by dmolineus** [comment]
Imhp It's confusing for editors as they would expect to get it paste on the top of the current page.

**Comment by discordier** [comment]
@leofeyer How do you paste to the top of the second page then?

1. Go to the first page.
2. Scroll to the very bottom.
3. Paste "after".

Seems unlogical to me from an editors perspective. From the coders perspective it is correct though.

**Comment by leofeyer** [comment]
Fixed in a1962469c5f46a942e7c3908c8c2324f3741e672.
