### ISSUE TITLE
Wrong label for insert button in content elements

### ISSUE THREAD

**Issue by seaneble** [contao/core#7897]
The label for inserting new content elements is wrong:

![wrong-label](https://cloud.githubusercontent.com/assets/1255670/8351547/6754203a-1b2e-11e5-9a0f-b78653b14d1f.png)

This occurs everywhere: In articles, in news items, in events. The label always says "Neue Formatdefinition oben erstellen", which originates from the stylesheet editor.

**Comment by leofeyer** [comment]
This seems to be a problem with the translation memory on transifex.com, because the labels are correct in the version 3.2 language files. Anyway, I have fixed the translation now.

**Comment by seaneble** [comment]
Thanks for investigating! :smile:
