### ISSUE TITLE
input_field_callback und Funktion "Mehrere bearbeiten"

### ISSUE THREAD

**Issue by mwitzmann** [contao/core#7898]
Nutzt man in seiner Erweiterung einen "input_field_callback" und die Funktion "Mehrere bearbeiten" in Contao, so hat das Feld mit dem "input_field_callback" keine Übersetzung (auch nicht unter Angabe eines Labels), da der DataContainer (DC_TABLE) dies unterbindet:

```php
// Show all non-excluded fields
foreach ($fields as $field)
{
   if ($field == 'pid' || $field == 'sorting' || (!$GLOBALS['TL_DCA'][$this->strTable]['fields'][$field]['exclude'] && !$GLOBALS['TL_DCA'][$this->strTable]['fields'][$field]['eval']['doNotShow'] && (strlen($GLOBALS['TL_DCA'][$this->strTable]['fields'][$field]['inputType']) || is_array($GLOBALS['TL_DCA'][$this->strTable]['fields'][$field]['input_field_callback']))))
	{
		$options .= '
  		<input type="checkbox" name="all_fields[]" id="all_'.$field.'" class="tl_checkbox" value="'.specialchars($field).'"> <label for="all_'.$field.'" class="tl_checkbox_label">'.($GLOBALS['TL_DCA'][$this->strTable]['fields'][$field]['label'][0] ?: $GLOBALS['TL_LANG']['MSC'][$field][0]).'</label><br>';
	}
}
```

Dadurch ist die Funktion "Mehrere bearbeiten" gerade für solche Fälle nicht mehr nutzbar, da man nicht erkennen kann, was man bearbeitet.

Ist dies so gewollt? Falls ja, warum? Übersehe ich etwas?

**Comment by aschempp** [comment]
Nach meinem Wissen muss im `input_field_callback` alles selber gemacht werden, inklusive dem Label und dem Speichern? Oder meinst du in der Feldauswahl?

**Comment by mwitzmann** [comment]
Ich meine die Feldauswahl. Hier wäre es gut, wenn man die im "Label" definierte Übersetzung anzeigen könnte. 

Mit freundlichen Grüßen
Mirko Witzmann

-----------------------------
info@mirko-witzmann.de
www.mirko-witzmann.de

Von unterwegs gesendet

**Comment by aschempp** [comment]
Mach bitte mal einen Screenshot wie die Auswahl jetzt aussieht, ggf. markieren welches das entsprechende Feld ist.

**Comment by mwitzmann** [comment]
Anbei der Screenshot:
![contao_mehrere_bearbeiten](https://cloud.githubusercontent.com/assets/6212507/8373662/0b5f9c98-1bef-11e5-91a1-83c96afe06f7.jpg)

**Comment by aschempp** [comment]
Danke. Das sieht für mich klar nach einen Bug aus.

**Comment by leofeyer** [comment]
Kannst Du die DCA-Konfiguration Deines Feldes bitte posten?

**Comment by discordier** [comment]
interessanter ist IMO hierbei was er in
`$GLOBALS['TL_DCA'][$this->strTable]['fields'][$field]['label'][0]` oder `$GLOBALS['TL_LANG']['MSC'][$field][0]` stehen hat. Ich vermute dass seine Sprachdatei nicht geladen ist oder aber gar keine existiert.

Im edit wird hierbei ja dann der Feldname angezeigt, hier jedoch kein fallback auf selbigen mehr vorgenommen.

**Comment by mwitzmann** [comment]
Ich muss gestehen, dass ich den Fehler nicht reproduziert bekomme: Ein erneuter Test hat ergeben, dass alles korrekt funktioniert und mein oben genannte Code-Auszug bestätigt dies ja auch.
Ich weiß nicht, was mich da geritten hat. Falls ich herausfinde, wodurch das Label nicht angezeigt wird, dann melde ich mich erneut.
Ich würde sagen, dass es zurzeit Fehlalarm ist?

**Comment by discordier** [comment]
Dann mach das ticket bitte zu.
