### ISSUE TITLE
Missing Inserttag in official overview

### ISSUE THREAD

**Issue by madmaharaja** [contao/core#7899]
I recently wanted to look up in the official documentation if there is an inserttag that displays the alias of the root page of a website. There is none mentioned but following the logic that these three tags are mentioned for parent pages
{{page::mainAlias}}
{{page::mainTitle}}
{{page::mainPageTitle}}
but only these two are mentioned for the root page
{{page::rootTitle}}
{{page::rootPageTitle}}
I just went ahead and tried to see what happens if I use {{page::rootAlias}}
Low and behold -- it worked! So apparently this inserttag was probably left out in the overview by mistake
https://github.com/contao/docs/blob/3.2/manual/de/04-inhalte-verwalten/inserttags.md
Or is there a specific reason for that?

**Comment by aschempp** [comment]
See https://github.com/contao/docs/pull/240

**Comment by madmaharaja** [comment]
Thanks for the reply -- sorry, didn't see there was already a ticket.
