### ISSUE TITLE
packagist.org still at version 3.5.0-beta1 (composer create-project)

### ISSUE THREAD

**Issue by Fuzzyma** [contao/core#7900]
The Contao-Version in the packagist.org-repo is still at Version 3.5.0-beta1.
So I cant run `composer create-project "contao/core":"3.5.*"`.

Any Idea what is the problem here? Usually packagist.org pulls weekly (or via hook)

**Comment by leofeyer** [comment]
Please report this issue at the maintainer's repo (see https://packagist.org/packages/contao/core).

**Comment by BugBuster1701** [comment]
Geht nicht, weil ein geforktes Repo keinen Issues Bereich hat.

**Comment by BugBuster1701** [comment]
Ich habe es der CCA mal getwittert.

**Comment by discordier** [comment]
Fixed.
