### ISSUE TITLE
ModuleNews::getMetaFields does not check for comments module

### ISSUE THREAD

**Issue by fritzmg** [contao/core#7901]
The `news` extension checks for the presence of the `comments` extension in various places, so that no error occurs if the `comments` extension is disabled.

However, if you enable the option `comments` in the `news_metaFields` of any of the news modules a
```
Fatal error:  Class 'CommentsModel' not found
```
will occur [here](https://github.com/contao/core/blob/master/system/modules/news/modules/ModuleNews.php#L289).

See also https://community.contao.org/de/showthread.php?57835-Seiten-nicht-erreichbar-wegen-Kommentarfunktion-in-Nachrichten

**Comment by leofeyer** [comment]
Fixed in 27ceba60a279b994a0de17c0b5273eb364470040.
