### ISSUE TITLE
Drag&Drop sorting active with notSortable=true

### ISSUE THREAD

**Issue by aschempp** [contao/core#7902]
Even though I set `notSortable` to true, my DCA has drag and drop sorting due to https://github.com/contao/core/blob/master/system/modules/core/drivers/DC_Table.php#L4267-L4275

A simple additional if-check for `&& !$GLOBALS['TL_DCA'][$this->strTable]['config']['notSortable']` should do the trick.

**Comment by leofeyer** [comment]
Fixed in f76f4f5e6ab81e66c2efdbdc83e3a4343aa6e228.
