### ISSUE TITLE
"Zur zuletzt besuchten Seite" im Login-Modul ignoriert Hashes.

### ISSUE THREAD

**Issue by Defcon0** [contao/core#7906]
Wenn ich eine Seite aufrufe, deren Link ein Hash hinten dran hat (#blabla), wird dieser beim Zurückleiten schlicht ignoriert.

**Comment by aschempp** [comment]
Das geht nicht anders. Der Hash wird nie an den Server übermittelt, weshalb Contao diesen auch nicht speichern kann.

**Comment by Defcon0** [comment]
Mhm, ungünstig. Es über die Session zu lösen, geht ja vermutlich auch nicht, weil beim Login die Session des eingeloggten Nutzers wiederhergestellt wird, oder?

Ich nutze das ganze für eine Veranstaltungsanmeldung. Wenn man sich während des Workflows einloggen möchte, kann man das tun und wird danach wieder zurückgeleitet.

**Comment by aschempp** [comment]
Session ist auch Serverseitig, also dasselbe Problem.

**Comment by Defcon0** [comment]
OK, dann mache ich es clientseitig. Danke für die Aufklärung :)!
