### ISSUE TITLE
Prefill the alt-Attribute in the News/Events teaser

### ISSUE THREAD

**Issue by MacKP** [contao/core#7907]
When i insert an Image in the Teser from a News or Events Contao doesn't prefill the Attributes in the Teaser

Tested with Contao 3.4.5 and 3.5.0

regards

**Comment by Aybee** [comment]
Subject alt-Tag => alt-Attribute?

**Comment by MacKP** [comment]
OMG Yes.. thx a lot. It's really to hot here...

**Comment by Toflar** [comment]
@leofeyer: This is indeed a bug. `tl_news.addImage` and `tl_news.singleSRC` as well as  `tl_calendar_events.addImage` and `tl_calendar_events.singleSRC` do not consider the file meta data. They just use `Controller::addImageToTemplate()` but do not pass the `alt` attribute.

**Comment by MacKP** [comment]
+1 thx @Toflar

**Comment by leofeyer** [comment]
Hm, I have just added an image to the "New Contao Versions in short intervalls" news and I have entered "Foobar" as alt text. Then I have changed the template of the simple news list to `news_latest` and checked the source code. The alt attribute was there.

How do I reproduce this?

**Comment by MacKP** [comment]
When you enter an alt text it will work. But there is no prefill from the alt text and underline when you have an image with these from the file-manager.

---
german:
Es geht darum, das der Text aus dem Dateimanager nicht übernommen wird an den beiden Stellen wo auch der Teasertext eingegeben werden kann. Ansonsten wird der ja überall übernommen nur eben da nicht.

**Comment by leofeyer** [comment]
Tut mir leid, ich verstehe es immer noch nicht. Wo genau wird der Text übernommen?

**Comment by Toflar** [comment]
To illustrate in code I guess something like that (untested, just to illustrate) is missing:

```diff
+++ /system/modules/news/modules/ModuleNews.php
@@ -185,6 +185,17 @@ abstract class ModuleNews extends \Module
 					}
 				}
 
+				$arrMeta = \Frontend::getMetaData($objModel->meta, $objPage->language);
+
+				// Use the file name as title if none is given
+				if ($arrMeta['title'] == '')
+				{
+					$arrMeta['title'] = specialchars($objModel->basename);
+				}
+
+				$arrArticle['alt']      = $arrMeta['title'];
+				$arrArticle['caption']  = $arrMeta['caption'];
+
 				$arrArticle['singleSRC'] = $objModel->path;
 				$this->addImageToTemplate($objTemplate, $arrArticle);
 			}

```

**Comment by leofeyer** [comment]
@Toflar This cannot be it. We are never using the meta information for single source items, because there are fields to enter the alt text, title and links. We are only using the meta information for multi source items such as downloads or galleries.

@MacKP Was genau bedeutet "Ansonsten wird der ja überall übernommen nur eben da nicht."?

**Comment by MacKP** [comment]
Überall wäre zum Beispiel bei der Texteingabe in einer News. Dort dann anwählen, das man zum Text auch ein Bild einfügen möchte. Dann werden dort diese Felder vorausgefüllt (und das ist ein einzelnes Bild). Ich versteh jetzt nicht so ganz warum das auf einmal bei einem einzelnen Bild nicht mehr der Fall sein sollte. Das ist doch ein Feature dieser Eingabe.

**Comment by leofeyer** [comment]
I have just found [this](https://github.com/contao/core/blob/master/system/modules/core/dca/tl_content.php#L1678-L1715). Do you mean this?

**Comment by MacKP** [comment]
@leofeyer ich glaube genau das ist das was ich meine. Zumindest klingt der Kommentar genau so ;-) Dieses Verhalten ist auf jeden Fall so. Bis auf die beiden Stellen, wo man die Teaser Angaben macht zu einer News bzw. zu einem Event.

**Comment by leofeyer** [comment]
Now I understand what you mean. However, it is not possible to automatically fill in these fields for news, events or FAQs, because we do not know the language of the page these items will be shown eventually. We can only fill in the fields for content elements in articles (because they are related to a page, which is related to a root page, which has a language information).

**Comment by asaage** [comment]
plausible but unsatisfying...

**Comment by MacKP** [comment]
@leofeyer ich versteh dann nicht, warum das in der News selber gemacht werden kann (Detailseite). Da wäre dann ja genau das selbe Problem.
Ansonsten könnte man entweder die Einstellung von der Weiterleitungsseite nehmen oder eben noch mal ne Einstellung in dem Archiv selber...

Viele Grüße

**Comment by leofeyer** [comment]
Stimmt, es gibt ja noch die Detailseite :)

**Comment by MacKP** [comment]
Danke! :) +1

**Comment by asaage** [comment]
:+1:

**Comment by leofeyer** [comment]
Behoben in 3d4e6211cc01799fa11993b43bb4457a89fc9012.
