### ISSUE TITLE
Login-Modul leitet nicht auf "zuletzt besuchte Seite", sondern auf cron.php

### ISSUE THREAD

**Issue by Defcon0** [contao/core#7908]
Hallo,

ich hatte hier mal ein Issue gepostet:

https://github.com/contao/core/issues/7640

Diese Änderung habe ich als Hotfix in die entsprechenden Klassen gesetzt und der Fehler scheint nun seltener aufzutreten. Er tritt aber trotzdem noch auf. Leider aber nur sporadisch und ich habe noch kein Muster erkennen können in dem der Fehler auftritt. Daher könnte es schwierig werden, das zu reproduzieren :(

Evtl. nutzt aber vielleicht jemandem der Hinweis, dass LAST_PAGE_VISITED dann auf cron gesetzt ist. Unter welchen Umständen kann das überhaupt passieren?

**Comment by Defcon0** [comment]
Das Problem ist übrigens noch immer das gleiche: In der Session steht sowohl bei current wie auch bei last system/cron/cron.php (wie in meinem anderen Beitrag, siehe oben).

**Comment by leofeyer** [comment]
@Toflar /cc

**Comment by Toflar** [comment]
`LAST_PAGE_VISITED` enthält `System::getReferer()` insofern ist ja klar, dass das da dann drin steht. Die Frage ist also warum enthält `System::getReferer()` die URL zur `cron.php` und das ist eigentlich ziemlich offensichtlich: Der Referer wird sowohl beim `BackendUser::__destruct()` als auch beim `FrontendUser::__destruct()` gespeichert bzw. in Contao 4 als Request Listener. Sprich:

Contao 3: Irgendwer der in einem Cronjob entweder ein BackendUser oder ein FrontendUser Objekt lädt, sorgt dafür, dass durch den Aufruf des Destruktors der Referer aktualisiert wird. Lösungsvorschlag: Im `FrontendCron` Controller eine `TL_IS_CRON` (o. ä.) definieren und beim Speichern jeweils prüfen.

Contao 4: Etwas ähnliches wie bei Contao 3 einfach mit Request-Attribut statt Konstante oder evtl. sogar dynamisch den Listener deaktivieren, wenn die Cron-Route aufgerufen wird.

**Comment by aschempp** [comment]
Warum nicht einfach die Route prüfen? Machen wir doch eigentlich schon damit nur bei `contao_backend` gespeichert wird?

**Comment by leofeyer** [comment]
Wie am 13. August auf Mumble besprochen, tritt das Problem nur im Frontend auf, da in der `BackendUser`-Klasse bereits wie von @aschempp angemerkt die Route geprüft wird (`if (TL_SCRIPT == 'contao/main.php')`). Dasselbe sollten wir in der Klasse `FrontendUser`-Klasse auch machen.

**Comment by leofeyer** [comment]
Behoben in 496145df74750adf83a9e79f159aa9c8b749b9d0.
