### ISSUE TITLE
Page Caching messes Languages up

### ISSUE THREAD

**Issue by SpeGal** [contao/core#7909]
I cannot use page caching anymore after the update from 3.4.5 to 3.5.

We have four languages running on the same domain. German is set as fallback language. Nevertheless English was always delivered after the update. Before the update everything worked correctly.

After deleting the page cache everything went back to normal -> German was delivered for German browser settings. But after a few hours again English was shown when going to the main domain. That happened repetetly (we emptied the cache, it worked for a while, didn`t work anymore, delete cache ...). Then we decided to deactivate the "Cache Page" in the page structur settings for all four languages (deactivating only for German didn't work). Since we deactivated page caching entierly, everything works smoothly again (except page speed since the pages are not cached anymore).

The Contao Community in the forum didn't have a solution either. Do you guys have any ideas what is going wrong? It's probably gonna be hard to reproduce this in the demo since it takes a while for the cache to be fully built up (in our case multiple hours).

**Comment by fritzmg** [comment]
"Building the cache" does not take several hours. imho you just didn't find the exact reproduction yet. I am guessing it possibly happens either

* as soon as a German user is automatically shown the german page and an English user is directly opening the english page
* or the other way around
* or when both get the English and German page respectively

Maybe these situations produce different cash keys and there is a bug somewhere so that at one point only the English version is shown automatically.

**Comment by SpeGal** [comment]
I was able to test the whole scenario in all different kind of cases now.

The result is:
As long as only one language has cached the start page, everything is okay. But as soon as two or more languages have a cache file for the initial page, the system gets messed up. Which user gets which language delivered depends then on the existence of a cache file first, then on the preferences of the browser setting. 

That means for example: 
If I have German as the first and English as the second entry in my browser settings but a cache file only exists for English so far, I will get the English cache file delivered instead of the German page and therefore German never gets cached at all!

Also if I only have German and no other language in my browser settings but another language got cached first, I will get that cached language instead of my preference (German) and therefore German will never get cached either! Other languages therefore also might never get cached depending on the settings of the users.

It might be even more complicated then I just explained but you guys are the pros and I hope you'll find the error soon. For now we'll leave the cache deactivated.

**Comment by fritzmg** [comment]
I guess this fix #7618 causes this issue now. Before Contao 3.5, a cache version of the index page was never created under certain circumstances. Now it's fixed, but the detection of which cache file to use (if at all) is still buggy.

**Comment by fritzmg** [comment]
Hm... I was unable to reproduce this though.

**Comment by SpeGal** [comment]
Well, it was difficult to reproduce it on one computer/in one browser because on my computer German was always shown. Other people complaint though and so I used a different browser (all cleaned out) and yes, English appeared (even with German browser settings). And the fallback language should not be cached befor one or two other languages are (so there musn't be a cache file for the main language).

So set up a page with three languages. Activate caching for all three pages (I set it on 24 hours). Use a different browser/computer set to one of the not main languages and access the main domain. Then do the same thing for the other not main language. Empty the cache of the browser and set the browser to the main language as the first language and the other languages as second or third (I had German as de and de-de). Then access page again and it doesn't show the main language but one of the other two. Then you can delete the page cache and browser cache and the main page will be shown again. It worked for me several times.

**Comment by SpeGal** [comment]
Can this issue be opened up again, please?! It is still a problem!

**Comment by Toflar** [comment]
It is open?

**Comment by SpeGal** [comment]
Sorry, only saw the "closed" sign a bit further up. But now I realize it was for the related issue.
Shouldn't this issue be assigned to the 3.5.1 though?

**Comment by Toflar** [comment]
It will be assigned or commented or closed or whatever by the time it's processed. Just be patient and wait.

**Comment by leofeyer** [comment]
Can this be reproduced in the online demo?

**Comment by SpeGal** [comment]
I could not reproduce this in the online demo because it is being used by other people, too. I tried several times but somebody else always messed up the results by their own testing. Maybe you have a system running where only you have access to? The steps to reproduce this issue are stated above.
