### ISSUE TITLE
Dialog 'main.php Speichern' erscheint beim Abspeichern eines Artikels

### ISSUE THREAD

**Issue by d003232** [contao/core#7910]
Ich möchte einen ganz normalen Artikel speichern. Das funktioniert normalerweise auch ohne Schwierigkeiten. Nun wollte ich einen größeren Artikel aus einer anderen Seite übernehmen. Sobald ich im Artikel auf Speichern drücke erscheint der Speichern Dialog von Windows und ich kann offenbar die Datei 'main.php' speichern??!

Das Phänomen tritt auf, sobald ich einen externen Link direkt in den Artikel einfüge. Ohne den externen Link wird alles ohne Schwierigkeiten gespeichert. Wenn ich den externen Link über den Seitenwähler einfüge (d.h. Instertag) funktioniert es.

Am nächsten Tag ohne weitere Änderung hat es wieder funktioniert. Ich konnte den externen Testlink in den Artikel einfügen und speichern. Nachdem ich dann wieder eine große Menge per copy & paste eingefügt habe tritt der Fehler wieder auf. Nun lässt sich auch der Testlink alleine nicht mehr abspeichern.
![main_php](https://cloud.githubusercontent.com/assets/13165419/8498657/aab460fe-2189-11e5-88c1-4df42622a552.JPG)

Contao 3.5.0, Backend Windows 8.1

**Comment by Aybee** [comment]
Das hatte ich auch letztens mal in nem Kunden Backend. Weiß aber nicht mehr genau welche Contao Version es war und wie ich es behoben hatte. Ich meine es lag daran, dass die .htaccess nicht aktiviert war. Auf jeden Fall funktionierte es dann irgendwann wieder.

**Comment by leofeyer** [comment]
Das ist vermutlich kein Contao-Problem sondern ein Server-Problem (z.B. Skriplaufzeit?). Am besten fragst Du mal bei Deinem Server-Administrator nach.

**Comment by garyee** [comment]
Habe auch gerade das Problem bei einem Kunden (Hoster: Strato), bei dem es schon einen anderen Fehler gab der auf die Skriplaufzeit zurück zuführen war. Von daher wohl keine schlechte Vermutung. Obwohl ich nicht ganz verstehe, was die Scriptlaufzeit damit zutun hat, dass er mit die Datei die er ausführen soll zum Download anbietet.

**Comment by cmichael-de** [comment]
Bei Strato unter Sicherheit den Filter gegen Gästebuch-Spam abschalten hilft.
