### ISSUE TITLE
Eventlist shows teaser not details when redirect not default (ref. #6315)

### ISSUE THREAD

**Issue by JustAMinion** [contao/core#7911]
Hi Leo,

i've an event with teaser and an attached article for detailed information. I use two diffrent presentation forms (two diferent domains shareing the same calender):
1.: i use an event redirect to an other page containing other detailed information
2.: i use a detailed event-full-presentation to show the in the event saved information

With issue #6315 the detailed information in the event is skipped when the redirection target is different to 'default', so i get only the teaser text.

I found the critical code in file "Events.php" (Line 283 ff). The field for the event detailed information is overwritten by 'true' in case of a different source than 'default'.

<code>
[...]
if ($objEvents->source != 'default')
{
    $arrEvent['details'] = true;
}
else 
{
[...]
</code>

I found an interpreting template in 'event_teaser.xhtml'.

My question, why is it necessary to re-use the "details"-field and not to introduce an other event-member such as "isExternalRedirect"?

I hacked a patch in 'Events.php' but this is not an permanent solution :( ...

Thanks for reading an regards.

Using Contao 3.5.0

**Comment by fritzmg** [comment]
I didn't quite get what you mean. Do you want to use a redirect target other than default (i.e. the reader page) __and__ you want to provide more detailed information in the event with content elements? If so, why?

**Comment by JustAMinion** [comment]
Why? because it was possible until contao 2.9 ... 

However. The backend allows (regardless the redirection setting) to add additional information to every event. So I expect this information in the event class member "details" and nothing else. To re-use this member to hold information if there is an external redirect or not, limits the functionality of the event class for undiscovered unknown future usages... so, why? 

Why not introduce an additional interface signal "hasExternRedirect" = true/false...

<code> $arrEvent['hasExternRedirect'] = ($objEvents->source != 'default'); </code>

... and let the template decide, what to do with this information and how to present ist and how to create the redirect link. It is just a bool more. (and you don't have to check if the member is currently a bool or not...it should be typesafe too :))

For my very complicated webpage constellation (i have to admit: 3 eventlist on 3 different domains combined in an "overall complete project"-eventlist on a 4. domain), I need to have this possiblity or I have to double all events involved or "hack" the "Events.php" (but this is not update resistent). 

The best solution (imho) is to delegate the decisions for peresentation to the templates, which can every user design as he/she likes (with update resistency!)

Thanks for reading again and reagrds.

**Comment by fritzmg** [comment]
> Why? because it was possible until contao 2.9 ...

Well, that's not really an answer to my question ;). What is the purpose of having additional information in the event, if there is (by default) no way of actually having a link to the details of the event (since the event links to something other than its detail page now)? Where do you display this additional information?

Also what you are saying makes no sense, because prior to Contao 3 you didn't even have the possibility to provide detailed information with content elements. You only had a single text field that was called `details` what is now called the `teaser` since Contao 3 and the `teaser` is always available, regardless of the event's target.

**Comment by JustAMinion** [comment]
hmmm ... no ;) ok, the event structure was different:
- there was a plain text teaser field
- and a textfield for styled detailed information (so the field existed!)

With Contao 3 the styled details field is gone and (during the update) existing detailed information were appended as text element. So, it was possible to have detailed infos regardless of the redirect switch ;)

ok, what I do: I have multiple domains for multiple organisations:
- Main Organisation (MO)
- Sub Orga 1 (SO1)
- Sub Orga 2 (SO2)

SO1 has large projects: multiple events have the same detailed information (differs only in date and location). Every project has a single project-description article and all concerned events redirect to a static page containing this article with all dates and locations well formed and sorted (on Domain for SO1) (i call it a project oriented presentation).

SO2 has small projects: every event has unique detailed information. The redirection is to an event reader (default). And I have a event full text list, that present all upcoming events with their detailed information (not teaser, handled by template).

For SO1 and S02 the teaser is a simple line of text presented in the sidebar for upcoming events (with "read more" link of course).

MO ist the main organisation (with the same sidebar, the read-more-links redirects to the SO1- or SO2-domains and the defined redirect target.) But I want to present detailed information for all events from SO1 and SO2 combined in a full text event list (in this case it does not matter, if multiple events from S01 have the same content. In this case it is a event oriented presentation.). It works fine for SO2 because the events were redirected to the default target and the details-string is rendered. for SO1 events the details string is skipped and the teaser is doubled ...

thanks again.

**Comment by fritzmg** [comment]
> hmmm ... no ;) ok, the event structure was different:
> 
> * there was a plain text teaser field
> * and a textfield for styled detailed information (so the field existed!)

True, sorry, yeah.


> With Contao 3 the styled details field is gone and (during the update) existing detailed information were appended as text element. So, it was possible to have detailed infos regardless of the redirect switch ;)

Well, no, the Contao 3 updater only creates text elements for news and events where the target is `default`: https://github.com/contao/core/blob/d11b2257e9a9c2b9b5daadb383298782f3a065d0/system/modules/core/library/Contao/Database/Updater.php#L298


In any case, you can still construct the detailed content for each event in an event template like this:
```php
if (is_bool($this->details))
{
	$strDetails = '';
	if (($objElement = \ContentModel::findPublishedByPidAndTable($this->id, 'tl_calendar_events')) !== null)
	{
		while ($objElement->next())
		{
			$strDetails .= $this->getContentElement($objElement->current());
		}
	}
	$this->details = $strDetails?: $this->details;
}
```
(untested)

**Comment by JustAMinion** [comment]
Thanks for the code! :) I try it the next time. If it works it could be a plan B if the "\ContentModel" is available from template scope.

**Comment by fritzmg** [comment]
Should be, as well as `\Controller::getContentElement`

**Comment by leofeyer** [comment]
If your problem has been solved, please don't forget to close the ticket.

**Comment by JustAMinion** [comment]
Sorry... my time for web programming is very limited right now.... ;) 

I've tried the code, and there is an other problem (see ModuleEventlist.php, line 271):

    // Show the teaser text of redirect events (see #6315)
    if (is_bool($event['details']))
    {
        $objTemplate->details = $event['teaser'];
    }

So I always gets the teaser. The bool was masked with #6315.

I tried to re-render always all details for all events by removing the "is_bool" statement. This works, but I consider that work around not as solution (so I will not close this ticket). Nevertheless ist seems update resistant to me.

**Comment by fritzmg** [comment]
I don't think there won't be another solution, since you are using the Events outside the intended usage.

Instead of `is_bool` you could do:
```php
if ($this->source != 'default')
{
    $strDetails = '';
    if (($objElement = \ContentModel::findPublishedByPidAndTable($this->id, 'tl_calendar_events')) !== null)
    {
        while ($objElement->next())
        {
            $strDetails .= $this->getContentElement($objElement->current());
        }
    }
    $this->details = $strDetails?: $this->details;
}
```
This would be slightly more efficient.
