### ISSUE TITLE
Model-Mehod not directly accessible via Collection

### ISSUE THREAD

**Issue by Fuzzyma** [contao/core#7912]
To use a Method you defined on a model you would write `$model->method()`. However since all data from a model are avaible from the Collection-Object after calling `$collection->next()` it should be possible to call a models method from a collection, too (`$collection->methodFromModel()`).
At the moment you have to write `$collection->current()->methodFromModel()` which is imo unexpected.

Would be nice if you could include a `__call()`-method to the collection-class to route the method calls to the current model.

**Comment by Toflar** [comment]
I don't think that's a good idea. The method belongs to the model and not to the collection so the current behaviour is absolutely correct. :-1: from me.

**Comment by Fuzzyma** [comment]
When I follow your thoughts it comes out that all properties from the model also belongs to the model and not to the collection. Accessing them via `$collection->modelProperty` shouldnt be allowed either.

There shouldnt be a difference

**Comment by Toflar** [comment]
That's true, it shouldn't be allowed either. It's wrong.

**Comment by aschempp** [comment]
It's also due to old style code. You should use `foreach ($collection as $model)` instead of `$collection->next()`.

**Comment by Fuzzyma** [comment]
oh thats new to me. Several docs point to `next()`.
Ok - this issue is invalid then
