### ISSUE TITLE
[3.4.2] Probleme bei Cron Aufruf, wenn ein Template nur im Custom-Ordner ist

### ISSUE THREAD

**Issue by amenk** [contao/core#7913]
Wir verwenden ein Template in `templates/kunde/dma_eg_default_video.html5`

Wenn man jetzt die Tabelle tl_cron leert (und damit den Cron Job forciert) und daraufhin http://localhost/system/cron/cron.php aufruft, so kommt folgender Fehler:

	[07-Jul-2015 14:36:19 GMT] PHP Fatal error: Uncaught exception 'Exception' with message 'Could not find template "dma_eg_default_video"' thrown in /var/www/kunde/web/system/modules/core/library/Contao/TemplateLoader.php on line 123
	#0 /var/www/kunde/web/system/modules/core/library/Contao/Controller.php(75): Contao\TemplateLoader::getPath('dma_eg_default_...', 'html5')
	#1 /var/www/kunde/web/system/modules/core/library/Contao/BaseTemplate.php(81): Contao\Controller::getTemplate('dma_eg_default_...', 'html5')
	#2 /var/www/kunde/web/system/modules/core/library/Contao/Template.php(238): Contao\BaseTemplate->parse()
	#3 /var/www/kunde/web/system/modules/core/classes/FrontendTemplate.php(38): Contao\Template->parse()
	#4 /var/www/kunde/web/system/modules/dma_elementgenerator/DMAElementGenerator.php(652): Contao\FrontendTemplate->parse()
	#5 /var/www/kunde/web/system/modules/dma_elementgenerator/DMAElementGenerator.php(48): DMAElementGenerator->compile(Object(DMAElementGeneratorContent))
	#6 /var/www/kunde/web/system/modules/dma_elementgenerator/DMAElementGeneratorContent.php(47): DMAElementGenerator->generate(Object(DMAElementGeneratorContent))
	#7 /var/www/kunde/web/system/modules/core/elements/ContentElement.php(165): DMAElementGeneratorContent->compile()
	#8 /var/www/kunde/web/system/modules/core/library/Contao/Controller.php(469): Contao\ContentElement->generate()
	#9 /var/www/kunde/web/system/modules/news/classes/News.php(186): Contao\Controller::getContentElement(Object(Contao\ContentModel))
	#10 /var/www/kunde/web/system/modules/news/classes/News.php(68): Contao\News->generateFiles(Array)
	#11 /var/www/kunde/web/system/modules/core/controllers/FrontendCron.php(100): Contao\News->generateFeeds()
	#12 /var/www/kunde/web/system/cron/cron.php(20): Contao\FrontendCron->run()
	#13 {main}

Workaround: verschiebt man das Template direkt nach `templates/`, so funktioniert es.

Der Cron Job sollte aber den auf der Seite verwendeten Templateordner auch in die Suche mit einbeziehen.

siehe https://github.com/DMAGmbH/dma_elementgenerator/issues/91

Das Ganze passiert aber auch, wenn ich z.B. eine Datei `ce_foo.html5` im Unterordner `kunde` anlege und für ein beliebiges Content Element auswähle. Ist also kein DMA EG Problem.

**Comment by BugBuster1701** [comment]
Templates werden grundsätzlich nicht rekursiv gesucht. Die Reihenfolge ist so:

* Verzeichnis templates des Moduls
* Verzeichnis TL_ROOT/templates (nicht rekursiv!)
* Im Template Verzeichnis des Themes, z.b. TL_ROOT/templates/mein_theme/meine_templates

**Comment by amenk** [comment]
Ja klar. Aber im normalen Frontend funktioniert es ja. Dort wird mein_theme korrekt verwendet. Wenn allerdings die cron.php aufgerufen wird, scheint mein_theme nicht bekannt zu sein (wild guess). Müsste man also irgendwie rausfinden, denke ich?

**Comment by aschempp** [comment]
Der Cron Job hat keinen Bezug zu irgend einer Seite, weshalb er auch keinen Bezug zu einem Theme haben kann. Hört sich nach einem Bug im DMA-Elementgenerator an, warum auch immer der in diesem Fall aufgerufen wird.

**Comment by amenk** [comment]
Ist vermutlich kein Bug im DMA EG. Passiert eben auch, wenn ich ein Template für ein beliebiges anderes Content Element setze welches in einem News Artikel liegt.
Anhand der News Element müsste man doch evtl. das Theme bestimmen können?
Das doofe ist halt, dass Aufgrund des Fehlers keine anderen Cron Jobs mehr ausgeführt werden.

**Comment by BugBuster1701** [comment]
Das liegt daran, dass ```getTemplate``` statt ```getTemplateGroup``` aufgerufen wird. Warum das aber so ist, bleibt erst mal offen.

**Comment by BugBuster1701** [comment]
ich vermute doch ein Fehler in DMA EG:
https://github.com/DMAGmbH/dma_elementgenerator/blob/master/src/dma_elementgenerator/DMAElementGenerator.php#L93

**Comment by BugBuster1701** [comment]
getTemplateGroup hat einen zweiten Parameter für die Theme-ID. Die wird also benötigt.

**Comment by BugBuster1701** [comment]
Nachtrag; an anderer Stelle wird getTemplateGroup verwendet, aber ohne den zweiten Parameter.

**Comment by amenk** [comment]
Wieso wurde das geschlossen? Ich habe doch geschrieben, der Fehler tritt auch auf, wenn man ein beliebiges nicht-DMA-EG-Content Element in eine News einfügt.

**Comment by aschempp** [comment]
Es liegt aber wohl daran dass das Modul im System installiert ist…

**Comment by amenk** [comment]
okay danke. Habe auch nochmal versucht es mit Contao 4 ohne das Modul zu reproduzieren. Da tritt der Fehler auch nicht auf.
