### ISSUE TITLE
[3.4.x] Konstanten fehlen beim Seitenausliefern aus dem Cache

### ISSUE THREAD

**Issue by BugBuster1701** [contao/core#7914]
Szenario: 
Eine Seite die im Cache ist, und Insert Tags beinhaltet die beim Ausliefern noch ersetzt werden müssen.
Diese Insert Tags rufen beispielsweise auf:

    \Picture::create(....)->getTemplateData();

das getTemplateData ruft getTemplateDataSource auf, dieses benötigt TL_FILES_URL , das aber nicht definiert ist. Grund ist, ```\Controller::setStaticUrls()``` wird erst für das Frontend in PageRegular aufgerufen, aber nicht beim Ausliefern aus dem Cache.
Folge ist, es kommen solche Dateipfade zurück:

    TL_FILES_URLassets/images/d/bla-cc9505ad.jpg

PHP gibt hier die Konstante als String aus, wenn diese nicht definiert ist.

Contao muss also dafür sorgen, das die Konstanten definiert sind, auch wenn die Seite aus dem Cache kommt.
In meiner Erweiterung habe ich das mal getestet durch einen Aufruf von:

    \Controller::setStaticUrls();

unmittelbar vor Aufruf der Picture::create Methode, hat funktioniert.

Ich denke in der FrontendIndex::outputFromCache Methode am Anfang wäre ein guter Ort diesen Aufruf ```\Controller::setStaticUrls();``` unterzubringen. Das habe ich aber noch nicht getestet.

**Comment by leofeyer** [comment]
Das Problem daran ist, dass es bei einer Seite aus dem Cache kein `$objPage` gibt. Somit könnten die beiden Konstanten höchstens auf Basis der in der `localconfig.php` gespeicherten statischen URLs gesetzt werden anstatt auf Basis der eventuell im Startpunkt der Webseite definierten URLs. Dies wiederum könnte zu inkonsistenten Ausgaben führen.

**Comment by aschempp** [comment]
Wir können die Variablen doch einfach in die Cache-Datei schreiben so wie das Cache timeout etc?

**Comment by leofeyer** [comment]
Sehr gute Idee.

**Comment by leofeyer** [comment]
Behoben in 6a5399a01948445e36a5615b66566049a85d2ea4.

**Comment by aschempp** [comment]
Was passiert wenn der Cache abgelaufen ist? Können wir die Variablen nicht nur setzen wenn wenn die Seite auch wirklich ausgeliefert wird? Oder ist das bereits zu spät?

**Comment by leofeyer** [comment]
Das ist zu spät, denn um zu erkennen, ob der Cache abgelaufen ist, müssen wir ein `include` der Datei machen. Und dabei werden dann auch die Konstanten definiert. Natürlich könnte man die Ausgabe in eine Funktion kapseln und diese nur ausführen, wenn der Cache noch valide ist.

**Comment by aschempp** [comment]
Ich meinte eher dass du in der include-Datei die Pfade wider als normale Variablen speicherst (so wie `$tstamp`) und dann setzt falls nötig.

**Comment by leofeyer** [comment]
Das geht auch :)

**Comment by leofeyer** [comment]
Geändert in 34e94f8014dfa073dd0b88fe131d4ec5788fb33d.
