### ISSUE TITLE
Add country for "Sint Maarten"

### ISSUE THREAD

**Issue by aschempp** [contao/core#7915]
The country "Sint Maarten" is missing in the country list (country code "sx": https://en.wikipedia.org/wiki/ISO_3166-2:SX).

Do not confuse with Saint Martin (country code "mf": https://en.wikipedia.org/wiki/ISO_3166-2:MF).

Maybe we can update the whole country list with latest ISO 3166 data?

**Comment by leofeyer** [comment]
> Maybe we can update the whole country list with latest ISO 3166 data?

Sure. Will you create a PR?

**Comment by aschempp** [comment]
Closed in favor of #7918
