### ISSUE TITLE
Alte Inhalte bleiben trotz Änderung des Elementtyps erhalten

### ISSUE THREAD

**Issue by k-webdesign** [contao/core#7916]
Contao 3.5.0:
Ich habe einen Artikel dupliziert und änderte den darin befindlichen Elementtyp "Text" auf "Bild". Text enthielt zuvor einen Text und ein angehängtes Bild. Eben dieses Bild brauche ich nun als einzelnes Element, aber die vorherigen Daten werden nun trotz Änderung des Elementtyps weiterhin angezeigt.
Ein Cache-Problem schließe ich aus, da ich es auf allen nicht genutzten Browsern nachstellen kann. In der Installation habe ich schon mehrere Elementtypen verändert, aber genau hieran scheint sich Contao aufzuhängen. In der Demo kann ich es leider nicht nachstellen. 

Eine andere Bilddatei zu wählen ändert im Frontend nur, dass das "angehängte" Bild durch die neue Bildquelle ersetzt wird. Alle Daten, Cache etc. sind gecleart und es tritt weiterhin auf. 

Behoben wird es nur, indem ich einen neuen Artikel mit dem Bild anlege. 

![bildschirmfoto 2015-07-12 um 13 38 36](https://cloud.githubusercontent.com/assets/4130440/8637634/a18e076e-289b-11e5-996a-6317c1d3f625.png)

![bildschirmfoto 2015-07-12 um 13 38 50](https://cloud.githubusercontent.com/assets/4130440/8637636/a5938a8c-289b-11e5-8c32-a84d23084f67.png)

![bildschirmfoto 2015-07-12 um 13 39 00](https://cloud.githubusercontent.com/assets/4130440/8637637/a8e2cc48-289b-11e5-9224-74a71cbef0a2.png)

![bildschirmfoto 2015-07-12 um 13 39 19](https://cloud.githubusercontent.com/assets/4130440/8637638/abad6bae-289b-11e5-924f-164900c56c6a.png)

![bildschirmfoto 2015-07-12 um 13 39 28](https://cloud.githubusercontent.com/assets/4130440/8637639/ae5f22ac-289b-11e5-8aa1-1244b2d23c25.png)

**Comment by k-webdesign** [comment]
Trat gerade eben wieder auf, diesmal als ich ein Textelement in eine Galerie wandeln wollte.

**Comment by Aybee** [comment]
D.h. das Template des CEs Bild gibt im FE Felder aus, welche nicht zum CE Bild gehören? Schau mal bitte, ob du dort ein individuelles Template ausgewählt hast. Das kann man in deinen Screenshots nicht sehen. Etwas anderes kann ich mir da nicht vorstellen.

**Comment by fritzmg** [comment]
Dass die Daten des "alten" Elementes vorhanden sind ist normal, diese bleiben in der Datenbank erhalten bzw. werden beim ändern des Elementtyps nicht gelöscht. Dass sie auch im Frontend ausgegeben werden kann eigentlich nur daran liegen, dass du ein Element Template ausgewählt hast, das eben genau das macht, wie Aybee schon erwähnt hat.

**Comment by Samson1964** [comment]
Also ich finde das durchaus sehr hilfreich, daß die Inhalte der vorhergehenden Elementtypen (weitgehend) erhalten bleiben. Beim Wechsel des Elementtyps ändert sich beim Datensatz in der Tabelle tl_content nur der Wert der Spalte type. Viele Elementtypen teilen sich außerdem Spalten. So nutzt das Textelement dieselben (Bild-)Spalten wie das Bildelement.

**Comment by Aybee** [comment]
@Samson1964 Darum geht es hier nicht. Das Verhalten ist bekannt. Es geht darum, dass im FE Werte aus Feldern ausgegeben werden, welche nicht zum CE Bild gehören, und das kann eigentlich nur durch ein falsches Template passieren.

**Comment by Samson1964** [comment]
@Aybee: Ja Du hast recht. Ich hätte genauer auf die FE-Ausgabe schauen sollen. 
Also bleibt nur ein falsches Template als Ursache übrig.

**Comment by leofeyer** [comment]
@k-webdesign Hast Du ein individuelles Template für das Element konfiguriert?
