### ISSUE TITLE
\String::splitFriendlyEmail() returning array in wrong order

### ISSUE THREAD

**Issue by fatcrobat** [contao/core#7919]
If we set an additional sender name within \String::splitFriendlyEmail() the email will be returned as first element of the array, without at the first position. That will lead to errors, when using list($sender, $senderName) for the return array of \String::splitFriendlyEmail(). Can you please set email always as first or second element, regardless the name was given?

Here an simple example, with the returning values:

```
\String::splitFriendlyEmail('john@doe.com')
``` 

returns

```
Array
(
    [0] => 
    [1] => john@doe.com
)
```

```
\String::splitFriendlyEmail('john@doe.com [John Doe]')
``` 

returns

```
Array
(
    [0] => john@doe.com
    [1] => John Doe
)
```

**Comment by aschempp** [comment]
`\String::splitFriendlyEmail('john@doe.com [John Doe]')` is wrong, it should be `\String::splitFriendlyEmail('John Doe <john@doe.com>')`

See https://en.wikipedia.org/wiki/Email_address

> To indicate the message recipient, an email address also may have an associated display name for the recipient, which is followed by the address specification surrounded by angled brackets, for example: `John Smith <john.smith@example.org>`.

**Comment by fatcrobat** [comment]
Ah thanks. Maybe the implementation should check this and return the email nevertheless always in second place, just for ignoramus like me? :)

**Comment by aschempp** [comment]
I don’t think so. If your code is wrong, the result will be wrong ;-)

**Comment by fatcrobat** [comment]
Is a user input termed code? :)

**Comment by fatcrobat** [comment]
Thanks anyway. :)

**Comment by discordier** [comment]
@aschempp Throwing an exception for invalid data might be a good idea non the less. :)
