### ISSUE TITLE
Zugriff auf Ordner mit hasAccess prüfen: nicht immer korrekt

### ISSUE THREAD

**Issue by mathContao** [contao/core#7920]
Wollte eben mit hasAccess der Klasse BackenUser prüfen, ob der BE-User Zugriff auf bestimmte Ordner hat. Dabei ist mir aufgefallen, dass hasAccess true liefert, wenn der Ordner in der abgefragten Bezeichnung (in einer speziellen Kombination*) nicht existiert.

Randbedingungen: BE-User, der KEIN Admin ist. Muss Zugriff auf den Ordner "files/tiny_templates" haben.
Getestet mit Contao 3.4.5

*spezielle Kombination: files/Gueltiger/Pfad plus beliebiger angehangener String

Beispiel:
Ordner "files/tiny_templates" ist vorhanden und der User darf ihn sehen
```php
if (\BackendUser::getInstance()->hasAccess('files/tiny_templates', 'filemounts')) {
          echo "Zugriff";
}
```
Ausgabe: "Zugriff" (richtig, denn den Ordner "files/tiny_templates" gibt es und der User hat Zugriff)

```php
if (\BackendUser::getInstance()->hasAccess('files/tiny_templates3', 'filemounts')) {
          echo "Zugriff";
}
```
Ausgabe: "Zugriff" (FALSCH! Den Ordner "files/tiny_templates3" gibt es nicht. Jedoch existiert der Ordner "files/tiny_templates")

```php
if (\BackendUser::getInstance()->hasAccess('files/tiny_temxxxxx3', 'filemounts')) {
          echo "Zugriff";
}
```
Ausgabe: keine (richtig, denn es gibt keinen Ordner "files/tiny_temxxxxx")

(vermutliche) Fehlerquelle (system/modules/core/classes/BackendUser.php Zeilen 246ff):
```php
elseif ($array == 'filemounts')
		{
			// Check the subfolders (filemounts)
			foreach ($this->filemounts as $folder)
			{
				if (preg_match('/^'. preg_quote($folder, '/') .'/i', $field[0]))
				{
					return true;
				}
			}
		}
```
Ich tippe, dass der reguläre Ausdruck fehlerhaft ist. Kenne mich mit dem Thema leider garnicht aus.

Auswirkungen: Die Abfrage kann zu fehlerhaften Ergebnissen kommen, wenn mehrere Ordner eine ähnliche Ordnerbezeichnung haben (z.B. Ordner, Ordner1, Ordner2 usw.)

**Comment by discordier** [comment]
In der Tat, da sollte wohl `if (preg_match('/^'. preg_quote($folder, '/') .'$/i', $field[0]))` stehen (beachte das `$` am Ende des regex).

**Comment by Toflar** [comment]
@discordier: Nein, ich denke das ist falsch. Dann wäre es ja durch `^` und `$` exakt das gleiche wie ein normaler String-Compare. Ich denke der Hintergrund für das fehlende `$` ist, dass wenn man eben in den Filemounts den Pfad `files/tiny_templates` erlaubt hat, dann sollte die Methode nicht nur bei `files/tiny_templates` `true` zurückgeben sondern auch bei `files/tiny_templates/subfolder/style.css` da die Filemounts ja vererbt werden.

Die Methode verhält sich dennoch falsch :-)

**Comment by discordier** [comment]
Ach so, da hast du auch wieder recht.
Dann eben:
```php
if (preg_match('/^'. preg_quote($folder, '/') .'([/]|$)/i', $field[0]))
```
Matched:
- files/tiny_templates
- files/tiny_templates/
- files/tiny_templates/subfolder/style.css

Matched nicht:
- files/tiny_templates3

**Comment by mathContao** [comment]
Warning: preg_match(): Unknown modifier ']' in .....\system\modules\core\classes\BackendUser.php on line 251

**Comment by fritzmg** [comment]
The line needs to be
```php
if (preg_match('/^'. preg_quote($folder, '/') .'([\/]|$)/i', $field[0]))
```
or alternatively
```php
if (preg_match('~^'. preg_quote($folder, '/') .'([/]|$)~i', $field[0]))
```

**Comment by discordier** [comment]
The first one @fritzmg, in the second you would have to quote `~` instead of `/`.
Sorry, I copy pasted the regex wrong above.

**Comment by fritzmg** [comment]
Oh you mean if `~` exists in a folder's path? Yeah, didn't think of that.

**Comment by discordier** [comment]
Therefore
```php
if (preg_match('/^'. preg_quote($folder, '/') .'([\/]|$)/i', $field[0]))
```
is correct.

**Comment by leofeyer** [comment]
Actually we don't need to put the slash into a group, do we?

```php
if (preg_match('/^'. preg_quote($folder, '/') .'(\/|$)/i', $field[0]))
```

**Comment by leofeyer** [comment]
Fixed in 7675ba510ff9e35bb7adfffb6f98299a337d51dc.
