### ISSUE TITLE
[3.5.0] PHP Doc Code Annotations

### ISSUE THREAD

**Issue by Zeromax** [contao/core#7923]
Just discovered out that you have done a really good job with the PHP Doc and I realy love this ;)
So many warnings and undifined Variables are gone now.

So there is a Problem which occures with the Anotation in https://github.com/contao/core/blob/master/system/modules/news/models/NewsArchiveModel.php#L33
There is defiened: `@method static $this findByPk()` which is not correct.

See the code inspector from PHP Strom
![unbenannt](https://cloud.githubusercontent.com/assets/1867177/8695157/cf659860-2ae3-11e5-960f-6ddad1d997db.PNG)

You should define the two Params in here, wich are allowed in the original Model class.
Not sure if it is enough to remove it?

**Comment by aschempp** [comment]
I've got the same error, I think that's a "new feature" of PhpStorm 9…

**Comment by leofeyer** [comment]
The issue has been fixed meanwhile.
