### ISSUE TITLE
Frontend-Module Passwort ändern, Passwort vergessen usw.

### ISSUE THREAD

**Issue by Total-Reality** [contao/core#7924]
Hallo,

es wäre schön, wenn man die Module mit einer Meldung ausstatten würde im Erfolgsfall.
Bspw. "Das Passwort wurde geändert" und außerdem sollte das Formular dann ausgeblendet werden.

Ich finde es unnötig, wenn man für jedes kleine Modul bzw. Formular extra eine Weiterleitungsseite anlegen muss, nur um dort hinzuschreiben "Das Passwort wurde geändert"

Viele Grüße

**Comment by Total-Reality** [comment]
Was bedeutet diese Angabe im Quelltext?
$this->Template->message = \Message::generate(false, true);

Hat das irgendeine Auswirkung?

**Comment by bezin** [comment]
> $this->Template->message = \Message::generate(false, true);

Das gibt alle Messages aus, die in $SESSION gespeichert sind. Welche das in diesem Fall allerdings sein könnten, durchschaue ich gerade noch nicht.

**Comment by leofeyer** [comment]
Mittlerweile implementiert.
