### ISSUE TITLE
ER2: Forbidden

### ISSUE THREAD

**Issue by Wagnerwagner** [contao/core#7925]
Das ER2 ist momentan nicht erreichbar. Egal ob Erweiterungskatalog oder Erweiterungsverwaltung es wird immer "Forbidden" angezeigt:

Contao 3.4.5:
![bildschirmfoto 2015-07-15 um 15 35 00](https://cloud.githubusercontent.com/assets/7679272/8699741/045d86b2-2b08-11e5-8c7a-3d6842e683c4.png)
![bildschirmfoto 2015-07-15 um 15 35 07](https://cloud.githubusercontent.com/assets/7679272/8699742/045efe16-2b08-11e5-84d2-82951fcf7fa1.png)

Contao 2.11:
![211](https://cloud.githubusercontent.com/assets/7679272/8699755/1002a308-2b08-11e5-9278-326d9592c374.JPG)

Werden da gerade unangekündigte Wartungsarbeiten durchgeführt?!

**Comment by Wagnerwagner** [comment]
Nachtrag: Composer funktioniert problemlos.

**Comment by discordier** [comment]
Evtl. bist du wg. zuvielen Requests in der blacklist gelandet. Probier es in einer Stunde nochmal.

**Comment by Wagnerwagner** [comment]
Wir scheinen nicht die einzigen mit diesem Problem zu sein: https://twitter.com/hashtag/Contao

**Comment by pedaworx** [comment]
@discordier weiss du schon was da los ist?

**Comment by pedaworx** [comment]
ok hat sich erledigt es geht wieder... thx

**Comment by Wagnerwagner** [comment]
Check, tut wieder!

**Comment by leofeyer** [comment]
Hab heute ein Update auf Ubuntu 14.04 gemacht und dort ist Apache 2.4 installiert. Leider war das Repository-Server-Modul damit noch nicht kompatibel (Stichwort `Require all granted` anstatt `allow from all`). Ist jetzt aber angepasst.
