### ISSUE TITLE
Viel zu hoher Speicherverbrauch bei Erstellung der sitemap.xml

### ISSUE THREAD

**Issue by do-while** [contao/core#7928]
Ich habe das Problem bei einer Kundeninstallation, wo ca. 5000 News eingetragen sind, das Bilden der Sitemap die Speichergrenze von 256 MB erreicht. Dadurch können neue Nachrichtenbeiträge nicht mehr gespeichert werden. Beim Speichern wird gleichzeitig eine neue Sitemap erstellt (Hook getSearchablePages). Resultat ist eine weiße Seite.
Nach Abschalten der sitemap.xml sind die Probleme weg, die Seiten-URLs werden dann natürlich nicht an Google übermittelt.

**Ursache:**
In der Datei news.php, Zeile 316 werden die kompletten Article-Objekte über Models geladen, obwohl nur der alias benötigt wird. Das hat natürlich einen erheblich höheren Speicherbedarf!
```php
$objArticle = \NewsModel::findPublishedDefaultByPid($objArchive->id);
```

In meinem Test braucht das System nur einen Bruchteil an Speicher, wenn ich die Zeile auf herkömmliche Art schreibe:
```php
$objArticle = $this->Database->prepare("SELECT alias FROM tl_news WHERE pid=?")->execute($objArchive->id);
```

**Gleich noch einen Verbesserungsvorschlag zur sitemap.xml:**
Schön wäre, wenn man die automatische Generierung irgendwo deaktivieren könnte und dafür mit einem Cronjob die Sitemap.xml aufbauen kann. Dann würde eine Speicherüberlastung nicht das Speichern von neuen Nachrichten behindern.

**Comment by fritzmg** [comment]
Ja, das NewsModel, bzw. Models generell können sehr viel Speicher verbrauchen. [Hier](https://community.contao.org/de/showthread.php?52268-Newsarchiv-mit-%FCber-10-000-Eintr%E4gen-sprengt-Speicher&p=337337&viewfull=1#post337337) habe ich vor einiger Zeit mal eine Analyse gemacht, wo der Speicherverbrauch in den Models derart stark ansteigt. Natürlich verbrauchen die Objekte der einzelnen Einträge selbst einiges an Speicher, aber noch viel mehr Speicher braucht das anlegen der related Models.

Im Fall der Sitemap wäre es natürlich tatsächlich am besten, wenn bei der Erzeugung wirklich nur ein direkter Datenbank Abruf gemacht wird, wie zB nur den Alias holen.

Aber allgemein: um den hohen Speicherverbrauch bei sehr vielen Newseinträgen geringer zu halten, habe ich damals in diesem Thread eine neu Art von Model Collection vorgeschlagen, von mir "Chunked Collection" genannt, wo die einzelnen Einträge in Blöcke aufgeteilt werden und man zuerst durch die Blöcke iterieren muss und da erst dynamisch die Daten aus der Datenbank bzw. in das Model bzw. die Model Collection geladen werden.

**Comment by leofeyer** [comment]
@contao/developers /cc

**Comment by Toflar** [comment]
Natürlich braucht das Laden der Models viel RAM.
Zum Problem: Also bei mir sieht der besagte Abschnitt so aus:

```php
				// Get the items
				$objArticle = \NewsModel::findPublishedDefaultByPid($objArchive->id);

				if ($objArticle !== null)
				{
					while ($objArticle->next())
					{
						$arrPages[] = $this->getLink($objArticle, $strUrl);
					}
				}
```

Wobei `getLink()` unter anderem auch `source`, `jumpTo` und andere Werte braucht. Also nur mit `alias` ist es nicht gemacht.

@do-while versuch mal so:

```php
					foreach ($objArticle as $articleModel)
					{
						$arrPages[] = $this->getLink($articleModel, $strUrl);
                        unset(articleModel);
					}
```

Alternativ können wir auch ein weiteres Options-Flag (zu `order`, `column`, `value` etc.) hinzufügen, welches wir dann `ignoreRegistry` oder so nennen. Dann kann man das auf `true` setzen und die `findBy` Methoden müssten in dem Fall dann die Model-Registry ignorieren.

**Comment by fritzmg** [comment]
Ich denke das unset wird nichts bringen, der hohe Speicherverbrauch passiert ja schon bei
```php
$objArticle = \NewsModel::findPublishedDefaultByPid($objArchive->id);
```

Aber warum genau verbraucht das laden der Related Models eigentlich so viel Speicher? Noch dazu mehr als die eigentlichen Einträge selbst.

**Comment by do-while** [comment]
Hallo Yanick,
ich habe es ausprobiert, es bringt nichts, wie fritzmg schreibt, verbraucht findPublishedDefaultByPid den Speicher.
Mit meiner Ersetzung (1. Beitrag) brauche ich 21 MiB, im Original ist Abbruch mit 256 MiB.
Das Optionsflag wird wohl nötig.

**Comment by Toflar** [comment]
Ja, klar. Sorry, hab nicht wirklich viel mitgedacht :)
Kommentier mal Zeile 173
```php
			\Model\Registry::getInstance()->register($this);
```
in Model.php aus.

**Comment by leofeyer** [comment]
Wie am 13. August auf Mumble besprochen, müssen wir das wieder auf DB-Queries umbauen.

**Comment by do-while** [comment]
+1

**Comment by leofeyer** [comment]
Siehe auch https://github.com/contao/core-bundle/issues/333.

**Comment by leofeyer** [comment]
Wir haben gerade einen Bug in der `Model`-Klasse gefunden: contao/core-bundle@faeea6e7ffa37ede2a21f62213fe01047815d00f Könnt ihr bitte mal testen, wie sich das auf die Performance auswirkt?
