### ISSUE TITLE
Dateiverwaltung: & im Link nicht korrekt codiert

### ISSUE THREAD

**Issue by mathContao** [contao/core#7929]
Betrifft nur den Dateiwähler, wenn er im "Dateimanager-Modus" ist

![unbenannt](https://cloud.githubusercontent.com/assets/1645099/8763548/abacd6a6-2da2-11e5-9d7e-04119e65c6ae.JPG)
Link im Demo-Backend: http://demo.contao.org/contao/main.php?do=files&popup=1 

Die restlichen & in den Links sind korrekt codiert.

**Comment by leofeyer** [comment]
Behoben in c717d9cdf02dde2615203da62bd126dc98b4596d.
