### ISSUE TITLE
url rewrite broken after update (3.3 -> 3.5) 

### ISSUE THREAD

**Issue by voxspox** [contao/core#7930]
Hi,

I updated my contao installation from 3.3 to 3.5 and now the URL rewriting is broken.
"rewrite URLs" is checked and "URL suffix" is empty, thus a valid URL is p.ex. www.domain.com/contact

The .htaccess.default contains:

    # If you do not want to use an URL suffix at all, you have to add a third
    # line to prevent URLs that point to folders from being rewritten (see #4031).
    RewriteCond %{REQUEST_FILENAME} !-d
    RewriteRule .* index.php [L]

I have to following behaviour:

If I do NOT use these rules, I can see the start page with styles, etc. ok, but the links are broken. P.ex. www.domain.com/contact leads to 404 Not Found.

If I do use these rules. I can navigate (p.ex to contact) but all styles, downloads, etc is broken and leads to "Page not found" Contao error page.
Additionally, I can not login anymore. System log reports: No active page for page ID "contao"

What is wrong here??

Knut

(I posted this also in the forum, but meanwhile I think this is a bug...
https://community.contao.org/en/showthread.php?22907-url-rewrite-broken-after-update-%283-3-gt-3-5%29 )

**Comment by discordier** [comment]
If you follow the whole paragraph in the `.htaccess.default`, you should end up with something like this:
```
RewriteCond %{REQUEST_FILENAME} !\.(htm|php|js|css|htc|png|gif|jpe?g|ico|xml|csv|txt|swf|flv|mp4|webm|ogv|mp3|ogg|oga|eot|otf|tt[cf]|woff2?|svgz?|pdf|gz)$
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule .* index.php [L]
```

It states:
>   # If you do not want to use an URL suffix at all, you have to add a __third__
  # line to prevent URLs that point to folders from being rewritten (see #4031).

The first line is the cond which skips all known asset file types, the second is the one skipping existing files. The THIRD one you have to add as it skips existing directories and does not misinterpret them as page alias.

NOTE: the `.htaccess.default` is meant to be adjusted(!) on most places and not simply to uncomment some lines without knowing what they are doing.

**Comment by voxspox** [comment]
ok, thanks. This setup works now. Indeed it was not obvious to me that I have to rearrange lines here while I could just uncomment/edit lines elsewhere in the file.
I think it would be more clear if the different blocks (suffix, directories, extensions, language, etc.) are in order which means the suffix stuff comes last because RewriteRule is the last command to use. And it is possible to just un-/comment and edit lines (no compiling).
Now the blocks are somehow mixed up and everybody has to think more to get into it.
