### ISSUE TITLE
Keyboard Shortcuts Link in Backend are broken

### ISSUE THREAD

**Issue by michelbalzer** [contao/core#7935]
This is mainly a reference to contao/website#43 because the links to the keyboard shortcuts needs to be modified in Contao itself, I guess.

(Reproducable in the Demo by clicking the link „keyboard shortcuts“ under http://demo.contao.org/contao/main.php)

**Comment by leofeyer** [comment]
Fixed in 50903082e8cce479a7241a7872df909870420dbd.
