### ISSUE TITLE
Manuell update 3.5.0 to 3.5.1 error after calling install.php

### ISSUE THREAD

**Issue by bizon1** [contao/core#7936]
error message:

     Fatal error: Class 'StringUtil' not found in /xxx/xxx/xxx/xxx/system/modules/core/classes/BackendTemplate.php on line 67

See also: https://community.contao.org/de/showthread.php?58341-Contao-3-5-1-verf%FCgbar&p=378274&viewfull=1#post378274

**Comment by leofeyer** [comment]
Did you rebuild the internal cache?

**Comment by bizon1** [comment]
Leo Thanks for your response. i just explained what I did in the forum:
https://community.contao.org/de/showthread.php?58341-Contao-3-5-1-verf%FCgbar&p=378285&viewfull=1#post378285

**Comment by fritzmg** [comment]
As already mentioned in the thread (and here) you need to delete the internal cache when doing a manual update.
