### ISSUE TITLE
Recommendation regarding max_input_vars in README

### ISSUE THREAD

**Issue by fritzmg** [contao/core#7938]
Some backend forms in Contao can potentially include a lot of input fields. The default group rights form has 745 input fields alone. Extensions could increase this number further. Some forms also use dynamic input fields, e.g. the input fields for the table content element could produce a lot, if you want to display a large table.

This can lead to a problem with the `max_input_vars` setting of PHP. The default of this setting is 1000 (http://php.net/manual/en/info.configuration.php). Thus if the backend form happens to have over a 1000 input fields, any input field after the 1000th will be discarded when saving the form.

PHP does create an error saying this, however it's only a _Warning_ and thus might not be noticed. Here are two cases where this happened:

* [Thema: Benutzergruppen - Checkbox Anzahl begrenzt!?](https://community.contao.org/de/showthread.php?56532-Benutzergruppen-Checkbox-Anzahl-begrenzt!)
* [Tabellengröße eingeschränkt?](https://community.contao.org/de/showthread.php?58333-Tabellengr%F6%DFe-eingeschr%E4nkt)

So I thought, maybe this should be mentioned in the README or somewhere. A recommendation to manually increase `max_input_vars` (e.g. to 2000 or 10000).

**Comment by aschempp** [comment]
Related to https://github.com/contao/core/issues/7749

**Comment by Samson1964** [comment]
[Älterer Thread im Forum](https://community.contao.org/de/showthread.php?32678-Inhaltselement-Tabelle-mit-Bug-bei-CSV-Import) zu dem Thema.

**Comment by fritzmg** [comment]
As @Total-Reality suggest [here](https://github.com/contao/core/issues/7749#issuecomment-149161174) may be the backend could additionally show a warning, if the current number of input fields exceeds the currently configured _max_input_vars_ value.

**Comment by leofeyer** [comment]
You should create a pull request to update the [Contao docs](https://github.com/contao/docs).

**Comment by fritzmg** [comment]
> You should create a pull request to update the Contao docs.

What about the warning message in the backend? But I guess that should be a separate issue for Contao 4.

**Comment by leofeyer** [comment]
I don't think we need a warning for this.

**Comment by fritzmg** [comment]
Well, a warning would make it much easier to find the source of the problem, if you don't know what to look for. For an unknown user it will not be clear why part of his submitted input is not saved.

You could simply

* pass the current value of `max_input_vars` to the backend template as a JavaScript variable
* count the number of input fields per form and display a warning if the number is greater than `max_input_vars`

Or do both in PHP.
