### ISSUE TITLE
[>=3.2] Update robots.txt

### ISSUE THREAD

**Issue by Tastaturberuf** [contao/core#7943]
Some still working extensions use the non standard ```/system/modules/*/html/``` folder for assets. Actually Google send some mails that the bot can't crawl to this ressource. We block this with the line ```Disallow: /system/```.

It is useful to add ```Allow: /system/modules/*/html/``` to the robots.txt.

**Comment by bytehead** [comment]
:+1:  Same here.

**Comment by xchs** [comment]
I have also received such a message from Google.

**Comment by stefansl** [comment]
Some modules use e.g. /system/modules/mymodule/html/js/script.js - so it should be `Allow: /system/modules/*/html/*`

**Comment by Tastaturberuf** [comment]
All behind /html is legit too.
Am 30.07.2015 3:40 nachm. schrieb "Stefan Schulz-Lauterbach" <
notifications@github.com>:

**Comment by stefansl** [comment]
@Tastaturberuf I tested with Google Webmaster Tools. It didn't work with subfolders.

**Comment by Tastaturberuf** [comment]
On https://developers.google.com/webmasters/control-crawl-index/docs/robots_txt?hl=en

> /*	equivalent to /	equivalent to /	Equivalent to "/" -- the trailing wildcard is ignored.

I dont know what’s the right way.

**Comment by Tastaturberuf** [comment]
In case of the xetenssion subcolumns the path is ```/system/modules/subcolumns/html/yaml3/subcols.css```

It works without the asterisk only with ```/system/modules/*/html/```

I think the paths are always recursive. This behavior make sense too.

**Comment by Tastaturberuf** [comment]
I have two error messages 
> currently not available

and
> blocked

the blocked are gone.

**Comment by leofeyer** [comment]
Closed in favor of #7944.
