### ISSUE TITLE
Cannot unset string offsets in Controller.php on line 1478

### ISSUE THREAD

**Issue by ausi** [contao/core#7945]
In [Controller.php:1478](https://github.com/contao/core/blob/ac68761904694febb7636efacf34c30575e720a0/system/modules/core/library/Contao/Controller.php#L1478) we try to unset the third array item, but `$size` isn’t always an array and this leads to the fatal error “Cannot unset string offsets”. I think we should change to a `deserialize($arrItem['size'], true)` in [Controller.php:1432](https://github.com/contao/core/blob/ac68761904694febb7636efacf34c30575e720a0/system/modules/core/library/Contao/Controller.php#L1432).

Related issue: #7875

**Comment by leofeyer** [comment]
Fixed in d0c2dae8ef50081e1605e83ad61b11b7a87bb569.

**Comment by fritzmg** [comment]
This fix causes a backwards compatibility break since image aren't resized _at all_ anymore, neither in the frontend nor the backend (see #8197), if `$size` is not an array. Instead of wrapping the size processing block in 
```php
if (is_array($size))
{
	…
}
```
you could simply do
```php
$size = deserialize($arrItem['size']) ?: array(0,0,0);
```
(or what @ausi originally suggested, if that's sufficient too)

**Comment by ausi** [comment]
If you use that, it should be `array(0, 0, 'crop')` or `array(0, 0, '')` IMO.

Or even better:

```php
$size = deserialize($arrItem['size'], true) + array(0, 0, 'crop');
```

which also adds default values if `$arrItem['size']` is an empty or shorter array.

**Comment by fritzmg** [comment]
Sure, sounds good. I chose `array(0,0,0)` because that's what Contao writes into the `size` field by default (in Contao >=3.4.0).

**Comment by ausi** [comment]
In my test Contao wrote `a:3:{i:0;s:0:"";i:1;s:0:"";i:2;s:0:"";}` into the database which is `array('', '', '')`

**Comment by fritzmg** [comment]
Ah yes, I misinterpreted it before, it's `array('','','')'.
