### ISSUE TITLE
Class InsertTags not useable

### ISSUE THREAD

**Issue by dmolineus** [contao/core#7946]
The new provided class `InsertTags` is not callable when calling it from a class which does not inherit from the `Controller`. It has to make the `__construct()` method public.

Contao does not suffer from this issue because of PHPs public/private concept which allows to call protected methods if having the same parent class [see](http://verraes.net/2011/03/accessing-private-properties-from-other-instances/).

```php
class WorkingExample extends Controller
{
    public function example()
    {
        $insertTags = new InstertTags();
        echo $insertTags->relplace($content);
    }
}

class FalingExample
{
    public function example()
    {
        $insertTags = new InstertTags();
        echo $insertTags->relplace($content);
    }
}

**Comment by leofeyer** [comment]
Fixed in 72238bd588309d888c741820fb18e01729c717db.
