### ISSUE TITLE
Alias-Generierung aus dem Seitennamen bei chinesischen Schriftzeichen fügt nur die ID ein

### ISSUE THREAD

**Issue by michelbalzer** [contao/core#7947]
Wir arbeiten gerade an einer Seite mit chinesisch-sprachigen Unterseiten (zh steht im Webseiten-Startpunkt bei Sprache, de-CH ist der Sprachen-Fallback in einem anderem Baum).

Contao 3.5.2
PHP 5.4.30 bei domainfactory

Wenn ich nun in einer der Unterseiten bspw. 关于我们 als Seitennamen eingebe und speichere, kommt als Alias nur -14, sprich ein Strich mit der Seiten-ID. (Ursprünglich dachte ich, der Alias bleibt komplett leer, das lag aber an http://github.com/terminal42/contao-changelanguage).

Ist das so gewollt? Gebe ich den Seitennamen direkt im Aliasfeld ein, bleibt der so bestehen und funktioniert auch tadellos mit eingeschaltetem mod_rewrite.

Das gleiche Problem tritt auch bei „Mehrere bearbeiten“ > Alias generieren in der Seitenstruktur auf.

**Comment by fritzmg** [comment]
Naja - was genau ist für dich das erwartete Verhalten? Ich denke chinesische Zeichen können in URLs nicht verwendet werden, daher kann auch kein Seitenalias mit chinesischen Zeichen vergeben werden. Den müsstest du einfach selbst setzen (Contao wird ja wohl kaum für dich die Zeichen auf englisch oder phonetisch übersetzen).

**Comment by michelbalzer** [comment]
Bei arabisch tut es genau das was du im letzten Satz ansprichst :)

Naja, nicht einfach die Zeichen ersetzen, als ich den Seitennamen manuell als Alias setzte, hat alles bestens geklappt.

Von unterwegs gesendet

**Comment by fritzmg** [comment]
Tatsächlich ;). Hatte `utf8_romanize` vergessen. Es fehlt hier Chinesisch (simplified und/oder traditional): https://github.com/contao/core/blob/3.5.2/system/helper/utf8_lookup.php

**Comment by aschempp** [comment]
1: chinesische Zeichen kann man in einer URL problemlos nutzen, genauso wie Umlaute. Problematisch ist nur dass Contao (standardmässig) keine 4-Byte Zeichen speichern kann. 

2: mit PHP 5.4 und dem Transliterator lassen sich chinesische Zeichen auch in ASCII umwandeln (siehe https://de.m.wikipedia.org/wiki/Pinyin). Allerdings hat die URL für einen Chinesen wohl nicht mehr viel nutzen, da kann man gleich die ID verwenden…

**Comment by leofeyer** [comment]
> Es fehlt hier Chinesisch (simplified und/oder traditional):

@michelbalzer Hast Du vor, die fehlenden Zeichen zu ergänzen?

**Comment by michelbalzer** [comment]
Ich kann es jedenfalls mal probieren, sofern ich das verstehe und dazu komme.

Was mir noch auffiel: der ID-Alias wird nur als beispielweise -61 gespeichert, ohne id-Präfix (also id-61), wodurch dann nur ein 404 kommt. Das ist bei der Alias-Generierung über „Mehrere Bearbeiten“ der Fall.

Das sind die Frontendeinstellungen (Contao 3.5.3):

<img width="754" alt="bildschirmfoto 2015-09-19 um 12 27 08" src="https://cloud.githubusercontent.com/assets/1337412/9975794/e0f02126-5ec9-11e5-8392-50553aa20bee.png">

**Comment by leofeyer** [comment]
In Contao 4.4 sollte das Alias erhalten bleiben und in Contao 4.5 kannst Du konfigurieren nach welchen Regeln das Alias erstellt werden soll.
