### ISSUE TITLE
Backend-Theme "flexible": Zeilenabstand bei Select-Listen zur Beschreibung zu groß

### ISSUE THREAD

**Issue by mathContao** [contao/core#7948]
Backend-Theme "flexible": Zeilenabstand bei Select-Listen zur Beschreibung zu groß

Aufgefallen in Contao 3.4.5 und 3.5.2; Browser: Firefox39

Aufgefallen im CSS-Editor. Der Beschreibungstext hat in einigen Fällen einen zu großen Abstand zu den Input-Feldern:

![abstand-css-style](https://cloud.githubusercontent.com/assets/1645099/8994948/b79abc9c-370e-11e5-81b9-d9e67267b60e.JPG)

Ursache: Die sichtbare Select-Listen (in diesem Fall die "px"-Liste)  sind (per jQuery?) gestylte Listen. Die "orginale" Select-Liste wurde mit "opacity:0" ausgeblendet und rutscht in die nächste Zeile. Jedoch benötigt sie den Platz. Somit entsteht der Abstand zwischen Eingabefelder und Beschreibungstext.

Mögliche Lösung: statt "opacity:0" => "display:none" (benötigt keinen Platz, wenn ausgeblendet ist)

**Comment by leofeyer** [comment]
> Mögliche Lösung: statt "opacity:0" => "display:none" (benötigt keinen Platz, wenn ausgeblendet ist)

Das wird nicht funktionieren, denn beim Klick soll sich ja das originale Dropdown-Menü öffnen.

**Comment by Aybee** [comment]
Irgendwie bekomme ich das in der Demo nicht reproduziert. Liegt es vielleicht an deinem Browser, oder was muss ich beim Reproduzieren beachten?

**Comment by mathContao** [comment]
http://demo.contao.org/contao/main.php?do=themes&table=tl_style&act=edit&id=422&rt=744ae2978bda69605ce943475c83c99a&ref=c54d5b2b

Browser zusammenziehen (Breite <750px).
Ggf. muss in den User-Einstellungen (http://demo.contao.org/contao/main.php?do=login&ref=7e1361cd) unter "Back end theme" das Theme "flexible" ausgewählt werden.

Getestet mit: Firefox 39 (IE, Opera, Chrome ohne Probleme)

**Comment by Aybee** [comment]
Ja, hatte ich alles gemacht, FF39. Bei mir ist dort alles OK.

**Comment by mathContao** [comment]
ok. kann geschlossen werden. bin dem ganzen nochmal tiefer auf den grund gegangen:

In der Konsole konnte ich keine Fehlermeldungen ausfindig machen.
Eine "nackte" Firefox-Installation hat diesen Fehler nicht bestätigen können.
Habe dann alle meine Erweiterungen im Firefox deaktiviert => Fehler konnte nicht bestätigt werden.
Habe dann die Erweiterungen Stück für Stück wieder aktiviert => Fehler konnte mit keiner Erweiterung in Verbindung gebracht werden.

Und jetzt tritt der Fehler auch nicht mehr auf, obwohl alle Erweiterungen wieder aktiviert sind. Oben beschriebenes Verhalten kann ich nun nicht mehr reproduzieren.
