### ISSUE TITLE
CSS-Editor: White-Space + Word-Space

### ISSUE THREAD

**Issue by mathContao** [contao/core#7949]
Abschnitt: Margin, Padding, Ausrichtung
Im Beschreibungstext der Checkbox steht "whitespace" (in der englischen und deutschen Übersetzung).

Das Feld ist dann mit "White-Space" (englisch, deutsch) beschrieben. (CSS: white-space).

![whitespace1](https://cloud.githubusercontent.com/assets/1645099/8995218/5c4e7c5a-3710-11e5-83eb-a7976bf63a4a.JPG)

Lösung: Im Beschreibungstext müsste es also lauten "whitespace" => "white-space"

--------------
Bei der Schrift/Font steht dann nochmal "white-space" im Beschreibungstext (deutsch, englisch).

Das Feld darunter lautet jedoch "Wort-Abstand" (deutsch) bzw. "word spacing" (englisch). (CSS: word-spacing)
![whitespace2](https://cloud.githubusercontent.com/assets/1645099/8995221/62b3d068-3710-11e5-97d7-1859cd74cf81.JPG)

Lösung: Im Beschreibungstext müsste es also lauten "white-space" => "word-spacing"

**Comment by leofeyer** [comment]
Behoben in 794321b3aa1df9479c41d242caf76a684cff89a5.
