### ISSUE TITLE
install.php verweist bei Fehlern auf falsche Ressourcen

### ISSUE THREAD

**Issue by Whissi** [contao/core#7950]
Hallo,

wenn es bei der `install.php` zu einem Fehler kommt, wird die Seite anschließend fehlerhaft angezeigt:

![contao-install-error1](https://cloud.githubusercontent.com/assets/729436/9021280/7e4ffc44-383b-11e5-86ff-1e68b8ea93c2.jpg)

Das liegt daran, dass `install.php` scheinbar ein *contao* Verzeichnis zusätzlich vor den Pfad setzt (wegen dem relativen Pfad?), also statt `https://example.org/system/themes/flexible/basic.css` referenziert `install.php` bspw. `https://example.org/contao/system/themes/flexible/basic.css`.

Das gleiche gilt auch für die ganzen Formulare, die kann man nicht erneut abschicken, da die ACTION-URL auch falsch ist.

**Comment by leofeyer** [comment]
Wie lässt sich das Problem reproduzieren?

**Comment by Whissi** [comment]
Einfach irgendeinen Fehler verursachen,
im obigen Falle habe ich einfach das Eingabefeld mit dem Port was standardmäßig ausgefüllt ist, geleert (weil ich stattdessen nur den Socket angeben wollte). Das führte zu besagtem Fehler.
Aber bspw. einen falschen Benutzernamen anzugeben sollte zu gleichem Problem führen.

**Comment by leofeyer** [comment]
Ich habe zwar die gleiche Fehlermeldung erhalten wie Du, allerdings wurde die Seite bei mir trotzdem richtig gerendert. Hat sonst noch jemand dieses Problem?

**Comment by asaage** [comment]
Ich hab gerad mal im installtool absichtlich ein falsches db-passwort angegeben.
Danach lässt sich das tool nichtmehr gescheit aufrufen.
Kann mich täuschen aber Ich möchte meinen früher gabs da mal einen Verbindungstest.
nun muß ich die localconfig händisch fixen.

**Comment by xchs** [comment]
Ich kann die Fehlermeldungen ebenfalls – wie oben angegeben – reproduzieren, die Seite wird (bei mir) aber soweit korrekt gerendert.

**Comment by Whissi** [comment]
Die Fehlermeldung ist ja eine Sache. Mir geht es vor allem darum, dass anschließend die URLs nicht stimmen. Das zeigt sich einmal im Aussehen, aber viel schlimmer, eben auch in der form-Action, d.h. man kann den Fehler anschließend nicht ohne weiteres korrigieren, weil das Formular nicht mehr abgeschickt werden kann (404).

Darf ich fragen wie ihr testet? Habt ihr Contao in einem Unterverzeichnis betrieben? Bei mir war Contao stehts im Docroot, d.h. ich habe wirklich via `https://example.org/contao/system/install.php` zugegriffen und nicht via `https://localhost/testproject/contao/system/install.php`. Evtl. ein Unterschied?

**Comment by xchs** [comment]
> Mir geht es vor allem darum, dass anschließend die URLs nicht stimmen.

Ja, das ist mir schon klar, ich konnte aber – wie schon gesagt – in meiner Testinstallation das Verhalten nicht reproduzieren. Die Seite des Installtools wird (jedenfalls bei mir) korrekt gerendert.

> Darf ich fragen wie ihr testet?

Getestet mit Contao 3.5.0 auf einem Online-Server. Der Zugriff auf die Contao-Installation erfolgt über ein Unterverzeichnis.

**Comment by Whissi** [comment]
Das Problem tritt nur im Internet Explorer auf.

```
URL                                                     Protocol        Method  Result
http://example.org/ctest/contao/install.php             HTTP            POST    303
http://example.org/ctest/contao/install.php             HTTP            POST    200
/ctest/assets/mootools/stylect/css/stylect.css          HTTP            GET     304
/ctest/system/themes/flexible/basic.css                 HTTP            GET     304
/ctest/system/themes/flexible/install.css               HTTP            GET     304
/ctest/assets/mootools/core/1.5.1/mootools.js           HTTP            GET     304
/ctest/assets/mootools/stylect/js/stylect.js            HTTP            GET     304
/ctest/assets/mootools/mootao/Mootao.js                 HTTP            GET     304
/ctest/assets/contao/js/core.js                         HTTP            GET     304
/ctest/system/themes/flexible/hover.js                  HTTP            GET     304
/ctest/assets/mootools/stylect/css/stylect.css          HTTP            GET     304
/ctest/system/themes/flexible/basic.css                 HTTP            GET     304
/ctest/system/themes/flexible/install.css               HTTP            GET     304
/ctest/assets/mootools/core/1.5.1/mootools.js           HTTP            GET     304
/ctest/assets/mootools/stylect/js/stylect.js            HTTP            GET     304
/ctest/assets/mootools/mootao/Mootao.js                 HTTP            GET     304
/ctest/assets/contao/js/core.js                         HTTP            GET     304
/ctest/system/themes/flexible/hover.js                  HTTP            GET     304
/ctest/contao/assets/mootools/stylect/css/stylect.css   HTTP            GET     404
/ctest/contao/system/themes/flexible/basic.css          HTTP            GET     404
/ctest/contao/system/themes/flexible/install.css        HTTP            GET     404
/ctest/contao/assets/mootools/core/1.5.1/mootools.js    HTTP            GET     404
/ctest/contao/assets/mootools/stylect/js/stylect.js     HTTP            GET     404
/ctest/contao/assets/mootools/mootao/Mootao.js          HTTP            GET     404
/ctest/contao/assets/contao/js/core.js                  HTTP            GET     404
/ctest/contao/system/themes/flexible/hover.js           HTTP            GET     404
```

**Comment by Whissi** [comment]
Wenn ich `TL_ASSETS_URL` in `install.php` setze (in dem Beispiel auf *ctest*) klappt es auch im IE.

**Comment by xchs** [comment]
> Das Problem tritt nur im Internet Explorer auf.

Kann ich nun auch bestätigen.

**Comment by leofeyer** [comment]
Hä? Die Konstante `TL_ASSETS_URL` wird im Installation-Bundle gar nicht benutzt. Das sind alles Twig-Templates und die kennen kein `TL_ASSETS_URL`.

**Comment by Whissi** [comment]
Das ist richtig, ich sagte ja auch nur, dass ich durch setzen dieser Konstante den Pfad korrigieren konnte und somit den Fehler im IE testweise beheben konnte. :)

**Comment by leofeyer** [comment]
Aber die Konstante wird doch gar nicht ausgegeben im Installtool. Wie kann dadurch also ein Fehler im IE behoben werden???

**Comment by Whissi** [comment]
Also, in `/mein-Unterverzeichnis-mit-Contao/contao/install.php` habe ich `define('TL_ASSETS_URL', '/mein-Unterverzeichnis-mit-Contao/');` gepackt. Die Konstante `TL_ASSETS_URL` wird bei mir in `system/modules/cores/templates/backend/be_install.html5` referenziert. An dem Template habe ich nichts geändert.

Damit funktioniert es bei mir im IE.

**Comment by leofeyer** [comment]
Ich nehme an, dass der IE ein Problem mit der PHP-Fehlermeldung hat, weil diese oberhalb von `<!DOCTYPE html>` ausgegeben wird. Als Folge berücksichtigt er das `<base>`-Tag nicht mehr und findet somit die CSS-Dateien nicht. Indem Du die Konstante `TL_ASSETS_URL` als Workaround missbrauchst, wandelst Du die URLs einfach in absolute URLs um.

Ich sehe jedoch nicht, dass das ein Contao-Problem ist, das wir in irgendeiner Form beheben sollten. @contao/developers Was meint ihr?

**Comment by Toflar** [comment]
Seit wann müssen Seiten mit Fehler schön gerendert werden? Wenn es ein catchable Error wäre, dann ja aber den können wir ja gar nicht fangen.

**Comment by Whissi** [comment]
...es geht hier nicht um schön. Es geht darum, dass die Seite anschließend im IE nicht mehr nutzbar ist: Die ganzen Formulare zeigen auf eine falsche URL...

**Comment by Toflar** [comment]
Die Seite ist doch eh nicht mehr funktionstüchtig wenn ein Fehler da ist? Das ist doch die Definition von einem Fehler? :)

**Comment by Whissi** [comment]
Nein, hier liegt wohl ein Missverständnis vor:

Der Nutzer trägt bspw. falsche MySQL-Zugangsdaten ein. Jetzt kann das Installer-Skript nicht zum MySQL-Server verbinden. Dieser Fehler ist aber korrigierbar, wenn der Nutzer, nachdem er den Hinweis "Access denied" gesehen hat, bspw. die Zugangsdaten korrigiert.

Das kann er aktuell aber nur dann, wenn er keinen IE nutzt. Im IE ist nicht in der Lage das Formular erneut mit korrigierten Daten abzusenden.


Frage: Hätte ein PR mit angepasstem Installer wo ich die Fehlermeldung innerhalb der Seite ausgeben würde (also so, wie es eigentlich "richtig" wäre), eine Chance auf Akzeptanz? Dann würde ich so etwas wohl vorbereiten...

**Comment by leofeyer** [comment]
Wie am 10. September auf Mumble besprochen, sollten wir hier prüfen, dass eine korrekte Portnummer eingegeben wird.

**Comment by leofeyer** [comment]
Behoben in 0c7eedf839918a688b83263dec57cd3c46dfc832.

**Comment by Whissi** [comment]
Sorry aber 0c7eedf behebt nicht wirklich den hier gemeldeten Fehler. Lediglich einen von mehreren möglichen Auslösern.

Ich hoffe zudem es wurde geprüft, dass ein permanent gesetzter Port nicht die Socket-Verbindung aushebelt.
