### ISSUE TITLE
Kalender-Modul: Hilfe der Weiterleitung defekt/unkonkret

### ISSUE THREAD

**Issue by mathContao** [contao/core#7951]
Die Hilfe der Kalender-Weiterleitungscheckbox ist defekt/unkonkret.

Hierbei beziehe ich mich auf folgende Hilfe (Fragezeichen-Icon in: Kalendermodul -> Kalendereintrag -> Abschnitt "Weiterleitungsziel/Redirect target")

Contao 3.5.2:
![screenshot1](https://cloud.githubusercontent.com/assets/1645099/9022587/99d1abda-387b-11e5-8fd1-ddabdd40de0f.JPG)
(Screenshot: Contao-Demo)

Klickt man dort auf das Fragezeichen-Icon, dann öffnet sich help.php (Hilfe-Wizard) mit folgendem Inhalt:
![screenshot2](https://cloud.githubusercontent.com/assets/1645099/9022615/54ece22c-387c-11e5-95a6-459f3cfbbcb7.JPG)
(Screenshot: Contao-Demo Contao 3.5.2; identisch mit Contao 3.4)

weiter unten findet man erst die gewünschte Hilfe:
![screenshot3](https://cloud.githubusercontent.com/assets/1645099/9022617/60e65004-387c-11e5-8756-8c7d2abe48ac.JPG)
(Screenshot: Contao-Demo Contao 3.5.2; identisch mit Contao 3.4)

Contao 3.2 und Contao 3.3 sieht das ganze noch etwas anders (aber auch "defekt") aus (Immerhin gibt es dort noch die Überschrift "Weiterleitungsziel"):
![screenshot4](https://cloud.githubusercontent.com/assets/1645099/9022630/123fb55c-387d-11e5-90ac-59851c48f7e5.JPG)
(Screenshot Contao 3.3, lokale Installation)

Contao 2.11, 3.0 und 3.1 sieht das ganze noch sehr gut und hilfreich aus:
![screenshot5](https://cloud.githubusercontent.com/assets/1645099/9022638/97bf5944-387d-11e5-9e27-613fe7d995c7.JPG)
(Screenshot Contao 3.1, lokale Installation)

Allgemein sieht die Hilfe in der aktuellen Version (Contao 3.4 und 3.5) sehr defekt aus. Die Inhalte passen zum großen Teil nicht zu den Überschriften in der Hilfe, viele Überschriften haben keinen Inhalt (weiter nach unten scrollen).

Der Zustand von Contao 3.1 wäre aus meiner Sicht wieder erstrebenswert.

**Comment by leofeyer** [comment]
Behoben in acbec17948342afc7cee7b80cde1fe95a87ba44a.
