### ISSUE TITLE
FR: mod_registration / mod_personalData koppelbar?

### ISSUE THREAD

**Issue by Anke** [contao/core#7952]
Registrierungsmodul und Modul Persönliche Daten ließen sich unkomplizierter einrichten, wenn die Felder und Feldsortierung, die man im ersten Modul (z.B. Registrierung) gewählt hat, im zweiten einzurichtenden Modul (z.B. Persönl. Data) bereits entsprechend vorausgewählt und sortiert wären. 

Lässt sich das irgendwie koppeln? (In aller Regel werden wohl für beide Module dieselben Felder verwendet mit Ausnahme des Benutzernamens bzw. der E-Mail-Adresse.)

Wenn man viele Felder hat, z.B. bei Sportvereinen oder Shops, ist es oft mühsam, im Modul Persönliche Daten dieselben Felder und dieselbe Reihenfolge hinzukriegen wie man sie im Registrierungsmodul definiert hat.

**Comment by leofeyer** [comment]
Höchstens indem Du ein Modul fertig konfigurierst und dieses dann kopierst und als Ausgangspunkt für das zweite Modul nimmst.
