### ISSUE TITLE
Kalender: Eventliste Menü: Link-Parameter

### ISSUE THREAD

**Issue by mathContao** [contao/core#7953]
Das Kalendermodul "Eventliste-Menü" addiert jeweils die Url-Parameter hinzu (sowohl im Anzeigeformat "Monat" als auch "Jahr").

Das entsteht beispielsweise (Anzeigeformat "Jahr"):
Url: domain.tld/events.html
Menüklick "2015": domain.tld/events.html?year=2015
Nochmal Menüklick "2014": domain.tld/events.html?year=2015?year=2014

Der eigentliche Parameter müsste eigentlich überschrieben werden

Getestet mit Contao 3.5.2

**Comment by leofeyer** [comment]
Wie kann ich das in der Onlinedemo reproduzieren?

**Comment by mathContao** [comment]
Front-End-Modul "Calendar - Event list menu" (ID21) bearbeiten.

http://demo.contao.org/contao/main.php?do=themes&table=tl_module&act=edit&id=21&rt=81e9716221b26f984f5038b481017eb0&ref=b3d6e768

Archiv-Format auf "Monat" oder "Jahr" setzen.

Und dann die Links auf http://demo.contao.org/en/news.html anklicken und dann nochmal.

**Comment by leofeyer** [comment]
Du änderst eine Event-Liste und der Fehler ist anschließend auf der News-Seite zu sehen? Ich vermute mal Du meinst die Event-Seite, allerdings habe ich dort keinen Fehler feststellen können.

**Comment by mathContao** [comment]
Hier die korrigierte Beschreibung, um den Fehler zu reproduzieren:

Front-End-Modul "Calendar - Event list menu" (ID21) bearbeiten.

http://demo.contao.org/contao/main.php?do=themes&table=tl_module&act=edit&id=21&rt=81e9716221b26f984f5038b481017eb0&ref=b3d6e768

Archiv-Format auf "Monat" oder "Jahr" setzen.

Dann hier das Modul von ID18 auf ID21 ändern:
http://demo.contao.org/contao/main.php?do=article&table=tl_content&act=edit&id=53&rt=3daee8453d77007f3bfcb79b2e07f42a&ref=9e02b559

Und dann im Frontend http://demo.contao.org/en/events.html die Links des Event-Menüs anklicken und nach dem Neuladen der Seite nochmal den Link anklicken. Es wird jeweils ein weiterer URL-Parameter angefügt.

**Comment by leofeyer** [comment]
Behoben in 973e1bd7ba15f00ed9b2f97bbc40112de253f062.

**Comment by sonjaeh** [comment]
Kann es sein, dass seit dem Update die im Eventlist-Menü ausgewählte Weiterleitungsseite nicht mehr greift?

**Comment by leofeyer** [comment]
Funktioniert es in der Onlinedemo?

**Comment by sonjaeh** [comment]
Aus meiner Sicht nicht. Habe das Event list menü (Format: Month, Redirect Page: Event Detail) in der Seite Events eingefügt. Zusätzlich ein Event list (Format: Month) auf der Seite Event Detail. Das braucht es aber zu Testzwecken gar nicht, weil man schon sieht, dass das List Menü nicht auf die Weiterleitungsseite verweist. Die Menü-Links lauten /events.html?month= anstatt /event-detail.html?month=

**Comment by leofeyer** [comment]
Wie genau lässt sich das in der Onlinedemo reproduzieren?

**Comment by leofeyer** [comment]
@sonjaeh Sollte sich das Problem in der Onlinedemo reproduzieren lassen, mach bitte ein neues Ticket dazu auf.
