### ISSUE TITLE
Link zu inserttags in Help Wizard zum Inhaltselement "text" (TinyMCE)

### ISSUE THREAD

**Issue by mathContao** [contao/core#7954]
Der Link im Help Wizard (überall wo der TinyMCE verwendet wird) auf contao.org zum Thema inserttags führt auf eine 404-Seite
![unbenannt](https://cloud.githubusercontent.com/assets/1645099/9045777/44e30036-3a26-11e5-82df-f0fba2c7f69c.JPG)
http://demo.contao.org/contao/help.php?table=tl_content&field=text 

Der Link zu Ace ist auch nicht mehr aktuell. Wir umgeleitet auf http://ace.c9.io/#nav=about

Contao 3.5

**Comment by leofeyer** [comment]
Behoben in bedef179caf128d5b0e3bad09f7ed0187183c466.
