### ISSUE TITLE
[Contao 3.5.] PHP-Warnung bei Parameter-Manipulation

### ISSUE THREAD

**Issue by mathContao** [contao/core#7955]
Aus dem Forum: https://community.contao.org/de/showthread.php?55193-Bug-Ung%FCltige-year-month-und-day-Parameter-an-der-URL-erzeugen-Fatal-error&p=379377&viewfull=1#post379377

Seit Contao 3.5 gibt es eine neue Behandlung bei Parametermanipulation bei News/Events

Folgende Manipulation (String statt Zahl) erzeugt trotzdem eine PHP-Warnung:
http://demo.contao.org/en/events.html?month=abc

Warnung:
```
Warning: checkdate() expects parameter 3 to be long, string given in system/modules/core/library/Contao/Date.php on line 436

#0 [internal function]: __error(2, 'checkdate() exp...', '...', 436, Array)
#1 system/modules/core/library/Contao/Date.php(436): checkdate(1, 1, 'abc')
#2 system/modules/core/library/Contao/Date.php(79): Contao\Date->dateToUnix()
#3 system/modules/calendar/modules/ModuleCalendar.php(92): Contao\Date->__construct('abc', 'Ym')
#4 system/modules/core/modules/Module.php(282): Contao\ModuleCalendar->compile()
#5 system/modules/calendar/modules/ModuleCalendar.php(78): Contao\Module->generate()
#6 system/modules/core/elements/ContentModule.php(59): Contao\ModuleCalendar->generate()
#7 system/modules/core/library/Contao/Controller.php(476): Contao\ContentModule->generate()
#8 system/modules/core/modules/ModuleArticle.php(213): Contao\Controller::getContentElement(Object(Contao\ContentModel), 'left')
#9 system/modules/core/modules/Module.php(282): Contao\ModuleArticle->compile()
#10 system/modules/core/modules/ModuleArticle.php(67): Contao\Module->generate()
#11 system/modules/core/library/Contao/Controller.php(409): Contao\ModuleArticle->generate(false)
#12 system/modules/core/library/Contao/Controller.php(269): Contao\Controller::getArticle(Object(Contao\ArticleModel), false, false, 'left')
#13 system/modules/core/pages/PageRegular.php(133): Contao\Controller::getFrontendModule('0', 'left')
#14 system/modules/core/controllers/FrontendIndex.php(267): Contao\PageRegular->generate(Object(Contao\PageModel), true)
#15 index.php(20): Contao\FrontendIndex->run()
#16 {main}
```
Hier wird der Parameter-Value ungeprüft für checkdate() verwendet.

Manipuliert man den Parameter mit einer Zahl, dann kommt die Fehlermeldung NICHT: http://demo.contao.org/en/events.html?month=2015123

Anmerkung zur Contao-Live-Demo: Dort kann man den Haken bei "Display error messages" nicht setzen. Trotzdem kommt die oben gezeigte PHP-Warnung ungefiltert. In meiner lokalen Installation kommt immerhin die normale Meldung "Es ist ein Fehler aufgetreten", wenn "Display error messages" nicht gewählt ist.

**Comment by leofeyer** [comment]
Wie lässt sich das reproduzieren?

**Comment by fritzmg** [comment]
Die von mathContao geposteten Links auf die Contao Demo reproduzieren das ja bereits.

**Comment by leofeyer** [comment]
Ah, mein Fehler. Sorry.

**Comment by leofeyer** [comment]
@contao/developers Ich tendiere hier zum Unterdrücken der Fehlermeldung mittels `@`, da wir ja sowieso eine Exception werfen, wenn `checkdate()` nicht `true` zurück gibt. Was denkt ihr?

**Comment by aschempp** [comment]
In Contao 3 vielleicht. Aber in Contao 4 sollten wir einen Error-zu-Exception Konverter einsetzen, oder?

**Comment by leofeyer** [comment]
Der würde aber nicht die 404er-Seite triggern, oder?

**Comment by aschempp** [comment]
wir müssten die entsprechende (erwartete) exception natürlich catchen und konvertieren.

**Comment by leofeyer** [comment]
Ja, nur wozu? `checkdate()` gibt sowieso `false` zurück und dann kommt unsere eigene Exception.

**Comment by aschempp** [comment]
http://derickrethans.nl/five-reasons-why-the-shutop-operator-should-be-avoided.html <http://derickrethans.nl/five-reasons-why-the-shutop-operator-should-be-avoided.html>

https://insight.sensiolabs.com/what-we-analyse/php.silenced_error <https://insight.sensiolabs.com/what-we-analyse/php.silenced_error>

**Comment by leofeyer** [comment]
Fixed in b6a53e03b4f650cf2377cad6a4494e0c8712a274 then.
