### ISSUE TITLE
[Contao 3] Seitenalias ausblenden, dessen Funktion aber erhalten

### ISSUE THREAD

**Issue by akroii** [contao/core#7957]
Ich bin mir nicht sicher ob es ein Bug oder ein Feature ist.

Im Bezug hierauf: [https://community.contao.org/de/showthread.php?58320-Seitenalias-ausblenden-dessen-Funktion-aber-erhalten&p=378151&viewfull=1#post378151]

Konkret wird der Alias numerisch generiert (also: host.de/543.html) wenn die dazugehörige Einstellung in den Benutzerrechten deaktiviert wird. Wäre es nicht besser wenn man das Feld Alias ausschalten kann, er aber trotzdem einen alphabetischen Alias (also: home.de/test/home.html) erstellt?

**Comment by fritzmg** [comment]
Wie schon im Thread erwähnt, kann man hier auch den `onload_callback` verwenden um das ändern des Alias bspw. für Nicht-Admins zu unterbinden:
```php
$GLOBALS['TL_DCA']['tl_page']['config']['onload_callback'][] = array('tl_page_disable_alias', 'disableAlias');

class tl_page_disable_alias extends \Backend
{
	public function disableAlias()
	{
		if ($this->User->isAdmin)
		{
			return;
		}

		$GLOBALS['TL_DCA']['tl_page']['fields']['alias']['eval']['disabled'] = true;
	}
}
```
