### ISSUE TITLE
Formularrechte - Formulare anlegen

### ISSUE THREAD

**Issue by nuun** [contao/core#7958]
Wenn ein Contao Benutzer (Redakteur) ein Formular neu anlegt, kann derselbe Benutzer das Formular  nicht weiter bearbeiten, da das Formular nicht als «Erlaubtes Formular» gekennzeichnet wird. Gibt es dazu eine Lösung oder einen Workaround? Grüsse ans Core Team.

**Comment by leofeyer** [comment]
Wie lässt sich das in der Onlinedemo reproduzieren?

**Comment by Zeromax** [comment]
Ich vermute mal folgendermaßen:
1. Benutzer anlegen
2. Rechte zum Formular anlegen geben und bestimmte Formulare freischalten
3. Als Benutzer anmelden und ein Formular erstellen und speichern
4. Da das Formular nicht für den Benutzer/Gruppe freigeschaltet ist, kann er es nicht bearbeiten.

Ich vermute aber mal, dass das alle Module betrifft in welchen man erstell rechte für "Archive" hat und die Archive extra zugewiesen werden. Oder?

**Comment by nuun** [comment]
Das ist genau so wie du erklärt hast Zeromax. Es betrifft sicher die Formulare.

Wenn ein Benutzer die Rechte besitzt um Formulare anzulegen, sollte er doch auch direkt die Rechte haben das Formular zu ändern, ohne dass man es als Admin erst freigeben muss.
Dies wäre so mein Input zur Optimierung. 

Momentan habe ich es so gelöst, dass ich dem Benutzer extra "Benutzerrollenrechte" erteilt habe in dem er sich selber Rechte für das neu angelegte Formular geben kann... Nicht ganz so glücklich finde ich.

Was meinen andere dazu? Leo?

**Comment by leofeyer** [comment]
> Wenn ein Benutzer die Rechte besitzt um Formulare anzulegen, sollte er doch auch direkt die Rechte haben das Formular zu ändern, ohne dass man es als Admin erst freigeben muss.

Genau so sollte das eigentlich bereits sein.

**Comment by nuun** [comment]
Sollte. Habe ich mir auch gedacht.
Ist es aber nicht - zumindest auf unserer V 3.4.0.

**Comment by aschempp** [comment]
3.4 ist End Of Live. Bitte auf demo.contao.org mit der 3.5 testen.

**Comment by nuun** [comment]
Getestet auf 3.5 (demo.contao.org) - dort ist dieser Fehler nicht aufgetreten.
Dann gibts wohl ein Update meiner 3.4 Installation.
Danke dem Core Team für die Inputs und für das Lösen dieses Bug's in 3.5!
