### ISSUE TITLE
Formulargenerator Formfields (Überschrift vs. Erklärung)

### ISSUE THREAD

**Issue by asaage** [contao/core#7960]
Nichts dramatisches - ich hatte mich grad nur gewundert...
Bis auf die css-Klasse im Frontend scheint es da ja keinen Unterschied zu geben.
Ich hatte allerdings ein Textfeld + select (h1-h6) anstelle eines Rich-Text-Editors erwartet.

**Comment by leofeyer** [comment]
?

**Comment by asaage** [comment]
Mir erschließt sich im Formulargenerator einfach nicht der Unterschied zwischen Field type "Headline" und "Explanation".
Weil es aus Kompatibilitätsgründen diesbezüglich eh keine Änderung geben wird schließ ich Sache wieder. Man muß ja nicht alles verstehen.

**Comment by leofeyer** [comment]
Diese Art Fragen stellst Du ohnehin am besten im [Forum](https://community.contao.org/de/).

In Contao 4 wurde der Feldtyp "Überschrift" übrigens entfernt. Die beiden Typen waren historisch bedingt noch beide in Contao 3 vorhanden.
