### ISSUE TITLE
Bug - Accordion: nicht mehr korrekt fokusierbar

### ISSUE THREAD

**Issue by NinaG** [contao/core#7963]
Wenn man z.B. drei Accordions untereinander hat, kann man noch das erste antabben, aber die nachfolgenden Toggler erreicht man nicht mehr, weil der Fokus nicht auf deren Toggler gesetzt werden kann.

Wir hatten eigentlich mal ein barrierefreies Accordion, das auch tastaturbedienbar war, aber nun ist das nicht mehr der Fall. Scheinbar ist da irgendwo zwischen Contao 3 und dem aktuellen Contao der entsprechende Code so verändert worden, dass die Angaben nicht mehr stimmen.

Wie testen?
-----------
1. Drei Accordions anlegen
2. Am besten im CSS einen einfachen Style a'la 
.ce_accordion .toggler:hover, .ce_accordion .toggler:focus { text-decoration: underline; } anlegen, damit man das Fokusieren des Togglers auch visuell sieht (hilft beim Testen).
3. Seite neu laden und dann so lange die Tabulator-Taste drücken, bis man beim Accordion ankommt. Das erste kann man noch antabben und dadurch auch öffnen, aber die nachfolgenden Accordion-Toggler sind nicht mehr erreichbar.

Vermutung: Ich sehe, dass die nachfolgenden Accordions dauerhaft das tabindex -1 behalten, wenn man nur per Tastatur unterwegs ist. Dadurch sind sie aus der Fokusierung ausgeschlossen. Es müsste sich in ein tabindex 0 wandeln, damit sie sich in die normale Fokusierungsreihenfolge einreihen.

**Comment by aschempp** [comment]
Verwendest du Mootools oder jQuery? Die Scripte sind nach meinem Wissen ziemlich unterschiedlich. Vielleicht kannst du beide testen?

**Comment by NinaG** [comment]
Zum Vergleich, der damalige Aufbau:
https://github.com/contao/core/blob/fbdc9f9f61598cd200fe68598ca9c43f05c09556/system/modules/core/templates/j_accordion.html5

Der heutige:
https://github.com/contao/core/blob/master/system/modules/core/templates/jquery/j_accordion.html5

Ich bezieh mich auf jQuery.

**Comment by NinaG** [comment]
Meines Wissens, war das Verhalten 'damals' so...

Erster Aufruf der Seite:
Das erste toggler-div hat ein tabindex="0"
Das zweite toggler-div hat ein tabindex="-1"	

Tabulator springt aufs erste toggler-div:
Wenn der Tabulator (Fokus) auf dem ersten toggler-div ist, ändert sich sein Attribut in tabindex="-1".
Gleichzeitig springt beim zweiten toggler-div das Attribut auf tabindex="0" damit es nun auch per Tastatur anfixierbar ist

**Comment by aschempp** [comment]
Die inkorrekte Variante stammt aus 086ac6133c1d34e08b4f8575240965f1853bbe1f bzw. Ticket #7622. Da hat @leofeyer wohl etwas zu stark vereinfacht…

**Comment by NinaG** [comment]
Heutiges Verhalten hingegen am Beispiel der Demoseite:
http://demo.contao.org/en/accordion.html

Erster Aufruf der Seite:
wie früher auch

Tabulator springt aufs erste toggler-div:
Es tut sich gar nichts beim tabindex-Attribut und somit sind alle nachfolgenden Accordions nicht mehr anfokusierbar.

**Comment by leofeyer** [comment]
Die Vereinfachung ist korrekt. Das jQuery-Akkordeon hat bereits ein eingebautes ARIA-Handling.

**Comment by NinaG** [comment]
Es geht nicht um das Aria-Handling, es geht um den Fehler vom tabindex. Der verursacht, dass alle Accordions nach dem ersten überhaupt nicht von Tastaturnutzern erreicht werden können!

**Comment by leofeyer** [comment]
Ich habe das Tabindex-Handling nur dem `moo_accordion`-Template angeglichen. Dort wird der Tabindex auch nur statisch auf `0` gesetzt und bekommt kein `-1`. Wenn müssen schon beide Templates (Mootools und jQuery) dasselbe machen.

**Comment by NinaG** [comment]
Von mir aus kann das Accordion auch generell dauerhaft nur ein tabindex=0 haben. Damit ist es fokusier- und somit erreichbar.

Aber derzeit ist es eben technisch falsch umgesetzt, so dass es ein -1 erhält und auch behält. Damit sind diese Accordions nicht mehr fokusierbar und somit für sehbehinderte Nutzer vollkommen unerreichbar.

**Comment by NinaG** [comment]
Also um das nochmal zu erklären:

Normalerweise ist der Accordion-Titel nicht fokusierbar, weil es kein Element ist, das regulär Fokus haben kann (also kein echter Link o.ä.).

Mit dem Tabindex-Attribut kann man das ändern.

Wenn der Accordion-Titel das Tabindex-Attribut mit dem Wert "0" erhält, wird es fokusierbar und reiht sich in die normale Tabulator-Reihenfolge (entsprechend dem DOM) ein.

Wenn der Accordion-Titel das Tabindex-Attribut mit dem Wert "-1" erhält, wird das Element nicht in die normale Tab-Reihenfolge aufgenommen, ist aber mittels Javascript (element.focus()) fokussierbar. Der Negativwert sollte aus diesem Grund imho auch nur mittels Javascript/DOM-Scripting zugewiesen werden, da er eben nicht Bestandteil der regulären HTML-Spezifikation ist.

Soll heißen: Es ist imho völlig in Ordnung, wenn die Accordion-Titel pauschal ein tabindex="0" haben. Sie sollten aber keinesfalls pauschal (und dauerhaft) ein tabindex="-1" ohne korrespondierendes focus-Scripting haben, da sie sonst nicht für Tastatur-Nutzer (o.ä. Eingabegeräte) erreichbar sind.

**Comment by leofeyer** [comment]
Behoben in 24bcf2de8badc7b4e1ef8c64cdf990cdde98e61b.

**Comment by NinaG** [comment]
Vielen Dank
