### ISSUE TITLE
ContentHyperlink with Image link—Cannot use custom template

### ISSUE THREAD

**Issue by blairwinans** [contao/core#7964]
Not sure if this is by design, but when trying to use a custom `ce_hyperlink_` template as well as an image link, it always defaults back to the `ce_hyperlink_image` template.

I would think you would want to be able to not just override the default `ce_hyperlink_image` but also be able to specify your own. I am using Contao 3.5.2, but this goes back a while. It all comes down to this [code](https://github.com/contao/core/blob/master/system/modules/core/elements/ContentHyperlink.php#L68), which is not respecting the custom template setting.

Steps to reproduce:

1. Create a Hyperlink element.
2. Select "Create an image link"
3. Select a custom template (i.e. ce_hyperlink_mycustomtemplate)
4. On the frontend, no matter what template you select, ce_hyperlink_image is always used

**Comment by leofeyer** [comment]
That's a known issue which has been solved in Contao 4.
