### ISSUE TITLE
Pfadnavigation in Dateiverwaltung bei gleichnamigen Verzeichnissen nicht verlinkt

### ISSUE THREAD

**Issue by Samson1964** [contao/core#7965]
In der Dateiverwaltung werden die übergeordneten Verzeichnisse im Pfad nicht verlinkt, wenn das aktuelle Verzeichnis den gleichen Namen hat. Getestet an der Online-Demo 3.5.2 und an einer 3.2.20 (siehe Bild).
![pfadverlinkung](https://cloud.githubusercontent.com/assets/4542730/9250739/a031fac2-41cf-11e5-8d3f-5415e769423c.jpg)
Das Bild zeigt den Pfad "Alle - dsb - images - _newsalt - images". Das erste "images" wird fälschlicherweise nicht verlinkt.

**Comment by leofeyer** [comment]
Wie genau lässt sich das in der Onlinedemo reproduzieren?

**Comment by asaage** [comment]
2 gleichnamige Ordner ineinander schachteln, dann "nur diesen Knoten anzeigen" wählen (bei dem in der Hirarchie tieferliegenden) dann versuchen in der gelben Breadcrumb den höhergelegenen gleichnamigen anzusteuern.

**Comment by leofeyer** [comment]
Behoben in 9db5070216a3d2d0f81261188b4c47344e5a75bd.
