### ISSUE TITLE
Insufficient SQL LIKE escaping in FilesModel

### ISSUE THREAD

**Issue by backbone87** [contao/core#7966]
https://github.com/contao/core/blob/master/system/modules/core/models/FilesModel.php#L316
`FilesModel::findMultipleFilesByFolder`

Die Backslashes werden nicht ausreichend escaped und ein Backslash in $strPath wird gar nicht escapt: `$strPath = str_replace(array('%', '_'), array('\\%', '\\_'), $strPath);`

Korrekt wäre: `$strPath = str_replace(array('%', '_', '\\'), array('\\\\%', '\\\\_', '\\\\\\\\'), $strPath);`

Warum: Backslashescape-Sequenzen werden 3-fach aufgelöst, vom PHP-Parser, vom SQL-Parser und dann vom LIKE-Regex-Parser. Relevante Dokumention: https://dev.mysql.com/doc/refman/5.7/en/string-comparison-functions.html (hier wird natürlich nur von den 2 MySQL-seitigen Parsern gesprochen)

**Comment by backbone87** [comment]
Noch ein lustiger Randeffekt: Warum ist dieser Fehler bisher nicht aufgetreten? Weil % und \ wohl selten in Dateinamen vorkommen und die so nicht escapten Chars als Wildcards trotzdem **mindestens** die zu erwartende Dateimenge selektieren.

**Comment by leofeyer** [comment]
Soweit ich weiß ist der Backslash kein MySQL-Platzhalter, oder?

**Comment by leofeyer** [comment]
@contao/developers

**Comment by ausi** [comment]
Ich denke die Anzahl der Backslashes ist bereits korrekt, `'\\\\%'` wäre falsch. Es stimmt, dass die Backslashes dreifach aufgelöst werden, allerdings wird das Escape-Level durch [`Statement::string_escape()`](https://github.com/contao/core/blob/ac68761904694febb7636efacf34c30575e720a0/system/modules/core/library/Contao/Database/Mysqli/Statement.php#L49-L52) bereits um eins erhöht. Ein kurzer Test hat das auch bestätigt:

```php
FilesModel::findMultipleFilesByFolder('files'); // findet alle Dateien in files/
FilesModel::findMultipleFilesByFolder('f%les'); // findet nichts
FilesModel::findMultipleFilesByFolder('f_les'); // findet nichts
```

Dass die Backslashes nicht escaped werden, ist jedoch in der Tat falsch. Was ein Test auch besätigt:

```php
\FilesModel::findMultipleFilesByFolder('f\\iles') // findet alle Dateien in files/
```

Korrekt wäre also `str_replace(array('\\', '%', '_'), array('\\\\', '\\%', '\\_'), ...`.

**Comment by leofeyer** [comment]
Behoben in 9ab0bcf9f70ff2245eae9a0f7bd6e55476c09aaf.
