### ISSUE TITLE
Navigationsmenü: Link auf index funktioniert nicht in Microsoft Edge 

### ISSUE THREAD

**Issue by reinweiss** [contao/core#7967]
Wenn die Startseite den Seitenalias "index" hat, steht in der Navigation href="".
Microsoft Edge mag dem Link nicht folgen und bleibt auf der gleichen Seite.

**Comment by Aybee** [comment]
Nice to know, but it's no Contao bug, it's an MS Edge bug.

**Comment by reinweiss** [comment]
Die Frage ist, ob aus dem Seitenalias "index" zwingend href="" gemacht werden muss. Wird ein anderer Alias wie z.B. home, startseite etc. verwendet, funktioniert alles.

**Comment by asaage** [comment]
würde "index" nicht zu href="" gäbe es ein Problem mit duplicate content.
Microsoftbrowser bleiben wohl ein Mysterium.

**Comment by reinweiss** [comment]
Ich bin mir nicht sicher, dass es richtig ist href="" zu schreiben. Was spricht gegen href="/"?

**Comment by Aybee** [comment]
Das `/` ist ja schon im BASE. Also ich bin dagegen, dass wir wieder anfangen MS Bugs auszubügeln. Außerdem weiß MS ja auch wie die HREFs aufgelöst werden sollen und gibt es ja auch selber an, z.B. hier ganz unten bei Examples https://msdn.microsoft.com/en-us/library/ms535191%28v=vs.85%29.aspx

**Comment by asaage** [comment]
zum einen die eingabevalidierung bei deaktivierten folder-urls,
zum anderen das Ergebnis ```example.com/.html``` wenn du Dateiendungen verwendest.
Die schnellste Lösung wäre warscheinlich die Verwendung von home oder startseite + eine Anpassung in den Rewriteregeln der htaccess

**Comment by aschempp** [comment]
Ich seh da nicht so ein Problem, wir sollten einfach einen absoluten Base Link generieren. Also z.B. "/" oder halt "/mein/contao/".

**Comment by Aybee** [comment]
> ... absoluten Base Link generieren...

Verstehe ich jetzt nicht so richtig. Meinst du statt
```html
<base href="https://contao.org/">
```
so?
```html
<base href="/">
```
Folgendes müsste eigentlich aufgelöst werden nach `https://contao.org//`.
```html
<base href="https://contao.org/">
...
<a href="/"...
```

**Comment by asaage** [comment]
```html
<base href="https://contao.org/">
...
<a href="./">link</a>
```
würde dann gehen.
Aber das Microsoft Edge ein ```<a href=""...``` nicht schluckt ist schon sehr seltsam da valide.

**Comment by reinweiss** [comment]
https://www.ietf.org/rfc/rfc2396.txt
---
4.2. Same-document References

A URI reference that does not contain a URI is a reference to the
current document.
[...]
---

**Comment by BugBuster1701** [comment]
<a href="./">link</a>

muss gar nicht sein, ein 

    <a href=".">link</a>

reicht bei meinen Tests schon.

**Comment by tabcontao** [comment]
Um das obige Zitat noch ein wenig zu erweitern:

A URI reference that does not contain a URI is a reference to the
current document.  In other words, an empty URI reference within a
document is interpreted as a reference to the start of that document,
and a reference containing only a fragment identifier is a reference
to the identified fragment of that document.

Also beim Fix bitte gleich berücksichtigen:

`<a href="#some_id">link</a>`

ist dann auch als ein Verweis auf ein Fragment des aktuellen Dokuments zu interpretieren und verweist NICHT automatisch auf die Startseite.

**Comment by aschempp** [comment]
In Zusammenhang mit dem <base> Tag scheint das anders. Kann natürlich sein dass Edge den Base-Tag (wieder) falsch behandelt…

**Comment by tabcontao** [comment]
Das mag ich gar nicht beurteilen, was richtig ist und was nicht. Klar ist nur, dass "empty URI reference" und "reference containing only a fragment identifier" in einem Atemzug genannt werden und somit so oder so gleich behandelt werden müssen. Wobei das Fragment eher kein Problem darstellt, weil Contao meines Wissens nirgends so eine URL erzeugt, in der nur ein Fragment drinsteht, das dann auf das entsprechende Fragment der Startseite verlinken soll. Der einzige Fall, der mir auf Anhieb einfällt ist der Toplink, der enthält im Link aber auch noch die Seite und nicht nur href="top". Und da wahrscheinlich keiner für Edge und alle anderen Browser jeweils zwei Links unterscheiden will, fährt man mit diesem zulässigen Workaround sowieso am besten. Der wird überall funktionieren, sogar in Edge.

**Comment by leofeyer** [comment]
Geändert in c9eab397c7c0859a6c4e0210f291b3bfdc628f01.

**Comment by Aybee** [comment]
> A URI reference that does not contain a URI is a reference to the
current document. In other words, an empty URI reference within a
document is interpreted as a reference to the start of that document,...

Diese URI reference "contains" eine URI und ist nicht "empty"
```html
<base href="https://contao.org/">
...
<a href=""...
```
Wie auf https://tools.ietf.org/html/rfc3986 im Kapitel zum Base-Tag nachgelesen werden kann. Denn der Wert im Base-Tag muss erst einmal davor gesetzt werden.

**Comment by fritzmg** [comment]
Und genauer gesagt wird die _Base URI_ for jede _Relative Reference_ gesetzt und eine _Relative Reference_ ist so definiert:
```
      relative-ref  = relative-part [ "?" query ] [ "#" fragment ]

      relative-part = "//" authority path-abempty
                    / path-absolute
                    / path-noscheme
                    / path-empty
```
inkludiert also unter anderem `path-empty`, während `path-empty` wiederum
```
path-empty    = 0<pchar>
```
einfach ein leerer String ist - im Falle der HTML also bspw. `href=""`.

Ist also eine _Base URI_ im HTML Dokument definiert dann entspricht `href=""` einfach der _Base URI_. Ist keine _Base URI_ definiert entspricht es dem aktuellen Pfad.

Dass sich Microsoft in deren neuen Browser nicht daran hält ist schon ein starkes Stück (vor allem weil sich auch sonst alle anderen Browser daran halt, inklusive allen Internet Explorer Versionen, zumindest seit Version 6).

**Comment by Ainschy** [comment]
Das schafft ein neues Problem:

Eine Startseite mit dem Alias index wird in der Navigation nicht mehr mit active gekennzeichnet, selbst wenn diese über die Navigation direkt aufgerufen wird. Der Link erhält die Klasse trail

**Comment by fritzmg** [comment]
> Das schafft ein neues Problem:
> 
> Eine Startseite mit dem Alias index wird in der Navigation nicht mehr mit active gekennzeichnet, selbst wenn diese über die Navigation direkt aufgerufen wird. Der Link erhält die Klasse trail

Wurde hier schon reported: https://github.com/contao/core/issues/8006

**Comment by Ainschy** [comment]
Danke für den Hinweis, hatte nur in den Issus zur 3.5.3 geschaut.

**Comment by vstuber** [comment]
Mir ist gerade aufgefallen, dass die Funktion "generateFrontendUrl" für eine Seite mit dem Alias "index" in gewissen Situationen (addLanguageToUrl=false, rewriteURL=true) einen Leerstring zurückgibt. Wäre es nicht richtig, hier dann auch "./" zurückzugeben anstatt des Leerstrings? Ansonsten muss man den Rückgabewert der Funktion stets selbst prüfen und entsprechend ändern.
