### ISSUE TITLE
Keine Fehlermeldung bei falschem Login durch Seitencache

### ISSUE THREAD

**Issue by matthiasneid** [contao/core#7968]
Wenn man bei Contao (getestet in 3.4.5 und in der Demo mit 3.5.2) für eine Seite, die ein Loginmodul enthält den Seitencache aktiviert (z.B. 6h) und dann **falsche** (keine leeren) Daten in dieses Loginmodul eingibt, wird nach dem Absenden des Loginformulars keine Fehlermeldung mehr angezeigt, da die Seite aus dem Cache geladen wird.

Das liegt daran, dass Contao die Fehlermeldung bei falschen Nutzernamen/Passwort über die Funktion `\Message::addError($GLOBALS['TL_LANG']['ERR']['invalidLogin']);` ([User.php](https://github.com/contao/core/blob/d11b2257e9a9c2b9b5daadb383298782f3a065d0/system/modules/core/library/Contao/User.php#L343)) in der Session `$_SESSION['TL_ERROR']` gespeichert wird und nicht wie z.B. bei leerer Eingabe ([ModuleLogin.php](https://github.com/contao/core/blob/d11b2257e9a9c2b9b5daadb383298782f3a065d0/system/modules/core/modules/ModuleLogin.php#L62)) in der Session `$_SESSION['LOGIN_ERROR']`. 

Nach der Weiterleitung wandelt [ModuleLogin.php](https://github.com/contao/core/blob/d11b2257e9a9c2b9b5daadb383298782f3a065d0/system/modules/core/modules/ModuleLogin.php#L196) die Fehlermeldung aus `$_SESSION['TL_ERROR']` in einen `LOGIN_ERROR` um. 

Dazu kommt es allerdings bei aktiviertem Seitencache erst gar nicht, da bei der Überprüfung, ob die Seite aus dem Cache geladen werden könnte in der [FrontendIndex.php](https://github.com/contao/core/blob/6f5d80a36de35f31a90f232470d892e02d409fa1/system/modules/core/controllers/FrontendIndex.php#L295) nur überprüft wird, ob ein `LOGIN_ERROR` existiert.

Die Fehlermeldung müsste also direkt in `$_SESSION['LOGIN_ERROR']` gespeichert werden oder vor der Weiterleitung von `TL_ERROR` in `LOGIN_ERROR` umgewandelt werden. Alternativ könnte natürlich auch `TL_ERROR` bei der Cache Überprüfung berücksichtigt werden.

**Comment by leofeyer** [comment]
@contao/developers Wir sollten eigentlich generell `$_SESSION['LOGIN_ERROR']` abschaffen und stattdessen `$_SESSION['TL_ERROR']` prüfen. Denn es macht ja niemals Sinn, eine Seite zu cachen, wenn ein Fehler vorliegt – egal ob ein Login-Fehler oder ein anderer, oder?

**Comment by Toflar** [comment]
Seiten mit Formularen cachen macht alleine wegen CSRF eigentlich nie Sinn. Klar, man könnte auch hier wieder mit ESI und Co. arbeiten aber generell sollten imho Seiten mit Formularen nicht gecached werden.

**Comment by leofeyer** [comment]
Wie am 10. September auf Mumble besprochen, wollen wir das zwar grundsätzlich anpassen (wird vermutlich erst in Contao 4 möglich sein), es bleibt aber dabei, dass Seiten mit Formularen niemals eine Cache-Zeit haben dürfen. Insofern musst Du das im Seitenbaum entsprechend umstellen.

**Comment by leofeyer** [comment]
Das Ticket bezüglich der in Contao 4 geplanten Anderungen ist contao/core-bundle#343.
