### ISSUE TITLE
[3.5.x] die nicely Templates

### ISSUE THREAD

**Issue by Zeromax** [contao/core#7969]
Just started to cutomize the Backend Theme and wanted to change the look and feel of the Templates which are called via the `die_nicely()` function in https://github.com/contao/core/blob/6aaa26c5051b23b7881b4d73bd816aab567284d6/system/helper/functions.php#L135

The Problem is, that I can not change the Templates cause they should be stored directly inside the `/templates` folder or the core templates folder.

Is it possible to check inside the theme directory? Like:
````php
$theme = Backend::getTheme();
if (file_exists(TL_ROOT . "/system/themes/$theme/templates/$strTemplate.html5"))
{
	include TL_ROOT . "/system/themes/$theme/templates/$strTemplate.html5";
}
```

This would allow to cutomize all back end templates which are called via `die_nicely` inside of a back end Theme.

What do you think?

**Comment by leofeyer** [comment]
Since this is a feature request, the next possible version to be included is Contao 4.1. However, we have dropped the `die_nicely()` function in Contao 4 …

**Comment by aschempp** [comment]
This would be a new feature, but the templates in Contao 4 have changed and are now rendered via Twig…

**Comment by Zeromax** [comment]
For me it is a bug ;)
Ok, so may be this problem won't occure if I use Contao 4? Cause the template loading is different?

**Comment by aschempp** [comment]
Yeah it would be about the PrettyErrorScreens now…

**Comment by Zeromax** [comment]
Ok. So I hopefully check this out after my holidays. If there is a problem in C4 I wil open an Issue there.

I Close this here, cause it is a feature Request.
