### ISSUE TITLE
Win10 Browser Edge wird als Chrome erkannt

### ISSUE THREAD

**Issue by BugBuster1701** [contao/core#7970]
Mit win10 Browser wird in der body Zeile generiert

    <body id="top" class="win chrome webkit ch42">

Als wäre das ein Chrome/Chromium Version 42.

Der Agent lautet:

    Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2311.135 Safari/537.36 Edge/12.10240

**Comment by BugBuster1701** [comment]
siehe auch dazu [User-agent string changes](https://msdn.microsoft.com/en-us/library/hh869301%28v=vs.85%29.aspx)

**Comment by Toflar** [comment]
Ist wohl jetzt die Frage ob wir den als `Internet Explorer` oder `Edge` ausweisen sollen :)

**Comment by leofeyer** [comment]
Das ist in der Tat eine Frage. @contao/developers

**Comment by ausi** [comment]
Ich bin für `Edge`. Soweit ich weiß war eines der Ziele von Edge nicht mehr als IE erkannt zu werden um nicht von Websites speziellen Code für alte IEs zu bekommen.

**Comment by Toflar** [comment]
Ich bin auch für `Edge`.

**Comment by ausi** [comment]
Vielleicht können wir die Browser-Erkennung in zukünftigen Contao-Versionen komplett weglassen?

**Comment by BugBuster1701** [comment]
[Piwik](https://github.com/piwik/device-detector/blob/master/regexes/client/browsers.yml#L10) macht draus: Microsoft Edge 12

In meinem Visitors Modul wird demnächst "Edge 12 / Edge Mobile 12" auftauchen.
So ganz loslassen kann MS aber scheinbar auch nicht, müsste ja Edge 1 sein :-)

**Comment by BugBuster1701** [comment]
daher wäre ich auch für "Edge"

**Comment by leofeyer** [comment]
Behoben in 0f1960afed1a41c983675819e6ecd38feeab2611.

**Comment by Aybee** [comment]
> @ausi Vielleicht können wir die Browser-Erkennung in zukünftigen Contao-Versionen komplett weglassen?

Was wäre der Vorteil? Ich hatte das schon einige Male benutzt und fand es recht praktisch. Das wäre doch auch ein BC-Break, oder?

**Comment by ausi** [comment]
@Aybee Browser Sniffing [sollte man nicht machen](http://www.sitepoint.com/why-browser-sniffing-stinks/), es ist schwer aktuell zu halten, sehr Fehleranfällig und ist in den meisten Fällen nicht nötig.

So wird in Contao z. B. der aktuelle Opera nicht erkannt, ein BlackBerry Z30 als mobile Safari 10, ein Nokia N9 mit falscher Version und so weiter.

Man sollte möglichst immer auf Feature-Detection setzen, z. B. mit [Modernizr](http://modernizr.com/).

An welchen Stellen hast du es denn benötigt?

Wegen des BC-Breaks dürfte es natürlich erst in der nächsten Major-Version entfernt werden.

**Comment by BugBuster1701** [comment]
Das Contao Backend nutzt das selbst für einige spezielle CSS Angaben.
Ich gehe mal davon aus dass dies noch so ist, ist ne Weile her wo ich das gesehen habe.

**Comment by Aybee** [comment]
> @ausi An welchen Stellen hast du es denn benötigt?

War nichts Weltbewegendes, ein paar CSS-Anpassungen für diverse IEs, und die mobile-Klasse mal benutzt. Normalerweise benutze ich die mobile-Klasse nicht sondern benutze media-queries. Aber es war schon praktisch. War glaube ich irgendwas mit Javascript `if(body.hasClass('mobile'))`

Modernizr ist mir zu aufgebläht und ich mag auch die zig CSS-Klassen im HTML-Tag nicht.

**Comment by ausi** [comment]
Für alte IEs kann man Conditional Comments einsetzen. Bei der `mobile` Klasse sehe ich das Problem, dass ein iPhone 6 Plus im Querformat mit 736 Pixel „mobile“ ist aber ein Nexus 7 mit 600 Pixel oder ein Nokia N9 mit 360 Pixel nicht. Was genau sagt „mobile“ aus?

Modernizr kann man konfigurieren, dass es nur die benötigten Detections enthält, die CSS-Klassen im HTML-Tag sind optional. In JavaScript kann man einfache Checks sonst auch direkt durchführen, ohne Modernizr.

**Comment by Aybee** [comment]
@ausi Danke für diese Infos.

Tja, das habe ich mir schon gedacht, dass .mobile nicht viel aussagt bzw. auch abhängig von der Contao Sniffer Klasse ist. Soviel ich weiß wird halt der UA analysiert, weil mit PHP da nicht mehr möglich ist. Aber dann kann man ja auch das "Layout für mobile Seiten" in Contao vergessen, weil es sich doch an diesem 'mobile' orientiert, soviel ich weiß. Na ja, habe ich bis jetzt auch noch nicht benutzt. Das 'mobile' sollte ja eigentlich ein Indikator für Smartphones sein, oder?

Aber nach wie vor finde ich es gut, dass ie, ie9 usw. als Klasse im Body vorhanden ist. Ich denke das ist sehr zuverlässig, solange ein User seinen UA nicht manipuliert hat.

ps Dass ein Touch-Screen nicht erkannt werden kann, hatte ich vor einiger Zeit bereits heraus gefunden.
