### ISSUE TITLE
ModuleWizard does not execute save_callback

### ISSUE THREAD

**Issue by aschempp** [contao/core#7972]
The ModuleWizard has `$blnSubmitInput` set to `false`, because it internally stores the values in the database.

Unfortunately, this does not execute `save_callback` and there's no way to check/manipulate the values.

**Comment by aschempp** [comment]
Which will probably also prevent a new version to be created if only the modules are changed.

**Comment by leofeyer** [comment]
How would you fix this?

**Comment by aschempp** [comment]
How about using the regular save method except if the GET parameters are set (javascript fallback) ?

**Comment by leofeyer** [comment]
?

**Comment by aschempp** [comment]
The widget is saving it's value on it's own for no reason in https://github.com/contao/core/blob/master/system/modules/core/widgets/ModuleWizard.php#L140

It should only do that for `\Input::get($strCommand)` but not for `\Input::post('FORM_SUBMIT') == $this->strTable`.

For some reason it also loads the current record on it's own (https://github.com/contao/core/blob/master/system/modules/core/widgets/ModuleWizard.php#L91-L97) instead of using `$dc->activeRecord` for example.

**Comment by leofeyer** [comment]
I am sure that there is a reason why the widget behaves this way, however, I do not remember. Will you be creating a PR?

**Comment by aschempp** [comment]
Yes I make :)

**Comment by aschempp** [comment]
fein

**Comment by aschempp** [comment]
see #355
