### ISSUE TITLE
htaccess Info in tl_files should consider Litespeed

### ISSUE THREAD

**Issue by Toflar** [contao/core#7974]
In the back end when adding a folder and not running Apache you get the hint

> Folder protection is accomplished by adding a .htaccess file which denies access to the folder. It seems that you are not using an Apache server, therefore the feature might not work at all or require to adjust your server configuration. Please double-check before uploading any non-public resources!

My installation runs on LiteSpeed (https://www.litespeedtech.com) which is a drop in replacement and does support htaccess protection as well.

So probably we should extend this check [here] (https://github.com/contao/core/blob/hotfix/3.5.3/system/modules/core/dca/tl_files.php#L679) to also check for `LiteSpeed` (and probably others?) and rephrase the message to something like `It seems that you are not using an htaccess compatible server`. What do you think?

**Comment by leofeyer** [comment]
I'm not that big a fan of supporting commercial products.

**Comment by aschempp** [comment]
This is fairly obsolete with Contao 4?

**Comment by discordier** [comment]
It is and therefore the check could be dropped completely. Especially as everyone seems to be favoring nginx these days.
