### ISSUE TITLE
Link Tastaturkürzel im Backend Startseite

### ISSUE THREAD

**Issue by bekanntmacher** [contao/core#7976]
Der Link "Tastaturkürzel" hat geändert. 
https://docs.contao.org/books/manual/3.5/de/02-administrationsbereich/backend-tastaturkuerzel.html

1. Link im Backend anpassen
2. Alter Link weiterleiten (alt: https://contao.org/manual/administration-area.html#backend-tastaturkuerzel)

**Comment by leofeyer** [comment]
Siehe #7935.
