### ISSUE TITLE
[3.5.2] Link Tastaturkürzel auf Backend-Startseite defekt

### ISSUE THREAD

**Issue by Mynyx** [contao/core#7977]
Auf der Startseite des Backends ist der Link zur Dokumentation der Tastaturkürzel auf contao.org defekt.

````
Backend-Tastaturkürzel

Wie Sie Ihren Arbeitsablauf durch die Verwendung von >Tastaturkürzeln< beschleunigen.
````
https://contao.org/manual/administration-area.html#backend-tastaturkuerzel

**Comment by BugBuster1701** [comment]
Siehe #7935.
