### ISSUE TITLE
[3.5.2] Modul Events Zeitspannen mit Halbgeviertstrich

### ISSUE THREAD

**Issue by Mynyx** [contao/core#7978]
Bei Angaben von Zeitspannen im Modul Events steht als "Bis-Strich" ein Bindestrich/Viertelgeviertstrich.

Typografisch schöner wäre der Halbgeviertstrich (siehe auch https://de.wikipedia.org/wiki/Halbgeviertstrich#Bis-Strich).

**Comment by leofeyer** [comment]
Allein das Wort "Halbgeviertstrich" – Willkommen in Deutschland :)

**Comment by aschempp** [comment]
![127421_stackenblocken_1](https://cloud.githubusercontent.com/assets/1073273/9405485/60025562-47f8-11e5-875f-13fee8e4be61.jpg)

**Comment by leofeyer** [comment]
Geändert in d6a8310a5eee50a5d788ed8d4900ad257f3ee88d.
