### ISSUE TITLE
Bug in the Installer.php when trying to recognize the collation

### ISSUE THREAD

**Issue by Toflar** [contao/core#7979]
When you try to set an explicit collation on a certain field like

```php
'sql' = "varchar(10) COLLATE utf8_general_ci NOT NULL default ''"
```

It does not work if the collation equals the DB collation settings and it will keep proposing that change in the DB update back end view.
This is due to https://github.com/contao/core/blob/d11b2257e9a9c2b9b5daadb383298782f3a065d0/system/modules/core/library/Contao/Database/Installer.php#L460

Obviously I don't need to specify `utf8_general_ci` if the DB collation is the same but if I want to make sure it is in that collation, then I have to specify it and it should only propose to change it when my DB is NOT `utf8_general_ci`.

**Comment by leofeyer** [comment]
Fixed in 587fcac5568ee8b3ab48985b1cfa71f8b04fac74.
