### ISSUE TITLE
[3.5.2] Backend Breadcrumb Dateiverwaltung neuer Ordner

### ISSUE THREAD

**Issue by Mynyx** [contao/core#7980]
Im Backend wird das Breadcrumb in der Dateiverwaltung bei Anlage eines neuen Ordners nicht korrekt angezeigt:

````Dateiverwaltung » files/__new__````

**Comment by BugBuster1701** [comment]
Weil zu dem Zeitpunkt der Name noch nicht bekannt ist? Was sonst sollte denn angezeigt werden?

**Comment by Mynyx** [comment]
Irgendeine weniger kryptische Darstellung, beispielsweise ``Dateiverwaltung » files`` oder ``Dateiverwaltung » files  » Neuer Ordner``

**Comment by Mynyx** [comment]
Wenn man sich an der Darstellung beim Erstellen eines neuen Templates orientiert, müsste es hier ``Dateiverwaltung » files » Einen neuen Ordner anlegen`` heißen

**Comment by Zeromax** [comment]
Same for News: http://demo.contao.org/contao/main.php?do=news&table=tl_content&act=edit&id=320

![unbenannt](https://cloud.githubusercontent.com/assets/1867177/9669472/b16c08d2-5287-11e5-8cad-0c0bf3d18940.PNG)

**Comment by leofeyer** [comment]
Geändert in 1b852e96b4f54a70a1dda40f10e64e4f98a0b95e.
