### ISSUE TITLE
[3.5.2] Backend Breadcrumb Event bearbeiten

### ISSUE THREAD

**Issue by Mynyx** [contao/core#7981]
Im Backend wir beim Bearbeiten eines Events (z. B. http://demo.contao.org/contao/main.php?do=calendar&table=tl_content&id=5) im Breadcrumb eine zusätzliche leere Ebene angezeigt:

````Events » Contao Public Example Events » » Contao Example Event````

**Comment by leofeyer** [comment]
Behoben in e2ee31d888bb3f48a220be78c91079f4fb96a258.
