### ISSUE TITLE
Formulargenerator: Typ Überschrift ist nicht <h1>...<h6>

### ISSUE THREAD

**Issue by mathContao** [contao/core#7982]
Wählt man im Formulargenerator den Feldtyp "Überschrift", dann steht der TinyMCE zur Verfügung. Identisch wie Feldtyp "Erklärung"

![unbenannt](https://cloud.githubusercontent.com/assets/1645099/9425332/d4f5b02a-490c-11e5-839c-6a90a9bfbda8.JPG)

Und generiert ein &lt;p&gt; statt ein &lt;h1...6&gt;
![unbenannt1](https://cloud.githubusercontent.com/assets/1645099/9425339/03aad26a-490d-11e5-979f-cc861729c7b9.JPG)

erwartet hätte ich jedoch bei dem Typ "Überschrift" die Standard-Contao-Eingabemaske für Überschriften, die dann auch eine &lt;h1...6&gt;-Überschrift generiert
![unbenannt2](https://cloud.githubusercontent.com/assets/1645099/9425344/2e69dc26-490d-11e5-837a-1a28b18ff336.JPG)

**Comment by leofeyer** [comment]
Das Feld "Überschrift" ist veraltet und wurde in Contao 4 bereits entfernt.
