### ISSUE TITLE
[3.5.2] Backend mootools datepicker zeigt "time" nicht korrekt an (01:00)

### ISSUE THREAD

**Issue by cyberlussi** [contao/core#7983]
Hi,
ich habe über verschiedene Wege festgestellt, dass der datepicker die reine Uhrzeit nicht korrekt anzeigt (rocksolid custom elements und metamodels). Beispielhaft kann man auch 
https://github.com/contao/core/blob/master/system/modules/news/dca/tl_news.php#L231
abändern in (plus 'datepicker'=>true)
```
array('rgxp'=>'time', 'doNotCopy'=>true, 'datepicker'=>true, 'tl_class'=>'w50'),
```
Das lässt den Picker erscheinen, dieser zeigt aber nicht die Zeit im Feld, sondern 01:00.

![2015-08-23_16_37_38_-_nachrichten_test_beitrag_id_1_bearbeiten_-_contao_open_source_cms_3_5](https://cloud.githubusercontent.com/assets/4976687/9428646/66bd6e1e-49b5-11e5-8be9-4062d0a4b46b.png)

**Comment by Aybee** [comment]
Mmh, evtl. muss da die deutsche locale (MooTools) geladen werden, denn auf der Demoseite geht es http://aryweb.nl/projects/mootools-datepicker/Test/timepicker.html

Denn
```js
Date.parse('15:20');
```
Gibt `Date {Thu Jan 01 1970 01:00:00 GMT+0100}` zurück.

**Comment by Aybee** [comment]
Vielleicht sollte dabei auch nochmal das **titleFormat** kontrolliert werden, ob das so richtig ist für einen einfachen Timepicker. Müsste da nicht besser`%H:%M` rein anstatt `%d. %B %Y`. Ich weiß jetzt aber nicht wirklich, wozu **titleFormat** da ist, da wurde ja auch ein wenig gepatcht, und die Doku vom Datepicker ist da auch nicht sehr aussagekräftig.

Contao Demo Quelltext:
```html
<script>
  window.addEvent("domready", function() {

    new Picker.Date($("ctrl_time"), {
      draggable: false,
      toggle: $("toggle_time"),
      format: "%H:%M",
      positionOffset: {x:-211, y:-209},
      pickOnly: "time",
      pickerClass: "datepicker_bootstrap",
      useFadeInOut: !Browser.ie,
      startDay: 1,
      titleFormat: "%d. %B %Y"
    });

  });
</script>
```

**Comment by discordier** [comment]
#7364?

**Comment by Aybee** [comment]
Nein, ich denke das gehört nicht zusammen. Der Datepicker versucht den Inhalt (value) des Input-Fields auszulesen, z.B. "15:20" und diesen dann mit `Date.parse('15:20');` in ein date-Object zu wandeln und das gelingt ihm nicht. Auf der Demo-Seite gelingt ihm das, aber da wird auch eine locale geladen und mit einem `3:20PM` Datum hantiert. Es wird ein JS-Problem sein.

**Comment by leofeyer** [comment]
Behoben in 9b0d72f6e9dbc841ccaaa3d2c161b78452ced545.

**Comment by Aybee** [comment]
:+1:
