### ISSUE TITLE
The button «Show differences» opens the page «Personal data» in BE

### ISSUE THREAD

**Issue by Evgenioni** [contao/core#7987]
If user edits his settings by links in the header, then the button «Show differences» on the Home page opens the settings page in popup. Edit the settings on «Users→Edit user ID…» works normal.
![image 1](https://cloud.githubusercontent.com/assets/2331446/9499605/1b7767a4-4c42-11e5-9ad6-3628a885adb7.png)

**Comment by leofeyer** [comment]
Fixed in 8b3d1191107fdbdda57b06e9d6a39a3f38fc679d.
