### ISSUE TITLE
the contao/core package registered on Packagist does not point to this repo but to a fork

### ISSUE THREAD

**Issue by stof** [contao/core#7990]
It may be worth switching it to the main reposiotry as it has a composer.json now, instead of using https://github.com/contao-community-alliance/composerized-contao-core

**Comment by leofeyer** [comment]
@discordier @aschempp /cc

**Comment by discordier** [comment]
@stof How can we ensure that previous versions are still available (all prior to 3.0 AFAIR) for which the composer.json does only exist in contao-community-alliance/composerized-contao-core?

I have not the slightest idea how this could work.

**Comment by aschempp** [comment]
It probably wont. But I'm not sure if it's worth switching/investing time on the matter as it's obsolete with Contao 4 anyways.
