### ISSUE TITLE
contao/password.php class BackendPassword not found

### ISSUE THREAD

**Issue by l0wskilled** [contao/core#7991]
Hey, when u force a user to edit passwort on first login, he gets redirected to password.php.

`$controller = new BackendPassword;`

Class `BackendPassword` is not found. So he gets shown a blank page.
Happened on Version 3.5.2

Edit: It actually is a 500 error

**Comment by leofeyer** [comment]
It does work in the online demo: http://demo.contao.org/contao/password.php
