### ISSUE TITLE
$this->text in default news templates

### ISSUE THREAD

**Issue by fritzmg** [contao/core#7993]
Since Contao 3.5 the actual detail content of a news entry is loaded on demand whenever `$this->text` is accessed in the template using [this](https://github.com/contao/core/blob/3.5.2/system/modules/news/modules/ModuleNews.php#L130) anonymous function.

The goal was to reduce the processing time and memory consumption for large newslists. However, the default news templates still access `$this->text`, e.g.
```php
  <?php if ($this->text || $this->teaser): ?>
    <p class="more"><?= $this->more ?></p>
  <?php endif; ?>
```
in the default _[news_latest](https://github.com/contao/core/blob/3.5.2/system/modules/news/templates/news/news_latest.html5#L34)_ template and also in the default _[news_short](https://github.com/contao/core/blob/3.5.2/system/modules/news/templates/news/news_short.html5)_ template. Thus this performance optimization will not be in effect by default.

But I am guessing this is intentional due to backwards compatibility?

**Comment by leofeyer** [comment]
@contao/developers /cc

**Comment by Toflar** [comment]
Extend by a `hasText` which only executes the count but does not parse the content elements.

**Comment by aschempp** [comment]
:+1: for @toflar

**Comment by fritzmg** [comment]
Though that would still create _n_ additional Database queries for _n_ news entries - which of course would still be faster than loading all the content elements.

Hm, but couldn't we make a `hasText` variable in the DCA which would only be updated whenever something is edited in the backend?

**Comment by aschempp** [comment]
It’s a simple JOIN, no additional query ;-)

**Comment by Aybee** [comment]
But then it is not possible anymore to output $this->text in al list. Am I right?

**Comment by fritzmg** [comment]
> It’s a simple JOIN, no additional query ;-)

ah, thought Toflar meant a separate query.

> But then it is not possible anymore to output $this->text in al list. Am I right?

No I think the anonymous function behind `$this->text` stays untouched.

**Comment by leofeyer** [comment]
Fixed in fc80967d2ac2b96abb101201a33839ecbfc81f5b. I have added `$this->hasText` and `$this->hasTeaser` to news templates and `$this->hasDetails` and `$this->hasTeaser` to event templates.

**Comment by fritzmg** [comment]
But doesn't this create additional database queries instead of doing it via a JOIN as @aschempp suggested? Or am I seeing it wrong

**Comment by leofeyer** [comment]
No idea what @aschempp meant, frankly …

**Comment by fritzmg** [comment]
If there is no other way then I would suggest to make `hasText` also an anonymous function, so that the user still decide to make the performance of a newslist even better (if needed) by not checking for `$this->hasText` either (and simply always show a "read more" link).
```php
$objTemplate->hasText = function () use ($id)
{
	return \ContentModel::countPublishedByPidAndTable($id, 'tl_news') > 0;
};
```
