### ISSUE TITLE
Feedformat Atom - Nachrichten mit Bildern erzeugen einen Fehler im Feed

### ISSUE THREAD

**Issue by WatzlavS** [contao/core#7996]
Hallo,

ich habe einen Nachrichtenfeed von RSS2.0 auf Atom umstellen müssen.
Die Nachrichten enthalten Bilder.

Der Feed erzeugt einen Fehler: "Das Endtag 'figure' stimmt nicht mit dem Starttag 'img' überein."
und wird nicht angezeigt,

Ändere ich in der von Contao erzeugten xml-Datei den HTML-Code 

von 
img src="Pfad_zur_Bildgatei">
in 
img src="Pfad_zur_Bildgatei" />

wird der Feed richtig angezeigt!

**Comment by leofeyer** [comment]
Behoben in 4bcb2ee6e9fef6f5b6fd374ce07a0691e951683f.
