### ISSUE TITLE
Custom Template mod_article doesn't work

### ISSUE THREAD

**Issue by Hendriks** [contao/core#7997]
In Contao 3.5.2:
Placing a custom mod_article template in a themes templates folder takes no effect (on the output)...

**Comment by leofeyer** [comment]
What exactly did you do?

**Comment by Hendriks** [comment]
Well, I copied a bunch of templates (one by one) into my "custom"-folder, using the backend templates module. Then I use to edit those templates in my FTP text editor of choice. And this worked out fine, except with the tl_article template. I use to get rid of the article container div, because I don't need it...

**Comment by fritzmg** [comment]
Hm, I cannot confirm this on my local test system. A custom _mod_article_ template in the theme's template folder will be in effect.

**Comment by Hendriks** [comment]
Well, if I only put
```php
<?= implode('', $this->elements) ?>
```
into my custom "mod_article.html5" template, the output is still being rendered with the "mod_article" container div...

**Comment by Aybee** [comment]
I also can not confirm this. Did you forget to slect the folder in your theme settings?

**Comment by Hendriks** [comment]
Hi. No, of course not; though all the other custom templates do work...!? I have no idea at the moment...

I did not change anything in the core.
I have the following extensions installed:

changelanguage	2.2.8	8	
con4gis_core	1.1.2	6	
con4gis_forum	1.1.2	9	
con4gis_maps	1.1.1	6	
conditionalselectmenu	3.0.1	14	
dcawizard	2.3.0	12	
dc_multilingual	2.0.0	15	
easy_themes	2.1.2	9	
haste	4.8.0	1	
isotope	2.3.0-RC2	5	
MultiColumnWizard	3.3.3	3	
NamespaceClassLoader	1.0.2	21	
news_related	3.5.0	8	
notification_center	1.3.0-RC1	5	
rocksolid-columns	1.0.6	3	
rocksolid-custom-elements	1.3.4	3	
rocksolid-icon-picker	1.0.7	3	
rocksolid-slider	1.5.3	3	
tablelookupwizard	2.0.1	23	
tags    3.3.1       6

**Comment by lionel-m** [comment]
The `tags` extension apparently overrides the `mod_article.html5` template with the `mod_article_tags.html5` template.

**Comment by Hendriks** [comment]
@lionel-m 

Ah, thanks! That was it! Sorry for the wrong "issue" here!

I didn't even know that this kind of "automatic" template overrides are possible. I thought you'd always have to specify custom templates "manually" / specifically...!? Is that new to Contao 3...?

**Comment by Aybee** [comment]
> @Hendriks
Is that new to Contao 3...?

I don't think so. With an extension you can do almost anything, even make Contao don't work anymore :wink:

**Comment by Hendriks** [comment]
Ok, silly question! You're probably right!
LOL
