### ISSUE TITLE
Fehler in der Suchmaschine von Contao

### ISSUE THREAD

**Issue by standing-bear** [contao/core#7999]
Ich habe schon in der Community gepostet, aber leider keine Lösung für das Problem mit der Contao-Suchmaschine gefunden.

Folgendes Problem liegt vor: Ich habe ein Online-Branchenbuch erstellt. Hier werden Kundenprofile eingetragen, die man sowohl über eine Branchenliste, wie auch über eine Volltextsuche (Contao-Suchmaschine) finden kann.

Jedes Kundenprofil ist als eigener Artikel innerhalb einer einzigen Seite angelegt. Die Profile wurden zum Zweck der einfachen Backend-Verwaltung mit der Extension dma_elementgenerator angelegt.
Der Aufbau des Suchindex ist auf diese eine Seite mit den Profil-Artikeln beschränkt.
Baut man den Suchindex über das Backend auf, werden alle Einträge einwandfrei gefunden.

ABER: nach und nach löscht sich der Suchindex wie von Geisterhand selbst. Die Treffer über die Suche werden immer weniger, bis schließlich nichts mehr gefunden wird. Weiterhin schaltet das System offenbar automatisch auf case sensitive um. Direkt nach Erstellung des Suchindex werden unter "Marketing" und "marketing" die gleichen Kunden-Profile gefunden. Nach einer Weile klappt es nur noch mit "marketing".

Im Backend habe ich bereits den Command Scheduler deaktiviert, um den Poor Mans Cron abzuschalten. Auch dies war ohne Ergebnis.

Offenbar laufen hier (Ajax?)- Prozesse im Hintergrund, die möglichweise den Suchindex aufbauen und/oder bereinigen sollen, ihn leider aber löschen.

Eine Vermutung wäre, dass die Verwendung des dma_elementgenerators zu einer fehlerhaften Indexierung und vielleicht sogar zum Löschen des Index führt.

Bin für jeden Hinweis auf eine schnelle Lösung dankbar. Es wäre mir auf die Schnelle auch schon geholfen, wenn es eine Möglichkeit gäbe alle den Suchindex betreffenden Prozesse komplett abzuschalten.

Ich kann das Gesamtsystem gern zu Debugging-Zwecken komplett zur Verfügung stellen. Das System ist auf einem 1&1-Server gehostet. Contao-Version ist 3.4.5.

Danke und Grüße
Standing Bear

**Comment by leofeyer** [comment]
Das Ticket-System ist dazu da, Fehler zu melden. In diesem Fall weißt Du selbst ja noch gar nicht, ob Contao überhaupt der Verursacher ist oder es eventuell an einer Erweiterung liegt, daher ist die Anfrage hier fehl am Platz.

Unterstützung beim Debugging erhältst Du im Forum. Wenn dort niemand Rat weiß, kannst Du auch einen Contao-Partner bitten, Dich zu unterstützen.

**Comment by standing-bear** [comment]
Hi Leo,
wie bitte kann ich das herausfinden? Ich habe nicht mal eine Ahnung, welche Prozesse Contao im Hintergrund für den Suchindex ablaufen lässt. Das mit der Extension ist nur eine sehr vage Vermutung. Kannst Du mir sagen, welche Prozesse hier angestoßen werden, und wie ich die ggf. abschalten kann? Dann könnte ich in Ruhe debuggen. Das Problem ist, das das System schon online ist.

Danke
Standing Bear

**Comment by aschempp** [comment]
Ich denke mal dazu solltest du einen Entwickler kontaktieren, der das für dich auf deinem System analysieren kann.

**Comment by standing-bear** [comment]
Ich bin selbst Entwickler. Und woher weiß ich, wer das könnte? Kann denn niemand daus dem Core-Team die einfache Frage nach den Ajax-Prozessen, die da laufen, und der Möglichkeit des Abschaltens beantworten. Das muss doch jemand programmiert haben?!

**Comment by aschempp** [comment]
Es gibt keine Ajax-Prozesse bei der Suchmaschine. Als Entwickler würde ich den Code lesen und mit einem Debugger oder ggf. var_dump() prüfen an welcher Stelle das Problem auftritt. 

Dein dargestelltes Problem ist mir aus Contao nicht bekannt. Es liegt also ziemlich sicher an einer Erweiterung. Und da wir die nicht kennen, ist es sehr schwer zu raten wo dein Problem sein könnte…

**Comment by BugBuster1701** [comment]
Hättest du mal doch lieber einen eigenen Forum Beitrag aufgemacht, so hatte ich grad echt Mühe [diesen](https://community.contao.org/de/showthread.php?54683-Suchindex-l%F6schen-und-neu-aufbauen-via-Cronjob&p=383294&viewfull=1#post383294) zu finden.
Ich habe dort mit Absicht nicht ein geschaut, da der Original Titel nicht von Interesse war.

**Comment by standing-bear** [comment]
Gute Idee, werde ich mal machen. thanx.

**Comment by asaage** [comment]
@standing-bear vielleicht findest du hier was: #6566

**Comment by BugBuster1701** [comment]
> Gute Idee, werde ich mal machen. thanx.

Nächstes Mal, nicht für dieses Problem ein Doppel Post machen.

**Comment by standing-bear** [comment]
Ich denke, ich konnte das Problem nun soweit eingrenzen, dass man eindeutig auf einen Contao-Bug schließen kann, so dass ich das Thema hiermit wiedereröffnen möchte.

Das Problem stellt sich folgendermaßen dar:
Ich lasse die Suchindex über das Backend aufbauen. Ich gebe dann auf der Website in der Suchmaschine einen Suchbegriff (webconcept) ein und bekomme eine Trefferliste. In dieser Liste werden aber nur die Artikel-Teaser angezeigt. Klickt man nun auf "weiterlesen", um den Artikel selbst aufzurufen, erscheint dieser auch zunächst.
Im Hintergrund ändert Contao allerdings die URL in der Tabelle ```tl_search```.

Bsp.: Vor der Suche steht bei einer Kundin im DB-Feld ```URL```:

```
unternehmen/articles/webconcept-marketing-andrea-buchelt-bremen.html
```
Wenn ich in der Ergebnisliste (Artikel-Teaser) auf weiterlesen klicke, wird allerdings die URL

```
unternehmen.html?articles=webconcept-marketing-andrea-buchelt-bremen
```

aufgerufen. Diese URL wird dann auch in der Datenbank in ```tl_search``` gespeichert. Und nun wird das Profil über denselben Suchbegriff (webconcept) nicht mehr gefunden!

Ändere ich die URL per MySQL wieder zurück auf den alten Wert, wird das Kundenprofil wieder gefunden.

Man kann also im Prinzip ein Profil nach dem anderen "abschießen", indem man einfach auf weiterlesen klickt. Dies kann also nur an der automatischen Indexierung von Contao liegen. Das Problem besteht im Grunde darin, dass derselbe Artikel über zwei unterschiedliche URLs abrufbar ist:
1. http://www.exxtraseiten.de/unternehmen/articles/webconcept-marketing-andrea-buchelt-bremen.html
2. http://www.exxtraseiten.de/unternehmen.html?articles=webconcept-marketing-andrea-buchelt-bremen

Daher auch meine Frage für eine schnelle Lösung. Wie kann ich die automatische Frontend-Indizierung abschalten? Oder kann man hier ein url rewriting einsetzen, und wie sähe das aus?

thanx for help

**Comment by leofeyer** [comment]
Es handelt sich nicht um einen Contao-Bug, denn die Suchergebnisse (z.B. http://www.exxtraseiten.de/volltextsuche-suchergebnisse.html?keywords=buchelt) werden so nicht von Contao generiert. Die Suchergebnisse von Contao sehen so aus: https://contao.org/de/suche.html?keywords=LTS

**Comment by standing-bear** [comment]
Wo genau ist da jetzt der Unterschied? Ich generiere die Suchergebnisse ja nicht selbst.

**Comment by standing-bear** [comment]
Problem gelöst ... mein Fehler im mod_search Template ... sorry+thanx
