### ISSUE TITLE
Use/ignore "Show hidden items" in module navigation menu

### ISSUE THREAD

**Issue by jantheofel** [contao/core#8001]
Although the option "Show hidden items" is not part of the settings for module type "navigation menu" the setting is used.

To reproduce the bug in the demo:
- Create a hidden page
- Switch module "Navigation - Main navigation" to "Quick navigation", activate checkbox "Show hidden items" ans save.
- Switch it back to "Navigation menu".
- The hidden page is now shown in the main menu.

Either that type of menu should ignore that setting or it has to show up in the settings for that module.

**Comment by leofeyer** [comment]
Fixed in 9f8f784e32e7f5d4697f6034f5914bcd5a8cb9d4.
