### ISSUE TITLE
[3.5.2]  (may other) - Firefox Response Images - Von Klein nach Gross keine Bildanpassung

### ISSUE THREAD

**Issue by blackbee** [contao/core#8004]
Hallo zusammen,

ich eröffne hier zu ein Issue, auch wenn ich weiß, dass es ein Firefox spezifisches Problem ist (bis einschl. Firefox 40.0.3).

## Ausgangslage:

Die Dynamische Bildanpassung (Responsive Bilder) sind aktiviert und auch die entsprechenden Media Query Einträge gesetzt.

Vergrößert man die Seite nun von Klein nach Groß laden alle anderen Browser (bis auf den Firefox) die Bilder entsprechend bzw. laden die größeren Versionen nach.

Im umgekehrten Fall ist es gleichermaßen. In den übrigen Browsern funktioniert es, im Firefox jedoch nicht. Hier fällt es nur weniger auf, weil das Bild z.B. durch das Grid/Flexible Contao Framework einfach zusammen geschoben wird.

Es ist durch Zufall bei einem Kunden aufgefallen und ich habe es bis jetzt bei 3 Projekten schon identifiziert.

Ich habe mich auf die Suche nach der Ursache begeben, warum das nicht funktioniert.

Firefox tauscht die Bildquelle nicht aus.

Polyfill.js ist aktiviert.

## Zum Nachvollziehen
Polyfill aktivieren. Responsive Image - Set anlegen und Bild auf eine Seite einbauen. Dann in einer kleinen Browser-Breite die Seite laden. Anschließend Seite groß ziehen, bis der definierte Breakpoint im Media-Query erreicht wird und das Bild umschalten müsste. Getestet mit Fireofx 40.0.3

## Ursache
Ich habe mich auf die Suche nach der Ursache begeben und bin fündig geworden. Auf folgender Webseite wird das Problem beschrieben:
http://shhdesign.co.uk/blog/fixing-picturefill-firefox-bug/

## Lösung
Auf der oben genannten Webseite wird auf ein Fix-It-Script von Lazy Images verwiesen, welches den Bug in Firefox via Script behebt, in dem es ein Workaround einbaut.
Das Script findet Ihr unter folgender Adresse:
https://github.com/aFarkas/lazysizes/blob/gh-pages/plugins/static-gecko-picture/ls.static-gecko-picture.js

Der Verfasser des Artikel unter Ursache gibt an, dass man entweder das ganze LazySizes einbinden kann oder aber nur den Bestandteil, der auch im Beitrag genannt wird.

## Erfahrung
Ich habe das Script jetzt in den besagten 3 Projekten eingebaut und seitdem lädt auch Firefox die höhere Bildquelle nach.

## Frage
Ich weiß nicht ob Mozilla irgendwann was ändern wird oder ob dauerhaft der Fix in Contao einfließen muss. Daher stelle ich diese Problembeschreibung einmal zur Diskussion.

**Comment by standing-bear** [comment]
Super, danke ... das Problem hatte ich auch mit ein paar Websites. Das erstaunliche daran ist, dass es im Firefox 37 noch problemlos funktionierte. Werde den Fix gleich mal testen.

**Comment by leofeyer** [comment]
@contao/developers /cc

**Comment by ausi** [comment]
Der [Firefox Bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1135812) wurde mit Version 41 behoben.

Es gibt scheinbar noch einen [weiteren Bug in Firefox](https://bugzilla.mozilla.org/show_bug.cgi?id=1166138) der `<img srcset>` betrifft, ich sehe hier allerdings keinen Handlungsbedarf für Contao.

**Comment by leofeyer** [comment]
Da das Problem tatsächlich mittlerweile behoben ist, sehe ich auch keinen Handlungsbedarf mehr. Wer explizit ältere Firefox-Versionen unterstützen will, kann das Zusatzskript ja einfach im Seitenlayout hinzufügen.
