### ISSUE TITLE
Multiple editing of several contents with one checkbox

### ISSUE THREAD

**Issue by jenda77** [contao/core#8005]
I would prefer to have the possibility to edit a chosen field for several contents with one click. It means it should work like in Typo3 where you have the choice between a multiple editing with different checkboxes and a multiple editing with one checkbox for several data fields (contents).  

It could improve the user experiment enorm.

**Comment by leofeyer** [comment]
?

**Comment by jenda77** [comment]
ich schreibe das dann lieber auf Deutsch. :-) 

Momentan bekommt man in der Mehrfachbearbeitung im letzten Schritt eine lange Liste mit Feldern, die man vorher ausgewählt hat und die man bearbeiten will. 

Ich schildere es z.B. an der mehrfachen Bearbeitung der Mitglieder. 

Ich möchte allen ausgewählten Mitgliedern dieselbe Gruppe zuweisen, d.h. hier geht es nur um eine Checkbox, die ich auswählen muss. Dann muss ich mich bei allen Mitgliedern durchklicken, um es zu ändern, obwohl ich dasselbe bei allen ändern möchte. Bei 100 und mehreren Einträgen ist es recht umständlich. 

Daher wäre es gut, wenn man vorher unterscheiden könnte, ob man dasselbe bei allen ausgewählten Feldern ändern will oder ob man bei allen etwas einzeln verändern will. Das könnte Contao von Typo3 lernen. :-) Vielleicht könnte man das mit einer zusätzlichen Checkbox neben der Checkbox lösen, die dieselbe Funktion hat wie "Alle auswählen". 

Ich hoffe, dass es verständlich genug ist. Sonst bitte fragen. 

Außerdem finde ich wichtig, dass man bei der Mehrfachbearbeitung mindestens den Titel der ausgewählten Inhaltselement hat, um zu wissen, was man gerade bearbeitet (https://github.com/contao/core/issues/4525#issuecomment-139479996).

**Comment by jscholtysik** [comment]
+1

Hatte die letzten beiden Tage auch mit der Mehrfachbearbeitung zu tun und fände das auch sehr praktisch...

**Comment by fritzmg** [comment]
Öh, die Funktion gibt es bereits... einfach "Überschreiben" statt "Bearbeiten" auswählen ;)

**Comment by asaage** [comment]
Dafür gitbt's doch den _Überschreiben / Override_ button.
Wenn man den Titel auswählt sieht man ihn auch.

**Comment by jenda77** [comment]
Alles klar, das freut mich. Leider ist die Benennung der Funktion nicht gleich verständlich. Vielen Dank für die Hilfe und Erklärung allerseits. Wieder etwas Neues gelernt. Hurra!

**Comment by jscholtysik** [comment]
Das hätte ich jetzt auch nicht gedacht, dass das hinter "Überschreiben" steckt. Steht auch so nirgends in der Doku drin... :-(

**Comment by jenda77** [comment]
Noch eine Frage. Wie ist es mit der Tasturkürzel am Mac in Contao 3.5, wenn man mehrere Checkboxen auswählen möchte? Mit de gedrückten Shif-Taste geht es nicht. Ich habe noch folgende Kombinationen probiert: alt+shif und cmd+shif und cmd+shif+alt. Alles funktioniert nicht. ctrl ist schon für das Kontextmenü reserviert - muss man es vorher für Contao "reservieren"?

**Comment by jenda77** [comment]
@jscholtysik Ja, leider fand ich es auch nirgendwo, deshalb kam ich mit einer Anfrage hierher. 

Ich finde, so eine nützliche Funktion sollte man schon gut in der Doku beschreiben (präsentieren und verkaufen). :-) Darf man die Contao-Doku selber bearbeiten, ergänzen?

**Comment by Zeromax** [comment]
See https://github.com/contao/docs
