### ISSUE TITLE
[3.5.3] Startseite/Home ist nicht active

### ISSUE THREAD

**Issue by StudioV19** [contao/core#8006]
Bis version 3.5.2 war es so, dass die Startseite nicht klickbar war. Siehe z. B. http://www.nordic-gateway.se/sv/
Nach dem Update auf 3.5.3 bekommt die Startseite nicht mehr den Status "active" wie bisher. Zumindest wenn sie den Seitenalias "index" hat. Meiner Ansicht nach ist das ein Fehler. Siehe http://studiov19.se/

**Comment by leofeyer** [comment]
Das scheint ein Problem mit Deiner Installation zu sein. In der Onlinedemo ist es jedenfalls nicht so: http://demo.contao.org/en/

**Comment by fenepedia** [comment]
Hey Leo, ich kann den Fehler bei meinen Installationen bestätigen. Früher kein Klicken möglich, da nur ein span ausgegeben wurde. Jetzt kommt ein Link-Element.

**Comment by fenepedia** [comment]
Ich kann es in der Online-Demo nicht ändern, aber das hängt wohl mit der Option "Add the language to the URL" zusammen

**Comment by fenepedia** [comment]
Ich vermute den Fehler hier: https://github.com/contao/core/blob/3.5.0/system/modules/core/library/Contao/Controller.php#L1105

**Comment by pixelbine** [comment]
Hallo zusammen,
kann den Fehler auch bestätigen. https://community.contao.org/de/showthread.php?59329-Startseite-mit-Seitenalias-index-nicht-mehr-als-quot-active-quot-unter-3-5-3 
Sobald "Die Sprache zur URL hinzufügen" deaktiviert wird, tritt der Fehler auf.

**Comment by leofeyer** [comment]
Behoben in bcd7c1e8b2ec3a2a62b52f118d4ac5e0a86be68e.
