### ISSUE TITLE
Official demo site provides English language only

### ISSUE THREAD

**Issue by taca** [contao/core#8010]
Currently, https://demo.contao.org/cotao/ provides English language only.
Past, it provides all languages that Contao supports.  Please restore other languages.

**Comment by Aybee** [comment]
Wrong Link http://demo.contao.org/contao/
This is done intentionally.

**Comment by taca** [comment]
Yes, it was my typo.  Why drop other languages?

**Comment by Aybee** [comment]
As it is not possible to save the language on a per user base in the demo. So if one switches to Japanese all users will see it as Japanese.

**Comment by taca** [comment]
IC.
Just a simple idea:
* Create a user for each language.  (customizing template?)
* Disable language selection menu on backend login page.
* Disable changing language after login to backend.

**Comment by leofeyer** [comment]
I'll see what I can do.

**Comment by leofeyer** [comment]
The issue will resolve itself as soon as the demo is updated to Contao 4.

**Comment by taca** [comment]
Great!
