### ISSUE TITLE
`hasDetails` is not filled in Event Reader

### ISSUE THREAD

**Issue by fritzmg** [contao/core#8011]
The function `hasDetails` which was introduced in fc80967d2ac2b96abb101201a33839ecbfc81f5b (see #7993) is not filled in the [EventReader module](https://github.com/contao/core/blob/3.5.3/system/modules/calendar/modules/ModuleEventReader.php). However, this function is still used in the default [_event_full_](https://github.com/contao/core/blob/3.5.3/system/modules/calendar/templates/events/event_full.html5#L11) template. Thus when using the default _event_full_ template in the EventReader module, it will never show the actual details of the event, only the teaser. This is also reproducible in the Contao Online Demo.

See also [3.5.3 Event Reader zeigt nur Teaserinhalt und seltsame Zeichen ](https://community.contao.org/de/showthread.php?59126-3-5-3-Event-Reader-zeigt-nur-Teaserinhalt-und-seltsame-Zeichen)

**Comment by SpeGal** [comment]
We have the same problem. All event content is gone in the frontend! In my eyes this is a major bug that should be fixed emediately.

**Comment by fritzmg** [comment]
Yes, hopefully it will be hot fixed.

**Comment by leofeyer** [comment]
Fixed in d80a6fdbb67c0591494a623de58ca2554890ef8b. There is another event reader related fix in bbfef9ad7cfa5da799ebe3f2fe0c59785ec5f100, can you please checkout the latest `hotfix/3.5.4` branch and test all your news modules?

**Comment by leofeyer** [comment]
I can only release a hotfix if you guys test the changes. Any feedback?

**Comment by vgt1920** [comment]
Mit der offiziellen Contao Demo unter 5.3.5 getestet. Mit der veränderten Datei ModuleEventReader.php wird jetzt mit dem Reader Template Event_full der Volltext für den Kalendereintrag angezeigt,

**Comment by ben-eSM** [comment]
Patched a client project also. Works fine now. Thanks.
