### ISSUE TITLE
Bug in Template event_full.html5

### ISSUE THREAD

**Issue by Kahmoon** [contao/core#8013]
Hallo zusammen,

ich glaube mir ist ein Fehler im event_full aufgefallen. Es hat mich gewundert warum keine Details (Inhaltselemente) eines Events angezeigt wurden, nur der Teaser wenn vorhanden.

Der Fehler war wohl in der Abfrage Zeile 11. "hasDetails" gibt es nicht. Verwenedt wurde das Core-Template.

Geht nicht:
```
  <?php if ($this->hasDetails): ?>
    <?= $this->details ?>
  <?php else: ?>
    <div class="ce_text block">
      <?= $this->teaser ?>
    </div>
  <?php endif; ?>
```

Geht:
```
  <?php if ($this->details): ?>
    <?= $this->details ?>
  <?php else: ?>
    <div class="ce_text block">
      <?= $this->teaser ?>
    </div>
  <?php endif; ?>
```
VG
Frank

**Comment by asaage** [comment]
duplicate (#8011)

**Comment by Kahmoon** [comment]
argh....da mache ich schon mal ein Ticket...

Danke und sorry :)
