### ISSUE TITLE
FAQ Template Daten

### ISSUE THREAD

**Issue by jacob418** [contao/core#8014]
Aktuell ist es zwar möglich, neue Felder für die FAQ anzulegen zb mit Hilfe der **dcaconfig.php**, allerdings können diese Felder nicht über die FE Module ausgegeben werden, da die entsprechenden Werte nicht an das Template übergeben werden.
Andere Module rufen als erste Aktion auf ihrem Template **setData(***$objModel***->row())** auf (z.B. ModuleNews: Zeile 92). Dadurch sind alle Werte aus der DB auch im Template vorhanden - auch nachträglich hinzugefügte Felder. In den Modulen "**faqlist, faqreader, faqpage**" ist das nicht der Fall, was Ergänzungen in der Funktionalität erschwert oder sogar unmöglich macht.

Mir fällt kein Grund ein in den FAQ Modulen nicht auch den kompletten Datensatz an das Template zu übergeben.

**Comment by fritzmg** [comment]
:+1:

**Comment by leofeyer** [comment]
Das liegt daran, dass z.B. in der Klasse `ModuleNews` ein neues Template-Objekt erstellt wird. Die FAQ-Module arbeiten jedoch mit dem Standard-Template (`$this->Template`) und dieses erhält den Datensatz in der `Module`-Klasse:

https://github.com/contao/core/blob/master/system/modules/core/modules/Module.php#L192

Rein vom Code her muss es also einen anderen Grund geben, warum Deine eigenen Felder nicht übernommen werden.
