### ISSUE TITLE
Defect link in backend main page

### ISSUE THREAD

**Issue by folkfreund** [contao/core#8015]
In the german backend, there is a defect link in this line:
'Wie Sie Ihren Arbeitsablauf durch die Verwendung von Tastaturkürzeln beschleunigen.'

Since relaunch of contao.org the link should read:
https://docs.contao.org/books/manual/3.5/de/02-administrationsbereich/backend-tastaturkuerzel.html

**Comment by BugBuster1701** [comment]
bzw. den "current" Link.
https://docs.contao.org/books/manual/current/de/02-administrationsbereich/backend-tastaturkuerzel.html

**Comment by fritzmg** [comment]
Isn't it already fixed in Contao 3.5.3? See #7935

**Comment by folkfreund** [comment]
Yes, fixed in 3.5.3 (at least in english Demo), sorry
