### ISSUE TITLE
Default TinyMCE config will remove script host from URL

### ISSUE THREAD

**Issue by fritzmg** [contao/core#8016]
By default TinyMCE (3 and 4) will remove the script host from any URL inserted into the HTML code. e.g., if you are in the backend via http://www.example.org/contao and you are inserting a link to http://www.example.org/foo.html, TinyMCE will remove http://www.example.org/ and only leave _foo.html_.

However, this can be problematic in multi-domain setups where you want to link to a specific domain. Say you have a Contao installation for two domains, http://www.example1.org and http://www.example2.org. Suppose you are logged into the backend via http://www.example1.org/contao and you want to link from a page of _example2.org_ to a page of _example1.org_ via a regular text element. This is not possible, because the inserted link, e.g. http://www.example1.org/foo.thml will be converted to _foo.html_ and then the link will point to http://www.example2.org/foo.html instead (since the link is on a page of the _example2.org_ domain).

This behaviour can be disabled with the following config:
```JavaScript
relative_urls: false,
remove_script_host : false
```
See the [documentation](http://www.tinymce.com/wiki.php/Configuration:remove_script_host). Note that this will _not_ cause file and page links from the picker to be linked absolutely. Page links will still be insert tags and file links will still be relative. Any other manually inserted links will not be altered either (which is the point of this setting).

**Comment by leofeyer** [comment]
> Suppose you are logged into the backend via http://www.example1.org/contao and you want to link from a page of _example2.org_ to a page of _example1.org_ via a regular text element. This is not possible, because the inserted link, e.g. http://www.example1.org/foo.thml will be converted to _foo.html_ and then the link will point to http://www.example2.org/foo.html

I don't think so. The script host is only removed if the link URL matches the browser URL, so if you are on example1.org and you are adding a link to example2.org, the URL remains absolute.

Try adding a link in the online demo to demo.contao2.org. Is the script host being removed?

**Comment by fritzmg** [comment]
> I don't think so. The script host is only removed if the link URL matches the browser URL, so if you are on example1.org and you are adding a link to example2.org, the URL remains absolute.

Yes exactly, but I was talking about the other way around. Again: if you have a multi-domain Contao installation for _example1.org_ and _example2.org_ and enter the backend via http://www.example.1org/contao and then go to an article on a page which is actually in the website root of the domain _example2.org_ and then enter (or create) a text content element and then create a manual link to some target which is on _example1.org_, e.g. http://www.example1.org/foo.html or whatever, then TinyMCE will remove http://www.example1.org

**Comment by leofeyer** [comment]
In this case, the `remove_script_host` option seems the best solution to me. However, I would not want to enable it by default, because it will add a lot of unnecessary script hosts to the source code.

**Comment by fritzmg** [comment]
Yeah, I understand

**Comment by leofeyer** [comment]
Shall we close the ticket then?

**Comment by fritzmg** [comment]
Well, I am still unsure - I think it would still be better to enable this option by default. I don'T think there will be a lot of unnecessary script hosts in the source code, at least not if you use the current link plugin of TinyMCE in Contao.

Aren't there only 4 cases?

* Links to files
* Links to internal pages
* Links to external pages
* Inserted images

Regarding the first case: even if you use
```JavaScript
relative_urls: false,
remove_script_host : false
```
the links to files will still be inserted _without_ the script host by the plugin.

The script host will also not be present for the second case, internal pages, since no actual URL is inserted, but an `{{link_url::*}}` insert tag instead (thus there is no script host for TinyMCE to be removed).

For external pages it does not matter.

And for inserted images it's the same situation as in the first case: the path to the image will still be relative, even with the `remove_script_host` feature turned on.

**Comment by ausi** [comment]
The problem with `relative_urls: false, remove_script_host: false` is, all links get converted to absolute URLs, e.g. `href="foo"` gets converted to `href="http://example.com/foo"` and even `href="{{link_url::1}}"` gets converted to `href="http://example.com/{{link_url::1}}"`.

**Comment by fritzmg** [comment]
Oh, yes, that is true, I didn't notice at first.

**Comment by ausi** [comment]
I think `convert_urls: false` looks like what you want, but I’m not sure if it’s correct to use it Contao.

**Comment by fritzmg** [comment]
Hm, yeah it seems so.

Not sure what they mean with this in the documentation:

> URLs are automatically converted (messed up) by default because the built-in browser logic works this way. There is no way to get the real URL unless you store it away.

**Comment by ausi** [comment]
Browsers convert URLs to absolute ones. You can try that out with this JavaScript code:

```js
var foo = document.createElement('a');
foo.href = 'foo';
alert(foo.href); // alerts something like "http://example.com/path/foo"
```

If you set `convert_urls` to `false`, tinyMCE works around that automatic conversion to keep the original value.

**Comment by leofeyer** [comment]
Shall we close the ticket now? :)

**Comment by fritzmg** [comment]
Yes :). I consider it a benign issue right now, since it's probably very rare, that someone wants to do this (since linking to a page via the TinyMCE is done with insert tags anyway).
