### ISSUE TITLE
Less CSS Parsing

### ISSUE THREAD

**Issue by Mediaquery** [contao/core#8019]
Es werden keine Berechnungen mehr durch Less CSS vorgenommen.
Simple Berechnungen wie width:1000px - 100px; werden nicht vorgenommen.
Hab es mit der Version CDN Version 2.5.1 gestest dort funktioniert es wunderbar.

**Comment by Zeromax** [comment]
see #7985 maybe the strict math option is the problem?

**Comment by leofeyer** [comment]
Wie kann ich das Problem reproduzieren?

**Comment by brandtmarke** [comment]
Wie Zeromax sagte, ist
```php 
'strictMath' => true,
```
in der Combiner.php (Zeile 353 bei Contao 3.5.3) die Ursache; ich habe es manuel wieder auf false gesetzt, da ich das gleiche Problem hatte und diverse Mixins etc., die Berechnungen enthalten im Less habe. Das ist aber natürlich nicht updatesicher. Schön wäre es, wenn man eine updatesichere Konfigurations-Lösung finden würde.

Um mit 
```php 
'strictMath' => true,
```
die Berechnungen trotzdem nutzen zu können, muss man sie in Klammern setzen:
```css 
width: (1000px - 100px);
```
siehe auch http://lesscss.org/usage/

**Comment by leofeyer** [comment]
@contao/developers @psi-4ward /cc

**Comment by asaage** [comment]
```calc``` und Klammen zu verwenden ist doch grundsätzlich eine gute Idee.
Dass mit der Option nicht vollständig aufgelöst wird hatte leo doch https://github.com/contao/core/issues/7985#issuecomment-138919082 schon herausgefunden.
