### ISSUE TITLE
[3.5.3] Datenbank aktualisieren Zwischenüberschriften fehlen

### ISSUE THREAD

**Issue by Mynyx** [contao/core#8020]
Bei der Funktion "Datenbank aktualisieren" im Bereich Erweiterungsverwaltung werden die verschiedenen Änderungen gruppiert nach Neue Spalten, Änderungen und Löschen.

Im Installtool stehen dort über den Gruppen auch entsprechende Überschriften (z. B. "Bestehende Spalten löschen"), diese fehlen bei der o. g. Funktion.

**Comment by leofeyer** [comment]
Behoben in d79e6814b243eaee7cd802ef5f871f508bcccbed.
