### ISSUE TITLE
Detect TLS-Terminating Reverse Proxy

### ISSUE THREAD

**Issue by fbender** [contao/core#8024]
I have a server setup with an LXC/Docker container containing an SSL-terminating Reverse Proxy (nginx) and another one containing Apache + Contao. This setup can be broken down to this, which is also common for load balancing applications: 

    Client --> SSL-Terminating-Proxy --> Webserver --> Application (PHP/Contao)

Unfortunately, Contao does not recognize that (for the client) it is running via HTTPS [1]. There are some [de-facto headers](https://en.wikipedia.org/wiki/List_of_HTTP_header_fields#Common_non-standard_request_fields) indicating [a TLS/SSL-Terminating Proxy](http://stackoverflow.com/questions/13111080/what-is-a-full-specification-of-x-forwarded-proto-http-header) that Contao could detect to transparently switch to HTTPS: 

* `X-Forwarded-Proto: https` is used by many reverse proxies
* `Front-End-Https: on` is used by Microsoft load balancers and proxies

There is also [RFC 7239](http://tools.ietf.org/html/rfc7239), which specifies the `Forward` header and includes a standards-compliant replacement for `X-Forwarded-Proto` (as demonstrated in the first line, the other lines show other examples of the header): 

* Forwarded: for=192.0.2.60;proto=http;by=203.0.113.43
* Forwarded: for="_gazonk"
* Forwarded: For="[2001:db8:cafe::17]:4711"
* Forwarded: for=192.0.2.43, for=198.51.100.17

Implementing detection of the de-facto headers is enough for me, and as simple as (adapted from current [Environment.php](https://github.com/contao/core/blob/0cb85bb79422c0c8bb8a3ef0f37a135826e663a5/system/modules/core/library/Contao/Environment.php#L306-L314)): 

```php
	protected static function ssl()
	{
		return ($_SERVER['SSL_SESSION_ID'] || strcasecmp($_SERVER['HTTPS'], 'on') === 0 || $_SERVER['HTTPS'] == 1 || strcasecmp($_SERVER['X_FORWARDED_PROTO'], 'https') === 0 || strcasecmp($_SERVER['FRONT_END_HTTPS'], 'on') === 0);
	}
```

Supporting RFC 7239 requires parsing the header and is probably a bit too complex for Contao 3.x (Symfony already implemented this in symfony/symfony#11073).

[1] For now, I did some `$_SERVER` hackery though it'd be nice if Contao would handle this automatically.

Loosely related to: #6959, #4615,

**Comment by aschempp** [comment]
Am I assuming correctly that this would be handled automatically if the Contao Environment class uses the Symfony request (in Contao 4)?

**Comment by fbender** [comment]
I have not checked the way Contao 4 handles this. But I assume the answer is yes. 

This request is specifically for Contao 3. I know it is now pretty much considered LTS but since 3.5 will be supported until 2019 and there are a lot of people with a similar setup and issues (judging by the Forum entries), I figured this will be a great addition. Plus, the change is innocent enough.

**Comment by leofeyer** [comment]
This is most likely a server configuration issue. We have a similar setup on our inetrobots.de servers with Nginx as SSL terminating proxy and Contao works like a charm without any adjustments.

**Comment by fbender** [comment]
May you share how the servers are set up? The standard configuration for load balancers and proxies is to expose the forwarded-proto header. Is there another http server between your terminating nginx and Contao?

**Comment by leofeyer** [comment]
No additional http server. Here's the Nginx location configuration:

```
proxy_pass http://127.0.0.1:8080;
include /etc/nginx/proxy.conf;
proxy_redirect http://example.com:443/ https://example.com/;
proxy_redirect https://example.com:443/ https://example.com/;
```

**Comment by fbender** [comment]
I can't find a `/etc/nginx/proxy.conf` on my Debian Jessie system, however there is a `proxy_params` file with the following content: 

```
proxy_set_header Host $http_host;
proxy_set_header X-Real-IP $remote_addr;
proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
proxy_set_header X-Forwarded-Proto $scheme;
```

Is this the same you have? 

What Contao settings do you have set that might influence this? `sslProxyDomain` or `proxyServerIps` or anything like that? Any specific settings in the page roots?

**Comment by leofeyer** [comment]
No specific Contao settings at all.

**Comment by fbender** [comment]
Ok thanks. Will test a bit but it will take a few days at least before I can get to this.

**Comment by amenk** [comment]
In my case there is Contao behind a second proxy machine which terminates ssl. Setting sslProxyDomain (which is actually the same as the main domain) seems to help in this case.
Would not be the worst thing if contao auto detects X_FORWARDED_PROTO - but it is also okay the way it is.
