### ISSUE TITLE
FR: HTML-Templates for form generator

### ISSUE THREAD

**Issue by Anke** [contao/core#8025]
I wish it was possible to use html styled email messages with the implemented form generator. For small forms it isn't really necessary to install EFG (that might not be supported any more) but often it would look good to have a logo and some styling eben in short and simple mails.

This is likely to be an unpopular question, but is there a reason why the built-in form generator has never been enhanced/extented? Imho it is (or ought to be) a fundamental feature of a CMS.

**Comment by leofeyer** [comment]
I'm closing this ticket due to lack of interest.

**Comment by Aybee** [comment]
Meanwhile most admins use the extension notification-center https://github.com/terminal42/contao-notification_center.
