### ISSUE TITLE
Remove v2warning from templates

### ISSUE THREAD

**Issue by Aybee** [contao/core#8027]
Die Variable `v2warning` war hier https://github.com/contao/core/commit/f1d20ab#diff-d3422f5ef1a5fafc0c8b7cf0094372f9L104 noch drin, wurde aber entfernt und kann aus den Templates ce_downloads und ce_gallery entfernt werden. https://github.com/contao/core/search?utf8=%E2%9C%93&q=v2warning

**Comment by leofeyer** [comment]
Entfernt in 3674d54bd4dbcd1e1ddac9888c2e9e5fabd994dd.
