### ISSUE TITLE
Problem with layoutbuilder-CSS

### ISSUE THREAD

**Issue by tabcontao** [contao/core#8029]
If you use a layout with main and right column and the right column is wider than the main column, the layout is broken and the right column is displayed below the main column. 
See also:
https://community.contao.org/de/showthread.php?59264-rechte-Spalte-umbricht-unter-Hauptspalte

**Comment by leofeyer** [comment]
See https://community.contao.org/de/showthread.php?59264-gel%F6st-rechte-Spalte-umbricht-unter-Hauptspalte&p=385153&viewfull=1#post385153
