### ISSUE TITLE
Add option_callback when creating header in mode 4

### ISSUE THREAD

**Issue by garyee** [contao/core#8031]
Hi,

it would be good and consistent if the DC would check for a option_callback when creating the header in mode 4.
Should be somewhere near [here](
https://github.com/contao/core/blob/master/system/modules/core/drivers/DC_Table.php#L4010)

thx

**Comment by leofeyer** [comment]
?

**Comment by garyee** [comment]
When creating a backend-listing with sorting mode 4 (Displays the child records of a parent record) the header can be filled with the help of the "headerFields", if one of those fields is a selectbox with an option_callback, contao will ignore that and will just display the database-value of the object. One could implement this with the help of the header_callback, but that would mean to do the work all over again.

**Comment by leofeyer** [comment]
Fixed in 007cec1f71e3503ceeb634d6a3cd6de60952cdbc.

**Comment by garyee** [comment]
:+1:
