### ISSUE TITLE
3.5.3: Element Text editieren / erstellen -> Paragraph falsch in DB gespeichert

### ISSUE THREAD

**Issue by pswerbung** [contao/core#8032]
Wir fahren mit PHP 5.4.38 und beobachten, dass wenn neue Inhalte erstellt werden als Textelement in der DB alle öffnenden Tags des Typs p und a falsch abgelegt werden in der DB:

```
&lt;p>Grosser Test&lt;/p>
<h2>&lt;a href="mailto:aksdjf@kssfj.ch">Titel&lt;/a></h2>
&lt;p>Mengentexte ...&lt;/p>
```

Dies geschieht somit bereits beim Speichern im TinyMCE. Im Frontend haben wir dann den (gerenderten) Quelltext unschön drin :-(

Wir haben zum debuggen:
- auf der Installation (resp. einem Duplikat) praktisch alle Extensions deinstalliert
- testweise alle JS in Seitenlayout deaktiviert
- den ganzen /assets/tinymce4 ersetzt aus dem aktuellen Contao-Archiv
- testweise ein HTML-Element erstellt. Sobald dort das <p> und <a> TAG verwendet wird, wird es wiederum falsch kodiert abgelegt.

… aber wir können den Fehler einkreisen. Ist der TinyMCE defekt in diesem Release? Da steht 4.1.10 in tinymce.min.js …?

**Comment by fritzmg** [comment]
Habe es jetzt nicht selbst in einer 3.5.3 Installation getestet, kann mir aber nicht vorstellen, dass das ein genereller Fehler ist. Sieht eher so aus, als würde ein Sicherheitsmodul eures Webservers dazwischen funken.

**Comment by pswerbung** [comment]
Dank fritzmg – wir haben mit dem Provider geschaut und sind nicht weiter gekommen.
- andere PHP Versionen (5.5, 5.6 …)
- anderer Webserver, wo bereits eine andere CN 3.5.3 läuft ohne Probleme: dort läuft aber dieses duplizierte Installation auch nicht
- CORE ersetzt von aktuellem 3.5.3 ZIP
- Uninstall ALLER Extensions in irgend einer Art

Immer speichert es uns codierte TAGs in die DB:
```
&lt;p>sdlkfjsksdf sdf d&lt;/p>
&lt;p>[nbsp]&lt;/p>
&lt;p>dfsd&lt;/p>
```
Welcher «Motor» ist für das Hineinspeichern verantwortlich in Contao? Könnte es an einem Timing liegen …?

**Comment by fritzmg** [comment]
Was meinst du mit Motor? Contao verarbeitet einfach (über DC_Table bzw. DataContainer) den Input und speichert ihn in der Datenbank. Warscheinlich passiert diese Umwandlung schon irgendwo vorher, eben durch bspw. irgendein Sicherheitsmodul des Webservers.

**Comment by fritzmg** [comment]
Übrigens: versuche das Ganze mal in einer komplett frischen Contao Installation. Du hast zwar

> CORE ersetzt von aktuellem 3.5.3 ZIP

und

> den ganzen /assets/tinymce4 ersetzt aus dem aktuellen Contao-Archiv

gemacht, aber dann könnte es immer noch sein, dass irgendjemand bspw. die `tinyMCE.php` oder `tinyNews.php` (oder `tinyFlash.php`) in `system/config` geändert hat.

**Comment by pswerbung** [comment]
@fritzmg: wir haben die Lösung erhalten durch diesen simplen Tipp:
https://community.contao.org/de/showthread.php?59272-Trouble-neues-Inhaltselement-Text-generiert-HTML-Code&p=385232#post385232

Hurra, somit ist das issue geclost. Ich bedanke mich herzlich für eure Hilfen!

**Comment by fritzmg** [comment]
Ah na dann :)
