### ISSUE TITLE
Contentelement Gallery

### ISSUE THREAD

**Issue by Taskrider** [contao/core#8033]
### Fehler bei der Sortierung.

Wenn die Sortierung auf *Zufällige Reihenfolge* gestellt ist und dabei die *Pagination* aktiviert ist werden nicht zwangsläufig alle Bilder ausgespielt!

Es kommt dabei vor das Bilder der ersten Seite der Galerie auf der zweiten Seite wieder mit ausgeben werden, genauso umgekehrt. 
Die Anzahl der gezeigten Bilder stimmt aber mit der Anzahl der gewählten Bilder überein.

**Comment by Zeromax** [comment]
Ich denke mal dass die Reihenfolge der Elemente bei einer Zufälligen Sortierung mit Pagination nicht in der Session gespeichert wird.
Somit werden die Bilder auf jeder Seite wieder "neu" gemischt.

**Comment by fritzmg** [comment]
Ja, bei der derzeitigen Implementierung sind diese beiden Optionen im Prinzip nicht miteinander kompatibel.

**Comment by leofeyer** [comment]
Wie am 14. Oktober auf Mumble besprochen, lässt sich das nur schwer technisch umsetzen (Random Seed, weiterzugebende URLs, Canonical-Problematik beim Indexieren etc.). Wir tendieren daher dazu, die Pagination zu deaktivieren, wenn die zufällige Sortierung ausgewählt wurde.

**Comment by fritzmg** [comment]
Man könnte ja in so einem Fall zuerst alle image IDs selektieren, diese randomizen und diese Liste dann in der Session für das jeweilige Inhaltselement abspeichern.

**Comment by leofeyer** [comment]
Geändert in f9e8d145895089158e6f1503b9a072fc3b01ac5e.

**Comment by Aybee** [comment]
The text of `$GLOBALS['TL_LANG']['tl_content']['random']` should be changed here
- Random order => Random order (no pagination)
- Zufällige Reihenfolge => Zufällige Reihenfolge (kein Seitenumbruch)
Tooks me a long time to figure out why there is no pagination.

**Comment by leofeyer** [comment]
Geändert in contao/core-bundle@2e51646b75bd4358e0ccdc6867f4b5d50bd71d62.

**Comment by Aybee** [comment]
Thank you.
