### ISSUE TITLE
double php tag in localconfig after installation

### ISSUE THREAD

**Issue by InitArt** [contao/core#8034]
php_errors.log
```
Sep-2015 15:32:44 Europe/Berlin] PHP Parse error:  syntax error, unexpected '<' in /var/www/contao/web/system/config/localconfig.php on line 3
```

localconfig.php
```
<?php

<?php

### INSTALL SCRIPT START ###
HIDDEN
### INSTALL SCRIPT STOP ###
```

This is what I've got after installing contao via install tool, resulting in a white page.

Using nginx 1.8 and PHP 5.6.13

**Comment by BugBuster1701** [comment]
Contao 4? Then looking here: https://github.com/contao/core-bundle/issues/344

**Comment by InitArt** [comment]
Alright, used the wrong search terms I guess
