### ISSUE TITLE
Uuids for filepicker/fileSelector

### ISSUE THREAD

**Issue by dmolineus** [contao/core#8035]
At the moment the FileSelector (talking not about the fileTree!) uses the file path as value. It would be great if there could be an option to get the uuid of the file so that a filepicker wizard could create the `{{file::uuid}}` insert tag instead of the path.

**Comment by pswerbung** [comment]
Yep, same here. What if files are reordered in FileTree, will they get lost now in Contao 3.5.x? In Version 3.2. I could use the file::uuid instead – but manually, which was also quite confusing …

**Comment by Aybee** [comment]
Related #7850
