### ISSUE TITLE
Image selector of articel does not work in 3.5

### ISSUE THREAD

**Issue by tpk109** [contao/core#8036]
Hi, 
the image-selector in 3.5 does not work. I deinstalled all Extensions.
![unbenannt](https://cloud.githubusercontent.com/assets/6112444/10095379/ac6f3834-6369-11e5-87df-e6bf58ed6d0b.JPG)

**Comment by Toflar** [comment]
Can you check the log files, please? :)

**Comment by tpk109** [comment]
Forgot to write: No Errors in Logfile

**Comment by Toflar** [comment]
In the Contao log files probably. But certainly in the web server log files.

**Comment by tpk109** [comment]
<addr>91.39.214.92 - - [25/Sep/2015:10:19:27 +0200] "GET /contao/main.php?do=article&table=tl_content&act=edit&id=4&mmo=1&rt=66ea5ee7b401d5978fda6b6a20b67303&ref=c2d0becd HTTP/1.1" 303 - "http://domain/contao/main.php?do=article&table=tl_content&act=edit&id=4&rt=66ea5ee7b401d5978fda6b6a20b67303&ref=37f1512d" "Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.93 Safari/537.36" domain
91.39.214.92 - - [25/Sep/2015:10:19:28 +0200] "GET /assets/css/5118afdcdd5e.css HTTP/1.1" 304 - "http://domain/contao/main.php?do=page&ref=d75febd1" "Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.93 Safari/537.36" domain
91.39.214.92 - - [25/Sep/2015:10:19:28 +0200] "GET /assets/js/5fb3f1a5e5e2.js HTTP/1.1" 304 - "http://domain/contao/main.php?do=page&ref=d75febd1" "Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.93 Safari/537.36" domain
91.39.214.92 - - [25/Sep/2015:10:19:27 +0200] "GET /contao/main.php?do=page&ref=d75febd1 HTTP/1.1" 200 177865 "http://domain/contao/main.php?do=article&table=tl_content&act=edit&id=4&rt=66ea5ee7b401d5978fda6b6a20b67303&ref=37f1512d" "Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.93 Safari/537.36" domain
91.39.214.92 - - [25/Sep/2015:10:19:28 +0200] "GET /system/modules/landingpages/assets/images/icon.png HTTP/1.1" 403 327 "http://domain/" "Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.93 Safari/537.36" domain
188.165.15.176 - - [25/Sep/2015:10:19:29 +0200] "GET /finanzierungsmakler.html HTTP/1.1" 200 4670 "-" "Mozilla/5.0 (compatible; AhrefsBot/5.0; +http://ahrefs.com/robot/)" www.wer-kennt-makler.de
91.39.214.92 - - [25/Sep/2015:10:19:32 +0200] "GET /contao/main.php?do=article&ref=6f4d3177 HTTP/1.1" 200 201091 "http://domain/contao/main.php?do=page&ref=d75febd1" "Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.93 Safari/537.36" domain
91.39.214.92 - - [25/Sep/2015:10:19:32 +0200] "GET /system/modules/landingpages/assets/images/icon.png HTTP/1.1" 403 327 "http://domain/" "Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.93 Safari/537.36" domain
91.39.214.92 - - [25/Sep/2015:10:19:34 +0200] "GET /contao/main.php?do=article&table=tl_content&id=48&rt=66ea5ee7b401d5978fda6b6a20b67303&ref=42777682 HTTP/1.1" 200 21999 "http://domain/contao/main.php?do=article&ref=6f4d3177" "Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.93 Safari/537.36" domain
91.39.214.92 - - [25/Sep/2015:10:19:35 +0200] "GET /system/modules/landingpages/assets/images/icon.png HTTP/1.1" 403 327 "http://domain/" "Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.93 Safari/537.36" domain
91.39.214.92 - - [25/Sep/2015:10:19:37 +0200] "GET /contao/main.php?do=article&table=tl_content&act=edit&id=53&rt=66ea5ee7b401d5978fda6b6a20b67303&ref=4795de99 HTTP/1.1" 200 27256 "http://domain/contao/main.php?do=article&table=tl_content&id=48&rt=66ea5ee7b401d5978fda6b6a20b67303&ref=42777682" "Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.93 Safari/537.36" domain
91.39.214.92 - - [25/Sep/2015:10:19:37 +0200] "GET /system/modules/landingpages/assets/images/icon.png HTTP/1.1" 403 327 "http://domain/" "Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.93 Safari/537.36" domain
91.39.214.92 - - [25/Sep/2015:10:19:39 +0200] "POST /contao/main.php?do=article&table=tl_content&act=edit&id=53&rt=66ea5ee7b401d5978fda6b6a20b67303&ref=4795de99 HTTP/1.1" 200 7811 "http://domain/contao/main.php?do=article&table=tl_content&act=edit&id=53&rt=66ea5ee7b401d5978fda6b6a20b67303&ref=4795de99" "Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.93 Safari/537.36" domain
91.39.214.92 - - [25/Sep/2015:10:19:40 +0200] "GET /contao/file.php?do=article&table=tl_content&field=singleSRC&act=show&id=53&value=&rt=66ea5ee7b401d5978fda6b6a20b67303 HTTP/1.1" 500 - "http://domain/contao/main.php?do=article&table=tl_content&act=edit&id=53&rt=66ea5ee7b401d5978fda6b6a20b67303&ref=4795de99" "Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.93 Safari/537.36" domain</addr>

**Comment by Toflar** [comment]
That looks like the access log which only tells us about the requests, but we need the error log :)

**Comment by tpk109** [comment]
It's a shared host (on alfahosting). That's the only log file I can find there.

**Comment by Toflar** [comment]
Then nobody can help you I guess. As long as there are no error logs or no way how we can reproduce it (did you try in the online demo?) everything we do is a shot in the dark :(

**Comment by tpk109** [comment]
And the js error in the screenshot is of no help?

**Comment by tpk109** [comment]
And the js error in the screenshot does not help? I asked the provider for
a log.

2015-09-25 10:33 GMT+02:00 Yanick Witschi <notifications@github.com>:

> Then nobody can help you I guess. As long as there are no error logs or no
> way how we can reproduce it (did you try in the online demo?) everything we
> do is a shot in the dark :(
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/contao/core/issues/8036#issuecomment-143160583>.
>



-- 
------------------------------------------
Thomas Kratz

Webseiten, Programmierung, Grafik & (Online)-Marketing:
www.web-om.de

Niehoffs Blaike 5
48369 Saerbeck
02574 – 245873
0176- 9652 999 0
info@web-om.de
USt-IdNr: DE815141427
------------------------------------------

**Comment by Toflar** [comment]
The error says "500 Internal Server Error" which means something on the server side failed. Might be 2 billion different things :)

**Comment by tpk109** [comment]
It simply was the memory limit, 16MB is to little. Perhaps a warning in the
backend would make sense?

2015-09-25 11:08 GMT+02:00 Yanick Witschi <notifications@github.com>:

> The error says "500 Internal Server Error" which means something on the
> server side failed. Might be 2 billion different things :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/contao/core/issues/8036#issuecomment-143166090>.
>



-- 
------------------------------------------
Thomas Kratz

Webseiten, Programmierung, Grafik & (Online)-Marketing:
www.web-om.de

Niehoffs Blaike 5
48369 Saerbeck
02574 – 245873
0176- 9652 999 0
info@web-om.de
USt-IdNr: DE815141427
------------------------------------------

**Comment by Toflar** [comment]
First of all it would be better suited in https://github.com/contao/check as it's a system requirement. It shouldn't go to the software itself. However, memory is always depending on your system. Heavy calculations or extensions that do expensive things will always affect the system. You will never be able to predict how much memory is needed and you'll never be able to prevent those things from happening. That's why you have server logs so you know where the error is. Nothing we should do here, in my opinion.
