### ISSUE TITLE
Sitemap-XML Probleme wenn Seitenalias "index"

### ISSUE THREAD

**Issue by Ma3xl3** [contao/core#8038]
In der Sitemap-XML wird die Location falsch ausgegeben, wenn der Seitenalias einer Seite mit  "index" ausgefüllt ist. (das ./ ist nicht korrekt). 
```xml
<url><loc>http://contao-3.5.local/./</loc></url>
```

Dies passiert allerdings nur, wenn kein in den Einstellungen die Checkbox  "Die Sprache zur URL hinzufügen" deaktiviert ist. Bei Aktivierung der Checkbox wird die Seite korrekt angegeben:
```xml
<url><loc>http://contao-3.5.local/en/</loc></url>
```

Die Home Seite sieht wie folgt aus:
![image](https://cloud.githubusercontent.com/assets/1608186/10140702/22c2fff6-6609-11e5-9d76-0abfc95e4700.png)

Kann dies bei der Online-Demo leider nicht ausprobieren, da die Einstellung "Die Sprache zur URL hinzufügen" nicht übernommen wird.

Durchgeführt mit Contao 3.5.3

**Comment by leofeyer** [comment]
Behoben in bcd7c1e8b2ec3a2a62b52f118d4ac5e0a86be68e.
