### ISSUE TITLE
Abstürzende Eventliste durch fehlerhafte Nutzereingaben

### ISSUE THREAD

**Issue by NinaG** [contao/core#8040]
Eine fehlerhafte Eingabe des Nutzers bei den Event-Werten bewirkt, dass Contao abstürzt.

Getestet mit: Contao 3.5.3

Hier zum Nachstellen die Werte:
Startdatum 20.09.2015 und Enddatum 22.11.2015, 
Haken bei 'Event wiederholen', Intervall: 1 Woche, Wiederholungen: 0 (unendlich), 
Haken bei 'Event veröffentlichen' und Feld befüllt 'Anzeigen bis' mit: 22.11.2015 00:00

Sobald man die normale Eventliste im Frontend aufruft (selbst wenn diese z.B. auf 5 Einträge beschränkt ist), stürzt das System mit einem Fatal error: Allowed memory size ab. Wie hoch die memory size dabei ist, ist egal (habe es u.a. mit 256MB getestet). 

Andere Nutzer konnten es im IRC nachstellen.

Natürlich ist die obige Eingabe recht sinnlos, kommt aber vor, wenn Nutzer misinterpretieren, wie sie ein wöchentlich stattfindendes Event für einen bestimmten Zeitraum einstellen. Ergo sollte Contao solche Fehleingaben möglichst erkennen und abfangen, bevor es deswegen abstürzt.

Sofern das möglich ist :-)

**Comment by NinaG** [comment]
Noch ein kleiner Nachtrag:
Die Kunden kommen auf solche Idee, weil bei sich wiederholenden Terminen in der Vollansicht NICHT steht, von wann bis wann so eine Terminreihe stattfindet. Es steht da dann nur das Startdatum und dass sich der Termin jede Woche wiederholt.

Was sich die Kunden stattdessen (unisono, also wirklich alle Kunden, die bei mir jemals das Eventmodul mit sich wiederholenden Terminen genutzt haben) wünschen, wäre, dass bei solchen Terminen die Rahmenbedingungen in der Detailansicht klarer stünden.

**Comment by leofeyer** [comment]
Ich konnte das Problem nicht in dieser Form reproduzieren. Die Eventliste stürzt nur ab, wenn ich alle Events anzeigen lasse. Bei einer Beschränkung auf 5 Einträgen wird alles korrekt dargestellt.

Ich kann außerdem keinen Fehler erkennen, da die Anzeige der Eingabe entsprechend richtig erfolgt.
