### ISSUE TITLE
Doppeltes ce_text in event_list-Template

### ISSUE THREAD

**Issue by NinaG** [contao/core#8041]
Im HTML-Output des event_list-Templates wird für den angezeigten Event-Teaser ein doppeltes (ineinander verschachtelt) 
``` 
<div class="ce_text block">
```
ausgegeben.

Getestet mit: Contao 3.5.3

In der Demo so nachstellbar:
Im bestehenden Demo-Modull 'Calendar - Event list' die Template-Auswahl auf 'event_list' umstellen.
Im Frontend dann z.B. hier unten die Liste der Upcoming Events ansehen:
http://demo.contao.org/en/events.html?month=201303

Sieht man sich den Quelltext an, kommt darin folgendes Ergebnis:
``` 
...
<div class="ce_text block">
<div class="ce_text block">
<h2>The famous Contao Event</h2>
<p>The famous Contao event is the biggest event in the Contao universe with a bunch of speakers, workshops and a lot of fun with great people.&nbsp;</p>  
</div>
</div>
...
```

**Comment by leofeyer** [comment]
Behoben in 760f6b39f1f1f0f9d1e6e698c2f9b64fc05b5606.
