### ISSUE TITLE
Input::stripTags fehlerhaft?

### ISSUE THREAD

**Issue by hh-com** [contao/core#8042]
Input::stripTags scheint fehlerhaft zu sein
```php
$testString = "<p>Eintrag bestehend aus x und y, aber auch z.</p>";

var_dump( $testString );
string(50) "<p>Eintrag bestehend aus x und y, aber auch z.</p>"

var_dump( strip_tags($testString) ); # PHP
string(43) "Eintrag bestehend aus x und y, aber auch z."

var_dump( Input::stripTags($testString) ); #Contao
string(56) "&lt;p>Eintrag bestehend aus x und y, aber auch z.&lt;/p>"
````

Contao-Version 3.5.2 (Input.php in 3.5.3 ident)

**Comment by BugBuster1701** [comment]
Das `Input::stripTags` geht von einem Formular Feld aus, dort werden aus Sicherheitsgründen die öffnenden spitzen Klammern gewandelt. Dagegen `strip_tags` ist eine allgemeine String Funktion.

Es gibt aber bei der Input Methode einen zweiten Parameter  mit der man die erlaubten Tags übergeben kann.
Siehe hier: https://github.com/contao/core/blob/d11b2257e9a9c2b9b5daadb383298782f3a065d0/system/modules/core/library/Contao/Input.php#L187

**Comment by hh-com** [comment]
Alles klar, somit erledigt.
