### ISSUE TITLE
SaveCallback für disable Feld bei tl_member verhält sich nicht konsistent

### ISSUE THREAD

**Issue by Fuzzyma** [contao/core#8043]
Wenn der SaveCallback ganz normal über das Speichern-Feld des Datensatzes aufgerufen wird, kann man den bearbeiteten Datensatz über den dca-parameter rausbekommen (`$dc->id`).
Wird der Callback jedoch über den toggle-button aufgerufen, mit dem man member aktivieren/deaktivieren kann, gibt `$dc->id` NULL zurück, weil  im DC_Table-Objekt die Eigenschaft `intId` nicht/falsch gesetzt wird.
Die wird nämlich im Konstruktor über `$this->intId = \Input::get('id');` gesetzt. Der toggle-button übergib aber in diesem Fall nur eine `tid` und keine `id`, was zu diesem fehlerhaften Verhalten führt.

Meiner Meinung nach, sollten sich beide Fälle gleich verhalten.

Auch der erste Parameter ist konfus (bei normalen Speichern `''` bzw `'1'` und über toggle `true` und `false`). true und false sind hier beim toggle sogar noch vertauscht. true beim aktivieren bzw `''` beim aktivieren. Wie soll man da rausbekommen, was denn nun richtig ist?

Ich vermute den "bug" (wenns denn einer ist) in [dieser](https://github.com/contao/core/blob/0cb85bb79422c0c8bb8a3ef0f37a135826e663a5/system/modules/core/dca/tl_member.php#L697) Zeile, wo der SaveCallback aufgerufen wird. Dort sollte eventuell nicht 
```php
$blnVisible = $this->$callback[0]->$callback[1]($blnVisible, ($dc ?: $this));
```

sondern

```php
$blnVisible = $this->$callback[0]->$callback[1](!$blnVisible, ($dc ?: $this));
```

stehen.
Außerdem sollte vorher die `id` im `$dc` gesetzt werden

**Comment by leofeyer** [comment]
Den einzigen Fehler, den ich hier eventuell erkenne, ist das `$dc->id` leer ist. Wie genau kann ich den Fall reproduzieren?

**Comment by Fuzzyma** [comment]
ich habe mir die einfach ausgeben lassen (var_dump() und die()). Entweder beim normalen Speichern (da war sie vorhanden) oder aber beim enable/disable-icon (da habe ich mir den Antwort-Body über die JS Konsole angeguckt weils ja Ajax ist).

Ich finde es durchaus merkwürdig, dass der Wert im save_callback zwischen `true`, `false`, `''` und `'1'` schwanken kann. Naja dadurch weiß man wenigstens woher der call kommt - vll auch nicht so schlecht

**Comment by leofeyer** [comment]
> ich habe mir die einfach ausgeben lassen (var_dump() und die()).

Ja, aber wie genau? Ich möchte mir das hier gerne nachstellen.

**Comment by Fuzzyma** [comment]
Eigenes Modul mit Hook. dca für tl_member.php:

```php
$GLOBALS['TL_DCA']['tl_member']['fields']['disable']['save_callback'][]  = array('MailOnActivation', 'activate');

class MailOnActivation extends tl_member{

    public function activate($varAktiv, $dc)
    {   
        var_dump($dc->id); die();
        if($varAktiv === true || $varAktiv === '' && \MemberModel::findByPk($dc->id)->disable == '1'){
            $this->sendMemberWasActivatedMail($dc->id);
        }

        return $varAktiv; 
    }
    
    
    public function sendMemberWasActivatedMail($memberId){

        // send Mail
        
    }
    
}
```

I hacked the core to add the id and its working

**Comment by leofeyer** [comment]
Behoben in 6377831d52922dc10831ac6874e4b0e205b87350.
