### ISSUE TITLE
Formular-Validierung (nicht vs. falsch ausgefülltes Pflichtfeld)

### ISSUE THREAD

**Issue by Anke** [contao/core#8044]
Zum Thema Formularvalidierung und Zurückspringen an den Seitenanfang (anstatt zur Fehlermeldung):

Bei der HTML5-Validierung geht der Fokus zum ersten Pflichtfeld, das nicht ausgefüllt wurde. Wird aber z.B. die Captcha-Frage falsch beantwortet, springt die Seite zurück an den Anfang. (Ich nehme an, das ist auch bei anderen Feldtypen so.) 

Wenn die HTML5-Validierung keine falsch ausgefüllten, sondern nur leere Pflichtfelder erkennt, ist es da nicht sinnvoll, eine ergänzende JS-Kontrolle in den Core mit aufzunehmen? Sonst hat man immer wieder ein Problem bei langen Formularen oder One-Page-Websites.

**Comment by leofeyer** [comment]
@contao/developers /cc

**Comment by aschempp** [comment]
ganz klar nein. die HTML5-Validierung kann auch deaktiviert werden.

Wir hatten in Contao 2.11 (wenn ich mich richtig erinnere) aber ein Snippet drin, welches jeweils zum ersten Fehler-Feld gescrollt ist. Ich glaube das hatten wir nur wegen jQuery entfernt, wäre ggf. sinnvoll als Vanilla wieder einzubauen.

**Comment by leofeyer** [comment]
As discussed in Mumble on August 11th, we should add this script in the `form.html5` template as it used to be in https://github.com/contao/core/blob/2.11.0/system/modules/frontend/templates/form.html5. However, it should be VanillaJS instead of MooTools or jQuery.

**Comment by ausi** [comment]
The VanillaJS version could look like this:

```js
try {
  document.querySelector('#<?= $this->formId ?> .error').scrollIntoView();
} catch(e) {}
```

[scrollIntoView](http://caniuse.com/#feat=scrollintoview) and [querySelector](http://caniuse.com/#feat=queryselector) are supported in all major browsers.

**Comment by leofeyer** [comment]
Thank you @ausi.

**Comment by leofeyer** [comment]
Implemented in contao/core-bundle@01d55985818d13593561f515bfa45dd33112990b.
