### ISSUE TITLE
Modul-Inhaltselement - Ungültiges Token

### ISSUE THREAD

**Issue by Wagnerwagner** [contao/core#8046]
Wenn man ein Modul als Inhaltselement einbindet und im Inhaltselement auf den Bearbeiten-Stift klickt, um das Modul selbst zu bearbeiten, landet man immer auf der "/contao/confirm.php" anstatt die Lightbox mit der Modulbearbeitungsmaske aufpoppt:

Inhalt der Fehlermeldung:
> Ungültiges Token
>contao/main.php?do=themes&table=tl_module&act=edit&id=35
>ModulThemesBetroffene Tabelletl_moduleAktionModul bearbeitenBetroffener DatensatzID 35
Der Link, den Sie aufgerufen haben, konnte nicht verifiziert werden. Wenn Sie den Link selbst aufgerufen oder von einer vertrauenswürdigen Person erhalten haben, können Sie den Vorgang fortsetzen.

Nach Klick auf den Button "Weiter" landet man dann in der Bearbeitungsmaske des Moduls.

Getestet / Funktioniert NICHT:
Contao 3.5.3 mit Composer - Fehlerseite erscheint
Contao 3.5.2 mit Composer - Fehlerseite erscheint
Link auf dem Bearbeiten-Stift:
contao/main.php?do=themes&amp;table=tl_module&amp;act=edit&amp;id=35

Getestet / Funktioniert:
Contao 3.5.2 ohne Composer - Keine Fehlerseite, Eingabemaske funktioniert.
Link auf dem Bearbeiten-Stift:
"contao/main.php?do=themes&amp;table=tl_module&amp;act=edit&amp;id=35&amp;popup=1&amp;nb=1&amp;rt=f128e59c27e73b64e4420398e9592759

Chrome-Konsole zeigt keine Fehler an.

**Comment by leofeyer** [comment]
Wie lässt sich das in der Onlinedemo reproduzieren?

**Comment by Wagnerwagner** [comment]
Im Onlinedemo funktioniert es fehlerfrei. Allerdings sehe ich da auch nicht, ob Composer oder das ER2 aktiv ist. Gibts ein Demo-System mit Composer?

Zum Reproduzieren allgemein:
- Ein Modul anlegen (z.B. eigenes HTML)
- In einen Artikel wechseln und dort ein Inhaltselement vom Typ Modul anlegen
- Das angelegte Modul auswählen und speichern
- Im Inhaltselement neben der Dropdownauswahl auf das Stift-Symbol klicken
![modul_edit](https://cloud.githubusercontent.com/assets/7679272/10303378/a4355bf0-6c13-11e5-90bd-d0cd1ca270ab.JPG)

Und je nachdem öffnet sich die "Lightbox" um das Modul aus dem Inhaltselement heraus zu bearbeiten oder man wird auf die Seite "Ungültiges Token" weitergeleitet (wenn der Link darauf "abgeschnitten" ist).

**Comment by leofeyer** [comment]
> Im Onlinedemo funktioniert es fehlerfrei.

Dann gehört diese Anfrage nicht hierher. Bitte stattdessen im [Forum](https://community.contao.org/de/) posten.

**Comment by Wagnerwagner** [comment]
Steht jetzt im Forum:
https://community.contao.org/de/showthread.php?59494-Modul-Inhaltselement-Ung%FCltiges-Token

**Comment by Wagnerwagner** [comment]
Fehlverhalten wird durch heimrichhannot/contao-blocks verursacht
https://github.com/heimrichhannot/contao-blocks/issues/1
