### ISSUE TITLE
Inserttag link_* ignoriert Seitenschutz bei externen Weiterleitungen

### ISSUE THREAD

**Issue by gerritlo** [contao/core#8047]
Hallo zusammen,

ich habe eine Seit als externe Weiterleitung eingerichtet und unter "Seite schützen" eine Mitgliedergruppe gewählt. Die Seite ist damit auch geschützt und die Weiterleitung kann nur als eingeloggtes Mitglied aufgerufen werden. Anders verhält es sich, wenn ich ein CE vom Typ Hyperlink verwende und dort die Weiterleitungsseite auswähle. Das generierte Inserttag durch das CE sieht wie folgt aus `{{link_url::79}}`.

Bei der Ersetzung des Inserttags in https://github.com/contao/core/blob/master/system/modules/core/library/Contao/InsertTags.php #357 wird der Seitenschutz ignoriert.

Wir die Case-Anweisung wie folgt ersetzt, funktioniert die Berechtigungsprüfung:
```php
case 'redirect':
	$objNextPage->loadDetails();

	if (!$objNextPage->protected)
	{
		$strUrl = $this->replaceInsertTags($objNextPage->url); // see #6765
	} else {

		$strForceLang = null;

		// Check the target page language (see #4706)
		if (\Config::get('addLanguageToUrl'))
		{
			$strForceLang = $objNextPage->language;
		}

		$strUrl = $this->generateFrontendUrl($objNextPage->row(), null, $strForceLang, true);
	}

	if (strncasecmp($strUrl, 'mailto:', 7) === 0)
	{
		$strUrl = \StringUtil::encodeEmail($strUrl);
	}
	break;
```

**Comment by gerritlo** [comment]
Kann den Fehler keiner nachvollziehen?

**Comment by leofeyer** [comment]
Das ist kein Fehler. Du musst das Hyperlink-Element ebenfalls schützen, wenn Du möchtest, dass nicht jeder zugreifen kann.

**Comment by gerritlo** [comment]
Wenn ich nun aber möchte, dass der Anwendern nach dem Login auf die Weiterleitungsseite geschickt wird, habe ich keine andere Möglichkeit.

Nutze ich den Element-Schutz, muss ich einen zweiten Hyperlink nehmen, der auf die Loginseite verweist. Wenn ich das aber so umsetze, werde ich nach dem Login wieder auf die Einstiegsseite geleitet (wo das Linkelement war) und muss erneut auf den Link klicken (den zweiten nun sichtbaren). Das ist doch nicht gewollt.

**Comment by leofeyer** [comment]
Wie genau ist Dein Setup?

**Comment by gerritlo** [comment]
Ich brauche eigentlich nur einen Hyperlink auf einer Seite, der nur für eingeloggte User funktioniert. Sind die User nicht eingeloggt, sollen Sie auf die Login-Seite geleitet werden. (Bis dahin geht alles noch mit Inhaltselementen, die Gästen etc. angezeigt werden.) Nach erfolgreichen Login, soll dann aber auf die Zielseite des Hyperlinks geleitet werden.

Das geht nur, wenn ich eine Seite als externe Weiterleitung einrichte und sie schütze. Dann wird der Anwender nämlich auf die Loginseite geleitet. Nach dem Login erfolgt dann der Redirect auf die geschützte ExternerLink-Seite.
