### ISSUE TITLE
Fehler in der Newsletterregistrierung

### ISSUE THREAD

**Issue by dhe** [contao/core#8049]
Hallo,
ich nutze Contao 3.5.3 LTS und hänge gerade an der Newsletterregistierung.
Wenn ich auf der Bestätigungsemail den Link mit dem Token klicke, komme ich auch auf die richtige Seite, erhalte aber jedes mal den Fehler "Der Aktivierungslink ist ungültig oder veraltet."

Der Benutzer wird aber im BE dennoch aktiviert.

In der Online-Demo leider nicht überprüfbar, da dort keine E-Mails rausgehen.

Hat jemand eine Idee?

**Comment by leofeyer** [comment]
Für diese Art von Fragen ist das [Forum](https://community.contao.org/de/) der richtige Platz.

**Comment by pswerbung** [comment]
@dhe Habe genau dasselbe Phänomen unter Contao 3.5.9: Es kommt die Fehlermeldung «Der Aktivierungslink ist ungültig oder veraltet» obwohl der Abonnent aktiviert wird! Es handelt sich somit um einen Core-Fehler aus meiner Sicht. Wird die falsche Meldung «abgegriffen»? Wo kann man dies korrigieren?

**Comment by leofeyer** [comment]
Ich habe es soeben in meiner lokalen Entwicklungsumgebung geprüft und konnte den Fehler nicht reproduzieren.

<img width="710" alt="" src="https://cloud.githubusercontent.com/assets/1192057/14632951/a196524e-061b-11e6-9217-009dd90fa6c7.png">
