### ISSUE TITLE
Eigene CSS ID/ Klasse wird in Modul 'Eigner HTML-Code' nicht ausgegeben

### ISSUE THREAD

**Issue by cs1982** [contao/core#8050]
Ich nutze C3.5.3 mit einem Grid. Wenn ich in einem Artikel an einem dort verwendeten Modul 'Eigner HTML-Code' eine 'Eigene CSS ID/ Klasse' definiere, wird diese im FE-HTML nicht ausgegeben.
Natürlich kann ich die Klasse gerade in dem Modultyp direkt im Code definieren. Es ist vermutlich jedoch nicht im Sinne des Erfinders, dass die Standardfelder nicht funktionieren.

**Comment by aschempp** [comment]
Du musst die Klasse im Inhaltselement erneut eingeben. Dieses verhalten wurde in Contao 4 geändert.

**Comment by asaage** [comment]
Also bei mir hat der Modultyp bzw. das CE 'Eigener HTML-Code' überhaupt nicht die Felder für 'Eigene CSS ID/ Klasse'... 
Es ist nicht so, dass ich das brauchen würde, aber so ganz konsistent find ich das auch nicht.

**Comment by cs1982** [comment]
Ich sehe am Modul selbst keine Möglichkeit, eine CSS-Klasse zu definieren. Am Inhaltselement, dass das Modul verwendet, schon. Wenn ich dort eine Klasse angeben (in den Bildern "test"), wird diese im HTML nicht ausgeben. Wenn ich das richtig überblicke, liegt es daran, dass um das ausgegebene HTML von Contao nicht noch ein div erzeugt wird, in dem dann die am Inhaltselement definierte Klasse stehen würde/ könnte.
Und wenn ich dich weiter richtig verstehe, ist das Verhalten in C4 vermutlich in diese Richtung geändert worden. Das wäre Konsequent. Oder ist einfach die Möglichkeit, eine Klasse anzugeben, entfallen?
![1_contao_modul_eigeneshtml](https://cloud.githubusercontent.com/assets/3968448/10281763/0e6aed16-6b77-11e5-89d9-5f3d7d653fa5.PNG)
![2_contao_inhaltselement_zu_modul_eigeneshtml](https://cloud.githubusercontent.com/assets/3968448/10281766/1148fb2c-6b77-11e5-9d93-4fe1c4f83664.PNG)
![3_contao_eigeneshtml_htmlausgabe](https://cloud.githubusercontent.com/assets/3968448/10281769/13603678-6b77-11e5-9509-1f80bcd643d3.PNG)

**Comment by aschempp** [comment]
Bei einem HTML-Modul musst du die CSS-Klasse natürlich von Hand im Quelltext eingeben. Ein Feld dafür hast du nur bei den normalen Modulen (z.B. Navigationsmenü).
