### ISSUE TITLE
Problem with unnecessary space

### ISSUE THREAD

**Issue by frontendschlampe** [contao/core#8051]
In the following code rows an invisible span is added to the "more"-Link in the newslist of Contao.

https://github.com/contao/core/blob/master/system/modules/news/modules/ModuleNews.php#L403

And with the span there will be added an additional space in front of the ``<span>`` but this space is a little bit inconsistent and in my opinion not necessary, because the rendered code aus the space within the ``<a>``:

``<a href="details.html" title="Read the article: newstitle">Read more … <span class="invisible">newstitle</span></a>``

I have a style for ``<a>``-Tags with an icon on the right. For news there will be a space and for all other not.

So the question is: Why there's the invisible ``<span>`` again with the newstitle within the ``<a>``-Tag? Can you delete the space after the "…"?

**Comment by fritzmg** [comment]
The space should probably be moved inside the `<span>`.

But in any case, you can also build the "read more" link yourself in the template if you need to.

**Comment by frontendschlampe** [comment]
Yes, I know ... ;-)

**Comment by leofeyer** [comment]
> So the question is: Why there's the invisible ``<span>`` again with the newstitle within the ``<a>``-Tag? Can you delete the space after the "…"?

It is there for the screen readers. And removing the space is not possible, because it would affect how the content is read. We might be able to move the space inside the `<span>` tag, but I wonder what you mean by "inconsisten"; I have just searched the core and looked at the numerous usages of this technique and *all of them* had a space before the `<span>` tag. Seems pretty consistent to me :)

**Comment by frontendschlampe** [comment]
Ok - I think "Inconsistent" was the wrong wording! I mean it in connection with "normal" links.  ;-)

But the space is terrible! To move it into the span, will solve the problem. The question is, if the additional span with the title of the news is really necessary for the screen readers, because it's a hyperlink and there's a title-attribute ... maybe we have to talk to somebody who know more about this! ;-) Maybe @MacKP or @NinaG

**Comment by MacKP** [comment]
moving the space in the <span> would be great ^^
@frontendschlampe it is in there for accassibility, that's one great feature from Contao-Core ;-)

regards

**Comment by leofeyer** [comment]
Fixed in 6c02f28824ba18e7a1e23b1eecdd15a7ad36fb8b.

**Comment by leofeyer** [comment]
Fixed in eb5f34fa12649210e1782b61108a2b09a170fd0d.
