### ISSUE TITLE
Wrong option/typo in core.js passed to Mootools Sortable

### ISSUE THREAD

**Issue by bezin** [contao/core#8053]
Hey there, 

i just stumbled upon a typo in the Core Backend Javasript. The Sortable Object gets a [wrong option in Backend.makeParentViewSortable](https://github.com/contao/core/blob/master/assets/contao/js/core-uncompressed.js#L1314):
It gets the option *contstrain: true*, but it should be *constrain*, as documented in [the mootools docs](http://mootools.net/more/docs/1.5.1/Drag/Sortables).

Cheers

**Comment by leofeyer** [comment]
Fixed in 17b880c81f6e74433d90357d9db46c127634a6c2.
