### ISSUE TITLE
Menu item for not existing page mistakenly gets rendered

### ISSUE THREAD

**Issue by Aybee** [contao/core#8054]
Ich glaube es ist am einfachsten zu beschreiben, wenn man es direkt in der Online-Demo nachvollzieht.

1. BE - Alle Unterseiten der Seite *Modules* auf unveröffentlicht setzen.
2. FE - Der Punkt *Modules* ist sichtbar, macht aber keinen Sinn, weil es keine erste Unterseite gibt. Die Contao Fehlermeldung **Zielseite nicht gefunden** wird angezeigt.
3. BE - Seiteneinstellungen von *Modules*, Weiterleitungsseite einstellen, erste (unveröffentlichte) Unterseite von *Modules* auswählen
4. FE - Der Punkt *Modules* ist nicht sichtbar, das ist korrekt, Contao erkennt jetzt, dass diese Seite unveröffentlicht ist.

Der Fehler hier ist also, dass Contao nicht erkennt, dass die erste Unterseite, welche ja automatisch als Weiterleitung genommen wird, wenn keine Seite ausgewählt ist, nicht als unveröffentlicht erkennt. Contao reagiert korrekt, wenn man eine Weiterleitungsseite einstellt.

**Comment by fritzmg** [comment]
Verstehe nicht ganz wie du das meinst.

1. Die erste Unterseite wird nicht automatisch als Weiterleitung genommen, das würdest du ja selbst so einstellen, wenn du eine Seite vm Typ _Interne Weiterleitung_ anlegst.
2. In der Contao Demo ist die Seite _Modules_ keine Seite vom Typ _Interne Weiterleitung_, daher tritt auch kein Fehler auf, wenn man die Unterseiten auf unveröffentlicht setzt.

**Comment by asaage** [comment]
Doch: wenn man eine interne Weiterleitung anlegt, das Weiterleitungsziel aber frei lässt wird automatisch auf die erste (veröffentlichte) Unterseite weitergeleitet.
Das lässt sich gut nutzen um Menüs zu schachteln wenn einem der Content für eine übergeordnete Seite fehlt und man in der Reihenfolge der Unterpunkte flexibel bleiben möchte.
Erst wenn es keine veröffentlichten Unterseiten gefunden werden schlägt das __be_no_forward.html__ zu.

**Comment by fritzmg** [comment]
Ah, das wusste ich gar nicht.

**Comment by asaage** [comment]
Ich glaube das Feld "Weiterleitungsziel" war früher auch mal Pflicht für Weiterleitungsseiten...
Was @Aybee 's Ausführung betrifft: Ein etwas clevereres Menü würde interne Weiterleitungsseiten ohne Ziel und ohne veröffentlichte Unterseiten einfach überspringen richtig?

**Comment by Aybee** [comment]
Sorry, die Online-Demo war gerade kaputt, da hatte jemand alles gelöscht und Recover war nicht möglich, so hatte  ich meine Demo genommen und in dieser war Modules gerade eine interne Weiterleitungsseite. Aber was ich meine trift trotzdem zu.

Hier nochmal der Versuch einer einfachen Beschreibung:

---
**Mit** Zielseite: Menüpunkt *Modules* wird **nicht** gerendert. **korrekt**
- Seite Modules (int. Weiterleitung, Zielseite Navigation)
  - Seite Navigation (**nicht veröffentlicht**, gesetztes Ziel)

---
**Ohne** Zielseite: Menüpunkt *Modules* wird gerendert. Ziel wirft **Fehler** da nicht existent.
- Seite Modules (int. Weiterleitung, Ziel nicht gesetzt)
  - Seite Navigation (**nicht veröffentlicht**, automatisches Ziel)

Ich kann mich nicht daran erinnern, dass das Setzen des Ziels mal Pflicht war, ich habe das so gut wie noch nie setzen müssen. Nur wenn die interne Weiterleitung nicht die erste Unterseite sein sollte.

**Comment by leofeyer** [comment]
Behoben in 580e99639b215e1246ebbb5264156746bad8884f.
