### ISSUE TITLE
Bug in 3.5.3: Linkpicker im Bildelement bietet nur Dateien an, wenn im Feld was steht

### ISSUE THREAD

**Issue by xantippe** [contao/core#8055]
der Linkpicker im Bildelement bietet nur Dateien an, wenn im Feld was steht z.B.

zum "Nachbauen" in der Demo:

* CE Bild
* bei Link # einfügen und speichern
* bei Link auf "Kugel" klicken
=> es gibt keine Umschaltmöglichkeit zu den Seiten (oben steht aber "Seitenwähler")

**Comment by leofeyer** [comment]
?

**Comment by xantippe** [comment]
also: wenn ein CE Bild angelegt wird und nichts im Bildlink steht
![contao 1](https://cloud.githubusercontent.com/assets/1045318/10484124/9ccd8132-7283-11e5-8313-b0116789bab3.jpg)
dann erschein bei Klick auf die blaue Kugel folgendes im Popup
![contao 2](https://cloud.githubusercontent.com/assets/1045318/10484144/b4a7f328-7283-11e5-9c5a-fdc502e7a8ce.jpg)

trägt man bei dem Link einen Anker ein z.B. # 
![contao 3](https://cloud.githubusercontent.com/assets/1045318/10484167/d3cd60f8-7283-11e5-89be-3715000da0ad.jpg)


UND speichert das CE!

und klickt nochmal auf die Kugel kommt das

![contao 4](https://cloud.githubusercontent.com/assets/1045318/10484173/e8caad76-7283-11e5-9c61-732b63e7340b.jpg)

OHNE Seitenauswahl

**Comment by leofeyer** [comment]
Behoben in 835897c3c798774f619741b3315edd621d9c27c0.

**Comment by xantippe** [comment]
upps - bin etwas erstaunt: pagePicker gibt es 4x ?
https://github.com/contao/core/commit/835897c3c798774f619741b3315edd621d9c27c0

warum nicht als "allgemeine Funktion"?

**Comment by k-webdesign** [comment]
Hi,

der Fehler besteht weiterhin (3.5.6). Hab es eben auch in der Demo nachstellen können. Könnt ihr noch mal drüber schauen? :)

LG Kim

**Comment by Aybee** [comment]
Kann das für die Demo nicht bestätigen. Kannst du genauere Angaben machen? Betriebssystem, Browser. Legst du ein CE Typ Bild an?

**Comment by k-webdesign** [comment]
Windows 7, Chrome 48 - Geschieht aber auch unter OSX in Chrome, FF, usw. 

Ich gehe in der Demo wie folgt vor:
Articles -> Home -> Home -> Im Text "About this demo" eine beliebige Anzahl Wörter markieren, über "Insert/edit link" einen Link hinzufügen, # bei URL eintragen, speichern/ok. Dann den Link noch mal anklicken. noch mal auf "Insert/edit link" und auf das Icon rechts klicken. Jetzt bin ich in der Dateiverwaltung und habe oben lediglich den Link "Open the file manager".
Screens kann ich bei Bedarf später nachliefern. Ist gespeichert, kannst dir in der Demo anschauen, falls du es noch innerhalb der Session siehst.

**Comment by Aybee** [comment]
Ah, ok, das kann ich auch auf Win 10 im FF rekonstruieren.

In dem Ticket hier geht es um den Filepicker fürs Bildelement. Der Defekt, den du beschreibst betrifft den Filepicker des TinyMCEs.

**Comment by leofeyer** [comment]
Behoben in 98e91c3528a6422ec25dd549f243aa9003795bf4.
