### ISSUE TITLE
correct language of meta information independently from BE language

### ISSUE THREAD

**Issue by frontendschlampe** [contao/core#8056]
I have a website only in English and there's only one pagetree with language "en". I'm using the backend in German. Now I want to edit the meta information of files in the file manager and the predefined language for meta information is German and I have to add the English language manually. After adding the English meta information, I have an empty fieldset with German information on top and the needed English information on the bottom. I can't delete the German fieldset.

If I switch to English backend and add a new meta information for a file, there's shown only the English fieldset and I can't add another language which is the correct behavior. Using the backend in German it should be the same behavior.

So the default language of meta information must not be the backend language but the available languages of root pages.

**Comment by aschempp** [comment]
This is really annoying. Same problem in Contao 4.0 where the backend is only available in english…

**Comment by leofeyer** [comment]
Fixed in 4c987f36e29ecf806183e0e94e7fb5aee84abc77.
