### ISSUE TITLE
3.5.4 Responsive Bilder bei Teaserbild bei Events funktionieren nicht

### ISSUE THREAD

**Issue by jenda77** [contao/core#8059]
Ich habe in die Template die Anweisung für Teaserbild `<?php $this->insert('picture_default', $this->picture); ?>` eingefügt und dabei im Backend bei dem Modul die zentral angelegte Bildgröße ausgewählt. Dies hat mit 3.5.3 funktioniert, jetzt wird diese ignoriert und nur die maximale Größe der Bild ausgegeben, obwohl die Bilder automatisch nach der zentralen Bildvorgabe angepasst, d.h. beschnitten werden sollten. Wenn man die Bildgröße bei jedem Teaserbild bei Events auswählt, funktioniert es. D.h. diese Anweisung greift nur nicht bei dem Modul durch.

**Comment by leofeyer** [comment]
Wie lässt sich das in der Onlinedemo reproduzieren?

**Comment by jenda77** [comment]
Indem man ein neues Modul mittels des Eventsliste-Moduls erstellt und dabei dort die Bildgröße auswählt, die man vorher bestimmt hat. Diese Bildgrößevorgabe funktioniert bei der Eventsliste nicht, wenn man den o.g. Code für responsive Bilder verwendet.

**Comment by leofeyer** [comment]
Klappt bei mir ohne Probleme.

Ich habe eine Bildgröße von 200x200 Pixel angelegt und anschließend in einem Event ein Bild mit einer Größe von 500x500 Pixeln hinzugefügt. Danach habe ich `<?php $this->insert('picture_default', $this->picture); ?>` in das Template `event_list.html` kopiert.

Rufe ich die Eventliste im Frontend auf, wird das Bild in 500x500 Pixeln angezeigt.

Dann bin ich zurück in die Moduleinstellungen gegangen und habe für das Eventlistenmodul meine angelegte Bildgröße ausgewählt. Zurück im Frontend wird das Bild nun in 200x200 Pixeln angezeigt.

**Comment by jenda77** [comment]
Bei mir funktioniert es trotzdem nicht, es sei denn, dass ich die Bildgröße vorher bei jedem Event eingebe. 
![bildschirmfoto 2015-11-13 um 14 37 33](https://cloud.githubusercontent.com/assets/3715050/11147257/05d99e6a-8a15-11e5-9d66-3ec4f2870292.png)

![bildschirmfoto 2015-11-13 um 14 40 36](https://cloud.githubusercontent.com/assets/3715050/11147262/0bd726f2-8a15-11e5-8046-74bec98c9beb.png)

**Comment by leofeyer** [comment]
Das ist keine frische Installation, da Drittanbieter-Erweiterungen und angepasste Templates verwendet werden.

**Comment by jenda77** [comment]
Ja, aber wenn ich diese abschalte, hilft es trotzdem nicht. Mit News funktioniert es.

**Comment by leofeyer** [comment]
Das hilft leider nicht weiter. Als Referenz kann nur ein frische Installation ohne Drittanbieter-Erweiterungen dienen.

**Comment by jenda77** [comment]
Und wieso geht es bei News? Außerdem muss doch Contao mit aktuellen Erweiterungen laufen - gerade mit denen von Rocksolid...

**Comment by jenda77** [comment]
Jetzt habe ich die vordefinierte Bildgröße bei jedem Event ausgewählt und, wie geschrieben, dann funktioniert es.
