### ISSUE TITLE
News RSS-Feed

### ISSUE THREAD

**Issue by squidi** [contao/core#8061]
Beim erstellen der XML für die News-Feed, wird die Backend-Sprache des Benutzers eingetragen. Damit stimmen die Links nicht.

Es müsste die Sprache die im Feed eingetragen ist übernommen werden.

**Comment by leofeyer** [comment]
Wie lässt sich das in der Onlinedemo reproduzieren?

**Comment by squidi** [comment]
Ja

**Comment by squidi** [comment]
Deutsch kann man sich natürlich nicht in der Demo einloggen, konnte dann aber auf einer anderen Installation nachvollzogen werden.

Aber schon in der Demo werden beide Feeds mit en im Link erstellt.

**Comment by leofeyer** [comment]
Kann ich nicht reproduzieren. Bei mir wird immer die im Feed eingestellte Sprache eingetragen.
