### ISSUE TITLE
Calling a field "order" causes a mySQL syntax failure

### ISSUE THREAD

**Issue by Defcon0** [contao/core#8062]
Hi folks,

the title says it all. The field name should be quoted in the constructed query (UPDATE tl_... SET 'order'=1 instead of UPDATE tl_... SET order=1). At the moment I get syntax errors because mySQL interprets order as a directive (order by) :-)

Bye Defcon0

**Comment by aschempp** [comment]
There is no field `order` in the default Isotope? Did you create an attribute with that name?

**Comment by Defcon0** [comment]
Nope. It's plain contao. Nothing to do with isotope. I just named it order_id and it worked again. It's the way contao translates form submits into mysql.

**Comment by asaage** [comment]
That is using "Form generator" with the "Store data" option enabled?

**Comment by Defcon0** [comment]
Sorry, "form submit" might have been ambiguous. It's all about the backend. I save backend records using the normal contao handling.

**Comment by leofeyer** [comment]
This is a known issue. You must not use reserved SQL keywords as column names.

**Comment by Defcon0** [comment]
But wouldn't it be possible to just "escape" the reserved keyword with apostrophs?

**Comment by leofeyer** [comment]
Yes, depending on the database driver. But the Contao 3 framework does not support this feature. It should be possible with Doctrine in Contao 4.

**Comment by Defcon0** [comment]
Ah ok, thanks for the clarification!
