### ISSUE TITLE
Recoverable error with help wizard in event settings

### ISSUE THREAD

**Issue by Aybee** [contao/core#8065]
In der Online Demo die Settings eines Events öffnen, dann bei Redirect target auf den Help Wizard klicken. Es kommt dieser Fehler:
> Recoverable error: Argument 1 passed to tl_calendar_events::getSourceOptions() must be an instance of DataContainer, none given, called in /home/www/demo/system/modules/core/controllers/BackendHelp.php on line 127 and defined in system/cache/dca/tl_calendar_events.php on line 807

**Comment by leofeyer** [comment]
Behoben in c453f7a9b7bf2593f2f26f1e376d21a82216618f.
