### ISSUE TITLE
Contao 4: Versionsnummernanzeige fehlerhaft

### ISSUE THREAD

**Issue by nistech** [contao/core#8068]
Ich habe Contao 4.0.3 installiert und dennoch zeigt das Backend die Version 4.0.2 an. Weiterhin zeigt es an, dass Contao aktuell ist.

**Comment by bytehead** [comment]
Der Bugtracker für Contao 4 ist hier: https://github.com/contao/core-bundle/issues.

**Comment by nistech** [comment]
Danke. Es ist nicht einfach hier durchzusehen. Aber geht wahrscheinlich nur mir so...;)
