### ISSUE TITLE
Input::findPost FORM_SUBMIT

### ISSUE THREAD

**Issue by baumannsven** [contao/core#8070]
Hier wird der Key FORM_SUBMIT unterschiedlich zurück gegeben.
Ist das so gewollt oder ein Bug?

https://github.com/contao/core/blob/master/system/modules/core/library/Contao/Input.php#L807

https://github.com/contao/core/blob/master/system/modules/core/library/Contao/Input.php#L812

**Comment by leofeyer** [comment]
Was genau meinst Du?

**Comment by baumannsven** [comment]
Bei der Methode findPost bekomme ich für den Key FORM_SUBMIT zwei unterschiedliche Werte zurück. Wenn die Methode den Wert aus dem Post holt, dann kommt auto_form_* zurück. Aber wenn es aus der Session kommt dann ohne auto_ . Dies sieht man ja bei dem reg_replace. Warum ist das so?

**Comment by leofeyer** [comment]
Das `auto_`-Prefix zeigt an, dass das Formular durch Ändern des Feldwertes automatisch abgeschickt wurde. Dieser Fall kann niemals eintreten, wenn der Wert aus der Session geladen wird, daher wird das Prefix in diesem Fall entfernt.
