### ISSUE TITLE
Umwandlung von Datum Format gibt es keine 24h zurück

### ISSUE THREAD

**Issue by baumannsven** [contao/core#8071]
Bei Date::getInputFormat, wenn ich hier ein Format übergebe bsp. "H:i".
Dann bekomme ich nicht das gewünschte 24h Zeitformat zurück, das eigentlich
das "H" aussagt. Denn es kommt anstatt 'HH' dies 'hh' zurück.

Zeitformate für PHP:
http://php.net/manual/de/function.date.php

Zeitformate bsp. Javascript (für dies ich diese Methode benutze):
http://www.ecma-international.org/ecma-262/5.1/#sec-15.9.1.15

https://github.com/contao/core/blob/master/system/modules/core/library/Contao/Date.php#L293

**Comment by leofeyer** [comment]
Die aktuelle Umwandlung ist korrekt gemäß [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601).

**Comment by baumannsven** [comment]
@leofeyer kannst du mir bitte beantworten warum ich dies dann machen muss?
https://github.com/ContaoBlackForest/contao-bootstrap-form-datetimepicker/blob/master/src/CalendarField.php#L229

**Comment by leofeyer** [comment]
Du verwechselst hier die Funktionen `getDateFormat()` und `getInputFormat()`. Letztere ist dafür gedacht, dem Benutzer das Format anzuzeigen, in dem er das Datum eingeben muss. Die PHP-Funktion `date()` kann damit nichts anfangen.
