### ISSUE TITLE
dateAdded for all entities

### ISSUE THREAD

**Issue by Defcon0** [contao/core#8073]
Recently we had been asked to give some statistics for a contao installation. The customer wanted to know how many news have been added in a certain time interval. In this case the field "date" was ok although it's not quite the same. I rather looked for dateAdded like in the member entity.

Would it be a large amount of work to integrate such a dateAdded field in all contao entities (like tstamp also is)?

**Comment by leofeyer** [comment]
I'm closing this ticket due to lack of interest.
