### ISSUE TITLE
insert_form does not send form

### ISSUE THREAD

**Issue by switch7x** [contao/core#8074]
When using {{insert_form::XX}} to include a form in one's page, it does not get process correctly when sending.

**Comment by aschempp** [comment]
What happens instead?

**Comment by switch7x** [comment]
The page just reloads, while a redirect page has been set in the form configuration. I tried this with several versions of contao. Also when you have the "efg" module installed and "save form data" is set, it wil not save the submitted form to you're database.

**Comment by leofeyer** [comment]
How do I reproduce this in the online demo?
