### ISSUE TITLE
calendar: SQL-Default for field source

### ISSUE THREAD

**Issue by jc97** [contao/core#8075]
Hallo,

I think, I found a bug in the dca tl_calendar_events:

``` PHP
'source' => array
        (
            ...
            'default'                 => 'default',
            ...
            'sql'                     => "varchar(32) NOT NULL default ''"
        ),
```

Users, who updated from lower Versions, will often find an empty String in the field "source" in there Database. In this case the module ModuleEventReader dosen't get the right value for "hasDetails", because it just checks $objEvent->source != 'default' so '' is not equal to 'default'. I think, the SQL-statement for "source" should be "varchar(32) NOT NULL default 'default'"

EDIT: To fix this, adding a procedure in "runonce" would be more helpful.

**Comment by fritzmg** [comment]
Hm, there are quite a lot of DCAs in the core with field definitions whose SQL defaults differ from the DCA defaults. But you are right, this should be covered in the update procedure.

**Comment by leofeyer** [comment]
@contao/developers /cc

**Comment by aschempp** [comment]
This is a common issue. I'm always uncertain wether to add a default value in the database or in the DCA. I don't know what was the reason to add such a feature to the DCA in the first place?

However, there are two "simple" solutions:
 1. Add an update routine that sets everything to `default`. That's what we usually do when new fields need to be initialized.
 2. Check for «is empty or is `default`»

**Comment by leofeyer** [comment]
Any reason why we should not set the default values in the DCA **and** in the database?

**Comment by aschempp** [comment]
It's kind of senseless to define both… we could do it in this case, but I would not suggest to do it everywhere.

**Comment by leofeyer** [comment]
It is not senseless. It is consistent :)

**Comment by aschempp** [comment]
To me it is senseless. The record will be created in the DB with the default values and then pre-filled with the default values…

**Comment by aschempp** [comment]
Additionally it's a duplication of configuration, meaning we potentially change one variable and forget about the other…

**Comment by leofeyer** [comment]
We might be able to drop the PHP routines if we set the default in the database?

**Comment by aschempp** [comment]
yeah. But I think there still is a reason to support both, because the records might not always be created by `DC_Table` and in that case I might now want the default value. But when the SQL statement in the DCA contains a default value we should remove the `default` setting in the DCA.

**Comment by leofeyer** [comment]
Sounds like a plan. We might need to adjust the "reset to default upon copy" routines then.

**Comment by jc97** [comment]
close and open was a "missclick"

I suggest to set the default only in the default-field in the dca not in sql. Additional update and copy routines should insert missing values based on default.

**Comment by leofeyer** [comment]
> I suggest to set the default only in the default-field in the dca not in sql

You suggested the opposite when you opened the ticket?

**Comment by jc97** [comment]
I know, but I think this way is a bit better. 
We should definitly keep the default-field, because the backend.should be able to prefill forms.

**Comment by aschempp** [comment]
> I suggest to set the default only in the default-field in the dca not in sql. Additional update and copy routines should insert missing values based on default.

That's a bad idea. We don't know what's an invalid value, so we don't know when to set it to the default.

**Comment by ausi** [comment]
IMO the two defaults are different. The DCA default could be set to something dynamic like `BackendUser::getInstance()->foo` or something that depends on the parent dataset.

I think we should change the core DCA configurations to use the SQL default instead of the DCA default if possible, e.g. in [tl_content.php:173](https://github.com/contao/core/blob/9455d0232edcf39e9bee9a86d4643bda02f87bb1/system/modules/core/dca/tl_content.php#L173).

**Comment by leofeyer** [comment]
As discussed in Mumble on Januar 26th, @ausi is going to create a pull request.

**Comment by ausi** [comment]
Pull request: contao/contao#340

**Comment by leofeyer** [comment]
Thank you @ausi.
