### ISSUE TITLE
\Widget::getEmptyValueByFieldType -> returns 0 for an empty enddate

### ISSUE THREAD

**Issue by Defcon0** [contao/core#8079]
We just made use of the method getEmptyValueByFieldType in the Widget class. It returns 0 if the sql type is an integer which seems to be right. But for example endDate in tl_calendar_events is an integer field, but the default value declared in the sql string is NULL, not 0. This leads to 0 being saved to database which for its part leads to 01.01.1970 being rendered which would cause misunterstandings.

Wouldn't it be better to have getEmptyValueByFieldType return the value in the sql string, e.g.:

int(10) unsigned NULL -> NULL
char(1) NOT NULL default '' -> ''

If none is defined, the method should work as it does at the moment.

**Comment by leofeyer** [comment]
You need to specify the `nullIfEmpty` option in this case.
