### ISSUE TITLE
Fehler: neue Anweisung für Inhalte in event_full funktioniert nicht

### ISSUE THREAD

**Issue by jenda77** [contao/core#8081]
Ich habe neulich eine alte Contao-Installation auf die neuste Version aktualisiert (3.5.4). Dabei wurden in der Eventsvollansicht plötzlich keine Inhaltselemente gezeigt, obwohl die da waren und die Datenbankaktualisierungen immer richtig durchgeführt wurden. Erst, als ich die neue Anweisung in der event_full-Template durch die alte ersetzt habe, wurden die Inhaltselemente gezeigt. 

Es geht um diesen Code in der event_full-Template - das ist die alte Version, die ich benutzt habe und die funktioniert, wogegen die neue nicht funktionierte. 

```
<?php if ($this->details): ?>
    <?php echo $this->details; ?>
  <?php else: ?>
    <div class="ce_text block">
      <?php echo $this->teaser; ?>
    </div>
  <?php endif; ?>
```

**Comment by leofeyer** [comment]
Wie lässt sich das in der Onlinedemo reproduzieren?

**Comment by asaage** [comment]
siehe hier: #8011

**Comment by jenda77** [comment]
Modul -> Eventleser und dann die unveränderte event_full.html5-Template zuweisen bzw. zugewiesen lassen.

**Comment by baumannsven** [comment]
@jenda77 
Wenn der neu nicht geht, könnte es vielleicht an der PHP Version liegen die du einsetzt.
Das hat sich bei der 3.5 geändert.

alt:
```php
<?php echo $this->details; ?>
```
neu:
```php
<? $this->details; ?>
```

**Comment by jenda77** [comment]
nein, ich verwende die PHP 5.5. Daran liegt es nicht. Wie schon @asaage darauf hinweist, ist die If-Abfrage falsch.

**Comment by Aybee** [comment]
Aber dann dürften ja in der Online-Demo hier http://demo.contao.org/en/event-detail/contao-north-day.html die Inhaltselemente nicht sichtbar sein. Aber das ist doch das Inhaltselement. Contao 3.5.4, event_full.

> @baumannsven neu:
<? $this->details; ?>

```php
<?= $this->details ?>
```

**Comment by BugBuster1701** [comment]
Er meint das ``hasDetails``, das wurde über #8011 in dem ModuleEventReader eingebaut.
@jenda77 Sicher dass das Update vollständig ist? Mal mit Contao Check geprüft?

**Comment by Aybee** [comment]
Ja, ich sah nur, dass das Gleichheitszeichen fehlte.

**Comment by jenda77** [comment]
Ja, die Installation scheint in Ordnung  zu sein. Es wird kein Fehler gemeldet. 


Jan Kout

--------------------------
DE: +49 176 45799488
CZ: +420 728 781 067

www.jankout.eu
koutjan@gmail.com

21. 10. 2015 v 17:06, Glen Langer <notifications@github.com>:

Er meint das hasDetails, das wurde über #8011 in dem ModuleEventReader eingebaut.
@jenda77 Sicher dass das Update vollständig ist? Mal mit Contao Check geprüft?

**Comment by SpeGal** [comment]
Ich hatte diesen Fehler in der vorherigen Version manuell im Template geändert und gehofft, dass durch das Update das dann automatisch wieder richtig ist. Allerdings habe ich jetzt gesehen, dass durch das 3.5.4 wieder "hasDetails" in der Zeile steht und wieder die Inhalte nicht angezeigt werden. Warum wurde das im neuen Update noch nicht behoben?
Für jetzt behelfe ich mich nochmal mit der Notlösung ->details

**Comment by BugBuster1701** [comment]
Weil das hasDetails erst mit der 3.5.4 kam? Das wurde doch wegen des Bugs #8011 erst eingebaut.
Wenn das bei dir immer noch nicht gefüllt wird, muss dafür die Ursache gesucht werden.

**Comment by SpeGal** [comment]
Nein, das "hasDetails" kam mit der 3.5.3 und musste vorübergehend mit "details" manuell ersetzt werden. Mit der 3.5.4 hätte entweder wieder standardmäßig "details" stehen oder das "hasDetails" zum Laufen gebracht werden müssen. Leider scheint sich da aber bisher noch gar nichts getan zu haben :(

Bei der #8011 siehst du ja auch, dass es noch keinen Fix gab ...

**Comment by BugBuster1701** [comment]
Doch: https://github.com/contao/core/blob/3.5.4/system/modules/calendar/modules/ModuleEventReader.php#L239
Durch den Commit: https://github.com/contao/core/commit/d80a6fdbb67c0591494a623de58ca2554890ef8b
Der wurde dann in Contao 4 noch portiert.

**Comment by SpeGal** [comment]
Die Zeile steht zwar in meiner ModuleEventReader.php aber es funktioniert trotzdem nicht!
Nur wenn ich im event_full wieder "details" schreibe geht es ... Der Fehler wurde also noch nicht behoben.

**Comment by BugBuster1701** [comment]
@Aybee meinte ja es ginge in der Demo. Was ist anders bei dir? Kannst du das nachvollziehen?

**Comment by SpeGal** [comment]
Der Unterschied liegt am wiederholenden Event. Alle wiederkehrenden Events werden richtig angezeigt, nicht wiederkehrende Events funktionieren mit der neuen Lösung immer noch nicht! Auch nicht in der Demo.

**Comment by leofeyer** [comment]
@SpeGal Wie genau kann ich das in der Onlinedemo reproduzieren?

**Comment by fritzmg** [comment]
> Auch nicht in der Demo.

They do seem to work in the Demo though.
