### ISSUE TITLE
module type 'Listing' does not respect access protection setting

### ISSUE THREAD

**Issue by trent2** [contao/core#8082]
Steps to reproduce in the demo:
- set 'Access protection' in the 'Applications - Listing' module to allow only "general Members" to view this module
- go to the FE page (applications.html) in the demo - the module still gets displayed.

**Comment by aschempp** [comment]
Probably because it’s included as a content element and the content element permissions are not set?

**Comment by trent2** [comment]
That's the case, correctly. If this is the expected behaviour please mark this as *invalid* and I rest my case. I didn't know this and this behaviour was kind of unexpected. Sorry.
