### ISSUE TITLE
[Feature] Maintenance mode hint before logout

### ISSUE THREAD

**Issue by Zeromax** [contao/core#8083]
I think it would be a cool option to add a alert to the logout button in the back end, if the maintenance mode is active. It is a hint for the admin that the page is unreachable.

It is a small usabilty improvement, but I think it will help lots of Admins to not leave there page in maintenance mode over night by accident ;)

**Comment by Toflar** [comment]
When the maintenance mode is on there's a huge red bar on the top of your back end. If you don't see that bar, you should maybe visit an eye shop, don't you? :D Also, most of the people close the window without logging out anyway so I don't really see any improvement here to be quite honest.

**Comment by aschempp** [comment]
well
 1. I usually also overlook the maintenance mode
 2. but I also close the windows without clicking *Logout*

In Contao 4 this has been changed anyways, there's no red bar anymore.

**Comment by Zeromax** [comment]
OK. So there is a different workflow and we can close this here?
I'm fine with it cause it was a proposal in General and not realy for me ;)

**Comment by Tastaturberuf** [comment]
Make a copy from the backend theme and add a javascript onclick event alert when the maintenance is on. Done.

**Comment by Zeromax** [comment]
@Tastaturberuf Thanks ;) I know this already
