### ISSUE TITLE
News headline should not be encoded in insert tag

### ISSUE THREAD

**Issue by aschempp** [contao/core#8087]
https://github.com/contao/core-bundle/blob/master/src/Resources/contao/library/Contao/InsertTags.php#L579-L580

`specialchars` should only be applied to the `title` attribute, but not to the "value"

**Comment by leofeyer** [comment]
The same applies to the event tags and probably more.

**Comment by leofeyer** [comment]
Also see #2604.

**Comment by leofeyer** [comment]
Fixed in 90539dc33bbf4fc3439afd508247531e8c8cb5e5.
