### ISSUE TITLE
Bug in Date class - non static method resolveCustomModifiers is called statically 

### ISSUE THREAD

**Issue by discordier** [contao/core#8088]
b53c69d027e67752df3b80afd9803cdbf9d31e26 introduced the non static method [`resolveCustomModifiers`](https://github.com/contao/core/blame/9455d0232edcf39e9bee9a86d4643bda02f87bb1/system/modules/core/library/Contao/Date.php#L658) but calls it statically in [line 618](https://github.com/contao/core/blame/9455d0232edcf39e9bee9a86d4643bda02f87bb1/system/modules/core/library/Contao/Date.php#L618).

This just broke our [unit tests](https://travis-ci.org/MetaModels/attribute_timestamp/jobs/88003087#L630).

Sadly there is no workaround to this bug as it is being triggered by the widget during timestamp converting.

**Comment by leofeyer** [comment]
Fixed in 0e1ea833783c8f8895b85225849289095c7b58d4.
