### ISSUE TITLE
Help docs in backend

### ISSUE THREAD

**Issue by jankout** [contao/core#8089]
I would wonder to have an access to the official help docs in Contao backend. In Typo3 is a common feature maybe Contao could inspire by them? I think it could be very helpful for all of us. :+1: 

The link of it could be placed in the header next to the user name. It should be possible to do the same things like on the current website of the help docs.

**Comment by aschempp** [comment]
Do you mean a link to the documentation homepage? Or some sort of inline docs?

**Comment by jenda77** [comment]
Yes, the link to the documentation. But the user should see it directly in the backend. That means the documentation should be showed in the backend. 

Of course it would be necessary to adjust the view of the documentation in the backend. But I think it could not be a lot of work.

**Comment by leofeyer** [comment]
This has been implemented meanwhile.
