### ISSUE TITLE
Zwei, bzw. dreispaltiges Layout defekt

### ISSUE THREAD

**Issue by Sukrams** [contao/core#8093]
Wenn ich bei Contao ein zwei- oder dreispaltiges Layout erstelle und z. B. die Navigation in die linke Spalte packe, überlappt sie den #main-Container und liegt über diesen. 

Lässt sich so auch in der Demo nachvollziehen.

**Comment by fritzmg** [comment]
Hört sich nach einem CSS Problem an und nicht nach einem Problem mit Contao. In der Demo kann ich das auch nicht nachvollziehen - wenn einfach nur eine Navigation in der linken Spalte vorhanden ist, ist alles normal: http://demo.contao.org/en/text-elements.html

**Comment by Sukrams** [comment]
Das tritt allerdings auch auf, wenn ich kein eigenes CSS benutze, sondern mit den Bordmitteln von Contao erstmal das grundlegene Layout baue.

Also bisher konnte ich z. b. folgende Schritte immer reproduzieren: Header/Footer auswählen und zwei- bzw. dreispaltiges Layout. Logo meinetwegen im Header, linke Spalte Navi und Hauptspalte Artikel.

Bei mir sieht das dann immer so aus: 
![contao](https://cloud.githubusercontent.com/assets/15678176/10992454/37181970-8466-11e5-99ba-f57bbdec5bab.png)

**Comment by fenepedia** [comment]
Wie wurde die Breite für die Seitenspalten vergeben? Das Holy-Grail-Layout funktioniert meines Wissens nur mit fixen Spaltenbreiten in px.

Die Seitenspalten dürfen nicht breiter sein als die Main-Spalte. Wenn man mit Prozent in den Seitenspalten arbeiten will, muss glaube ich das komplette Layout mit Prozent gemacht werden. Man darf also nicht % und px mischen.

http://matthewjamestaylor.com/blog/ultimate-3-column-holy-grail-pixels.htm

**Comment by Sukrams** [comment]
Achso, das wusste ich nicht. Ich hatte da keinen Wert für angegeben, weil ich das eigentlich recht flexibel haben wollte, aber mit einer festen Angabe (auch in Prozent) funktioniert es.

Eventuell wäre dann ein kleiner Hinweis sinnvoll, dass da ein Wert angegeben sein muss?

**Comment by fritzmg** [comment]
Ja, es wäre vielleicht sinnvoll die Felder `widthLeft` und `widthRight` mandatory zu machen.

**Comment by Sukrams** [comment]
Und wenn man einfach den Hinweistext entsprechend ergänzt? Dann hätte man das Problem nicht, dass die Felder unbedingt einen Wert haben müssten.
