### ISSUE TITLE
Simple tokens if, else, elseif, endif

### ISSUE THREAD

**Issue by jenda77** [contao/core#8097]
It would be great to have a support for using of simple tokens for **if**, **else**, **elseif** and **endif**. 

I would suggest to take following form: 
```
if {'value'} ... {else} ... {endif}
```

**Comment by aschempp** [comment]
Please read the manual: https://docs.contao.org/books/manual/3.5/en/04-managing-content/newsletters.html#personalized-newsletters :-)

**Comment by jenda77** [comment]
Unfortunately, it does not work with efg and custom html mail template... I have
```
{if {{form::Mailing_blanko}}=="0"}<tr><th>Mailing blanko</th><td>nein</td></tr>{else}
```

**Comment by aschempp** [comment]
That's a problem of EFG and not Contao core. Our notification center works perfectly. https://contao.org/de/erweiterungsliste/view/notification_center.de.html

**Comment by jenda77** [comment]
Ok, I let Thomas know that he should fix it. Thank you for your quick help. 

https://bitbucket.org/thk/efg/issues/97/if-anfrage-in-35
