### ISSUE TITLE
[Contao 3.5.4] Maximale Dateigröße

### ISSUE THREAD

**Issue by mathContao** [contao/core#8098]
Contao 3.5.4

Im Dateiuploader steht rechts unten 2MiB maximale Dateigröße. In den Systemeinstellungen Ist bei "Maximale Upload-Dateigröße" der Wert "2048000" eingetragen (= 2MiB).

Apache-Server/PHP.ini "upload_max_filesize" ist auf 8M gesetzt

Die hochgeladene Datei (PDF-Datei) ist 1,33MB groß. Und trotzdem wird der Upload abgebrochen. 

![unbenannt](https://cloud.githubusercontent.com/assets/1645099/11017890/8d7740ee-85af-11e5-933e-04ce93a42e96.JPG)

Das ist bestimmt nicht so gewollt, oder?

**Comment by BugBuster1701** [comment]
Was ist bei dir gesetzt in der php.ini bei post_max_size ?

**Comment by mathContao** [comment]
ebenfalls 8M

**Comment by asaage** [comment]
Ich habe ein paar test's gemacht
php.ini
```
max_file_uploads 20
post_max_size	 8M
upload_max_filesize 2M
```
contao setting
```
Maximale Upload-Dateigröße* 129536000
```
php.ini
```
max_file_uploads 20
post_max_size	 120M
upload_max_filesize 120M
```
contao setting
```
Maximale Upload-Dateigröße* 2000000
```
Ergebnis: im Upload-Dialog wird der kleinere Wert von upload_max_filesize bzw. Maximale Upload-Dateigröße angezeigt. Das macht Sinn und ist richtig so - wenngleich ein Hinweis in den Einstellungen wünschenswert wäre (dass man damit die php Limitierung nicht erweitern kann).
Simultane Datei-Uploads sind bei mir immer 2 - egal ob ich in den Contaoeinstellungen 1 oder 8 angebe. Auch Bilder mit mehr als den angegebenen maximalen Pixeln wurden ohne zu zucken hochgeladen.
Das Problem von @mathContao konnte ich jedenfalls nicht reproduzieren.

**Comment by mathContao** [comment]
Meine Tests:
(jeweils per phpinfo() ermittelt)

Server (Hoster: Alfahosting):
PHP 5.6.6
post_max_size = 8M
upload_max_filesize = 8M


und Lokal (Contao2Go Version 3.0)
PHP 5.6.9
post_max_size = 256M
upload_max_filesize = 256M


Contao-Einstellungen:
Maximale Upload-Dateigröße = 2099000 (Upload funktioniert!)
Maximale Upload-Dateigröße = 2095000 (Upload funktioniert nicht!)

Leider bekomm ich die PDF-Datei (1,3MB) hier nicht hochgeladen (Meldung: "Unfortunately, we don’t support that file type. Try again with a PNG, GIF, JPG, DOCX, PPTX, XLSX, TXT, or PDF. ").
Hier zum Download: http://workupload.com/file/An4oLFdy

**Comment by leofeyer** [comment]
Besteht das Problem noch in Contao 3.5?

**Comment by Funbug** [comment]
Ich kidnappe mal das Ticket mit dem Wunsch Dateigrößenangabe in MB machen zu können. Mal ehrlich: wie oft habt ihr schon googlen müssen, wieviel kB 10, 20 oder 30 MB sind ... und überall sonst ist die Ausgabe ja auch in MB und nicht in kB (siehe oben).

**Comment by fritzmg** [comment]
Die Angabe ist in Byte, nicht KiB ;). Darüberhinaus muss man das ja nicht Googlen, einen Wert ein oder mehrmals mit 1024 multiplizieren (oder 1000, je nachdem was du haben möchtest) kann ja auch der Taschenrechner deines Betriebssystems. 

Andererseits kann es sicher nicht schaden, wenn man, genau so wie in der PHP Konfiguration, Angaben wie zB `128M` (= 134217728 Bytes) machen könnte.

**Comment by Funbug** [comment]
Schnell: wieviel Byte sind 15 MB? -> Unnötiger Aufwand.

Google hat einen einfachen Umrechner. Das geht für mich schneller als mit dem Taschenrechner. Es hält dich anschließend ja niemand auf, einen byte-genauen Wert in MB mit Nachkommastellen einzugeben. 

Ich spreche nur von der **Anzeige**, nicht davon wie der Wert gespeichert wird. Ich bin ziemlich sicher, dass die Angabe in MB deutlich einfacher wäre als in Byte, einfach weil es gebräuchlicher ist.

**Comment by do-while** [comment]
So sind halt die geltenden Normen, wenn man binäre Skalierung anwendet.
kB, MB, usw. sind gebräuchlicher, aber falsch.
[https://de.wikipedia.org/wiki/Byte]

**Comment by leofeyer** [comment]
Behoben in c885ddfa055acc389be114431532c9f095203b30.

**Comment by fritzmg** [comment]
> Schnell: wieviel Byte sind 15 MB? -> Unnötiger Aufwand.

15 * 1024 * 1024 = 15728640 ;)

> Ich spreche nur von der Anzeige, nicht davon wie der Wert gespeichert wird. Ich bin ziemlich sicher, dass die Angabe in MB deutlich einfacher wäre als in Byte, einfach weil es gebräuchlicher ist.

Achso, ich dachte du meintest die Systemeinstellung. Die Anzeige ist doch bereits in MiB?

**Comment by leofeyer** [comment]
> Ich kidnappe mal das Ticket 

Meine Änderung bezog sich übrigens nur auf das ursprünglich beschriebene Problem. Tickets kidnappen ist generell keine gute Idee und verwirrt alle Beteiligten nur unnötig.

**Comment by Funbug** [comment]
Ja, um genau zu sein meinte ich das Eingabefeld "Maximale Upload-Dateigröße" in den Systemeinstellungen. Und hier bin ich der Überzeugung, das eine Eingabe in MB sinnvoller wäre.

Sorry Leo. Wird nicht wieder vorkommen.
