### ISSUE TITLE
ID for each form element

### ISSUE THREAD

**Issue by jenda77** [contao/core#8099]
It would be great to have the possibility to set an ID for each form element on your own like we can do it with the class now.

**Comment by Toflar** [comment]
What's your use case?

**Comment by jenda77** [comment]
When I wanted to manipulate a form element with jQuery.

**Comment by baumannsven** [comment]
@jenda77 each for element has an ID. Show in the text. (id="ctrl_ID")

**Comment by jenda77** [comment]
Yes, but I would like to set it on my own, not automatic.

**Comment by baumannsven** [comment]
I have twice ways for you:
1. You used the parseWidget HOOK
2. You used an individual template by the form field

Note this is for contao community forum

**Comment by baumannsven** [comment]
@Toflar can you close this?

**Comment by jenda77** [comment]
Thank you for your help. I though it could be more userfriendly and not so neard's way ;-)

**Comment by Toflar** [comment]
There's absolutely no need for an ID to manipulate a form element anyway. Just target it using the CSS class.

> @Toflar can you close this?

Nope :)

**Comment by jenda77** [comment]
Yes, sometimes it works sometimes it's better to use ID because It's unique. I think it could be there like by another content elements. It's just a way like that you have implemented by all of other content elements. :-)

**Comment by Toflar** [comment]
The form receives an ID as well, it is very easy to target any containing element exactly and uniquely.

**Comment by jenda77** [comment]
Yes, I know. I wont to use my own. But it´s ok when there is no will to extend it. We don´t need to discuss father. ;-)
