### ISSUE TITLE
Remove Input::stripSlashes()

### ISSUE THREAD

**Issue by leofeyer** [contao/core#8100]
It seems that `Input::stripSlashes()` can be removed, because `get_magic_quotes_gpc()` always returns `false` as of PHP 5.4.0:

> This function has been DEPRECATED as of PHP 5.4.0. Always return false.

And if `static::$blnMagicQuotes` is `false`, the method is bypassed with an early return statement, so we might as well remove the method completely.

@contao/developers Any objections? Did I miss anything?

**Comment by aschempp** [comment]
The method is public, you can't remove it.

**Comment by ausi** [comment]
IMO it should be marked `@deprecated` and always `return $varValue`.

**Comment by Toflar** [comment]
I second @ausi.

**Comment by leofeyer** [comment]
But you agree that it does not do anything anymore, don't you?

**Comment by Toflar** [comment]
Yes.

**Comment by leofeyer** [comment]
Changed in 413ce52e40a0bb002c7d4ab12b2960c9198ac9b3.
