### ISSUE TITLE
[3.5.4] Dateiverwaltung Alle umschalten 

### ISSUE THREAD

**Issue by Mynyx** [contao/core#8105]
In der Dateiverwaltung wird von der Funktion "Alle umschalten" nicht der gesamte Verzeichnisbaum aufgeklappt.

In demo.contao.org bleibt beispielsweise der Ordner /contaodemo/media geschlossen.

**Comment by leofeyer** [comment]
Das scheint ein Problem in der Onlinedemo zu sein. Hier lokal tritt der Fehler nicht auf.

**Comment by Mynyx** [comment]
Nein, der Fehler ist mir zuerst bei einer lokalen Installation aufgefallen.

**Comment by leofeyer** [comment]
Ich kann es wie gesagt hier nicht reproduzieren.

**Comment by Mynyx** [comment]
Maßgeblich ist doch, dass der Fehler in der Online Demo reproduzierbar ist?

**Comment by leofeyer** [comment]
Naja, nicht wirklich. Wie soll ich den Fehler denn debuggen, wenn er hier gar nicht auftritt?

**Comment by Mynyx** [comment]
Hast du in deiner lokalen Installation denn die gleichen Dateien und Verzeichnisse im Ordner files wie in der Onlinedemo?

**Comment by leofeyer** [comment]
Ja.

**Comment by leofeyer** [comment]
Behoben in 0bf8301278c0d0f0ebcdd42341cb385777edf646.
