### ISSUE TITLE
$GLOBALS['TL_HOOKS']['getCountries'] in System.php don't do any thing

### ISSUE THREAD

**Issue by tsarma** [contao/core#8106]
```qoute
The getCountries hook allows to modify the system's list of countries.
```

The Hook is useless, because the returned array is same as before calling HOOK function.

**Comment by bytehead** [comment]
I don't see any reason why [this](https://github.com/contao/docs/blob/master/api/extensions/hooks/getCountries.md) not should work.

See example 2.

**Comment by aschempp** [comment]
Here's the good looking version :sunglasses: 
https://docs.contao.org/books/api/extensions/hooks/getCountries.html

**Comment by tsarma** [comment]
I wrote above, after trying links provided above. Have you tired it?
For example there is not parameter passed by reference at all in HOOK point.

```php
		// HOOK: add custom logic
		if (isset($GLOBALS['TL_HOOKS']['getCountries']) && is_array($GLOBALS['TL_HOOKS']['getCountries']))
		{
			foreach ($GLOBALS['TL_HOOKS']['getCountries'] as $callback)
			{
				static::importStatic($callback[0])->$callback[1]($return, $countries);
			}
		}
```

**Comment by baumannsven** [comment]
You must reference  the first argument by your method

```php

public static function myGetCountries (&$return, $countries)
{

} 
```

**Comment by tsarma** [comment]
Thank you @baumannsven that was it. Thank you all

**Comment by bytehead** [comment]
@tsarma You could open a issue on [contao/docs](https://github.com/contao/docs/issues) regarding to this issue, otherwise the documentation will stay wrong.
