### ISSUE TITLE
Alias-Generierung von Hebräischen Zeichen

### ISSUE THREAD

**Issue by zonky2** [contao/core#8107]
Hallo,

ich habe im Seitennamen hebräische Zeichen - wenn ich den Alias generieren lasse, werden die Buchstaben in "ASCII-7-Buchstaben" umgewandelt - prinzipiell sollte das aber funktionieren siehe Wiki
https://yi.wikipedia.org/wiki/%D7%95%D7%95%D7%A2%D7%91

aus דף הבית wird df-hbyt.html

**Comment by leofeyer** [comment]
Kann ich nicht reproduzieren.

![](https://cloud.githubusercontent.com/assets/1192057/11186190/d75e06d4-8c80-11e5-86ab-1c586caeb1f0.png)

Die Seite lässt sich dann auch unter `http://demo.contao.org/en/ﬢﬣ.html` aufrufen.

**Comment by xantippe** [comment]
**wenn ich den Alias generieren lasse**

hast Du hebräische Zeichen als Seitenname eingegeben und hast den Alias generiert?

**Comment by leofeyer** [comment]
Das kann sowieso nicht funktionieren, weil die automatisch erstellten Aliase immer "romanisiert" werden. Dazu müsstest Du den `save_callback` überschreiben.

**Comment by xantippe** [comment]
o.k. :-(

**Comment by xantippe** [comment]
... aber wenn ein hebräischer Alias möglich ist (manuell) warum nicht auch beim Generieren!?!

**Comment by leofeyer** [comment]
Tja, gute Frage eigentlich. @contao/developers /cc

**Comment by xantippe** [comment]
habe gerade versucht "דף הבית" als Alias einzutragen - kommt ```Please enter only alphanumeric characters and the following```

**Comment by leofeyer** [comment]
Da ist vermutlich ein Steuerzeichen in dem String.

**Comment by xantippe** [comment]
Anmerkung:
ich habe zu dem Thema etwas rumgesucht... bei Joomla gibt/gab es ähnliche Anfragen - dort scheint es eine Einstellung zu geben "...```Settings -> General -> SEO``` and click ```YES``` to allow unicode aliases."

**Comment by xantippe** [comment]
danke fürs wieder-öffnen..

**Comment by leofeyer** [comment]
Wie auf Mumble am 17. Dezember besprochen, wollen wir eine Einstellung hinzufügen, mit der man UTF8-Zeichen in Aliasen aktivieren kann. Allerdings sind wir uns bezüglich der Implementierung nicht sicher, da @aschempp und @discordier das Ganze gerne als Service hätten, der zudem noch [diese Library](https://github.com/cocur/slugify) nutzt. Ich würde nur die Methode `StringUtil::generateAlias()` anpassen :)

**Comment by discordier** [comment]
Nicht zwingend diese library, aber etwas aehnlich konfigurierbares (oder noch besser konfigurierbarer) nur eben zwingend als service den man per DI konfigurieren kann.

**Comment by aschempp** [comment]
Ich habe mir nochmals Gedanken hierzu gemacht. Eigentlich ist ein romanize in den meisten Fällen sinnvoll. Aber es ist falsch, dann die hebräischen Zeichen zu löschen. ä sollte schon zu ae werden, aber die hebräischen und chinesischen Zeichen sollten einfach bleiben.

**Comment by xantippe** [comment]
...dann sollte es auf alle Fälle eine Eingriffsmöglichkeit geben (Hook/Event), um das nach eigenen Vorgaben umstellen zu können

**Comment by leofeyer** [comment]
> ä sollte schon zu ae werden, aber die hebräischen und chinesischen Zeichen sollten einfach bleiben.

Das wäre ja total inkonsistent. Was ist, wenn ich `ä` statt `ae` haben möchte? Wenn sollten schon alle UTF-8-Zeichen bestehen bleiben :)

**Comment by Xendiadyon** [comment]
entschudigt bitte, wenn ich das hier noch einmal aufwärme.
Gibt es nun eine Möglichkeit (Hook o.ä.) wie ich bei der Generierung des Seitenalias' ä -> ae statt a erzwingen kann? Oder muss ich dazu (nicht updatesicher?) in die helper/utf8_lookup.php eingreifen?

**Comment by fritzmg** [comment]
Ich denke das array `$UTF8_LOOKUP_TABLE` kannst du update sicher bspw. in der `initconfig.php` ändern.

**Comment by Xendiadyon** [comment]
Vielen Dank für die rasche Antwort. Wir verwenden Contao 4.3. Kann es sein, dass hier die UTF8_LOOKUP_TABLE nicht mehr existiert, sondern über patchwork/utf8/bootup gemacht wird? Das verkompliziert alles etwas, oder?

**Comment by aschempp** [comment]
Eine Möglichkeit wäre ein `selocale()` auf Deutsch in der initialize.php. Allerdings solltest du vorher das Handbuch von `setlocale` lesen und prüfen ob dass auf deinem Server funktioniert.

**Comment by fritzmg** [comment]
> Vielen Dank für die rasche Antwort. Wir verwenden Contao 4.3. Kann es sein, dass hier die UTF8_LOOKUP_TABLE nicht mehr existiert, sondern über patchwork/utf8/bootup gemacht wird? Das verkompliziert alles etwas, oder?
> 
> Da müsste man doch idealerweise in der config.yml eine Einstellungsmöglichkeit haben?

Siehe dazu auch https://github.com/contao/core-bundle/issues/560

**Comment by Xendiadyon** [comment]
Vielen Dank an euch beide.
setlocale() funktioniert perfekt und ist natürlich die ideale Lösung.

Ich wünschte, wir hätten bald mal ein Manual zu Contao 4 :)

**Comment by ausi** [comment]
Auch `setlocale(LC_CTYPE, 'de_DE')` könnte zu Problemen führen. Am besten man setzt es nur direkt vor der Alias-Gererierung und setzt es danach wieder zurück.

```php
$localeBefore = setlocale(LC_CTYPE, 0);
setlocale(LC_CTYPE, 'de_DE');
// Alias generierung ...
setlocale(LC_CTYPE, $localeBefore);
```

**Comment by Xendiadyon** [comment]
Ich muss hier leider noch einmal einklinken.

Seit Contao 4.4 funktioniert das setlocale nicht mehr und die aliase werden mit Umlauten generiert:
![image](https://user-images.githubusercontent.com/2657385/28107644-eac0222c-66e8-11e7-955c-60f272227f31.png)

Wie gehen wir hier weiter vor?

**Comment by leofeyer** [comment]
Das ist korrekt, Contao unterstützt Unicode-URLs ab Version 4.4.

**Comment by Xendiadyon** [comment]
okay. Ist also ein Feature und soll so :)
https://github.com/contao/core-bundle/issues/954
