### ISSUE TITLE
Alternativtext und Bildunterschrift werden nicht gespeichert, wenn Bild mit "wichtigem Teil" verwendet wird

### ISSUE THREAD

**Issue by derastronaut** [contao/core#8108]
Anleitung zur Reproduktion

1. Lade zwei Bilder in die Dateiverwaltung.
2. Eines der Bilder bearbeitest du, in dem du eine Auswahl für den wichtigen Teil ziehst und speicherst.
3. Du gehst im Menü auf Nachrichten, klickst bei einem Archiv auf bearbeiten, damit du eine neue News erstellen kannst (Archiv muss natürlich angelegt sein bzw. werden).
4. Nachdem du auf neuen Artikel geklickt hast, gibst du einen Titel ein und machst ein Häkchen bei Ein Bild hinzufügen.
5. Du wählst das Bild aus der Dateiverwaltung aus, bei dem du die Auswahl gezogen hast, gibst einen alternativen Text und eine Bildunterschrift ein. Du kannst meinetwegen auch die anderen Felder ausfüllen, aber die beiden genannten sind relevant.
6. Klick auf speichern!

Der alternative Text und die Bildunterschrift sollten NICHT übernommen werden und die Felder leer sein.

Da das Bild jetzt in der Datenbank gespeichert ist, können ALT und BU noch mal eingegeben werden und ein erneutes Speichern speichert dann auch die beiden Felder.

Nimmt man bei der Anleitung stattdessen das unbearbeitete Bild, werden ALT und BU auf Anhieb gespeichert.

Getestet in drei Contao-Installationen (3.5.4), eine davon eigens für diesen Test frisch angelegt.

**Comment by leofeyer** [comment]
Behoben in 00704326082e80de06dc5a8000981f5ff77bb8e6.
