### ISSUE TITLE
useAutoItem leads to recursive nesting when event list and news reader are used on the same page

### ISSUE THREAD

**Issue by sylverestoermann** [contao/core#8109]
**Scenario:**
On a page with a news listing, a link to single news display leads to e.g. /news/mynewselement.html
The page layout includes various modules, amongst others an event listing of upcoming events ("Next 5 events"), displayed in the right column
In \Contao\PageRegular->generate() all modules are loaded in a particular order. This way, my right column module event listing leads to loading of \Contao\ModuleEventList and its method generate(). Now, in this particular setting, the following if-statement is true (but shouldn't):

```php
if ($this->cal_readerModule > 0  && (isset($_GET['events']) || (\Config::get('useAutoItem') && isset($_GET['auto_item']))))
```

isset($_GET['events']) is false, but \Config::get('useAutoItem') and isset($_GET['auto_item']) are both true, thus making the parenthesis true. Thus loads the event reader ($this->cal_readerModule) and now Contao searches for an event "mynewselement" ($_GET['auto_item']). However, it doesn't find it, so issuing a 404 is in order. This in turn leads to loading of a regular page as well, which means the modules of the page layout are loaded, so we land again at \Contao\ModuleEventList->generate() and its 
problematic if-statement. This goes on and on as we effectively have an infinite loop until PHP times out or Xdebug's maximum nesting level is reached.

**Workaround:**
Disable the event listing module in the right column. If not feasible, at least create a duplicated page layout without the event listing module in the right column and set this layout as page layout on the news reader page.

I don't have an elegant solution on how to improve the if statement without possibly breaking existing features.

(Problem discovered on Contao 3.5.2; persists with Contao 3.5.4; did not occur with Contao 3.1.1)

**Comment by leofeyer** [comment]
The problem only occurs, because you have added an event **reader** module to your event **list**, right? You cannot have to **reader** modules on the same page; but you can have to **list** modules.

**Comment by sylverestoermann** [comment]
No, the setup is like this:

Page layout contains 1 **event list** and a mini-calendar in the *right column* ("Upcoming events").
![page layout](https://cloud.githubusercontent.com/assets/2239635/11207438/7f8cd968-8d15-11e5-8e07-5590248c6d9d.png)

I have a page (/news.html) where the **article** displayed in the *main column* contains a **news list** module. News elements are linked to the **news reader** which is to be found on another page (/news-items/ALIAS.html; useAutoItem is activated, of course, cf. subject of issue). When that page holding the **news reader** is loaded, Contao hangs while loading the **event list** in the *right column*, as the code of \Contao\**ModuleEventlist** (!) contains an if-statement, that causes an **event reader** to be loaded. This **event reader** is loaded by code, it's not defined anywhere on the page or in the page layout.

[Code block](https://github.com/contao/core/blob/master/system/modules/calendar/modules/ModuleEventlist.php#L65):
```php
// Show the event reader if an item has been selected
if ($this->cal_readerModule > 0  && (isset($_GET['events']) || (\Config::get('useAutoItem') && isset($_GET['auto_item']))))
{
    return $this->getFrontendModule($this->cal_readerModule, $this->strColumn);
}
```

This is a feature, as the event list assumes that an item has been selected due to the fact that $_GET['auto_item'] is set. Which is of course correct as it is supposed to be used by the **news reader**.

**Comment by leofeyer** [comment]
But the code is only executed if `$this->cal_readerModule > 0`, which means your calendar list module must have an event reader associated.

**Comment by sylverestoermann** [comment]
OK, yes, indeed it does. And as event categories define where to forward to, the reader associated with the event list is not necessary. Thank you!
