### ISSUE TITLE
ModuleRegistration ignores DCA encrypt

### ISSUE THREAD

**Issue by t-me** [contao/core#8110]
Hello

I'm running Version 3.5.4 and on registration the DCA is not encrypting.

'encrypt'=>true,

It is only on front-end registration not on back-end.

**Comment by leofeyer** [comment]
Where did you add the `encrypt` option?

**Comment by t-me** [comment]
I have made a module and followd this manual for extending the profile 
https://docs.contao.org/books/cookbook/customizing-contao/adding-custom-fields.html

This is my field meta data :

    $GLOBALS['TL_DCA']['tl_member']['fields']['bsn_nummer'] = array
    (
        'label'     => &$GLOBALS['TL_LANG']['tl_member']['bsn_nummer'],
        'exclude'   => true,
        'inputType' => 'text',
        'eval'      => array('mandatory'=>true, 'unique'=>true, 'rgxp'=>'bsn', 'encrypt'=>true, 'minlength'=>9, 'maxlength'=>9, 'feEditable'=>true, 'feViewable'=>true, 'feGroup'=>'personal', 'tl_class'=>'w50'),
        'sql'       => "varchar(255) NOT NULL default ''"
    );

**Comment by leofeyer** [comment]
Fixed in ba67ef7c0412014b25b9b1581d13d100bd57826d.
