### ISSUE TITLE
[3.5.4] Minify markup broken

### ISSUE THREAD

**Issue by Tastaturberuf** [contao/core#8113]
It seems the minify markup option is broken. see online demo.

**Comment by leofeyer** [comment]
It does not look broken in the online demo. What's bothering you?

**Comment by Tastaturberuf** [comment]
Because it is only indented not minified.
![minify](https://cloud.githubusercontent.com/assets/1027521/11248970/68cb530c-8e24-11e5-9792-a2203bff11be.PNG)

**Comment by Tastaturberuf** [comment]
In 3.2 it looks so

![minify_3 2](https://cloud.githubusercontent.com/assets/1027521/11249314/62c93e86-8e26-11e5-821b-a3365c0f1bd1.PNG)

**Comment by fenepedia** [comment]
Kann ich bestätigen, ist bei meiner Installation auch so.

**Comment by dmolineus** [comment]
Guess it's related to https://github.com/contao/core/issues/7734

**Comment by leofeyer** [comment]
See #7734.

**Comment by fenepedia** [comment]
Thx
