### ISSUE TITLE
Geschütze Seiten - Chrome

### ISSUE THREAD

**Issue by JCreeper** [contao/core#8114]
Ich habe einen Frontend Login und dahinter verbergen sich einige geschütze Seiten. Nach dem Login bekomme ich dann auf den jeweiligen Seiten die Meldung "Zugriff verweigert". Das allerdings nur im Chrome (auch im Inkognito Modus).
Im Safari und Firefox klappt alles fehlerfrei.

Weiss jemand woran das liegen kann? Auf dem Rechner eines Freundes klappt es im Chrome.

**Comment by leofeyer** [comment]
Das Ticket-System ist für das Melden von Fehlern gedacht, die sich überall (idealerweise auch in der Onlinedemo) reproduzieren lassen. Deine Anfrage ist im [Forum](https://community.contao.org/de/) besser aufgehoben.
