### ISSUE TITLE
RSS Newsfeed Bilder-Enclosures mit falscher URL

### ISSUE THREAD

**Issue by wlma** [contao/core#8116]
Habe das Problem das die Basis-URL in den Feed-Einstellungen nicht für Bilder (möglicherweise auch für andere Anhänge übernommen wird
in der Demo:
Bild bei einer Nachricht hinzufügen
im Feed als Basis-Url: https://demo.contao.org eintragen 
der erzeugte Feed generiert Item-Links mit https (so auch erwartet)
enclosure urls sind noch mit http

siehe:
[http _demo.contao.org_share_test.txt](https://github.com/contao/core/files/39061/http._demo.contao.org_share_test.txt)

**Comment by leofeyer** [comment]
Das liegt daran, dass Du die Demo über HTTP aufgerufen hast und TinyMCE deshalb die URLs in relative URLs umwandelt. Bei unterschiedlichen Protokollen sollte er das aber eigentlich nicht machen – hast Du schon bei den TinyMCE-Entwicklern nachgefragt?

**Comment by wlma** [comment]
Hallo Leo, der TinyMCE hat imho doch gar nichts damit zu tun? Die Parameter werden ja über  die normalen Formularfelder von Contao eimgetragen

**Comment by leofeyer** [comment]
Ich schaue es mir an.

**Comment by leofeyer** [comment]
Behoben in 9a336e95a587eb81c98ab6466b251576fb2c6a40.
