### ISSUE TITLE
Verzeichnis in Dateiverwaltung erstellen, wenn noch keine Seite angelegt wurde

### ISSUE THREAD

**Issue by mwitzmann** [contao/core#8117]
Guten Tag,

wenn man in Contao 3.5.4 nach der Installation, noch bevor man eine Seitenstruktur angelegt hat, ein Verzeichnis über die Dateiverwaltung anlegen möchte, erhält man eine Fehlermeldung.

![bildschirmfoto 2015-11-20 um 08 44 04](https://cloud.githubusercontent.com/assets/6212507/11294349/e826d9f2-8f62-11e5-9384-567f162e2df9.png)

**Comment by fenepedia** [comment]
Kann den Fehler nicht bestätigen.
Habe gerade extra noch mal frisch Contao 3.5.4 installiert und bei mir läuft alles fehlerfrei.

**Comment by leofeyer** [comment]
Das Problem wurde bereits behoben und sieht in Contao 3.5.5 so aus:

![](https://cloud.githubusercontent.com/assets/1192057/11297462/dd2a1fe4-8f78-11e5-97be-a0e74d580255.png)

**Comment by mwitzmann** [comment]
So sieht es bereits auch in Contao 3.5.4 aus, jedoch wird beim Speichern die Fehlermeldung angezeigt.

**Comment by leofeyer** [comment]
Das wiederum kann ich nicht reproduzieren.
