### ISSUE TITLE
ContentTable: default sort option does not work

### ISSUE THREAD

**Issue by fritzmg** [contao/core#8118]
### Description

The option __Sort index__ in the Content Element _Table_ does not work, it has no effect on the frontend output.

### Reproduction in COD

* create a new content element of the type _Table_
* create a table like the following:
```
1 2 3
1 3 Lorem
2 2 Ipsum
3 1 Dolor
```
* activate the following options: __Add table header__, __Sortable table__, set __Sort index__ to `1`
* check the frontend: the table will not be resorted according to the second column

### Analysis

When activating aforementioned options, [ContentTable.php](https://github.com/contao/core/blob/3.5.4/system/modules/core/elements/ContentTable.php#L56) will do the following:
```php
// Set table sort cookie
if ($this->sortable && $i == $this->sortIndex)
{
	$co = 'TS_TABLE_' . $this->id;
	$so = ($this->sortOrder == 'descending') ? 'desc' : 'asc';

	if (\Input::cookie($co) == '')
	{
		\System::setCookie($co, $i . '|' . $so, 0);
	}
}
```
It appears this Cookie is never actually read by anything. Searching the whole Contao installation for `TS_TABLE_` only brings the result in _ContentTable.php_, nowhere else.

Also, if you change the default sort index in the backend, the Cookie is not deleted.

**Comment by aschempp** [comment]
If I remember correctly, you have to enable a javascript in your page layout

**Comment by fritzmg** [comment]
To fix it, the part in _ContentTable.php_ could be changed to
```php
// Set table sort cookie
if ($this->sortable && $i == $this->sortIndex)
{
	$co = 'TS_TABLE_' . $this->id;
	$so = ($this->sortOrder == 'descending') ? '1' : '0';
	\System::setCookie($co, $i . '|' . $so, 0);
}
```
and _j_tablesort.html5_ for instance could be changed to
```php
<?php

// Add the tablesorter style sheet
$GLOBALS['TL_CSS'][] = 'assets/jquery/tablesorter/' . $GLOBALS['TL_ASSETS']['TABLESORTER'] . '/css/tablesorter.css|static';

?>

<script src="<?= TL_ASSETS_URL ?>assets/jquery/tablesorter/<?= $GLOBALS['TL_ASSETS']['TABLESORTER'] ?>/js/tablesorter.js"></script>
<script>
  (function($) {
    // http://stackoverflow.com/a/1460174/374996
    function readCookie(name)
    {
      var nameEQ = encodeURIComponent(name) + "=";
      var ca = document.cookie.split(';');
      for (var i = 0; i < ca.length; i++) {
        var c = ca[i];
        while (c.charAt(0) === ' ') c = c.substring(1, c.length);
        if (c.indexOf(nameEQ) === 0) return decodeURIComponent(c.substring(nameEQ.length, c.length));
      }
      return null;
    }
    $(document).ready(function() {
      $('.ce_table .sortable').each(function(i, table) {
        var cookie = readCookie( 'TS_' + $(this).attr('id').toUpperCase() );
        $(table).tablesorter({ sortList: [cookie !== null ? cookie.split('|') : []] });
      });
    });
  })(jQuery);
</script>
```

**Comment by fritzmg** [comment]
> If I remember correctly, you have to enable a javascript in your page layout

JavaScript and _j_tablesort_ is enabled. As I said, there is no part in Contao that actually does anything with the `TS_TABLE_…` cookie.

**Comment by leofeyer** [comment]
The cookie value is read here: https://github.com/contao/core/blob/master/assets/mootools/tablesort/js/tablesort-uncompressed.js#L59

**Comment by fritzmg** [comment]
Ah ok, so it only works with MooTools tablesort by default.

**Comment by leofeyer** [comment]
Also, the `TS_` cookie is specific to the MooTools table sorter.

**Comment by leofeyer** [comment]
Ups, you were faster :)

**Comment by leofeyer** [comment]
Here's the discussion: https://github.com/contao/core/issues/6727

**Comment by fritzmg** [comment]
Yep. Though the point about the cookie not beeing deleted is still valid, no? If you change the __Sort index__ value in the backend, the change will not be reflected in the frontend.

**Comment by leofeyer** [comment]
What do you mean by "the cookie not being deleted"?

**Comment by fritzmg** [comment]
### Reproduction

* create a new content element of the type _Table_
* create a table like the following:
```
1 2 3
1 3 Lorem
2 2 Ipsum
3 1 Dolor
```
* activate the following options: __Add table header__, __Sortable table__, set __Sort index__ to `1`
* activate _moo_tablesort_ in the page layout (disable _j_tablesort_)
* open the frontend and view the table - the table should be sorted by the second column
* now edit the element in the backend again and set the __Sort index__ to `0` (or `2`) and save
* open the frontend and view the table - the table is still sorted by the second column, since the cookie was not written again due to
```php
if (\Input::cookie($co) == '')
{
	…
}
```

**Comment by leofeyer** [comment]
Yes, that is because the cookie has precedence over the back end setting. As soon as there is a cookie, the back end setting will be ignored.
