### ISSUE TITLE
Inline JavaScript gets destructed when HTML gets minified

### ISSUE THREAD

**Issue by andypillip** [contao/core#8119]
I recognized when putting my Google Tag Manager Code Snippet in the fe_page Template.

It produces an error 
> Uncaught SyntaxError: Unexpected identifier

because a whole line get's cut off.

Here's the comparison (O=Original line in template, M=Minified version in Page output)

    O: (function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src='//www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);})(window,document,'script','dataLayer','GTM-PTWLR3');
    M: (function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src='})(window,document,'script','dataLayer','GTM-PTWLR3');

To be honest I just tested in a Contao 2.11 installation, the live demo does not allow changing templates.

**Comment by fritzmg** [comment]
> To be honest I just tested in a Contao 2.11 installation, the live demo does not allow changing templates.

Hm, that's not really valid then. There have been a lot of changes to the minimization process since Contao 2.11.

**Comment by fritzmg** [comment]
If you are using XHTML Template, see http://contao.ninja/Richtiges_Auskommentieren.html
