### ISSUE TITLE
Headerfields in dca config not exists

### ISSUE THREAD

**Issue by baumannsven** [contao/core#8121]
https://github.com/contao/core/blob/master/system/modules/core/dca/tl_content.php#L47

Here fields don`t exists:
 - title
 - inColumn
 - showTeaser

https://github.com/contao/core/blob/master/system/modules/news/dca/tl_news.php#L68

Here fields don`t exists:
 - makeFeed

**Comment by leofeyer** [comment]
Not sure what you mean? The fields exist in the online demo:

![](https://cloud.githubusercontent.com/assets/1192057/11320034/a5fcec70-908d-11e5-8759-b2f4aaa03da9.png

> - makeFeed

This is true, the entry is a left-over and should be removed.

**Comment by baumannsven** [comment]
Yes the field by tl_news must remove.

The fields for tl_content are right. This come from dynamic parent table.
@leofeyer For this i so sorry.

**Comment by leofeyer** [comment]
Fixed in 113e9d813a52dff80c1457a637a949cc7d609894. Thank you for your help.
