### ISSUE TITLE
Element youtube - URL

### ISSUE THREAD

**Issue by sascha-mueller** [contao/core#8122]
Die URL eines Videos schaut sehr komisch aus.
//www.youtube.com/watch?v=rOGhp63Lvbo
Müßte dass nicht http://www.youtube.com/watch?v=rOGhp63Lvbo heißen?

Anzusehen im FE der Demo unter:
http://demo.contao.org/en/media-elements.html

**Comment by BugBuster1701** [comment]
Das ist der protokoll unabhängige Syntax. (http/https)

**Comment by sascha-mueller** [comment]
Ok. Wenn das so gehört hab ich wieder was gelernt. Danke Glen.
Damit wär mein Kommentar dann obsolet.

**Comment by leofeyer** [comment]
@BugBuster1701 Das geht für externe Links, wenn diese ebenfalls über beide Protokolle erreichbar sind. Im Falle von YouTube erfolgt bei HTTP-Anfragen automatisch eine Weiterleitung auf HTTPS, so dass wir eigentlich auch immer HTTPS verwenden könnten.

**Comment by sascha-mueller** [comment]
Klingt logisch. Wäre ich dafür.

**Comment by leofeyer** [comment]
@contao/developers Irgendwelche Bedenken?

**Comment by aschempp** [comment]
Was sagen die Browser zu Protocol-Mixing dazu?

**Comment by leofeyer** [comment]
Die haben nur ein Problem, wenn man auf einer HTTPS-Seite Inhalte über HTTP einbindet. Andersherum ist ok.

**Comment by leofeyer** [comment]
Außerdem sprechen wir ja hier über einen Link und kein Embedded-Object.

**Comment by aschempp** [comment]
`true`

**Comment by Toflar** [comment]
Es sollte immer `https` verwendet werden, wenn möglich. Protokoll-relative URL's sind ein "Anti-Pattern" und sollten nie verwendet werden.

**Comment by bytehead** [comment]
@Toflar +1

**Comment by leofeyer** [comment]
> Protokoll-relative URL's sind ein "Anti-Pattern" und sollten nie verwendet werden.

Das habe ich noch nie gehört. Wo steht das?

**Comment by Toflar** [comment]
Hier z.B. http://www.paulirish.com/2010/the-protocol-relative-url/ - aber es ist ja nur logisch :)

**Comment by leofeyer** [comment]
Naja, ein Anti-Pattern ist es nur in diesem speziellen Anwendungsfall, nämlich wenn

* die Seite über HTTP erreichbar ist und
* die eingebundene Ressource über HTTP und HTTPS erreichbar ist.

In diesem Fall macht es natürlich immer Sinn, HTTPS zu verwenden.

Bei uns ist es jedoch so, dass wir nicht immer wissen, ob die einzubindenden Ressourcen beide Protokolle unterstützen. Daher ist es in unserem Anwendungsfall auch kein Anti-Pattern IMO.

**Comment by aschempp** [comment]
> Bei uns ist es jedoch so, dass wir nicht immer wissen, ob die einzubindenden Ressourcen beide Protokolle unterstützen. 

Dann macht Protokoll-relativ gar keinen Sinn, weil die Ressource ggf. über eine invalide URL eingebunden würde. Wir wissen aber dass es beides gibt (oder bei YouTub nur HTTPS), daher sollten wir immer HTTPS verwenden.

**Comment by leofeyer** [comment]
Dieses Ticket hat sich durch #8183 erledigt.
