### ISSUE TITLE
PageForward can cause infinite redirect

### ISSUE THREAD

**Issue by fritzmg** [contao/core#8123]
### Description

If you have a multi-domain setup with two different domains and happen to have a page in each website tree with _the same alias_ and one of them is an internal redirect to the other page respectively, then Contao will generate an infinite redirect, because it does not consider the domain.

### Reproduction

* create two website roots, one with example1.org and one with example2.org
* create a regular page in _example1.org_ with the alias _test_
* create a internal redirect page in _example2.org_ with the alias _test_ and point the target to the page _Test_ in _example1.org_
* open http://example2.org/test.html in the frontend

This will cause an infinite redirect, since contao keeps redirecting to http://example2.org/test.html instead of http://example1.org/test.html

### Cause

[PageForward.php](https://github.com/contao/core/blob/3.5.4/system/modules/core/pages/PageForward.php#L111) does not check if the target page happens to be on another domain. i.e. it is omitting the 4th parameter of `\Controller::generateFrontendUrl` (`$blnFixDomain`) which was [introduced in Contao 3.3.0](https://github.com/contao/core/blob/3.3.0/system/modules/core/library/Contao/Controller.php#L2189) (previously, this check had to be done outside of \Controller::generateFrontendUrl).

### Note

Even if the pages do not have the same alias, PageForward.php will probably simply cause a subsequent 404 Error, since the target page might not exist (since it is ommitting the correct domain). Haven't tested this case though.

**Comment by fritzmg** [comment]
There are several instances in Contao where `\Controller::generateFrontendUrl` is used without the 4th parameter `$blnFixDomain`. This is also related to #6743 where basically the same thing happens (the redirect to the wrong URL, not the infinite redirect).

**Comment by leofeyer** [comment]
This is a complex issue.

First, let me say that we are planning to fix URLs by default in Contao 5 (see #6743). Since this is a BC break, we are only fixing URLs when forwarding to another page in Contao 3 and 4.

Second, you are right that the fourth argument needs to be set in the `PageForward` class.

**Comment by leofeyer** [comment]
Fixed in d7f5d408f7c65650c2f2f013caa9bf8eb656800d.

**Comment by fritzmg** [comment]
> Since this is a BC break, we are only fixing URLs when forwarding to another page in Contao 3 and 4.

Hm, but you closed #7922 in favor of #6743 . However, issue #7922 is also about forwarding to another page (i.e. the target page defined in the news entry). Issue #7922 is not about forwarding to the news archive's page (which issue #6743 is about, mainly).
