### ISSUE TITLE
[3.5] Artikel Sichtbarkeits-Toggle auch bei Seiten ohne Zugriffsrecht

### ISSUE THREAD

**Issue by Mynyx** [contao/core#8126]
Bei Artikeln wird das Sichtbarkeits-Toggle-Icon bei allen Artikeln entsprechend dem aktuellen Zustand ggf. farbig angezeigt, wenn der Benutzer das Recht für das Feld tl_article->Artikel veröffentlichen hat - allerdings unabhängig davon, ob der Benutzer auch das notwendige Zugriffsrecht "Artikel bearbeiten" hat.

Analog zu den anderen Icons dürfte auch das Sichtbarkeits-Toggle-Icon, wenn der Benutzer das Zugriffsrecht "Artikel bearbeiten" nicht hat, allerdings nur grau angezeigt werden.

**Comment by aschempp** [comment]
Das Icon wird entsprechend dem Veröffentlichungs-Status angezeigt, nicht entsprechend der Berechtigung.

**Comment by Mynyx** [comment]
Wenn man das so interpretiert, dann sollte das Icon aber auch unabhängig vom Recht des Feldes  "tl_article->Artikel veröffentlichen stets angezeigt werden - schließlich beziehen sich die Feldrechte immer nur auf das Recht zum Bearbeiten und nicht das Recht zu Lesen.

**Comment by aschempp** [comment]
Ich denke das wäre ein Thema für die neuen Backend Icons (siehe https://association.contao.org/abstimmung/items/finanzierung-eines-neuen-iconsets-fuer-contao-35.html)

**Comment by Mynyx** [comment]
Es würde doch lediglich eine graue Version des vorhandenen Icons benötigt werden?

**Comment by leofeyer** [comment]
> Analog zu den anderen Icons dürfte auch das Sichtbarkeits-Toggle-Icon, wenn der Benutzer das Zugriffsrecht "Artikel bearbeiten" nicht hat, allerdings nur grau angezeigt werden.

Das sehe ich nicht so. Das Auge-Icon hat eine Doppelfunktion: es zeigt zum einen den Veröffentlichungsstatus an und fungiert zum anderen als Button. Wenn ein Benutzer einen Button nicht betätigen kann, ist dieser normalerweise grau. Allerdings ist die Seite ja trotzdem veröffentlicht.

Wenn Du mich fragst, ist das der beste Kompromiss für ein Problem, das sich nicht so einfach lösen lässt.

**Comment by Mynyx** [comment]
> Wenn ein Benutzer einen Button nicht betätigen kann, ist dieser normalerweise grau. Allerdings ist die Seite ja trotzdem veröffentlicht.

Das Icon in Form des geöffneten Icons könnte in diesem Fall in einer grauen Version angezeigt werden.

**Comment by leofeyer** [comment]
Geändert in contao/core-bundle@fcc885a715932ea10d83c580c77da8dc194c2af6.
