### ISSUE TITLE
Wrong French translation "Nom du groupe"

### ISSUE THREAD

**Issue by sebj54** [contao/core#8128]
Hi,

I noticed that there were multiple wrong translations for "title" field in the back-office. In many modules, the "title" label is wrong and is "Nom du groupe" (which means "Group name").

I remember that it was not this way in a previous (but I don't know which one) so it should be due to a bad "Find and replace" I presume :smile: 

Thanks in advance!

**Comment by Toflar** [comment]
Salut @sebj54, merci pour ton message :)

Translations are contributed by the community whereas we use Transifex for managing them. You can submit the correct French language strings there: https://www.transifex.com/contao/contao/

**Comment by sebj54** [comment]
Thanks for the information, I didn't know about Transifex.

**Comment by lionel-m** [comment]
@sebj54 J'ai corrigé pour la version 3.5 et 4.0.

**Comment by sebj54** [comment]
@lionel-m Great! Thanks :smiley:

**Comment by sebj54** [comment]
Can the translations in the last versions of Contao? 
Or could I download language files somewhere?

Thanks in advance.
