### ISSUE TITLE
rgxp "url" funktioniert nicht im Backend

### ISSUE THREAD

**Issue by Total-Reality** [contao/core#8130]
Hallo,

ich hab das Ticket hier gelesen:
https://github.com/contao/core/issues/4375

Aber so ganz kann das ja doch nicht sein was da steht, denn im Frontend funktioniert die Angabe ja und er meckert mich z.B. an, wenn ich kein http:// vor den Link schreibe. Warum geht das im Frontend nicht? Was ist da der Unterschied?

**Comment by leofeyer** [comment]
Steht in #4375: Im Backend sind auch URL-Fragmente erlaubt.
