### ISSUE TITLE
An invalid form control with name='text' is not focusable.

### ISSUE THREAD

**Issue by xchs** [contao/core#8131]
To reproduce in the Contao online demo (Contao 3.5.5):
* add a new content element of type "Text" to an article
* add a few words into the textarea
* save the record

See https://github.com/contao/core-bundle/issues/266 where we have already encountered this issue.

**Comment by xchs** [comment]
Unsetting the `required` attribute for textareas fixes the problem:
```php
unset($this->arrAttributes['required']);
```
(https://github.com/contao/core-bundle/commit/4349cd63a8ac2ffb507cc31ef37ffcd9c2f60235)

**Comment by ausi** [comment]
I think it was introduced in https://github.com/contao/core/commit/f181cdab2e15440e7b27956fd5ef7de28cea0a25#diff-74d23f9d8cb214ddcca2663dc0abf4f5L757

**Comment by leofeyer** [comment]
You are right. The issue only affects Chrome as far as I remember.

**Comment by ausi** [comment]
IMO it affects all browsers that support `required`.

**Comment by leofeyer** [comment]
It does work in Safari and Firefox on Mac.

**Comment by ausi** [comment]
I’m not able to save the element in Firefox on Mac.

**Comment by xchs** [comment]
Firefox shows an "Bitte füllen Sie dieses Feld aus" message on my (Windows) system.

**Comment by leofeyer** [comment]
I suggest to use the TinyMCE `setup` callback to remove the `required` attribute. @ausi What do you think? We'll have to use vanilla JS here.

**Comment by leofeyer** [comment]
Here's what works for me:

```js
<script>
window.tinymce && tinymce.init({
  …
  setup: function(editor) {
    editor.getElement().removeAttribute('required');
  },
  …
});
</script>
```

**Comment by leofeyer** [comment]
I'd also like to change the fix that we have added in Contao 4, because the PHP code should not be responsible to fix JavaScript issues, right?

**Comment by ausi** [comment]
LGTM, but `removeAttribute()` is not vanilla IMO.

Yes I think it is correct to do it in JavaScript, not in PHP.

**Comment by xchs** [comment]
Yup, seems reasonable.

**Comment by leofeyer** [comment]
@ausi Sure? http://www.w3schools.com/jsref/met_element_removeattribute.asp

**Comment by ausi** [comment]
Sorry, I should’ve looked it up.
`removeProperty` is MooTools, [`removeAttribute`](https://developer.mozilla.org/en-US/docs/Web/API/Element/removeAttribute) is native.

**Comment by leofeyer** [comment]
Fixed in c16e537f33d51767b773416094a8c3f0bd9b704f then.

**Comment by bizon1** [comment]
Last night i made 10 Contao updates to 3.5.5. Fix an everything else is working fine so far. 
Thanks to all.

**Comment by SpeGal** [comment]
Did I get it right, that every system that got updated to 3.5.5 cannot create any new text elements right now? Will the fix be pushed out very soon therefore?

**Comment by bytehead** [comment]
Yes, you are right. But the 3.5.6 is on the way later this day afaik. :)

**Comment by leofeyer** [comment]
> Did I get it right, that every system that got updated to 3.5.5 cannot create any new text elements right now?

No, the issue only affects Chrome and Firefox.

**Comment by leofeyer** [comment]
> But the 3.5.6 is on the way later this day afaik. :)

https://twitter.com/leofeyer/status/670170668575641600

**Comment by xantippe** [comment]
Ich habe das Problem in einer 3.5.6 immer noch - sollte das nicht gefixt sein?

btw: Caches alle geleert

**Comment by bizon1** [comment]
@xantippe 
Kann es sein, dass du eine eigene (noch alte) tinyCustom.php verwendest? Falls ja muss die natürlich an die neue tinyMCE,php aus der 3.5.6 angepasst werden.

**Comment by xantippe** [comment]
... habs schon gemerkt https://github.com/contao/core/issues/8131#issuecomment-171354499
