### ISSUE TITLE
Contao 3.5.5: Neu angelegtes Content-Element Text lässt sich nicht mehr speichern

### ISSUE THREAD

**Issue by kachelblitz** [contao/core#8132]
Folgender Bug fiel mir beim Update auf 3.5.5 auf, sowohl lokal als auch in der Online-Demo:
1. Erstelle neues Content-Element "Text". Editor enthält Text.
2. Speichern: Chrome: Keine Rückmeldung, Inhalt wird nicht gespeichert. Firefox: oben links im Browser erscheint eine Sprechblase "Bitte füllen Sie dieses Feld aus" (Koordinaten 0,0), Speichern ebenfalls nicht möglich.
Das Kopieren, Modifzieren und Speichern eines vorhanden CE-Element "Text" funktioniert dagegen.

**Comment by Aybee** [comment]
Ich glaube dieses Ticket ist **sehr wichtig**, weil sonst keine Inhaltselemente Typ Text erstellt werden können. Arbeitet schon jemand daran?

**Comment by ausi** [comment]
I was able to reproduce it. The problem is that the `<textarea>` gets an `required` attribute.

**Comment by leofeyer** [comment]
See #8131.
