### ISSUE TITLE
Fehler im Backend: Anzeige "Bitte füllen Sie dieses Feld aus."

### ISSUE THREAD

**Issue by SpeGal** [contao/core#8135]
Seit dem Update auf 3.5.5. gibt es Probleme beim Anlegen von Artikelelementen. Wenn ich bspw. ein normales Text-Element anlegen und speichern möchte, erscheint ganz links oben in der Ecke des Browserfensters die Meldung "Bitte füllen Sie dieses Feld aus." und eine Speicherung ist leider nicht möglich. Allerdings befindet sich natürlich links oben in der Ecke auch kein Feld, das ich ausfüllen könnte ...

**Comment by bytehead** [comment]
See #8131.
