### ISSUE TITLE
Elementtyp Text kann in Chrome nicht gespeichert werden seit Contao 3.5.5

### ISSUE THREAD

**Issue by Ma3xl3** [contao/core#8136]
Seit dem Update auf Contao 3.5.5 kann ich keine neuen Textelemente in Chrome speichern. Wenn ich auf speichern klicke passiert nichts. Im Developer Tool erhalte ich folgende Fehlermeldung: 

```
An invalid form control with name='text' is not focusable.
```

Ein bereits vorhandenes Textelement kann ich jedoch bearbeiten und speichern.

Ich verwende Chrome 46.0.2490.86.
Auf der Demoseite funktioniert es auch nicht. Ich bin wie folgt vorgegangen:

Articles ->  Home (edit icon) ->  Add new content element -> Elementtype Text
Einen Text eingeben und auf speichern klicken.

**Comment by bytehead** [comment]
See #8131.
