### ISSUE TITLE
Anlegen neuer Templateordner ist im Backend nicht möglich 

### ISSUE THREAD

**Issue by proplab** [contao/core#8138]
Sowohl in Contao 3.5.5 als auch in Contao 3.5.6 können keine neuen Templateverzeichnisse angelegt werden.
Der Link dafür fehlt.
Wenn ich ein Verzeichnis via SSH anlege wird es angezeigt und kann verwendet werden.

Bei mir betrifft es sowohl Updates, als auch Neuinstallation.

**Comment by xchs** [comment]
Das Problem liegt vermutlich hier: https://github.com/contao/core/blob/da885ca8682746ddba27e281caac6329f9a931b9/system/modules/core/drivers/DC_Folder.php#L340-L343

**Comment by BugBuster1701** [comment]
Betrifft auch Contao 4.1

**Comment by leofeyer** [comment]
Fixed in 27f883f4695905ac039809badf8387cff5be0473.
