### ISSUE TITLE
ModuleRegistration ignores unique when DCA encrypt

### ISSUE THREAD

**Issue by t-me** [contao/core#8144]
Hello,

On issues #8110 you solved the DCA Encrypt on ModuleRegistration,

Only the value will not be compared now when it must be unique.
People registration can set same input as other people.

**Comment by leofeyer** [comment]
No idea how to solve this without decrypting every single row and comparing the unencrypted values, which will notably affect the performance.

@contao/developers /cc

**Comment by aschempp** [comment]
How about DB level uniqueness? The same encryption should result in the same value…

**Comment by ausi** [comment]
> The same encryption should result in the same value…

I don’t think so: `Encryption::encrypt('foo') !== Encryption::encrypt('foo')`

**Comment by aschempp** [comment]
Not? If you use the same encryption key?

**Comment by leofeyer** [comment]
Definitely not.

**Comment by discordier** [comment]
This is the benefit of block ciphers in favor over substitution. You can not guess the plaintext from ciphered text.
There is nothing to do here aside from checking against the whole DB.
However, when you encrypt everything you are aware of the fact that it costs time. That's the tradeoff of security by encryption. Therefore I think it is ok to scan the DB in that case.

**Comment by aschempp** [comment]
I would actually say this is an edge case we don't need to handle in the care. It can be simply added using a `save_callback`.

**Comment by leofeyer** [comment]
> Therefore I think it is ok to scan the DB in that case.

Well, I don't. Imagine a customer database with 1,000,000 entries and encrypted credit card numbers. To check the uniqueness we would have to select all entries, decrypt them on PHP level and then compare them. How much RAM is the application supposed to consume?

**Comment by discordier** [comment]
Bad example as CC numbers never must get stored and many ppl pay with company CC for all accounts but anyway, what do you want it to be?
There is nothing(!) we can do here without loosening the encryption. Imagine a new column which holds a hash of the original value, thus allows yet again to take a guess on the original value. Salting that hash will increase security again but raise the original issue.
Therefore, if you want to have unique encrypted values, you will have to check via rowscan. This however will have to be in bulk sets, to not let the memory explode.

**Comment by leofeyer** [comment]
Or we simply add a known issue that encrypted columns cannot be unique.

**Comment by leofeyer** [comment]
As discussed in Mumble on April 21st, we are going to make this a known limitation.

**Comment by leofeyer** [comment]
Added in contao/contao@bb2c8c90ee991062a8b7f20582ab1f9a735cb1c7.
