### ISSUE TITLE
Static function in ModuleNews.php called using this. Breaks News in php5.3 installation.

### ISSUE THREAD

**Issue by Sehiro** [contao/core#8145]
PHP Error msg: PHP Fatal error:  Using $this when not in object context in /system/modules/news/modules/ModuleNews.php on line 144

Possible fix:

Changing line 144 from
$strText .= $this->getContentElement($objElement->current());
to
$strText .= ModuleNews::getContentElement($objElement->current());
would fix the issue. "getContentElement" is a static function anyways.

Thanks

Cheers
Stefan

**Comment by fritzmg** [comment]
Contao 3.5 requires PHP 5.4. Also, if at all, you should change the call to 
```php
\Controller::getContentElement($objElement->current());
```
(though it doesn't matter in the end)

**Comment by Sehiro** [comment]
In my opinion and from design perspective it does not matter much if you call the Controllers or your own classes static method. BUT the fact that php does not considers this (using $this in static methods) an error anymore is most likely due to convenience and not due to good design. It issues still a warning, though. And as a ground rule, nothing with "hints" or "warnings" should go into production. ;)

In this case I would consider it an error because it is wrong to call a static method with $this despite the fact that it works.

In any case, changing it would make no difference to php >= 5.4 installations and it would mean much to me, because I can't change my php version yet and I would not have to patch each new update.

Thanks

Stefan

**Comment by fritzmg** [comment]
> In this case I would consider it an error because it is wrong to call a static method with $this despite the fact that it works.

I agree ;)
