### ISSUE TITLE
Bug: Green arrow for expand node in content preview always visible

### ISSUE THREAD

**Issue by Aybee** [contao/core#8146]
Hallo Leo,

du hast die Validierung von `limit_height h64` aufgesetzt, nachdem die Höhe bereits auf 64px gesetzt wurde. Dadurch wird die Abfrage `if (size.height < hgt)` niemals wahr werden.

https://github.com/contao/core/blob/master/assets/contao/js/core-uncompressed.js#L1066-L1088

Wahrscheinlich musss `div.setStyle('height', hgt);` einfach nur **nach** der Abfrage der Ermittlung der Größe kommen - `size = div.getCoordinates();`.

In der Online-Demo kannst du das sehen, wenn du in der Content-Listview ein Element betrachtest, welches beispielsweise nur eine Überschrift enthält.

Edit: Vielleicht kann man das auch so machen, dass in dem Fall erst gar kein Image dort rein generiert wird. Ich habe das in meinem Theme so umgesetzt und vermisse dieses ausgegraute Icon, auf welches ich sowieso nicht klicken kann, nicht.

**Comment by leofeyer** [comment]
Fixed in 83a3d82410765dd5c427dcc5929781b0fe1c997c.
