### ISSUE TITLE
Front end preview as admin: no Front end users are shown

### ISSUE THREAD

**Issue by asaage** [contao/core#8148]
![image](https://cloud.githubusercontent.com/assets/4138336/11611817/105997c2-9be1-11e5-9ebc-73add8a5e4c1.png)
Easily to be reproduced in the online demo.

**Comment by fritzmg** [comment]
I don't know if it was alwas this way, but you have to begin typing a username in order to show a list of usernames that match your input. On my browser the input field is not even displayed as a dropdown.

**Comment by asaage** [comment]
i see...
somehow i was used to getting presented a dropdown of the memberlist but i might have mixed that up with the "rebuild search index" dialog in the BE where that is the case.
