### ISSUE TITLE
Front end preview as non-admin bypasses protection

### ISSUE THREAD

**Issue by asaage** [contao/core#8149]
![image](https://cloud.githubusercontent.com/assets/4138336/11611841/2600a8f8-9be2-11e5-8dd3-65d33ee4ec72.png)
That might be a duplicate of #567 but as that was closed 4 years ago without solution **i suggest to change at least the wording**.
Not only does that selection allow to show unpublished elements but also protected elements and pages.
In my use-case that's definitely a security issue - so i am going to disable the Frontendpreview completely for non-admin BE-users.
Any Info on that for contao4 is appreciated.

**Comment by fritzmg** [comment]
Element and page protection only applies to frontend users. Thus any backend user (regardless of whether he or she is an Admin) is able to view all elements.

**Comment by asaage** [comment]
![image](https://cloud.githubusercontent.com/assets/4138336/11615189/8fa37c22-9c5a-11e5-9829-69ec531cea6d.png)
That would make clear, what is going on.
And the ability to turn this feature off in the security settings would be nice to have.

**Comment by fritzmg** [comment]
Having such an option wouldn't make any sense. Any backend user can see any element (given the appropriate access rights) in the backend regardless of its 'protected' state.

**Comment by asaage** [comment]
you name it: (given the appropriate access rights)

**Comment by fritzmg** [comment]
The access rights have nothing to do with the visibility in the frontend.

**Comment by asaage** [comment]
just an example:
A BEuser of the public relation office who has the ability to edit some public gallery-sites with the appropriate pagemount should not be able to see protected content (which is edited by the the business-management BEgroup) if he has no FE-Account that legitimates him to do so.
But under the present conditions he CAN with the help of the Frontend-preview. Therefore turning the Frontend-preview feature completely off totaly makes sense to me.

I have made the "show unpublished" only available for admin's in the *be_switch* template but as i can not imagine that my usecase is too special i think having a checkbox in the system settings would not be a big deal at all.

**Comment by fritzmg** [comment]
> But under the present conditions he CAN with the help of the Frontend-preview.

Only if the backend user has the right to do so. If you disable the access to the frontend user for that backend user, he cannot view the frontend as any frontend user.

**Comment by asaage** [comment]
>he cannot view the frontend as any frontend user.
that is right.
but he can show the hidden elements (which are in fact the hidden and the protected ones)...

maybe i'm going to investigate more on that tomorrow.

**Comment by leofeyer** [comment]
What is the status of your investigation?

**Comment by asaage** [comment]
I still think it's a secuity-flaw
backend-user's should not get access to protected frontend-content but the show-hidden-dropdown allows for exactly that.
so it should at least be renamed to show-hidden-and-protected.

**Comment by leofeyer** [comment]
@contao/developers /cc

**Comment by aschempp** [comment]
I think the suggestion is valid, but hard to change because people are very used to it
 1. Change `BE_USER_LOGGED_IN` to not change frontend access permission (only publishing).
 2. Only allow frontend user login if the backend user has access to `tl_member`

So if you want to see certain frontend pages you need to login as that user. That's actually why there is such an option, because I usually login as a user but do not show unpublished content...

**Comment by leofeyer** [comment]
Changed in contao/core-bundle@426f71483e75ae16f0391b3bfade055717baba91.
