### ISSUE TITLE
[3.5] Update Hinweis auch bei Nutzern ohne Zugriff auf Systemwartung

### ISSUE THREAD

**Issue by Mynyx** [contao/core#8151]
Der Update Hinweis auf der Startseite des Backends wird auch Benutzern angezeigt, die keinen Zugriff auf das Modul Systemwartung haben.
Diese erhalten daher nach Klick auf den Link stets eine Fehlermeldung.

**Comment by leofeyer** [comment]
Behoben in 447dd6b771ba8d20353df102de2de9c66cc4e73b.
