### ISSUE TITLE
C3.5.6: Formulare: HTML-Tags erlauben funktioniert nicht

### ISSUE THREAD

**Issue by Anke** [contao/core#8152]
Wenn man in Formularen die Option HTML-Tags erlauben aktiviert und bspw. welche im Standardwert vorgibt (z.B. Empfehlungslink oder Zeilenumbruch), werden die Tags im FE angezeigt und beim Absenden erscheint eine Fehlermeldung, dass die verwendeten Sonderzeichen aus Sicherheitsgründen nicht zulässig sind. Ist das ein Bug?

**Comment by leofeyer** [comment]
?

**Comment by Anke** [comment]
![contao_forms_html_01](https://cloud.githubusercontent.com/assets/1300920/11826197/0cef8ae2-a384-11e5-9308-d3f461361512.jpg)
![contao_forms_html_02](https://cloud.githubusercontent.com/assets/1300920/11826196/0ceda1b4-a384-11e5-8e33-f667d3a61349.jpg)
![contao_forms_html_03](https://cloud.githubusercontent.com/assets/1300920/11826198/0cefa964-a384-11e5-9829-03da30ad030b.jpg)

**Comment by asaage** [comment]
Deinem Screenshot ist ja zu entnehmen, dass die html-tags noch da sind.
So gesehen verhält sich alles korrekt - zu mehr ist ein einfaches textarea wohl nicht in der Lage.
Du könntest das mit z.B. mit einem tinymce oder ähnlichen Plugin zum Leben erwecken - was allerdings zur Folge hätte, dass beim Klick auf den Link dieser bearbeitet würde und nicht aufgerufen..
Wenn das Formular per Mail versendet werden soll stehst du dann wieder vor dem selben Problem.

Ich vermute eher, der Feldtyp "Erklärung" oder "Überschrift" (in Contao 3 wohl beides das selbe) ist in diesem Fall der angebrachte.

**Comment by Anke** [comment]
Danke. Den Hinweis mit "\n" hatte ich irgendwo gefunden, das wurde aber im FE ebenfalls so angezeigt.

Sorry, habe mich hiermit wohl vertan und diskutiere das im Forum weiter.
