### ISSUE TITLE
Benutzergruppen: Mehr als 1000 einzelne Berechtigungen lassen sich nicht setzen

### ISSUE THREAD

**Issue by Brubbel66** [contao/core#8157]
Ich habe eine Benutzergruppe in Contao 3.5.6 und setze darüber für die Mitglieder sehr spezifische Rechte. Ich habe verschiedene zusätzliche Erweiterungen und Tabellen, so dass eine große Anzahl von einzelnen Berechtigungen gesetzt werden kann. 
Wenn ich mehr als 1000 (999?) Einzelberechtigungen setze, können keine weiteren Berechtigungen mehr angeklickt werden. Erst wenn ich irgendwo 2 Berechtigungen entferne, kann ich an anderer Stelle 2 weitere Berechtigungen setzen. Die Summe scheint nicht über 1000 hinausgehen zu dürfen.

Ich konnte es in der Online-Demo nicht nachstellen, da dort nicht genug Einzelberechtigungen zur Verfügung stehen.

**Comment by asaage** [comment]
Schau dir deine PHP-konfiguration an!
**max_input_vars** ist das Stichwort, das Thema kam hier vor kurzen schonmal auf, hat aber nichts mit Contao zu tun.

**Comment by Brubbel66** [comment]
Das ist die richtige Antwort. Ich danke Dir sehr und sorry, dass ich den Hinweis vorher nicht gefunden habe.
