### ISSUE TITLE
[3.5.6] Funktion Benutzer wechseln ändert alle Sessions des ursprünglichen Benutzers

### ISSUE THREAD

**Issue by Mynyx** [contao/core#8158]
Die Funktion "Zu Benutzer wechseln" ändert alle Sessions des ursprünglichen Benutzers, statt nur die Session zu ändern, in welcher der ursprüngliche Benutzer die Funktion ausführt.

Siehe https://github.com/contao/core/blob/master/system/modules/core/dca/tl_user.php#L627

**Comment by Zeromax** [comment]
Ah.. This is the reason why I am logged in as a diffent account in an other browser...

**Comment by leofeyer** [comment]
?

**Comment by Mynyx** [comment]
Einloggen im Backend mit dem selben Benutzer in zwei verschiedenen Browsern. In einem Browser über die Benutzerliste zu einem anderen Backend Benutzer wechseln. Im anderen Browser ist man dann ebenfalls mit dem anderen Benutzer eingeloggt, obwohl es sich um verschiedene Sessions handelt.

**Comment by aschempp** [comment]
Es handelt sich für Contao um dieselbe Session. Users sind persönlich und sollten nicht mehrfach benutzt werden.

**Comment by Mynyx** [comment]
In tl_session werden die Sessions separat geführt, insofern verstehe ich nicht was du meinst?

Außerdem geht es ja gerade darum, dass die selbe Person sich mehrfach anmeldet, und nicht um verschiedene Personen

**Comment by Mynyx** [comment]
Fehlen hierzu noch weitere Informationen?

**Comment by leofeyer** [comment]
@contao/developers /cc

**Comment by aschempp** [comment]
Müssten wir ein neues Session- und Login-Cookie erzeugen?

**Comment by Zeromax** [comment]
Ich denke es würde reichen den richtigen Session Eintrag aus der Tabelle tl_session zu löschen und nicht alle.

**Comment by leofeyer** [comment]
Behoben in f8da814202d308af807a921dc0a021331898f662.
