### ISSUE TITLE
Duplicate Key Error: Mitglieder/Frontendnutzer duplizieren ohne Username, Version 3.5.4

### ISSUE THREAD

**Issue by theDyingMountain** [contao/core#8159]
Wenn ein Nutzer ohne eingetragenen Username dupliziert wird, ist der Username der Kopie nicht NULL sondern ein leerer String. Dies sorgt für einen "duplicate Key" Error beim erneuten Duplizieren eines Mitglieds. Der Fehler tritt in Version 3.5.4 auf.

**Comment by leofeyer** [comment]
Wie lässt sich das in der Onlinedemo reproduzieren?

**Comment by asaage** [comment]
Ich wette, das wurde bereits gefixed #8072 #8064 https://github.com/contao/core/commit/d60458d09dd1ffe5887ab5f07d932f2bca3e4c1e

**Comment by theDyingMountain** [comment]
Okay ja sieht so aus, also seit Version 3.5.6
