### ISSUE TITLE
Icons for backend titles

### ISSUE THREAD

**Issue by JLBA** [contao/core#8160]
Hi,

Just a small improvement for Contao BE. 

This is sometimes a little bit difficult to find quickly what we are looking for in BE pages like Settings because there are a lot of things all with the same green title. Could you just add little icons at the start of each title to differentiate them ?

Thnaks.

**Comment by leofeyer** [comment]
What do you mean by "backend titles"?

**Comment by xchs** [comment]
> What do you mean by "backend titles"?

I guess the legends are meant.

![legend](https://cloud.githubusercontent.com/assets/1218766/14574533/8153e54e-035c-11e6-8b67-cd12989c571a.png)

However, I am not sure if it really helps to add there everywhere a little icon. :confused:

**Comment by JLBA** [comment]
Yes, I wanted to say Legends. That was one day when I’ve worked many hours long and all legends were mixing. I suddenly hoped some icons could help me find the one i was looking for (ok, that was also a signal for time for me to have a break ;-)

JL

**Comment by leofeyer** [comment]
We would need to create about 60 to 80 additional icons (!) for this and I doubt that anyone will do the work. Also, we have just begun to decrease the number of icons in the new back end theme in Contao 4.2, therefore I vote -1 on this.

@contao/developers What's your opinion?

**Comment by NinaG** [comment]
-1 (same thoughts like Leo) 

... bin zwar kein Entwickler, aber das mal rein meine Meinung aus Usability-Sicht. So viele Icons bringen keinen Mehrwert/mehr Übersichtlichkeit.

**Comment by frontendschlampe** [comment]
I also think, that there are enough icons. Maybe for future theme development there should be a design which highlight the legend titles a little bit more!

**Comment by Toflar** [comment]
-1

**Comment by ausi** [comment]
-1

**Comment by do-while** [comment]
Every of this fieldset have an id="..." with the palette name in it.
e.g. <fieldset id="pal_expert_legend" class="tl_box">

@JLBA: you can add your own styles to the backend theme to add any icons you want.

**Comment by JLBA** [comment]
Ok. Thanks.

JL Test
jltest@free.fr
