### ISSUE TITLE
[3.5.6] Dateiverwaltung Thumbnails height und width Attribut fehlt

### ISSUE THREAD

**Issue by Mynyx** [contao/core#8162]
In der Dateiverwaltung fehlen bei Thumbnails die height und width Attribute

**Comment by leofeyer** [comment]
?

**Comment by discordier** [comment]
Er meint dass in der Dateiverwaltung bei den thumbnails im HTML die width und height nicht angegeben wird.
Er moechte:
```diff
<div class="tl_left" style="padding-left:60px">
  <a href="files/music_academy/images/admin.gif" title="" target="_blank">
  <img src="assets/contao/images/iconGIF.gif" width="18" height="18" alt="image/gif">
  </a> admin.gif <span class="tl_gray">(1.3 KiB, 518x96 px)</span><br>
-  <img src="assets/images/a/admin-b6bb4f2a.gif" alt="" style="margin:0 0 2px -19px">
+  <img src="assets/images/a/admin-b6bb4f2a.gif" width="4800" height=4711" alt="" style="margin:0 0 2px -19px">
</div>
```

**Comment by leofeyer** [comment]
Und warum ist das ein Problem?

**Comment by xchs** [comment]
Problem vielleicht nicht, aber der Browser lädt die Seite u. U. etwas schneller, wenn bereits beim ersten Rendering klar ist, welcher Platz für dieses Element zu reservieren ist.

**Comment by leofeyer** [comment]
Geändert in cc7a16e6ec7246dccb2205791e95552b5ae41afd.
