### ISSUE TITLE
[3.5.6] PageRoot Fehler System-Log Eintrag

### ISSUE THREAD

**Issue by Mynyx** [contao/core#8163]
Im Text zum System-Log Eintrag in PageRoot->generate() ist eine überflüssige schließende Klammer:

Siehe https://github.com/contao/core/blob/master/system/modules/core/pages/PageRoot.php#L39

**Comment by leofeyer** [comment]
Fixed in 391e6b8eee7ee5a6d22b1a1bee6f929be73eb02f.
