### ISSUE TITLE
Upload button in image picker

### ISSUE THREAD

**Issue by tpk109** [contao/core#8169]
When choosing an image there is the link "Open the file manager". It would be convinient to also have a "Upload Image" link there, as in most of the cases it's that what one wants to do at that point.

**Comment by leofeyer** [comment]
What exactly do you mean?

**Comment by tpk109** [comment]
If yor are editing a text and you want to add an image: You press the "change selection", then you realize, that you have to upload a new one. At this point it would be nice to have an "Upload Image" button right next to the "Open the file manager". This would save one click and on a slower server this would be a quite convenient thing. Especially as uploading an image is exactly what you want to do when you click "Open the file manager" at that point in about 90% of the cases.

**Comment by aschempp** [comment]
It's not one click less. You still have to select the folder where to upload. Which is two clicks, the same as "Open file manager" and click the green plus icon next to a folder…

**Comment by tpk109** [comment]
Whoops, I did not notice these ...

Then on a little improvement: a green plus for  the top level?!

2015-12-23 21:26 GMT+01:00 Andreas Schempp <notifications@github.com>:

> It's not one click less. You still have to select the folder where to
> upload. Which is two clicks, the same as "Open file manager" and click the
> green plus icon next to a folder…
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/contao/core/issues/8169#issuecomment-166984645>.
>



-- 
------------------------------------------
Thomas Kratz

Webseiten, Programmierung, Grafik & (Online)-Marketing:
www.web-om.de

Niehoffs Blaike 5
48369 Saerbeck
02574 – 245873
0176- 9652 999 0
info@web-om.de
USt-IdNr: DE815141427
------------------------------------------

**Comment by leofeyer** [comment]
The new DCA picker renders this ticket redundant.
