### ISSUE TITLE
Session : Potentielle Session-Fixation-Schwachstelle

### ISSUE THREAD

**Issue by fatcrobat** [contao/core#8170]
Nach der Anmeldung am CMS wird server-seitig kein neues Session-Identifier-Cookie
(BE_USER_AUTH bzw. FE_USER_AUTH) ausgestellt. Somit sind die Applikationen grundsätzlich
gegen Session-Fixation-Angriffe anfällig. Da ein Angreifer bei einem erfolgreichen Session-Fixation-
Angriff die Session seines Opfers vollständig übernehmen kann, ist das Schadenspotential durchaus als hoch einzustufen.

Zur Lösung müsste man nach erfolgreicher Anmeldung immer einen neuen Session-Identifier-Cookie ausstellen.

**Comment by leofeyer** [comment]
Bitte schreib in diesem Fall eine E-Mail an security@contao.org.
