### ISSUE TITLE
automatically use pre-defined densities when none given

### ISSUE THREAD

**Issue by fritzmg** [contao/core#8171]
Contao >= 3.4 offers to possibility to use auto-generated responsive images and image densities. However, you would always need to have a pre-defined image size setting defined.

But if an editor needs to or wants to set the size of an image anywhere individually, he cannot rely on the pre-defined image size settings and thus would need to use the regular image size modes (`proportional`, `box`, `center_center`, etc.). An image that was generated by Contao this way will just be a plain image in the given size, without any additional densities available and thus will not look good on devices with higher dppx.

I think it would be useful if you could define a default density set (`1x,2x,3x`) somewhere in Contao, e.g. the system settings, which would be used by the `Picture::create` function whenever there are no densities and no further image sizes defined.

Unfortunately it's also rather cumbersome to provide this functionality with an extension, since there are no suitable Hooks for that as far as I can see.

**Comment by Toflar** [comment]
I don't get why the admin cannot create such image size settings for the user?

**Comment by fritzmg** [comment]
See the above description: 

> But if an editor needs to or wants to set the size of an image anywhere individually, he cannot rely on the pre-defined image size settings and thus would need to use the regular image size modes.

I hope you are not suggesting, that if an editor wants to define a custom image size, he should first send an e-mail to the administrator of the website, so that he can define an responsive image size setting for each individual image. _Every time_ an editor wants to do that ;)

**Comment by Toflar** [comment]
> I hope you are not suggesting, that if an editor wants to define a custom image size, he should first send an e-mail to the administrator of the website, so that he can define an responsive image size setting for each individual image. Every time an editor wants to do that ;)

Yes, I am. This is exactly the way to go because the editors don't get the responsive image settings usually and then they configure a whole lot of bulls**t :) And if you do have editors that understand the settings, you can also just allow them to edit the image size settings themselves?

**Comment by fritzmg** [comment]
Extension to provide said functionality:

* [[default_densities](https://contao.org/en/extension-list/view/default_densities.en.html)]
* [fritzmg/contao-default-densities](https://github.com/fritzmg/contao-default-densities)

**Comment by fritzmg** [comment]
> Yes, I am. This is exactly the way to go because the editors don't get the responsive image settings usually and then they configure a whole lot of bulls**t :) And if you do have editors that understand the settings, you can also just allow them to edit the image size settings themselves?

I don't get your point. The point here is not to allow editors to fiddle around with pixel densities or responsive image sets. The point is to allow them to set the (base/desktop) size of an image freely whenever they want to (which, by default, Contao does allow them to do anyway, otherwise the options wouldn't be there, wouldn't they?) and still make the images look good on devices with higher dppx.

**Comment by leofeyer** [comment]
I am with @Toflar on this one.

**Comment by fritzmg** [comment]
@leofeyer to paraphrase: so your philosophy is, if an editor uses any of these resizing modes:

![defaultmodes](https://cloud.githubusercontent.com/assets/4970961/11978769/50aa2502-a98e-11e5-9761-e75e119ab0cb.png)

Contao should definitely never ever try to generate images and the accompanying markup so that those images do not look awful on devices with higher dppx as well?

**Comment by leofeyer** [comment]
No, I was referring to the "the admin can create the image sizes for the users" part.

**Comment by fritzmg** [comment]
But that's not my point of this ticket. If an editor needs set a custom image size of any content element, news or event entry, for whatever reason (e.g. because the design/layout allows them to set the size freely and the used images vary in proportions) he _will_ use these resizing modes, don't you agree?

**Comment by leofeyer** [comment]
Maybe. Or they will just ask the site admin to create another image size.

**Comment by fritzmg** [comment]
For every image, every time? I very much doubt it will ever work that way in real life ;). This could potentially happen for every content element and every news entry and every event entry. And I also doubt it's the philosophy of Contao to be a cumbersome CMS where you need to contact the site admin every time you want the image to look good in the frontend for freely sized images.

**Comment by leofeyer** [comment]
@contao/developers /cc

**Comment by Toflar** [comment]
It took me like 10 times reading the initial issue until I got the problem. I think what @fritzmg is asking for is if you e.g. have a `500px x 500px` image and you set the thumbnail to be `200px` `wide` and `proportional` you would get the image resized to `200px x 200px` on any device. Even if in that case it would be possible to provide a `2x` image as you can easily create a `400px x 400px` thumbnail out of a `500px x 500px` original image. Is that right, @fritzmg? If not, then I'm sorry but I still don't get the point.

**Comment by fritzmg** [comment]
Even if it's somehow part of the guidlines of using Contao to refrain from using the regular image resizing modes, why are they there in the first place (an editor might ask). Also they are used in the COD as well - look at http://demo.contao.org/en/media-elements.html for instance with any high DPI device (e.g. a smartphone) - the images look awful because the size of the gallery is simply set within the Content Element, instead of using a image size setting:

![highdpi](https://cloud.githubusercontent.com/assets/4970961/11979045/68869fe6-a990-11e5-94f5-b413209d35fd.png)

Whereas if you were able to set default densities somewhere, these images would also include a `srcset` with, for instance `1x, 2x, 3x` densities.

**Comment by fritzmg** [comment]
@Toflar yes, that is what I meant :)

I am simply talking about the ability to set default pixel densities (e.g. in the system settings) so that any image, that is resized by Contao with the regular resize modes (`proportional`, `center_center`, etc.) instead with an image size setting (which might have some pixel densities defined already) will or might look good on devices with higher dppx as well (as long as the resoultion of the original image is high enough).

**Comment by ausi** [comment]
IMO a default density set would not be the best solution to this problem. What about image size settings that allow to override the dimensions? So an admin could create an overridable image size with the density settings and let the user enter the dimensions in the content element.

**Comment by fritzmg** [comment]
@ausi sounds good too, but how would you set the image resizing mode then? Currently there is just one select for the image size setting / resize mode.

**Comment by ausi** [comment]
The admin would set the resize mode. If the user should be able to select between resize modes, the admin could create one image size for every allowed resize mode.

**Comment by Toflar** [comment]
I agree this is an issue that needs to be solved.

Just as a side note:

As this is a new feature it would go into 4.2 at the earliest so this issue should be moved to `core-bundle`. @ausi is already working on converting our old classes to proper unit testable services in https://github.com/contao/core-bundle/pull/342 so maybe you guys can work together there to enhance the functionality in 4.2?

**Comment by fritzmg** [comment]
> The admin would set the resize mode. If the user should be able to select between resize modes, the admin could create one image size for every allowed resize mode.

Yeah I guess so. Currently the image size setting support only 3 different resizing modes anyway, so it won't be much of a hassle to provide these settings to the user/editor.

**Comment by leofeyer** [comment]
We have discussed this at the developer's meeting in July 2016 and we are planning to add a theme setting that allows to define default densities, which are then applied to the "old" resize modes.

**Comment by leofeyer** [comment]
See core-bundle#554.
