### ISSUE TITLE
Contao 3.5.6 TinyMCE textcolor

### ISSUE THREAD

**Issue by EDsolution** [contao/core#8176]
Hi.
How can I enable font color option / picker in TinyMCE?

Thanks.

**Comment by aschempp** [comment]
you should probably look at the tinyMCE documentation: https://www.tinymce.com

**Comment by EDsolution** [comment]
Well I have added "forecolor backcolor" to toolbar in tinyNews.php but nothing happens in Contao.

**Comment by leofeyer** [comment]
Please refer to the [forums](https://community.contao.org/en/) for this kind of questions.
