### ISSUE TITLE
Allow custom eval's which get passed to widgets

### ISSUE THREAD

**Issue by Fuzzyma** [contao/core#8177]
Is there any possibility to pass custom options to widgets used in the dca?
Example:
One writes a color picker which can be used in Frontend and Backend.
To use it in the Backend, you write `inputType => 'color'` or similar.
Sometimes you want to pass options to the colorpicker e.g. `grayscale:true`. I found no possibility to do that.It would be nice to pass this options via the `eval`-entry or another custom option.
So you would end up like this:

```php
$GLOBALS['TL_DCA']['myPaintModule']['fields']['gray1'] = array(
    'label'     => 'someLabel'
    'inputType' => 'color',
    'eval'      => array('tl_class'=>'clr w50', 'grayscale' => true),
    'sql'       => "something"
);
```

**Comment by aschempp** [comment]
`eval` is the correct place, but the widget obviously needs to support such an option (and the color picker does not)…

**Comment by Fuzzyma** [comment]
I chose color picker as an example for any other widget. So let's say the
widget DOES support such an option: at which place can I read the values
from eval? I dumped the whole object in the widget class and didn't find
any hint

Andreas Schempp <notifications@github.com> schrieb am Di., 05.01.2016,
17:13:

**Comment by aschempp** [comment]
The conversion from DCA to widget data happens in [`Widget::getAttributesFromDca()`](https://github.com/contao/core/blob/master/system/modules/core/library/Contao/Widget.php#L1344). As you can see, the whole `eval` data is passed to the widget attributes, which is later on used as constructor argument for the widget class. What each widget does with those values is up to the class constructor method…

**Comment by Fuzzyma** [comment]
Thats it - A big thanks!
Mnemonic: **All eval options are passed as array to the widget constructor**
