### ISSUE TITLE
Invalid/non-focusable form controls for core and 3rd party content elements

### ISSUE THREAD

**Issue by NicolasSchneider** [contao/core#8180]
Hello all,

please see https://github.com/madeyourday/contao-rocksolid-custom-elements/issues/60 for the beginning of this discussion. This doesn't seem to be exclusively a 3rd party bug, so I'm opening an issue here.

Since Contao 3.5.6, I'm getting `An invalid form control with name='...' is not focusable.` in the console all over the place. At first it was only `madeyourday/contao-rocksolid-custom-elements`, but it happens on newly created "Text" type content elements as well.

The issue seems to stem from HTML5 form validation on hidden/non-displayed form controls and **is not occurring on a clean installation**.

**Comment by leofeyer** [comment]
See #8131.
