### ISSUE TITLE
tl_user::dateAdded should have eval->doNotCopy->true

### ISSUE THREAD

**Issue by Toflar** [contao/core#8185]
Same applies for tl_member.

**Comment by Aybee** [comment]
:+1:  Yes, I also recognized that just today after copying a user to a new user.

**Comment by leofeyer** [comment]
I have found a couple of other fields which should not be copied either IMHO:

* `tl_member.dateAdded`
* `tl_member.lastLogin`
* `tl_member.currentLogin`
* `tl_member.loginCount`
* `tl_member.locked`
* `tl_member.session`
* `tl_member.createdOn`
* `tl_user.dateAdded`
* `tl_user.lastLogin`
* `tl_user.currentLogin`
* `tl_user.loginCount`
* `tl_user.locked`
* `tl_user.session`

@contao/developers Any objections against adding the "do not copy" flag to all of them?

**Comment by Toflar** [comment]
I agree.

**Comment by aschempp** [comment]
Agreed, but will they be initialized with the DCA default value? E.g. for `loginCount`?

**Comment by leofeyer** [comment]
Yes, they will.

**Comment by leofeyer** [comment]
Fixed in 1ee28631e57f54c1f1fc4759357c26f2e153a7f5.
