### ISSUE TITLE
3.5.5 error with 'fixed rendering of grouped checkboxes'

### ISSUE THREAD

**Issue by Anke** [contao/core#8190]
The result of this fix is checkboxes marked 'grouped' have vanished. In the FE there are only fieldsets with legends but no checkboxes. I have to fix all forms with once grouped checkboxes. If the grouping option is leading to errors and if it isn't necessary to use it, then why do we have it?

**Comment by leofeyer** [comment]
?

**Comment by Anke** [comment]
Jo, mal schnell auf Deutsch. Ich kann das in einer aktuellen 3.5.6 Installation nicht reproduzieren. 

Aber als ich letztens ein Update von ? auf 3.5.6 durchgeführt habe, waren Checkboxen im FE auf einmal unsichtbar, nur der Fieldsetrahmen war zu sehen. Wie ich festgestellt hatte, war das in den Formularen der Fall (es waren leider viele), bei denen die Option Gruppe aktiviert war. Daher habe ich mich gefragt, warum es diese Option gibt, wenn sie keine (mir bekannte) Funktion hat und ggf. zu Fehlern führt.

**Comment by Aybee** [comment]
Die Gruppe bietet die Möglichkeit um die nachfolgenden INPUTS nochmals ein FIELDSET mit LEGEND zu legen.
```html
<div class="widget widget-checkbox">
  <fieldset class="checkbox_container" id="ctrl_22">
    <legend>checkbox</legend>
    <input type="hidden" value="" name="checkbox">

    <fieldset>
      <legend>group 1</legend>
      <span><input type="checkbox" value="v1" class="checkbox" id="opt_22_1" name="checkbox[]"> <label for="opt_22_1" id="lbl_22_1">l1</label></span>
      <span><input type="checkbox" value="v2" class="checkbox" id="opt_22_2" name="checkbox[]"> <label for="opt_22_2" id="lbl_22_2">l2</label></span>
    </fieldset>

    <fieldset>
      <legend>group 2</legend>
        <span><input type="checkbox" value="v3" class="checkbox" id="opt_22_4" name="checkbox[]"> <label for="opt_22_4" id="lbl_22_4">l3</label></span>
        <span><input type="checkbox" value="v4" class="checkbox" id="opt_22_5" name="checkbox[]"> <label for="opt_22_5" id="lbl_22_5">l4</label></span>
    </fieldset>

  </fieldset>
</div>
```
Evtl. wurde da beim Update irgendwas falsch interpretiert, sodass "Gruppe" dort angehakt war.
