### ISSUE TITLE
Kalender Kopie

### ISSUE THREAD

**Issue by OppaBredow** [contao/core#8191]
Wenn ich einen bestehenden Kalender kopiere, dann setzt er alle Beginn-Daten der Kopie auf den heutigen Tag. Also auch Neujahr, Ostern usw. Es wäre besser, auch die Termine mit zu übernehmen.

**Comment by Aybee** [comment]
Diverse Felder stehen auf `doNotCopy` https://github.com/contao/core/blob/master/system/modules/calendar/dca/tl_calendar_events.php#L225

Du kannst das in deiner dcaconfig überschreiben.

Ob es jetzt Sinn macht das Standartverhalten zu ändern weiß ich nicht. Will man das Datum usw. beim Kopieren von einzelnen Events oder eines Kalenders im Regelfall behalten oder nicht? Das wäre die Frage.

**Comment by OppaBredow** [comment]
Ich denke mal als Standard im Regelfall behalten. Stimmt das Datum, hast du keine Arbeit. Stimmt es nicht, musst du sowieso eintragen. Du kannst also nur gewinnen. Selbst wenn du aus 01.01.2015 ein 01.01.2016 machen musst, du gewinnst.

**Comment by Samson1964** [comment]
Beim Kopieren innerhalb eines Kalenders will man das Datum wohl i.d.R. nicht beibehalten. Allerdings würde es auch nicht stören, wenn es mitkopiert würde, weil man es ohnehin immer ändern muß.

Beim Kopieren eines ganzen Kalenders will man dagegen sicher das Datum meist behalten. Ansonsten ergäbe das ganz auch keinen Sinn, wenn alle Datumsangaben plötzlich falsch sind. Und wie OppaBredow schon dargestellt hat, macht es mehr Sinn die Datumsangaben beizubehalten, weil es deutlich weniger Nacharbeit für den Anwender bedeutet.

Beide Fälle betrachtet, wäre also doNotCopy = false die deutlich zeitsparendere Variante.

**Comment by OppaBredow** [comment]
Entschuldigung, habe mich verdrückt. Ich möchte noch hinzufügen, dass beim Eintragen des Starttermins, sich der Endtermin automatisch auf einen Tag nach dem Starttermin legen sollte. Das wäre logisch und zweckmäßig.

**Comment by leofeyer** [comment]
Siehe #7931.
