### ISSUE TITLE
rel="" in einer Tabelle wird nicht verarbeitet

### ISSUE THREAD

**Issue by mecintosch** [contao/core#8196]
rel="" sollte in data-lightbox umgewandelt werden.
Außerhalb einer Tabelle auf der selben Seite läuft es.

**Comment by Aybee** [comment]
Gehe ins Forum und beschreibe dein Problem dort ein wenig genauer. Wenn ein Bug gefunden wurde komme hierhin zurück.

**Comment by fritzmg** [comment]
Post the HTML code of the text element you want to save. (I presume it's a regular text element?)

**Comment by mecintosch** [comment]
In meiner Tabelle steht ein Link mit rel="lightbox"
<table>
<tbody>
<tr>
<td><a href="#" rel="lightbox">test</a></td>
</tr>
</tbody>
</table>

Der Link sollte in der Ausgabe allerdings so aussehen:
<a href="#" data-lightbox="" class="cboxElement">test</a>

**Comment by fritzmg** [comment]
Post the HTML code in [code tags](https://help.github.com/articles/markdown-basics/#code-formatting) or on pastebin.

**Comment by fritzmg** [comment]
I cannot reproduce it in the Contao Online Demo. If you insert your HTML code in a regular Contao text element there, `rel="lightbox"` gets converted to `data-lightbox=""` in the Frontend.

**Comment by mecintosch** [comment]
Ja, bei einer Tabelle mit dem Elementtyp Text, aber nicht beim Elementtyp Tabelle.

![bildschirmfoto 2016-01-19 um 14 18 36](https://cloud.githubusercontent.com/assets/16761621/12419665/d3e24088-beb7-11e5-9380-a09ed3fb0deb.png)

**Comment by fritzmg** [comment]
Indeed, `\StringUtil::toHtml5(…)` - which converts `rel="lightbox"` to `data-lightbox=""` - is currently only applied to `text` fields.

**Comment by fritzmg** [comment]
@mecintosch why don't you just write `data-lightbox` instead of `rel="lightbox"` in the first place?

**Comment by leofeyer** [comment]
Die `StringUtil::to*()`-Funktionen sind dafür da, um den von TinyMCE erstellen Code in das richtige Format zu übersetzen. Sie sollten nicht blind auf alles angewendet werden.

Die Lösung hat @fritzmg bereits genannt: Schreib einfach das `data-lightbox`-Attribut in die Zelle.
