### ISSUE TITLE
Maximale Frontend-Breite wird ignoriert, wenn size leer ist

### ISSUE THREAD

**Issue by Samson1964** [contao/core#8197]
Ich bin vor einigen Wochen von Contao 3.2. auf 3.5.6 umgestiegen. Jetzt habe ich festgestellt, daß einige Bilder in Inhaltselementen in voller Größe statt mit maximaler Frontend-Breite angezeigt werden. Ursache ist die Spalte size in tl_content. Wenn size leer ist (Standard in Contao 3.2), rechnete Contao 3.2 das Bild auf die maximale Frontend-Breite proportional herunter, wenn das Bild größer war. Contao 3.5.6 macht stattdessen gar nichts mehr und stellt das Bild im Original dar. Damit geht die Abwärtskompatibilität verloren.

Contao 3.5.6 hat aber nicht alles "vergessen". Ist die Spalte size mit einem (ungültigen) Wert gefüttert, z.B.
```
a:3:{i:0;s:0:"";i:1;s:0:"";i:2;s:12:"prapartianol";}
```
wird das Bild wie in 3.2 proportional heruntergerechnet.

**Comment by leofeyer** [comment]
Wie lässt sich das in der Onlinedemo reproduzieren?

**Comment by Samson1964** [comment]
Gar nicht. Dazu müsste man ein Update von Contao 3.2 auf 3.5 machen. Anleitung für 3.5 ohne vorheriges Update:

- Bildelement anlegen ohne Größenangabe 
- In tl_content bei diesem Element den Inhalt von size löschen 

Damit hätte man jetzt Contao 3.2 nachgebaut.

**Comment by fritzmg** [comment]
> Wenn size leer ist (Standard in Contao 3.2)

Eigentlich ist das auch in Contao 3.2 _nicht_ Standard. In allen Contao Versionen wird dieses Feld zwar mit `''` per SQL befüllt - legst du das jeweilige Element jedoch über das Backend an, wird unter Contao 3.2
```
a:3:{i:0;s:0:"";i:1;s:0:"";i:2;s:12:"proportional";}
```
und unter Contao 3.5
```
a:3:{i:0;s:0:"";i:1;s:0:"";i:2;s:0:"";}
```
in das Feld geschrieben.

_Allerdings_ habe ich immer wieder von User gelesen, wo unter Contao <3.3 folgendes in das Feld geschrieben wurde:
```
a:1:{i:0;s:12:"proportional";}
```

Wenn das Feld allerdings _komplett_ leer ist, dann muss das theoretisch andere Gründe bei dir haben.

**Comment by Samson1964** [comment]
Ich hatte bei Contao mal mit 3.0.6 angefangen. Deshalb kann es auch sein, das dieses Verhalten vor 3.2 usus war. Nicht ganz auszuschließen: Bei der Migration der Nachrichten habe ich nicht das Feld size befüllt. Kann aber auch nicht sein, da es auch bei Bildern auftritt, die ich über das Backend hinzugefügt habe.

Aber egal wie das leere size-Feld entstanden ist: Contao 3.5 ist an der Stelle nicht mehr abwärtskompatibel. Bei leerem size-Feld wurde früher das Bild ggfs. auf die max. Frontendbreite heruntergerechnet. Wohl seit dem Umbau mit den responsiven Bildern ist das nicht mehr so.

**Comment by fritzmg** [comment]
Ja, da hast du Recht. Der Bug bzw. dieser backwards compatibility break wurde in Contao `3.5.3` hinzugefügt: [3.5.3/system/modules/core/library/Contao/Controller.php#L1458](https://github.com/contao/core/blob/3.5.3/system/modules/core/library/Contao/Controller.php#L1458) - `$intMaxWidth` wird erst innerhalb von `is_array($size)` gesetzt. In allen Versionen davor, also Contao `3.5.2` und niedriger: [3.5.2/system/modules/core/library/Contao/Controller.php#L1436](https://github.com/contao/core/blob/3.5.2/system/modules/core/library/Contao/Controller.php#L1436) (zumindest bis Contao `3.2.0`, weiter habe ich es nicht überprüft) wird `$intMaxWidth` _auf jeden Fall_ gesetzt - je nachdem ob man sich im Backend befindet oder was in der config angegeben wurde.

Dieser Bug wirkt sich auch negativ auf das Backend aus: ist das `size` Feld leer (warum auch immer), werden die Bilder im Backend ebenso nicht mehr auf 320px verkleinert, sondern in deren Originalgröße ausgegeben.

Der Block
```php
if ($intMaxWidth === null)
{
	$intMaxWidth = (TL_MODE == 'BE') ? 320 : \Config::get('maxImageWidth');
}
```
sollte also wieder _vor_
```php
if (is_array($size))
{
    …
```
gesetzt werden.

**Comment by leofeyer** [comment]
@ausi Was sagst Du dazu?

@contao/developers /cc

**Comment by ausi** [comment]
Soweit ich das sehe, sollten wir d0c2dae8ef50081e1605e83ad61b11b7a87bb569 reverten und stattdessen den fix von https://github.com/contao/core/issues/7945#issuecomment-183747138 einbauen:

```php
$size = deserialize($arrItem['size'], true) + array(0, 0, 'crop');
```

**Comment by leofeyer** [comment]
Behoben in 4fdbe3fdf8e53e6954bfc48121ebf994749d98b3.
