### ISSUE TITLE
[3.5.6] Load initconfig.php before the initializeSystem hook

### ISSUE THREAD

**Issue by Tastaturberuf** [contao/core#8199]
I want to change the database for local development in the initconfig.php. But an extension use the initializeSystem hook and use the "old" mysql credentials from localconfig.php.

**Comment by aschempp** [comment]
You should do that in the localconfig file…

**Comment by Tastaturberuf** [comment]
Is that safe when something changes in the backend settings?

**Comment by aschempp** [comment]
If you don’t add it to the comment start and stop section, yes

**Comment by Tastaturberuf** [comment]
Ok thanks, i don’t know that.
