### ISSUE TITLE
Problem mit Bereitstellung der benötigten Bildgrößen

### ISSUE THREAD

**Issue by frontendschlampe** [contao/core#8201]
Ich bin hier mal auf ein kleines Problem gestoßen, was meiner Meinung nach ein Bug ist und sehr unschön - folgende Voraussetzungen:

1. Originalbild in der Dateiverwaltung 2000 x 2000 px
2. Polyfill aktiviert
3. Imageset angelegt mit der Bildgröße (Exaktes Format) 1000 x 500 px in den Auflösungen 1x, 2x, 3x

**Theorie** ergibt folgende Bildgrößen: 1000 x 500 px, 2000 x 1000 px, 3000 x 1500 px **aber** das Bild hat ja im Original nur 2000 x 2000 px, somit müsste das Originalbild für die Auflösung 3x interpoliert werden, was Qualitätsverluste zur Folge hätte

**Praxis** hier werden die Bilder für 1x und 2x erwartungsgemäß erstellt, aber statt das Bild für die Auflösung 3x wegzulassen oder interpoliert zur Verfügung zu stellen, wird das Originalbild genutzt

Hier liegt somit der Fehler, denn das ist ein absolutes Fehlverhalten. Es gibt nur die o.g. 2 Möglichkeiten:

1. Bild interpoliert ausgeben (könnte man ggfs. auch als Option machen)
2. Bild in der Auflösung 3x gar nicht ausgeben

/cc @fritzmg

**Comment by ausi** [comment]
Ich kann den Fehler in Contao 3.5.6 nur reproduzieren, wenn das resultierende Bild größer als die „Maximale GD-Bildbreite“ oder „Maximale GD-Bildhöhe“ werden würde. Ich finde das Orginal-Bild sollte dann ausgegeben aber die `x`-Angabe dementsprechend korrigiert werden, damit sie korrekt ist.

Ich finde auch die Option das interpolieren bzw. hochskalieren deaktivieren zu können sehr wichtig. Im Moment verschenken wir hier viel server-performance und bandbreite. Allerdings würde ich das eher als Feature ansehen, für Contao 4.2?

**Comment by frontendschlampe** [comment]
Ich muss @ausi zustimmen - es lag an den GD-Größen. Verflixt ... Danke für die Lösung @ausi ;-)

Aber trotz alledem wäre das Weglassen, oder wie von @ausi beschrieben, wenigstens die Anpassung der Proportionen wichtig.

Die Option des Hochskalierens ist ist auch in meinen Augen dann eher für Contao 4 zu sehen.

**Comment by leofeyer** [comment]
Siehe #8220.

**Comment by Aybee** [comment]
> @frontendschlampe 
2. Polyfill aktiviert

Obwohl der Hilfetext hier so lautet:
> Die Option _Das Image-Polyfill laden_ muss im Seitenlayout aktiviert sein.

AFAIK wird das Poyfill nicht benötigt, es sei denn, man möchte alte Browser unterstützen. Korrigiert mich, wenn ich falsch liege.

**Comment by ausi** [comment]
Das ist korrekt, der Polyfill wird nur für ältere Browser benötigt (z. B. IE11). Moderne Browser unterstützen `srcset` und `<picture>` nativ.
