### ISSUE TITLE
Ansichtsproblem auf 5k Display in Firefox 43.0.4 & Safari 9.0.3

### ISSUE THREAD

**Issue by frontendschlampe** [contao/core#8202]
Ich weiß nicht, ob man das nachfolgende Problem irgendwie lösen kann, aber vielleicht hat je jemand eine Idee.

**Voraussetzungen**

- Originalbild 1024 x 682 px
- Bildgrößen Haupteinsstellung Breite 267 px, Höhe 0, Größenänderungsmodus proportional, Zoom 0, Pixeldichte 1x, 1.5x, 2x und zusätzlich noch eine identische Untereinstellung mit dem Media-Query (min-width:1200px)

**Ergebnis**

in Google Chrome 48.0.2564.82

einfache Auflösung *Ansicht korrekt*
![resp-img_chrome](https://cloud.githubusercontent.com/assets/1232819/12581190/45acf1c2-c435-11e5-9ec0-c8c78be07393.jpg)

5k *Ansicht korrekt*
![resp-img_chrome_5k](https://cloud.githubusercontent.com/assets/1232819/12581192/4c17bc72-c435-11e5-8658-1daf1f6cbe54.jpg)

in Firefox 43.0.4

einfache Auflösung *Ansicht korrekt*
![resp-img_firefox](https://cloud.githubusercontent.com/assets/1232819/12581201/53069b52-c435-11e5-970e-35f261e56e15.jpg)

5k *Ansicht NICHT korrekt*
![resp-img_firefox_5k](https://cloud.githubusercontent.com/assets/1232819/12581204/58c37862-c435-11e5-80e3-69dbe79e64a3.jpg)

in Safari 9.0.3

einfache Auflösung *Ansicht korrekt*
![resp-img_safari](https://cloud.githubusercontent.com/assets/1232819/12581208/5e64c988-c435-11e5-9335-4d5bee6dcdc2.jpg)

5k *Ansicht NICHT korrekt*
![resp-img_safari_5k](https://cloud.githubusercontent.com/assets/1232819/12581212/66c14098-c435-11e5-8abc-601f5e21dec4.jpg)

Im Quellcode steht innerhalb von ```<picture>```: ```<source srcset="...>```und ```<img srcset alt src="...>```

Wenn ich die Untereinstellung rausnehme, dann steht natürlich nur noch ```<img srcset="...>``` und dann passt alles auf allen Browsern.

Sieht ja alles nach einem Browserproblem aus, oder?

**Comment by fritzmg** [comment]
Das ist ein Fehler in FireFox - ich hab dazu schon eine Bug Report submitted: https://bugzilla.mozilla.org/show_bug.cgi?id=1241465

**Comment by leofeyer** [comment]
Hast Du das `respimage.js`-Skript eingebunden?

**Comment by leofeyer** [comment]
P.S.: Ich schließe das Ticket, weil es kein Contao-Bug ist.

**Comment by fritzmg** [comment]
> Hast Du das respimage.js-Skript eingebunden?

Der Bug im FireFox kann durch `respimage` nicht behoben werden (`respimage` greift hier auch gar nicht, soweit ich weiß?). Der Umstand im Safari und Internet Explorer wird mehr oder weniger durch `respimage` "ausgelöst" (aber ohne `respimage` würden diese Browser die sources aus dem `<picture>` Element gar nicht erst verwenden).

**Comment by leofeyer** [comment]
Welcher Feature-Request?

**Comment by fritzmg** [comment]
Der letzte Absatz in meinem Post:

> Hier habe ich @ausi schon vorgeschlagen, dass man z.B. jeder Responsive Imageeinstellung und jeder Bildgröße mit Media Query eine CSS Klasse geben kann, die dann direkt dem <img> gegeben wird. So kann man zumindest dann auch per CSS das Bild auf die richtige Größe zurück resizen lassen - egal wo die Bildgrößeneinstellung eingestzt wird.

Bei Browsern, die das `<picture>` Element nicht unterstützen, tauscht `respimage` ja einfach nur das `src` Attribut des `<img>` auf das passende Bild aus (Abhängig von Media Queries, viewport Größe und Pixeldichte, je nachdem). Dadurch verändern sich aber auch die Ausmaße des Bildes - `respimage` unternimmt hier nichts um die eigentliche Größe (in CSS-Pixel) des Bildes beizubehalten.

Daher muss man die Größe des Bildes zusätzlich auch noch selbst per CSS limitieren/setzen. Da man aber (bei einem CMS wie Contao) potentiell nicht vorhersehen kann, ob und wo ein Redakteur eine vordefinierte Bildgröße einsetzt, lässt sich das mit aktuellen Mitteln nur schwer allgemein umsetzen.

Daher wäre es praktisch, wenn man jeder Bildgrößeneinstellung auch eine CSS Klasse mitgeben könnte, die auf das `<img>` angewandt wird, um, unabhängig davon wo die Bildgrößeneinstellung eingesetzt wird, die Größe des `<img>` per CSS (und Media Queries) fixieren zu können, wenn man möchte.

**Comment by leofeyer** [comment]
@ausi Was sagst Du dazu?

**Comment by ausi** [comment]
Bezüglich `respimage` kann das Problem in den älteren Browsern mit dem [intrinsic-dimension plugin](https://github.com/aFarkas/respimage/tree/gh-pages/plugins/intrinsic-dimension) behoben werden, der Firefox-Bug bleibt damit aber bestehen.

Eine CSS-Klasse pro Bildgröße definieren zu können halte ich für sehr sinnvoll, nicht nur für diesen speziellen Anwendungsfall. In diesem Zuge könnte man auch überlegen das Alias für Bildgrößen (#7520) zu implementieren und standardmäßig eine CSS-Klasse `image-size-{ALIAS}` zu vergeben.

**Comment by fritzmg** [comment]
> Bezüglich respimage kann das Problem in den älteren Browsern mit dem intrinsic-dimension plugin behoben werden

Hm, in meinen Tests hat das allerdings nichts genutzt und soweit ich den Code (und die Beschreibung) von diesem Plugin verstehe, greift das nur bei `<img srcset="…" sizes="…" …>`, nicht bei `<picture …>`.

**Comment by ausi** [comment]
IE11 kann kein `srcset`. Das intrinsic-dimensions Plugin funktioniert in meinen Tests sowohl in IE11 als auch in Safari mit `<picture>`: [codepen.io/anon/pen/PZVvbO](http://codepen.io/anon/pen/PZVvbO?editors=1000)

**Comment by fritzmg** [comment]
Hm, you are right, I don't know what weng wrong in my testings.
