### ISSUE TITLE
Fehlerhafte URL bei News/Event RSS-Feeds - 3.5.6

### ISSUE THREAD

**Issue by Ainschy** [contao/core#8204]
Situation:

Events/News haben eine Weiterleitung auf eine Seite/Artikel
Die Sprache wird der URL hinzugefügt

Der RSS Feed enthält bei diesen Events/News eine URL ohne Sprachenkürzel

News.php
https://github.com/contao/core/blob/master/system/modules/news/classes/News.php#L357-L370

Events.php
https://github.com/contao/core/blob/master/system/modules/calendar/classes/Events.php#L406-L419

Lösung für News.php bei interner Seite:
```
			// Link to an internal page
			case 'internal':
				if (($objTarget = $objItem->getRelated('jumpTo')) !== null)
				{
					if (\Config::get('addLanguageToUrl'))
					{
						$obj = \Pagemodel::findWithDetails($objTarget->pid);
						$strForceLang = $obj->language;
					}
					return $strBase . $this->generateFrontendUrl($objTarget->row(), NULL, $strForceLang );
				}
				break;
```

Das Problem ist in der Demo nachstellbar. Contao 3.5.6

**Comment by Toflar** [comment]
Das ist wohl in der Tat ein Bug. Allerdings ist es unnötig die Daten der Parent-ID zu laden und auch die Prüfung auf `Config::get('addLanguageToUrl')` ist überflüssig, weil das `Controller::generateFrontendUrl()` macht.

Imho müsste das so aussehen:

```diff
if (($objTarget = $objItem->getRelated('jumpTo')) !== null)
{
+    $objTarget->loadDetails();    
-    return $strBase . $this->generateFrontendUrl($objTarget->row());
+    return $strBase . $this->generateFrontendUrl($objTarget->row(), null, $objTarget->language);
}
```

Gilt natürlich auch für den `case` `article` direkt darunter.

**Comment by Ainschy** [comment]
Ok, werde ich ausprobieren. Danke!

**Comment by fritzmg** [comment]
Der letzte Parameter sollte auch auf `true` gesetzt werden.

**Comment by leofeyer** [comment]
Also bei internen Seiten sehe ich ein, dass der Fix notwendig ist, ebenso bei der Weiterleitung auf einen bestimmten Artikel. Problematisch ist nur der Fall "Standardseite":

https://github.com/contao/core/issues/6743#issuecomment-42932519

Wobei der Use-Case, den @aschempp beschreibt, sicherlich nur ein "zufälliges" Feature ist :)

**Comment by aschempp** [comment]
ich hab doch gar nix geschrieben? :D

**Comment by fritzmg** [comment]
@aschempp er meint im verlinkten Kommentar von dir ;)

**Comment by leofeyer** [comment]
So, die Inserttag-URLs werden in 376ecec6beef2ad9cf0877a98f554b3e30536398 korrekt generiert. Allerdings gibt es noch etliche andere Aufrufe von `generateFrontendUrl()` ohne `$blnForceLanguage` und `$blnFixDomain`. Sollten wir die nicht auch anpassen?

Genau genommen sollte `$blnFixDomain` überall auf `true` gesetzt werden, so wie @fritzmg es immer wieder anmerkt. Immerhin ist es in fast allen Fällen ein Bugfix.

@contao/developers /cc

**Comment by Toflar** [comment]
Ich glaube die Fehlerquellen liessen sich auch reduzieren, wenn man da das `PageModel` verwenden würde und `getFrontendUrl()` darauf aufruft. Würden wir die noch anpassen, so dass sie immer die eigene Sprache übergibt als `$blnForceLanguage` kämen wir der Sache wohl näher :)

**Comment by leofeyer** [comment]
Das `PageModel` setzt aber `$blnFixDomain` nicht.

**Comment by Toflar** [comment]
Müsste es aber sinnvollerweise auch, imho?

**Comment by leofeyer** [comment]
Finde ich auch. Sind halt alles BC-Breaks :(

**Comment by leofeyer** [comment]
Den Fix für die Inserttag-URLs habe ich in 709284317edbb898c82f7e8fa80d64dfd68a4d3b schon mal übernommen. Den Rest müssen wir diskutieren.

**Comment by leofeyer** [comment]
Siehe #8238.
