### ISSUE TITLE
Multiple "where"-clause in Model::find()

### ISSUE THREAD

**Issue by Fuzzyma** [contao/core#8205]
Is it really intended, that you have to add the following array to get multiple where clauses:
```php
SomeModel->find([
    'columns' => [
        "foo='bar'",
        "bla=2"
    ]
]);
```

Related lines are in the QueryBuilder (l.68)

```php
		// Where condition
		if ($arrOptions['column'] !== null)
		{
			$strQuery .= " WHERE " . (is_array($arrOptions['column']) ? implode(" AND ", $arrOptions['column']) : $arrOptions['table'] . '.' . $arrOptions['column'] . "=?");
		}
```

A simple `implode` is used.

Why we cannot give an assoziative array instead?
Or at least use the `value`-field for the values?

**Comment by aschempp** [comment]
Associative arrays are not supported. But you can use `value`, you just have to use placeholders in `column`.

**Comment by Fuzzyma** [comment]
Well that would be a feature worth to implement... 

Does placeholders mean I still have to write foo=? 
Because that isn't really better...

**Comment by aschempp** [comment]
yes you have. And the future would be to use Doctrine, so I doubt we will add new features ;-)
