### ISSUE TITLE
HTML entity is corrupted in "custom HTML" module after re-edit

### ISSUE THREAD

**Issue by voxspox** [contao/core#8206]
Contao: 3.5.6
Steps to reproduce:

- create a Custom HTML front end module
- enter `&emsp;` in HTML code field
- the text is highlighted in green
- save
- the text is replace by a single character, highlighted in red

While the site seems to render correctly, I can not see (and read) what I have written before in the HTML code field.

**Comment by leofeyer** [comment]
That's not a bug but the intended behavior. Unicode entities are converted to their UTF-8 equivalent.
