### ISSUE TITLE
change settings icon in "Change Image Size" view has wrong caption and tooltip

### ISSUE THREAD

**Issue by voxspox** [contao/core#8207]
Contao: 3.5.6
**Steps to reproduce:**

- goto theme overview
- click on "edit image size of theme ID .."
- the box shows the theme name, author, revision date and a "change settings" icon with crossed tools
- this icon has the wrong tooltip: "change image size of ID %s" and wrong "alt" attribut

**Comment by leofeyer** [comment]
Fixed in ab624e3e75b2faa8389727accc220a7acbd8126d.
