### ISSUE TITLE
C3: Crash der tl_search

### ISSUE THREAD

**Issue by Anke** [contao/core#8208]
Ich hatte innerhalb kurzer Zeit auf mehreren Kundenwebsites einen Crash der tl_search. 

Wie kann es dazu kommen, sind das ggf. gezielte 'Angriffe' auf die Contao-Suche?

Kann man irgendwie verhinden, dass das Layout beim Auftreten eines solchen Fehlers total verschossen wird, weil unterhalb der Website eine (anders formatierte) Contao-Fehlermeldung erscheint? Fehlermeldungen anzeigen ist jedoch deaktiviert.

Leider habe ich keinen Screenshot gemacht und kann den Fehler auch nicht reproduzieren. In der DB steht dann hinter der tl_search "in Benutzung" (bis ich sie repariere).

Ein Hinweis auf eine korrupte Tabelle wäre eigentlich im Backend nach dem Login wünschenswert, noch idealer wäre eine Mail-Benachrichtigung an den Website-Admin, aber ich fürchte, das ist wohl nicht realisierbar.

Hier die Fehlermeldung:
<pre>[28-Jan-2016 13:50:08 Europe/Berlin] PHP Fatal error: Uncaught exception 'Exception' with message 'Query error: Table './db370127/tl_search' is marked as crashed and should be repaired (SELECT id, checksum FROM tl_search WHERE url='' AND pid='2' LIMIT 0,1)' thrown in 
...system/modules/core/library/Contao/Database/Statement.php on line 295
#0 ...system/modules/core/library/Contao/Database/Statement.php(264): Contao\Database\Statement->query()
#1 ...system/modules/core/library/Contao/Search.php(144): Contao\Database\Statement->execute('', '2')
#2 ...system/modules/core/classes/FrontendTemplate.php(318): Contao\Search::indexPage(Array)
#3 ...system/modules/core/classes/FrontendTemplate.php(124): Contao\FrontendTemplate->addToSearchIndex()
#4 ...system/modules/core/pages/PageRegular.php(190): Contao\FrontendTemplate->output(true)
#5 ...system/modules/core/controllers/FrontendIndex.php(267): Contao\PageRegular->generate(Object(Contao\PageModel), true)
#6 ...index.php(20): Contao\FrontendIndex->run()
#7 {main}</pre>

**Comment by fritzmg** [comment]
> Ich hatte innerhalb kurzer Zeit auf mehreren Kundenwebsites einen Crash der tl_search.

Auf verschiedenen Servern?

> Kann man irgendwie verhinden, dass das Layout beim Auftreten eines solchen Fehlers total verschossen wird, weil unterhalb der Website eine (anders formatierte) Contao-Fehlermeldung erscheint? Fehlermeldungen anzeigen ist jedoch deaktiviert.

Dieser Fehler sollte eigentlich gar nicht im Frontend erscheinen, es sei denn du hast in den Einstellungen die Anzeige der Fehlermeldungen aktiviert.

**Comment by Anke** [comment]
Sagen wir so: Die beiden letzten Male beim selben Hoster, unterschiedliche Kunden. (Shared Server, DomainFactory)

Anzeige der Fehlermeldungen ist nicht aktiviert!

**Comment by Toflar** [comment]
Wenn die php.ini Einstellungen auf dem Server `display_errors = "1"` lauten, dann hilft alles nichts. Da kann Contao nichts machen, weil Fatal Errors nicht unterdrückt werden können. Auszug aus dem PHP Manual:

> Although display_errors may be set at runtime (with ini_set()), it won't have any effect if the script has fatal errors. This is because the desired runtime action does not get executed.

**Comment by Anke** [comment]
Die php.ini kann man bei dF einsehen und ändern. Die Einstellungen lauten:
<code>display_errors = Off</code>
<code>log_errors = Off</code>
<code>error_log = </code>
Habt ihr noch weitere Ideen?

**Comment by Samson1964** [comment]
Ich habe solche Crashs der tl_search etwa 2-3 mal im Jahr (dupilcate entry o.ä.). Im FE erscheint bei mir nur eine weiße Seite. Ich bin auch bei df) und display_errors ist on und in Contao habe ich Fehlermeldungen abgeschaltet. Bei mir haben die Contao-Einstellungen das Sagen ;-)
Die Fehler in der Datenbank entstehen wohl durch gleichzeitige Zugriffe auf ein und denselben Datensatz. Ist ja doch recht viel los bei mir - auf der Homepage ca. 64.000 Seitenabrufe am Tag. Auch mein Counter-Modul ist auf diese Art und Weise schon öfter gecrasht.

**Comment by Anke** [comment]
Seltsam, display_errors steht bei mir bei allen Shared Hosting Paketen bei dF standardmäßig auf off.

Die Websites, bei denen die tl_search zuletzt gecrashed ist oder wurde, sind nicht sonderlich frequentiert.

**Comment by leofeyer** [comment]
Dieses Problem hat höchstwahrscheinlich nichts mit Contao zu tun. MyISAM-Tabellen können sehr leicht crashen; weitere Informationen hier: http://dba.stackexchange.com/questions/15075/why-do-mysql-tables-crash-how-do-i-prevent-it#15079
