### ISSUE TITLE
ModuleRegistration does not throw an error when username and password are identical

### ISSUE THREAD

**Issue by skolarianer** [contao/core#8209]
The following comparison fails:

`// Check whether the password matches the username`
`if ($objWidget instanceof \FormPassword && $varValue == \Input::post('username'))`
`{`
`	$objWidget->addError($GLOBALS['TL_LANG']['ERR']['passwordName']);`
`}

Maybe related to #8144

**Comment by leofeyer** [comment]
Fixed in cecbe762d636b0f829bcbb30d33a95090c2b9140.
