### ISSUE TITLE
ce_hyperlink mit Filepicker

### ISSUE THREAD

**Issue by asaage** [contao/core#8213]
Im speziellen Fall habe ich ein Leerzeichen im Ordnernamen...

Bei der Auswahl einer Datei über den Filepicker (Contentelement Hyperlink) bekomme ich 
```Bitte geben Sie ein gültiges URL-Format ein und kodieren Sie Sonderzeichen!```
das sollte entweder automatisch passieren, oder in der Dateiverwaltung sollten Sonderzeichen direkt beim Anlegen oder Umbenennen ersetzt werden.

Ordner mit Umlauten kann ich zb. nicht anlegen - mit Leerzeichen aber schon.
Weiß nicht an welcher Stelle man da besser ansetzt.

**Comment by asaage** [comment]
bin jetzt eher dazu übergegangen ce_download zu verwenden, weil mir das ermöglicht, die Dateien auch später noch in der Dateiverwaltung umzusortieren - (was bei ce_hyperlink nicht der Fall ist).
Ein Save-Callback mit urlencode würde mir sicherlich die Links aus dem Seitenwähler zerschießen {{link_url::32}}  != %7B%7Blink_url%3A%3A32%7D%7D

**Comment by leofeyer** [comment]
> Ein Save-Callback mit urlencode würde mir sicherlich die Links aus dem Seitenwähler zerschießen {{link_url::32}} != %7B%7Blink_url%3A%3A32%7D%7D

Das ist korrekt.

**Comment by asaage** [comment]
vielleicht doch lieber Leerzeichen beim Anlegen von Ordnern in der Dateiverwaltung mit underscores replacen?
oder den Filepicker etwas anderes Ausspucken lassen z.B. {{file_url::123}} ?
oder den Save-Callback mit etwas mehr Logik versehen...
Wie gesagt - ich hab immernoch keinen Plan, welcher Weg am sinnvollsten ist...

**Comment by asaage** [comment]
Ich glaub es wäre gut, wenn der Rückgabewert des Filepickers ein Insert-Tag wäre um die Vorteile des DB-Filesystem auch nutzen zu können.
In der StringUtil gibt es die Function insertTagToSrc, die das dann möglicherweise auflösen könnte.
Die Übernahme von meta->titel in den Linktext wäre vielleicht auch nicht verkehrt.

**Comment by Aybee** [comment]
:+1: 
Der filepicker im TinyMCE macht das bereits und sogar noch besser. Man sieht keinen Inserttag, sondern den richtigen aktuellen Pfad. Wenn man dann in der Dateiverwaltung den Namen der Datei ändert, sieht man im Tiny den geänderten Namen.

Der filepicker im Feld **Bildlink-Adresse** macht das **nicht**. Ich halte das für einen **Bug**. Das könnte gefährlich sein, weil man sich darauf verlässt, dass man die Dateien in der Verwaltung umbenennen kann.

**Comment by asaage** [comment]
> Der filepicker im TinyMCE macht das bereits

Darüber hatte ich mich schon gewundert - gerade weil nirgendwo was von dem Inserttag zu sehen ist.

**Comment by leofeyer** [comment]
Ich habe gerade versucht, die automatische Kodierung zu implementieren. Ich scheitere aber daran, dass wir nicht nur ganze URLs, sondern auch Teile davon (z.B. einen Query-String) erlauben.

**Comment by asaage** [comment]
Ich würde beim Filepicker nochmal das Inserttag ins Spiel bringen wollen.
Die Begründung, warum das [hier](https://github.com/contao/core/issues/7850#issuecomment-157762830) nicht so ist verstehe ich nicht ganz.

**Comment by fritzmg** [comment]
Ich verstehe es auch nicht - und warum es jetzt plötzlich auch schon wieder als feature von `4.2.0` entfernt wurde. Es sollte doch absolut nichts dagegen sprechen, dass das FilePicker Widget und auch der Link Wizard im TinyMCE einen `{{file::…}}` Insert Tag liefern sollte, wenn eine Datei ausgewählt wurde?

**Comment by leofeyer** [comment]
> und warum es jetzt plötzlich auch schon wieder als feature von 4.2.0 entfernt wurde.

Weil das Ticket jetzt erstmal "up for discussion" ist, bis wir uns auf eine vernünftige Implementierung geeinigt haben. Die generelle Verwendung des `{{file::}}`-Tags kommt logischerweise nicht in Frage, weil der TinyMCE dann keine Bilder mehr anzeigen könnte. (Er kann sie natürlich schon anzeigen, aber erst nach dem ersten Speichern und nicht direkt nach der Auswahl.)

**Comment by fritzmg** [comment]
Es geht hier (im speziellen) ja nicht um den TinyMCE. Es geht um den Picker.

**Comment by Aybee** [comment]
> weil der TinyMCE dann keine Bilder mehr anzeigen könnte. (Er kann sie natürlich schon anzeigen, aber erst nach dem ersten Speichern und nicht direkt nach der Auswahl.)

Ich meine das wäre eher zu verschmerzen, als wenn die Zuordnungen verloren gingen.

**Comment by fritzmg** [comment]
I have released a small extension that implements the `{{file::*}}` insert tag behaviour as a `load_` and `save_callback` for all `url` and `imageUrl` fields in the core:

* ER2: [filepicker_uuid](https://contao.org/en/extension-list/view/filepicker_uuid.10000009.en.html)
* GitHub: [https://github.com/fritzmg/contao-filepicker-uuid](fritzmg/contao-filepicker-uuid)

@asaage diese Extension behebt allerdings nicht dein Problem - zumindest nicht ganz. Wenn du einen Link zu einer Datei zum ersten mal hinzufügst, musst du die URL selbst encoden (zB `+` oder `%20` statt Leerzeichen verwenden). Danach encodet die Extension den Pfad automatisch beim Konvertieren des Insert Tags zurück zum Pfad (`onload_callback`).

**Comment by Aybee** [comment]
Der zweite Link geht nicht. Meintest du den hier?
https://github.com/fritzmg/contao-filepicker-uuid

**Comment by fritzmg** [comment]
Sorry, fixed.

**Comment by discordier** [comment]
AFAIR, this is a reoccurring discussion.
We had this discussion several times for the file upload in regard to automatic renaming of files etc.
We came to the conclusion that we simply can not convert the files correctly, as there are way to many things to keep in mind regarding allowed chars in file names in respect to user locale, operating system etc.
Therefore this should be closed with "will not fix". Sorry about that.

**Comment by fritzmg** [comment]
? @discordier this is not about the automatic renaming of files in the uploader. This issue evolved to a discussion about why any of the file pickers do not use `{{files::*}}` insert tags.

**Comment by fritzmg** [comment]
@discordier btw. issue #7850 was closed by @leofeyer since he didn't want to have two tickets discussing the same thing ( https://github.com/contao/core/issues/7850#issuecomment-210016801 ). Any separate issue would have probably been closed too). But now this issue was closed also.

**Comment by asaage** [comment]
#8578
