### ISSUE TITLE
Kommentare können im Backend nicht kopiert werden

### ISSUE THREAD

**Issue by michelbalzer** [contao/core#8214]
Im Backend können die Kommentare mittels „Mehrere bearbeiten“ nicht kopiert werden, obwohl es dafür einen Button gibt. Fehlermeldung im System-Log: <code>Invalid command "copyAll"</code>. Insofern sollte der Button verschwinden oder die Funktion erlaubt sein. Das Duplizieren-Icon ist ja auch nicht vorhanden. (Ich wollte Kommentare kopieren um was im FE-Layout zu testen.)

Reproduzierbar in der Demo:

1. http://demo.contao.org/contao/main.php?do=comments&act=select aufrufen,
2. einen oder mehrere markieren,
3. auf „Copy“ oder „Kopieren“ klicken,
4. Fehlermeldung sehen,
5. ins System-Log schauen.

(Vermute mal, dass das in der /system/modules/comments/dca/tl_comments.php steht

**Comment by leofeyer** [comment]
Behoben in 9ff8521490389a580f99bc9d7953fec7f6f9b1ee.
