### ISSUE TITLE
Bug in Newsletter module. Missing `smtpEnc` parameter in SQL.

### ISSUE THREAD

**Issue by DyaGa** [contao/core#8218]
There is a missing parameter `smtpEnc` in SQL statement in file [Newsletter.php line 31](https://github.com/contao/core/blob/master/system/modules/newsletter/classes/Newsletter.php#L31).
It is used in [line 48](https://github.com/contao/core/blob/master/system/modules/newsletter/classes/Newsletter.php#L48).

Should be:
```sql
SELECT n.*, c.useSMTP, c.smtpHost, c.smtpEnc, c.smtpPort, c.smtpUser, c.smtpPass ...
```

**Comment by leofeyer** [comment]
Fixed in 8a32e4730e1cef2af3696f55323bf16d49c0eea2.
