### ISSUE TITLE
ContentElement Feature-Request:Link Lists

### ISSUE THREAD

**Issue by asaage** [contao/core#8221]
usually i do not grant access to modules for editors but in a current project the customer uses a lot of internal links which gets me into styling troubles because he accomlishes this by the use of ce_text and tinyMCE sometimes ```<p>```'s are used sometimes ```<ul><li>```'s and sometimes  ```<ol><li>```'s
I thought about multiple Solutions:
* having the **mod_customnav** as a ContentElement would serve well in this case
but it's missing the ability for external links wich might be desirable for others
* using the **ce_list** element
but it requieres you to write markup and therefore is a nogo (btw nice to see that this element supports csv import - i rarely used this)
* using the **ce_hyperlink** element which provides the appropriate fields but lacks the wrapping functionality (compared to ce_download/ce_downloads)

Any Suggestions?
I think I'd favour something similar to ce_list with an aditional button which opens a modal ce_hyperlink input-dialog and implement it as **ce_hyperlinks**.

**Comment by leofeyer** [comment]
A link list element should be provided by an extension.

**Comment by Aybee** [comment]
You also can manage a linklist with members and render them with the listing module, or create a page Links with subpages as external URLs so you can use a nav module to render them.

**Comment by asaage** [comment]
@Aybee the listing module does not provide editing functionality (not shure why i should misuse the members for that) and the nav module requires acces to the Sitestructure and to the FE-modules.
I was just thinking about a relative simple CE to use in articles events and news like the ce_list..

**Comment by Aybee** [comment]
> not shure why i should misuse the members for that

I think this is no misuse. If you have many links that way you can manage them as datasets.

That were just some suggestions if you don't want to write an extension.
