### ISSUE TITLE
Viewport-Tag wird nur in Verbindung mit dem Layout-Builder eingefügt

### ISSUE THREAD

**Issue by J-J-A** [contao/core#8222]
Es wird kein Viewport im Headbereich eingetragen, wenn man nur "Responsive Layout" aktiviert hat. Ich muss dafür zusätzlich den "Layout-Builder" in den Seiteneinstellungen anklicken. 

Wenn es so gewollt ist, sollte die Beschreibung **"Adds a meta viewport tag to the page header and scales the CSS layout based on the device width."** das auch vermerken, und aussagen, dass der Viewport bzw. "Responsive Layout" nur in Verbindung mit dem "Layout-Builder" funktioniert.

**Comment by sascha-mueller** [comment]
Kann ich bestätigen.

**Comment by Aybee** [comment]
Zusätzlich sollte der Hilfetext des Feldes "Viewport" von
> Here you can overwrite the viewport content (defaults to <em>width=device-width,initial-scale=1.0</em>).

nach
> Here you can overwrite the viewport content (defaults to <em>width=device-width,initial-scale=1.0</em> if layout builder CSS is included).

geändert werden.

**Comment by michelbalzer** [comment]
Das Viewport-Feld kann ich allerdings auch selbst ausfüllen, wenn ich den Layout-Builder _nicht_ verwende. Die Standard-Ausgabe des Viewport-Felds wird erst mit dem Layout-Builder ins HTML geschrieben. Trage ich einen eigenen Wert ein, um zwar eine responsive Website aufzusetzen aber dabei auf den Layout-Builder zu verzichten, wird dieser Wert auch im Frontend ausgegeben.

Also, derzeit sieht es so aus:

- Layout-Builder aktiv: Standard-Viewport-Angabe wird ausgegeben
- Layout-Builder nicht aktiv: Standard-Viewport-Angabe wird nicht ausgegeben
- Layout-Builder nicht aktiv, eigene Viewport-Angabe angegeben: eigene Viewport-Angabe wird ausgegeben

Müsste also in etwa lauten, besser bekomme ich das gerade nicht hin

> Here you can overwrite or set the viewport content ( defaults to width=device-width,initial-scale=1.0 if layout builder CSS is included, else to none output or the custom value).

**Comment by leofeyer** [comment]
Es macht überhaupt keinen Sinn, nur das Stylesheet "Responsive layout" einzubinden, weil darin die Anweisungen des Stylesheets "Layout builder" überschrieben werden. Ohne das Stylesheet "Layout builder" bringt das Stylesheet "Responsive layout" überhaupt nichts.

**Comment by sascha-mueller** [comment]
Hallo Leo,
es mag sein, dass es keinen Sinn macht die Dateien getrennt einzubinden.

Derzeit ist es allerdings so, dass die zugehörige Beschreibung 

"Adds a meta viewport tag to the page header and scales the CSS layout based on the device width."

sich so liest als würde das alleinige Anklicken des Punkte "Responsive layout" den "meta viewport tag" hinzufügen, was aber nicht stimmt.

Richtiger wäre etwas wie:
... erweitert den Layoutbuilder um ein responsives Verhalten. Bei aktiviertem Layoutbuilder wird der "meta viewport tag" eingefügt. Ansonsten ist der viewport von Hand einzutragen.

Ob dieser Missverständliche Text nun ein klassischer Defekt ist oder nicht, ist Geschmackssache.

**Comment by leofeyer** [comment]
@contao/developers Wie wollen wir das beheben? Sollten wir nur die Erklärung anpassen oder lieber automatisch auch den "Layout Builder" auswählen, wenn jemand "Reponsive Layout" anklickt? Ich wäre für letzteres, da es wie gesagt keinen Sinn macht, nur "Responsive Layout" auszuwählen.

**Comment by aschempp** [comment]
Das sehe ich anders. "Responsive Layout" fügt doch das Grid-System hinzu? Dafür brauche ich den Layout-Builder nicht, aber da macht es immer Sinn den Meta-Tag auszugeben?

**Comment by leofeyer** [comment]
Nein, "12-column grid" fügt das Grid-System hinzu. "Responsive Layout" überschreibt nur ein paar Anweisungen des "Layout Builder"-Stylesheets, damit das Layout responsive wird.

**Comment by leofeyer** [comment]
https://github.com/contao/core/blob/master/assets/contao/css/responsive-uncompressed.css

**Comment by leofeyer** [comment]
Und das macht ohne "Layout Builder" nicht wirklich Sinn :)

**Comment by aschempp** [comment]
Ah, I see. Dann können wir es doch einfach lassen wie es ist? :joy:

**Comment by leofeyer** [comment]
Hast Du das Ticket überhaupt gelesen? :smile:

**Comment by aschempp** [comment]
Klar, ich sehe nur das Problem nicht. Funktioniert die Checkbox "Responsive Layout" nicht, wenn "Layout Builder" nicht aktiviert ist?

**Comment by leofeyer** [comment]
Dann lies nochmal. Ist eigentlich ziemlich klar formuliert.

**Comment by leofeyer** [comment]
Behoben in 382a03d8d373313df7f14e3010712376a5d64ed5.

**Comment by sascha-mueller** [comment]
Bitte auch die Beschreibung im BE mit anpassen, sonst wundern sich "die Leute" im nächsten Schritt über diesen Unterschied ;-)

**Comment by leofeyer** [comment]
Welchen Unterschied?

**Comment by sascha-mueller** [comment]
Unterschied jetziger Text zu dem dann gegebenen Verhalten.

**Comment by leofeyer** [comment]
Da ist ja eben kein Unterschied :)

**Comment by fritzmg** [comment]
This is a BC break for people who used the responsive layout styles without the layout builder. See #8261 for example.

**Comment by leofeyer** [comment]
Not a supported use case IMHO.

**Comment by Teetrinker** [comment]
That is still an issue:

If you don't use any Contao stylesheets, the viewport field description still suggests that the viewport tag will be written into the output if the field is empty.

Erklärung anpassen wäre ein kleiner, aber feiner Schritt.

**Comment by Aybee** [comment]
Ja, das fehlt definitiv. Der Hlfetext ist falsch.
```php
// IST
$GLOBALS['TL_LANG']['tl_layout']['viewport'][1] = 
'Hier können Sie den Viewport-Inhalt überschreiben (Standard: <em>width=device-width,initial-scale=1.0</em>).';

// SOLL
$GLOBALS['TL_LANG']['tl_layout']['viewport'][1] = 
'Hier können Sie das Meta-Tag <strong>viewport</strong> setzen oder überschreiben. Standardwert (nur wenn "Responsives Layout" aktiviert ist): <em>width=device-width,initial-scale=1.0</em>.';

//   'Here you can set or edit the meta tag <strong>viewport</strong>. Default (only if "Responsiv layout" is checked): <em>width=device-width,initial-scale=1.0</em>.';
```

**Comment by leofeyer** [comment]
Geändert in contao/core-bundle@b3280fd9b020769968c46a2b1f7f1fcb2eeace60.

**Comment by Aybee** [comment]
Ist die Bedingung entfallen? Bisher wurde der Viewport nur gesetzt, wenn Responsives Layout ausgewählt wurde. Denn der Hilfetext sieht jetzt immer noch so aus, als würde ich dort nichts einzutragen brauchen und würde auf jeden Fall den Eintrag bekommen. Da ich bei meinen Installationen das Responsive Layout nie angehakt habe, musste ich dort bisher immer einen Wert eintragen. Jetzt sieht der Hilfetext so aus, als bräuchte ich das nicht mehr.

**Comment by leofeyer** [comment]
https://github.com/contao/core/blob/master/system/modules/core/pages/PageRegular.php

**Comment by Aybee** [comment]
Wird also nur eingetragen, wenn ich in das Feld etwas eingebe.
https://github.com/contao/core/blob/master/system/modules/core/pages/PageRegular.php#L365-L369
Dann stimmt der Hilfetext also nicht.
`(defaults to &lt;em&gt;width=device-width,initial-scale=1.0&lt;/em&gt;)`

Dieser Fall hier
https://github.com/contao/core/blob/master/system/modules/core/pages/PageRegular.php#L287-L290
trifft bei mir eigentlich nie zu. Evtl. mal, wenn ich in ner fremden Installation bin.
