### ISSUE TITLE
autosave tinymce

### ISSUE THREAD

**Issue by Bicet** [contao/core#8223]
It doesn't work on 3.5.6 :(

**Comment by leofeyer** [comment]
Does it work in the online demo?

**Comment by Bicet** [comment]
No it doesn't neither on the online demo

**Comment by leofeyer** [comment]
I have just checked it and it works like a charm in the online demo.

**Comment by leofeyer** [comment]
This menu item is added by the autosave plugin:

![tinymce-autosave](https://cloud.githubusercontent.com/assets/1192057/13348907/8efdbb3c-dc76-11e5-8cdd-5467b73a8c78.png)
