### ISSUE TITLE
Not only Google webfont

### ISSUE THREAD

**Issue by JLBA** [contao/core#8225]
Hi everyone,

In page Layout, could you add the ability to use locally installed webfont, not only Google ones ?
For now, I'm playing with specific css but if there was a simplier way of using it... 

Thanks.

**Comment by Toflar** [comment]
?

**Comment by xantippe** [comment]
!

**Comment by sascha-mueller** [comment]
LAde doch die lokal installierten WEBfonts einfach auf Deine Seite, dann sind es echte WEBfonts und Du kannst diese dann sogar im Web benutzen ;-)

**Comment by JLBA** [comment]
Ok. I'm trying to understand. 

In the layout parameters, the field is called "Google webfont" and it only asks to put font names so I thought this can only use Google webfont (directly linked with Google servers). 
I searched some help in Contao's doc but found nothing.

How can I use non system fonts so fonts installed in ~/contao/files/fonts/ for example ?

**Comment by asaage** [comment]
> Can I use non system but locally installed fonts (@font-face) like in ~/contao/files/fonts/ for example ?

you can.

> How do I explain to Contao where my fonts are ?

you can use (@font-face) as a selector in the css-editor and declare the fonts in the code-field.
for better browser support i tend to go to [here](http://www.fontsquirrel.com/tools/webfont-generator), put all resources into your files/fonts directory and use layout -> additional styleeshet's

**Comment by JLBA** [comment]
That's what i actually do and so what I said. The field Google webfonts in the layout is strictly for Google font. My request was for another field for simply use locally stored webfont.

I know Squirrel too. I've just discovered fonts2u.com which directly proposes the @font-face files + css to download when possible.

**Comment by leofeyer** [comment]
The "Google web fonts" field was added to Contao much earlier than the external style sheets. Actually the field could be removed, because you can add web fonts in an additional head tag or in an external style sheet, but to remain backwards compatibility, we are keeping it for now.
