### ISSUE TITLE
certain characters in values (for checkboxes and selects) lead to error

### ISSUE THREAD

**Issue by fritzmg** [contao/core#8226]
If you use `inputType => 'checkbox'` or `select` in your DCA and your values for your options contain characters like `=`, `(` or `)` it will lead to an error when you try to save it.

Example:
```php
… array
(
	…
	'inputType' => 'select',
	'options' => array('x=y','(z)'),
	…
)
```
![invalid_01](https://cloud.githubusercontent.com/assets/4970961/13105004/f88cbaca-d560-11e5-8e23-7be8f72cf19e.png)
![invalid_02](https://cloud.githubusercontent.com/assets/4970961/13105006/fa975dac-d560-11e5-9d99-34816636f186.png)

Characters like these should be valid, but may be the DC does not escape them before saving them to the database?

**Comment by leofeyer** [comment]
Did you set the `decodeEntities` flag?

**Comment by fritzmg** [comment]
Oh right, no, it works with 
```php
'eval' => array('decodeEntities'=>true)
```
