### ISSUE TITLE
Minor errors in flexible backend theme

### ISSUE THREAD

**Issue by Anke** [contao/core#8227]
The following (minor) issues apply to narrow screens:

Editing CSS styles, the text areas "Selektor" and  "Eigener Code" seem to be set (inline) to "height: 15px" for wide screens which isn't high enough when narrowing the window. This value is only changing to 21px on a window refresh. 

After emptying the internal cache the alert box "Den Cache aufbauen" is hidden in the collapsible area. Would be convenient to make it visible one way or another. (Maybe by an overlay to show it even when the user is at the bottom of the page?)

In the CCS editor the refresh button cannot be used at a screen widths < 768px. (The icon is at the right place but cannot be clicked.)

**Comment by leofeyer** [comment]
?

**Comment by Anke** [comment]
After emptying the internal cache the alert box "Den Cache aufbauen" is hidden in the collapsible area. Would be convenient to make it visible one way or another. (Maybe by an overlay to show it even when the user is at the bottom of the page?)
![contao_cache_aufbauen](https://cloud.githubusercontent.com/assets/1300920/13127213/72878c66-d5ce-11e5-9f12-9e8671fe7616.jpg)

In the CCS editor the refresh button cannot be used at a screen widths < 768px. (The icon is at the right place but cannot be clicked.)
![contao_refresh](https://cloud.githubusercontent.com/assets/1300920/13127255/9b90b29a-d5ce-11e5-9a3e-2b30ec979f7b.jpg)

CSS editor: textareas not high enough when narrowing the window. The dynamically set height is only changing from 15px to 21px when reloading the window.
![contao_css_textareas](https://cloud.githubusercontent.com/assets/1300920/13127296/eab88a1e-d5ce-11e5-96c8-e99357808926.jpg)

**Comment by leofeyer** [comment]
The first two issue have been fixed in 655bb5c10c3668fb90e8b0f304a227067ebfb1a1. The latter is not an issue IMHO, since I don't see a real use case (except testing the responsiveness).
