### ISSUE TITLE
ce_hyperlink mit image - kein individuelles Template möglich

### ISSUE THREAD

**Issue by BeutlerKa** [contao/core#8230]
Guten Morgen,
wenn ich einem ce_hyperlink emelement ein image hinzufüge, wird kein individuelles Template mehr genutzt wenn man es auswählt.

Es wird immer das ce_hyperlink_image template genutzt.

Grüsse,
K. Beutler

**Comment by leofeyer** [comment]
Das Problem konnte aus Gründen der Rückwärtskompatibilität leider erst in Contao 4 behoben werden.
