### ISSUE TITLE
Usability: 1. and 2. level of News, Events, Articles at the same place

### ISSUE THREAD

**Issue by jenda77** [contao/core#8231]
I would prefer when the 1. (title, teaser etc.) and 2. level (content) of News, Articles and Events would be at the same place. I can imagine that the news header (title, teaser, etc.) could be showed per accordion or tab before the content (similar like it´s now but without leaving the window with the content). 

A lot of customers can´t understand why the levels are in the backend separated now although they belong together. I think it could improve the user experience a lot because it would be more clearer where user can find it.

**Comment by asaage** [comment]
I agree in terms of user experience.
We had that (at least for news and events) in contao 2.x and it changed when ContentElements where made available for both.
It took some effort to explain that to customers and most of them still don't feel comfortable with it.
On the other hand i dont think mixing/displaying both views (in your words levels) on one page would be a great idea.
The content listing header offers already access to the news/events palette
![image](https://cloud.githubusercontent.com/assets/4138336/13204448/88fdb8bc-d8d0-11e5-9859-29a8e2aa44b4.png)

but to navigate the opposite direction is a bit more difficult.
for fresh news there is a save and edit button:
![image](https://cloud.githubusercontent.com/assets/4138336/13204489/b430698e-d8d1-11e5-826c-ba86a5d1bcf9.png)
but unfortunately its missing once you leave this Panel.
![image](https://cloud.githubusercontent.com/assets/4138336/13204539/db1d3300-d8d2-11e5-8687-7ae0c0f55593.png)

**Comment by leofeyer** [comment]
> but unfortunately its missing once you leave this Panel.

This has already been changed in Contao 4.

**Comment by asaage** [comment]
:+1:

**Comment by jenda77** [comment]
@leofeyer I am sorry but my ask is an another. The solution you have implemented into 4th version is not the solution I am asking for. 

I would like to have the both levels at the same place without leaving the windows for the content. There are a lot of possibilities how to make it more user friendly. In my eyes Contao could be more user friendly with this suggestion. 

When I show somebody how to create or managed news, articles and events, often it´s not really ease for the people to understand it. My experience with mostly every customers is that they cannot understand why the both levels are separated although they belong together. And today it´s possible to make it more user friendly. The technology for it is there. 

Please, rethink it once more, it could be a big improvement of the user experience with Contao. And when you think it is not, please, tell me why. I would like to know the arguments against my suggestion and to understand why this issue was closed. Thank you.

**Comment by leofeyer** [comment]
@asaage has already answered this.

> We had that (at least for news and events) in contao 2.x and it changed when ContentElements where made available for both.

There have been a lot of requests to change it and we will not change it back.
