### ISSUE TITLE
Daten bereinigen über direkten Button

### ISSUE THREAD

**Issue by jgrotstabel** [contao/core#8233]
Hallo zusammen,

wir sind jetzt mehrfach auf das Problem gestoßen, dass Editoren die technisch nicht so versiert sind, ein Problem damit haben das deren Änderungen im Frontend nicht sofort zu sehen sind.
Das kommt ja z.B. dann vor wenn der Cache-Modus "Nur Servercache verwenden" im Zusammenhang mit einer Cachezeit von z.B.  24 Stunden genutzt wird.

Wir haben jetzt rausgefunden das man über den Benutzernamen im Backend Header zu diesen Feldern kommt. Die Frage ist aber ob es nicht wie in vielen anderen CM-Systemen wirklich Sinn macht diese drei Funktionen Daten bereinigen für  "Session-Daten", "Bildercache" und vor allem "Seitencache" über einen Button im Backend Header sofort klickbar zu machen.
Z.B. ist das in Typo3 so. Das kann man einem Editor super einfach erklären.

Was man dazu auch noch überlegen könnte wäre, ob man es in der Frontend-Vorschau nicht so hinbekommen könnte, dass diese den Cache komplett ignoriert. Dann braucht man den Cache auch, egal welchen Weg man dafür nutzt, nur nach dem Freigeben des Inhaltes einmal leeren.

Viele Grüße
Jens

**Comment by Samson1964** [comment]
Das Thema geistert schon seit Jahren durch das Contaoforum. Theoretisch sollte ja bei eingeloggtem Backend der Cache immer ignoriert werden. So jedenfalls die vorherrschende Meinung. Praktisch aber trifft man dieses Verhalten nur sehr selten an.

**Comment by jgrotstabel** [comment]
Aber für die praktische Arbeit der Editoren wäre das wohl schon der richtige Weg.
Und zum Abschluss seiner Arbeiten könnte man eben einen leicht zu finden Button verwenden um den Cache zu leeren. Hört sich ja nach einem sehr gutem Weg an und meiner Meinung nach einer großen Verbesserung für die Nutzbarkeit des Backend im Zusammenhang mit dem Cache.

**Comment by Aybee** [comment]
Ich bin auch mal wieder dafür, dass es keinen FE-Cache gibt, wenn ich im BE eingeloggt bin.

Einen Cache-Leeren-Button fände ich nicht gut. Dann kann man auch einen zusätzlichen **'Speichern und Cache leeren'-Button** anbieten. Wobei sich dann die Frage stellt, wofür ich einen Speichern-Button benötige, bei dem der Cache **nicht** gelöscht wird.

Auf jeden Fall würde ich meinen Kunden ungern mitteilen, dass sie zusätzlich zum Speichern den 'Cache leeren Button' klicken müssen.

Komischerweise habe ich selber aber überhaupt keine Probleme damit, die Änderungen sofort im FE zu sehen, wahrscheinlich, weil ich für die Seiten keinen Cache eingestellt habe.

**Comment by jgrotstabel** [comment]
Das ist korrekt.

> Das kommt ja z.B. dann vor wenn der Cache-Modus "Nur Servercache verwenden" im Zusammenhang mit einer Cachezeit von z.B. 24 Stunden genutzt wird.

**Comment by asaage** [comment]
> Komischerweise habe ich selber aber überhaupt keine Probleme damit, die Änderungen sofort im FE zu sehen, wahrscheinlich, weil ich für die Seiten keinen Cache eingestellt habe.

selbstklärend oder? :smile:
Ich hab das vor einiger zeit mal durchgetestet und es verhielt sich so, dass der Cache ignoriert wird, wenn ich im FE angemeldet bin oder wenn ich im BE angemeldet bin (oder auch beides also auch wenn ich Frontendpreview nutze).
Wenn ich zum Anschauen meiner Änderungen einen anderen Browser oder Incognito Modus nutze kommt der Cache zum Zug.

**Comment by jgrotstabel** [comment]
Kann ich nicht bestätigen. Wir haben diesen Workflow mehrfach durchgespielt.
Hast Du eine aktuelle Contao Version für Dich am laufen und testest das einmal?

**Comment by asaage** [comment]
das war die aktuelle.

**Comment by asaage** [comment]
Habs gerad nochmal durchgespielt - es ist so, wie beschrieben.
Kann's sein, dass deine Editoren hinter einem Caching-Proxy hängen? Den Fall hatte ich auch schon...

**Comment by Aybee** [comment]
Folgende Ausdrücke müssen alle `true` sein, wenn gecached werden soll https://github.com/contao/core/blob/master/system/modules/core/classes/FrontendTemplate.php#L205

Bei mir ist **DISABLE_CACHE** immer ´false´,
```
!isset($_GET["file"])            - true
!isset($_GET["token"])           - true
empty($_POST)                    - true
!BE_USER_LOGGED_IN               - true
!FE_USER_LOGGED_IN               - true
!$_SESSION["DISABLE_CACHE"]      - false
!isset($_SESSION["LOGIN_ERROR"]) - true
intval($objPage->cache) > 0      - false
!$objPage->protected             - true
```
 was wohl hierdurch bedingt ist https://github.com/contao/core/blob/master/system/modules/core/classes/Frontend.php#L512 - also bei mir wird das Cookie **BE_USER_AUTH** gefunden.

**Comment by fritzmg** [comment]
> Ich bin auch mal wieder dafür, dass es keinen FE-Cache gibt, wenn ich im BE eingeloggt bin.

Theoretisch sollte es ja so sein. Siehe: [system/modules/core/controllers/FrontendIndex.php#L295](https://github.com/contao/core/blob/3.5.6/system/modules/core/controllers/FrontendIndex.php#L295)

**Comment by Aybee** [comment]
> Backend Login alleine reicht also nicht.

Doch, weil es ja reicht, wenn **DISABLE_CACHE** auf true gesetzt wird, was passiert, wenn das Cookie **BE_USER_AUTH** gefunden wird.

Ich habe das oben mal korrigiert, weil das etwas verwirrend war

**Comment by fritzmg** [comment]
> Doch, weil es ja reicht, wenn DISABLE_CACHE auf true gesetzt wird, was passiert, wenn das Cookie BE_USER_AUTH gefunden wird.

Nein, das passiert erst danach, daher hat das keine Auswirkung.

**Comment by Aybee** [comment]
Ich habe jetzt `$_SESSION['DISABLE_CACHE']` an dieser Stelle https://github.com/contao/core/blob/3.5.6/system/modules/core/controllers/FrontendIndex.php#L295 gedebuggt und es ist bei mir immer `1`. Ich schaffe es auch nicht die Installation so einzustellen, dass im Frontend ne Seite aus dem Cache geholt wird.
- Startpunkt Cache 60 sec
- Nur der Server-Cache
- Interner Cache aktiv
- Abgesichert an und aus
- Keine FE-Vorschau

**Comment by asaage** [comment]
Verwirrung perfekt...
gerade nochmal ein wenig rumgespielt und ich hatte plötzlich doch gecachte Inhalte trotz BE Login ja sogar trotz Frontend-Vorschau.
also das war der Fall, als ich die Graue Leiste für die Vorschau zwar hatte - aber kein Cookie für FE_PREVIEW gesetzt war. Weder "Neu laden" noch "anwenden" beschert mir den notwendigen Cookie. Der sollte vielleicht nochmal zuverlässig gesetzt werden.
Die einzigen stellen, die ich gefunden habe sind RebuildIndex und BackendSwitch

**Comment by jgrotstabel** [comment]
Technisch gesehen komm ich jetzt leider nicht mehr ganz mit. Aber es hört sich für mich so an, als wenn da doch was nicht klappt mit der Frontend-Vorschau, korrekt?

**Comment by fritzmg** [comment]
> Ich habe jetzt $_SESSION['DISABLE_CACHE'] an dieser Stelle https://github.com/contao/core/blob/3.5.6/system/modules/core/controllers/FrontendIndex.php#L295 gedebuggt und es ist bei mir immer 1. Ich schaffe es auch nicht die Installation so einzustellen, dass im Frontend ne Seite aus dem Cache geholt wird.
> 
>     Startpunkt Cache 60 sec
>     Nur der Server-Cache
>     Interner Cache aktiv
>     Abgesichert an und aus
>     Keine FE-Vorschau

Kann ich nicht bestätigen. Ich bin im Backend einglogged und gebe mir gleich am Anfang der Funktion folgendes aus:
```php
protected function outputFromCache()
{
	var_dump(!empty($_POST));
	var_dump(\Input::cookie('FE_USER_AUTH'));
	var_dump(\Input::cookie('FE_AUTO_LOGIN'));
	var_dump($_SESSION['DISABLE_CACHE']);
	var_dump(isset($_SESSION['LOGIN_ERROR']));
	var_dump(\Config::get('debugMode'));

	…
}
```
Ausgabe:
```
bool(false)
NULL
NULL
bool(false)
bool(false)
bool(false)
```
Also alles ist entweder `NULL` oder `false`, inklusive
```php
$_SESSION['DISABLE_CACHE']
```

**Comment by fritzmg** [comment]
Und der Grund dafür ist klar, `$this->getLoginStatus(…)` wird __nur__ in `FrontendIndex.php` aufgerufen - und kann auch nur von `Frontend` ableitenden Klassen aufgerufen werden, weil die Funktion ja so definiert ist:
```php
protected function getLoginStatus($strCookie)
```

**Comment by Aybee** [comment]
@fritzmg 
Du sitzt da wohl tiefer im Code als ich und ich möchte das jetzt nicht auch noch checken, wer die Variable $_SESSION['DISABLE_CACHE'] wann unter welchen Bedingungen setzt.

Ich hatte den Cache auf eine Minute gesetzt und den Test sehr oft wiederholt, dass heißt, dass selbst, wenn die Seite beim ersten Mal nicht aus dem Cache kam, sie doch zumindestens danach aus dem Cache gekommen sein muss, oder?

Ich hoffe, dass das alles in dem neu eröffneten Ticket geklärt werden kann.

**Comment by asaage** [comment]
Frage: worin besteht eigentlich die Notwendigkeit, dass ```FE_USER_AUTH``` bzw ```FE_AUTO_LOGIN``` den Cache aushebeln?
Ich hatte letztens nämlich den Fall, dass ich gern auch eingeloggte FrontendMitgliedern aus dem Cache bedienen wollte.

Würde es nicht auch Sinn machen, die gecachte Version einer Seite in dem Moment zu erneuern in dem Sie von einem Nutzer mit ```BE_USER_AUTH``` cookie aufgerufen wird? Damit hätte sich dann auch das eigentliche Thema dieses issues mehr oder weniger erledigt.

**Comment by fritzmg** [comment]
> Ich hatte den Cache auf eine Minute gesetzt und den Test sehr oft wiederholt, dass heißt, dass selbst, wenn die Seite beim ersten Mal nicht aus dem Cache kam, sie doch zumindestens danach aus dem Cache gekommen sein muss, oder?

Nein, sobald du einmal eine Seite _nicht_ aus dem Cache bekommst (weil sie dort noch nicht existiert, egal ob sie dann im Cache existiert oder nicht) bekommst du danach _keine_ Seite mehr aus dem Cache, wenn du im Backend eingelogged warst - weil dann wird
```php
$this->getLoginStatus('BE_USER_AUTH');
```
ausgeführt und in weiterer Folge
```php
$_SESSION['DISABLE_CACHE'] = true;
```
gesetzt. Wenn du aber nur Seiten aufrufst, die bereits im Cache existieren, passiert das nie.

Teste es einfach mal so wie in #8249 beschrieben.

> Frage: worin besteht eigentlich die Notwendigkeit, dass FE_USER_AUTH bzw FE_AUTO_LOGIN den Cache aushebeln?
> Ich hatte letztens nämlich den Fall, dass ich gern auch eingeloggte FrontendMitglieder aus dem Cache bedienen wollte - was leider unmöglich ist.

Ich denke weil man nicht vorhersehen kann, wie der Inhalt einer Seite für das jeweilige Mitglied aussieht. Für eine Seite kann ja nur eine Version im Cache liegen, nicht pro Mitglied/Gruppe.

> Würde es nicht auch Sinn machen, die gecachte Version einer Seite in dem Moment zu erneuern in dem Sie von einem Nutzer mit BE_USER_AUTH cookie aufgerufen wird? Damit hätte sich dann auch das eigentliche Thema dieses issues mehr oder weniger erledigt.

zB, ja, also in der Liste der oben erwähnten Bedingungen könnte man ja auch
```php
\Input::cookie('FE_USER_AUTH')
```
hinzufügen. Wie es gefixt wird, entscheiden halt die devs ;).

**Comment by leofeyer** [comment]
Siehe #8249.
