### ISSUE TITLE
FormSelectMenu ignores rgxp in frontend

### ISSUE THREAD

**Issue by Defcon0** [contao/core#8234]
Hello folks,

in FormSelectMenu.php (Contao 3.5.6, line 97) in the magic setter __set() the rgxp is ignored. Why is that? I have defined a custom rgxp in order to check some values. In the backend everything works like a charm, in the frontend, the rgxp isn't added to $this in \Widget::addAttributes() because of FormSelectMenu's magic setter.

Bye Defcon0

**Comment by aschempp** [comment]
Why would you need a regular expression match if the field lets you only select available options?

**Comment by Defcon0** [comment]
The case is a little more complex:

We have written a generic exporter module (heimrichhannot/contao-exporter) that prints field values to table cells in a table written to some file format (csv, xls, ...). Now I have some field (inputType "select") which has an options_callback. This field lets a judge select the competition submission to review the submission.

Our first approach had been to limit the possible options to only the available submissions, i.e. only submissions not reviewed by the judge himself before. Since one single judge shouldn't review the same submission more than once. At this point we wouldn't have the rgxp, right.

But this breaks the exporter mentioned before. It transforms the submission id linked to a review to the submission's team name. And this is done by the options_callback. But if the judge has reviewed all submissions, the options calculated by the options_callback is empty. Hence the exporter cannot transform the submission name based on the options.

I hope, this was understandable :-)

Furthermore: Your argumentation only applies for the frontend since in the backend select field's regexps **are** validated ;-)

**Comment by aschempp** [comment]
Looks like you should implement the validateFormField hook for your special case ;-)
