### ISSUE TITLE
Feature: Warnhinweis im Backend wenn Fehlermeldungen anzeigen aktiviert ist

### ISSUE THREAD

**Issue by netzarbeiter** [contao/core#8235]
Wenn der «Abgesicherter Modus» oder der «Wartungsmodus» aktiviert ist, erhalte ich im Backend einen Warnhinweis. Wäre es möglich auch eine Warnung bei aktiviertem «Fehlermeldungen anzeigen» zu generieren.

![wartungsmodus](https://cloud.githubusercontent.com/assets/1942550/13327525/8f6d38cc-dbea-11e5-8849-b029e474df91.png)

Text für den Hinweis:
Sie geben zur Zeit die Fehlermeldungen auf dem Bildschirm aus. Deaktivieren Sie den Punkt **Fehlermeldung anzeigen** für produktive Seiten.

**Comment by frontendschlampe** [comment]
+1

**Comment by Toflar** [comment]
Im Idealfall werden die gesamten Messages in der Systemwartung ausgegeben und oben nur eine allgemeine "Ihre Contao-Installation verfügt über Optimierungspotenzial. Besuchen Sie die Systemwartung um die Hinweise zu sehen. -> Zur Systemwartung". Und die Message auch nur dann, wenn man Zugriff auf die Systemwartung hat. So kann ich meinen User die Inhalte pflegen lassen, währenddem ich code (und deshalb Fehlermeldungen aktiviere) ohne dass ich jeden Tag eine E-Mail erhalte indem der Kunde schreibt "Contao ist noch nicht optimiert". :-) Ausserdem können wir die Liste dann beliebig erweitern, im Backend da oben ist irgendwann schluss.

**Comment by aschempp** [comment]
Eine sehr gute Idee! Ein normaler User sollte nämlich nicht Cache aufbauen…

**Comment by MDevster** [comment]
+1
Ähnliche Ansätze wurden übrigens auch in den Backend Theme Gruppe besprochen und sollen für Admins ins Dashboard integriert werden können.

**Comment by fenepedia** [comment]
+1

**Comment by fritzmg** [comment]
:+1:

**Comment by planepix** [comment]
+1

**Comment by Zeromax** [comment]
+1

**Comment by schmanat** [comment]
+1

**Comment by leofeyer** [comment]
Da es die Option "Fehlermeldungen anzeigen" in Contao 4 gar nicht mehr gibt, hat sich dieses Ticket wohl erledigt.
