### ISSUE TITLE
Umleitungsfehler da HTTP-Statuscode an den Alias angehängt wird?!

### ISSUE THREAD

**Issue by kozi** [contao/core#8247]
Bekomme einen Umleitungsfehler seit ich auf Version 3.5.8 aktualisiert habe. (von 3.5.6)

Habe interne Seiten und eine Login-Seite

![seitenstruktur](https://cloud.githubusercontent.com/assets/464029/13488655/e57e4e76-e122-11e5-9e58-29aa209fbaa0.png)

Beim Aufruf der URL wird eine Weiterleitung vorgenommen. Der generierte Alias enthält am Ende aber auch den Statuscode 301 und deshalb wird die Seite immer weiter umgeleitet, da die richtige Seite nicht gefunden wird. 
Die Fehler 404 Seite, die ich eingerichtet habe leitet auf die oberste Ebene weiter

**Comment by aschempp** [comment]
Wie hat es sich denn vorher verhalten?

**Comment by bytehead** [comment]
Duplicate - fixed here: #8243.

**Comment by kozi** [comment]
Correct it is a duplicate!  #8243
