### ISSUE TITLE
update.phar - checksums not updated?

### ISSUE THREAD

**Issue by fritzmg** [contao/core#8248]
There are some forum reports where the live update tool of Contao reports an incomplete update, suggesting that your servers needs the safe mode hack - even though the update seems to have run fine. Could it be that the errors present in Contao `3.5.7` and `3.5.8` are already fixed through the live update - however the check afterwards checks against the wrong checksums?

**Comment by leofeyer** [comment]
This issue has been fixed in the Live Update client already.
