### ISSUE TITLE
iPad / iOs filemanager popup without focus

### ISSUE THREAD

**Issue by fenepedia** [contao/core#8250]
If I use an iPad with safari and like to insert an image, the filemanager popup has no focus.
I can't scroll down. If I scroll, the background scrolls, but not the content of the popup.

I found a workaround in chrome.
If I install chrome browser to my ipad an do the same. First the same behavior exists.

To get focus on the popup I need to toggle a folder inside the filemanager and now I get the focus on the popup.

Contao 3.5

**Comment by leofeyer** [comment]
@JanoschSkuplik @ausi Can you reproduce this?

**Comment by JanoschSkuplik** [comment]
@leofeyer yes, I can reproduce this behavior in the demo. (See http://www.janosch-skuplik.de/files/temp/2016-03-09%20Contao%20File%20Picker.mov)

**Comment by aschempp** [comment]
I have experienced the same issue on my iPhone 6 before, too.

**Comment by ausi** [comment]
I can reproduce it too. AFAIK this is due to frame-flattening in iOS.

A workaround could be to make the parent container scrollable, like:

```css
.simple-modal .simple-modal-body div.contents {
	overflow: auto;
	-webkit-overflow-scrolling:touch;
}
```

It needs a fixed height then, which we would have to set via JavaScript.

**Comment by leofeyer** [comment]
Fixed in c5846443aad0d9c1f83353cc0da1c2d11ce1cf13.

**Comment by Kahmoon** [comment]
It still doesn´t work on my iphone 6S (Firefox + Safari) + Contao 3.5.9

**Comment by leofeyer** [comment]
I have adjusted the fix in 93c3081a7d07c3b3a73e92f0ac5061029fc6ca75.

**Comment by Schmidty2** [comment]
Hallo,
das oben genannte Problem besteht wieder (immer noch?).
Ich habe Contao 3.5.27 installiert und verwende iOS 10.3.1 auf einem iPad pro, getestet wurde mit Safari, Chrome und Firefox für iOS.
Das Problem besteht nicht nur beim File-Manager sondern bei allen Popups in denen Eingaben getätigt werden z.B. auch beim Notification-Center.
Es lassen sich weder ein Bild einfügen noch andere Arbeiten in Popups durchführen, z.B. im Notification-Center. Es scrollt immer der Hintergrund und nicht der Inhalt des Popups.
