### ISSUE TITLE
404 Contao page error

### ISSUE THREAD

**Issue by ufeldmann** [contao/core#8251]
If you create a 404 page as an regular page with an article (no forwarding activated), it is not possible to open the 404 page directly. If you open it directly, an Contao "Page not found" error occurs.

<img width="608" alt="contao_page_error" src="https://cloud.githubusercontent.com/assets/3776638/13520881/71eb7c46-e1e4-11e5-8757-8a5d1e57e185.png">

If you open a not existing html page, the 404 page will be shown.

<img width="609" alt="not_existing_page" src="https://cloud.githubusercontent.com/assets/3776638/13520920/b7817a6c-e1e4-11e5-9f4e-3ebb318b94fc.png">

**Comment by fritzmg** [comment]
That's a limitation of the fact, that Contao (currently) still allows accessing a page via its ID. So when you try to open an URL like http://demo.contao.org/en/48.html or, as in your case, http://demo.contao.org/en/404.html it wil be interpreted as a Page ID, not a Page Alias and thus in the latter case, no page is found, since there is no page that has the ID 404.

However, this should have been fixed some time ago: #7661 - not sure what the status on this is now.

**Comment by ufeldmann** [comment]
The problem also occurs, if you are using an alias without numbers.
I think for the 404 page it is another bug.

![bildschirmfoto 2016-03-04 um 10 28 35](https://cloud.githubusercontent.com/assets/3776638/13523131/e183e6e2-e1f3-11e5-839c-fd84a70cf75f.png)

**Comment by fritzmg** [comment]
Yeah, seems so :)

**Comment by asaage** [comment]
I noticed this behaviour too some time ago...
but opening the 404 page directly makes no sense at all - the page will appear when you enter nonexisting pages in the address-bar.
and your (wrong) url will stay in the adress-bar then.

on the other hand having a "page not found" that differs from your customized error-page does not make sense either...
As a workaround i'd suggest to call a redirect in your ```be_no_page.html5``` to a real nonexisting page.

That seems to be a bug indeet.

**Comment by ufeldmann** [comment]
I think it should be possible to open the 404 page directly, for example for the htaccess 404 redirect.

**Comment by fritzmg** [comment]
> I think it should be possible to open the 404 page directly, for example for the htaccess 404 redirect.

For that you only need to define 
```
ErrorDocument 404 /index.php
```
in your .htaccess

**Comment by asaage** [comment]
i do not use any redirect but 
```ErrorDocument 404 /error404.html```
in htaccess

**Comment by ufeldmann** [comment]
Yes I am also doing this currently with the not existing page for the htaccess ErrorDocument. ;)
But for old installations where you (perhaps) set up the real 404 page as ErrorDocument, it worked until the update to Contao 3.5.x. (I am not sure about the version wherefrom the bug occurs)

**Comment by leofeyer** [comment]
This limitation has been introduced in #8060 to prevent endless recursion.
