### ISSUE TITLE
Group Content Elements in filtered BE List View

### ISSUE THREAD

**Issue by Hendriks** [contao/core#8252]
If you fiter the content elements of an article in BE list view by opening group elements like eg. sliderStart those are displayed cascading / encapsulated within each other; which in this context doesn't make sense. If you filter by closing elements like eg. sliderStop those elements are displayed in a linear manner, the way you expect them to; and the way the opening ones should do so too...

**Comment by leofeyer** [comment]
I actually don't agree. I find it very helpful to see the nesting level of the opening elements and I would like to see the same for the closing ones.

**Comment by leofeyer** [comment]
Regular view

<img width="922" alt="" src="https://cloud.githubusercontent.com/assets/1192057/14710147/82680876-07d4-11e6-96e8-41f15813207a.png">

Only "wrapper start" elements

<img width="911" alt="" src="https://cloud.githubusercontent.com/assets/1192057/14710164/8f8f2e26-07d4-11e6-809e-43dff39aa2e5.png">

Only "wrapper stop" elements

<img width="910" alt="" src="https://cloud.githubusercontent.com/assets/1192057/14710172/9733c90c-07d4-11e6-9adb-bd89f4d3f16d.png">

**Comment by leofeyer** [comment]
As discussed on Mumble on April 21st, we will not fix this. The nested view is an interim solution anyway and will be replaced with real nested content elements in Contao 5. Then this issue will be fixed automatically.
