### ISSUE TITLE
Logout module prevents rebuilding the index of protected pages

### ISSUE THREAD

**Issue by stefansl** [contao/core#8253]
If Contao rebuilds the search index and a logout module is somewhere included, the frontend member will be logged out automatically while indexing.
Maybe we should add a session before rebuilding the index, e.g. `$_SESSION['REBUILD_INDEX_ACTIVE'] = true;`

In the ModuleLogout.php we could return, if the session is set.

I don't have a clue, where to unset the session, but maybe someone here?

**Comment by stefansl** [comment]
additionally see here: https://community.contao.org/de/showthread.php?61607-Gesch%FCtzte-Seiten-indexieren-Access-denied&p=401811&viewfull=1#post401811

**Comment by fritzmg** [comment]
:+1: this brought me some trouble already as well

**Comment by leofeyer** [comment]
The question is rather why you want a logout page to be indexed?

**Comment by fritzmg** [comment]
Well no one wants that, but if you don't think of excluding the logout page from indexing yourself, it might take you a long time to figure out what's going wrong

**Comment by stefansl** [comment]
That's the point. No one wants to index the logout page or module. But even in the official contao demo there would be a problem while indexing protected pages, because "Do not search" is not activated in the page "Logout". See http://demo.contao.org/contao/main.php?do=page&act=edit&id=44

**Comment by leofeyer** [comment]
Yes, but that is a configuration error IMHO.

@contao/developers /cc

**Comment by fritzmg** [comment]
It will probably be irrelevant with Contao 4.2.0 or 5 when the new Logout page type is introduced (I am assuming such a page type is excluded from indexing anyway then) (https://github.com/contao/core-bundle/issues/236).

**Comment by stefansl** [comment]
Yes, it's definitly a configuration error. But maybe a lot of people run into this one. but as @fritzmg said, it could be irrelevant according to #236

**Comment by aschempp** [comment]
I agree it's a configuration problem. The only useful thing I can imagine is a blue hint in the module, similar as we do for the j_mediaplayer template.

**Comment by fenepedia** [comment]
I also ran in this problem a few days ago and it took my very long to find the problem.
+1 to a blue hint

**Comment by stefansl** [comment]
It's a very special case, so a hint is IMHO too much. Protecting the logout module from indexing would be more comfortable.

**Comment by aschempp** [comment]
That’s true. The logout module could automatically disable indexing of it’s contained page.

**Comment by leofeyer** [comment]
No, that does not work. If the page is not correctly configured, it will be included by `findSearchablePages()` and then called when the search index is rebuilt.

**Comment by stefansl** [comment]
I guess, we can close this. Implementing #8255 gives enough hints to users, when indexing fails.
