### ISSUE TITLE
E_DEPRECATED wird nicht beachtet

### ISSUE THREAD

**Issue by css-umsetzung** [contao/core#8254]
Das errorlog von Contao wächst in wenigen Stunden um mehrere MB an, da Contao nicht meine PHP Einstellungen beachtet, das ich keine deprecated Warnungen loggen oder sehen möchte.

Das Problem tritt nun extrem auf, da Deprecated Meldungen in der generateFrontendUrl eingefügt wurden.

**Comment by fritzmg** [comment]
The `generateFrontendUrl` actually creates `E_USER_DEPRECATED` errors.

Regardless of that, I think the bug is within the error handler here: https://github.com/contao/core/blob/3.5.8/system/helper/functions.php#L43 It checks for
```php
if (ini_get('error_reporting') > 0)
```
However, the PHP documentation states, that you should use
```php
if (error_reporting() > 0)
```
See http://php.net/manual/en/language.operators.errorcontrol.php

>  PHP supports one error control operator: the at sign (@). When prepended to an expression in PHP, any error messages that might be generated by that expression will be ignored.

> If you have set a custom error handler function with set_error_handler() then it will still get called, but this custom error handler can (and should) call error_reporting() which will return 0 when the call that triggered the error was preceded by an @. 

Possibly, with `ini_get('error_reporting')` you only get the server's PHP configuration value, but not the runtime value.

See also https://community.contao.org/de/showthread.php?61539-contao-5

**Comment by fritzmg** [comment]
Hm, can't confirm my suspicion on my local web server though.
```php
var_dump(error_reporting());
var_dump(ini_get('error_reporting'));
```
within the `__error` handler will yield
```
int(0)
string(1) "0"
```
when triggering
```php
@trigger_error('Test.', E_USER_DEPRECATED);
```

@css-umsetzung can you insert
```php
var_dump(error_reporting());
var_dump(ini_get('error_reporting'));
```
[here](https://github.com/contao/core/blob/3.5.8/system/helper/functions.php#L41) (before the if condition) and do the same test and post the results here?

**Comment by Babelfisch** [comment]
Den Fehler kann ich bestätigen. Habe ich in Contao `displayErrors` aktiviert, bekomme ich in der functions.php folgende Werte, wenn `@trigger_error` aufgerufen wurde:

```php
echo ini_get('error_reporting'); // 22519
echo error_reporting(); // 0
```

Mit `error_reporting()` in der Abfrage würden die Meldungen also korrekterweise nicht ausgegeben werden.

**Comment by discordier** [comment]
In fact, to ensure that really only errors for which the setting has been enabled are logged, it shoud rather be:
```diff
- if (ini_get('error_reporting') > 0)
+ if (!(error_reporting() & $intType))
```

However, we might want to consider to add `E_USER_DEPRECATED` to the exclusion in the default config.

**Comment by discordier** [comment]
See PR #8267
