### ISSUE TITLE
feature: show more feedback while rebuilding search index

### ISSUE THREAD

**Issue by fritzmg** [contao/core#8255]
#8253 got me thinking that a little more feedback during "rebuild index" would be helpful. So instead of just having a list like this:

![indexing01](https://cloud.githubusercontent.com/assets/4970961/13564365/6978e140-e449-11e5-8534-83481f69e77b.png)

the list could at least show the HTTP response status of the indexed page (if not `200`) and colourize according to the response code:

![indexing02](https://cloud.githubusercontent.com/assets/4970961/13564386/89ce6384-e449-11e5-8fa0-761e4e58a6c2.png)

This would help detecting the aforementioned misconfiguration as well as other misconfigurations like missing news archives/calenders in reader modules and the like.

**Comment by stefansl** [comment]
Nice one 🙌

**Comment by fritzmg** [comment]
I have created a gist for a `be_rebuild_index.html5` template that implements this behaviour. It also fixes a problem that is present in all Contao versions, where the 'complete' message is potentially shown too early.

https://gist.github.com/fritzmg/81acff5ed269f3281ee1

Simple put this template in your Contao's `/templates` directory.

**Comment by stefansl** [comment]
It's would be better to use the predefined Contao CSS classes (tl_red is already there). As we're using mooTools right now, it would be nicer not to inlude jQuery in the Backend. Try this script 
`<script>
      window.addEvent('domready', function() {
        var urls = $$('.page_url'),
            last = urls.length-1, url;
        urls.each(function(el, i) {
          el.getAttribute('data-url') && new Request({
            'url': el.getAttribute('data-url'),
            onProgress: function(event, xhr){
              var status = xhr.status;
              if (status == 200 ) {
                el.addClass('tl_green');
              } else {
                el.addClass('tl_red');
                el.appendText(' - ' + status);
              }
            },
            onComplete: function() {
              if (i == last) {
                $('index_loading').setStyle('display', 'none');
                $('index_complete').setStyle('display', 'block');
              }
            }
          }).get();
        });
      });
    </script>`

**Comment by stefansl** [comment]
Ok, for better readability I created a Gist: https://gist.github.com/stefansl/a896953e324beae1c10e

**Comment by fritzmg** [comment]
Yes, I used jQuery because I am not as proficient in MooTools. In your gist you should also change the loop logic and count the completed requests. Otherwise Contao will say it finished rebuilding the index before all requests really are finished.

**Comment by stefansl** [comment]
Oh ok, thx for the link. I guess, the loop is working as it should. The index i from the each function does this job. I tested it here.

**Comment by fritzmg** [comment]
> The index i from the each function does this job.

No, that's the problem. The function checks whether the completed request was the last element in the list of URLs. However, the last element in the list of URLs is not necessary the last request to be finished. The more pages have to be indexed, the more likely it is, that the last request is not the last URL. This happens because some pages simply take longer to generate and in general it's up to the browser in which order he executes the committed requests (they are not necessarily executed in the order of the each loop).

That's why you should simply count the completed requests and compare that to the total number of requests, as I am doing [here](https://gist.github.com/fritzmg/81acff5ed269f3281ee1#file-be_rebuild_index-html5-L5-L43).

**Comment by fritzmg** [comment]
Also you should use `onFailure` and `onSuccess` instead of `onProgress` :). The latter is not supported in all browsers.

**Comment by fritzmg** [comment]
I have updated the gist now with a MooTools version that does the same as the jQuery version.

**Comment by stefansl** [comment]
very nice +1 i deleted mine

**Comment by fritzmg** [comment]
@leofeyer Any chance you could integrate this into Contao `3.5.x` as well, along with #8262? (The posted script fixes both.) I know it would be a new feature, but it's such a small change ;)

**Comment by aschempp** [comment]
What's so difficult to understand that 3.5 will not get new features?

**Comment by fritzmg** [comment]
> What's so difficult to understand that 3.5 will not get new features?

There is nothing difficult to understand.

The next Contao LTS version will be released in June 2017 and its LTS support time frame will start in __December 2017__. So if you stay with LTS versions of Contao, you'll still use Contao `3.5.x` for another one and a half year or even almost 2 years.

Thus it feels extremely dogmatic and rigid to absolutely deny the current LTS version even the __tiniest bit__ of improvement.

**Comment by aschempp** [comment]
But that's the whole point. If you user **Long Term Support** you decide to use a very stable version that will get support for a long time, but you won't get new features. If you want new features, don't use an LTS version.

**Comment by fritzmg** [comment]
> But that's the whole point. If you user Long Term Support you decide to use a very stable version that will get support for a long time, but you won't get new features.

Yes, that is the technical definition. You can either stubbornly follow that rule or do what makes sense for Contao and its community.

Keep in mind that we aren't talking about system wide, deep changes here. This issue is about _a few additional lines of JavaScript code_, for _one single page in the backend_. Including this would not make the whole Contao system suddenly unstable.

**Comment by leofeyer** [comment]
@fritzmg I can understand your point. But in fact, stubbornly following that rule does make the most sense for Contao and its community. Otherwise we would end in a mess of code conflicts and a large number of discussions about why we broke the rule for certain features and not for other ones.

If you look at other open source projects (e.g. Debian), you will notice that they all follow this rule for a good reason.

**Comment by leofeyer** [comment]
Implemented in 5061876805588464fd95bcff2e8b4608dcce47e2.
