### ISSUE TITLE
Multiple Slashes /// in URLs possible

### ISSUE THREAD

**Issue by Hendriks** [contao/core#8256]
Online demo proof: http://demo.contao.org/en////navigation.html
Isn't this supposed to be massive duplicate content?

**Comment by fritzmg** [comment]
> Isn't this supposed to massive duplicate content?

Duplicate content is only a problem (for Google), if it's classified as malicious - e.g. equal content across multiple top level domains.

**Comment by leofeyer** [comment]
Found this: http://stackoverflow.com/a/21304287

**Comment by leofeyer** [comment]
@contao/developers /cc

**Comment by Toflar** [comment]
Imho it should be taken care in our `getPageIdFromUrl` or whatever it's called.

**Comment by leofeyer** [comment]
That's not possible, because Apache will rewrite the URL so Contao never knows that there have been multiple slashes. On application level, we only have the possibility to adopt the wrong (!) behavior for other browsers than Apache, which handle double slashes correctly in the first place. :smile:

**Comment by leofeyer** [comment]
@Hendriks Can you please check if the following rewrite rule fixes the issue?

```apache
  # Put this in your .htaccess file after RewriteBase
  RewriteCond %{REQUEST_URI} //
  RewriteRule .* - [F,L]
```

**Comment by Hendriks** [comment]
@leofeyer Sorry, I tried it but it doesn't seem to fix the issue...

**Comment by leofeyer** [comment]
That is because Apache has already merged any double slashes in the URL Contao sees. If the rewrite rules does not work, there is no way for us to fix it.
