### ISSUE TITLE
Debug-Chanels im Debug-Panel wählbar z.B. als Tabs

### ISSUE THREAD

**Issue by xantippe** [contao/core#8258]
Debug-Chanels im Debug-Panel wählbar z.B. als Tabs

**Comment by Toflar** [comment]
Alles schon vorhanden in Contao 4.

**Comment by xantippe** [comment]
für 3.5x kommt keine Anpassung (mehr)?

**Comment by BugBuster1701** [comment]
Feature für 3.5 kommen nicht mehr. Siehe Release Plan. Die 3.5 ist die LTS und es kommen nur noch Bugfixe.
