### ISSUE TITLE
gleiche Einheitendarstellung im Debug-Panel zwischen Arrayangaben und Header

### ISSUE THREAD

**Issue by xantippe** [contao/core#8259]
gleiche Einheitendarstellung im Debug-Panel zwischen Arrayangaben und Header

siehe 
![shot156](https://cloud.githubusercontent.com/assets/1045318/13570492/c83ccc76-e46e-11e5-930b-f2ac1c095914.jpg)

**Comment by fritzmg** [comment]
Das passt doch, oder? Die zweite Markierung bedeutet ja wahrscheinlich 2ms (sonst wäre ja die gesamte Execution time mindestens 2000ms).

**Comment by leofeyer** [comment]
Ich sehe hier auch keinen Fehler.
