### ISSUE TITLE
Fehler in Suche bei Komma im Keyword

### ISSUE THREAD

**Issue by pcr-coding** [contao/core#8260]
##### Folgendes vorausgesetzt

1. Es befinden sich Kommazahlen (z. B. `2,55`) in einem Artikel der durchsucht werden kann.
2. Es wird ein Suchbefehl der eine Zahl enthält ausgeführt (z. B `ABC 55`).

##### Es tritt folgender Fehler auf
In der Ergebnisliste der Suche werden die Keywords nach denen gesucht wurde farbig markiert. Dabei wird die `2` aus der Kommazahl `2,55` fälschlicherweise farbig markiert obwohl `2` kein Suchwort war.

##### Woran liegt der Fehler?
Die Contao-Suche merkt sich alle Treffer (siehe [`Search.php`](https://github.com/contao/core/blob/master/system/modules/core/library/Contao/Search.php#L414-L415)) damit diese später farbig markiert werden können. Dazu werden die Treffer mit `GROUP_CONCAT(word)` in einem Feld `matches` zusammengeführt. Da das Keyword `2,55` bereits ein Komma enthält kann es in den zusammengeführten `matches` nicht mehr vom Listentrennzeichen (das ebenfalls ein Komma ist) unterschieden werden (z. B.: `aaa,bbb,2,55,ccc,eee,...`).

Hier sollte ein Listentrennzeichen verwendet werden das nicht im Keyword vorkommen kann, da sonst das Highlighting später fehlerhaft ist.

**Comment by leofeyer** [comment]
Ich kann das Problem nicht nachvollziehen.

Ich habe die Kommazahl `2,55` in ein Text-Element geschrieben und den Suchindex neu aufgebaut. Die Suche nach "ABC 55" findet jedoch nichts, da die Kommazahl als Ganzes als Keyword in den Suchindex geschrieben wurde (also `2,55` und nicht `2` und `55`).

Wie genau lässt sich der Fehler reproduzieren?
