### ISSUE TITLE
3.5.8 Kann Layout-Builder nicht deaktivieren

### ISSUE THREAD

**Issue by Anke** [contao/core#8261]
Hallo,

ich habe zwei Websites von 3.5.6 auf 3.5.8 geupdated. Seitdem lässt sich der Layout-Builder nicht deaktivieren. Er aktiviert sich sogar von selbst in Layouts, in denen er deaktiviert war.

Kann das Problem leider in der Demo nicht prüfen, da hier noch die 3.5.6 installiert ist. Hat irgend jemand dasselbe Problem und falls ja, eine schnelle Lösung parat?

VG
Anke

PS: Check ist okay. Fehlermeldungen gibt es keine. Ändere ich die Framework-Optionen in der DB, ist alles in Ordnung, bis ich im BE ein Seitenlayout erneut speichere. Dann hat der Layout-Builder wieder ein Häkchen.

**Comment by BugBuster1701** [comment]
Hast du das "Responsive Layout" aktiviert? Denn dann wird ab 3.5.7 automatisch die layout.css aktiviert. Ich könnte mir vorstellen, dass nun irgendwo aus diesem Grund auch der Builder mit aktiviert wird, habs aber nicht geprüft.

**Comment by Anke** [comment]
Danke, Glen, hast recht. Bei deaktviertem Responsive Layout lässt sich auch der Layout Builder deaktivieren. Unpraktisch, da ich oft das Responsive Layout und eine Hybridversion aus Layout Builder und einem Liquid-Framework nutze.

**Comment by fenepedia** [comment]
So viel CSS steht in der responsive.css ja nicht drin. Denke am einfachsten ist, dass du einfach das CSS bei dir einfügst.

 `/* Contao Open Source CMS, (c) 2005-2015 Leo Feyer, LGPL license */
@media(max-width:767px){#wrapper{margin:0;width:auto}#container{padding-left:0;padding-right:0}#main,#left,#right{float:none;width:auto}#left{right:0;margin-left:0}#right{margin-right:0}}img{max-width:100%;height:auto}.ie7 img{-ms-interpolation-mode:bicubic}.ie8 img{width:auto}`

**Comment by fenepedia** [comment]
Siehe auch dieses Ticket: https://github.com/contao/core/issues/8222

Und hier die File https://github.com/contao/core/blob/master/assets/contao/css/responsive-uncompressed.css

**Comment by Anke** [comment]
Stand das in den Release Notes?

**Comment by BugBuster1701** [comment]
Wenn du damit den "Bugfix2 #8222 meinst, nein, der taucht [hier](https://github.com/contao/core/releases/tag/3.5.7) leider nicht auf.
