### ISSUE TITLE
Navigation bug concerning modules lost password and login

### ISSUE THREAD

**Issue by Defcon0** [contao/core#8263]
Hello folks,

I found a an issue in the login module combined with the lost password module. Given that the login module has checked the field "redirectBack" consider the following action path:

1. Log out if not already logged in.
2. Navigate to a lost password page and fill out the form
3. A link is sent to you -> click it
4. Fill out this for as well and confirm.
5. Now you're redirected to the login page
6. After logging in with the new password, you'll be redirected to the page you visited before which is the lost password url containing a token already used
7. You get a nasty error message

I couldn't found a good solution yet, but maybe someone else has one?

**Comment by fritzmg** [comment]
I think you need to create a separate login module and put it on a separate page. Then choose this page as your redirect page in your lost password module.

**Comment by Defcon0** [comment]
You're right, setting the confirm page to login with "rediretBack" is a bad idea :)
