### ISSUE TITLE
Settings from frontend preview also affect regular page visits (while being logged in the BE)

### ISSUE THREAD

**Issue by bezin** [contao/core#8268]
Hello all,

I run in a weird issue today I never experienced yet, but which I'd like to discuss:

I always recognized the frontend preview and a regular page visit as two different modes. The first is more like an editor mode – indicated by the tool bar at the top, the second is the page the way the regular user will see it. Hence I do not expect settings I made in FE preview mode to affect the regular page requests, e.g. showing hidden elements or pages. 

Reproduce in the online demo: 
1. Log into the BE and go to the FE preview
2. Select "Show hidden elements"
3. Leave the FE preview and go to demo.contao.org, while still being logged in to the BE. 

You do not have the toolbar anymore, but the settings are still active. To me this is rather confusing, since the editor/admin has no feedback about this setting anymore. In my opinion, from a user experience point-of-view, this setting should only be active, when in preview mode. 

I just wanted to check whether I am alone with my perception of the situation ;)

Cheers!

**Comment by asaage** [comment]
i noticed that to and think it would be absolutely neceesary to get rid of the cookie if the preview-bar is not present.

**Comment by aschempp** [comment]
This is the expected behavior. Things like a responsive design do not work if the bar is visible.
