### ISSUE TITLE
Fehler bei File::getContent() wenn die Datei beschrieben aber noch nicht geschlossen ist.

### ISSUE THREAD

**Issue by agoat** [contao/core#8269]
Wenn ich eine Datei erstelle mit
`$objFile = new \File(pfad, true)`
und dann Daten hineinschreibe (wie in der Combiner Klasse)
`$objFile->append($daten)`
funktioniert es.
Wenn ich aber Daten an den Anfang schreiben will oder die bereits geschriebenen Daten wieder lesen möchte 
`$objFile->prepend($daten)`
`$data = $objFile->getContent()`
führt daszu einem Fehler: **failed to open stream: No such file or directory in system/modules/core/library/Contao/File.php on line 599**

Wenn man in die core/library/Contao/File.php hineinschaut, dann wird bei getContent() das File neu geöffnet und die Daten gelesen. Allerdings wird eine temporäre Datei bei append() und write() verwendet und erst bei close() die Datei am richtigen Pfad erstellt wenn $blnDoNotCreate gesetzt ist. Sollte da die getContent() Methode nicht ebenfalls auf die temporäre Datei zugreifen??

**Comment by leofeyer** [comment]
Fixed in 0a5324c210aaf9b05a6cffea21f5f5e6bba70a89.
