### ISSUE TITLE
Events: Time output in event_full does not work

### ISSUE THREAD

**Issue by jankout** [contao/core#8271]
Unfortunately, the time of events cannot be outputted in the template _event_full_ with this code.

```
<?php if ($this->time): ?>, <?= $this->time ?><?php endif; ?>
```

 Is there a solution for it?

**Comment by fritzmg** [comment]
Should be perfectly possible. May be you have an invalid time format setting in your page root?

**Comment by jenda77** [comment]
No, the settings are right. It works with any problems in event_teaser with <?php echo $this->time  . " Uhr"; ?> but in the event_full not.

**Comment by fritzmg** [comment]
Well, what happens in your event_full template then? No output at all? Is the comma being outputted but the time itself not?

**Comment by jenda77** [comment]
no, nothing will be outputted.

**Comment by jenda77** [comment]
The time will not be outputted. 

`<?php if ($this->time): ?>, <?= $this->time ?><?php endif; ?>` does not work. Just `<?= $this->date ?>`, but then will be the time outputted with the brackets.

**Comment by jenda77** [comment]
Here my solution

```
 <span class="day"><?php echo ($this->parseDate("l", $this->startDate)); ?></span>
<span class="date"><?php echo ($this->parseDate("d.m.Y", $this->startDate)); ?></span><span class="time"><?php if ($this->begin): ?>, <?php echo ($this->parseDate("H:i", $this->begin) . " Uhr"); ?><?php endif ?>
```

**Comment by leofeyer** [comment]
You cannot expect every template to work the same. `<?= $this->time ?>` works in the `event_teaser.html5` template but it does not in the `event_full.html5` or `event_upcoming.html5`.

What exactly are you trying to accomplish?

**Comment by Aybee** [comment]
IMHO it did not depend on a template, it depends on the module type you have choosen. Event reader and event list both use event_xxx templates. Different module types output different variables. So we should not argue "it works in event_full and not in event_last" but "it works in reader and not in list".

**Comment by leofeyer** [comment]
I have added `<?php dump($this->time); ?>` in the `event_upcoming.html5` and `event_full.html5` templates and I have modified the "Contao North-Day" event like this:

<img width="891" alt="" src="https://cloud.githubusercontent.com/assets/1192057/20392448/2ed8d326-acd8-11e6-8a90-2c03d5b8513e.png">

Now when I open the list of upcoming events (`en/events.html`), the dump output is `09:00 – 18:00` and when I open the event reader (`en/event-detail/contao-north-day.html`), the dump output is is `09:00 – 18:00` as well.

Did I do it wrong or is the ticket invalid?

**Comment by Aybee** [comment]
Maybe his events span multiple days.

In your settings add a date e.g. `2014-10-27` into field `End date` . Then you will see that `time` is an empty string.
