### ISSUE TITLE
isset() in \Input?

### ISSUE THREAD

**Issue by Defcon0** [contao/core#8272]
Hello folks,

is there any special reason, why there's no isset()-representation in \Input available? I need this for checking if some value is filtered or not (even if the value is '').

Bye

**Comment by Toflar** [comment]
Why don't you just use `isset($_POST['key'])`??

**Comment by leofeyer** [comment]
That's what I use, too.

**Comment by Defcon0** [comment]
Just for convenience. In some of our modules, it's needed to specify a general method which can be set to get or post in the concrete implementation. In this case it would be nice to just call `\Input::isset($strMethod, $strField);` instead of `$strMethod == 'get' ? \Input::get($strField) : \Input::post($strField);`

**Comment by leofeyer** [comment]
Do you mean this?

```php
// Current
isset($_POST[$field]) ? Input::post($field) ? Input::get($field);

// Current
Input::hasPost($field) ? Input::post($field) ? Input::get($field);
```

**Comment by Defcon0** [comment]
Exactly

**Comment by leofeyer** [comment]
You do realize that your version is actually longer, don't you?

**Comment by Defcon0** [comment]
My version is an addition if the method is stored to a variable. Hence, the following methods would be useful:

Input::hasGet($field)
Input::hasPost($field)
Input::has($field, $method)

**Comment by aschempp** [comment]
As this would be a new feature to me, I vote against it. We should not add new features to the old classes in Contao 4. The Symfony request object has methods for that: 
```php
$request = \System::getContainer()->get('request_stack')->getCurrentRequest();
$request->query->has('xxx') // GET
$request->request->has('xxx') // POST
```

**Comment by Defcon0** [comment]
Ah, ok. I didn't use Contao 4, yet, so I didn't know that. In this case, this would be enough, of course. Even if the syntax is painfully long, I understand the use cases for this wrapper (testing e.g.).

**Comment by aschempp** [comment]
Absolutely correct. In a real Symfony class (service) you would use dependency injection so you wouldn't need the `\System::getContainer()->get('…')` call.

**Comment by Defcon0** [comment]
Ah,  I see. Thanks for clearification :+1:
