### ISSUE TITLE
Spaltennamen ohne Backticks

### ISSUE THREAD

**Issue by Samson1964** [contao/core#8273]
Im Contao-Core ist es üblich bei SQL-Queries die Tabellen- und Spaltennamen nicht zusätzlich mit Backticks zu schützen, wie das eiegentlich gemacht werden sollte. Eine Abfrage wie
```
UPDATE tl_webgrab_replaces SET replace='red' WHERE id='1'
```
führt zu einer Fehlermeldung, da replace als Befehl interpretiert wird. Gibt es diesbezüglich Tendenzen, sich der empfohlenen MySQL-Syntax anzunähern?
Ich benutze jetzt erstmal einen anderen Spaltennamen.

http://dev.mysql.com/doc/refman/5.1/en/keywords.html

**Comment by BugBuster1701** [comment]
Also mit Backticks in meinen Erweiterungen habe ich keine Probleme:

>        $objDlstats = \Database::getInstance()
                    ->prepare("SELECT * FROM `tl_dlstats`
                        WHERE `id`=?")
                    ->execute($dlstatsid);

Funktioniert bei mir.
Reservierte Worte zu vermeiden ist aber prinzipiell eine gute Idee.

**Comment by leofeyer** [comment]
Siehe #8062.
