### ISSUE TITLE
Weiterleitungen bei Error 404 und 403 werden mit Status-Code generiert

### ISSUE THREAD

**Issue by cboelter** [contao/core#8274]
Ich habe eine frische Contao 3.5.8, dort ist es so das wenn ich bei den Fehlerseiten 404 und 403 eine Weiterleitung auswähle, wird diese mit dem HTTP-Status-Code erzeugt.

Beispiel: login301.html statt login.html

Gefixed habe ich es durch folgenden Code:

https://github.com/contao/core/blob/master/system/modules/core/pages/PageError403.php#L87 
$this->redirect($objNextPage->getFrontendUrl(), ($obj403->redirect == 'temporary') ? 302 : 301);  

https://github.com/contao/core/blob/master/system/modules/core/pages/PageError404.php#L124
 $this->redirect($objNextPage->getFrontendUrl(), ($obj404->redirect == 'temporary') ? 302 : 301);

In dem ursprünglichen Code werden die HTTP-Codes als URL-Parameter betrachtet, was zu dem Problem führt.

**Comment by bytehead** [comment]
Duplicate of #8243.
