### ISSUE TITLE
Add CSV delimiter to DC_File

### ISSUE THREAD

**Issue by richardhj** [contao/core#8278]
Please add the possibility to save fields with ```'multiple'=>true``` csv delimited via the DC_File like it is possible in the DC_Table.
It would be nice to see the implementation in the 3.5. branch :-)

**Comment by aschempp** [comment]
I don’t think we should add that.

1. Contao 3.5 will not get new features
2. The localconfig.php is deprecated in Contao 4

**Comment by discordier** [comment]
I'm with @aschempp on this one. As localconfig.php is deprecated, so should be the DC_File.

**Comment by richardhj** [comment]
Yeah, I just forgot. I agree.
