### ISSUE TITLE
import events with CSV, start date timestamp pb

### ISSUE THREAD

**Issue by vmulot** [contao/core#8280]
Hi,

Contao 3.5.8

I'm using a custom module with custom class to import some events from a csv.
All is going well,except one thing : startTime/endTime, startDate, endDate

The date (or time) is stored as a timestamp, and seems to be good (checked in phpmyadmin,or even dumped from my script) but when i check in Contao BO, all of my newly imported events have the same startDate(or time) displayed in the list.
if i edit one (or multiple) events and i just save them again(nothing was changed), dates are well displayed.

but with 13 000 events imported in different calendars, i can't edit them all manually.

i'm using :
`$db->prepare('INSERT INTO tl_calendar_events %s')->set($arrAtelier)->execute()`
i tried also with:
`$db->prepare('INSERT INTO tl_calendar_events SET(....) VALUES(???...)->execute(array(...,...,..)`

results are the same.
edit: it seems it display the default date (the today's one) untill i save all again with contao.
any clue ?
Sorry for my english, i hope, you'll understand the pb.

Thanks !

**Comment by leofeyer** [comment]
Please refer to the [forums](https://community.contao.org) for this kind of questions.

**Comment by vmulot** [comment]
Ok thanks, i thought it could be a Contao issue that's why i went here first.
