### ISSUE TITLE
Kalender - zum aktuellen Monat

### ISSUE THREAD

**Issue by mecintosch** [contao/core#8283]
Fehler wurde im Forum schon kurz besprochen...
https://community.contao.org/de/showthread.php?61831-Kalender-in-den-aktuellen-Monat-bl%E4ttern&p=403491

Der Kalender öffnet sich immer mit Ansicht des aktuellen Monats, auch wenn es keine Einträge in diesem Monat gibt. Gibt es ältere Einträge und wechselt man mit < Previous dort hin, hat man anschließend keine Möglichkeit mehr zum aktuellen Monat zurück zu wechseln. 

Dass man bei Nichtvorhandensein von künftigen Einträgen nicht in die Zukunft wechseln kann finde ich schon richtig, aber den aktuellen Monat sollte man schon immer anwählen können.

**Comment by leofeyer** [comment]
Behoben in a167c39da7f7ed281449e12bb14d3b03cb3912d6.
