### ISSUE TITLE
TCPDF erzeugt Fehler und beendet Contao

### ISSUE THREAD

**Issue by Samson1964** [contao/core#8284]
1. In Demo in Artikel "About Contao" die Syndikation PDF aktivieren
2. http://demo.contao.org/en/about-contao.html aufrufen und auf PDF klicken

Mehr Infos im Contao Forum https://community.contao.org/de/showthread.php?60494-PDF-Export-mit-Tabelle&p=403529

**Comment by do-while** [comment]
Das passiert aber nicht auf allen Seiten der Demo. Beispiel: [http://demo.contao.org/en/text-elements.html](http://demo.contao.org/en/text-elements.html)

**Comment by do-while** [comment]
Sobald man das Tabellen-Element deaktiviert, geht es.

**Comment by asaage** [comment]
prüft mal auf alleinstehende ```[nbsp]``` innerhalb von egal welchen tags.
Ich hab das Problem schon länger.

**Comment by leofeyer** [comment]
Ich konnte das Problem in der Onlinedemo nicht nachvollziehen.
