### ISSUE TITLE
Image "changelog.gif" could not be found

### ISSUE THREAD

**Issue by SpeGal** [contao/core#8287]
Since the new update to 3.5.9 the changelog.gif can not be found by the system anymore. I get constant error logs because of it. I guess it only concerns the maintanance page in the backend but still: the little icon is missing on the right of the Contao status message. It is still in the folder on the server as it is supposed to be but the link seems to be broken now:

Details: 	Image "changelog.gif" could not be processed: Image "changelog.gif" could not be found
Funktion: 	Contao\Image::get

Code from the maintanance page in the backend:
`<p class="tl_confirm">Ihre Contao-Version 3.5.9 ist aktuell <a href="contao/changelog.php" onclick="Backend.openModalIframe({'width':860,'title':'CHANGELOG','url':this.href});return false" title=""></a></p>`

**Comment by bytehead** [comment]
It's already fixed in https://github.com/contao/core/commit/cbf025662c6b5e761e11353f7892efa0706acc72 (3.5.10).
