### ISSUE TITLE
Presentation of checkboxes and radios field label with formgernerator in BE preview

### ISSUE THREAD

**Issue by Aybee** [contao/core#8288]
Das hier wollte ich schon immer mal gemeldet haben, weil ich finde, dass das unschön aussieht. Also *myRadiobuttons* sollte links stehen, da wo auch *myTextfield* steht.

![formgenerator](https://cloud.githubusercontent.com/assets/1143013/14020444/6e364a2e-f1d7-11e5-9794-e2846bf52dc0.png)
Im Quellcode sieht das so aus, dass die erste Tabellenspalte dabei leer bleibt.
**Text field**
```html
<table class="tl_form_field_preview">
    <tr class="">

      <td class="col_0 col_first">
        <label class="mandatory" for="ctrl_22">
          <span class="invisible">Mandatory field</span>
          myTextfield
          <span class="mandatory">*</span>
        </label>
      </td>

      <td class="col_1 col_last">
        <input type="text" placeholder="myTextfield" value="myTextfield" class="text mandatory" id="ctrl_22">
      </td>

    </tr>
</table>
```
**Radio buttons menu** (Checkbox menu dito) (empty first column)
```html
<table class="tl_form_field_preview">
    <tr class="">

      <td class="col_0 col_first">&nbsp;</td>

      <td class="col_1 col_last">
        <fieldset class="radio_container mandatory" id="ctrl_24">
          <legend>
            <span class="invisible">Mandatory field</span>
            myRadiobuttons
            <span class="mandatory">*</span>
          </legend>
          <span>
            <input type="radio" value="1" class="radio" id="opt_24_0">
            <label for="opt_24_0" id="lbl_24_0">one</label>
          </span>
          <span>
            <input type="radio" value="2" class="radio" id="opt_24_1">
            <label for="opt_24_1" id="lbl_24_1">two</label>
          </span>
        </fieldset>
      </td>

    </tr>
</table>
```

**Comment by leofeyer** [comment]
Ja klar, weil das Label im zweiten Beispiel die `<legend>` ist und die kann nicht außerhalb von `<fieldset>` stehen.

**Comment by Aybee** [comment]
Evtl. hilft ein kleiner Patch mit CSS auf diese LEGEND
```css
element.style {
  position: absolute;
  left: 4px;
}
```
Ich seh grad, dass das LABEL von den Textareas nicht zu sehen ist. Soll ich dafür ein neues Ticket aufmachen? Da würde auch eine CSS-Anpassung helfen.
```css
.tl_form_field_preview td {
  vertical-align: top;
}
/* vielleicht sogar */
th, td {
  vertical-align: top;
}
```
Ich richte das mal in meinem BE ein und behalte es im Auge, ob es irgendwo negative Auswirkungen hat.

**Comment by leofeyer** [comment]
Was ist das denn für eine Contao-Version? `<table class="tl_form_field_preview">` gibt es bei mir gar nicht.

**Comment by Aybee** [comment]
Mmh, ist aus der Online-Demo, 3.5.9. Gerade nochmal nachgeschaut mit radio und checkbox.

**Comment by leofeyer** [comment]
Geändert in 3158e586381908b3baa4657465111372312782c4.
