### ISSUE TITLE
Erlaubte Download-Dateitypen: Groß-/Kleinschreibung macht einen Unterschied

### ISSUE THREAD

**Issue by mathContao** [contao/core#8289]
Hallo zusammen,

folgendes Problem habe ich mit Contao 3.5.4:
==== Zusammenfassung =====
"Erlaubte Download-Dateitypen" / "Download file types" sind case-sensitiv. GROß-geschriebene Dateiendungen werden anders behandelt als klein-geschreibene Dateiendungen.

==== Ausführliche Beschreibung ======
Dateiverwaltung:
dort liegen in dem einen Ordner 2 Text-Dateien (Endung txt und TXT)
![screen0_dateimanager](https://cloud.githubusercontent.com/assets/1645099/14049643/d45932d2-f2b6-11e5-8674-732cf5ce8f23.png)

In den System-Einstellungen ist als Download-Dateiendung "TXT" (Großbuchstaben) angegeben:
![screen1_einstellungen_txt](https://cloud.githubusercontent.com/assets/1645099/14049703/4408ff40-f2b7-11e5-8450-306c776b46f6.png)

Und kann die beiden Dateien jedoch nicht im Dateiwähler (z.B. in den Nachrichten als Anhang) finden:
![screen2_nicht_da](https://cloud.githubusercontent.com/assets/1645099/14049958/de2305fc-f2b8-11e5-8a0d-2bed74d994d9.png)

Ändere ich jedoch in den System-Einstellungen die Download-Endung von "TXT" auf "txt":
![screen3_einstellungen_txt](https://cloud.githubusercontent.com/assets/1645099/14051619/b572ab06-f2c4-11e5-90cf-951e0dfeeb36.png)

dann sind die beiden Text-Dateien plötzlich doch wieder zu finden (z.B. in den Nachrichten als Anhang):
![screen4_datei_da](https://cloud.githubusercontent.com/assets/1645099/14051737/7910ff68-f2c5-11e5-8460-2961987f9868.png)

Leider lässt sich das Verhalten in der Demo nicht nachvollziehen, da Änderungen in den Systemeinstellungen nicht möglich sind

**Comment by Aybee** [comment]
Dateitypen kannst du nur kleingeschrieben angeben. `TXT` wird nicht als Dateityp erkannt. Die Dateien `test.txt` und `test.TXT` werden in tl_files beide unter `extension = txt` verwaltet. In diesem Fall hättest du auch nur einen Datensatz für diese beiden Dateien.

Da z.B. für Windows `test.txt` und `test.TXT` ein und dieselbe Datei sind, solltest du auch keine Datein mit Großbuchstaben im Suffix verwenden.

Inwieweit Contao da jetzt drauf achten kann, dass z.B. der Upload von `test.TXT` verboten wird, wenn schon eine `test.txt` existiert, weiß ich nicht.

**Comment by mathContao** [comment]
die Erklärung klingt verständlich.

Problem: Es ist nirgends beschrieben, dass in den Einstellungen nur Kleinbuchstaben je Endung eingegeben werden soll.

Und: bei "Erlaubte Upload-Dateitypen" spielt die Groß- und Kleinschreibung wiederum keine Rolle.

Ich hatte Spezial-Dateiendungen dort eingetragen. Die Software generiert automatisch Dateiendungen mit Großbuchstaben. Deshalb habe ich die Großschreibung direkt für Contao übernommen. Und beim Upload hat es ja problemlos funktioniert.

Meine Lösungsvorschläge:
1) Beschreibungstext bei "Erlaubte Download-Dateitypen" (und ggf. die anderen Felder) anpassen und darauf hinweisen, dass nur Kleinbuchstaben verwendet werden sollen.
2) Groß- und Kleinbuchstaben zulassen. Und dann ein LowerCase() durchführen, wenn die Dateiendungen benötigt werden

**Comment by leofeyer** [comment]
Geändert in 9a2adee9d6823bc98a745b00e9f19570cc0baaec.

**Comment by poldixd** [comment]
Ich habe das Update durchgeführt und jetzt gesehen, dass die Änderung wichtig ist. Nur haben wir ca. 400 **JPG**s im System, die nun nicht mehr funktionieren. Wenn ich diese alle per Batch umändere in **jpg**, dann geht die Verknüpfung zu den _Content Elementen_ weg und ich muss alle neu zuordnen.

**Comment by bytehead** [comment]
Related to #8317

**Comment by fritzmg** [comment]
> Ich habe das Update durchgeführt und jetzt gesehen, dass die Änderung wichtig ist. Nur haben wir ca. 400 JPGs im System, die nun nicht mehr funktionieren. Wenn ich diese alle per Batch umändere in jpg, dann geht die Verknüpfung zu den Content Elementen weg und ich muss alle neu zuordnen.

Lieber ein downgrade auf `3.5.9` machen oder auf `3.5.12` warten - nichts an den Dateien oder der Datenbank ändern.
