### ISSUE TITLE
error handler does not remove full path on windows

### ISSUE THREAD

**Issue by fritzmg** [contao/core#8290]
The error handler of Contao usually removes the full path to the file where the error happens [here](https://github.com/contao/core/blob/3.5.9/system/helper/functions.php#L108) and [here](https://github.com/contao/core/blob/3.5.9/system/helper/functions.php#L111). This was introduced in Contao `2.11.9` due to #4971. However string operations like
```php
str_replace(TL_ROOT . '/', '', …)
```
will not work under Windows since `TL_ROOT` and any other file path coming from PHP will contain backwards slashes (except for paths from the FilesystemIterator when `FilesystemIterator::UNIX_PATHS` is used). Since `TL_ROOT` is appended with a forward slash, the root directory will never be removed from the file path.

This is also an ongoing problem in Contao 4:

- contao/core-bundle#208
- contao/core-bundle#224
- contao/core-bundle#461
- contao/core-bundle#464

Any instances of
```php
str_replace(TL_ROOT . '/', '', …)
```
need to be replaced with
```php
str_replace(TL_ROOT . DIRECTORY_SEPARATOR, '', …)
```
in Contao 3.5 and 4.

**Comment by leofeyer** [comment]
I have fixed the function in a6c5bd26c1c1a3ae941645cc8d0de485f9d08032.

However, there are a few other places where I don't know if the path is normalized or not on Windows:

* [DC_Folder.php line 838](https://github.com/contao/core/blob/master/system/modules/core/drivers/DC_Folder.php#L838)
* [DC_Folder.php line 2000](https://github.com/contao/core/blob/master/system/modules/core/drivers/DC_Folder.php#L2000)
* [DC_Folder.php line 2371](https://github.com/contao/core/blob/master/system/modules/core/drivers/DC_Folder.php#L2371)
* [DC_Folder.php line 2392](https://github.com/contao/core/blob/master/system/modules/core/drivers/DC_Folder.php#L2392)
* [DC_Folder.php line 2466](https://github.com/contao/core/blob/master/system/modules/core/drivers/DC_Folder.php#L2466)
* [Form line 453](https://github.com/contao/core/blob/master/system/modules/core/forms/Form.php#L453)
* [Form line 502](https://github.com/contao/core/blob/master/system/modules/core/forms/Form.php#L502)
* [BaseTemplate line 109](https://github.com/contao/core/blob/master/system/modules/core/library/Contao/BaseTemplate.php#L109)
* [FileSelector line 305](https://github.com/contao/core/blob/master/system/modules/core/widgets/FileSelector.php#L305)
* [FileSelector line 363](https://github.com/contao/core/blob/master/system/modules/core/widgets/FileSelector.php#L363)

@contao/developers /cc

**Comment by BugBuster1701** [comment]
Witzig, habe ich gestern dran gearbeitet für meine errorlog_enhanced Erweiterung.Dabei habe ich unter Windows festgestellt, das machmal sogar eine Mischung zurück kommt, also TL_ROOT in Windowsschreibweise und dann weiter mal mit `/` und mal mit `\ `.
Ich habe es dann so geändert:
```
str_replace(array(TL_ROOT . '/',TL_ROOT . '\\' ), array('',''), ...)
```

**Comment by BugBuster1701** [comment]
DIRECTORY_SEPARATOR fängt aber schon das meiste ab, von daher eine Verbesserung.

**Comment by leofeyer** [comment]
`DIRECTORY_SEPARATOR` funktioniert aber nur, wenn der Pfad nicht schon normalisiert ist. Und genau das ist das Problem, denn die Hälfte der Pfade in Contao ist normalisiert und die andere nicht – je nachdem, woher der Pfad kommt.

**Comment by fritzmg** [comment]
In [DC_Folder.php line 838](https://github.com/contao/core/blob/3.5.9/system/modules/core/drivers/DC_Folder.php#L838) you can remove `str_replace` altogether. Look at line [#822](https://github.com/contao/core/blob/3.5.9/system/modules/core/drivers/DC_Folder.php#L822) - you are already asserting there, that `$source` does _not_ contain `TL_ROOT` (`$source` does in fact not contain `TL_ROOT`).

In [DC_Folder.php line 2000](https://github.com/contao/core/blob/3.5.9/system/modules/core/drivers/DC_Folder.php#L2000) you are adding the forward slash to `TL_ROOT` yourself:
```php
… TL_ROOT . '/assets/images/*/' …
```
thus it's fine to do `str_replace(TL_ROOT . '/', '', $strThumbnail)`.

In [DC_Folder.php line 2371](https://github.com/contao/core/blob/3.5.9/system/modules/core/drivers/DC_Folder.php#L2371) the path given to `DC_Folder::generateTree` contains a _forward_ slash after `TL_ROOT`, e.g.
```
C:\xampp\htdocs\c35dev/files
```

Since the path given to `DC_Folder::generateTree` contains a _foward_ slash after `TL_ROOT`, the same is true for [DC_Folder.php line 2392](https://github.com/contao/core/3.5.9/master/system/modules/core/drivers/DC_Folder.php#L2392)
```
C:\xampp\htdocs\c35dev/files/_test
```

And of course for [DC_Folder.php line 2466](https://github.com/contao/core/3.5.9/master/system/modules/core/drivers/DC_Folder.php#L2466) as well.


This is because `DC_Folder::generateTree` is called like this:
```php
$this->generateTree(TL_ROOT . '/' . \Config::get('uploadPath'), …);
```
i.e. with a forward slash after `TL_ROOT`.

**Comment by fritzmg** [comment]
The file path in `$_SESSION['FILES'][…]['tmp_name']` contains a _forward_ slash due to https://github.com/contao/core/blob/3.5.9/system/modules/core/forms/FormFileUpload.php#L299
```php
'tmp_name' => TL_ROOT . '/' . $strFile
```

**Comment by leofeyer** [comment]
@fritzmg Thanks a lot for checking. What about the [BaseTemplate](https://github.com/contao/core/blob/master/system/modules/core/library/Contao/BaseTemplate.php#L109) class?

**Comment by fritzmg** [comment]
The path in question in the BaseTemplate class also contains a _forward_ slash after `TL_ROOT`, e.g.:
```
C:\xampp\htdocs\c35dev/system/modules/core/templates/navigation/nav_default.html5
```
due to https://github.com/contao/core/blob/3.5.9/system/modules/core/library/Contao/TemplateLoader.php#L105 (and so on)
```php
return TL_ROOT . '/…
```

**Comment by leofeyer** [comment]
Ok, thanks again. Then the issue should be fixed in Contao 3.
