### ISSUE TITLE
MooTools templates

### ISSUE THREAD

**Issue by Aybee** [contao/core#8294]
Die Kapselung der Skripte in den MooTools-Templates ist unterschiedlich.

**accordion**, **chosen**, **slider**, **tablesort**
```js
(function() {
  // code
})();
```
**mediabox**, **slimbox**
```js
(function($) {
  // code
})(document.id);
```
Hat das einen bestimmten Grund? Oder können wir das vereinheitlichen? Ist eins davon besser?

**Comment by fritzmg** [comment]
In den ersteren Fällen wird die Funktion `$` bzw. `document.id` nicht benötigt, daher wird wird sie auch nicht in die gekapselte Funktion weitergegeben.

**Comment by Aybee** [comment]
Ich danke dir für die Antwort. Hättest du vielleicht auch noch ne kurze Begründung, wieso das einmal benötigt wird und einmal nicht?

Wird hier vielleicht einmal einem Konflikt mit einem anderen im Core enthaltenen jQuery-Script vorgebeugt? Schützt eine Version sicherer vor Konflikten als die andere, und wäre es da nicht angebracht immer die sicherste zu benutzen? Sorry, sind nur Gedanken dazu. Wollte diese Gedanken vor einer weiteren Antwort von dir mitteilen.

**Comment by fritzmg** [comment]
In MooTools gibt es die Funktion `$` und `$$`. Mit `$` Selektiert man nur ein einzelnes Element anhand deren ID. Mit `$$` selektiert man mehrere Elemente. Siehe dazu http://mootools.net/blog/2010/03/19/a-better-way-to-use-elements

`$` ist eine short-hand-function für `document.id`. Da sich die short-hand-function Bezeichnung `$` mit der von jQuery überschneidet, muss bzw. sollte man entsprechenden MooTools code, wo `$` in Verwendung ist, mit 
```
(function($) {
  …
})(document.id);
```
wrappen, damit jQuery Code und dieser MooTools Code koexistieren kann.

In den Templates __accordion, chosen, slider, tablesort__ wird die Funktion `$` bzw. `document.id` nicht benötigt (sieh dir den Code an, dort kommt bspw. nur `$$` vor), daher muss sie auch nicht an die wrapper function übergeben werden.

Generell könnte man sich in solchen Fällen den wrapper auch sparen, allerdings ist es auch unabhängig von der jQuery vs. MooTools Code Problematik eine wrapper function zu verwenden. Das wird zB hier gut erklärt: http://stackoverflow.com/a/2421949/374996

**Comment by Aybee** [comment]
Die Bedeutung von `$` und `$$` in MooTools und jQuery war mir zwar klar, aber super erklärt und aufgedröselt, danke.

D.h. also, dass ich, wenn ich ein Template anpasse und dort dann doch `$` benutze, ich den "Wrapper" auch korrigieren sollte um Problemen vorzubeugen. Deswegen war auch meine Überlegung, ob es nicht besser wäre, direkt den sichereren in allen Templates zu benutzen. Oder wäre das irgendein Overhead?

**Comment by fritzmg** [comment]
> D.h. also, dass ich, wenn ich ein Template anpasse und dort dann doch $ benutze, ich den "Wrapper" auch korrigieren sollte um Problemen vorzubeugen.

Ja musst, bzw. solltest du machen, also auch `document.id` für `$` an den wrapper übergeben.

> Deswegen war auch meine Überlegung, ob es nicht besser wäre, direkt den sichereren in allen Templates zu benutzen. Oder wäre das irgendein Overhead?

Naja, ein theoretischer Overhead ist es auf jeden Fall, gehen halt ein paar Nanosekunden drauf dafür... ;). Jemand der derartiges an den scripts ändert sollte aber über diesen Umstand ohnehin Bescheid wissen, daher erachte ich es nicht für notwendig - aber vielleicht sehen das die devs anders.

**Comment by Aybee** [comment]
Danke. Kann dann von mir aus auch geschlossen werden. Ergibt wahrscheinlich nur eine vernachlässigbare Anzahl an Fehleranfragen im Forum bei angepassten Templates. Und der Code scheint so halt sauberer (minimalistischer) zu sein.

**Comment by may17** [comment]
`Mit $ Selektiert man nur ein einzelnes Element anhand deren ID`

Kleine Ergänzung document.id / $ ist nicht nur für die Ansprache von ids gedacht sondern auch dafür  Elementen explizit die Element Methoden von Mootools zu übergeben. Gerade bei älteren IE Versionen musste document.body einmal mittels mootools initialisiert werden. Sprich $(document.id).

Siehe Doku:

`The document.id function has a dual purpose: Getting the element by its id, and making an element in Internet Explorer "grab" all the Element methods.`

http://mootools.net/core/docs/1.5.1/Element/Element
