### ISSUE TITLE
Module Listing "Custom module template" is not implemented

### ISSUE THREAD

**Issue by Aybee** [contao/core#8297]
In mudule Listing there is the field **Custom module template** but there is no default template and if you choose any it also does not get rendered.

I think we should remove the field **customTpl** from the palette as it's confusing if it has no effect.
https://github.com/contao/core/blob/master/system/modules/listing/dca/tl_module.php#L15

**Comment by leofeyer** [comment]
Removed in 59007938052d6f5899426fb81cb4c40b7ffd2a6c.
