### ISSUE TITLE
Optgroups are badly rendered for multiple select in Backend

### ISSUE THREAD

**Issue by sebj54** [contao/core#8299]
Hi everyone,

I am actually facing a problem while developing a BE module for Contao.
I have a select field with custom options and optgroups. This field was not multiple until now and options are now badly rendered because of optgroups. See screenshots below:

![Select not multiple](https://cloud.medialta.com/index.php/s/0JTQxvT9J6l0wiI/download)
![Select multiple]
(https://cloud.medialta.com/index.php/s/jrZWAvWfEjV82gj/download)
In DCA, options are still the same, I only set multiple to true.

Thanks in advance for your help!

**Comment by fritzmg** [comment]
Post your DCA and a `var_dump` of the array.

**Comment by sebj54** [comment]
Here is an extract of the DCA (tell me if you need full DCA):

```php
'workshops' => array
(
	'label'                   => &$GLOBALS['TL_LANG']['tl_forum_registration']['workshops'],
	'exclude'                 => true,
	'filter'                  => true,
	'sorting'                 => true,
	'inputType'               => 'select',
	'options'                 => \ForumRegistrationModel::getWorkshops(),
	'eval'                    => array('multiple' => true, 'includeBlankOption'=>false, 'chosen'=>true),
	'sql'                     => "blob NULL"
),
```

Here are my options:

```
Array
(
    [Theme 1 - Technology breakthroughs for materials efficiency] => Array
        (
            [1_1] => Theme 1, 1st workshop session: 3D printing for zero material waste
            [1_2] => Theme 1, 2nd workshop session: Conected Devices for zero wiring
            [1_3] => Theme 1, 3rd workshop session: Materials Solutions for Lightweighting
        )

    [Theme 2 - Continuous innovation for materials efficiency] => Array
        (
            [2_1] => Theme 2, 1st workshop session: Catch up on plastics packaging waste
            [2_2] => Theme 2, 2nd workshop session: New materials combinations for building and housing
            [2_3] => Theme 2, 3rd workshop session: New mobility models to increase car usage rates
        )
)
```

Thnaks for your help.

**Comment by fritzmg** [comment]
I can't confirm the problem. To test I inserted the following into the `dcaconfig.php`:
```php
$GLOBALS['TL_DCA']['tl_news']['fields']['test'] = array
(
    'label'                   => array('Test','Lorem ipsum'),
    'filter'                  => true,
    'sorting'                 => true,
    'inputType'               => 'select',
    'options'                 => array
    (
        'Theme 1 - Technology breakthroughs for materials efficiency' => array
        (
            '1_1' => 'Theme 1, 1st workshop session: 3D printing for zero material waste',
            '1_2' => 'Theme 1, 2nd workshop session: Conected Devices for zero wiring',
            '1_3' => 'Theme 1, 3rd workshop session: Materials Solutions for Lightweighting'
        ),
        'Theme 2 - Continuous innovation for materials efficiency' => array
        (
            '2_1' => 'Theme 2, 1st workshop session: Catch up on plastics packaging waste',
            '2_2' => 'Theme 2, 2nd workshop session: New materials combinations for building and housing',
            '2_3' => 'Theme 2, 3rd workshop session: New mobility models to increase car usage rates'
        )
    ),
    'eval'                    => array('multiple' => true, 'includeBlankOption'=>false, 'chosen'=>true),
    'sql'                     => "blob NULL"
);

if( stripos( $GLOBALS['TL_DCA']['tl_news']['palettes']['default'], ',test' ) === false )
    $GLOBALS['TL_DCA']['tl_news']['palettes']['default'] .= ',test';
```
This results in the following options menu:
![dcatest](https://cloud.githubusercontent.com/assets/4970961/14275247/6ae5e972-fb16-11e5-8c08-345b383d8a6a.png)

**Comment by sebj54** [comment]
That's really weird. I disabled all modules except core ones and I still have this strange behavior. 
I am going to explore other solutions, starting with updating Contao from 3.5.6 to 3.5.9.

I will keep you in touch.

**Comment by do-while** [comment]
if you want to get the options from a program, you should use 'option_callback' instead of 'options'
https://docs.contao.org/books/api/dca/callbacks.html#field-callbacks

**Comment by fritzmg** [comment]
> if you want to get the options from a program, you should use 'option_callback' instead of 'options'
> https://docs.contao.org/books/api/dca/callbacks.html#field-callbacks

It's not a requirement. The core uses it in this way as well: https://github.com/contao/core/blob/3.5.9/system/modules/core/dca/tl_content.php#L249
