### ISSUE TITLE
New feature: Responsive picture for the video element

### ISSUE THREAD

**Issue by jenda77** [contao/core#8303]
It would be very nice to have the same possibility for choosing the picture size in the video element like in the picture element. 

Example for using: it could be very useful when you want to choose just one special part of your picture (what it is only possible when you select the part in the file manager and then use the related picture size).

**Comment by fritzmg** [comment]
This is not supported by the HTML5 standard, since the poster is an attribute of the `<video>` element. And any element within `<video>` will only be shown in older browsers (since it serves as a fallback).
