### ISSUE TITLE
[3.5] Hook setNewPassword - Problem Encrypted Password instead of not encrypted

### ISSUE THREAD

**Issue by blackbee** [contao/core#8305]
Hi everyone,

I propably found a Problem / Defekt in the Hook setNewPassword.

In the docs is said about the Hook setNewPassword:
(https://docs.contao.org/books/api/extensions/hooks/setNewPassword.html)

**Parameters**

string $strPassword
The new password (_not encrypted!_).

**The Problem**

In the Modules **ModulePassword** and **ModuleChangePassword** is the hook integrated - thats fine. But the transfered variable **$strPassword** is allready encrypted, so that the Hook-Function gets the encrypted Password.

I used this hook and both modules for setting the new Password in another system for a user.

Maybe the Module ModulePersonalData is also defect. Also I didn't tried what happens, when changing the Password over the Contao Backend for a user.

**Here an example**

I set the Password to **testtest** but the transfered Password I get in the Hook Function is:
$2y$10$LUSFooXYJJ.DlSx9BlxQRu5VafbiHlTyPTv..R5aC62T6O/2Du6R.

**Comment by aschempp** [comment]
Well the manual is correct:

> It passes the user object and the encrypted password as arguments

If you need the raw password, you might get it from the post data…

**Comment by blackbee** [comment]
I am sorry Andreas,

please take a look at the manual:

[setNewPassword _ Contao API Reference.pdf](https://github.com/contao/core/files/217294/setNewPassword._.Contao.API.Reference.pdf)
![docs-contao-hooks](https://cloud.githubusercontent.com/assets/1532987/14496711/62d2cde8-0194-11e6-9962-2d5251ab622d.PNG)

The Description Text is correct, but the Parameter description is incorrect. That's why i opened the ticket.

Is there a better way getting the unencrpyted Password by using **$_POST['password']** ?

Because **/Input::post('password')** is also encrypted :-(

**Comment by fritzmg** [comment]
> Also I didn't tried what happens, when changing the Password over the Contao Backend for a user.

I tested it there and it also passes the encrypted password. The manual seems to be indeed wrong about this. The first paragraph states

> It passes the user object and the __encrypted password__ as arguments and does not expect a return value.

while the description of the parameters states

> The new password (__not encrypted__!).

as you pointed out.

**Comment by aschempp** [comment]
So we should update the manual. Want to provide a pull request?

**Comment by blackbee** [comment]
Hi Andreas,
hi everybody,

I found some more problems / errors in the Contao docs.

What's the best way for discussing the found problems?

Background:
I have to use a lot of hooks for a customer - at the moment about 20.

BTW: Shall we continue in English or German?

Thanks.

**Comment by aschempp** [comment]
Thanks for reaching out about the documentation. The docs are hosted on a separate GIT repository at https://github.com/contao/docs. There's a small contributions guideline (https://github.com/contao/docs/blob/master/CONTRIBUTING.md). Feel free to open issues over there for each case, or provide a pull request directly. Or just open an issue to ask questions. German is fine for me :-)
