### ISSUE TITLE
[3.5] Problem mit Umlauten bei E-Mail Adressen

### ISSUE THREAD

**Issue by comolo** [contao/core#8306]
Hallo zusammen,

ich bin auf folgenden Bug gestoßen:

**Hintergrund:**
Über ein eigenes Skript werden Daten automatisch in die Mitgliedertabelle tl_member importiert. Manche E-Mail-Adressen enthalten Umlaute und diese werden vom Skript in Punnycode konvertiert und dann in die Datenbank geschrieben.

**Problem:**
Wenn man die Mitgliederverwaltung im Backend aufruft, wird in der Übersicht die E-Mail-Adresse im Punnycode-Format angezeigt, so wie diese auch in der Datenbank steht. Zwar nicht schön, aber ok.
Wird nun das Mitglied aufgerufen, steht im Feld E-Mail der Inhalt wieder im Unicode-Format drin.
Das Problem: Man kann nun allerdings den Mitglieder-Datensatz nicht mehr abspeichern, da sich Contao beschwert, dass die E-Mail-Adresse Umlaute enthält.

**Lösung:**
Die Lösung wäre, dass Contao die E-Mail-Adressen vor dem Speichern in das Punnycode-Format konvertiert und diese bei der Ansicht wieder in Unicode ausgibt.

**Beispiel:**
In der Liste Darstellung im Punnycode Format
![auswahl_003](https://cloud.githubusercontent.com/assets/1228676/14558907/86806e54-0305-11e6-9546-a4df2a8d327b.png)

Beim Bearbeiten: im Unicode Format
![auswahl_002](https://cloud.githubusercontent.com/assets/1228676/14558905/8679138e-0305-11e6-8915-16067e885373.png)

Beim Speichern -> Fehler
![auswahl_004](https://cloud.githubusercontent.com/assets/1228676/14558906/867c06b6-0305-11e6-9462-305c16003c29.png)

**Comment by asaage** [comment]
klingt ja wild...
Ich kann mich erinnern, das vor einiger Zeit die akzeptierten Zeichen in E-mails erweitert wurden.
https://github.com/contao/core/issues/7984
Hat allerdings nicht so viel mit deinem Problem zu tun...
Punnycode in der Datenbank halte ich für eine schlechte Idee - also fast so schlecht wie Umlaute in einer Mailadresse.

**Comment by comolo** [comment]
Bei der betroffenen Website läuft Contao 3.5.4. Wir prüfen mal, ob das Problem mit der Version 3.5.9 noch besteht.

Ich gebe dir Recht, es ist eleganter die E-Mail-Adressen nicht im Punnycode-Format abzuspeichern.
Aber erstmal wäre wichtig, dass das Problem gelöst wird.

**Comment by leofeyer** [comment]
> Punnycode in der Datenbank halte ich für eine schlechte Idee

Ich nicht. Ich halte ein standardisiertes Format für eine sehr gute Idee, weil es viele Probleme gelöst hat, die wir vorher hatten (unter dem Suchbegriff "Punycode" sollte es Issues geben).

> Wird nun das Mitglied aufgerufen, steht im Feld E-Mail der Inhalt wieder im Unicode-Format drin.

Ich kann das initiale Problem nicht reproduzieren. Wenn ich in der Onlinedemo die E-Mail-Adresse von Donna Evans auf d.eväns@example.com ändere, wird sie nach dem Speicher nicht im Punycode-Format ausgegeben.

**Comment by asaage** [comment]
okay - dasss punnycode implementiert ist wusste ich nicht. Aber ich habe im BE überhaupt keine Möglichkeit Umlaute in Mails zu verwenden - weder bei user noch bei member.
![image](https://cloud.githubusercontent.com/assets/4138336/14566904/c42c2eba-0331-11e6-8e28-a15cd7502860.png)

**Comment by leofeyer** [comment]
Behoben in 9f1e0399e51c9e8031e7ae9096ccd357616595d1.
