### ISSUE TITLE
{{email_close}} insert tag missing?

### ISSUE THREAD

**Issue by fritzmg** [contao/core#8309]
There is an `{{email_open::*}}` insert tag with which you can create obfuscated email links with a custom link text, e.g.
```html
{{email_open::email@example.org}}<img src="http://placehold.it/350x150" alt=""></a>
```
Doing it this way will not work in the TinyMCE editor however. TinyMCE will remove the `</a>` since it's a stray tag at this point. In the frontend this will in turn create invalid HTML, because now the `</a>` is missing of course.

To prevent this, you can use `{{link_close}}` instead:
```html
{{email_open::email@example.org}}<img src="http://placehold.it/350x150" alt="">{{link_close}}
```

For non-developer editors this might be a bit confusing though, since they might not know why they must use the `{{link_close}}` tag in conjunction with `{{email_open::*}}` and wonder why there isn't simply an `{{email_close}}` tag.

**Comment by asaage** [comment]
a link is a link...
but aren't emails obfuscated anyway?

**Comment by fritzmg** [comment]
> a link is a link...

For an editor it might be confusing, that he has to use `{{email_open::*}}` and then `{{link_close}}`

> but aren't emails obfuscated anyway?

Not by default, as far as I know. That's what the insert tags `{{email::*}}` and `{{email_open::*}}` are for.

**Comment by asaage** [comment]
TinyMCE
```html
<p>blaa@foo.org</p>
<p>{{email_open::blaa@foo.org}}other Text{{link_close}}</p>
<p><a href="mailto:blaa@foo.org">blaa@foo.org</a></p>
<p><a href="mailto:blaa@foo.org"><img src="files/btn_search.gif"></a></p>
```

FE-Output
```html
<p>&#x62;&#108;&#97;&#x61;&#64;&#x66;&#111;&#111;&#46;&#x6F;&#114;&#x67;</p>
<p><a href="&#109;&#97;&#105;&#108;&#116;&#111;&#58;&#x62;&#108;&#97;&#x61;&#64;&#x66;&#111;&#111;&#46;&#x6F;&#114;&#x67;" title="&#x62;&#108;&#97;&#x61;&#64;&#x66;&#111;&#111;&#46;&#x6F;&#114;&#x67;" class="email">other Text</a></p>
<p><a href="&#109;&#97;&#105;&#108;&#116;&#111;&#58;&#x62;&#108;&#97;&#x61;&#64;&#x66;&#111;&#111;&#46;&#x6F;&#114;&#x67;">&#x62;&#108;&#97;&#x61;&#64;&#x66;&#111;&#111;&#46;&#x6F;&#114;&#x67;</a></p>
<p><a href="&#109;&#97;&#105;&#108;&#116;&#111;&#58;&#x62;&#108;&#97;&#x61;&#64;&#x66;&#111;&#111;&#46;&#x6F;&#114;&#x67;"><img src="files/btn_search.gif" alt=""></a></p>  
```
--------
custom HTML (which allows stray tags)
```html
<p>blaa@foo.org</p>
<p>{{email_open::blaa@foo.org}}other Text{{link_close}}</p>
<p><a href="mailto:blaa@foo.org">blaa@foo.org</a></p>
<p><a href="mailto:blaa@foo.org"><img src="files/btn_search.gif"></a></p>
```
FE-Output
```html
<p>blaa@foo.org</p>
<p><a href="&#109;&#97;&#105;&#108;&#116;&#111;&#58;&#98;&#x6C;&#x61;&#97;&#x40;&#x66;&#x6F;&#111;&#x2E;&#111;&#114;&#103;" title="&#98;&#x6C;&#x61;&#97;&#x40;&#x66;&#x6F;&#111;&#x2E;&#111;&#114;&#103;" class="email">other Text</a></p>
<p><a href="mailto:blaa@foo.org">blaa@foo.org</a></p>
<p><a href="mailto:blaa@foo.org"><img src="files/btn_search.gif" alt=""></a></p>
```

**Comment by Aybee** [comment]
> so in tinymce ther is no real use for {{email}}

Good to know. I always used `{{email::my@mail.org}}` within TinyMCE.

**Comment by fritzmg** [comment]
Ah, didn't know that either.

**Comment by leofeyer** [comment]
Added in contao/core-bundle@7e46aac945339cbf73d3256caf8ed7f66e85ec05.
