### ISSUE TITLE
Invalid HTML with debug mode

### ISSUE THREAD

**Issue by Aybee** [contao/core#8310]
Debug mode results in HTML like this
```html
<!-- TEMPLATE START: system/modules/core/templates/frontend/fe_page.html5 -->
<!DOCTYPE html>
<html lang="en">
<head>
...
```
As a result you have many validating errors. First line should start with
```html
<!DOCTYPE html>
```

**Comment by leofeyer** [comment]
The focus of the debug mode is obviously on debugging the application and not on generating perfectly valid HTML code.

**Comment by fritzmg** [comment]
This could instead be a feature request to make the template debug output optional.

**Comment by leofeyer** [comment]
Contao 3.5 is feature complete and Contao 4 is using the Symfony debug bar, so no.

**Comment by fritzmg** [comment]
> Contao 3.5 is feature complete and Contao 4 is using the Symfony debug bar, so no.

I meant for Contao 4. I haven't checked, but is there actually a way to make the used templates visible in Contao 4 that way (since the debug mode is gone)?

**Comment by bytehead** [comment]
You will see the used templates in the html source code in Contao 4 in dev mode.

**Comment by leofeyer** [comment]
> The focus of the debug mode is obviously on debugging the application and not on generating perfectly valid HTML code.

**Comment by fritzmg** [comment]
> You will see the used templates in the html source code in Contao 4 in dev mode.

I see, thx.

**Comment by Aybee** [comment]
Ok, aber man hatte mir mal bei der FR-Anfrage, ob man die externen CSS-Dateien nicht vom Combiner ausschließen könnte, sobald ich im BE eingeloggt bin, mal gesagt, ich sollte den Debug-Modus einschalten, dann wären sie nicht combined. Da ich aber permanent mit CSS-Dateien arbeite, müsste ich also permanent den Debug-Modus eingeschaltet haben und dann hätte ich da natürlich auch gerne validen Quellcode, da ich den auch permanent überwache. Mit diesem Fehler spinnen die Validate-Tools aber total rum, weil dieser eine Fehler eine ganze Reihe anderer nach sich zieht.

Könnte man für das fe_xxx-Template nicht ne Ausnahme machen und den Kommentar unterhalb des Doctype ausgeben?

**Comment by aschempp** [comment]
Sobald du den Debug-Modus aktivierst, is die Seite **per definition** nicht in einem *idealen* Zustand. Da macht es keinen Sinn den Quellcode zu prüfen, genau so wenig wie du eine Google Prüfung machen würdest, weil dir Google dann sagt dass deine Scripte nicht combined sind…

**Comment by Aybee** [comment]
Ok, ist mir jetzt auch egal, ich habe mir sowieso was eigenes programmiert, wo meine externen Dateien im FE kombiniert werden und sobald  ich im BE eingeloggt bin, sind sie es halt nicht.

Ich verstehe nur nicht, warum man sich so dagegen stellt coremäßig diese Möglichkeit zu schaffen, die Dateien nicht zu combinen, wenn man eingeloggt ist. Im Forum wird des Öfteren danach gefragt, weil man halt mit den diversen Dev-Tools im Browser seine Datei sehen möchte welche man gerade bearbeitet und nicht die kombinierte.

**Comment by fritzmg** [comment]
Ich finde auch, dass es nicht schaden würde, wenn man das combining separat konfigurieren könnte.

**Comment by Toflar** [comment]
Das Combining wird sowieso weg müssen, wegen HTTP2. Das hat aber nichts mit dem ursprünglichen Ticket zu tun :) Anderes Thema -> anderes Ticket. Das Combining deaktivieren müssen wir definitiv können.

**Comment by Aybee** [comment]
< @Toflar Das Combining deaktivieren müssen wir definitiv können.

Da gab es bereits Anfragen zu

 https://github.com/contao/core/issues/3140
> @Aybee Und, ganz wichtig, eine Checkbox um den Combiner ein und auszuschalten.

https://github.com/contao/core/issues/6242
https://github.com/contao/core/issues/6242#issuecomment-30748104
> @Aybee Und dann bitte nicht vergessen, während man im BE als Admin eingeloggt ist, nicht in den Combiner. Bitte während der Entwicklung die original Datei einbinden. Für CSS hatte ich diesbezüglich schon ein Ticket erstellt.
