### ISSUE TITLE
The hook isVisibleElement is not called when shown hidden elements is activated in fe preview

### ISSUE THREAD

**Issue by Toflar** [contao/core#8312]
The early return statement causes the hook not to be called when "show hidden elements" is activated. For Contao elements, this might be fine because you want them to be shown when that option is true. However, that hook is for developers and - by definition - should allow developers to say "hey, my element is still not visible, no matter what you said in the FE preview". I think this can be considered a bug even though people are maybe relying on the fact that the hook is not called when the option is activated. Moreover, I cannot come up with any use case for that matter anyway.

**Comment by leofeyer** [comment]
Fixed in ec9cd0cfdd9ac7fb58f1b5bbb7ce6bb081d2c340.
