### ISSUE TITLE
Insert-Tag iflng/ifnlng: Angabe mehrerer Sprachen / Fallback auf Nicht-Dialekt

### ISSUE THREAD

**Issue by michelbalzer** [contao/core#8313]
In https://github.com/contao/core/issues/2719#issuecomment-2945213 wurde Variante 2 mit kommaseparierten Sprachkürzeln im iflng/ifnlng-Insert Tag erwähnt.

`{{iflng::de,de-CH}}Text in Deutsch und Schweizerdeutsch{{iflng}}`

Diese scheint damals wohl nicht den Eingang gefunden zu haben. Könnte man das implementieren?

Dabei ist mir noch aufgefallen, dass bei einer Website mit de-CH-Sprache ein Fallback auf ein `iflng::de` erfolgen könnte, wenn nichts für de-CH angegeben wurde.

Contao 3.5.9

**Comment by madmaharaja** [comment]
Genau hiernach habe ich gesucht! Die Lösung mit der Kommaseparierung finde ich sehr gut und auch Leos Idee mit dem Sprachanausschluss (s. https://github.com/contao/core/issues/2719#issuecomment-2945213) gefällt mir.
Noch ein Vorschlag: Wie wäre es mit einer Art "Wildcard" für Untersprachvarianten?
Z.B.:
{{iflng::de*}}Text in Deutsch und allen deutschen Sprachvarianten, z.B. de-CH, de-AT etc.{{iflng}}

**Comment by leofeyer** [comment]
Implementiert in contao/core-bundle@0bcc37f72b5653cd5fc060e0ba52fcac78229dc5.

**If language**

* `{{iflng::en}}`: Seitensprache ist Englisch
* `{{iflng::en,fr}}`: Seitensprache ist Englisch oder Französisch
* `{{iflng::en*}}`: Seitensprache ist irgendeine Variante von Englisch (z.B. `en` oder `en-US`)
* `{{iflng::en*,fr}}`: Seitensprache ist irgendeine Variante von Englisch oder Französisch

**If not language**

* `{{ifnlng::en}}`: Seitensprache ist nicht Englisch
* `{{ifnlng::en,fr}}`: Seitensprache ist nicht Englisch und nicht Französisch
* `{{ifnlng::en*}}`: Seitensprache ist keine Variante von Englisch
* `{{ifnlng::en*,fr}}`: Seitensprache ist keine Variante von Englisch und nicht Französisch
