### ISSUE TITLE
Hint for keyboard shortcuts pointing to Nirvana

### ISSUE THREAD

**Issue by Toflar** [contao/core#8318]
The hint still points to https://contao.org/de/manual/administration-area.html#backend-tastaturkuerzel which does not exist anymore.

**Comment by fritzmg** [comment]
Shouldn't it have been fixed with #7935 ?

**Comment by Toflar** [comment]
The german translation does not seem to be fixed on Transifex :)

**Comment by leofeyer** [comment]
Strange enough, the translation **is** actually fixed on Transifex:

<img width="622" alt="" src="https://cloud.githubusercontent.com/assets/1192057/14722413/bd617afc-080b-11e6-8f86-8cbf86cd7fab.png">

And I just checked contao.org (3.5.11) and the link is correct there. Where did you stumble upon this?

**Comment by fritzmg** [comment]
The Contao `>=3.5.3` installations at my disposal also all have the correct link.

**Comment by Toflar** [comment]
Must have missed the language files then. Sorry for that.
