### ISSUE TITLE
database update for Contao >=3.5.10 can lead to duplicate entry error for index in tl_search

### ISSUE THREAD

**Issue by fritzmg** [contao/core#8320]
If you have entries in your `tl_search` table before updating to Contao `>=3.5.10` you might get a `duplicate entry` error when updating the database. You need to purge/truncate the `tl_search` table before executing the database update. Maybe Contao `3.5.12` should introduce a `Updater::run3510Update` method, which truncates the `tl_search` table and then updates the database.

**Comment by leofeyer** [comment]
We have discussed this already and since it is not necessary to open the install tool to upgrade from Contao 3.5.9, most people would never run the `run3510Update` method. We have therefore agreed on adding a notice to the release announcement.

**Comment by fritzmg** [comment]
The release announcement doesn't say anything about this. It only says, that you have to rebuild the search index after the update. It does __not__ say that you need to purge the search index before the update!

**Comment by leofeyer** [comment]
I have updated the release announcement.

**Comment by fritzmg** [comment]
I still think this should be handled by the install tool. I don't get why it was decided that "no one uses the install tool for this update". This seems like you were thinking of yourself, rather than the rest of the community. As a Contao developer you automatically know whether it is necessary to open the install tool or not.

But anybody else would adhere to the manual update procedure __as described in the official user manual for Contao__:

> __Updating the database__

> After you have updated the Contao files, you need to update the database, too. Fortunately, the Contao install tool will do most of the work for you. Just open it and enter your password, then scroll down to the database section and confirm the changes.

https://docs.contao.org/books/manual/3.5/en/01-installation/manual-update.html#updating-the-database

If someone deviates from this and runs into the problem described in this issue, then it's their fault.

**Comment by fiedsch** [comment]
Apart from supporting fritzmg's idea, the text in the release announcment might be easier to read if it is in the "right order", i.e.

> After the update, you have to rebuild the search index. This applies to both the manual update and the Live Update. If you update manually, you should also purge the search index before you apply the database changes.


should be

> If you update manually, you should also purge the search index before you apply the database changes. After the update, you have to rebuild the search index. This applies to both the manual update and the Live Update. 


and maybe change "should" to "have to".

**Comment by leofeyer** [comment]
> and maybe change "should" to "have to".

No, because you don't have to. It **might** be necessary depending on what's in the search tables.

**Comment by fiedsch** [comment]
OK, I see. Thanks.
