### ISSUE TITLE
Weiterleitung von 403 auf geschützte Seite (nach Login) klappt nicht mehr

### ISSUE THREAD

**Issue by NinaG** [contao/core#8324]
## KORREKTUR: Hatte ursprünglich geschrieben, dass die Einstellung "Zur zuletzt besuchten Seite" angehakt ist, das war ein Fehler. Habe den Text jetzt richtig gestellt, damit das Problem klarer ist:

Früher war das so:
1. Es gab eine geschützte Seite (und eine dafür geeignete Mitgliedergruppe)
2. Auf der 403-Fehlerseite gab es ein Login-Modul in dem nichts weiter angehakt war (also weder Weiterleitungsseite noch "Zur zuletzt ..."!)
3. Wenn ein nicht angemeldeter Frontend-Besucher den Direktlink einer beliebigen geschützten Seite aufgerufen hat (z.B. weil dieser in einem Newsletter verlinkt war), wurde er zur 403 geleitet, meldete sich dort an und wurde dann automatisch zur zuvor aufgerufenen geschützten Seite geleitet.

Leider klappt das seit einigen Versionen nicht mehr. Weshalb das so ist, weiß ich nicht. Es ist aber ärgerlich, weil dadurch ein sehr wichtiger Usability-Vorteil geschützter Seiten verloren gegangen ist.

NACHTRAG: Es scheint, dass Contao fälschlicherweise auf die Weiterleitungsseite der Mitgliedergruppe zugreift, obwohl im Login-Modul keine Einstellung wegen Weiterleitungsseite definiert ist. Das ist anders als früher. Früher wurde klar unterschieden: 
a) Weiterleitungsseite im Login-Modul - Weiterleitung erfolgt (und wird ggf von WS aus Mitgliedergruppe überschrieben)
b) keine Weiterleitungsseite im Login-Modul - Seite wird geladen, auf der der Nutzer sich gerade befindet

-> Fall B ist sehr wichtig für Direkt-Marketing-Maßnahmen (siehe meine Fallerklärung weiter unten)!

Diese Funktionalität funktionierte schon mal, aber irgendwann muss das (fälschlicherweise) aus dem Code rausgeflogen sein. Ich wurde von Kunden darauf hingewiesen, dass das mittlerweile nicht mehr geht, vermute aber, dass das schon länger (vielleicht seit 3.2 oder länger?) so ist.

**Comment by fritzmg** [comment]
Das hast du falsch konfiguriert. Bei dem Login Modul, dass du _direkt_ auf der 403 Seite eingebunden hast, darfst du __nicht__ "Zur zuletzt besuchten Seite" aktivieren. Spiele dir das mal durch:

1. User befindet sich auf Seite http://www.example.org/foo.html
2. User requested die Seite http://www.example.org/protected.html
3. Auf dieser URL, also unter dieser Seite, wird die 403 Seite generiert. Dort befindet sich das Login Formular und der User logged sich ein.
4. Nach dem Login soll der User auf der Seite http://www.example.org/protected.html __bleiben__ und nicht auf die zuletzt besuchte Seite weitergeleitet werden - die zuletzt besuchte Seite wäre in diesem Fall ja `foo.html`

Warum das in deiner Konfiguration früher mal funktioniert hat, kann ich dir nicht sagen.

**Comment by NinaG** [comment]
Ich habe es auch ohne "Zur zuletzt besuchten Seite" versucht, aber dann wird der Nutzer prinzipiell zur Startseite geleitet.

**Comment by fritzmg** [comment]
> Ich habe es auch ohne "Zur zuletzt besuchten Seite" versucht, aber dann wird der Nutzer prinzipiell zur Startseite geleitet.

Passiert das auch im `coreOnlyMode`? Hast du deine Contao Installation mit dem Contao Check validiert?

**Comment by NinaG** [comment]
Ich zieh mir eine lokale Kopie und teste das asap.

**Comment by NinaG** [comment]
Contao Check: natürlich validiert
Abgesicherter Modus: wie gehabt, anstatt dass der Nutzer auf der bestehenden geschützten Seite bleibt (nach dem Login), leitet Contao ihn zur Startseite weiter.

Wobei ich hier konkretisieren muss: Ich meine damit nicht, die allgemeine Homepage, sondern die Startseite des internen Bereichs. Es sieht so aus, als würde Contao da also die "Weiterleitungsseite" die in der Mitgliedergruppe definiert ist, über die Anweisung aus dem konkreten Loginmodul stellen.

Ausgangslage
-> im Loginmodul ist weder eine Weiterleitungsseite noch die Angabe "zur zuletzt besuchten Seite" aktiviert.
-> der Nutzer gehört einer Mitgliedergruppe an, die bei einem normalen Login zur Startseite des internen Bereichs geleitet wird.

Was gewünscht ist:
-> Wenn der Nutzer einem Direktlink auf eine geschützte Seite folgt, wegen nicht eingeloggtem Status auf 403 landet und sich dann von dort einloggt, soll er auf der nun angezeigten geschützten Seite landen.

Was passiert:
-> Contao schickt ihn stattdessen zu der Weiterleitungsseite die in der Mitgliedergruppe definiert ist.

Früher war das Verhalten so:
-> War im Loginmodul eine Weiterleitungsseite angeklickt, wurde der Nutzer dort hin gesandt. War zusätzlich in seiner Mitgliedergruppe eine Weiterleitungsseite definiert, hat Contao diese als Ziel gewählt.
-> War im Loginmodul hingegen KEINE Weiterleitungsseite angeklickt (und sonst auch nichts), blieb der Nutzer nach dem Login auf der Seite auf der er sich gerade befand.

Letzteres passiert jetzt nicht mehr. Die Weiterleitungsseite der Mitgliedergruppe übertrumpft immer alles, auch wenn das gar nicht gewünscht ist.

**Comment by fritzmg** [comment]
> Es sieht so aus, als würde Contao da also die "Weiterleitungsseite" die in der Mitgliedergruppe definiert ist, über die Anweisung aus dem konkreten Loginmodul stellen.

Du darfst im Login Modul keine Weiterleitungen aktivieren, wenn du keine Weiterleitung machen möchtest.

**Comment by NinaG** [comment]
Wie ich schrieb, habe ich im Login-Modul keine Weiterleitung aktiviert. 
Es gibt eine Weiterleitung in der Mitgliedergruppe.

Das von den Kunden gewünschte Verhalten sieht im Prinzip so aus (und das wollen eigentlich alle meine Kunden mit geschützten Bereichen so):

Fall A) Normales Login:
Besucher ist auf der Website unterwegs und will dann in den geschützten Bereich. Er klickt auf den entsprechenden Bereich und das normale dort hinterlegte Login-Modul. Das Login-Modul hat eine Weiterleitungsseite definiert, die auf die normale Startseite des geschützten Bereichs verweist. Wenn der Besucher einer besonderen Mitgliedergruppe angehört (z.B. Partner oder VIP-Kunden), ist für seine Mitgliedergruppe eine andere Weiterleitungsseite eingestellt worden. Er kann dennoch wie alle Besucher das selbe Login in den geschützten Bereich nutzen, weil die Weiterleitungsseite-Definition aus der Mitgliedergruppe wie gewünscht, die WS-Definition aus dem Login-Modul überstimmt.

Bis hier her läuft also alles perfekt.

Fall B) Direktlink-Login aus Marketing-Maßnahmen:
Besucher erhalten über unterschiedliche Marketing-Maßnahmen Direktlinks auf bestimmte Seiten im geschützten Bereich (z. B. aus einem Newsletter, aus Social-Media, QR-Codes in Fachmagazinen, Aussendungen an Kunden/Partner, etc). Diese Direktlinks verweisen eben direkt auf die geschützten Seiten - daher ist hier das Verhalten gewünscht, dass die Kunden das Login sehen (auf der 403) und dann nach dem Login direkt auf dem Direktlink landen. 

Die Weiterleitungsseite aus der Mitgliedergruppe darf hier keine Rolle spielen. Früher war es eben so, dass wir dafür ein 2. Login-Modul auf der 403 hatten, dem keinerlei Weiterleitung etc. eingestellt war.

Sprich: Hier knallt es und funktioniert nicht mehr.

**Comment by fritzmg** [comment]
Das Problem ist: wie unterscheidest du einen "normalen" Login von einem "direkt-Link" Login? Dazu gibt es im Login Modul aktuell keine Möglichkeit. Wenn im Login Modul also keine Weiterleitung eingestellt ist, dann _muss_ im Zweifelsfall die Weiterleitung der Mitglieder Gruppe greifen.

Das wäre also ein Feature Request für Contao 4. Also zB eine Checkbox wie __Weiterleitung der Mitglieder Gruppe ignorieren__.

In Contao 3(.5) kannst du aber dein Verhalten trotzdem noch nachbauen:

* Du machst deine 403 Seite zu einer Weiterleitung auf eine andere Seite, wo sich ein Login Modul befindet.
* In diesem Login Modul aktivierst du die Weiterleitung __Zur zuletzt besuchten Seite__

Das sollte folgenden Ablauf erzeugen

* Benutzer logged sich regulär auf http://www.example.org/login.html ein
* Benutzer wird nach dem Login auf die Seite weiter geleitet, die in seiner Mitgliedergruppe definiert ist.

* Benutzer geht direkt auf http://www.example.org/protected.html
* Benutzer wird auf http://www.example.org/login-direct.html weitergeleitet
* Benutzer logged sich ein und wird danach auf http://www.example.org/protected.html weitergeleitet

Unschön ist bei dieser Lösung, dass man zwei Login Seiten hat. Einmal `login.html` und einmal `login-direct.html`.

**Comment by asaage** [comment]
Ich stand kürzlich vor einem ähnlichen Problem (LoginModul auf der 403-Seite), wusste aber nicht, dass es scheinbar mal anders funktionierte.  Als Lösung habe ich dann die Erweiterung [login_link] verwendet - mit der kann kannst du Direktlinks auf geschützete Seiten in deinen Newslettern verwenden - die den Benutzer dann auch ohne LoginModul und ohne Weiterleitung anmelden.

**Comment by NinaG** [comment]
@fritzmg <<Das Problem ist: wie unterscheidest du einen "normalen" Login von einem "direkt-Link" Login? Dazu gibt es im Login Modul aktuell keine Möglichkeit. >>

Die Unterscheidung gab es eben früher mal, indem das Loginmodul "verstand", dass es auf der aktuellen Seite bleiben soll, sofern im Loginmodul gar nichts eingestellt ist. Diese Einstellung ist mittlerweile offensichtlich eben kaputt und wurde dadurch ersetzt, dass die Weiterleitungsseite der Mitgliedergruppe prinzipiell immer wirkt.

Aus meiner Sicht ist es also ein Bug (weil es schon mal ging) und müsste gefixed werden. Aber ich stimme dir zu, dass es sinnvoll wäre, für Contao 4 einen offensichtlicheren Weg zu schaffen, also im Login-Modul direkt eine Checkbox "Weiterleitung der Mitgliedergruppe ignorieren".

@fritzmg  @asaage Danke für eure Tipps, wie ich das ggf aktuell über Alternativwege richtig hinbauen kann. So habe ich zumindest erstmal eine Art Lösung :)

**Comment by fritzmg** [comment]
> Die Unterscheidung gab es eben früher mal, indem das Loginmodul "verstand", dass es auf der aktuellen Seite bleiben soll, sofern im Loginmodul gar nichts eingestellt ist. Diese Einstellung ist mittlerweile offensichtlich eben kaputt und wurde dadurch ersetzt, dass die Weiterleitungsseite der Mitgliedergruppe prinzipiell immer wirkt.

Wann soll die Weiterleitungsseite der Mitgliedergruppe nicht wirken? Wie würde man das aktuell festlegen?

**Comment by NinaG** [comment]
Sie soll dann nicht wirken, wenn im Loginmodul einfach gar nichts ausgewählt ist. 
Also KEINE Weiterleitungsseite im Loginmodul gewählt ist und NICHT "Zur zuletzt besuchten Seite" angehakt ist.

**Comment by fritzmg** [comment]
Ich finde nicht dass das logisch ist. Wenn man im Login Module eine Weiterleitungsseite eingestellt hat, dann will man ja, dass man genau _dorthin_ weitergelteit wird.

**Comment by NinaG** [comment]
Wird man ja auch. Außer man überschreibt es über die Mitgliedergruppe. So ist es und das funktioniert ja auch.

**Comment by fritzmg** [comment]
> Wird man ja auch.

In älteren Contao Versionen eben nicht, deinen Aussagen zufolge. Da könnte es sein, dass man statt dessen auf die Weiterleitungsseite der Mitgliedergruppe weitergeleitet wird, obwohl man das vielleicht nicht so möchte - eben weil man explizit im Modul die Weiterleitungsseite festgelegt hat.

**Comment by NinaG** [comment]
Es war imho immer schon so, dass man auf die WS der Mitgliedergruppe geleitet wurde, sofern diese gesetzt war und im Modul eine WS eingestellt war. Die WS der Mitgliedergruppe ist ja genau für den Zweck da, dass sie eine etwaige im Modul definierte allgemeine WS überschreibt.

Nur eben wenn KEINE WS im Modul definiert ist, müsste auch nichts überschrieben werden, weil offensichtlich gar keine Weiterleitung (egal welcher Art) gewünscht ist. Und genau da liegt eben aktuell der Fehler, dass die WS der Mitgliedergruppe immer aktiv ist, selbst wenn das Modul gar nicht für eine Weiterleitung definiert wurde.

**Comment by fritzmg** [comment]
Wenn ich mir den Code direkt ansehe, das ist das aktuelle Verhalten mindestens schon seit Contao 3.0.0 so: https://github.com/contao/core/blob/3.0.0/system/modules/core/modules/ModuleLogin.php#L76

```php
// Redirect to the last page visited
if ($this->redirectBack && $_SESSION['LAST_PAGE_VISITED'] != '')
{
	$strRedirect = $_SESSION['LAST_PAGE_VISITED'];
}
else
{
	// Redirect to the jumpTo page
	if ($this->jumpTo && ($objTarget = $this->objModel->getRelated('jumpTo')) !== null)
	{
		$strRedirect = $this->generateFrontendUrl($objTarget->row());
	}

	// Overwrite the jumpTo page with an individual group setting
	$objMember = \MemberModel::findByUsername(\Input::post('username'));

	if ($objMember !== null)
	{
		$arrGroups = deserialize($objMember->groups);

		if (is_array($arrGroups) && !empty($arrGroups))
		{
			$objGroupPage = \MemberGroupModel::findFirstActiveWithJumpToByIds($arrGroups);

			if ($objGroupPage !== null)
			{
				$strRedirect = $this->generateFrontendUrl($objGroupPage->row());
			}
		}
	}
}
```
Übersetzt: wenn die Option __Zur zuletzt besuchten Seite__ _nicht_ aktiv ist, dann wird entweder auf die im Modul festgelegte Weiterleitungsseite weitergeleitet, sofern vorhanden, oder auf die in der Mitglieder Gruppe festgelegte Weiterleitungsseite, sofern vorhanden. Nur wenn gar nichts davon der Fall ist, bleibt man auf der selben Seite.

**Comment by NinaG** [comment]
Hm, dann vielleicht doch noch in Contao 2? Ich weiß, dass es bei den Kunden mal funktioniert hat. Da es ewig dauert, bis man sowas herausfindet (deren Kunden melden das nicht, sondern ärgern sich nur), kann es tatsächlich schon so lange zurück liegen.

**Comment by NinaG** [comment]
Und danke fürs Prüfen :)

**Comment by fritzmg** [comment]
Hm... zumindest in Contao `2.10.3` war es auch schon so: https://raw.githubusercontent.com/contao/core/2.10.3/system/modules/frontend/ModuleLogin.php
```php
// Redirect to the last page visited
if ($this->redirectBack && strlen($_SESSION['LAST_PAGE_VISITED']))
{
	$strRedirect = $_SESSION['LAST_PAGE_VISITED'];
}
else
{
	// Redirect to the jumpTo page
	if (strlen($this->jumpTo))
	{
		$objNextPage = $this->Database->prepare("SELECT id, alias FROM tl_page WHERE id=?")
									  ->limit(1)
									  ->execute($this->jumpTo);

		if ($objNextPage->numRows)
		{
			$strRedirect = $this->generateFrontendUrl($objNextPage->fetchAssoc());
		}
	}

	// Overwrite the jumpTo page with an individual group setting
	$objGroup = $this->Database->prepare("SELECT groups FROM tl_member WHERE username=?")
							   ->limit(1)
							   ->execute($this->Input->post('username'));

	if ($objGroup->numRows)
	{
		$arrGroups = deserialize($objGroup->groups);

		if (is_array($arrGroups) && count($arrGroups) > 0)
		{
			$time = time();

			// Get the first active jumpTo page
			$objGroupPage = $this->Database->prepare("SELECT p.id, p.alias FROM tl_member_group g LEFT JOIN tl_page p ON g.jumpTo=p.id WHERE g.id IN(" . implode(',', array_map('intval', $arrGroups)) . ") AND g.jumpTo>0 AND g.redirect=1 AND g.disable!=1 AND (g.start='' OR g.start<$time) AND (g.stop='' OR g.stop>$time) AND p.published=1 AND (p.start='' OR p.start<$time) AND (p.stop='' OR p.stop>$time) ORDER BY " . $this->Database->findInSet('g.id', $arrGroups))
										   ->limit(1)
										   ->execute();

			if ($objGroupPage->numRows)
			{
				$strRedirect = $this->generateFrontendUrl($objGroupPage->row());
			}
		}
	}
}
```

**Comment by asaage** [comment]
zum Thema Logik... und "Weiterleitungsseite der Mitgliedergruppe" das empfand ich bislang auch immer als problematisch wenn ein Mitglied 2 oder 3 Gruppen angehört.

**Comment by fritzmg** [comment]
> zum Thema Logik... und "Weiterleitungsseite der Mitgliedergruppe" das empfand ich bislang auch immer als problematisch wenn ein Mitglied 2 oder 3 Gruppen angehört.

Man kann einen Nutzer ja nicht auf 2 oder mehr Seiten weiterleiten, daher wird einfach die erste genommen ;)

**Comment by fritzmg** [comment]
@NinaG ich würde außerdem die __redirect4ward__ Extension empfehlen. Da brauchst du die Weiterleitung dann nicht mehr in der Gruppe definieren, sondern kannst es über ein eigenes Inhaltselement unabhängig vom Login Modul machen - da hast du mehr Freiheiten und Möglichkeiten dann.

**Comment by leofeyer** [comment]
> Auf der 403-Fehlerseite gab es ein Login-Modul

Ich habe das Login-Modul immer auf einer separaten Seite und die 403er mit einer Weiterleitung auf diese konfiguriert. Dann klappt auch die Weiterleitung zur zuletzt besuchten Seite, oder?

**Comment by fritzmg** [comment]
> Ich habe das Login-Modul immer auf einer separaten Seite und die 403er mit einer Weiterleitung auf diese konfiguriert. Dann klappt auch die Weiterleitung zur zuletzt besuchten Seite, oder?

Ja, aber @NinaG s ursprüngliches Problem war ja, dass die Weiterleitungsseite der Mitgliedergruppe dies wieder aufhebt - und man eben zu dieser Seite kommt.

**Comment by ssylvio** [comment]
Ich möchte mich mal in die Diskussion einmischen.
Auf einer Website, die seit Jahren geschützte Seiten verwendet, haben wir das Login genauso konfiguriert, wie Leo das beschreibt. Das funktionierte bis zur Version 3.5.17. Nun habe ich das Update auf 3.5.18 gemacht und das funktioniert nicht mehr. Die 403er-Seite ist nicht mehr aufrufbar. Es kommt stattdessen immer die Startseite. Ich denke, da ist in 3.5.18 etwas schief gelaufen, oder? 
Übrigens: Ein Downgrade zurück auf 3.5.17 und alles funktioniert wieder.

**Comment by fritzmg** [comment]
Ja, es gibt aktuell ein oder evt. mehrere Bugs im Zusammenhang mit dieser Änderung: 32e70a8b290de70f46a8c0c11b585dc66365f5fc (für #8498).

Beschreibe dein Setup genauer, damit man das reproduzieren kann.

**Comment by ssylvio** [comment]
Da gibt es gar nicht viel zu beschreiben: Nimm eine Contao-Installation mit Version 3.5.18. Lege dort eine normale Startseite und eine Seite vom Typ "403 Zugriff verweigert" an. Versuche die 403er Seite im Frontend aufzurufen. Es erscheint die Startseite (erste Seite unter dem Startpunkt). Auch wenn man in der 403er Seite eine Weiterleitung konfiguriert, kommt die Startseite, statt der Seite, auf die die Weiterleitung zeigt.
Wenn man hingegen die Version 3.5.17 oder eine frühere Version nimmt und das gleiche macht, kommt beim Aufrufen der 403er Seite auch dieselbe, so wie man sich das vorstellt.

**Comment by fadencross** [comment]
+1

**Comment by asaage** [comment]
Also ich möchte ja behaupten, dass 403 und 404 Seiten noch nie aufrufbar waren. In 3.5.8 ist das zumindest so und warum sollte man die auch aufrufen wollen?

**Comment by fritzmg** [comment]
> Da gibt es gar nicht viel zu beschreiben: Nimm eine Contao-Installation mit Version 3.5.18. Lege dort eine normale Startseite und eine Seite vom Typ "403 Zugriff verweigert" an. Versuche die 403er Seite im Frontend aufzurufen. Es erscheint die Startseite (erste Seite unter dem Startpunkt). Auch wenn man in der 403er Seite eine Weiterleitung konfiguriert, kommt die Startseite, statt der Seite, auf die die Weiterleitung zeigt. Wenn man hingegen die Version 3.5.17 oder eine frühere Version nimmt und das gleiche macht, kommt beim Aufrufen der 403er Seite auch dieselbe, so wie man sich das vorstellt.

In der Contao Online Demo lässt sich dieses Verhalten nicht reproduzieren. Dort kann man allerdings auch nicht die Option __Add the language to the URL__ deaktivieren.

**Comment by fritzmg** [comment]
> Also ich möchte ja behaupten, dass 403 und 404 Seiten noch nie aufrufbar waren. In 3.5.8 ist das zumindest so und warum sollte man die auch aufrufen wollen?

Wenn du auf eine Seite zugreifst, auf die du nicht zugreifen kannst, dann wird dir normalerweise der Inhalt der 403 oder 404 Seite gezeigt.

**Comment by asaage** [comment]
> Wenn du auf eine Seite zugreifst, auf die du nicht zugreifen kannst

Na das ist klar - aber die url bleibt ja die, die man eingegeben hat.

**Comment by fritzmg** [comment]
> Da gibt es gar nicht viel zu beschreiben: Nimm eine Contao-Installation mit Version 3.5.18. Lege dort eine normale Startseite und eine Seite vom Typ "403 Zugriff verweigert" an. Versuche die 403er Seite im Frontend aufzurufen. Es erscheint die Startseite (erste Seite unter dem Startpunkt). Auch wenn man in der 403er Seite eine Weiterleitung konfiguriert, kommt die Startseite, statt der Seite, auf die die Weiterleitung zeigt. Wenn man hingegen die Version 3.5.17 oder eine frühere Version nimmt und das gleiche macht, kommt beim Aufrufen der 403er Seite auch dieselbe, so wie man sich das vorstellt.

Auch in einer lokalen `3.5.18` Installation kann ich das Verhalten so nicht nachstellen. Irgendwas muss bei deinem Setup anders sein.

Oder versuchst du tatsächlich die 404 oder 403 Seite direkt aufzurufen, so wie @asaage meint? Bspw. über deren Alias (über die ID geht das schon länger nicht mehr).

**Comment by fritzmg** [comment]
Auch wenn ich versuche die 403 oder 404 Seite _direkt_ über deren Alias aufzurufen, gelange ich nicht zur Startseite. Es wird mir statt dessen die 403 respektive die 404 Seite des Contao Core's gezeigt.

**Comment by ssylvio** [comment]
> In der Contao Online Demo lässt sich dieses Verhalten nicht reproduzieren. Dort kann man allerdings auch nicht die Option Add the language to the URL deaktivieren.

Ich habe das gerade getestet. Wenn "Add the language to the URL" aktiviert ist, tritt das Problem nicht auf. Es liegt also m.E. daran.
Wenn man die 403er Seite direkt aufruft, kommt normalerweise Contao's 403er Seite. Wennd er Bug aber aktiv ist (also 3.5.18 ohne "Add the language to the URL"), kommt die Startseite.

**Comment by fadencross** [comment]
> Ich habe das gerade getestet. Wenn "Add the language to the URL" aktiviert ist, tritt das Problem nicht auf. Es liegt also m.E. daran.
bei mir das selbe ergebnis.

**Comment by fritzmg** [comment]
Wie schon erwähnt kann ich auch ohne __Add the language to the URL__ das Problem nicht reproduzieren. Bei Aufruf von bspw. `http://example.org/access-denied.html` kommt die 403 Seite von Contao. Bei Aufruf von `http://example.org/page-not-found.html` kommt die 404 Seite von Contao.

**Comment by ssylvio** [comment]
> Außerdem hat dein Problem ja eigentlich nichts mit dem Thema hier in diesem Ticket zu tun, oder?

Das sehe ich anders. Ich denke, dass beide Probleme zusammenhängen, aber das müssen die verantwortlichen Entwickler entscheiden.

> Wie schon erwähnt kann ich auch ohne Add the language to the URL das Problem nicht reproduzieren. 

Ich habe eine Beispielinstallation unter [http://ex1.qualli.de ](http://ex1.qualli.de) bereitstellen lassen. Der Login lautet test und das Kennwort 123456789. Hier sieht man, wenn man die 403 oder die geschützte Seite aufruft, kommt die Startseite. Die Seite wurde mit 3.5.17 installiert und dann geupdated. 
Wenn man hier jetzt die Sprache in der URL aktiviert, funktioniert alles bestens.

**Comment by asaage** [comment]
in der Tat seltsam...
Ich hab den alias der Startseite mal auf "index" gesetzt (das sollte man eigentlich machen denke ich) dann läuft alles wie man es sich vorstellt (mit oder ohne Sprachkürzel).
Also ich denke schon es ist ein Bug mach ein neues Ticket dazu "403 geht nicht wenns keine Seite mit index-alias gibt" 
Mit diesem issue hat es nichts zu tun.

**Comment by Aybee** [comment]
Und das `index.php` sollte man auch sofort nach der Installation als erstes aus der URL entfernen.

**Comment by asaage** [comment]
> Und das index.php sollte man auch sofort nach der Installation als erstes aus der URL entfernen.

stimmt - aber das geht ja leider nicht immer - zumindest nicht allein mit Bordmitteln

**Comment by ssylvio** [comment]
> Ich hab den alias der Startseite mal auf "index" gesetzt (das sollte man eigentlich machen denke ich) dann läuft alles wie man es sich vorstellt (mit oder ohne Sprachkürzel).

Vielen Dank. Das hat das Problem tatsächlich behoben.

**Comment by fritzmg** [comment]
> Das sehe ich anders. Ich denke, dass beide Probleme zusammenhängen, aber das müssen die verantwortlichen Entwickler entscheiden.

Nein, das hier ursprünglich beschriebene Problem behandelt den Fall, wenn man auf eine geschütze Seite zugreifen möchte, aber keinen Zugriff darauf hat - und hier gab' es keinen tatsächlichen Fehler.

Der Fehler den du beschreibst ist etwas ganz anderes. Der tritt auf, wenn du auf _die 403 Seite selbst_ (warum auch immer) zugreifen möchtest.

> Vielen Dank. Das hat das Problem tatsächlich behoben.

Ok, das heißt in deiner ursprünglichen Reproduktionsbeschreibung hat einfach nur gefehlt, dass du deiner Startseite nicht den Alias "index" gegeben hast. Auf diese Weise kann ich das Problem nun auch nachvollziehen.

**Comment by fritzmg** [comment]
Das Problem ist nun in #8552 festgehalten.

**Comment by leofeyer** [comment]
Leider beinhaltet das Ticket nun zwei Diskussionen, von denen eine gar nicht zum Thema gehört. 😢

**Comment by leofeyer** [comment]
Ich habe mir erlaubt, die themenfremde Diskussion aus dem Thread zu entfernen, weil es ja dazu ein separates Ticket gibt und das Problem in Contao 3.5.19 behoben wurde.

Besteht das ursprünglich in diesem Ticket beschriebene Problem noch in Contao 3.5.19 und wenn ja, wie genau kann ich es nachstellen?
