### ISSUE TITLE
Generierte URLs in RSS-Feed falsch bei zwei Startpunkten/Multidomain

### ISSUE THREAD

**Issue by Shoekrates** [contao/core#8327]
Installierte Contao-Version: 3.5.12, war aber auch in einer 3.5.9 zu beobachten.

Wenn in einer Contao-Installation zwei Startpunkte mit zwei separaten Domains angelegt werden und jeder Startpunkt bekommt sein eigenes Nachrichtenarchiv, das auf einer eigenen Listen- und Leserseite ausgegeben wird, dann funktioniert zwar die URL-Generierung im RSS-Feed des Nachrichtenarchivs von Startpunkt 1, aber im 2. Startpunkt wird die Domain im Feed gedoppelt. Für jede Seite ist ein eigenes Theme mit den entsprechenden Modulen angelegt. Beide angelegte RSS-Feeds haben korrekt gesetzte Domains in den Einstellungen.

Beispiel, um es etwas klarer zu machen:

Seite 1
Domain: http://www.domain1.de
RSS-Feed: http://www.domain1.de/share/news-domain1.xml
Generierte Links in RSS-Feed: http://www.domain1.de/newsleser/news1.html

Seite 2
Domain: http://www.domain2.de
RSS-Feed: http://www.domain2.de/share/news-domain2.xml
Generierte Links in RSS-Feed: http://domain2.de/http://www.domain2.de/newsleser/news2.html

Das Problem tauchte bei einem Kundenprojekt auf, wir konnten es in einer frischen Neuinstallation ohne jegliche Erweiterungen nachstellen.
Da das Multidomain-Setup in der Demo nicht nachzustellen ist, hier die Links zu unserer Demo:

Seite 1
Domain: http://testen.ecco-server.de
RSS-Feed: http://testen.ecco-server.de/share/testen-ecco-server-de.xml
Generierte Links in RSS-Feed: http://testen.ecco-server.de/newsleser/testen-ecco-server-de.html

Seite 2
Domain: http://testen2.ecco-server.de
RSS-Feed: http://testen2.ecco-server.de/share/testen2-ecco-server-de.xml
Generierte Links in RSS-Feed: http://testen2.ecco-server.de/http://testen2.ecco-server.de/newsleser/testen2-ecco-server-de.html

Wer sich das im Backend anschauen möchte, kann gerne den Login von uns erhalten.

Es gab schon mal ein ähnliches Ticket: https://github.com/contao/core/issues/5891

**Comment by fritzmg** [comment]
Hm, ich kann das Problem in einer frischen Contao `3.5.12` installation nicht nachvollziehen. In meinem Testfall hat die Installation zwei Domains, mit zwei Newsarchiven die jeweils eine Weiterleitungsseite in der jeweiligen Domain haben.
```xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.sitemaps.org/schemas/sitemap/0.9 http://www.sitemaps.org/schemas/sitemap/0.9/sitemap.xsd">
  <url><loc>http://example1.dev/</loc></url>
  <url><loc>http://example1.dev/news.html</loc></url>
  <url><loc>http://example1.dev/news/entry.html</loc></url>
  <url><loc>http://example1.dev/news/entry/test-1.html</loc></url>
</urlset>
```
```xml
<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.sitemaps.org/schemas/sitemap/0.9 http://www.sitemaps.org/schemas/sitemap/0.9/sitemap.xsd">
  <url><loc>http://example2.dev/</loc></url>
  <url><loc>http://example2.dev/news.html</loc></url>
  <url><loc>http://example2.dev/news/entry.html</loc></url>
  <url><loc>http://example2.dev/news/entry/test-2.html</loc></url>
</urlset>
```

**Comment by Shoekrates** [comment]
Das sind die generierten Sitemaps, es geht aber um die RSS-Feeds der Nachrichtenarchive.

**Comment by fritzmg** [comment]
Ah stimmt, sorry, hatte ich überlesen.

**Comment by fritzmg** [comment]
Well, I can confirm _some_ problem with the RSS feed generation. In my case, the domain was not duplicated, however, the resulting feed was still wrong:
```xml
	<item>
		<title>Test 1</title>
		<description>
			<![CDATA[]]>
		</description>
		<link>http://example1.dev/news/entry/test-1-69.html</link>
		<pubDate>Fri, 29 Apr 2016 12:05:00 +0200</pubDate>
		<guid>http://example1.dev/news/entry/test-1-69.html</guid>
	</item>
	<item>
		<title>Test 2</title>
		<description>
			<![CDATA[]]>
		</description>
		<link>http://example1.dev/news/entry/test-2.html</link>
		<pubDate>Fri, 29 Apr 2016 12:05:00 +0200</pubDate>
		<guid>http://example1.dev/news/entry/test-2.html</guid>
	</item>
```
The second item should be http://__example2.dev__/news/entry/test-2.html, not _example1.dev_. I'll investigate this further.

**Comment by Shoekrates** [comment]
OK, sounds good – thanks. 
You generated a combined RSS-Feed, haven't you?
Please also test two separate feeds. I think this will lead to the same problem we have.

**Comment by fritzmg** [comment]
I guess so, but in any case, the generated RSS feed is wrong :)

**Comment by fritzmg** [comment]
@Shoekrates ich konnte das exakte Problem von dir leider nicht nachstellen. Bei mir haben die URLs der generierten Feeds (egal ob sie Zusammgengefasst oder einzeln sind) immer nur den Host, mit dem man im Backend ist (und nicht den Host bzw. die Domain, die in der Seitenstruktur eingestellt ist).

**Comment by Shoekrates** [comment]
@fritzmg ich habe dir eine Mail mit Zugang zu unserem Testsystem geschickt.

**Comment by fritzmg** [comment]
Konnte das Problem doch nachstellen - die Installation war nicht ganz so "frisch" - es war auch noch `news_categories` installiert, die sich da zusätzlich einhängt.

**Comment by fritzmg** [comment]
@Shoekrates teste mal die Änderung von #8329

**Comment by Shoekrates** [comment]
Das funktioniert, sowohl auf der Testseite als auch im Kundenprojekt mit einigen installierten Erweiterungen. Perfekt, vielen Dank!

**Comment by fritzmg** [comment]
If someone uses the `news_categories` extension and experiences this issue as well, you can track the following ticket: codefog/contao-news_categories#86

**Comment by fritzmg** [comment]
@Shoekrates I have updated the pull request, you should update your `News.php` with the updated one too, if you have news with redirect targets to pages or articles.

**Comment by Shoekrates** [comment]
Da ich kein regelmäßiger Github-Nutzer und Entwickler bin: kann mir jemand bitte kurz erklären, warum Leo das "invalid" Label hinzugefügt hat? 
Was bedeutet das für den Commit? Landet der jetzt nicht im nächsten Contao-Release (dann wahrscheinlich 3.5.13)? Und wenn nicht, warum nicht?
Ist eine reine Verständnissache.

**Comment by fritzmg** [comment]
Der PR ist momentan für den nächsten bugfix release getagged, sollte also in der nächsten Version drin sein.

**Comment by Shoekrates** [comment]
Aber warum das Label "invalid"? Klingt für mich danach, dass irgendwas an dem PR nicht valide ist und deshalb erstmal abgelehnt wurde.
Ich möchte einfach mal die Abläufe bei Bugfixes in Contao kennenlernen. Wenn es an anderer Stelle irgendwo beschrieben ist, wäre ich für einen Link dankbar.

**Comment by fritzmg** [comment]
Der PR wurde nicht als invalid getagged.

**Comment by Shoekrates** [comment]
Ah, dann gilt das invalid Label (s.o.) nur für diesen Issue 8327 hier? So langsam komme ich glaube ich dahinter. Der PR selbst ist ja in Issue 8329.

**Comment by leofeyer** [comment]
"Invalid" hatte ich hinzugefügt, weil Du das Ticket mit dem Hinweis auf die "news_categories"-Extension geschlossen hattest. Ich bin daher davon ausgegangen, dass es sich nicht um ein Core-Problem handelt.
