### ISSUE TITLE
Scrollbalken verdeckt die letzte Zeile von HTML/Markdown Elementen

### ISSUE THREAD

**Issue by J-J-A** [contao/core#8328]
Man kann die letzte Zeile nur noch umständlich anklicken. 

Scrollt man im Chrome auf der Höhe des Scrollbalken, blendet dieser sich aus irgendwelchen Gründen auch nicht mehr automatisch aus. In Safari ist das ähnlich mühsam, im Firefox geht es besser. Unter Mac OS mit Contao 3.5.0 getestet. 

<img width="907" alt="bildschirmfoto 2016-04-29 um 11 32 21" src="https://cloud.githubusercontent.com/assets/17248733/14912861/5a1bd5ce-0dff-11e6-84ed-e912203474a2.png">

Ich habe diesen Feldern im BE einfach ein padding nach unten gegeben. Vielleicht könnte man das schon im Core integrieren, falls es auch anderen so geht.

**Comment by leofeyer** [comment]
Wie lässt sich das in der Onlinedemo reproduzieren?

**Comment by asaage** [comment]
Das scheint Browserspezifisch zu sein.
win-chrome vergrößert das Feld wenn es Focus bekommt aber verdeckt zunächst auch die letzte Zeile.

**Comment by Aybee** [comment]
Zum Testen in einem CE Typ HTML dieses hier eingeben:
```html
<p>
  Ich bin eine lange Textzeile. Ich bin eine lange Textzeile. Ich bin eine lange Textzeile. Ich bin eine lange Textzeile. Ich bin eine lange Textzeile.
</p>
```
Es erscheint eine vertikale Scrollbar und der Quelltext (die 3 Zeilen) sind nicht auf einen Blick zu sehen. Da müsste hauptsächlich unten etwas Luft geschaffen werden. FF, Chrome, Edge, IE11 Opera.
Hier direkt bei ACE sieht das besser aus https://ace.c9.io/#nav=about. Gleichen Code in den Editor einfügen.

**Comment by J-J-A** [comment]
Im Prinzip bei allen Typen HTML/Code/Markdown.

**Comment by leofeyer** [comment]
Vielleicht wäre es das beste, wenn wir angesichts der Cross-Browser-Problematik mit Soft-Wraps arbeiten würden, so dass gar nicht erst ein vertikaler Scrollbalken entsteht.

```js
  var editor = ace.edit('<?= $this->selector ?>_div');
  editor.$blockScrolling = Infinity;
  editor.setTheme("ace/theme/clouds");
  editor.renderer.setScrollMargin(3, 3, 0, 0);
  editor.renderer.scrollBy(0, -6);
  editor.getSession().setValue(ta.value);
  editor.getSession().setMode("ace/mode/<?= Backend::getAceType($this->type) ?>");
  editor.getSession().setUseSoftTabs(false);
  editor.getSession().setUseWrapMode(true);  // <----------- diese Zeile einfügen
  editor.setAutoScrollEditorIntoView(true);
```

Könnt ihr bitte mal testen, ob das das Problem behebt?

**Comment by Aybee** [comment]
Für mich wäre das so ok - Windows 10, FF, Chrome, Edge, IE11. Vielleicht ein wenig viel Luft unten, aber nicht unangenehm mit diesem Platz.

**Comment by Aybee** [comment]
![artikel_ _test_ _inhaltselement_id_537_bearbeiten_-_contao_open_source_cms_3 5_-_2016-05-17_17 34 05](https://cloud.githubusercontent.com/assets/1143013/15328575/a9bd2de4-1c55-11e6-91b6-1a926c895a40.png)
Abgesicherter Modus, keine dcaconfig oder initconfig, Theme default, C 3.5.12, FF 46.01

**Comment by leofeyer** [comment]
Was passiert, wenn Du [Zeile 62](https://github.com/contao/core/blob/master/system/config/ace.php#L62) löschst?

**Comment by Aybee** [comment]
![artikel_ _inhaltselement_id_537_bearbeiten_-_contao_open_source_cms_3 5_-_2016-05-17_17 43 53](https://cloud.githubusercontent.com/assets/1143013/15328948/35c751a6-1c57-11e6-8c94-1bba4c2e36be.png)

**Comment by Aybee** [comment]
Ups, sorry, das war nicht mit 62 gelöscht, sondern wieder der Ursprungszustand ohne die neue Zeile von oben.

**Comment by Aybee** [comment]
Ok, **setUseWrapMode** wieder entfernt und `+ editor.renderer.scrollBar.getWidth()` entfernt, dann sieht es so aus, wie bei dir.

**Comment by Aybee** [comment]
Sorry, jetzt dreh ich hier langsam am Rad: Neue Zeile `setUseWrapMode` **und** `+ editor.renderer.scrollBar.getWidth()` entfernt - damit war es so wie bei dir.

**Comment by leofeyer** [comment]
Behoben in 8a2afd9ff75143ae83c00e90229363ee4a7a0575.
