### ISSUE TITLE
Simplify date entry

### ISSUE THREAD

**Issue by Teetrinker** [contao/core#8332]
(The date format in my installation is d.m.Y)
To enter a date (e.g. in a new event), I need to write ten digits: DD.MM.YYYY
It would be helpful if D.M.YYYY would also be accepted as a correct date format.

In short:
Entering "1.4.2016" in a date field should not be a problem.

**Comment by aschempp** [comment]
Simply change your date format. Instead of `d.m.Y` you can use `j.n.Y`. See https://php.net/date

**Comment by Teetrinker** [comment]
The date format determines the way dates are displayed in the frontend. The entry of dates in the backend could still be less of a hassle.

But for my case, your tip is all I needed. Thanks @aschempp

**Comment by fritzmg** [comment]
@Teetrinker you can define the date format of the frontend in the settings of each website root individually. Only the date format in the system settings also affects the date format of the backend inputs.

**Comment by Teetrinker** [comment]
@fritzmg thanks!
