### ISSUE TITLE
Missing dependency in unofficial composer Packagist Repo

### ISSUE THREAD

**Issue by mvscheidt** [contao/core#8333]
https://github.com/contao-community-alliance/composerized-contao-core has no Issue Tracker so I couldn't open an issue there.

----

https://packagist.org/packages/contao/core misses the dependency ```"matthiasmullie/minify": "~1.3",```

This causes the following error when I activated ```Minify the markup```

```
[06-May-2016 11:57:08 Europe/Berlin] PHP Fatal error: Uncaught exception 'Error' with message 'Class 'MatthiasMullie\Minify\JS' not found' thrown in /var/www/share/.../htdocs/system/modules/core/library/Contao/Template.php on line 467
#0 /var/www/share/.../htdocs/system/modules/core/library/Contao/Template.php(292): Contao\Template->minifyHtml('<!DOCTYPE html>...')
#1 /var/www/share/.../htdocs/system/modules/core/classes/BackendTemplate.php(120): Contao\Template->output()
#2 /var/www/share/.../htdocs/system/modules/core/controllers/BackendMain.php(275): Contao\BackendTemplate->output()
#3 /var/www/share/.../htdocs/system/modules/core/controllers/BackendMain.php(135): Contao\BackendMain->output()
#4 /var/www/share/.../htdocs/contao/main.php(20): Contao\BackendMain->run()
#5 {main}
```

Compare the composer.json files - the one I downloaded from the contao homepage has the missing dependency.

Contao from the Website (just downloaded)
```
		"php": ">=5.4.0",
		"leafo/scssphp": "~0.1",
		"michelf/php-markdown": "~1.4",
		"matthiasmullie/minify": "~1.3",
		"oyejorge/less.php": "~1.7",
		"phpspec/php-diff": "~1.0",
		"simplepie/simplepie": "~1.3",
		"swiftmailer/swiftmailer": "^5.2.1",
		"tecnickcom/tcpdf": "~6.0",
		"true/punycode": "~1.0",
		"contao-components/compass": "~0.12"
```

Packagist ( https://packagist.org/packages/contao/core ) 
```
		"contao-community-alliance/composer-plugin": "~2.0",
		"php": ">=5.4.0",
		"leafo/scssphp": "~0.1",
		"michelf/php-markdown": "~1.4",
		"oyejorge/less.php": "~1.7",
		"phpspec/php-diff": "~1.0",
		"simplepie/simplepie": "~1.3",
		"swiftmailer/swiftmailer": "~5.2",
		"tecnick.com/tcpdf": "~6.0",
		"true/punycode": "~1.0",
		"contao-components/compass": "~0.12"
```

The Core requires this in the Template.php Class

Use Statement: https://github.com/contao/core/blob/master/system/modules/core/library/Contao/Template.php#L13

Usages: 
* https://github.com/contao/core/blob/master/system/modules/core/library/Contao/Template.php#L467
* https://github.com/contao/core/blob/master/system/modules/core/library/Contao/Template.php#L473

----

Imho adding the dependency should fix it? Not really sure why it's missing (other than an oversight)

**Comment by leofeyer** [comment]
> https://github.com/contao-community-alliance/composerized-contao-core has no Issue Tracker so I couldn't open an issue there.

Which does, however, not mean that you should create a ticket here. We are not maintaining `composerized-contao-core` and therefore cannot solve the problem.

**Comment by DanielSchwiperich** [comment]
The packagist site is linking here for creating issues ;)
https://packagist.org/packages/contao/core

So you should maybe talk to @discordier for example to remove the link and create a seperate issue tracker (which will lead to issues created for contao then there for sure)

**Comment by discordier** [comment]
As already written in the README of the repo:
> This is useful when unit testing Contao extensions etc. and is not intended for new installations or the like.

You should not use it for real installations (as you obviously did). The repo is lacking all translations and solely intended for providing the classes for unit testing.
Therefore we added the classmap autoloading (but do not support the namespace hack).
You SHOULD not install Contao via `composer create-project` from this repository.

However, the composer.json has been adjusted.

We do not have an issue tracker on purpose, as we do not want valid Contao tickets separated from the real repository.
