### ISSUE TITLE
Conao 3.5.6 onundo_callback findet Callback im $GLOBALS-Array nicht

### ISSUE THREAD

**Issue by mwitzmann** [contao/core#8334]
Es scheint, als sei das "$GLOBALS['TL_DCA'][$table]"-Array in DC_TABLE.php in der Methode "undo()" nicht vorhanden. Lediglich "$GLOBALS['TL_DCA']['tl_undo']" gibt es zu diesem Zeitpunkt. Das führt wiederum
 dazu, dass das "onundo_callback" nicht ausgeführt wird.

Kann dies jemand bestätigen?

**Comment by aschempp** [comment]
Dieser Fehler wurde in einer neueren Contao-Version behoben.
