### ISSUE TITLE
Contao 3.5.12, Markup komprimieren, Backend Inline JS-Script, open_basedir() führt zur Fehlermeldung

### ISSUE THREAD

**Issue by mwitzmann** [contao/core#8336]
Das Minify-Plugin von Matthias Mullie führt in der neusten Contao Version dazu, dass bei Komprimierung des Markups, einem gesetzten open_basedir() und Inline JS-Code im Backend (zurzeit nur dort aufgefallen), ein PHP-Warning erzeugt wird.

Ausgelöst wird es durch die Methode Minify::canImportFile(). Diese Methode wird seit Contao 3.5.12 in Minify::load() aufgerufen und ersetzt den Code:

```
// Zeile 88: [...]
if (@file_exists($data) && is_file($data)) {
// [...]
```

Das erzeugte PHP-Warning sieht in etwa so aus:

```
Warning: is_file(): open_basedir restriction in effect. File( window.addEvent("domready", function(){ new Picker.Date( $$("#ctrl_inputCreateFromDate"),{ draggable: false, toggle: $$("#toggle_inputCreateFromDate"), format: "%d.%m.%Y", pickerClass: "datepicker_bootstrap", useFadeInOut: !Browser.ie, startDay: 1, titleFormat: "%d. %B %Y" } ); } ); ) is not within the allowed path(s): (/path/to/root/dir:/tmp:/.composer) in vendor/matthiasmullie/minify/src/Minify.php on line 385
```

**Comment by leofeyer** [comment]
Ist das nicht eher ein Bug im Minify-Plugin?

**Comment by mwitzmann** [comment]
Grundsätzlich ja, aber Contao sollte dann zumindest solange die Version des Plugins nutzen, die funktioniert, bis der Bug im Plugin behoben ist.

**Comment by fritzmg** [comment]
Issue reference: matthiasmullie/minify#111

@mwitzmann gibt es überhaupt eine ältere Version von `matthiasmullie/minify`, wo der Fehler nicht auftritt?

**Comment by mwitzmann** [comment]
@fritzmg Definitiv ist die Version von `matthiasmullie/minify` in Contao 3.5.6 lauffähig und Contao 3.5.11 scheint die alte funktionierende Überprüfung zu beinhalten, sprich
`if (@file_exists($data) && is_file($data)) { // [...]`

**Comment by fritzmg** [comment]
Laut `composer.lock` file wird in Contao `3.5.9` die Version `1.3.28` von `matthiasmullie/minify`. Als workaround könnte man einstweilen selbst in der `/composer.json` den Eintrag
```
"matthiasmullie/minify": "~1.3"
```
zu
```
"matthiasmullie/minify": "1.3.28"
```
ändern und ein `compser update` machen.

**Comment by leofeyer** [comment]
Behoben in 64f454ac7c5b1985e1203c69f52a8060f00da38c.
