### ISSUE TITLE
Neue Domainendungen nicht als Admin-Email-Adresse möglich

### ISSUE THREAD

**Issue by daniellatsch** [contao/core#8337]
Beim Anlegen eines Admins während der Installation und unter Verwendung einer E-Mail Adresse mit neuer Domainendung (in meinem Fall .studio), wird das abgesendete Formular als "nicht vollständig ausgefüllt" wieder zurückgesetzt.
![bug](https://cloud.githubusercontent.com/assets/5945089/15163906/b47f5a58-170b-11e6-9e83-f0e63d487ec1.JPG)

**Comment by leofeyer** [comment]
Bist Du sicher, dass es an der E-Mail-Adresse liegt? Die Regex in `Validator::isEmail()` hat nämlich kein Problem mit der TLD .studio.
