### ISSUE TITLE
Remove the entropy source param in mcrypt_create_iv() call

### ISSUE THREAD

**Issue by Toflar** [contao/core#8338]
I think we should convert 

```php
$iv = mcrypt_create_iv(mcrypt_enc_get_iv_size(static::$resTd), MCRYPT_RAND);
```

in our Encryption class into

```php
$iv = mcrypt_create_iv(mcrypt_enc_get_iv_size(static::$resTd));
```

as `MCRYPT_RAND` was the only one supported on Windows too prior to PHP 5.3 but we can safely delete it now and let it generate from `MCRYPT_DEV_URANDOM`.

**Comment by leofeyer** [comment]
Removed in cb58f10dcb0656bf41550c56054db4cae5f5f141.
