### ISSUE TITLE
Neues Element in Artikel hinzufügen führt zu Fehlermeldung

### ISSUE THREAD

**Issue by HandyDoktor** [contao/core#8339]
Hi, habe Contao neu installiert und bin den Academy Anweisungen gefolgt bis zum Hinzufügen des ersten Inhalts (Elements) in einem Artikel. Dabei wird mir diese Fehlermeldung angezeigt und ich werde ausgeloggt. Wer kann mir helfen?
Thomas
![bildschirmfoto 2016-05-13 um 23 13 45](https://cloud.githubusercontent.com/assets/19353371/15262366/2bce502a-1962-11e6-9fde-a6a483c284f3.jpg)

**Comment by fenepedia** [comment]
Hallo Thomas, ich gehe mal davon aus, dass du mit "Academy" die Contao Academy meinst. Du kannst mir gerne solche Fragen direkt per E-Mail senden.

Sende dazu den Inhalt der Datei /system/logs/error.log.

Ansonsten ist es im 1. Schritt hilfreich deine Fragen im Forum zu stellen.

**Comment by HandyDoktor** [comment]
Hoi Christian
Ja, das meine ich. Und ich finde Deine Videos im Fall super!
Da ich den Zugang zu dieser Datei wohl bei meinem Hoster besorgen muss, werd ich sie dir gerne morgen zustellen und hoffe, dass du mir helfen kannst.
Liebe Grüsse und gute Nacht
Thomas

**Comment by fenepedia** [comment]
Die Dateien kannst du dir selbst per FTP herunterladen. Die findest du im Contao Verzeichnis unter dem genannten Pfad.

**Comment by HandyDoktor** [comment]
hilft das weiter? ich hatte mal eine seite erstellt mit dem namen „ErsterBeitrag“. die habe ich aber wieder gelöscht…

**Comment by Toflar** [comment]
Bitte diskutiert das nicht auf dem offiziellen Contao Tracker. Das hat hier nichts zu suchen :)

**Comment by HandyDoktor** [comment]
ok. wo dann?

**Comment by Toflar** [comment]
Hier geht es um die Software Contao an sich. Für Fragen zur Bedienung von Contao etc. am besten im offiziellen Contao Forum (https://community.contao.org) oder im Falle der Contao Academy bei der Platform des Anbieters.
