### ISSUE TITLE
Focus on subfolder in Templates is broken

### ISSUE THREAD

**Issue by agoat** [contao/core#8341]
Normally a click on the folder name will reduce the filetree to that folder and a breadcrumb ist displayed on top. 
Works fine on the articles-, site structure- and file manager page, but is broken on the templates page. 
Only the &fn=templates/subfolder is added to the url but not recognized and reloaded.

Sorry, at the moment i can not give a hint why it´s not working with the newest (3.5.12) version.

**Comment by leofeyer** [comment]
Fixed in d5fbc89754ca1a4bd6b55d481f87adefcc8e8dac.
