### ISSUE TITLE
tinymce editor icons not showing in backend

### ISSUE THREAD

**Issue by ivl1705** [contao/core#8342]
affected browsers: Google Chrome, Firefox

all checking done with new profile.

with firebug, the issue could be tracked down to following console entry:

```
`downloadable font: OS/2: bad linegap: -32 (font-family: "tinymce" style:normal weight:normal stretch:normal src index:1) source: http://demo.contao.org/assets/tinymce4/skins/contao/fonts/tinymce.woff
http://demo.contao.org/assets/tinymce4/skins/contao/skin.min.css
Line 1`
```
can this be confirmed?

**Comment by asaage** [comment]
I noticed this yesterday and the rason was a missing mime-handler in IIS for *.woff files.
Are you running your installation on IIS?

**Comment by ivl1705** [comment]
Thanks for your Input with mime-handlers. I'm running on apache.
Seems to be an issue with my Internet access. From another Computer with current Firefox the icons render fine.

**Comment by discordier** [comment]
Check for a proxy in your network
