### ISSUE TITLE
Akkordeon | role=tablist etc. is wrong (Bug in Contao 3.5.x and Contao 4.x)

### ISSUE THREAD

**Issue by MacKP** [contao/core#8344]
As mentioned at the conference from Sonja Weckenmann and @mayerhh the role 

> tablist

 and 

> multiselectable="true"

 is wrong here.

Here is an Link to the slide -> [https://pbs.twimg.com/media/Ci4wk7IVAAAgw1a.jpg:large](https://pbs.twimg.com/media/Ci4wk7IVAAAgw1a.jpg:large)

I can try to make an PR for that when we strike an agreement what it should look like.

regards

**Comment by MacKP** [comment]
Here is an old Ticket with aria-expended (just for mention it) -> #7620

**Comment by MacKP** [comment]
Some more Information about this -> [http://w3c.github.io/aria/practices/aria-practices.html#accordion](http://w3c.github.io/aria/practices/aria-practices.html#accordion)

**Comment by leofeyer** [comment]
It is not a problem to remove the tablist role in the MooTools accordion, but jQuery adds it by default (see https://github.com/jquery/jquery-ui/blob/master/ui/widgets/accordion.js#L84), so we will have to create a pull request there.

And I cannot find a `multiselectable` attribute anywhere. Where is this added?

**Comment by leofeyer** [comment]
Fixed in 8fa62fc19366de2e513a532a54735d6c4aade2f5.

Since we are not using an accordion container, the tablist attribute is not added via jQuery. We might still create a pull request there to get it fixed.
