### ISSUE TITLE
isValidOption & "special chars"

### ISSUE THREAD

**Issue by vmulot** [contao/core#8345]
Hi,
i have a pb with the Widget isValidOption for select and checkboxes.
i have a form generated with form generator with some fields, text, select, checkboxes.
Values of select and checkboxes have some "special chars" like ( or ).

i did a custom module, and for some reasons i had to do a load callback for a select field.
the callback get the options (and values) from the previous form.

at this time, it's working.
but
if i need to change the value in my custom module form, i can't save the form
> Invalid input: Activ. menages: employeurs, produc. biens & serv. (usage propre)
i did some quick and dirty debug, and noticed something in the Widget isValidOption method  :

- i dumped $strInput and $v['value'] to compare both.
the first one seems to have ( and ) encode and not the second one, so it does not match.
i tried to add a rgxp alnum and a decodeEntities but it is still not working.

Did i miss something, or is it a real issue ? (i'd like to keep my original values with ( ) or some others chars).
Thanks for help

**Comment by vmulot** [comment]
Hi, did someone manage to reproduce this pb ?

**Comment by leofeyer** [comment]
How exactly do I reproduce this?

**Comment by vmulot** [comment]
What i did :
Contao 3.5.12
Part 1 :
1- Create a new form (form generator) with  a select field
2- Create options for this fields, with  "&"  character in the one value (or more if you want), let's say : black & white
This form is for the frontend User.

Part 2 :
1- create a custom module, something very simple.
2- create a select field in the dca, with a "options_callback"
3- in the callback, grab the options from the select in the form of part 1.
4- add a hook so when frontend User submit the form, it saves the values in our custom module table. 

Goal, is that admin can modify the data given by the frontend user (with the same choices he had) in the form and submit again to generate a final pdf.

Part 3 :
when submiting the frontend form, we should have data in BO in our custom module.
1- edit one item
2- select an option with the "&" (in the value)
3 - try to submit
4- you should have the error invalid input.

i 'm using in my dca the eval 'decodeEntities' => true
and when i try to inject the options i'm using "specialchars" function.

Thanks, i hope it'll be enough to reproduce.

**Comment by leofeyer** [comment]
How is the user submitted data stored in the database?

**Comment by vmulot** [comment]
Hi,
the data is stored with the form options  "store data" where i selected a db table.

**Comment by leofeyer** [comment]
Can you please post exactly what is stored?
