### ISSUE TITLE
Validation of minlength and (maybe) minval on optional fields

### ISSUE THREAD

**Issue by Toflar** [contao/core#8346]
See https://github.com/contao/core/blob/master/system/modules/core/library/Contao/Widget.php#L898

When my form field contains

```php
'eval' => ['mandatory' => false, 'minlength' => 8]
```

it will always throw an error regarding the minimum length. However, I want to say that this field is optional but when you enter a value, it must be at least 8 chars long. We should add a check for `mandatory` here, imho. Or is there any use case where an optional field should be validated for a minimum length?

**Comment by leofeyer** [comment]
I have just tested it by modifying the `tl_user` DCA:

```php
		'start' => array
		(
			'label'                   => &$GLOBALS['TL_LANG']['tl_user']['start'],
			'exclude'                 => true,
			'inputType'               => 'text',
			'eval'                    => array('rgxp'=>'datim', 'datepicker'=>true, 'mandatory'=>false, 'minlength'=>8, 'tl_class'=>'w50 wizard'),
			'sql'                     => "varchar(10) NOT NULL default ''"
		),
```

It works like a charm on my system. Could a third-party extension be the culprit?

**Comment by Toflar** [comment]
Pls check on the password field of tl_member :)

**Comment by leofeyer** [comment]
Password fields are special, because they contain three or five dots. I assume that these are submitted and because three and five are smaller than eight …

**Comment by Toflar** [comment]
Aaah, the password widgets of Contao use `*****`, that's why. So the password widgets should be adjusted to check the `minlength` only if it's not `*****`.

**Comment by leofeyer** [comment]
Even with `tl_member.password` I was not able to reproduce the issue. I have set `'mandatory'=>false` and I could save the back end form without an error message.

How exactly do I reproduce this issue?

**Comment by Toflar** [comment]
Cannot reproduce that anymore either.
