### ISSUE TITLE
ce_player: responsive videos

### ISSUE THREAD

**Issue by pswerbung** [contao/core#8347]
Just had to check this threat to understand, that I need to manually edit template ce_player.html5 for appropriate responsive scaling of videos:
https://community.contao.org/de/showthread.php?39069-Elementtyp-Video-Audio-Responsive-Width-100&highlight=video+responsive

These two settings need to be made and I would suggest it to include within core functionality of contao:

video {
max-width:100%;
}

Template ce_player im Video Tag die PHP-Ausgabe der festen Größe entfernen und folgendes Inline-CSS einfügen:
style="width:100%;height:100%;"

**Comment by leofeyer** [comment]
Not everyone wants to display the video player at 100% width and height, therefore this is not the default behavior. We would need to use `max-width` instead of `width`, however I'm not sure if this works as well.

**Comment by Aybee** [comment]
I think we safely can use max-width 100%  in combination with height auto. But everyone can do this setting in his CSS.
