### ISSUE TITLE
Registered autoitems are declared as unused get 

### ISSUE THREAD

**Issue by MoniqueHahnefeld** [contao/core#8348]
Hi,
I would like to use many autoitems in urls of my extension's modul. I registered my autoitems in the $GLOBALS['TL_AUTO_ITEM'].
This exception does not really make sense than. So maybe can there be added this foreach, which asked if the unused-array values are used as autoitems? =)

THX 

#4277
https://github.com/contao/core/blob/e8b344e4a2aee1bd2c53e166bce7955382232b0b/system/modules/core/classes/FrontendTemplate.php#L115-118

	if ($blnCheckRequest && \Input::hasUnusedGet())
		{
				foreach (\Input::getUnusedGet() as $param) {
					if(!in_array($param, $GLOBALS['TL_AUTO_ITEM'])){
						throw new \UnusedArgumentsException();
					}
				}
		}

**Comment by leofeyer** [comment]
See #8349.
