### ISSUE TITLE
.htaccess and gzip compression

### ISSUE THREAD

**Issue by EDsolution** [contao/core#8351]
Hi.
There might be a bug in default contao .htacess file where gzip or mod_deflate is set.

If you comment the `<IfModule mod_filter.c>` than the gzip compression works, but if you leave as it is by default than the gzip compression isn't working.

**Comment by EDsolution** [comment]
Figure out that if you comment mod_filter.c than on apache 2.4.6 you get 500 error.

Hm...

**Comment by fritzmg** [comment]
You mean you disabled the condition? Then that means your Apache does not have `mod_filter` enabled.

**Comment by EDsolution** [comment]
Thanks for hint!

**Comment by EDsolution** [comment]
Leo - why is this invalid? This is not an issue regarding 500 error but about gzip compression if <IfModule mod_filter.c> is "active".

**Comment by leofeyer** [comment]
According to the ticket, you do not have `mod_filter` installed/enabled in your Apache configuration. If this is the case, then it is not a Contao problem and therefore the issue is invalid.
