### ISSUE TITLE
"Insert Link" should also give the option to link to "subarticles", not just to pages

### ISSUE THREAD

**Issue by eknoes** [contao/core#8353]
When I have some articles with teaser texts on a page, the "Insert Link" function of the WYSIWYG-Editor does not show them. He just gives you the option to link the whole page, but not to the single article which is just touched.

It would be better to also have the option to link on the article. Currently you have to navigate to the Page and copy the read more link.

**Comment by asaage** [comment]
**{{article::*}} This tag will be replaced with a link to an article (replace * with the article ID or alias).**

Unfortunately the Insert Link function of the WYSIWYG-Editor lacks the ability to pick articles but that is also also true for news, events, faq's and newsletters.
I bet there are already related featurerequests for upcomming contao-versions.
