### ISSUE TITLE
Theme-Import funktioniert nicht

### ISSUE THREAD

**Issue by agentmedia** [contao/core#8354]
Der Theme-Import in 3.5.11 und 3.5.12 funktioniert nicht.

Test: 

- Contao (ohne Themes) installieren
- Theme "test" erstellen
- Theme "test" exportieren
- Theme "test" löschen
=> Theme-Liste wieder leer, OK
- Theme "test.cto" wieder importieren
=> Erfolgsmeldung erscheint, Theme-Liste ist aber weiterhin leer.

Der Fehler tritt in 3.4.0 nicht auf.

**Comment by leofeyer** [comment]
@ausi Kannst Du das bestätigen?

**Comment by ausi** [comment]
Ich konnte den Fehler nicht reproduzieren mit einer frischen 3.5.12 Installation.
@agentmedia kannst du die CTO-Datei zur Verfügung stellen?

**Comment by agentmedia** [comment]
Hallo,

hier mit Endung zip (aber nicht erneut gezippt), weil .cto hier nicht erlaubt ist:

[test_theme.cto.zip](https://github.com/contao/core/files/297768/test_theme.cto.zip)

Mein Theme hieß wohl doch "test theme" und nicht nur "test" ...

Getestet in FF 46.0.1
Sage ich weil ich gelegentlich dort anderes Verhalten habe als im Chrome.

Danke für eure Bemühungen ;)

CU
Klaus

**Comment by ausi** [comment]
Auch mit dieser Datei konnte ich den Fehler nicht reproduzieren. Hast du nach der Tabellen- und Templates-Prüfung auf den „Weiter“-Button geklickt?

**Comment by agentmedia** [comment]
Ja. Erstmal ein schönes Wochenende, ich bin erstmal offline.
