### ISSUE TITLE
The search index will not be created when connected over https

### ISSUE THREAD

**Issue by agoat** [contao/core#8359]
After I purged the search index and trying to rebuild it I stumbled over this phenomenon:
The seach index can´t be rebuild in the backend when the backend is loaded over an https connection. On unsecure http connection it works perfect. Also if the frontend pages are loaded over https it works.

Didn´t looked into the source code yet.

**Comment by fritzmg** [comment]
As far as I know, this cannot be solved in Contao. Browsers do not allow unsecure connections, when connected over SSL.

You either have to rebuild the search index via `http://` or you need to active SSL on all your sites.
