### ISSUE TITLE
404 error if visiting an empty reader page

### ISSUE THREAD

**Issue by frontendschlampe** [contao/core#8367]
If you visit an empty reader page for news, events, faq and others there should be an error 404, because normally this page doesn't exist!

**Comment by asaage** [comment]
But you might have other content on that page that you want to present.
I think that is related to #8361
And i think it would be usefull to have the option to redirect the reader to its first item none was selected.

**Comment by leofeyer** [comment]
It is a split topic of #8364 actually.

**Comment by frontendschlampe** [comment]
> I think that is related to #8361

it's not related because it has nothing to do with the information of the sitemap ;-)

> But you might have other content on that page that you want to present.
> And i think it would be usefull to have the option to redirect the reader to its first item if none was selected.

I don't know. In the past 9 years I'm working with Contao I have no request for a redirect and I think it would not correct, but I think there will be 10 different opinions if you will ask 10 different people. In fact: the actual behavior is not correct! Maybe there's a possibility to make a choice in the module: 404 or redirect or nothing

**Comment by fritzmg** [comment]
That's what I proposed in my original feature request: contao/news-bundle#5

**Comment by fritzmg** [comment]
This will be implemented as an optional parameter in the site structure (https://github.com/contao/core/issues/8361#issuecomment-226487484)

**Comment by leofeyer** [comment]
See https://github.com/contao/core/issues/8361#issuecomment-226487484.
