### ISSUE TITLE
[News/Events] multiple edit: enclosures. Not possible

### ISSUE THREAD

**Issue by mathContao** [contao/core#8368]
[Contao 3.5.12]

Example: Edit Events
http://demo.contao.org/contao/main.php?do=calendar&table=tl_calendar_events&id=3&rt=3ae72ff8b8d16130c54df6c236dbc3e8&ref=df5b5e09

multiple edit:
![unbenannt1](https://cloud.githubusercontent.com/assets/1645099/16096864/33b51c3a-334b-11e6-95f1-0e8b945297c2.JPG)

select "Add enclosures" and "enclosures"
![unbenannt2](https://cloud.githubusercontent.com/assets/1645099/16096871/39b821cc-334b-11e6-8f99-4658292459ff.JPG)

Check "Enclosures" and it shows the "page itself" (same checkbox + page buttons)
![unbenannt3](https://cloud.githubusercontent.com/assets/1645099/16096878/42526dd8-334b-11e6-90cb-2003c2b99b88.JPG)

**Comment by fritzmg** [comment]
I cannot confirm that in the Contao Online Demo, it works as expected.

**Comment by mathContao** [comment]
das Problem lässt sich nicht zu 100% nachvollziehen, weil es mal auftritt und mal nicht.

Eine kleine Vermutung habe ich dabei: Wählt man die Checkbox aus, dann erscheint (im Normallfall) kurz ein kleines Fenster, mit dem Hinweis, dass geladen wird. Der oben gezeigte Fehler tritt jedoch dann auf, wenn dieses Fenster nicht kurz aufblinkt. Kann es sein, dass hier eventuell das Laden von JavaScript durcheinander gerät?

**Comment by leofeyer** [comment]
Ich habe die Onlinedemo gestern aktualisiert (Version 3.5.14). Wie lässt sich das Problem dort reproduzieren?

**Comment by mathContao** [comment]
Es ließ sich schwer reproduzieren.
Aktuell kann ich es in der Demo nicht reproduzieren.

Kann geschlossen werden
