### ISSUE TITLE
Umbennung von template Dateien nicht möglich

### ISSUE THREAD

**Issue by FrankoGitHub** [contao/core#8370]
Ich kann in der 3.5.13 unter (Windows/lokal/xampp) die template Dateien in dieser Version nicht mehr umbenennen:
Ändere ich den Namen über "Speichern" erhalte ich nur die Meldung "Ein Fehler ist aufgetreten".
Gehe ich über "Speichern und Schließen" gelange ich wieder auf die Listendarstellung ohne das der neue Name geändert wurde ...

In den Logs erhalte ich z.B.:
File or folder "C:\xampp\test\htdocs/templates/fe_page.html5" is not within the files directory

**Comment by leofeyer** [comment]
Behoben in a0df9599a5d627edcff1ebfbd3973880fd815903. Kannst Du bitte kurz testen, ob es für Dich funktioniert?

**Comment by FrankoGitHub** [comment]
Ja, mit den Änderungen funktioniert es bei mir ...
Danke
