### ISSUE TITLE
File path not handled consistently (file class)

### ISSUE THREAD

**Issue by agoat** [contao/core#8374]
If I use the path (and name) returned from file::dirname and try to generate a new image than an error with an uncaucht exception is return:
```
Fatal error: Uncaught exception InvalidArgumentException with message Image "..." could not be found thrown in system/modules/core/library/Contao/Image.php on line 112
```

That´s because inside the image class the file->exist method is used to check if the file exist. BUT the path from file::dirname is absolute and the file->exist method expects an relative path.

So the dirname(path) is not handled consistently inside the file class. 

See also #8325.

**Comment by leofeyer** [comment]
> If I use the path (and name) returned from file::dirname and try to generate a new image

Can you please post a code snippet?

**Comment by agoat** [comment]
Sure.

I am creating a new image size inside a template file. The $this->image['path'] contains the value from file::dirname, $this->name contains file::basename. Both variables coming from my extension but the values taken directly from the file class.

```
<div class="images col">
<figure class="lb">
<?php 
	$picture = \Picture::create($this->image['path'].'/'.$this->image['name'], array(0,0,5))->getTemplateData();
	$picture['path'] = $image['path'];
	$picture['name'] = $image['name'];
	$picture['alt'] = $image['alt'];
	$picture['title'] = $image['title'];
	$this->insert((TL_MODE == 'BE') ? 'picture_default' : 'picture_lightbox', $picture);
?>
</figure>
</div>

```

Besides:
In the mean time I worked on my extension and amongst other things I added a $this->image['src'] parameter with the full filename taken from file::path (what is relative to TL_ROOT).
So my extension (or template files) don´t rely on the file::dirname anymore. 

But neverthelsss I think we should stay consistently!!

**Comment by leofeyer** [comment]
If `$this->image['path']` is an absolute path, you need to convert it to a relative path first. `File::$dirname` is always an absolute path.

**Comment by agoat** [comment]
But does this make sense??
The File::dirname method is adding TL_ROOT > You have to str_replace the TL_ROOT to use it with the image class > that again calls the file::exist method, which adds the TL_ROOT again. 
When taking the performance into account, I think that is not a good solution. 
I still think we should stay relative and if anyone need an absolute path we have the global TL_ROOT variable, which is added quickly.

Regardless of this, I´m using the file::path instead of the file::dirname (which is better anyway). So if the file::dirname is meant to be absolute, you can close this.

**Comment by leofeyer** [comment]
> So if the file::dirname is meant to be absolute, you can close this.

It is.
