### ISSUE TITLE
custom mod_article_teaser only possible with .html5

### ISSUE THREAD

**Issue by fritzmg** [contao/core#8376]
When an article should be displayed as teaser, the article module creates a new template (`mod_article_teaser`) here: https://github.com/contao/core/blob/3.5.14/system/modules/core/modules/ModuleArticle.php#L123

However, it uses the `\BackendTemplate` class:
```php
/** @var \FrontendTemplate|object $objTemplate */
$objTemplate = new \BackendTemplate('mod_article_teaser');
```
Thus, if your page layout still uses XHTML (for whatever reason) and you create a custom `mod_article_teaser.xhtml` in your `/templates` directory, its changes won't have any effect, since backend templates are always loaded with `.html5`.

Weirdly enough, the annotation above defines it as a `\FrontendTemplate`.

See also https://community.contao.org/de/showthread.php?62904-Seltsames-Template-Problem

**Comment by leofeyer** [comment]
Fixed in 2742d640aa979355b8df0a4a86973b5bb045bae0.
