### ISSUE TITLE
Feature: Edit image-size in content element via lightbox

### ISSUE THREAD

**Issue by NicolasGoerlach** [contao/core#8378]
It would be nice if we can edit the predefined image-sizes via lightbox from a content element. So we dont have to switch for a quick change.
![artikel iso 9001 inhaltselement id 2092 bearbeiten contao open source cms 3 5](https://cloud.githubusercontent.com/assets/8327905/16233459/b256dd4e-37ce-11e6-8e24-8e8bb6749ae5.png)

Maybe a small icon, after the select fields.

**Comment by leofeyer** [comment]
Although I like the idea, it is not trivial to implement. We need the ID of the theme to know which image sizes to show and we do not have this in the article module (or news module or …).

**Comment by NicolasGoerlach** [comment]
Es würde meiner Meinung nach auch reichen, wenn sich auf Klick des neuen Icons einfach die Bildgrößen in der Lightbox öffnen. So spare ich immer noch ein paar Klicks.

**Comment by fritzmg** [comment]
What about just editing the currently selected image size? Similar to the ContentModule element.

**Comment by aschempp** [comment]
Should be fairly simple, the image size ID is not related to a theme. Dunno about access permission though.

**Comment by asaage** [comment]
> the image size ID is not related to a theme

honestly: i think this is a bug because you define them by theme

**Comment by leofeyer** [comment]
> Should be fairly simple, the image size ID is not related to a theme. Dunno about access permission though.

This would only work if an image size has been selected and saved already. But I agree that this is the most feasible solution.
