### ISSUE TITLE
User, member, article icons status behaves incorrect on eye toggeling in combination with auto activation

### ISSUE THREAD

**Issue by Aybee** [contao/core#8379]
Ich machs mal auf deutsch, damit mich überhaupt jemand versteht.

Online-Demo:

1. Ein **Mitglied** zum Bearbeiten öffnen
2. Die Autoaktivierung auf einen Zeitpunkt in der Zukunft stellen
3. Speichern und schließen
4. Das Auge ist jetzt grün und das User-Icon grau (richtig)
5. Auf das Auge klicken

Man sieht jetzt, dass die beiden Icons synchron grau und farbig werden sobald man das Auge klickt. Der richtige Zustand - User-Icon grau, Auge grün - lässt sich so nicht wieder herstellen, erst wenn das Auge grün ist und man die Seite neu lädt.

Ich habe es noch mit den **Benutzern**, den **Seiten** und **Artikeln** getestet. Bei den Benutzern und Artikeln ist es genauso. Bei den Seiten ist es korrekt, das Seiten-Icon wird hier nicht durch Klicks auf das Auge beeinflusst, wenn die Autoaktivierung in der Zukunft erfolgen soll.

Ich weiß nicht, wo das sonst noch eingebaut ist, da ich diese Autoaktivierung nie benutze und diese Option in meinen Backends deshalb auch gar nicht zur Verfügung steht.

**Comment by leofeyer** [comment]
Behoben in c4272ebfe56ac33d3f811fbcb6c3bd3383a34007.
