### ISSUE TITLE
lazy load in file manager

### ISSUE THREAD

**Issue by DVeris** [contao/core#8380]
when in folder many images
it would be great feature

**Comment by leofeyer** [comment]
What would be a great feature?

**Comment by frontendschlampe** [comment]
> What would be a great feature?

see headline

>> lazy load in file manager

;-)

**Comment by DVeris** [comment]
yes, lazy load in file manager (file picker)

**Comment by DVeris** [comment]
when folder has too many images (1000+)
file picker (file manager) load long

**Comment by leofeyer** [comment]
@contao/developers Any suggestions how to accomplish this?

**Comment by aschempp** [comment]
Should be fairly simple by using some JS lazy-loading script? Unfortunately we need to look for MooTools or ideally VanillaJS. Or we can write our own: https://css-tricks.com/snippets/javascript/lazy-loading-images/

**Comment by lionel-m** [comment]
There is [lazysizes](https://github.com/aFarkas/lazysizes) from the dev of respimage (not tested).

**Comment by leofeyer** [comment]
Lazysizes looks good on the first glance.

**Comment by ausi** [comment]
I don’t think that the loading of the images in the browser is the problem, but rather the resizing of the images in the main request.

**Comment by aschempp** [comment]
Yeah, the images should be generated lazily…

**Comment by leofeyer** [comment]
> I don’t think that the loading of the images in the browser is the problem, but rather the resizing of the images in the main request.

That might be true.

**Comment by agoat** [comment]
> I don’t think that the loading of the images in the browser is the problem, but rather the resizing of the images in the main request.

That´s why I created and use the [imageondemand](https://contao.org/en/extension-list/view/imageondemand.20010069.en.html) extension in all my contao installations.
It moves the resizing of the images from the main request to the image loading request from the browser. 
Working in front- and backend. 

Thus I get no more timeouts on a shared hosting, not even with pages that end up with 200 images for a responsive design (On my page some images have 4 different sizes and another 4 for the lightbox). Another advantage is to have always short page generation times.

It is probably not the best solution, but perhaps it can be a solution.

**Comment by leofeyer** [comment]
Deferred image resizing has been added in Contao 4.9.
