### ISSUE TITLE
change inserttag user:: to member:: and add (BE) user values

### ISSUE THREAD

**Issue by zonky2** [contao/core#8382]
we should change the key user to member - https://github.com/contao/core/blob/26aba3bbce8dfb0370485685d831be6cad4d578c/system/modules/core/library/Contao/InsertTags.php#L233 and add a new section with (backend) user vaues

in this case, we have the same key in compare with the table name (tl_member and tl_user)

**Comment by leofeyer** [comment]
-1

Why would we need back end user values in the front end?

**Comment by zonky2** [comment]
we can use the user info at backend e.g. at MetaModels

**Comment by aschempp** [comment]
Sounds very much like a task that should be done in PHP and not using some insert tags (that will not be available most of the time).

**Comment by leofeyer** [comment]
Also, this is a major BC break. If at all, we could add a new insert tag named `be_user`, but you might as well add this one in you own custom extension.

**Comment by discordier** [comment]
An insert tag for the currently logged in backend user does not make any sense to me.
Everything where this would make sense (in the most abstract way), this can better be fixed by implementing `load_callback` and the like.

Therefore I vote strongly agains implementing such an insert tag.
