### ISSUE TITLE
Uneinheitliches Markup von Artikeln mit und ohne Teaser

### ISSUE THREAD

**Issue by Anke** [contao/core#8383]
Wenn man Artikel mal mit und mal ohne Teaser untereinander auflistet (z.B. um Info-Blöcke etwa gleicher Höhe anzubieten), sieht das so aus:

ohne Teaser: `<div id="title" class="mod_article block">`
mit Teaser: `<article id="title" class="mod_article block">`

Ist das so beabsichtigt? 

Wenn man wie o.g. vorgeht und Artikel mit und ohne Teaser abwechseln, beginnen Artikel ohne Teaser standardmäßig mit einer H1-Überschrift, Teaser jedoch, wie vom Template vorgegeben, mit einer H2-Überschrift, was ein uneinheitliches Layout ergibt.
Wenn es nicht möglich ist, im BE für den Teaser ebenfalls die gewünschte Überschriftsebene auszuwählen, fände ich es fürs Styling praktischer, im mod_article_teaser-Template die Überschrift in den Teaser-Div mit reinzunehmen und auf H1 zu setzen:

```
<article class="<?= $this->class ?> block"<?= $this->cssID ?><?php if ($this->style): ?> style="<?= $this->style ?>"<?php endif; ?>>

  <div class="ce_text block">

    <div class="teaser">
       <h1><?= $this->headline ?></h1>
       <?= $this->teaser ?>
       <p class="more"><a href="<?= $this->href ?>" title="<?= $this->readMore ?>"><?= $this->more ?><span class="invisible"> <?= $this->headline ?></span></a></p>
    </div>

  </div>

</article>
```

**Comment by Aybee** [comment]
Hier mal zum Vergleich
```html
<div class="inside">

  <!-- Teaser anzeigen -->
  <article id="test" class="mod_article first block">
    <div class="ce_text block">
      <h2>Test</h2>
      <div class="teaser">
        <p>lorem ipsum</p>
        <p class="more"> <a title="Read the article: Test" href="en/test/articles/test.html">Read more …<span class="invisible"> Test</span></a></p>
      </div>
    </div>
  </article>

  <!-- Normal: Teaser nicht anzeigen -->
  <div id="about-contao" class="mod_article block">
    <h1 class="ce_headline first">  About Contao</h1>
    <div class="ce_text last block">
      <p> <span>Contao is an open source...</span></p>
    </div>
  </div>

</div>
```
Ja, warum ist der Wrapper des Artikel-Teaser gleich `<article id="test" class="mod_article first block">`. Ich denke er sollte auch `<div id="test" class="mod_article [teaser] first block">` sein.

Bei der **H1**, da kann ich dir nicht zustimmen. Ich denke, dass **H2** die meistbenutzte Headline in z.B. der Hauptspalte ist. Wenn, dann müsste man in den Artikel-Eigenschaften die Möglichkeit haben diese Headline für den Teaser einzustellen.

**Comment by fritzmg** [comment]
Hmmm

http://www.w3schools.com/tags/tag_article.asp
```
The <article> tag specifies independent, self-contained content.

An article should make sense on its own and it should be possible to distribute it independently from the rest of the site.

Potential sources for the <article> element:

    • Forum post
    • Blog post
    • News story
    • Comment
```
http://html5doctor.com/the-article-element/

Der Teaser eines Artikels sollte demnach wohl eher nicht den `<article>` Tag benutzen.

**Comment by Aybee** [comment]
Ich meine die Diskussion ob ein Contao-Artikel mit ARTICLE gewrappt wird, hatten wir damals und uns entschieden beim DIV zu bleiben, weil diese Contao-Artikel doch auch für die unterschiedlichsten Zwecke genutzt werden. Es gibt ja die Erweiterung semantic_html5 mit welcher man auch einen extra Wrapper irgendwo drumlegen kann.

Aber das der Teaser jetzt mit ARTICLE gewrappt wird finde ich schon irgendwie seltsam. Ist mir nie aufgefallen, weil ich das mit dem Teaser sogut wie nie benutze.

**Comment by fritzmg** [comment]
Ja, ich frage mich auch ob das semantisch so überhaupt richtig ist.

**Comment by Anke** [comment]
H1 oder H2 ist mir nicht so wichtig, aber ich meine, die Überschrift wäre innerhalb des teaser-Divs besser aufgehoben, damit man sie per CSS gezielter ansprechen kann, gerade wenn man Artikel mit und ohne Teaser auflistet.

**Comment by Aybee** [comment]
Das sollte aber nicht stören, erstens schreibt man ja sowieso meisten `.mod_article h1` und nicht `div.mod_article h1` und zweitens sind in normalen Artikeln die Überschriften ja auch entweder direkt `h1.ce_headline` oder eine `h1` innerhalb von `.ce_text`.

**Comment by Anke** [comment]
Die Teaser-Überschrift ist doch Teil des Teasers, nicht wahr? Da mach es imho Sinn, sie - wie den Weiterlesen-Link - in den Teaser-Div reinzunehmen und nicht außerhalb zu stellen. Es gibt Szenarien, bei denen das Ansprechen der Überschrift per CSS so vereinfacht wird.

Zudem wäre es mir eigentlich lieber, wenn nicht der Artikel-Titel als Teaser-Überschrift herhalten müsste, sondern wenn die Teaser-Überschrift in einem eigenen Feld definiert werden könnte. Kunden haben manchmal recht lange Überschriften, und da der Artikel-Title in der Artikel-Übersicht im BE verwendet wird, kann das recht unübersichtlich aussehen. 

Daher wäre es ideal, wenn der Artikel-Titel nur intern verwendet würde und ein eigenes Feld für eine Teaser-Überschrift vorhanden wäre. Wenn man keine Teaser verwendet, wird der Artikel-Titel ja auch nur intern verwendet.

**Comment by leofeyer** [comment]
> ohne Teaser: `<div id="title" class="mod_article block">`
> mit Teaser: `<article id="title" class="mod_article block">`
>
> Ist das so beabsichtigt? 

Ja, das ist semantisch korrekt so.
