### ISSUE TITLE
Chosen select menu jumps on mouse hover

### ISSUE THREAD

**Issue by Aybee** [contao/core#8384]
_Contao 3.5.14, Windows 10, Firefox, Chrome_

Nachstellen in der Online-Demo:
1. Listing Modul ID 62 zum Bearbeiten öffnen http://demo.contao.org/contao/main.php?do=themes&table=tl_module&act=edit&id=62&rt=14ac42fe392dc8f0e6a0f5e39183a2f5
2. Auf **Modul type** Listing klicken
3. Jetzt mit der Maus langsam nach unten fahren
4. Wie man sieht springt (scrollt) die Liste an eine ungünstige Stelle, sodass man die Orientierung verliert

Ursache:

``` html
<ul class="chzn-results">
  <li class="group-result" id="ctrl_type_chzn_g_0" style="display: block;">
    <div>&nbsp;Navigation</div>
  </li>
  <li class="active-result group-option" id="ctrl_type_chzn_o_1" style="display: block;">Navigationsmenü</li>
```

Bitte mal die Dev-Tools öffnen und eine bestehende CSS-Regel ändern

``` css
.chzn-results .active-result {
  cursor: pointer;
  background-color: red; /* neu */
}
```

Wenn man jetzt die Liste wieder öffnet sieht man direkt unter dem Suchfeld einen schmalen Streifen in Rot, welcher zu dem **Event list menu** gehört. Wenn die Maus dort drüber fährt, wird zu diesem Punkt gescrollt - das ist die Ursache.

Quickfix:

``` css
.chzn-container .chzn-results {
  max-height: 225px; /* alt ist 228px */
}
```

Eine bessere Lösung wäre, wenn diese Scrollaktion beim dortigen herumbewegen mit der Maus  erst überhaupt nicht ausgeführt würde.

Das Scrollen wird über die Funktion **result_do_highlight** angestoßen https://github.com/contao/core/blob/master/assets/mootools/chosen/chosen-uncompressed.js#L357

**result_do_highlight** wird an mehreren Stellen getriggert, so z.B. auch beim Öffnen der Liste über **results_show** https://github.com/contao/core/blob/master/assets/mootools/chosen/chosen-uncompressed.js#L400. Hier macht das Scrollen Sinn, da zu dem aktiven (selected) Punkt gelangt werden muss. Auch beim Navigieren mit der Tastatur macht das Sinn. Aber bei **search_results_mouseover** https://github.com/contao/core/blob/master/assets/mootools/chosen/chosen-uncompressed.js#L480 denke ich nicht.

Mir war das schon sehr lange ein Dorn im Auge, aber da ich fast nur mit eigenen BE-Themes arbeite, dachte ich, es läge vielleicht daran. Jetzt ist mir das so auf den Keks gegangen, dass ich da mal richtig nachgesehen habe wo das herkommt.

**Comment by leofeyer** [comment]
Leider lässt sich das Problem unter Mac nicht nachvollziehen. Könntest Du ein kurzes Video davon machen? @fritzmg Kannst Du den Fehler reproduzieren?

**Comment by fritzmg** [comment]
Jap, kann es reproduzieren: https://youtu.be/2IuX1mEd-RI

Es passiert, weil das JavaScript Select Menü automatisch on mouse over Elemente sichtbar macht, wenn sie nur halb sichtbar sind - und in diesem Fall ist zB der Punkt `Event list menu` für ~1 Pixel sichtbar - und wenn man über dieses Pixel drüber fährt, springt die Liste nach oben, damit der Punkt komplett sichtbar ist.

**Comment by Aybee** [comment]
@fritzmg Danke.

Leider ist 225px wohl auch kein Allheilmittel, weil das im Chrome funktioniert, aber der Firefox müsste da schon 226px haben. Diese "Lösung" wäre also sehr anfällig, evtl. passt es dann sogar auf deinem Mac nicht mehr.

Die richitge Lösung wäre, die enthaltene Scroll-Funktion innerhalb von **result_do_highlight** für das mouse-over abzuschalten, weil sie dort IMHO nicht benötigt wird Vielleicht mit nem Parameter.
```js
result_do_highlight(el, scroll=true)
```

**Comment by Aybee** [comment]
> @fritzmg weil das JavaScript Select Menü automatisch on mouse over Elemente sichtbar macht

Nur nochmal zur genaueren Klärung: Das Highlighten ist ok nur das Scrollen sollte bei mouse over abgestellt werden.

**Comment by Aybee** [comment]
So sollte das eigentlich funktionieren. Ich hoffe dieses Diff reicht. Damit wird bei der Funktion `search_results_mouseover()` https://github.com/contao/core/blob/master/assets/mootools/chosen/chosen-uncompressed.js#L480 nur noch gehighlightet aber nicht mehr gescrollt.
```diff
diff U1wB C:/assets/mootools/chosen/chosen-uncompressed.js C:/assets/mootools/chosen/chosen-uncompressed-patched.js
--- C:/assets/mootools/chosen/chosen-uncompressed.js	Wed Jul 12 11:00:13 2017
+++ C:/assets/mootools/chosen/chosen-uncompressed-patched.js	Sun Aug 13 22:03:34 2017
@@ -356,3 +356,3 @@
 
-	result_do_highlight: function(el){
+	result_do_highlight: function(el, doScroll=true){
 
@@ -372,5 +372,5 @@
 			high_bottom = high_top + this.result_highlight.getCoordinates().height;
-			if (high_bottom >= visible_bottom){
+			if (high_bottom >= visible_bottom && doScroll){
 				this.search_results.scrollTo(0, (high_bottom - maxHeight) > 0 ? high_bottom - maxHeight : 0);
-			}else if (high_top < visible_top){
+			}else if (high_top < visible_top && doScroll){
 				this.search_results.scrollTo(0, high_top);
@@ -483,3 +483,3 @@
 		if (target){
-			this.result_do_highlight(target);
+			this.result_do_highlight(target, false);
 		}
```
BTW: Da scheint noch ein Firefoxbug zu existieren, welches die Optgroups betrifft. Unser Padding auf den Optgroups https://github.com/contao/core/blob/master/system/themes/default/src/basic.css#L130-L131 bewirkt auch ein leichtes Springen bei mouseover ohne chosen. Was man sehen kann, wenn man JS deaktiviert. Der Chrome hat dies nicht, aber er ignoriert auch jedwedes Padding auf den Optgroups. Dieses Springen können wir beseitigen, wenn wir dieses Padding dort entfernen.

**Comment by leofeyer** [comment]
Also bei mir funktioniert es mit 224px in allen Browsern auf dem Mac.

Das Problem an der JavaScript-Lösung ist, dass halb eingeblendete Einträge beim Scrollen nicht mehr komplett eingeblendet werden, wenn man sie auswählen möchte.

**Comment by leofeyer** [comment]
@Aybee Kannst Du bitte mal testen, ob das Problem mit `192px` oder `190px` auch behoben wäre?

**Comment by leofeyer** [comment]
@Aybee @fritzmg Könnt ihr bitte mal testen, ob das Problem mit `192px` oder `190px` auch behoben wäre?

**Comment by Aybee** [comment]
Sorry, ich hatte gestern schon mit der Antwort begonnen, wollte aber noch etwas ausarbeiten, bin aber noch nicht dazu gekommen. Hier das von Gestern:

Nein, springt bei mir auch mit 192 o. 190. Diese Lösung ist auch nicht gut, da sie nicht mehr funktioniert, sobald ein Browser den Text etwas anders darstellt.

Was meinst du mit "halb eingeblendete Einträge". Sowas habe ich nicht. Kannst du da mal ein Video machen, oder mir per Skype zeigen?

Das Scrollen innerhalb von `result_do_highlight()` ist doch nur dafür da, wenn  man das Select öffnet, dass dann das OPTION[selected] in den sichtbaren Bereich gescrollt wird. Wenn ich mit der Mouse da drüber fahre oder scrolle, muss doch nichts mehr zusätzlich mit JS gescrollt werden, oder?.

Eine aufwändigere Lösung wäre evtl. die Max-Height dynamisch zu berechnen. Aber das scheint auch nicht so einfach zu sein, da die `.group-result` eine etwas andere Höhe haben als die `acitve-result`. Liegt evtl. an dem `font-weight:bold` aber nur vermutet.

**Comment by Aybee** [comment]
Push. Das sollte unbedingt gefixt werden. Ich hatte das bei meiner Demoinstallation im Core gepatcht und jetzt nach dem Update ist es wieder da. Das ist wirklich sehr nervig dieses Springen (siehe Video von @fritzmg).

**Comment by leofeyer** [comment]
> Push. Das sollte unbedingt gefixt werden.

Ich denke wir sind uns einig, dass dieses Problem keinerlei Priorität hat, oder? Es funktioniert auch alles ohne Einschränkungen, wenn wir es nicht fixen.

> Was meinst du mit "halb eingeblendete Einträge". Sowas habe ich nicht.

Der Sinn der Funktion ist es, die Auswahl so zu scrollen, dass der ausgewählte Punkt vollständig sichtbar ist.

![](https://user-images.githubusercontent.com/1192057/31180278-844b3ac2-a91e-11e7-8543-7ac3f15165d9.gif)

Mit Deiner Änderung wäre das aber nicht mehr der Fall:

![](https://user-images.githubusercontent.com/1192057/31180297-8f4a9b02-a91e-11e7-8b01-ff78de90f2bf.gif)

Insofern ist die Lösung auf jeden Fall nicht korrekt.

**Comment by Aybee** [comment]
Du hast jetzt das Glück, das du diesen Jump-Effect bei dir nicht hast, sonst würdest du das bestimmt auch direkt ändern wollen, weil es sehr nervig ist.

Auf dieses Feature, dass angeschnittene Punkte nachgescrollt werden, könnte ich sehr gut verzichten . Das macht ein Select sonst auch nicht und wirkt bei mir auch eher verstörend - kein Mehrwert, eher im Gegenteil. Entweder scrollt man mit der Maus, oder mit der Scrollbar. Wenn ich den Mousecursor nach oben oder unten bewege, dann sehe ich da keinen Vorteil, das Nachgescrollt wird, wenn ich mit der Maus aus Versehen einen angeschnittenen erwische.

Ich für meinen Teil würde sofort auf dieses Scrollen nach diesem Öffnen verzichten wollen und meine obige Lösung einbauen.

Wenn man dieses Nachführen dennoch möchte, kann man das auch machen. Dann muss man erstmal dafür sorgen, das die LIs inkl. der group-option eine feste Höhe bekommen, welche in allen Browsern gleich ist. Und die UL muss ein max-height bekommen, welches ein Vielfaches davon ist:
```css
.chzn-container .chzn-results {
  max-height: 240px;
}
.chzn-container .chzn-results li {
  line-height: 20px;
  overflow: hidden;
  padding: 0 2px 0 1px;
}
```
Evtl. ist das bereits die Lösung. Ich habe es mit einigen Selects und unterschiedlichen Auswahlen - oben, mitte, unten -  in Contao 3.5.29 getestet.

**Comment by leofeyer** [comment]
Behoben in 2ceee04038b31260cee2feeae7ce340a0d21ed78.

**Comment by Aybee** [comment]
Das springt bei mir immer noch. Das wird nur gehen, wenn man sicherstellt, dass die Höhe **aller** LIs in **allen** Browsern gleich ist.

Im Moment ist die Höhe im FF **19.8px**. Ergibt sich aus 
`fontsize 14px * line-height 1.2 + padding 3px`

Obwohl die Rechung im Chrome die gleiche ist, sind die LIs im Chrome **19px** hoch.

ps Sorry, ich hatte mich in meiner Lösung oben mit dem Padding vertan, links und rechts waren ja 7px, habe es also jetzt oben korrigiert.

**Comment by Aybee** [comment]
**IE** und **Edge** berechnen eine Höhe der LIs von 19.72px.

height 16.72px
line-height 16.71px

**Comment by leofeyer** [comment]
Ah, stimmt, die `line-height` wollte ich angepasst haben. Sonst geht es nicht.

**Comment by leofeyer** [comment]
Mit einer `line-height` von `13px` funktioniert es bei mir in allen Mac-Browsern. Bei Dir?

**Comment by Aybee** [comment]
Ja, geht. Im FF und Edge getestet. Damit ham wir jetzt ne Höhe von 16px, was auch ein Vielfaches von 192 ist.

Ich hatte zur Sicherheit noch **overflow:hidden** hinzugefügt, was evtl. nicht nötig ist und ein **height:13px** würde es auch nochmal sicherer machen obwohl wahrscheinlich überflüssig.

ps Wie du siehst, spare ich mir immer gerne das Padding oben und unten. In manchen Browsern und mit manchen Schriftarten ist die Schrift dann zwar nicht 100%ig vert. zentriert, aber mir egal.

pps 13px sieht ein wenig gequetscht aus, evtl. wäre 14px mit ner max-width von 204px angenehmer?

**Comment by leofeyer** [comment]
`13px` entspricht der bisherigen Höhe, insofern ist das ok. Behoben in cadb0b217650f30e5ff4689207a67422582e7da0.
