### ISSUE TITLE
dropzone is outdated and has a serious iOS bug

### ISSUE THREAD

**Issue by Defcon0** [contao/core#8385]
Hello,

would it be possible to update the dropzone js in a future release? At the moment there's a quite critical iOS specific bug in there (https://github.com/enyo/dropzone/issues/935) causing frontend widgets using dropzone simply not to work on iOS.

As mentioned in the dropzone issue above in version >=4.1.1 the bug is solved.

**Comment by leofeyer** [comment]
DropZone 4 is not compatible to DropZone 3, which we are currently using. I have therefore procrastinated the update but I guess now I cannot anymore. 😢

**Comment by aschempp** [comment]
Maybe we should also reconsider DropZone at that point. I also like fineuploader.com for example.

**Comment by Defcon0** [comment]
One thing dropzone (at least in version 3 used in contao) didn't fully support had been the opportunity to add mock files, i.e. if I have a frontend widget (which we did with contao-multifileupload which at the moment doesn't work with form generator but contao-formhybrid) in a form that has a database record behind, the files/images/... already stored in the record should be visible even after reload as a mock file.

I think in dropzone 4 this works quite well now. In case of fineuploader I'm not sure if that's implemented.

**Comment by leofeyer** [comment]
If you create a PR, I'll add whatever (reasonable) uploader you want. 😄

**Comment by aschempp** [comment]
Should be fairly easy to adapt from our https://github.com/terminal42/contao-fineuploader :-)
@qzminski do you agree?

**Comment by Defcon0** [comment]
@aschempp: We should do better research on existing modules :) The only issue preventing us from using your module is the necessity for mootools in the frontend. Why is mootools needed in frontend exactly? At least Fineuploader doesn't need it.

**Comment by aschempp** [comment]
I don't know, maybe you can find out? 😄

**Comment by Defcon0** [comment]
I think it's your call in here https://github.com/terminal42/contao-fineuploader/blob/master/assets/handler.js . At least I don't have "Request" in jQuery :) Maybe we fork it and do a pull request for jQuery support.

**Comment by qzminski** [comment]
FineUploader ftw and it became a free software recently https://blog.fineuploader.com/2016/05/19/fine-uploader-5-9-free-at-last/

The MooTools could be exchanged to jQuery obviously. It was just introduced probably because the project we created this extension for used MooTools.

**Comment by leofeyer** [comment]
@contao/developers I wonder if a major update or even a replacement of the uploader is something we should consider in a bugfix release?

**Comment by aschempp** [comment]
I don't think so…

**Comment by leofeyer** [comment]
Updated in contao/core-bundle@720f284786cc0e7bb62928278c97f163beb6f9e5.
