### ISSUE TITLE
creating a new 403 or 404 page yields unpublished article with no title and no alias

### ISSUE THREAD

**Issue by fritzmg** [contao/core#8387]
* (remove any existing 403 or 404 page from the website root)
* create a new page in the website root
* set the type to 403 or 404
* set it to published
* click _Save and close_
* click on _Edit the articles of page ID …_

You will see that the created article for this page will have no title and no alias and it will be unpublished.

![screen shot 2016-07-01 at 10 27 08](https://cloud.githubusercontent.com/assets/4970961/16516176/ca907d84-3f76-11e6-88f9-4289af795486.png)

Articles of new regular published pages have a title and an alias and are published.

Also happens in Contao `4.2.0`.

**Comment by leofeyer** [comment]
This only happens if you change the page type before entering a page title, right?

**Comment by leofeyer** [comment]
Fixed in 353431298ab4a8f8dfaf6a4f9213297542b9f215.

**Comment by fritzmg** [comment]
Yes and no. If you enter a page name before changing the page type, the article will have a title. However, it will still be unpublished, even though you published the page itself before saving.

**Comment by leofeyer** [comment]
Correct.

**Comment by fritzmg** [comment]
That's unintuitive though. If you create a regular page and publish it before saving, its article will also be published. If you create a 403 or 404 page [1] and publish it before saving, its article will not be published.

[1] most people probably create a new page and switch its type immediately, since that is what they want, and don't publish it before switching the type.
