### ISSUE TITLE
[3.5.14] E-Mail-Adresse wird nicht gefunden, da Groß- und Kleinschreibung unterschieden wird

### ISSUE THREAD

**Issue by Samson1964** [contao/core#8388]
Das Passwort-vergessen-Modul für Mitglieder fragt die E-Mail-Adresse des Mitglieds ab. Bei Eingabe von "Hans.Mustermann@domain.de" kommt die Meldung, das kein Mitglied mit dieser Adresse gefunden wurde. In der tl_member steht "hans.mustermann@domain.de". Die Adresse ist also vorhanden!

Contao scheint keine generelle Umwandlung in Kleinschreibung vorzunehmen, denn in tl_member sehe ich auch Großbuchstaben. Das Mitglied hat sich also mal mit "hans.mustermann@domain.de" registriert, bei der Passwort-vergessen-Funktion aber "Hans.Mustermann@domain.de" geschrieben.

In der Demo läßt sich das nicht nachstellen, da erstens keine Registrierung möglich ist und zweitens es keine Passwort-vergessen-Funktion gibt.

**Comment by Samson1964** [comment]
Sorry, war ein Mißverständnis. Entgegen meines Wissens war der Mitgliederaccount noch nicht aktiviert - obwohl ich ihn wissentlich gestern selbst aktiviert hatte. Aber muß wohl mein Alter sein ...

**Comment by asaage** [comment]
Abgesehen davon müssen beide Adressen auch nicht zwangsläufig das selbe Postfach bedienen
(in den gängigen mailserver-implementationen ist das allerdings so).
https://tools.ietf.org/html/rfc5321#section-2.4
