### ISSUE TITLE
Indexing Text which contains Soft Hyphens

### ISSUE THREAD

**Issue by HermannAuer** [contao/core#8389]
Search functions do not work on text which contain soft hyphens.

All soft hyphens must be completely removed before the indexer analyzes the text!

If there, for example, a text string "Ge­samt­kon­zept" is partitioned by Soft Hyphens into "Ge[-]samt[-]kon[-]zept" you cannot find "gesamtkonzept", you only can find "ge" or "samt" or "kon" or "zept". This is, of course, not helpful for the user.

On the other hand, I don't want to renounce the soft hyphens because long words in the German language would smash the layout on small screens. So I prefer to renounce the search function rather than the soft hyphens.

I use actually Contao 3.5.12 and xampp (Panel Version 3.2.2) with PHP 5.6.21.

**Comment by asaage** [comment]
> On the other hand, I don't want to renounce the soft hyphens because long words in the German language would smash the layout on small screens.

must be difficult to edit hyphens in the BE for variable-width FE layouts.
possible workaround:
https://css-tricks.com/almanac/properties/h/hyphenate/
unfortunately no chrome and android browsersupport yet...
http://caniuse.com/#feat=css-hyphens

**Comment by aschempp** [comment]
why do you think editing is difficult?

**Comment by asaage** [comment]
just because you never know where ugly-looking linebreaks will occur in the front-end and dividing the whole text or only long words like that: "Ge[-]samt[-]kon[-]zept" seems cumbersome.

**Comment by HermannAuer** [comment]
Ok, it may be cumbersome - this is the hard lot of deskmen. But i did so: everywhere where the German language rule allows a line break, I inserted a soft hyphen. ;-)

**Comment by leofeyer** [comment]
Fixed in 92a33a794cd31d5894e50bfb491f0515caf38804.
