### ISSUE TITLE
Bitte bei allen Downloads-Stellen Variable extension befüllen

### ISSUE THREAD

**Issue by NinaG** [contao/core#8392]
In den Downloads-Elementen kann man sich mit $file['extension'] die Dateiendung ausgeben lassen. Dadurch kann man z.B. im Template einstellen, dass nicht nur die Größe, sondern eben auch den Dateityp ausgegeben bekommt.

Leider geht das aber beim Datei-Anhang von Nachrichten nicht. Dort wird der Dateityp nirgends separat in die Variablen geschrieben, so dass man ihn nicht mal eben ins Template übertragen kann.

Es wäre schön, wenn Contao sich da an allen Stellen, wo es Downloads gibt, identisch verhält - also überall die Variable "extension" befüllt und akzeptiert.

(in C3.5.x getestet)

**Comment by leofeyer** [comment]
Fixed in cf1e67afc2d6a905ca5ca38c0eccd93d46bdf936.
