### ISSUE TITLE
Database update changes persist after update

### ISSUE THREAD

**Issue by Fuzzyma** [contao/core#8393]
See [stackoverflow](http://stackoverflow.com/questions/38169473/contao-database-update-always-shows-alter-table-with-unchanged-column/38190657#38190657) for the original question.

> I am using contao 4 but I had this problem already in version 3. I have created a table with some columns. One of this column is marked as int(10) default NULL. Nothing special about that. However: When I run my database upate, this column is always shown as changed.

>    ALTER TABLE `tl_products` CHANGE `tags` `tags` int(10) default NULL;

> It doenst matter how often I press upate. This statement never disappears. I already saw that at different other cases (e.g. when one writes default 0 instead of default '0'). Does anyone know how to fix this one?

The accepted answer suggests to change this behavior since e.g. a nullable int field is completely valid

**Comment by aschempp** [comment]
Unfortunatly Contao's database diff tool is very strict. You must write INT(10) (in capitals) and then it should work.

**Comment by Fuzzyma** [comment]
Oh - so simple. Thank you!! Do we have a FAQ somewhere to write that down immediately?

**Comment by aschempp** [comment]
Well there's the Contao documentation at https://docs.contao.org

There's not really a section related to that DB stuff, but you could write a cookbook article…

**Comment by Aybee** [comment]
I searched the 3.5.14 core for `"int(` and this is what I found
```
"int(10) NOT NULL default '0'"
"int(10) NULL"
"int(10) unsigned NOT NULL auto_increment"
"int(10) unsigned NOT NULL default '0'"
"int(10) unsigned NOT NULL default '300'"
"int(10) unsigned NULL"
"int(9) NOT NULL default '0'"
```
Is there a change in Contao 4? This is all in lower case.

**Comment by fritzmg** [comment]
I experience this problem with the Contao core as well (with certain SQL definitions), not just with custom SQL definitions. I'll look further into it. I am not sure why `INT(10) default NULL` would work suddenly.

**Comment by BugBuster1701** [comment]
`int(10) default NULL` ist theoretisch die Kurzform für `int(10) NOT NULL default NULL` und das macht keinen Sinn.
Daher wenn NULL als Default sein soll, dann direkt `int(10) NULL` oder eben `int(10) NOT NULL default '0'`
Das "int" plötzlich groß geschrieben werden soll, wäre neu, in 4.1 ging das noch wie zu 3.5 Zeiten.

**Comment by fritzmg** [comment]
Ah stimmt, so war das.
