### ISSUE TITLE
Form Field name with dot

### ISSUE THREAD

**Issue by tsarma** [contao/core#8400]
When form field attribute name has a dot, then value remains empty when the form is submitted. This submitted value is also not available in $GLOBALS['TL_HOOKS']['processFormData'] and $GLOBALS['TL_HOOKS']['prepareFormData']

![dot](https://cloud.githubusercontent.com/assets/683894/16681270/eafce544-44f3-11e6-8063-7a6670326dfc.jpg)

**Comment by leofeyer** [comment]
See #8403.
