### ISSUE TITLE
Wrong sorting in module listview with sort by type

### ISSUE THREAD

**Issue by Aybee** [contao/core#8402]
Wie auf dem Screenshot zu sehen ist, stimmt die Sortierung nicht.
![sort-modules-by-type](https://cloud.githubusercontent.com/assets/1143013/16689247/597623fe-4522-11e6-87fb-8edee9c10c7f.png)
Das liegt daran, dass nach dem Feldinhalt von `tl_module.type` und nicht nach dem Sprachbaustein sortiert wird. Beispiel: **logout** => **Automatic Logout**.

Mit BE in DE und dann noch eigenen Erweiterungen, sieht das teilweise sehr schlimm aus. Zum Teil fehlt die Überschrift dabei auch komplett.

Wenn man diese Zeile
https://github.com/contao/core/blob/master/system/modules/core/dca/tl_module.php#L185
testweise auskommentiert

``` php
#'reference'               => &$GLOBALS['TL_LANG']['FMD'],
```

sieht man zwar nur den Feldinhalt als Headline (Beispiel: **Article list** => **articleList**), aber das sieht schon besser aus, die Sortierung stimmt (in allen Sprachen) und es gibt keine leeren Überschriften.

Man müsste also entweder aufwendig die Sortierung nach den Sprachbausteinen aufbereiten anstatt nach den Feldinhalten, oder für Felder, welche durch Sprachbausteine übersetzt werden, in den Headlines den Feldinhalt anstatt des Sprachbausteins anzeigen.

**Comment by leofeyer** [comment]
Ich sehe das Problem, wüsste aber nicht, wie wir das sinnvoll lösen könnten. Die Sortierung erfolgt auf DB-Ebene und die Übersetzung erst anschließend, daher müssten wir theoretisch alles buffern und vor der Ausgabe neu sortieren. Sehr performant ist das bestimmt nicht.

**Comment by Aybee** [comment]
Ich finde, wenn nach einer Tabellenspalte sortiert wird (ich denke das ist immer der Fall) und der Wert dann **übersetzt** wird, dann müsste der Wert aus den **Feldern** in der Überschrift stehen. Die Übersetzung kann dann ja in eckigen Klammern dahinter erfolgen. Wobei die Übersetzung ja sowieso schon hinter jedem Modul steht.

Vielleicht könnte man diese Zeile https://github.com/contao/core/blob/3.5.15/system/modules/core/drivers/DC_Table.php#L4232
```php
$remoteNew = $this->formatCurrentValue($firstOrderBy, $row[$i][$firstOrderBy], $sortingMode);
```
ergänzen mit
```php
$remoteNew = $this->formatCurrentValue($firstOrderBy, $row[$i][$firstOrderBy], $sortingMode);

if($GLOBALS['TL_DCA'][$this->strTable]['fields'][$firstOrderBy]['reference'])
{
	$remoteNew = $row[$i][$firstOrderBy] . ' <span style="color:#b3b3b3; font-weight:normal;">[' . $remoteNew . ']</span>';
}
```
Ich habe in meiner Testinstallation (mit vielen Erweiterungen) mal alle Seiten mit Sortieroptionen durchprobiert, und mir ist erstmal nichts Ungewöhnliches aufgefallen.

Von mir aus kann man dieses
```php
 . ' <span style="color:#b3b3b3; font-weight:normal;">[' . $remoteNew . ']</span>'
```
auch ganz weglassen, weil es ja sowieso schon hinter den einzelnen Modulen steht.

**Comment by leofeyer** [comment]
Das ist noch nicht die optimale Lösung IMHO. Da fällt uns sicherlich beim nächsten Call noch etwas besseres ein @contao/developers.

**Comment by Toflar** [comment]
Options laden, sortieren gem. Sprache und dann FIND_IN_SET(). Was anderes fällt mir da spontan auch nicht ein.

**Comment by Aybee** [comment]
Hier nochmal der Vergleich, wie ich meine, dass es aussehen könnte und wie es jetzt aussieht.
**IST**:
![themes_ _contao_official_demo_ _frontend-module_-_contao_open_source_cms_3 5_-_2016-11-18_00 54 20](https://cloud.githubusercontent.com/assets/1143013/20412907/ed743680-ad29-11e6-9d62-1d6c7d5f1685.png)
**SOLL** (könnte):
![themes_ _contao_official_demo_ _frontend-module_-_contao_open_source_cms_3 5_-_2016-11-18_00 52 00](https://cloud.githubusercontent.com/assets/1143013/20412916/fde6ecba-ad29-11e6-8835-8ef8d89a852d.png)

**Comment by leofeyer** [comment]
Warum gibt es bei Dir eine Gruppe "HTML-Code"? Sollte da nicht "html" stehen?

**Comment by Aybee** [comment]
Ja, stimmt. Kommt vielleicht daher, weil es ein Feld in tl_module gibt, welches den gleichen Namen hat wie ein Modultyp. ?
`modules\core\languages\de\tl_module.xlf`
```
<trans-unit id="tl_module.html.0">
  <source>HTML code</source>
  <target>HTML-Code</target>
</trans-unit>
```

**Comment by leofeyer** [comment]
Deswegen sage ich ja, dass das noch nicht die optimale Lösung ist. 😄 

Außerdem funktioniert das zwar für diesen einen Fall, aber macht es auch in anderen Fällen Sinn? Wenn Mitglieder z.B. nach Land gruppiert sind, stünde da nur "de" und "fr" etc. Das wäre keineswegs aussagekräftig, wenn man nicht zufällig die ISO-Länderkürzel kennt.

**Comment by Aybee** [comment]
Ja, stimmt, dann dürfte die Sortierung nach Land für Mitglieder momentan auch nicht wirklich sortiert sein. Wir müssten also tatsächlich zuerst die Übersetzung holen und dann danach sortieren, für den Fall, dass `referenz` für das Feld gesetzt ist.

**Comment by leofeyer** [comment]
<img width="1033" alt="" src="https://user-images.githubusercontent.com/1192057/30168365-7d7e49c2-93e9-11e7-8aef-6f60cadc54c0.png">

**Comment by Aybee** [comment]
Fände ich in Ordnung so. Ach, ist ja wie in meinem Beispiel oben unter **SOLL (könnte)**. Oder?

**Comment by leofeyer** [comment]
Stimmt. 😄

**Comment by leofeyer** [comment]
Geändert in 9675369e23ea00789857e486fc5ea9802a61993d.

**Comment by Aybee** [comment]
Thank you 💯
