### ISSUE TITLE
Extend TL_MODE with "CRON"

### ISSUE THREAD

**Issue by garyee** [contao/core#8406]
Hi,

it would be good to have a simple tool to know if the current code is executed by a Cron-job.
My idea was, to extend the two Possible values of TL_MODE ("BE","FE") with a third option "CRON".
The use-case is, that I have a method which is called from a button in the BE or a cron-job. I would wan't to display an error message (Message Class) in the BE, or write something in the log table.

One other positive sideeffect would be that cron would become a source of a log-entry, which means there could be categories of cron log-entrys (like general or error).

**Comment by Toflar** [comment]
In Contao 4, you have the `app/console` you can use and which is the right tool for that. Basically we do have that feature already.

**Comment by garyee** [comment]
But isn't app/console like the debug mode in Contao 3?

**Comment by Toflar** [comment]
? No that's the CLI interface to any Symfony application.

**Comment by garyee** [comment]
Okay so how would I use it in my source code in order to know if I should display an error-message or create a new log entry?

**Comment by Toflar** [comment]
Are you talking about cronjobs that are triggered via the `cron.php`?

**Comment by garyee** [comment]
"Real" crons and Poor-Man-Crons, the difference for the use-case is if there is someone who "triggered" the method from the BE and to whom I want to give direct feedback or if it is just a cron-job getting executed with no direct user.

**Comment by Toflar** [comment]
If you registered your method in `$GLOBALS['TL_CRON']` you can just set whatever constant in that method and do things depending on this constant in your code.

**Comment by garyee** [comment]
Yeah, I know :) , but wouldn't it be nice if contao did it for me? so I don't have to do it over and over again for every extension with a Cron-job?
It is more of an idea for a (tiny) feature then a bug report...

**Comment by Toflar** [comment]
The feature addition does not make sense at all in a Symfony environment which is the only version that gets new features )

**Comment by garyee** [comment]
okay

**Comment by garyee** [comment]
okay so how can I do it easily in contao 4?

**Comment by aschempp** [comment]
http://symfony.com/doc/current/cookbook/console/console_command.html

**Comment by discordier** [comment]
It might be worth mentioning that we are trying to phase out every constant for Contao 5, therefore the addition of new values for existing constants in Contao 4 is definately not the way to go.
@garyee, you should find a different way for configuring your cron tasks which is not involving constants.
