### ISSUE TITLE
Link zu Seitenstruktur bearbeiten wird auch angezeigt wenn Recht fehlt

### ISSUE THREAD

**Issue by Mynyx** [contao/core#8407]
Zum Beispiel wenn in einem Inhaltselement im Editor ein Link über den Dialog "Link einfügen" erstellt wird, dann wird der Link die "Die Seitenstruktur bearbeiten" stets angezeigt, auch wenn der Benutzer gar nicht über das Recht für das Modul Seitenstruktur verfügt.

isotope/core#1677

**Comment by leofeyer** [comment]
Fixed in cc4e37374e118dbe11e53a3c156179396601c384.
