### ISSUE TITLE
Neuer Hook um Zugang zur Seite zu beschränken

### ISSUE THREAD

**Issue by bennyborn** [contao/core#8409]
Mit dem Hook `isVisibleElement` kann man sich schön noch zusätzliche Felder in die tl_content einbauen um den Zugriff auf Inhaltselemente zu beschränken. Leider vermisse ich ähnliche Funktionalität in der Seitenstruktur.

Ich arbeite gerade an einem Projekt in dem es leider nicht ausreicht einfach nach einer bestimmten Mitgliedsgruppe zu filtern.

Aktuell muss ich mir mit einer Modifikation im Core behelfen indem ich in der `Module::renderNavigation` einen Hook `isVisiblePage` eingebaut habe um die Seite zumindest in der Navigation zu überspringen.

Wäre vielleicht etwas das man in künftige Releases übernehmen könnte?

**Comment by fritzmg** [comment]
Wird isVisibleElement nicht schon bei Seiten eingesetzt?

**Comment by bennyborn** [comment]
Leider nein, nur bei Artikeln, Elementen und Modulen.

Am 15.07.2016 4:45 nachm. schrieb "fritzmg" <notifications@github.com>:

**Comment by fritzmg** [comment]
@leofeyer couldn't https://github.com/contao/core/blob/3.5.15/system/modules/core/controllers/FrontendIndex.php#L247
```php
// Check the user groups if the page is protected
if ($objPage->protected && !BE_USER_LOGGED_IN)
{
	$arrGroups = $objPage->groups; // required for empty()

	if (!is_array($arrGroups) || empty($arrGroups) || !count(array_intersect($arrGroups, $this->User->groups)))
	{
		$this->log('Page "' . $pageId . '" can only be accessed by groups "' . implode(', ', (array) $objPage->groups) . '" (current user groups: ' . implode(', ', $this->User->groups) . ')', __METHOD__, TL_ERROR);

		$objHandler = new $GLOBALS['TL_PTY']['error_403']();
		$objHandler->generate($pageId, $objRootPage);
	}
}
```
be changed to:
```php
// Check the user groups if the page is protected
if (!\Controller::isVisibleElement($objPage))
{
	$this->log('Page "' . $pageId . '" can only be accessed by groups "' . implode(', ', (array) $objPage->groups) . '" (current user groups: ' . implode(', ', $this->User->groups) . ')', __METHOD__, TL_ERROR);

	$objHandler = new $GLOBALS['TL_PTY']['error_403']();
	$objHandler->generate($pageId, $objRootPage);
}
```
?

**Comment by bennyborn** [comment]
@fritzmg No hurry, just asking for future use ;)

But I guess adding this just to `FrontendIndex` would still cause problems. There must be a way not to only redirect to a 403 page but to hide the page entirely from the navigation which seems to be handled in `Module::renderNavigation`

**Comment by fritzmg** [comment]
I know, I just meant in principle.

**Comment by leofeyer** [comment]
@contao/developers /cc

**Comment by aschempp** [comment]
Liesse sich doch über den `generatePage` Hook lösen?

**Comment by bennyborn** [comment]
@aschempp Leider nicht. Es geht ja nicht nur darum die Seite nicht zugänglich zu machen, das ginge sicherlich schon über `generatePage` oder andere Hooks, sondern auch darum das die Seite garnicht erst in der Navigation auftaucht. Wäre ja unschick dem User etwas zu zeigen was er ohnehin nicht sehen darf :)

**Comment by fritzmg** [comment]
Further usage possibilites for `Controller::isVisibleElement`:

https://github.com/contao/core/blob/3.5.15/system/modules/core/modules/Module.php#L386:
```php
if (!$objSubpage->protected || BE_USER_LOGGED_IN || (is_array($_groups) && count(array_intersect($_groups, $groups))) || $this->showProtected || ($this instanceof \ModuleSitemap && $objSubpage->sitemap == 'map_always'))
```
»
```php
if (\Controller::isVisibleElement($objSubpage) || $this->showProtected || ($this instanceof \ModuleSitemap && $objSubpage->sitemap == 'map_always'))
```

https://github.com/contao/core/blob/3.5.15/system/modules/core/modules/ModuleBooknav.php#L184:
```php
if (!$objPage->protected || BE_USER_LOGGED_IN || (is_array($_groups) && count(array_intersect($groups, $_groups))) || $this->showProtected)
```
»
```php
if (\Controller::isVisibleElement($objPage) || $this->showProtected)
```

**Comment by Toflar** [comment]
Wir sehen die Notwendigkeit dieses Features. Neue Hooks in der 3.5 kommen aber nicht in Frage und eine Anpassung des `isVisibleElement` ist ein BC Break. Ausserdem müsste dieser Hook ja auch in `Module::renderNavigation()` aufgerufen werden.

In Contao 4 wollen wir ein neues Berechtigungssystem einführen, das mit Symfony Security Voters funktioniert, da werden wir das Anliegen berücksichtigen.

Jetzt musst du leider noch mit dem `generatePage` Hook und einem eigenen `nav_`-Template (bzw. Versuch mal den `parseTemplate`-Hook, damit kriegst du's sicher auch hin) Vorlieb nehmen.

**Comment by fritzmg** [comment]
> und eine Anpassung des isVisibleElement ist ein BC Break

Es müsste ja gar nichts geändert werden, oder?

**Comment by Toflar** [comment]
Doch, er kriegt neuerdings auch Elemente vom Typ `PageModel` und um das initiale Problem lösen zu können müsste der Hook ja auch in `Module::renderNavigation()` aufgerufen werden, was nochmal ein anderes Verhalten verursacht.
