### ISSUE TITLE
get parameters fill up page cache

### ISSUE THREAD

**Issue by fritzmg** [contao/core#8410]
When the page cache is activated in your Contao site, there will be a cached page for each query string.

Thus, if you bombard a website with random query strings, the page cache will fill up for each of these query strings (for each page) (also the database will be spammed with system log entries).

e.g. for `example.org` there will a cached page `/* example.org/empty.en */`

for `example.org/?foo=1` there will be a cached page `/* example.org/?foo=1 */`

for `example.org/?1mCyAE=0yEASc` there will be a cached page `/* example.org/?1mCyAE=0yEASc */`

etc.

Maybe pages with unused GET parameters should not be cached (if that is possible?).

See also https://community.contao.org/de/showthread.php?63241-IP-l%E4sst-sich-nicht-blockieren&p=414607

**Comment by fritzmg** [comment]
The same applies for not found pages. Any URL for which no page exists will also be saved in the cache (with the content of the defined 404 page). Thus if a bot bombards the website with non-sensical URLs in general, the page cache will also be filled up with unnecessary cache files.

**Comment by leofeyer** [comment]
I have fixed the 404 and 403 pages in ddceb0f76b628b2ab841202e96cad47b24052dc4.

@contao/developers What about the other issue? It does not seem wrong to me to cache pages with a query string. WDYT?

**Comment by aschempp** [comment]
I don't think there's much we can do. Varying query parameters are totally valid. I'm pretty sure a full-fledged shared cache like Varnish or a CDN would behave exactly the same.

**Comment by leofeyer** [comment]
>  I'm pretty sure a full-fledged shared cache like Varnish or a CDN would behave exactly the same.

Me too.

**Comment by Toflar** [comment]
> @contao/developers What about the other issue? It does not seem wrong to me to cache pages with a query string. WDYT?

Of course not. Any parameter added is a valid unique cache key. Symfony does the very same [here](https://github.com/symfony/http-kernel/blob/master/HttpCache/Store.php#L422) although it is improved because they normalize (filter useless stuff and especially sort) the query string first so that e.g. `page=2&foobar=15` gets the same cache key as `foobar=15&page=2`.

However, I don't think we should adapt this in Contao 3.5. We'll automatically benefit from the SF2 code in Contao 4.3 once we merged my ESI PR.

**Comment by leofeyer** [comment]
Actually, I even think we should revert the changes from ddceb0f76b628b2ab841202e96cad47b24052dc4. Why should a 404 page not be cached? It will speed things up even if it is an error page.

**Comment by fritzmg** [comment]
True, but couldn't you calculate the cache key differently for a 404 page, so that only one gets generated?
