### ISSUE TITLE
Datepicker ersetzt nicht alle Platzhalter

### ISSUE THREAD

**Issue by Samson1964** [contao/core#8411]
Der Datepicker hat Probleme den Platzhalter n (Monat einstellig) zu ersetzen. Stehen die Datumseinstellungen auf z.B. "d.n.Y" steht beim Öffnen eines Nachrichtenteasers korrekt z.B. "17.7.2016" da. Nach Ändern des Datums über den Datepicker, steht statt der "7" ein "n" im Eingabefeld.

Jeweils Contao 3.5.12, siehe https://community.contao.org/de/showthread.php?63248-Datum-Uhrzeit-Felder

**Comment by leofeyer** [comment]
Lässt sich das in der Onlinedemo irgendwie reproduzieren?

**Comment by ADoebeling** [comment]
Jap, lässt auf demo.contao.org reproduzieren:

[![YT Video](https://img.youtube.com/vi/-dU4O0w5R3o/0.jpg)](https://www.youtube.com/watch?v=-dU4O0w5R3o)

**Comment by leofeyer** [comment]
@ADoebeling Alles klar, vielen Dank. 😄

**Comment by leofeyer** [comment]
Behoben in 094e809e88a511f1e951565c0fd63eccdf7d1bb3. Stellte sich als MooTools-Bug heraus.

**Comment by Toflar** [comment]
Bitte der Vollständigkeit halber noch das Issue von Mootools More verlinken.

**Comment by leofeyer** [comment]
Welches Issue?

**Comment by Toflar** [comment]
Na du wirst ja wohl den Bug im Datepicker bei MooTools gemeldet haben?

**Comment by leofeyer** [comment]
Natürlich nicht. MooTools wird doch gar nicht mehr weiterentwickelt.

**Comment by Toflar** [comment]
???

**Comment by fritzmg** [comment]
Well, there is MooTools `1.6.0` at least, which was released this year. Contao still uses `1.5.1`.

**Comment by leofeyer** [comment]
Feel free to create the ticket yourself if it is important to you.

**Comment by leofeyer** [comment]
I have updated MooTools to the latest bugfix version in 7b86fcfbaeaa6b62bae1f262ddb54e51b72bd042.

**Comment by Aybee** [comment]
Thank you.

Warum kein Update auf die letzte stable 1.6.0? http://mootools.net/core/builder

Wegen der schlechten Erfahrungen, dass dies zu mehreren Folge-Tickets führen könnte?

**Comment by leofeyer** [comment]
The Contao LTS version does not get new features and MooTools 1.6.0 is a feature release.

**Comment by fritzmg** [comment]
> The Contao LTS version does not get new features and MooTools 1.6.0 is a feature release.

During Contao 3.5, MediaElement.js was frequently updated with feature releases, starting from 2.16.4 and now it's at 2.21.2.

**Comment by leofeyer** [comment]
That was necessary because they fixed a security vulnerability in one of the latest versions. Also, MediaElement.js is much more trusted to adhere to semantic versioning than MooTools. MooTools has released breaking changes in minor and bugfix versions more than once in the past.

**Comment by fritzmg** [comment]
The version was bumped two times:

* https://github.com/contao/core/commit/3b099ea9a1b8240e4144e927137b3b6a76de3ef6
* https://github.com/contao/core/commit/4d42a56531c82598436d5102fac94721ea99ad49



> Also, MediaElement.js is much more trusted to adhere to semantic versioning than MooTools. MooTools has released breaking changes in minor and bugfix versions more than once in the past.

I see.
