### ISSUE TITLE
 2 Factor Authentication / Zwei Wege Authentifizierung 

### ISSUE THREAD

**Issue by ways2web** [contao/core#8413]
2 Factor Authentication with Google Authenticator etc. ?  (exampel: Google Authenticator)

Zwei Wege Authentifizierung fürs Backend-Login (Bsp: Google Authenticator)

(backend feature)

**Comment by ADoebeling** [comment]
Finde ich gut, gerade aufgrund der Anzahl der Möglichen einer 2FA-Implementationen erscheint mir die Funktion jedoch in einer Extension besser aufgehoben?

**Comment by aschempp** [comment]
Eine entsprechende Umsetzung in Contao 4 hängt an der vollständigen Integration von Symfony Security (siehe auch https://github.com/contao/core-bundle/issues/122). Danach liesse sich das vermutlich relativ leicht dank vorhandenen Symfony-Bundles lösen (z.B. https://packagist.org/packages/scheb/two-factor-bundle).

**Comment by padarom** [comment]
Falls noch jemand nach solch einem Bundle sucht, wir haben gerade unser Bundle veröffentlicht, mit dem Backend-Nutzer Zwei-Faktor Authentifizierung über TOTP (also z.B. Google Authenticator) aktivieren können:

https://github.com/DieSchittigs/contao-tfa-bundle

**Comment by leofeyer** [comment]
This has been implemented in Contao 4.9.
