### ISSUE TITLE
Backend: Fehler beim Zuweisen eines Bildes. Im Modus OverrideAll.

### ISSUE THREAD

**Issue by markocupic** [contao/core#8414]
Möchte man z.B. mehreren Events gleichzeitig ein Bild zuordnen (im Modus Überschreiben), bleibt das Modal-Fenster geöffnet. Das Bild kann nicht zugeordnet werden und in der Konsole erscheint folgende Fehlermeldung:

HTTP400: FEHLERHAFTE ANFORDERUNG: Die Anforderung konnte vom Server aufgrund ungültiger Syntax nicht verarbeitet werden.
(XHR): POST - http://xxx-xxxxx.ch/contao/main.php...

Der Fehler tritt auf allen meinen Installationen und auf der Demoseite auf. Getestet mit Chrome und IEXPLORER.

**Comment by ADoebeling** [comment]
Konnte ich in der Contao-Demo soeben reproduzieren.

[![Screencast](http://i.makeagif.com/media/7-21-2016/K95pxY.gif)](https://www.youtube.com/watch?v=Kg5CZZ2jwsg)

**Comment by leofeyer** [comment]
Behoben in 14ab484f6646b22b6844c852e15ee6cc68417c72.
