### ISSUE TITLE
UrlGenerator ignores addLanguageToUrl

### ISSUE THREAD

**Issue by micha-nerdlichter** [contao/core#8415]
I want to add the language to my folder URLs like ```mypage.de/en/company/about.html``` In [Frontend.php](https://github.com/contao/core-bundle/blob/805a97005f01f6e4686a2d8b10a99d628a693f4d/src/Resources/contao/classes/Frontend.php#L101) I found the ```addLanguageToUrl``` setting. By enabling this contao can handle language URLs without adding it to the page aliases. This is a very nice feature.

But the setting is ignored by the ```UrlGenerator```, so the navigation module doesn't add the language to the links. I fixed this in a ```generateFrontendUrl``` hook, but this seems like a rather dirty hack:
```php
public function generateFrontendUrl($arrRow, $strParams, $strUrl) {
    $lang = $arrRow['language'];
    if (\Config::get('addLanguageToUrl') && substr($strUrl, 0 , strlen($lang)) != $lang) {
        $strUrl = $lang . '/' . $strUrl;
    }
    return $strUrl;
}
```
Is there a proper way to do this or is the  ```addLanguageToUrl``` feature just not finished yet?

**Comment by leofeyer** [comment]
You need to set `prepend_locale` to `true` in your `app/config/parameters.yml` file.

**Comment by micha-nerdlichter** [comment]
Hm, that adds the _locale=de as  GET parameter: ```mypage.de/company/about.html?_locale=en``` But I want ```mypage.de/en/company/about.html```. The ```addLanguageToUrl``` setting does exactly that if I'm not mistaken. What I don't understand is why this setting is used by ```tl_page.php```, by ```Frontend.php``` but not by ```UrlGenerator.php```

**Comment by bytehead** [comment]
check if you have the most actual version (`4.2.1`) of the `contao/core-bundle`.

**Comment by micha-nerdlichter** [comment]
according to my ```composer.lock``` yes [I do](http://i.imgur.com/ksAmL7d.png)

**Comment by fritzmg** [comment]
Hm, can't confirm that. Setting `prepend_locale` to `true` results in the expected behaviour on my installation. i.e. you'll get URLs like `example.org/en/foo.html`.

**Comment by micha-nerdlichter** [comment]
@bytehead If you are referencing to [#510](https://github.com/contao/core-bundle/issues/510) this is not the problem. In ```4.2.1``` I don't have the ```_locale``` param as long as I don't enable the ```prepend_locale``` setting.

**Comment by micha-nerdlichter** [comment]
I'm using @aschempp's [Changlanguage](https://github.com/terminal42/contao-changelanguage) plugin. So propabely this is messing up the URL handling? I'll do some further investigating...

**Comment by aschempp** [comment]
You should try the `dev-develop` branch of ChangeLanguage (upcoming v3).

**Comment by micha-nerdlichter** [comment]
Not that easy, added ```"terminal42/contao-changelanguage": "dev-develop as 2.2.11"``` to the ```composer.json``` but this conflicts with "terminal42/contao-newslanguage". In 2.2.11 this worked... are you planning on updating newslanguage too?

**Comment by fritzmg** [comment]
That functionality is already integrated in v3, so you don't need that :)

**Comment by aschempp** [comment]
For changelanguage 3 you must remove newslanguage, thats why there's the conflict. The newslanguage functionality is now included.
