### ISSUE TITLE
Protected Pages - Showing Event, Faq, News (Auto items) in XML Sitemaps

### ISSUE THREAD

**Issue by caleoroco** [contao/core#8416]
Hi
I've come across this as an issue today. V3.5.14

When you have events, news, faq or anything else with "items" on a page with list and automatic reader and the page is protected to user groups the path to items are shown in the xml sitemap

**Comment by leofeyer** [comment]
How do we reproduce this in the online demo?

**Comment by caleoroco** [comment]
recreated on demo site for you.

Sample Protected Page (protected)
-  sub page of protected page (not protected directly but should pick up access control from parent page

Archive on sub page with reader

**Comment by caleoroco** [comment]
screenshot of the offending item in xml sitemap 

-the protected page is fine and doesn't show, but any sub-pages with an auto reader archive/list on them display the page and paths to items.  So it seems that the access control isn;t being passed down on these items or it is being overridden by the module

![image](https://cloud.githubusercontent.com/assets/1584853/17153864/83efb8b8-5376-11e6-886f-a48bfe90a90e.png)

**Comment by ADoebeling** [comment]
I'm able to confirm this bug, I just reproduced it on demo.contao.org.
[![Gif](https://j.gifs.com/QWl7RM.gif)](https://www.youtube.com/watch?v=jiJAg3M4Wes)
https://www.youtube.com/watch?v=jiJAg3M4Wes

**Comment by asaage** [comment]
To hide a page in the sitemap use "Expert settings" of the (reader)page and select "Show never".
I bet the protected- and the sitemap properties have allways been totally unrelated.

**Comment by caleoroco** [comment]
@asaage That's right you can do that, however, the protection should be cascading down to all sub-pages

**Comment by fritzmg** [comment]
Indeed, pages do not inherit the __Show in sitemap__ setting, you would have to manually set that option for every protected page. Maybe protected pages shouldn't be in the sitemap by default, but I don't know if there is a use-case where you do want them to be in the sitemap.

**Comment by caleoroco** [comment]
subpages of protected items don't show in the sitemap, the issue only relates to pages that have a listing/reader combo on them so i'm more inclined to think it's an issue with how the reader/listing modules invoke the sitemap

**Comment by fritzmg** [comment]
Oh, sorry, I misunderstood the problem. Yeah, I think you are right.

**Comment by leofeyer** [comment]
Fixed in 6e8a7fa802575c8e3c2b881a2ab3b7194a8299d6.
