### ISSUE TITLE
Formulargenerator: Keine Auswahl für Modul Template

### ISSUE THREAD

**Issue by Rotbarsch** [contao/core#8418]
Hallo,

wir arbeiten aktuell mit Contao 3.5.14. Ein bisheriges Projekt wurde mit der Version 3.5.6 umgesetzt, wo regen Gebrauch von der Funktion gemacht wurde einem Modul vom Typ "Formular" ein Modultemplate zuzuweisen. In der Version 3.5.14 fehlt dieses Auswahlfeld im Backend komplett.

**Comment by frontendschlampe** [comment]
Das gab es noch in keiner Version, dass man das Formulartemplate anpassen konnte. Das muss über eine Erweiterung geschehen sein. Wir haben das ebenfalls über eine Erweiterung gelöst!

**Comment by Rotbarsch** [comment]
Anbei ein Screenshot von der angesprochenen Version 3.5.6. Ich wüsste gerne welche Erweiterung sie verwendet haben?

![image](https://cloud.githubusercontent.com/assets/11535500/17100897/a08eed78-5271-11e6-90c1-30df9db89287.png)

**Comment by frontendschlampe** [comment]
Puuh ... das ist keine Core-Funktion ... wir benutzen https://github.com/hofff/contao-formtools

**Comment by Rotbarsch** [comment]
Nach erfolgreicher Installation der Erweiterung können wir nun eigene Templates festlegen. Leider werden alle Felder immer noch als ein großer HTML String ausgegeben. Kann man die Felder einzeln als Objekt/Array erhalten?

**Comment by bezin** [comment]
Dafür könnte es sich lohnen, einen Blick auf die [Form-Klasse von Contao Haste](https://github.com/codefog/contao-haste/blob/master/docs/Form/Form.md) zu werfen und das Formular in einer eigenen Extension zu implementieren. Mit dem Core ist das meines Wissens nicht möglich.
