### ISSUE TITLE
Autofocus on cssId in tl_content edit view

### ISSUE THREAD

**Issue by bezin** [contao/core#8419]
Hey Guys, 

in tl_content edit view (with tl_article as the parent), the cssId field gets the autofocus attribute, if the expert settings panel is open. If you want to edit a content element, you sometimes have to scroll all the way up.

You may reproduce this in the online demo by opening a random article and edit any content element inside. If the expert settings panel is open, cssId will be autofocused.

I tested this with Chrome 51 on Windows 10. 

Best
benzin

**Comment by aschempp** [comment]
Is this reproduceable in the online demo? The edit form should autofocus the first input field. Maybe you set eval => autofocus ?

**Comment by bezin** [comment]
As I wrote, it is reproducable in the online demo, but I'll be more specific :)
 
1. Go to the "Home" article on the frontpage.
2. Edit the first content element "About this demo"
> If the expert settings panel is closed, the headline field will be focused. 
> If the expert settings panel is open, the cssId field will be focused. 

Do prove, do the following: 
3. Open the expert settings panel. Just toggle it. 
4. Go back.
5. Edit the same content element again.

The cssId input will be focused – but the headline input should have been focused according to the rule you mentioned.

**Comment by fritzmg** [comment]
I cannot reproduce the behaviour, at least not under Windows 7 x64 with FireFox 32bit 47.0.1. __But__ the actual HTML output does indeed assign the `autofocus` attribute to the `ctrl_cssID_0` input field in the online demo:
```html
<input type="text" name="cssID[]" id="ctrl_cssID_0" class="tl_text_2" value="" autofocus onfocus="Backend.getScrollOffset()">
```

**Comment by bezin** [comment]
I did some browser tests (all on Windows 10 x64, if not stated otherwise): 
The issue occurs as described in Chrome 51, IE 11, Edge, Opera 38.
It works as expected in Firefox 47, as well as in Safari 8 on MacOSX 10.10.

**Comment by fritzmg** [comment]
The problem happens here: https://github.com/contao/core/blob/3.5.15/system/modules/core/drivers/DC_Table.php#L1917
```php
// Autofocus the first field
if ($blnIsFirst && $GLOBALS['TL_DCA'][$this->strTable]['fields'][$this->strField]['inputType'] == 'text')
{
	echo 'foo';
	$GLOBALS['TL_DCA'][$this->strTable]['fields'][$this->strField]['eval']['autofocus'] = 'autofocus';
	$blnIsFirst = false;
}
```
The first part of the condition, `$blnIsFirst`, is always `true`, as long as the "first text field" has not been found. The second part will be `true` when the `inputType` of the field is `text`. One would assume that the first "text" field is actually the headline field - __however__ the input type of the headline field is actually `inputUnit`, thus this condition will not be true for the `headline` field for example.

This situation continues with all the other fields. The _first_ field that matches this condition will be the `cssID` field. Its `inputType` is `text`. Thus the first `<input>` field of the `cssID` field receives the `autofocus` parameter by `DC_Table`.

The condition should probably be changed to something like this:
```php
// Autofocus the first field
if ($blnIsFirst && in_array($GLOBALS['TL_DCA'][$this->strTable]['fields'][$this->strField]['inputType'], array('text', 'inputUnit')))
{
	…
}
```

**Comment by leofeyer** [comment]
Are `text` and `inputUnit` the only two autofocusable fields?

**Comment by aschempp** [comment]
I don't think so, we can very well focus a textarea/tinyMCE if that's the first field…
Maybe the focussing should be done with Javascript?

**Comment by leofeyer** [comment]
We used to do it with JavaScript but there were issues, too, so we switched to using the `autofocus` attribute (which exists for this exact reason). We just have to define a list of possible autofocus fields.

**Comment by leofeyer** [comment]
Why? If you focus via JavaScript, you also have to provide a list of fields, don't you?

**Comment by Toflar** [comment]
No, you check for the first focusable input field which is not of type hidden (and maybe more conditions) within the edit mask. Contao provides the possibility to add custom widgets and they might consist of input fields so this list would have to be extendable and we end up with some stupid `$GLOBALS` registry again. I'd prefer to have a JS solution that just works out of the box without forcing people to think about this when they develop a widget.

**Comment by aschempp** [comment]
Totally agree with @Toflar

**Comment by leofeyer** [comment]
> you check for the first focusable input field which is not of type hidden (and maybe more conditions) 

Which is exactly "providing a list of possible fields". 😄 

The only advantage of the JS approach is that developers do not have to take care in their custom widgets. However, this is a bug in Contao anyway, because the `autofocus` attribute is set in the `Widget` class, even though not every widget is autofocusable.

**Comment by aschempp** [comment]
> > you check for the first focusable input field which is not of type hidden (and maybe more conditions)
> Which is exactly "providing a list of possible fields". 😄

Not at all. `$('#form_id')[0].fields` or similar will give you the real input fields, whereas each widget can have multiple and must support `autofocus`.

**Comment by leofeyer** [comment]
We cannot use `$('#form_id')[0].fields` though, because this will also include hidden fields, disabled fields and fields that have been made invisible using the `.invisible` class. Also, it will try to focus the textarea that has been converted by TinyMCE.

**Comment by leofeyer** [comment]
Here are some of the related issues you should read: #4297, #5774, #8281

**Comment by Toflar** [comment]
4297: Is unrelated (not changing anything from the behavior perspective, just re-adding a missing feature).
5774: Is just something we should have ignored because it is simply wrong. Autofocus must focus the first input and if this is an alias field in his case then that's correct.
8281: Would not happen if you do it by JS.

**Comment by leofeyer** [comment]
Ok, you know what, just create a PR with the "right" solution and I'll merge it.

**Comment by Toflar** [comment]
Done.

**Comment by leofeyer** [comment]
See #8427.
