### ISSUE TITLE
Bug in file RepositoryManager.php?

### ISSUE THREAD

**Issue by AppChecker** [contao/core#8422]
Hello.

In method [RepositoryManager::upgrade (RepositoryManager.php line 378)](https://github.com/contao/core/blob/436f0cc99089756e7a3d2e0aa53155b1823942d6/system/modules/repository/classes/RepositoryManager.php#L378):
`($ext->version != $ext->upd_version || $ext->upd_build != $ext->upd_build)`

$ext->upd_build is compared with itself.

May be it should be:
`($ext->version != $ext->upd_version || $ext->build != $ext->upd_build)`

This possible defect found by [AppChecker](https://cnpo.ru/en/solutions/appchecker.php)

**Comment by discordier** [comment]
Nice catch.

This means "build updates" will not get correctly handled (unless they have a version bump)...
They are shown in the correct state in the list, see line [1308](https://github.com/contao/core/blob/436f0cc99089756e7a3d2e0aa53155b1823942d6/system/modules/repository/classes/RepositoryManager.php#L1308).
Definitely worth fixing though.

**Comment by discordier** [comment]
Update: This only affects the display string of the current action.
It will incorrectly show "validating extension xy" instead of "upgrading extension xy".
It will pull the files correctly though.

**Comment by leofeyer** [comment]
Fixed in 8b0089617e35d3e5510d9c64c14f4531e848098c.
