### ISSUE TITLE
soft hyphens and generateAlias

### ISSUE THREAD

**Issue by micha-nerdlichter** [contao/core#8423]
Following the arguments in #2709 shouldn't ```generateAlias``` be using the shy-free title? I see no sense in replacing the shy entities with ```-``` e.g. the page title ```Schiff[-]fahrts[-]markt[-]bericht``` generates the alias ```schiff-fahrts-markt-bericht```.

**Comment by leofeyer** [comment]
It actually does not on my system. Can this be reproduced in the online demo?

**Comment by Toflar** [comment]
I read the source code and it should really not happen. Moreover, I couldn't reproduce it in the latest 3.5 version which you should obviously be using before reporting a bug :)

**Comment by ADoebeling** [comment]
I also can't reproduce this issue.

![image](https://cloud.githubusercontent.com/assets/10674780/17343830/eae947a8-58ff-11e6-8c1a-a043b17ac295.png)

**Comment by micha-nerdlichter** [comment]
Oh, I tried this in Contao ```4.2.1``` and started this issue in ```3.5``` Sorry, my bad. I'll check this in ```3.5```. But shouldn't this be fixed in ```4.2.1``` too?
