### ISSUE TITLE
Newsletter - Unterstützung von SimpleTokens in Testsendung

### ISSUE THREAD

**Issue by CodeAlDente** [contao/core#8426]
Aktuell werden keine SimpleTokens bei der Testsendung unterstützt, das wäre aber sehr nützlich. Vielleicht mit der Option, wie bei der Generierung vom Suchindex, die Daten eines bestimmten Mitglieds beim Versand zu übernehmen?

Empfänger wäre dann natürlich nicht das ausgewählte Mitglied sondern entweder eine zuvor festgelegte E-Mail Adresse oder der der Administrator der Seite.

![1470184102](https://cloud.githubusercontent.com/assets/10899559/17349922/35dcd6ae-5922-11e6-9872-bea44a6b8274.png)

**OT:** Werden SimpleTokens aus dem mail_ - Template eigentlich korrekt übernommen? Oder sollte ich im Template auf SimpleTokens verzichten? Ich würde nämlich gerne etwas wie "Sie sind mit der E-Mail Adresse ##email## registriert" im Footer stehen haben.

**Comment by leofeyer** [comment]
Ich schließe das Ticket aufgrund mangelnden Interesses.
