### ISSUE TITLE
ReOpen #5095, Templates fehlen in der Auswahl, bzw. Fatal Error im FE

### ISSUE THREAD

**Issue by BugBuster1701** [contao/core#8428]
Die Wegnahme der Filterung bei getTemplateGroup in #5095 nach dem Theme führt dazu, dass bei gleichnamigen Templates in mehreren angelegten Themes nur das letzte gefundene angezeigt wird.

Das verwirrt total, wenn ich in Theme EINS beispielsweise im Layout nur ein fe_page Template sehe, aber das von Theme ZWEI ist, Anzeige: fe_page (Theme ZWEI)

Nenne ich das Template im Theme ZWEI um, bspw. fe_page_zwei, und in Theme EINS gibt es keine angepasste fe_page, dann sehe ich im Layout von Theme EINS die fe_page (core) und die fe_page_zwei (Theme ZWEI). 
Wählt man die zweite aus versehen aus, kommt verständlicherweise im FE ein Fatal Error.

Ausführlicher inkl. Angaben zur Nachstellung im [Forum](https://community.contao.org/de/showthread.php?63454-Bug-im-Layout-Seitentemplate-bei-mehreren-Themes)

**Comment by leofeyer** [comment]
Aber wenn wir die Änderung rückgängig machten, hätten wir ja wieder das Problem aus #5095, oder?

**Comment by BugBuster1701** [comment]
Einfach gesagt, dann muss man eben eine gemeinsame Lösung finden.
z.b. suche alle Templates so wie jetzt nur filtere anschließend die raus die aus "fremden" Themes kommen, **wenn** man das Theme kennt.
Zumindest bei der Theme->Layout Definition sollte das doch gehen.
Wenn z.B. bei Nachrichten das Theme nicht bekannt ist, dann so suchen wie bisher.

**Comment by fritzmg** [comment]
> Wenn z.B. bei Nachrichten das Theme nicht bekannt ist, dann so suchen wie bisher.

Tritt dann aber dort nicht potentiell das selbe Problem auf?

**Comment by BugBuster1701** [comment]
Muss ich mal heute Abend testen. Wenn dort auch nur das zuletzt gefundene angezeigt werden sollte (bei gleichen Template Namen), wäre das auch ein Fehler.

**Comment by fritzmg** [comment]
Ich denke es sollten einfach _immer_ __alle__ Templates angezeigt werden. Also tatsächlich alle, nicht nur das letzte der gleichnamigen Templates. Sodass man dann eine Liste hat wie zB:
```
fe_page (Theme 1)
fe_page (Theme 2)
…
```

**Comment by BugBuster1701** [comment]
Das wäre zumindest eine Verbesserung, auch wenn ich im Layout von Theme 1 keine Templates von Theme 2 brauche. Aber so könnte man wenigstens das richtige auswählen.

**Comment by fritzmg** [comment]
Jap. Allerdings ist es dann auch wieder irreführend, wenn man irgendwo ein Template auswählt, dass einem anderen Theme zugewiesen ist, aber dann das Template aus dem eigentlichen Theme verwendet wird... naja.

**Comment by tabcontao** [comment]
Kann man es nicht so machen, dass statt dem Theme(verzeichnis) neben dem Templatenamen einfach nur "Theme" nach dem Templatenamen angezeigt wird. Und im FE wird dann einfach das Template vom aktuellen Theme genommen. Sollte es das ausgewählte Template im aktuellen Theme dann nicht geben, dann nimmt man eben das Default-Template - oder gibt weiterhin die Fehlermeldung aus, damit man den Fehler auch bemerkt. Oder man nimmt dann eben tatsächlich das Template aus dem anderen Theme.

Wichtig finde ich hauptsächlich, dass ich das Template im Frontend angewendet bekomme, das ich auch haben will, was ja größtenteils schon zu funktionieren scheint. Und dass die Anzeige im Backend so wenig verwirrend ist wie möglich.

**Comment by BugBuster1701** [comment]
> einfach nur "Theme" nach dem Templatenamen angezeigt wird.
Bloß nicht, wie soll ich dann gleichnamige Unterscheiden?

> Oder man nimmt dann eben tatsächlich das Template aus dem anderen Theme.
Dann mancht die ganze Trennung kein Sinn mehr, also nein.

Die Frontendsuche des richtigen Templates arbeitet ja richtig. Nur was im Backend zur Auswahl steht ist manchmal verwirrend oder sogar falsch.

Einziger halbwegs nutzbarer Workaround derzeit ist es, die veränderten Templates immer umzubenennen und auch bei mehreren Themes unterschiedliche Namen für die Templates  zu verwenden, bis auf den Prefix natürlich. So bekommt man dadurch wenigstens alle gefundenen aufgelistet und kann dann logisch denkend das richtige Template auswählen.

**Comment by tabcontao** [comment]
Gleichnamige Templates müsstest du ja dann nicht unterscheiden, weil dann sowieso im Frontend immer das zum jeweiligen Layout->Theme passende genommen würde. Spannend wäre ja nur die Frage, was passiert, wenn es dieses Template im aktuellen Theme nicht gibt. Ein "richtiges" Template gibt es laut dem eben  manchmal gar nicht. Ansonsten könnte man an dieser Stelle einfach feststellen, dass immer nur "passende" Templates angeboten werden sollten. Wenn ICH immer entscheiden könnte, zu welchem Theme das Template gehören muss, dann könnte das Contao doch mit Sicherheit auch und sollte es dann eben auch tun.

**Comment by BugBuster1701** [comment]
> Wenn ICH immer entscheiden könnte, zu welchem Theme das Template gehören muss, dann könnte das Contao doch mit Sicherheit auch und sollte es dann eben auch tun.

Das klappt aber eben nur, wenn das Theme bekannt ist. Unter Themes->Layout bspw. ist das der Fall.
Aber das ursprüngliche Ticket bezieht sich auf Fälle wo das eben nicht der Fall ist. Daher die Komplexität es in beiden Fällen recht zu machen und meine Idee, wenn Theme bekannt, dann alle suchen und falsche rausfiltern, ansonsten alle anzeigen.

**Comment by leofeyer** [comment]
Ich hab mal versucht, das nachzustellen, konnte aber keinen Fehler feststellen.

<img width="750" alt="" src="https://cloud.githubusercontent.com/assets/1192057/20350160/07c742f6-ac0e-11e6-89ef-1ecb709ddf27.png">

Das Template `fe_page` gibt es einmal global und in jedem Theme-Ordner.

<img width="750" alt="" src="https://cloud.githubusercontent.com/assets/1192057/20350177/1ad4d28c-ac0e-11e6-88a7-c80f624b7935.png">

Jeder Theme-Ordner ist mit einem Theme verknüpft.

<img width="746" alt="" src="https://cloud.githubusercontent.com/assets/1192057/20350182/23f7c540-ac0e-11e6-876b-f9a924a07122.png">

Im Seitenlayout aus dem ersten Theme werden mir auch alle drei Templates angezeigt.

**Comment by BugBuster1701** [comment]
Äh, da steht doch nun "fe_page (global, Contao Official Demo, Test 1)
Und welche ist das nun? Das sind doch genau 3 mögliche die hier in einer Zeile auftauchen. Genau das ist eins meiner Probleme.
Bei mir wird aber genau nur diese eine in der Auswahl angeboten.

> Im Seitenlayout aus dem ersten Theme werden mir alle drei Templates angezeigt.

Und wenn nur eine fe_page.html5 in /templates/test1 liegt, keine in /templates und auch keine in /templates/contaodemo, dann wird  mir in der jedem Layout innerhalb vom  Contao Official Demo nur diese aus test1 angeboten und ich kann nicht sagen, ich will keine eigene.
Hier mal meine Screens, bei mir heißt nur das zweite Verzeichnis anders.
![screen-8428-1](https://cloud.githubusercontent.com/assets/1218809/20371157/0b9ce25a-ac63-11e6-9bd1-0ff58ea7ba6f.png)
![screen-8428-2](https://cloud.githubusercontent.com/assets/1218809/20371159/10c54074-ac63-11e6-8c88-bce8b795ed00.png)

**Comment by leofeyer** [comment]
> Und welche ist das nun? Das sind doch genau 3 mögliche die hier in einer Zeile auftauchen. Genau das ist eins meiner Probleme.

Wieso "welches ist das nun"? Es ist das Template `fe_page`. Woher das im Endeffekt genommen wird, weiß Contao erst, wenn es die Frontend-Seite baut. Es zeigt Dir daher alle Stellen an, an denen es ein `fe_page`-Template gibt.

**Comment by fritzmg** [comment]
Naja, aber wenn es ein globales `fe_page` Template gibt und eins aus einem Theme Ordner, dann möchte man ja vielleicht dediziert das globale Template auswählen? Ich denke das ist, was BugBuster meint?

Wobei man hier wohl einfach die eigenen `fe_page` Template umbenennen muss, damit diese auswählbar sind.

**Comment by leofeyer** [comment]
> Naja, aber wenn es ein globales `fe_page` Template gibt und eins aus einem Theme Ordner, dann möchte man ja vielleicht dediziert das globale Template auswählen?

Das geht nicht (und ging auch noch nie).

**Comment by BugBuster1701** [comment]
Das Problem ist auch, ich kann es nicht abwählen.
Ich lege im zweiten Theme ein fe_page Template an weil ich es dort verwenden möchte.
Editiere ich nun im ersten Theme ein Layout und speichere es, wird automatisch das fe_page vom zweiten Theme eingetragen. Und das führt dann im Frontend zum Error.

**Comment by fritzmg** [comment]
Hmm.. konnte das bei mir nicht reproduzieren. Macht auch irgendwie keinen Sinn, denn im Seitenlayout wird ja nur der Name des Templates gespeichert und nicht der volle Pfad. Welches Template zutrifft, ergibt sich einfach daraus, zu welchem Theme das Seitenlayout gehört.

Passiert das bei dir auch im abgesicherten Modus?

**Comment by leofeyer** [comment]
> Hmm.. konnte das bei mir nicht reproduzieren. Macht auch irgendwie keinen Sinn, denn im Seitenlayout wird ja nur der Name des Templates gespeichert und nicht der volle Pfad. Welches Template zutrifft, ergibt sich einfach daraus, zu welchem Theme das Seitenlayout gehört.

Eben.

**Comment by BugBuster1701** [comment]
Äh ja, da habe ich nicht genau das getestet, was ich später schrieb. Das funktioniert.
Das Problem wie im ersten Beitrag hier bleibt. Nenne ich das Template für das zweite Theme um, kann ich dieses im Theme eins auswählen. Und das funktioniert dann natürlich nicht.
Ja es steht in Klammern das Verzeichnis dahinter, aber ob jeder sofort drauf kommt, für welches Theme das Verzeichnis steht, bezweifle ich. Ich selber hatte mich darin schon geirrt.

**Comment by BugBuster1701** [comment]
Ach mist, Fehler von mir. Da steht doch der Theme Name dahinter. Aber man kann es eben auswählen.
Ich hatte für Entwicklungstests mehrere fast gleichnamige Theme Namen. Daher kam es dann zur falschen Auswahl.

**Comment by leofeyer** [comment]
Ist hier noch etwas zu tun oder kann das Ticket geschlossen werden?

**Comment by BugBuster1701** [comment]
Solange man die Templates umbenennt ist alles OK, aber wenn man die beim Namen lässt...
Habe gerade noch mal probiert. Contao Demo, dort ein zweites Theme angelegt mit eigenem Template Ordner, darin eine fe_page angelegt.
Wenn ich dann ein Layout der Online Demo editiere und einfach wieder abspeichere, ist, laut Anzeige im Formular, die fe_page vom zweiten Theme gespeichert "fe_page (theme zwei)", die lässt sich auch wie gesagt nicht abwählen.
Im Frontend wird aber das richtige geladen.
Lege ich in der Contao Demo auch noch ein Template fe_page an, steht bei Layout dann "fe_page (Contao Official Demo, theme zwei)"

Ich kann damit Leben, da ich ja nun weiß was dahinter steckt.
Können das andere auch?

**Comment by leofeyer** [comment]
Ich weiß nicht was bei Dir anders ist, aber bei mir steht in so einem Fall immer auch "global" mit in den Klammern.

<img width="461" alt="" src="https://cloud.githubusercontent.com/assets/1192057/26169842/63a7911e-3b3f-11e7-93bb-b643e73ca065.png">

Scheint also kein generelles Core-Problem zu sein.
