### ISSUE TITLE
[feature] newsPicker, eventPicker, faqPicker

### ISSUE THREAD

**Issue by Aybee** [contao/core#8431]
Mir schwebt vor dieses Modale Fenster mit den Pickern filePicker und pagePicker um newsPicker, eventPicker und faqPicker zu erweitern.

Hier mal ein paar Screenshots zum besseren Verständnis mit einem newsPicker:
![newspicker](https://cloud.githubusercontent.com/assets/1143013/17459188/bd1b46c8-5c2e-11e6-8903-4b141777e08b.png)
![filepicker](https://cloud.githubusercontent.com/assets/1143013/17459157/876980ae-5c2d-11e6-96c2-2957f8e10eb7.png)
![pagepicker](https://cloud.githubusercontent.com/assets/1143013/17459159/878e8b42-5c2d-11e6-8c2e-a003449ca9df.png)
Der Grund ist, weil immer wieder angefragt wird, ob es möglich sei ohne Insert-Tags auf News zu verlinken.

Selber bekomme ich das nicht umgesetzt, z.B. das als Erweiterung anzubieten.

**Comment by ADoebeling** [comment]
Ich glaube das Thema ist duplicate: https://github.com/contao/core/issues/7656

**Comment by Aybee** [comment]
Ah ja, den hatte ich nicht gefunden. Danke.
