### ISSUE TITLE
Wrong headlines in pagePicker modal window

### ISSUE THREAD

**Issue by Aybee** [contao/core#8432]
In der Online-Demo:

1. Ein CE Typ Hyperlink erstellen
2. Klick auf den **Page picker** beim Feld **Link target**

Die Überschrift lautet **Site structure**. Man hat dort 4 Seiten, welche man aufrufen kann.

1. file picker
2. file manager
3. page picker
4. site structure

Auf allen 4 Seiten heißt die Überschrift **Site structure**. Das ist verwirrend. Sie sollten

1. Dateiwähler
2. Dateimanager
3. Seitenwähler
4. Seitenstruktur

heißen.

**Comment by leofeyer** [comment]
Ich glaube nicht, dass das mit vertretbarem Aufwand implementiert werden kann. Der Picker gehört zum Markup der Seite, der Inhalt des Pickers wird jedoch in einem Iframe aufgerufen. Wir müssten also überall per JavaScript prüfen, ob wir in einem Iframe sind, und wenn ja, müssten wir das Markup der Elternseite dynamisch ändern.

Vielleicht sollten wir eher überlegen, ob die Überschrift nicht gegen etwas Allgemeineres ausgetauscht werden kann, das in allen 4 Fällen ok wäre?

**Comment by Aybee** [comment]
Ja, das hatte ich mir schon gedacht. Eine andere Überschrift wäre dann auch erstmal besser als nichts. Mir fällt gerade nichts Gescheites ein. Evtl. sowas wie Zielwähler, Linkpicker, URL-Picker...

**Comment by leofeyer** [comment]
> Eine andere Überschrift wäre dann auch erstmal besser als nichts. Mir fällt gerade nichts Gescheites ein. Evtl. sowas wie Zielwähler, Linkpicker, URL-Picker...

@contao/developers Fällt euch etwas ein?

**Comment by aschempp** [comment]
Oder einfach basierend auf dem Eingabefeld, z.B. *Link-Ziel wählen…*

**Comment by Aybee** [comment]
Ja, das wäre gut, anderes Beispiel "_Bildlink-Adresse_", damit weiß man dann auch, wo man hergekommen ist.

**Comment by leofeyer** [comment]
Behoben in dffb49530974c213a724a7b1153af183515901ae.
