### ISSUE TITLE
[C3.5] ModulePersonalData runs `save_callback` in wrong way

### ISSUE THREAD

**Issue by DyaGa** [contao/core#8433]
According to general usage of `save_callback` in core dca files the second callback parameter should be always `DataContainer` object (see https://github.com/contao/core/blob/master/system/modules/core/drivers/DC_Table.php#L3009). Callback example:

```php
public function checkRootType($varValue, DataContainer $dc)
```

But `ModulePersonalData` runs `save_callback` in wrong way, see: https://github.com/contao/core/blob/master/system/modules/core/modules/ModulePersonalData.php#L259. The second argument is `$this->User`.

So, here is a problem. If we add a custom `save_callback` for any `tl_member` field and try to save member data in `FE` mode, then we get an error:

```
PHP Recoverable error: Argument 2 passed to Base\Backend\MemberCallback::saveField() must be an instance of DataContainer, instance of Contao\FrontendUser given, called in ...system/modules/core/modules/ModulePersonalData.php on line 259 and defined in ...
```

**Comment by leofeyer** [comment]
> According to general usage of `save_callback` in core dca files the second callback parameter should be always `DataContainer` object

That's not correct at all. Where did you get this from? The data container shall be the *last* argument, not the *second* one.

**Comment by aschempp** [comment]
@DyaGa this is a known limitation because the front end does not have a data container object. Simply do not define a type in the method and use `instanceof` to check.

**Comment by DyaGa** [comment]
Ok. Then I put a notice here. For anyone who wants to use `save_callback` for `tl_member` field you should do something like this:

```php
public function saveField($varValue, $dc)
{
	if ($dc instanceof \DataContainer) {
		// do something with $dc as \DataContainer object
	} elseif ($dc instanceof \FrontendUser) {
		// do something with $dc as \FrontendUser object
	}

	return $varValue;
}
```
