### ISSUE TITLE
[C3.5] Remove invisible characters from a string value before validating

### ISSUE THREAD

**Issue by DyaGa** [contao/core#8434]
I have just got an issue. Form shows an error for next phone number. I reproduce it in Contao demo:

![](https://i.gyazo.com/3928d2e93be43328ae3feeeffa0907d4.png)

The problem is in invisible characters [e2808e](http://www.fileformat.info/info/unicode/char/200e/index.htm) (left-to-right mark).

Input phone value with invisible character:
```
‎79022222222
```
You can copy this value and paste it in the form and you will get an error.

Hex value:
```
e2808e3739303232323232323232
```

This invisible characters should be removed from string on validating phone numbers, numbers, etc.

**Comment by ADoebeling** [comment]
AFAIK there are lots of invisible characters we should filter:
https://en.wikipedia.org/wiki/Whitespace_character

**Comment by Toflar** [comment]
Contao is validating the input correctly and that's all it should do. I consider altering the user input a very bad practice. Definitely 👎  on this.

**Comment by leofeyer** [comment]
I second @Toflar's opinion. Pasting invisible characters into a field is wrong in the first place and should not be attempted to be fixed programmatically.
