### ISSUE TITLE
TinyMCE problem: Embed image in formfield "headline" and "explanation"

### ISSUE THREAD

**Issue by nuun** [contao/core#8437]
Hi there
There is a small problem with the TinyMCE Editor in the newest Contao 3.5.15. Reproducable in the demo.contao.org.
1. insert an image directly in a TinyMCE field "headline" or TinyMCE field "explanation" in a form 
2. save
3. then "go back" to the field list
4. the image will not displayed in this preview list... because of a wrong saved image path...

I know this is not a very important bug and we usually don't insert images directly in tinyMCE except in one big clients installation...
So maybe somebody will look at this little bug..
Thanks a lot - Mr. nuun

**Comment by bytehead** [comment]
It's because the `file` inserttag gets not replaced:
`<img src="{{file::82397276-a4c3-11e3-8e29-000c29e44aea}}" alt="" width="725" height="446">`

**Comment by bytehead** [comment]
I don't know, why the [`BaseTemplate`](https://github.com/contao/core/blob/master/system/modules/core/library/Contao/BaseTemplate.php#L70-L114) does not replace any inserttags. The [`FrontendTemplate`](https://github.com/contao/core/blob/master/system/modules/core/classes/FrontendTemplate.php#L100) does.

**Comment by nuun** [comment]
ok - thanks for helping bytehead.

**Comment by leofeyer** [comment]
Fixed in c1e72c563bee6d95661cfacd6e7867d08bbd363e.

**Comment by nuun** [comment]
A big Thanks Leo!
