### ISSUE TITLE
bad stylesheet (tinymce.css)

### ISSUE THREAD

**Issue by asaage** [contao/core#8440]
update https://github.com/contao/core/blob/master/system/themes/tinymce.css
and change the selectors ```ul li```and ```ol li``` to ```ul>li```and ```ol>li``` please.
I noticed some strange behaviour - see screenshot.
![image](https://cloud.githubusercontent.com/assets/4138336/17672623/8fae771e-631d-11e6-9a70-f3021d76d93f.png)

**Comment by leofeyer** [comment]
Fixed in 0b3442b6c11881d3e82384ffca9770e8b764709d.
