### ISSUE TITLE
Get field name in its options_calback

### ISSUE THREAD

**Issue by Defcon0** [contao/core#8444]
Hello folks,

in one of our projects we dynamically get options of fields by an options_callback. In this particular case it's about 150 fixed fields. Because the options are retrieved by a database call there's a dependency to the field's name in its options_callback.

To my knowledge there is no way to get the field's name in its options_callback at the moment. So would it be possible to add this information to the calls of options_callbacks?

Bye Defcon0

**Comment by leofeyer** [comment]
Isn't the DCA object passed to the options_callback?

**Comment by aschempp** [comment]
Afair you can get the field from $dc->strField

**Comment by Defcon0** [comment]
Ah,  you're right. In my case it's been $dc->field since options_callback has been called in a static context  so had no direct access to protected $strField. Thanks for the tipp!
