### ISSUE TITLE
Wrong events in FE list with recurring events

### ISSUE THREAD

**Issue by Aybee** [contao/core#8445]
Zum Testen in der Online-Demo das Modul **Calendar - Event list** am besten so einstellen
- Headline - All events
- Event list format - All events
- Number of events - 0
- Items per page - 10

Jetzt im Event-Calendar **Contao Public Example Events** alle Events Auge auf grau stellen.

Ein neues Event erstellen

- Start date - Heute
- Repeat-Event
- Interval - 1 year(s)
- Recurrences - 0

Das Ergebnis im FE sind Events, die 1970 starten und das Datum ist nicht das des Events, sondern der 01.01.

Jetzt das Ganze mal mit 
- Interval - 1 month(s)

Ergebnis: Start 1970, Datum 01.01., 01.02. ... Der Starttag und -monat entspricht nicht dem Startdatum des Events.

Das Ganze mit
- Interval - 1 day(s) | 1 week(s)

Scheint in Ordnung zu sein.

**Comment by ADoebeling** [comment]
Ich konnte das eben auf demo.contao.org **nicht** reproduzieren. Bitte check mal meine Schritte gegen, habe ich etwas aus Deiner Beschreibung falsch verstanden?

[![Alt text](https://img.youtube.com/vi/_MUMTvLy98o/0.jpg)](https://www.youtube.com/watch?v=_MUMTvLy98o)

**Comment by asaage** [comment]
Event list format:
All upcoming events ≠All events

**Comment by Aybee** [comment]
Ja, wie @asaage bereits sagt, Event list format - All events.

Aber auch mit deiner Einstellung hast du dort Fehler in der Listenausgabe. Deine Events sind doppelt, am 01.01. und am 20.08.

**Comment by Aybee** [comment]
Sorry, hatte oben noch einen Fehler, ich meinte alle Events erstmal unveröfffentlichen, also Auge auf grau, damit man den Fehler im neu erstellten Event besser erkennen kann.

**Comment by leofeyer** [comment]
Ich kann das Problem auch nicht reproduzieren. Das erste Event ist bei mir am 24.08.2016 und das letzte am 24.08.2037.

**Comment by Aybee** [comment]
Bitte nochmal testen. Einfach alles so machen, wie oben beschrieben. Siehe Screenshots.

![themes_ _contao_official_demo_ _front_end_modules_ _edit_module_id_20_-_contao_open_source_cms_3 5_-_2016-08-24_16 55 45](https://cloud.githubusercontent.com/assets/1143013/17935509/e2db0f24-6a1b-11e6-96f1-e9be81a0a6b6.png)
![events_ _edit_event_id_9_-_contao_open_source_cms_3 5_-_2016-08-24_16 54 57](https://cloud.githubusercontent.com/assets/1143013/17935532/f43bca9c-6a1b-11e6-9ff5-2d1197c557af.png)
![events_-_contao_official_demo_-_2016-08-24_16 55 21](https://cloud.githubusercontent.com/assets/1143013/17935555/04d6f7b4-6a1c-11e6-929a-91d46be1dc2f.png)

**Comment by Aybee** [comment]
Momentan noch in der Online-Demo für 44 Minuten, falls es keiner überschreibt.

**Comment by leofeyer** [comment]
Tatsächlich tritt der Fehler in der Onlinedemo auf und in meiner Testumgebung nicht.

**Comment by Aybee** [comment]
Die Demo ist noch 3.5.14. Liegt es daran?

**Comment by leofeyer** [comment]
Nein, die Demo ist 3.5.15. Das hatte ich schon aktualisiert. Es liegt sicherlich an irgendeiner PHP-Zeitfunktion, die je nach Server unterschiedliche Werte zurück gibt.

**Comment by Aybee** [comment]
Als ich das getestet hatte, war die Online-Demo noch 3.5.**14**, siehe die Screenshots.

**Comment by leofeyer** [comment]
> Als ich das getestet hatte, war die Online-Demo noch 3.5.14, siehe die Screenshots.

Ja, hab ich ja nicht bestritten. Ich hab nur gesagt, dass ich die Demo zwischenzeitlich schon aktualisiert hatte, um das als Fehlerquelle ausschließen zu können.

**Comment by leofeyer** [comment]
Behoben in 0e7bd7a76c3629928ecc6205233f7aa1f9c90ee2.
