### ISSUE TITLE
Eventlist - Future recurring events not appearing in list

### ISSUE THREAD

**Issue by operatorone** [contao/core#8447]
Zukünftige Events mit Wiederholungs-Intervallen werden nicht in Listen dargestellt. Alle Options im Select-Feld Event list format unter der Optgroup Upcoming events scheinen nicht zu funktionieren. Past events und Event list scheint in Ordnung zu sein.

https://community.contao.org/de/showthread.php?63655-Eventliste-Fehler-bei-Events-mit-Intervall&p=417644#post417644

**Comment by leofeyer** [comment]
Wie lässt sich das in der Onlinedemo reproduzieren?

**Comment by operatorone** [comment]
Reproduktionsanweisung:

- Erstelle eine sich wiederholendes Event
- Modul: Eventliste anlegen und bei Anzeigeformat +3 Monate einstellen
- Template: event_list oder event_upcoming (egal)

Resultat: Anzeige im Frontend "Aktuell sind keine Termine vorhanden."
Alle sich nicht wiederholenden Termine werden in der Zukunft angezeigt.

**Comment by leofeyer** [comment]
Die problematischen Änderungen in der Datei `ModuleEventlist.php` wurden aufgrund von #8194 gemacht.

**Comment by operatorone** [comment]
Danke für die Info.

**Comment by leofeyer** [comment]
Behoben in fed9dbcbb691c42b075d3eb445b691e1316fdbd2.

**Comment by operatorone** [comment]
Danke für den Fix.
