### ISSUE TITLE
Cross-Origin bei "Suchindex neu aufbauen"

### ISSUE THREAD

**Issue by splinter03** [contao/core#8448]
Hallo!

Mit ist soeben aufgefallen, dass wenn ich den Suchindex lösche und manuell wieder erstelle, dieser nicht vollständig ist.
Ich habe mehrere Startpunkte, die jeweils über eine Subdomain zu erreichen sind. Starte ich nun die "Suchindex neu aufbauen"-Funktion, wird auf der Seite ein JavaScript gestartet, dass jede Seite einmal aufruft. Da nun aber nicht alle Seiten unter der gleichen Domain liegen, meldet Firefox:

`Quellübergreifende (Cross-Origin) Anfrage blockiert: Die Gleiche-Quelle-Regel verbietet das Lesen der externen Ressource...`

Im Moment habe ich also keine Möglichkeit, den Suchindex komplett neu aufzubauen, oder?

Ich nutzte die Contao-Version 3.5.15.

**Comment by fritzmg** [comment]
Hier gibt es zwei Probleme:

1. musst du deinen Webserver so konfigurieren, dass ein entsprechender `Access-Control-Allow-Origin` parameter im response header zurückgegeben wird.
2. muss auch das `be_rebuild_index` Template geändert werden, dass solche Cross-Origin requests funktionieren, also genauer gesagt das Script:
```html
<script>
  window.addEvent('domready', function() {
    var urls = $$('.page_url'),
        complete = 0;
    urls.each(function(el) {
      if (el.getAttribute('data-url')) {
        var request = new Request({
          'url': el.getAttribute('data-url'),
          onSuccess: function() {
            el.addClass('tl_green');
          },
          onFailure: function(xhr) {
            el.addClass('tl_red');
            el.set('text', el.get('text') + ' - ' + xhr.status );
          },
          onComplete: function() {
            complete++;
            if (complete == urls.length) {
              $('index_loading').setStyle('display', 'none');
              $('index_complete').setStyle('display', 'block');
            }
          }
        });
        delete request.headers['X-Requested-With'];
        request.send();
      }
    });
  });
</script>  
```
(Dieser Code enthält bereits Verbesserungen aus https://gist.github.com/fritzmg/81acff5ed269f3281ee1, welche in Contao 4 schon integriert sind.)

Siehe https://community.contao.org/de/showthread.php?60613-Suchindex-erstellen-bei-Multidomain-Installation&p=406597&viewfull=1#post406597

**Comment by leofeyer** [comment]
Was genau muss denn in `be_rebuild_index` geändert werden?

**Comment by fritzmg** [comment]
Der `X-Requested-With` header, den das MooTools Request Objekt by default setzt, musst entfernt werden, zB. mit
```js
delete request.headers['X-Requested-With'];
```
Zumindest habe ich das so von http://stackoverflow.com/questions/18445337/mootools-cors-request-vs-native-javascript/18607750#18607750

**Comment by leofeyer** [comment]
Das sollte keinerlei Unterschied machen, zumal `X-Requested-With` ja nichts über den Host aussagt. IMO muss nur `Access-Control-Allow-Origin` auf dem Server entsprechend konfiguriert werden.

**Comment by fritzmg** [comment]
Ohne das zu tun funktioniert es auf jeden Fall nicht.
```
<IfModule mod_headers.c>
    Header set Access-Control-Allow-Origin: *
</IfModule>
```
alleine reicht mit dem MooTools Request Objekt nicht.

**Comment by fritzmg** [comment]
@splinter03 füge mal vorhin genannten Code in deine .htaccess ein und teste nochmal.

**Comment by splinter03** [comment]
Leider ohne Erfolg, denn der Header wird nur für statische Dateien ausgegeben. Ich hab mal gegoogelt und anscheinend ist es davon abhängig, wie PHP eingerichtet wird. Der Apache kann den Header bei PHP-Dateien nicht ändern, zumindest bei 1und1. Habt ihr noch eine Idee?

Warum werden die Seiten überhaupt über einen JavaScript-Request aufgerufen. Wäre es nicht besser, das ganze über das PHP-Backend zu machen, also die Urls über die PHP-Funktion "curl" aufzurufen?

**Comment by fritzmg** [comment]
> Leider ohne Erfolg, denn der Header wird nur für statische Dateien ausgegeben.

? Was genau hast du eingetragen. die `.htaccess.default` von Contao hat folgendes bereits integriert:
```
<IfModule mod_headers.c>
  <FilesMatch "\.(ttf|ttc|otf|eot|woff2?|font\.css)$">
    Header set Access-Control-Allow-Origin "*"
  </FilesMatch>
</IfModule>
```
Aber das meinte ich nicht. Du sollst
```
<IfModule mod_headers.c>
    Header set Access-Control-Allow-Origin: *
</IfModule>
```
selbst in der `.htaccess` hinzufügen. Ganz am Ende bspw.


> Warum werden die Seiten überhaupt über einen JavaScript-Request aufgerufen. Wäre es nicht besser, das ganze über das PHP-Backend zu machen, also die Urls über die PHP-Funktion "curl" aufzurufen?

Damit man den Fortschritt mitbekommt. Natürlich könnte man das auch über ein PHP Script lösen, dass per AJAX angestoßen wird - und dann wird per AJAX der aktuelle Status abgefragt. Aber das ist halt aufwendiger ;)


Lokal konnte ich das Problem übrigens aus irgendeinem Grund nicht nachstellen. Selbst ohne jegliche Änderungen kontte ich von bspw. `example1.dev` auf `example2.dev` erfolgreich requests schicken o_0. Verstehe des gerade selbst nicht.

**Comment by splinter03** [comment]
Genau das habe ich gemacht :)
Zum testen habe ich auch einfach mal `Header always set Special-Header "OK"` eingefügt, aber wie gesagt, der Header wird nur bei statischen Dateien an den Browser gesendet.

> Lokal konnte ich das Problem übrigens aus irgendeinem Grund nicht nachstellen.
evt. greift die cross-origin-Policy des Browsers unter "localhost" nicht

**Comment by Toflar** [comment]
Das liegt zu 100% daran, dass PHP über CGI ausgeführt wird. Die Regeln für Apache's `mod_header`-Modul sind dann ein bisschen anders. Deswegen funktioniert es problemlos für statische Dateien, nicht aber für die die über den CGI-Handler kommen. Man findet dazu etliche Beiträge im Internet. Hier ein [Startpunkt](http://serverfault.com/questions/383011/mod-headers-not-sending-headers-when-file-is-php).

**Comment by fritzmg** [comment]
> evt. greift die cross-origin-Policy des Browsers unter "localhost" nicht

Vermutlich, ja.

@Toflar hmm, aber was ist dann die Lösung bei CGI? (Was ja der reguläre Fall sein wird.) Laut dem serverfault thread sollte
```
Header always set …
```
dann ja reichen.

@splinter03 hast du nun in deiner `.htaccess` irgendwo
```
Header always set Access-Control-Allow-Origin "*"
```
ohne `<IfModule mod_headers.c>` stehen?

**Comment by splinter03** [comment]
> aber was ist dann die Lösung bei CGI

Ich denke dann kann man den Header nur über PHP manipulieren

Ohne IfModule mod_headers.c habe ich es auch probiert.

**Comment by splinter03** [comment]
Ich habe jetzt testweise die index.php und die .htaccess wie folgt angepasst:

**index.php** - direkt an den Anfang
`header('Access-Control-Allow-Origin: http://domain.derContaoInstallation.de');`
`header('Access-Control-Allow-Headers: x-requested-with');`

**.htaccess**
`Header set Access-Control-Allow-Origin "http://domain.derContaoInstallation.org"`
`Header set Access-Control-Allow-Headers "x-requested-with"`

Damit funktioniert es.

**Comment by splinter03** [comment]
Wobei ein Problem bleibt. Der 1und1-Server macht anscheinend dicht, wenn gleichzeitig mehrere hundert Anfragen gleichzeitig getriggert werden. Arbeitet man die Requests sequentiell ab, läuft die Indizierung problemlos durch. Dafür ist die Modifikation des Templates "be_rebuild_index.html5" notwendig:

```javascript
window.addEvent('domready', function() {
	var urls = $$('.page_url');
	performRequest(urls);
});

function performRequest(urls) {
	var span = urls[0];
	var url = span.getAttribute('data-url');
	
	if (url) {
		var request = new Request({
			'url': url,
			onSuccess: function() {
				span.addClass('tl_green');
			},
			onFailure: function(xhr) {
				span.addClass('tl_red');
				span.set('text', span.get('text') + ' - ' + xhr.status );
			},
			onComplete: function() {
				checkStatus(urls);
			}
		}).get();
	}
	else {
		checkStatus(urls);
	}
}

function checkStatus(urls) {
	urls.shift();
	if (urls.length > 0) {
		performRequest(urls);
	}
	else {
		$('index_loading').setStyle('display', 'none');
		$('index_complete').setStyle('display', 'block');
	}
}
```

**Comment by bytehead** [comment]
Das ist mit Sicherheit nicht nur bei dem 1und1 Server so, konnte ich auch schon beobachten.

**Comment by leofeyer** [comment]
>  Der 1und1-Server macht anscheinend dicht, wenn gleichzeitig mehrere hundert Anfragen gleichzeitig getriggert werden. Arbeitet man die Requests sequentiell ab, läuft die Indizierung problemlos durch.

Falls wir das diskutieren wollen, müsstest Du dazu ein neues Ticket öffnen bitte.

**Comment by splinter03** [comment]
Ich bin ein bisschen erstaunt, dass das Ticket geschlossen wurde. Das Ursprungsproblem besteht doch noch, die Funktion "Suchindex aktualisieren" kann nicht mit Multi-Domain-Installationen.

**Comment by leofeyer** [comment]
Das Problem kann aber nicht durch Anpassung von Contao gelöst werden, daher gibt es für uns hier nichts mehr zu tun. Soweit ich verstanden habe, muss die Serverkonfiguration angepasst werden, oder?

**Comment by do-while** [comment]
Gegenbeispiel bei All-Inkl. dort habe ich heute den Suchindex mit 9441 News-Beiträgen plus einigen Webseiten aufgebaut. Nach ca. 20 Minuten war alles durch. 
tl_search_index: 2759369 Einträge, 150 MiB
Das hängt dann wohl wirklich am Provider.

**Comment by Toflar** [comment]
Korrekt, das ist eine Server-Config. Abgesehen davon, dass ein `*` für den `Access-Control-Allow-Origin` Header eine sehr schlechte Idee ist und Contao auch nicht automatisch alle Domains mitsenden soll, weil das je nach Multidomain-Betrieb auch nicht sein darf. Hängt also von der Installation und der Konstellation ab.

Wir könnten im Backend eine Option an, welche Domain indexiert werden soll. Dann kann man sich selber manuell auf allen einloggen und somit den CORS Request umgehen. Das ist aber nicht wirklich praktisch und wir wollen in Zukunft ja ohnehin einen echten Crawler nutzen, der allen Links im Frontend (somit z.B. auch paginierten News) folgen soll. Das ist die einzige Art und Weise wie man richtig indexieren kann. Daher würde ich hier jetzt nichts mehr umbauen, wenn die Lösung sowieso komplett anders sein soll.

**Comment by splinter03** [comment]
Na ja, bei vielen Contao-Installationen kann der Server nicht beeinflusst werden. Da wäre es super wenn Contao eine Möglichkeit mitbringt, wie z.B. das setzen des Headers über die index.php:

`header('Access-Control-Allow-Origin: http://domain.derContaoInstallation.de');`
`header('Access-Control-Allow-Headers: x-requested-with');`

und mit Contao wird ja auch eine .htaccess-Datei mitgeliefert, die auch einen entsprechenden Eintrag enthalten könnte.

`Wir könnten im Backend eine Option an, welche Domain indexiert werden soll.` Im Header muss doch nur die Domain angegeben werden, unter der man gerade in Contao angemeldet ist.

Das mit dem Crawler finde ich gut, ich finde es aber auch schade, das User, die auf das LTS und Managed Webspace setzen, mit einen kaputten Suchindex zurechtkommen müssen, ohne das sie es merken.

**Comment by fritzmg** [comment]
@Toflar 

> Korrekt, das ist eine Server-Config. Abgesehen davon, dass ein * für den Access-Control-Allow-Origin Header eine sehr schlechte Idee ist

Wird aber auch von Contao für gewisse statische Ressourcen mitgeliefert: https://github.com/contao/core/blob/3.5.15/.htaccess.default#L28


@do-while hast du das auch mit einem angepassten _be_rebuild_index_ template getestet bzw. die Responses aller Requests analysiert?

**Comment by Toflar** [comment]
Ja natürlich, für die da genannten Ressourcen ist das ja auch kein Problem.

**Comment by fritzmg** [comment]
Das Mitliefern der entsprechenden `Header set` Einträge in der `.htaccess.default` von Contao wird in vielen Fällen nichts bringen, da das setzen von Headern über die `.htaccess` im Apache nicht funktioniert, wenn PHP über FastCGI ausgeführt wird. In so einem Fall müsste man das direkt in der vhost Konfiguration machen (siehe http://serverfault.com/a/383063/143519).

Hat man keinen Zugriff auf die vhost Konfiguration, könnte man folgende Extension statt dessen benutzen: [fritzmg/contao-multidomain-rebuild-index](https://github.com/fritzmg/contao-multidomain-rebuild-index).

> Das sollte keinerlei Unterschied machen, zumal X-Requested-With ja nichts über den Host aussagt. IMO muss nur Access-Control-Allow-Origin auf dem Server entsprechend konfiguriert werden.

Im Gegensatz zu `$.ajax` von jQuery setzt das MooTools `Request` Objekt den `X-Requested-With` Request Header _immer_. Daher muss auch bei einem Cross-Domain Request der Server mit einem
```
Access-Control-Allow-Headers: X-Requested-With
```
antworten, andernfalls funktioniert der request nicht.
