### ISSUE TITLE
Webserver blockiert, wenn der Suchindex aktualisiert wird

### ISSUE THREAD

**Issue by splinter03** [contao/core#8449]
Aktualisiert man den Suchindex, werden gleichzeitig mehrere hundert Anfragen an den Webserver gesendet. Das führt bei einigen Providern (wie z.B. 1und1) dazu, dass die Requests blockiert werden (sicher ein DDOS-Schutz). Arbeitet man die Requests sequentiell ab, läuft die Indizierung problemlos durch. Dafür ist die Modifikation des Templates "be_rebuild_index.html5" notwendig:

```javascript
window.addEvent('domready', function() {
	var urls = $$('.page_url');
	performRequest(urls);
});

function performRequest(urls) {
	var span = urls[0];
	var url = span.getAttribute('data-url');
	
	if (url) {
		var request = new Request({
			'url': url,
			onSuccess: function() {
				span.addClass('tl_green');
			},
			onFailure: function(xhr) {
				span.addClass('tl_red');
				span.set('text', span.get('text') + ' - ' + xhr.status );
			},
			onComplete: function() {
				checkStatus(urls);
			}
		}).get();
	}
	else {
		checkStatus(urls);
	}
}

function checkStatus(urls) {
	urls.shift();
	if (urls.length > 0) {
		performRequest(urls);
	}
	else {
		$('index_loading').setStyle('display', 'none');
		$('index_complete').setStyle('display', 'block');
	}
}
```

**Comment by leofeyer** [comment]
-1 von mir. Die sequenzielle Abarbeitung dauert einfach viel länger und wir sollten das nicht allen Benutzern zumuten, besonders weil das Problem bei einem Großteil gar nicht auftritt.

**Comment by splinter03** [comment]
Langsam ist es, aber dafür auch zuverlässig.

> weil das Problem bei einem Großteil gar nicht auftritt.

...das wage ich zu bezweifeln, da alle, die auf das LTS setzen, das gar nicht mitbekommen, da das original "be_rebuild_index.html5"-Template ja immer Erfolg meldet. Ist aber auch nur mein persönliches Baugefühl dazu, da ich auch nur zufällig darauf gestoßen bin, dass unser Suchindex unvollständig ist.

**Comment by leofeyer** [comment]
Das kannst Du leicht herausfinden, indem Du die Änderungen am [Template aus Contao 4.2](https://github.com/contao/core-bundle/blob/master/src/Resources/contao/templates/backend/be_rebuild_index.html5
) übernimmst.

@contao/developers Sollten wir vielleicht die [MooTools Request Queue](http://mootools.net/more/docs/1.5.2/Request/Request.Queue) an dieser Stelle verwenden?

**Comment by bytehead** [comment]
@leofeyer Hab ich schon versucht, die Request Queue von Mootools ist aber buggy.

**Comment by Toflar** [comment]
Richtig wäre es mit Promises zu lösen.

**Comment by leofeyer** [comment]
Dafür bräuchten wir aber MooTools 1.6. 😄

**Comment by leofeyer** [comment]
Nicht dass wir das nicht hätten, nur: https://github.com/contao/core/issues/8411#issuecomment-241132603

**Comment by Toflar** [comment]
Nö, nur ein Promises Polyfill für die Browser ohne ES6 Support. Aber auf die 1.6 können wir doch eh updaten? Ist ja ein rückwärtskompatibles Bugfix-Release (klar mit neuen Features, aber auch mit Bugfixes).

**Comment by leofeyer** [comment]
Behoben in 891ad94312ca1e16d75daccd16fbb529bdb9149f.

**Comment by tsarma** [comment]
While rebuilding index of a site containing over 16000 pages. It stopped sending ajax request to server after first encounter of 404 page. It happened after indexing 6000 pages and after about 40 mins.

![404](https://cloud.githubusercontent.com/assets/683894/19722206/ede984dc-9b75-11e6-9b4d-8f6e37d86c25.jpg)

**Comment by leofeyer** [comment]
Did you adjust the `be_rebuild_index.html5` template?

**Comment by leofeyer** [comment]
The [stopOnFailure](https://github.com/contao/core/blob/master/system/modules/core/templates/backend/be_rebuild_index.html5#L26) option is definitely disabled.

**Comment by tsarma** [comment]
No I did not edit the be_rebuild_index.html5

**Comment by leofeyer** [comment]
See #8541.
