### ISSUE TITLE
Remove logging from StringUtil::parseSimpleTokens()

### ISSUE THREAD

**Issue by leofeyer** [contao/core#8451]
We should remove the verbose logging from the `StringUtil::parseSimpleTokens()` method. IMO, unknown simple tokens are not an error; they might just not exist. And we are not logging unknown insert tags, either.

@contao/developers What do you think?

**Comment by aschempp** [comment]
They sure are an error to me. Insert tags are logged in the console.

**Comment by Toflar** [comment]
This is always an error.

**Comment by leofeyer** [comment]
> Insert tags are logged in the console

Ah, that's true. Then we should log simple tokens there, too.

**Comment by aschempp** [comment]
Unfortunately, simple tokens are not usually parsed when opening a page, but e.g. when sending emails, which does not have a console…

**Comment by leofeyer** [comment]
True, but insert tags can also be used in e-mails. 😉

**Comment by leofeyer** [comment]
Should we log unknown insert tags in the system log, too?

**Comment by Toflar** [comment]
> Should we log unknown insert tags in the system log, too?

Imho, this would be cool. This is a log entry that does not flood the logs but instead can be fixed and provides useful info (should report the current env request too).

**Comment by leofeyer** [comment]
> This is a log entry that does not flood the logs

If the unknown tag is on every page, a log entry will be added upon every request.

But still I agree. Shall I remove the unknown tags from the debug console then?

**Comment by Toflar** [comment]
I think so, yes. Never checked that anyway and it's mostly editors using insert tags so they won't notice it anyway as they don't use the debug bar.

**Comment by leofeyer** [comment]
See https://github.com/contao/core-bundle/pull/572.
