### ISSUE TITLE
Uneinheitliche Länderbezeichnungen

### ISSUE THREAD

**Issue by Mynyx** [contao/core#8453]
Die Länderbezeichnungen in ````contao/system/modules/core/languages/.../countries.xlf```` sind uneinheitlich: Bei den meisten Ländern wird die gewöhnliche kurze Form verwendet, wie z. B. Deutschland (statt "Bundesrepublik Deutschland"). Dagegen wird Tschechien als "Tschechische Republik" bezeichnet und Vereinigtes Königreich als "Vereinigtes Königreich Großbritannien und Nordirland".

Außerdem ist in jeweils in Zeile 3 der xlf-Dateien angegeben ````original="system/modules/core/languages/en/countries.php"````, obwohl diese Datei offenbar nicht existiert.

**Comment by leofeyer** [comment]
> Außerdem ist in jeweils in Zeile 3 der xlf-Dateien angegeben ````original="system/modules/core/languages/en/countries.php"````, obwohl diese Datei offenbar nicht existiert.

Das ist egal.

> Bei den meisten Ländern wird die gewöhnliche kurze Form verwendet, wie z. B. Deutschland (statt "Bundesrepublik Deutschland"). Dagegen wird Tschechien als "Tschechische Republik" bezeichnet und Vereinigtes Königreich als "Vereinigtes Königreich Großbritannien und Nordirland".

Könntest Du bitte genau auflisten, was Deiner Meinung nach geändert werden müsste?

**Comment by Mynyx** [comment]
CNT.gb: ``United Kingdom of Great Britain and Northern Ireland (the)`` ändern in ``United Kingdom``
CNT.cz: ``Czech Republic (the)`` ändern in ``Czechia ``

**Comment by bezin** [comment]
Ich denke, da gäbe es noch ein paar mehr Dinge, z.B. dass man grundsätzlich schon einmal Artikel in Klammern weglassen könnte, z.B. in "Central African Republic (the)", um eine cleanere Liste zu haben. 

Dann gibt es aber auch noch so Bezeichnungen wie "Bolivia (Plurinational State of)" – gefühlt würde auch hier "Bolivia" reichen (gleiches Argument: "Amtsbezeichnung vs. Umgangssprache").

Allerdings ist das auch eher nur ein persönliches Empfinden. Ich finde es schwierig, da eine Grenze zu ziehen. Wenn etwas geändert wird, sollte es aber konsequent geändert werden.

**Comment by leofeyer** [comment]
@contao/developers /cc

**Comment by ausi** [comment]
Ich würde mich da gerne auf einen Standard verlassen.

ISO 3166-1 verwenden als Namen scheinbar den englischen „short name“ der [United Nations Terminology Bulletin Country Names](http://unstats.un.org/unsd/geoinfo/UNGEGN/wg1.html). Dort ist jedoch auch der UN-Official-English-Short-Name für GB „United Kingdom of Great Britain and Northern Ireland“, nur der National-Official-Short-Name ist „United Kingdom“. Und es gibt dort keine deutsche Übersetzung.

Wir könnten uns aber auch auf die PHP-Intl-Extension verlassen und uns die Namen dort rausholen, die würden ganz gut passen IMO und sind in vielen Sprachen verfügbar:

```php
Locale::getDisplayRegion('-DE', 'en'); // Germany
Locale::getDisplayRegion('-DE', 'de'); // Deutschland
Locale::getDisplayRegion('-GB', 'en'); // United Kingdom
Locale::getDisplayRegion('-GB', 'de'); // Vereinigtes Königreich
Locale::getDisplayRegion('-CZ', 'en'); // Czech Republic
Locale::getDisplayRegion('-CZ', 'de'); // Tschechische Republik
Locale::getDisplayRegion('-BO', 'en'); // Bolivia
Locale::getDisplayRegion('-BO', 'de'); // Bolivien
```

**Comment by bezin** [comment]
> Ich würde mich da gerne auf einen Standard verlassen.
Das bringt auf den Punkt, was ich oben nicht in Worte fassen konnte :) +1

Die PHP-Intl-Extension nutzt das [Common Local Data Repository (CLDR)](http://cldr.unicode.org/index). 
Hier mal die Liste aller Länder- bzw. Terriorienübersetzungen aus der letzten Version der CLDR: https://gist.github.com/bezin/c00e7b7d74558d1aecb0be61621649e4

**Comment by ausi** [comment]
Nachdem anscheinend Apple, Google und Microsoft auch auf CLDR setzen, sollte das für uns auch ausreichen :)

**Comment by leofeyer** [comment]
Aktualisiert in 8d151b9b195c5da9473191f0d716552615a855e8.

**Comment by Mynyx** [comment]
Europäische Union als Land?

https://github.com/contao/core/commit/8d151b9b195c5da9473191f0d716552615a855e8#diff-a36f97917d9c9e60cc75b67593ca529eR89

**Comment by ausi** [comment]
Vermutlich sollten wir nur die Länder inkludieren die im [CLDR unter „regular“](http://unicode.org/cldr/trac/browser/tags/release-29/common/validity/region.xml#L16) aufgeführt sind.

**Comment by lionel-m** [comment]
@bezin Where did you find the German translation? I would like to find the list in French if exists... Thx

**Comment by schmanat** [comment]
@lionel-m i think he used the php-intl extension. [see commet above](https://github.com/contao/core/issues/8453#issuecomment-247007968)

**Comment by asaage** [comment]
@lionel-m 
maybe here: http://unicode.org/cldr/trac/browser/tags/release-29/common/main/fr.xml
inside ```<territories>```

**Comment by lionel-m** [comment]
@schmanat, @asaage Thanks !

**Comment by leofeyer** [comment]
> Vermutlich sollten wir nur die Länder inkludieren die im CLDR unter „regular“ aufgeführt sind.

Hab ich entsprechend aktualisiert. Die einzige Ausnahme ist die Sprache `no`, die eigentlich deprecated ist; wir haben aber eine norwegische Übersetzung.

**Comment by Mynyx** [comment]
Wäre die Frage, ob die Übersetzung Norwegian Bokmal oder Norwegian Nynorsk ist?

**Comment by lionel-m** [comment]
There are two `Southern Sotho` (Probably the same?):

1. Southern Sotho
2. Southern Sotho (South Africa)

In the list there isn't `Southern Sotho (South Africa)` but [`Northern Sotho`](http://unicode.org/cldr/trac/browser/tags/release-29/common/main/en.xml#L422). Is it correct?

**Comment by bezin** [comment]
> maybe here: http://unicode.org/cldr/trac/browser/tags/release-29/common/main/fr.xml
inside <territories>

Ahh, you managed to find a direct link to those xml-files :) I didn't, that's why I downloaded the whole set and created that gist :D

**Comment by leofeyer** [comment]
> Wäre die Frage, ob die Übersetzung Norwegian Bokmal ````nb```` oder Norwegian Nynorsk ````nn```` ist?

Das weiß ich nicht. Müssten wir mal [Michael](https://www.transifex.com/user/profile/DonHartmann/) fragen.

> 1. Southern Sotho
> 2. Southern Sotho (South Africa)
>
> In the list there isn't `Southern Sotho (South Africa)` but [`Northern Sotho`](http://unicode.org/cldr/trac/browser/tags/release-29/common/main/en.xml#L422).

Southern Sotho => 'st'
Southern Sotho (South Africa) => 'st_ZA'
Northern Sotho => 'nso'

**Comment by lionel-m** [comment]
@leofeyer thanks
