### ISSUE TITLE
Feature: individual template for form

### ISSUE THREAD

**Issue by jenda77** [contao/core#8454]
It would be great to have the possibility to choose an individual template for form too. Currently it´s possible to set it for each form element. But the form itself does not have this option - I can imagine it could be in the form settings. 

I hope that isn´t a lot of work. Thank you.

**Comment by leofeyer** [comment]
Implemented in 64903ec45e33bb73d1aca75c936bb1f44258a906.

**Comment by jenda77** [comment]
Thank you, @leofeyer
