### ISSUE TITLE
Ungültiges Passwort in ModuleCloseAccount

### ISSUE THREAD

**Issue by malitze** [contao/core#8455]
Es können Passwörter gewählt bzw. mittels ModuleChangePassword vergeben werden, welche von ModuleCloseAccount als ungültig erachtet werden und somit Accounts nicht geschlossen werden können. Nach ein paar Tests scheint dies vor allem bei Passwörtern die eine Raute enthalten der Fall zu sein (z.B. "#passwort").

Ursächlich scheint mir, dass das Input Widget in ModuleCloseAccount (Zeile 73) im Gegensatz zu den anderen Stellen ohne eval `'preserveTags'=>true` konfiguriert wird.

**Comment by leofeyer** [comment]
Wie lässt sich das in der Onlinedemo reproduzieren?

**Comment by malitze** [comment]
1. Im Backend Close Account Modul erstellen und anschließend bspw. in die User Seite einbinden.
2. Im Frontend anmelden und auf der User Seite das Passwort zu "#passwort" ändern.
3. Zum neu eingebundenen Close Account Modul navigieren, Passwort eingeben und Formular bestätigen => "Invalid password!"

**Comment by leofeyer** [comment]
Behoben in e9260b02ae16018b5742713ccb07e403de96a13b.
