### ISSUE TITLE
Autoload creator does not register Traits

### ISSUE THREAD

**Issue by sebj54** [contao/core#8456]
Actually, Autoload creator module registers correctly classes and interfaces but does not register traits in autoload.php files.

If you create a trait and then generate the autoload.php file via the Devtools module, it won't work.

Am I doing something wrong or is it not intended to work with traits?
Thanks for your help!

**Comment by leofeyer** [comment]
The autoload creator [does not support traits](https://github.com/contao/core/blob/master/system/modules/devtools/modules/ModuleAutoload.php#L174), but I think it should.

**Comment by sebj54** [comment]
That's why I created the issue, I think it should too!

**Comment by leofeyer** [comment]
Fixed in 79b2bced33f58d3f0da65cd050ea45669db3f573.
