### ISSUE TITLE
MooTools CDN-filename is wrong

### ISSUE THREAD

**Issue by baumisimon** [contao/core#8458]
The MooTools-filename in googleapis-CDN depends on the selected version. Newer versions (>1.5.1) are named mootools.min.js instead of mootools-yui-compressed.js.
See also https://developers.google.com/speed/libraries/#mootools

In system\modules\core\pages\PageRegular.php (line 409) the filename is set to mootools-yui-compressed.js, which results in an 404-error and therefore local fallback is loaded.

**Comment by leofeyer** [comment]
Fixed in 70c89124ec8449677b109c3b2c17714947785c8e.
