### ISSUE TITLE
Duplicate entry in  tl_search im Unique Key "checksum,pid"

### ISSUE THREAD

**Issue by BugBuster1701** [contao/core#8460]
Der Fehler tritt immer dann auf, wenn sich eine Seite auf zwei verschiedene Arten aufrufen lässt. Beispiel an der Online-Demo:
http://demo.contao.org/en/ vs. http://demo.contao.org/en/index.html ==> Fehlermeldung ganz unten.

Der Indexer prüft ob URL-PID Kombi vorhanden, ja Update, nein Insert.
Hier folgt beim zweiten Aufruf also ein Insert, die Checksumme ist aber gleich, Peng!

**Comment by BugBuster1701** [comment]
Entweder vorher prüfen oder per "insert ignore..." wären die Möglichkeiten dir mir einfallen dazu.

**Comment by t-me** [comment]
Same problem on my website :
[https://www.maat-lifestyle.nl/](https://www.maat-lifestyle.nl/) vs [https://www.maat-lifestyle.nl/index.html](https://www.maat-lifestyle.nl/)
i have just updated contao to 3.5.16

**Comment by leofeyer** [comment]
Seems OK to me, since you are not supposed to explicitly call the `/index.html` fragment.

**Comment by BugBuster1701** [comment]
Das passiert wohl auch bei der Frontendvorschau, wenn man diese bei der ersten Seite aufruft.

**Comment by antilet** [comment]
> ...you are not supposed to explicitly call the  /index.html  fragment.

Das lässt sich doch gar nicht vermeiden: wenn die Startseite über die Navigation aufgerufen wird, wird sie mit ihrem alias aufgerufen, und wenn www.domain.de aufgerufen wrid, dann eben ohne... :(

**Comment by bezin** [comment]
> Das lässt sich doch gar nicht vermeiden: wenn die Startseite über die Navigation aufgerufen wird, wird sie mit ihrem alias aufgerufen, und wenn www.domain.de aufgerufen wrid, dann eben ohne... :(

Wenn du das Navigationsmodul verwendest und die Startseite den Alias index hat, sollte die Seite ohne Alias aufgerufen werden. Wenn du einen Startseiten-Link manuell setzt, solltest du ihn auf / setzen statt auf /index.

**Comment by antilet** [comment]
Die Startseite hat aber - warum auch immer - einen anderen alias und ja via Navigationsmodul.
Unabhängig davon, sollte meiner Meinung nach der Fehler wieder behoben werden, so wie vor 3.2.16;
es macht in meinen Augen keinen Sinn, zu sagen, man soll dies nicht und das nicht ...

**Comment by leofeyer** [comment]
Improved in e29de00cf7d888a6c60d2db76f40ade3a7d05310.

**Comment by vstuber** [comment]
Ich denke, dass selbst mit dieser Änderung immer noch ein schwerwiegendes Problem vorliegt.

**Beispiel:**

Ich rufe eine Seite mit einem Get-Parameter auf, z. B.
`http://irgendeineseite.de/index.php/home.html?test=123`

Danach nochmal mit geändertem Parameter, z. B.
`http://irgendeineseite.de/index.php/home.html?test=124`

Dabei läuft das System noch immer in einen Fatal Error bzw. Uncaught Exception
`"Duplicate entry '52037b6602fe14f41604503cf06bcb15-73' for key 'checksum_pid'".`

Das passiert nicht, wenn man die Seite zunächst komplett ohne den Get-Parameter aufruft, aber auf jeden Fall, wenn bereits der erste Aufruf der Seite den Get-Parameter hat.

Ich habe die Änderung aus e29de00 mal in die 3.5.16 übernommen, aber das behebt diesen Fehler nicht.

**Comment by UH-Nerion** [comment]
Hallo,

wir haben das gleiche Problem. Sporadisch wird eine Seite nicht richtig geladen. Am Ende der Seite taucht dann die Contao Fehler-Meldung auf, mit verweiß auf die Logdateien, dort ist dann folgendes zu finden:

`[09-Sep-2016 12:40:06 GMT] PHP Fatal error: Uncaught exception 'Exception' with message 'Query error: Duplicate entry 'e926d079e1d8ad3db4baf086cbd219d9-111' for key 'checksum_pid' (UPDATE tl_search SET tstamp=1473424806, url='xxx', title='xxx', protected='', filesize='75.05', groups=0, pid='111', language='de', text='xxx', checksum='e926d079e1d8ad3db4baf086cbd219d9' WHERE id='5')' thrown in /.../system/modules/core/library/Contao/Database/Statement.php on line 295
#0 /.../system/modules/core/library/Contao/Database/Statement.php(264): Contao\Database\Statement->query()
#1 /.../system/modules/core/library/Contao/Search.php(206): Contao\Database\Statement->execute('5')
#2 /.../system/modules/core/classes/FrontendTemplate.php(330): Contao\Search::indexPage(Array)
#3 /.../system/modules/core/classes/FrontendTemplate.php(124): Contao\FrontendTemplate->addToSearchIndex()
#4 /.../system/modules/core/pages/PageRegular.php(190): Contao\FrontendTemplate->output(true)
#5 /.../system/modules/core/controllers/FrontendIndex.php(285): Contao\PageRegular->generate(Object(Contao\PageModel), true)
#6 /.../httpdocs/index.php(20): Contao\FrontendIndex->run()
`

Das Problem tritt erst seit Version 3.5.16 auf.
Kurzfristig beheben lässt sich das Problem, indem man unter Systemwartung die "tl_search" leert.
Da es immer wieder sporadisch auftaucht, ist das für uns sehr schlecht, da vereinzelt die Webseiten-Designs dann nicht korrekt geladen werden.

Danke

**Comment by leofeyer** [comment]
Behoben in 9142f5c46276ac3483c445ef9c30a625162091e9.

**Comment by UH-Nerion** [comment]
Danke
Habe nun mal die beiden Änderungen in der Search.php vorgenommen. Hoffentlich ist das Problem damit behoben.

**Comment by leofeyer** [comment]
Falls nicht, bitte nochmal hier melden. 😉

**Comment by UH-Nerion** [comment]
Hallo,
leider ist das Problem heute wieder aufgetaucht, nachdem jetzt einige Tage Ruhe war.
Ein aktualisieren der Webseite hat geholfen, dennoch wurde folgender Fehler im error_log protokolliert:

`[15-Sep-2016 09:54:23 GMT] PHP Fatal error: Uncaught exception 'Exception' with message 'Query error: Duplicate entry 'ab5ea4d5eaafe3b224e7af60063410d2-123' for key 'checksum_pid' (UPDATE tl_search SET tstamp=1473933263,....`

**Comment by leofeyer** [comment]
Wenn Du im Backend eingeloggt bist, sollte überhaupt nichts indiziert werden.

**Comment by fritzmg** [comment]
> Wenn Du im Backend eingeloggt bist, sollte überhaupt nichts indiziert werden.

Ich denke er meinte es passiert, wenn er das Frontend aufruft, während er im Backend eingelogged ist (in einem anderen Tab bspw.)

**Comment by UH-Nerion** [comment]
Ja genau @fritz

**Comment by leofeyer** [comment]
> Ich denke er meinte es passiert, wenn er das Frontend aufruft, während er im Backend eingelogged ist (in einem anderen Tab bspw.)

Ja, das meine ich auch. Solange `BE_USER_LOGGED_IN` gleich `true` ist, sollte weder in den Cache noch in den Suchindex geschrieben werden.

**Comment by UH-Nerion** [comment]
Ich kann euch nur berichten was ich festgestellt habe. Warum das so ist, weiß ich leider nicht :-)

**Comment by fritzmg** [comment]
@leofeyer Der Suchindex wird immer aufgebaut wenn das Frontend aufgerufen wird, egal ob man im Backend eingelogged ist oder nicht.

**Comment by fritzmg** [comment]
`$this->getLoginStatus('BE_USER_AUTH')` (in the constructor of `FrontendIndex`) seems to return `false`, even though you are logged into the backend and the cookie exists.

**Comment by antilet** [comment]
> Ja, das meine ich auch. Solange  BE_USER_LOGGED_IN  gleich  true  ist, sollte weder in den Cache noch in den Suchindex geschrieben werden.
Der Fehler tritt/trat sogar bei Frontendvorschau auf...
(wie es nach den o.g. Änderungen aussieht, weiß ich nicht.)

**Comment by fritzmg** [comment]
It's because of this part of `getLoginStatus`:
```php
// Disable the cache if a back end user is logged in
if (TL_MODE == 'FE' && $strCookie == 'BE_USER_AUTH')
{
	$_SESSION['DISABLE_CACHE'] = true;

	// Always return false if we are not in preview mode (show hidden elements)
	if (!\Input::cookie('FE_PREVIEW'))
	{
		$_SESSION['TL_USER_LOGGED_IN'] = false; // backwards compatibility
		return false;
	}
}
```
This is actually legacy code since `$_SESSION['DISABLE_CACHE'] = true;` does not have any effect (see #8249). Since this part of the code returns `false` the search index will be generated as usual while being logged into the backend.

**Comment by leofeyer** [comment]
> @leofeyer Der Suchindex wird immer aufgebaut wenn das Frontend aufgerufen wird, egal ob man im Backend eingelogged ist oder nicht.

Nein, in der Frontend-Vorschau (show unpublished elements) wird der Suchindex nicht aufgebaut.

**Comment by leofeyer** [comment]
> @leofeyer Der Suchindex wird immer aufgebaut wenn das Frontend aufgerufen wird, egal ob man im Backend eingelogged ist oder nicht.

Nein, in der Frontend-Vorschau (show unpusblished elements) wird nichts indiziert.

**Comment by fritzmg** [comment]
> Nein, in der Frontend-Vorschau (show unpusblished elements) wird nichts indiziert.

Ja, in der Frontend-Vorschau nicht, sonst jedoch schon.

**Comment by fritzmg** [comment]
@UH-Nerion dein Problem konnte ich aber bisher nicht reproduzieren.

**Comment by ausi** [comment]
I think this can be fixed with this PR: #8647
