### ISSUE TITLE
On selecting fields within editAll act, checkbox label for fields without translation should not be blank

### ISSUE THREAD

**Issue by fatcrobat** [contao/core#8461]
As mentioned in the title, when selecting the fields in "editAll" act, the label for fields without translations should not be blank. Can you please output the field name in this case? In module development phase, or when login with non translated language, you dont know what field you should select.

![themes innovation fund front end modules edit multiple - contao open source cms 3 5](https://cloud.githubusercontent.com/assets/480054/18303689/a1c7e7d2-74de-11e6-8156-fcfba31017bb.jpg)

Tested with contao 3.5.14.

Thanks for your efforts.

**Comment by leofeyer** [comment]
Fixed in a9388f666414ad9320517a5518dfc7b88ca3f89b.
