### ISSUE TITLE
Backend Toggle Subpalette wird nicht versioniert

### ISSUE THREAD

**Issue by Mynyx** [contao/core#8463]
Wird im Backend eine Subpalette aktiviert/deaktiviert z. B. Seitenlayout Option "jQuery laden" oder Artikel Option "Artikel schützen" wird dies nicht versioniert.

**Comment by Mynyx** [comment]
Sollte das aktivieren/deaktivieren einer Subpalette überhaupt zu einer Änderung des Datensatzes führen?

IMHO sollte dies erst geschehen, wenn der Datensatz explizit gespeichert wird.

**Comment by KaiserCh** [comment]
Das Häkchen für die Palette ist ein Feld in der Datenbank und hat i.d.R. außerdem noch submitOnChange. Also ja, es sollte meiner Meinung nach versionieren.
Das macht sogar unter Umständen richtig viel aus: Stell dir mal vor, du hattest ursprünglich ein ce_text mit Bild, und möchtest jetzt kein Bild mehr. Das einzige Feld, das sich ändert, ist addImage, aber die Wirkung ist gewaltig. Würde man danach explizit "Speichern" drücken, würde die Änderung an addImage sicherlich versioniert, aber bereits das Setzen oder Entfernen des Häkchens ändert den Datensatz in der DB.

**Comment by backbone87** [comment]
Der datensatz sollte erst mit einem click auf "speichern" in die DB geschrieben werden, so wie es z.B. der DC_General oder auch meine (inzwischen abandoned) DC_TableExtended gemacht hat.

Auch die save_callbacks der felder sollten NICHT dazu verwendet werden, daten in die DB zu schreiben, dies sollte erst im onsubmit callback der table geschehen. aber daran halten sich viele erweiterungen und auch der core selbst nicht.

**Comment by KaiserCh** [comment]
Der aktuelle Status Quo ist: Subpaletten werden über submitOnChange aktiviert/deaktiviert. Das ist faktisch identisch mit "Speichern". So machts der Core, so machens fast alle Extensions. submitOnChange ist auch kein save_callback, sondern würde selbige höchstens triggern.
Es wäre nur konsequent, wenn auf den Änder-Submit auch das komplette Programm an Speicher-Routinen zünden würde, und da gehört Versionierung dazu.

**Comment by Mynyx** [comment]
Ja, deshalb habe ich ja auch das Ticket erstellt ;-)

Jedoch finde ich es ergänzend auch diskussionswürdig, dass das Aktivieren/Deaktivieren einer Subpalette bereits zu einer Änderung in der Datenbank führt. Zunächst sollte nur die Subpalette eingebelendet/ausgeblendet werden, die Änderung in der Datenbank sollte dann erst beim speichern erfolgen.

**Comment by asaage** [comment]
Für mich eher wieder ein Argument gegen ```submitOnChange```
wie bereits [hier](https://github.com/contao/core/issues/8286#issuecomment-200764620)

**Comment by backbone87** [comment]
> Es wäre nur konsequent, wenn auf den Änder-Submit auch das komplette Programm an Speicher-Routinen zünden würde, und da gehört Versionierung dazu.

Das geht nicht, weil für submitOnChange fehlermeldungen deaktiviert werden. ein weiterer höchstkritischer punkt, weil somit potentiell fehlerhafte daten in die DB geschrieben werden.

**Comment by leofeyer** [comment]
Wie in Mumble am 6. Oktober besprochen, ist das eine "Nebenwirkung" einer bereits bekannten Einschränkung (Datensatz sollte erst gespeichert werden, wenn alle Felder ausgefüllt sind und "Speichern" geklickt wurde), die sich nur beheben lässt, wenn wir den DC_Table neu schreiben.
