### ISSUE TITLE
Inserttag in field "page name" not being stripped from search index

### ISSUE THREAD

**Issue by arno1979** [contao/core#8464]
When using the inserttag "lang" in the field "page name" of the page properties form the inserttag is not being processed correctly or stripped from the search index.

Example:
Value entered in the field "page name":
`{{lang::en}}Testpage{{lang}}`

Text displayed as search result:
Testpage">Testpage [100.00% Relevanz]
lang::en}}Testpage Test Mack Test: Page

Values stored in database table tl_search:
title: `{{lang::en}}Testpage{{lang}}`
text: `{{lang::en}}Testpage{{lang}} Test Mack Test: Page`

See also:
https://community.contao.org/de/showthread.php?63869-Inserttag-im-Seitenname-Probleme&p=419091#post419091

**Comment by leofeyer** [comment]
Fixed in f5cb7b9292724573ece3855ff4ff03a1027bd0c7.

**Comment by arno1979** [comment]
Thanks for fixing this. I just tested this again with 3.5.17. Although the insert tags now gets correctly stripped from the "page name" field the same result appears again when entering a value with insert tags in the field "page title".
Sorry for not noticing this earlier but I think I couldn't have noticed it, because the effect of course appeared whether "page title" was filled or not.
Shall I open a new ticket for this or will this one simply be reopened?
Thanks for your help!

**Comment by arno1979** [comment]
I'm sorry but I have to write again because this is getting really weird.
After I checked this morning everything seemed to be working fine when just entering a page name including an insert tag (like I described in my comment above.

Just now I went back to the project to do some further testing and the error that was supposedly fixed with https://github.com/contao/core/commit/15c617489608c84f11dfb92a5b13aa5304eaeaf7 is back.

So I did some more digging and I think I'm on to something:
The title of the search result is fine. But the context is where the insert tag is still visible. Just now I realized that it's not the complete insert tag. This is also visible in the example values of my initial post of this issue; the displayed context looks like this:
`lang::de}}Deutsch Informationen auf deutsch Ich denke, du musst nach Installation der`
In your fix you added the strip_insert_tags function to the title field only.
I therefore tried to apply it to the context field as well but no effect is visible. As you can see from the example above the opening `{{` are missing. I think that's probably the reason why strip_insert_tags is not working at this point. By the way: the closing `{{lang}}` part gets stripped successfully.

I think there is more than one solution to the problem:
- Strip the insert tags before they are written to the database when indexing the page.
This would result in a clean output without having to deal with the insert tags in ModuleSearch.php.
On the other hand (at least in the case of the language insert tag) the desired language identification – which in my opinion should be present in the search result – gets lost.
- The more difficult (as I suspect) solution would be to keep the tags in the database field of tl_search (as it is done now) and take care of not cutting the insert tags when generating the context field in ModuleSearch.php probably somewhere around line 277.

I hope this helps.

**Comment by leofeyer** [comment]
How exactly do I reproduce the issue?

**Comment by arno1979** [comment]
Here are the relevant data from my test environment:
1. I created a new page and entered `{{lang::en}}Testpage{{lang}}` into page name.
2. Settings for the search engine module are:
find any word, fuzzy search, context lenght = 100, total length = 1000
3. Empty the search index, do not reindex.
4. Load the new page manually once and make sure an entry for the new page is added to tl_search.
My entry looks like this:
title = `{{lang::en}}Testpage{{lang}}`
text = `{{lang::en}}Testpage{{lang}} Zur Erhebung von Besucherstatistiken wird das Programm Piwik verwendet. Hier können Sie der Erfassung Ihrer Daten widersprechen.`
5. Execute a search using `testpage` as query string.
The html for my result looks like this (I'm still using XHTML):
`<h3><a href="http://blickpunkt-auge.vvv/testpage.html" title="Testpage"><span xml:lang="en" lang="en">Testpage</span></a> <span class="relevance">[100.00% Relevanz]</span></h3><p class="context">lang::en}}<span class="highlight">Testpage</span> Zur Erhebung von Besucherstatistiken wird das Programm Piwik verwendet. Hier können Sie der</p>`

The problem lies within the `<p class="context">`. As the insert tag is the first thing in the text column it gets chopped while the context is generated by ModuleSearch.php and does not get replaced correctly.

Let me know if I can be of any help.

**Comment by leofeyer** [comment]
Fixed in e4aaf51d7f0c0295ea505efe705d6c82869958c2.
