### ISSUE TITLE
Datei-Upload mit Standard-Uploader 

### ISSUE THREAD

**Issue by Mynyx** [contao/core#8466]
Wird in der Dateiverwaltung mit dem Standard-Uploader eine Datei eines nicht zugelassenen Dateitypes hochgeladen, erscheinen die folgenden beiden Fehlermeldungen:
>Der Dateityp "bmp" darf nicht hochgeladen werden!
>Bitte wählen Sie mindestens eine Datei aus!

Die zweite Fehlermeldung ergibt jedoch keinen Sinn, es wurde schließlich eine Datei ausgewählt. Diese Meldung sollte nicht angezeigt werden werden, wenn zuvor bereits ein anderer Fehler aufgetreten ist.

**Comment by leofeyer** [comment]
Behoben in 9e4854afe8e3b3d73a65d15c83a6bdf016afb0ec.
