### ISSUE TITLE
Datei-Upload mit DropZone

### ISSUE THREAD

**Issue by Mynyx** [contao/core#8467]
Wird in der Dateiverwaltung mit dem DropZone-Uploader eine Datei eines nicht zugelassenen Dateitypes hochgeladen, wird zum einen der Dateiname nur eingeblendet, wenn das Symbol mit der Maus überfahren wird (bei erfolgreich hochgeladenen Dateien ist der Dateiname permanent sichtbar) und wird dabei jedoch von der ebenfalls eingeblendeten Fehlermeldung überdeckt, sodass es sinnvoller erscheinen würde bei fehlgeschlagenen Uploads den Dateinamen ebenfalls permanent anzuzeigen und zum anderen ist die eingeblendete Fehlermeldung "You can't upload files of this type." nicht übersetzt.

**Comment by leofeyer** [comment]
Siehe zum Thema "DropZone" auch #8385.

**Comment by leofeyer** [comment]
Ich habe Dropzone in contao/core-bundle@720f284786cc0e7bb62928278c97f163beb6f9e5 auf Version 4 aktualisiert, die den Fehler behebt.
