### ISSUE TITLE
Dateiverwaltung Umlaute Dateinamen

### ISSUE THREAD

**Issue by Mynyx** [contao/core#8469]
In der Dateiverwaltung können Dateien mit Umlauten im Dateinamen erfolgreich hochgeladen werden. Der Dateinamen wird dabei auch nicht verändert.

Bearbeitet man jedoch den Dateinamen einer solche Datei indem man beispielsweise noch einen zusätzlichen Buchstaben anfügt, werden automatisch Umlaute mit der jeweiligen Entsprechung ersetzt.

**Comment by asaage** [comment]
https://github.com/contao/core/issues/8295
