### ISSUE TITLE
Fehlerhafte SVG-Datei führt zu PHP Error bei Aufruf der Dateiverwaltung

### ISSUE THREAD

**Issue by Mynyx** [contao/core#8470]
Eine fehlerhafte SVG-Datei führt zu einem PHP Error bei Aufruf der Dateiverwaltung. Zur Reproduktion beispielsweise das letzte ````>```` in einer SVG-Datei löschen.

````
[10-Sep-2016 09:13:28 Europe/Berlin] 
PHP Warning: DOMDocument::loadXML(): expected '&gt;' in Entity, line: 260 in /www/htdocs/xxx/contao/system/modules/core/library/Contao/File.php on line 261
#0 [internal function]: __error(2, 'DOMDocument::lo...', '/www/htdocs/xxx...', 261, Array)
#1 /www/htdocs/xxx/contao/system/modules/core/library/Contao/File.php(261): DOMDocument->loadXML('<svg xmlns="htt...')
#2 /www/htdocs/xxx/contao/system/modules/core/library/Contao/File.php(303): Contao\File->__get('imageSize')
#3 /www/htdocs/xxx/contao/system/modules/core/library/Contao/File.php(351): Contao\File->__get('imageViewSize')
#4 /www/htdocs/xxx/contao/system/modules/core/drivers/DC_Folder.php(2453): Contao\File->__get('viewHeight')
#5 /www/htdocs/xxx/contao/system/modules/core/drivers/DC_Folder.php(308): Contao\DC_Folder->generateTree('/www/htdocs/xxx...', 0, false, false, false)
#6 /www/htdocs/xxx/contao/system/modules/core/classes/Backend.php(650): Contao\DC_Folder->showAll()
#7 /www/htdocs/xxx/contao/system/modules/core/controllers/BackendMain.php(131): Contao\Backend->getBackendModule('files')
#8 /www/htdocs/xxx/contao/contao/main.php(20): Contao\BackendMain->run()
#9 {main}

[10-Sep-2016 09:13:28 Europe/Berlin] PHP Fatal error:  Call to a member function getAttribute() on null in /www/htdocs/xxx/contao/system/modules/core/library/Contao/File.php on line 266
````

**Comment by leofeyer** [comment]
Ja klar, die Datei ist ja auch fehlerhaft. Was sollte Deiner Meinung nach passieren?

**Comment by Mynyx** [comment]
Ein Zugriff auf die Dateiverwaltung ist wegen des Fatal Error nicht mehr möglich. (Also nicht nur das Bearbeiten der spezifischen Datei sondern die gesamte Dateiverwaltung.)

Es sollte zuerst die Datei auf Validität geprüft werden bevor Operationen durchgeführt werden, die zu einem PHP Error führen. Man könnte auch nach Alternativen für die verwendeten Funktionen sehen, die eine Fehlerhandling mit Exceptions haben, damit man diese abfangen könnte.

**Comment by fritzmg** [comment]
Errorneous JPGs cause fatal errors as well currently, don't they?

**Comment by discordier** [comment]
The fatal is a follow up error. We have to check if the resource is null before using it.

**Comment by Mynyx** [comment]
Der Rückgabewert der Funktion gibt auch Auskunft darüber, ob Fehler aufgetreten sind, sodass eine Lösung wie folgt aussehen könnte: ````if (@$doc->loadXML(...````

http://php.net/manual/en/domdocument.loadxml.php#refsect1-domdocument.loadxml-returnvalues

**Comment by leofeyer** [comment]
Geändert in d59ea0ec551616c5387fd0dc8a6bc2993168ef75.
