### ISSUE TITLE
Dateigröße wird bei dimensionslosen SVG-Dateien in der Dateiverwaltung nicht angezeigt

### ISSUE THREAD

**Issue by Mynyx** [contao/core#8471]
In der Dateiverwaltung wird in der Übersicht bei dimensionslosen SVG-Dateien die Dateigröße nicht angezeigt.

Siehe https://github.com/contao/core/blob/master/system/modules/core/drivers/DC_Folder.php#L2453-L2483

**Comment by ausi** [comment]
See #8483
