### ISSUE TITLE
Übersetzungsfehler im Backend - Erweiterungskatalog

### ISSUE THREAD

**Issue by LukasMusilek** [contao/core#8473]
In der Version 3.5.15 wird im Backend im Modul Erweiterungskatalog ein Filterfeld mit "Staat" betitelt - es sollte wohl "Status" heißen. 
![staat](https://cloud.githubusercontent.com/assets/22133345/18418644/907f951e-784a-11e6-89cb-c177e943c911.png)

**Comment by leofeyer** [comment]
Ich habe die Übersetzung auf Transifex entsprechend aktualisiert.

**Comment by Aybee** [comment]
Ich weiß nicht, ob du das gesehen hast, aber es gibt bereits eine Variable für Status. Hast du jetzt der Variable `state` `Status` zugeordnet?

`$GLOBALS['TL_LANG']['tl_repository']['state'] = 'State';`
https://github.com/contao/core/blob/master/system/modules/repository/languages/en/tl_repository.xlf#L200
`$GLOBALS['TL_LANG']['tl_repository']['status'] = 'Status';`
https://github.com/contao/core/blob/master/system/modules/repository/languages/en/tl_repository.xlf#L338

**Comment by LukasMusilek** [comment]
Sollen solche Übersetzungsfehler generell hier gepostet werden oder gibt es da eine geeignetere Stelle?

**Comment by leofeyer** [comment]
Nein, hier passt schon. 😄

**Comment by asaage** [comment]
was ich regelmäßig über langconfig ändere:
```
$GLOBALS['TL_LANG']['MSC']['printAsPdf'] = "Artikel als PDF speichern";
```
weil ich immer wieder gefragt werde, warum der Drucker nicht anspringt bei...
"Artikel als PDF drucken" :smile:

**Comment by leofeyer** [comment]
Guter Hinweis. Hab ich in c8c3991c06af318883cae7a0fb7f3eaff968c897 geändert.
