### ISSUE TITLE
show page status at rebuild search index if status not 200

### ISSUE THREAD

**Issue by zonky2** [contao/core#8476]
if we rebuild the search index and its not possible to retive the page, we should set the color at red and note the staus e.g. "404 Not found"

at this time is every page "green"

![shot277](https://cloud.githubusercontent.com/assets/1045318/18464752/392e9c02-7993-11e6-89cd-4a563295483b.jpg)

**Comment by fritzmg** [comment]
Duplicate of  https://github.com/contao/core/issues/8255

**Comment by zonky2** [comment]
thx & sorry ;-)
