### ISSUE TITLE
Dateiverwaltung legt bei Dateioperationen keine Version an

### ISSUE THREAD

**Issue by Mynyx** [contao/core#8479]
Die Dateiverwaltung legt bei Dateioperationen wie Upload, Neuer Ordner, Kopieren und Verschieben keine Versionen an.

**Comment by leofeyer** [comment]
Wieso sollte das Deiner Meinung nach anders ein?

**Comment by Mynyx** [comment]
Weil bei Änderungen an einer versionierten Tabelle stets eine neue Version angelegt werden sollte.

**Comment by fritzmg** [comment]
Die Datenverwaltung versioniert aber keine Dateien, daher bringt es auch nichts die Tabelle zu Versionieren.

**Comment by Mynyx** [comment]
Dann sollte die Tabelle tl_files nicht versioniert werden. Derzeit wird sie das aber.

**Comment by fritzmg** [comment]
Warum schreibst du das eigentliche Problem dann nicht einfach in dein Ticket? :wink:

**Comment by Mynyx** [comment]
Vielleicht reden wir gerade ein bisschen aneinander vorbei ;-)

Die Funktionen "Datei bearbeiten" und "Quelltexteditor" versionieren derzeit Änderungen und es ist auch möglich Änderungen wiederherzustellen, auch bezogen auf den Dateiinhalt bei über den Quelltexteditor bearbeiteten Dateien.

Nicht möglich ist es eine gelöschte Datei wiederherzustellen, siehe #8480.

Von Dateien, die unbenannt wurden, eine frühere Version wiederherzustellen führt auch zu Problemen, dazu wäre dann ggf. noch ein Ticket zu erstellen. Wobei das mit diesem Ticket in einem gewissen Zusammenhang steht, denn beim Verschieben ist man da letztlich wieder beim gleichen Problem.

**Comment by leofeyer** [comment]
Wie genau lässt sich das in der Onlinedemo reproduzieren?

**Comment by leofeyer** [comment]
Ich verstehe das Problem nicht. Wieso sollte beim Verschieben einer Datei eine neue Version angelegt werden? Dadurch ändert sich ja der Inhalt nicht.

In der Seitenstruktur wird beim Verschieben auch keine neue Version angelegt.

**Comment by Mynyx** [comment]
Weil bei jeder Änderungen an einer versionierten Tabelle stets eine neue Version angelegt werden sollte. Ansonsten würde das Prinzip Versionierung doch ad absurdum geführt werden. Denn die nicht versionierte Änderung wird ja der nächsten erstellten Version zugerechnet.

Wenn also ein Benutzer eine Datei oder auch Seite verschiebt und der nächste Benutzer dann beispielsweise den Seitentitel ändert, wird die Änderung der Position der Seite dann der Version, welche die Änderung vom zweiten Benutzer erstellt wird, zugerechnet. Macht dieser nun seine Änderung des Seitentitels durch das wiederherstellen der vorherigen Version rückgängig, macht er damit gleichzeitig ungewollt auch die Änderung der Position rückgängig.

**Comment by asaage** [comment]
> In der Seitenstruktur wird beim Verschieben auch keine neue Version angelegt.

Klingt für mich auch irgendwie nicht richtig.

**Comment by leofeyer** [comment]
Wie in Mumble am 6. Oktober diskutiert, versionieren wir in Contao nur Inhalte und keine Strukturen und das möchten wir auch so beibehalten.
