### ISSUE TITLE
Versionsübersicht verweist bei gelöschten Dateien auf Wiederherstellung

### ISSUE THREAD

**Issue by Mynyx** [contao/core#8480]
Die Versionsübersicht auf der Startseite des Backends verweist bei gelöschten Dateien mit dem entsprechenden Icon auf die Wiederherstellung. Eine Wiederherstellung ist bei Dateien jedoch nicht möglich.

**Comment by leofeyer** [comment]
Behoben in 009123ea5589dc36d6ab52fc665aef00a9eebd29.
