### ISSUE TITLE
Dateiverwaltung Versionsvergleich von im Quelltexteditor bearbeiteten Dateien nach Versionwiederherstellung

### ISSUE THREAD

**Issue by Mynyx** [contao/core#8481]
1. Eine im Quelltexteditor bearbeitbare Datei z. B. CSS hochladen
2. Die Datei im Quelltexteditor bearbeiten
3. Die erste Version widerherstellen
4. Versionsvergleich/Unterschiede anzeigen aufrufen
5. Es wird nun fehlerhaft angezeigt "Die beiden ausgewählten Versionen sind identisch."
6. Button Unterschiede anzeigen anklicken, jetzt wird ein korrekter Versionsvergleich angezeigt

**Comment by leofeyer** [comment]
Behoben in 6f142035a6437b8fb30d9efccad3b9f42154df35.
