### ISSUE TITLE
Search crashes while indexing different url for same page id

### ISSUE THREAD

**Issue by eknoes** [contao/core#8482]
**Reproduce**

- Go to [http://demo.contao.org/en/](http://demo.contao.org/en/)
- Open Demo Home Page with different url [http://demo.contao.org/en/index.html](http://demo.contao.org/en/index.html)
- See the crash

**Cause**
[\Contao\Search::indexPage(197)](https://github.com/contao/core/blob/master/system/modules/core/library/Contao/Search.php#L197) just checks for entries with the same url and Page id and inserts a new entry because it does not find anything. But Page ID and checksum have to be unique, so there is a Database Error because the checksum is the same.

**History**
This bug was introduced with Contao 3.5.16 fccd6822adb8177209b37a41af3b042f70442ea9

**Fix**
On my contao instance I just changed [Line 197](https://github.com/contao/core/blob/master/system/modules/core/library/Contao/Search.php#L197) to 

    $objIndex = $objDatabase->prepare("SELECT id FROM tl_search WHERE url=? AND pid=? OR pid=? AND checksum=?")
    ->limit(1)
    ->execute($arrSet['url'], $arrSet['pid'],  $arrSet['pid'],  $arrSet['checksum']);

But I did not deal with the search yet, so I do not know the impact on the index page yet.

**Comment by fritzmg** [comment]
Duplicate of #8460

**Comment by eknoes** [comment]
Sorry, I missed that.
