### ISSUE TITLE
DC_Table Filter Timestamp Optimierung

### ISSUE THREAD

**Issue by Mynyx** [contao/core#8485]
In DC_Table werden zur Generierung eines Filters nach Datum sämtliche verschiedene Timestamps aus der Datenbank abgerufen.

Tatsächlich benötigt werden jedoch nur sämtliche verschiedene Datumsangaben.

Ändert man so beispielsweise die Abfrage ````SELECT DISTINCT  `tstamp` FROM  `tl_log` ```` in ````SELECT DISTINCT UNIX_TIMESTAMP(FROM_UNIXTIME(`tstamp` , '%Y-%m-%d')) AS  `tstamp` FROM  `tl_log` ```` verkürzt sich die Skriptlaufzeit bei großen Tabellen um mehrere Sekunden.

**Comment by leofeyer** [comment]
Das kann ich nicht nachvollziehen. Bei mir dauert die Unix-Zeitstempel-Umwandlung deutlich länger:

<img width="469" src="https://cloud.githubusercontent.com/assets/1192057/18664829/9ff3f9be-7f24-11e6-978a-091df4074ec7.png">

<img width="676" src="https://cloud.githubusercontent.com/assets/1192057/18664838/a736eeca-7f24-11e6-8ccf-39c4bc36bb84.png">

**Comment by leofeyer** [comment]
@contao/developers @KaiserCh /cc

**Comment by KaiserCh** [comment]
Ja, der DB Query dauert signifikant länger, aber andererseits ist die Ergebnismenge auch deutlich kleiner. Ich hab hier z.B. ein Log, das nur Werte von einem Tag enthält, aber davon eben einige hundert Stück. Der alte Code hat den schnelleren Query, gibt dafür aber auch einige hundert Ergebnisse. Der langsamere Code bringt ein einzelnes Ergebnis.
Bei sehr intensiv genutzten Projekten mit tausenden Log-Einträgen in wenigen Tagen ist es durchaus möglich, dass der SQL-Zeitverlust geringer ist, als die PHP-Laufzeit, die durch gesparte Schleifen frei wird. 
Beispiel, 4000 Log-Einträge in 4 Tagen:
Variante 1: 4000 Foreach-Durchläufe in DC_Table
Variante 2: 4 Durchläufe

Ziemlich grenzwertig. Wirklich Power kriegt man da nur durch einen Wechsel weg von tstamp-Integern hin zu echten Dates, aber das fällt hier flach.

**Comment by Mynyx** [comment]
Die Skriptlaufzeit verkürzt sich, da anschließend erheblich weniger Datensätze verarbeitet werden müssen.

Die Laufzeit der Datenbankabfrage selbst verkürzt sich nicht.

**Comment by leofeyer** [comment]
> Ziemlich grenzwertig. Wirklich Power kriegt man da nur durch einen Wechsel weg von tstamp-Integern hin zu echten Dates, aber das fällt hier flach.

Vielen Dank für Deine Analyse. Das mit den Date-Feldern sehe ich genauso wie Du.

> Die Skriptlaufzeit verkürzt sich, da anschließend erheblich weniger Datensätze verarbeitet werden müssen.

Ich mache dazu auch nochmal einen Test.

**Comment by Mynyx** [comment]
Der Vorteil bei der Skriptlaufzeit liegt ungefähr bei einer Sekunde pro 100.000 Datensätze in tl_log.

Vermutlich wird man da bei 892 Datensätzen noch keinen Unterschied messen können?

**Comment by leofeyer** [comment]
Wie in Mumble am 6. Oktober besprochen, wollen wir diese Optimierung implementieren. Allerdings müssen wir berücksichtigen, dass wir nicht nur Tag-Filter haben, sondern auch Monat und Jahr.

**Comment by leofeyer** [comment]
Implementiert in ce20bee3f6cc27a42250a04f91bf225d27760103.
