### ISSUE TITLE
Formulargenerator Feld Duplizieren Feldname ungültig

### ISSUE THREAD

**Issue by Mynyx** [contao/core#8487]
Wenn man im Formulargenerator ein Feld mit Feldnamen (z. B. Select-Menü) dupliziert, ist der generierte Feldname "Beispiel (Kopie)" ungültig, da der Feldname keine runde Klammern enthalten darf.
Das Leerzeichen ist außerdem auch nicht zulässig, wird aber beim Speichern in einen Unterstrich umgewandelt.

**Comment by leofeyer** [comment]
Es gibt aber keine Möglichkeit, das Feld mit dem ungültigen Namen zu speichern, insofern sehe ich hier kein Problem. Im Grunde ist es sogar gut, dass hier eine Fehlermeldung erscheint, wenn man vergisst, den Feldnamen zu ändern.

**Comment by BugBuster1701** [comment]
@Mynyx Wenn dich das stört, dann kannste das "(Kopie)" auch wegnehmen, dazu in der langconfig.php:

`$GLOBALS['TL_LANG']['MSC']['copyOf'] = '%s';`

oder falls du den Hinweis haben willst aber gültig:

`$GLOBALS['TL_LANG']['MSC']['copyOf'] = '%s_Kopie';`
