### ISSUE TITLE
Problem seit Update auf 3.5.16 Fatal error: Uncaught exception Exception with message Query error: Duplicate entry 

### ISSUE THREAD

**Issue by Malunke** [contao/core#8489]
Hallo,

ich habe seit dem Update auf 3.5.16 folgendes Problem:

```
Fatal error: Uncaught exception Exception with message Query error: Duplicate entry 'd9c450f04e27b856fd068ff86c051249-43' for key 'checksum_pid' (INSERT INTO tl_search (tstamp, url, title, protected, filesize, groups, pid, language, text, checksum) VALUES (1474006441, 'XXX', 'Home', '', '69.91', 0, '43', 'de', 'Home XXXX. , XXXX', 'd9c450f04e27b856fd068ff86c051249')) thrown in system/modules/core/library/Contao/Database/Statement.php on line 295

#0 system/modules/core/library/Contao/Database/Statement.php(264): Contao\Database\Statement->query()
#1 system/modules/core/library/Contao/Search.php(214): Contao\Database\Statement->execute()
#2 system/modules/core/classes/FrontendTemplate.php(330): Contao\Search::indexPage(Array)
#3 system/modules/core/classes/FrontendTemplate.php(124): Contao\FrontendTemplate->addToSearchIndex()
#4 system/modules/core/pages/PageRegular.php(190): Contao\FrontendTemplate->output(true)
#5 system/modules/core/controllers/FrontendIndex.php(285): Contao\PageRegular->generate(Object(Contao\PageModel), true)
#6 index.php(20): Contao\FrontendIndex->run()
#7 {main}
```

Wenn ich dieses Seitenelement bearbeite und abspeichere, ist der Fehler verschwunden. Bei einer weiteren Bearbeitung kommt der Fehler jedoch wieder. Ich glaube beim Löschen aller Caches und Indizes ist der Fehler auch erstmal weg, wenn Cache und Index wieder aufgebaut werden, kommt der Fehler aber auch wieder.

Ein Downgrade auf 3.5.15 behebt das Problem sofort.

**Comment by fritzmg** [comment]
Duplicate of #8640

**Comment by Malunke** [comment]
Vielen Dank, konnte über die Suche #8460 jedoch nicht finden bzw. dem selben Fehler zuordnen.

2 Fragen: 

Ist das Problem nun behoben, #8460 scheint ja sporadisch immer noch aufzutreten?

Sollte die fehlerhafte Änderung nicht lieber aus dem Update 3.5.16 entfernt werden und erst mit 3.5.17 ohne Fehler umgesetzt werden?

Vielen Dank

**Comment by fritzmg** [comment]
Contao 3.5.16 ist ja bereits released, es kann nicht mehr entfernt werden.

**Comment by barrystaes** [comment]
Hi guys. I tried translating the German here.. but i still wonder.. has this been fixed in 3.5.17?

I'm having this problem in a new Contao 3.5.16 installation. But this error is not always shown on the frontpage.

**Comment by leofeyer** [comment]
> has this been fixed in 3.5.17?

Yes.
