### ISSUE TITLE
DB SQL tl_files.path varchar(1022) bigger than max_key_length for index.

### ISSUE THREAD

**Issue by barrystaes** [contao/core#8490]
After a clean install of Contao 3.5.15 **(via Installatron)** visiting `install.php` says:
```
database is not up-to-date!

ALTER TABLE `tl_files` CHANGE `path` `path` varchar(1022) NOT NULL default '';
ALTER TABLE `tl_files` DROP INDEX `path`, ADD KEY `path` (`path`(333));

[ Update database ]
```
Initially it showed more queries but it processed those OK with that button.

These two remain and result in these respective fatal error messages:
```
Fatal error: Uncaught exception Exception with message Query error: Specified key was too long; max key length is 1000 bytes (ALTER TABLE `tl_files` CHANGE `path` `path` varchar(1022) NOT NULL default '';) thrown in system/modules/core/library/Contao/Database/Statement.php on line 295
#0 system/modules/core/library/Contao/Database.php(207): Contao\Database\Statement->query('ALTER TABLE `tl...')
#1 system/modules/core/controllers/BackendInstall.php(616): Contao\Database->query('ALTER TABLE `tl...')
#2 system/modules/core/controllers/BackendInstall.php(177): Contao\BackendInstall->adjustDatabaseTables()
#3 contao/install.php(24): Contao\BackendInstall->run()
#4 {main}

Fatal error: Uncaught exception Exception with message Query error: Incorrect prefix key; the used key part isn't a string, the used length is longer than the key part, or the storage engine doesn't support unique prefix keys (ALTER TABLE `tl_files` DROP INDEX `path`, ADD KEY `path` (`path`(333));) thrown in system/modules/core/library/Contao/Database/Statement.php on line 295
#0 system/modules/core/library/Contao/Database.php(207): Contao\Database\Statement->query('ALTER TABLE `tl...')
#1 system/modules/core/controllers/BackendInstall.php(616): Contao\Database->query('ALTER TABLE `tl...')
#2 system/modules/core/controllers/BackendInstall.php(177): Contao\BackendInstall->adjustDatabaseTables()
#3 contao/install.php(24): Contao\BackendInstall->run()
#4 {main}
```

Related because similar to first error error:

- https://github.com/contao/core/issues/6462 fixed by https://github.com/contao/core/commit/2ae5acb4197701192ef96d229cbf2c9764459017 Remove the index from the `tl_style.selector` field
- http://stackoverflow.com/questions/3489041/mysqlerror-specified-key-was-too-long-max-key-length-is-1000-bytes

Chances are that Installatron caused/exposed this "Update database" problem, so i'll try a manual install to rule that out.

**Comment by fritzmg** [comment]
Are you using UTF8MB4?

**Comment by barrystaes** [comment]
@fritzmg when i search an export of the entire Contao database, there is no mention of `UTF8MB4`.
Does that answer your question, or where should i look?

**Comment by fritzmg** [comment]
In the Install Tool, under [i]Check database connection[/i] » [i]Character set[/i] and [i]Collation[/i] » [i]Collation[/i]

**Comment by barrystaes** [comment]
@fritzmg Ah ok.. thats says UTF8.

**Comment by fritzmg** [comment]
Then I guess more information about the database is needed. How was it created? With what collation?

**Comment by barrystaes** [comment]
I am not sure how Installatron creates the DB and user.. i'd say via either CLI, MySQL root user, or possibly the DirectAdmin API. I just asked that question at Installatron support.

And after that i believe it copies files and pokes `install.php`  (via HTTP POST) as if a user is entering the forms.

**Comment by leofeyer** [comment]
See #8484.
