### ISSUE TITLE
StringUtil.php + Notification center

### ISSUE THREAD

**Issue by Alibi-Contao** [contao/core#8491]
Habe im Notification center folgenden Code für die Email-Ausgabe eingegeben:

> {if form_rueckruf=="ja"}
> Weitere Mitteilungen:a
> {elseif form_aussendienst=="ja"}
> Weitere Mitteilungen:b
> {elseif form_angebot=="ja"}
> Weitere Mitteilungen:c
> {endif}
> 
> {if form_rueckruf=="ja"}
> - Um Rückruf wird gebeten.
> {endif}
> {if form_aussendienst=="ja"}
> - Ein Außendienst-Besuch ist gewünscht.
> {endif}
> {if form_angebot=="ja"}
> - Bitte schicken Sie mir ein Angebot.
> {endif}

Die Buchstaben a, b und c hinter "Weitere Mitteilungen:" dienen nur zur Kontrolle, welche Zeile in die Email verwendet wurde.
Ziel:
Wenn eine der Checkboxen aktivert wurde, soll die Zeile "Weitere Mitteilungen:"  (und darunter die entsprechenden Texte) in die Email geschrieben werden. 
Mit der "StringUtil.php" aus Contao 3.5.15 hat es funkioniert, mit der Fassung aus Contao 3.5.16 leider nicht mehr.
Wenn man unter 3.5.16 die erste und  die letzte Checkbox aktiviert, bekommt man das:
Weitere Mitteilungen:a
Weitere Mitteilungen:c
- Um Rückruf wird gebeten.
- Bitte schicken Sie mir ein Angebot.

Also zweimal "Weitere Mitteilungen:" 
Siehe auch hier: https://community.contao.org/de/showthread.php?63978-Frage-zum-Notification-center

**Comment by leofeyer** [comment]
Das Repo zum Notification Center ist hier: https://github.com/terminal42/contao-notification_center

**Comment by fritzmg** [comment]
It may be a bug with the new version of `\StringUtil::parseSimpleTokens()` introduced due to #8436 
But I guess it needs to be tested by someone from terminal42 first.

**Comment by Toflar** [comment]
This is not related to NC, if it is a bug, it's a Contao Core bug. I think the `elseif` is not skipped when the prepending `if` statement evaluates to `true`. I'll check this.

**Comment by Toflar** [comment]
Bug confirmed. Will submit a PR, pls reopen.

**Comment by Toflar** [comment]
This is the failing test to it: https://github.com/contao/core-bundle/pull/579

**Comment by ausi** [comment]
Bugfix pull request: contao/core-bundle#580

**Comment by leofeyer** [comment]
Thank you @Toflar and @ausi.
