### ISSUE TITLE
Frontend-Vorschau Bezeichnung "Frontend-Benutzer" statt "Mitglied"

### ISSUE THREAD

**Issue by Mynyx** [contao/core#8493]
In der Frontend-Vorschau ist das Eingabefeld für den Benutzernamen des Mitgliedes mit "Frontend-Benutzer" beschriftet. 

An allen anderen Stellen werden jedoch nur die Bezeichnungen "Mitglied" für Frontend-Benutzer und "Benutzer" für Backend-Benutzer verwendet.

Die Bezeichnung "Frontend-Benutzer" erscheint daher inkonsistent. Es wäre sinnvoll diese auf "Mitglied" zu ändern, so wüsste man direkt was gemeint ist.

**Comment by Aybee** [comment]
Dazu zählt auch die Rubrik für die FE-Module für Mitglieder, welche die Bezeichnung "Benutzer" hat.

**Comment by leofeyer** [comment]
> "Mitglied" für Frontend-Benutzer und "Benutzer" für Backend-Benutzer

Damit hast Du Dir die Frage selbst beantwortet. "Benutzer" und "Mietglied" sind lediglich Kurzformen für "Backend-Benutzer" und "Frontend-Benutzer". Es steht aber nirgends, dass wir die langen Formen nicht benutzen dürfen.

**Comment by Mynyx** [comment]
Natürlich darf man sie benutzen, die Frage wäre nur, ob das sinnvoll ist.

Da ansonsten - außer in der Tooltip-Erläuterung des Menüpunktes Mitglieder im Backend - nur die Kurzform verwendet wird, ist es für unerfahrene Benutzer nicht unmittelbar erkennbar, dass es sich um ein Synonym von Mitglied handelt.

**Comment by leofeyer** [comment]
Geändert in contao/core-bundle#1640.
