### ISSUE TITLE
Login shows message from previous page

### ISSUE THREAD

**Issue by barrystaes** [contao/core#8494]
The login dialog seems to show output (`tl_message`) that was shown on the previous page.

![image](https://cloud.githubusercontent.com/assets/1420588/18615643/2f4fb578-7dac-11e6-9f79-ce330dff6888.png)

This UI issue might not occur often, does no real harm, but might be easy to prevent and thats why i still report it.

Here is how i got this:

1. New Contao 3.5.16 installation, (manual)
2. in backend import a theme,  (browser window 1)
3. going to `install.php` to import the SQL file with an example site (browser window 2)
4. in backend tab which requires me to login again. (browser window 1)

I am not sure if i did a force-refresh myself (but i guess not) and think the backend page forwarded me to the login page after i clicked somewhere.

**Comment by leofeyer** [comment]
@contao/developers Is this a problem we should take care of?

**Comment by aschempp** [comment]
I doubt it. I think Symfony flash messages would work the same?

**Comment by leofeyer** [comment]
I guess so.

**Comment by Toflar** [comment]
No, flashbag messages are of a certain (arbitrary) type. So you could add ans fetch e.g. only the "contao.login" flashbag message.

**Comment by leofeyer** [comment]
As discussed in Mumble on October 6th, we do not think it is worth the effort to change this.
