### ISSUE TITLE
Module event reader missing raw variable of field "title"

### ISSUE THREAD

**Issue by Aybee** [contao/core#8496]
Im Event-Leser-Modul fehlt eine Variable, welche den direkten Inhalt des Feldes `tl_calendar_event.title` ausgibt.

Im Event-Listen-Modul kann man dies mit `$this->link` ausgeben.

Das fällt dann auf, wenn man das Feld modifiziert mit 

``` php
$GLOBALS['TL_DCA']['tl_calendar_events']['fields']['title']['eval']['allowHtml'] = true;
```

Man hat dann keine Chance über eine direkte Variable auf z.B.

``` html
<strong>Contao</strong> North-Day
```

zuzugreifen. 

Variablen, welche den Titel enthalten, allerdings mit specialchars(), sind

```
[title]          => &lt;strong&gt;Contao&lt;/strong&gt; North-Day
[linkTitle]      => &lt;strong&gt;Contao&lt;/strong&gt; North-Day
[picture][title] => &lt;strong&gt;Contao&lt;/strong&gt; North-Day
```

Eine Variable `$this->link` ist im Leser-Modul nicht vorhanden.

In der Online-Demo nicht reproduzierbar, weil dort kein Zugriff auf $GLOBALS['TL_DCA']. Nach der Modifikation des Feldes, im Titel eines Events HTML-Tags hinzugügen und im FE anschauen.

Siehe auch im Forum https://community.contao.org/de/showthread.php?63348-HTML-Tags-in-Event-Headline-Titel

**Comment by jenda77** [comment]
Ich bitte auch, dies zu verbessern. 👍

**Comment by leofeyer** [comment]
Was ist mit `htmlspecialchars_decode($this->title)`?

**Comment by jenda77** [comment]
Klar, das kann man nutzen. Aber es geht wieder darum, dass Events andere Logik und Benutzerfreundlichkeit haben als News. Deswegen diese Bitte hier, dass man dieselbe Bearbeitung von Core aus für Events hat, wie das der Fall bei News ist. ;-)

**Comment by leofeyer** [comment]
Also geht es nur darum, `$this->link` im Event-Leser hinzuzufügen?

**Comment by jenda77** [comment]
Ja, eigentlich schon, damit wenn man die HTML-Tags für die Überschriften in der dcaconfig.php erlaubt, diese Variable für die korrekte Ausgabe verwenden kann. Einfach dasselbe wie bei News.

**Comment by Aybee** [comment]
> @leofeyer Also geht es nur darum, $this->link im Event-Leser hinzuzufügen?

Ja, bitte.

**Comment by leofeyer** [comment]
Ich wollte es gerade implementieren und habe festgestellt, dass `$this->title` im Event-Leser nicht mit `specialchars()` enkodiert ist (Contao 4.3.0-dev). Tritt das Problem in Contao 4 nicht mehr auf?

**Comment by Aybee** [comment]
Keine Ahnung, ich habe leider keine 4 am Start zum Testen.

**Comment by Aybee** [comment]
Die Variable ->title bringt jetzt den Inhalt des Feldes tl_calendar_events.title so, wie er dort gespeichert ist. In Contao 3.5.31 und 4.4.8. Also alles OK.
