### ISSUE TITLE
missing languages in releases?

### ISSUE THREAD

**Issue by fritzmg** [contao/core#8499]
May be it's intentional, but I noticed that in the recent bugfix releases, more and more languages disappeared from the release archives. For instance, from `3.5.15` to `3.5.17` the following languages have been removed from the core modules in total:

* da
* lv
* my
* sl
* sq
* uk

**Comment by leofeyer** [comment]
We are only shipping translations which are at least 95% complete and those language have dropped below the limit and have therefore be removed.

**Comment by fritzmg** [comment]
I see, thx for the clarification.
