### ISSUE TITLE
Upcoming events: does not work with start and end date

### ISSUE THREAD

**Issue by jenda77** [contao/core#8500]
Unfortunately, when I set in an event the start and end datum (21.9. - 24.9.) and when I choose in the list module for all upcoming events the option _Shortened view_ the event disappears after the first day. But actually it should be there until 25.9 because it takes part until this date. 

In the demo you can see the upcoming events in the calendar but not in the event list too.

**Comment by leofeyer** [comment]
Please do not create multiple tickets for the same issue (see #8497).
