### ISSUE TITLE
ReOpen #8464 Inserttag in field "page name" not being stripped from search index

### ISSUE THREAD

**Issue by arno1979** [contao/core#8501]
Thanks for fixing #8464. I just tested this again with 3.5.17. Although the insert tags now gets correctly stripped from the "page name" field the same result appears again when entering a value with insert tags in the field "page title".
Sorry for not noticing this earlier but I think I couldn't have noticed it, because the effect of course appeared whether "page title" was filled or not.

After I checked yesterday morning everything seemed to be working fine when just entering a page name including an insert tag.

Then I went back to the project to do some further testing and the error that was supposedly fixed with 15c6174 is back.

So I did some more digging and I think I'm on to something:
The title of the search result is fine. But the context is where the insert tag is still visible. Just now I realized that it's not the complete insert tag. This is also visible in the example values of my initial post of this issue; the displayed context looks like this:
lang::de}}Deutsch Informationen auf deutsch Ich denke, du musst nach Installation der
In your fix you added the strip_insert_tags function to the title field only.
I therefore tried to apply it to the context field as well but no effect is visible. As you can see from the example above the opening {{ are missing. I think that's probably the reason why strip_insert_tags is not working at this point. By the way: the closing {{lang}} part gets stripped successfully.

I think there is more than one solution to the problem:

- Strip the insert tags before they are written to the database when indexing the page. This would result in a clean output without having to deal with the insert tags in ModuleSearch.php. On the other hand (at least in the case of the language insert tag) the desired language identification – which in my opinion should be present in the search result – gets lost.
- The more difficult (as I suspect) solution would be to keep the tags in the database field of tl_search (as it is done now) and take care of not cutting the insert tags when generating the context field in ModuleSearch.php probably somewhere around line 277.

I hope this helps.

**Comment by arno1979** [comment]
#8464

**Comment by leofeyer** [comment]
Please do not open multiple tickets regarding the same issue (see #8464).
