### ISSUE TITLE
Versionen von tl_content ohne Beschreibung

### ISSUE THREAD

**Issue by Mynyx** [contao/core#8502]
Versionen von tl_content Elementen haben keine Beschreibung, auch nicht wenn das Element eine Überschrift hat, wie nach der Änderung eines solchen Elementes in der Versionsübersicht auf der Startseite des Backends nachvollzogen werden kann.

**Comment by leofeyer** [comment]
Siehe dazu auch https://github.com/contao/core/issues/4828#issuecomment-9774236.

**Comment by Mynyx** [comment]
Der Fall ``headline`` ist ja bereits vorhanden (https://github.com/contao/core/blob/707bb503263c1935a410fe32aca6fac767d415e1/system/modules/core/classes/Versions.php#L204-L207), warum funktioniert der denn bei tl_content Elementen nicht?

**Comment by leofeyer** [comment]
Behoben in 86e2366715b07802ad8454513fdacb6ccb33d67b.
