### ISSUE TITLE
Feature Request: Hook für das Schreiben der localconfig.php

### ISSUE THREAD

**Issue by Loilo** [contao/core#8506]
## Motivation

Contao allein reicht als "Build Toolchain" einer Website von Zeit zu Zeit nicht aus. Es müssen oft z. B. Node-basierte Werkzeuge wie Grunt u. ä. verwendet werden.
Die müssen dafür auf lokale Konfigurationsdaten zugreifen – Sachen, die in Contao klassischerweise in der `localconfig.php` abgelegt werden. Diese kann von anderen Sprachen aber nicht gelesen werden und eine redundante Konfiguration ist nicht wünschenswert.

## Ausprobierter Lösungsansatz

Wir haben die Daten der `localconfig.php` per `runonce.php` eines Moduls in eine YAML-Datei übertragen, die auch andere Toolchains auslesen können.
Leider reicht das nicht völlig aus, weil über das Installtool nachträglich immernoch Änderungen an der `localconfig.php` vorgenommen werden können.

## Vorgeschlagene Lösung

Um Werkzeugen von dritter Seite Zugriff auf stets aktuelle lokale Konfigurationsdaten zu geben, wäre in meinen Augen ein entsprechender Hook sinnvoll, der getriggert wird, wenn die `localconfig.php` [von Contao geändert wird](https://github.com/contao/core/blob/26aba3bbce8dfb0370485685d831be6cad4d578c/system/modules/core/library/Contao/Config.php#L264).

Oder fällt für dieses Problem jemandem eine bessere Lösung ein?

**Comment by Toflar** [comment]
> Oder fällt für dieses Problem jemandem eine bessere Lösung ein?

Contao 4 und Symfony nutzen. Die `localconfig.php` wird irgendwann wegfallen, weil alles im Container sein soll.

**Comment by aschempp** [comment]
Und in Contao 4.3 lässt sich die komplette localconfig durch YAML ersetzen 😎

**Comment by Loilo** [comment]
...ich meinte doch schon mal irgendwann sowas gesehen zu haben.
Verflixt, hab nicht dran gedacht, in die 4er-Versionen zu gucken. :grimacing:

Dann nehm ich mal an die 3.5 LTS-Version wird kein Feature in der Richtung mehr bekommen.

**Comment by Toflar** [comment]
Semantic Versioning. Keine Features in Bugfix-Releases.

**Comment by Loilo** [comment]
Da hab ich mich unglücklich ausgedrückt, ich meinte allgemein im 3.x Zweig.

**Comment by frontendschlampe** [comment]
Es wird keine weitere 3er Version mehr geben als 3.5.x

**Comment by Loilo** [comment]
Das war meine Vermutung. 😉 
Nun gut, dann muss ich mich wohl mit Contao 4 anfreunden und hoffen, dass die Kunden dasselbe mit Composer tun. :smile:
Damit ist das Ding also obsolet. Dann mach ich hier mal dicht.
