### ISSUE TITLE
Linebreaks in localconfig.php

### ISSUE THREAD

**Issue by Bravehartk2** [contao/core#8507]
If I add linebreaks to localconfig.php for some fields with long values,
there is an "=" added after the rest of the value in the second line.
That happens only from time to time. (Cache expires?)

**Example** 
`$GLOBALS['TL_CONFIG']['allowedTags']               =    '<a><abbr><acronym><address><article><aside>\n
<audio><b><bdi><bdo><big><blockquote><br><base><button><canvas><caption><cite><code><col><colgroup><data><datalist><dataset><dd><del><dfn><div><dl><dt><em><fieldset><figcaption><figure><footer><form><h1><h2><h3><h4><h5><h6><header><hgroup><hr><i><img><input><ins><kbd><keygen><label><legend><li><link><map><mark><menu><nav><object><ol><optgroup><option><output><p><param><pre><q><s><samp><section><select><small><source><span><strong><style><sub><sup><table><tbody><td><textarea><tfoot><th><thead><time><tr><tt><u><ul><var><video><wbr>';
`
becomes:
`$GLOBALS['TL_CONFIG']['allowedTags']               =    '<a><abbr><acronym><address><article><aside>\n
<audio><b><bdi><bdo><big><blockquote><br><base><button><canvas><caption><cite><code><col><colgroup><data><datalist><dataset><dd><del><dfn><div><dl><dt><em><fieldset><figcaption><figure><footer><form><h1><h2><h3><h4><h5><h6><header><hgroup><hr><i><img><input><ins><kbd><keygen><label><legend><li><link><map><mark><menu><nav><object><ol><optgroup><option><output><p><param><pre><q><s><samp><section><select><small><source><span><strong><style><sub><sup><table><tbody><td><textarea><tfoot><th><thead><time><tr><tt><u><ul><var><video><wbr>';=
`

**Comment by leofeyer** [comment]
You really should not do this just to make entries in the local configuration files more readable.

**Comment by Bravehartk2** [comment]
That answer doesn't explain, why this happens. An explanation would be really great!
Its standard PHP to add linebreaks if lines get to long. It is one of our coding standards and our IDE does it automatically.

**Comment by Bravehartk2** [comment]
And I think I'am not the only one, with that problem ;-)

**Comment by aschempp** [comment]
The localconfig has been introduced 10 years ago and is not a state-of-the-art thing. In the future we'll use YAML in Symfony. Not manually editing the localconfig is a good idea and what you try is just a known limitation…

**Comment by backbone87** [comment]
to answer the question: it is that way because the code that manipulates the localconfig.php are some wildwest string operations that assume a very specific codestyle of the localconfig.php. Basically each localconfig.php produced this way is valid PHP code, but not every valid PHP code put into localconfig.php is correctly parseable by the current implementation of the config manipulator.

**Comment by Bravehartk2** [comment]
THX a lot!!! That answered my questions. 
BTW: where to put configuration that have to be different per instance (stage, production, etc.) if not in the localconfig?

**Comment by aschempp** [comment]
> where to put configuration that have to be different per instance (stage, production, etc.) if not in the localconfig?

The best solution would be to use Contao 4, where such a config is stored in the `parameters.yml` on each host. But that very much depends on your setup, you can also use environment parameters for that: http://symfony.com/doc/current/configuration/external_parameters.html
