### ISSUE TITLE
Danish translations missing in version 3.5.17

### ISSUE THREAD

**Issue by Michael-reklamehuset** [contao/core#8508]
I am not sure how the translations gets bundled into the zip file but it seems like the /languages/da/ folders are missing from the modules in the 3.5.17 build.

**Comment by fritzmg** [comment]
See #8499. The Danish translation has dipped below 94% on transifex: https://www.transifex.com/contao/contao/
To get it back you either need to manually install the Danish translation or collaborate on transifex to get it back up to 95%+ again.

**Comment by Michael-reklamehuset** [comment]
Ah thanks - I'll join the translation team and see if I can bring it up towards 100% - would I need to do anything to get the Danish translation in again or will it be automatically once I get the translation above 94%?

**Comment by fritzmg** [comment]
I suppose the translation will get re-added in the next bugfix release, when it's back up to 95%+.
