### ISSUE TITLE
birthdays before 1957-10-04 cannot be saved for tl_member

### ISSUE THREAD

**Issue by fritzmg** [contao/core#8509]
## Reproduction

1. go to http://demo.contao.org/contao/ and log in
2. go to _Account manager_ » _Members_ and edit one of the members
3. set the __Date of birth__ to `1901-01-01` for example and save

The date of birth will be `1970-01-01`.

## Cause

The DCA definition of the `dateOfBirth` field for `tl_members` is as follows:
https://github.com/contao/core/blob/3.5.17/system/modules/core/dca/tl_member.php#L163-L170
```php
'dateOfBirth' => array
(
	'label'                   => &$GLOBALS['TL_LANG']['tl_member']['dateOfBirth'],
	'exclude'                 => true,
	'inputType'               => 'text',
	'eval'                    => array('rgxp'=>'date', 'datepicker'=>true, 'feEditable'=>true, 'feViewable'=>true, 'feGroup'=>'personal', 'tl_class'=>'w50 wizard'),
	'sql'                     => "varchar(11) NOT NULL default ''"
),
```
Since, it's a `varchar` field and a simple `text` input, dates before `1957-10-04` should work.

However, the `DC_Table` converts it to a timestamp here:
https://github.com/contao/core/blob/3.5.17/system/modules/core/drivers/DC_Table.php#L2890-L2895
```php
// Convert date formats into timestamps
if ($varValue != '' && in_array($arrData['eval']['rgxp'], array('date', 'time', 'datim')))
{
	$objDate = new \Date($varValue, \Date::getFormatFromRgxp($arrData['eval']['rgxp']));
	$varValue = $objDate->tstamp;
}
```
This code will transform `1901-01-01` to `bool(false)` (since timestamps before `1970-01-01`cannot work). In general, this part of `DC_Table` will _always save timestamps_ into any fields with `'rgxp' => 'date'`, even though the field itself is a `text` field and its SQL definition is `varchar` and not `int`.

**Comment by fritzmg** [comment]
Actually, dates before 1970 _can_ be saved, until the integer precision of the `\Date` class is depleted. In such cases, a negative integer is saved into `dateOfBirth` as a string, e.g. `'-31539600'`.

**Comment by leofeyer** [comment]
See #7438.
