### ISSUE TITLE
Button "Speichern und Kopieren" bei Artikelelemente

### ISSUE THREAD

**Issue by marcfunkitug** [contao/core#8510]
Am Ende eines Inhaltselement gibt es die Buttons "Speichern", "Speichern und Schließen",... etc.

Häufig möchte man das zuvor angelegte Inhaltselement kopieren. Aktuell ist der Weg so:
1) Inhaltselement anlegen
2) Speichern und Schließen
3) Plus-Symbol
4) Clipboard-Symbol
5) Inhaltselement anpassen

Es wäre vielleicht eine Idee unten einen weiteren Button einzufügen der sich "Speichern und Kopieren" nennt und der das zuvor beschrieben selbst ausführt:

1) Inhaltselement anlegen
2) Speichern und Kopieren
3) Neues Element bearbeiten
4) wiederhole 2) und 3)...

**Comment by Toflar** [comment]
> Häufig möchte man das zuvor angelegte Inhaltselement kopieren.

Wirklich? Das hab ich noch nie gebraucht. Eher ein "Speichern und neu mit dem selben Elementtyp". Bei "Speichern und neu" fällt man automatisch immer auf den Text-Typ zurück. Wenn man eine Liste von Downloads oder so machen möchte, dann möchte man immer wieder den selben Typ nutzen. Aber den vorherigen kopieren? Wirklich?

**Comment by fritzmg** [comment]
> Eher ein "Speichern und neu mit dem selben Elementtyp".

👍 

Sowas wäre ziemlich genial ;).

**Comment by leofeyer** [comment]
Implementiert in contao/core-bundle@9f7a52312e94e6ecedc3673f0963776300d24ccd.

<img width="540" alt="" src="https://cloud.githubusercontent.com/assets/1192057/19263242/b379e94e-8f9b-11e6-83fc-b6ef85f472aa.png">
