### ISSUE TITLE
Bestehende HEX-Farben Auswahlmöglichkeit (Autocomplete)

### ISSUE THREAD

**Issue by marcfunkitug** [contao/core#8511]
Es um die Farben (HEX-Werte), die im Layout CSS verwendet werden.

Es gibt zwar den Picker, womit ich eine Farbe wählen kann, aber schöner wäre noch ein "Autocomplete" mit bereits genutzten Farben.

Sprich: Ich gehe in ein Farbfeld, drücke die # und Contao schlägt mir einen Hex-Code (inkl. Farbe) vor, den ich bereits in einer der CSS-Dateien verwendet habe.

**Comment by asaage** [comment]
Naja - Für den Fall meine ich sind die Theme- oder Stylesheetvariablen eigentlich gedacht.
Die ```#``` passt ohnehin nicht in die Farbfelder.

**Comment by marcfunkitug** [comment]
Die Theme- / Stylesheet Variablen waren mir leider unbekannt. Aber dennoch fände ich dieses Feature ganz nützlich.

Die # sollte auch nur dazu dienen den Autocomplete anzeigen zu lassen (wie z. B. hier bei GitHub).

**Comment by leofeyer** [comment]
Ich schließe das Ticket aufgrund mangelnden Interesses.
