### ISSUE TITLE
Duplicating unique fields

### ISSUE THREAD

**Issue by dmolineus** [contao/core#8513]
Duplicating a database row could fail if a field is marked as unique (and has a unique key) when already an empty value exist.

I suggest always set an random unique value instead of creating an empty one in that case. 
https://github.com/contao/core/blob/master/system/modules/core/drivers/DC_Table.php#L887

**Comment by aschempp** [comment]
The correct empty value should be NULL and not an empty string if the field is unique?

**Comment by dmolineus** [comment]
You're right. Allowing null values and everything works fine.
