### ISSUE TITLE
ACE Editor überlagert Debug-Toolbar

### ISSUE THREAD

**Issue by Mynyx** [contao/core#8515]
Der ACE Editor überlagert die Debug-Toolbar, wenn man beide aktiviert und dann nach Aufruf einer entsprechenden Seite beispielsweise das Fenster so skaliert, dass diese übereinander liegen.

Das Problem lässt sich beheben, indem
````
#contao-debug>* {
    z-index: 9999;
}
````
zu
````
#contao-debug {
    z-index: 9999;
}
````
geändert wird.

**Comment by leofeyer** [comment]
Behoben in 07dd574284616fd3d80d50dc1a5d15e3b1af6d62.
