### ISSUE TITLE
Log-Eintrag beim Erstellen oder Bearbeiten eines Templates fehlt

### ISSUE THREAD

**Issue by Mynyx** [contao/core#8516]
Es wird kein Log-Eintrag erstellt, wenn ein neues Template erstellt wird oder ein Template im Quelltexteditor bearbeitet wird.

**Comment by leofeyer** [comment]
Der Log-Eintrag in der Dateiverwaltung entstammt der Versionierung. Da Templates aber nicht versioniert werden, gibt es auch keinen Log-Eintrag.
