### ISSUE TITLE
Firefox Umlaut Problem

### ISSUE THREAD

**Issue by baumannsven** [contao/core#8520]
Im Backend unter Firefox gibt es Umlaut Probleme.

![ohne titel](https://cloud.githubusercontent.com/assets/2493263/19314976/5aac4c38-909c-11e6-809c-530073020692.jpg)

Es liegt an der benutzten Schriftart, mit der Firefox nicht zurecht kommt.
Durch dieses Problem kann man keine Input Felder richtig ausfüllen, abgesehen von der falschen Darstellung.

Hinweis das selbe ist auch auf contao.org nachzuvollziehen im Hauptmenü beim Suchfeld.

**Comment by leofeyer** [comment]
Wie lässt sich das in der Onlinedemo reproduzieren?

**Comment by baumannsven** [comment]
Mit Firefox neuen Mitgliedergruppe erstellen siehe oben und folgende String rein:
Bläserphilharmonie

**Comment by leofeyer** [comment]
Kann ich nicht reproduzieren.

<img width="1136" alt="" src="https://cloud.githubusercontent.com/assets/1192057/19316251/08267434-90a1-11e6-956a-f2315e94c40c.png">

**Comment by fritzmg** [comment]
@baumannsven welches OS?

**Comment by baumannsven** [comment]
Nach dem Update von FF 49.0.1 gibt's das Problem

**Comment by leofeyer** [comment]
Dann ist es wohl eher ein FF-Bug als ein Contao-Bug.

**Comment by leofeyer** [comment]
Ich kann das Problem aber auch mit FF 49.0.1 nicht reproduzieren.

**Comment by baumannsven** [comment]
Entschuldigung meinte FF 49.0.1 gibt es das Problem nicht mehr

**Comment by aschempp** [comment]
Der Fehler kann systemabhängig sein. Wenn die verwendete Schrift keine Umlaute kann, nimmt der Browser die nächste verfügbare. Möglicherweise ist die bei @baumannsven andres als bei @leofeyer ?

**Comment by leofeyer** [comment]
Wenn das so wäre, hätte ein Update auf FF 49.0.1 das Problem nicht lösen können, oder?

**Comment by baumannsven** [comment]
Nach dem Update auf den aktuellen FF ging alles wieder. Hat in dem nichts mit Abhängigkeiten von System zu tun
