### ISSUE TITLE
Can't set Inserttag-Flags in Link-target fields

### ISSUE THREAD

**Issue by pepesale** [contao/core#8521]
It should be possible to set Inserttag-Flags in Link-target fields of

- Image setting _Link target_ in content elements
- Hyperlink content element
- Page settings for page type _external redirect_
- ...

For example setting

`{{link_url::*}}?title={{page::title|urlencode}}`

throws the error

> Please enter a valid URL format and encode special characters!

while
`{{link_url::*}}?title={{page::title}}`
works.

**Comment by leofeyer** [comment]
Fixed in 2af70072aa245de296e05c0f5fd9243326480e9f.
