### ISSUE TITLE
Mixed directory names in file manager and file tree

### ISSUE THREAD

**Issue by piotrwarsztocki** [contao/core#8522]
This only happens when
1. Contao is installed in subdirectory of webserver - fe. "xyztest"
2. Directory "files" contains subdirectory with the same name fe. "xyztest"

./xyztest/
./xyztest/files/xyztest/
./xyztest/files/xyztest/somefile.jpg

Contao mixes names of directories and in file manager you can see
/filesxyztest/somefile.jpg

**Comment by leofeyer** [comment]
I was not able to reproduce this. Can you post a screenshot please?

**Comment by xchs** [comment]
I cannot reproduce it on my system either.
