### ISSUE TITLE
Contao 4: Backend-Template modifizieren

### ISSUE THREAD

**Issue by NinaG** [contao/core#8523]
Ich schlage vor, dass wir das Contao 4 Backend-Template um ein paar WAI ARIA Landmark Roles ergänzen:

```
<div id="header" role="banner">
<div id="left" role="navigation">
<div id="main" role="main">
<div id="footer" role="contentinfo">
```

Diese Landmark Roles unterstützen blinde/stark sehbehinderte Nutzer bei der Identifikation und Navigation zwischen den einzelnen Bereichen.

**Comment by leofeyer** [comment]
Müsste `role="navigation"` nicht eher dem `<div id="tl_navigation">` zugewiesen werden? Die linke Spalte kann ja mehr als nur eine Navigation enthalten.

**Comment by NinaG** [comment]
Ich ging davon aus, dass die linke Spalte ausschließlich für Navigationsinformationen gedacht ist. Wenn auch noch andere Sachen da hinkommen, hast du natürlich recht. Dann wäre das spezifischer.

**Comment by leofeyer** [comment]
Siehe https://github.com/contao/contao/issues/6362 .
