### ISSUE TITLE
Contao 4: FE-Icons in Seitenstruktur - Alternativtext

### ISSUE THREAD

**Issue by NinaG** [contao/core#8524]
In der Seitenstruktur gibt es vor jeder Seite ein Icon, das über einen Link zur FE-Ansicht der Seite führt. Weder der Link noch das Symbol haben einen Alternativtext oder Titel. So ist es für blinde Nutzer nicht erkennbar, was für ein Link das ist.

Vorschlag: 
Der Link sollte einen Titel erhalten. Z.B.: title="Seite 'foo' im Frontend ansehen".
Das Icon sollte einen Alternativtext erhalten. Z.B.: alt="Frontend-Ansicht öffnen"

**Comment by aschempp** [comment]
Sollte der Alt-Tag eines Bildes nicht die Seite beschreiben? Also müsste der Alt-Text eher sein "Geschützte reguläre Seite" für ein entsprechendes Icon?

**Comment by NinaG** [comment]
Ja, das wäre vermutlich noch stimmiger. Der Link enthält via _title_ das Linkziel, das Icon via _alt_ die Bedeutung des Symbols (wie du sagst).

**Comment by leofeyer** [comment]
Die Links haben selbstverständlich alle einen Titel, sonst gäbe es gar keine Tooltips.

<img width="1153" alt="" src="https://cloud.githubusercontent.com/assets/1192057/19346523/185d7a70-9144-11e6-8ba1-56c83fb22650.png">

**Comment by NinaG** [comment]
Ich spreche von diesem speziellen Icon in der Seitenstruktur, das vor jeder Seite eingeblendet wird. 

Allerdings gebe ich dir recht, dass der Link doch einen title hat. Wenn ich mir den Quellcode in Firefox, IE Inspector und Co anzeige, wird er nicht gezeigt. Schau ich anders drauf, sehe ich ihn auch. Das hatte mich durcheinander gebracht.

Es bleibt aber noch das Problem mit dem Icon an der Stelle. Wie Andreas zurecht sagte, hat das Icon vor den Seiten eine Bedeutung, da es je nach angezeigtem Icon dem Benutzer die Info gibt, um was für einen Seitentyp es sich handelt. Diese Info bleibt blinden Nutzern an der Stelle vorenthalten. Das ließe sich leicht ändern, wenn diese Info als Alternativtext auf das Bild gelegt wird.

**Comment by NinaG** [comment]
Nachtrag: Ich verstehe jetzt, weshalb ich den titel vorher nicht gesehen hatte. Er ist original im Quellcode drin. Das Tooltip-Javascript entfernt ihn aber aus dem Quellcode und weist ihn stattdessem dem visuell aufgehübschten Tooltip zu. Stellt sich nur die Frage, ob Screenreader-Nutzer die Info sei weiterhin erhalten. Ich werde das testen und mich ggf. nochmal dazu melden.

**Comment by NinaG** [comment]
Nachdem ich mit dem Geschäftsführer des Hamburger Blindenverbandes (Heiko Kunert) Contao 4 ausgiebig getestet habe, werde ich nun lieber gezielt die einzelnen Punkte in separate Tickets packen. Das macht es übersichtlicher und klarer, was geändert werden muss.

**Comment by fritzmg** [comment]
btw. @NinaG Tickets für Contao 4 solltest du lieber bei den entsprechenden Bundles posten, denke ich.
