### ISSUE TITLE
C4: Login-Formular fürs Backend ohne Tabelle

### ISSUE THREAD

**Issue by NinaG** [contao/core#8525]
Ich habe gerade erstaunt bemerkt, dass das Login-Formular für das Contao 4-Backend noch in eine Tabelle gehüllt ist. 

Es wäre sicher empfehlenswert, diese deutlich veraltete Art der Formulargestaltung an dieser Stelle zu entfernen und den Login-Screen tabellenlos zu gestalten. Immerhin haben wir aus guten Gründen mittlerweile auch im Formulargenerator die Tabellenvariante entfernt.

Falls Hilfe beim Umschreiben der entsprechenden CSS-Anweisungen benötigt werden, helfe ich gerne.

**Comment by leofeyer** [comment]
Ist mittlerweile implementiert.
