### ISSUE TITLE
page cache does not distinguish between http and https

### ISSUE THREAD

**Issue by fritzmg** [contao/core#8531]
## Situation A

1. enable the page cache on a page
2. purge the page cache
3. log out of the back end or use a private browser window
4. load that page in the frontend via `http://` to generate a cached entry
5. load that same page again via `https://`

The HTML source will contain `http://` references, e.g.
```php
<base href="http://example.org/">
```
This is a problem because now all JavaScript and Stylesheet resources will not be loaded by the browser anymore for security reasons.

## Situation B

1. enable the page cache on a page
2. purge the page cache
3. log out of the back end or use a private browser window
4. load that page in the frontend via `https://` to generate a cached entry
5. load that same page again via `http://`

The HTML source will contain `https://` references, e.g.
```php
<base href="https://example.org/">
```
This can be a problem for domains on servers that do not have a valid SSL certificate installed. The browser will not or cannot load any JavaScript or Stylesheet resources in that case.

## Alleviation

The problems of both situations can be alleviated by generating permanent redirects from `http` to `https` or vice versa, to ensure that the page cache stays consistent. 

However, if you want to serve your site both via `http` _and_ `https` you cannot circumvent the problems of situation A this way, I think.

In both cases, the problem with assets at least can also be circumvented by using an __Assets URL__. In that case Contao generates scheme relative URLs like `//example.dev/…` and thus the wrong `<base href>` does not matter anymore. Other problems might still persist though (e.g. with AJAX calls that are relative to the base href). Also any relative links will probably suddenly link away from your current scheme.

**Comment by aschempp** [comment]
I see the issue, but in my opinion this is a misconfiguration. It never, ever, makes sense to server a page over HTTP if a valid certificate is available. Always add a redirect to your htaccess configuration.

**Comment by leofeyer** [comment]
Also, if a resource is available via HTTPS, you should always include it via HTTPS – even if your website is only available via HTTP.

HTTP is deprecated and Google Chrome will warn users when making unencrypted connections in one of the next releases (see https://security.googleblog.com/2016/09/moving-towards-more-secure-web.html).

**Comment by fritzmg** [comment]
> I see the issue, but in my opinion this is a misconfiguration. It never, ever, makes sense to server a page over HTTP if a valid certificate is available. Always add a redirect to your htaccess configuration.

I agree.

However, this known limitation is currently undocumented. May be something like this can be added to the `.htaccess.default`
```
  ##
  # If you use the Contao page cache, you need to serve
  # your site either via http or https, not both.
  # 
  # Uncomment the following lines to redirect to http:
  #
  #   RewriteCond %{HTTPS} on
  #   RewriteRule .* http://%{SERVER_NAME}%{REQUEST_URI} [R=301,L] 
  #
  # Uncomment the following lines to redirect to https:
  #
  #   RewriteCond %{HTTPS} off
  #   RewriteRule .* https://%{SERVER_NAME}%{REQUEST_URI} [R=301,L] 
  #
  # Purge the page cache afterwards if necessary.
  ##
```
After `Uncomment the following lines to add "www." …`

> Also, if a resource is available via HTTPS, you should always include it via HTTPS – even if your website is only available via HTTP.

Yes, as I said, Situation B is only relevant, if you only have a default, unsecure SSL certificate for your domain and no permanent redirect to `http`.

**Comment by fenepedia** [comment]
+1

**Comment by leofeyer** [comment]
I don't think the `.htaccess` file is the right place for this information.

I did not include HTTP to HTTPS rewrite rules on purpose, because this is something that you can (and should) configure in your server's control panel. It is a lot more performant if no `.htaccess` file needs to be parsed.

I would prefer if you created a PR that updates the [documentation](https://github.com/contao/docs) accordingly.

**Comment by fritzmg** [comment]
> It is a lot more performant if no .htaccess file needs to be parsed.

Of course, but Contao 2 and 3 already use the `.htaccess` for a lot of things. It also has things like this in it:
```
  ##
  # Uncomment the following lines to add "www." to the domain:
  #
  #   RewriteCond %{HTTP_HOST} ^example\.com$ [NC]
  #   RewriteRule (.*) http://www.example.com/$1 [R=301,L]
  #
  # Uncomment the following lines to remove "www." from the domain:
  #
  #   RewriteCond %{HTTP_HOST} ^www\.example\.com$ [NC]
  #   RewriteRule (.*) http://example.com/$1 [R=301,L]
  #
  # Make sure to replace "example.com" with your domain name.
  ##
```
Nevertheless, I'll see about adding it to the documentation instead. Currently there is no section for the page cache in general though.

**Comment by hinformatik** [comment]
Why the frick is this ticket closed? Problem still unresolved and undocumented.

REOPEN PLZ!

**Comment by discordier** [comment]
So, why don't you simply document it then instead of swearing in the issue tracker?
It is not documented because nobody has done it. Open source is easy, everybody may contribute and improve their itches.

**Comment by fritzmg** [comment]
Part of this problem could be alleviated by using the
```
{{env::path|uncached}}
```
insert tag for the `<base href="…">`. So the complete `fe_page` template could look like this:
```php
<?php $this->extend('fe_page'); ?>

<?php $this->block('head'); ?>
  <meta charset="<?= $this->charset ?>">
  <title><?= $this->title ?></title>
  <base href="{{env::path|uncached}}">

  <?php $this->block('meta'); ?>
    <meta name="robots" content="<?= $this->robots ?>">
    <meta name="description" content="<?= $this->description ?>">
    <meta name="keywords" content="<?= $this->keywords ?>">
    <meta name="generator" content="Contao Open Source CMS">
  <?php $this->endblock(); ?>

  <?= $this->viewport ?>
  <?= $this->framework ?>
  <?= $this->stylesheets ?>
  <?= $this->mooScripts ?>
  <?= $this->head ?>

  <?php $this->block('html5shiv'); ?>
    <!--[if lt IE 9]><script src="<?= TL_ASSETS_URL ?>assets/html5shiv/<?= $GLOBALS['TL_ASSETS']['HTML5SHIV'] ?>/html5shiv-printshiv.min.js"></script><![endif]-->
  <?php $this->endblock(); ?>
<?php $this->endblock(); ?>
```

**Comment by Toflar** [comment]
BTW: I just wanted to state that it is absolutely correct for a reverse proxy cache to treat http and https the same! :)
