### ISSUE TITLE
Caching für sourcemap files deaktivieren

### ISSUE THREAD

**Issue by Metis77** [contao/core#8532]
Google Chrome lädt bei den aktuellen Einstellungen in der .htaccess die Sourcemap files (.map) nicht immer neu.
So ist die Arbeit mit Sourcemaps schwierig.

Lösungsvorschlag:
```
##
# Expires headers (for better cache control)
# @see https://github.com/h5bp/html5-boilerplate
##
<IfModule mod_expires.c>
  ExpiresActive on

  ##
  # Productional website
  ##
  ExpiresByType text/cache-manifest           "access plus 0 seconds"
  ExpiresByType text/html                     "access plus 0 seconds"
  ExpiresByType text/xml                      "access plus 0 seconds"
  ExpiresByType application/xml               "access plus 0 seconds"
  ExpiresByType application/json              "access plus 0 seconds"
  ExpiresByType application/rss+xml           "access plus 1 hour"
  ExpiresByType application/atom+xml          "access plus 1 hour"
  ExpiresByType image/gif                     "access plus 1 month"
  ExpiresByType image/png                     "access plus 1 month"
  ExpiresByType image/jpeg                    "access plus 1 month"
  ExpiresByType image/x-icon                  "access plus 1 month"
  ExpiresByType video/ogg                     "access plus 1 month"
  ExpiresByType audio/ogg                     "access plus 1 month"
  ExpiresByType video/mp4                     "access plus 1 month"
  ExpiresByType video/webm                    "access plus 1 month"
  ExpiresByType text/x-component              "access plus 1 month"
  ExpiresByType application/x-font-ttf        "access plus 1 month"
  ExpiresByType font/opentype                 "access plus 1 month"
  ExpiresByType application/x-font-woff       "access plus 1 month"
  ExpiresByType image/svg+xml                 "access plus 1 month"
  ExpiresByType application/vnd.ms-fontobject "access plus 1 month"
  ExpiresByType text/css                      "access plus 1 year"
  ExpiresByType application/javascript        "access plus 1 year"

  ##
  # Disable caching during development
  # @see https://github.com/contao/core/issues/4364
  ##
  # ExpiresByType text/cache-manifest           "access"
  # ExpiresByType text/html                     "access"
  # ExpiresByType text/xml                      "access"
  # ExpiresByType application/xml               "access"
  # ExpiresByType application/json              "access"
  # ExpiresByType application/rss+xml           "access"
  # ExpiresByType application/atom+xml          "access"
  # ExpiresByType image/gif                     "access"
  # ExpiresByType image/png                     "access"
  # ExpiresByType image/jpeg                    "access"
  # ExpiresByType image/x-icon                  "access"
  # ExpiresByType video/ogg                     "access"
  # ExpiresByType audio/ogg                     "access"
  # ExpiresByType video/mp4                     "access"
  # ExpiresByType video/webm                    "access"
  # ExpiresByType text/x-component              "access"
  # ExpiresByType application/x-font-ttf        "access"
  # ExpiresByType font/opentype                 "access"
  # ExpiresByType application/x-font-woff       "access"
  # ExpiresByType image/svg+xml                 "access"
  # ExpiresByType application/vnd.ms-fontobject "access"
  # ExpiresByType text/css                      "access"
  # ExpiresByType application/javascript        "access"

  <FilesMatch (\.map)$>
     Header set Expires "0"
  </FilesMatch>

</IfModule>

##
# Header adjustments
##
<IfModule mod_headers.c>

  ##
  # Disable caching during development
  # @see https://github.com/contao/core/issues/4364
  ##
  #Header unset Cache-Control
  #Header append Cache-Control must-revalidate

  ##
  # Do not cache the cron.txt file
  # @see https://github.com/contao/core/issues/5105
  ##
  <FilesMatch "cron\.txt$|\.map">
    Header set Cache-Control "no-cache, no-store, must-revalidate, max-age=0, proxy-revalidate, no-transform"
  </FilesMatch>

  ##
  # Add a Vary Accept-Encoding header for the compressed resources. If you
  # modify the file types above, make sure to change them here accordingly.
  # @see http://developer.yahoo.com/performance/rules.html#gzip
  #
  # Note: If you are using a case-sensitive file system like HFS+ or ext4, you
  # have to change the <FilesMatch> directive as follows:
  #
  # <FilesMatch "\.(?i:js|css|xml|gz|svgz)$">
  #
  # For more information see: https://github.com/contao/core/issues/4364
  ##
  <FilesMatch "\.(js|css|xml|gz|svgz)$">
    Header append Vary Accept-Encoding
  </FilesMatch>

</IfModule>
```

Relevant sind diese beiden Teile:
```
<IfModule mod_expires.c>
  ...
  <FilesMatch (\.map)$>
     Header set Expires "0"
  </FilesMatch>
```
und
```
<IfModule mod_headers.c>
  ...
  <FilesMatch "cron\.txt$|\.map">
    Header set Cache-Control "no-cache, no-store, must-revalidate, max-age=0, proxy-revalidate, no-transform"
  </FilesMatch>
```

**Comment by leofeyer** [comment]
@contao/developers /cc

**Comment by Toflar** [comment]
Ja, kann man ergänzen. Klar :)

**Comment by leofeyer** [comment]
Ich kenne mit mit Sourcemap-Dateien nicht aus. Macht es wirklich Sinn, das Caching immer zu unterbinden?

**Comment by Toflar** [comment]
Ja, Sourcemap-Dateien sind eine grosse Unterstützung für JS-Devs. Ich nutze sie natürlich auch immer und sie sind ja im Live-Betrieb irrelevant. Aber eigentlich sollte der Browser auch so schlau sein und Caching automatisch deaktivieren für Sourcemap-Dateien...

**Comment by Metis77** [comment]
@leofeyer 
Ja.
Ohne offene Def Tools werden Sourcemap Dateien (.map) gar nicht erst geladen, weil sie als Kommentar übergeben werden.

Wenn die Def Tools offen sind, schauen diese dann in den .js oder .css files nach, ob dort eine Sourcemap definiert ist, und laden diese ggf.

für CSS schaut das zB so aus:
`
/*# sourceMappingURL=styles.css.map */
`

**Comment by Metis77** [comment]
@Toflar 
Ja der Browser sollte sourcemaps immer selber neu laden. Chrome tut dies aber nicht immer.
Wie andere Browser mit Sourcemaps umgehen weiß ich nicht genau.

Das ist ein bekanntes Problem und wird zB hier 
https://groups.google.com/forum/#!topic/google-chrome-developer-tools/2rolf--fJ3M
und hier
http://stackoverflow.com/questions/15505311/how-to-get-chrome-to-reload-source-maps
diskutiert.

Aus erstem Link stammt obige Lösung.
Bisher scheint das damit besser zu klappen.

**Comment by discordier** [comment]
Sourcemaps sind mittlerweile unerlaesslich, jedoch frage ich mich, warum du die source maps ungecached holen moechtest, die js files hingegen nicht.

Ich habe bei mir die devtools so eingestellt dass sie den cache deaktivieren so lange sie offen sind und damit bislang noch keine Probleme gehabt.

Bei deinem Setup wyrde er doch nun ggf. die JS Datei (oder CSS) aus dem cache holen und die source map neu holen, wodurch sie dann wieder desync sind.
Kannst du das evtl. ein wenig naeher beleuchten?

Abgesehen von dieser Unklarheit spricht nix dagegen source maps nie zu cachen, das sie eh nur gezogen werden wenn gebraucht.

**Comment by Metis77** [comment]
@discordier 
Es geht hier eher um einen bekannten Chrome bug (siehe links oben).

Den gibt es seit Jahren, und der bewirkt, dass die .map files nicht immer korrekt neu geladen werden, auch wenn in den Dev tools das caching deaktiviert ist.

Falls jemanden schon einmal aufgefallen ist dass in chorme dev tools die Zeilenangaben aus den sourcemaps manchmal falsch sind, in firefox aber stimmen, dann liegt das an diesem Bug.

Manuel umgehen lässt sich der soweit ich weiß nur mit 3 umständlichen Methoden:
1.) entweder privater modus
2.) oder map file direkt öffnen und refresh
3.) oder alle browser Daten löschen

mit der .htaccess geht es leichter.

**Comment by discordier** [comment]
Wenn es nur um den chrome bug geht, dann ok, einbauen.

Ich frage mich jedoch, ob wir hierdurch dann nicht Probleme in anderen Browsern erzeugen, wo dann ggf. die generierten files aus dem cache kommen und die maps eben nicht.

**Comment by Metis77** [comment]
Ich denke der Standart ist, dass beim Entwickeln immer die aktuelle Sourcemap & CSS Datei in den Devtools benötigt wird.
Und andere Browser laden die .map Datei eh immer neu in ihren Devtools, anscheinend nur der Chrome ab und an nicht.

**Comment by leofeyer** [comment]
Korrekt wäre IMO folgendes:

```
<FilesMatch "\.map$">
  Header set Expires "0"
</FilesMatch>
```

und

```
<FilesMatch "(cron\.txt|\.map)$">
    Header set Cache-Control "no-cache, no-store, must-revalidate, max-age=0, proxy-revalidate, no-transform"
</FilesMatch>
```

Die Unterschiede liegen in der FilesMatch-Regex.

**Comment by Toflar** [comment]
Richtig, die Regex war nicht korrekt. Deine Variante passt.

**Comment by leofeyer** [comment]
Behoben in 3070493c6b1fa564157ff6b75a8ac17d0f1e9a20.
