### ISSUE TITLE
Remove mycrypt from the core

### ISSUE THREAD

**Issue by Toflar** [contao/core#8534]
The mycrypt extension is deprecated as of PHP 7.1 and will be removed from the PHP core over to PECL. If possible, we should find a BC way and switch to phpseclib so we can remove the mycrypt requirement from Contao completely.

**Comment by discordier** [comment]
Some reading and merely as a bookmark for me https://github.com/phpseclib/phpseclib/issues/1028

I will have a look into this.

**Comment by leofeyer** [comment]
Since The PHP OpenSSL extension is a Contao requirement, why don't we just use `openssl_encrypt()` and `openssl_decrypt()`?

**Comment by leofeyer** [comment]
Another option would be https://github.com/defuse/php-encryption

**Comment by aschempp** [comment]
Just remember that we need to keep BC for existing encrypted data.

**Comment by leofeyer** [comment]
I strongly assume that `openssl_decrypt()` will lead to the same results as `mcrypt_decrypt()` when using the same cipher, mode, key and IV. 😄

**Comment by BugBuster1701** [comment]
Zur Erinnerung: "...it will be removed from the core and into PECL in PHP 7.2."

**Comment by discordier** [comment]
Ja? Worauf willst du hinaus?

**Comment by BugBuster1701** [comment]
Wenn der Release Rhythmus so weitergehen sollte, haben wir in einem Jahr die 7.2.
Auch wenn Contao selber wohl die Encryption Klasse nicht nutzt, wird es einige Erweiterungen geben die das tun. (Ich auch, habe aber bereits einen Ersatz, wenn auch nicht identisch)

_Zur Zeit haben wir jede Menge Websites, laut Google, die den tl_search Index Fehler im Frontend anzeigen. Ja, das ist u.a. ein Konfig Fehler, aber wollen wir das da noch E_DEPRECATED Meldungen dazu kommen? Dann kommen wir wieder in Erklärungsnot, warum Contao nicht schuld ist, was den Nutzern dann aber auch nicht hilft._

Ich fände es daher sinnvoll wenigstens die E_DEPRECATED Unterdrückung noch in der 3.5.x eingebaut werden könnte. (wie  bei phpseclib)

**Comment by leofeyer** [comment]
Ich habe einen PR zur Diskussion gestellt: #8589
