### ISSUE TITLE
Mehrere bearbeiten: Checkbox (de)aktivieren über Klick auf Zeile funktioniert nicht überall

### ISSUE THREAD

**Issue by Samson1964** [contao/core#8535]
Ich habe das Verhalten in der aktuellen Demo 3.5.17 nachvollziehen können:

1. Dateiverwaltung öffnen (ähnlich wahrscheinlich auch in Seitenstruktur - aber nicht getestet)
2. Ein paar Bäume über das +Symbol aufklappen
3. Es lassen sich nur die Elemente aus dem 1. Baum über einen Klick auf die Zeile auswählen
4. Wenn Elemente vor Punkt 2 schon zu sehen waren, funktioniert der Klick über die Zeile.

Die Checkboxen funktionieren aber überall, weswegen das ein kleines kosmetisches Problem ist.

**Comment by leofeyer** [comment]
Das Problem ist, dass die `click`-Events mehrfach zugewiesen werden, weil `Backend.enableToggleSelect()` auch bei `ajax_change` aufgerufen wird. Ich habe es allerdings nicht geschafft, das entsprechend umzustellen.

@aschempp @qzminski Help please. 😄

**Comment by qzminski** [comment]
Can anyone keen explain me the situation in English?

**Comment by leofeyer** [comment]
The click events are assigned multiple times, because `Backend.enableToggleSelect()` is triggered on `domready` as well as on `ajax_change` (to also assign the events to the newly loaded elements).

This leads to problems, because existing elements get another click event on top of the already existing click event. And if an element happens to have two, four, six, eight … handlers, the checkbox is enabled by the first handler and immediately disabled again by the second one.

**Comment by qzminski** [comment]
Frankly I would go with the storage solution because that's the extraordinary element property. The CSS class should be used only for CSS.

**Comment by Toflar** [comment]
You could as well just write an array and add the elements to it. Basically, `store()` and `retrieve()` do exactly that. It's just an array on the `Element` object of MooTools. No magic at all but pretty useful for such cases I find :)

**Comment by qzminski** [comment]
@Toflar that would be yet another thing to maintain for no reason, so your solution is 100% accurate imo.

**Comment by aschempp** [comment]
Why not simply remove existing click events when adding the new one?

**Comment by Toflar** [comment]
Because it might be events of others that are intended?

**Comment by leofeyer** [comment]
Correct. And there are other click events.

**Comment by aschempp** [comment]
1. I don't think there are others.
2. You can unset one specific event by passing the callback ;-)

**Comment by Toflar** [comment]
> You can unset one specific event by passing the callback ;-)

I know, but I never liked that :)

**Comment by leofeyer** [comment]
> I don't think there are others.

Yes, there are, e.g. the "hover row" events in Contao 3.

> You can unset one specific event by passing the callback ;-)

I know and I have tried it but I did not succeed. I have even created a `boundEvent` variable according to the [MooTools guide](http://mootools.net/core/docs/1.5.1/Element/Element.Event#Element:removeEvent).

**Comment by aschempp** [comment]
> Yes, there are, e.g. the "hover row" events in Contao 3.

That event is not on the checkbox, and it is a hover event not a click event…

**Comment by leofeyer** [comment]
True, but there are click events. I have checked it last week.

**Comment by leofeyer** [comment]
@Toflar You fix does not solve the problem, I'm afraid. The checkboxes are clickable indeed, but the "shift click" feature is still broken. 😢

**Comment by leofeyer** [comment]
Fixed in c84f5fd2658b486ac462a49eff8f51af29715c28.
