### ISSUE TITLE
Mehrere Bearbeiten: Das Feld "Name" darf höchstens XX Zeichen lang sein!

### ISSUE THREAD

**Issue by derastronaut** [contao/core#8536]
Hallo,

folgender Fall unter Contao 3.5.17: Werden in der **Dateiverwaltung** mehrere (viele) Bilder mit langen Dateinamen bearbeitet, erhält man beim Versuch zu speichern ab einem gewissen Bild die Fehlermeldung "**Das Feld "Name" darf höchstens XX Zeichen lang sein!**" Dabei wird XX (z.B. 39) mit jedem weiteren Bild kleiner.

Es müssen allerdings viele Bilder sein und der Dateiname an sich schon etwas länger. In meinem Fall waren es 60 Bilder mit dem Dateinamen "2016-10-15_tsv1_dormagen-langenfeld_1234" (1234 ist ein Beispiel für die Bildnummer). Hier kam die Fehlermeldung ab dem 54. Bild.
Bei einem weiteren Test mit 58 Bildern kam die Fehlermeldung ab dem 55. Bild, jedoch mit dem Dateinamen "2016-09-03_tsv1_dormagen-baunatal_1234". Die Fehlermeldung kommt also relativ zur Anzahl der Zeichen im Dateinamen.

Ich habe es in einer Testinstallation geprüft, auch dort bekomme ich die Fehlermeldung. In der Contao-Demo konnte ich es nicht prüfen, da ich dort keine Bilder hochladen kann.

Bussi!

**Comment by Samson1964** [comment]
Ich hatte auch schon Dateinamen wie "Testbild_neckarulm", wo gemeckert wurde, ich dürfte nur max. 11 Zeichen verwenden. Dabei ist meine Pfadstruktur gar nicht so tief, z.B. "files/kwabc/news/2005/01/bilder". Alles über "Mehrere bearbeiten". Ob das viele Dateien waren weiß ich nicht mehr. Vielleicht 15, vielleicht 30, vielleicht 40. 
Dieses Verhalten ist seit ein paar Tagen aber auch nicht mehr aufgetreten.

**Comment by Samson1964** [comment]
Ich habe jetzt mal einen Test gemacht mit etwa 50-60 Dateien/Ordnern und einfach nach dem Öffnen auf Speichern geklickt. Mehrere Dateien werden angemahnt:
files/kwabc/news/2007/09/nyc_meeting/New_treasurer_in_discussion.jpg (nur 11 Zeichen erlaubt beim Dateinamen)
files/kwabc/news/2007/09/nyc_meeting/NY_Athletic_Club.jpg (7 Zeichen)
files/kwabc/news/2007/09/nyc_meeting/Otto_Dinner_1.jpg (3 Zeichen)

**Comment by leofeyer** [comment]
Behoben in e4b22f4578b2126675a7896f8ace26a48b7de1c4.
