### ISSUE TITLE
Link defekt: Weitere Informationen zum sizes-Attribut finden Sie auf w3.org.

### ISSUE THREAD

**Issue by derastronaut** [contao/core#8537]
Hallo,

in dem Hilfe-Layer zu **Pixeldichte/Skalierungsfaktor** unter Responsiv-Images führt der Link bei "**Weitere Informationen zum sizes-Attribut finden Sie auf w3.org**" ins Leere (404).

Ich kann nicht mit 100 %iger Sicherheit sagen, ob der Link, den ich gefunden habe, der korrekte ist, aber hier: http://w3c.github.io/html/semantics-embedded-content.html#element-attrdef-img-srcset

Der defekte Link tritt in Contao 3.5.17 und 4.2.4 auf. (Ist es eigentlich Absicht, dass man im Backend von Contao 4.2.x die letzte Versionsziffer nicht mehr angezeigt bekommt?)

**Comment by asaage** [comment]
>  (Ist es eigentlich Absicht, dass man im Backend von Contao 4.2.x die letzte Versionsziffer nicht mehr angezeigt bekommt?)

Ich sehe nicht einmal 4.2

Vielleicht ist das auch eher eine Information für contao-manager falls man damit auch Updates durchführen können wird.

**Comment by leofeyer** [comment]
> Ich kann nicht mit 100 %iger Sicherheit sagen, ob der Link, den ich gefunden habe, der korrekte ist

Ich hab den hier gefunden: https://html.spec.whatwg.org/multipage/embedded-content.html#attr-img-srcset

@ausi Welche Seite soll ich verlinken?

> (Ist es eigentlich Absicht, dass man im Backend von Contao 4.2.x die letzte Versionsziffer nicht mehr angezeigt bekommt?)

Siehe dazu contao/core-bundle#493.

**Comment by ausi** [comment]
Die Links von w3.org sollten zukunftssicherer sein denke ich:

`sizes`: <https://www.w3.org/TR/2016/PR-html51-20160915/semantics-embedded-content.html#element-attrdef-img-sizes>

`srcset`: <https://www.w3.org/TR/2016/PR-html51-20160915/semantics-embedded-content.html#element-attrdef-img-srcset>

**Comment by leofeyer** [comment]
Behoben in ec1bfc47630fcc94669354687e787cb8ecd38af9.
