### ISSUE TITLE
tinyMCE file popup hardcoded to tl_content.singleSRC

### ISSUE THREAD

**Issue by aschempp** [contao/core#8539]
https://github.com/contao/core/blob/master/assets/contao/js/core-uncompressed.js#L1053

**Comment by leofeyer** [comment]
What would you suggest?

**Comment by aschempp** [comment]
Idk, somehow we should pass the field name to tinyMCE? At last maybe using some data-attributes on the textarea?

**Comment by leofeyer** [comment]
Actually, the field does not matter at all, because it is never used. We just need a field to initialize the page picker. Or did it cause a problem for you?

**Comment by aschempp** [comment]
Well, if you want to set `rootNodes` on the picker for example?

**Comment by leofeyer** [comment]
Then we need to be able to override the table, too, don't we?

**Comment by aschempp** [comment]
Absolutely, that's why I wrote *hardcoded to tl_content.singleSRC*. I have not investigated how to change it though, I just thought that this is odd…

**Comment by leofeyer** [comment]
You would have to specify the table and field name in your `be_tinyMCE.html5` template.

**Comment by aschempp** [comment]
That's not really an option, as there can be multiple tinyMCE fields on the same page for different fields…

**Comment by leofeyer** [comment]
True.

**Comment by leofeyer** [comment]
Changed in contao/core-bundle@2b76cf4d8b8bd7e666e13155247df73d0c77a683.
