### ISSUE TITLE
Nach Update auf 3.5.18: Aufbauen des Suchindex scheitert bei geschützten Seiten

### ISSUE THREAD

**Issue by arno1979** [contao/core#8541]
Ich habe gerade das Update auf 3.5.18 eingespielt und gleich mal den Suchindex neu aufbauen wollen, um zu testen wie sich das sequentielle Aufbauen darstellt.
In meiner Testumgebung bin ich damit auf ein Problem gestoßen, welches aktuell dazu führt, dass ich den Suchindex nicht mehr neu aufbauen kann.

Das Problem hängt offensichtlich mit den geschützten Seiten und den Mitgliedern zusammen.
In meiner Testumgebung ist es so, dass es mehrere geschützte Bereiche gibt, die für unterschiedlichen Mitgliedergruppen freigegeben sind. Zum Testen und eben zum aufbauen des Suchindexes habe ich einen Frontend-Benutzer der Mitglied aller Gruppen ist, somit Zugriff auf alle geschützten Bereiche im Frontend hat.
Wähle ich vor dem Neuaufbau des Suchindexes diesen Benutzer aus, werden die Seiten des ersten geschützten Bereichs noch indiziert. Kommt die Reihe an den zweiten Block mit geschützten Seiten, werden diese rot markiert und bekommen eine "403"-Meldung voran gestellt. Kein Zugriff also. Sobald dieser zweite Block abgehandelt ist wird dann noch eine öffentlich zugängliche Seite indiziert, dann bleibt der Indexer einfach stehen.

Ich habe dann noch mal probiert keinen Frontend-Benutzer auszuwählen, dann tritt das Problem gleich beim ersten Block geschützter Seiten auf.

Zusätzlich ist mir noch aufgefallen, dass wenn ich einen Frontend-Benutzer ausgewählt habe, die Indexierung stehen bleibt und ich dann einfach unten auf der Seite auf "Weiter" klicke, ich mich erneut im Backend anmelden muss. Das war bisher meiner Meinung nach auch nicht so.

**Comment by leofeyer** [comment]
Wie kann ich das z.B. mit der Contao Official Demo reproduzieren?

**Comment by fritzmg** [comment]
Scheint das selbe Problem wie [hier](https://github.com/contao/core/issues/8449#issuecomment-256306390) zu sein.

**Comment by fritzmg** [comment]
In der Online Demo kann man den Fall von @arno1979 nicht reproduzieren, da man in der Online Demo die Option __Index protected pages__ nicht aktivieren kann.

Den Fall von @tsarma kann man jedoch in der Online Demo reproduzieren. Ich werde dazu heute noch eine genaue Anleitung posten, falls notwendig.

**Comment by fritzmg** [comment]
1. log into the Contao Demo.
2. [edit the _Page not found_ page](http://demo.contao.org/contao/main.php?do=page&act=edit&id=19) and disable the redirect.
3. create a new calendar and set its redirect page to the same page as the default Calendar (_Event detail_).
4. copy the event entries from the default calendar several times to the new calendar.
5. publish the copied events.
6. go to _System_ » _Maintenance_ and _Rebuild the search index_.

After the 404 pages from the new calendar are encountered, the queue stops after one more successful entry.

![screen shot 2016-10-26 at 13 19 42](https://cloud.githubusercontent.com/assets/4970961/19724198/487d57ee-9b7f-11e6-9b10-5e057b5d6cca.png)

**Comment by leofeyer** [comment]
> In der Online Demo kann man den Fall von @arno1979 nicht reproduzieren, da man in der Online Demo die Option __Index protected pages__ nicht aktivieren kann.

Deswegen hatte ich ja gefragt, wie man "das z.B. mit der Contao Official Demo reproduzieren" kann und nicht wie man das in der Onlinedemo reproduziert.

**Comment by leofeyer** [comment]
Ok, so as a quick fix, you can simply adjust the `be_rebuild_index.html5` template and restore the previous version without the request queue:

```html
    <script>
      window.addEvent('domready', function() {
        var urls = $$('.page_url'),
            completed = 0;
        urls.each(function(el) {
          el.getAttribute('data-url') && new Request({
            url: el.getAttribute('data-url'),
            onSuccess: function() {
              el.addClass('tl_green');
            },
            onFailure: function(xhr) {
              el.addClass('tl_red');
              el.set('text', '[' + xhr.status + '] ' + el.get('text'));
            },
            onComplete: function() {
              if (++completed >= urls.length) {
                $('index_loading').setStyle('display', 'none');
                $('index_complete').setStyle('display', 'block');
              }
            }
          }).get();
        });
      });
    </script>
```

**Comment by tsarma** [comment]
Adding `queue.resume();` inside both `onSuccess` and `onFailure` function works also.

**Comment by leofeyer** [comment]
Yes, it seems to be a bug in the `Request.Queue` class that it calls `runNext()` instead of `resume()` in the onCancel, onSuccess, onFailure and onException methods. I am already working on a fix.

**Comment by leofeyer** [comment]
I have fixed the issue in Contao 4 in contao-components@6ad0118f6795704775a7d4fe59819e0dba266200.

**Comment by arno1979** [comment]
Ok, great, thanks for taking care of this.
And I won't continue trying to recreate this on the official demo version. I had no problem indexing protected pages there without selecting a frontend user. But when selecting for instance "John Doe" no pages get indexed at all.

**Comment by leofeyer** [comment]
I have fixed the issue in Contao 3 in f2acb55f0efde992502554188b6229a608c85e5d.

**Comment by tsarma** [comment]
I think issue number #8535 is wrong here https://github.com/contao/core/commit/f2acb55f0efde992502554188b6229a608c85e5d#diff-952066d567123da84efbd01c59d6340dR8

**Comment by leofeyer** [comment]
Fixed in e331658f62065854474a916aa86b3a8223e03cf4.

**Comment by mlwebworker** [comment]
Im Forum wurde mit https://community.contao.org/de/showthread.php?64531-Suchindex-neu-aufbauen-funktioniert-nicht-mehr-nach-Update-auf-3-5-18&p=424618&viewfull=1#post424618
gemeldet, dass zumindestens bei Multidomänumgebungen auch weiterhin Probleme vorhanden sind.

**Comment by fritzmg** [comment]
@mlwebworker das hat nichts mit dem Problem hier zu tun. Das was du meinst, ist folgendes Problem: https://github.com/contao/core/issues/8448

**Comment by arno1979** [comment]
Also bei mir funktioniert das indizieren geschützter Seiten leider immer noch nicht. Frontend-User mit Rechten für alle geschützten Seiten ist ausgewählt, aber trotzdem werden 403 Meldungen zurück gegeben sobald der Indexer versucht eine der geschützten Seiten zu indizieren.
Ich habe auch noch mal gecheckt: Sobald der Neuaufbau gestartet wird, wird auch eine FE_USER_AUTH Session in der tl_session angelegt. Eine Anmeldung scheint also statt zu finden, daran sollte es nicht liegen. Wenn ich mir aber z. B. im Firebug in der Konsole das HTML eines der 403 Einträge ansehe, dann bekomme ich da die "Zugriff verweigert"-Seite von Contao angezeigt. Das System erkennt also nicht, dass ein Frontend-Benutzer angemeldet ist und dementsprechend kann die Seite auch nicht indiziert werden.
