### ISSUE TITLE
Login right after password change may fail

### ISSUE THREAD

**Issue by bennyborn** [contao/core#8542]
Today we launched a site which has thousands of users imported from the old page. The users has been informed about the relaunch via newsletter so we currently got plenty of traffic on it. Because we could not decrypt the old passwords all users now have to request a new one - nothing unusual so far. But many users are now complaining that their new passwords don't work. We can confirm this. Right after setting a new password the login might fail from time to time.

I dug a bit into the core and noticed that the User class does a simple `execute` for it`s SELECT query which might lead into cached results.

My idea: Users try to login using their old password (which of course fails), request a new one and try to login again. But because the old SELECT statement is still cached we get the old password and the login fails.

So I think the User class should use `executeUncached` instead of `execute`. What are your thoughts on this? The line in question is this one https://github.com/contao/core/blob/master/system/modules/core/library/Contao/User.php#L527

**Comment by leofeyer** [comment]
The [executeUncached](https://github.com/contao/core/blob/master/system/modules/core/library/Contao/Database/Statement.php#L514-L519) method has been deprecated a long time ago and is only an alias for `execute`. The query is cached by MySQL.

@contao/developers /cc

**Comment by Toflar** [comment]
I'm sorry but where exactly is Contao caching anything?

**Comment by bennyborn** [comment]
@Toflar There was a misunderstanding. I thought `execute` would still cache the results. Thats probably why there was an `executeUncached` method earlier.

According to the MySQL documentation there is a `SQL_NO_CACHE` option to prevent caching of a specific query. A solution could be changing the SELECT to the following
```sql
SELECT SQL_CACHE * FROM " . $this->strTable . " WHERE " . $strColumn . "=?
```

**Comment by Toflar** [comment]
Sorry but I think this is due to some weird database setup and not an issue for Contao.

**Comment by bennyborn** [comment]
No weird setup, site is hosted on HostEurope which runs the MySQL with the default config.
And according to the MySQL [documentation](http://dev.mysql.com/doc/refman/5.7/en/query-cache-operation.html) this query is totally a query that would be cached.

**Comment by aschempp** [comment]
Are you maybe using a cluster or something?

> If a table changes, all cached queries that use the table become invalid and are removed from the cache. This includes queries that use MERGE tables that map to the changed table. A table can be changed by many types of statements, such as INSERT, UPDATE, DELETE, TRUNCATE TABLE, ALTER TABLE, DROP TABLE, or DROP DATABASE.

On a regular database configuration, the cache is automatically invalidated if you update a record.

**Comment by leofeyer** [comment]
> On a regular database configuration, the cache is automatically invalidated if you update a record.

That was my understanding, too.

**Comment by bennyborn** [comment]
> Are you maybe using a cluster or something?
Nope, at least not to my knowledge. We're told they are running a standard MySQL for each customer on the shared hosting.

We`re running almost all of our sites on their servers and never experienced a similar problem. But then again I think we never had a site with hundreds of users simultaneously resetting their password :\

**Comment by ausi** [comment]
Is it possible, that some users try their old password more than three times so that the account is locked for some time?

**Comment by bennyborn** [comment]
Well, I've seen many temporarily locked accounts in the system log today but to be honest I've never thought of this scenario. I'm afraid you could be right. I`ll take a look at it tomorrow as soon as the next customer complains about it! :)

**Comment by aschempp** [comment]
I assume it would make sense to remove a lock if the user has reseted its password? Not sure if that's already the case

**Comment by ausi** [comment]
I agree. If someone resets his password, the lock should be removed.

**Comment by discordier** [comment]
See #8545

**Comment by leofeyer** [comment]
I'm closing this ticket in favor of #8545.
