### ISSUE TITLE
TinyMCE XSS

### ISSUE THREAD

**Issue by michelbalzer** [contao/core#8548]
Does this affect Contao and it's TinyMCE?

https://github.com/tinymce/tinymce/commit/c68a5930512d7b37b5dc495bde5f7cbb739e11e7

**Comment by leofeyer** [comment]
I don't think so, because we are not shipping the media plugin:

https://github.com/contao/core/tree/master/assets/tinymce4/plugins

**Comment by michelbalzer** [comment]
Okay. I just saw this when I was unterwegs and thought I should mention it here. I will close this then.
