### ISSUE TITLE
accessing 403/404 page directly shows Contao's default 403/404 page

### ISSUE THREAD

**Issue by fritzmg** [contao/core#8551]
I am not sure if this was any different in past Contao versions, but if you access the 403 or 404 page directly via their respective page aliases, e.g.
```
http://example.org/access-denied.html
```
or
```
http://example.org/page-not-found.html
```
Contao shows its default 403 and 404 page respectively, instead of the actual 403 or 404 page. This can also be reproduced in the Contao Online Demo:

1. edit the _Access denied_ page in the site structure.
2. change the alias to `access-denied`.
3. open http://demo.contao.org/en/access-denied.html

This is only a minor issue of course, since you typically do not ever open these pages directly.

**Comment by asaage** [comment]
> Contao shows its default 403 and 404

If you access ```http://example.org/access-denied.html || http://example.org/page-not-found.html``` directly - this has always been the case which is ok in my opinion.
Problem with redirect to start occured with hiting ```http://example.org/protected-page.html & http://example.org/not-existing-page.html``` if alias ```index``` not present.

**Comment by leofeyer** [comment]
This is the expected behavior, otherwise we would end in a redirect loop.
