### ISSUE TITLE
accessing 403/404 page directly causes redirect to start page

### ISSUE THREAD

**Issue by fritzmg** [contao/core#8552]
If you try to access the 403 or 404 page directly via their page aliases, you will be redirected to the start page, __iff__ your start page does _not_ have `index` as its alias and _Add the language to the URL_ is _not_ enabled.

1. Create a start page using the alias `home`.
2. Create a 403 page using the alias `access-denied`.
3. Do __not__ enable _Add the language to the URL_ in the system settings.
4. Open `http://example.org/access-denied.html`.

In Contao `3.5.18`. This will redirect you to `http://example.org/home.html`. May be also due to the changes in 32e70a8b290de70f46a8c0c11b585dc66365f5fc (for #8498).

If you are using the alias `index` instead for your start page, or if you are using _Add the language to the URL_, or if you are using Contao `3.5.17` or lower (?), you will instead see Contao's default 403 page (see also #8551).

**Comment by leofeyer** [comment]
Fixed in 756a39c2bcad15909be4934730fe8ed41267afad.
