### ISSUE TITLE
DCA: input type "select", includeBlankOption und options array mit einer Option 0 - default ist immer 0

### ISSUE THREAD

**Issue by arno1979** [contao/core#8554]
Ich habe gerade eine DCA Feld hinzugefügt. Folgende Konfiguration:
```php
$GLOBALS['TL_DCA']['tl_calendar_events']['fields']['ageFrom'] = array
(
    'label'                   => &$GLOBALS['TL_LANG']['tl_calendar_events']['ageFrom'],
    'exclude'                 => true,
    'inputType'               => 'select',
    'options'                 => array(0,1,2,3,4,5),
    'eval'                    => array('chosen'=>false, 'mandatory'=>false, 'tl_class' => 'w50', 'includeBlankOption' => true),
    'sql'                     => "int(10) unsigned NOT NULL default '0'"
);
```
Effekt: Obwohl ich `'includeBlankOption' => true` angegeben habe und diese auch als erstes im Select-Menü erscheint, ist sie beim Neuanlegen eines Datensatzes nicht die Default-Auswahl.
Dabei ist es egal, ob ich im Options-Array die 0 als string oder integer angebe und auch wo in der Reihenfolge die 0 steht. Sobald eine 0 im Options-Array ist wird diese als Default verwendet.
Auch ein explizites setzen des Defaults über den zusätzlichen DCA-Parameter z. B. `default => 1` ändert daran nichts.

**Comment by aschempp** [comment]
0 und leer werden in diesem Kontext gleichgesetzt, du solltest andere Werte für die Optionen verwenden.
