### ISSUE TITLE
Properly handle internal nofollow-links

### ISSUE THREAD

**Issue by atradior** [contao/core#8555]
Short version:
Setting nofollow in the page settings should not lead to nofollowing internal links to it.
If at all nofollowing internal links to an internal page should be a separate feature/toggle

In my presentation at  campixx 2016 i proposed a quick fix to the inconsistent handling of nofollow in Contao. Daniel was so nice to report this issue to the core team and offer a pull request. https://github.com/contao/core/pull/8276#event-593577722 

Unfortunately the current implementation is still not the best way. "nofollow" signals to search engines that all links on this page should not be followed (aka not trusted). You should use that tag for example when you can't controll the content of your page (e.g. user generated content). Another way to solve the UGC issues is to nofollow individual external links (in a way most blogs do it in the comments section). 

Using nofollow in the head leads to *all* links (internal + external) not trusted. Without going into to much details: you should never nofollow internal links, because why would you not trust pages on your own domain, thus using nofollow in the header is the "nuclear"-option.

Either way: using nofollow in the header should not change how internal links TO the page are treated. My suggestion is 

a) as default let all internal link be follow and 
b) if at all offer a toggle to nofollow internal links to a page. 

In my experience nofollowing internal links is an edge case and only relevant if you can't controll the generation of URLs on your domain (i.e. user can somehow create pages and you don't trust the content).

**Comment by Aybee** [comment]
Yes I agree, never use nofollow for your own pages. Only use it for links to websites you can't controll or if you reference a bad URL if at all.

**Comment by leofeyer** [comment]
@contao/developers /cc

**Comment by ausi** [comment]
> Unfortunately the current implementation is still not the best way.

I think the current implementation is correct. It only sets `rel="nofollow"` for links to internal pages that that have the robots tag set to `noindex,nofollow`, all others don’t get the `rel` attribute. 

The robots meta tag `noindex,nofollow` tells the search engine that it should ignore the whole page including all its links. So it makes sense that links to such a page get `rel="nofollow"` so that search engines don’t crawl the page in the first place.

**Comment by bekanntmacher** [comment]
Do not generally use nofollow links for internal links.

https://www.youtube.com/watch?v=4SAPUx4Beh8

**Comment by atradior** [comment]
Thats not correct in my humble opinion. First of all you should use noindex to indicate, that you dont want a page in the index, second of all you can you robots.txt to exclude single pages or parts of you webpage. Thirdly rel canonical is also sometimes an option.

Not trusting outgoing links (i.e. nofollow) does not imply that you dont want the page itself to rank. So consider the case you have a page with untrusted links you still want to rank in the results. nofollowing internal links to that page will make it really hard to do so.

> The robots meta tag noindex,nofollow tells the search engine that it should ignore the whole page including all its links. So it makes sense that links to such a page get rel="nofollow" so that search engines don’t crawl the page in the first place.

**Comment by bekanntmacher** [comment]
Did you see the above video of Matt Cutts (google)?

**Comment by ausi** [comment]
Matt Cutts advises that you should let the search engine crawl all pages on your site, even login pages. If you want to follow that, do not set `noindex` for any page and you will also get no `rel="nofollow"` links.

> Not trusting outgoing links (i.e. nofollow) does not imply that you dont want the page itself to rank.

That is correct for `nofollow`, but `noindex` means that the page should in fact not be ranked.

> So consider the case you have a page with untrusted links you still want to rank in the results. nofollowing internal links to that page will make it really hard to do so.

The current implementation in Contao does not add `rel="nofollow"` for such a page, because the page would be set to `index,nofollow`.

**Comment by leofeyer** [comment]
As discussed in Mumble on December 14th, we all think that the current implementation is correct.

> Did you see the above video of Matt Cutts (google)?

As @ausi told you, Matt Cutts also advised in the video that you should not use `noindex,nofollow` at all.
