### ISSUE TITLE
[3.5.x] - DCA - rgxp - extnd : & (Kaufmännisches Und) im Benutzernamen möglich

### ISSUE THREAD

**Issue by blackbee** [contao/core#8556]
Hallo zusammen,
mir ist heute ein Fehler aufgefallen, der bereits schon zu Problemen geführt hat.

Laut [](https://docs.contao.org/books/api/dca/reference.html) ist dort unter Eval -> rgxp -> extnd vermerkt:
_disallows #&()/<=>_

Allerdings kann man sehr wohl bei

- der Registrierung (Registrierungs-Modul)
- in der Mitglieder-Verwaltung (Backend)
- in der Benutzer-Verwaltung (Backend)

im Feld **Benutzername** ein **&** **_(Kaufmännisches Und)_** einsetzen. Dies akzeptiert Contao ohne Probleme, was es aber eigentlich laut DCA nicht soll.

**Getestet:**
Offizielle Demo: http://demo.contao.org
2 Installationen mit Contao 3.5.x

**Hinweis zum Formular-Generator:**
Wählt man für ein Feld im Formular Generator Extended Alphanumeric aus, funktioniert die Prüfung einwandfrei. (Getested ebenfalls auf der offiziellen Demo):

Eventuell wird die Eingabe des Benutzernamens nicht oder unvollständig durch den \Validator::isExtendedAlphanumeric geschleust? (Siehe modules\Core\library\Contao\Widget.php)

```
// Do not allow any characters that are usually encoded by class Input [=<>()#/])
case 'extnd':
if (!\Validator::isExtendedAlphanumeric(html_entity_decode($varInput)))
{
	$this->addError(sprintf($GLOBALS['TL_LANG']['ERR']['extnd'], $this->strLabel));
}
break;
```

**Comment by aschempp** [comment]
Wenn du die Funktionsbeschreibung ansiehst dann steht da nichts von einem kaufmännischen `&`. Wo hast du gelesen dass dies verboten ist? Ich vermute du hast einen Link nicht gepostet den du wolltest?

**Comment by fritzmg** [comment]
> Wo hast du gelesen dass dies verboten ist?

Ist in den docs: https://docs.contao.org/books/api/dca/reference.html

**Comment by fritzmg** [comment]
Looks like the documentation is wrong, since the comment actually says

> Do not allow any characters that are usually encoded by class Input

And the `Input` class only encodes `=<>()#/`.

**Comment by blackbee** [comment]
Maybe the problem is a little bit greater:
When you select **Extended Alpahnumeric Characters** in the form generator for a text field,

Contao gives u an error back, that the entered **&** is not allowed.

**Comment by fritzmg** [comment]
> Maybe the problem is a little bit greater:
> When you select Extended Alpahnumeric Characters in the form generator for a text field,
> 
> Contao gives u an error back, that the entered & is not allowed.

I can't reproduce that in the Contao Online Demo.

**Comment by blackbee** [comment]
Maybe my fault, that i selected a min character as well and entered only the **&**.

**Comment by leofeyer** [comment]
I'm closing this in favor of #8557 and contao/docs#433.
