### ISSUE TITLE
mediaelement.js and picture element problem on IE9

### ISSUE THREAD

**Issue by may17** [contao/core#8558]
The picture default template uses an conditional comment for ie9 wich inserts an video tag. This video tag is also interpreted by mediaelement.js on ie9 and an error occurs because there is no valid sources. This issue brings up horrible results on pages with images ;)

To fix this issue it would be better to set the selector in the j_mediaelement file to .ce_player video and .ce_youtube video.

Even if IE9 support has no high priority it would be generally better to concrete the selector to avoid further problems.

**Comment by leofeyer** [comment]
You mean

```js
$('.ce_player video,.ce_youtube video,audio').mediaelementplayer({
```

instead of

```js
$('video,audio').mediaelementplayer({
```

?

**Comment by may17** [comment]
Yes looks great. Thank You.

**Comment by may17** [comment]
I again slept on it and perhaps the solution:

`$('.ce_player video,.ce_youtube video,audio').mediaelementplayer({`

brings up problems in some systems because we only match for ce_player and ce_youtube but there are a lot of third party extensions and customizations out there that might be broken with this fix.

We need a selector like "invoke mediaelement on every video without video tags in picture tags".

Something like this:

```javascript
var media_items = $('video,audio').filter(function() {
  if($(this).parent().prop("tagName") !== "PICTURE") {
     return this;
  }
});

media_items.mediaelementplayer({
```

**Comment by leofeyer** [comment]
That is even better IMHO. Can we also apply it to `'video,audio'`?

**Comment by may17** [comment]
Yes we can. I will create an pull request for this issue.

**Comment by leofeyer** [comment]
I'm closing this in favor of #8568.
