### ISSUE TITLE
Einige Links auf externe Seiten funktionieren in der Frontend-Vorschau nicht

### ISSUE THREAD

**Issue by arno1979** [contao/core#8563]
Ich habe gerade von einem Kunden Rückmeldung bekommen, dass externe Links nicht funktionieren würden.

Auf Nachfrage stellte sich heraus, dass die Links in der Frontend-Vorschau überprüft wurden und ich konnte in der Tat nachvollziehen, dass einige Links funktionieren und einige nur eine weiße Seite verursachen.

Beispiele:
funktioniert nicht:
`<a href="https://www.facebook.com/WIR.im.offenen.Gespraech/" class="button">Website</a>`
funktioniert:
`<a href="http://www.akademie-der-vielfalt.org/" class="button">Website</a>`

Wohlgemerkt: Sind die Artikel veröffentlicht und werden regulär aufgerufen funktioniert alles ganz normal!

**Comment by fritzmg** [comment]
Ich kann mir nicht vorstellen, dass das ein Problem von Contao ist. Was heißt überhaupt "sie funktionieren nicht"?

**Comment by arno1979** [comment]
Es ist halt nicht nur ein Link, sondern mehrere.
Es wird eine weiße Seite angezeigt, schrieb ich ja.

**Comment by fritzmg** [comment]
Ja, aber das kann von Contao nicht verursacht werden. Contao gibt ja von Haus aus keinen click Listener auf derartige Links. 

Du musst analysieren warum das passiert. 

Das Thema ist im Community Forum wohl besser aufgehoben.

**Comment by arno1979** [comment]
Wie du meinst.

**Comment by leofeyer** [comment]
Vermutlich bleiben die Seiten weiß, weil Sie innerhalb des Framesets geladen werden und dann irgendeine Same-Origin-Policy greift. Die Preview-Bar sollte eh schon lange mal auf "ohne Frameset" umgebaut worden sein, wäre da nicht das Manpower-Problem …

**Comment by fritzmg** [comment]
Ja, https://www.facebook.com/WIR.im.offenen.Gespraech/ hat tatsächlich
```
X-Frame-Options: DENY
```
im Response Header. http://www.akademie-der-vielfalt.org/ hingegen nicht, der Link sollte funktionieren.
