### ISSUE TITLE
Kommentarfunktion: Keine Benachrichtigung an User bei Antwort auf einen Kommentar

### ISSUE THREAD

**Issue by quintacom** [contao/core#8565]
Scheinbar wird man leider nicht informiert, wenn eine Antwort per Backend auf einen Kommentar gepostet wird. Auch wenn man zuvor "Über neue Kommentare per E-Mail benachrichtigen" bei seinem Kommentar markiert und in der E-Mail per Link aktiviert hat.

Aufgefallen und gestestet konkret bei Contao 3.4.5, aber auch bei 3.5.12. In der Online-Demo konnte ich das nicht testen oder nachvollziehen, da dort anscheinend grundsätzlich keine Benachrichtigungen versendet werden. Kann das sein? Ich habe dort jedenfalls keine Mails (auch nicht zum Aktivieren) bekommen. 

Wenn es tatsächlich so sein sollte, kann es unmöglich so bleiben. Denn derjenige, dem die Antwort auf seinen Kommentar gilt, muss doch benachrichtigt werden.

**Comment by Aybee** [comment]
Mein Test in der Online-Demo war auch negativ. Sollte behoben werden, wenn dem tatsächlich so ist.

**Comment by leofeyer** [comment]
> wenn eine Antwort per Backend auf einen Kommentar gepostet wird. Auch wenn man zuvor "Über neue Kommentare per E-Mail benachrichtigen"

Genau, denn das eine ist eine **Antwort** und das andere ein **neuer Kommentar**; und die Checkbox heißt "über **neue Kommentare** per E-Mail benachrichtigen". Insofern wäre es also ein neues Feature und kein Bugfix.

**Comment by quintacom** [comment]
Ok, so gesehen hast Du natürlich recht. Dann soll das also so sein ... 
Aber wozu soll ein Redakteur oder Administrator eine Antwort auf einen Kommentar geben, wenn derjenige davon nichts mitbekommen wird? Höchstens wenn er zufällig wieder auf den Beitrag geht.

**Comment by leofeyer** [comment]
Ja, das ergibt nur wenig Sinn. 😄

**Comment by Aybee** [comment]
👍 für dieses Feature - notify commenter on reply.

**Comment by leofeyer** [comment]
Implementiert in contao/core-bundle@ca3947c6d59858a90007a27cd0961243ceb5655b.

**Comment by Aybee** [comment]
Vielen Dank 💯
