### ISSUE TITLE
TinyMCE creates [nbsp] entities too often

### ISSUE THREAD

**Issue by ausi** [contao/core#8566]
If I edit a lot of text in Contao I often get many `[nbsp]` all over the text (especially in Chrome).

Can be reproduced in Chrome:

1. Create new text element
2. Write the word `Lorem`
3. Link the word to `#`
4. Move the cursor at the end and press <kbd>SPACE</kbd>
5. Write the word `Ipsum`
6. Save

After that the text is shown as `Lorem[nbsp]Ipsum`.

To fix that we should IMO hook into the tinyMCE editor and replace all `&nbsp;` that seem to be wrong with a regular space character.

**Comment by fritzmg** [comment]
Maybe this should rather be fixed in TinyMCE itself. Sounds similar to #7690.

**Comment by ausi** [comment]
I’m not sure if that’s possible. AFAIK the browser itself inserts the `&nbsp;`.

**Comment by fritzmg** [comment]
I don't know, they were able to fix that issue with the insert link plugin. But maybe that's different.

**Comment by leofeyer** [comment]
Just for the record, this is the snippet I use in my `dcaconfig.php` file to work around the issue:

```php
$callback = function($val) {
    return str_replace('[nbsp]', ' ', $val);
};

if (!empty($GLOBALS['TL_DCA'][$this->strTable]['fields'])) {
    foreach ($GLOBALS['TL_DCA'][$this->strTable]['fields'] as &$field) {
        if (isset($field['eval']['rte']) && strncmp($field['eval']['rte'], 'tiny', 4) === 0) {
            $field['save_callback'][] = $callback;
        }
    }
}
```

**Comment by Toflar** [comment]
@ausi any news on this? :)

**Comment by ausi** [comment]
Yes. I found another way to reproduce it :)

In Chrome:

1. Create new text element
2. Write the words `Lorem ipsum`
3. Mark the word `ipsum`
4. Overwrite it with `dolor`
5. Save

After that the text is shown as `Lorem[nbsp]dolor`.

**Comment by ausi** [comment]
As it looks like they can appear everywhere, the question is where do we want to keep them?

IMO in the following cases the `&nbsp;` should **not** get removed:

* If there are two or more like `Lorem&nbsp;&nbsp;ipsum`
* Following a whitespace followed by text like `Lorem &nbsp;ipsum`
* Preceding a whitespace followed by text like `Lorem&nbsp; ipsum`
* If they are the only content of an element like `<p>&nbsp;</p>`, `<td>&nbsp;</td>`,...

In all other cases they should get replaced with an ordinary space character, e.g.:

* `Lorem&nbsp;ipsum`
* `Lorem&nbsp;</p>`
* `<p>&nbsp;Lorem`

If we agree on that, I can create a pull request that implements a tinyMCE plugin for that.

**Comment by fritzmg** [comment]
Why not replace all `&nbsp;` by default and only keep `[nbsp]` (which presumably have been deliberately entered by the user)?

**Comment by ausi** [comment]
This would change the behavior for things like `<p>&nbsp;</p>` and `Lorem&nbsp;&nbsp;&nbsp;&nbsp;ipsum`. I think this would not be a good default for most users.

**Comment by Toflar** [comment]
> If they are the only content of an element like <p>&nbsp;</p>, <td>&nbsp;</td>,...

Why this?

**Comment by asaage** [comment]
@Toflar empty elements would not be rendered and there are plenty of editors out there  who try to achive spacing between paragraphs by hitting Enter in TinyMCE.
empty ```<td>```'s can stall the tcpdf generator on some Windows-systems

**Comment by ausi** [comment]
>> If they are the only content of an element like `<p>&nbsp;</p>`, `<td>&nbsp;</td>`,...
> 
> Why this?

Because [tinyMCE itself adds `&nbsp;`](https://github.com/tinymce/tinymce/blob/793f54807510d4e931d73d1f9c2956114e22704d/js/tinymce/classes/html/Schema.js#L704-L707) automatically for many elements if they are empty, like `<p>`, `<h1>`, `<td>` and more. We could check for this configuration with `editor.schema.getElementRule('p').paddEmpty` and only strip the `&nbsp;` if it’s `false`.

**Comment by ausi** [comment]
I created a pull request for tinyMCE: tinymce/tinymce#3455

**Comment by guay** [comment]
What might help when customizing you own tinyCustom.php. Add the following 2 code lines:
entity_encoding: 'raw',
entities: '160,nbsp',
Thus, manually set [nbsp] will remain in your text, but no [nbsp] are added automatically.
Read: https://www.abeautifulsite.net/tinymce-removes-non-breaking-spaces

**Comment by ausi** [comment]
This doesn’t fix the issue IMO. It just changes how the non-breaking space is displayed in the source code. After your change it gets saved as a raw `U+00A0` unicode character instead of the html entity `&nbsp;`, but it is still a non-breaking space and also behaves that way.

**Comment by leofeyer** [comment]
@ausi Shall we close this ticket? It seems we cannot do much except waiting for the TinyMCE developers to merge your PR, can we?

**Comment by ausi** [comment]
> It seems we cannot do much except waiting for the TinyMCE developers to merge your PR, can we?

My tinyMCE pull request adds the `stripnbsp` plugin, so we could just add this plugin to `contao-components/tinymce4`. But maybe we should wait a little bit longer to get some feedback from the tinyMCE developers?

**Comment by leofeyer** [comment]
I don't know if there will be more feedback, but generally you are right.

**Comment by ausi** [comment]
@leofeyer As there is still no feedback from the tinyMCE developers, I think we should add this plugin to `contao-components/tinymce4`.

**Comment by leofeyer** [comment]
Definitely.

**Comment by ausi** [comment]
@leofeyer tinymce/tinymce#3455 is now up to date and it should be possible to merge it into contao-components now.

**Comment by leofeyer** [comment]
Done. I have added the plugin to https://github.com/contao-components/tinymce4 (version 4.6.3+). Thank you very much @ausi.

**Comment by ausi** [comment]
@leofeyer Should we add it to the *be_tinyMCE.html5* template too?

**Comment by leofeyer** [comment]
I already have: https://github.com/contao/core-bundle/commit/0d97ecb36efda5b94e2444a78ea4a7e19997b022

**Comment by ausi** [comment]
Awesome, Thanks 🎉
