### ISSUE TITLE
Impossible to login to Contao (BE) with OVH (french hosting company)

### ISSUE THREAD

**Issue by sebj54** [contao/core#8567]
Hi,

I don't know if some of you use [OVH](https://www.ovh.com/), but it is an hoster very popular in France. Since the end of October, it is nearly impossible to login to the backend of Contao.

Each time you try to login, you are facing this error message: "You have to allow cookies to use Contao.". I didn't met the issue because we are using servers, not shared hosting. Another French developer talked to me about this bug and asked me to inform Contao developers. Here is a post in the Franch forum about this issue: https://community.contao.org/fr/viewtopic.php?f=1&t=3521.

He also gave me more informations about the problem and a way to fix it. Apparently, it seems to be due to a new cache system on shared hosting.

Here is the answer he got from OVH support:

> Voici le retour de nos administrateurs.
>
> Nous ne supprimons pas les cookies, ils sont transmis tel quel aux scripts. Par contre, nous en ajoutons un pour que les requêtes soient au maximum transmisses au même serveur web.
> 
> Ce que nous voyons c’est qu’il y a trois redirections (donc quatre requêtes) pour lesquelles le navigateur envoie correctement les cookies qu’il reçoit. Votre script les réceptionne correctement (testé avec `print_r($_COOKIE);` dans index.php) mais, lors de la dernière redirection ils sont supprimés.
> 
> Il fort probable que c'est votre script qui a un souci avec les cookies que nous avons ajouté. Ils servent au bon fonctionnement de l’infrastructure, il faut effectuer des corrections à votre niveau.

In English:
> Here is the return from our adminstrators.
>
> We don't delete cookies, they are transmitted as they are to the scripts. On the other hand, we add a new one in order to make requests transmitted to the right web server.
>
> What we see is that there are three redirects (so four requests) for which the browser sends correctly the cookies it receives. Your script receives theme correctly (tested with `print_r($_COOKIE);` in index.php) but they are deleted with the last redirect.
>
> Most likely, your script has an issue with cookies we have added. They are used to the good functioning of the infrastructure. You have to do some fixes at your level.

Do you have any idea of what causes this problem? 
I actually don't have any shared hosting to provide, but I can ask to the developper if needed.

Thanks in advance!

**Comment by fritzmg** [comment]
Why are there three redirects?

**Comment by iGweb** [comment]
Hello, I encounter the same problem !!

Here is a link to the site in question:
http://www.cabinetsofar.com/contao
ID: admin
PASSWORD: 12345678

Thanks in advance !
Samuel TRICOT - iGweb

**Comment by leofeyer** [comment]
> http://www.cabinetsofar.com/contao

This is obviously not a default and/or complete installation. The layout is broken.

**Comment by iGweb** [comment]
Hello,
Thank you for your messages !

I just put a "standard" version of contao allowing you to identify the problem

Here is a link to the site in question:
http://www.cabinetsofar.com/contao
ID: admin
PASSWORD: 12345678

Thanks

**Comment by bezin** [comment]
> I just put a "standard" version of contao allowing you to identify the problem

I just logged into your backend perfectly without any issues?

**Comment by sebj54** [comment]
Personnaly, I encounter the described bug in Chrome & Firefox (both with last versions).
![image](https://cloud.githubusercontent.com/assets/5880435/20180530/1fb68e06-a75b-11e6-9620-17c6a535a225.png)


I also see the three redirects:
![image](https://cloud.githubusercontent.com/assets/5880435/20179970/c45beac6-a758-11e6-9ae4-09c0fca2b787.png)

**Comment by fritzmg** [comment]
It also does not work for me.

**Comment by ADoebeling** [comment]
I can confirm the problems on your installation. (Win10/Chome/GE)

Every file from your server is trying to write a cookie:
`Set-Cookie:SERVERID585=2020175|WCSxM|WCSuK; path=/`

This cookie seems to be requested by your server configuration. May this be the reason for your issues?

**Comment by sebj54** [comment]
I don't understand the closing of this issue...

Sure the server tries to write a cookie for every file: this behavior is explained in the first post and is required by OVH on shared hosting. So starting from now Contao is considered no longer compatible with this hosting?

**Comment by leofeyer** [comment]
Can you upload the Contao check so we can validate the installation please?

**Comment by sebj54** [comment]
Thanks for the reopening.

Check is online now and the installation looks conform (except for flexible backend theme). 
Do we need to make it 100% valid and update it to 3.5.18 ?

**Comment by leofeyer** [comment]
Yes.

**Comment by sebj54** [comment]
Sorry for the delay.

Contao have been updated to 3.5.18 and the installation should be conform now.
The problem is still there for me.

**Comment by leofeyer** [comment]
@sebj54 Can you please send me the FTP or SSH login credentials via e-mail? I'll look into it.

**Comment by leofeyer** [comment]
Ok, I figured it out. For some reason, the IP address changes upon every request – maybe due to a proxy server –, therefore you have to disabled the session IP binding in your `localconfig.php`:

```php
$GLOBALS['TL_CONFIG']['disableIpCheck'] = true;
```

Now it works as expected.

**Comment by Toflar** [comment]
That's lowering security. Imho you should find out the OVH proxy IP's and then configure them all in `$GLOBALS['TL_CONFIG']['proxyServerIps'] = '1.1.1.1,2.2.2.2,etc.';`. That way, Contao will ignore all the proxy IP's and - unless there's yet another proxy in between - find the correct IP of the end user.

**Comment by fritzmg** [comment]
Or, if you want to do it via the Contao back end, go to _System_ » _Settings_ » _Proxy configuration_ and enter the IPs in __Trusted proxy servers__ (also comma separated).

**Comment by fritzmg** [comment]
Btw. does it even matter if you enter the trusted proxy servers or disable the IP check in general? In the end, does not _every_ request come from either of these proxy servers?

**Comment by Toflar** [comment]
It depends. Normally, proxy servers extend the `X-Forwarded-For` (or `Forwarded-For`) header by their own IP. So sou end up having e.g. `<proxy-ip>, <user-ip>`. If you have 3 proxies you should have  `<proxy-ip>, <proxy-ip>, <proxy-ip>, <user-ip>`. Now if you trust all these 3 proxies this means you must know their ip addresses. You can then enter them in the `proxyServerIps` setting which will cause Contao to ignore them when detecting the IP address of a user (which is untrusted obviously).

**Comment by sebj54** [comment]
Thanks everyone for your help!

@Toflar Your suggestion seems more secure to me too. 

So we have get back to OVH to know if this solution would work or not.

**Comment by sebj54** [comment]
I come back here for adding some information about the problem.

OVH doesn't want to share the IPs of their proxy servers so the only solution actually is to disable IP check.

**Comment by Toflar** [comment]
Okay, then the real solution is simple: Move away from OVH.
