### ISSUE TITLE
length restriction of config strings

### ISSUE THREAD

**Issue by m-vo** [contao/core#8569]
I just noticed there is a problem with long config options:

``$GLOBALS['TL_FFL']['vendor-prefix_module-name_fieldA']`` -> 32 chars: ok
``$GLOBALS['TL_FFL']['vendor-prefix_module-name_fieldAB']`` -> 33 chars: does not work

There is no error shown or logged, it fails pretty silently. In the case of a form field (the only thing I tested so far) even the name resolution from the language file works. When selecting the entry in the form element dropdown the site however reloads with the first entry ('headline') selected.

If there is a limit due to performance reasons, IMHO there should be an error generated when parsing the config file.

**Comment by fritzmg** [comment]
This happens because of
```php
		'type' => array
		(
			…
			'sql'                     => "varchar(32) NOT NULL default ''"
		),
```
In the `tl_form_field` DCA. The SQL server will silently truncate `vendor-prefix_module-name_fieldAB` to `'vendor-prefix_module-name_fieldA' when creating a form field of that type. Unless your SQL server is running in a strict mode, then there might be an error.

**Comment by m-vo** [comment]
I see! Is there a reason why the type column in ``tl_module`` is 64 chars long and the one in ``tl_form_field`` only 32?

Do you think adding length validation would be reasonable (or is this use case/error too specific?)

**Comment by fritzmg** [comment]
Every now and then somebody stumbles over this. The same applies to other parts of Contao, like Content Elements for example. I am not sure what the exact reason for this limitation is.

You can fix this yourself by adding
```php
$GLOBALS['TL_DCA']['tl_form_field']['fields']['type']['sql'] = "varchar(64) NOT NULL default ''";
```
to your `/system/config/dcaconfig.php` (and then do a database update).

**Comment by m-vo** [comment]
I think I can live with the limitation - as the name gets stored in a db column there will allways be one. It's good to know, however. :-)

Putting the sql server in strict mode is a good idea for the development environment anyway.

_Btw.: Would it be a good idea if ``Model->save()`` or maybe ``Model->__set`` performed a validation based on the dca-data in general? (Instead of letting the widgets and various code pieces do it on their own.) Possible drawbacks: a tighter coupling with the dca / performance_

**Comment by leofeyer** [comment]
We should probably set all the key fields to `varchar(64)`.

> I am not sure what the exact reason for this limitation is.

Space usage. MySQL will use the length declared in the column declaration when allocating memory, therefore you should not set your VARCHAR columns to the maximum if you know that you will not need it.

**Comment by leofeyer** [comment]
Changed in 544a6be7d0f5c07da9674a0cb6c675feab5295f8.
