### ISSUE TITLE
allowedTags mit SVG-Elementen erweitern

### ISSUE THREAD

**Issue by NinaG** [contao/core#8571]
Ich habe jetzt schon öfters verzagte Anfragen von Webdesignern und Online-Redakteuren bekommen, die versucht hatten den Code von SVG-Grafiken inline z.B. über das HTML-CE von Contao einzubinden. Ein Beispiel wäre der USE-Aufruf für Icons aus einem SVG-Sprite.

In den CEs läuft aber von Contao die Prüfung auf die HTML-Elemente und somit werden diverse Elemente unbrauchbar.

Ich könnte mir daher vorstellen, dass es sinnvoll wäre, die Standard-allowedTags um wichtige Elemente von SVG-Grafiken zu erweitern. Es müssen ja nicht alle möglichen SVG-Elemente sein, aber zumindest die wichtigsten. 

Wichtig wären wohl u.a.
die primären Container elements / Structural elements
` <defs> <g> <marker> <mask> <svg> <switch> <use>`

Basic Shapes / Elements
`<circle> <ellipse> <line> <polygon> <polyline> <rect> <text>`

Eine umfangreiche Referenz wäre hier:
https://developer.mozilla.org/en-US/docs/Web/SVG/Element

Optimal wäre vermutlich, wenn wir alle Elemente aufnehmen, dann führt es am wenigsten zu Verwirrung.

**Comment by NinaG** [comment]
Hier eine vollständige Liste abzüglich der Elemente, die wir sowieso schon in den allowedTags drin haben:

`<altGlyph><altGlyphDef><altGlyphItem><animate><animateColor><animateMotion><animateTransform>
<circle><clipPath><color-profile><cursor>
<defs><desc><discard>
<ellipse>
<feBlend><feColorMatrix><feComponentTransfer><feComposite><feConvolveMatrix><feDiffuseLighting><feDisplacementMap><feDistantLight><feDropShadow><feFlood><feFuncA>
<feFuncB><feFuncG><feFuncR><feGaussianBlur><feImage><feMerge><feMergeNode><feMorphology><feOffset><fePointLight><feSpecularLighting><feSpotLight><feTile><feTurbulence><filter>
<font><font-face><font-face-format><font-face-name><font-face-src><font-face-uri><foreignObject>
<g><glyph><glyphRef>
<hatch><hatchpath><hkern>
<iframe><image>
<line><linearGradient>
<marker><mask><mesh><meshgradient><meshpatch><meshrow><metadata><missing-glyph><mpath>
<path><pattern><polygon><polyline>
<radialGradient><rect>
<script><set><solidcolor><stop><svg><switch><symbol>
<text><textPath><title><tref><tspan>
<unknown><use>
<view><vkern>`

Ggfs sollte man aus Sicherheitsgründen <iframe> weiterhin rauslassen.

**Comment by asaage** [comment]
Da fände ich es ehrlichgesagt besser wenn man ```{{file::grafik.svg}}``` nutzt. So mach ich das jedenfalls immer.
Ich befürchte allerding, man kommt damit nicht aus dem Template-verzeichnis heraus - Resourcen aus der Dateiverwaltung fallen damit glaube ich aus.
Wie wäre es mit einem extra Contentelement mit file-picker dafür?

**Comment by NinaG** [comment]
Es geht ja nicht um die Verlinkung von SVG-Dateien, sondern echten Inline-Code von SVG innerhalb der Seite. Damit kann man dann z.B. Symbole via USE-Element aufrufen, animieren, umfärben, etc. weil es alles innerhalb des eigentlich DOM der Seite bleibt.

**Comment by asaage** [comment]
Ich habe auch nicht von Verlinkung gesprochen. Der ```{{file::}}``` InsertTag würde genau das erzeugen, was du meinst.

**Comment by NinaG** [comment]
Ich weiß schon, was `{{file::}}` macht (ein Template referenzieren). Aber inwiefern löst es das Problem, dass der SVG-Code im HTML-CE kaputt gemacht wird? Die Redakteure sollen ja aktiv auf den SVG-Code einwirken können.

Wennman den Code (den sie nutzen und ggf. auch anpassen sollen) in ein Template auslagert, müsste man ihnen auch darauf Zugriff geben. Das ist ein enormes Zusatzrecht.

Mit der Logik müsste man ja auch das gesamte HTML-CE entfernen, denn dann könnte man ja generell sagen: Lagert alles ins Template aus. Aber es hat eben seine Berechtigung und existiert deshalb. :)

**Comment by asaage** [comment]
Deswegen meine ich ja bräuchte es vielleicht ein neues Inhaltselement das wie {{file}} funktioniert aber Zugriff auf Dateien der Dateiverwaltung hat. Dann genügt ein Upload der svg-Datei. SVG im Code-editor zu bearbeiten wäre mit zusätzlichen allowedTags zwar auch gangbar aber ich denk die meisten verwenden dafür doch lieber das Grafikprogramm ihrer Wahl.

**Comment by asaage** [comment]
btw.. ```<script>``` aufzunehmen aber ```<iframe>``` auszuschließen macht Sicherheitstechnisch glaube ich auch nicht soviel Sinn.

**Comment by leofeyer** [comment]
Korrekt. Keines von beiden sollten wir erlauben.

**Comment by thomaspahl** [comment]
Ich denke, die ``allowedHtml`` Liste mit SVG tags zu fluten, ist nicht die beste Lösung. SVG ist ein XML-Container, die Tags haben ggf. auch eine andere Semantik, das Ganze bringt (s.o.) u.U. unerwünschte Effekte in den HTML-Bereich.
M.E. wäre es besser, an der entsprechende Stelle (``Input::postHTML() ?``) SVG- und ggf. andere XML-Container auszufiltern, strip_tags auf den reinen HTML-Rest anzuwenden und dann die SVG-Blöcke wieder einzufügen. Ggf. kann man für gefährliche SVG-Tags dann ``allowedSvg`` einführen.

Ich arbeite viel mit kleinen SVGs und habe Instanzen, in denen in ``Input::postHTML()`` deshalb die strip_tags Zeile auskommentiert ist (d.h. alle Tags gehen durch) - was auch nicht for the general public geeignet scheint.

**Comment by Toflar** [comment]
Filtern ist generell keine gute Idee. Man kann nie wissen, was gefährlich ist. Unser Input-Encoding werden wir in Contao 5 komplett weglassen und in sauberes Output-Encoding umwandeln müssen. Die Beispiele hier zeigen bereits, dass es keinen Sinn macht zu filtern. Wir können dem User nicht vorschreiben, was sicher ist und was nicht. Ich persönlich weiss was sicher ist und ich kann auch mit `<script>` umgehen. Imho sollte einfach alles erlaubt sein, wenn man Zugriff auf das HTML-Element hat und es muss auch Teil der Schulung für Redakteure sein, nicht einfach blind etwas reinzukopieren ohne zu verstehen, was es tut. Ich brauche das HTML-Element für Redakteure sowieso nie, ich baue immer eine Reihe von eigenen Inhaltselementen die genau das tun, was sie sollen. Z.B. auch ein iFrame ausgeben. Also wenn dann würde ich wohl die ganze Prüfung weglassen und nicht um 200 Tags erweitern.

**Comment by KaiserCh** [comment]
Na ja, es ist ja nicht nur das reine HTML-Element, bei dem man Schindluder treiben kann. Klar, es ist prädestiniert dafür, aber rein theoretisch kann man auch im CE_Text auf den HTML-Knopf drücken, und da hat ja nun jeder Redakteur Zugriff.

Und ich glaube nicht, dass man Redakteure tatsächlich erziehen kann. Das geht vielleicht im kleinen Rahmen mit intelligenten Leuten, aber die Masse ist einfach dämlich. Ich hab mit zu vielen wirklich inkompetenten und vor allem belehrungsresistenten Kunden zu tun gehabt, als dass ich eine Freigabe von <script> oder <iframe> auch nur ansatzweise begrüßen könnte.

**Comment by NinaG** [comment]
Dämlich finde ich unpassend. Unerfahren trifft es imho besser. Die Redakteure können meist die Nachwirkungen gewisser Aktionen nicht abschätzen. Schon oft gesehen: Redakteure kopieren direkt von einer Website und ziehen sich dadurch unwissentlich den original Code von dieser Website in den Editor. Wenn da keine Sperre auf gewisse Scripts u.ä. drin ist, ziehen die sich so schon mal unabsichtlich ganze Scripts mit rüber.

**Comment by KaiserCh** [comment]
Das ist jetzt eine Auslegungssache. Wenn man die Redakteure schult und ihnen klar macht, wie der Workflow geplant ist, und sie sich dann trotzdem nicht daran halten, ist das entweder dämlich oder mutwillig geschäftsschädigend.
Wie gesagt, ich hatte zu oft den Fall, wo Redakteure sich beschwer haben, dass sie kein Twitter/... Fertig-Skript eintragen können, obwohl ihnen vorher mehrfach gesagt wurde, dass gewisse Optionen aus Sicherheitsgründen gesperrt sind. Belehrung lesen, Belehrung unterschreiben, Belehrung ignorieren... Dagegen hilft nur eine restriktive Politik seitens der Administratoren.

Manches kann man einfach nicht als "unerfahren" einstufen, sondern nur als "denkt nicht von 12 bis Mittag". Contao schränkt z.B. die Dateitypen nicht ein, die man im ce_text bei "Bild hinzufügen" wählen kann. Ein User, der tatsächlich mal mitdenkt, weiß aber, was Bilder sind und was nicht. Trotzdem hatte ich schon häufiger den Fall, dass da jemand eine PDF gewählt hat... Soviel dazu, wenn man Usern zu viel Freiheit lässt, auch wenn der Grund hier ein Bug ist.

**Comment by Toflar** [comment]
Wie dem auch sei, ich bin dagegen, die SVG-Tags zu den erlaubten Tags hinzuzufügen. Die beziehen sich ganz klar auf HTML und nicht auf SVG. Wenn, dann sollten wir ein Inline-SVG-Inhaltselement hinzufügen, das sich anders validiert. Oder gar nicht. Oder alles in `<svg>` wrappt. Ich denke das wäre sinnvoller zu diskutieren.

**Comment by NinaG** [comment]
Ein SVG-Inhaltselement wäre mir auch recht.

**Comment by Toflar** [comment]
Und wie willst du da dafür sorgen, dass keiner Müll pasted? :)

**Comment by NinaG** [comment]
?

**Comment by Toflar** [comment]
?

**Comment by KaiserCh** [comment]
Unser Kernproblem ist doch: Wie verhindern wir, dass leichtsinnige oder mutwillig gemeine Redakteure Schaden anrichten können, ohne dass wir entsprechend sensibilisierte User unnötig einschränken.

Ausgehend von Contao 3.5, was können wir und was können wir nicht? 
Wir können einer Gruppe nicht den Zugriff auf einen Content Element Typ verwehren, also wäre ein "hier wird nicht validiert" - Contenttyp keine Lösung.
Wir können aber sehr wohl den Zugriff auf ein Feld beschränken.

Logische Lösung: tl_content kriegt eine weitere Checkbox "Validierung übergehen", die dann beim Speichern entsprechend mit ausgewertet wird. Den Rest regeln die Benutzer-/Gruppenrechte. Klar, wenn der Admin das Häkchen setzt, könnte ein für das Feld nicht befugter Redakteur dann bösartigen Code einpflanzen, aber hmpf. Irgendwas ist ja eh immer.

**Comment by Toflar** [comment]
Diesen Ansatz halte ich für nicht praktikabel. Kann mir mal jemand erklären, warum ein Redakteur überhaupt ein Inline-SVG einfügen will? Das macht für mich für redaktionelles Arbeiten irgendwie keinen Sinn. Der Beschriebene Use Case mit dem `use`-Statement halte ich für gesucht. Dann müssen die User ja sowas in HTML schreiben, ich kenne keinen Redakteur der in der Lage wäre, sowas zu tun. Wäre doch viel schlauer, denen ein `{{icon::foobar}}` zur Verfügung zu stellen? Und ausser für Icons sehe ich grad keinen Anwendungsfall?

**Comment by NinaG** [comment]
Gesucht ist der Use Case nicht, sondern real :)
Meiner Erfahrung nach, wird es meist fürs Einbinden von Icons und sonstigen Grafiken (SVG-Logos o.ä.) genutzt., wobei die eben nicht einzeln aus der Dateiverwaltung eingebunden werden sollen, sondern aus einer Inline-SVG-Sammlung. Das ist ein seriöser Anwendungszweck, wie er u.a. ganz normal für SVG-Techniken empfohlen wird.

Die Alternative ist, dass wir eindeutig sagen: Contao unterstützt von sich aus echtes Inline SVG für Redakteure nicht. Ihr braucht dafür eine Extension.

Ok, ist möglich, aber nicht schön.

**Comment by NinaG** [comment]
Und ja, Dinge wie {{icon::foobar}} sind schön und meist für Redakteure praktischer. Aber ich spreche hier halt von der generellen Frage, ob wir per Default Inline SVG für Redakteure unterstützen wollen oder nicht. Wenn die Antwort "Nein" ist, kann ich damit leben. Dann ist es aber zumindest geklärt.

**Comment by discordier** [comment]
Dann spricht aber wiederum alles fyr ein eigenes Inhaltselement, wo du das Container SVG einbindest (das mit den `<defs>`) und einen Insert Tag, wo du ein selbiges referenzierst (Wird dann zu `<use>`), ggf noch mit entsprechendem Attributssupport fyr `x="100" y="100" ...`.

**Comment by KaiserCh** [comment]
Ein Inhaltselement für die SVG würde nicht gehen, da kein CTE die Tags durch lässt. Henne-Ei... Aber muss ja auch nicht sein, einfach im fe_page ein {{file::basis-file.svg}} direkt hinter den öffnenden body-tag packen.

Ich für meinen Teil bezweifle, dass es generischer Inline-SVG - Support in den Core schafft. Dafür braucht man es doch zu selten. Ich hab schon Feature-Requests gesehen, die eine deutlich breitere Nutzerbasis ansprechen und trotzdem nur als Extension existieren.

**Comment by discordier** [comment]
Das CTE sollte auch einen file picker beinhalten, wo du die "library" auswaehlst.
Es macht keinerlei Sinn eine potentiell mehrere kb grosse Datei in ein Textfeld zu copy&pasten.

**Comment by KaiserCh** [comment]
Ich sehe ein CTE, dass Files aus dem Upload-Ordner direkt in die Seite inkludiert, als sehr riskant an. Wie schon gesagt, du kannst den Zugang zu CTEs nicht für Nutzergruppen beschränken. Also was würde einen User daran hindern, eine bösartige "SVG" in dem ihm zugänglichen Bilder-Ordner zu laden und dann als Inline-SVG zu injecten? Würde da PHP-Code drin stehen, wäre das der ultimative Security-GAU. Aber auch "normale" HTML/JS-Injection wäre extrem gefährlich.

Es hat schon seinen Sinn, warum {{file:: nur auf den Template-Ordner zugreifen darf, in den üblicherweise nur Admins und FTP-User können.

Außerdem: Wie du sagtest, mehrere kB Markup. Was würde einen User aus Unbedarftheit daran hindern, 5-6 solche großen CTE anzulegen? Plötzlich ist die reine HTML-Seite so groß wie eine Horde Icon-Fonts.
Vom Caching her ist das natürlich dann auch Mist. Der HTML-Part wird üblicherweise nicht beim User gecached.

**Comment by thomaspahl** [comment]
Es gibt auch kleinere SVGs, bei denen copy&paste eine effektive Lösung ist, wie @NinaG beschreibt...

Ich teste im Moment einen overlay für Input::PostHtml() (per extension, ca. 20 Zeilen zusätzlicher code), der SVG unbeschadet erhält. Bisher macht das in meinen Tests alles brav, ich gucke  im Moment nach side effects. Offen ist noch, wo man mit Durchlassen von SVG code security issues produziert, dh. da muss man ggf. SVG-spezifisch filtern (einfache PHP injects kommen aber nur als string as-is durch - im Quellcode).

Langfristig bin ich bei @toflar - original speichern und ggf. prüfen vor Output. Ich verwende Contao Data auch an anderer Stelle, und jedesmal nervt, dass man all die unerwünschten Änderungen in den Feldern, bei denen sich Contao einbildet, dass sie nötig sind, rückgängig machen muss.

**Comment by discordier** [comment]
@KaiserCh:
> Ich sehe ein CTE, dass Files aus dem Upload-Ordner direkt in die Seite inkludiert, als sehr riskant an. Wie schon gesagt, du kannst den Zugang zu CTEs nicht für Nutzergruppen beschränken.

Das ist aber wenn man den code pasten kann nicht anders, also kein Argument.

> Also was würde einen User daran hindern, eine bösartige "SVG" in dem ihm zugänglichen Bilder-Ordner zu laden und dann als Inline-SVG zu injecten? Würde da PHP-Code drin stehen, wäre das der ultimative Security-GAU. Aber auch "normale" HTML/JS-Injection wäre extrem gefährlich.

PHP Code wyrde verbatim auf der Webseite erscheinen, also in keinster Weise interpretiert werden.
Bei Javascript ist dies schon anders, da gebe ich dir recht, jedoch koennte man eben hier MIME type guessing oder XML validation betreiben.
Abgesehen davon ist jedoch das Problem, dass Javascript code in SVG ein sehr valider usecase und eines der killer features ist, dies sollte man meiner Meinung nach nicht verbieten.

Das Grundproblem was sich hier aktuell jedoch (in der Theorie) herauskristallisiert ist:

1. Ihr habt Redakteure die permanent versuchen wollen das System kaputt zu machen, der Firma zu schaden oder sonstigen Bloedsinn anzustellen anstatt damit zu arbeiten.
2. Ihr erwartet dass Contao dies verhindert, aber bitte ohne dass dem Redakteur hieraus Nachteile entstehen.

Fazit: Scheissen und Kraut hacken geht zeitgleich nicht - zumindest nicht mit den aktuellen Bordmitteln.

@thomaspahl Ouput encoding statt input encoding ist der einzig wahre Weg, weshalb wir den auch in Contao 5 beschreiten wollen, ebenfalls das "gesund strippen" des content ist aufgrund der Mannigfaltigkeit des contents (wie eben nun SVG) schlichtweg unmoeglich und muss just-in-time an der Stelle erfolgen wo er verarbeitet wird, nicht "ausserhalb" durch eine Input Klasse.

**Comment by asaage** [comment]
https://github.com/contao/core/issues/8571#issuecomment-261213817
> Wir können einer Gruppe nicht den Zugriff auf einen Content Element Typ verwehren

Das Konzept wäre eventuell auch mal zu überdenken - hat mich schon des öfteren mal gewurmt.

**Comment by NinaG** [comment]
Danke für die bisherigen Beiträge. Ich finde es klasse, dass ihr das so genau durchdenkt. 👍

**Comment by ausi** [comment]
> Unser Kernproblem ist doch: Wie verhindern wir, dass leichtsinnige oder mutwillig gemeine Redakteure Schaden anrichten können, ohne dass wir entsprechend sensibilisierte User unnötig einschränken.

Ich denke auch dass es genau darum geht. Es gibt die Unterscheidung zwischen „trusted“ und „untrusted“ User. Wenn einem Nutzer vertraut wird, kann man ihm Zugriff auf Felder erlauben die `preserveTags` auf `true` gesetzt haben wie z. B. „eigener JavaScript-Code“ in den Layouteinstellungen, denn für diese Felder gibt es keine Einschränkungen was eingegeben werden darf.

Wenn man also allen Nutzern die Zugriff auch HTML-Felder haben soweit vertraut, dass Sie `<script>`-Elemente einfügen dürfen, kann man einfach `preserveTags` dort aktivieren:

```php
$GLOBALS['TL_DCA']['tl_content']['fields']['html']['eval']['preserveTags'] = true;
```

Vertraut man den Nutzern nicht, sollte man weder `preserveTags` noch die oben erwähnte `allowedTags`-Liste verwenden, sonst hat man ein Sicherheitsproblem.

Möchte man aber „untrusted“ Usern eine Möglichkeit bieten um Inline-SVGs zu verwenden, braucht man ein Stück Software das diesen SVG-Code nach Sicherheitsregeln überprüft. Dieser Use-Case kommt mir jedoch sehr ungewöhnlich vor.

**Comment by discordier** [comment]
@ausi Genau darauf dass dieser Use case sehr ungewoehnlich ist wollte ich mit meinem letzten statement hinaus.

**Comment by Olli** [comment]
Warum greifen die allowedTags für Admins? Gerade die SVG Geschichte ist doch gerade für Adminnutzer interessant welche die Seite gestalten.

**Comment by ausi** [comment]
@Olli wenn ein Admin ein Element bearbeitet und darin SVG-Elemente einfügt und danach editiert ein Redakteur dasselbe Element, dann würden die SVG-Elemente wieder verschwinden wenn `allowedTags` nur für Redakteure gelten würde. Man kann jedoch Felder mit `preserveTags` ausstatten und nur Admins darauf Zugriff geben, dann können dort SVG-Elemente problemlos eingesetzt werden.

**Comment by Olli** [comment]
Ah ok klar macht Sinn. Wäre also optimal wenn man den Filter per Gruppe/User zu- und abschalten könnte.

**Comment by ausi** [comment]
Eben nicht. Du hättest nach wie vor das Problem, dass sobald ein Redakteur das Feld bearbeitet die Tags wieder rausfliegen. Die Konfiguration muss pro Feld erfolgen (`preserveTags`), nicht pro Benutzer/Gruppe.

**Comment by leofeyer** [comment]
Wie am 4. Juli auf Mumble besprochen, sind Inline-SVGs potentiell unsicher und wir wollen sie standardmäßig nicht freischalten.

**Comment by Olli** [comment]
Ok Sicherheit ist wichtig.
Wäre dann aber nicht eine "Hakenfunktion" interssant die in der Standardinstall nicht angehakt ist?
Hakt man die an, sind die SVG Tags freigeschaltet. Das macht die Sache recht übersichtlich und manageable für den Admin.
