### ISSUE TITLE
too many redirects on Home when alias is "index"

### ISSUE THREAD

**Issue by danielroeding** [contao/core#8572]
After Update from 3.5.12 to 3.5.19 this error comes up.
"too many redirects"

After changing the alias from index to home the Page is loading.

**Comment by leofeyer** [comment]
How do I reproduce the issue?

**Comment by danielroeding** [comment]
I set the alias of the startpage from "home" to "index" to remove the /home.html for the Homepage.

**Comment by leofeyer** [comment]
Works like a charm on my system:

<img width="576" alt="" src="https://cloud.githubusercontent.com/assets/1192057/20388251/45e3e290-acc4-11e6-9dd3-dab4ad652b39.png">

No redirect loop:

<img width="536" alt="" src="https://cloud.githubusercontent.com/assets/1192057/20388256/4a598d34-acc4-11e6-936b-7e62b4854ff1.png">

**Comment by danielroeding** [comment]
Mh ok. In my installation it is not working. I will test it on other projects.
![screenshot-2016-nov-17-108-pm](https://cloud.githubusercontent.com/assets/12136943/20389196/b6c90ab8-acc8-11e6-9727-f10b5d7e7eaa.png)

**Comment by aschempp** [comment]
Make sure there's no redirect configured in your .htaccess file.

**Comment by danielroeding** [comment]
yes. i use the default htaccess  file with only one custom change for all-inkl.com
addhandler php56-cgi .php

**Comment by NinaG** [comment]
And delete the addhandler-info. 

You don't need that anymore for All-Inkl. Log into Kasserver, go to "Domain", check if PHP is set to "5.6 CGI". If not, edit the settings.

**Comment by BugBuster1701** [comment]
Have you tested it with another browser?
