### ISSUE TITLE
Bugs with Date Picker in Backend

### ISSUE THREAD

**Issue by beaniemonk** [contao/core#8573]
This was tested in 3.5.19 in safe mode.

1. If the global date format is something like `n/j/y`, the date picker will add a space before single-digit days (e.g. `11/ 8/16`). This causes a validation error message when saving.

2. If the English `m/d/Y` format is used, the date picker will misinterpret it as  `d/m/Y` and open to the incorrect date. For example, 11/08/16 will open the date picker to August 11th, 2016.

![date-picker](https://cloud.githubusercontent.com/assets/1709265/20395366/aa0e6024-acb0-11e6-8273-3b5fece86562.png)

Thanks!

**Comment by fritzmg** [comment]
Just as a side note: if you want to change the date format for the front end, you should do that in the settings of the website root, not the system settings.

**Comment by leofeyer** [comment]
Fixed the first one in https://github.com/contao-components/mootools/commit/fd72125138d6455e090c8e922b772636368e93d3. I cannot reproduce the second one, though:

<img width="463" alt="" src="https://cloud.githubusercontent.com/assets/1192057/20563349/8193f6e0-b188-11e6-8594-929c67b69d82.png">

**Comment by beaniemonk** [comment]
I think you did reproduce the 2nd issue. :)

If your date format in global settings is "m/d/Y", then 08/11/2016 should open the date picker to August 11th. But in your screenshot it's opened to November 8th.

**Comment by leofeyer** [comment]
Fixed the second issue in contao-components/mootoosl@e0291f8620f1a289ca93ae23c017c0e8bbb161f5.

**Comment by leofeyer** [comment]
Back ported the changes to Contao 3.5 in 851d490f4b00bbec545ebcf67d195da276686f0d.
