### ISSUE TITLE
GalleryContent.php: „Division by zero“-Error wenn perRow über dcaconfig.php entfernt wurde

### ISSUE THREAD

**Issue by michelbalzer** [contao/core#8576]
- Contao 3.5.19
- PHP 5.6.12

Ich hatte in der _system/config/dcaconfig.php_ `$GLOBALS['TL_DCA']['tl_content']['fields']['perRow']` eingetragen, da niemand auswählen sollte, wie viele Bilder pro Reihe eine Galerie haben soll – machte meines Erachtens wg. Responsive Design keinen Sinn. Datenbank-Update, alle _perRow_-Felder in der _tl_content_ wurden – wie gewünscht – entfernt.

Jetzt entstand das Problem, dass Contao trotz allem versuchte, die Anzahl der Bilder pro Reihe zu ermitteln und versuchte so, durch Null zu teilen und nichts ging mehr (rödel rödel rödel).

```php
[22-Nov-2016 11:15:18 Europe/Berlin] 
PHP Warning: Division by zero in /system/modules/core/elements/ContentGallery.php on line 304
#0 /system/modules/core/elements/ContentGallery.php(304): __error(2, 'Division by zer...', '/kunden/300762_...', 304, Array)
#1 /system/modules/core/elements/ContentElement.php(265): Contao\ContentGallery->compile()
#2 /system/modules/core/elements/ContentGallery.php(76): Contao\ContentElement->generate()
#3 /system/modules/core/library/Contao/Controller.php(484): Contao\ContentGallery->generate()
#4 /system/cache/dca/tl_content.php(1166): Contao\Controller::getContentElement(Object(Contao\ContentModel))
#5 /system/modules/core/drivers/DC_Table.php(4284): tl_content->addCteType(Array)
#6 /system/modules/core/drivers/DC_Table.php(378): Contao\DC_Table->parentView()
#7 /system/modules/core/classes/Backend.php(650): Contao\DC_Table->showAll()
#8 /system/modules/core/controllers/BackendMain.php(131): Contao\Backend->getBackendModule('article')
#9 /contao/main.php(20): Contao\BackendMain->run()
#10 {main}
```

[Zeile 304, ContentGallery.php](https://github.com/contao/core/blob/master/system/modules/core/elements/ContentGallery.php#L304)

Sollte man da eine Prüfung einbauen, dass die Rechnung nicht gemacht wird, wenn perRow `0` oder `NULL` ist? (siehe auch #6186)

**Comment by bezin** [comment]
Du solltest das Feld aus der Palette nehmen und nicht das Feld im DCA deaktivieren :)

**Comment by leofeyer** [comment]
> Sollte man da eine Prüfung einbauen, dass die Rechnung nicht gemacht wird, wenn perRow 0 oder NULL ist?

Das glaube ich nicht, denn der Core muss nicht den Fall behandeln, dass Du ein Feld komplett entfernst. Da solltest Du besser @bezin's Rat befolgen.
