### ISSUE TITLE
Page/Filepicker should store file inserttag instead of real path in the database

### ISSUE THREAD

**Issue by timgatzky** [contao/core#8578]
Hi guys,
take a regular Hyperlink element, choose a file... Contao will store the real path in e.g. tl_content.url. In case of moving/renaming the file/folder, the link to the file will get broken. 
The filepicker should store the file:: inserttag here to keep the file in sync. 
If the file is not in snyc yet, add it in the save_callback.

Current state: 
![screenshot_1708](https://cloud.githubusercontent.com/assets/970730/20590562/2bc75dc8-b224-11e6-8500-f5aada2f8ec0.jpg)

Should be state:
![screenshot_1707](https://cloud.githubusercontent.com/assets/970730/20590571/38df6c3a-b224-11e6-93a4-05134cf3152c.jpg)

**Comment by fritzmg** [comment]
This is a feature that has been requested in the past in various issues. However, the discussions always strayed away and all of these issues got closed without further explanation or discussion. I have implemented this feature in [fritzmg/contao-filepicker-uuid](https://github.com/fritzmg/contao-filepicker-uuid) but this should definitely be something that should be present in the Core. It's unfortunate, that it made it never into the Core of Contao 3.

**Comment by Toflar** [comment]
> should definitely be something that should be present in the Core.

Why is there no pull request if I may ask?

**Comment by fritzmg** [comment]
I planned on making a PR for Contao 4, since it's a new feature. However, I haven't really got a clue yet how to do that there. I am guessing it should be implemented directly in `DC_Table`?

**Comment by timgatzky** [comment]
Well, I stumbled upon this today, well one of our clients did. Since I did not know if you guys already had that issue on the screen, I did not make any effort yet.

**Comment by fritzmg** [comment]
No changes to the filepicker or JavaScript are necessary. You just need to convert any file paths to a `{{file::*}}` insert tag when writing to the database and convert any `{{file::*}}` insert tags to file paths when reading from the database (for readability in the backend).

**Comment by timgatzky** [comment]
Yes, true. save_callback and load_callback should do the trick

**Comment by timgatzky** [comment]
Hi, take a look: https://github.com/timgatzky/contao-core/commit/5f539f36180c639add38fb63b18df87a5ec273d5

**Comment by fritzmg** [comment]
I would put it directly into the `DataContainer.php`. This is where it's done for the `text` element too. See [/system/modules/core/classes/DataContainer.php#L345-L348](https://github.com/contao/core/blob/3.5.19/system/modules/core/classes/DataContainer.php#L345-L348)

**Comment by leofeyer** [comment]
Changed in contao/core-bundle@3e208583e940e636fab279bd566307945d3e212c.
