### ISSUE TITLE
Fehler bei "mehrere bearbeiten"?

### ISSUE THREAD

**Issue by dazzle89** [contao/core#8580]
Contao 3.5.12

Ich weiß nicht ob es ein Fehler ist, aber ich denke mal schon.

Wenn ich mehrere Seiten bearbeiten möchte und dann auf "bearbeiten" -> "ein Seitenlayout zuweisen" klicke, fehlt die Möglichkeit, ein Seitenlayout auszuwählen. Es gibt kein Dropdown.

**Comment by fritzmg** [comment]
1. solltest du immer mit der neuesten Contao Version testen
2. Fehlt das Dropdown, weil du keines ausgewählt hast. Das Feld __Ein Layout zuweisen__ ist eine Checkbox, kein Dropdown.

**Comment by dazzle89** [comment]
Sorry, habe den Fehler gefunden.

Ich muss nicht auf "ein Layout zuweisen" klicken (da passiert quasi nichts dann), sondern auf "Seitenlayout" direkt darunter.

**Comment by fritzmg** [comment]
Du musst beides auswählen. Denn wenn die jeweiligen Seiten diese Option nicht aktiviert haben, hast du gar nichts zur Auswahl, wenn du nur das Feld __Seitenlayout__ auswählst.
