### ISSUE TITLE
Feature: Contao Manager in Install tool

### ISSUE THREAD

**Issue by jankout** [contao/core#8582]
It would be great to have the new Contao Manager in the Install tool as it was with the Composer extension. Just a button within a new section with a short description. 

After clicking on it the Contao Manager would be installed/opened

Thank you.

**Comment by leofeyer** [comment]
I think you totally got the concept of the Contao Manager wrong. Please wait for the official announcement.

**Comment by jankout** [comment]
Ok, I'm looking forward to seeing the official announcement. Can I know when it comes? Today?

**Comment by aschempp** [comment]
How come you assume it will be today?

**Comment by jankout** [comment]
It is just a wish and your plan with the realization of it was for November 2016. And today is December. That's why I hope it could come today.

**Comment by fritzmg** [comment]
> How come you assume it will be today?

According to [Informationen zum Contao Manager](https://contao.org/de/news/informationen-zum-contao-manager.html) it was planned to be released together with Contao 4.3 (which was released a few days ago), that's why people keep expecting it ;) (on the Forum as well). Is there an updated roadmap for the Contao Manager that could be communicated?

**Comment by leofeyer** [comment]
The Contao Manager consists of several different packages.

The plugin bundle has been released with Contao 4.3 and the necessary classes and configuration entries have been added to all core bundles. Together with the manager bundle, this allows you to run a "managed edition" of Contao.

Then there is a separate GUI + application, which allows you to everything you can already do with the managed edition on the command line in your browser. These parts of the Contao Manager have not yet been released but they are almost ready.

**Comment by jankout** [comment]
Ok, thank you for your answer. I hope we can use the GUI + application soon. I’m looking forward to using it. 

Best wishes, Jan
