### ISSUE TITLE
Contao 4.3 DCA (clr, w50) funktioniert bei älteren Erweiterungen nicht mehr

### ISSUE THREAD

**Issue by Xendiadyon** [contao/core#8584]
Seit dem Update von Contao 4.2.3 auf Contao 4.3 lassen sich einige Felder im Backend nicht mehr auswählen, weil die Nachbarfelder 100% Breite haben und ein ganz merkwürdiges Float-Verhalten zeigen. Sie überlagern sich gegenseitig und haben komische Umbrüche.

Es tritt insbesondere bei "älteren" Erweiterungen auf, die ich versuche auf Contao 4.3 zu portieren; namentlich dlh_googlemaps und urlcleaner.
![image](https://cloud.githubusercontent.com/assets/2657385/20837827/2376e4d0-b8a6-11e6-9de6-ac01d7344d5c.png)

Bei Contao 4.2.3 hat noch alles funktioniert; seit Contao 4.3 hat sich das float-Verhalten geändert.
Soll das so? Gibt es dafür Workarounds?

Vielen Dank.

**Comment by leofeyer** [comment]
Das liegt daran, dass im DCA dieser Erweiterungen an verschiedenen Stellen CSS-Klassen fehlen (namentlich `w50`, `long` und `clr`). Das ist bisher nicht aufgefallen, aber jetzt, das das Backend "richtig" responsive ist – also nicht nur zwischen zwei Breiten springt, sondern flexibel skaliert –, merkst man es.

**Comment by Xendiadyon** [comment]
gibt es irgendwo eine Dokumentation, wie die CSS-Klassen w50, long und clr einzusetzen sind, damit ich da reingrätschen und per dcaconfig die Klassen manuell reinbauen kann?

Vielen Dank

**Comment by asaage** [comment]
In metamodels gibts ein widget dafür. Hier ein Screenshot davon.
![image](https://cloud.githubusercontent.com/assets/4138336/20922035/0bc1b73a-bba7-11e6-9e2d-992fc0ff5397.png)

**Comment by leofeyer** [comment]
Soll das Feld die Hälfte der Breite einnehmen, bekommt es die Klasse `w50`. Soll es die ganze Breite einnehmen, bekommt es die Klasse `long`.

Die Klasse `clr` brauchst Du nur, wenn Du nach einem `w50`-Feld eine neue Zeile beginnen möchtest, obwohl eigentlich noch Platz neben dem Feld für ein weiteres `w50`-Feld wäre. In diesem Fall bekommt das Feld, das in die neue Zeile soll, die Klasse `w50 clr`.

**Comment by asaage** [comment]
https://docs.contao.org/books/manual/3.2/de/06-data-container-arrays/paletten.html#felder-ausrichten

**Comment by Aybee** [comment]
Für Felder über 2 Spalten reicht die Klasse `long` nicht aus, man muss zusätzlich die Klasse `clr` setzen. `long` kann man sich dann sparen, weil die Breite bereits mit `clr` gesetzt wird, bzw. das Setzen einer Breite überflüssig ist.

Hier die Klassen
C3 https://github.com/contao/core/blob/master/system/themes/flexible/src/basic.css#L394
C4 https://github.com/contao/core-bundle/blob/master/src/Resources/contao/themes/flexible/src/basic.css#L486
Doku: https://docs.contao.org/books/api/dca/palettes.html#arranging-fields

Die Doku müsste entsprechend angepasst werden.

Das Ticket sollte eigentlich nach core-bundle verschoben werden.
