### ISSUE TITLE
BackendUser::__destruct() : mysqli::real_escape_string(): Couldn't fetch mysqli 

### ISSUE THREAD

**Issue by fatcrobat** [contao/core#8585]
We discoverd this error within several contao 3.5 projects (tested with 3.5.19) with the following setup:

```
$GLOBALS['TL_CONFIG']['dbDriver'] = 'MySQLi';
$GLOBALS['TL_CONFIG']['dbPconnect'] = false;
```

in contao back end under `contao/main.php?do=login`.

Stacktrace:

```
Warning: mysqli::real_escape_string(): Couldn't fetch mysqli in system/modules/core/library/Contao/Database/Mysqli/Statement.php on line 51
#0 [internal function]: __error(2, 'mysqli::real_es...', '/home/rico/Kund...', 51, Array)
#1 system/modules/core/library/Contao/Database/Mysqli/Statement.php(51): mysqli->real_escape_string('a:67:{s:7:"refe...')
#2 system/modules/core/library/Contao/Database/Statement.php(350): Contao\Database\Mysqli\Statement->string_escape('a:67:{s:7:"refe...')
#3 system/modules/core/library/Contao/Database/Statement.php(325): Contao\Database\Statement->escapeParams(Array)
#4 system/modules/core/library/Contao/Database/Statement.php(262): Contao\Database\Statement->replaceWildcards(Array)
#5 system/modules/core/classes/BackendUser.php(164): Contao\Database\Statement->execute('a:67:{s:7:"refe...', '1')
#6 [internal function]: Contao\BackendUser->__destruct()
#7 {main}
```

There seems to be a sequence issue at 'BackendUser::__destruct() Line:163`

```
$this->Database->prepare("UPDATE " . $this->strTable . " SET session=? WHERE id=?")
						   ->execute(serialize($session), $this->intId);
```

Replace this please with:

```
\Database::getInstance()->prepare("UPDATE " . $this->strTable . " SET session=? WHERE id=?")
						   ->execute(serialize($session), $this->intId);
```

and the error will go away, as `this->Database` is not available any more when `Contao\Database\Mysqli\Statement:::string_escape()` will access `$this->resConnection` because **`Contao\Database::__destruct()` is triggered before `BackendUser::__destruct()`**.

The error will also go away when you set `$GLOBALS['TL_CONFIG']['dbPconnect']` to true. But dont  that is a good solution.

**Comment by discordier** [comment]
You must have some extension installed which confuses the Contao Singleton stack.

We have had reports of this problem before and always it was some extension.

The problem you are describing is a known issue and Contao demands scrutiny that the Singletons are initialized in the correct order.
If any of them are initialized out of order, the BackendUser class can not save it's session and shows above mentioned behavior.

**Comment by fatcrobat** [comment]
I understand, but if you replace `$this->Database` with `\Database::getInstance()` the error wont occur. Correct me, but is it not duty of contao/core to catch errors like this?

**Comment by aschempp** [comment]
The issue does not occur because a second database connection is established. Certainly not what you want…

**Comment by Loilo** [comment]
I got one question for clarity reasons: If an installed extension causes this error and Contao is run in safe mode then there's no way that the error should still appear, right?

**Comment by discordier** [comment]
Correct. However you can still cause this behaviour by doing creative things in `initconfig.php`, `langconfig.php`, `localconfig.php`, any template etc.

**Comment by Loilo** [comment]
Thanks, that was the deciding hint for me!
