### ISSUE TITLE
active frontend preview settings while logged in

### ISSUE THREAD

**Issue by m-vo** [contao/core#8586]
Not sure if this is a bug or intended:
- have a site with at least one unpublished element
- open FE preview and set it up to show unpublished elements
- close preview and forget about the setting you just made
- open the site reguarly (without preview frameset) but still beeing logged in (BE)
- wonder why there are unpublished elements shown but there is no way to deactivate it

I didn't investigate futher and assume it's a session-thing to work in the frameset. But shouldn't we then just always show the site in preview mode as long a user is logged into the backend or find a way to only apply the settings when the frameset is actually shown? 

Could someone shed some light onto this? Btw: Is the refactoring of the current preview-mode to a non-frameset version still a thing for the 3.5? (I guess there is/will be a symfony way to do it in 4.*?) 
Maybe I could find some time to work on it if it still makes some sense to support it.

**Comment by fritzmg** [comment]
I guess this is a known limitation since this is controlled by the session.

**Comment by bezin** [comment]
Yep, this is a know limitation I mentioned some time ago as well #8268

**Comment by leofeyer** [comment]
> Could someone shed some light onto this?

It is a known issue. Closing the frameset does not alter the session data.

> Is the refactoring of the current preview-mode to a non-frameset version still a thing for the 3.5? (I guess there is/will be a symfony way to do it in 4.*?)

Contao 3.5 is feature-complete, so the non-frameset version of the preview bar will only be available for Contao 4.

**Comment by m-vo** [comment]
Thanks for the clarification.
