### ISSUE TITLE
Laufendes wiederkehrendes Events wird in der Eventliste nicht angezeigt

### ISSUE THREAD

**Issue by snarosy75** [contao/core#8588]
Das Problem ist eine Wiederaufnahme der unter https://github.com/contao/core/issues/8497 fehlerhaften (Nicht-)-Anzeige von laufenden Events und wurde im Zuge dessen mit unter https://github.com/contao/core/commit/69a5d2586fb40df22ad3905cdc049fe243d7ab83 beschriebenen Bugfix gelöst.
Es wurde damals aber bereits angemerkt, dass dies für wiederkehrende Events nicht funktioniert, und das ist jetzt genau mein Problem:

In meinem konkreten Fall handelt sich um die Anzeige von Apotheken-Bereitschaftsdiensten, die sich alle 8 Tage wiederholen, am Abend beginnen und in der Früh enden.
Ab Mitternacht wird aber bereits jene Apotheke angezeigt, die eigentlich erst in der nächsten Nacht Dienst hat.

Problem ist wie anfangs geschrieben, dass es sich um ein wiederkehrendes Event handelt. Testweise sls nicht wiederholendes Event eingetragen, funktioniert die Anzeige korrekt. Das würde in meinem Fall aber bedeuten, dass ich 365 Veranstaltungen statt 8 eintragen muss.

**Comment by fritzmg** [comment]
Wie bereits im Forum beschrieben solltest du genaue Reproduktions Schritte für http://demo.contao.org/ posten.

**Comment by snarosy75** [comment]
habe ich eben erledigt: https://community.contao.org/de/showthread.php?64303-Eventliste-blendet-laufende-Events-aus&p=426442#post426442
Ich hoffe, mein Problem lässt sich somit verdeutlichen.

**Comment by Physiklehrer** [comment]
Zur Problematik in system/modules/calendar/modules/ModuleEventlist.php, Zeile 175:
```
// Skip occurrences in the past but show running events (see #8497)
if ($event['repeatEnd'] && strtotime($event['datetime']) < $intStart)
```
Beispiel: Event mit täglicher Wiederholung vom 1.12. bis 10.12., heute ist der 7.12.
Zunächst wird ja nach (absolutem) Start- und Enddatum des Events gefiltert (also alles vor 1.12. und nach 10.12.) fliegt raus. Bei Wiederholungsevents sind dann aber natürlich die Events vom 1.12. bis heute (7.12.) immer noch drin, was ja nicht sein darf. Diese werden mit Zeile 175 nachträglich ausgeblendet.

Die Lösung wäre es, auch bei dieser nachträglichen Filterung auf das Enddatum des aktuellen Wiederholungsevents zu prüfen. Statt "strtotime($event['datetime'])" müsste also etwas in der Art "strtotime($event['ENDtime'])" stehen, allerdings eben nicht das globale Enddatum des Events (10.12.), sondern das der jeweils betrachteten Wiederholung. Wenn eine solche Variable nicht zur Verfügung steht, müsste sie aber noch generiert werden.

**Comment by leofeyer** [comment]
> Statt "strtotime($event['datetime'])" müsste also etwas in der Art "strtotime($event['ENDtime'])" stehen, allerdings eben nicht das globale Enddatum des Events (10.12.), sondern das der jeweils betrachteten Wiederholung

Dieser Zeitstempel sollte eigentlich in `$event['end']` stehen. @Physiklehrer Könntest Du bitte mal die Zeile 175 wie folgt ändern und sehen, ob das Problem dadurch behoben wird?

```php
if ($event['repeatEnd'] && $event['end'] < $intStart)
```

In dem speziellen Testfall wurde das wiederholte Event bei mir nach der Änderung korrekt angezeigt.

**Comment by Physiklehrer** [comment]
getestet, funktioniert bestens, Problem behoben! Vielen Dank!

Unerwünschte Nebenwirkungen konnte ich keine feststellen.

**Comment by leofeyer** [comment]
Super, Danke Dir. Behoben in 53e9b22e38fdea172963e7f18ee2011cbd4f5d89.

**Comment by snarosy75** [comment]
Danke für eure hilfe!
