### ISSUE TITLE
Widget-Validate-Error results in saving the whole record nevertheless

### ISSUE THREAD

**Issue by Defcon0** [contao/core#8591]
Hello,

situation is as follows:

I have a form in the backend (e.g. tl_news) and there are several fields. Some of them are required, some not. At first I type in something in all fields and save -> everything OK.

Now I change some optional field to a new value. In a required field situated *after* the one mentioned before, I remove the value completely which results in the field's validation to return an error for that field.

Now I would've expected contao that the whole record is only stored if *all* fields are validated correctly. But this isn't the case. The first (optional) field indeed is saved to db.

In some cases this handling will result in inconsistent records. I don't believe it's a bug since someone sure would have noticed that years ago before me.

So why is contao doing this strange behavior?

Bye

**Comment by discordier** [comment]
This is a well known issue which can not be changed simply unless moving away from DC_Table.
