### ISSUE TITLE
srcset läuft Amok bei zu kleinen Bildern

### ISSUE THREAD

**Issue by Xendiadyon** [contao/core#8592]
Wenn wir mehrere Bildgrößen definieren, das Zielbild aber zu klein ist (oder vom Format nicht passt?), wird im picture - srcset Unfug generiert:
![image](https://cloud.githubusercontent.com/assets/2657385/21101182/3add95fe-c078-11e6-99b7-3c776beaf94e.png)

```
<picture>
    <!--[if IE 9]><video style="display: none;"><![endif]-->
          <source srcset="assets/images/c/2bebbc0257-e337f049.png" media="(max-width:600px)">
        <!--[if IE 9]></video><![endif]-->

<img src="assets/images/5/2bebbc0257-9d94837c.png" srcset="assets/images/5/2bebbc0257-9d94837c.png 1x, assets/images/2/2bebbc0257-446f8972.png 1,352x" alt="" itemprop="image">

  </picture>
```

hier beim 1,352x; (es liegt wohl am Komma) das wird von Chrome so interpretiert:
![image](https://cloud.githubusercontent.com/assets/2657385/21101050/9719ec88-c077-11e6-8a4c-c32c7d1f90fa.png)
Das Bild ist 700x300 Pixel groß, sollte aber 335x222 bzw ein Vielfaches davon sein.

Evtl. reicht es einfach, aus dem Komma ein Punkt zu machen?

**Comment by discordier** [comment]
Wo kommt denn das Komma her? Das habt ihr doch in der size selbst hinterlegt?

**Comment by Xendiadyon** [comment]
Nope. In meinen Augen wird das irgendwie in einen nichtganzzahligen Wert umgerechnet.

Wir haben die Retina-Auflösungen als Ganzzahlen definiert:
![image](https://cloud.githubusercontent.com/assets/2657385/21187350/e314d6e2-c217-11e6-84b5-0f9c991ed41c.png)

**Comment by Xendiadyon** [comment]
ich habe leider keine Ahnung, wo und wieso von image/Picture.php die Kommazahlen entstehen. Vielleicht weiß @ausi mehr, wo man da reingucken könnte?

**Comment by ausi** [comment]
@Xendiadyon Contao-Version?

**Comment by fritzmg** [comment]
Liegt evt. an der PHP `round` function, die hier in Verwendung ist: https://github.com/contao/core/blob/3.5.19/system/modules/core/library/Contao/Picture.php#L267

> Please note that the format of this functions output also depends on your locale settings. For example, if you have set your locale to some country that uses commas to separate decimal places, the output of this function also uses commas instead of dots.


http://php.net/manual/en/function.round.php#80375

**Comment by ausi** [comment]
Das Problem ist vermutlich die number to string conversion. Ist auf dem Server der [locale](http://php.net/manual/en/function.setlocale.php) für `LC_NUMERIC` auf `de` gesetzt?

**Comment by leofeyer** [comment]
@ausi Das sollten wir irgendwie abfangen, denn `de` ist ja keine unübliche Locale auf Servern im deutschsprachigen Raum.

**Comment by ausi** [comment]
@leofeyer Ja, `number_format()` ist wahrscheinlich die Lösung. Ich fixe das in contao/image und mach einen PR für Contao 3.5.

**Comment by leofeyer** [comment]
Danke.

**Comment by ausi** [comment]
Pull request: #8602

**Comment by ausi** [comment]
@Xendiadyon hast du in der Installation selbst den locale per `setlocale()` gesetzt?
Falls ja, für `LC_ALL`?
Und aus welchem Grund?

**Comment by leofeyer** [comment]
Closed in favor of #8602.

**Comment by Xendiadyon** [comment]
@ausi wir wollten dass die Umlaute beim Generieren des Seitenalias korrekt verwendet werden. ä -> ae usw. Ohne setlocale hätten wir ä -> a gehabt.

**Comment by Toflar** [comment]
@Xendiadyon das wäre sowieso ein sinnvolles Feature, müsste aber eigentlich im save_callback gesetzt und wieder zurückgesetzt werden, um nachfolgende Calls nicht zu beeinflussen. Irgendwo gab es eine Diskussion dazu. Findet da jemand das Ticket, damit wir das nochmal aufnehmen können?

**Comment by fritzmg** [comment]
@Toflar I think you mean https://github.com/contao/core-bundle/issues/560 » https://github.com/contao/core-bundle/pull/569

**Comment by Xendiadyon** [comment]
Ich habe es mit setlocale (LC_CTYPE, 'de_DE'); geschafft, nur die Alias-Umlautgenerierung zu beheben ohne dass LC_NUMERIC angefasst wird.

Vielen Dank für eure Inputs und die Infos.
