### ISSUE TITLE
XSS vulnerability due to missing character encoding

### ISSUE THREAD

**Issue by pgerundt** [contao/core#8594]
(I'm sorry, this is my first issue report.)

There is a XSS vulnerability in the method `validate()` of the following classes (Contao 3.5.19 LTS):

[Details sent to security@lists.c-c-a.org]

**Comment by discordier** [comment]
Please use the security mailing list security@contao.org with your findings and edit this issue to remove the details of the attack.

**Comment by ausi** [comment]
Thank you @pgerundt for reporting the issue!
We will take a look at it ASAP.

**Comment by leofeyer** [comment]
Fixed in dae2116b4c92a38d44a40993dac3e7c172bc740b. Thanks again @pgerundt for finding and reporting the issue.

**Comment by aschempp** [comment]
This has been qualified as a security fix. @pgerundt please contact association@contao.org to obtain your security bounty.
