### ISSUE TITLE
Systemwartung  > Bildercache leeren: unter Windows wird .empty mit gezählt

### ISSUE THREAD

**Issue by zonky2** [contao/core#8595]
Systemwartung  > Bildercache leeren: unter Windows wird .empty mit gezählt - daher steht hier auch nach dem Leeren "assets/images: 1 Datei(en)"

... nicht so dramatisch, aber kann für Verwirrung sorgen, da man die eine (Bild)Datei nicht "findet"...

Edit:
![shot308](https://cloud.githubusercontent.com/assets/1045318/21212998/ea9864f4-c291-11e6-805f-a83fd3551c50.jpg)

**Comment by leofeyer** [comment]
Was ist denn `.empty`?

**Comment by zonky2** [comment]
na, ich würde mal sagen die "fake datei" für git, um auch leere Order mit zu nehmen...

**Comment by fritzmg** [comment]
Warum sind dort überhaupt `.empty` Dateien drin? By default sind ja in jedem der Unterordner `index.html` Dateien.

**Comment by leofeyer** [comment]
Nein, wir verwenden nirgendwo `.empty`-Dateien. Sonst wären die entsprechend berücksichtigt.

**Comment by discordier** [comment]
Sehe ich auch zum ersten Mal?

**Comment by zonky2** [comment]
komisch - habe einige Installationen, die ich über den Contao-Check installiert habe... da kommen die Daten ja direkt von Github => ggf. hat der was als "give away" parat gehabt...

**Comment by leofeyer** [comment]
Kann das sonst jemand unter Windows reproduzieren?

**Comment by aschempp** [comment]
Vielleicht sollten wir unsichtbare Dateien generell ignorieren beim zählen?

**Comment by leofeyer** [comment]
Das denke ich nicht, denn z.B. eine `.htaccess` möchte ich schon gezählt haben.

**Comment by aschempp** [comment]
Im `assets/images` Verzeichnis? Für den Backend-Benutzer können die unsichtbaren Dateien niemals relevant sein, es geht ja darum wieviele Bilder in dem Ordner sind…

**Comment by zonky2** [comment]
sehe ich wie @aschempp - im BE geht es um die Anzahl der Bilder und nicht um die Anzahl aller möglichen Dateien...
