### ISSUE TITLE
"Front end modules" enabling/disabling in "Page layouts" not working

### ISSUE THREAD

**Issue by tsarma** [contao/core#8596]
Per ajax enabling/disabling of front end module in Page layout using eye-icon is not working any more. Test on Contao 3.5.18 on online demo.contao.org

**Comment by m-vo** [comment]
Maybe your connection had an issue - did you try it again?
(It works for me.)

**Comment by leofeyer** [comment]
Works for me, too. Just tested it in the online demo.

**Comment by tsarma** [comment]
I hope this is a local problem to me. But I have tested again from 2 computers, Chrome, Safari and Firefox none worked. 
In generally eye-icon works for publishing pages and articles. Any idea?

**Comment by aschempp** [comment]
Maybe you're using an Ad blocker?

**Comment by m-vo** [comment]
Maybe try opening your browsers dev tools (F12) and look at the network tab to trace down your problem.

**Comment by tsarma** [comment]
No, not what I know of. I have tested from my mobile phone on mobile network. Still same- not working. 
@m-vo : There is not network activity at all, when I press the eye-icon from page layout section

**Comment by Toflar** [comment]
JavaScript error in console? Maybe a browser extension?

**Comment by tsarma** [comment]
By the way, I think the eye-icon in the page layout section is not the same as page/article publish eye-icon.  
page/article publish eye-icon is triggered with ajax, but the page layout is not. May be that has confused me.

**Comment by tsarma** [comment]
In the page layout section one has the press the save button, after toggling the eye-icon. The eye-icon does not work with ajax like other eye-icon in the system.

**Comment by Aybee** [comment]
Yes. Within site structure page listing you are not in a form which can be saved so there it gets saved immediately via ajax. Within page layout you are in a form and the eye is just a setting which you have to save.

So it was a missunderstanding and this ticket **can be closed**.
