### ISSUE TITLE
C3.5.19 Suchindex neu aufbauen

### ISSUE THREAD

**Issue by pgerundt** [contao/core#8599]
Wird Contao z. B. für zwei Domains http://www.a.com und http://www.b.com benutzt, so wird der Suchindex für alle Seiten http://www.a.com/* nur aufgebaut, wenn man im Backend über http://www.a.com/contao angemeldet ist.
Für alle Seiten von http://www.b.com/* bekommt der XMLHttpRequest als Status 0 zurück (wegen blockierter Cross-Origin-Anfrage).

Kann das jemand bestätigen?

**Comment by fritzmg** [comment]
#8597

**Comment by pgerundt** [comment]
Danke!
Weiterer Hinweis: Der "alte" Code C3.1.? der be_rebuild_index.html5 funktioniert:

```
window.addEvent('domready', function() {
    var urls = $$('.page_url'), 
    last = urls.length-1, url;
    urls.each(function(el, i) {
        el.getAttribute('data-url') && new Request({
            'url': el.getAttribute('data-url'),
            onComplete: function() {
                el.addClass('tl_green');
                if (i == last) {
                    $('index_loading').setStyle('display', 'none');
                    $('index_complete').setStyle('display', 'block');
                }
            }
        }).get();
    });
});
```

Der "neue" Code (C3.5.19) nicht:
```
window.addEvent('domready', function() {
    var queue = new Request.Queue({
        onEnd: function() {
            $('index_loading').setStyle('display', 'none');
            $('index_complete').setStyle('display', 'block');
        },
        concurrent: 1,
        stopOnFailure: false
    });
    $$('.page_url').each(function(el, i) {
        el.getAttribute('data-url') && queue.addRequest(i, new Request({
            onSuccess: function() {
                el.addClass('tl_green');
            },
            onFailure: function(xhr) {
                el.addClass('tl_red');
                el.set('text', '[' + xhr.status + '] ' + el.get('text'));
            },
            url: el.getAttribute('data-url')
        }));
    });
    Object.values(queue.requests).invoke('get');
});

```

**Comment by fritzmg** [comment]
> Weiterer Hinweis: Der "alte" Code C3.1.? der be_rebuild_index.html5 funktioniert:

Wie hast du das getestet? Hast du auch tatsächlich die Requests analysiert und bestätigt, dass der Request erfolgreich war und die Frontend Seite als Response bekommt?

**Comment by pgerundt** [comment]
Danke! Mein Fehler. Der "alte" Code kannte nur "onComplete", der neue unterscheidet zwischen "onSuccess" und "onFailure". Der CORS-Fehler tritt natürlich bei beiden Varianten auf.

Sorry, ich klick mal auf "close".
