### ISSUE TITLE
{{env::files_url}} & {{env::assets_url}} keine Funktion

### ISSUE THREAD

**Issue by NicolasGoerlach** [contao/core#8600]
Die Inserttags {{env::files_url}} & {{env::assets_url}} funktionieren leider nicht unter der aktuellen LTS Version (3.5.19).

**Comment by fritzmg** [comment]
Funktionieren in der Contao Demo einwandfrei.

**Comment by NicolasGoerlach** [comment]
Dann verstehe ich die Tags wohl nicht richtig, wenn ich in der Demo ein HTML-Element anlege und dort das Inserttag {{env::files_url}} eingebe müsste er mir doch http://demo.contao.org/files ausgeben, oder nicht?

**Comment by fritzmg** [comment]
Nein, der Insert Tag gibt die im Website Root eingetragene File URL aus.

**Comment by NicolasGoerlach** [comment]
Ah alles klar, sollte vllt in der Doku ergänzt werden, alle anderen env-Tags funktionieren ohne Zusatz.

**Comment by fritzmg** [comment]
Was meinst du mit Zusatz?

**Comment by BugBuster1701** [comment]
Das Verständnis Problem taucht öfters auf. 
https://community.contao.org/de/showthread.php?34361-Ist-env-files_url-depricated&p=251890&viewfull=1#post251890
