### ISSUE TITLE
DatePicker Field im Backend -> submitOnChange funktioniert nicht

### ISSUE THREAD

**Issue by theDyingMountain** [contao/core#8603]
Bei Auswahl eines Datums aus dem Datepicker Popup greift das `onChange `Event nicht. Dazu müsste bei der Initialisierung des Datepickers im DataContainer die Option `onSelect` gesetzt werden.

Wenn das Datum per Tastatur in das Feld eingetippt wird, wird das change Event regulär wie erwartet aufgerufen.

**Comment by leofeyer** [comment]
Wie lässt sich das reproduzieren?

**Comment by aschempp** [comment]
hört sich nach einem Bug im Datepicker-Plugin an.

**Comment by theDyingMountain** [comment]
Zur Reproduzierung:
Ein Field mit Inputype Text anlegen und in der Evaluation submitOnChange = true setzen sowie datepicker = true setzen. Hier ein Beispiel:
`        'date' => array(
            'inputType' => 'text',
            'eval' => array(
                'rgxp' => 'date',
                'tl_class' => 'wizard w50',
                'submitOnChange' => true,
                'datepicker => true
            ),
            'sql' => "varchar(10) NOT NULL default ''"
        ),`

Es ist kein Bug im Datepicker sondern eher eine fehlende Configuration, wie bereits erwähnt wird der onSelect Callback nicht gesetzt beim Initialiseren im DataContainer Zeile 390 - 401.

**Comment by leofeyer** [comment]
Fixed in 6cf429d4ba369a2c62bd862c3cb877834109ad1d.
