### ISSUE TITLE
[V3.5] compatibility PHP7.1

### ISSUE THREAD

**Issue by mathContao** [contao/core#8606]
Issue: PHP7.1 with Contao 3.5

from forum:
https://community.contao.org/de/showthread.php?65088-Contao-3-5-x-mit-PHP-7-1&p=427805&viewfull=1#post427805

> Warning: A non-numeric value encountered in system/modules/core/library/Contao/Picture.php on line 241
> 
> #0 system/modules/core/library/Contao/Picture.php(241): __error(2, 'A non-numeric v...', '/homepages/27/d...', 241, Array)
> #1 system/modules/core/library/Contao/Picture.php(198): Contao\Picture->getTemplateDataSource(Object(stdClass))
> #2 system/modules/core/library/Contao/Controller.php(1535): Contao\Picture->getTemplateData()
> #3 system/modules/core/elements/ContentImage.php(69): Contao\Controller::addImageToTemplate(Object(Contao\FrontendTemplate), Array)
> #4 system/modules/core/elements/ContentElement.php(265): Contao\ContentImage->compile()
> #5 system/modules/core/elements/ContentImage.php(60): Contao\ContentElement->generate()
> #6 system/modules/core/library/Contao/Controller.php(484): Contao\ContentImage->generate()
> #7 system/modules/core/modules/ModuleArticle.php(213): Contao\Controller::getContentElement(Object(Contao\ContentModel), 'right')
> #8 system/modules/core/modules/Module.php(287): Contao\ModuleArticle->compile()
> #9 system/modules/core/modules/ModuleArticle.php(67): Contao\Module->generate()
> #10 system/modules/core/library/Contao/Controller.php(417): Contao\ModuleArticle->generate(false)
> #11 system/modules/core/library/Contao/Controller.php(277): Contao\Controller::getArticle(Object(Contao\ArticleModel), false, false, 'right')
> #12 system/modules/core/pages/PageRegular.php(133): Contao\Controller::getFrontendModule('0', 'right')
> #13 system/modules/core/controllers/FrontendIndex.php(285): Contao\PageRegular->generate(Object(Contao\PageModel), true)
> #14 index.php(20): Contao\FrontendIndex->run()
> #15 {main}
> 
> 
> Warning: A non-numeric value encountered in system/modules/core/library/Contao/Picture.php on line 242
> 
> #0 system/modules/core/library/Contao/Picture.php(242): __error(2, 'A non-numeric v...', '/homepages/27/d...', 242, Array)
> #1 system/modules/core/library/Contao/Picture.php(198): Contao\Picture->getTemplateDataSource(Object(stdClass))
> #2 system/modules/core/library/Contao/Controller.php(1535): Contao\Picture->getTemplateData()
> #3 system/modules/core/elements/ContentImage.php(69): Contao\Controller::addImageToTemplate(Object(Contao\FrontendTemplate), Array)
> #4 system/modules/core/elements/ContentElement.php(265): Contao\ContentImage->compile()
> #5 system/modules/core/elements/ContentImage.php(60): Contao\ContentElement->generate()
> #6 system/modules/core/library/Contao/Controller.php(484): Contao\ContentImage->generate()
> #7 system/modules/core/modules/ModuleArticle.php(213): Contao\Controller::getContentElement(Object(Contao\ContentModel), 'right')
> #8 system/modules/core/modules/Module.php(287): Contao\ModuleArticle->compile()
> #9 system/modules/core/modules/ModuleArticle.php(67): Contao\Module->generate()
> #10 system/modules/core/library/Contao/Controller.php(417): Contao\ModuleArticle->generate(false)
> #11 system/modules/core/library/Contao/Controller.php(277): Contao\Controller::getArticle(Object(Contao\ArticleModel), false, false, 'right')
> #12 system/modules/core/pages/PageRegular.php(133): Contao\Controller::getFrontendModule('0', 'right')
> #13 system/modules/core/controllers/FrontendIndex.php(285): Contao\PageRegular->generate(Object(Contao\PageModel), true)
> #14 index.php(20): Contao\FrontendIndex->run()
> #15 {main}

**Comment by mathContao** [comment]
wurde in Contao 3.5.20 gefixed

https://community.contao.org/de/showthread.php?65088-Contao-3-5-x-mit-PHP-7-1&p=427811&viewfull=1#post427811

**Comment by Funbug** [comment]
Ich habe den Fehler leider immer noch in einer 3.5.27:
`Warning: A non-numeric value encountered in system/modules/core/elements/ContentGallery.php on line 304`

Das (int) löst das Problem:
`$intMaxWidth = (TL_MODE == 'BE') ? floor((640 / $this->perRow)) : floor(((int)\Config::get('maxImageWidth') / $this->perRow));`
