### ISSUE TITLE
templates/mod_booknav.html5: spitze Klammern/ brackets

### ISSUE THREAD

**Issue by mathContao** [contao/core#8607]
templates/mod_booknav.html5

Für die Buch-Navigation nach links/rechts werden im Template spitze Klammern < und > verwendet.
Aus meiner Sicht ist das syntaktisch nicht passend, da diese Pfeile besser per CSS oder Grafik eingefügt werden sollten. Und schick sehen die Klammern auch nicht aus. Ich entferne jedes Mal im Template diese Pfeile.
Daher möchte ich gerne eine Diskussion anregen, ob zukünftig in diesem Template diese Pfeile/spitze Klammern entfallen könnten.

I think the brackets ( < and > ) does not make sense (syntactic) and does not look good. I remove it all times in template and insert a Icon/Image by CSS.
Up for discussion to remove it.

![grafik](https://cloud.githubusercontent.com/assets/1645099/21496623/280f819a-cc20-11e6-89f6-1022f9ebc930.png)

**Comment by frontendschlampe** [comment]
yes ... I think, that would be great. Next and previous should be better!

**Comment by mathContao** [comment]
$this->prevLink and $this->nextLink inserts the title of linked page.

example (now):

- < page1
- up
- page3 >

I recommend:
- page1
- up
- page3

**Comment by asaage** [comment]
I'd prefer pagetitles of previous and next page with ```rel="next/previous"``` attributes or meta-tags added to the head. 
But i am not so shure if that behaves well with paginated content (news- /eventslists)

**Comment by leofeyer** [comment]
Removed in contao/core-bundle@d7239fa8b23805554c52b7f857cfab38fdbb09f3.
