### ISSUE TITLE
Register model before `postSave()`

### ISSUE THREAD

**Issue by richardhj** [contao/core#8608]
Please have a look at https://github.com/contao/core/blob/3.5.21/system/modules/core/library/Contao/Model.php#L516

Is there a reason, you register the model `postSave()`? Wouldn't it be better to call the `postSave()` after the model was registered - even semantically?
Unfortunately, this behavior leads to errors in my environment.
## Details:
I use the postSave to trigger an event
```php
class Attendance extends Model
{
/**
     * Trigger the SaveAttendanceEvent
     *
     * @param int $intType
     */
    protected function postSave($intType)
    {
        global $container;

        parent::postSave($intType);

        /** @var EventDispatcher $dispatcher */
        $dispatcher = $container['event-dispatcher'];
        $dispatcher->dispatch(SaveAttendanceEvent::NAME, new SaveAttendanceEvent($this, $this->cloneOriginal()));
    }
}
``` 
A listener, which performs a `save()` on the model - which is not registered yet - leads into following error: 
```
Query error: Duplicate entry '9' for key 'PRIMARY' (INSERT INTO tl_mymodule (id, tstamp, offer, participant, status, sorting, created) VALUES ('9', '1483138351', '1', '1', '1', '0', '1483138351'))
```

**Comment by leofeyer** [comment]
@contao/developers I think @richardhj is right. Do you agree?

**Comment by ausi** [comment]
I’m not sure. What if someone relies on the fact that `postSave()` is called before the model is registered?

Should calling `save()` inside the `postSave()` method be a supported use case? If it would work, wouldn’t that create an endless loop anyway, because `save()` would call `postSave()` again?

**Comment by richardhj** [comment]
> Should calling save() inside the postSave() method be a supported use case? If it would work, wouldn’t that create an endless loop anyway, because save() would call postSave() again?

Good point @ausi. True, it would lead in an endless recursion as I just tested. But the developer has to take care about it and it would not make a difference to trigger the event in the `postSave()` or `save()`.
IMHO, the decision to register the event before or after the `postSave()` does not have to do with the point whether it is a supported use case.

> I’m not sure. What if someone relies on the fact that postSave() is called before the model is registered?

It has to be dicussed whether this should be handled as a bugfix or not.
For me, `postSave` means *after save* - and the model registration is a part of the save process.

**Comment by aschempp** [comment]
There is a general issue that we assume a model is only in the database when it is in the registry everywhere. Not being able to call `save()` on a model in `postSave()` certainly is an issue though.

I'm not sure if we can change the current behavior. But as a developer, you can easily work around this by manually registering the model in the registry. The second call will simply be ignored.

**Comment by Toflar** [comment]
I think the way it is now is correct. 

You cannot call `save()` in the `postSave()` "event" because it would cause a recursive loop and this is correct and not a bug.

To be honest, I don't see any valid use case for `postSave()` anyway. If you want to modify the data before it is stored, you clearly have to use `preSave()`, change the array that's returned and everything else will be taken care of by Contao.

**Comment by discordier** [comment]
A valid usecase for `postSave` is to update referenced models after a model has been persisted. However I agree that saving the very same model again in `postSave` is not supported nor should it (for recursions sake and lack of usecase).
