### ISSUE TITLE
Symlinks im Downlodverzeichnis 3.5.20 tar.gz /vendor/bin

### ISSUE THREAD

**Issue by vgt1920** [contao/core#8609]
Beim manuellen Update mittels SSH-Zugang habe ich bemerkt, dass im Downloadarchiv der tar.gz (per curl geholt) im Verzeichnis /vendor/bin seit der Version 3.5.20 vier Symlinks @lessc, @minifycss, @minifyjs und @pscss enthalten sind. Sind die "lebensnotwendig" für Contao?
siehe auch: https://community.contao.org/de/showthread.php?65141-Symlinks-im-Downlodverzeichnis-3-5-20-tar-gz-vendor-bin

**Comment by leofeyer** [comment]
Allgemeine Fragen => Forum
Fehler melden => Ticket-System
