### ISSUE TITLE
Aliase werden beim Kopieren von Events/Nachrichten falsch generiert 

### ISSUE THREAD

**Issue by Samson1964** [contao/core#8610]
Bei Artikeln und Seiten werden beim Kopieren keine Aliase für die neuen Datensätze generiert. Bei kopieren Nachrichten und Events wird allerdings ein Alias generiert. Dabei wird das Alias des kopierten Datensatzes genommen und eine kryptische Zeichenfolge angehangen. Siehe dazu auch das [Forum](https://community.contao.org/de/showthread.php?65110-Seltsame-Aliase-bei-Events-Nachrichten-bei-Mehrere-bearbeiten-Kopieren).
In der Onlinedemo läßt sich das wie folgt nachvollziehen:

1. News -> Contao Official Demo News -> Edit Archive
2. Alle Nachrichten markieren -> Copy (oder nur 1 Nachricht kopieren mittels Edit multiple)
3. Der Alias einer kopierten Nachricht ist nun nicht wie erwartet leer, sondern dort steht z.B.: new-contao-versions-in-short-intervalls-c94a2fed 

Kopiert man die kopierten Nachrichten erneut, steht im Alias z.B.: new-contao-versions-in-short-intervalls-c94a2fed-ab01ac07 

Das direkte Kopieren über das grüne Plus funktioniert einwandfrei. Es wird kein Alias eingetragen.

Analog dazu funktionieren die Events auch nicht.

**Comment by aschempp** [comment]
Was wäre aus deiner Sicht denn richtig?

**Comment by Samson1964** [comment]
So wie bei Artikeln und Seiten (Edit multiple -> Copy) und beim normalen Kopieren von Events/Nachrichten - also kein Alias automatisch anzulegen. Den Fehler gab es auch in der kürzlich abgeschalteten 3.5er Demo.

**Comment by leofeyer** [comment]
Wir am 7. September auf Mumble besprochen, sollten wir das `doNotCopy`-Flag bei allen Alias-Feldern hinzufügen.

**Comment by leofeyer** [comment]
Geändert in 1d8f2b62ccde714de967583fcac426a56811388a.
