### ISSUE TITLE
cURL unable to establish a secure connection to contao.org

### ISSUE THREAD

**Issue by fritzmg** [contao/core#8614]
There are more and more reports in the community forum about users not being able to use the Live-Update or Extension Repository anymore (or in a fresh install) due to the following OpenSSL error:
```
SSL operation failed with code 1. OpenSSL Error messages: error:14077438:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert internal error
```
As far as I researched, the error only happens in certain combinations of OpenSSL and cURL versions - also depending on the used Linux distribution for example. One post suggests the following:

> The issue is actually with certain SSLv3 servers that don't understand the TLSv1.1 handshake and are closing the connection. This unfortunately can't be fixed on the client without disabling TLSv1.1, or forcing an SSLv3 connection.

I am sure this is otherwise simply caused by an improperly configured server environment - but is there anything that can be done on the server side of contao.org - or is there any specific advice that can be relayed to hosters so that it can be fixed? (Many hosters are often reluctant to admit failure...)

**Comment by leofeyer** [comment]
Our servers "understand" TLSv1.1, so this might not be the problem.

**Comment by leofeyer** [comment]
Both the Live Update and the ER2 are not using cURL but our own `Request` class, so here is what we could try:

```php
// Request.php line 284
$fp = @fsockopen('sslv3://' . $uri['host'], $port, $errno, $errstr, 15);
```

(I have changed `ssl://` to `sslv3://` here.) Can you test this and provide feedback please?

**Comment by fritzmg** [comment]
I don't have a reproduction at hand myself, however I'll relay that change to the forum and report back here.

**Comment by freiwild** [comment]
ER and Live-Update are not working. Got serveral error messages with the Contao check. See: [https://community.contao.org/de/showthread.php?54200-LU-funktioniert-nicht-mehr-mit-PHP-5-6&p=429103&viewfull=1#post429103](url)
Changed the line 284 in system/modules/core/library/Contao/Request.php as mentioned above.
Still same errors.
![grafik](https://cloud.githubusercontent.com/assets/3893317/21806983/b77fe8ac-d73c-11e6-8597-a6cdd57f7594.png)

**Comment by leofeyer** [comment]
The Contao check uses cURL and is thus not suited to test the `Request` class changes.

**Comment by fritzmg** [comment]
You could test the changes in the Contao Check as well though. Simply replace any occurences of `ssl://` with `sslv3://`.

**Comment by leofeyer** [comment]
Oh yes, you are right! There is an `fsockopen()` call in the check, too:

https://github.com/contao/check/blob/master/check/controller/installer.php#L106

**Comment by fritzmg** [comment]
Full error messages:
```
[10-Jan-2017 13:04:37 GMT] 
PHP Warning: SoapClient::SoapClient(): SSL operation failed with code 1. OpenSSL Error messages:
error:14077438:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert internal error in …/system/modules/repository/classes/RepositoryBackendModule.php on line 131
#0 [internal function]: __error(2, 'SoapClient::Soa...', '…...', 131, Array)
#1 …/system/modules/repository/classes/RepositoryBackendModule.php(131): SoapClient->SoapClient('https://contao....', Array)
#2 …/system/modules/core/classes/BackendModule.php(98): RepositoryBackendModule->compile()
#3 …/system/modules/repository/classes/RepositoryBackendModule.php(72): Contao\BackendModule->generate()
#4 …/system/modules/repository/classes/RepositoryManager.php(57): RepositoryBackendModule->generate()
#5 …/system/modules/core/classes/Backend.php(423): RepositoryManager->generate()
#6 …/system/modules/core/controllers/BackendMain.php(131): Contao\Backend->getBackendModule('repository_mana...')
#7 …/contao/main.php(20): Contao\BackendMain->run()
#8 {main}

[10-Jan-2017 13:04:37 GMT] 
PHP Warning: SoapClient::SoapClient(): Failed to enable crypto in …/system/modules/repository/classes/RepositoryBackendModule.php on line 131
#0 [internal function]: __error(2, 'SoapClient::Soa...', '…...', 131, Array)
#1 …/system/modules/repository/classes/RepositoryBackendModule.php(131): SoapClient->SoapClient('https://contao....', Array)
#2 …/system/modules/core/classes/BackendModule.php(98): RepositoryBackendModule->compile()
#3 …/system/modules/repository/classes/RepositoryBackendModule.php(72): Contao\BackendModule->generate()
#4 …/system/modules/repository/classes/RepositoryManager.php(57): RepositoryBackendModule->generate()
#5 …/system/modules/core/classes/Backend.php(423): RepositoryManager->generate()
#6 …/system/modules/core/controllers/BackendMain.php(131): Contao\Backend->getBackendModule('repository_mana...')
#7 …/contao/main.php(20): Contao\BackendMain->run()
#8 {main}

[10-Jan-2017 13:04:37 GMT] 
PHP Warning: SoapClient::SoapClient(https://contao.org/services/repository.wsdl): failed to open stream: operation failed in …/system/modules/repository/classes/RepositoryBackendModule.php on line 131
#0 [internal function]: __error(2, 'SoapClient::Soa...', '…...', 131, Array)
#1 …/system/modules/repository/classes/RepositoryBackendModule.php(131): SoapClient->SoapClient('https://contao....', Array)
#2 …/system/modules/core/classes/BackendModule.php(98): RepositoryBackendModule->compile()
#3 …/system/modules/repository/classes/RepositoryBackendModule.php(72): Contao\BackendModule->generate()
#4 …/system/modules/repository/classes/RepositoryManager.php(57): RepositoryBackendModule->generate()
#5 …/system/modules/core/classes/Backend.php(423): RepositoryManager->generate()
#6 …/system/modules/core/controllers/BackendMain.php(131): Contao\Backend->getBackendModule('repository_mana...')
#7 …/contao/main.php(20): Contao\BackendMain->run()
#8 {main}

[10-Jan-2017 13:04:37 GMT] 
PHP Warning: SoapClient::SoapClient(): I/O warning : failed to load external entity https://contao.org/services/repository.wsdl in …/system/modules/repository/classes/RepositoryBackendModule.php on line 131
#0 [internal function]: __error(2, 'SoapClient::Soa...', '…...', 131, Array)
#1 …/system/modules/repository/classes/RepositoryBackendModule.php(131): SoapClient->SoapClient('https://contao....', Array)
#2 …/system/modules/core/classes/BackendModule.php(98): RepositoryBackendModule->compile()
#3 …/system/modules/repository/classes/RepositoryBackendModule.php(72): Contao\BackendModule->generate()
#4 …/system/modules/repository/classes/RepositoryManager.php(57): RepositoryBackendModule->generate()
#5 …/system/modules/core/classes/Backend.php(423): RepositoryManager->generate()
#6 …/system/modules/core/controllers/BackendMain.php(131): Contao\Backend->getBackendModule('repository_mana...')
#7 …/contao/main.php(20): Contao\BackendMain->run()
#8 {main}
```
@leofeyer regarding SOAP: the ciphers mentioned here https://github.com/contao/check/issues/109#issuecomment-261294899 could be added as a context. See http://stackoverflow.com/a/23130512/374996 for example. Not sure if that's the right thing to do.

**Comment by freiwild** [comment]
So change the 106 line to: `$connection = @fsockopen('sslv3://download.contao.org', 443, $errno, $errstr, 10);`  and test ?

**Comment by leofeyer** [comment]
Yes.

**Comment by freiwild** [comment]
Same.
![grafik](https://cloud.githubusercontent.com/assets/3893317/21807990/7f5a23a2-d741-11e6-953f-d05e3fd2bf0f.png)

**Comment by fritzmg** [comment]
@freiwild: replace [these lines](https://github.com/contao/core/blob/3.5.21/system/modules/repository/classes/RepositoryBackendModule.php#L128-L131)
```php
$this->client = new SoapClient($wsdl, array(
	'soap_version' => SOAP_1_2,
	'compression' => SOAP_COMPRESSION_ACCEPT | SOAP_COMPRESSION_FIXED | 1
));
```
with
```php
$this->client = new SoapClient($wsdl, array(
	'soap_version' => SOAP_1_2,
	'compression' => SOAP_COMPRESSION_ACCEPT | SOAP_COMPRESSION_FIXED | 1,
	'stream_context' => stream_context_create(
		[
			'ssl' => [
				'ciphers' => 'ECDHE-RSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-SHA384:ECDHE-RSA-AES256-SHA:AES256-GCM-SHA384:AES256-SHA256:AES256-SHA:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-SHA256:ECDHE-RSA-AES128-SHA:AES128-GCM-SHA256:AES128-SHA256:AES128-SHA:ECDHE-RSA-DES-CBC3-SHA:DES-CBC3-SHA',
			],
		]
	)
));
```
and access the Extension Repository again in the back end.

**Comment by fritzmg** [comment]
You can also try
```php
$this->client = new SoapClient($wsdl, array(
	'soap_version' => SOAP_1_2,
	'compression' => SOAP_COMPRESSION_ACCEPT | SOAP_COMPRESSION_FIXED | 1,
	'stream_context' => stream_context_create(
		[
			'ssl' => [
				'crypto_method' => STREAM_CRYPTO_METHOD_SSLv3_CLIENT
			]
		]
	)
));
```
if you have PHP 5.6+

**Comment by freiwild** [comment]
No Change. Error Log:
`[10-Jan-2017 13:42:11 GMT] 
PHP Warning: SoapClient::SoapClient(): SSL operation failed with code 1. OpenSSL Error messages:
error:14077438:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert internal error in .../system/modules/repository/classes/RepositoryBackendModule.php on line 144
#0 [internal function]: __error(2, 'SoapClient::Soa...', '/var/www/vhosts...', 144, Array)
#1 .../system/modules/repository/classes/RepositoryBackendModule.php(144): SoapClient->SoapClient('https://contao....', Array)
#2 .../system/modules/core/classes/BackendModule.php(98): RepositoryBackendModule->compile()
#3 .../system/modules/repository/classes/RepositoryBackendModule.php(72): Contao\BackendModule->generate()
#4 .../system/modules/repository/classes/RepositoryManager.php(57): RepositoryBackendModule->generate()
#5 .../system/modules/core/classes/Backend.php(423): RepositoryManager->generate()
#6 .../system/modules/core/controllers/BackendMain.php(131): Contao\Backend->getBackendModule('repository_mana...')
#7 .../contao/main.php(20): Contao\BackendMain->run()
#8 {main}

[10-Jan-2017 13:42:11 GMT] 
PHP Warning: SoapClient::SoapClient(): Failed to enable crypto in .../system/modules/repository/classes/RepositoryBackendModule.php on line 144
#0 [internal function]: __error(2, 'SoapClient::Soa...', '/var/www/vhosts...', 144, Array)
#1 .../system/modules/repository/classes/RepositoryBackendModule.php(144): SoapClient->SoapClient('https://contao....', Array)
#2 .../system/modules/core/classes/BackendModule.php(98): RepositoryBackendModule->compile()
#3 .../system/modules/repository/classes/RepositoryBackendModule.php(72): Contao\BackendModule->generate()
#4 .../system/modules/repository/classes/RepositoryManager.php(57): RepositoryBackendModule->generate()
#5 .../system/modules/core/classes/Backend.php(423): RepositoryManager->generate()
#6 .../system/modules/core/controllers/BackendMain.php(131): Contao\Backend->getBackendModule('repository_mana...')
#7 .../contao/main.php(20): Contao\BackendMain->run()
#8 {main}

[10-Jan-2017 13:42:11 GMT] 
PHP Warning: SoapClient::SoapClient(https://contao.org/services/repository.wsdl): failed to open stream: operation failed in .../system/modules/repository/classes/RepositoryBackendModule.php on line 144
#0 [internal function]: __error(2, 'SoapClient::Soa...', '/var/www/vhosts...', 144, Array)
#1 .../system/modules/repository/classes/RepositoryBackendModule.php(144): SoapClient->SoapClient('https://contao....', Array)
#2 .../system/modules/core/classes/BackendModule.php(98): RepositoryBackendModule->compile()
#3 .../system/modules/repository/classes/RepositoryBackendModule.php(72): Contao\BackendModule->generate()
#4 .../system/modules/repository/classes/RepositoryManager.php(57): RepositoryBackendModule->generate()
#5 .../system/modules/core/classes/Backend.php(423): RepositoryManager->generate()
#6 .../system/modules/core/controllers/BackendMain.php(131): Contao\Backend->getBackendModule('repository_mana...')
#7 .../contao/main.php(20): Contao\BackendMain->run()
#8 {main}

[10-Jan-2017 13:42:11 GMT] 
PHP Warning: SoapClient::SoapClient(): I/O warning : failed to load external entity &quot;https://contao.org/services/repository.wsdl&quot; in .../system/modules/repository/classes/RepositoryBackendModule.php on line 144
#0 [internal function]: __error(2, 'SoapClient::Soa...', '/var/www/vhosts...', 144, Array)
#1 .../system/modules/repository/classes/RepositoryBackendModule.php(144): SoapClient->SoapClient('https://contao....', Array)
#2 .../system/modules/core/classes/BackendModule.php(98): RepositoryBackendModule->compile()
#3 .../system/modules/repository/classes/RepositoryBackendModule.php(72): Contao\BackendModule->generate()
#4 .../system/modules/repository/classes/RepositoryManager.php(57): RepositoryBackendModule->generate()
#5 .../system/modules/core/classes/Backend.php(423): RepositoryManager->generate()
#6 .../system/modules/core/controllers/BackendMain.php(131): Contao\Backend->getBackendModule('repository_mana...')
#7 .../contao/main.php(20): Contao\BackendMain->run()
#8 {main}

[10-Jan-2017 13:42:13 GMT] 
PHP Warning: SoapClient::SoapClient(): SSL operation failed with code 1. OpenSSL Error messages:
error:14077438:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert internal error in .../system/modules/repository/classes/RepositoryBackendModule.php on line 144
#0 [internal function]: __error(2, 'SoapClient::Soa...', '/var/www/vhosts...', 144, Array)
#1 .../system/modules/repository/classes/RepositoryBackendModule.php(144): SoapClient->SoapClient('https://contao....', Array)
#2 .../system/modules/core/classes/BackendModule.php(98): RepositoryBackendModule->compile()
#3 .../system/modules/repository/classes/RepositoryBackendModule.php(72): Contao\BackendModule->generate()
#4 .../system/modules/repository/classes/RepositoryCatalog.php(43): RepositoryBackendModule->generate()
#5 .../system/modules/core/classes/Backend.php(423): RepositoryCatalog->generate()
#6 .../system/modules/core/controllers/BackendMain.php(131): Contao\Backend->getBackendModule('repository_cata...')
#7 .../contao/main.php(20): Contao\BackendMain->run()
#8 {main}

[10-Jan-2017 13:42:13 GMT] 
PHP Warning: SoapClient::SoapClient(): Failed to enable crypto in .../system/modules/repository/classes/RepositoryBackendModule.php on line 144
#0 [internal function]: __error(2, 'SoapClient::Soa...', '/var/www/vhosts...', 144, Array)
#1 .../system/modules/repository/classes/RepositoryBackendModule.php(144): SoapClient->SoapClient('https://contao....', Array)
#2 .../system/modules/core/classes/BackendModule.php(98): RepositoryBackendModule->compile()
#3 .../system/modules/repository/classes/RepositoryBackendModule.php(72): Contao\BackendModule->generate()
#4 .../system/modules/repository/classes/RepositoryCatalog.php(43): RepositoryBackendModule->generate()
#5 .../system/modules/core/classes/Backend.php(423): RepositoryCatalog->generate()
#6 .../system/modules/core/controllers/BackendMain.php(131): Contao\Backend->getBackendModule('repository_cata...')
#7 .../contao/main.php(20): Contao\BackendMain->run()
#8 {main}

[10-Jan-2017 13:42:13 GMT] 
PHP Warning: SoapClient::SoapClient(https://contao.org/services/repository.wsdl): failed to open stream: operation failed in .../system/modules/repository/classes/RepositoryBackendModule.php on line 144
#0 [internal function]: __error(2, 'SoapClient::Soa...', '/var/www/vhosts...', 144, Array)
#1 .../system/modules/repository/classes/RepositoryBackendModule.php(144): SoapClient->SoapClient('https://contao....', Array)
#2 .../system/modules/core/classes/BackendModule.php(98): RepositoryBackendModule->compile()
#3 .../system/modules/repository/classes/RepositoryBackendModule.php(72): Contao\BackendModule->generate()
#4 .../system/modules/repository/classes/RepositoryCatalog.php(43): RepositoryBackendModule->generate()
#5 .../system/modules/core/classes/Backend.php(423): RepositoryCatalog->generate()
#6 .../system/modules/core/controllers/BackendMain.php(131): Contao\Backend->getBackendModule('repository_cata...')
#7 .../contao/main.php(20): Contao\BackendMain->run()
#8 {main}

[10-Jan-2017 13:42:13 GMT] 
PHP Warning: SoapClient::SoapClient(): I/O warning : failed to load external entity &quot;https://contao.org/services/repository.wsdl&quot; in .../system/modules/repository/classes/RepositoryBackendModule.php on line 144
#0 [internal function]: __error(2, 'SoapClient::Soa...', '/var/www/vhosts...', 144, Array)
#1 .../system/modules/repository/classes/RepositoryBackendModule.php(144): SoapClient->SoapClient('https://contao....', Array)
#2 .../system/modules/core/classes/BackendModule.php(98): RepositoryBackendModule->compile()
#3 .../system/modules/repository/classes/RepositoryBackendModule.php(72): Contao\BackendModule->generate()
#4 .../system/modules/repository/classes/RepositoryCatalog.php(43): RepositoryBackendModule->generate()
#5 .../system/modules/core/classes/Backend.php(423): RepositoryCatalog->generate()
#6 .../system/modules/core/controllers/BackendMain.php(131): Contao\Backend->getBackendModule('repository_cata...')
#7 .../contao/main.php(20): Contao\BackendMain->run()
#8 {main}

[10-Jan-2017 13:42:13 GMT] 
PHP Warning: Invalid argument supplied for foreach() in .../system/modules/repository/templates/repository_catlist.html5 on line 32
#0 .../system/modules/repository/templates/repository_catlist.html5(32): __error(2, 'Invalid argumen...', '/var/www/vhosts...', 32, Array)
#1 .../system/modules/core/library/Contao/BaseTemplate.php(88): include('/var/www/vhosts...')
#2 .../system/modules/core/library/Contao/Template.php(277): Contao\BaseTemplate->parse()
#3 .../system/modules/core/classes/BackendTemplate.php(34): Contao\Template->parse()
#4 .../system/modules/core/classes/BackendModule.php(100): Contao\BackendTemplate->parse()
#5 .../system/modules/repository/classes/RepositoryBackendModule.php(72): Contao\BackendModule->generate()
#6 .../system/modules/repository/classes/RepositoryCatalog.php(43): RepositoryBackendModule->generate()
#7 .../system/modules/core/classes/Backend.php(423): RepositoryCatalog->generate()
#8 .../system/modules/core/controllers/BackendMain.php(131): Contao\Backend->getBackendModule('repository_cata...')
#9 .../contao/main.php(20): Contao\BackendMain->run()
#10 {main}

[10-Jan-2017 13:42:13 GMT] 
PHP Warning: Invalid argument supplied for foreach() in .../system/modules/repository/templates/repository_catlist.html5 on line 68
#0 .../system/modules/repository/templates/repository_catlist.html5(68): __error(2, 'Invalid argumen...', '/var/www/vhosts...', 68, Array)
#1 .../system/modules/core/library/Contao/BaseTemplate.php(88): include('/var/www/vhosts...')
#2 .../system/modules/core/library/Contao/Template.php(277): Contao\BaseTemplate->parse()
#3 .../system/modules/core/classes/BackendTemplate.php(34): Contao\Template->parse()
#4 .../system/modules/core/classes/BackendModule.php(100): Contao\BackendTemplate->parse()
#5 .../system/modules/repository/classes/RepositoryBackendModule.php(72): Contao\BackendModule->generate()
#6 .../system/modules/repository/classes/RepositoryCatalog.php(43): RepositoryBackendModule->generate()
#7 .../system/modules/core/classes/Backend.php(423): RepositoryCatalog->generate()
#8 .../system/modules/core/controllers/BackendMain.php(131): Contao\Backend->getBackendModule('repository_cata...')
#9 .../contao/main.php(20): Contao\BackendMain->run()
#10 {main}`

**Comment by freiwild** [comment]
@fritzmg Same. Still not working.

**Comment by fritzmg** [comment]
And finally try
```php
$this->client = new SoapClient($wsdl, array(
	'soap_version' => SOAP_1_2,
	'compression' => SOAP_COMPRESSION_ACCEPT | SOAP_COMPRESSION_FIXED | 1,
	'stream_context' => stream_context_create(
		[
			'ssl' => [
				'ciphers' => 'ECDHE-RSA-AES256-SHA:AES256-SHA:ECDHE-RSA-AES128-SHA:AES128-SHA:CDHE-RSA-DES-CBC3-SHA:DES-CBC3-SHA'
			]
		]
	)
));
```

**Comment by freiwild** [comment]
:( Same.
`[10-Jan-2017 13:59:20 GMT] 
PHP Warning: SoapClient::SoapClient(): SSL operation failed with code 1. OpenSSL Error messages:
error:14077438:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert internal error in .../system/modules/repository/classes/RepositoryBackendModule.php on line 171
#0 [internal function]: __error(2, 'SoapClient::Soa...', '/var/www/vhosts...', 171, Array)
#1 .../system/modules/repository/classes/RepositoryBackendModule.php(171): SoapClient->SoapClient('https://contao....', Array)
#2 .../system/modules/core/classes/BackendModule.php(98): RepositoryBackendModule->compile()
#3 .../system/modules/repository/classes/RepositoryBackendModule.php(72): Contao\BackendModule->generate()
#4 .../system/modules/repository/classes/RepositoryManager.php(57): RepositoryBackendModule->generate()
#5 .../system/modules/core/classes/Backend.php(423): RepositoryManager->generate()
#6 .../system/modules/core/controllers/BackendMain.php(131): Contao\Backend->getBackendModule('repository_mana...')
#7 .../contao/main.php(20): Contao\BackendMain->run()
#8 {main}

[10-Jan-2017 13:59:20 GMT] 
PHP Warning: SoapClient::SoapClient(): Failed to enable crypto in .../system/modules/repository/classes/RepositoryBackendModule.php on line 171
#0 [internal function]: __error(2, 'SoapClient::Soa...', '/var/www/vhosts...', 171, Array)
#1 .../system/modules/repository/classes/RepositoryBackendModule.php(171): SoapClient->SoapClient('https://contao....', Array)
#2 .../system/modules/core/classes/BackendModule.php(98): RepositoryBackendModule->compile()
#3 .../system/modules/repository/classes/RepositoryBackendModule.php(72): Contao\BackendModule->generate()
#4 .../system/modules/repository/classes/RepositoryManager.php(57): RepositoryBackendModule->generate()
#5 .../system/modules/core/classes/Backend.php(423): RepositoryManager->generate()
#6 .../system/modules/core/controllers/BackendMain.php(131): Contao\Backend->getBackendModule('repository_mana...')
#7 .../contao/main.php(20): Contao\BackendMain->run()
#8 {main}

[10-Jan-2017 13:59:20 GMT] 
PHP Warning: SoapClient::SoapClient(https://contao.org/services/repository.wsdl): failed to open stream: operation failed in .../system/modules/repository/classes/RepositoryBackendModule.php on line 171
#0 [internal function]: __error(2, 'SoapClient::Soa...', '/var/www/vhosts...', 171, Array)
#1 .../system/modules/repository/classes/RepositoryBackendModule.php(171): SoapClient->SoapClient('https://contao....', Array)
#2 .../system/modules/core/classes/BackendModule.php(98): RepositoryBackendModule->compile()
#3 .../system/modules/repository/classes/RepositoryBackendModule.php(72): Contao\BackendModule->generate()
#4 .../system/modules/repository/classes/RepositoryManager.php(57): RepositoryBackendModule->generate()
#5 .../system/modules/core/classes/Backend.php(423): RepositoryManager->generate()
#6 .../system/modules/core/controllers/BackendMain.php(131): Contao\Backend->getBackendModule('repository_mana...')
#7 .../contao/main.php(20): Contao\BackendMain->run()
#8 {main}

[10-Jan-2017 13:59:20 GMT] 
PHP Warning: SoapClient::SoapClient(): I/O warning : failed to load external entity &quot;https://contao.org/services/repository.wsdl&quot; in .../system/modules/repository/classes/RepositoryBackendModule.php on line 171
#0 [internal function]: __error(2, 'SoapClient::Soa...', '/var/www/vhosts...', 171, Array)
#1 .../system/modules/repository/classes/RepositoryBackendModule.php(171): SoapClient->SoapClient('https://contao....', Array)
#2 .../system/modules/core/classes/BackendModule.php(98): RepositoryBackendModule->compile()
#3 .../system/modules/repository/classes/RepositoryBackendModule.php(72): Contao\BackendModule->generate()
#4 .../system/modules/repository/classes/RepositoryManager.php(57): RepositoryBackendModule->generate()
#5 .../system/modules/core/classes/Backend.php(423): RepositoryManager->generate()
#6 .../system/modules/core/controllers/BackendMain.php(131): Contao\Backend->getBackendModule('repository_mana...')
#7 .../contao/main.php(20): Contao\BackendMain->run()
#8 {main}

[10-Jan-2017 13:59:23 GMT] 
PHP Warning: SoapClient::SoapClient(): SSL operation failed with code 1. OpenSSL Error messages:
error:14077438:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert internal error in .../system/modules/repository/classes/RepositoryBackendModule.php on line 171
#0 [internal function]: __error(2, 'SoapClient::Soa...', '/var/www/vhosts...', 171, Array)
#1 .../system/modules/repository/classes/RepositoryBackendModule.php(171): SoapClient->SoapClient('https://contao....', Array)
#2 .../system/modules/core/classes/BackendModule.php(98): RepositoryBackendModule->compile()
#3 .../system/modules/repository/classes/RepositoryBackendModule.php(72): Contao\BackendModule->generate()
#4 .../system/modules/repository/classes/RepositoryCatalog.php(43): RepositoryBackendModule->generate()
#5 .../system/modules/core/classes/Backend.php(423): RepositoryCatalog->generate()
#6 .../system/modules/core/controllers/BackendMain.php(131): Contao\Backend->getBackendModule('repository_cata...')
#7 .../contao/main.php(20): Contao\BackendMain->run()
#8 {main}

[10-Jan-2017 13:59:23 GMT] 
PHP Warning: SoapClient::SoapClient(): Failed to enable crypto in .../system/modules/repository/classes/RepositoryBackendModule.php on line 171
#0 [internal function]: __error(2, 'SoapClient::Soa...', '/var/www/vhosts...', 171, Array)
#1 .../system/modules/repository/classes/RepositoryBackendModule.php(171): SoapClient->SoapClient('https://contao....', Array)
#2 .../system/modules/core/classes/BackendModule.php(98): RepositoryBackendModule->compile()
#3 .../system/modules/repository/classes/RepositoryBackendModule.php(72): Contao\BackendModule->generate()
#4 .../system/modules/repository/classes/RepositoryCatalog.php(43): RepositoryBackendModule->generate()
#5 .../system/modules/core/classes/Backend.php(423): RepositoryCatalog->generate()
#6 .../system/modules/core/controllers/BackendMain.php(131): Contao\Backend->getBackendModule('repository_cata...')
#7 .../contao/main.php(20): Contao\BackendMain->run()
#8 {main}

[10-Jan-2017 13:59:23 GMT] 
PHP Warning: SoapClient::SoapClient(https://contao.org/services/repository.wsdl): failed to open stream: operation failed in .../system/modules/repository/classes/RepositoryBackendModule.php on line 171
#0 [internal function]: __error(2, 'SoapClient::Soa...', '/var/www/vhosts...', 171, Array)
#1 .../system/modules/repository/classes/RepositoryBackendModule.php(171): SoapClient->SoapClient('https://contao....', Array)
#2 .../system/modules/core/classes/BackendModule.php(98): RepositoryBackendModule->compile()
#3 .../system/modules/repository/classes/RepositoryBackendModule.php(72): Contao\BackendModule->generate()
#4 .../system/modules/repository/classes/RepositoryCatalog.php(43): RepositoryBackendModule->generate()
#5 .../system/modules/core/classes/Backend.php(423): RepositoryCatalog->generate()
#6 .../system/modules/core/controllers/BackendMain.php(131): Contao\Backend->getBackendModule('repository_cata...')
#7 .../contao/main.php(20): Contao\BackendMain->run()
#8 {main}

[10-Jan-2017 13:59:23 GMT] 
PHP Warning: SoapClient::SoapClient(): I/O warning : failed to load external entity &quot;https://contao.org/services/repository.wsdl&quot; in .../system/modules/repository/classes/RepositoryBackendModule.php on line 171
#0 [internal function]: __error(2, 'SoapClient::Soa...', '/var/www/vhosts...', 171, Array)
#1 .../system/modules/repository/classes/RepositoryBackendModule.php(171): SoapClient->SoapClient('https://contao....', Array)
#2 .../system/modules/core/classes/BackendModule.php(98): RepositoryBackendModule->compile()
#3 .../system/modules/repository/classes/RepositoryBackendModule.php(72): Contao\BackendModule->generate()
#4 .../system/modules/repository/classes/RepositoryCatalog.php(43): RepositoryBackendModule->generate()
#5 .../system/modules/core/classes/Backend.php(423): RepositoryCatalog->generate()
#6 .../system/modules/core/controllers/BackendMain.php(131): Contao\Backend->getBackendModule('repository_cata...')
#7 .../contao/main.php(20): Contao\BackendMain->run()
#8 {main}

[10-Jan-2017 13:59:23 GMT] 
PHP Warning: Invalid argument supplied for foreach() in .../system/modules/repository/templates/repository_catlist.html5 on line 32
#0 .../system/modules/repository/templates/repository_catlist.html5(32): __error(2, 'Invalid argumen...', '/var/www/vhosts...', 32, Array)
#1 .../system/modules/core/library/Contao/BaseTemplate.php(88): include('/var/www/vhosts...')
#2 .../system/modules/core/library/Contao/Template.php(277): Contao\BaseTemplate->parse()
#3 .../system/modules/core/classes/BackendTemplate.php(34): Contao\Template->parse()
#4 .../system/modules/core/classes/BackendModule.php(100): Contao\BackendTemplate->parse()
#5 .../system/modules/repository/classes/RepositoryBackendModule.php(72): Contao\BackendModule->generate()
#6 .../system/modules/repository/classes/RepositoryCatalog.php(43): RepositoryBackendModule->generate()
#7 .../system/modules/core/classes/Backend.php(423): RepositoryCatalog->generate()
#8 .../system/modules/core/controllers/BackendMain.php(131): Contao\Backend->getBackendModule('repository_cata...')
#9 .../contao/main.php(20): Contao\BackendMain->run()
#10 {main}

[10-Jan-2017 13:59:23 GMT] 
PHP Warning: Invalid argument supplied for foreach() in .../system/modules/repository/templates/repository_catlist.html5 on line 68
#0 .../system/modules/repository/templates/repository_catlist.html5(68): __error(2, 'Invalid argumen...', '/var/www/vhosts...', 68, Array)
#1 .../system/modules/core/library/Contao/BaseTemplate.php(88): include('/var/www/vhosts...')
#2 .../system/modules/core/library/Contao/Template.php(277): Contao\BaseTemplate->parse()
#3 .../system/modules/core/classes/BackendTemplate.php(34): Contao\Template->parse()
#4 .../system/modules/core/classes/BackendModule.php(100): Contao\BackendTemplate->parse()
#5 .../system/modules/repository/classes/RepositoryBackendModule.php(72): Contao\BackendModule->generate()
#6 .../system/modules/repository/classes/RepositoryCatalog.php(43): RepositoryBackendModule->generate()
#7 .../system/modules/core/classes/Backend.php(423): RepositoryCatalog->generate()
#8 .../system/modules/core/controllers/BackendMain.php(131): Contao\Backend->getBackendModule('repository_cata...')
#9 .../contao/main.php(20): Contao\BackendMain->run()
#10 {main}`

**Comment by fritzmg** [comment]
Btw. you should use
` ```…``` `
to post error messages ;)

**Comment by freiwild** [comment]
``` Thanks :) ```

**Comment by leofeyer** [comment]
What is the status of this ticket?

**Comment by fritzmg** [comment]
imho it can be closed. Hopefully all hosters have updated their outdated OpenSSL versions.
