### ISSUE TITLE
Sort icon should not be visibile for modules if the user doesn't have the rights to edit modules

### ISSUE THREAD

**Issue by arno1979** [contao/core#8616]
The title pretty much says it all: I just noticed that a non-admin user gets to see the sort icon for a module inside of an article in the backend (see screenshot). He can even drag & drop the module around without having the rights to edit modules. This is obviously confusing because the editor gets the impression that he can change the placement of the module inside the article without actually being able to do that.
<img width="250" alt="screenshot-dragable-module" src="https://cloud.githubusercontent.com/assets/1838113/21851856/27e81d24-d811-11e6-910f-3240c7eabd96.png">

**Comment by leofeyer** [comment]
Why would the editor not be able to move the element around?

**Comment by aschempp** [comment]
Looks like you're using the `ce-access` extension?

**Comment by arno1979** [comment]
@leofeyer Oh, he is able to move the element around but it has no effect. And if he reloads the backend page the module is back to its original position.
@aschempp Yes, I am. I never thought this could have anything to do with the problem. How do you think `ce-access` is related to the issue?

**Comment by aschempp** [comment]
Well ce-acces limits access to content elements. It probably also limits the move functionality, that's why the blue arrow is gone…

**Comment by arno1979** [comment]
@aschempp My problem is not that the blue move arrow is missing, that's fine with me. My issue is with the green sort icon (see also my screenshot). That should be gone as well as the user has no right to edit content elements of the type "module".
But maybe this means that its not actually a ´contao/core´ but an ´ce-access´issue and the extension should take care of removing the sort icon from the backend view?

**Comment by aschempp** [comment]
Absolutely. I can slightly remember that removing that arrow was not possible/not that easy, but if you have a developer that could fix that feel free to create a pull request :-)

**Comment by arno1979** [comment]
@aschempp In this case the developer would be me. :-) I haven't looked into it at all but hope I will find the time soon. At least I now know that its a `ce-access` issue, so I guess we could close this ticket.
