### ISSUE TITLE
[3.5.22] Startseite mit Seitenalias ungleich "index" führt zu Redirect-Loop

### ISSUE THREAD

**Issue by Mynyx** [contao/core#8619]
Wenn der Seitenalias der Startseite ungleich "index" ist z. B. "startseite" führt der Aufruf der Startseite zu einem Redirect-Loop (als URL-Suffix "/" ist eingestellt).

Sofern der Seitencache aktiviert ist, muss dieser um den Fehler zu reproduzieren nach der Änderung des Seitenalias geleert werden.

**Comment by asaage** [comment]
https://github.com/contao/core/issues/8560

```/``` als URL-Suffix klingt für mich noch abenteuerlicher als ```/``` als Seiten-Alias 😄

**Comment by Mynyx** [comment]
Der Fehler wird offenbar durch die googlesitemap-Erweiterung verursacht, ist also nicht wirklich ein Bug im Core, gleichwohl tritt er jedoch mit Contao 3.5.17 nicht auf.

**Comment by leofeyer** [comment]
Sollte es sich doch als Bug im Core herausstellen, sag Bescheid, dann öffne ich das Ticket wieder.
