### ISSUE TITLE
Artikel mit Download-Element kann nach Update auf 3.5.22 nicht mehr bearbeitet werden

### ISSUE THREAD

**Issue by netzarbeiter** [contao/core#8620]
Nach dem Update auf Contao 3.5.22 erhalte ich beim Versuch einen Artikel mit Download-Element zu bearbeiten eine weisse Seite.

error.log
```
[17-Jan-2017 09:52:13 Europe/Zurich] PHP Fatal error:  Call to a member function getFrontendUrl() on null in /system/modules/core/elements/ContentDownload.php on line 91
[17-Jan-2017 09:52:48 Europe/Zurich] 
PHP Warning: Unknown: open(/tmp//sess_r9pt3pv9015s6cidbv5l92jie5t6iksk, O_RDWR) failed: Permission denied (13) in Unknown on line 0
#0 [internal function]: __error(2, 'Unknown: open(/...', 'Unknown', 0, NULL)
#1 {main}
```

**Comment by planepix** [comment]
Kann ich bestätigen. Auch hier nach dem Update das gleiche Phänomen.

**Comment by fenepedia** [comment]
Kann ich ebenfalls bestätigen.

**Comment by fritzmg** [comment]
Caused by #8604, @Toflar weiß schon bescheid. Als Workaround könntet ihr einstweilen diese Zeilen:

* https://github.com/contao/core/blob/3.5.22/system/modules/core/elements/ContentDownload.php#L91
* https://github.com/contao/core/blob/3.5.22/system/modules/core/elements/ContentDownloads.php#L149
* https://github.com/contao/core/blob/3.5.22/system/modules/core/elements/ContentDownloads.php#L225

mit
```php
$strHref = \Environment::get('request');
```
ersetzen.

**Comment by leofeyer** [comment]
In der `ContentDownloads` sollte das Problem eigentlich nicht auftreten, oder?

**Comment by fritzmg** [comment]
Ich hab's jetzt nicht extra getestet, aber auch `ContentDownloads` erzeugt im Backend die selbe Ausgabe wie im Frontend, oder nicht? Und auch dort wird auf `$objPage->getFrontendUrl()` zugegriffen.

**Comment by leofeyer** [comment]
Das stimmt, wobei es da aber auch schon vorher Zugriffe auf `$objPage` gab. Hm …

**Comment by jubofl** [comment]
Bei mir sehen die drei Zeilen schon so aus wie von @fritzmg weiter oben empfohlen. Die Dateien sind vom Mai/Oktober 2016.

**Comment by Toflar** [comment]
Ja, das war die alte Version und auch die stimmt nicht ;-) Ich werd mich kümmern, wenn ich ein paar Minuten hab.

**Comment by jubofl** [comment]
Ach, Denkfehler!
Ich habe doch alles auf .22 wiederherstellen lassen. Okay, dann mache ich das Update auf .23, und dann dürften die ContendDownload(s) so aussehen wie beschrieben.
Danke!

**Comment by leofeyer** [comment]
Behoben in f4475daf029f2946f7942d7ed4bc6a17610e638f. Bitte kurz testen und Feedback geben, damit wir zeitnah Contao 3.5.23 veröffentlichen können.

**Comment by netzarbeiter** [comment]
Der Fix funktioniert bei mir.

**Comment by ausi** [comment]
@leofeyer Das Auto-Item wird von `$objPage->getFrontendUrl()` nicht berücksichtigt, deshalb funktionieren Download-Inhaltslemente innerhalb von z. B. News-Beiträgen aktuell in 3.5.23 nicht mehr.

**Comment by leofeyer** [comment]
Wir werden die Änderung wohl komplett zurück bauen müssen. 😩

**Comment by leofeyer** [comment]
Reverted in 4525ee770edf53440df1c7af564dff3cdaeb2f49.
