### ISSUE TITLE
FormTextArea, specialchars & allowHtml

### ISSUE THREAD

**Issue by sebj54** [contao/core#8623]
Hi,

I made a form on a website and I used a textarea with allowHtml set to to true. So I expected my field would save plain html in database instead of replacing `<` & `>` with `&lt;` & `&rt;`.

But this is not the case because of [this code](https://github.com/contao/core/blob/3.5.22/system/modules/core/forms/FormTextArea.php#L147) in `FormTextArea`:
```php
public function __get($strKey)
{
	switch ($strKey)
	{
		// [...]
		case 'value':
			return specialchars(str_replace('\n', "\n", $this->varValue));
			break;
		// [...]
	}
}
```

Is it the expected behavior?

**Comment by Aybee** [comment]
I think this code is only for the content of the attribute "value".
```html
<textarea value="firts line\nsecond line<br>">
<textarea value="firts line
second line&lt;br&gt;">
```

**Comment by sebj54** [comment]
That's right, it's used by Contao for the value attribute when generating a textarea widget. Personnaly, I use widgets to generate a form and to validate field values before saving them in database.
The problem with `FormTextArea` is that there is no other way to get its value without stripping tags.

Here are some extracts of my code:

```php
$strClass = $GLOBALS['TL_FFL'][$field['inputType']];
$objWidget = new $strClass($strClass::getAttributesFromDca($field, $name, $field['value'], '', '', null, true));

if ($isPost)
{
	$objWidget->validate();
}

$model->$widgetName = $objWidget->value;
$model->save();
```

**Comment by leofeyer** [comment]
I think this is a bug introduced in 92a5488ddd90d9d1c15c2f7ee6f939abf7ae8a9f when fixing #7000. We should not generally apply `specialchars()` to the widget's value.

**Comment by sebj54** [comment]
I can handle that issue and submit a pull request if you want!

**Comment by leofeyer** [comment]
Thank you, but I don't think this will be necessary. It is a small fix and the ticket has already been assigned to the next milestone.

**Comment by sebj54** [comment]
That's why I asked, thanks!

**Comment by leofeyer** [comment]
Fixed in 3da97c6a942c2ca51c5b1dd0baf1f6cf44379019.

**Comment by leofeyer** [comment]
I had to revert the changes in e603e0f4b567593ec39d53363c53cccd80ae7017 (see [the discussion](https://github.com/contao/core/pull/8670/files/3e273a87f35ebb3ecafa36d695c3e380a1712b26#diff-dc55a5dd360155b9da2ccfb10dbc396f)).

**Comment by sebj54** [comment]
I understand why you reverted the changes.
To satisfy everyone, can you allow to return html tags if `allowHtml` is explicitely set to `true` in the DCA?
By doing this, you are not changing the actual default behaviour.

**Comment by leofeyer** [comment]
@ausi What do you think?

**Comment by ausi** [comment]
`FormTextArea` is a frontend form widget, not related to the DCA. I think many people may use the widget with `allowHtml` activated, so this would be a behavior change for them.

@sebj54 In your code, you can wrap the value in an `html_entity_decode()` to get the unescaped value back:

```php
$model->$name = html_entity_decode($objWidget->value);
```

**Comment by sebj54** [comment]
Right, `FormTextArea` is a frontend form widget and that's exactly how we use it in my company. We create a widget from a DCA (not the backend's one, but an adapted "copy" of the field's configuration). See my [previous comment](https://github.com/contao/core/issues/8623#issuecomment-273179533) for an brief example.

I thought to use the `html_entity_decode()` function but it will render unwanted tags even if tag is not in `$GLOBALS['TL_CONFIG']['allowedTags']`. 

The only satisfying solution actually is to *patch* `FormTextArea` to remove this default behaviour. In my opinion, stripping potential closing tag (`</textarea>`) and not allowed tags is enough protection.

**Comment by ausi** [comment]
> I thought to use the `html_entity_decode()` function but it will render unwanted tags even if tag is not in `$GLOBALS['TL_CONFIG']['allowedTags']`.

You are right, thats the bug IMO. I think we should use `specialchars` with `$blnDoubleEncode` enabled:

```php
specialchars(str_replace('\n', "\n", $this->varValue), false, true);
```

With this change `html_entity_decode()` should work for you and the widgets value should still be secure.

**Comment by leofeyer** [comment]
Isn't this a behavior change, too?

**Comment by ausi** [comment]
Yes, but IMO not an unsecure change.

**Comment by sebj54** [comment]
Should I understand that it will be possible? :)

**Comment by leofeyer** [comment]
Yes. Changed in 73218ac9ae990d5b938bb51d63741690e8d44d39.
