### ISSUE TITLE
Images in News not viewable/editable for user-groups other than Admins

### ISSUE THREAD

**Issue by rorych** [contao/core#8625]
Hi there 

So i have been having a problem with an installation of ours.
It seems like on random, users that are not admins cannot edit the image of a news-entry.
We see the Error -> tl_content_news::checkAccessToElement (Invalid news content element ID 1)

I have checked what is happening and have the feeling it is a bug in contao.
In system/modules/news/dca/tl_content.php inside "checkPermission()"
there is a switch depending on the GET Parameter act.
This seems to decide what to check.

If you try to open the current image inside a news-entry, the act seems to be "show".
This is not listed as a case inside the switch statement.
Based on this fact, the "default" action is been triggered.

The default action is -> 
`if (!$this->checkAccessToElement(Input::get('id'), $root))`

Consulting the checkAccessToElement method, i see that if the third parameter isn't = "true", the following SELECT is being executed:
`SELECT a.id, n.id AS nid FROM tl_content c, tl_news n, tl_news_archive a WHERE c.id=$id AND c.pid=n.id AND n.pid=a.id`

After checking the SELECT Query, it looks like we are now trying to SELECT a record inside tl_content but with the ID of a tl_news record.

This results in random true or false returns from this method, explaining why i couldn't find any parity between all the failing news-entrys.

**suggestion**
As a workaround i added "show" as a case looking like this:
`case 'show':
				// Check access to the news item
				if (!$this->checkAccessToElement(Input::get('id'), $root, true))
				{
					$this->redirect('contao/main.php?act=error');
				}
				break;`

What do you think? I'm thinking this is a dirty fix but what could we to do resolve this problem in future versions?

Thanks in advance

**Comment by rorych** [comment]
Hi there

I'm sorry to reopen this Case.
We found that the workaround provided in the first Entry has the effect, that now we get the error, when editing an image inside the details of a news-element.

Meaning, now i can edit the teaser image without the error, because the "show" case looks for the ID inside the tl_news table.
But if i edit an image inside the details of a news-element, the same act=show is triggered and the tl_news is being queried although the details are kept inside tl_content, so the error appears here now...

I'm asking myself why the GET Parameter "table" is not being used, to define which table to query...?

I'm not shure if putting a if statement inside the show case is the right way to go, i don't have the overview you guys have.

Our workaround:

```
case 'show': 
if(Input::get('table') == "tl_news"){
	// Check access to the news item 
	if (!$this->checkAccessToElement(Input::get('id'), $root, true)) 
	{ 
		$this->redirect('contao/main.php?act=error'); 
	}
} else {
	// Check access to the content item
	if (!$this->checkAccessToElement(Input::get('id'), $root)) 
	{ 
		$this->redirect('contao/main.php?act=error'); 
	}
}
break;
```

**Comment by leofeyer** [comment]
I cannot reproduce the issue. I never had problems accessing the image as a non-administrator user. Also, the SQL query looks correct to me:

```sql
SELECT a.id, n.id AS nid FROM tl_content c, tl_news n, tl_news_archive a WHERE c.id='327' AND c.pid=n.id AND n.pid=a.id LIMIT 0,1
```

`327` is the ID of the content element and not the news record.
