### ISSUE TITLE
"Auto_item aktivieren" should remove /articles/ from URL too

### ISSUE THREAD

**Issue by Metis77** [contao/core#8627]
The setting "Auto_item aktivieren" removes the events/ and items/ part from the URL.
I think it should also remove the articles/ part.

For SEO the shorter URL would be much better. And it would become more readable for humans too.
http://example.com/page/articles/article_1.html 
http://example.com/page/article_1.html  <- better

**Comment by leofeyer** [comment]
This is basically possible, however, we would need to unset the `auto_item` if it matches an article to make it work.

```php
// Controller::getFrontendModule()
if (!is_object($intId) && $intId == 0)
{
	// Set the item from the auto_item parameter
	if (!isset($_GET['articles']) && \Config::get('useAutoItem') && isset($_GET['auto_item']))
	{
		\Input::setGet('articles', \Input::get('auto_item'));
	}

	// Show a particular article only
	if ($objPage->type == 'regular' && \Input::get('articles'))
	{
		list($strSection, $strArticle) = explode(':', \Input::get('articles'));

		if ($strArticle === null)
		{
			$strArticle = $strSection;
			$strSection = 'main';
		}

		if ($strSection == $strColumn)
		{
			$objArticle = \ArticleModel::findPublishedByIdOrAliasAndPid($strArticle, $objPage->id);

			// Send a 404 header if there is no published article
			if (null === $objArticle)
			{
				throw new PageNotFoundException('Page not found: ' . \Environment::get('uri'));
			}

			// Send a 403 header if the article cannot be accessed
			if (!static::isVisibleElement($objArticle))
			{
				throw new AccessDeniedException('Access denied: ' . \Environment::get('uri'));
			}

			\Input::setGet('auto_item', null); // <----- THIS IS REQUIRED

			// Add the "first" and "last" classes (see #2583)
			$objArticle->classes = array('first', 'last');

			return static::getArticle($objArticle);
		}
	}
```

@contao/developers Why are we currently not unsetting the `auto_item` parameter after the first module has used it?

**Comment by ausi** [comment]
I think because I can have two modules on the same page that both want to access the `auto_item`.

**Comment by bytehead** [comment]
I think it's a very bad idea to remove the `auto_item`. We use `auto_item` often in our extensions and they are mostly not the first modules on the page.

**Comment by leofeyer** [comment]
> I think because I can have two modules on the same page that both want to access the `auto_item`.

You mean like two reader modules?

> and they are mostly not the first modules on the page

I didn't suggest to remove the parameter after the first module but after the first module that has used it!

**Comment by bytehead** [comment]
> I didn't suggest to remove the parameter after the first module but after the first module that has used it!

This is totally wrong to me as well. You never know where the value will be used.

**Comment by ausi** [comment]
>> I think because I can have two modules on the same page that both want to access the `auto_item`.
>
> You mean like two reader modules?

Yes, or one reader module and one “related news” module or the like.

**Comment by leofeyer** [comment]
I see. Then it is not possible to remove the `/articles/` fragment.
