### ISSUE TITLE
Datei- und Seiten-Picker öffnen im kompletten Browserfenster

### ISSUE THREAD

**Issue by gerritlo** [contao/core#8629]
Hallo!

Ich habe bei einer Contao-Installation das Problem, dass die Seiten- und Dateipicker sich nicht mehr in einem Dialogfenster öffnen, sondern im kompletten Browserfenster. Dadurch habe ich auch keinen Übernehmen-Button.

Im Log habe ich einen Javascript-Fehler. Ich vermute, dass der Fehler aufgetreten ist, nachdem ich ein manuelles Update von Contao 3.5.xx auf 3.5.22 (SwiftMailer) und eben auf 3.5.24. Leider besteht die Fehlerausgabe in der Browser-Console noch immer.

Danke und Grüße!
![bild 13](https://cloud.githubusercontent.com/assets/1765486/22162886/d6316fac-df50-11e6-84b9-9e2587926c2c.png)
![bild 12](https://cloud.githubusercontent.com/assets/1765486/22162887/d6341f54-df50-11e6-8d8d-71190d176f3e.png)

**Comment by leofeyer** [comment]
Bitte wende Dich mit solchen Anliegen ans [Forum](https://community.contao.org/de/).
