### ISSUE TITLE
Typo: Beschreibungstext in Themes -> vordefinierte Größen

### ISSUE THREAD

**Issue by mathContao** [contao/core#8630]
Themes » Bildgrößen » Die Bildgröße bearbeiten

Typo: is -> ist
![grafik](https://cloud.githubusercontent.com/assets/1645099/22185859/5cb6c8cc-e0ed-11e6-815d-963daeaafdd6.png)

Contao 3.5.23

**Comment by leofeyer** [comment]
I have updated the translation on transifex.com.
