### ISSUE TITLE
Nach Update auf 3.5.24 Download-Element mp4-Dateien nicht sichtbar

### ISSUE THREAD

**Issue by green-pixelbox** [contao/core#8633]
mp4 Dateien sind im Download Element bei der Dateiauswahl nicht mehr sichtbar, in der Dateiverwaltung selber ist die mp4 aber sichtbar

**Comment by fritzmg** [comment]
Hast du mp4 Dateien in den System Einstellungen explizit erlaubt?

**Comment by green-pixelbox** [comment]
Super, das ist es. mp4 war in den Einstellungen nicht mit aufgelistet. Hatte es aber auch nicht entfernt vorher.
