### ISSUE TITLE
3.5.24 Inhaltselement nicht unsichtbar, obwohl dieses als unsichtbar markiert ist

### ISSUE THREAD

**Issue by minstyle** [contao/core#8634]
Über das Backend von Contao 3.5.24 können Core-Inhaltselemente mittlerweile nicht mehr als "unsichtbar" deklariert werden, obwohl diese über das "Auge-Icon" als unsichtbar markiert sind.

Beispiel:

1. Eine neue Seite erstellt.
2. Darin beispielsweise ein neues Inhaltselement mit dem Elementtyp "Überschrift" erstellt und als "veröffentlicht" gespeichert.
3. In der Artikelübersicht dieser Seite wird das "Auge"-Icon als grünes (veröffentlichtes) Symbol dargestellt.
4. Klickt man nun auf das grüne Augen-Symbol, so wird das Inhaltselement als "unsichtbar" (rot) markiert.
5. Allerdings ist dieses Inhaltelement nicht ausgeblendet. Editiere ich das Inhaltslement, so wird es weiterhin als "veröffentlicht" angezeigt!

**Comment by leofeyer** [comment]
Kann das irgendjemand anders reproduzieren?

**Comment by do-while** [comment]
Bist Du vielleicht über die Frontend-Vorschau auf der Seite und hast versteckte Elemente zugelassen?
Passiert das auch in einem "Privaten Fenster" im Browser?

**Comment by minstyle** [comment]
Mit der Frontend-Vorschau hat es leider nichts zu tun, denn der Sichtbar/Unsichtbar-Zustand des Inhaltselements wird im Backend nicht automatisch gespeichert, wenn ich auf das Augensymbol klicke.

Der Bug ist im Chrome und Firefox zu sehen. Mit dem Inkognito-Modus muss ich noch testen...

**Comment by do-while** [comment]
Habe es gerade mal probiert. Bei mir funktioniert das wie gewohnt - kein Contao-Bug!
Getestet mit vorhandenen Inhaltselementen und mit neu angelegten. Immer alles Ok.

Ist denn der Haken bei Unsichtbar auch gesetzt, wenn Du in das Inhaltselement hinein gehst?
Schaltet es mit dem Auge mit um?

Was sagt der Contao-Check?
Ich denke, das ist eher ein Forum-Thema.

**Comment by Samson1964** [comment]
Geht es hier um Artikel oder Inhaltselemente? 
Zu 2) In Seiten kann man keine Inhaltselemente erstellen.
Zu 3 und 4) Siehe meine Frage.

Ansonsten schließe ich mich do-while an. Es geht mit Inhaltselementen(!) in meiner geupdateten 3.5.24. Und auch verschieb' ins Forum.

**Comment by minstyle** [comment]
Es geht um Inhaltselemente innerhalb von **Seiten > Artikel**.

Hier zwei Screenshots, was ich genau meine:

[http://easycaptures.com/fs/uploaded/927/3879160274.gif](url)
[http://easycaptures.com/fs/uploaded/927/8972326579.gif](url)

**Comment by fritzmg** [comment]
Ich kann das Problem in keiner 3.5.24 Installation von mir nachvollziehen. Überprüfe mit den Developer Tools deines Browsers, was mit dem AJAX Request passiert.

**Comment by minstyle** [comment]
Hier ist folgende Fehlermeldung zu sehen:

![image](https://cloud.githubusercontent.com/assets/2649562/22367860/13cf90a4-e484-11e6-9405-e9fb6da10817.png)

Danke für den Hinweis!
Scheint wohl ein Serverproblem zu sein.

**Comment by fritzmg** [comment]
> Aber wieso tritt dieser Fehler nur beim Klick auf das Augensymbol auf? Wenn ich die Checkbox im Inhaltselemnt auf unsichtbar schalte, tritt dieser Fehler nicht auf.

Das sind grundsätzlich verschiedene Requests. Über das Auge ist es ein AJAX Request der dann im Backend PHP Script anders behandelt wird als der reguläre POST Request über das Formular.

**Comment by minstyle** [comment]
Den Fehler scheint wohl die Erweiterung **changelanguage Version 3.1.0 Build 4** zu verursachen.

Bei Aufruf der URL erhalte ich nämlich folgende Fehlermeldung:

`Fatal error: Uncaught exception TypeError with message Argument 1 passed to Terminal42\ChangeLanguage\EventListener\BackendView\AbstractViewListener::Terminal42\ChangeLanguage\EventListener\BackendView\{closure}() must be an instance of Contao\DataContainer, instance of tl_content given, called in /usr/www/users/exap5810/system/modules/core/dca/tl_content.php on line 1765 thrown in system/modules/changelanguage/library/Terminal42/ChangeLanguage/EventListener/BackendView/AbstractViewListener.php on line 51
#0 system/modules/core/dca/tl_content.php(1765): Terminal42\ChangeLanguage\EventListener\BackendView\AbstractViewListener->Terminal42\ChangeLanguage\EventListener\BackendView\{closure}(Object(tl_content))
#1 system/modules/core/dca/tl_content.php(1705): tl_content->toggleVisibility('52', false, NULL)
#2 system/modules/ce-access/CeAccess.php(148): tl_content->toggleIcon(Array, NULL, 'Sichtbarkeit \xC3\xA4...', 'Die Sichtbarkei...', 'visible.gif', ' class="toggle"...')
#3 system/modules/core/classes/DataContainer.php(683): CeAccess->toggleButton(Array, NULL, 'Sichtbarkeit \xC3\xA4...', 'Die Sichtbarkei...', 'visible.gif', ' class="toggle"...', 'tl_content', NULL, NULL, false, NULL, '29', Object(Contao\DC_Table))
#4 system/modules/core/drivers/DC_Table.php(4241): Contao\DataContainer->generateButtons(Array, 'tl_content', NULL, false, NULL, NULL, '29')
#5 system/modules/core/drivers/DC_Table.php(378): Contao\DC_Table->parentView()
#6 system/modules/core/classes/Backend.php(650): Contao\DC_Table->showAll()
#7 system/modules/core/controllers/BackendMain.php(131): Contao\Backend->getBackendModule('article')
#8 contao/main.php(20): Contao\BackendMain->run()
#9 {main}`

Nochmals danke für euren Support!

**Comment by fritzmg** [comment]
Dann gleich hier reporten: https://github.com/terminal42/contao-changelanguage/issues ;)
