### ISSUE TITLE
Registration Module: own fields in Frontend not visible

### ISSUE THREAD

**Issue by snape84** [contao/core#8637]
Hello community, 

I extended the FE registration form of contao (template: member_grouped) with my own fields and added a new FE_Group with corresponding legend. 
While all my fields I added to 'personal' 'contact' etc. are shown in the form without any problems, all fields I add to my own FEGroup are not displayed in FE. 
The output of showTemplateVars() shows all viariables of my new fields. 
Here is piece of sample code. For test purposes i hard-coded all the labels: 

```php
$GLOBALS['TL_DCA']['tl_member']['palettes']['default'] = str_replace
(
  'login;',
  'login;{exam_legend},comments;',
  $GLOBALS['TL_DCA']['tl_member']['palettes']['default']
);

$GLOBALS['TL_DCA']['tl_member']['fields']['comments'] = array
(
  'label'     => $GLOBALS['TL_LANG']['tl_member']['comments'],
  'label'     => array('comments', 'Helptext'),
  'exclude'   => true,
  'inputType' => 'text',
  'eval'      => array('feGroup'=>'exam', 'feEditable'=>true, 'feViewable'=>true, 'mandatory'=>false, 'maxlength'=>80),
  'sql'       => "varchar(80) NOT NULL default ''"
);
```

**Comment by Aybee** [comment]
Hier ist der zugehörige Thread aus dem Forum https://community.contao.org/de/showthread.php?65455-Registrierung-zus%C3%A4tzliche-Felder-im-grouped-template

Ich kann nicht alles bestätigen, und zwar war es bei meinen Tests überhaupt nicht möglich ein eigenes Feld im FE auszugeben, auch nicht wenn es zur Core-Gruppe "personal" gehörte.

Auch in den Template-Variablen von personalData war das neue Feld nicht vorhanden.

**Comment by leofeyer** [comment]
I have pasted your code above into my `dcaconfig.php` file and it worked like a charm:

<img width="674" alt="" src="https://cloud.githubusercontent.com/assets/1192057/23073028/5c87d728-f534-11e6-9517-7a6474d794c6.png">

**Comment by Aybee** [comment]
Ok, seems that it was my fault and my config was in `if(TL_MODE == 'BE')`.

The part we were missing is, that we have to create a language variable followed by `Details`
```php
$GLOBALS['TL_LANG']['tl_member']['[feGroup]Details'] = 'Exam';
$GLOBALS['TL_LANG']['tl_member']['examDetails'] = 'Exam';
```
https://github.com/contao/core/blob/master/system/modules/core/modules/ModulePersonalData.php#L385-L386
This seems to be not documented.
