### ISSUE TITLE
Simple tokens are no longer removed from templates if they don't exist.

### ISSUE THREAD

**Issue by sdamrau** [contao/core#8640]
In the past "not existing" simple tokens e.g. when using conditional forms - where replaced with an empty string (means: deleted).
Since 3.5.18 they stay in the rendered template, which can be confusing.

**example (notification center template):**
```
contact by: ##contact_by_tel_or_email##
telephone: ##telephone##
email: ##email
```

**rendered before 3.5.18:**
```
contact by: email
telephone: 
email: my@mail.com
```

**rendered since 3.5.18:**
```
contact by: email
telephone: ##telephone##
email: my@mail.com
```

Should be here: https://github.com/contao/core/blob/master/system/modules/core/library/Contao/StringUtil.php#L498

**Comment by ausi** [comment]
I think this can be fixed by using something like:

```
contact by: ##contact_by_tel_or_email##
{if telephone!=""}
telephone: ##telephone##
{endif}
{if email!=""}
email: ##email##
{endif}
```

AFAIR we keep unknown tokens on purpose, because we don’t want to remove things that just look like a token e.g. `####----SECTION-HEADLINE----####` would be removed otherwise.

**Comment by sdamrau** [comment]
der Wald und die Bäume. 

thanks ausi!
