### ISSUE TITLE
Fehler beim Ordnererstellen in der Dateiverwaltung - Contao 3.5.24

### ISSUE THREAD

**Issue by Olli** [contao/core#8642]
Ich habe eine Verzeichnis im Hauptverzeichnis angelegt. In dem Verzeichnis wollte ich ein Unterverzeichnis erstellen. Fehlermeldung ist:
```
Warning: Invalid argument supplied for foreach() in system/modules/core/widgets/MetaWizard.php on line 72

#0 system/modules/core/widgets/MetaWizard.php(72): __error(2, 'Invalid argumen...', '/www/htdocs/w00...', 72, Array)
#1 system/modules/core/library/Contao/Widget.php(804): Contao\MetaWizard->validator(NULL)
#2 system/modules/core/classes/DataContainer.php(323): Contao\Widget->validate()
#3 system/modules/core/drivers/DC_Folder.php(1210): Contao\DataContainer->row()
#4 system/modules/core/classes/Backend.php(650): Contao\DC_Folder->edit()
#5 system/modules/core/controllers/BackendMain.php(131): Contao\Backend->getBackendModule('files')
#6 contao/main.php(20): Contao\BackendMain->run()
#7 {main}
```
PHP ist Version 7.0
Hoster ist All-Inkl
PHP läuft als FPM

**Comment by Olli** [comment]
Unterverzeichnis wird aber angelegt.

**Comment by derastronaut** [comment]
Ich habe es in zwei Installationen (3.5.24), ebenfalls unter PHP 7.0 bei All-inkl, getestet und keine solche Fehlermeldung in den Logs. Kannst du es ggf. in einer anderen Installation testen?

**Comment by Olli** [comment]
Ok das passiert nur, wenn in der Seitenstruktur kein Startpunkt angelegt ist. Es ging nämlich gerade und ich habe den Startpunkt mal wieder entfernt und da passierte es wieder. Kommt also real selten vor.

**Comment by leofeyer** [comment]
Ich kann das Problem auch ohne Seitenstruktur nicht reproduzieren. Bei mir kommt dann lediglich ein Hinweis bei den Meta-Daten und keine Fehlermeldung:

<img width="744" alt="" src="https://cloud.githubusercontent.com/assets/1192057/23994459/51c04110-0a45-11e7-8cb8-efe294ff991c.png">

**Comment by Olli** [comment]
Ok ich probierte es gerade mit einer komplett neuen Install - ist nicht reproduzierbar. Sorry hätte ggf gleich mal das an einer neuen Install testen sollen.

**Comment by Olli** [comment]
Ok ich probierte es gerade mit einer komplett neuen Install - ist nicht reproduzierbar. Sorry hätte ggf gleich mal das an einer neuen Install testen sollen.
