### ISSUE TITLE
CSS Klassen und ID in Experten Einstellungen Frontendmodul "Nachrichtenliste" wird nicht ausgegeben

### ISSUE THREAD

**Issue by theDyingMountain** [contao/core#8645]
Eine CSS Klasse oder ID in den Einstellungen (siehe Bild) des Frontendmoduls zur Nachrichtenliste, wird im Frontend nicht ausgegeben.

![grafik](https://cloud.githubusercontent.com/assets/4446224/22966826/2dbdd9fa-f364-11e6-8c85-997ec440fb3f.png)

**Comment by Toflar** [comment]
Wenn du es als Inhaltselement einbindest, ist das gewünschtes Verhalten.
Du musst entsprechende Einstellung im Inhaltselement vornehmen. Erst ab Contao 4 werden die jeweiligen Klassen zusammengeführt.

**Comment by theDyingMountain** [comment]
Okay danke für die schnelle Antwort, aber wäre es dann nicht sinnvoller die Einstellung aus den Moduleinstellungen zur Nachrichtenliste für Contao 3 zu streichen? So wird dem Nutzer eine funktionslose Möglichkeit gegeben.

**Comment by Toflar** [comment]
Natürlich nicht? Wenn du das Modul im Seitenlayout einbindest, werden die Einstellungen ja übernommen?

**Comment by theDyingMountain** [comment]
Ah jetzt habe ich verstanden. Okay alles klar. Dann wäre aber zumindest ein Hinweistext hilfreich.

**Comment by fritzmg** [comment]
@theDyingMountain du könntest für Contao 3 [fritzmg/contao-mergecssclasses](https://github.com/fritzmg/contao-mergecssclasses) verwenden :)

**Comment by theDyingMountain** [comment]
@fritzmg danke für den Tipp ;)
