### ISSUE TITLE
RSS Teaser Image as media:content

### ISSUE THREAD

**Issue by pswerbung** [contao/core#8646]
Können wir nicht das Teaser Image in zukünftigen Contao Versionen als `<media:content>` Element statt als `<enclosure>` einfügen? 

Dienste wie MailChimp könnten dann die Bilder aus dem RSS-Feed lesen und ausgeben. Das wäre wohl hier zu implementieren:
https://github.com/contao/core/blob/3.5.24/system/modules/news/classes/News.php#L209-L218

Was spricht dagegen?

**Comment by fritzmg** [comment]
Reference regarding MailChimp: http://kb.mailchimp.com/merge-tags/rss-merge-tags

> ```*|RSSITEM:IMAGE|*```
> 
> __Related RSS tag:__ <media:content>
>
> __What it displays:__ In [certain feed set-ups](http://www.rssboard.org/media-rss), this tag displays the image defined in the <media:content> tag. Child elements like height, width and source URL aren't editable in MailChimp, but can be included in the RSS feed on your site.
