### ISSUE TITLE
SOAP-ERROR: Parsing WSDL: Couldn't load from 'http://contao.org/services/repository.wsdl'

### ISSUE THREAD

**Issue by greenskyes** [contao/core#8655]
Ich habe gerade eben ein Fehler beim Erweiterungskatalog bekommen: SOAP-ERROR: Parsing WSDL: Couldn't load from 'http://contao.org/services/repository.wsdl' : failed to load external entity "http://contao.org/services/repository.wsdl".
Das Problem habe ich bei mehreren Websiten mit diversen Contao-Installationen, die auf unterschiedlichen Hostern liegen: Strato, Telekom, Host Europe, 1&1. 
Ist das vorübergehend?

**Comment by fritzmg** [comment]
contao.org scheint gerade im "I Am Under Attack" Modus von CloudFlare zu sein.

**Comment by aschempp** [comment]
Ich glaube nicht dass dies an CloudFlare liegt. Die HTTP URL (ohne S(sl)) wird seit längerem nicht mehr unterstützt. Du kannst die URL in den Systemeinstellungen auf https:// ändern.

**Comment by greenskyes** [comment]
Danke für die Antworten, es schein tatsächlich ein temoräres Problem zu sein - die Erweiterungen funktionieren wieder ohne Fehlermeldung.

**Comment by fritzmg** [comment]
> Ich glaube nicht dass dies an CloudFlare liegt. Die HTTP URL (ohne S(sl)) wird seit längerem nicht mehr unterstützt. Du kannst die URL in den Systemeinstellungen auf https:// ändern.

Die http URL wird sowieso auf https redirected. Das Problem war, dass CloudFlare für jede Anfrage auf `(*.)contao.org` mit der "Checking your Browser before accessing" Seite geantwortet hat.

Siehe auch https://support.cloudflare.com/hc/en-us/articles/200170076-What-does-I-m-Under-Attack-Mode-do- (für den "I Am Under Attack" Modus von CloudFlare).
