### ISSUE TITLE
3.5.15 Mehrere kopieren in Kombination mit mehrere löschen mit den kopierten Elementen in der Zwischenablage

### ISSUE THREAD

**Issue by anjuis** [contao/core#8656]
Mehrere kopieren in Kombination mit mehrere löschen in der Folge mit den kopierten Elementen in der Zwischenablage führt zu falschen Ergebnissen beim Einfügen, bei mir wurde dann ein Element anstatt der mehreren Elemente wiederholt ungefähr in  Anzahl der mehreren kopierten Artikel eingefügt.

**Comment by anjuis** [comment]
...und löscht dann beim Ablage leeren die kopierten (!!!!) Elemente aus dem Artikel.

**Comment by Samson1964** [comment]
In Kombination ist ja nicht vorgesehen, falls Du das beabsichtigt hattest. Das widerspricht auch dem gesunden Menschenverstand.
Du meinst wahrscheinlich so etwas in der Art: Mehrere Seiten kopiert, Vorgang nicht beendet, Mehrere Nachrichten gelöscht, Vorgang beendet. Dabei werden die in der Zwischenablage kopierten Seiten gleich mitgelöscht. Oder? Nachgestellt habe ich das jetzt nicht.

**Comment by leofeyer** [comment]
Wie genau lässt sich das reproduzieren?
