### ISSUE TITLE
how to configure proxy

### ISSUE THREAD

**Issue by mmiat** [contao/core#8657]
hi
my site can't connect to repository, it says to me:

`SOAP-ERROR: Parsing WSDL: Couldn't load from 'https://contao.org/services/repository.wsdl' : failed to load external entity "https://contao.org/services/repository.wsdl"`

my provider told me that there is a proxy, so I've added these lines to my localconfig.php

$GLOBALS['TL_CONFIG']['useProxy'] = true;
$GLOBALS['TL_CONFIG']['proxy_url'] = 'http://:@proxy.provider.it:3128';

is it enough? it does still not work :(
thanks

**Comment by BugBuster1701** [comment]
You need this extension: https://github.com/BugBuster1701/contao-proxy
Of course, as a manual installation. See the readme.

**Comment by fritzmg** [comment]
Hm, why is that extension necessary, the ER already supports the proxy settings of Contao?

**Comment by BugBuster1701** [comment]
Contao proxy is for incoming connections over proxy, the extension for outgoing connections.

**Comment by fritzmg** [comment]
This is for outgoing proxy connections, is it not?
```php
// HOOK: proxy module
if (Config::get('useProxy')) {
	$proxy_uri = parse_url(Config::get('proxy_url'));
	$this->client = new SoapClient($wsdl, array(
		'soap_version' => SOAP_1_2,
		'compression' => SOAP_COMPRESSION_ACCEPT | SOAP_COMPRESSION_FIXED | 1,
		'proxy_host' => $proxy_uri['host'],
		'proxy_port' => $proxy_uri['port'],
		'proxy_login' => $proxy_uri['user'],
		'proxy_password' => $proxy_uri['pass']
	));
}
```
[/system/modules/repository/classes/RepositoryBackendModule.php#L114-L125](https://github.com/contao/core/blob/3.5.24/system/modules/repository/classes/RepositoryBackendModule.php#L114-L125)

Just trying to understand why an extension would be necessary to connect to the Extension Repository via Proxy, when Contao already provides that functionality.

**Comment by fritzmg** [comment]
@mmiat Your provider needs to make sure, that the proxy servers supports the ciphers of the SSL connection to `contao.org`. i.e., if the OpenSSL version of the proxy is too old, any connections to `contao.org` might not work.

**Comment by BugBuster1701** [comment]
Contao supports the extension "proxy". The config term "useProxy" ist only present, if the extension is installed and configured. See "HOOK: proxy module"

**Comment by fritzmg** [comment]
Yes, but if you add those lines manually to the `localconfig.php`, the proxy will already be used anyway.

**Comment by mmiat** [comment]
@BugBuster1701 I've uploaded proxy module, but there is no new option in System > Settings

**Comment by fritzmg** [comment]
@mmiat you probably haven't cleared your internal cache

**Comment by mmiat** [comment]
@fritzmg yes, thanks, this bastard cache.... ok, I see option and I've filled it, I've written 
`http://:@proxy.provider.it:3128`
but when I reload the page I see
`http://proxy.provider.it:3128`
I suppose is the same, however repository is still unavailable

**Comment by fritzmg** [comment]
As I said, your hoster needs to verify, that the proxy server itself is actually able to establish a connection via SSL to `contao.org`.

**Comment by mmiat** [comment]
upgraded php to 5.6, now I simply have error "Could not connect to host"

**Comment by leofeyer** [comment]
You can check if PHP can generally connect to contao.org with the [Contao check](https://github.com/contao/check). If a connection can be established, you should purge the WSDL cache. If not, your server administrator needs to adjust the server configuration.
