### ISSUE TITLE
[3.5.24] Exception with message Could not find template

### ISSUE THREAD

**Issue by akroii** [contao/core#8658]
```
Fatal error: Uncaught exception Exception with message Could not find template "mod_random_image_svg" thrown in system/modules/core/library/Contao/TemplateLoader.php on line 123

#0 system/modules/core/library/Contao/Controller.php(76): Contao\TemplateLoader::getPath('mod_random_imag...', 'html5')
#1 system/modules/core/library/Contao/BaseTemplate.php(81): Contao\Controller::getTemplate('mod_random_imag...', 'html5')
#2 system/modules/core/library/Contao/Template.php(277): Contao\BaseTemplate->parse()
#3 system/modules/core/classes/FrontendTemplate.php(46): Contao\Template->parse()
#4 system/modules/core/modules/Module.php(311): Contao\FrontendTemplate->parse()
#5 system/modules/core/modules/ModuleRandomImage.php(61): Contao\Module->generate()
#6 system/modules/core/library/Contao/Controller.php(321): Contao\ModuleRandomImage->generate()
#7 system/modules/core/library/Contao/InsertTags.php(447): Contao\Controller::getFrontendModule('38')
#8 system/modules/core/library/Contao/Controller.php(692): Contao\InsertTags->replace('{{insert_module...', true)
#9 templates/angebot.html5(7): Contao\Controller::replaceInsertTags('{{insert_module...')
#10 system/modules/core/library/Contao/InsertTags.php(1113): include('/Users/grafik_u...')
#11 system/modules/core/library/Contao/Controller.php(692): Contao\InsertTags->replace('...', false)
#12 system/modules/core/controllers/FrontendIndex.php(477): Contao\Controller::replaceInsertTags('...', false)
#13 system/modules/core/controllers/FrontendIndex.php(28): Contao\FrontendIndex->outputFromCache()
#14 index.php(19): Contao\FrontendIndex->__construct()
#15 {main}

```

Schritte zum reproduzieren:

1.  custom.html5 bei /template ablegen
2. Module -> 1 Zufallsbild anlegen (hat id 38)
3. in der Datei custom.html5 über <?php echo $this->replaceInsertTags('{{insert_module::38}}'); ?> das gerade angelegte Zufallsbild reinpacken.
4. in einem FE-Modul z.b. iso_reader_default.html5 über {{file::custom.html5}} rufen
5. Server Cache bei den Einstellungen setzen
6. Cache Einstellungen im Seitenbaum setzen.
7. Die Seite mit Firefox öffnen (im kalten Cache) und nach einigen Klicks in der Navigation den gerade angelegten Artikel öffnen. -> hier mehrmals versuchen, da der Fehler erst nach einigen versuchen auftritt.

**Comment by Toflar** [comment]
Das hatten wir gerade kürzlich. `{{insert_module}}` kannst du nicht mit dem Cache verwenden. Das ist eine known limitation.

**Comment by akroii** [comment]
Was ist mit `\Controller::getFrontendModule();` ?

**Comment by fritzmg** [comment]
In diesem Fall sollte es aber funktionieren, da keine Theme Informationen gebraucht werden, oder nicht? Wo befindet sich das Template `mod_random_image_svg`?

**Comment by akroii** [comment]
[contao root]/template/frontend -> mod_random_svg.html5

**Comment by fritzmg** [comment]
Es wird aber nach dem Template namens `mod_random_image_svg` verlangt, nicht `mod_random_svg` :wink:

**Comment by akroii** [comment]
Richtig, ich meinte natürlich `mod_random_image_svg.html5`

**Comment by fritzmg** [comment]
Das Problem ist der `{{file::*}}` Insert Tag und dass dein `mod_random_image_svg` Template sich in einem Theme Unterordner befindet. Der Insert Tag wird für den Cache nicht ersetzt, sondern erst wenn die Seite aus dem Cache ausgeliefert wird. Wenn eine Seite aus dem Cache geladen wird, fehlen aber viele dynamische Informationen zur Seite, wie zB zu welchem Theme sie gehört (weil ja für den Cache nichts aus der Datenbank geladen wird). Daher kann das Template nicht gefunden werden, weil es sich in einem Theme Unterordner befindet.

**Comment by fritzmg** [comment]
Einen möglichen Bug sehe ich hier aber doch. Der Grund warum der `{{file::*}}` Insert Tag _nicht_ für den Cache ersetzt wird ist ja, damit Datei Referenzen, also in der Form `{{file::UUID}}` auch aus dem Cache korrekt bleiben, selbst wenn man nachdem der Cache generiert wurde die Datei verschiebt. 

Das sollte aber vielleicht nicht unbedingt für Fälle gelten, wo man über `{{file::...}}` Templates bzw. PHP Scripte inkludiert.

**Comment by aschempp** [comment]
Wenn ich mich richtig erinnere wurde das in Contao 4 geändert.

**Comment by fritzmg** [comment]
Ah ok :). In Contao 3 könnte man es aufgrund der Rückwärtskompatibilität ohnehin nicht mehr ändern.

**Comment by fritzmg** [comment]
Just to add it here as well: even in Contao 4, `{{file::foo.php}}` or `{{file::foo.html5}}` is __not__ uncached.

If your script/template needs data that might not be available when the page is returned from the cache, you should instead integrate it the following way:

1. Prepend your script's filename with either `ce_` or `mod_`, depending on whether you need it as a content element or as a module.
2. Create a content element or module of the type `html`.
3. Fill the __HTML code__ content with an arbitrary HTML comment, like `<!-- my custom script -->`.
4. Set the __Custom module/element template__ to your script.

This way you can safely integrate your custom script without an insert tag (and thus its output is generated before the cache).

However, if you need the output within a form field default value etc. where you would otherwise use an insert tag, you are out of luck.
