### ISSUE TITLE
Laufendes wiederkehrendes Events werden nach Ablauf des Starttermins nicht mehr aufgelistet 

### ISSUE THREAD

**Issue by 31er** [contao/core#8659]
Seit dem Update von Contao 3.5.15 auf 3.5.21 habe ich ein Problem mit wiederholenden Events.

Über Events werden Termine für ein Anmeldeformular gezogen, wo der FE-User eine Terminwahl treffen muss. Das Anmeldeformular im Formulargenerator hat ein Select-Menü (DB), wo folgende Bedingung enthalten ist:
`((tl_calendar_events.pid=7) AND ((tl_calendar_events.startTime='') OR (tl_calendar_events.startTime>=UNIX_TIMESTAMP()))) && (published='1')`

Bei Events ist ein Termin mit 20 Wiederholungen angelegt. Ist der erste Termin (Starttermin) des Events noch aktuell, werden im Select-Menü des Anmeldeformulars alle Wiederholungstermine korrekt aufgelistet und sind auch selektierbar.

Seit dem Update auf 3.5.21 werden nach dem Ablaufen des ersten Termins (Starttermin) die Terminwiederholungen nicht mehr aufgelistet, das Select-Menü bleibt einfach leer. Wird das Datum des abgelaufenen Starttermins wieder auf ein zukünftiges Datum gesetzt, dann werden auch wieder die Terminwiederholungen angezeigt.

Wie gesagt, mit 3.5.15 und davor hat diese Methode ohne Probleme funktioniert. Vielleicht steht mein Problem im Zusammenhang mit diesem hier: https://github.com/contao/core/issues/8588

Ein Update auf 3.5.24 ist bereits durchgeführt und brachte auch keine Lösung. 
Gibt es evtl. einen Workaround um das Problem zu lösen?

**Comment by leofeyer** [comment]
Wie genau lässt sich das Problem reproduzieren?

**Comment by 31er** [comment]
1. Kalender anlegen.
2. Im neuen Kalender nur einen Event anlegen mit z.Bspl. 10 Wiederholungen.
3. Formular anlegen mit Feldtyp Select-Feld (DB) anlegen. Der Feldtyp Selekt-Feld (DB) ist vom EFG. Es muss also die Erweiterung EFG installiert sein. 
4. In das Optionfeld folgende Werte eintragen:
Datenbank-Feld: tl_calendar_events.title
Datenbank-Feld: tl_calendar_events.id
Bedingung: `((tl_calendar_events.pid=7) AND ((tl_calendar_events.startTime='') OR (tl_calendar_events.startTime>=UNIX_TIMESTAMP()))) && (published='1')`
Bei tl_calendar_events.pid= muss natürlich die ID des entsprechenden Kalenders eingetragen werden.

Im FE werden nun im Select-Feld des Formulars alle Termine zur Auswahl aufgelistet, so lange der erste Termin aktuell ist. Ist der erste (Haupt-)Termin abgelaufen, werden die Wiederholungen nicht  mehr ausgegeben, das Select-Menü bleibt leer.

**Comment by fritzmg** [comment]
Das ist aber normal. Die Logik für die Wiederholungen passiert ja in den Event Modulen selbst.

**Comment by 31er** [comment]
Super, danke für den Hinweis. Darauf hin habe ich eben nochmal mit dem Kunden gesprochen und er kann nicht 100% belegen, das es mal so funktioniert hat. 
Die Termine wurden zuerst einzeln angelegt und dann wurde später alles mit Wiederholungen realisiert. Erst nach dem Update auf 3.5.21 hat der Kunden einen Hinweis erhalten das keine Termine im Formular zur Auswahl stehen und somit wurde erstmal vermutet, das das Update hier etwas  "verbogen" hat.
Sorry für den Umstand und danke für die Bemühungen. Ticket kann geschlossen werden.
