### ISSUE TITLE
Resized Bilder und SEO

### ISSUE THREAD

**Issue by bekanntmacher** [contao/core#8664]
Hallo zusammen

Für die Suchmaschinenoptimierung ist es also Gift wenn der Bildpfad und/oder der Dateiname einer Datei ändert. Denn bei Änderungen verschwinden zum Beispiel die Bilder im Nirwana. Das mühsam erkämpfte Ranking ist Flöte und das kann sehr frustrieren sein.

Beim Contao (https://github.com/contao/core/blob/master/system/modules/core/library/Contao/Image.php#L371) ändert der Dateiname von resized Bildern aber schon bei der Änderung des Zeitstempels. 

Könnte man dies technisch nicht irgendwie anders lösen?

**Comment by leofeyer** [comment]
Das Google hauseigene Pagespeed-Modul macht noch ganz andere Sachen, wie z.B.

```
video1-f1fab542.jpg.pagespeed.ic.JphVq1g9lu.webp
```

aus einer Datei, die ursprünglich `video1.mp4` hieß. Wenn das so dramatisch für das Ranking wäre, meinst Du nicht, dass Google das dann auch anders gelöst hätte?

**Comment by KaiserCh** [comment]
Ranking gibt es nach meinen Erfahrungen vornehmlich für Textcontent. Grafiken, genau wie Audio & Video, sind ohne zusätzliche textbasierte Metadaten (z.B. JSON-LD) eh kein wirklich indizierbarer Content.

Wo die Änderung des Pfades wirklich Einfluss hat sind OpenGraph - Metatags. Facebook kann ein wenig aus dem Tritt kommen, wenn das OG-Meta-Image eines vor längerer Zeit geteilten Objektes nicht mehr existiert. 

Außerdem: Wann ändert sich der Timestamp (oder genauer: die mtime) einer Grafik? Doch in der Regel dann, wenn die Datei verändert wurde. In dem Fall ist es absolut korrekt, wenn Google den Kram "vergisst". Ansonsten ändert sich die mtime, wenn man z.B. Backups einspielt oder Befehle wie "touch" verwendet. Sollte sehr selten passieren.

**Comment by bekanntmacher** [comment]
Leo, wenn du ein Bild so im Suchergebnis hast (siehe Anhang), geniesst du ziemlich schön Traffic. Da der Pfad/Dateiname die Referenz im Google-DB ist, verschwindet das Bild sehr schnell wenn er ändert. 

![carport](https://cloud.githubusercontent.com/assets/1622464/23921360/af7bc844-08fe-11e7-9551-23b552fbd787.png)

**Comment by leofeyer** [comment]
@bekanntmacher Das ist keine Antwort auf meine Frage.

**Comment by bekanntmacher** [comment]
@leofeyer ja, kommt nicht so klar raus. Indirekt wollte ich zeigen/aussagen, dass es nicht relevant ist. Zu deiner Frage: nein, meine ich nicht.
