### ISSUE TITLE
Buchnavigation hängt sich bei Newsdetailansicht auf

### ISSUE THREAD

**Issue by Olli** [contao/core#8665]
Genutzt wird ein  Contao 3.5.24 mit PHP Version 7.0
Ich habe eine Buchnavigation eingebaut, Referenz ist der Startpunkt.
Wenn ich mir eine News in der Detailansicht anzeigen lassen möchte, wird der PHP Prozess nach 30 Sekunden beendet mit folgender Meldung
` Fatal error: Maximum execution time of 30 seconds exceeded in /www/htdocs/***/projekte/**/system/modules/core/modules/ModuleBooknav.php on line 157`

**Comment by backbone87** [comment]
Das muss nicht zwangsläufig an der buchnavigation liegen. Die Fehlermeldung sagt nur aus, dass der request nach 30s abgebrochen wurde und zu diesem Zeitpunkt die buchnavi generiert wurde.

**Comment by fritzmg** [comment]
An der Stelle in `ModuleBooknav.php` befindet sich diese Schleife:
```php
// Skip forward pages (see #5074)
while ($this->arrPages[$intKey]->type == 'forward' && isset($arrLookup[++$current]))
{
	$intKey = $arrLookup[($current + 1)];
}
```
Auf den ersten Blick erkenne ich dort aber keine Möglichkeit, dass es dort zu einer Endlosschleife kommen könnte.

**Comment by discordier** [comment]
Es sei denn man hat irgendwie einen zirkulaeren Bezug in der DB gebaut, aber da hab ich auch keine Ahnung wie das gehen sollte.

**Comment by Olli** [comment]
Ok ein Nachtrag - es tritt nicht nur bei der Newsseite auf sondern auch noch bei einer normalen Seite. 
Ich habe mal die Schleife auskommentiert - es wird nur eine Forward Seite angezeigt. Die Up und Prev Seite ist leer.

**Comment by Olli** [comment]
Login in das System wäre möglich falls notwendig

**Comment by Olli** [comment]
Noch ein Nachtrag - so sieht die Struktur aus 
http://imgur.com/a/q6kwD
Aktuell hängt es z.B wenn man auf "Demo Unterpunkt" geht.

**Comment by fritzmg** [comment]
> Noch ein Nachtrag - so sieht die Struktur aus
> http://imgur.com/a/q6kwD

Das scheint aber kein Screenshot der gesamten Struktur zu sein ;).

Lässt sich der Fehler evt. in der Contao Demo reproduzieren?

**Comment by Olli** [comment]
Ja oberhalb von Demo ist der Starpunkt. Ich muss mal schauen ob ich das morgen in meiner Demo reproduzieren kann ... wenn ich es nicht vergesse.

**Comment by fritzmg** [comment]
Ich meinte auf demo.contao.org

**Comment by fritzmg** [comment]
Welche Referenzseite ist im Modul eingestellt? Oder gar keine?

**Comment by Olli** [comment]
Der Startpunkt ... demo.contao.org kenne ich gar nicht - muss ich mal schauen.

**Comment by Olli** [comment]
demo.contao.org ist ja eine 4.2er ... das nutzt mir nix in der 3.5.24er.

**Comment by Olli** [comment]
wer den Quelltext vor der Nase hat:
$current ist bei mir false
denn array_search($objPage->id, $arrLookup) findet die ID nicht. 
Deswegen wird die Schleife vermutl. auch endlos laufen.

**Comment by Olli** [comment]
So und nun kommen wir zu des Pudels Kern: Wie man meinem Screener entnehmen kann ist "Demo" in der Navigation nicht sichtbar aka versteckt. Ich habe aber in der Buchnavi angehakt, dass versteckte Seiten nicht angezeigt werden sollen. 
Mache ich einen Haken bei "Versteckte Seiten anzeigen" funktioniert die die Buchnavi.

**Comment by Olli** [comment]
Ich kann es auf demo.contao.org nicht nachstellen.

**Comment by leofeyer** [comment]
Wir sollten den Fall `$intCurrent === false` eventuell abfangen.

**Comment by leofeyer** [comment]
Ich kann es jedoch bei mir auch nicht reproduzieren.

**Comment by Olli** [comment]
Ok ich konnte es tatsächlich reproduzieren. 
Ich hatte was vergessen - eine bzw mehrere Umleitungen (Asche auf mein Haupt @fritzmg ). Ich habe es noch mal mit einer frischen Install getestet - da tritt der Fehler beim Aufruf von "1. unterpunkt" auf.

http://imgur.com/a/6yhv8

**Comment by discordier** [comment]
@leofeyer den false Fall myssen wir also wirklich abfangen oder aber die forwards hier direkt aufloesen. Letzteres geht vermutlich nur rudimentaer, da ja eigene Page types moeglich waeren, welche dann hier nicht behandelt werden wyrden.

**Comment by Olli** [comment]
@leofeyer  hat sich in dem Issue noch mal was ergeben? In der History sehe ich nichts und da das Issue auch "invalid" ist befürchte ich, dass das jetzt übersehen wird.

**Comment by leofeyer** [comment]
Keine Sorge.

**Comment by Olli** [comment]
Ein weiterer Fall wo die Booknav spinnt ist wenn kein Haken bei "Geschützte Seiten anzeigen" gesetzt ist aber eine geschützte Seite in der Ebene liegt.

**Comment by leofeyer** [comment]
@Olli Kannst Du mir nochmal erklären, wie ich das Problem reproduziere? Auf welche Seite leitet die Seite "demoweiterleitung" weiter?

**Comment by Olli** [comment]
Die leitet auf die Seite 'demo' weiter.

**Comment by leofeyer** [comment]
Ich kann das Problem jetzt reproduzieren:

<img width="489" alt="" src="https://cloud.githubusercontent.com/assets/1192057/25168039/4f307d36-24e2-11e7-9166-d7042319e68f.png">

Allerdings verstehe ich nicht, wie Du die Seite "1. Unterpunkt" bzw. bei mir "Link elements" überhaupt aufrufen konntest, da die Seite bei mir weder in der Haupt- noch in der Buchnavigation angezeigt wird:

<img width="341" alt="" src="https://cloud.githubusercontent.com/assets/1192057/25168085/81150114-24e2-11e7-9d67-1a47702ebe9c.png">

Hast Du die URL manuell in die Adresszeile des Browsers eingetippt?

**Comment by Olli** [comment]
Na klar manuell eingetippt. Sowas kann ja auch über irgend eine Individuelle Nav aufgerufen werden oder der Besucher kommt über die Suchmaschine auf so eine Unterseite.

**Comment by leofeyer** [comment]
Behoben in 26059a9903093ceac0eb8123ee502a46fd1b2183.
