### ISSUE TITLE
CE Audio/Video more than one file ?

### ISSUE THREAD

**Issue by garyee** [contao/core#8667]
Hi,

I do not know if this is a bug or if it's intended behaviour.
In the backend one can choose multiple files for the media content element, but only the first one (of an extension(type) will be passed to the frontend(template $this->files) 

In my opinion it would be good if all files would be passed on, to let the user decide what to do with it (with a custom template for example).

The 'error'/reason is in the [ContentMedia Class on Line 152](https://github.com/contao/core/blob/master/system/modules/core/elements/ContentMedia.php#L152)

**Comment by fritzmg** [comment]
The purpose of being able to select multiple files is so that you can provide the `<video>` or `<audio>` element with multiple formats of the same video or audio file. As you can see `$this->files` will be an array containing those multiple formats (indexed by the file extensions).

**Comment by garyee** [comment]
$this->files is an array with the first chosen element of each format. I see the meaning for web-video but not so for audio. Why not leave the choice to the user, if she/he needs multiple files of different formats or multiple files of one format?

My use-case is a website for a company that develops audio-software and so the site is very audio heavy, and audio-playlists are needed on many sub pages. So I just included the mediaelement playlist js, styled the element a bit and wondered why only the first element got displayed.

**Comment by fritzmg** [comment]
> I see the meaning for web-video but not so for audio.

It's exactly the same reason. The purpose of being able to select multiple files for the "Video" or "Audio" element is to provide different formats for __one__ video or audio file.

This should also be evident to you by looking at the `ce_player` template: https://github.com/contao/core/blob/master/system/modules/core/templates/elements/ce_player.html5
It creates exactly __one__ `<video>` or `<audio>` element with _multiple sources_. Browsers will then only play _one_ of these sources - the first one in the list of sources that it can play (at least Firefox and Safari handle it this way).

If you want to create multiple `<video>` or `<audio>` elements for each selected file in your `ce_player` template, you can still do that by using `$this->multiSRC` and `\FilesModel::findByUuid(…)`.

**Comment by garyee** [comment]
I just read the specifications and you are right. So it is kind of tweaking what I'am doing, but with the mediaelment js it is very easy :) ... I will just use $this->PlayerSrc. Thanks for the tip and the quick answer.
