### ISSUE TITLE
imageUrl field removes colon from http:// when insert tag is present

### ISSUE THREAD

**Issue by fritzmg** [contao/core#8668]
## Reproduction

1. Create an image content element.
2. Select an image.
3. Insert `http://{{env::host}}` into the `imageUrl` field.
4. Save.

After saving, the `imageUrl` field will contain
```
http//{{env::host}}
```
instead of
```
http://{{env::host}}
```
If you insert a real URL like `http://www.google.at`, the colon remains. It only seems to happen if an insert tag is present.

Of course you don't really have to use `http://{{env::host}}` in general, you can simply use `{{env::url}}` instead - but that is beside the point.

## Tested Contao Versions

Contao 3.5.24
Contao 4.3.5 (demo.contao.org)

**Comment by leofeyer** [comment]
This is due to the PHP `parse_url()` function parsing `http://{{env::host}}` as:

```
Array
(
    [host] => http
    [path] => //{{env::host}}
)
```

However, the following would be correct:

```
Array
(
    [scheme] => http
    [host] => {{env::host}}
)
```

But since we cannot teach PHP to handle Contao insert tags and since there is a working alternative (namely using `{{env::url}}`), I consider this a known limitation.

**Comment by Toflar** [comment]
This happens in `Idna::encodeUrl()`, right? There already seems to be some special handling related to insert tags (see https://github.com/contao/core/blob/master/system/modules/core/library/Contao/Idna.php#L144) so maybe we can just add yet another check @fritzmg?

**Comment by fritzmg** [comment]
Hm, not sure how it should be done. It only occurs when you do the following:

* `http://{{foo::moo}}`
* `http://foo.org{{foo::moo}}`

It does __not__ occurr when you do the following for instance:

* `http://foo.org/?host={{env::host}}`
* `http://foo.org/{{foo::moo}}`

**Comment by leofeyer** [comment]
Of course we could make it work, but I don't think it is worth the effort. Using `{{env::url}}` is a working and perfectly fine alternative.
