### ISSUE TITLE
Input fields often non clickable due to .widget position: relative

### ISSUE THREAD

**Issue by filipbasara** [contao/core#8669]
I noticed that some input fields in extensions can not be clicked (as in there is something overlaying it) if `.widget` in `basic.css` has the CSS property of `position: relative`.
Disabling `position: relative` fixes that issue.

**Comment by leofeyer** [comment]
How exactly do I reproduce this? And does the issue occur in all browsers?

**Comment by wugu** [comment]
I could reproduce the problem width Firefox 52 and Chrome 57.

The setting of "tl_class" with the parameter "wizard" in the configuration of your "custom_elements" or your own extension will get the css-class "widget" in the backend of contao. The css-class "widget" will set the style "position: relative" and you can't use most of input-fields in the same container.

My snippet that fired the class "wizard" looks like that:

``````
'eval' => array(
     'rgxp' => 'datim',
     'datepicker' => true,
     'tl_class' => 'wizard',
      ),
),
```````
The quick and dirty reason is to enhance the backend-css with your own css-file which contents the style:
```
.widget {
     position:static !important;
}
```

So you can expand the backend-css:
https://community.contao.org/de/showthread.php?59351-Darstellung-der-Inhaltselemente-im-Backend-anpassen&p=386546&viewfull=1#post386546

**Comment by leofeyer** [comment]
Does the issue occur in the [online demo](http://demo.contao.org/contao), too?

**Comment by Aybee** [comment]
Don't know how to reproduce this issue but the selector `.widget` only exists in Contao 4 in flexible Theme.

The question ist:  Why is it set to relative? Was it neccessary in a special situation?

**Comment by leofeyer** [comment]
The only demo uses Contao 4, so how do I reproduce it there?

**Comment by fritzmg** [comment]
As far as I experienced it this happens with a certain combination of widgets that are floating (i.e. with a class of `w50`). If I encounter it again, I'll post a clear reproduction.

**Comment by asaage** [comment]
I experienced it when i use `w50` and forget to add a `clr` class in the next row of input's.

**Comment by fritzmg** [comment]
Me too I think. Though it should not be required to add `clr` in the next row, should it? Because if an extension adds a widget in an arbitrary place in the palette, you won't know what widget is in the "next row".
