### ISSUE TITLE
rename folder in Contao backend causes warning

### ISSUE THREAD

**Issue by fiedsch** [contao/core#8674]
A missing `preg_quote($strSource, '@')` in `Dbafs::moveResource()`
https://github.com/contao/core/blob/master/system/modules/core/library/Contao/Dbafs.php#L261
causes a warning like
```
Warning: preg_replace(): Unknown modifier 'f' in system/modules/core/library/Contao/Dbafs.php on line 261
```
when a folder with an @ in its name is copied. 

How to recreate: (can't recreate in the online demo due to missing access rights in the file manager)

* Create a folder `some@foo`
* Click the + icon to copy the folder
* Click 'insert' to produce the warning (showing "Ein Fehler ist aufgetreten!" in the backend) 

Applies to Contao 3 and Contao 4

**Comment by leofeyer** [comment]
Fixed in 5fa4427b897024cce02374eecdef66e1eea788cf.
