### ISSUE TITLE
TinyMCE: Ordered List zeigt nur Zahlen an, keine Buchstaben

### ISSUE THREAD

**Issue by Russe** [contao/core#8676]
Im Backend wird im TinyMCE bei einer Ordered List nur das normale Zahlensystem mit 1, 2, 3 usw. angezeigt. Wenn man im HTML-Code einen type für Buchstaben festlegt wird dann in der Ansicht nach wie vor als Aufzählungszeichen 1, 2, 3 usw. angezeigt statt a, b, c

1. Im Backend einen Artikel mit einem Textelement anlegen.
2. Im TinyMCE folgenden Quellcode eingeben.
`<ol>`
`<ol type="a">`
`<li>Eins</li>`
`<li>Zwei</li>`
`<li>Drei</li>`
`</ol>`
3. Dann mit OK bestätigen.

Im Frontend werden die gewünschten Buchstaben als Aufzählungszeichen angezeigt.

Das Verhalten ist in der Onlinedemo nachvollziehbar.

https://wiki.selfhtml.org/wiki/Referenz:HTML/Attribute/type_(ol)

**Comment by aschempp** [comment]
das hört sich für mich nach einem TinyMCE Bug an, und nicht Contao?

**Comment by NinaG** [comment]
Das liegt am tinyMCE selbst, ich kenne das Problem. Bei mir hat geholfen:
In die tinymce.css das hier einfügen:
ol > li {
    list-style: inherit;
}

**Comment by NinaG** [comment]
Es liegt an dieser Anweisung aus der /assets/tinymce4/skins/contao/content.min.css

ol > li {
    list-style: outside none decimal;
}

**Comment by Russe** [comment]
Ich habe das einmal bei mir so angepasst, leider werden da aber immer noch Zahlen angezeigt.
Cache von Contao und Browser hatte ich geleert.

Es gibt aber noch eine andere CSS-Datei, bei der funktioniert es:
/system/themes/tinymce.css

Vielen Dank für den Tipp.
Was allerdings blöd ist, die geänderte Datei wird mir nun vom System Check als beschädigt gemeldet. Könnte das in einer der nächsten Contao-Versionen angepasst werden, dass hier auch Buchstaben angezeigt werden? Oder spricht da etwas dagegen?

**Comment by NinaG** [comment]
Ich konnte die Anweisung normal in der tinymce.css aus der Dateiverwaltung einfügen. Nach dem Leeren des Caches (Backend/Browser) funktionierte es. Das ist der bevorzugte Weg, weil es updatesicher ist.

**Comment by NinaG** [comment]
Falls du von der Contao 4.3 sprichst, ist hier eine Anleitung wie du das mit der tinymce.css updatesicher hinbekommst (ist jetzt etwas anders als unter C3):
https://community.contao.org/de/showthread.php?66248-tinymce-css-in-Contao4&p=436465#post436465

**Comment by leofeyer** [comment]
Geändert in e4043866d552bdd785585899eb44d522803a6b3f.
