### ISSUE TITLE
Backport performance improvements of StringUtil::encodeEmail

### ISSUE THREAD

**Issue by ausi** [contao/core#8679]
I think we should backport https://github.com/contao/core-bundle/commit/4d26b211113df7b89c21db13a98a6870357b35d9 to fix the performance issues in Contao 3.5 too.

If we don’t want to backport the whole new email-handling, i think it is enough to replace the `*`s in [StringUtil.php:305](https://github.com/contao/core/blob/31f43d9ddaf363bf381e39e525bcdf7b7f1811c2/system/modules/core/library/Contao/StringUtil.php#L305) with `{1,64}` and `{1,252}`.

The performance issue itself can be reproduced by executing `\StringUtil::encodeEmail(str_repeat('x', 100 * 1024));`;

**Comment by leofeyer** [comment]
Back ported in 682ab5110a4e72a5d4a88741f7a7d8a3089d4553.

**Comment by ausi** [comment]
I think I made a mistake, it should be `{0,64}` and `{0,252}`, otherwise `ab@a.xx` only matches as `b@a.xx`

**Comment by leofeyer** [comment]
Fixed in 4cfdfb4f540afe7e3b8358eb3de3a5969cb51097.
