### ISSUE TITLE
Switch display order (label/input) in mod_comment_form.html5

### ISSUE THREAD

**Issue by markocupic** [contao/core#8680]
Why do we display the input form field in front of the label in mod_comment_form.html5?

```php
<div class="widget">
<?= $this->fields['name']->generateWithError() ?>
<?= $this->fields['name']->generateLabel() ?>
</div>
```

This behaviour is a bit inconsistent. Because f.ex. in form_textfield.html5 the display order is quite contrary:

`<label>Some label</label>
<input type="text" name="bla" value="" class="text">`

The input field follows the label.

**Comment by leofeyer** [comment]
We have changed this in Contao 4. (Also see #6602).

**Comment by markocupic** [comment]
Ok. Thx.
