### ISSUE TITLE
Bildgröße im Backend bei svg reduzieren

### ISSUE THREAD

**Issue by stefan-at-work** [contao/core#8684]
Bei der Nutzung z.B. des CE-Text in Zusammenhang mit einem auswählten Bild im svg-Format, wird das svg aufgrund der fehlenden Bildmaße im Backend in voller Breite dargestellt. Dies nimmt bei mehreren untereinander platzierten CE sehr viel Platz in Anspruch.

Schön wäre es, hier die Bildgrößen im BE automatisch zu verkleinern.

**Comment by leofeyer** [comment]
@ausi /cc

**Comment by ausi** [comment]
@stefan-at-work Lässt sich das Problem mit folgender Änderung in der *Controller.php*-Datei lösen?

```diff
- if ($size[0] > $intMaxWidth || (!$size[0] && !$size[1] && $imgSize[0] > $intMaxWidth))
+ if ($size[0] > $intMaxWidth || (!$size[0] && !$size[1] && ($imgSize[0] > $intMaxWidth || !$imgSize[0])))
  {
      // See #2268 (thanks to Thyon)
-     $ratio = ($size[0] && $size[1]) ? $size[1] / $size[0] : $imgSize[1] / $imgSize[0];
+     $ratio = ($size[0] && $size[1]) ? $size[1] / $size[0] : ($imgSize[0] ? $imgSize[1] / $imgSize[0] : 0);
```

**Comment by stefan-at-work** [comment]
@ausi - thx it works

**Comment by leofeyer** [comment]
@ausi Ist `($imgSize[0] > $intMaxWidth || !$imgSize[0])` dasselbe wie `(empty($imgSize[0]) || $imgSize[0] > $intMaxWidth)`?

Die zweite Änderung kann ich nicht nachvollziehen. Bei mir lautet die Zeile wie folgt:

```
$ratio = ($size[0] && $size[1]) ? $size[1] / $size[0] : (($imgSize[0] && $imgSize[1]) ? $imgSize[1] / $imgSize[0] : 0);
```

Aus welcher Version ist Dein Code?

**Comment by ausi** [comment]
> Ist `($imgSize[0] > $intMaxWidth || !$imgSize[0])` dasselbe wie `(empty($imgSize[0]) || $imgSize[0] > $intMaxWidth)`?

Ja, ist das selbe IMO.

> Die zweite Änderung kann ich nicht nachvollziehen.

Ich denke die wurde schon in #8653 korrigiert, die Änderung an der `if`-Abfrage sollte somit ausreichen.

**Comment by leofeyer** [comment]
Behoben in 704a749a2f56d7899ec895b9ef5a01935915ab06.
