### ISSUE TITLE
3.5 - Formulardaten speichern - Spaltenname mit Trennstrich/Bindestrich - Fehler 

### ISSUE THREAD

**Issue by michapietsch** [contao/core#8685]
Hallo,

gerade beobachtet:

Speichern von Formulardaten erzeugt einen Fehler, wenn ein Spaltenname einen Trennstrich/Bindestrich enthält, z. B. "E-Mail".

AFAIK sind Trennstriche/Bindestriche zulässig, zumindest in MySQL.

Mögliche Lösung: Spaltennamen im Insert-Statement in Backticks.

LG Micha

**Comment by fiedsch** [comment]
> AFAIK sind Trennstriche/Bindestriche zulässig, zumindest in MySQL.

Nein. MySQL "sieht" bei `e-mail` `e` minus `mail`

**Comment by aschempp** [comment]
> Mögliche Lösung: Spaltennamen im Insert-Statement in Backticks.

Bessere Lösung: deine Felder entsprechend benennen 😁

**Comment by michapietsch** [comment]
@aschempp Das wissen wir, aber nicht jeder. Warum nicht Robustheit über Konvention setzen?

@fiedsch Wie wirkt sich das praktisch aus?

**Comment by michapietsch** [comment]
PS: @aschempp Ich hab das schon so gemacht, bin selbst nicht mehr betroffen. ;)

**Comment by leofeyer** [comment]
> Warum nicht Robustheit über Konvention setzen?

Es geht bei der Datenbank-Klasse aus dem Contao 3-Framework nicht um Konvention, sondern um Kompatibilität. Die Datenbank-Klasse hat früher auch noch andere DB-Systeme wie PostgreSQL oder Oracle unterstützt und daher auf die MySQL-spezifischen Backticks bei den Feldnamen verzichtet.

Ob das gut oder schlecht ist, spielt jetzt eigentlich keine Rolle mehr, da wir in Zukunft auf Doctrine setzen und daher nicht das Contao 3-Framework umbauen werden.

**Comment by michapietsch** [comment]
@leofeyer Danke für die ausführliche Antwort! So fühlt man sich ermutigt, mal wieder Issues zu melden 👍
