### ISSUE TITLE
showTemplateVars zeigt viel zu viel (ganze Composer-Struktur der gesamten Installation + Serverdaten?)

### ISSUE THREAD

**Issue by NinaG** [contao/core#8686]
Wenn ich unter Contao 4.3 z.B. in einem Event-Listen-Template die showTemplateVars-Anweisung reinschreibe, erwarte ich eigentlich, dass Contao mir zur Event-Liste die Variablen ausgibt. Tatsächlich geschieht aber viel mehr. Scheinbar gibt Contao dann die komplette Struktur des ganzen Composers und noch extrem viele Serverinfos aus. Die meisten Browser stürzen dabei gleich völlig ab, aber mit Chrome konnte ich das mal mehrere Minuten laufen lassen, bevor ich abgebrochen habe. Zu dem Zeitpunkt hatte ich dann schon eine riesige Ausgabe (obwohl nur 1 Event im Modul ist) die definitiv Zeug enthält, das so niemals über diese Anweisung ausgegeben werden dürfte.

In der Form ist die Anweisung völlig unbrauchbar geworden. Da läuft irgendwas schief. Bitte prüft das.

Getestet auf: Contao 4.3 (frische Installation, keine Extensions installiert) beim Hoster All-Inkl; habe das memory_limit auf 2048M gestellt, damit es wenigstens im Chrome überhaupt zeitweise ausgegeben wurde (in den anderen Browsern stürzte es immer ab).

Siehe auch:
https://community.contao.org/de/showthread.php?66237-showTemplateVars-zeigt-viel-zu-viel-(ganze-Composer-Struktur-der-gesamten-Installatio

**Comment by Toflar** [comment]
Ist mir auch schon aufgefallen. Also der Dump war auch schon in der 3.5 mehrheitlich unbrauchbar.
`showTemplateVars()` solltest du sowieso nicht mehr nutzen, `dumpTemplateVars()` wäre besser. Aber auch dann ist der Stack zu gross. 

@contao/developers Ich denke wir sollten `showTemplateVars()` auf `dumpTemplateVars()` mappen und da nicht `dump()` nutzen, sondern die `VarDumper` Komponente direkt und das `Data` Objekt via eines eigenen Handlers auf max 2 Levels (konfigurierbar) reduzieren. Kann ich mir anschauen.

**Comment by NinaG** [comment]
dumpTemplateVars macht auch Ärger, siehe #8687

**Comment by Toflar** [comment]
> Daher wäre ich sehr dankbar, wenn das schnell gefixt wird.

Es dürfte einen Moment dauern, weil die Debug-Tools nur im `dev`-Environment zur Verfügung stehen und den notwendigen Entry-Point dafür generiert das `manager-bundle` zurzeit noch nicht. Siehe https://github.com/contao/manager-bundle/issues/23.

**Comment by NinaG** [comment]
Das ist ein echtes Problem, denn wie soll ich dann in der Zwischenzeit die benötigten Variablen herausfinden? Ich brauche das bei echten Projekten ständig, weil ich häufig Templates individualisiere. Eigentlich hatte ich sehr gehofft, dass ich mit Contao 4.3 nun endlich produktiv arbeiten kann. Über Tipps wie ich die Zeit überbrücken kann (ohne C4.3 doch vorübergehend aufzugeben) wäre ich dankbar.

**Comment by aschempp** [comment]
Mit showTemplateVars() ?

**Comment by NinaG** [comment]
Das kann ich ja offensichtlich nicht nutzen, weil alles abstürzt bzw. ich das memory unendlich hochdrehen muss um nach ner Minute überhaupt erste Ergebnisse sehen zu können. Abgesehen davon, dass das sehr frustrierend ist, wir mir irgendwann auch der Webhoster auf die Schulter ticken und mich fragen, was ich da mache ...

**Comment by ausi** [comment]
@NinaG eventuell kannst du dir mit `<?php var_dump(array_keys($this->arrData)); ?>` behelfen, damit solltest du eine Liste mit allen variablen bekommen die in dem Template zur Verfügung stehen. Mit `<?php var_dump($this->VARIABLENNAME); ?>` kannst du dir dann einzelne Variablen ansehen.

**Comment by NinaG** [comment]
Danke, das ist eine Notlösung mit der ich arbeiten kann. Umständlich, aber es belastet den Server nicht so und ich komme an die Infos ran. 👍

**Comment by discordier** [comment]
@NinaG kannst du mal folgenden patch bei dir testen?
```diff
--- src/Resources/contao/library/Contao/System.php
+++ src/Resources/contao/library/Contao/System.php
@@ -156,8 +156,9 @@
 			if (!class_exists($strClass) && $container->has($strClass))
 			{
 				$this->arrObjects[$strKey] = $container->get($strClass);
+				return;
 			}
-			elseif (in_array('getInstance', get_class_methods($strClass)))
+			if (in_array('getInstance', get_class_methods($strClass)))
 			{
 				$this->arrObjects[$strKey] = call_user_func(array($strClass, 'getInstance'));
 			}
@@ -165,6 +166,11 @@
 			{
 				$this->arrObjects[$strKey] = new $strClass();
 			}
+			// Add caster for the real class to debug dumper.
+			if ($container->has('var_dumper.cloner'))
+			{
+				$container->get('var_dumper.cloner')->addCasters([get_class($this->arrObjects[$strKey]) => 'Symfony\Component\VarDumper\Caster\StubCaster::cutInternals']);
+			}
 		}
 	}
```

**Comment by leofeyer** [comment]
Danke @Toflar.

**Comment by Aybee** [comment]
So far you also can dump to a logfile.
```php
log_message(print_r($this->arrData, true), 'my-logfile.log');
```
You also should use the smart dump() function instead of var_dump(). It uses print_r() on arrays and var_dump() on strings.
```php
dump($this->VARIABLENNAME);
```

**Comment by Toflar** [comment]
Not true for Contao 4. It uses the `VarDumper` component and it dumps a lot more because the stack is a lot bigger. I'll take care, just use the workaround provided by @ausi in the meantime.

**Comment by Aybee** [comment]
That means there is no dump() and log_message() in C4 anymore?

**Comment by aschempp** [comment]
log_message() still exists afaik, but dump() only exists in dev mode.

**Comment by NinaG** [comment]
@discordier Ich habe das eingefügt, aber bei showTemplateVars bestehen immer noch dieselben Probleme.

**Comment by discordier** [comment]
Dann waere interessant zu wissen, welche Klassen denn da noch mit ausgegeben werden. Bei mir wurden da dann alle sauber abgeschnitten.

**Comment by Toflar** [comment]
`var_dumper.cloner` existiert nicht ohne das `DebugBundle`. Logisch passiert nichts. Wie gesagt, wir brauchen

* a) den `app_dev.php` entry point in der ME (kann ich leider nicht helfen)
* b) besseres Handling in der Template-Klasse (mach ich am WE)

**Comment by Toflar** [comment]
@leofeyer kann man dieses Ticket zum core-bundle verschieben? Das ist hier falsch.

**Comment by Toflar** [comment]
War viel einfacher als gedacht. Braucht keine Anpassungen am `manager-bundle`. Kannst die Änderungen schon mal bei dir lokal übernehmen und testen und dann ein Loblied auf Symfony singen 😄  https://github.com/contao/core-bundle/pull/750

**Comment by discordier** [comment]
Und so werden die Klassen nicht rekursiv gedumped?
In deinem Screenshot sieht man leider kein model in arrData, deshalb die Frage.

**Comment by fritzmg** [comment]
Ich glaube das ursprüngliche Problem war die Referenz auf das Modul selbst über die Funktionen `details` und `hasDetails`. Mit dem VarDumper wird nur mehr ausgegeben, dass es eine Referenz gibt und wie oft diese vorkommt - das Modul selbst wird aber nicht gedumped (glaube ich):

![dumper](https://cloud.githubusercontent.com/assets/4970961/24598844/de013614-184d-11e7-8dac-f158bf54b1bf.png)

Über das PageModel werden scheinbar nicht rekursiv Models gedumped:

![dumper2](https://cloud.githubusercontent.com/assets/4970961/24598858/eb456160-184d-11e7-8c83-65e66b189340.png)

**Comment by Toflar** [comment]
Alles korrekt 😄

**Comment by fritzmg** [comment]
Haben eigentlich die Nummern bei den Objekten (`#312`, …) irgendeine Bedeutung?

**Comment by Toflar** [comment]
Jop. Die stehen für den "internal object handle". Damit vergleicht die Komponente zwei (oder mehr) aufeinanderfolgende Dumps des gleichen Objekts.

**Comment by leofeyer** [comment]
Siehe contao/core-bundle#750.
