### ISSUE TITLE
Kein Entfernen von Sonderzeichen in Dateiverwaltung mehr?

### ISSUE THREAD

**Issue by NinaG** [contao/core#8688]
Unter C3 war es imho so, dass Contao beim Anlegen von Ordnern oder Dateien darauf geachtet hat, dass keine Sonderzeichen und Umlaute im Ordner-/Dateinamen waren. Falls der Redakteur das so angelegt hat, hat Contao es dann eigenständig geändert (Sonderzeichen bis auf - und _ entfernt, Umlaute auf ue, oe, ae und ß auf ss umgeschrieben etc.).

In Contao 4.3 scheint dieser Sicherheitsmechanismus weg zu sein. Abgesehen von den offensichtlichen Problemen, führt es auch zu neuen Fehlern. Ich habe aus Müdigkeit z.B. irrtümlich eine Datei namens **Spielen, Sport & Natur** (JPG) angelegt. Contao lässt es zu, dass die Datei gespeichert wird. Wenn der Nutzer nun aber versucht, diese Datei zu kopieren, schmeißt Contao diesen Fehler:

_Forbidden: 
File or folder "files/freizeit-tourismus/uebersicht/Spielen, Sport " is not mounted or cannot be found._

Ruft man danach das Backend nochmal frisch auf, ist die kopierte Datei Spielen, Sport & Natur_1.jpg da. Aber es würde damit wohl noch diverse Folgefehler geben, wie die Fehlermeldung suggeriert.

Ich halte es für extrem wichtig, dass die automatische Fehlerkorrektur bei Ordner- und Dateinamen wieder vollumfänglich integriert wird. Meine regelmäßige Arbeit mit Redakteuren/Anwendern zeigt, dass sie sehr sehr wichtig ist. Insbesondere unerfahrene Anwender arbeiten häufig mit schrecklichen Datei-/Ordnernamen, aber wie man sehen kann, macht selbst ein erfahrener Profi vor Müdigkeit solche Fehler ;)

**Comment by NinaG** [comment]
Kleine Ergänzung: Es scheint so, dass Umlaute jetzt nur noch einfach umgeschrieben werden, als z.B. **ü** zu **u** statt bisher **ü** zu **ue**.

Es wäre schön, wenn es da wieder die originale Variante mit ue ist. Es ist nur eine Kleinigkeit, aber meines Wissens können Suchmaschinen ue als ü in Namen erkennen und somit eine Winzigkeit sauberer Indexieren. Zugegeben, eine Kleinigkeit, aber da es bis C3 so war, wäre es schön, wenn es weiterhin so ist :)

**Comment by backbone87** [comment]
normalerweise sollten dateisysteme damit klar kommen, nur etwaige URLs und pfade müssen dann korrekt escaped werden.

**Comment by Samson1964** [comment]
> Unter C3 war es imho so, dass Contao beim Anlegen von Ordnern oder Dateien darauf geachtet hat, dass keine Sonderzeichen und Umlaute im Ordner-/Dateinamen waren.

Ist mir noch nie aufgefallen. Habe deshalb testweise mal eine Datei mit Leerzeichen, Undzeichen und Umlauten hochgeladen. In meinem Contao 3.5.12 wurde nichts geändert. Kann mich auch nicht erinnern, daß das in irgendeiner anderen Version seit 3.0.6 war. Vielleicht macht(e) das bei Dir irgendeine Erweiterung?

**Comment by asaage** [comment]
@Samson1964 editier mal in der Dateiverwaltung Metainformationen der betreffenden Dateien!
Wenn ich mich recht erinnere war es so, das Upload und Editieren unterschiedliche Kriterien auf den Dateinamen anwendet.
