### ISSUE TITLE
Eventlist und Eventreader: Bei Zeitraum Leerzeichen vom Bindestrich entfernen

### ISSUE THREAD

**Issue by Amarok365** [contao/core#8690]
Es gibt ein typographisches Problem bei allen Modulen rund um Events und Kalender: wenn man ein Event erstellt, das einen Zeitraum enthält, also z. B. von 20:00 bis 22:00 Uhr, wird mit Contao folgendes ausgegeben:
**"20:00 – 22:00"**
"Leerzeichen Bindestrich Leerzeichen" ist typographisch leider ein falscher Bindestrich oder "Bis-Strich". Die Leerzeichen sollten entfernt werden, denn erst dann hat der Bindestrich die richtige Bedeutung **"bis"**. Mit Leerzeichen hat er eine Bedeutung **"gegen"**, etwa bei Spielen, z. B. "Hamburger SV – Hannover 96". Siehe https://de.wikipedia.org/wiki/Halbgeviertstrich
"Laut Duden stehen vor und nach einem Bis-Strich kein Leerzeichen"
**Vorschlag:** Ersatz von "Leerzeichen Bindestrich Leerzeichen" in "`&ndash;`"

Alle Vorkommen laut Community-User [Spooky](https://community.contao.org/de/member.php?9203-Spooky):
    /system/modules/calendar/classes/Events.php#L222
    /system/modules/calendar/classes/Events.php#L232
    /system/modules/calendar/classes/Events.php#L240
    /system/modules/calendar/classes/Calendar.php#L412
    /system/modules/calendar/classes/Calendar.php#L416
    /system/modules/calendar/dca/tl_calendar_events.php#L736 (nur Backend)
    /system/modules/calendar/dca/tl_calendar_events.php#L744 (nur Backend)
    /system/modules/calendar/modules/ModuleEventReader.php#L143
    /system/modules/calendar/modules/ModuleEventReader.php#L152
    /system/modules/calendar/modules/ModuleEventReader.php#L160

**Comment by fritzmg** [comment]
May be make this configurable through TL_LANG, so that the time entry is generated via
```php
\Date::parse(…) . $GLOBALS['TL_LANG']['MSC']['timeSpanDash'] . \Date::parse(…); 
```
for example.

**Comment by Amarok365** [comment]
Which I would prefer as well. A `&ndash;` is not the only solution, it could be also e.g. `&rarr;`, `&raquo;` or whatever the webmaster desires to depict a period of time.

**Comment by leofeyer** [comment]
Fixed in 49a89e4b403050374b4c2e1b5c17aabd0f3d0e43.
