### ISSUE TITLE
New feature: Quick access to the cache clearing

### ISSUE THREAD

**Issue by jankout** [contao/core#8692]
I think that it would be nice to have the possibility to a more quick access to the cache clearing. It could be placed in the main bar next to the link to the user account (with an own icon). And when I go over it with my mouse the options for the cache(s) (as we know them now), I would like to clear, appear in a dropdown menu and I can choose what I want to clear and then I should press the "do" button and the system does the rest for me. Maybe there could be also a quick cache clearing for the main things - this would work just with a single click. 

Actually, it is similar like in Typo3 where I've founded very useful. Especially when we work with Firefox it's very necessary to clear the cache after every change.

**Comment by discordier** [comment]
I am strongly against this.
This would be of benefit in 3.5 which is feature complete.
In Contao 4, the cache clearing tasks will get moved to manager tasks and therefore removed from the backend altogether and therefore it does not make sense to introduce this feature when it will get removed in the near future.

**Comment by ausi** [comment]
> Especially when we work with Firefox it's very necessary to clear the cache after every change.

Why is the Contao cache related to the browser you are using? The behavior should be the same for all browsers I think.

**Comment by aschempp** [comment]
The page cache is part of the CMS content, so I think that should be manageable from the backed. Using the manager for that hardly makes sense to me.

**Comment by fritzmg** [comment]
I agree with @aschempp, controlling the content for the front end should definitely be possible from the regular back end, not just the manager.

Btw. @jankout have a look at [netzmacht/contao-cache-control](https://github.com/netzmacht/contao-cache-control) if you want to have a more fine grained control over the page cache in Contao 3.

**Comment by xchs** [comment]
Related issue: https://github.com/contao/core/issues/7155

**Comment by Metis77** [comment]
this has been closed as duplicate.
the other issue #7155 has been closed by referencing this one.

**Comment by fritzmg** [comment]
#7115 has not been closed
