### ISSUE TITLE
inconsistent cache key generation

### ISSUE THREAD

**Issue by fritzmg** [contao/core#8694]
There is an inconsistency with the cache key generation and usage. When a page is generated for the page cache, `FrontendTemplate::addToCache` _always_ uses the __current host__ for the cache key: 
[system/modules/core/classes/FrontendTemplate.php#L216-L220](https://github.com/contao/core/blob/3.5.25/system/modules/core/classes/FrontendTemplate.php#L216-L220)
```php
$strCacheKey = \Environment::get('host') . '/empty.' . $objPage->language;
…
$strCacheKey = \Environment::get('host') . '/' . \Environment::get('request');
```
However, `Automator::generateConfigCache` _always_ uses either the _DNS setting_ from the page object or `*`: 
[system/modules/core/library/Contao/Automator.php#L539](https://github.com/contao/core/blob/3.5.25/system/modules/core/library/Contao/Automator.php#L539)
```php
$strBase = ($objPages->dns ?: '*');
```
So when the internal cache is active, the resulting `system/cache/config/mapping.php` will look like this for example:
```php
<?php

return array (
  '*/empty.fallback' => '*/empty.de',
  '*/empty.de' => '*/empty.de',
);
```
But the cache file was generated with `example.org/empty.de` as its cache key.

This then leads to the start page _never_ being served from the page cache, if the internal cache is built and no DNS setting was present in the website root.

**Comment by leofeyer** [comment]
So we need to adjust the [FrontendTemplate](https://github.com/contao/core/blob/3.5.25/system/modules/core/classes/FrontendTemplate.php#L213-L221) class as follows, right?

```php
// Server-side cache
if ($intCache > 0 && (\Config::get('cacheMode') == 'both' || \Config::get('cacheMode') == 'server'))
{
	$strBase = ($objPage->dns ?: '*');

	// If the request string is empty, use a special cache tag which considers the page language
	if (\Environment::get('request') == '' || \Environment::get('request') == 'index.php')
	{
		$strCacheKey = $strBase . '/empty.' . $objPage->language;
	}
	else
	{
		$strCacheKey = $strBase . '/' . \Environment::get('request');
	}
```

**Comment by fritzmg** [comment]
No, if you use `$strBase = ($objPage->dns ?: '*');` for __both__ it won't work. You must use it only for the empty request.

**Comment by leofeyer** [comment]
See #8695.
