### ISSUE TITLE
TLD redirects with 302 to home.html

### ISSUE THREAD

**Issue by dpeters250** [contao/core#8697]
We currenlty have an issue with 3.5.25:
When the tld is visited the site redirects to [...]index.php/home.html or [...]/home.html. 
There is no redirect on version 3.5.17. Is there anything we are missing or is this maybe a bug from #8560 ?

Example not working one:
skiprofi.it -> skiprofi.it/index.php/home.html
Example working:
sport-penz.at -> sport-penz.at

Contao is in the base directory and not in a subfolder.
Google Webmaster Tools is not happy with that redirect thing and marks it with a bad ranking.

You can easiely view the redirect with the developer tools in any browser:

- 3.5.25: [skiprofi.it](http://skiprofi.it)
- 3.5.25: [rentmaxx.com](http://rentmaxx.com)
- 3.5.17: [sport-penz.at](http://sport-penz.at)

**Comment by aschempp** [comment]
The first page in your tree should have the alias "index" and not "home", then there will be no redirect.

**Comment by dpeters250** [comment]
Nice! It's working thank you!
Since when is that feature implemented?

**Comment by Toflar** [comment]
> Since when is that feature implemented?

Not sure exactly but 2.11 maybe? For more than 5 years for sure.

**Comment by dpeters250** [comment]
Interesting that we have encountered the problem only now. Thanks!

**Comment by fritzmg** [comment]
The redirect was added in version `3.5.18`.
