### ISSUE TITLE
Events-RSS aus mehreren Events-Archiven nicht nach Datum sortiert

### ISSUE THREAD

**Issue by NinaG** [contao/core#8698]
Ich lasse unter Contao 4 ein RSS-Feed, bestehend aus mehreren Archiven, generieren.

Erwartet: Contao listet die Events (gemischt aus allen angehakten Archiven) ordentlich nach dem Datum sortiert auf.

Realität: Die Events werden wild gemischt ausgegeben, ich kann keine Ordnung erkennen. Erst ein paar frühere, dann ein paar spätere und dann wieder frühere Events. So ist es natürlich unbrauchbar.

**Comment by NinaG** [comment]
Anmerkung, es scheint auch dann zu passieren, wenn man nur ein Archiv wählt. Konkretes Beispiel (nur ein Archiv ausgewählt) ergibt dann diese Listung:

- 13.04.2017 (19:00) ...
- 30.06.2017 – 02.07.2017 ...
- 13.04.2017 ...
- 15.04.2017 ...
- 11.06.2017 (14:00 – 18:00) ...
- 12.08.2017 ...
- 01.05.2017 (10:30 – 15:00) ...

Wie ihr sehen könnt, ist es bis zum Schluss wild durcheinander. Kann es sein, dass das RSS-Feed nicht nach dem Datum sortiert, sondern danach, wann ein Eintrag erstellt wurde o.ä.?

**Comment by NinaG** [comment]
Es hat definitiv mit dem Änderungsdatum zu tun. Das RSS-Feed scheint sich wirklich nicht danach zu richten, wann ein Event stattfindet, sondern wann der Eintrag das letzte Mal bearbeitet (gespeichert) wurde. Das ist für den Nutzer nicht sinnvoll, da er erwartet, dass er eine nach Datum der Veranstaltung sortierte Liste sieht.

**Comment by ausi** [comment]
Ich konnten den Fehler nicht reproduzieren. Kannst du das Problem auf demo.contao.org nachstellen?

**Comment by fritzmg** [comment]
@NinaG welche Extensions hast du im Einsatz? Einige haken sich da ein.

**Comment by NinaG** [comment]
Ich habe die aktuellste Contao-Version und als Extension nur page-image von terminal42 im Einsatz.

**Comment by asaage** [comment]
Eine Sortierung nach Erstellungs- oder Änderungsdatum scheint mir natürlich.
Wenn man mit dem Feed auf dem Laufenden bleiben will kommen die Events doch eh in der Regel einzeln rein und das Event-datum ist in dem Fall doch nur eine Art Betreff/Titel.

**Comment by NinaG** [comment]
Das mag vielleicht noch für normale News so Sinn ergeben, aber bei Events überhaupt nicht mehr. Damit wird doch z.B. auch das Modul RSS-Reader komplett sinnlos, wenn es dann die Events nicht sauber sortiert ausgibt, sondern beliebig zwischen den Daten springt.

Konkreter Anwendungsfall:
Eine Stadt hat jede Menge Veranstaltungen auf ihrer Website. Sie erstellt davon ein RSS-Feed, das dann diverse Event-Portale, Tourismus-Portale etc. auslesen können und damit bei ihnen die Terminliste dieser Stadt auf ihren Websites haben. Super Sache. Nur saudoof und unnutzbar, wenn die Termine da dann nicht nach Datum sortiert erscheinen, sondern wild durcheinander. Im Prinzip könnte ein Redakteur dann niemals einen Termin nachtragen oder mal einen Rechtschreibfehler korrigieren, weil sofort das Feed alles durcheinander würfelt.

Mein Vorschlag: Contao sollte eine Einstellmöglichkeit anbieten, dass man beim Erstellen des Feeds wählen kann, wonach die Einträge sortiert werden:
a) nach dem eigentlichen Datum des Eintrages, egal ob bei Events oder News
b) nach dem Änderungsdatum des Eintrages

So werden beide Herangehensweisen ermöglicht und der Website-Betreiber entscheidet selbst, welchen Anwendungsfall er hat.

**Comment by derastronaut** [comment]
Ich muss Nina hier beipflichten, denn aus diesem Grund benutze ich für meinen Kalender gar keinen RSS-Feed mehr.

**Comment by leofeyer** [comment]
Ich kann das Problem auch nicht reproduzieren. In einer Standard-Installation ohne Erweiterungen und mit der COD werden die Events immer korrekt im Feed sortiert. Auch die Aussage, dass Events nach dem Änderungsdatum sortiert werden ist falsch:

https://github.com/contao/core/blob/master/system/modules/calendar/models/CalendarEventsModel.php#L309
