### ISSUE TITLE
News article access rights 

### ISSUE THREAD

**Issue by tsarma** [contao/core#8699]
I don't know if this is a bug or a lacking feature. Anyway I wanted to mention is here. 

For normal Contao articles, we can define access setting from page. 
![screen shot 2017-04-13 at 14 32 12](https://cloud.githubusercontent.com/assets/683894/25004966/308178c0-2057-11e7-9a23-09082cdacd12.png)

So can we disable delete button from article, if we like to.
![screen shot 2017-04-13 at 14 30 50](https://cloud.githubusercontent.com/assets/683894/25005204/37dd8568-2058-11e7-9428-57994f9dcbcd.png)

But this function is not available for news article.
![screen shot 2017-04-13 at 14 28 59](https://cloud.githubusercontent.com/assets/683894/25005267/72496582-2058-11e7-9c58-a716c017e81c.png)

**Comment by leofeyer** [comment]
That's because news articles do not have back end access rights. You have to define the access rights on the news archive instead.

**Comment by tsarma** [comment]
> That's because news articles do not have back end access rights.

Yes that is what I am trying to point out.

> You have to define the access rights on the news archive instead.

Access rights on the news archive is applied only to a frontend member group. It doesn't let you control the function of news editors.

![screen shot 2017-04-19 at 11 10 48](https://cloud.githubusercontent.com/assets/683894/25172826/703da822-24f2-11e7-9d0a-7fa488a01207.png)

**Comment by fritzmg** [comment]
> Access rights on the news archive is applied only to a frontend member group. It doesn't let you control the function of news editors.

You can define news archive and news permissions per back end user and back end user group as well.

**Comment by leofeyer** [comment]
You are looking in the wrong place. Check the user (group) settings instead:

<img width="511" alt="" src="https://cloud.githubusercontent.com/assets/1192057/25173228/9c904690-24f3-11e7-97e7-79e9645c6ed9.png">

**Comment by tsarma** [comment]
News permissions Create/Delete is applied to news Archive but not to a news article. 
What I am pointing out, is there is no way to control the function of news articles it self, like page articles as I have shown in first screen shots.

**Comment by leofeyer** [comment]
> That's because news articles do not have back end access rights. You have to define the access rights on the news archive instead.

**Comment by derastronaut** [comment]
@tsarma no, there is no specific solution to manage rights like "who is allowed to delete or edit single articles in one and the same news-archive. What leofeyer means is you have to create one news-archive per user and then you can give them their own archive-rights.

What you, me and some other Contao-user want isn't realized yet. Take a look at https://github.com/contao/core/issues/8660 and https://community.contao.org/de/showthread.php?65791-Nur-eigene-Nachrichten-bearbeiten-Autoren. It's German. I hope you can read it.

**Comment by tsarma** [comment]
@derastronaut Thank you for the clarification. Now understood it, what leofeyer meant by "you have to define the access rights on the news archive". That would mean for me, like you have said create one news-archive per BE user with corresponding rights.

Thank you everyone for the discussion.
