### ISSUE TITLE
Bilder nicht bearbeiten, wenn original Größe = target Größe

### ISSUE THREAD

**Issue by Znrl** [contao/core#8700]
Image Klasse Image.php
(3.5.25) ab Zeile 418

Im CE Element spielt das kein Rolle.
Contao 4 in der Demo scheint das richtig zu machen, habe ich aber jetzt nicht ausführlich getestet.

Beim Einsatz von Bildgrößen führt das dazu, dass Kopien von Bildern erstellt werden, die die gleichen Abmessungen wie das original haben. Diese sind oft größer als das original und es ist prinzipiell ja auch nicht nötig.

Das tritt auf, wenn man als Einstellung für Höhe und Breite nicht die des original Bildes verwendet.
Sondern man nur über den Skalierungsfaktor auf die Größe des Originals kommt.
Oder nur eine Größe dem original entspricht und die andere nicht.

Beispielsweise:
Bild mit 1200px Breite 1000px Höhe

Einstellung Bildergrößen:
Breite: 600px, Höhe:600px
Skalierung: 1x, 2x

Führt dazu, dass ein neues Bild mit 1200x1000px Breite erstellt (2x) wird obwohl das dem originalen Bild entspricht.
Vermeiden lässt sich das in dem Fall, durch leer lassen der Höhe oder Einstellung Höhe 500px.

Das Heißt die (berechneten) targetWidth und targetHeight (mit dem Skalierungsfaktor) müssen BEIDE mit denen des originalen Bildes übereinstimmen oder eines muss leer bzw. nicht angegeben sein.

Forumsthread: https://community.contao.org/de/showthread.php?66398-Performance-bei-Bildgr%C3%B6%C3%9Fen

**Comment by ausi** [comment]
> Contao 4 in der Demo scheint das richtig zu machen, habe ich aber jetzt nicht ausführlich getestet.

In Contao 4 wurde das Image-Handling komplett neu geschrieben und in eine eigene [contao/image](https://github.com/contao/image) library ausgelagert. Ob ein resize nötig ist oder nicht wird dort erst überprüft nachdem die genauen Koordinaten für das Resizing feststehen. Deshalb sollte dieser Bug in Contao 4 nicht auftreten können.

Für Contao 3.5 müsste man vermutlich eine Methode nachrüsten die für die verschiedenen Resize-Modes feststellen kann ob ein Resizing überhaupt nötig ist oder nicht. Alternativ könnte man `computeResize()` im Vorraus ausführen und den check auf das Ergebnis davon machen. Ich bin mir aber nicht sicher ob der Aufwand dafür steht, da der Bug ja nicht direkt ein Fehler ist sondern nur nicht das optimalste Ergebnis.

Verursacht das Verhalten direkte Probleme auf deiner Seite?

**Comment by Znrl** [comment]
Nein ich hab das nur aus dem Forum hier übertragen.
Dort hat ein User Probleme mit dem memory_limit gehabt, was damit potentiell zusammenhängen kann, da hier u.U. mindestens 1 Bild mehr erstellt werden muss.
Es ist auch unschön, wenn man das optimiert hat und Contao dann das wieder "vergrößert" (Speicher/Bandbreite).

Wenn man das hier weiß kann man denke ich aber in vielen Fällen drum rum arbeiten.

**Comment by ausi** [comment]
*„resizeMode fit the box -> kleinere Seite = target seize“* ist nicht korrekt, es muss die Proportion des Bildes mit der Proportion der eingestellten Größe verglichen werden.

Dann gibt es noch die Fälle

- wo nur eine Größe angegeben ist (für alle Resize-Modes).
- mit Zoom != 0 aber keinem Important-Part 
- mit Zoom != 0 und einem Important-Part der mit der eingestellten Größe nicht gezoomt werden kann
- alle 9 „exaktes Format“ Varianten die wie crop behandelt werden können

Ich würde also eher zu der Variante *`computeResize()` im Voraus ausführen* tendieren.

**Comment by leofeyer** [comment]
Wir haben das Problem nochmals diskutiert und sind zu dem Schluss gekommen, dass der Aufwand zu groß ist, um das in Contao 3 zu beheben.

**Comment by Aybee** [comment]
In Contao 3 kann man den `getImage` HOOK als Workaround benutzen.
```php
public function notBiggerAsOriginal($image, $width, $height, $mode, $strCacheName, $objFile, $target, $objImage)
{
  if(TL_MODE == 'FE' && $width >= $objFile->imageSize[0] && $height >= $objFile->imageSize[1])
  {
    return \System::urlEncode($image);
  }
  return false;
}
```
Die Logik kann man noch an seine Bedürfnisse anpassen. Ich benutze in obigem Fall nur Bildgrößen und teste, ob die Zielbreite größer wäre als die Originalbreite UND die Zielhöhe größer als die Originalhöhe. In diesem Fall sende ich den Pfad zum Originalbild zurück.
