### ISSUE TITLE
youtube ID is forced to lower case

### ISSUE THREAD

**Issue by fritzmg** [contao/core#8704]
Tested in Contao `3.5.26`.

## Reproduction

1. Create a new content element of type `youtube`.
2. Enter the following valid YouTube video ID into the `youtube` field: `HZNM2Ki42T8`.
3. Save the element.

The YouTube video ID is forced to lowercase (`hznm2ki42t8`), which is a completely different YouTube video ID. See also [this thread](https://community.contao.org/de/showthread.php?66532-Elementtyp-Youtube-fehlerhaft&p=438773&viewfull=1#post438773) for example.

## Cause

The problem is caused [here](https://github.com/contao/core/blob/3.5.26/system/modules/core/widgets/TextField.php#L123):
```php
$varInput = \Idna::encodeUrl($varInput);
```
The function `\Idna::encodeUrl` converts the input to lowercase.

May be this is caused by the recent Punycode update?

## Workaround

For anyone encountering this issue, you could do the following workaround in the mean time:
```php
unset($GLOBALS['TL_DCA']['tl_content']['fields']['youtube']['eval']['rgxp']);
```
Add this to your `dcaconfig.php` for example. This removes the `url` regex validation and prevents the ID from being converted to lowercase.

**Comment by fritzmg** [comment]
The same happens in Contao `4.3.7`.

**Comment by BugBuster1701** [comment]
Yes, Punycode 2.x:
```
    public function encode($input)
    {
        $input = mb_strtolower($input, $this->encoding);
...
    public function decode($input)
    {
        $input = strtolower($input);
...
```

When using the Punycode class, the parameter must be only the domain, not the whole URL.
That was in Punycode 1.x already so. (see PHPDoc)

But, Contao 4.3.7 used Punyconde 1.x. The problem should not occur there.

**Comment by fritzmg** [comment]
May be the online demo was already at `4.3.8`? I saw the announcement right after I tested.

**Comment by leofeyer** [comment]
I think we should revert the Punycode changes and go back to version 1.

**Comment by leofeyer** [comment]
On the other hand, `Idna::encodeUrl()` uses `parse_url()` and only sends the host name to the `Punycode` class. The query should not be modified.

**Comment by leofeyer** [comment]
The problem is actually caused here: https://github.com/contao/core/blob/3.5.26/system/modules/core/library/Contao/Idna.php#L178-L182

**Comment by BugBuster1701** [comment]
Ich glaube das Problem ist, es gibt zwar Idna:encodeUrl aber kein Idna:decodeUrl.
Decode in Punycode 2.x wird ja auch mit strtolower gewandelt.

In [FormTextField.php#L119](https://github.com/contao/core-bundle/blob/master/src/Resources/contao/forms/FormTextField.php#L119) und [TextField.php#L149](https://github.com/contao/core-bundle/blob/master/src/Resources/contao/widgets/TextField.php#L149) habe ich schon mal zwei Stellen gefunden, vielleicht gibt es noch mehr.
Dort müssten dann die neue Methode decodeUrl benutzt werden.

**Comment by fritzmg** [comment]
That won't help. Once it's saved as lower case, it cannot be "decoded" as upper case ;)

**Comment by BugBuster1701** [comment]
Wenn ich es in die DB groß reinschreibe dann funktioniert schon mal das auslesen, es bleibt groß.
Jetzt muss ich nur  noch finden wo es beim Schreiben auf klein gesetzt wird.

**Comment by leofeyer** [comment]
I think we should revert the changes and only use Punycode 2 in Contao 4.4.

**Comment by leofeyer** [comment]
I have reverted the changes in 87d76ad04d3d7f9ccd6c3b93929f508cc1773382.
