### ISSUE TITLE
Unerwarteter Logout im FE bzw. BE

### ISSUE THREAD

**Issue by frontendschlampe** [contao/core#8705]
In eine Multi-Domain-Installation (Contao 3.5.24) ist mir folgendes aufgefallen:

- Domain http://www.domainA.tld und http://www.domainB.tld zeigen auf die selbe Contao-Installation
- Domain http://www.domainA.tld ist eine öffentlich erreichbare Website
- auf Domain http://www.domainB.tld gibt es öffentlich nur ein Login-Formular
- einloggen im Frontend unter http://www.domainB.tld - man wird auf http://www.domainB.tld/seite2.html weitergeleitet
- im Backend unter http://www.domainB.tld/contao einloggen
- im Backend etwas bearbeiten
- im Frontend die Seite http://www.domainB.tld/seite2.html refreshen (F5): man ist nun ausgeloggt im Frontend und bekommt 403 Denied (kein login, da man auf http://www.domainB.tld/seite2.html ist und keine weiterleitung bei 403 konfiguriert ist)
- im Frontend unter http://www.domainB.tld wieder einloggen (man wird auf http://www.domainB.tld/seite2.html weitergeleitet)
- im Backend refreshen (F5): man ist nun ausgeloggt im Backend

**ABER:**
Wenn man sich unter http://www.domainA.tld/contao (Backend) und http://www.domainB.tld (Frontend) einloggt, funktioniert alles wie gewünscht.

In Contao 3.2 war das bisher auch möglich, wenn man unter der selben Domain im FE und BE eingeloggt ist.

**Achtung:**
Ich meine hier nicht das Thema, wenn ich mich im FE auslogge und dann auch im BE ausgeloggt bin. Ein Logout wird aktiv nicht durchgeführt.

**Comment by fritzmg** [comment]
Duplicate of #8528

**Comment by frontendschlampe** [comment]
na toll ... ich hatte so ein Ticket auch in Erinnerung, aber ich bin nur bis Ende Oktober zurück! :-D Danke.
