### ISSUE TITLE
Benutzer kann nicht-leere Verzeichnisse mit Leerzeichen löschen

### ISSUE THREAD

**Issue by d3vm4t** [contao/core#8706]
Ein Benutzer kann nicht-leere Verzeichnisse mit Leerzeichen im Verzeichnisnamen löschen, obwohl er dazu keine Berechtigung hat.

Das Problem lässt sich wie folgt reproduzieren (3.5.2x):
1. ein Verzeichnis mit dem Namen "Test A" und ein Verzeichnis mit dem Namen "Test_B" an beliebiger Stelle in der Dateiverwaltung anlegen (hier: "files/Test/Test A" und "files/Test/Test_B")
2. in beide Verzeichnisse werden eine beliebige Anzahl Dateien bspw. Bildern oder PDF hochgeladen
3. ein beliebiger Backend Benutzer (hier: "Testuser") wird einer Gruppe (hier: "Testgruppe") hinzugefügt
- in den Benutzereigenschaften von _Testuser_ ist "Rechtevererbung" auf "Nur Gruppenrechte verwenden" gesetzt
4. die Testgruppe wird editiert: 
- bei "Filemounts" wird das Verzeichnis "files/Test" gemountet
- Unter "Erlaubte Datei-Operationen" werden ausschließlich die drei Checkboxen "Dateien auf den Server hochladen", "Dateien und Verzeichnisse bearbeiten, kopieren und verschieben" und "Einzelne Dateien und leere Verzeichnisse löschen" gesetzt und anschließend gespeichert
5. Der Benutzer _Testuser_ loggt sich im Backend ein und klickt auf Dateiverwaltung
- _Testuser_ kann den Ordner _Test_B_ nicht löschen (das ist das erwartete Verhalten)
- _Testuser_ kann den Ordner _Test A_ löschen und das sollte nicht der Fall sein

**Comment by leofeyer** [comment]
@contao/developers @ausi /cc

**Comment by ausi** [comment]
Ein fehlendes `urldecode()` hat den Fehler verursacht weil `Test A` zu `Test%20A` wurde. Wird mit dem Pull-Request #8710 behoben.

**Comment by d3vm4t** [comment]
Getestet und behebt das Problem. Danke!

**Comment by leofeyer** [comment]
Danke @ausi.
