### ISSUE TITLE
Fokus Popups bei iOS

### ISSUE THREAD

**Issue by Schmidty2** [contao/core#8708]
Hallo,
das oben genannte Problem aus https://github.com/contao/core/issues?utf8=%E2%9C%93&q=8250 besteht wieder (immer noch?).
Ich habe Contao 3.5.27 installiert und verwende iOS 10.3.1 auf einem iPad pro, getestet wurde mit Safari, Chrome und Firefox für iOS.
Das Problem besteht nicht nur beim File-Manager sondern bei allen Popups in denen Eingaben getätigt werden z.B. auch beim Notification-Center.
Es lassen sich weder ein Bild einfügen noch andere Arbeiten in Popups durchführen, z.B. im Notification-Center. Es scrollt immer der Hintergrund und nicht der Inhalt des Popups.

**Comment by leofeyer** [comment]
Kann das jemand reproduzieren?

**Comment by ausi** [comment]
Ja, kann ich reproduzieren mit dem File-Tree-Picker, jedoch nur auf dem iPad, nicht am iPhone. Scheint ein iOS bug zu sein, konnte ihn aber auf die Schnelle nicht genau lokalisieren...

**Comment by ausi** [comment]
@Schmidty2 Kannst du bitte testen ob sich der Fehler mit folgendem CSS-Code beheben lässt?

```css
.ios .simple-modal:before {
	content: "";
	position: absolute;
	top: 0;
	left: 0;
	width: 1px;
	height: calc(100% + 1px);
	pointer-events: none;
}
```

Du kannst den Code am Ende der Datei *assets/mootools/simplemodal/1.2/css/simplemodal.css* hinzufügen.

**Comment by Schmidty2** [comment]
@ausi 
Hallo,
Danke für die Mühen. Mit obiger CSS-Anweisung und Firefox bzw. Chrome unter iOS funktioniert das Ganze jetzt problemlos, sowohl beim Dateien einfügen als auch beim NC.
Bei Safari funktioniert es auch, aber zwischendurch funktioniert es dann bei Safari wieder nicht mehr richtig. Wenn ich dann den Safari-Cache lösche funktioniert es wieder.

**Comment by ausi** [comment]
Firefox, Chrome und Safari auf iOS verwenden dieselbe Browser-Engine, deshalb sollte es eigentlich keine Unterschiede geben. Konntest du genauer feststellen wann es im Safari funktioniert und wann nicht? Oder ist dabei kein Muster erkennbar?

**Comment by Schmidty2** [comment]
Hallo,
ich habe jetzt noch einmal den Safari Cache komplett gelöscht, nach dem Einfügen von 3-4 Bildern hängt der Safari komplett. Dann den Cache löschen und das Ganze funktioniert wieder.
Heute habe ich zusätzlich das iPad komplett ausgeschaltet und neu gestartet, seitdem treten auch bei Safari keine Probleme mehr auf.

Ich habe auch noch einige Tests auf dem iPhone 6s plus mit iOS 10.3.1 gemacht: Ohne Patsch Probleme vorhanden - mit Patch läuft alles.

Der Patch sollte also funktionieren.

**Comment by ausi** [comment]
Da das CSS bei dir und mir den Fehler behoben hat, handelt es sich ziemlich sicher um den iOS scrolling bug. Weitere Informationen dazu findet man hier: http://patrickmuff.ch/blog/2014/10/01/how-we-fixed-the-webkit-overflow-scrolling-touch-bug-on-ios/

@leofeyer Ich denke wir sollten den CSS patch einbauen.

**Comment by leofeyer** [comment]
Der Kommentar auf der verlinkten Seite enthält auch noch

```css
outer:after{
    content:””;
    width: 100%;
    clear: both;
}
```

Das brauchen wir aber nicht?

**Comment by leofeyer** [comment]
<img width="755" alt="" src="https://user-images.githubusercontent.com/1192057/26983280-89026a66-4d3b-11e7-8168-b4feff825b4c.png">

Was ist mit `display: block`?

**Comment by ausi** [comment]
`display: block` und `:after` brauchen wir nicht, da wir es mit `position: absolute` lösen. Mein CSS-Code von oben sollte passen denke ich.

**Comment by leofeyer** [comment]
Behoben in contao-components/simplemodal@5ce3763ac029eac52cf736f881c6a951907b55af.

**Comment by Schmidty2** [comment]
Hallo,
ich habe gerade festgestellt, dass bei Contao 3.5.30 das Problem wieder vorhanden ist.
Die von ausi genannten CSS-Anweisungen wurden erneut von Hand nachgetragen und haben das Problem wieder gelöst.

**Comment by leofeyer** [comment]
Kann ich nicht bestätigen. Der Code ist eindeutig noch da:

https://github.com/contao/core/blob/3.5.30/assets/mootools/simplemodal/1.2/css/simplemodal-uncompressed.css#L76-L85

**Comment by Schmidty2** [comment]
Hallo, sorry für die späte Rückmeldung.
Das Ganze funktioniert definitiv nicht, ich habe es gerade in einer neu installierten 3.5.31 ohne zusätzliche Erweiterungen getestet.
Unter Contao 4.4.8 besteht das Problem ebenfalls, hier kann auch in der offiziellen Demo nachvollzogen werden (https://github.com/contao/core-bundle/issues/1213).
