### ISSUE TITLE
Feature: tl_form_fields

### ISSUE THREAD

**Issue by jonnysp** [contao/core#8711]
bitte beim nächsten Update das "class field" bei Formularfeldern
**headline, explanation, html** mit anzeigen lassen ist ja eh da.

in **tl_form_fields** -> **pallettes** ->  **{expert_legend:hide},class;** hinzufügen. und ggf. templates anpassen

**Comment by Toflar** [comment]
`html` braucht das sicher nicht, weil `html` ist ja was immer du eingibst. `headline` gibt es nicht mehr und `explanation` hat die Klasse bereits. Ist also alles bereits erledigt in der 4.

**Comment by jonnysp** [comment]
ich wollte es in die v3. Bei html hast du recht.

**Comment by fritzmg** [comment]
Contao 3 bekommt keine neuen Features mehr. Du musst auf Contao 4 umsteigen dafür.

**Comment by jonnysp** [comment]
danke!
