### ISSUE TITLE
Page alias: '/' are allowed, but the resulting URL is not correct

### ISSUE THREAD

**Issue by Teetrinker** [contao/core#8713]
[experienced with the managed edition]

When creating a new page, I can set an alias with a slash in it:
`page/childpage`

Bute the childpage is not reachable via
`domain.tld/de/page/childpage`

On a sidenote: What happens to the URL's when a site is transfered from Contao 3.5 and used this link structure?

**Comment by backbone87** [comment]
with default config, contao appends `.html` to urls, so if you use `page/childpage` as alias, the url would be `domain.tld/de/page/childpage.html`

**Comment by fritzmg** [comment]
Did you forget to enable __Enable folder URLs__ in your system settings?

**Comment by Teetrinker** [comment]
I'm sorry, my fault. I changed the url_suffix setting in the config file.

`# Contao configuration
contao:
    url_suffix: ''  `

So maybe just a "not supported option" - yet?

**Comment by fritzmg** [comment]
It is supported. It's just not configurable in the system settings any more. It will be configurable in the Contao Manager though.

**Comment by Teetrinker** [comment]
> Did you forget to Enable folder URLs in your system settings?
Yes that was it!

Should slashes in aliases be allowed if this system setting is turned off?
