### ISSUE TITLE
form_hidden templates dont escape value properly

### ISSUE THREAD

**Issue by backbone87** [contao/core#8714]
the value shouldnt be output unescaped, but with `specialchars($this->value, false, true)`

**Comment by leofeyer** [comment]
@ausi /cc

**Comment by backbone87** [comment]
btw its already escaped inside the FormHidden::generate

**Comment by ausi** [comment]
I agree. In [form_textfield.html5:20](https://github.com/contao/core/blob/a44556644b8e548fce79d0ae5f07fc84b940f18d/system/modules/core/templates/forms/form_textfield.html5#L20) we use `value="<?= specialchars($this->value) ?>"` and we should do the same in [form_hidden.html5:2](https://github.com/contao/core/blob/a44556644b8e548fce79d0ae5f07fc84b940f18d/system/modules/core/templates/forms/form_hidden.html5#L2).

But I’m not sure if we should use the suggested `$blnDoubleEncode` flag, wouldn’t this be inconsistent with the `generate()` method and the other form templates?

I think it would be a good idea to use double encode everywhere in the future, but I don’t think this should be done in a bugfix release of Contao 3.5.

**Comment by backbone87** [comment]
There should be a flag then, to toggle dbl Encode.

**Comment by leofeyer** [comment]
Fixed in 958c2a88ca82e9fc60faaf459d55de48b38d40c2.
