### ISSUE TITLE
Forms.php Change Request

### ISSUE THREAD

**Issue by webfuzzy** [contao/core#8715]
Für die Entwicklung eines Frontend CRUD-Moduls würde ich gerne die Formularbearbeitung und die Tabellenzugriffe dem Formulargenerator überlassen anstatt sie selbst zu programmieren. Das könnte er auch, bis auf zwei Kleinigkeiten:

1. Vorbelegung der Felder 
2. Update eines Records 

Dazu habe ich auch kürzlich einen Forumseintrag gemacht:
s. https://community.contao.org/de/showthread.php?66678-CRUD-Modul-f%C3%BCrs-Frontend

1. kann man mit der Erweiterung _Inputvar_ lösen.
Ich denke aber, das sollte auch ohne Erweiterung gehen. Evtl. sollte man _Inputvar_ in den Core übernehmen.

2. habe ich in meiner Entwicklungsumgebung _(Contao 3.5.x)_ mit zwei kleinen Core-Patches in _Forms.php_ und _Statement.php_ gelöst:

TL_ROOT/system/modules/core/forms/form.php
```
489:	//		if ($k != 'cc' && $k != 'id')
489:			if ($k != 'cc')  
```

```
527:	//		$this->Database->prepare("INSERT INTO " . $this->targetTable . " %s")->set($arrSet)->execute();
527:			$this->Database->prepare("REPLACE INTO " . $this->targetTable . " %s")->set($arrSet)->execute();
```

TL_ROOT/system/modules/core/library/Contao/Database/Statement.php
```
203:	// REPLACE
204:	else if (strncasecmp($this->strQuery, 'REPLACE', 7) === 0)
205:	{
206:		$strQuery = sprintf('(%s) VALUES (%s)',
207:							implode(', ', array_keys($arrParams)),
208:							str_replace('%', '%%', implode(', ', array_values($arrParams))));
209:		$this->strQuery = str_replace('%s', '%p', $this->strQuery);
210:	}
```

Die Zeile 209 benötigt man, weil in Zeile 154 der Platzhalter %p eingeführt wird(?):
`154:		$this->strQuery = str_replace('%s', '%p', $this->strQuery);`

Meine Bitte wäre diese Patches in geeigneter Form als CR in den Core zu übernehmen.

**Comment by Balindil** [comment]
:+1:

**Comment by discordier** [comment]
`NEVER` use `REPLACE INTO`:
> REPLACE works exactly like INSERT, except that if an old row in the table has the same value as a new row for a PRIMARY KEY or a UNIQUE index, the old row is deleted before the new row is inserted. See Section 13.2.5, “INSERT Syntax”.

This is really bad habit.

**Comment by aschempp** [comment]
Have you tried Haste\Form? https://github.com/codefog/contao-haste/blob/master/docs/Form/Form.md

**Comment by leofeyer** [comment]
Wie am 18. Mai auf Mumble besprochen, ist der Formulargenerator nicht dazu vorgesehen, um gespeicherte Datensätze nochmal zu bearbeiten. Dazu fehlt schon alleine ein entsprechendes Berechtigungskonzept, das festlegt, wer welchen Datensatz bearbeiten darf.

Es führt unserer Meinung kein Weg daran vorbei, in so einem Fall eine eigene Lösung zu entwickeln (z.B. mittels `Haste`) oder eben eine Erweiterung wie z.B. MetaModels zu nutzen.

**Comment by webfuzzy** [comment]
Leider eine sehr unbefriedigende Antwort :-(
s.a. https://github.com/contao/core/issues/2986
s.a https://github.com/contao/core/issues/6334
Trotzdem Danke.
