### ISSUE TITLE
activeRecord missing in Widget configuration

### ISSUE THREAD

**Issue by fritzmg** [contao/core#8717]
In Contao `<=3.2.21` you were able to access the `activeRecord` within a Widget via `$this->arrConfiguration['activeRecord']`. In the current LTS version (`3.5.27`) this is no possible any more.

3227b43e1b1cc8ee058e6b25790a5bdd66a31cc4 removed
```php
$arrData['activeRecord'] = $this->activeRecord;
```
from `DataContainer::row`, but added
```php
$arrAttributes['activeRecord'] = $objDca->activeRecord;
```
in `Widget::getAttributesFromDca`.

But this was also removed in or before 5d878de67eb218d5eb7ba967dbc669859b8489ec (can't find the exact commit). Now the activeRecord is never loaded/set for a Widget.

**Comment by leofeyer** [comment]
It has been changed in 09436b2e33436ea7520c9515c8b98f1e06db88ab and the commit also shows the new way to retrieve the active record.

**Comment by fritzmg** [comment]
thx, missed that!
