### ISSUE TITLE
Calendar-Feed: Bindestrich fehlt im RSS-Feed bei Generierung per CRON

### ISSUE THREAD

**Issue by Physiklehrer** [contao/core#8719]
Im Zusammenhang mit der Änderung #8690 bzw. #8701 tritt bei mir folgendes Problem auf:

Wird die XML-Datei aus dem Backend heraus durch Anlegen eines neuen Events oder über die Systemwartung erzeugt, werden die Bindestriche auch in der XML-Datei korrekt angezeigt:

![systemwartung](https://cloud.githubusercontent.com/assets/22505307/26521924/dcd5ca58-42f4-11e7-82e1-8f39d9df68c3.jpg)

Am nächsten Tag, wenn die Datei per CRON erzeugt wurde, sieht das ganze nun so aus - der Bindestrich fehlt:

![cron](https://cloud.githubusercontent.com/assets/22505307/26521928/f399dd60-42f4-11e7-89d3-9709df7dfd70.jpg)

Könnte es sein, dass beim Aufruf durch CRON die neu eingeführte Variable MSC.cal_timeSeparator nicht zur Verfügung steht?

**Comment by leofeyer** [comment]
Behoben in 440681d1c06f1ded8f48485f2e3ca7bd5398ca3f.
