### ISSUE TITLE
Error: ZIP file will not be downloaded in the right format

### ISSUE THREAD

**Issue by jankout** [contao/core#8721]
Unfortunately, the ZIP files will not be downloaded in the right format when they are implemented thorough the download content element. 

See http://www.rabbiwolff.com/de/#download

**Comment by leofeyer** [comment]
It seems that the downloads are direct links to the files in the file system and do not go through the downloads content element?

**Comment by jankout** [comment]
Sorry, you are right. Could you tell me, please, how should seem the code in the template? There is now 

`<a download="<?= $box->linkLabel ?>" href="{{file::<?= $box->document ?>}}">`

and for DCA

```
'document' => array(
						'label' => array('Datei zum Herunterladen', ''),
						'inputType' => 'fileTree',
						'eval' => array(
						'fieldType' => 'radio',
						'filesOnly' => true,
						'extensions' => \Config::get('allowedDownload'),
						'isDownloads'=> true,
						'tl_class' => 'w50'),
					),
```

**Comment by leofeyer** [comment]
Please refer to the [forum](https://community.contao.org) for this kind of questions.
