### ISSUE TITLE
Database prepare not allowed open / close parenthesis 

### ISSUE THREAD

**Issue by kzorluoglu** [contao/core#8724]
Link: (For) Example (add/delete) Row
example.html?title=%28For%29+Example+%28add%2Fdelete%29+Row

```
    function createSearchQuery()
    {
        $title = $this->Input->get('title');
        if ($title) {
            $query .= "`title` LIKE '%".$title."%' AND ";
        }
        $query = rtrim($query, ' AND ');
        return  $query;
    }
```
generated query is here;
`WHERE `title` LIKE '%(For) Example (add/delete) Row%'
`
```
$sqlResult = $this->Database
->prepare("SELECT * FROM testtable " . $createSearchQuery . " ORDER BY title LIMIT ?,?")
->execute($offset, $this->perPage);
```
Result empty..
Again  have tested with preg_replace() for parenthesis remove, 
```
preg_replace('~[^a-z0-9/ ]+~i', '', $_GET['title']);
```

but same empty result. What is the problem?

**Comment by backbone87** [comment]
this is not a support channel. this tracker is meant for bug reports/feature requests. if you have questions regarding usage, pls use the contao forum or IRC or use general help pages like stackoverflow.

besides that your example is subject to SQL injections (at least without the preg_replace).

**Comment by kzorluoglu** [comment]
I think, this is a cleaning or replacing problem from prepare() function in Database class. That's mean, the question not for support. Main question, why prepare function removed/not allowed parenthesis? Must change Core Database Class itself?

**Comment by backbone87** [comment]
it isnt a problem of the prepare method. you use `Input::get` which encodes parenthesis as html character entities. that is known behavior and wont change.

**Comment by kzorluoglu** [comment]
then, i have 2. solution also  with preg_replace and Http Get Var tested, but that does not work either?

**Comment by kzorluoglu** [comment]
Unfortunately this solution I must use.
`preg_replace('/[^a-zA-Z0-9] () / ', '', $_GET['title']);`

**Comment by ausi** [comment]
@kzorluoglu please note that using strings from `$_GET` or `\Input::get()` directly in your SQL query is very dangerous and vulnerable to [SQL injections](https://en.wikipedia.org/wiki/SQL_injection). You should use pass the value [as a parameter](https://en.wikipedia.org/wiki/SQL_injection#Parameterized_statements) to the database class.

**Comment by kzorluoglu** [comment]
i write before bind parameter from pdo. that  does only for information.:+1:
