### ISSUE TITLE
Upgrade MediaElement to 4.1.3 version?

### ISSUE THREAD

**Issue by rafa8626** [contao/core#8726]
I noticed that your framework is using a 2.x version. Currently WP is working towards upgrading this, so I wonder if you would like to upgrade MEJS as well, since this latest version has fixed many bugs that 2.x versions had.

**Comment by leofeyer** [comment]
Contao 3.5 is not actively developed anymore, therefore we won't add a new major version of the plugin. We are using MEJS 4.1 in Contao 4.4 though:

https://github.com/contao-components/mediaelement/releases

**Comment by rafa8626** [comment]
@leofeyer Thanks for the update
