### ISSUE TITLE
Header für die Suchergebnisse kann nicht angepasst werden

### ISSUE THREAD

**Issue by TheShah** [contao/core#8727]
Contao Version 3.5.25

Im Backend kann man ja für die Suchmaschine die "Elemente pro Seite" auf "0" stellen. Dadurch werden die Suchergebnisse nicht Seitenweise dargestellt, sondern in einer langen List.

Der String aus den Languagefiles "default.xlf" und ebenfalls auch die Logik aus dem Modulefile "ModulSearch.php" sind dann in diesem Fall falsch weil immer ein String generiert wird das eine Seiteweise-Ausgabe voraussetzt.

Zeile 296 aus "ModuleSearch.php": 
$this->Template->header = vsprintf($GLOBALS['TL_LANG']['MSC']['sResults'], array($from, $to, $count, $strKeywords));
hier wird der Fall das keine Seitenweise-Ausgabe eingestellt ist nicht abgedeckt.

**Comment by leofeyer** [comment]
Der String ist auf jeden Fall falsch, aber welche Logik genau meinst Du?

**Comment by leofeyer** [comment]
Was genau ist an "Results 1 - 32 of 32 for …" falsch, wenn es nur eine Seite gibt?

**Comment by TheShah** [comment]
Ich würde gerne den String  "Results 1 - 32 of 32 for …"  in zum Beispiel 
"32 Results for 'Searchstring' '(duration)' "
ändern.

Das geht aber nicht weil der String mit 
$this->Template->header = vsprintf($GLOBALS['TL_LANG']['MSC']['sResults'], array($from, $to, $count, $strKeywords));
generiert wird.

zumindest habe sehe ich keinen anderen Weg.

**Comment by leofeyer** [comment]
Das kannst Du folgendermaßen umsetzen:

Der String `Results %s - %s of %s for &lt;strong&gt;%s&lt;/strong&gt;` ist eine Kurzform von `Results %1$s - %2$s of %3$s for &lt;strong&gt;%4$s&lt;/strong&gt;`. Bei letzterem werden zusätzlich die Nummern der Parameter angegeben, damit man diese mehrfach verwenden kann oder die Reihenfolge tauschen kann.

Du brauchst also: `%3$s results for &lt;strong&gt;%4$s&lt;/strong&gt;`
