### ISSUE TITLE
Stylesheet: Fehlermeldung, wenn Schriftgöße < 1êm

### ISSUE THREAD

**Issue by webfuzzy** [contao/core#8730]
Definiert man in einem Style die Schriftgröße < 1em, also z.B. "0.8em" und ändert später etwas anderes an dem Style, so erhält man beim Speichern die Fehlermeldung "Bitte geben Sie nur Zahlen ein!" und im Feld steht ".8em". Man muss dann explizit nochmal "0.8em" in das Feld eintragen.
![fontsize-error](https://user-images.githubusercontent.com/28669574/27234104-2b3ddae2-52bc-11e7-9717-6c29a51d5453.jpg)

**Comment by ausi** [comment]
Ich konnte das Problem in Contao 3.5.27 nicht reproduzieren. Welche Contao-Version hast du verwendet?

**Comment by webfuzzy** [comment]
Ich habe Contao 3.5.25. 
Die Effekt tritt auch bei mir nicht immer auf. Ich werde noch mal versuchen, genauer rauszukriegen, wann genau. Aber sollte nicht evtl. ".8" auch als Zahl akzeptiert werden?
So steht es dann nämlich auch in der  Listanzeige:
.mod_hhfilecontent .scrollarea {
    height:400px;
    overflow:auto;
    margin-top:10px;
    border:1px solid #AFAFAF;
    font-size:.8em;
}

**Comment by schmanat** [comment]
Was passiert denn wenn du anstelle von .8 0.8 eingibst? Ich habe es gerade bei mir probiert, da hatte ich keine Probleme damit.

**Comment by webfuzzy** [comment]
> Was passiert denn wenn du anstelle von .8 0.8 eingibst?
Mit 0.8 geht es natürlich. Das Dumme ist, dass beim Öffnen des Styles ab und zu .8 statt 0.8 in der Schriftgröße steht. Da es nur sporadisch passiert, kann ich (bisher) leider keine sichere Anleitung zur  Reproduktion geben :-/

**Comment by leofeyer** [comment]
Ich kann das Problem nicht reproduzieren. Wenn man `.8` eingibt, kommt die Fehlermeldung. Wenn man `0.8` eingibt, funktioniert es. Denn Fall, dass ich `0.8` eingebe und später beim erneuten Bearbeiten auf einmal `.8` im Feld steht, hatte ich nie.
