### ISSUE TITLE
4.4: Backend font with special characters for non-west languages

### ISSUE THREAD

**Issue by jankout** [contao/core#8732]
Hello, 

I like the new design of 4.4.x 

For non-west languages is important to use the extended version of the font Lato to show the special characters correctly. That means e.g. **Lato:300,400,700&amp;_subset=latin-ext_**. Thank you. 

<img width="452" alt="snimek obrazovky 2017-06-18 v 10 36 49" src="https://user-images.githubusercontent.com/3715050/27319701-021ca3ee-5593-11e7-986d-37b7d40c7a94.png">

Best wishes, Jan

**Comment by aschempp** [comment]
I agree. This has already been implemented in Contao Manager (https://github.com/contao/contao-manager/commit/774a2e1b58634b04ecfd2e3ddb398c6d00c90c15)

**Comment by jankout** [comment]
Great. Thank you. Could you tell me how I can change it by myself now, please? With the new version I´m not sure how I can do it. Thank you.

**Comment by leofeyer** [comment]
http://www.latofonts.com/

> In addi­tion, they come in two fla­vors: “Lato” with full char­ac­ter set (160−640 KB per font) and “Lato­Latin” with just the Latin char­ac­ters (40−150 KB per font).

And we are using the extended font set already.

**Comment by jankout** [comment]
I've figured out that the appearance is wrong only in the dropdown fields. See the both cases. 
<img width="896" alt="snimek obrazovky 2017-06-20 v 14 01 53" src="https://user-images.githubusercontent.com/3715050/27332252-64b044ce-55c1-11e7-823a-a6f03e930af5.png">
<img width="896" alt="snimek obrazovky 2017-06-20 v 14 01 48" src="https://user-images.githubusercontent.com/3715050/27332253-64c23abc-55c1-11e7-82f9-b6b5d0e3876c.png">

**Comment by leofeyer** [comment]
Which browser and OS?

**Comment by jankout** [comment]
macOS 10.12.5, Safari.

**Comment by leofeyer** [comment]
Works like a charm on my system (macOS 10.12.5, Safari).

![](https://user-images.githubusercontent.com/1192057/27550372-b4bfba84-5a9f-11e7-87bc-1b0f2c851bac.png)

**Comment by jankout** [comment]
But not with Czech characters

Jan Kout

-------------------
+4917645799488
www.jankout.eu 

26. 6. 2017 v 18:47, Leo Feyer <notifications@github.com>:
