### ISSUE TITLE
Nachrichten-Artikel wird bereits vor dem Speichern veröffentlicht

### ISSUE THREAD

**Issue by d3vm4t** [contao/core#8736]
Folgendes Problem (Contao 3.5.2x):
Wird in einem Nachrichtenarchiv ein neuer Artikel erstellt und unter "Veröffentlichung" die Checkbox "Beitrag veröffentlichen" gesetzt, dann wird der Artikel sofort veröffentlicht, ohne dass zuvor auf Speichern geklickt wird. Man sieht also im Frontend den Artikel bereits veröffentlicht nach dem die Checkbox angeklickt wurde (keine Preview-Ansicht, sondern auch auf einem beliebigen anderen Gerät sichtbar).
Das ist natürlich nicht gut, falls man den Artikel erst ab einem späteren Zeitpunkt veröffentlichen will. Aber damit das Feld "Anzeigen ab" erscheint, muss ja erstmal die Checkbox gesetzt werden.

Können andere das so nachvollziehen oder ist das sogar das gewünschte Verhalten?
Besten Dank im Voraus.

**Comment by fritzmg** [comment]
Kann ich nachvollziehen. Früher hatte man das Problem noch nicht, da das Anzeigen ab/bis keine Subpalette war.

**Comment by leofeyer** [comment]
@contao/developers /cc

**Comment by aschempp** [comment]
Am einfachsten wäre es wohl Start & Stop wieder aus einer Subpalette raus zu nehmen…

**Comment by Toflar** [comment]
Nö, die findByPublished müsste einfach auch tstamp>0 machen im Model?
