### ISSUE TITLE
4.4: Error Forward page. In Lightbox no radio buttons

### ISSUE THREAD

**Issue by jankout** [contao/core#8737]
When I create a forward page with internal link and want to add the link with the lightbox no radio buttons appear. See video
![forward page ligtbox no radio buttons](https://user-images.githubusercontent.com/3715050/27576715-3f62c734-5b1e-11e7-81d7-d359ef69802f.gif)

**Comment by aschempp** [comment]
Duplicate of https://github.com/contao/core-bundle/issues/883
