### ISSUE TITLE
Fehler in Modul "Artikelliste" bei 4.4. und PHP 5.6

### ISSUE THREAD

**Issue by madi84** [contao/core#8739]
Bei Version 4.4. und PHP 5.6 erscheint auf Seiten die das Modul "Artikelliste" enthalten der folgende PHP Fehler:

> Parse error: syntax error, unexpected '->' (T_OBJECT_OPERATOR), expecting ')' in /.../vendor/contao/core-bundle/src/Resources/contao/modules/ModuleArticleList.php on line 114

Mit PHP 7.1 funktioniert es.

**Comment by fritzmg** [comment]
Btw. Fehler des core-bundles von Contao 4.4 sollten hier reported werden: https://github.com/contao/core-bundle/issues

**Comment by leofeyer** [comment]
Also PhpStorm hat damit kein Problem. Bist Du sicher, dass Du PHP 5.6 hast?

**Comment by madi84** [comment]
Hi leofyer, ja, war auf PHP 5.6-latest eingestellt (5.6.21). Nach Umstellung auf PHP 7.1 läuft es wieder.

@fritzmg: Hast Recht, kann ihn leider nicht mehr löschen oder verschieben

**Comment by ausi** [comment]
Kann ich bestätigen, die Syntax schein erst seit PHP 7.0 erlaubt zu sein.

Kurzer Test der Syntax: <https://3v4l.org/DVi1e>
