### ISSUE TITLE
Fehlerhafte E-Mail-Adressvalidierung?

### ISSUE THREAD

**Issue by Wagnerwagner** [contao/core#8740]
Hallo zusammen in den letzen Tagen ist es in einer von uns genutzten Contao Installation dazu gekommen, dass E-Mail nicht versendet wurden. Eine kurze Recherche hat ergeben, dass von den Nutzern E-Mail-Addressen mit Umlauten und Sonderzeichen im Local-Teil der Adresse verwendet wurden

z.B. íchsehekorrektauß@binesaberni.ch

Im System-Log finden sich dem entpsprechend folgende Einträge:

`Could not send email for message ID 2: Address in mailbox given [íchsehekorrektauß@binesaberni.ch] does not comply with RFC 2822, 3.6.2.`

Es scheint wohl so zu sein, dass die Validierung mehr durchlässt als der Mailer verträgt. 

P.S. Die HTML5 Validierung erkennt die Fehlerhafte E-Mail-Adresse in der Regel.

![pbgadmjleahagfhb](https://user-images.githubusercontent.com/7679272/27919756-ca9673b8-6272-11e7-816a-9f3376a5a20c.png)

**Comment by leofeyer** [comment]
Laut unserem [Validator](https://github.com/contao/core-bundle/blob/master/tests/Contao/ValidatorTest.php#L60-L107) wäre das auch eine korrekte E-Mail-Adresse. @contao/developers Müssen wir eventuell am Mailer etwas anpassen?

**Comment by ausi** [comment]
AFAIK UTF-8 email addresses are allowed by [RFC 6531](https://tools.ietf.org/html/rfc6531) but not allowed by [RFC 2822](https://tools.ietf.org/html/rfc2822).

If we want the same validation as Swiftmailer, we can use [egulias/email-validator](https://github.com/egulias/EmailValidator) I think.

The [HTML5 email validation](https://www.w3.org/TR/2016/REC-html51-20161101/sec-forms.html#valid-e-mail-address) checks against the regex ``/^[a-zA-Z0-9.!#$%&'*+\/=?^_`{|}~-]+@[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?(?:\.[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?)*$/`` which is not compliant with any RFC.

**Comment by Toflar** [comment]
Swiftmailer internally uses egulias/email-validator so we might as well just ask Swiftmailer if the e-mail is valid (if the interface for that exists). Looks like this has been fixed in 6.0 but we cannot use this because of PHP 7 as a minimum requirement... (see https://github.com/swiftmailer/swiftmailer/issues/608)

**Comment by leofeyer** [comment]
We actually want SwiftMailer to use the RFC 6531 validation, don't we?

**Comment by leofeyer** [comment]
https://github.com/swiftmailer/swiftmailer/issues/419 seems related.

**Comment by leofeyer** [comment]
SwiftMailer supports RFC 6531 in version 6, however, SwiftMailer 6 only supports PHP 7, so we can only fix this in Contao 4.5.

**Comment by leofeyer** [comment]
Fixed in contao/core-bundle@a1f0fe1e656410c5368764d98a1c56ac48a14f0d.
