### ISSUE TITLE
Contao 4.4.x: Frontend fehlerhafte Ausgabe bei Verwendung ce_list und ce_text mit Listen

### ISSUE THREAD

**Issue by dguelden** [contao/core#8741]
Neue und frische Installation mit Conato 4.4.0 als "managed-edition".
Im BE funktioniert die Erstellung von un-/nummerierten Listen als **ce_list** bzw. unter **ce_text** wie gewohnt, und die Ausgabe im BE ist auch in Ordnung. Jedoch im Frontend wird keine Nummerierung ausgegeben bzw. die Bullet's fehlen ebenso. Extra Definitionen im CSS schaffen ebenso keine Abhilfe.

**Comment by fritzmg** [comment]
Wenn das HTML der Frontend Ausgabe korrekt ist, handelt es sich nicht um einen Bug in Contao. Ist das der Fall? Wenn ja, dann kannst du im Community Forum um Hilfe suchen.

**Comment by dguelden** [comment]
"Solved". Liegt tatsächlich am CSS-Reset im Layout, mit dem es bis dato keinerlei Probleme gab. Nachdem dies deaktiviert ist, werden die Nummerierungen und Bullets im Frontend ganz normal wieder angezeigt, und auch die Definitionen für Listen im separaten CSS greifen wieder.
Danke für den Hinweis Aybee.

**Comment by BugBuster1701** [comment]
Ich benutze das CSS Reset auch, und da wo benötigt setze ich die Bullets wieder mit !important Zusatz.

PS: Du kannst das Ticket hier selber schließen.

**Comment by Aybee** [comment]
Wieso !important? Der Selector hat eine so niedrige Specificity, dass man es sofort überschreiben kann. Und wenn dein CSS nach dem Reset kommt, welches der Fall sein sollte, dann braucht man noch nicht mal ne höhere Specificity.

Hier das Contao Reset.
```css
ul, 
ol {
  margin: 0 0 12px;
  list-style-type: none;
}
```
