### ISSUE TITLE
unallowed download-types appear in the filepicker when inside a collapsed folder

### ISSUE THREAD

**Issue by asaage** [contao/core#8744]
Just a minor bug for me - especially as the picker is currently beeing worked on - but it might occur in contao 4 too - please check.

steps to reproduce:
- have a file in SubfolderA with a file-extension wich is not listed in allowed download-types
- make shure your fileTree is collapsed
- create a download-contentelement

if the picker appears and you expand SubfolderA you will be able to select that file

I bet it's ajax-related because if the folder is already expanded it works as expected.
https://github.com/contao/core/blob/master/system/modules/core/dca/tl_content.php#L1631

**Comment by aschempp** [comment]
This will be fixed with contao/core-bundle#950
