### ISSUE TITLE
Remove $_SERVER['REMOTE_ADDR'] usage in Environment::ssl() when evaluating X-Forwarded-Proto

### ISSUE THREAD

**Issue by Whissi** [contao/core#8745]
The idea behind pr #8691 to trust only known proxies isn't bad but breaks compatibility with [mod_remoteip](https://httpd.apache.org/docs/current/mod/mod_remoteip.html) or [mod_cloudflare](https://www.cloudflare.com/static/misc/mod_cloudflare/mod_cloudflare.c) for example. And sometimes you don't even know your AWS ELBs (see https://symfony.com/doc/current/request/load_balancer_reverse_proxy.html#but-what-if-the-ip-of-my-reverse-proxy-changes-constantly).

Please consider the following changes:

1. Out of the box, Contao shouldn't use `X-Forwarded-Proto`. There should be a config option to enable `X-Forwarded-Proto` usage.
3. When enabled, `X-Forwarded-Proto` should be considered as trusted because any load balancer is supposed to remove/replace any existing `X-Forwarded-Proto` header.

**Comment by leofeyer** [comment]
I'm against changing the behavior of the `Environment` class in Contao 3.5, because I consider this a new feature with unforeseeable effects.

Does the issue occur in Contao 4.4 as well?

**Comment by aschempp** [comment]
Well… I was against adding support for `X-Forwarded-Proto` in [Contao 3.5.26](https://github.com/contao/core/pull/8691), **because of unforeseeable effects** …

**Comment by leofeyer** [comment]
@Whissi You can simply unset the header in your `initconfig.php` file, can't you?

**Comment by Whissi** [comment]
Yes, I can unset `$_SERVER['HTTP_X_FORWARDED_PROTO']` in `initconfig.php`.

But I am suggesting to revert the whole thing. It is flawed: Like others have already shown, you shouldn't trust `X-Forwarded-Proto`. An application which will use this variable out-of-the box when available will be vulnerable to the problem which caused the HTTPOXY vulnerability.

`X-Forwarded-Proto` is something which will be set by the load balancer. If your web server is behind such a load balancer and your load balancer also terminates HTTPS traffic from the outside (remember this is not always the case!) then you should set something like `SetEnvIf X-Forwarded-Proto "^https$" HTTPS=on` in your web server configuration (however, double check that your load balancer unset/overwrite any existing `X-Forwarded-Proto` header!).

In PHP world, relying on `$_SERVER['HTTPS'] == on` is the only way to go. While http://php.net/manual/en/reserved.variables.server.php is misleading (i.e. PHP authors copied description of HTTP environment variables from Apache's documentation for the first version), this variable isn't set by PHP itself. It comes through various SAPIs. Common web servers (Apache, nginx, lighttpd, IIS) are all exporting `HTTPS` variable, so this should be the only way to go.

And like you are asking me to unset `$_SERVER['HTTP_X_FORWARDED_PROTO']`, one could also set `$_SERVER['HTTPS'] = 'on'` in `initconfig.php` ;)

**Comment by ausi** [comment]
> Out of the box, Contao shouldn't use `X-Forwarded-Proto`. There should be a config option to enable `X-Forwarded-Proto` usage.

This is already the case, Contao ignores `X-Forwarded-Proto` by default because `proxyServerIps` is empty by default.

> When enabled, `X-Forwarded-Proto` should be considered as trusted because any load balancer is supposed to remove/replace any existing `X-Forwarded-Proto` header.

This is also the case already. If you set `proxyServerIps`, Contao uses the `X-Forwarded-Proto` header if the remote address matches.

If you don’t know the IP addresses of your proxy servers and you are sure that your server and load balancer setup is secure, you can just set `proxyServerIps` to `$_SERVER['REMOTE_ADDR']`.

**Comment by Toflar** [comment]
We could fix this the same way SF does, no? Just allow `proxyServerIps` to be set to `*`.

**Comment by leofeyer** [comment]
> Does the issue occur in Contao 4.4 as well?

@Whissi You did not answer my question.

**Comment by Whissi** [comment]
Sorry, I currently don't have a Contao 4.x behind a load balancer (only 3.x). But I don't see a reason why unset shouldn't work in 4.x like it is working in 3.x. But as said, I still would suggest to remove this feature because it doesn't belong into the application.

**Comment by leofeyer** [comment]
Ok, I'm closing the ticket then, because there won't be any more behavior changes in Contao 3.5 and we don't know if the problem still exists in Contao 4 (if it does, I'll reopen the ticket).
