### ISSUE TITLE
\Controller redirect throws Exception -> Why?

### ISSUE THREAD

**Issue by Defcon0** [contao/core#8746]
Hello,

since Contao 4 \Controller::redirect  seems to be rewritten in an odd way. For some reason, the function throws an exception:

`throw new RedirectResponseException($strLocation, $intStatus);`

This is pretty bad if the function is in a try-block that catches Exceptions.

What's the point in changing the old function to this one?

**Comment by fiedsch** [comment]
I had that problem in one of my extensions too. It happens if  `$intStatus` is not a `3xx` (redirect) code.

**Comment by Defcon0** [comment]
Since I don't give in any $intStatus, this shouldn't be any problem, right? The problem is that for some reason an **exception** is thrown in redirect(). If this redirect() is called in a try {} - block catching \Exception, we have a problem.

**Comment by fritzmg** [comment]
@fiedsch he means the `core-bundle`. Look at the current implementation:
```php
/**
 * Redirect to another page
 *
 * @param string  $strLocation The target URL
 * @param integer $intStatus   The HTTP status code (defaults to 303)
 */
public static function redirect($strLocation, $intStatus=303)
{
	if (headers_sent())
	{
		exit;
	}

	$strLocation = str_replace('&amp;', '&', $strLocation);
	$strLocation = static::replaceOldBePaths($strLocation);

	// Make the location an absolute URL
	if (!preg_match('@^https?://@i', $strLocation))
	{
		$strLocation = \Environment::get('base') . ltrim($strLocation, '/');
	}

	// Ajax request
	if (\Environment::get('isAjaxRequest'))
	{
		throw new AjaxRedirectResponseException($strLocation);
	}

	throw new RedirectResponseException($strLocation, $intStatus);
}
```
For some reason the redirects are implemented as exceptions. I am guessing it is done this way, so that you can create redirects anywhere, without having to return and process actual responses - which is a required feature within the Contao framework.

@Defcon0 issues about the `core-bundle` should go to https://github.com/contao/core-bundle ;)

**Comment by Toflar** [comment]
> For some reason the redirects are implemented as exceptions. I am guessing it is done this way, so that you can create redirects anywhere, without having to return and process actual responses

Exactly. If your try-catch block catches all exceptions, your try-catch block is wrong. In 99.9% of all cases, you should never catch `Exception` but `MySpecificProblemException`.

**Comment by leofeyer** [comment]
If you need to catch all exceptions, try the following:

```php
try {
    // …
} catch (RedirectResponseException $e) {
    throw $e;
} catch (\Exception $e) {
    // …
}
```

**Comment by aschempp** [comment]
@Defcon0 and follow-up on @fritzmg: The redirects are implements as exceptions so they are correctly handled by the Symfony framework. Symfony follows a request-response concept, so we need to send a response based on the request. Exiting the script with some headers is not a valid solution.

**Comment by Defcon0** [comment]
Ah,  I see, thanks guys for the clearification!

**Comment by fritzmg** [comment]
> If your try-catch block catches all exceptions, your try-catch block is wrong. In 99.9% of all cases, you should never catch Exception but MySpecificProblemException.

```php
try
{
	…
}
catch (\Exception $e)
{
	…
}
```
is used in Contao quite a lot though ;)

**Comment by Toflar** [comment]
Yes. Which does not make it right ;) There are many things in Contao that are wrong or could be done better. Like in any software that is older than 10 years :P

**Comment by fritzmg** [comment]
I know, I am not criticizing ;). Just wanted to point it out in case anyone wants to do
```php
\Controller::redirect()
```
in "unusual" places. Those try catch blocks might need to be modified then.

**Comment by Defcon0** [comment]
Good to know anyway, thanks!
