### ISSUE TITLE
Issue with Colorbox and activatet Basic Form Css

### ISSUE THREAD

**Issue by Floxn** [contao/core#8747]
You can reproduce the issue if you activate the Basic Form CSS Framework at 2 Column Layout. Open [this Site](https://demo.contao.org/en/media-elements.html) and klick one picture to open the lightbox. Now move your pointer over the closing button. 
![bildschirmfoto 2017-07-14 um 10 41 30](https://user-images.githubusercontent.com/15326334/28205585-ee448eb0-6882-11e7-8ce0-d5dd68fc96ca.jpg)

I think this should be the problem in [this file](https://github.com/contao/core/blob/master/assets/contao/css/form-uncompressed.css#L119)
> button:hover,input[type="submit"]:hover,.button:hover {
	text-decoration:none;
	background-position:0 -15px !important;
}
button:active,input[type="submit"]:active,.button:active {
	background-color:#e6e6e6;
	background-position:0 -30px !important;
}

**Comment by fritzmg** [comment]
I don't see the issue on the contao demo. Also the styles you referenced do not actually exist?

**Comment by Floxn** [comment]
now i have activated the Basic Form CSS

**Comment by fritzmg** [comment]
Ok, I see now. The problem is, that in Contao 4 the CSS selector has been changed from `.button` to `button`. See https://github.com/contao-components/contao/blob/7.1.1/css/form.css#L88-L124
May be the form styles should be wrapped by `form`, since a `<button>` can also exist outside of forms.

**Comment by Floxn** [comment]
this works for me

**Comment by leofeyer** [comment]
See https://github.com/contao-components/contao/pull/8
