### ISSUE TITLE
Change field for parentId in mode 4

### ISSUE THREAD

**Issue by bohnmedia** [contao/core#8748]
Hi,

I have problems to generate 2 views in mode 4 based on different parent tables in Contao 3.5.

There are three tables.
- tl_calendar_events
- tl_calendar_tickets
- tl_member

**Case 1**

I created a dca for "tl_calendar_tickets" it contains all tickets for an event.

tl_calendar_events.id = tl_calendar_tickets.pid

I created the DCA in Mode 4 to display the event-details inside the headerFields. It works fine.

**Case 2**

I need a second list of "tl_calendar_tickets" but based on the field member instead of pid.

tl_member.id = tl_calendar_tickets.member

In this list i want to display the member information in headerFields instead of the event-details. I have no idea how to build the dca for case 2 or how to build a dca to contain both cases.

I tried to set the 'filter' in 'sorting'.

`array('member=?', Input::get('member'))`

But it just adds a custom filter. I didnt find a way to overwrite pid.

Another way could be using another mode, but then i am losing my headerFields. It seems, that all other modes are ignoring my header_callback.

Thanks and greetings,
Dennis

**Comment by leofeyer** [comment]
Please refer to the [forums](https://community.contao.org/) for this kind of questions. The issue tracker on GitHub is for reporting bugs or requesting new features.
