### ISSUE TITLE
pages can not be selected in the pagebrowser. Radio buttons are missing.

### ISSUE THREAD

**Issue by premiumcontaothemes** [contao/core#8749]
Problem tritt erst ab der Contao Version 4.4.1 auf.
![bildschirmfoto 2017-07-25 um 14 23 51](https://user-images.githubusercontent.com/12493330/28571830-e68ee178-7144-11e7-9a49-77db4676703b.png)

**Comment by leofeyer** [comment]
Siehe contao/core-bundle#979, contao/core-bundle#965, contao/core-bundle#975 sowie https://contao.org/de/news/contao_4-4-1.html.
