### ISSUE TITLE
No events possible before 1970-1-1

### ISSUE THREAD

**Issue by FRappsil** [contao/core#8754]
Trying to create a birthday list by using the calendar events and just recognized that events dated before 1970-1-1 are automatically saved without any further notice on january 1st, 1970. That's not very helpful for a birthday list. All events after 1970-1-1 are saved at the correct date. Would like to have this changed for our "older" colleagues. ;-)

**Comment by leofeyer** [comment]
See #7438, #8593 and #8509.
