### ISSUE TITLE
Modul Registrierung verwendet für die initiale Version keinen Rückgabewert des Hooks

### ISSUE THREAD

**Issue by philvdb** [contao/core#8755]
Szenario: Selbst-Registrierung von Mitglied im Frontend über das Core-Registrierungsmodul.

Vorgabe: Keine eigene Auswahl des Username durch den User, stattdessen Verwendung der (vom User eingegebenen) E-Mail-Adresse auch als Username.

Dies war bis #7816 wohl mit der sehr simplen Erweiterung [MailUsername](https://contao.org/de/erweiterungsliste/view/mailusername.de.html) von @aschempp leicht machbar.

Nach #7816 gibt es einen Fatal Error, weil für die Anlage der ersten Version des Mitglieds in [ModuleRegistration.php](https://github.com/contao/core/blob/master/system/modules/core/modules/ModuleRegistration.php#L419) als Username (aus meiner Sicht unnötigerweise) `$objNewUser->username` verwendet wird, statt `$arrData['username']`. Letzteres könnte durch ein pass by reference im Hook verändert werden. Damit könnten wir den Fatal Error in diesem Szenario verhindern.

Im aktuellen Zustand seit #7816 gibt es also wenn ich es richtig sehe keinen Weg im Backend um den Fatal Error herum ("Column 'username' cannot be null" beim Schreiben in tl_version - denn `$objNewUser->username` bleibt leer, auch wenn der Username sonst über den Hook in Datenbank und `&$arrData` befüllt wird).

`$objNewUser->username` wird nicht mehr angefasst, nachdem es durch `$objNewUser->setRow($arrData);` gesetzt wurde. Deshalb ist das Ersetzen von `$objNewUser->username` durch `$arrData['username']` beim Anlegen der ersten Version des Eintrags in tl_version aus meiner Sicht ein non-breaking change, der sofort umgesetzt werden kann.  Wenn einverstanden und nötig liefere ich gerne einen pull request.

**Comment by leofeyer** [comment]
@aschempp /cc

**Comment by aschempp** [comment]
@philvdb ein Hardcoding auf den Username halt ich nicht für sinnvoll, weil das mit allen anderen Felder dann ja potentiell weiterhin Probleme gibt. Kannst du testen ob sich das Problem lösen lässt indem `mailusername` sich das `MemberModel` holt und den Username da hineinschreibt? Durch die Model Registry sollte das eigentlich funktionieren.

**Comment by philvdb** [comment]
@aschempp : Danke schon mal für die Antwort!

Der Tipp mit der Registry funktioniert. Hatte zunächst einfach deine Erweiterung übernommen (nach Anpassung an die statische Schreibweise), die ja folgendes machte:

```php
$arrData['username'] = $arrData['email'];
\Input::setPost('username', $arrData['email']);
\Database::getInstance()->prepare("UPDATE tl_member SET username=? WHERE id=?")->execute($arrData['email'], $intId);
```

Wenn ich die letzte Zeile durch
```php
$objMember = \MemberModel::findByPk($intId);
$objMember->username = $arrData['email'];
$objMember->save();
```
ersetze, gibt's wie du vermutest keinen fatal error mehr. Problem insofern gelöst, auch wenn ich weiterhin denke, dass $arrData['email'] bei der Versionserstellung besser wäre.

Denn den ersten Teil deiner Message verstehe ich nicht ganz - "hardcoding auf den username" - und "Probleme mit anderen Feldern". Nur falls wir uns missverstanden haben - es geht ausschließlich um den Teil, wo die Version angelegt wird, sonst soll nichts verändert werden. Beim Anlegen der Version wird der Username ja explizit gesetzt für den Eintrag in tl_version, also der Username als solches ist eh "gehardcoded":

```php
// Create the initial version (see #7816)
$objVersions = new \Versions('tl_member', $objNewUser->id);
$objVersions->setUsername($objNewUser->username); // <-- hier stattdessen $arrData['username'], sonst nirgends!
$objVersions->setUserId(0);
$objVersions->setEditUrl('contao/main.php?do=member&act=edit&id=%s&rt=1');
$objVersions->initialize();
```

Ich verstehe nicht genau was du meinst mit den anderen Feldern, bei denen es "potentiell weiterhin Probleme gibt".

Also ab jetzt ist's nur noch ein "Schönheitsfehler", die model registry rettet meinen use case (/unseren, denn @aschempp hatte ja für diesen immerhin eine Erweiterung erstellt).

Vielen Dank nochmal für's Anschauen!

**Comment by aschempp** [comment]
Interestingly though, this has already been fixed in the latest version! 😂 
https://github.com/terminal42/contao-mailusername/issues/7

**Comment by leofeyer** [comment]
Müssen wir jetzt im Core irgendetwas ändern oder nicht?

**Comment by philvdb** [comment]
@aschempp : Huch! Hatte dein Modul aus dem Contao-ER heruntergeladen aber da offensichtlich eine alte Version gegriffen. Sorry.

@leofeyer : Müssen aus meiner Sicht nicht, die registry macht einen workaround gangbar. Besser fände ich's immer noch aber es ist sicher nicht viele weitere graue Zellen oder Haare wert ;)

Kann sonst gerne geschlossen werden, danke für die prompte Reaktion & Zeit. Immer wieder froh, Contao zu verwenden.
