### ISSUE TITLE
Multiple forms in a Single Page

### ISSUE THREAD

**Issue by UB3RL33T** [contao/core#8756]
I have a Contao 3.5.17 installation with multiple forms on the contact-page. Each form is sending the contact request to a different department. This serves the purpose of speeding up the processing time of the contact requests. 
The forms are nested inside accordions, one accordion for each department. 

The Issue I'm having presents as followed:
If a form is sent, it does not matter which, the form sent by Contao is always the first one implemented on the page, instead of the one that was actually sent. 

If the forms are implemented as followed:

- Management
- Shopping
- Marketing
- personnel
- other

It does not matter which form is being sent by the user, the form chosen by contao is always management.
I've been searching the contao forum and the issues here on github but I can't find anything that describes my issue.

Is there anything known about this kind of behaviour or am I missing something?
I am using the EFG-Extension.

**Comment by fritzmg** [comment]
Does this issue occur without EFG too?

**Comment by UB3RL33T** [comment]
Yes, I just tested it without EFG. The behaviour has not changed.

**Comment by asaage** [comment]
Check if each form has its own id and submit-input!

**Comment by UB3RL33T** [comment]
The forms were created by the formgenerator provided by contao, each with its own id and submit.

I did however go ahead and trying to duplicate this behaviour on another contao installation (3.5.27).
With Success: 
I created 3 simple forms in the formgenerator with the inputfields name, email, a textarea for a message and a submit. Then I implemented them in one page. The behaviour is identical to what i described earlier.

The input is transmitted properly for each form, but the values for recipient address as well as the subject are always the ones from the form that is found first in the HTML markup.

**Comment by amenk** [comment]
Disclaimer: I am a colleague of UB3RL33T :-)
I am wondering of this supposed to work technically if it would work? Should the ID be included in the form? Cause the ID does not seem to be in the `$_REQUEST`

**Comment by UB3RL33T** [comment]
Upon taking a closer look, it seems as if the value of the hidden field _request_token_ is the same for each form.

**Comment by ausi** [comment]
AFAIK every Contao form has a `FORM_SUBMIT` hidden field to distinguish between multiple forms on a single page.

**Comment by amenk** [comment]
This does not seem to be there in our tests.

**Comment by ausi** [comment]
The form should always be there as you can see in the form template: [system/modules/core/templates/forms/form.html5:12](https://github.com/contao/core/blob/977f7ff10d5606f48e97f55d7c39facf114ceedb/system/modules/core/templates/forms/form.html5#L12).

**Comment by amenk** [comment]
Right, thanks - FORM_SUBMIT is there - but always `auto_tl_form` - for each form.

**Comment by ausi** [comment]
The FORM_SUBMIT gets set in [system/modules/core/forms/Form.php:100](https://github.com/contao/core/blob/977f7ff10d5606f48e97f55d7c39facf114ceedb/system/modules/core/forms/Form.php#L100). Did you set the `formID` to `tl_form` for all your forms?

**Comment by UB3RL33T** [comment]
That did it. The Field Form ID was set to tl_form in each form. Likely due being created once and duplicated, like I did testing it. 

@asaage I think that is what you meant? Sorry, I thought you meant the ID set in the HTML markup for the form-tag.

Thank you all very much. Sorry for causing trouble.

**Comment by ausi** [comment]
> The Field Form ID was set to tl_form in each form. Likely due being created once and duplicated, like I did testing it.

That’s a bug then I think. Duplicating the form should not copy the formID.

Maybe we should add `'doNotCopy'=>true` to [system/modules/core/dca/tl_form.php:258](https://github.com/contao/core/blob/977f7ff10d5606f48e97f55d7c39facf114ceedb/system/modules/core/dca/tl_form.php#L258) ?

**Comment by asaage** [comment]
> Maybe we should add 'doNotCopy'=>true to system/modules/core/dca/tl_form.php:258 ?

👍 
reopen or create a new ticket!
but ```doNotCopy=>true``` does not imply unique right?
```unique=>true``` needs also to be added.

on the other hand i personally never used this field and it also does not populate its auto-incement-value in the BE.
I wish i knew the purpose of this option.
*"Die Formular-ID wird zur Ansteuerung eines Contao-Moduls benötigt."* i was not able to find documentation or examples :(

**Comment by Toflar** [comment]
@asaage You can e.g. create a search form, place it anywhere in the layout and specify `tl_search`. That will cause the search module to be triggered in case it's placed on the same page.

**Comment by leofeyer** [comment]
Fixed in 8806c2662c09fcec01bc5101b8d478ba8355ce5f.
