### ISSUE TITLE
Behavior of captcha validation different from other field validations

### ISSUE THREAD

**Issue by Anke** [contao/core#8757]
If mandatory form fields haven't been filled out correctly or at all, I get instant error messages and nothing happens when clicking on the submit button. 

Not answering the captcha question is also showing an instant error message and nothing will happen when hitting submit.

However if the captcha field contains a wrong answer, the page will be reloaded on hitting submit and only then the error message will be displayed. That's very inefficient when using long forms, content tabs, accordions etc. Isn't it possible to check the captcha answer e.g. when losing focus? (Customers consider this an error, losing orders based on this problem, as FE users often don't realize something went wrong.)

**Comment by fritzmg** [comment]
The server needs to check the captcha. You will need to implement this yourself.

**Comment by asaage** [comment]
I suggest you turn off the captcha.
with client-side scripting you most likely wont be able to imitate the html5-form-validation accross browsers.
For spam-protection you might use something like **honeypot** in case you realy need that.

**Comment by Anke** [comment]
Thank you, that's a helpful lead ...
