### ISSUE TITLE
Character counter for title and description

### ISSUE THREAD

**Issue by tpk109** [contao/core#8758]
A js character counter for title and description in pages would be handy

**Comment by aschempp** [comment]
Die Erweiterung [inputcount](https://contao.org/de/erweiterungsliste/view/inputcount.10060009.de.html) konnte sowas mal.

**Comment by xchs** [comment]
Die Erweiterung "[SEO SERP Vorschau](https://contao.org/de/erweiterungsliste/view/seo_serp_preview.de.html)" kann das m. W. auch. Zumindest für das Feld "Beschreibung".
