### ISSUE TITLE
CSS Stylesheet, Box-Sizing Model

### ISSUE THREAD

**Issue by marcfunkitug** [contao/core#8760]
Es wäre in Zeiten von Responsive Webdesign sicherlich sinnvoll, wenn man eine Auswahlmöglichkeit hat zum Thema "Box-Sizing". Bisher tragen wir das immer im Feld "Eigener Code" ein.

A new feature like "Selection of Box-Sizing", because we wrote down the code under "self code".

**Comment by fritzmg** [comment]
This would be a new feature, which would only be added in Contao 4. But I think internal stylesheets are deprecated there.

**Comment by marcfunkitug** [comment]
I dont write the Contao version but i mean the feature for Contao 4 ;)

But what do you mean with "deprecated"? The CSS Editor in Contao...will it be remove?

**Comment by leofeyer** [comment]
> The CSS Editor in Contao...will it be remove?

Maybe at some point. At least it is not further developed.

**Comment by marcfunkitug** [comment]
Will be there a new CSS-Editor in Contao 4 or only an import for css?

**Comment by leofeyer** [comment]
We are supporting SCSS and LESS in both Contao 3 and Contao 4. You can manage the style sheets in the file manager.
