### ISSUE TITLE
Frontend-Vorschau als Mitglied wenn Benutzername Sonderzeichen enthält

### ISSUE THREAD

**Issue by Mynyx** [contao/core#8762]
Wenn man im Backend über die Mitgliederliste die Frontend-Vorschau als Mitglied aufruft und der Benutzername des Mitgliedes Sonderzeichen wie ````&```` enthält, funktioniert dies nicht und es wird die Frontend-Vorschau als Gast angezeigt.

Warum wird hier eigentlich der Benutzername als Parameter übergeben und nicht die ID des Mitglieds?

**Comment by leofeyer** [comment]
Weil es viel einfacher ist, den Benutzernamen in der URL zu ändern als die ID. Kannst Du bitte prüfen, ob contao/core-bundle@052b327347391c8778dc34e514623e80936ed51a das Problem für Dich behebt? Dann würde ich den Fix zurück portieren.

**Comment by Mynyx** [comment]
Den Benutzernamen kann man allerdings auch ganz einfach mit der Frontend-Vorschau Symbolleiste ändern. Mit dem Fix funktioniert es nun jedenfalls.

**Comment by leofeyer** [comment]
Behoben in e2d9af8f215615d5f78148ffc58102b6c14d2b97.
