### ISSUE TITLE
IE Menu Fehler beim Reader (News/Event)

### ISSUE THREAD

**Issue by DEGROUP** [contao/core#8763]
Hello,
es gibt folgenden Bug im IE.

Wenn man im IE von der Home ein Projekt anklickt und und in den Projekt Details ist, also im "portfolio-reader" und danach auf einen der Hauptmenupunkte klickt bekommt man eine Fehlermeldung.

In der URL steht noch "portfolio-reader" was nicht der Fall sein sollte!

Anbei die Details, wir haben das Problem mit folgendem Template:

Klicke ich auf folgender Seite:
www.specialty-structures.com

Auf eines der Projekte komme ich auf:
www.specialty-structures.com/portfolio-reader/projektname.html

Klicke ich dann auf einen Menupunkt, z.B. "Projects" lande ich bei allen Browsern wieder auf der Startseite, ausser im IE. Hier ist im Link noch "/portfolio-reader/" vorhanden.

Anbei auch das Feedback des Templateherstellers:
Ich habe es auf Safari, Chrome, Firefox und Opera auf dem Mac getestet. 
Des Weiteren auf IE, Firefox und Chrome auf Windows.

Der einzige Browser, bei dem der Fehler auftritt, ist der IE. 

Hierbei wird eine falsche URL im Menü erzeugt. Das erzeugen der URL ist ein Vorgang, der unabhängig der Gestaltung der Menüpunkte ist. 
Das passiert im Kern des Systems.

Sie müssten diesen Bug bei den Contao Entwicklern im Github melden.

Vielen, lieben Dank vorab!

**Comment by asaage** [comment]
Der Fehler liegt nicht bei Contao (oder der Erzeugung falscher URL's im Menü) sondern in den vom "Templatehersteller" eingesetzten Javascripts.

```js
// Auf der Detailseite in der js-console:
$(".animsition-link").unbind("click");
// und die Links funktionieren...
```
Ist wohl eher ein Bug von https://github.com/blivesta/animsition - welches mit dem ```<base>``` tag nicht zurande kommt vermute ich.

**Comment by fritzmg** [comment]
@DEGROUP this is a general problem of animsition and would occur within any framework, where the `<base href…>` is used. See also https://community.contao.org/de/showthread.php?67661-Ordner-URLs-werden-beim-Internet-Explorer-immer-neu-angehängt
