### ISSUE TITLE
Sprachen von Transifex können nicht mehr geladen werden

### ISSUE THREAD

**Issue by baumannsven** [contao/core#8764]
Wenn ich per CLI die Sprachen nach installieren möchte, bekomme ich keine mehr.

`tx pull --all`

`New translations found for the following languages:el, zh, vi, is, it, ar, cs, et, id, es, ru, nl, pt, nb, tr, lv, lt, rm, ro, pl, ta, fr, de, ku, pt_BR, hr, zh_TW, da, fa, hi, bs, fi, hu, ja, sr, sq, ko, sv, sk, uk, sl, my
Pulling new translations for resource contao.v3_5-calendar-default (source: system/modules/calendar/languages/en/default.xlf)
 -> el: system/modules/calendar/languages/el/default.xlf
Exception`

**Comment by bytehead** [comment]
`DecodeError: ('Received response with content-encoding: gzip, but failed to decode it.', error('Error -2 while decompressing: inconsistent stream state',))`

**Comment by leofeyer** [comment]
Den Fehler musst Du bei Transifex reporten. Wir können da wenig tun.
