### ISSUE TITLE
Module comments saves tl_page as source... why not tl_module?

### ISSUE THREAD

**Issue by kaeptn2lvl** [contao/core#8765]
There seems to be an difference between the ce_element and the module
ce_element saves tl_content as source, but the module saves tl_module
why is that? 
we are extending comments to use the notification center as notify system... and the usage of comments as a include module, not having the “right” source, makes it very hard to retrieve associated params stored in tl_module tbl ... (as there is no reference in tl_page for the included comments module)
in our extended version it does not seem to make any difference if one uses tl_module as source reference (and of course the according id...) 

but we might not have the full picture of the contao core. and we don´t want to break std. behavior of the comments with our extension... so it would be great if someone could explain why "tl_page" is used as reference. And if this should be necessary (because other contao parts are depending on it) , how we can get the reference to module..

**Comment by leofeyer** [comment]
Please refer to the [forums](https://community.contao.org/en/) for this kind of question.

**Comment by kaeptn2lvl** [comment]
thx, we will.  it seemed odd...
