### ISSUE TITLE
CSS editor save section changes without explict save operation

### ISSUE THREAD

**Issue by Peter1001** [contao/core#8767]
When editing CSS using the CSS editor it immediately saves the changes when toggling the sections (`Position`, `Border`, `Background` ...) on/off. Although I use the **Back** button in Contao CSS editor to revert my changes this decision is stored and thus the setting of the specific section are present or not depending on my last section toggle selection.
In contrast to this changing a single value is not kept when going back which is correct behavior.

_Bevahior detected on 3.5.28._

**Comment by fritzmg** [comment]
I think this is simply a known limitation.
