### ISSUE TITLE
Calendar produces wrong link to page for prev/next month

### ISSUE THREAD

**Issue by Peter1001** [contao/core#8768]
When using the calendar (here `cal_mini`) the link generated for the buttons **prev**/**next** are pointing to the current page instead to the target page. The links for the single days are correct.

The bug seems to be in `/system/modules/calendar/modules/ModuleCalendar.php `in function `compile()`:
`  $objTemplate->prevHref = $this->strUrl` ...
instead of
`  $objTemplate->prevHref = $this->strLink` ...

The same problem exists for `nextHref`.

_Problem found in 3.5.28._

**Comment by fritzmg** [comment]
That's intentional. The target page is for the news list.

**Comment by Peter1001** [comment]
In the module configuration for the calendar you also can specify a target (redirection) page.
It works using this target page for the links for each of the days (with event behind) in the calendar correctly but not for prev/next month.

The code in `compileWeeks()` uses this target page:
` $arrDays[$strWeekClass][$i]['href'] = $this->strLink` ...

I already locally tried the proposed correction above and it works as expected.

**Comment by asaage** [comment]
> It works using this target page for the links for each of the days (with event behind) in the calendar correctly but not for prev/next month.

Why should you want to go to another page while you flick through a calenders next/prev months?
For me that does not make sense.

**Comment by fritzmg** [comment]
> In the module configuration for the calendar you also can specify a target (redirection) page.
> It works using this target page for the links for each of the days (with event behind) in the calendar correctly but not for prev/next month.

No, you misunderstood me. The target page within the calendar module is for the page, where you integrated a news list module - so that the calendar module can redirect to that page, whenever you click on a day/event in the calendar. And then on the target page, it would list all events of that day.
