### ISSUE TITLE
Das deaktivieren von Modulen ermöglichen

### ISSUE THREAD

**Issue by informatikTirol** [contao/core#8770]
Bei Contao 3 war es möglich mit .skip ein Modul zu deaktivieren.
Aus mehreren Gründen sehr praktisch und sinnvoll. 

Bitte auch unter Contao 4

**Comment by aschempp** [comment]
Das funktioniert in Contao 4 (Managed Edition) für Module in system/modules weiterhin, du musst lediglich den Cache löschen.

**Comment by informatikTirol** [comment]
Danke für die Info! Für "Bundle Module" sollte das aber auch möglich sein...

**Comment by aschempp** [comment]
An einer entsprechenden Funktion wird im Zusammenhang mit dem Contao Manager bereits gearbeitet. Dazu gibt's schon ein Ticket.

**Comment by leofeyer** [comment]
https://github.com/contao/contao-manager/issues/28

**Comment by informatikTirol** [comment]
Vielen Dank, hab danach gesucht, nicht gefunden..
