### ISSUE TITLE
Contao 4.4.2, aktivierter Cache -> sofortiger Logout bei Frontendvorschau

### ISSUE THREAD

**Issue by informatikTirol** [contao/core#8771]
Sobald ich unter Contao 4.4.2 bei aktiviertem Frontendcache das Frontend aufrufe, werde ich sofort im Backend ausgeloggt. 
Erst wenn ich den Cache lösche bleibe ich eingeloggt..

**Comment by leofeyer** [comment]
Siehe #8528 und #8705.

**Comment by informatikTirol** [comment]
Beide Tickets haben meiner Meinung damit nichts zu tun.. 
Wenn ich im aktiviertem Seitencache das Frontend (auch per Frontendvorschau) aufrufe werde ich sofort aus dem Backend ausgeloggt.. Ich logge mich im Frontend nie ein.. 
Z.B ist das Benutzen des Rocksolid Frontend Helper nur möglich wenn man davor den Cache löscht und dann deaktiviert..

**Comment by leofeyer** [comment]
Du hast Recht, da habe ich die falschen Tickets verlinkt. Es ist eigentlich ein Duplikat von contao/core-bundle#1003.

**Comment by informatikTirol** [comment]
Danke!
