### ISSUE TITLE
3.5.28: Problem with SSL

### ISSUE THREAD

**Issue by design23** [contao/core#8772]
Hi there,

Contao: 3.5.28
PHP 7

Had some problems when hoster activated SSL -> page delivered mixed content (https & http).
Hoster has been contacted and their solution was to change line 319 in system/core/library/Contao/Environment.php

`return ($_SERVER['SSL_SESSION_ID'] || $_SERVER['HTTPS'] == 'on' || $_SERVER['HTTPS'] == 1);`

was changed to 

`return ($_SERVER['SSL_SESSION_ID'] || $_SERVER['HTTPS'] == 'On' || $_SERVER['HTTPS'] == 1);`

So they only changed the value "on" to "On". 

Our workaround - as suggested [here](https://community.contao.org/de/showthread.php?67794-Problem-mit-SSL):
In system/config/initconfig.php:

`if ($_SERVER['HTTPS'] == 'On') 
{ 
    $_SERVER['HTTPS'] = 'on'; 
}  `

**Comment by BugBuster1701** [comment]
On my server is the value "on", not "On". 
Here should then be tested for both variants.
Or so: `strtolower($_SERVER['HTTPS']) == 'on'`

**Comment by leofeyer** [comment]
I have never seen a server using `On` with an uppercase first letter. What OS and PHP version are you running?

**Comment by design23** [comment]
Can't really tell you that. I don't know what OS they are using, but I know it uses PHP 7.
Personally, I have never seen a server where the value uses capital first letters ;) 
Not even at 1und1...

**Comment by Toflar** [comment]
Just go for `strtolower`. SF does too: https://github.com/symfony/symfony/blob/master/src/Symfony/Component/HttpFoundation/Request.php#L1108

**Comment by leofeyer** [comment]
Fixed in 5db1ef7063bdf3ae70856a107d33bfebc4168482.
