### ISSUE TITLE
Page redirect can have a self-reference?

### ISSUE THREAD

**Issue by codiso** [contao/core#8774]
I think this is not the aim ;-)
A page redirect should not target itself …
<img width="1029" alt="seitenstruktur_ _seite_id_117_bearbeiten_-_contao_open_source_cms" src="https://user-images.githubusercontent.com/2002902/29429268-656c46d6-8390-11e7-8ef0-45a6ea2702b8.png">

**Comment by leofeyer** [comment]
Circular references are prevented in both Contao 3 and Contao 4.

<img width="763" alt="" src="https://user-images.githubusercontent.com/1192057/30825197-61b5fe90-a232-11e7-8391-087f4d8dc0d2.png">
