### ISSUE TITLE
Formular-Template Leerzeichen fehlt, wenn Startseiten-Alias = index

### ISSUE THREAD

**Issue by hypergalaktisch** [contao/core#8775]
Im Formular fehlt ein Leerzeichen, wenn die Startseite den alias 'index' hat. Der Submit funktioniert dann nicht mehr.

![image](https://user-images.githubusercontent.com/13819491/29455786-d696a874-8412-11e7-98f0-15e0b8657988.png)

**Comment by ausi** [comment]
Duplicate: contao/core-bundle#992
