### ISSUE TITLE
Image size field is always mandatory

### ISSUE THREAD

**Issue by aschempp** [contao/core#8776]
Regardless of mandatory setting, #8574 causes the image field to always be mandatory. It is no longer possible to keep both values empty (and therefore use the original image size).

See https://github.com/isotope/core/issues/1830

**Comment by ausi** [comment]
If the image size is not mandatory, `'includeBlankOption'=>true` is required to be set IMO.

**Comment by leofeyer** [comment]
The `includeBlankOption` is set:

https://github.com/contao/core/blob/master/system/modules/core/dca/tl_content.php#L251

And I can also leave both fields empty:

<img width="546" alt="" src="https://user-images.githubusercontent.com/1192057/29613343-dd57e78a-8805-11e7-83f0-8aa25a1134d7.png">

**Comment by leofeyer** [comment]
@aschempp You have already mentioned the solution yourself:

> I guess we need to add a blank option.

I figure you have reported the issue because it is not backwards compatible?

**Comment by aschempp** [comment]
no, I didn't realize about the blank option. I guess we can live with that…
