### ISSUE TITLE
Suchindex erst nach "Unveröffentlichen"

### ISSUE THREAD

**Issue by adnan-dev** [contao/core#8777]
Hallo,
setze gerade mein erstes Contao-Projekt auf. Beim erstellen des Suchindex habe ich nie bestimmte Seiten über die Suche finden können. Hab alles mögliche versucht und dann durch Zufall entdeckt, was die Seiten, die gefunden wurden, von den anderen, die nicht gefunden wurden, unterscheidet: die Hauptseiten sind "unveröffentlicht". Hab also dann die anderen Hauptseiten mal unveröffentlicht und siehe da, sie konnten nun gefunden werden. Danach hab ich sie wieder veröffentlicht und sie blieben in der Suche drin!?!?!?!?!?

Einerseits ärgerlich, daß die Seite zu Anfang nicht über die Suche gefunden werden kann. Andererseits, was eigentlich ja ein no-go sein sollte, daß eine Seite, die unveröffentlicht ist, über die Suche gefunden wird!

Hab Conta 3.5.28 installiert.

Danke im Voraus.

**Comment by adnan-dev** [comment]
Zusatz: wenn ich also nun den Artikel unveröffentliche und den Suchindex aufbauen lasse, erhalte ich 13 Einträge in tl_search: die Suche liefert die erwarteten Ergebnisse. Schalte ich das Auge wieder an und baue den Suchindex neu auf, sind nur noch 10 Einträge (hab 3 Artikel veröffentlicht) in tl_search: die Sucher liefert keine Ergebnisse.

Das widerspricht sich doch? Oder raff ich etwas nicht?

**Comment by leofeyer** [comment]
Lässt sich das Problem in der Onlinedemo reproduzieren?

**Comment by adnan-dev** [comment]
ich teste mal, aber die online-demo ist doch v4...?
aber ich hab mal eben in den punkt "about" ein neues text-element eingefügt und sowohl überschrift als auch text "asdasdasd" eingetragen und gesucht. kommt kein ergebnis bei raus. egal ob veröffentlicht oder nicht, oder suchindex neu aufgebaut oder nicht.
sieht eher also nachm user problem aus.
aber welcher?

**Comment by xchs** [comment]
Ich kann das Problem in meiner Testinstallation (Contao 3.5.28, COD) nicht reproduzieren.

**Comment by leofeyer** [comment]
Ich habe es auch gerade nochmal mit Contao 3.5 versucht und konnte das Problem ebenfalls nicht reproduzieren.
