### ISSUE TITLE
Select widget validates empty option

### ISSUE THREAD

**Issue by aschempp** [contao/core#8781]
If a select menu (in my case a multiple one) does not have an option, a blank option with no value is generated. If this option is selected and the records saved, it generates an error because of invalid value.

See https://github.com/isotope/core/issues/1820

**Comment by leofeyer** [comment]
What do you want me to do?

**Comment by aschempp** [comment]
skip/not validate an empty option value?

**Comment by leofeyer** [comment]
What is the DCA configuration of the field?

**Comment by aschempp** [comment]
No `includeBlankOption` if you mean that.

https://github.com/isotope/core/blob/master/system/modules/isotope/dca/tl_iso_shipping.php#L200-L209

**Comment by leofeyer** [comment]
Maybe you should add the option if the value can be empty?

**Comment by aschempp** [comment]
The field is not mandatory. And it‘s correctly not validated if you don‘t select anything. Only if you select the blank option…

**Comment by leofeyer** [comment]
>  if you don‘t select anything. Only if you select the blank option…

I have tried to reproduce this with the `tl_news_feed.archives` field. If there is only one option, I cannot not select anything. The blank option is always selected automatically. 🤔

**Comment by aschempp** [comment]
You mean you changed the DCA configuration? Because that field is a checkbox list?

**Comment by leofeyer** [comment]
Yes, I have changed the configuration:

```php
'format' => array
(
	'label'                   => &$GLOBALS['TL_LANG']['tl_news_feed']['format'],
	'default'                 => 'rss',
	'exclude'                 => true,
	'filter'                  => true,
	'inputType'               => 'select',
	'options'                 => array(), // defaults to array('rss'=>'RSS 2.0', 'atom'=>'Atom')
	'eval'                    => array('includeBlankOption'=>'', 'tl_class'=>'w50'), // does not have the "includeBlankOption" flag
	'sql'                     => "varchar(32) NOT NULL default ''"
),
```

**Comment by leofeyer** [comment]
As discussed in Mumble on October 5th, 2017, you should add `'includeBlankOption'=>true` in your DCA, so the empty string is an allowed value. The HTML specification does not allow `<select></select>` elements without options.
