### ISSUE TITLE
Save and close not working properly when duplicating module - Contao 4.4.3

### ISSUE THREAD

**Issue by e9li** [contao/core#8784]
When duplicating a module redirection is not working as expected after «Save and Close». My fresh installation takes me to the main page of the backend and not to the list of modules as I would expect. Has someone the same behavior?

**Comment by fritzmg** [comment]
See #6127. There are still instances where this can happen.

**Comment by fritzmg** [comment]
@leofeyer shouldn't https://github.com/contao/core/issues/6127 be re-opened then?
