### ISSUE TITLE
RepositoryBackendModule.php

### ISSUE THREAD

**Issue by nilsbremke** [contao/core#8785]
`require_once dirname(dirname(__FILE__)).'/classes/RepositorySettings.php';`
in phpstorm wird mir das als falsch angezeigt. 
müsste doch so lauten: 
`require_once __DIR__(__FILE__)'/classes/RepositorySettings.php';`

oder auch in Repository.php ist ein Fehler scheinbar!

**Comment by leofeyer** [comment]
> `require_once __DIR__(__FILE__)'/classes/RepositorySettings.php';`

Nein, dieser Aufruf ist auf jeden Fall falsch. `__DIR__` ist ja keine Funktion.
