### ISSUE TITLE
Circular references with news modules possible

### ISSUE THREAD

**Issue by Teetrinker** [contao/core#8789]
Problem: An editor (backend user) can add a news module as a content element in a news entry. The site crashes: it shows a white screen (online demo, Contao 4.4.5) or delivers an Error 500 (my 3.5.27 installation).

How to reproduce in the online demo:

- edit module "News - Latest - Footer", switch "News template" to "news_full"
- in the news channel, edit a news entry, add a content element of type module, choose the module "News - Latest - Footer"

It may sound like an edge case for a stupid user, but with a site complex enough, the circular reference is not obvious to the user/editor.

The real problem beside the server error is, that there is no log entry produced.

The same problem may apply to the event module. I haven't tested that.

**Comment by leofeyer** [comment]
I don't think there is a reasonable way to prevent this. @contao/developers /cc

**Comment by Toflar** [comment]
If we incorporate ce-access in 4.5 we might also think about having some config in the tl_content DCA that contains disallowed content elements. One already configures "ptable" so we could also have some array that disallows certain types.
Anyway, I'm also interested in the "white page without log entry". Sounds like something that should never happen. @Teetrinker can you debug and see why this happens maybe?

**Comment by KaiserCh** [comment]
I've encountered these unlogged whitescreens multiple times, but mostly with Magento. Sometimes there are error logs in the operation systems logfiles, e.g. /var/log/php5-fpm.log, /var/log/apache2/error.log,... but I had errors that could not be traced. Mostly, the reason was an extreme lack of memory.

Regarding disallowed elements: Would this include certain insert tags?

**Comment by Toflar** [comment]
> Regarding disallowed elements: Would this include certain insert tags?

No, nobody can control insert tags.

**Comment by Teetrinker** [comment]
@Toflar Can't debug. But can help with the setup if interested. Actually, the blank was when I tested the issue in the online demo. You should be able to reproduce it.

**Comment by leofeyer** [comment]
As discussed in Mumble on October 5th, there is no way to solve this. A memory overflow can only be logged on SAPI level, e.g. in the access log of your web server.
