### ISSUE TITLE
Alert Button in FF shows the word 'Alerts' half

### ISSUE THREAD

**Issue by MacKP** [contao/core#8791]
FF 55.0.2 on Linux shows not only the Icon.
![contao_be_alerts_ff](https://user-images.githubusercontent.com/1241811/30934851-252ebf40-a3cf-11e7-8ddf-9066fc6cb463.png)
I have no patch atm. Just wanted to document this (I can have a look later this week i think, when no one comes first).
No Problem with Chrome on Linux. Can't test with IE ore Edge right now. Will do that later.

regards

**Comment by leofeyer** [comment]
See contao/core-bundle#1083.
