### ISSUE TITLE
YouTube ID converted to lowercase

### ISSUE THREAD

**Issue by aschempp** [contao/core#8796]
YouTube IDs can contain uppercase letters, which is a different ID than lowercase. Contao 3.5 has `rgxp => url` on the YouTube ID field, and that is converted to lowercase in `TextField.php`.

The easiest solution would probably be to remove the rgxp anyway.

**Comment by qzminski** [comment]
It's likely because the `\Idna::encodeUrl()` encodes the host (strtolower). Looks like the provided YouTube ID is treated like a host.

**Comment by fritzmg** [comment]
Hm, duplicate of https://github.com/contao/core/issues/8704 ? I don't remember if this was ever fixed.

**Comment by aschempp** [comment]
Hah! I'm on 3.5.26 😏
