### ISSUE TITLE
Selecting "Add the Language to the URL" in Site structure/Website root for every domain separately

### ISSUE THREAD

**Issue by havutcuoglu** [contao/core#8799]
Hi Guys,

I'm facing a Contao problem, which might be need optimizing or changing.
The selection "Add the Language to the URL" in Settings make that all root pages get this option. But if you have more root pages for regular Sites or micro sites in one installation and using different domains like domain.com, sub.domain.com, mynameis.com, you don't have the possibility to decide you need or don't need the language option.

* domain.com/de or domain.com/en
* sub.domain.com (this domain will get also the language)
* mynameis.com (this domain will get also the language)

I think it is better to move the option "Add the Language to the URL" in root pages **or add a possibility in the root page to select "Don't use Language in URL"**.

What do you think?

**Comment by asaage** [comment]
https://github.com/contao/core-bundle/issues/1051

**Comment by havutcuoglu** [comment]
Thank you very much.
