### ISSUE TITLE
Wildcard search

### ISSUE THREAD

**Issue by Vinny38** [contao/core#8800]
Seen on https://demo.contao.org/en/search.html

> 2. WILDCARD SEARCH
By default, the search engine searches for exact keywords only. This means that a search for music will not return pages containing the words musical or musician. However, if you want to search for all words that begin with music, you can add an asterisk (\*) after the keyword (music\* instead of music). Of course, you can also put the wildcard in front of a keyword or in THE MIDDLE OF A KEYWORD."

ISSUE: the asterisk wildcard does not seem to be working while placed in the middle of a keyword...

**Comment by Aybee** [comment]
I can confirm this.

@Vinny38 You can use markdown to formate a quoted text https://help.github.com/articles/basic-writing-and-formatting-syntax/#quoting-text

**Comment by leofeyer** [comment]
The description in the demo is wrong. If you look at the code, you will see that wildcards in the middle of a keywords are not supported and never have been.

https://github.com/contao/core/blob/2474ff9a8e0cf0f533818461d20930e49baaa9b0/system/modules/core/library/Contao/Search.php#L346-L384

You should probably open an issue here: https://github.com/contao/official-demo/issues
