### ISSUE TITLE
Problem changing the Image size using user-groups

### ISSUE THREAD

**Issue by codiso** [contao/core#8803]
Hi, I have a client installation under 4.4.7. As an Admin i can change the imga size but if I use user-groups the image size popup does not show anything and the inputfields for width and height are disabled.

<img width="433" alt="nachrichten_ _reiseberichte____badereisen_ _artikel_ _makarska_riviera_ _inhaltselemente_ _inhaltselement_id_207_bearbeiten_-_contao_open_source_cms" src="https://user-images.githubusercontent.com/2002902/31861057-e44f9304-b725-11e7-95d8-5dca2565502c.png">

What is the problem? The user group has the permission to change that properties …

<img width="316" alt="benutzergruppen_ _gruppe_id_2_bearbeiten_-_contao_open_source_cms" src="https://user-images.githubusercontent.com/2002902/31861069-39d1417e-b726-11e7-8c89-535fe13d6035.png">

**Comment by fritzmg** [comment]
You need to define in the user or user group settings which image size setting the user is allowed to use.

**Comment by codiso** [comment]
Yes i've seen it 👍

**Comment by codiso** [comment]
Works fine …
