### ISSUE TITLE
Styling der ColorBox durch zu generische Regel mit Zwang in Formulare-CSS gestört

### ISSUE THREAD

**Issue by soletan** [contao/core#8805]
Wenn man in Contao 4.4.5 Managed Edition für ein Seitenlayout das CSS-Framework für Formulare aktiviert und ColorBox nutzt, um Bilder darzustellen, dann funktioniert die Darstellung der Buttons in der Colorbox beim Hover nicht, weil eine Regel aus dem Formulare-CSS zu stark priorisiert wurde.

![grafik](https://user-images.githubusercontent.com/48088/31912857-960befe6-b845-11e7-9ab7-32410d8b4fb4.png)

![grafik](https://user-images.githubusercontent.com/48088/31912868-9fba2f12-b845-11e7-9add-b326d074230f.png)

Eine Analyse mit dem DOM-Inspektor zeigte, dass folgende Regel hier stört:

![grafik](https://user-images.githubusercontent.com/48088/31912925-d7410e10-b845-11e7-99a4-9f0073cb60d3.png)

Die Regel bei 1 kann nicht greifen, weil die Regel bei 2 zu generisch ist und mit dem wenig empfehlenswerten `!important` überbetont wird.

**Comment by fritzmg** [comment]
Duplicate of https://github.com/contao/core-bundle/issues/1038, https://github.com/contao/core-bundle/issues/1111 & https://github.com/contao/core/issues/8747 » https://github.com/contao-components/contao/pull/8

**Comment by leofeyer** [comment]
The main ticket is this: https://github.com/contao-components/contao/pull/8

We could have fixed it already, but we have to agree on a solution first.
