### ISSUE TITLE
Copy&Paste funktioniert in HTML Modul mit nicht

### ISSUE THREAD

**Issue by Olli** [contao/core#8806]
Kann getestet werden auf https://demo.contao.org ... "Custom HTML" Modul anlegen, irgendwas rein schreiben, speichern, Copy in Zwischenablage und gleich wieder Paste. 
Es wird irgend ein komisches Sonderzeichen in die Zwischenablage kopiert aber nicht der markierte Inhalt.
FF 56.0, Debian Linux SID, Quelltexteditor im Contao angeschaltet  
Im Chromium gehts.

**Comment by Aybee** [comment]
Auf Windows 10 kein Problem mit FF 56.0.1.

**Comment by Olli** [comment]
Ok ich habs noch in einem anderen FF-Profil getestet ... ist wahrscheinlich ein Add-On was irgend was blockiert oder so.
Thx fürs testen.
