### ISSUE TITLE
Form generator field Select menu does not send option content if value ist empty

### ISSUE THREAD

**Issue by Aybee** [contao/core#8808]
Wenn ein Option keinen Value hat, dann muss der Content gesendet werden.
```html
<option>foo</option>
```
Dies muss "foo" senden. https://www.w3.org/TR/html5/forms.html#attr-option-value

Lässt man in dem Feld "Select menu" das `value` leer, rendert Contao aber leere Values.
```html
<option value="">foo</option>
```
Dies sendet in einem **non mandatory** Feld `""` wenn man "foo" ausgewählt hat. In einem **mandatory** sendet es überhaupt nicht, weil es einen Wert benötigt. Gibt also den Fehler:
> Bitte füllen Sie das Feld "Mein Select" aus!

Im Code steht ja, dass value nicht ausgefüllt werden muss, 
https://github.com/contao/core/blob/master/system/modules/core/widgets/OptionWizard.php#L43
aber dass dann leere Values gerendert werden sehe ich als Bug.

**Comment by fritzmg** [comment]
Man muss ja auch leere Values senden können.

**Comment by Aybee** [comment]
Eigentlich doch nur, wenn man ein Option ganz oben mit leerer Auswahl benötig. '- bitte wählen' (includeBlankOption). Dazu sollte es dort einfach eine Checkbox geben "Include blank option", wo man dann noch alternativ ein Label angeben kann.

**Comment by fritzmg** [comment]
Das Label der leeren Option möchte ich aber meist selber wählen. Bspw. ist derzeit über den Formulargenerator auch so etwas gar nicht möglich:
```html
<option value=""></option>
```
Ganz zu schweigen von
```html
<option></option>
```

**Comment by Aybee** [comment]
Ich sag ja oben bereits "wo man dann noch alternativ ein Label angeben kann".

Die beiden unteren Snippets von dir machen IMHO keinen Sinn.

Mal sehen, wie die oben genannte Erweiterung mit dem jetzigen Core-Verhalten klar kommt.

Wahrscheinlich braucht man oben genanntes
```html
<option>foo</option>
```
auch gar nicht, ich wollte es aber mal festgehalten haben.

**Comment by fritzmg** [comment]
> Die beiden unteren Snippets von dir machen IMHO keinen Sinn.

Warum nicht? Ob man jetzt
```html
<option value="">-</option>
```
```html
<option value=""></option>
```
oder
```html
<option></option>
```
schreibt spielt ja keine Rolle. Im speziellen ist  ja kein ungeschriebenes Gesetz, dass die leere Auswahl
```html
<option value="">-</option>
```
sein muss. Das Label der leeren Auswahl kann ja genau so gut leer sein.

**Comment by Aybee** [comment]
Ja stimmt. Also generell kann man festhalten, dass eine Checkbox fehlt "Add blank option" und wenn die ausgewählt ist bekommt man die Möglichkeit ein Label anzugeben, oder es leer zu lassen. Richtig?

Weicht etwas von dem ursprünglichen Threadtitel ab. Es ging auch darum, dass Contao immer ein leeres `value=""` generiert.

**Comment by aschempp** [comment]
Man kann doch einfach beim Feld "Wert" dasselbe wie bei "Label" reinschreiben und das Problem ist gelöst?

**Comment by leofeyer** [comment]
Sehe ich auch so. Das andere ist kein unterstützter Anwendungsfall (weil redundant).
