### ISSUE TITLE
User permission cannot be extended by groups v3.5.30

### ISSUE THREAD

**Issue by aloesche** [contao/core#8810]
Version 3.5.30 LTS (PHP 5.6)

Hi, I tried to extend the user permission with a group in order to allow certain fields to access and edit simple content elements. I tried with vanilla 3.5.30 and did the following:

A) Created a user group (Module: Article, allowed all fields of tl_article, tl_content and tl_page)
B) Created a user assigned the above group to extend with personal permissions (allowed page mounts)
=> User can see the pages and content elements but is not able to edit or adjust (taking any action on it)

(Just noticed while testing various combinations, that only individual user settings are working (at least the user can edit the articles (wihtout data fields)). As soon as you select a user group to extend the permissions (which is obviously required to define allowed fields )) he is not able to edit any articles anymore.

The test env is reachable for you if you want to see this behavior just let me know.

Please be calm in case the problem is sitting in front of the computer :)

**Comment by leofeyer** [comment]
Please refer to the [forums](https://community.contao.org/) for this kind of questions.
