### ISSUE TITLE
Inserttags in Kommentaren werden nicht ersetzt

### ISSUE THREAD

**Issue by planepix** [contao/core#8811]
Möchte man in den Kommentaren ein Bild hinzufügen, werden diese nicht angezeigt.

Vorgehensweise:
Im TinyMCE ein Bild hinzufügen. Wird im Backend angezeigt. Im Frontend nicht.
Das Bild bzw. der Pfad wird nicht richtig aufgelöst.
Im Quellcode steht:
`<img src="{{file::946135fa-bf40-11e7-a74f-246e96295020}}" alt="">`

Auch mit Inserttags klappt das nicht; auch diese werden im Kommentar nicht aufgelöst.
`{{image::5e0db830-8e25-11e7-886d-5d32e2d8945c?width=200[&]height=150}}
` wird im Frontend genau so als Text dargestellt.

Aktuell in der Version 3.5.30 und auch online in der 4er-Version getestet. Auch in der Online Demo wird der Inserttag nicht ersetzt.

Soll ich das Ticket auch noch einmal für die 4.x erstellen?

**Comment by fritzmg** [comment]
Ich denke dass für Kommentare die Insert Tags entfernt werden ist beabsichtigt.

**Comment by planepix** [comment]
Ok. Aber das Einfügen von Bildern (als Admin). Das ging in früheren Versionen.

**Comment by fritzmg** [comment]
Prinzipiell werden Insert Tags nur für den Kommentar entfernt: https://github.com/contao/core/blob/3.5.30/system/modules/comments/classes/Comments.php#L120
Das heißt im reply sollte es eigentlich funktionieren.

**Comment by planepix** [comment]
Bedeutet, dass man als Admin die Kommentare nicht editieren kann und dann dort Bilder einfügen kann. Richtig?

**Comment by fritzmg** [comment]
Genau. Die geschwungenen Klammern werden entfernt.

**Comment by planepix** [comment]
Danke @fritzmg
