### ISSUE TITLE
C4 multiple edit/delete menu backend not comfortable

### ISSUE THREAD

**Issue by eBlick** [contao/core#8816]
I didn't finde any information why the edit/delete/copy menu in multiple edit mode is so uncomfortable.
First I don't see any reason to put these options into a dropdown, while there is so much space around (two clicks necessary), second If there ist a reason for this, why do we have the "delete" option priorized on top?
I use the copy, or overwrite option much more often and I believe that other users do this, too.
I regularly click on the delete option by accident when I miss the dropdown arrow.

If you please get rid of the dropdown or at least put the "copy" option on top.

<img width="139" alt="bildschirmfoto 2017-11-25 um 13 44 48" src="https://user-images.githubusercontent.com/6641281/33230608-dbfcc880-d1e6-11e7-9b92-034924eec2f1.png">

**Comment by OMOSde** [comment]
For Contao 4.4+ you can use the upcoming version 1.2 from https://github.com/OMOSde/contao-om-backend. There is an option in the user settings to remove the submenus for save and edit multiple buttons.

**Comment by Samson1964** [comment]
+1

**Comment by Toflar** [comment]
Yeah there's general consent about that. The thoughts behind this are easy to understand: If you're on mobile you don't have that much space for 6 buttons, that's why there are only two or three and the rest is in a dropdown. The best way would be to make it responsive but nobody worked on that so far. If you could do that, we'd be very happy to integrate that solution :)

**Comment by leofeyer** [comment]
> Yeah there's general consent about that.

Is there? I find myself using the "delete" option a lot more than the copy option, so I'm -1 on making "copy" the top option.

> The best way would be to make it responsive but nobody worked on that so far. 

I once tried to change it, however, the stacked button requires a certain HTML markup with a surrounding container, so we cannot simply take buttons out of the stack with only CSS.

**Comment by OMOSde** [comment]
CSS only, could be possible. I do it here: https://github.com/OMOSde/contao-om-backend/blob/master/src/Resources/public/css/om_backend.css#L152-L191

But, not very well tested.

**Comment by Toflar** [comment]
> Is there?

Yeah, about using the space on desktop if it's there. Not about the order of the buttons obviously (I don't care about that any way).

**Comment by fritzmg** [comment]
> I once tried to change it, however, the stacked button requires a certain HTML markup with a surrounding container, so we cannot simply take buttons out of the stack with only CSS.

Shouldn't be that difficult without changing the current markup even. This is just crude reconstruction: https://jsfiddle.net/de7vj417/

**Comment by leofeyer** [comment]
The goal is not to deconstruct the stacked button completely, but to extract single buttons depending on the browser width.

**Comment by fritzmg** [comment]
I see. But is that goal really necessary? Wouldn't it be more important to have at least have _one_ breakpoint at which at least all buttons are visible?

**Comment by leofeyer** [comment]
I don't think that seven buttons next to each other is a good UX decision.

**Comment by fenepedia** [comment]
What about adding an custom user option, so everybody could set the default value?

**Comment by JLBA** [comment]
Contrary to Leo, I think users need to see anytime what they can do and catch buttons quickly (one click). Hiding buttons in one dropdown menu can be a solution on smartphones. On computers or tablets, it's just a foolish search of absolute flat purity design initiated by Apple (followed by Google) who was better inspired in 1984 ;-)

**Comment by leofeyer** [comment]
Changed in contao/core-bundle@bfe804eb96b5655bc34d75cce97e950022713981 then.
