### ISSUE TITLE
Dateiverwaltung separat

### ISSUE THREAD

**Issue by bekanntmacher** [contao/core#8822]
<img width="227" alt="bildschirmfoto 2017-11-30 um 22 37 34" src="https://user-images.githubusercontent.com/1622464/33456246-1b0263b4-d61f-11e7-95a5-65307816bf96.png">

Wo würdet ihr die Dateiverwaltung suchen? 

In meinen Augen ist die Dateiverwaltung unter System am falschen Ort. Was spricht gegen einen separaten Menüpunkt analog der Benutzerverwaltung?

**Comment by leofeyer** [comment]
Das sind ja keine Menüpunkte, sondern nur Gruppen.

**Comment by Aybee** [comment]
Ich würde es unter Inhalte erwarten, aber man gewöhnt sich an alles 😉

**Comment by bekanntmacher** [comment]
Die bestehenden sind Gruppen aber das ist ja nicht zwingend. Man kann ja ein Punkt auch direkt verlinken. Oder doch eine Gruppe machen und gleich noch Klicks sparen:

Dateien
-- Dateiverwaltung
-- Datei hochladen

**Comment by leofeyer** [comment]
@contao/developers Was denkt ihr darüber, den Punkt "Dateiverwaltung" in die Gruppe "Inhalte" zu verschieben?

**Comment by ausi** [comment]
Ich denke nicht dass ein Verschieben zu „Inhalte“ es besser macht als es jetzt ist.

**Comment by frontendschlampe** [comment]
naja ... unter Inhalte würde es sicherlich besser passen. Wenn man von einem Redakteur ausgeht, der Inhalte pflegt, dann gehören Dateien zu den Inhalten ...

**Comment by Toflar** [comment]
Ich find's irgendwie seltsam. Wer sagt denn, dass Dateien Inhalte sind? Wenn ich eine Datei in einem HTML-Frontendmodul per InsertTag referenziere, ist das dann "Inhalt" oder "Layout"? Also ich persönlich komm mit allem zurecht, aber ich denke wir sollten eine Umfrage starten und die Mehrheit entscheiden lassen.

- Belassen wie's ist
- Nach "Inhalte" schieben
- Eigene Menügruppe "Dateiverwaltung" (die dann nur die Dateiverwaltung enthält, denk ich...)
- was sollten wir sonst noch zur Auswahl anbieten?

**Comment by leofeyer** [comment]
Der Punkt "eigene Menügruppe" steht ja nicht wirklich zur Diskussion, da die Gruppe sonst "Dateiverwaltung" hieße und es darin nur einen Punkt "Dateiverwaltung" gäbe. 😄

**Comment by frontendschlampe** [comment]
> Wenn ich eine Datei in einem HTML-Frontendmodul per InsertTag referenziere, ist das dann "Inhalt" oder "Layout"?

Da gebe ich Dir Recht. ;-)

> Der Punkt "eigene Menügruppe" steht ja nicht wirklich zur Diskussion, da die Gruppe sonst "Dateiverwaltung" hieße und es darin nur einen Punkt "Dateiverwaltung" gäbe. 😄

Ist irgendwie ein blödes Thema und eine Grundsatzdiskussion! :-D Man könnte die Dateien ja ggfs. sogar aufspalten in wirkliche Inhalte und Arbeitsdateien wie Scripte, CSS usw. Dass die mit in Files liegen, ist nicht immer vorteilhaft!

**Comment by bekanntmacher** [comment]
> Der Punkt "eigene Menügruppe" steht ja nicht wirklich zur Diskussion, da die Gruppe sonst "Dateiverwaltung" hieße und es darin nur einen Punkt "Dateiverwaltung" gäbe. 😄

doch.
Nein, 2 Punkte: einen Punkt "Dateiverwaltung" und einen Punkt "Datei hochladen"

> Ist irgendwie ein blödes Thema und eine Grundsatzdiskussion! :-D Man könnte die Dateien ja ggfs. sogar aufspalten in wirkliche Inhalte und Arbeitsdateien wie Scripte, CSS usw. Dass die mit in Files liegen, ist nicht immer vorteilhaft!

Ja, sauber trennen, würde ich auch begrüssen: 
 1. Dateiverwaltung zu den Inhalten verschieben
 2. Darin nur Dateien ablegen welche Inhalte sind und von den Redakteuren bedient werden
 3. Alles Andere raus aus der Dateiverwaltung in einen eigenen Ordner

**Comment by Aybee** [comment]
> Alles Andere raus aus der Dateiverwaltung in einen eigenen Ordner

IMHO zu viel Aufwand und ungeahnte Probleme, die damit auftreten könnten. Eigene Ordner geht ja bereits.

```
| files/
| | theme/
| | customer/ (mounted for editors)
```

**Comment by bekanntmacher** [comment]
So ist es ja jetzt schon @Aybee . Dateien verwalten hat aber für die Redakteure nicht's mit System zu tun. Es ist einfach die Pflege von Inhalten. 

Aktuell haben wohl die meisten ein Gemisch aus:
1. Medien (Bilder, Videos, Pdf's, etc.) = Inhalte
2. Css, js, etc. = Layout-Dateien
3. includes à la Yannik  = Eingebundene Dateien zu individuellen Zwecken  

(Dann haben wir noch Templates im Template-Ordner welcher wieder "Eingebundene Dateien zu individuellen Zwecken" beinhalten kann.)

Ihr müsst mich wohl bestätigen: da besteht dringendes Aufräumpotential, nicht?

Grundsätzlich bauen wir das Backend ja für die Redakteure und Redakteure verwalten Inhalte. Somit gehört die Dateiverwaltung zu den Inhalten. Dann sollte sie aber korrekterweise auch keine Dateien 2. und 3. enthalten. Es sei denn, man gönne ihr einen eigenen Navigationspunkt.

Somit sehe ich folgende 2 Varianten:

V 1: Dateiverwaltung beinhaltet nur noch Inhalte > verschieben zu den Inhalten
V 2: Dateiverwaltung beinhaltet nach wie vor alles > eigener Menüpunkt

Wenn ihr mich fragt, ich bin für V 1.

**Comment by do-while** [comment]
Ich verstehe die Diskussion nicht so richtig, wie @Aybee oben geschrieben hat, kann ich für den Redakteurs-Login doch schon immer auswählen, was er sehen kann (z.B. ein Unterverzeichnis mit den Medien (Inhalten)). Du kannst doch eine Struktur aufbauen, wo genau Deinen Anforderungen mit erfüllt werden.
Oder soll der Admin seine Dateien, die keine Inhalte sind, nur noch per FTP pflegen können?

Ich sehe keinen Grund, die Dateiverwaltung zu verändern.

**Comment by bekanntmacher** [comment]
Es geht darum, dass die Dateiverwaltung nicht unter "System" sondern unter "Inhalte" erwartet wird.

**Comment by do-while** [comment]
Das war schon immer unter System und ich hatte bisher keinen Kunden, der sie nicht gefunden hat. Gerade Redakteure verwenden den Upload ja eher direkt im Dateipicker, so dass sie den Menüpunkt überhaupt nicht aufrufen. Wer denkt denn schon daran, vor dem Schreiben des Artikels die Bilder hochzuladen?

**Comment by bekanntmacher** [comment]
>Das war schon immer unter System und ich hatte bisher keinen Kunden, der sie nicht gefunden hat.

Ja, für Gewohnte ist es klar und wer sucht der findet alles irgendwo... doch auf dem Rechner sind die Dateien auch nicht unter den Systemeinstellungen zu finden.

**Comment by aschempp** [comment]
> Ja, für Gewohnte ist es klar und wer sucht der findet alles irgendwo... doch auf dem Rechner sind die Dateien auch nicht unter den Systemeinstellungen zu finden.

Auf macOS sind sie unter *Finder* und auf Windows unter *Arbeitsplatz*. Jedes System hat seine Eigenheiten, ich finde *System* überhaupt nicht falsch.

**Comment by bekanntmacher** [comment]
Aber bei keinem System sind sie unter den Systemsteuerungen zu finden. Es hat doch nichts mit dem System zu tun oder hat es das? 

Für die Redaktoren sind hochgeladene Dateien ganz einfach Bestandteil vom CONTENT.

**Comment by aschempp** [comment]
Das wäre wohl Ansichtssache. Ich lade Dateien in das System 😛 

Deinem Beispiel folgend ist **alles** Content. Die Seitenstruktur und das Theme sind auch Content. Mitglieder sind auch Content des Systems. Isotope erstellt einen eigenen Menüpunkt für seine Module, aber auch das ist Content. 

Für mich gehört es in System, weil ich die Dateien in jedem Content-Modul (News, Artikel, Events, etc.) benutzen kann, sie sind *systemweit* gültig. Aus demselben Grund ist die Seitenstruktur nicht Content.

**Comment by bekanntmacher** [comment]
> Deinem Beispiel folgend ist alles Content. Die Seitenstruktur und das Theme sind auch Content. Mitglieder sind auch Content des Systems. Isotope erstellt einen eigenen Menüpunkt für seine Module, aber auch das ist Content.

Das sehe ich überhaupt nicht so. Die Dateiverwaltung ist unter System schlicht am falschen Ort und am liebsten hätte ich sie (wie  ich eingangs gesagt habe) unter einem separaten Menüpunkt. 

Unter System erwartet man die Dateiverwaltung nicht. Das Problem ist, dass du und alle die hier mit diskutieren sich scheinbar daran gewohnt haben und schlicht nicht in der Lage sind, sich von der Gewohnheit zu lösen. Wenn ich einem Kind alle Menüpunkte auf je eine Karte schreiben würde und sage "sortiere/gruppiere mal" dann würde das Kind die Dateiverwaltung sicher nicht dem System zuordnen.

**Comment by planepix** [comment]
Und frei konfigurierbar machen? Zu hoher Aufwand? Zu viele Abfragen und Dinge zu berücksichtigen?

Dann jeder seine Sortierung einstellen, wie er mag.

Der Catalog Manager hat so etwas, womit man die Positionen bestimmen kann.

**Comment by Toflar** [comment]
Jeder kann die Reihenfolge und Labels bereits jetzt komplett frei anpassen. Dazu gibt es Hooks und Events. Die Flexibilität ist also bereits vorhanden. Sowas konfigurierbar zu halten (am besten noch pro User) ist einfach Arbeitsbeschaffung. Anders kann ich das nicht bezeichnen. Wir haben wichtigere Baustellen.

**Comment by planepix** [comment]
Da hast du wahr ;) @Toflar.
Zum Glück schreibt keiner ein Buch 😎

**Comment by leofeyer** [comment]
Wie am 12. April auf Mumble besprochen ist es tatsächlich nicht intuitiv, dass sich die Dateiverwaltung unter "System" befindet. Besser wäre es vermutlich in einer eigenen Gruppe.

Allerdings wollen wir das erst ändern, wenn wir das Backend-Redesign angehen, da sonst die ganze vorhandene Doku nicht mehr stimmt.
