### ISSUE TITLE
Contao 4.4 Cron throws error with PHP 7.2

### ISSUE THREAD

**Issue by TB1234** [contao/core#8823]
With PHP 7.2.0 the latest Conto 4.4.8 version throws an error if you call the Contao cron.

Error: Warning: count(): Parameter must be an array or an object that implements Countable in /home/.../vendor/lexik/maintenance-bundle/Listener/MaintenanceListener.php on line 184
PHP: 7.2.0
Contao: 4.4.8

**Comment by xchs** [comment]
This belongs to the[ contao/core-bundle](https://github.com/contao/core-bundle) repository.

**Comment by TB1234** [comment]
OK, tnx. Opened issu in core-bundle:
https://github.com/contao/core-bundle/issues/1217
