### ISSUE TITLE
Don't remove old subscriptions that have not been activated yet

### ISSUE THREAD

**Issue by tsarma** [contao/core#8824]
https://github.com/contao/core/blob/9ca7b0d03b522622ce4bd2b00ad4fc34efbf28f6/system/modules/newsletter/modules/ModuleSubscribe.php#L243-L250

Please don't not delete old subscriptions automatically. I have multiple newsletter channels corresponding to each online competitions. A person can take part in a competition only after subscribing to the corresponding NL. 

To each competition, I have prepared a NL registration with pre selected channel but hidden. This registration form is then placed inside an article describing the competition. 

If a person subscribe to a NL and before activation, he then subscribes to the next NL. He is deleted from the first NL channel.

**Comment by leofeyer** [comment]
Would it help if we limited deletions to the current channel(s)?

**Comment by leofeyer** [comment]
@contao/developers /cc

**Comment by tsarma** [comment]
> Would it help if we limited deletions to the current channel(s)?

Yes, this would work and I find it basically correct to restrict to the current channels. 
Thank you for looking into this once again, in the mean time we are integrating this workflow in  external newsletter tool (which is not yet setup). In this way, I can prepare a normal Contao form which submits to external newsletter tool.

**Comment by leofeyer** [comment]
Fixed in 8b7425ba202fe0005d4063df7166dae4254791c9.
