### ISSUE TITLE
Recreate the XML files manually -> sitemap still in cache.

### ISSUE THREAD

**Issue by eBlick** [contao/core#8825]
after recreating the XML files in maintenance, the sitemap seems to be still in page cache.
Should this not be cleared automatically when using this option (without purging page cache simultaneously)?

**Comment by leofeyer** [comment]
> Should this not be cleared automatically when using this option

It is actually:

https://github.com/contao/core/blob/master/system/modules/core/library/Contao/Automator.php#L269
