### ISSUE TITLE
make the bredcrumb work like in 3.5

### ISSUE THREAD

**Issue by asaage** [contao/core#8827]
the current breadcrumb looks kind of weird to me - it should not display something like "News Detail"
![image](https://user-images.githubusercontent.com/4138336/33882200-a04c11b6-df37-11e7-81df-0e5b99b44f16.png)

in Contao 3 it was using the pageTitle of the page in the first place and fell back to the name of the page if no title was not set.

![image](https://user-images.githubusercontent.com/4138336/33882285-e2ec3078-df37-11e7-8549-2a23c4f633d0.png)

I see concerns about the length of the breadcrumb https://github.com/contao/core/issues/7357 but this is something i would fix with css text-overflow: ellipsis

going this route:
 ![image](https://user-images.githubusercontent.com/4138336/33882337-0925baa2-df38-11e7-90e0-6d7b8197fd00.png) is somehow not very desirable.

**Comment by fritzmg** [comment]
Issues for Contao 4 should be posted in the `contao/core-bundle` repository.

**Comment by asaage** [comment]
my misstake
