### ISSUE TITLE
Flags in Stylesheets und Javascript ignorieren

### ISSUE THREAD

**Issue by Babelfisch** [contao/core#8828]
Ich weiß nicht, ob das schon mal angesprochen wurde aber der Trenner | für Flags in TL_CSS und TL_JAVASCRIPT wird durchaus auch in URLs verwendet. Ein Beispiel wären die Google Fonts, bei denen man mehreren Fonts mittels | trennen kann und so nur einen Zugriff auf fonts.googleapis.com hat. Es wäre schön, wenn man eine Möglichkeit hätte, die Trenner in der URL nicht als Flag zu interpretieren.

Eine relativ leicht zu implementierende Variante wäre ein *(tata)* zusätzliches Flag `raw`. Das Stylesheet würde man dann bspw. so definieren:

```php
$GLOBALS['TL_CSS'][] = '//fonts.googleapis.com/css?family=Ubuntu|Noto+Sans|raw';
```

Dazu müsste die statische Methode `resolveFlaggedUrl` in der `StringUtil.php` an folgender Stelle nur geringfügig ergänzt werden:

https://github.com/contao/core/blob/3e41ad8718f6dea9c10c8a9b0341ed86f2bbe2ae/system/modules/core/library/Contao/StringUtil.php#L792

```php
if ($chunks[count($chunks)-1] == 'raw')
{
	array_pop($chunks);
	$url = implode('|', $chunks);
	
	return $options;
}
```

Nebenwirkungen sollten hier keine entstehen und es gäbe dann einen relativ leichten Weg, den Trenner | bei Bedarf zu benutzen.

**Comment by leofeyer** [comment]
Was ist wenn jemand `|raw|static` nutzt? Ein wenig exakter sollte die Prüfung schon sein IMO. Eventuell müssten wir die Pipes, die zur URL gehören, escapen?

@contao/developers /cc

**Comment by Toflar** [comment]
Wenn wir überhaupt etwas machen, dann bauen wir einen Service oder irgendwie sonst eine brauchbare Alternative für Superglobals, dann ist das Problem sowieso behoben.

Aber man kann es ja auch einfach dem Entwickler überlassen, bis wir eine schöne Variante haben:

```php
$GLOBALS['TL_CSS'][] = 'https://fonts.googleapis.com/css?family=Ubuntu%7CNoto+Sans|static';
```

**Comment by Babelfisch** [comment]
Grrr, auf die Idee URL-Encoding zu probieren hätte ich auch kommen können. Ich weiß nicht, ob das in jedem Fall funktioniert aber bei Google Font klappt das zumindest super.

Dann ist mein Vorschlag denke ich hinfällig.
