### ISSUE TITLE
Duplicate pages on multilingual

### ISSUE THREAD

**Issue by xApep** [contao/core#8829]
Hi.
we have one page root which is English version and set as fallback (checked). "Default" domain is **test.com**.
The other page root is set to German, domain name is **test.de** and also fallback (checked).

The issue is that when you go to German domain:
test.de/uber-uns.html it shows German version which is correct
but if you go to test.de/about-us.html it shows English version - which is not correct because it should show 404 error.

The other way around works correct. If you go to 
test.com/about-us.html it shows English version
if you go to test.com/uber-uns.html it shows 404 error - which is correct.

I'm using Contao 3.5.9

Kind regards.

**Comment by fritzmg** [comment]
These kinds of questions should be posted on the community forum, not here.

Regarding your problem: did you define both domains in both your website roots? Also you should definitely update to Contao 3.5.31.

**Comment by xApep** [comment]
The sad fact is that community is dead especially the International one.

Thanks for your help, the "default" domain was not defined in domain name in EN...now it works at it should.

Thanks.

**Comment by fritzmg** [comment]
> The sad fact is that community is dead especially the International one.

Do you mean the english forum? I check that forum regularly ;)

**Comment by xApep** [comment]
English yes. Well I post there couple of questions but you can imagine the results of feedback :)

**Comment by Toflar** [comment]
BTW, #contao on freenode.net has around 15 to 20 people every day :)

**Comment by Aybee** [comment]
> @fritzmg Do you mean the english forum? I check that forum regularly ;)

Me too ;)

**Comment by xApep** [comment]
Haha, everybody is just checking but not replying :)

**Comment by Aybee** [comment]
Then we have no solution. Try the IRC or the german forum.

**Comment by fritzmg** [comment]
The english forum also experiences technical difficulties currently.
