### ISSUE TITLE
Geschützte Downloads

### ISSUE THREAD

**Issue by cgpro** [contao/core#8831]
Ich verwende 4.4.9 und mir ist aufgefallen, dass Dateien in geschützten Verzeichnissen herunterladbar sind, obwohl man nicht eingeloggt ist. Es wird über {{file::f00a6c4f-e14a-11e7-8071-5254a2023713}} darauf verlinkt.

Ich kann gerne per PN einen Zugang übermitteln, bei dem man es live sehen kann. In der Demo kann ich es leider nicht nachstellen da die Dateiverwaltung eingeschränkt ist.

PS: Server hostingwerk / nginx

**Comment by fritzmg** [comment]
Vermutlich solltest du zerst im Community Forum nach Hilfe suchen, bevor du das als Bug reportest.

**Comment by cgpro** [comment]
Dann werde ich da mal mein Glück versuchen, danke! :)
