### ISSUE TITLE
Unknown insert tag: faq_url

### ISSUE THREAD

**Issue by christianbarkowsky** [contao/core#8832]
Nach Aktualisierung von 4.4.10 auf 4.5.0 kommt ein 403 bei aktivierter Ordner-URL.

> [2017-12-28 20:07:04] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\AccessDeniedHttpException: "Access Denied." at /www/htdocs/vendor/symfony/symfony/src/Symfony/Component/Security/Http/Firewall/ExceptionListener.php line 117 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\AccessDeniedHttpException(code: 0): Access Denied. at /www/htdocs/vendor/symfony/symfony/src/Symfony/Component/Security/Http/Firewall/ExceptionListener.php:117, Symfony\\Component\\Security\\Core\\Exception\\AccessDeniedException(code: 403): Access Denied. at /www/htdocs/vendor/symfony/symfony/src/Symfony/Component/Security/Http/Firewall/AccessListener.php:68)"} []

**Comment by Aybee** [comment]
Contao 4 ist in core-bundle https://github.com/contao/core-bundle

**Comment by christianbarkowsky** [comment]
@leofeyer ups ... bitte verschieben.

**Comment by leofeyer** [comment]
Bitte ruf die Webseite mal über `app_dev.php` auf und poste den kompletten Stack-Trace.

**Comment by christianbarkowsky** [comment]
Nix Stack-Trace ... werde gleich wieder auf index geleitet.
Unter dev ist nun folgendes zu finden

**[2017-12-29 10:53:00] contao.INFO: Unknown insert tag: faq_url::3 [] []**

**Comment by aschempp** [comment]
Was hatt denn die Ordner URL mit einer Weiterleitung in einer News zu tun?

**Comment by christianbarkowsky** [comment]
@aschempp das war die erste Vermutung nach dem Live-Update gestern Abend. :confused:
Local habe ich den Fehler ebenfalls nachstellen können.

**Comment by fritzmg** [comment]
> Nach Aktualisierung von 4.4.10 auf 4.5.0 kommt ein 403 bei aktivierter Ordner-URL.

Du solltest eine genaue Reproduktion posten.

**Comment by leofeyer** [comment]
Ich bin mir ziemlich sicher, dass https://github.com/contao/core-bundle/pull/1275 oder https://github.com/contao/core-bundle/issues/1280 das Problem lösen wird.
