### ISSUE TITLE
File/image name for multilingual

### ISSUE THREAD

**Issue by xApep** [contao/core#8840]
Hi.
Let's say we have two version of website; English and German.
Let's also say that for SEO we want to be ranked for "motor homes".

As you know SEO ranking score for is also image name and alt.

Image name is "motor-home-scx-v65.jpg".

In File manager you can set "title, link and caption" for files/images, for different languages.
But you can't set different file/image name for different language - for the same image.

For example;
- in English the image name should be "motor-home-scx-v65.jpg"
- in German the image name should be "wohnmobil-scx-v65.jpg"

Or this feature is available in Contao and I just don't find it?

Thanks!

**Comment by fritzmg** [comment]
If you want files with different file names, you have to use different files. Only meta data can be stored for different languages.

**Comment by xApep** [comment]
Thanks. 
Wouldn't that be some nice feature if you could also add multilingual file name?

This is not really an issue in articles, news, etc. but it's a major issue in Isotope or in custom extensions where images are not "translated" and also when you have 100+ products / items you must select the same images 4-times (if you have 4 languages) and it takes unnecessary time to do this, since it can be solved much quicker.

A thing to think about it ;)

**Comment by kikmedia** [comment]
No, this is not available and will never be. Even on your desktop computer, a single file could not have multiple names.

**Comment by xApep** [comment]
Yeah you're right. The only solution would be, when you change multilingual file-name it should automatically duplicate image with new file-name and than some sort of a mapping (uuid).

Thanks for quick replay ;)
