### ISSUE TITLE
Missing $this in customizeSearch hook

### ISSUE THREAD

**Issue by Toflar** [contao/core#8841]
https://github.com/contao/core/blob/3.5/system/modules/core/modules/ModuleSearch.php#L130

The hook does not get `$this` as an argument which I consider to be a bug because you cannot adjust anything depending on the module settings (like `$arrPages` because you have no idea if a root page was set as reference page or not). To me that's the whole purpose of this hook so that's a bug to me :-)

**Comment by leofeyer** [comment]
Fixed in 9d7f3d5bc973aa04fbf73d2d99516a37d34256cf and contao/core-bundle@fe9042261b32e97ad0e58ee7aea357daebe0b4e9.
