### ISSUE TITLE
Alias ersetzt keine Umlaute (4.4.x)

### ISSUE THREAD

**Issue by timgatzky** [contao/core#8842]
Hi Leute,
in Contao 4.4 werden per standardize() die Umlaute äöü (wahrscheinlich auch andere Sonderzeichen) nicht mehr umgeschrieben. Damit entstehen Alias mit Sonderzeichen.
Ist das beabsichtigt - hab ich was übersehen?

VG, Tim

**Comment by fritzmg** [comment]
Ja, das ist beabsichtigt. In Contao 4.5 ist das nun konfigurierbar und in Contao 4.4 kannst du https://packagist.org/packages/ausi/contao-slug-backport installieren um es dort auch konfigurierbar zu machen.

**Comment by timgatzky** [comment]
Wenn ich das nicht installiere, wie quasi 99% aller Anwender, entstehen irgendwelche Probleme wenn die Alias Umlaute beinhalten?

**Comment by fritzmg** [comment]
Keine technischen zumindest. Nur Probleme mit Kunden, die sich darüber aufregen, dass die URL nicht schön aussieht, wenn sie sie vom Browser bspw. in eine Email kopieren :grin:

**Comment by timgatzky** [comment]
Wie verhalten sich Inserttags, die mit Alias referenziert werden? {{article::ALIAS}} erlauben die Inserttags hier Umlaute?

**Comment by fritzmg** [comment]
Dem Insert Tag ist das egal, ja.

**Comment by Aybee** [comment]
Mmh, d.h. wenn wir bei den Kunden auf die LTS setzen, was ich z.B. mache, dann müssen wir das bis Dezember 2019 als Erweiterung installieren? Das ist ja "%27ne+sch%C3%B6ne+Schei%C3%9Fe". Kann man das nicht in die 4.4 direkt reinpacken?

**Comment by timgatzky** [comment]
Ich dachte auch, das wäre aus Versehen passiert. An sowas fummelt man ja nicht rum. (Mich wundert nichts mehr.)

**Comment by premiumcontaothemes** [comment]
Wie wird das begründet, dass das nicht mehr Teil von Contao ist? Jemand muss sich dabei was gedacht haben...

**Comment by fritzmg** [comment]
Dass unicode in Aliasen unterstützt werden wurde in Contao 4.4 als feature implementiert. Ab Contao 4.4 kannst du daher zB auch solche URLs haben:
```
https://example.org/电脑坏了
```

**Comment by fenepedia** [comment]
Amazon verwendet z.B. auch URLs mit Umlauten.

Beispiel:
https://www.amazon.de/Die-Wege-zur-Effektivit%C3%A4t-pers%C3%B6nlichen/dp/3897495732

Ich fände es aber trotzdem gut, wenn die Erweiterung noch in Contao 4.4 integriert wird.

**Comment by Aybee** [comment]
Ändert aber nichts daran, dass ich diesen Link nicht lesen kann, auch wenn er von Amazon ist 😉

**Comment by fritzmg** [comment]
Den kannst du aber lesen: https://www.amazon.de/Die-Wege-zur-Effektivität-persönlichen/dp/3897495732 ;)

**Comment by Aybee** [comment]
Yup, that's better.

**Comment by fritzmg** [comment]
So gibt Contao 4.4 das aber auch aus. Der _Browser_ encodet dann aber leider die URL, wenn du die URL kopierst.

**Comment by Aybee** [comment]
Ja, aber ich glaube dies wurde in diversen Tickets schon alles diskutiert. Der Punkt ist, dass nicht wirklich abzusehen ist, in welchem Kontext die nicht lesbare URL nachher ausgegeben wird. Z.B. in Newslettern oder Emails.

Diese URL hier kann man auch leicht lesen und diese bleibt beim Kopieren so, wie man sie hier liest.
https://www.amazon.de/Die-Wege-zur-Effektivitaet-persoenlichen/dp/3897495732
