### ISSUE TITLE
3.5.28: Member with auto-login still logged in although his credentials changed

### ISSUE THREAD

**Issue by connine** [contao/core#8843]
I noticed the following behavior in Contao 3.5.28: 

- I used a member account to log into a restricted FE page and checked the auto-login option
- I changed the username of this member in the BE and closed the browser I used for FE login
- I opened the browser again and was logged in automatically with my old credentials 
- Same happend when I changed the password of this member account

In my opinion the auto-login function should be disabled if the account information changes.

**Comment by leofeyer** [comment]
As discussed in Mumble on February 15th, we should remove the autologin hash from `tl_member.autologin` if the username or the password changes. This affects Contao 3.5 to 4.4 (Contao 4.5 uses Symfony security).

**Comment by leofeyer** [comment]
Fixed in 9a6cc88f31ee486e5ca82d1524ebd76a680770cb.
