### ISSUE TITLE
DCA speichert veraltete IDs in Session

### ISSUE THREAD

**Issue by SGehle** [contao/core#8845]
Ich würde gerne in einem onload_callback die IDs der aktuell angezeigten Datensätze ausgeben lassen, allerdings gibt  $session['CURRENT']['IDS'] nur die IDs des letzten Aufrufs aus.
Meine Verdacht: Vielleicht werden die Filter erst nach dem Aufruf des onload_callback aktiv, daher habe ich das gleiche über ein global_operations button_callback versucht. Gleiches Problem.

Habe ich einen Denkfehler oder ist dies ein Bug?

**Comment by leofeyer** [comment]
Du beziehst Dich vermutlich auf folgende Zeilen:

https://github.com/contao/core/blob/c7f0310ebd3f4e8b32a82f10f9ffa6827ab4b2a3/system/modules/core/drivers/DC_Table.php#L387-L390

Diese Zeilen stammen noch aus Zeiten von TYPOlight 2 und wurden in Contao 4 bereits entfernt (siehe https://github.com/contao/core-bundle/issues/1130). `$session['CURRENT']['IDS']` enthält die IDs der Datensätze, die in der Ansicht "mehrere bearbeiten" ausgewählt wurden und nicht die IDs der aktuell angezeigten Datensätze.
