### ISSUE TITLE
nl_default - Captcha fehlt, obwohl aktiviert

### ISSUE THREAD

**Issue by marcfunkitug** [contao/core#8846]
Hallo!

In der Contao 4.4.1.1 bauen wir gerade einen Newsletter. Im Backend unter "Module" kann man bei "Abbonieren" einstellen, ob ein Captcha angezeigt werden soll oder nicht.

Auch bei deaktivierter Funktion (Captcha ausblenden), wird das Captcha nicht angezeigt.
Im Template betrifft dies Zeile 36, in der mittels <?= $this->captcha ?> das entsprechende ausgegeben werden soll.

Diese Variable ist aber komplett leer.

**Comment by BugBuster1701** [comment]
Ab 4.4.0 gibt es das Feature: "Hide the CAPTCHA field by default by adding a honeypot field"
D.h., erst wenn ein "Bot"  ein verstecktes Feld füllt, kommt das Captcha zum Vorschein beim Absenden.
