### ISSUE TITLE
Newsletter -> Rechtlicher Hinweis

### ISSUE THREAD

**Issue by marcfunkitug** [contao/core#8847]
Schön wäre es, dass beim Abonnieren des Newsletters die Möglichkeit bestünde eine Checkbox als Pflichtfeld zu definieren.

In Deutschland ist es der Fall, dass eine Datenschutzerklärung mit der Newsletteranmeldung akzeptiert wurden muss (vor allem in Bezug auf den 25.05.2018, Stichwort DS-GVO).

Deshalb halte ich dieses "Pflichtfeld" als dringendes Feature für Contao!

**Comment by joke1** [comment]
Ich denke nicht, dass dies notwendig ist. Wie willst du denn beweisen, dass der Nutzer auf die Checkbox geklickt hat?
Wichtig ist, dass deine Opt-In E-Mails keine Werbung beinhalten & du die Einverständnis dokumentierst. Einmal das Verfahren an sich und einmal die jeweilige Einverständnis, falls dich jemand bei der Aufsichtsbehörde meldet. 

Hier sind einige Sachen ganz gut erklärt. Einiges ändert sich übrigens auch wieder 2019, wenn die e-Privacy-Verordnung inkraft tritt...
https://www.onlinehaendler-news.de/recht/gesetze/26117-datenschutzgrundverordnung-dsgvo-teil-1-newsletterversand.html

**Comment by leofeyer** [comment]
> In Deutschland ist es der Fall, dass eine Datenschutzerklärung mit der Newsletteranmeldung akzeptiert wurden muss (vor allem in Bezug auf den 25.05.2018, Stichwort DS-GVO).

Das habe ich bisher auch noch nirgends gelesen. @marcfunkitug Woher stammt diese Info?

**Comment by marcfunkitug** [comment]
html,body{background-color:#fff;color:#333;line-height:1.4;font-family:sans-serif,Arial,Verdana,Trebuchet MS;}Aktuell besuche ich sein Seminar zur neuen DS-GVO und grundsätzlich muss ich "einen Nachweis des Double-Opt-In / Einwilligung zum Newsletter" haben. Um diesen korrekt haben zu können, muss Datum, IP und E-Mailadresse gespeichert werden. Anhand dieser Daten ist ein personenbezogener Bezug möglich. Frage ich z. B. noch freiwillig Vor- und Nachname ab, speichere ich generell personenbezogene Daten, wofür ich das Einverständnis haben muss und dem Empfänger über seine Rechte aufklären muss.

 

Freundliche Grüße sendet Ihnen

Marc Funk IT UG (haftungsbeschränkt)
Bahnhofstraße 7b
44623 Herne

Tel: + 49 23 23 / 399 80 32
Fax: + 49 23 23 / 399 80 31
Mail: kontakt@marc-funk.de
Web: https://marc-funk.de

USt.-ID: DE295742420
Amtsgericht Bochum
HRB 15027

Leo Feyer schrieb am 15.03.2018 11:09:



In Deutschland ist es der Fall, dass eine Datenschutzerklärung mit der Newsletteranmeldung akzeptiert wurden muss (vor allem in Bezug auf den 25.05.2018, Stichwort DS-GVO).


Das habe ich bisher auch noch nirgends gelesen. @marcfunkitug Woher stammt diese Info?

**Comment by AlexanderPilhar** [comment]
Ich beschäftige mich ebenfalls seit einiger Zeit mit der DSGVO und wie diese im Detail umsetzbar ist - und recherchiere eben gerade zum Thema Einwilligungserklärung zu Newslettern. Zumindest in Deutschland scheint einfaches Double Opt-In ohnehin schon längst nicht mehr zu genügen:

- [Abmahnungs-Abonnement: Wann Newsletter für den Anbieter zum Risiko werden](https://www.rgblog.de/newsletter-einwilligungstext/)
- [Birgt Ihr E-Mail-Newsletter ein Abmahnrisiko? – Schlechte Beispiele und Gute Beispiele](https://drschwenke.de/birgt-ihr-e-mail-newsletter-ein-abmahnrisiko-schlechte-beispiele-und-gute-beispiele/)

Wichtig scheint insbesondere auch zu sein, dass man als Anbieter eines Newsletter die Einwilligung auch nachweisen kann - wofür Double Opt-In anscheinend nicht ausreicht...

**Comment by leofeyer** [comment]
Ich denke nicht dass die beiden Artikel aus 2012 und 2015 in irgendeiner Form eine Aussage zur DSGVO beinhalten.

**Comment by AlexanderPilhar** [comment]
Ja, da muss ich zustimmen - der Kommentar bezog sich aber auch weniger auf die DSGVO, sondern vielmehr darauf, dass man eine Einwilligung nachweisen können muss (und mit DSGVO weiterhin muss) und Double Opt-In bislang scheinbar nicht ausgereicht hat.

Hier ist ein aktueller Artikel zum Thema:
[Einwilligung bei der DSGVO: Das Opt-In und Double-Opt-In Verfahren](https://www.lpsp.de/blog/einwilligung-dsgvo-double-opt-in-verfahren)

Wenn ich mir die DB-Struktur so ansehe, dürfte Contao bereits DSGVO-konforme Einwilligungen und deren Nachweis ermöglichen (im Artikel Abschnitt "Nachweispflicht": Timestamp der Einwilligung)!?

**Comment by cmeis** [comment]
Mindestens ein Problem bleibt mit dem "normalen" Contao-Newsletter aber bestehen:
Wenn ein Abonnent den Newsletter abbestellt, wird der Eintrag aus der Tabelle entfernt. Dir fehlt also ab diesem Zeitpunkt der Nachweis, dass in der Vergangenheit (bis zum Abbestellen) eine Einwilligung vorgelegen hat.
Wenn Dich der Empfänger also NACH seiner Abmeldung dazu kontaktiert, hast Du keine Info mehr (außer z.B. in Backups der DB o.ä.).

Wir machen es so, dass wir die Anmeldung (und auch Abmeldung) jeweils in einer separaten Tabelle dokumentieren.

**Comment by leofeyer** [comment]
Und was speichert ihr in der separaten Tabelle?

Der Abonnent hat ja das Recht auf Löschung der personenbezogenen Daten, daher darf man ab dem Zeitpunkt des Abbestellens weder die IP-Adresse noch die E-Mail-Adresse weiterhin speichern. Wie also soll der Nachweis erfolgen?

Gibt es eine gesetzliche Vorschrift zur Speicherung der Opt-In-Daten? Oder eine Regelung wie lange man ein erfolgtes Opt-In nach Ende des Abonnements nachweisen können muss?

**Comment by cmeis** [comment]
In der Tabelle stehen "natürlich" die wichtigsten Eckdaten, also Timestamp, Mailadresse und IP. Das ganze Thema ist in der Tat etwas "grau".

Unser Kunde möchte sich ggf. gegen unberechtigte Beschwerden wehren können (ich konstruier mal: ich melde mich ab, und beschwer mich direkt danach über den letzten erhaltenen Newsletter; es soll der Nachweis möglich sein, dass zum Zeitpunkt des Versandes der Newsletter abonniert war). Je nachdem, wen man fragt, ist das über ein "berechtigtes Interesse" für einen gewissen Zeitraum sauber...

Das andere ist, wenn der Kunde generell ein "Werbeverbot" ausspricht - in diesem Fall MUSS ich seine Mailadresse ja zwangsläufig behalten. Nämlich um sicherzustellen, dass ich ihm eben KEINE Mails mehr sende (im Sinne einer Empfänger-Blacklist).

Aber das ganze Thema ist natürlich aktuell eines mit einem guten Rest Rechts-Unsicherheit, wir werden mal sehen wie sich das entwickelt. ;-)

**Comment by leofeyer** [comment]
Wir haben die nach aktuellem Kenntnisstand notwendigen DSGVO-Änderungen implementiert (siehe https://github.com/contao/core-bundle/issues/1512#issuecomment-401007331). Die Speicherung der Daten in einer separaten Tabelle, aus der sie trotz Beendigung des Abonnements nicht gelöscht werden, ist rechtlich höchst bedenklich und wird daher von Contao nicht unterstützt.
