### ISSUE TITLE
generateSitemap does not properly handle port-components in URLs

### ISSUE THREAD

**Issue by binfalse** [contao/core#8848]
When urls in Contao require a port (such as `https://example.com:1234`, eg. when running at an unusual port), the urls in the sitemap become invalid...
The Automator sends every single url through [`rawurlencode`](https://secure.php.net/manual/en/function.rawurlencode.php), see https://github.com/contao/core/blob/c7f0310ebd3f4e8b32a82f10f9ffa6827ab4b2a3/system/modules/core/library/Contao/Automator.php#L414 (properly to prevent invalid XML?)
But `rawurlencode` will convert much more than necessary for XML documents... Therefore a few entities are recovered afterwards, see https://github.com/contao/core/blob/c7f0310ebd3f4e8b32a82f10f9ffa6827ab4b2a3/system/modules/core/library/Contao/Automator.php#L415
However, colons are only recovered in combination with `://`... Thus, port components will become something like `https://example.com%3A1234`

Thus, the resulting sitemap contains lot's of invalid urls...

**Comment by binfalse** [comment]
PR #8849 uses [`htmlspecialchars`](https://secure.php.net/manual/en/function.htmlspecialchars.php) instead of [`rawurlencode`](https://secure.php.net/manual/en/function.rawurlencode.php) to create XML-safe versions of the URLs, which should fix the problem.
(However, I'm not sure if anything else is relying on `rawurlencode`-like entities somewhere?)

**Comment by aschempp** [comment]
Should we use CDATA instead of urlencode? Or is there a Google recommendation?

**Comment by dmolineus** [comment]
The requirements for url  escaping are described here: https://www.sitemaps.org/protocol.html

**Comment by fritzmg** [comment]
Only the path and query should be encoded probably, not the whole URI including the host and port.

**Comment by leofeyer** [comment]
See #8849.
