### ISSUE TITLE
Eval findInSet will not sort by label

### ISSUE THREAD

**Issue by Aybee** [contao/core#8852]
In a field type `select` with
```php
...['eval']['findInSet'] = false;
```
the options are not sorted by theire values. Neither by setting it to `true`.

**Comment by leofeyer** [comment]
How do I reproduce this? Which field did you test and where did you test it (BE or FE)?

**Comment by Aybee** [comment]
I saw this in BE with a new field for tl_members with chosen multiselect.
```php
$GLOBALS['TL_DCA']['tl_member']['fields']['foo'] = array(
  'label'     => &$GLOBALS['TL_LANG']['tl_member']['foo'],
  'inputType' => 'select',
  'options'   => $GLOBALS['TL_LANG']['CUSTOM']['foo'],
  'eval'      => array('findInSet'=>true, 'multiple'=>true, 'chosen'=>true, 'includeBlankOption'=>true, 'mandatory'=>false, 'feEditable'=>true, 'feViewable'=>true, 'feGroup'=>'custom'),
  'sql'       => "blob NULL"
);

$GLOBALS['TL_LANG']['CUSTOM']['foo'] = array(
   'a',
   'c',
   'b'
);
```

**Comment by leofeyer** [comment]
And what output exactly do you expect?

**Comment by Aybee** [comment]
I expect the output that is stated in the docs.
https://docs.contao.org/books/api/dca/reference.html
https://docs.contao.org/books/manual/3.3/de/06-Data-Container-Arrays.html
> EN Sort by the actual option values instead of their labels.
DE Sortiert ein Optionsarray anhand der Schlüssel anstatt anhand der Werte.

The keys in my example are 0, 1, 2. The values are a, c, b. So I expect a sorting a, b, c when set to false and a, c, b whe set to true.

**Comment by ausi** [comment]
I think the german translation is misleading.
The `findInSet` option is for sorting the entries in the listView of the DCA, not for sorting the options array itself for the widget. See https://github.com/contao/core/blob/c7f0310ebd3f4e8b32a82f10f9ffa6827ab4b2a3/system/modules/core/drivers/DC_Table.php#L4414

**Comment by leofeyer** [comment]
@Aybee Please create an issue (or preferably a pull request) at https://github.com/contao/docs.

**Comment by Aybee** [comment]
Ok. I sorted the values with
```php
natcasesort($GLOBALS['TL_LANG']['CUSTOM']['foo']);
```
