### ISSUE TITLE
Überprüfung der E-Mail Adresse

### ISSUE THREAD

**Issue by netserving** [contao/core#8853]
Hallo zusammen,

ich hoffe ich habe nichts übersehen.
Die aktuelle Prüfung der E-Mail Adresse lässt beispielsweise die Endung .jetzt nicht zu.

Sollte dies noch nicht in der neusten Version integriert sein, würde eine Anpassung dringend Sinn machen.

Mit freundlichen Grüßen
Paul Schmitz

**Comment by leofeyer** [comment]
Wie lässt sich das in der Onlinedemo reproduzieren?

**Comment by netserving** [comment]
in der aktuellen Onlinedemo lässt sich der Fehler nicht reproduzieren.
In der Version 3.5.19 kommt es allerdings zum Fehler.
Ich gehe davon aus das diese Version nicht mehr im LTS ist, daher kann der Fehler ignoriert werden.

**Comment by fritzmg** [comment]
Bevor du einen Fehler meldest, solltest du generell immer zuerst Contao aktualisieren.
