### ISSUE TITLE
Sending newsletters to invalid domains

### ISSUE THREAD

**Issue by leofeyer** [contao/core#8854]
If the domain of an e-mail address does not exist, the newsletter sending process will fail with the following exception:

```
PHP Fatal error: Uncaught exception 'Swift_TransportException' with message 'Expected response code 250 but got code "450", with message "450 4.1.2 <kontakt@ich-existiere-nicht.ch>: Recipient address rejected: Domain not found
```

We are already catching e-mail addresses which are not RFC compliant, so I guess we should check this case as well. However, we cannot simply catch all `Swift_TransportException` exceptions, because exceptions such as

```
Uncaught exception 'Swift_TransportException' with message 'Connection could not be established with host mailserver.com  [Connection timed out #110]
```

should definitely be throws.

@contao/developers How do we solve this? Should we `preg_match()` the exception message?

**Comment by Toflar** [comment]
What would you do then? Throw a more specific exception and catch this or what's the plan?

**Comment by leofeyer** [comment]
As discussed in Mumble on February 15th, we have to analyze the exception code (which is the [SMTP reply code](http://www.supermailer.de/smtp_reply_codes.htm)) and process it accordingly. We also need to distinct between `450 4.1.2 Domain not found` and `450 4.2.0 Greylisted` and so on.

Either way, this kind of errors should not terminate the sending process.

**Comment by leofeyer** [comment]
Unfortunately I cannot reproduce this in my local test environment. Instead of throwing an exception, the request just times out (using an external SMTP server).

Can anyone else reproduce this?
