### ISSUE TITLE
How to install a Contao 3.x extension in Contao 4.x managed edition?

### ISSUE THREAD

**Issue by diegovdev** [contao/core#8857]
Hi I found a few places that explain how to add an old Contao 3.x extension to Contao 4.x. But all those places talk about an app/AppKernel.php file that does not exist in Contao 4.4.13, I guess that file exists only in the standard edition. See [here](https://stackoverflow.com/questions/46195570/how-to-install-extensions-in-contao-4-4) and [here](https://www.marcosimbuerger.ch/contao-kurzanleitungen-details/contao-3-erweiterung-in-contao-4-installieren.html).

Also the [official manual](https://docs.contao.org/books/extending-contao4/) is incomplete in this regard. So I am asking here in hope I can get an answer. I created my own extensions for Contao 3.x years ago and I would like to use them in a new Contao 4.4 installation. Thanks!

**Comment by fiedsch** [comment]
If I'm not mistaken, it should be enough to add `~4.4` in the `requires` section of your extensions `composer.json` like so:

```
 "contao/core-bundle":"~3.5 || ~4.4",
```

**Comment by fritzmg** [comment]
> Hi I found a few places that explain how to add an old Contao 3.x extension to Contao 4.x.

Do you mean making it available via composer, like @fiedsch suggests? See the README of the composer-plugin: https://github.com/contao-community-alliance/composer-plugin/blob/master/README.md

If you mean manually installing, that's all you have to do in the Managed Edition:

* copy the extension to `system/modules`
* delete `var/cache`
* execute the Contao Install Tool

Any extension in `system/modules` is automatically loaded in the Contao Managed Edition.

**Comment by Aybee** [comment]
Or without the console only with the Contao Manager
- copy the extension to `system/modules`
- refresh the packages with the manager to create symlinks

Also see Contao 3 extension in Contao 4 https://youtu.be/rwC8xfdO3Ao?t=681 - duration 2:04

**Comment by diegovdev** [comment]
Thanks for your responses. I meant install manually without composer, so I followed the steps from @fritzmg and also added this 2 steps:
* go to `backend > System > Maintenance` and run the `"Recreate the symlinks"` job
* go to `http://localhost/contao/install` and update database

That worked just fine. Thanks.
