### ISSUE TITLE
DC Tables stores invalid data records

### ISSUE THREAD

**Issue by dmolineus** [contao/core#8862]
The DC table saves data even if an error occurs in the edit mask. This leads to invalid data records. 

Think about a user is editing an event where a duplicated alias exist.
 - Title is saved
 - Exception is thrown then saving the alias
 - Date is not updated

If an error occurs no data should be saved. This behaviour leads to invalid data records if the user stop working on the data record.

**Comment by aschempp** [comment]
This is a known limitation of the DC Table. It even creates empty records if you start adding a record. I don't think we can change it without a completely new DC.

**Comment by leofeyer** [comment]
We cannot.

**Comment by dmolineus** [comment]
Couldn't transactions solve the issue since Contao 4.5 uses innodb?

**Comment by aschempp** [comment]
A transaction would not solve the problem of page reload data updates.
