### ISSUE TITLE
Insert tags are not working in event title

### ISSUE THREAD

**Issue by Schooott** [contao/core#8863]
Insert tags are not working if they are used in event titles.
Contao 4.4.14 and 4.4.16.

**Comment by leofeyer** [comment]
How do I reproduce this?

**Comment by Schooott** [comment]
Add any insert tag to an event title like this with Contao version 4.4.16:
`My event {{version}}`

**Result:** Insert tags are not shown on eventlist or details.

This works for news titles, so it should work for events in the same way.

**Comment by Schooott** [comment]
Seems to work with:
`<?= $this->link ?>`
but not with
`<?= $this->title ?>`
When used in the event_list template.
Is this intended?

**Comment by leofeyer** [comment]
I just checked this with my local 4.4 installation. I have appended `{{version}}` to all news articles and events of the Contao Official Demo and then opened the front end in my browser.

* The version number was shown in the news list, news archive and news reader modules.
* The version number was shown in the event list, upcoming events and event reader modules.

The `event_full.html5` template uses `$this->title`, therefore I cannot reproduce what you are saying. Can you please try to reproduce it in the [online demo](https://demo.contao.org/contao)?
