### ISSUE TITLE
Bild/Galerie: Link-Attribut optimieren

### ISSUE THREAD

**Issue by minstyle** [contao/core#8865]
Hallo zusammen,

in Contao 4.4.16 werden automatisch alle Bilder (mit aktivierter Option "Großansicht") mit dem Attribut `<a data-lightbox="xyz"><img><a>` versehen.

Beispiel:

![screenshot](https://user-images.githubusercontent.com/2649562/37460990-3eed0862-284d-11e8-8c41-cb097eca2bba.png)

Verantwortlich ist dafür die Contao-Variable `<?= $col->attributes ?>`.

Allerdings wird das Link-Attribut `data-lightbox` standardmäßig ausgegeben. Schön wäre es, wenn man diesen Begriff jederzeit nach seinen eigenen Bedürfnissen anpassen könnte. So möchte ich beispielsweise hier den Begriff `data-fancybox` stattdessen nutzen.

Beispiel:

![screenshot2](https://user-images.githubusercontent.com/2649562/37461487-c942b808-284e-11e8-90ba-60e302ea583c.png)

Idealerweise ist in der Variable `<?= $col->attributes ?>` nur der generische Bildwert (hier: "lb41") hinterlegt und das Link-Attribut legt man im HTML-Template oder anderswo global und updatesicher fest.

**Comment by Aybee** [comment]
Dazu bekommst du im Forum bestimmt eine einfache Lösung. Ich denke nicht, dass man das Attribut im Inhaltselement einstellbar machen muss.

Wie initialisierst du die Fancybox? Du kannst die Links mit dem Attribute data-lightbox per JS suchen und modifizieren wie du möchtest, bevor du die Fancybox initialisierst.

Ein "Link-Attribut" gibt es nicht.

**Comment by minstyle** [comment]
Vielen Dank für deine Antwort.

Habe es nun selbst mit PHP `str_replace` gelöst. Trotzdem finde ich es schade, dass hier `data-lightbox` von Contao vorgegeben wird.

**Comment by Aybee** [comment]
Ich würde es im j_fancybox Template machen, da du dieses ja sowieso brauchst, dann sparst du dir ein angepasstes Template. Es gibt auch eine Fancybox Erweiterung, welche auch ein eigenes Template mitbringt. Aber Achtung, dort wird ein REL-Attribut hinzugefügt, welches dann invalide Werte bekommt. In HTML sind nur bestimmte Werte valide https://developer.mozilla.org/de/docs/Web/HTML/Link_types.
(Immer wieder gesehen, dass der Wert "follow" benutzt wird, dieser ist z.B. auch invalide.)

Also reicht data-lightbox, welches im Core bereits Colorbox, Mediabox und Slimbox unterstützt, auch für alle anderen Lightboxes. Eine Erweiterung mit einer neuen Box benötigt nur ein entsprechendes Template, welches man ja sowieso aufsetzt.
