### ISSUE TITLE
Problem mit Inserttag {{br}} in Events Contao 3.5.34

### ISSUE THREAD

**Issue by Misco** [contao/core#8867]
```
<?php if ($this->hasDetails): ?> 
    <h2><a href="<?= $this->href ?>" title="<?= $this->title ?> (<?php if ($this->day) echo $this->day . ', '; ?><?= $this->date ?><?php if ($this->time) echo ', ' . $this->time; ?>)"<?= $this->target ?>><?= $this->link ?></a></h2> 
  <?php else: ?> 
    <h2><?= $this->title ?></h2> 
  <?php endif; ?>
```

{{br}} $this->link klappt.
{{br}} $this->title klappt nicht.

sollte sich gleich verhalten, oder?

**Comment by Aybee** [comment]
Das gäbe Probleme, da `$this->title` auch für Attribute - hier `title` -  gedacht ist.

**Comment by Misco** [comment]
$this->link auch im else verwenden. Auch ohne Detail-Element erfolgt eine Ausgabe.
Die Bezeichnung ist dann nur etwas Irreführend, umbennen in $this->headline?

**Comment by asaage** [comment]
Ich würde an deiner Stelle darauf verzichten ```{{br}}``` in Titelfeldern zu verwenden.
im Template kommst du evtl. noch mit [StringUtil](https://github.com/contao/core/blob/3.5/system/modules/core/library/Contao/StringUtil.php) hin.
Wie es mit dem title-Element im head aussieht weiß ich allerdings gerade nicht und im BE bleibts ohnehin sichtbar.

**Comment by fritzmg** [comment]
`{{br}}` in Titeln ist an und für sich kein Problem. Contao entfernt an allen relevanten Stellen automatisch die Insert Tags, anstatt sie zu ersetzen. Des wegen funktioniert auch hier der `{{br}}` Insert Tag nicht, weil ja, wie schon angemerkt wurde, der Event Titel auch in einem `title` Attribut zum Einsatz kommt und dort natürlich kein HTML Code ausgegeben werden sollte.

**Comment by Aybee** [comment]
Von welchem Modul sprichst du hier überhaupt?

In der **Eventlist** bekommst du den Titel mit Inserttags und HTML mit `$this->link`. `$this->title` ist ohne HTML, weil für das TITLE-Attribut gedacht.

In dem **Eventreader** bekommst du den Titel mit Inserttags und HTML über `$this->title`.

> {{br}} $this->link klappt.
{{br}} $this->title klappt nicht.
sollte sich gleich verhalten, oder?

Die Anwort darauf ist also "Nein".

Habe gerade aber festgestellt, das das TITLE-Tag und TITLE-Attribut unschön aussehen. Aus
```html
Contao Example{{br}}Event
```
wird
```html
<title>Contao ExampleEvent</title>
... title="Contao ExampleEvent" ...
```

**Comment by fritzmg** [comment]
Naja, das ist aber ein Befüllungsfehler. Man sollte `Contao Example{{br}} Event` oder `Contao Example {{br}}Event` eingeben.

**Comment by Misco** [comment]
Mir ging es um das Verhalten der h2 in der fertigen Webseite, diese Verhält sich so Unterschiedlich je nach dem ob es mehr als den Teaser gibt oder nicht.

Contao 
Example Event
Teaser
mehr>

Contao Example Event
Teaser

**Comment by Aybee** [comment]
Ich denke, du solltest das im Forum klären. Du hast noch nicht gesagt, welches Modul es betrifft und das mit der H2 und dem Teaser geht aus deinem ersten Post auch nicht hervor.

Achte aber schonmal darauf, dass du das Template `event_full` nur für den Reader und die anderen event_-Templates aus dem Core nur für die Liste nehmen kannst. Die Auswahl ist zwar leider möglich, aber es ist nicht gesagt, dass die vorhandene Variablen identisch sind. Normalerweise liefert jedes Modul eigene Variablen.
