### ISSUE TITLE
Undefined variable in branch 3.x

### ISSUE THREAD

**Issue by lindesbs** [contao/core#8868]
Beginning of branch 3.x the variable blnRecordExists is used without initialized with data. This bug results in cleaning autologin data on logout()

The variable blnRecordExists in branch 2.11
Initialization in 
https://github.com/contao/core/blob/2.11/system/libraries/Model.php#L77

Defined when row exists
https://github.com/contao/core/blob/2.11/system/libraries/Model.php#L178

In the branch 3.x it is used in 
https://github.com/contao/core/blob/3.5/system/modules/core/classes/FrontendUser.php#L244

But this variable will never be defined

**Comment by leofeyer** [comment]
That is true, however I don't see how this can result in cleaning the data? Since the property is never initialized, it should be `null` and thus result in **not** cleaning the data. Did you mean this?

**Comment by lindesbs** [comment]
Yes. Users which has been self logout manually, will be relogedin automatically.

**Comment by leofeyer** [comment]
@contao/developers I guess we can just remove the if condition entirely, can't we?

**Comment by lindesbs** [comment]
Our fix is replacing with this:
if ($this->autologin)

**Comment by aschempp** [comment]
Very interesting find. The variable is undefined because the User class is no longer based on Model since Contao 3. I don't understand why the check for `blnRecordExists` is necessary at all though...

**Comment by aschempp** [comment]
Well it is possible to do a `FrontendUser::getInstance()` call and call `logout`, which would be an unexpected result. We should probably check for `$this->intId > 0`.

**Comment by lindesbs** [comment]
There is an additional problem with ModuleCloseAccount. We have to check, if the MemberRow still exists. The entry will be deleted afterwards it will be logout()
https://github.com/contao/core/blob/3.5/system/modules/core/modules/ModuleCloseAccount.php#L135

**Comment by leofeyer** [comment]
IMHO, `$blnRecordExists` should simply be replaced with `\Config::get('autologin') > 0` (see `FrontendUser::login()`.

@aschempp What is the case in which we have to check `$this->intId > 0`?

**Comment by aschempp** [comment]
> @aschempp What is the case in which we have to check $this->intId > 0?

We're using that in Contao 4 to determine if a user is loaded.
 - https://github.com/contao/core-bundle/blob/4.5/src/Resources/contao/library/Contao/User.php#L225
 - https://github.com/contao/core-bundle/pull/1477/files#diff-b5f5d2dd78f20df363e462370be2c122R552

**Comment by leofeyer** [comment]
@lindesbs Does this issue occur in Contao 4 as well?

**Comment by lindesbs** [comment]
Not yet tested

**Comment by leofeyer** [comment]
@lindesbs Do you have time to check? If it occurs in Contao 4 as well, we have to fix it.

**Comment by lindesbs** [comment]
Obviously no further impact

**Comment by leofeyer** [comment]
I still think we should fix this if we implement #8888.

**Comment by leofeyer** [comment]
Fixed in 148cfdecd7dad2961be160f61752ad4093231fc0.
