### ISSUE TITLE
Variable für den Namen des Event-Archivs fehlt in den Event-Details

### ISSUE THREAD

**Issue by elektrischerwalfisch** [contao/core#8869]
Aktuell gibt es keine Möglichkeit sich bei den Event-Details (Template event_full.html5) über eine Variable den Namen des Archivs ausgeben zu lassen in dem sich das Event befindet. Man kann sich über  `<?php echo $this->pid ?>` zwar die ID des Archivs ausgeben lassen, aber nicht den Namen.
In der Eventliste (Template event_teaser.html5) ist das mit `<?php echo $this->calendar->title ?>` möglich, aber eben nicht bei den Event-Details.

**Comment by leofeyer** [comment]
Implementiert in contao/calendar-bundle@46c09ea73576c1bd0a560ae74f94b7c1fa1115aa.
