### ISSUE TITLE
Check for GDLib with JPEG

### ISSUE THREAD

**Issue by ScreamingDev** [contao/core#8872]
Contao surely checks if all php modules are available during installation and nags about it.
But just looking for GDLib is not the same as using gd for JPEG images, which can still fail.
Please check if gd is capable if editing jpeg, gif and png files during installatoin and warn about possible problems.

- GDLib is listed as mandatory but not in detail.
- Not blocking installation, just warn that images may not be maintainable.
- Maybe add simple small images to the repo and edit them.
- Breaks backend when user want to edit an image from a preinstalled theme (message: "Unable to open image ...")

**Comment by fritzmg** [comment]
> Contao surely checks if all php modules are available during installation and nags about it.

Contao does no such thing.

**Comment by leofeyer** [comment]
@ScreamingDev Can you please elaborate?

**Comment by discordier** [comment]
@leofeyer I guess he has PHP with gd but compiled it without `--with-jpeg --with-gif --with-png` or at least one of them is missing.

Hence he has gd loaded but it can not open his files and is getting a fatal then.
