### ISSUE TITLE
Contao 3.5.x (LTS) doesn't handle dbSqlMode correctly when dbPconnect is used

### ISSUE THREAD

**Issue by robert-scheck** [contao/core#8875]
In MariaDB 5.5.x, `SQL_MODE` was not set by default. Since MariaDB 10.1.x, `SQL_MODE` is set by default to `NO_ENGINE_SUBSTITUTION,NO_AUTO_CREATE_USER` or with MariaDB 10.2.x `SQL_MODE` is even set to `NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION,STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO` (see https://mariadb.com/kb/en/library/sql-mode/ for details).

In theory, Contao properly sets `SQL_MODE` explicitly empty by default (which should restore the old `SQL_MODE` behaviour), based on `system/config/default.php` with

```
$GLOBALS['TL_CONFIG']['dbSqlMode']   = '';
```

being finally used at `system/modules/core/library/Contao/Database/Mysqli.php` with

```
$this->resConnection->options(MYSQLI_INIT_COMMAND, "SET sql_mode='" . $this->arrConfig['dbSqlMode'] . "'");
```

Effectively this however only works when `dbPconnect` is *not* being used, thus

```
$GLOBALS['TL_CONFIG']['dbPconnect'] = false;
```

But once `dbPconnect` is `true`, e.g. MetaModels are poorly failing at `composer/vendor/metamodels/core/src/MetaModels/MetaModel.php` in line 980 or 990 due to the fact that an SQL statement like

```
INSERT INTO mm_example_discussion (tstamp) VALUES (1523883630);
```

might be executed for a schema like this:

```
+------------+------------------+------+-----+---------+----------------+
| Field      | Type             | Null | Key | Default | Extra          |
+------------+------------------+------+-----+---------+----------------+
| id         | int(10) unsigned | NO   | PRI | NULL    | auto_increment |
| pid        | int(10) unsigned | NO   |     | NULL    |                |
| sorting    | int(10) unsigned | NO   |     | 0       |                |
| tstamp     | int(10) unsigned | NO   |     | 0       |                |
| author     | int(11)          | NO   |     | 0       |                |
| text       | text             | YES  |     | NULL    |                |
| attachment | blob             | YES  |     | NULL    |                |
| datetime   | bigint(10)       | YES  |     | NULL    |                |
+------------+------------------+------+-----+---------+----------------+
```

With MariaDB 5.5.x, the SQL statement above just works. With MariaDB 10.x and `SQL_MODE` being set and `dbPconnect` to `true`, this fails with an exception containing

```
Query error: Field 'pid' doesn't have a default value (INSERT INTO mm_example_discussion (tstamp) VALUES (1523883630))
```

When however setting `dbPconnect` to `false`, above works again.

So while MetaModels are indeed generating suboptimal SQL statements or database schema, the issue trigger of `dbPconnect` between `true` and `false` should be still a Contao 3.5.x (LTS) related issue given MetaModels are reusing the database handle/object from Contao and are also not touching `SQL_MODE` at all.

**Comment by leofeyer** [comment]
Contao 3.5 is in the last phase of its release cycle and no longer receives bug fixes unless they are security related.
