### ISSUE TITLE
4.5.8 Zweiter, eigener Layoutbereich wird nicht angezeigt 

### ISSUE THREAD

**Issue by kubjo** [contao/core#8878]
Nach den Update auf 4.5.8 
erscheint ein zweiter eigener Layoutbereich nicht mehr im Quellcode.
Unter 4.5.6 war es noch so:
```
<div class="custom">
<div id="erster_eigener_Layoutbereich">...</div>
<div id="zweiter_eigener_Layoutbereich">...</div>
</div>
```
Nach dem Update fehlt:
`<div id="zweiter_eigener_Layoutbereich">...</div>`
komplett.

**Comment by leofeyer** [comment]
Das liegt vermutlich an den Änderungen aus contao/core-bundle#1115. @frontendschlampe /cc

**Comment by frontendschlampe** [comment]
Naja, es sollte eigentlich nicht der Fall sein, wenn beide Layoutbereiche Inhalte haben. @kubjo wie und wo hast du die Layoutbereiche eingelegt? Haben beide Inhalt?

**Comment by kubjo** [comment]
Der Erste beinhaltet die Navi, der zweite hat keinen Inhalt. Der zweite dient in meinem Fall als leerer Bereich, der den Hintergrund sichtbar macht. Zu sehen hier: [https://www.wernerottens.de](https://www.wernerottens.de)  Habe inzwischen ein Leerzeichen als HTML Code eingefügt und dadurch den Layoutbereich wieder "hergezaubert".  Wenn das so gewollt ist, dass der Layoutbereich nicht erscheint, wenn er keinen Inhalt hat, dann muß es wohl so sein! Inzwischen hat der Kunde einen weiteren Inhalt in den Layoutbereich "Fenster" eingefügt, wenn er diesen wieder rausnimmt, und das Leerzeichen auch, ist das "fenster" weg!

**Comment by frontendschlampe** [comment]
ja ... das habe ich mir gedacht. ;-) Das ein leerer Layoutbereich angezeigt wird, haben wir in https://github.com/contao/core-bundle/issues/1115 geändert, weil es ein Bug ist. Es sollten natürlich nur Layoutbereiche mit Inhalten angezeigt werden und dann auch nur der entsprechende Layoutbereich und nicht alle anderen einfach mit.

**Comment by kubjo** [comment]
Ja, ok! War nur ein bissle verwirrend, dass der plötzlich verschwunden ist. Gibt es eine elegantere Möglichkeit, als CE Text mit Leerzeichen, diesen dauerhaft sichtbar zu machen? Ich verwende diese Möglichkeit bei mehreren Seiten.

**Comment by frontendschlampe** [comment]
Jo, kein Problem.

Also eine Idee wäre mit einem ```::before``` oder ```::after``` zu arbeiten oder die ```fe_page.html5``` anzupassen. Du könntest aber auch ein eigenes ```block_section_XXX.html5``` Template anlegen und beim entsprechenden Layoutbereich dann auswählen.

Semantisch ist es nicht unbedingt sinnvoll, HTML-Quellcode nur zur Ausschmückung zu benutzen.
