### ISSUE TITLE
Not possible to disable an included module in a layout

### ISSUE THREAD

**Issue by eki89** [contao/core#8880]
Hey everyone,

i have just seen that it is not possible to disable/enable an included frontend module in layouts. The visibility toggle buttons switchs to grey, but after a reload of the layout dataset the buttun is still green/enabled. I've checked the requests while pressing the button, but only the svg image is loaded. An AJAX request wont be performed.

**Comment by kikmedia** [comment]
Did you save the layout after toggling the icon?

**Comment by fritzmg** [comment]
I can confirm the issue.

> Did you save the layout after toggling the icon?

You shouldn't have to do that, since you do not have to do that anywhere else? Or is it deliberate in this case?

**Comment by xchs** [comment]
See the comments in ticket https://github.com/contao/core/pull/5558

**Comment by fritzmg** [comment]
The comments in the ticket don't explain the behaviour though.

**Comment by xchs** [comment]
Turn off JavaScript and you will see the difference ;)

The enable/disable toggle in the page layout is implemented with a checkbox (hidden when JavaScript is on) and gets triggered by the eye icon. The status of all other visibility togglers is written directly to the database though.

**Comment by fritzmg** [comment]
Ah ok :). Still a little unintuitive though.

**Comment by leofeyer** [comment]
> > Did you save the layout after toggling the icon?
>
> You shouldn't have to do that, since you do not have to do that anywhere else? Or is it deliberate in this case?

You have to.

> Still a little unintuitive though.

True.
