### ISSUE TITLE
[3.5.35] Mehrere löschen bei hoher Datensatzanzahl nicht erfolgreich

### ISSUE THREAD

**Issue by Mynyx** [contao/core#8882]
In den Einstellungen unter "Maximum Datensätze pro Seite" habe ich 5000 konfiguriert.
Anschließend habe ich im Modul Newsletter die Abonnentenliste eines Newsletters aufgerufen und bei Anzeige "Alle" ausgewählt, sodass 5000 Abonnenten angezeigt werden. Dann habe ich "Mehrere bearbeiten", "Alle auswählen" und "Löschen" angeklickt.
Die Abonnentenliste wird anschließend neu geladen - es wurden jedoch keine Abonnenten gelöscht. Auch erscheint keine Fehlermeldung.

**Comment by Samson1964** [comment]
Solche Aufgaben würde ich eher in phpMyAdmin erledigen, anstatt ein CMS, wo viel "unnützes Zeug" drumherum noch geladen wird, zu benutzen. Ein einfaches Tabelle leeren - falls Du alle 70.000(?) Abonnenten gleichzeitig löschen willst - hätte nur Sekundenbruchteile dort gedauert.

**Comment by fritzmg** [comment]
@Mynyx sicher dass nicht zumindest 1000 gelöscht wurden? Für so eine Operation muss die PHP Variable `max_input_vars` auf mindestens `5000` (plus ein paar mehr für hidden form fields etc.) stehen. Default ist `1000`.

**Comment by Aybee** [comment]
> @Samson1964 Solche Aufgaben würde ich eher in phpMyAdmin erledigen, ...

Ja, aber dazu sollte man schon etwas mehr über die Strukturen wissen. Nur mal als Beispiel. Wenn du im Contao BE 1000 Seiten löschst, werden z.B. auch alle auf diesen Seiten enhaltenen Artikel und deren Inhaltselemente gelöscht. Wenn du dies über phpMyAdmin machst, hast du jede Menge Daten-Leichen in tl_article und tl_content.

**Comment by Mynyx** [comment]
@fritzmg Nein, es wurden keine Datensätze gelöscht.

**Comment by fritzmg** [comment]
Nichtsdestotrotz musst du `max_input_vars` erhöhen.

**Comment by leofeyer** [comment]
@Mynyx Hast Du versucht, ob `max_input_vars` das Problem behebt?

**Comment by aschempp** [comment]
An option would be to limit the number of available checkboxes/multi-edit-fields based on the `max_input_var` setting, but that seems pretty advanced for a very rare use-case …
