### ISSUE TITLE
[3.5.35] Newsletter-Verteiler bearbeiten: Änderungsdatum fehlerhaft dargestellt

### ISSUE THREAD

**Issue by Mynyx** [contao/core#8883]
Bei einem Newsletter-Verteiler ist als tstamp 1423317420 gespeichert. In der Detailansicht des Verteilers (Blaues Icon) wird als Änderungsdatum korrekt 07.02.2015 14:57 angezeigt.

In der Ansicht Verteiler bearbeiten (Stift Icon) wird stattdessen jedoch als Änderungsdatum fehlerhaft 02.05.2015 15:47 angegeben.

**Comment by leofeyer** [comment]
Funktioniert in der Online-Demo einwandfrei.

**Comment by Mynyx** [comment]
Ich habe mir das nun noch einmal genauer angesehen. In der Ansicht Verteiler bearbeiten (Stift Icon) wird das Änderungsdatum offenbar über folgende SQL-Abfrage ermittelt: ````SELECT MAX(tstamp) AS tstamp FROM tl_newsletter WHERE pid='1'````. Dies ergibt als Ergebnis das letzte Änderungsdatum der Newsletter in dem Newsletter-Verteiler. Dadurch unterschiedet sich das angezeigte Datum dann von dem Änderungsdatum des Newsletter-Verteilers selbst. 
Da das Änderungsdatum in der Ansicht Verteiler bearbeiten (Stift Icon) jedoch zwischen den anderen Eigenschaften des Newsletter-Verteilers angezeigt wird, ist es nicht nachvollziehbar, warum dieses nicht auf den Newsletter-Verteiler sondern auf die Newsletter in diesem bezogen ist.

**Comment by leofeyer** [comment]
Es kommt halt darauf an, wie man "letzte Änderung" definiert.

Nehmen wir als Beispiel einen Artikel in Contao: Wann war die letzte Änderung eines Artikels? Wenn etwas an den Metadaten geändert wurde oder wenn etwas am Inhalt geändert wurde?

Ich gebe Dir aber Recht, dass der Zeitstempel im Parent-View die letzte Änderung der Metadaten anzeigen sollte und nicht des Inhalts.

@contao/developers Seht ihr das genauso?

**Comment by Mynyx** [comment]
Um dies eindeutiger zu gestalten, könnte die Bezeichnung zu "Änderungsdatum Einstellungen" geändert werden.

**Comment by leofeyer** [comment]
Behoben in contao/contao@48a1e8e250f6018cc7685a82e65de258c911aac2.
