### ISSUE TITLE
Provide custom attribute with setter/getter to use as custom returnPath (Bounce Return E-Mail )

### ISSUE THREAD

**Issue by fatcrobat** [contao/core#8885]
Current implementation of `Email::sendTo()` does not give you any chance to modify the Bouce-Mail returnPath. It would be great if you can provide an public setter and getter to modify a new property named `returnPath`.

https://github.com/contao/core/blob/4539b50fd849dda41c58cdf0da2230dffd909c94/system/modules/core/library/Contao/Email.php#L494

`sentTo` could be changed to:
```
$this->objMessage->setReturnPath($this->strReturnPath?:$this->strSender);
```

**Comment by leofeyer** [comment]
See contao/core-bundle#1543.

**Comment by leofeyer** [comment]
Contao 3 is in the "security fixes only" phase of the long term support phases, so we will not add new features or fix non-security bugs anymore.
