### ISSUE TITLE
Image link overide metadata.

### ISSUE THREAD

**Issue by rburch** [contao/core#8890]
Not sure if this would be useful to others or not, but a couple times I've come across needing to re-enter the alt-tags I have set up in the file manager because I want to make an image link in a content element. I think it would be helpful for the overide fields to only overide the fields that are filled in, if not use the data from the file manager. That way you could link an image without having to re-enter alt tags.

**Comment by asaage** [comment]
This will prevent you from clearing individual fields and it will not happen in contao3.
Related issues are: https://github.com/contao/contao/issues/6374 & https://github.com/contao/contao/issues/6369.

**Comment by leofeyer** [comment]
> This will prevent you from clearing individual fields and it will not happen in contao3.

The same applied to Contao 4, too. I will therefore close the issue.
