### ISSUE TITLE
PHP 7.2 compatibility issue in MemberGroupModel.php

### ISSUE THREAD

**Issue by HaraldHubinger** [contao/core#8893]
In Contao 3.5.35 upon upgrade to PHP 7.2 the frontend shows this warning:

Warning: Use of undefined constant BE_USER_LOGGED_IN - assumed 'BE_USER_LOGGED_IN' (this will throw an Error in a future version of PHP) in system/modules/core/models/MemberGroupModel.php on line 83

fixable by replacing line 83 in MemberGroupModel.php
`if (!BE_USER_LOGGED_IN)`
with
`if (!defined('BE_USER_LOGGED_IN'))`

Being aware that regular bug-fixes are over I submit this to possibly be included in a following security-release, since it seems to me to be a compatibility issue with a supported version of PHP.

**Comment by leofeyer** [comment]
Compatibility issues are not security-related, either, so this will not be fixed anymore.

**Comment by BugBuster1701** [comment]
in  PageModel.php on line 515, too.
But, I know, it's to late.  :smile:
