### ISSUE TITLE
custom filter " in like

### ISSUE THREAD

**Issue by gebi84** [contao/core#8896]
i added a custom filter which works so far, but the select is building a query with like %"var"%

for what are this '"'? without this my code works

https://github.com/contao/core/blob/3a0c44093ddd87c7f386d4e27bbc2efbb2e95d6b/system/modules/core/drivers/DC_Table.php#L5375

hery my issue:
i have a field date with values:
2016-10-11 13:29:29
2016-10-11 15:29:29

and now i want to filter by date "2016-10-11"

**Comment by fritzmg** [comment]
This is applied for fields where `'eval' => ['multiple' => true]`. In that case, the database contains a serialized representation of the data. Thus Contao querys for `%"…"%`.
