### ISSUE TITLE
Mitgliederaktivierung nicht mehr möglich (Token leer)

### ISSUE THREAD

**Issue by thescrat** [contao/core#8899]
**Affected version(s)**
4.7.2

**Description**  
Mitgliederregistrierung mit Aktivierung ist ab Contao 4.7 nicht mehr möglich, da in der Bestätigungsmail nur ein "token=" ankommt. In der Datenbank ist das Feld "activation" welches den Token speichert, leer!

Ich habe jetzt wieder die 4.6.14 eingespielt, damit läuft es!

**Comment by baumannsven** [comment]
@thescrat Warum hast du das geschlossen? Geht es doch? Wenn ja wäre nett wenn du das hier kommentierst.

**Comment by xchs** [comment]
@baumannsven Falsches Repository.
