### ISSUE TITLE
Feature: Optionale Möglichkeit zur Auswahl der Inhaltselemente per Icon

### ISSUE THREAD

**Issue by BennyK80** [contao/core#8903]
Hallo zusammen,

ein Feature, welches eine leichtere und schnellere Auswahlmöglichkeit eines Inhaltselementes ermöglichen würde, wäre eine optionale Darstellung mit Icons.

Einige meiner Kunden sind überfordert mit den Begriffen im Select-Menü und der Verwendeung des Select-Menüs selbst. Es ist nicht immer ganz klar, dass dort etwas ausgewählt werden kann.
(Für mich schon, für den Kunden nicht immer.)

Nach ein paar Wochen Contao-Pause, haben es einige wieder vergessen und benötigen Hilfe.

Worpress hat das meiner Meinung nach sehr schön gelöst.
https://de.wordpress.org/gutenberg/

Daher die Überlegung, ob so etwas nicht auch in Contao nützlich wäre.
z.B. so oder ähnlich.

![Contao_Inhaltselemente-Auswahl](https://user-images.githubusercontent.com/7669964/64266224-8d74c580-cf34-11e9-86ef-5015cada3c48.png)

Wenn kein Icon hinterlegt wurde (z.B. bei Custom Elemnts) wird ein Platzhalter angezeigt.

Natürlich sehe ich auch den paltzsparenden Vorteil der aktuellen Lösung.
Das Contao kein Homepage-Baukasten ist, ist mir ebenfalls bewusst.
Vielleicht ist es auch nicht im Sinne des Erfinders. 
Eventuell gab es auch schon Diskussionen dazu?

Daher nur optional!
z.B. in den Backend-Einstellungen des Benutzerprofils.
"Inhaltselemente mit Icons anzeigen"

Ich bin kein Entwickler und kann somit nicht den Arbeitsaufwand dahinter beurteilen. 
Wie sehen das andere?

Viele Grüße,
Benny

**Comment by fritzmg** [comment]
@BennyK80 du bist hier im alten Repository für Contao 2/3. Für Contao 4 bitte das Mono Repository [contao/contao](https://github.com/contao/contao) verwenden.

**Comment by BennyK80** [comment]
@fritzmg Danke für den Hinweis!

**Comment by aschempp** [comment]
@fritzmg nur damit es erwähnt ist, bei GitHub lassen sich Issues mittlerweile zwischen Repositories verschieben, "im falschen Repo" ist nicht mehr so schlimm 😉

**Comment by fritzmg** [comment]
Ja, ich schreibe das nur zur "Schulung" ;)
